### ISSUE TITLE
Poor handling for non-integer values on the y-axis

### ISSUE THREAD

**Issue by MichaelDanielTom** [apexcharts/apexcharts.js#10]
When making charts that have float/decimal values, the values always round. This makes it extremely annoying for plotting data under 1. Right now I have a workaround so that I can see the actual value on hover by setting the formatter like:

`options.yaxis.labels.formatter = val => val.toFixed(2)`

However there doesn't seem a way to get any non integer ticks to show up. Therefore if all data is between 0 and 1, you'll only be able to see two ticks: 0 and 1.

P.S. Thanks for the great library! A lot easier to use than chart.js for simple stuff.

**Comment by MichaelDanielTom** [comment]
Thanks so much Juned!

**Comment by junedchhipa** [comment]
Fixed the decimal places also.
Now you don't need to provide `options.yaxis.labels.formatter = val => val.toFixed(2)` for handling small values

**Comment by MichaelDanielTom** [comment]
@junedchhipa Quick possible improvement could also be to default the representation for floats to truncate after a reasonable amount. Thoughts?

![image](https://user-images.githubusercontent.com/5520838/43663261-d3699f02-9736-11e8-8f4f-d1e5a40ae0d0.png)

**Comment by junedchhipa** [comment]
Not a bad idea to avoid long fraction parts. 
And what should be the name of this option? `options.yaxis.labels.decimalsInFloat` sounds good? :)

**Comment by junedchhipa** [comment]
Updated the "fraction/decimal" part to allow the user to give a default value.
Currently, the default is set to 2 - https://github.com/apexcharts/apexcharts.js/commit/b37f2490f28bd1d41f95ec14c4b6bfafb91a76a4
The option can be set at `options.yaxis.decimalsInFloat`
Need to add in the docs

**Comment by paaaz** [comment]
> Seems like `yaxis.decimalsInFloat` doesn't work. I set it to `0`, yet I still see decimals in my Y axis:
> 
> <img alt="CleanShot 2021-10-26 at 18 32 57" width="553" src="https://user-images.githubusercontent.com/12532733/138975671-e27c1e79-0775-425c-b43b-d35f11a3b215.png">
> 
> Instead, I have to set this in my yaxis options:
> 
> ```js
> labels: {
>   formatter: (value: number) => Math.floor(value),
> },
> ```

I can confirm that, it already worked with previous versions, now with v3.27.3 it does not seem to work

**Comment by malcolm7778** [comment]
try using react-chartjs-2

**Comment by Rahulgrover8806** [comment]
> When making charts that have float/decimal values, the values always round. This makes it extremely annoying for plotting data under 1. Right now I have a workaround so that I can see the actual value on hover by setting the formatter like:
> 
> `options.yaxis.labels.formatter = val => val.toFixed(2)`
> 
> However there doesn't seem a way to get any non integer ticks to show up. Therefore if all data is between 0 and 1, you'll only be able to see two ticks: 0 and 1.
> 
> P.S. Thanks for the great library! A lot easier to use than chart.js for simple stuff.

Thankyou
