### ISSUE TITLE
Candlestick Data format, remove nested array

### ISSUE THREAD

**Issue by ZBedjaJohnson** [apexcharts/apexcharts.js#1005]
Is it possible to provide candlestick data as ; [Timestamp, O,H,L,C] rather than [Timestamp, [O,H,L,C]]

eg; [1538856000000, 6593.34, 6600, 6582.63, 6600] rather than [1538856000000, [6593.34, 6600, 6582.63, 6600]]

Lots of data providers give data in the proposed format.

**Comment by junedchhipa** [comment]
Thanks for the suggestion.
Removed the requirement of providing a nested array inside an array.

**Comment by ZBedjaJohnson** [comment]
Great! 
Thanks @junedchhipa
