### ISSUE TITLE
CandleStick - Not Always Show OHLC Value when I updateSeries chart

### ISSUE THREAD

**Issue by phamthanhphuocloc1995** [apexcharts/apexcharts.js#1007]
CandleStick - Not Always Show OHLC Value when I updateSeries chart

Any Issue ?

I want OHLC value always show when I hover inside candlestick chart but I haven't any issue

Sorry for my english not good!

**Comment by junedchhipa** [comment]
Please post a [codepen](https://codepen.io/apexcharts/pen/xYqyYm) demo to demonstrate the issue clearly.

**Comment by phamthanhphuocloc1995** [comment]
https://youtu.be/TeEK4tmPgbc

I have upload my chart demo in youtube . When I hover to see HOLC value this work. but i have a function updateSeries chart every second and this not always show HOLC value.

**Comment by phamthanhphuocloc1995** [comment]
@junedchhipa Any issue for this ?

**Comment by junedchhipa** [comment]
@phamthanhphuocloc1995 I can see the issue that the tooltip doesn't update as soon as the chart updates. I tried to reproduce it on my end, but unable to do so.
I will create another demo and check it.
Meanwhile, if you can post a working example, that would be helpful.

**Comment by phamthanhphuocloc1995** [comment]
@junedchhipa , sorry I don't know this problem can be fixed or not ?
