### ISSUE TITLE
Clean xaxis interval

### ISSUE THREAD

**Issue by CyrilleDumortier** [apexcharts/apexcharts.js#1009]
![image](https://user-images.githubusercontent.com/34237081/67212879-56437080-f41d-11e9-881b-ec196ccf66c6.png)

Is it possible to delete the dates between the 2 points (15 aout, 15 sept. etc) ?
Thanks in advance !

**Comment by junedchhipa** [comment]
You cannot delete it directly, but you can use `xaxis.labels.formatter` to format the date-time using any other 3rd party plugin.

Here is an example
```javascript
xaxis: {
    tickAmount: 4,
    labels: {
        formatter: function(timestamp, val) {
            return dayjs(timestamp).format('YYYY MM-DD')
        }
    }
}
```
