### ISSUE TITLE
Missing the first element of the x-axis

### ISSUE THREAD

**Issue by silverphoenix1110** [apexcharts/apexcharts.js#101]
I have an issue same as this example: https://apexcharts.com/javascript-chart-demos/column-charts/column-with-negative-values/

The first element of the x-axis ("2011-01-01") was disappeared when I use xaxis.labels.rotates = -90

**Comment by junedchhipa** [comment]
Noted.
There is a function which calculates if labels exceed available grid area so that it can draw without overlapping. And I think that function is returning false positives sometimes for rotated labels. 
I will fix that

**Comment by junedchhipa** [comment]
Fixed it in the https://github.com/apexcharts/apexcharts.js/commit/4c658eb848321159378ecac06c5830f0b6311159

**Comment by rajeshwarpatlolla** [comment]
I am using "apexcharts": "^3.17.0", but still i have the same issue.

<img width="651" alt="Screenshot 2020-05-23 at 10 39 39 PM" src="https://user-images.githubusercontent.com/9896335/82736308-5d7d8480-9d46-11ea-992a-1d35abe059fd.png">

I am not able to see the first label. It's the same case with all types of graphs.

**Comment by vcostin** [comment]
I have something very similar, the first element in categories is `undefined`
