### ISSUE TITLE
Line Chart Gradient Fill Not Working Properly In Mac Safari 13.0.2

### ISSUE THREAD

**Issue by Gunaviru** [apexcharts/apexcharts.js#1011]
![Line Chart Gradient Issue](https://user-images.githubusercontent.com/19776007/67281485-2368ad80-f4ed-11e9-9785-3a9c53e342a5.png)

**Comment by junedchhipa** [comment]
Cannot reproduce it, gradient area charts on the website look fine on my Mac Safari.
Can you please create a codepen demo?
