### ISSUE TITLE
plotOptions.bar.dataLabels.position vertical don't works properly

### ISSUE THREAD

**Issue by danielschmitz** [apexcharts/apexcharts.js#1012]
## Codepen

https://codepen.io/danielschmitz/pen/eYYgxXP

```
plotOptions: {
          bar: {
            dataLabels: {
              position: 'top',
              orientation: 'vertical'
            },
          }
        },
```

## Explanation

- What is the behavior you expect?
datalabels in vertical position:

![image](https://user-images.githubusercontent.com/1509692/67292477-6872ec80-f4b9-11e9-8b91-c63bc75b5f65.png)

- What is happening instead?

datalabels in horizontal position:

![image](https://user-images.githubusercontent.com/1509692/67292558-86d8e800-f4b9-11e9-9f78-825ff598170e.png)

- What error message are you getting?
Notinhg

**Comment by junedchhipa** [comment]
Hey @danielschmitz, Sorry for the confusion. This feature was just added today, and I accidentally updated docs without releasing the library update.

Removed from the docs, the feature will be available after v3.10.1

**Comment by danielschmitz** [comment]
OK, no problem 😄

**Comment by robertogonzalezdelarosa** [comment]
it is posible to have vertical datalabels for line chart?
