### ISSUE TITLE
Clear/Update Annotations with options/conditions

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1016]
I have a chart with multiple types of annotations. Is there a way I can signify, either through a class or id, which annotations to clear? 

Or even better, could we get an "Update Annotation" method that takes a callback that receives an array of the current annotations and then returns a new array of annotations?

Something like this:

    ApexCharts.updateAnnotations( currentAnnotations => {
        const updatedAnnotations = currentAnnotations.filter( ({ x }) => x < 5 )
        return updatedAnnotations
    })

**Comment by junedchhipa** [comment]
I will provide a new method `removeAnnotation` which you can delete to use existing annotations though id.

An example of the usage will be

Adding annotation
```javascript
var chart = new ApexCharts(
    document.querySelector("#chart"),
    options
);

chart.render();

chart.addYaxisAnnotation({
    id: 'unique-id',
    y: 9000,
    label: {
        style: {
            fontSize: '15px',
            color: '#333',
            background: '#FEB019',
        },
        text: 'Y-axis Annotation',
    }
});

```

Remove it
```javascript
chart.removeAnnotation('unique-id')
```

**Comment by ThinkSalat** [comment]
Is there a way to know which annotations you currently have from here? It seems like it would be easy to expose that information in a callback function

**Comment by ThinkSalat** [comment]
I've just tried this and it doesn't work. I add an annotation using apexcharts.exec(chartId, 'addYAxisAnnotation, options), including an id.

When I try to remove that annotation by id, nothing happens.

Does this work if the annotations are added through the "exec" method?

**Comment by MaYoRr** [comment]
> I will provide a new method `removeAnnotation` which you can delete to use existing annotations though id.
> 
> An example of the usage will be
> 
> Adding annotation
> 
> ```js
> var chart = new ApexCharts(
>     document.querySelector("#chart"),
>     options
> );
> 
> chart.render();
> 
> chart.addYaxisAnnotation({
>     id: 'unique-id',
>     y: 9000,
>     label: {
>         text: 'Y-axis Annotation',
>     }
> });
> ```
> 
> Remove it
> 
> ```js
> chart.removeAnnotation('unique-id')
> ```

It`s work?
