### ISSUE TITLE
Update to new version then legend didn't work

### ISSUE THREAD

**Issue by nlpsl202** [apexcharts/apexcharts.js#1020]
I Update my apexcharts.min.js from 3.6.12 to  3.10.0 then the legend didn't work
It happens only when using IE
like this :
3.6.12
![image](https://user-images.githubusercontent.com/8954021/67547691-551e8600-f732-11e9-82d0-685ecdf735a1.png)

3.10.0
![image](https://user-images.githubusercontent.com/8954021/67547468-c873c800-f731-11e9-9571-abd32d968966.png)

code like this

> var options = {
                chart: {
                    height: 300,
                    type: "bar",
                    stacked: true,
                    toolbar: {
                        show: true
                    },
                    zoom: {
                        enabled: true
                    }
                },
                responsive: [
                  {
                      breakpoint: 480,
                      options: {
                          legend: {
                              position: "bottom",
                              offsetX: -10,
                              offsetY: 0
                          }
                      }
                  }
                ],
                plotOptions: {
                    bar: {
                        horizontal: false
                    }
                },
                xaxis: {
                    type: "datetime",
                    categories: [
                      "01/01/2011 GMT",
                      "01/02/2011 GMT",
                      "01/03/2011 GMT",
                      "01/04/2011 GMT",
                      "01/05/2011 GMT",
                      "01/06/2011 GMT"
                    ]
                },
                legend: {
                    position: 'bottom',
                    fontSize: '14px',
                },
                fill: {
                    opacity: 1
                },
                series: [
                  {
                      name: "PRODUCT A",
                      data: [44, 55, 41, 67, 22, 43]
                  },
                  {
                      name: "PRODUCT B",
                      data: [13, 23, 20, 8, 13, 27]
                  },
                  {
                      name: "PRODUCT C",
                      data: [11, 17, 15, 15, 21, 14]
                  },
                  {
                      name: "PRODUCT D",
                      data: [21, 7, 25, 13, 22, 8]
                  }
                ]
            };

            var chart = new ApexCharts(document.querySelector("#chart"), options);

            chart.render();

is anything need to set?

**Comment by junedchhipa** [comment]
Can you please paste your whole chart configuration?
Or better create a codepen demo?

**Comment by nlpsl202** [comment]
I just post my hole code, codepen isn’t work on IE browser,thank for help
