### ISSUE TITLE
DataURI not working with '<strong>' in labels

### ISSUE THREAD

**Issue by DavidGrabnar** [apexcharts/apexcharts.js#1022]
JS Fiddle with example of my problem: https://jsfiddle.net/f3uravjw/

## Explanation

- What is the behavior you expect?

  I want to get my chart's dataURI via dataURI method.
- What is happening instead?

  If my chart has labels in this format: **'Some name'  + ' \<strong\>(' + percentage + '%)\</strong\>'**, dataURI() promise will neither resolve or reject.
  If my chart has labels in format without tags: **'Some name'  + ' (' + percentage + '%)'**, dataURI works as expected.
- What error message are you getting?

  There are no error messages and exceptions thrown.

**Comment by junedchhipa** [comment]
This is already fixed in v3.11.2

Sorry for the delay in response.
