### ISSUE TITLE
downloading SVG or PNG is not showing colors for legend

### ISSUE THREAD

**Issue by upadhb** [apexcharts/apexcharts.js#1026]
There seems to be an issue when downloading the charts. Just yesterday it was working all well, I even tried different laptops, but same issue. 

When I download any chart form the demos ( I have attached one in this issue), the Legends lose their color and position. 

![ivdgmpi1](https://user-images.githubusercontent.com/17695919/67611778-3932d880-f762-11e9-951e-7a42479f353d.png)

**Comment by junedchhipa** [comment]
The bug is already fixed - https://github.com/apexcharts/apexcharts.js/commit/c52ccb50370ebf6c623893e06690cc9beeea78b8
Not released yet. It will be released tomorrow.

**Comment by upadhb** [comment]
thank you @junedchhipa

**Comment by msolution-tommy** [comment]
hhh
