### ISSUE TITLE
On v-3.10.0 bars have no width. On v-3.8.5 have correct width.

### ISSUE THREAD

**Issue by frontend-fxs** [apexcharts/apexcharts.js#1027]
Hi,

[Codepen v3.10.0 with bar width issue](https://codepen.io/frontend-fxs/pen/ExxWePK)
[Codepen v3.8.5 without issue](https://codepen.io/frontend-fxs/pen/oNNWXEJ)

Updating to the new version 3.10.0, mixed line&bar chart, bars have no width.

apexcharts@^3.8.5
![image](https://user-images.githubusercontent.com/29771110/67405828-93426b00-f5b5-11e9-88f3-0d16f4052905.png)
![image](https://user-images.githubusercontent.com/29771110/67406543-7eb2a280-f5b6-11e9-8877-f427494bd73b.png)

apexcharts@^3.10.0
![image](https://user-images.githubusercontent.com/29771110/67406241-18c61b00-f5b6-11e9-8019-f5381da77028.png)
![image](https://user-images.githubusercontent.com/29771110/67406615-938f3600-f5b6-11e9-94e1-838bae24d49e.png)

Thanks

**Comment by junedchhipa** [comment]
Although it looks like v3.8.5 has the correct width of bars, it's actually overlapping and wrong.
v3.10.0 is the correct behavior.

The reason it looks so thin is because of the time difference.
I will look more at how it can be enhanced visually because there is space that can be utilized.
