### ISSUE TITLE
Miscellaneous issues on apexcharts site

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#103]
I'll try to point out multiple things I've seen on the site : 

- [x] Docs in gradient shows a property `shadePercent` while the gradient radialBar demo uses `shadeIntensity`.

- [x] [This page](https://apexcharts.com/javascript-chart-demos/radialbar-charts/) has two misspelled Gauge. Also, you can't access the gradient radialBar (which is sexy !). On that exact same radialBar demo, the hover makes it really weird (at least, on Safari, the green goes white).

- [x] I would put the locale in the chart essentials part of the docs (even just as a link). It's a very important feature to anyone producing app for non-english speakers, and it's easily missable as functionality as it's not that much mentionned throughout the site, and nested deeply in the menu (Options > chart > locales). Or maybe a demo ? Or in the feature page ? 

- [ ] Demos lacks the support for vue, which are important for quick import in a project as a base to work on. I would gladly contribute to provide all the code samples for the demos part as vue if you're okay with this (as part of the vue-apexcharts examples project). Maybe you can set up the site to be open source if possible so that the community could help on these little issues.

**Comment by junedchhipa** [comment]
Thank you for pointing out the errors, much appreciated.

I will take care of the typo errors you listed in the first two points.
The 3rd one - I will create a more visible page for `locales`

Coming to the 4th point - I agree, there aren't many examples which demonstrates and covers all use cases for vue.js (apart from this doc https://apexcharts.com/docs/vue-charts/). If you want to create demos for vue.js, that would be great. Would codepen/codeSandbox work fine to create the demos? I will create a new section in site "Vue-js samples".

Regarding community contribution, the website is in WordPress (not a great decision 😀) and currently - it is difficult to migrate everything from there to GitHub-pages. Also, there are many functionalities which are not supported in gh-pages. I will think more about how only the docs can be open-sourced so others can contribute.

Thanks a lot

**Comment by lucafaggianelli** [comment]
oh sorry, ok it works only on the menu items i guess...

**Comment by junedchhipa** [comment]
I will add a generic search on the right sidebar too which will list down pages from the whole website.

**Comment by junedchhipa** [comment]
Closing this. Feel free to create a PR for vue-demos in `samples` directory.

**Comment by junedchhipa** [comment]
Created all demos for vue as well.
https://apexcharts.com/vue-charts-demos
