### ISSUE TITLE
name === '<P3' do not show in legend

### ISSUE THREAD

**Issue by yukinotech** [apexcharts/apexcharts.js#1033]
## Codepen

[codepen demo](https://codepen.io/yukinotech/pen/jOOLpyV) 

## Explanation

this is the series,but only 'P3' can be shown in legend,'<P3' cant be shown in legend,is this a bug?
```
      let series = [
        {
          name: '<P3',
          data: [0, 0, 0, 0, 0, 0, 1, 0]
        },
        {
          name: 'P3',
          data: [0, 3, 0, 5, 0, 0, 1, 0]
        }
      ]
```
![test](http://asobi-bucket.oss-cn-beijing.aliyuncs.com/pixiv/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-10-29%20%E4%B8%8A%E5%8D%8811.20.02.png)

**Comment by yukinotech** [comment]
i found this in src, why cant have '<' in name?
```js
  static escapeString(str, escapeWith = 'x') {
    let newStr = str.toString().slice()
    newStr = newStr.replace(
      /[` ~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi,
      escapeWith
    )
    return newStr
  }
```
```js
seriesName: Utils.escapeString(w.globals.seriesNames[realIndex])
```

**Comment by junedchhipa** [comment]
It is escaped to prevent querySelector bugs when referencing elements using series-name

You can put a space in < P3 and it will work fine.

```
    let series = [
        {
          name: '< P3',
          data: [0, 0, 0, 0, 0, 0, 1, 0]
        },
        {
          name: 'P3',
          data: [0, 3, 0, 5, 0, 0, 1, 0]
        }
      ]
```

**Comment by yukinotech** [comment]
> It is escaped to prevent querySelector bugs when referencing elements using series-name
> 
> You can put a space in `< P3` and it will work fine.
> 
> ```
>     let series = [
>         {
>           name: '< P3',
>           data: [0, 0, 0, 0, 0, 0, 1, 0]
>         },
>         {
>           name: 'P3',
>           data: [0, 3, 0, 5, 0, 0, 1, 0]
>         }
>       ]
> ```

thank you for solving my question！That is really helpful！
