### ISSUE TITLE
Radar chart yaxis fontSize issues

### ISSUE THREAD

**Issue by MiholapMaksim** [apexcharts/apexcharts.js#1034]
Hi! I try to use the Radar chart from the rechart library but unfortunately, I can't change font-size on the label - yaxis. If I change it on react dev tools it works fine. But in code, it only could changes the color of labels. Is someone had the same issues?

**Comment by unsafeFunction** [comment]
@junedchhipa
Hi! Unfortunately your fix not working. I open markup and see that default font-size - 13px
But if the component was rerendering the font-size is changing on my font-size
