### ISSUE TITLE
Some of the classes are getting conflict

### ISSUE THREAD

**Issue by thirukumaran13** [apexcharts/apexcharts.js#1036]
**Is your feature request related to a problem? Please describe.**
I added apexcharts in my webpage. The charts loaded nicely. However the tooltip was not showing correctly. After a bit of debug found that I was using class named "active" and tooltip also is using 'active' class. I have created some css for active and it was causing the issue. I changed my code and renamed "active" class.  

**Describe the solution you'd like**
Prefix all the classes with "apexcharts" to avoid any conflict.

**Describe alternatives you've considered**
Make sure apexcharts classes not used in the webpage (like "dark","light","active", etc.)

**Additional context**
NA

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.
