### ISSUE TITLE
Docs typo in plotOptions Bard

### ISSUE THREAD

**Issue by rasca** [apexcharts/apexcharts.js#1037]
In https://apexcharts.com/docs/options/plotoptions/bar/ it says:

```
            orientation:: horizontal
```

when it should be 

```
            orientation: 'horizontal'
```

On a related note, I couldn't find the docs source to provide a patch. Could you please ploint me to it so I can do it next time? Thanks!

**Comment by junedchhipa** [comment]
Thanks for raising the issue, fixed it.
Unfortunately, the website (doc too) is not open-sourced, so you will not be able to do make any changes there. Kindly post to GitHub issues for any further suggestions.
