### ISSUE TITLE
Y Axis labels misalign

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1038]
As you can see below, some of the labels are a full line above the very top label
![Screen Shot 2019-10-30 at 10 28 44 AM](https://user-images.githubusercontent.com/31082405/67883066-a64ac300-fb00-11e9-8efa-ad9ba54a697b.png)

[codpen](https://codepen.io/apexcharts/pen/eVvKqQ)

**Comment by ThinkSalat** [comment]
My colleague thinks it's because the longer the label text is the further to the right the "center" of the text will be. And then when the label gets rotated 90 degrees, it rotates on different center.

**Comment by junedchhipa** [comment]
Please provide a valid codepen for the issue.
Your provided codepen opens a wrong pen.

Closing it as not reproducible.

**Comment by junedchhipa** [comment]
![Screen Shot 2019-12-31 at 3 31 36 PM](https://user-images.githubusercontent.com/17950663/71617781-a93a6080-2be2-11ea-8d12-07744e6bbc0b.png)

I was able to reproduce it and fixed it.
