### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by PlippiePlop** [apexcharts/apexcharts.js#1041]
![9eu74hwt](https://user-images.githubusercontent.com/728661/67964465-a3cf9280-fc00-11e9-8433-6e50e422d2ba.png)

Hello,

I have a dataset where the Xaxis categories consists of week number 1 > 53,
Looking at the date formats that option is missing from all the date options available.

Is there a way it can do type: 'datetime' with given week numbers? so it's possible to zoom in and out?

**Comment by junedchhipa** [comment]
You can try `xaxis.type: 'numeric'`.
But while zooming, it may print float values, so make sure you use `xaxis.labels.formatter` function to prevent float values.
