### ISSUE TITLE
Artifact on stacked straight area with null values

### ISSUE THREAD

**Issue by PierrickP** [apexcharts/apexcharts.js#1042]
## Codepen

https://codepen.io/PierrickP/pen/WNNXMBW

![image](https://user-images.githubusercontent.com/1214544/67970972-39bcea80-fc0c-11e9-9f58-4c393838a38d.png)

The green serie 
```
[
        [1, 2],
        [2, 3],
        [3, null],
        [4, null],
        [5, null]
]
```

## Explanation

- What is the behavior you expect?
The green triangle on 4 should not be there

- What is happening instead?
An artifact

- What error message are you getting?
No message

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.
