### ISSUE TITLE
chart.toolbar.show: false;  layout display remains

### ISSUE THREAD

**Issue by Elaniobro** [apexcharts/apexcharts.js#1043]
## Codepen
[pen](https://codepen.io/elaniobro/pen/ZEEvQWX)

## Explanation

- What is the behavior you expect?
display to be none
![Capture](https://user-images.githubusercontent.com/710847/68039644-f2ce0400-fca2-11e9-9236-d5c0db1f979b.PNG)

- What is happening instead?
height of the hamburger menu persists
![Capture](https://user-images.githubusercontent.com/710847/68039998-b8b13200-fca3-11e9-8925-3e438b8a1bee.PNG)

**Comment by junedchhipa** [comment]
The toolbar is an absolutely positioned element that doesn't affect the chart's height if its visibility is turned on/off.

**Comment by Elaniobro** [comment]
@junedchhipa where is that extra space coming from then? You can see in the images above, that the hamburger menu space is persistent.

**Comment by Elaniobro** [comment]
@junedchhipa #520 helped to quasi solve the issue I posted. But how can one get this to work with labels and such? As soon as:
```js
chart: {
      sparkline: {
            enabled: true
      }
}
```
is removed or set to false, the additional padding around the graph is present.

**Comment by SirLamer** [comment]
Just to add to the OP's point, reserving this space for the toolbar even when it is not used is resulting in wasted space in cases where the toolbar is not desired. I get that Apex Charts is a robust full-featured packaged but in cases where a site needs both fancy and simple charts, it makes sense to use the same renderer for simple ones. "sparkline" is more like an extreme minimalist rendering suitable for something like a summary next to a search result or for the buttons on a control panel or something. I'd like to show a very simple chart which requires very little vertical space over top of a form but 22 of 150 pixels are being squandered on reserving space for a disabled toolbar button.

I'll also volunteer candidly that reserving this vertical space for a small corner button is somewhat wasteful. It might make more sense to superimpose the button on the top-right corner of the actual plot area, or perhaps provide the option to do this in case somewhat really expects to need that corner for plot data.

**Comment by officialpiyush** [comment]
bump, any updates on this stuck on this, I don't want the external padding around the graph, I'm using the TreeMap graph, `sparkline: true` works, but also removes the labels, which is not what I want. Any workarounds for this, or maybe any config I missed?

**Comment by officialpiyush** [comment]
cc @junedchhipa

**Comment by officialpiyush** [comment]
bump

**Comment by officialpiyush** [comment]
any updates?

**Comment by Elaniobro** [comment]
I got around this, by using negative margins, then creating a new `<div>` with `display: grid` and creating my own labels. Not ideal, but it did work.

**Comment by GregPeden** [comment]
Activity.

**Comment by officialpiyush** [comment]
bump

**Comment by GregPeden** [comment]
bump
