### ISSUE TITLE
Can I have only integer values in Y - axis when actual values may be non-integer?

### ISSUE THREAD

**Issue by DinooliUduwarage** [apexcharts/apexcharts.js#1047]
![Untitled](https://user-images.githubusercontent.com/36589723/68102872-96652180-fefa-11e9-9f79-c1fc0a045a58.png)

I want to get rid of the decimal places in the right y axis, yet my column values can be non-integer
@junedchhipa

**Comment by junedchhipa** [comment]
Yes, you can use the `yaxis.labels.formatter` function to format the values according to your needs.

```javascript
yaxis: [
  {
    labels: {
      formatter: function(val) {
        return val.toFixed(0);
      }
    }
  }
]
```

**Comment by DinooliUduwarage** [comment]
In here you can get integer values to the y axis but, if the bar graph actual value is also rounded up or down to nearest integer. When you hover over the bar you see 36 if the actual value is 35.7, and 42 when actual value is 42,3.
![12](https://user-images.githubusercontent.com/36589723/68174949-a1c15700-ffa5-11e9-8f04-d6ed91f7196f.png)
This is my actual value 35.5, but here the y axis values have decimal points,where I have limited to 2 points.
![11](https://user-images.githubusercontent.com/36589723/68174916-87877900-ffa5-11e9-90ad-029fce8bef8b.png)
This is how u get values when applied above function, you can see there my actual value is rounded up n y axis have integers
**what I need is to display my actual value as it is in decimal points and y axis have only integer values**

**Comment by Olgagr** [comment]
@DinooliUduwarage Did you solve this somehow? I would like to have the same effect.

**Comment by aeharake** [comment]
> Yes, you can use the `yaxis.labels.formatter` function to format the values according to your needs.
> 
> ```js
> yaxis: [
>   {
>     labels: {
>       formatter: function(val) {
>         return val.toFixed(0);
>       }
>     }
>   }
> ]
> ```

Thank you, this works.

**Comment by invisibled** [comment]
> Yes, you can use the `yaxis.labels.formatter` function to format the values according to your needs.
> 
> ```js
> yaxis: [
>   {
>     labels: {
>       formatter: function(val) {
>         return val.toFixed(0);
>       }
>     }
>   }
> ]
> ```

This is not a great solution. Any manipulation of `val` creates duplicate labels. eg. 1.2 and 1.6 become 1, in two spots. Would be great to have an option to force only integers.

**Comment by markalroberts** [comment]
> In here you can get integer values to the y axis but, if the bar graph actual value is also rounded up or down to nearest integer. When you hover over the bar you see 36 if the actual value is 35.7, and 42 when actual value is 42,3. ![12](https://user-images.githubusercontent.com/36589723/68174949-a1c15700-ffa5-11e9-8f04-d6ed91f7196f.png) This is my actual value 35.5, but here the y axis values have decimal points,where I have limited to 2 points. ![11](https://user-images.githubusercontent.com/36589723/68174916-87877900-ffa5-11e9-90ad-029fce8bef8b.png) This is how u get values when applied above function, you can see there my actual value is rounded up n y axis have integers **what I need is to display my actual value as it is in decimal points and y axis have only integer values** @junedchhipa

Agreed - I would like to be able to have points on the chart be 2dps for accuracy but have the labels on the y-axis be rounded for readability. The label formatter seems to format both at the same time which is not good.

**Comment by ihssaneee** [comment]
you can use `yaxis.labels.formatter `function  and also use `min:0` and `forceNiceScale: true`, that fixed the dupicate labels for me
