### ISSUE TITLE
Can i change or update backgroundColors of Bar in Bar(Column) chart

### ISSUE THREAD

**Issue by phamthanhphuocloc1995** [apexcharts/apexcharts.js#1048]
Can i change or update backgroundColors of Bar in Bar(Column) chart with any function or event I have not found in document

**Comment by junedchhipa** [comment]
Updating `backgroundBarColors` is the same as updating any other option.
If you are using vanilla javascript version, you can do

```javascript
var apexcharts = new ApexCharts(el, opts)
apexcharts.updateOptions({
  plotOptions: {
    bar: {
      colors: {
        backgroundBarColors: ['#ff0', '#ff0']
      }
    }
  }
})
```
