### ISSUE TITLE
Tooltip show z only from the first seria for each of four serias

### ISSUE THREAD

**Issue by annache** [apexcharts/apexcharts.js#1049]
## Codesanbox demo

**https://codesandbox.io/s/react-basic-example-vzmfo** from template [CodeSandbox React template](https://codesandbox.io/s/6yoqonyo7r)

## Explanation

- What is the behavior you expect?
I expected that for each **z** will be taken from appropreate seria, not just from the first one
- What is happening instead?
It shows **z** from the first seria for each of four serias 
- What error message are you getting?
No error

**Comment by sergkop** [comment]
The demo is giving 404 error.
