### ISSUE TITLE
last label doesn't show for x axis type: 'datetime'

### ISSUE THREAD

**Issue by patrickolfindo** [apexcharts/apexcharts.js#1053]
## Codepen
https://codepen.io/patrickolfindo/pen/yLLKeYY

## Explanation

- What is the behavior you expect?
   The final label from the series ('10-29 07:00') to show
- What is happening instead?
   The labels end 1 tick before the end at '10-29 06:00'
- What error message are you getting?
   No error message received

I was also wondering whether there's a way to toggle when to show or hide the last label in the x axis

**Comment by patrickolfindo** [comment]
Changing `xaxis.type=category` instead of `datetime` shows the last tick

**Comment by junedchhipa** [comment]
v3.11.3 fixes the cropping of the last x-axis label. If the label cannot be drawn, it will be skipped.

**Comment by tejaswinieswar** [comment]
Any workaround to show the last label instead of skipping it? Like adding padding to graph etc?

**Comment by pnr32** [comment]
> Any workaround to show the last label instead of skipping it? Like adding padding to graph etc?

I join the question.

**Comment by jma1020** [comment]
> Any workaround to show the last label instead of skipping it? Like adding padding to graph etc?

I join the question too.

**Comment by jma1020** [comment]
I find a trick, 
It can be solved by giving a virtual yAxis.

**Comment by jma1020** [comment]
It's not a fundamental solution, but I solved it by inserting this code.
```
yaxis:[ 
  ~~
  , {
      opposite: true,
      axisTicks: {
        show: false,
      },
      axisBorder: {
        show: false,
   
      },

      labels: {
        show: false,   
      },
    },
```
I added a virtual xAxis on the right.

**Comment by atuljha23** [comment]
just add the padding properties to your x-axis 

something like 

```
 grid: {
      padding: {
        right: 25,
      },
}
```
