### ISSUE TITLE
Duplicate Y Axis Ticks / Values in Stacked Chart

### ISSUE THREAD

**Issue by stevebor1** [apexcharts/apexcharts.js#1054]
## Codepen

https://codepen.io/stevebor1/pen/gOOemvJ

![image](https://user-images.githubusercontent.com/1202448/68237514-1acba900-ffbc-11e9-9748-f5c6de89aa3d.png)

## Explanation
apexcharts 3.10.1

May be related to issue #410, but noticed that the issue is still present when using  'stacked:true' option.

When using stacked:true, the y-axis appears to have duplicate tick values when the dataset has 0 y values, or when only one series has values.

- What is the behavior you expect?
The y-axis values should not be duplicated

- What is happening instead?
They are duplicated. 0, 1, 1, 2, 2

- What error message are you getting?
none

**Comment by stevebor1** [comment]
Actually this appeared to duplicate yaxis as I returned a fixed value from the formatter.
A better solution would be to check to see if the number is whole, and display based on that condition.

    yaxis: {
        labels: {
            formatter: function (val) {
              return parseInt(val) === val ? val : ''
            }
        }
    }

**Comment by sheikh303** [comment]
this could be a work around here:
`yaxis: {
        min: 0,
        max: _maxYAxisValue_,
        tickAmount: _maxYAxisValue_,
}`

**Comment by NgoNhatThai** [comment]
Check your data, if there are no data, set max = number (EX: 5)
yaxis: {
    labels: {
        formatter: function (val) {
          return parseInt(val) === val ? val : ''
        }
    },
max: Math.max(...data) === 0 && 5,
tickAmount: 5 //depend on your op
}
