### ISSUE TITLE
discrete markers not working in scatter graph

### ISSUE THREAD

**Issue by DominicVillemure** [apexcharts/apexcharts.js#1055]
## https://codepen.io/apexcharts/pen/PgPXYO
change the chart type to scatter in the codepen and now working anymore

## Explanation

- What is the behavior you expect?
Like in line charts, I want to be able to target a single marker
- What is happening instead?
Working great in line chart, not in scatter

**Comment by DominicVillemure** [comment]
Workaround for now is to use line chart and set stroke width to 0

**Comment by alexpopa-work** [comment]
@DominicVillemure Great workaround! Thanks a lot.
