### ISSUE TITLE
Displaying tooltip (type) values in an external div

### ISSUE THREAD

**Issue by lincolnshiredev** [apexcharts/apexcharts.js#1058]
I would like to show the values that are currently shown in the tool tip in an external div.
I have explored the mouseMove event but I am not exactly sure what I would be looking for in the plethora of attributes displayed. 

I am using an Area chart and if i print the mouse move event in console I of course get all mouse movements on the chart not just on the data. I am looking to achieve something similar to this chart:
https://tools.bitcoin.com/widgets/ (see the two charts at the top) so where ever I move the mouse on the chart I get the datapoint for the intersection of X and Y (hope that makes sense).

I did wonder if it might be possible to just make a custom static tooltip at the top but I dont see any options for that other than placing top left and right etc and of course it disappears after moving the mouse.

**Comment by helen-andronova** [comment]
I need the same functionality. Thanks
