### ISSUE TITLE
Gauge chart container renders at incorrect height in Firefox 

### ISSUE THREAD

**Issue by dnw6** [apexcharts/apexcharts.js#1059]
## Examples
![image](https://user-images.githubusercontent.com/9420088/68312095-74aa9c80-00aa-11ea-8e8c-c0109822f689.png)

You can see the issue on the demo page: https://apexcharts.com/javascript-chart-demos/radialbar-charts/semi-circle-gauge/

The other radial charts have the same issue, but to a lesser degree.

This issue wasn't present in 3.8.6, but is present in 3.9.0 and 3.10.0.

## Explanation

- What is the behavior you expect?
Consistent container height in all browsers
- What is happening instead?
Chart container height significantly larger in Firefox
- What error message are you getting?
n/a

**Comment by CupOfTegan** [comment]
+1 this issue

**Comment by matthewlenz** [comment]
They actually vary in height on Chrome as well.  I have a page with 5 charts (1 line, 1 bar, horizontal bar and 1 radialBar) with the same chart.height set.  The radialBar chart is slightly taller on Chrome and WAY taller on Firefox.

**Comment by pierre-alain-b** [comment]
I confirm I see this as well with Apexcharts 3.20 and 3.26.

**Comment by pierre-alain-b** [comment]
The issue vanished when I added 
`
      sparkline: {
                  enabled: true
                }
`
in the chart options.

**Comment by pierre-alain-b** [comment]
I guess this issue can now be closed. The options seen on this page are correct: https://apexcharts.com/javascript-chart-demos/radialbar-charts/semi-circle-gauge/
