### ISSUE TITLE
average value line in bar chart

### ISSUE THREAD

**Issue by DinooliUduwarage** [apexcharts/apexcharts.js#1061]
is there a way to have a line to indicate average value of the bar graph values?
![avg](https://user-images.githubusercontent.com/36589723/68356884-9141e580-0139-11ea-9421-b1f682b43cd9.png)
As a line shown in the dark blue dashed line

**Comment by junedchhipa** [comment]
Sorry, that's not supported.
You will have to calculate the average and draw the line by adding a new series in the chart.

**Comment by VincentVanclef** [comment]
@junedchhipa Drawing it manually is fine, but is there anyway to make the line go from edge-to-edge? It looks silly since it stops at the center point of the columns :/

![image](https://user-images.githubusercontent.com/541084/148209145-1f660464-a4b8-44e5-b1c2-265e918fab31.png)

**Comment by VincentVanclef** [comment]
nvm i just discovered annotations, that solved it beatifully!

**Comment by CoderAnurag007** [comment]
> nvm i just discovered annotations, that solved it beatifully!

please tell the solution

**Comment by harishkoninti** [comment]
By using Annotations we can solve it. Add below code in Options.

` annotations: {
      yaxis: [
        {
          y: 60,
          borderColor: "#00E396",
          label: {
            borderColor: "#00E396",
            style: {
              color: "#fff",
              background: "#00E396"
            },
            text: "Y Axis Annotation"
          }
        }
      ],
    }`

You can also refer documentation [here](https://apexcharts.com/docs/annotations/)
