### ISSUE TITLE
Pie / Donut with title / legend drawn outside container

### ISSUE THREAD

**Issue by FDArchy** [apexcharts/apexcharts.js#1062]
Hello Have some trouble with pie / donut chart in fixed height container - when it have title or legend, pie / donut not change own size, instead of this it overflow container, even without trimming. Will it be fixed?
![001](https://user-images.githubusercontent.com/6572223/68378660-89943800-015d-11ea-8ec3-d03d84888b04.PNG)

**Comment by FDArchy** [comment]
Hello. No ideas how to fix it?

**Comment by junedchhipa** [comment]
Please create a working codepen example to quickly reproduce it on my side.

**Comment by FDArchy** [comment]
[Codepen](https://codepen.io/fd_archy/pen/YzzyMQp)

At top donut chart with legend, the legend overflows the chart below, instead of reducing the size of the pie. Is this the right conduct? How can this be fixed?

**Comment by FDArchy** [comment]
Hello. Which fixes in 3.11.0 release? Was fixed that problem?

**Comment by junedchhipa** [comment]
Sorry, the fix was not included in 3.11.0 but it will be addressed in the next release.

**Comment by FDArchy** [comment]
Great thanks!
