### ISSUE TITLE
Datalabel with Background and Transparency at ApexCharts

### ISSUE THREAD

**Issue by giuseppepaolo** [apexcharts/apexcharts.js#1063]
**Is your feature request related to a problem? Please describe.**
The datalabels from charts aren't clear, when use more than one datasets.

**Describe the solution you'd like**
I'd like to add one possibility to use background and transparency in datalabels, like this attachment.

**Additional context**
![image](https://user-images.githubusercontent.com/25927209/68397105-6a8fa900-0151-11ea-8fc1-33719b4bd757.png)

**Comment by junedchhipa** [comment]
Providing background color for data labels is possible now
Docs: https://apexcharts.com/docs/datalabels/

**Comment by OzzyTheGiant** [comment]
How do I change background color of a dataLabel in a Pie/Donut chart? All I get is a white background and the docs don't seem to specify anything about that.

**Comment by junedchhipa** [comment]
For pie/donuts data-labels background, try this

```javascript
dataLabels: {
  enabled: true,
  style: {
    colors: ['#111']
  },
  background: {
    enabled: true,
    foreColor: '#fff',
    borderWidth: 0
  }
}
```

**Comment by GantaVenkataKousik** [comment]
This was fine . But this can only set the same color to all the labels . 
**How to set different colors for different labels based on their label ?**

**Comment by nodahikaru** [comment]
@GantaVenkataKousik Did you solve?

**Comment by GantaVenkataKousik** [comment]
@nodahikaru no bro

**Comment by nodahikaru** [comment]
@GantaVenkataKousik I am pretty sure it's impossible in apexcharts

**Comment by GantaVenkataKousik** [comment]
@nodahikaru okay, thanks
