### ISSUE TITLE
Axis ticks on x-axis in column-line mixed charts not consistent with line only charts

### ISSUE THREAD

**Issue by enomoto-kudamono** [apexcharts/apexcharts.js#1064]
## Codepen

[https://codepen.io/enomoto/pen/yLLELaE](https://codepen.io/enomoto/pen/yLLELaE)
(apexcharts version: 3.10.1)

## Explanation

- What is the behaviour you expect?
  - Axis ticks on x-axis should be integer, as the same behaviour with two line series
- What is happening instead?
  - Axis ticks on x-axis taken in decimal values

**Comment by junedchhipa** [comment]
If the combo chart contains columns, then the x-axis adjusts to contain the columns and prevent cropping. If the x-axis in your example starts at 1, the first column will be cropped.
