### ISSUE TITLE
Toolbar not showing all icons

### ISSUE THREAD

**Issue by TKirahvi** [apexcharts/apexcharts.js#1065]
![apextoolbar](https://user-images.githubusercontent.com/3405318/68475629-486d5800-0231-11ea-98f3-998557e275da.JPG)
## Explanation
I would like to have toolbar icons showing, so in my options are: 
```
toolbar: {
            show: true,
            tools: {
              download: true,
              selection: true,
              zoom: true,
              zoomin: true,
              zoomout: true,
              pan: true,
              reset: true
            },
        }
```

X-axis is 'datetime'.

I would assume that this enables all the tools. But as you can see from the screenshot, only two of them are showing. Others are visible when hovering over them

**Comment by junedchhipa** [comment]
Please post a fully working codepen so I can reproduce it on my side.

**Comment by TKirahvi** [comment]
Seems that I cannot reproduce this issue with codepen. I tried with https://codepen.io/tkirahvi/pen/bGGKgro which has the same options but it didn't happen.

**Comment by davehowson** [comment]
I have this issue as well.
You cannot reproduce this on codepen since it seems to be a responsiveness related issue.
![image](https://user-images.githubusercontent.com/26568721/100412367-7c185b80-309a-11eb-849e-365a0b12d110.png)

This issue only occurs when I switch to a lower screensize like the iPad screensize and then refresh the page.

At this screensize, for some reason, the .apexcharts-element-hidden class is being applied to some of the icons

![image](https://user-images.githubusercontent.com/26568721/100412474-d6b1b780-309a-11eb-94ee-bc811144c870.png)

**Comment by SMKim94** [comment]
@davehowson I'm having the same problem.
Have you solved the problem?

**Comment by 1skonty1** [comment]
Add this in xaxis: {tickPlacement: 'on',}

**Comment by arezooHND** [comment]
I have this problem on touch mode, how can I fix it?
![arezoo](https://user-images.githubusercontent.com/69170728/190372586-f1330266-668c-4d6f-995b-7632819fb7d4.png)

**Comment by rot0505** [comment]
I have this issue, too.
Is there someone who fixed this issue?

**Comment by roblegaspi** [comment]
same here reset and hamburger is missing also timestamp
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/103054295/218136920-9856540b-84ed-4975-8bf2-f66e3311466a.png">

**Comment by davetapley** [comment]
@sergkop @junedchhipa can we get this reopened?

For repro go to e.g.: https://codepen.io/apexcharts/pen/KKMqqKo on desktop and observe:
<img width="163" alt="Screen Shot 2023-04-10 at 10 44 55 AM" src="https://user-images.githubusercontent.com/48232/230959981-da5cb912-bab7-4282-befb-fee9c45e9979.png">

Then open on mobile device (or use browser dev tools to emulate), reload, and observe:
<img width="168" alt="Screen Shot 2023-04-10 at 10 46 55 AM" src="https://user-images.githubusercontent.com/48232/230960327-9507380c-6805-4108-b948-29a7aaf04c12.png">

---

Would you accept a PR to add configuration option for `isTouchDevice` check which @OmerFI identified ⬆️ ?

**Comment by valeriapaulinalustres** [comment]
I am developing with React and I have solved it by adding to my css global file:

.apexcharts-element-hidden{
  opacity:1 !important; 
}

**Comment by Jarnbjorn92** [comment]
I had noticed my apexchart toolbar having the same issue when I removed the tickPlacement. Placing it back into the xaxis resolved it for me.

Example:

options: {
   xaxis: {
      categories: [ ** your categories ** ],
      **tickPlacement: 'on'**  <---- add this
  }
}

Hope this help anyone looking for a potential solution in future.
