### ISSUE TITLE
Line chart not showing lines

### ISSUE THREAD

**Issue by TKirahvi** [apexcharts/apexcharts.js#1066]
## Explanation
I have created apex line chart and all the data points are added to the series. 
They are shown in the chart when hovering on the chart but there are no lines between them. 
If I inspect it, the svg path is like this: 

`<path id="SvgjsPath7948" d="M 476.6071428571429 324.96296296296293" fill="none" fill-opacity="1" stroke="#08cc14" stroke-opacity="1" stroke-linecap="butt" stroke-width="5" stroke-dasharray="0" class="apexcharts-line" index="0" clip-path="url(#gridRectMaskyfyoj37x)" pathTo="M 476.6071428571429 324.96296296296293" pathFrom="M 615.0279831455777 324.96296296296293"></path>`
![apexlinechart](https://user-images.githubusercontent.com/3405318/68476509-81a6c780-0233-11ea-982f-0bcfd08d7a03.gif)

https://codepen.io/tkirahvi/pen/bGGKgro

**Comment by junedchhipa** [comment]
Please post a full working codepen so I can inspect the data and options used to create the chart.

**Comment by TKirahvi** [comment]
https://codepen.io/tkirahvi/pen/bGGKgro

**Comment by TKirahvi** [comment]
And with updateSeries: https://codepen.io/tkirahvi/pen/oNNPaEp

**Comment by TKirahvi** [comment]
The issue was fixed with adding option: 
stroke: { curve: 'straight' }

**Comment by rahulborah** [comment]
I am also facing the same issue with react-apexcharts. Here is the link https://codesandbox.io/s/wild-snowflake-g7qje

**Comment by chika334** [comment]
please i'm having issues with react-apexchart the chart's not showing

**Comment by chika334** [comment]
class PopCharts extends Component {
  constructor(props) {
    super(props);
    this.state = {
      options: {
        chart: {
          id: "apexchart-example",
        },
        xaxis: {
          categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
        },
      },
      series: [
        {
          name: "series-1",
          data: [],
          // data: [1, 6, 8, 9],
        },
      ],
    };
  }

  static propTypes = {
    transactions: PropTypes.object.isRequired,
  };

  componentDidUpdate() {
    return this.props.transactions.transaction === null
      ? ""
      : this.props.transactions.transaction.map((allData) => {
          this.setState((state) => {
            // const xaxisData = state.options.xaxis.categories.push(allData.request.timestamp)
            const details = state.series.map((detail) => {
              detail.data.push(allData.request.amount);
            });
          });
        });
  }

  render() {
    console.log(this.state);
    return (
      <div>
        <Chart
          options={this.state.options}
          series={this.state.series}
          type="bar"
          width={300}
          height={320}
        />
      </div>
    );
  }
}

const mapStateToProps = (state) => ({
  transactions: state.transactions,
});


please help

**Comment by chika334** [comment]
`class PopCharts extends Component {
  constructor(props) {
    super(props);
    this.state = {
      options: {
        chart: {
          id: "apexchart-example",
        },
        xaxis: {
          categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
        },
      },
      series: [
        {
          name: "series-1",
          data: [],
          // data: [1, 6, 8, 9],
        },
      ],
    };
  }

  static propTypes = {
    transactions: PropTypes.object.isRequired,
  };

  componentDidUpdate() {
    return this.props.transactions.transaction === null
      ? ""
      : this.props.transactions.transaction.map((allData) => {
          this.setState((state) => {
            // const xaxisData = state.options.xaxis.categories.push(allData.request.timestamp)
            const details = state.series.map((detail) => {
              detail.data.push(allData.request.amount);
            });
          });
        });
  }

  render() {
    console.log(this.state);
    return (
      <div>
        <Chart
          options={this.state.options}
          series={this.state.series}
          type="bar"
          width={300}
          height={320}
        />
      </div>
    );
  }
}

const mapStateToProps = (state) => ({
  transactions: state.transactions,
});`

**Comment by Frederic-Ferreira** [comment]
I had the same issue when working with multiple data series : I was displaying a number of views (y axis) for a period of time (x axis), with different number of views for differents accounts, in a Line Chart. 

Sometimes, the ApexChart was not displaying certain lines, and the problem comes from the fact that **the number of values on the x axis categories, should never be lesser than the number of data series for the y axis**. 

So, if you have for example ['Jan', 'Feb', 'March'] for the xaxis categories, but a series : { data: [1, 2, 3, 4, 5] }, there is a great chance that the problem comes from this inegality in data values. 

From my own understanding, you can have a lesser number of data series than the number of categories, but never the opposite.

**Comment by luffy-taro** [comment]
Having similar issue, in my case the lines disappear when there's a null value on y-axis. 
Although hover and tooltip works, tooltip also shows changing values but the line itself has disappeared.

**Comment by nfuenma** [comment]
You can try to add a width for the stroke for example: stroke: { width: 2 }
