### ISSUE TITLE
Typescript type error for `chartOptions.stroke.width`

### ISSUE THREAD

**Issue by maasha** [apexcharts/apexcharts.js#1070]
According to the docs:

https://apexcharts.com/vue-chart-demos/line-charts/dashed/

`chartOptions.stroke.width` can accept an array of numbers, however, I get 

`Type  'number[]' is not assignable to type 'number'.`

**Comment by KartikGoyal** [comment]
I am getting same error  as Maasha mentioned above.
My angular project version is @angular/cli": "^10.0.0

ERROR in src/app/showcase/components/home/home.component.ts:38:22 - error TS2322: Type 'number' is not assignable to type '{ name?: string; type?: string; color?: string; data: number[] | { x: any; y: any; fillColor?: string; strokeColor?: string; }[] | [number, number][] | [number, number[]][]; }'.

38             series: [44, 55, 13, 43, 22],
                        ~~
src/app/showcase/components/home/home.component.ts:38:26 - error TS2322: Type 'number' is not assignable to type '{ name?: string; type?: string; color?: string; data: number[] | { x: any; y: any; fillColor?: string; strokeColor?: string; }[] | [number, number][] | [number, number[]][]; }'.

38             series: [44, 55, 13, 43, 22],
                            ~~
src/app/showcase/components/home/home.component.ts:38:30 - error TS2322: Type 'number' is not assignable to type '{ name?: string; type?: string; color?: string; data: number[] | { x: any; y: any; fillColor?: string; strokeColor?: string; }[] | [number, number][] | [number, number[]][]; }'.

38             series: [44, 55, 13, 43, 22],
                                ~~
src/app/showcase/components/home/home.component.ts:38:34 - error TS2322: Type 'number' is not assignable to type '{ name?: string; type?: string; color?: string; data: number[] | { x: any; y: any; fillColor?: string; strokeColor?: string; }[] | [number, number][] | [number, number[]][]; }'.

38             series: [44, 55, 13, 43, 22],
                                    ~~
src/app/showcase/components/home/home.component.ts:38:38 - error TS2322: Type 'number' is not assignable to type '{ name?: string; type?: string; color?: string; data: number[] | { x: any; y: any; fillColor?: string; strokeColor?: string; }[] | [number, number][] | [number, number[]][]; }'.

38             series: [44, 55, 13, 43, 22],
                                        ~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
