### ISSUE TITLE
Possibility to show legend with only one series

### ISSUE THREAD

**Issue by TKirahvi** [apexcharts/apexcharts.js#1074]
As by design, the legend doesn't show if there is only one series. I have a project where legend should be shown all the time regardless of series amount (the amount can change). This cannot be achieved now with this library :(

https://codepen.io/tkirahvi/pen/PooeQXz

**Comment by junedchhipa** [comment]
```javascript
legend: {
  showForSingleSeries: true
}
```

**Comment by junedchhipa** [comment]
In your codepen, you have apexcharts v2.1.2.
Please use the latest one to enable this behavior.

**Comment by TKirahvi** [comment]
I must have missed that option. Sorry about that.
