### ISSUE TITLE
Issue with Radial chart rounded lineCap.

### ISSUE THREAD

**Issue by saicharanallam** [apexcharts/apexcharts.js#1076]
## Codepen

https://codepen.io/xanrick/pen/gOOBvMv

## Explanation
When I enter a series value I expect the person who is seeing to estimate the value. However, when I enter a series value of above 95 its very hard to distinguish it almost looks like 100% or almost 100%.

There is no error message, it's just a visual bug.
Ofcourse I can stop using 
{
    lineCap: 'round'
  }, however it looks really good with the round.

Issue 2:
In bar chart, I am using this option       {endingShape: 'rounded'}, the rounded shape at the end is not similar to the rounded shape on the radial bar, it's less tangential to the bar. It looks good, but not consistent with the round shape on the radial bar, so it kinda looks odd!

**Comment by junedchhipa** [comment]
The `endingShape: 'rounded'` in a bar chart is drawn manually while radialbar round shape is achieved by setting `stroke-linecap: round` of SVG. So, there will be some differences.

Sorry, but as this is standard SVG behavior, I have no fix for it.
