### ISSUE TITLE
chart.width: "100%" and chart.height: "100%" does not work properly

### ISSUE THREAD

**Issue by it-xtech-dev** [apexcharts/apexcharts.js#1077]
## Codepen

https://codepen.io/xtech-dev/pen/VwwEQyM

## Explanation
In my case chart container size is determined by parent elements and has both non zero width and height,. When setting chart.width: "100%" and chart.height: "100%" I'm expecting that chart will nicely fill the container. That doesn't happens because chart size exceeds container size.

- What is the behavior you expect?
Chart should fill container area exactly with 100% width and 100% height.

- What is happening instead?
Chart is overflowing container area.
https://i.imgur.com/gY8hTPo.png

- What error message are you getting?
No error message in this scenario.

**Comment by Venlious** [comment]
I have a similar issue when using 100% width and 100% height. This appears to happen during the initial render, as soon as the screen is resized it'll fix itself.

**Comment by andyslack** [comment]
I am experiencing the same issue

On first page load: 

<img width="508" alt="Screenshot 2020-10-17 at 18 43 32" src="https://user-images.githubusercontent.com/3747768/96348403-c0cad300-10a8-11eb-9a05-9ba9722c71e5.png">

On resize screen:

<img width="498" alt="Screenshot 2020-10-17 at 18 43 39" src="https://user-images.githubusercontent.com/3747768/96348415-c7594a80-10a8-11eb-8ede-c08789e64009.png">

**Comment by tschni** [comment]
I fixed it in Vue.js using `<client-only>` around the chart

**Comment by shaikhhafizf** [comment]
> I am experiencing the same issue
> 
> On first page load:
> 
> <img alt="Screenshot 2020-10-17 at 18 43 32" width="508" src="https://user-images.githubusercontent.com/3747768/96348403-c0cad300-10a8-11eb-9a05-9ba9722c71e5.png">
> 
> On resize screen:
> 
> <img alt="Screenshot 2020-10-17 at 18 43 39" width="498" src="https://user-images.githubusercontent.com/3747768/96348415-c7594a80-10a8-11eb-8ede-c08789e64009.png">

Same issue i am also facing

**Comment by eduardolanzini** [comment]
The same problem.

**Comment by Sulaymon-dev** [comment]
I've same issue :-(

**Comment by JulesVi** [comment]
Hello, same problem here with angular 10 module :(

**Comment by yousifnimah** [comment]
Hello, I did a workaround and the problem has been solved.

First, In data property define the "renderKey": 0 

`
data() {
    return {
      renderKey: 0
      .....
    }
`

Second, add a key as "renderKey" to the **<vue-apex-charts >**  to be like the code below:

```
<vue-apex-charts
                v-show="renderKey === 100"
                :key="renderKey"
                :height="300"
                :options="chartOptions"
                :series="series"
              >
</vue-apex-charts>
```

Third, in mounted add  the code below:
` setTimeout(() => {
      this.renderKey = 100
    }, 100)`

**Comment by Kody458** [comment]
Also experiencing this issue. The renderKey solution above does work, however this essentially disables the animation you see what loading the page, so it's not ideal.

No error in the console, it simply overflows its container then fixes itself when the screen is resized.

**Comment by tusharahmmed** [comment]
Hi, I have done this in **react.js** by updating the state value using the useEffect hook.
I have used **preloader** before showing the chart.
```
import React, { useState, useEffect } from "react";
import ReactApexChart from "react-apexcharts";
import { Spinner } from "baseui/spinner";

const ProductChart = () => {
  const [chartData, setChartData] = useState(null);

  // update state
  useEffect(() => {
    setChartData({
      options: {
        chart: {
          id: "basic-bar",
        },
        xaxis: {
          categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
        },
      },
      series: [
        {
          name: "products shipment",
          data: [30, 40, 45, 50, 49, 60, 70],
        },
      ],
    });
  }, []);

  if (chartData) {
    return (
      <div style={{ width: "100%" }} className="bg-white w-full">
        <ReactApexChart
          options={chartData.options}
          series={chartData.series}
          height={"300"}
          type="bar"
        />
      </div>
    );
  }
  return (
    <div className="bg-white w-full h-full flex items-center justify-center">
      <Spinner />
    </div>
  );
};

export default ProductChart;
```

**Comment by riazkhan186** [comment]
we can add a delay before render the chart by using setTimeout(). This solve in my case.

**Comment by HossamMuhammedOmar** [comment]
If someone is still facing the problem, simply do not wrap it in a **flex** container directly.
It will not work in the first case. 
But, it will resolve the issue on the second one.
> NOTE: I used React with Chakra UI, but it works with any framework.


```
 <Flex w="88%" h="350px">
    <ColumnChart
        width="100%"
        height="100%"
     />
 <Flex/>
```

```
<Flex w="88%" h="350px">
    <Box w="100%">
        <ColumnChart
           width="100%"
           height="100%"
        />
   </Box>
</Flex>
```

**Comment by devberkay** [comment]
faced the same problem in vue-apexcharts and i solved it with this combination: 
```

<ClientOnly>
    <div class="w-[100%] h-[75%]">
      <apexchart
        :options="options"
        :series="series"
        height="75%"
        type="area"
        width="100%"
      />
    </div>
  </ClientOnly>
```

**Comment by eliseubrito7z** [comment]
> If someone is still facing the problem, simply do not wrap it in a **flex** container directly. It will not work in the first case. But, it will resolve the issue on the second one.
> 
> > NOTE: I used React with Chakra UI, but it works with any framework.
> 
> ```
>  <Flex w="88%" h="350px">
>     <ColumnChart
>         width="100%"
>         height="100%"
>      />
>  <Flex/>
> ```
> 
> ```
> <Flex w="88%" h="350px">
>     <Box w="100%">
>         <ColumnChart
>            width="100%"
>            height="100%"
>         />
>    </Box>
> </Flex>
> ```

this worked for me, thanks so much!

**Comment by gregbrowndev** [comment]
All of these solutions that I can see (I'm not familiar with Vue) only work if you explicitly set the height on some parent. In my dashboard, the chart is laid out in a flexbox row where the height is determined by the sibling elements. I'm seeing the same behaviour where the chart doesn't take up the full height, but if you resize the page it fixes the issue.

**Comment by jaanisfehling** [comment]
> Hi, I have done this in **react.js** by updating the state value using the useEffect hook. I have used **preloader** before showing the chart.
> 
> ```
> import React, { useState, useEffect } from "react";
> import ReactApexChart from "react-apexcharts";
> import { Spinner } from "baseui/spinner";
> 
> const ProductChart = () => {
>   const [chartData, setChartData] = useState(null);
> 
>   // update state
>   useEffect(() => {
>     setChartData({
>       options: {
>         chart: {
>           id: "basic-bar",
>         },
>         xaxis: {
>           categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
>         },
>       },
>       series: [
>         {
>           name: "products shipment",
>           data: [30, 40, 45, 50, 49, 60, 70],
>         },
>       ],
>     });
>   }, []);
> 
>   if (chartData) {
>     return (
>       <div style={{ width: "100%" }} className="bg-white w-full">
>         <ReactApexChart
>           options={chartData.options}
>           series={chartData.series}
>           height={"300"}
>           type="bar"
>         />
>       </div>
>     );
>   }
>   return (
>     <div className="bg-white w-full h-full flex items-center justify-center">
>       <Spinner />
>     </div>
>   );
> };
> 
> export default ProductChart;
> ```

Thanks a lot, this works perfectly in React.

**Comment by devonik** [comment]
My issue here was that may container has max-width 600px and initially the container has 400px so the chart rendered with 400. I had a api call wich toggled a condition to show a 600px width div. But the rendered chart was stillt 400px

So my solution
.page {
  &__container {
    width: 600px;
    max-width: 100%;
  }
}
The max-width i set so on mobile the container wont stick on 600px

**Comment by rodneyweast** [comment]
I am also experiencing this problem with angular.  I've made minimal changes to the demo code, and it works if I set width=100%

but as soon as height=100% is added it displays complete blank except for the 3 lines in the upper right and corner that provide the ability to export image.

app.component.html looks like:

```
<style>
.chartDiv {
  margin: 2;
  width: 95%;
  height: 95%;
  /* border: 1px solid blue; */
}   
</style>


<div class="chartDiv">
  <apx-chart
  [series]="chartOptions.series"
  [chart]="chartOptions.chart"
  [xaxis]="chartOptions.xaxis"
>
</apx-chart>

</div>
```


and  app.component.ts looks like:

```
import { Component } from "@angular/core";

import {
  ChartComponent,
  ApexAxisChartSeries,
  ApexChart,
  ApexXAxis,
  ApexTitleSubtitle
} from "ng-apexcharts";

export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  xaxis: ApexXAxis;
  title: ApexTitleSubtitle;
};

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  public chartOptions: ChartOptions;
  title!: 'Charting';
  
  constructor() {
    this.chartOptions = {
      series: [
        {
          name: "My-series",
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
        }
      ],
      chart: {
        width: "100%",
        height: "100%",
        type: "bar"
      },
      title: {
        text: "My First Angular Chart"
      },
      xaxis: {
        categories: ["Jan", "Feb",  "Mar",  "Apr",  "May",  "Jun",  "Jul",  "Aug", "Sep"]
      }
    };
  }
}
```

**Comment by Jafar-128bit** [comment]
I had the same issue, but I solved it like this - 

`const [parentWidth, setParentWidth] = useState<string | number | undefined>(undefined);
    const parentComponent = useRef<HTMLDivElement>(null);

    useEffect(() => {
        let timeout: NodeJS.Timeout;

        const observer = new ResizeObserver(entries => {
            for (let entry of entries) {
                if (parentComponent.current === entry.target) {
                    timeout = setTimeout(() => {
                        setParentWidth(entry.contentRect.width);
                    }, 500);
                }
            }
        });

        if (parentComponent.current) {
            observer.observe(parentComponent.current);
        }

        return () => {
            observer.disconnect();
            clearTimeout(timeout); // Clear the timeout on component unmount
        };
    }, []);

<section className="inventoryCharts" ref={parentComponent}>
        <ReactApexChart
            options={chartData.options as ApexOptions}
            series={chartData.series}
            type='line'
            height={350}
            width={parentWidth}
        />
    </section>`
