### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null after filter

### ISSUE THREAD

**Issue by ssuettenbach** [apexcharts/apexcharts.js#1078]
I am using apexcharts with Nuxt and wanted to add a filter method when the users clicks on one of the slices of a donut-chart. 

The filtering works, the chart is updated as wanted.
But I get an error-message in my developer console.

> Uncaught TypeError: Cannot read property 'getAttribute' of null at t.value (apexcharts.esm.js?e122:6)

This is my setup
```
<template>
      <client-only>
        <VueApexCharts
          type="donut"
          :options="options"
          :series="states"
          v-if="isLoaded"
          @dataPointSelection="clickHandler"
        />
      </client-only>
</template>

<script>
export default {
  name: 'HardwareState',
  props: {
    devices: {
      type: Array,
      default () {
        return []
      }
    }
  },
  data () {
    return {
      isLoaded: false,
      options: {
        //...
      },
      filter: null
    }
  },
  computed: {
    states () {
      let green = 0
      let yellow = 0
      let red = 0
      let grey = 0
      this.devices.forEach((d) => {
            switch (d.state) {
              case 'green':
                green++
                break
              case 'yellow':
                yellow++
                break
              case 'red':
                red++
                break
              default:
                grey++
          }
      })
      const states = [green, yellow, red, grey]
      if (this.filter !== null) {
        for (let i = 0; i < states.length; i++) {
          if (i !== this.filter) {
            states[i] = 0
          }
        }
      }
      console.log(states)
      return states
    }
  },
  mounted () {
    this.isLoaded = true
  },
  methods: {
    clickHandler (event, chartContext, selectedData) {
      this.filter = (this.filter !== null) ? null : selectedData.dataPointIndex
    }
  }
}
</script>
```

**Comment by zxwild** [comment]
The same error for pie chart when "chart.updateOptions()" is called.

```javascript
events: {
  dataPointSelection: this.handleSelection,
}

handleSelection(event, chart, item) {
  let index = item.dataPointIndex;
  let targetItem = this.items[index];

  targetItem.selected = !targetItem.selected;
  chart.updateOptions(
    {colors: this.currentChartColors},
    false, false, false,
  );
},
```

**Comment by Kolvin** [comment]
Same error on use of `chart.toggleSeries()`

**Comment by junedchhipa** [comment]
Can I have a [codesandbox](https://codesandbox.io/s/pwwz8009n0) demo, please?

**Comment by dandymon** [comment]
I've noticed this error too with trying to use the exec command, (using React), but found out what I was doing was in error

Works
```
<Chart options="chart1opts" series="series1" type="bar">
<Chart options="chart2opts" series="series2" >
<Button onClick={()=>ApexCharts.exec("idChart2","toggleSeries","series2datacol2")}

```

Doesn't work: putting the first chart beneath the second chart
```
<Chart options="chart2opts" series="series2" type="bar">
<Button onClick={()=>ApexCharts.exec("idChart2","toggleSeries","series2datacol2")}
<Chart options="chart1opts" series="series1" type="bar">

```
The fault laid in the fact that I had accidentally given both the charts the same id - and interestingly, where I had placed the button appeared to be causing the rendering to look at the graph that was most recently rendered to apply the exec command to. So it worked sometimes. Since i did not have a dataseries called seriesdatacol1 in my second chart, I suspect this was the error, it couldn't find that dataseries in that chart.

Try giving your charts unique id's, maybe if they both don't have an id, then this is the same as them being called the same thing (`undefined` most likely), and maybe you're getting the same problem as I did.

How to add id in react:
https://github.com/apexcharts/react-apexcharts/issues/73#issuecomment-634494834

**Comment by AmrutHunashyal** [comment]
![image](https://user-images.githubusercontent.com/7254975/121807959-fe9dec80-cc73-11eb-8255-96118d9dd368.png)

Trying to use ApexCharts in Salesforce Lightning in lwc. Although the chart appears fine but when clicked on x-axis data series throws error as show in the image.

**Comment by JulianL99** [comment]
I am getting the same issue when using the apexcharts Polar Area chart. I have a custom on click handler for when one of the slices is clicked, and that is when the error is triggered:
![image](https://github.com/user-attachments/assets/10985bb8-05df-4dad-b032-304d1bce6b88)

Seems to have something to do with `parentNode` being undefined, but when I stepped thru the debugger, it seemed like it was defined. Any info on this would be appreciated!
