### ISSUE TITLE
Allow for static label in donut charts

### ISSUE THREAD

**Issue by twigs67** [apexcharts/apexcharts.js#1079]
I don't see this feature in the docs, but it would be great if we could add a static label inside the donut. If this is possible, can someone share how to do this?

Thanks

**Comment by junedchhipa** [comment]
The total labels of donut can be tweaked to achieve this

```javascript
plotOptions: {
  pie: {
    donut: {
      labels: {
        show: true,
        name: {
          show: false
        },
        value: {
          offsetY: -10
        },
        total: {
          show: true,
          showAlways: true,
          offsetY: -10,
          formatter(w) {
            return ['Static', 'label']
          }
        }
      }
    }
  }
}
```

![Screen Shot 2020-01-24 at 12 55 53 AM](https://user-images.githubusercontent.com/17950663/73016663-4dab6d80-3e44-11ea-87d5-ba6baa263505.png)
