### ISSUE TITLE
toggleDataPointSelection not showing label value in donut chart

### ISSUE THREAD

**Issue by aospinagcg** [apexcharts/apexcharts.js#1080]
## Codepen

https://codepen.io/aospinagcg/pen/gOOBdER

## Explanation

- What is the behavior you expect?
![image1](https://user-images.githubusercontent.com/47115208/68875696-409a3180-06d1-11ea-9608-06f6119924d7.PNG)

- What is happening instead?
![image2](https://user-images.githubusercontent.com/47115208/68875754-59a2e280-06d1-11ea-8641-159513cc8c55.PNG)

The method should show the name and value of the series when in plotOptions they are showing, currently only expand the label

**Comment by mgilge3** [comment]
I am also having this issue with the donut chart.  I am trying to render the chart with a section selected and labels in the center.  The labels do not show until I mouse over the chart, is there a way to fix this?

**Comment by marssantoso** [comment]
Is there an update on this? Still happening in version `3.26.0`.

Or is there any workaround, yet?

**Comment by juancdominici** [comment]
> Is there an update on this? Still happening in version `3.26.0`.
> 
> Or is there any workaround, yet?

> The tooltip only shows when the user directly interacts with the chart.
> It doesn't get displayed on the data-point selection. It's not a bug but the feature you're expecting isn't there.
> _Originally posted by @junedchhipa in https://github.com/apexcharts/apexcharts.js/issues/1361#issuecomment-595896423_

Hope this helps, maybe its the same for labels.

**Comment by AlanNabiev** [comment]
Hi guys, I found a hack. You can use [total](https://apexcharts.com/docs/options/plotoptions/pie/).This is the labels property.
`
[total](https://apexcharts.com/docs/options/plotoptions/pie/#total): {
          [show](https://apexcharts.com/docs/options/plotoptions/pie/#totalShow): false,
          [showAlways](https://apexcharts.com/docs/options/plotoptions/pie/#totalShowAlways): false,
          [label](https://apexcharts.com/docs/options/plotoptions/pie/#totalLabel): 'Total',
          [fontSize](https://apexcharts.com/docs/options/plotoptions/pie/#totalFontSize): '22px',
          [fontFamily](https://apexcharts.com/docs/options/plotoptions/pie/#totalFontFamily): 'Helvetica, Arial, sans-serif',
          [fontWeight](https://apexcharts.com/docs/options/plotoptions/pie/#totalFontWeight): 600,
          [color](https://apexcharts.com/docs/options/plotoptions/pie/#totalColor): '#373d3f',
          [formatter](https://apexcharts.com/docs/options/plotoptions/pie/#totalFormatter): function (w) {
            return w.globals.seriesTotals.reduce((a, b) => {
              return a + b
            }, 0)
          }
        }
`
We also need a variable that will store the current value. Then we will write this variable in total.formatter (it will be reactive and the value will change accordingly). Label is more difficult. We need to create a function to change to change our a variable and also change the label there. Something like this
`
selectUserToken (token) {
      this.selectedUserToken = token
      this.apexTokenPieChartOptions.plotOptions.pie.donut.labels.total.label = token.symbol
    }
`

**Comment by benjamin-aubry** [comment]
Hi,
Another hack : 
Call toggleDataPointSelection 3 times, it works !

**Comment by SilvioDiasJr** [comment]
@benjamin-aubry you helped a lot! thanks
