### ISSUE TITLE
Hope to support the map type chart using GeoJSON

### ISSUE THREAD

**Issue by Exrick** [apexcharts/apexcharts.js#1084]
**Is your feature request related to a problem? Please describe.**
I hope to support the map type chart using GeoJSON in the future.

**Describe the solution you'd like**
Support the map type chart using GeoJSON. eg: https://echarts.apache.org/examples/en/#chart-type-map

**Describe alternatives you've considered**
Other charts like echarts https://echarts.apache.org/examples/en/#chart-type-map.

**Additional context**
This is the most beautiful chart I have ever seen. Thanks for your work.

**Comment by junedchhipa** [comment]
@Exrick Thank you for kind words and the suggestion.
Unfortunately, map charts are out of scope for this library and won't be implemented in the near future.

**Comment by theDanielJLewis** [comment]
2 years later, any change of opinion on this, or a third-party extension that adds geo/map charts?

**Comment by SoraDevin** [comment]
I would also like an answer to this question
