### ISSUE TITLE
dataPointSelection returns 'undefined' for line type

### ISSUE THREAD

**Issue by dotmanu** [apexcharts/apexcharts.js#1086]
Hi, I'm trying to use dataPointSelection to return a value on click. It works perfectly for pie charts, but when using a line chart, it returns 'undefined'.

```
var options = {
                tooltip: {
                    intersect: true,
                    shared: false
                },
                markers: {
                    size: 6
                },
                chart: {
                    type: 'line',
                    zoom: {
                        enabled: false
                    },
                    events: {
                        dataPointSelection: (e, ctxt, config) => {
                            const value = config.w.config.series[config.dataPointIndex];
                            console.log(value);
                        }
                    }
                }
}
```

The tooltip and markers options are like in the documentation, so I'm not sure what's going on. Any idea of what's happening? Thanks a lot.

**Comment by junedchhipa** [comment]
For XY charts (line/column/scatter), you need to do it this way.

```javascript
chart: {
  events: {
    dataPointSelection: (e, ctx, config) => {
      const value =  config.w.globals.series[config.seriesIndex][config.dataPointIndex]
    }
  }
}
```

`w.config.series` is the original array which is passed by user. `w.globals.series` is the transformed array simplified.

**Comment by Qaiser45** [comment]
> For XY charts (line/column/scatter), you need to do it this way.
> 
> ```js
> chart: {
>   events: {
>     dataPointSelection: (e, ctx, config) => {
>       const value =  config.w.globals.series[config.seriesIndex][config.dataPointIndex]
>     }
>   }
> }
> ```
> 
> `w.config.series` is the original array which is passed by user. `w.globals.series` is the transformed array simplified.

I want category name

**Comment by Qaiser45** [comment]
Apex Chart
for area line chart categories
config.w.globals.categoryLabels[config.dataPointIndex]
for area line chart data
config.w.globals.series[config.seriesIndex][config.dataPointIndex]

for other types
config.w.globals.labels[config.dataPointIndex]
