### ISSUE TITLE
Zooming bug when the zoom type is y or xy

### ISSUE THREAD

**Issue by eltaiebi** [apexcharts/apexcharts.js#1087]
I am working on a project where I have to display a time series in a line chart. I added the zoom to the graph and it works well, but I noticed that when the scale is too small and I try to zoom, the graphic disappeared and I have an error in the console.
The error occurs only when the zoom type is y or xy

**Here is the error message from the Chrome console :** 
apexcharts:6 Error: <circle> attribute cy: Expected length, "NaN".

**Here is the codepen link that contains an example :**
  [Codepen link](https://codepen.io/eltaiebi/pen/ZEEPmOP)

**Version ApexCharts v3.10.1**

I hope my description was clear
Thank you

**Comment by junedchhipa** [comment]
Thank you for reporting. It seems like y-axis values are being rounded off which results in an invalid y-axis scale.
I will look into it soon.
