### ISSUE TITLE
Range Bar Chart Different Colors For Each Row

### ISSUE THREAD

**Issue by TaylorFoster90** [apexcharts/apexcharts.js#1088]
Looking for a way to customize each row on the range bar chart to have a different color. On the [example in the docs](https://apexcharts.com/docs/chart-types/range-bar-chart/) it is comparing "Bob" and "Joe" data, so they are each getting their own color. However, in my case, I am only working with one set of data and plotting out contract terms on the range bar chart so each row is picking up the index of 0 for the color. Can I make it to where each row is getting their own color?

<img width="888" alt="Screen Shot 2019-11-21 at 1 14 46 PM" src="https://user-images.githubusercontent.com/10275025/69364770-eb29cb80-0c60-11ea-9502-50ce3eb8501b.png">

In this above example I want "Current Term" to be blue and "Notice Period" to be the next color in the color array. 

## Explanation

- What is the behavior you expect?
Different Colors For Each Row.
- What is happening instead?
Same Color For Each Row
- What error message are you getting?
N/A

**Comment by JoeyEff** [comment]
Does the range bar support an array of colors? The snippet below works for the bar chart, but the range bar just shows blue.

<img width="509" alt="RangeBar" src="https://user-images.githubusercontent.com/1790195/70953972-993e5080-2028-11ea-9dd1-e1fc75fc7ff0.PNG">

**Comment by junedchhipa** [comment]
Fixed in this commit - [ddd31c8](https://github.com/apexcharts/apexcharts.js/commit/ddd31c8d9de346de274616d350c1d4d02c66e6d0)

Works in latest version 3.11.2
https://apexcharts.com/javascript-chart-demos/timeline-charts/distributed/

**Comment by TaylorFoster90** [comment]
@junedchhipa tysm for this feature!
