### ISSUE TITLE
Strange display

### ISSUE THREAD

**Issue by Asthonishia** [apexcharts/apexcharts.js#1089]
## Codepen

https://codepen.io/Asthonishia/pen/qBBwVGq

## Explanation

- **What is the behavior you expect?**
I want no blank space on the first category and that the width of categories adjust to the content

- **What is happening instead?**
I have 2 problems : 

1. My second data (PEHD | CAISSES BROYEES FLOREAL (13651 kg)) is relative to the second category "Vrac" but it lets a blank space on the first one. It keeps the position it has on the dataset :(. If i mode it on dataset, the empty space on first category and the bar on "Vrac" moves too
2. The second category get the same width as the first one while it has only one data

- **What error message are you getting?**
none

**Comment by junedchhipa** [comment]
This is the expected behavior.
Datapoints with 0 values will still take up space in a category chart.
I increased the stroke with and below is the visual I got.

![5xhh5tb1](https://user-images.githubusercontent.com/17950663/71543471-18247900-2999-11ea-8d61-dc604bcbfc7b.png)
