### ISSUE TITLE
Lines of chart draw over DataLabels

### ISSUE THREAD

**Issue by andrey-oparin** [apexcharts/apexcharts.js#1091]
Sometimes Lines of chart draws over DataLabels, how i cat fix it ?

Possible draw DataLabels after draw all lines of chart ?

![data-labels-bug](https://user-images.githubusercontent.com/6649855/69473434-0292c100-0de7-11ea-8366-e750d43e0750.PNG)

**Comment by andrey-oparin** [comment]
I move apexcharts-datalabels after line definition with developer console and fix it

![data-labels-fix](https://user-images.githubusercontent.com/6649855/69473749-7da9a680-0dea-11ea-88d3-a3be05b7d13d.PNG)

Please fix SVG render

**Comment by junedchhipa** [comment]
Thanks for reporting, the issue is fixed and will be released soon.
