### ISSUE TITLE
Calling Brush Chart with NPM Returns Promise Error

### ISSUE THREAD

**Issue by bigcountry-scav** [apexcharts/apexcharts.js#1092]
I have an area chart and a brush chart if using 3.10.1 from CDN I have no issues and both charts show correctly as seen here ...

https://codesandbox.io/s/apex-cdn-bxfmj

If I use the NPM however only the area chart is seen and the brush results in promise errors of ApexCharts is undefined as seen here ...

https://codesandbox.io/s/apex-npm-mdu68

**Comment by aon108** [comment]
This issue also happens with me. using the CDN version works fine, if i try use the NPM version however i get error ApexCharts not defined when rendering the brush chart. The main chart renders fine!
