### ISSUE TITLE
Ability to clear selection

### ISSUE THREAD

**Issue by iranana** [apexcharts/apexcharts.js#1094]
Hi, thanks for making such a great library, I hope this is the right place for this:

**Is your feature request related to a problem? Please describe.**
Currently, it doesn't seem possible to clear a selection once you've made one.

**Describe the solution you'd like**
Ideally, it would be possible to clear a selection by simply clicking outside of the selection area on the chart.

**Describe alternatives you've considered**
Clearing selections when resetting zoom levels is another option, but I'm not sure if this is a desirable side-effect.

**Additional context**
I'm trying to implement a function where you can highlight areas of a chart to filter data in a table. The user will need a way to clear their selection and revert back to the initial state.

**Comment by FelixWaigner** [comment]
Is there any update or did u got a solution by yourself and can share it? :)

**Comment by junedchhipa** [comment]
Try this?

```javascript
chart.updateOptions({
  chart: {
    selection: {
      xaxis: {
        min: undefined,
        max: undefined
      }
    }
  }
})
```

**Comment by sacalata** [comment]
> Try this?
> 
> ```js
> chart.updateOptions({
>   chart: {
>     selection: {
>       xaxis: {
>         min: undefined,
>         max: undefined
>       }
>     }
>   }
> })
> ```
> 
> If you don't have a chart reference, and need to update options using chartID, you can try the alternative way of updating chart options
> 
> ```js
> // update options using exec method
> ApexCharts.exec('chartID', 'updateOptions', {
>   chart: {
>     selection: {
>       xaxis: {
>         min: undefined,
>         max: undefined
>       }
>     }
>   }
> })
> ```

What about reseting data point selections?, we can change the data point selected with `toggleDataPointSelection `, any way to programatically de-select all data points?

**Comment by democlitos** [comment]
Since @junedchhipa code wasn't working for me, here is my solution:

```javascript
// Clear selection after clicking on "Reset" (Home button)
updated: function (chartContext, config) {
  let selectionRect = chartContext.w.globals.dom.baseEl.querySelector('.apexcharts-selection-rect')
  if (selectionRect) {
    selectionRect.setAttribute('width', 0)
  }
}

// Clear selection after clicking outside of the selection area 
click: function(event, chartContext, config) {
  let selectionRect = chartContext.w.globals.dom.baseEl.querySelector('.apexcharts-selection-rect')
  if (selectionRect && event.target != selectionRect) {
    selectionRect.setAttribute('width', 0)
    selectionRect.setAttribute('x', -500)
  }
},
```
