### ISSUE TITLE
Show value as data-* attribute on point

### ISSUE THREAD

**Issue by tommitch** [apexcharts/apexcharts.js#1096]
I'm currently evaluating this lib as a replacement for the custom written charts my company is using. 

One of the main advantages our own charts has concerns our automated QA efforts which rely on a data-value={value} attribute to confirm values on the charts.

I've been unable to find anything in the docs that would allow me to achieve the same result for each data point on a line chart. Is this just something I have missed in the docs or is this something that is currently not possible?

**Comment by thenametomwastaken** [comment]
In case anyone ends up at the issue with the same requirement as me, you can achieve much the same behaviour by adding data labels to the chart and setting the font size to 0 (assuming all you want is a programmatic way to pull the values from a rendered chart without data labels appearing)
