### ISSUE TITLE
Multiple Y Axis chart with negative values adds a thick border

### ISSUE THREAD

**Issue by gsabetta** [apexcharts/apexcharts.js#1097]
## Codepen
https://codepen.io/gerardosabetta/pen/bGGPaPZ

If you are using vue-apexcharts, and want to create a demo in Vue environment, use [CodeSandbox Vue template](https://codesandbox.io/s/pwwz8009n0)
If you are using react-apexcharts, and want to create a demo in React environment, use [CodeSandbox React template](https://codesandbox.io/s/6yoqonyo7r)

## Explanation

A thick border appears when I add the second series

- What is the behavior you expect?
I expect it to work like a regular multiple series chart
- What is happening instead?
A thick border appears
- What error message are you getting?
none

**Comment by junedchhipa** [comment]
The thick border is actually `stroke`.
In a combo chart, you can control the stroke by

```javascript
         stroke: {
             width: [3, 0]
          }
```

where the first series has a stroke-width of 3 while the second series (column) has no stroke.
