### ISSUE TITLE
 hideOverlappingLabels not working, all other options are working in stacked chart. xaxis:{labels:{ hideOverlappingLabels:true}}

### ISSUE THREAD

**Issue by jatindumka** [apexcharts/apexcharts.js#1099]
## Codepen

Modify [this codepen](https://codepen.io/apexcharts/pen/bxzgZJ) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

If you are using vue-apexcharts, and want to create a demo in Vue environment, use [CodeSandbox Vue template](https://codesandbox.io/s/pwwz8009n0)
If you are using react-apexcharts, and want to create a demo in React environment, use [CodeSandbox React template](https://codesandbox.io/s/6yoqonyo7r)

## Explanation

- What is the behavior you expect?
- What is happening instead?
- What error message are you getting?

**Comment by junedchhipa** [comment]
Your provided codepen link is invalid.
Please provide a working codepen example.
