### ISSUE TITLE
undefined is not an object (evaluating 'e.createElementNS') React-Native

### ISSUE THREAD

**Issue by sumitaryavrat** [apexcharts/apexcharts.js#11]
When I import the "import ApexCharts from 'apexcharts' "  undefined is not an object (evaluating 'e.createElementNS') React-Native this error occurs.

**Comment by junedchhipa** [comment]
The library has no direct support for React-Native as of now. The undefined error is due to `document` not being available which will only be present in browsers.

**Comment by sumitaryavrat** [comment]
ok, so how can it work for react-native. Can you suggest me any changes in code??

**Comment by hunterlong** [comment]
:(

**Comment by JConcepts** [comment]
no news ? @sumitaryavrat you made it work on react-native ?
