### ISSUE TITLE
x-axis is displayed as local datetime instead of UTC

### ISSUE THREAD

**Issue by tforssander** [apexcharts/apexcharts.js#110]
(This may or may not be related to #95)

First of all, I assume that I've miss-configured something, but my X-axis appears to always be shown as local time instead of UTC. I tried using both timestamp (1536104489000) and datetime (2018-09-04 23:41:29) as x-axis data. 

The first entry in the raw data is 1536104489000 (2018-09-04T23:41:29) but when viewed it shows up as 2018-09-05 01:41:29. I am in a UTC+2 timezone. 

Is it possible that Apexcharts or underlying frameworks somehow converts my UTC data into local timezone? If so, is it possible to turn it off?

PS: Thank you so much for Apex :) I love it

**Comment by junedchhipa** [comment]
Hi @tforssander 

Yes, I need to look into the datetime offset issues as many users are reporting it.
It is a possibility that while manipulating datetime, I might have accidentally used local time instead of UTC.

Needs digging further, thanks for reporting the issue. And glad you loved it :)

**Comment by tforssander** [comment]
@junedchhipa Great, thank you for the quick reply.

**Comment by junedchhipa** [comment]
Fixed it. You will see the correct "hours" in the next patch release of ApexCharts

**Comment by junedchhipa** [comment]
By the way, I checked the code - It is not converting UTC dates to local date anywhere.
ApexCharts deals everything in UTC

**Comment by bivald** [comment]
Hi,

This solves the issue for GMT+1, but not for those of us on GMT+2 (or any other timezone, really). I've made a suggestion for a solution on https://github.com/apexcharts/apexcharts.js/commit/661647c0f899c2f09e7aa9ee765fba8b06dddb13

**Comment by bivald** [comment]
Forgot to ping @junedchhipa :) should I try to do a PR?

**Comment by junedchhipa** [comment]
@bivald Sorry for the delay, missed the message.
I tried your suggestion you provided in that commit, but for some reason - it didn't work great.

Sure, you can try creating a PR :)

**Comment by tgpoint** [comment]
Lets try to replace .toUTCString() to .toISOString() in code...

**Comment by engHusseinMansour** [comment]
Hello
This solves the issue for GMT+1, but not for those of us on GMT+2 
There is no solution ?
and please what do you mean by the word PR ?

**Comment by mike-pratt** [comment]
Hi @junedchhipa , this is still an issue unfortunately, it's not using UTC date times.

See the following example: https://codepen.io/miketrell/pen/mddeyYK

I've modified the start time to 1570606650000, which corresponds to the date '9 October 2019 07:37:30' UTC time, or '9 October 2019 08:37:30' GMT + 1 (my) local time.

If you change you systems local time, the charts line starts from UTC +/- the offset you've set, rather than 07:37:30 UTC as I would expect. Is there a hidden utc toggle you can set on the xaxis that I'm missing here?

**Comment by alex-lechner** [comment]
I'm having the same issue. The chart weirdly displays the data on hour 1 instead of hour 0 and then on hour 17 instead of hour 15.  🤔

**Comment by drpuur** [comment]
@junedchhipa : where does it say that the display format should be UTC? This change broke my setup, as I want to show timestamps in localtime.

**Comment by junedchhipa** [comment]
Should I add a toggle for UTC? Be default, it should be true, but in case someone wants to display local time, it will not convert.

**Comment by drpuur** [comment]
That would be great, yes! Thanks.

**Comment by junedchhipa** [comment]
@drpuur Can you please create a codepen with the local timestamp series and give me a brief description of what are you expecting v/s what you're seeing?

**Comment by drpuur** [comment]
@junedchhipa : sorry, it is the first time I use CodePen :-( and it is late already (I am not sure why it does not work), but here is the link anyway: https://codepen.io/drpuur/pen/ExaQWGx

I should show a time series with one datapoint every two hours on 06-Jan-2020 (from midnight to midnight localtime, which is from 05-Jan-2020 23:00 (UTC) to 06-Jan-2020 23:00 (UTC).

What I would like to see is the time in localtime, the newest Release of ApexCharts (Version 3.12.0) does show all timestamps in UTC.

**Comment by junedchhipa** [comment]
Thanks for the codepen. I have added a new boolean option `xaxis.labels.datetimeUTC`.
Please try it after the next release and let me know if it fixes the issue.

**Comment by loopezz** [comment]
When could we expect the next release? I'm looking forward to it. :-)

**Comment by junedchhipa** [comment]
In a few hours :)

**Comment by drpuur** [comment]
Just a note: it would be very welcome if the datetimeUTC would work for tooltips as well.
I included the setting for xaxis.labels in my codepen.

**Comment by drpuur** [comment]
@junedchhipa : I noticed today that the xaxis labels are still wrong in Safari (I checked with an IPad and with an IPhone). https://codepen.io/drpuur/pen/ExaQWGx 

Tests with Chrome do not have this problem.

Tooltips are fine for Chrome and Safari.

**Comment by vladTeplitski** [comment]
Hi guys,
GMT+2 time still seems not to work. Do you have any estimation about this fix ?

**Comment by MarcelMatko** [comment]
Hi guys, is it possible to show ApexCharts in CET timezone?

**Comment by kamaladenalhomsi** [comment]
![image](https://user-images.githubusercontent.com/16209653/82754513-a4fb2380-9dcd-11ea-8171-565c6ccbff92.png)
the same issue here, it format hours in UTC

**Comment by kamaladenalhomsi** [comment]
for incoming people facing this:

as @drpuur showed in his codepen, just add:
```js
xaxis: {
   labels: {
       datetimeUTC: false,
   }
}
```

this will fix it for both labels and tooltip

**Comment by Tofandel** [comment]
@kamaladenalhomsi It didn't work for me on the tooltip..

**Comment by coconut-cracker** [comment]
> for incoming people facing this:
> 
> as @drpuur showed in his codepen, just add:
> 
> ```js
> xaxis: {
>    labels: {
>        datetimeUTC: false
>    }
> }
> ```
> 
> this will fix it for both labels and tooltip

You, Sir (and @junedchhipa ofc), are a gentleman and a scholar!

I can't say how long I spent trying rummaging around trying to fix this, thinking I'd messed up a calculation somewhere... ><

**Comment by davidv171** [comment]
> for incoming people facing this:
> 
> as @drpuur showed in his codepen, just add:
> 
> ```js
> xaxis: {
>    labels: {
>        datetimeUTC: false
>    }
> }
> ```
> 
> this will fix it for both labels and tooltip

This did not help me at all. A moment.js/Date instance with a provided timezone is always converted back into UTC, no matter what the setting on this is.
