### ISSUE TITLE
Turning off unknown tooltip part

### ISSUE THREAD

**Issue by AmberWilliams** [apexcharts/apexcharts.js#1100]
I tried turning off the y/x axis tooltip and marker but the tooltip part with the arrow pointing does not turn off. I can't seem to find what this would be called to turn off.
<img width="179" alt="apexcharts-tooltip-issue" src="https://user-images.githubusercontent.com/51619139/69730629-54598500-1120-11ea-8220-05bd256ec02b.png">

What is its name?

**Comment by AmberWilliams** [comment]
In your css just add the following 

`.pexcharts-xaxistooltip {
  display: none;
}`

**Comment by junedchhipa** [comment]
You can do

```javascript
xaxis: {
  tooltip: {
    enabled: false
  }
}
```

**Comment by AmberWilliams** [comment]
@junedchhipa this is what I was looking for. Didn't think to look in the xaxis options. Thanks

**Comment by jota12x** [comment]
@junedchhipa Thanks. It just happened to me and I was trying 
<img width="718" alt="imagen" src="https://user-images.githubusercontent.com/6154802/70040050-36978e80-15fe-11ea-87cc-55fddebef102.png">
The x->show:false option didn't work at all. Maybe might be necessary some update to the documentation (?)
