### ISSUE TITLE
Question: Offset X rendering misaligned data labels

### ISSUE THREAD

**Issue by flaviomsb** [apexcharts/apexcharts.js#1102]
Hi,

One of my bar charts shows the data labels in the wrong position and I read the documentation several times for clues without success. 

I have also looked up for past issues (open or closed) but could not find anything.

How is the right way to solve this kind of issue? In my chart options I am using

`bar: {
    dataLabels: {
      position: 'top'
    }
  },
  dataLabels: {
    enabled: true,
    offsetX: 30
  },`

Pretty much just like what the official documentation recommends but nevertheless the labels look misaligned.

![Screen Shot 2019-11-27 at 8 06 33 PM](https://user-images.githubusercontent.com/2546031/69778106-b50cb000-1168-11ea-949f-ae2afea34a9d.png)

Thanks a lot.

**Comment by flaviomsb** [comment]
Looks like a bug because the **same chart** with the configuration above renders correctly when the values are close

![Screen Shot 2019-11-27 at 11 00 41 PM](https://user-images.githubusercontent.com/2546031/69778499-1da85c80-116a-11ea-9f3a-dae8f2c66810.png)

**Comment by junedchhipa** [comment]
Can you please create [codepen](https://codepen.io/apexcharts/pen/xYqyYm) demos for both the examples?

**Comment by flaviomsb** [comment]
This issue is quite inconsistent to replicate, it's there but I cannot make a sample that shows the problem. Feel free to close it and maybe future releases will naturally fix this issue.

I have for now tweaked the data labels configuration in order to get the numbers inside the bar.

thanks.

**Comment by zohar1000** [comment]
@flaviomsb did you find a solution for that? I'm having the same problem where offsetX is misaligned on the bar chart.

**Comment by joaofuzessy** [comment]
I have the same issue reported by @zohar1000 . Any updates on this one?

**Comment by HamzaNapollo** [comment]
![chart](https://github.com/user-attachments/assets/176a8465-0153-47f1-9945-9630bcc0433e)
Facing same problem with datalabels merging with bars on its maximum.
did u find any solution?
