### ISSUE TITLE
Problem with brush chart selection

### ISSUE THREAD

**Issue by lukasz-ciskowski** [apexcharts/apexcharts.js#1104]
## Explanation

- What is the behavior you expect?
Brush chart selection should remain the same range after resolution change.
- What is happening instead?
After moving the brush chart range and changing the resolution (forcing charts to scale) the brush selection is resetting to its default position at the beginning of the chart.
For defining the new range by mouse dragging (let's call it range x), then move the brush chart selection (to range y) and change the resolution, the brush selection is resetting to the position x.
- How to reproduce it?
This error occurs in demo example with brush chart

**Comment by larsmathuseck** [comment]
Similar problem here: The brush jumps to the first selection after a re-rendering when using annotations.

**Comment by Arawnh** [comment]
Any updates on this?
