### ISSUE TITLE
dataLabel not aligned in donut with customScale

### ISSUE THREAD

**Issue by Chmielik** [apexcharts/apexcharts.js#1105]
## Codepen

https://codepen.io/Chmielik/pen/OJPLMRp

## Explanation

- What is the behavior you expect?
To have responsive chart, scaled with ratio I've set. I've used original codepen, and just added `           customScale: 0.8,`
- What is happening instead?
Chart is actually scaling, but dataLabel is getting css transform: translate(X, Y) which cause that is not centered in donut
- What error message are you getting?
No error

**Comment by FDArchy** [comment]
Have the same troubles, pie/donut charts are have problems with adaptivity.
