### ISSUE TITLE
"Syncing charts" documentation doesn't exist

### ISSUE THREAD

**Issue by MatheusAvellar** [apexcharts/apexcharts.js#1106]
**Is your feature request related to a problem? Please describe.**
I could not find any documentation on syncing multiple charts, apart from a [demo page](https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/) (and its Vue counterpart). I had to deduce from the demo source code what made charts actually sync, and it's not even that obvious. Searching for 'sync' on the docs just gives you links to said demo page. There seems to be no hint of the `group` and `id` properties at all on the documentation, even under the "Options (References)" > "chart".

**Describe the solution you'd like**
For starters, adding `group` and `id` sections under "Options (References)" > "chart" would be nice. Perhaps a section "Synchronization" under "Chart Essentials" could be created as well. Another good thing would be to add comments on the "Syncing charts" demo source code explicitely stating WHAT is doing the syncing.

**Describe alternatives you've considered**
Spending a fair amount of time on Google (to no avail), then trying to deduce from the demo source code what parts are useful and what aren't. Did you know `chart.group` by itself isn't enough to sync charts, as it requires a `chart.id` on each chart for it to work? I didn't.

**Comment by junedchhipa** [comment]
Thank you for reporting the problem.
Yes, the docs are not perfect, and I am improving it every day.
I will update this section soon 🙌

**Comment by junedchhipa** [comment]
Created a page for it - https://apexcharts.com/docs/chart-types/synchronized-charts/
