### ISSUE TITLE
Rendering differences between apexcharts and vue-apexcharts

### ISSUE THREAD

**Issue by wujekbogdan** [apexcharts/apexcharts.js#1107]
## Codepen

https://codesandbox.io/s/vue-basic-example-5h6yl

## Explanation

> What is the behaviour you expect?

The Vue and non-vue charts initialized with the same set of options should look exactly the same.

> What is happening instead?

They look different:
  - the gradient is applied to the line rather than to the area below the line. It looks like the `type: 'area'` property is ignored.
  - the shape is different, the lines are not rounded

I just noticed these differences, but I'm afraid that the issue applies also to other options that I didn't test. I'm just starting to play with apexcharts.

// EDIT:
I took a brief look at the source code of the vue component. It looks like the `extend` method is buggy, probably it doesn't copy all the properties that are passed via `props.options`.

<img width="552" alt="apex-charts-vue" src="https://user-images.githubusercontent.com/533954/69970169-a67e1a00-1515-11ea-8dd8-66a649f2688d.png">

> What error message are you getting?

There's no error message.

**Comment by junedchhipa** [comment]
The `type` prop in the `<VueApexCharts>` element overrides the type specified in the options object.
This is intended behavior and is not a bug.
