### ISSUE TITLE
Possibility to set specific series as unselected in legend container

### ISSUE THREAD

**Issue by tforssander** [apexcharts/apexcharts.js#111]
Hi again,

I've encountered a scenario where I would like to specify specific series as unselected in the legend container. I've tried looking at the documentation and can't seem to find anything related to that, except that it is only possible to hide the legend container.

Thanks!

**Comment by junedchhipa** [comment]
You mean, if you have a multiple series chart, you want to initialize the chart by having certain series "deselected" like this?

![screen shot 2018-09-18 at 7 42 16 pm](https://user-images.githubusercontent.com/17950663/45693548-f96eea00-bb7a-11e8-8567-5d7ff7f35703.png)

Or you want that series not to show in the legend at all?

**Comment by tforssander** [comment]
Exactly, I would like to have certain series "deselected" when initialised but keep the series in the legend container, so the user can "select" it again. :)

**Comment by junedchhipa** [comment]
Well, currently ApexCharts doesn't have this option directly, but you can try a `hacky` solution.

```javascript
const legendItem = document.querySelector(".apexcharts-legend-text.apexcharts-legend-series:nth-child(1)")

legendItem.dispatchEvent(new Event('click'))
```

Will think of adding an option in config in future releases.

**Comment by pribilinskiy** [comment]
@junedchhipa Such an option would be great! We have too many items in legend and then in the tooltip and limit to e.g. 10 items by initially disabling the rest would be very useful.

**Comment by junedchhipa** [comment]
A new public method `toggleSeries('seriesName')` is added since 2.1.4 which will allow you to toggle series visibility programmatically.

You can also create a custom legend and call this method to control the series visibility.

Codepen [Demo](https://codepen.io/junedchhipa/pen/YJQKOy)
[Docs](https://apexcharts.com/docs/methods/#toggleSeries)

**Comment by jgebert** [comment]
what about in a REACT apex chart?

**Comment by reubenremy** [comment]
@junedchhipa How do we utilize this w/ React? It would be great if there was a prop on legend component that would made all the series untoggled by default. Is there a way I can accomplish this?

**Comment by beeboop** [comment]
In React, we can assess the ref

```
const chartRef = useRef();

...

<ReactApexChart ref={chartRef} ... />
```

And then
```
useEffect(() => {
  chartRef?.current?.chart.toggleSeries('seriesName');
});
```

**Comment by reubenremy** [comment]
Yea, I utilized a similar but different work around. The exec method located on ApexChart class can toggle so I toggle what I need on component mount. 

```
    state = {
        toggle1: false
    }
```

```
    onChangeHandler = e => this.setState({[e.target.id]: e.target.checked})
```

```
    disableSeriesOnMount = () => ApexChart.exec('main-chart','hideSeries', 'SERIES_NAME')
 
```

```
    seriesManager() {
        !this.state.toggle1 ? ApexChart.exec('main-chart','hideSeries', 'SERIES_NAME') :
        ApexChart.exec('main-chart','showSeries', 'SERIES_NAME')
        return
    }
```

```
    componentDidMount() {
        this.disableSeriesOnMount()
    }
```

 ```
   componentDidUpdate() {
        this.seriesManager()
    }
```

**Comment by Kartiksardhara** [comment]
You mean, if you have a multiple series chart, you want to initialize the chart by having certain series "deselected" like this?
const series = [70, 60, 50, 40, 30, 20, 10, 5, 10];
labels: ['Equity', 'Debt', 'Liqud', 'Commodities'],
![Screenshot 2023-12-29 142508](https://github.com/apexcharts/apexcharts.js/assets/129400287/bc30910b-3890-4ddc-abfc-26a9d8053f51)

Legend require only 'Equity', 'Debt', 'Liqud', 'Commodities'
i want that series not to show in the legend at all?

**Comment by sajjadali56** [comment]
Hi @tforssander, I wanted the same functionality and got the following working code for my React website. 
You have to call hideSeries or toggleSeries method on chart object for specific series. Here's my code where series is the array of objects {name, data}

```js
const options = {
...
  chart: {
    events: {
      mounted: (chartContext, config) => {
        series
          .map((x) => x.name)
          .forEach((x, i) => {
            if (i > 0) chartContext.hideSeries(x);
          });
      },
    },
  },
};


return <Chart
            options={options}
            series={clonedSeries}
            type="line"
            height={height}
          />

```
