### ISSUE TITLE
Donut Chart Fill Color Is Grey When Custom Series Colors Are Specified

### ISSUE THREAD

**Issue by codercowboy** [apexcharts/apexcharts.js#1110]
I'm having trouble getting a donut's fill color to follow my configuration. I want the sections of the donut for each series to use the series' color (or the fill color perhaps?), but instead they appear grey.

My appstack version is 3.8.4. 

Here's my configuration for an example chart:

```
var options = {
      chart: { height: 350, type: 'donut' },
      fill: { colors: ['red', 'green', 'yellow'] },
      colors: ['red', 'green', 'yellow'],
      labels: ['Offline Servers', 'Online Servers', 'Warning Servers'],
      series: [44, 55, 13]
};
```
Here's what I'm seeing:

<img width="430" alt="Screenshot 2019-12-04 17 40 23" src="https://user-images.githubusercontent.com/2514385/70193830-a6b91980-16bd-11ea-8f3e-149ea4986831.png">

I would expect the fill color for the highlighted section of the donut to be red here. What am I missing?

**Comment by junedchhipa** [comment]
You should only provide either hex or RGB/RGBA format. Color names are not accepted at the moment as stated in the [docs](https://apexcharts.com/docs/options/colors/).
