### ISSUE TITLE
How to change order of data per series on a stacked bar chart?

### ISSUE THREAD

**Issue by techuila** [apexcharts/apexcharts.js#1112]
![image](https://user-images.githubusercontent.com/15911107/70214528-8bf6ab80-1776-11ea-98dc-10d3416d96b0.png)
In this example, how can I change the order of series: marine sprite to the last or on any position on the year 2008?

**Comment by junedchhipa** [comment]
Sorry, it's not supported.  The order of stacks is always the same as the order of objects in the series array.
