### ISSUE TITLE
Is there any way to remove the empty space on the left?

### ISSUE THREAD

**Issue by wujekbogdan** [apexcharts/apexcharts.js#1114]
**Is your feature request related to a problem? Please describe.**

Ther's always some empty space on the left. Even if I don't set `yaxis.title.text` that empty space remains. 

**Describe the solution you'd like**

It would be good to be able to get rid of that empty space completely so that the left edge of the graph is aligned to the edge of the container element (the same way as the right side of the chart is)

**Describe alternatives you've considered**

I tried some CSS tricks, like negative margins but it doesn't work well because it moves the whole chart to the left.

**Additional context**

This is how it looks like:
<img width="266" alt="Zrzut ekranu 2019-12-5 o 13 52 37" src="https://user-images.githubusercontent.com/533954/70241749-78901400-1767-11ea-802b-ceb414d67e29.png">

This is how I would like it to look like:
<img width="312" alt="Zrzut ekranu 2019-12-5 o 14 00 08" src="https://user-images.githubusercontent.com/533954/70241805-93628880-1767-11ea-9ade-2e053d00475f.png">

At the moment the only solution is to disable the y-axis, but it's not a real solution.

---
**Update**
I've just noticed that a similar issue applies to the right chart's edge if there is an x-axis label that is close to the edge.

It would be perfect if we could make the chart fit perfectly to the wrapping container.

**Comment by junedchhipa** [comment]
I have pushed a commit to reduce the left spacing on the yaxis which will be released in the next version.

For right spacing, you can do

```javascript
grid: {
  padding: {
    right: 0
  }
}
```
