### ISSUE TITLE
TypeError: Cannot read property 'yRatio' of null

### ISSUE THREAD

**Issue by ManuelReyes14** [apexcharts/apexcharts.js#1117]
-What is the behavior you expect?
Rendering radar chart. I follow the review about installing and rendering a radar chart.

-What is happening instead?
Do not show the chart and show me a error about yRatio.  

-What error message are you getting?
Uncaught (in promise) TypeError: Cannot read property 'yRatio' of null apexcharts.min.js?2227:1 
    at a.value (apexcharts.min.js?2227:1)
    at i.value (apexcharts.min.js?2227:1)
    at i.value (apexcharts.min.js?2227:1)
    at i.eval (apexcharts.min.js?2227:1)
    at eval (apexcharts.min.js?2227:1)
    at new Promise (<anonymous>)
    at i.value (apexcharts.min.js?2227:1)
    at VueComponent.init (vue-apexcharts.js?1c90:123)
    at VueComponent.mounted (vue-apexcharts.js?1c90:69)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)

**Comment by junedchhipa** [comment]
Please post a working [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example to demonstrate the issue.

**Comment by ganesh-dks** [comment]
Hi, Please help me out, I face this yRatio issue, I Have verified that the data is there in the response and therefore have put all the code in success function of ajax call. I could not find how to get the response data out of ajax success function as it is becoming undefined. 

$(document).ready(function () {
        DrawCharts();
    });
    function DrawCharts() {
        //alert('return sent');
        $.ajax({
            type: "POST",
            url: "chart.php",
            data: '1',
            dataType: 'JSON', //or HTML, JSON, etc.
            success: function (response) {
                alert(response.weather[0].temperature);
                var optionstemp = {
                    chart: {
                        id: "chart",
                        height: 450,
                        width: '100%',
                        type: ' line',
                        background: '#f4f4f4',
                        foreColor: '#333'
                    },
                    series: [
                        {
                            name: 'Temperature',
                            data: [response.weather[0].temperature] // temperature data
                        }
                    ],
                    xaxis: {
                        categories: [response.weather[0].timestamp]// x axis timestamp
                    },
                    plotOptions: {
                        bar: {
                            horizontal: false
                        }
                    },
                    fill: {
                        colors: ['#f44336']
                    },
                    dataLabels: {
                        enabled: false
                    },
                    title: {
                        text: 'Temperature readings',
                        align: 'center',
                        margin: 20,
                        offsetY: 20,
                        style: {
                            fontSize: '25px'
                        }
                    }
                };
                var optionsHum = {
                    chart: {
                        height: 450,
                        width: '100%',
                        type: ' bar',
                        background: '#f4f4f4',
                        foreColor: '#333'
                    },
                    series: [{
                        name: 'Humidity',
                        data: response.weather[0].humidity// Humidity data
                    }],
                    xaxis: {
                        categories: response.weather[0].timestamp  // x axis timestamp
                    },
                    plotOptions: {
                        bar: {
                            horizontal: false
                        }
                    },
                    fill: {
                        colors: ['#f44336']
                    },
                    dataLabels: {
                        enabled: false
                    },
                    title: {
                        text: 'Humidity readings',
                        align: 'center',
                        margin: 20,
                        offsetY: 20,
                        style: {
                            fontSize: '25px'
                        }
                    }
                };


                const tempchart = new ApexCharts(document.querySelector('#temperature'), optionstemp);
                const humchart = new ApexCharts(document.querySelector('#humidity'), optionsHum);
                tempchart.render();
                humchart.render();
            }
        });
    }

**Comment by junedchhipa** [comment]
@ganesh-dks  What is in your `[response.weather[0].temperature] ` and `[response.weather[0].timestamp]`?

**Comment by ganesh-dks** [comment]
> @ganesh-dks What is in your `[response.weather[0].temperature] ` and `[response.weather[0].timestamp]`?

these are arrays

**Comment by ganesh-dks** [comment]
I put alert msgs and checked, data is coming in success function

**Comment by apjunzhisheng** [comment]
@ganesh-dks  Hi, just wondeirng did you fix this problem, since I face the same issue and I have no idea what going on with this.

**Comment by mohamad68** [comment]
I have this issue to 
I am using Vue.js
below is the error code:
Uncaught (in promise) TypeError: Cannot read property 'yRatio' of null
    at a.value (apexcharts.min.js?90ff:1)
    at i.value (apexcharts.min.js?90ff:1)
    at i.value (apexcharts.min.js?90ff:1)
    at i.eval (apexcharts.min.js?90ff:1)
    at eval (apexcharts.min.js?90ff:1)
    at new Promise (<anonymous>)
    at i.value (apexcharts.min.js?90ff:1)
    at eval (apexcharts.min.js?90ff:1)

**Comment by baikalbear** [comment]
I use vue-apexcharts and I had the same error when i had unwanted space in value of type parameter.
<VueApexCharts type=**"donut "** height="397" :options="chartOptions" :series="series"></VueApexCharts>
In this case you just need to remove this space.

**Comment by ganesh-dks** [comment]
> @ganesh-dks Hi, just wondeirng did you fix this problem, since I face the same issue and I have no idea what going on with this.

Nope, I ended using other library.

**Comment by Dieselhead** [comment]
Like the comment by @bearbaikal suggests, this error is shown if you provide an invalid type.

**Comment by nvurgaft** [comment]
It happened to me in v3.27.0 when I accidentally passed a `null` as a chart type
