### ISSUE TITLE
Is it possible to show different labels in different yaxis in radar chart

### ISSUE THREAD

**Issue by xinjing-z** [apexcharts/apexcharts.js#1120]
I want to show different labels in different y-axis, because in different y-axis, the data definitions are different. 
In the formatter document: function(val, index), the index is the tick index, is the yaxis index available? so that can return different labels according to yaxis index and tick index. 
Thanks!

**Comment by junedchhipa** [comment]
Using the `index`, you can decide what label you want to display using formatter.
There are no multiple y-axes in the radar chart, so the yaxis index will not be available there.
Hope this helps!
