### ISSUE TITLE
Allow filtering series using filterSeries method

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1124]
A method like this would be incredibly useful

```
ApexCharts.exec( chartId, 'filterSeries, series => {
     return series.filter( ({ someParameter }) => someParameter === 'March' )
})
```
The series passed in would be the original series passed into the chart, or if it's easier, just the current series it's displaying: thought this would make toggling impossible without _readding_ the original points back in

This arose because I have charts that have multiple series, and I need to toggle multiple of them at once. A filter would be incredibly useful.

Lots of methods have a config object passed in, so I don't think it would be hard to pass in the series, or even a config object to a method like this.

**Comment by ThinkSalat** [comment]
I think you just have to add the following to src/apexcharts.js

```
/**
 * Allows users to filter series
 * provides the original series and allows user to return which series should be displayed
 * @param {function} callback - callback which provides the original series
 */

 filterSeries(callback) {
	 const originalSeries = this.w.config.series.slice()
	 this.resetSeries(false)
	 this.revertDefaultAxisMinMax()
	 const filteredSeries = callback(originalSeries)
	 return this._updateSeries(filteredSeries)
 }
```

**Comment by ThinkSalat** [comment]
I've gone ahead and added this in my PR which I just submitted.

**Comment by junedchhipa** [comment]
Filtering series this way will cause inconsistencies with the legend.
As there is a lot of data that is updated when a series is toggled/untoggled.

Hence, filtering out all the series and just displaying 1 will also need an update to the legend code.

Closing for now, will come back again once I find a better alternative.
