### ISSUE TITLE
problems with legend position

### ISSUE THREAD

**Issue by FunkiR** [apexcharts/apexcharts.js#1125]
how can this be fixed?

![Screenshot_20191210_145320](https://user-images.githubusercontent.com/32128554/70523594-d56f3e00-1b5c-11ea-80ab-7b502bafa43a.png)
![Screenshot_20191210_145249](https://user-images.githubusercontent.com/32128554/70523602-d902c500-1b5c-11ea-8541-2669ad1a1076.png)

**Comment by junedchhipa** [comment]
Please create a working codepen example to easily reproduce it.

**Comment by FunkiR** [comment]
done [https://codepen.io/funkir/pen/povyOPX](https://codepen.io/funkir/pen/povyOPX)
