### ISSUE TITLE
removeAnnotation doesn't work ApexCharts.exec

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1126]
## Codepen

[codepen here](https://codepen.io/TalasNwhas/pen/bGNpgbq)

Click test. it should toggle the annotation on and off. Instead, it removes the label but not the line.

**Comment by ThinkSalat** [comment]
I added an updateAnnotations function in a PR which should allow people view the current annotations and choose which ones they want to keep and add any they like.

**Comment by junedchhipa** [comment]
I have fixed the bug in `removeAnnotation` method.
