### ISSUE TITLE
ReferenceError: Cannot access 'isReversed' before initialization

### ISSUE THREAD

**Issue by FunkiR** [apexcharts/apexcharts.js#1129]
tooltip/Intersect.js line 199

![Screenshot_20191212_133825](https://user-images.githubusercontent.com/32128554/70700808-bf8c8500-1ce4-11ea-8175-bc674a741a47.png)

**Comment by ThinkSalat** [comment]
This is like explained in beginner's programming tutorials. You're trying to access a variable which hasn't been declared yet. You need to change the order of your logic.

**Comment by FunkiR** [comment]
it logic was in my package version (3.10.1)

**Comment by ThinkSalat** [comment]
My bad, I thought this was your own.

**Comment by junedchhipa** [comment]
Sorry, this was a silly mistake by me in the previous version which is already fixed.
The new version will be out in a few days.
