### ISSUE TITLE
chart drawing Wrong 

### ISSUE THREAD

**Issue by duckhee** [apexcharts/apexcharts.js#1131]
![nmpzc0ap](https://user-images.githubusercontent.com/22145663/70789306-1a51d980-1dd6-11ea-9d4a-3ec9c7580547.png)

chart show like this data. how to delete line? line does not have data.

**Comment by junedchhipa** [comment]
Please show what data you are using.
It seems you are inputting a reverse datetime series.

**Comment by duckhee** [comment]
> Please show what data you are using.
> It seems you are inputting a reverse datetime series.

not good english skilll so, how to explain this situation.  i used data in mysql. and then get all data and show this chart. use data. and then split comma . use front end double for and push [x,y] x data is dateTime , y data some value . 
you think is x data is used dateTime reverse , but console log is now reverse data show some data here.
![image](https://user-images.githubusercontent.com/22145663/70859216-4ba3e400-1f53-11ea-9c59-1eee7e15d835.png)

**Comment by junedchhipa** [comment]
Please create a [codepen demo](https://codepen.io/apexcharts/pen/xYqyYm) to reproduce the issue.

**Comment by duckhee** [comment]
oh I'm sorry some data is overlapping. I found database data overlap

thank you for you are help

**Comment by junedchhipa** [comment]
No problems!
