### ISSUE TITLE
Tooltip hide non-collapsed data mistakenly when using stacked barchart with shared + inverseOrder tooltip

### ISSUE THREAD

**Issue by WiNloSt** [apexcharts/apexcharts.js#1133]
## Codesandbox

https://codesandbox.io/s/stacked-bar-chart-inverse-tooltip-order-bug-bm390

## Explanation
This bug happens if you use the combination of `stacked` bar chart + `tooltip.shared` = true + `tooltip.inverseOrder` = true. And when you toggle some data set off and hover over the bar chart. I'll not show any data in the tooltip at all.

#### Not reverse tooltip (default)
![Screen Shot 2562-12-13 at 01 48 21](https://user-images.githubusercontent.com/1937582/70798322-32772800-1dd9-11ea-87bf-b8ee943193aa.png)

#### tooltip.inverseOrder = true
![Screen Shot 2562-12-13 at 18 49 12](https://user-images.githubusercontent.com/1937582/70798354-4a4eac00-1dd9-11ea-8d23-57e9577235c7.png)

From my digging, I found out that the problem lies in the function [`DOMhandling`](https://github.com/apexcharts/apexcharts.js/blob/0ee4c5ee3f69818acf94bcc5a43dc7dded7e600f/src/modules/tooltip/Labels.js#L191)

from this function call, we pass `t` as the index of the label without inversing so in this case, the order of looping is inverse so it starts the loop from series-2 (disabled) then series-1.

https://github.com/apexcharts/apexcharts.js/blob/0ee4c5ee3f69818acf94bcc5a43dc7dded7e600f/src/modules/tooltip/Labels.js#L119-L134

then the function runs to here. It checks if it found `collapsedSeriesIndices` (contains 1 because non-inverse series-2 data is 1) containing the current index or not. We got the index of 1 with the series-1 data because the order is inverse. So it matches then it also set the display style to `none`

https://github.com/apexcharts/apexcharts.js/blob/0ee4c5ee3f69818acf94bcc5a43dc7dded7e600f/src/modules/tooltip/Labels.js#L261-L266

- What is the behavior you expect?
The tooltip should show the data that's not toggled off.

- What is happening instead?
The tooltip doesn't show any data at all.

- What error message are you getting?
no error message

**Comment by junedchhipa** [comment]
Thanks for reporting, I confirm the issue.
Will be addressed soon.
