### ISSUE TITLE
legend.horizontalAlign doesn't do anything

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1135]
Here's how the different options look

right:
![Screen Shot 2019-12-13 at 2 00 51 PM](https://user-images.githubusercontent.com/31082405/70835144-09db3800-1db1-11ea-84f8-fd42dd6411e8.png)

left:
![Screen Shot 2019-12-13 at 2 00 29 PM](https://user-images.githubusercontent.com/31082405/70835145-09db3800-1db1-11ea-99c7-41cadfb54c00.png)

center:
![Screen Shot 2019-12-13 at 2 00 08 PM](https://user-images.githubusercontent.com/31082405/70835146-09db3800-1db1-11ea-91d1-cefccaa4b2a4.png)

I haven't found that this option actually does anything.

**Comment by junedchhipa** [comment]
I tried the `legend.horizontalAlign` property and it works fine as shown below

legend.horizontalAlign = 'center'
![Screen Shot 2019-12-14 at 11 44 28 AM](https://user-images.githubusercontent.com/17950663/70844458-53865a00-1e67-11ea-988b-38dcd8ba3119.png)

legend.horizontalAlign = 'left'
![Screen Shot 2019-12-14 at 11 44 56 AM](https://user-images.githubusercontent.com/17950663/70844461-5b45fe80-1e67-11ea-8db5-a91a9bc6c93d.png)

legend.horizontalAlign = 'right'
![Screen Shot 2019-12-14 at 11 44 45 AM](https://user-images.githubusercontent.com/17950663/70844465-6436d000-1e67-11ea-8989-69ad1ffe7969.png)

Can I see your code?

**Comment by ThinkSalat** [comment]
Is there a way to stack the legend vertically? I'm trying to align each individual item to the left or right, not the legend container as a whole.

**Comment by junedchhipa** [comment]
To make it easier to work with the legend, they are drawn with plain HTML/CSS
You can customize the legend by targetting the .apexcharts-legend class.
If you inspect legend in the developer options, you will see all the classes assigned to its children too.
