### ISSUE TITLE
Annotation stroke width configuration

### ISSUE THREAD

**Issue by rtybanana** [apexcharts/apexcharts.js#1137]
I can't find any way to configure the stroke width of the annotations. Currently I am having to draw multiple annotation lines next to one another to create a thicker line; however, this is not ideal because the annotation is used as a marker which is updated often, and the creation of multiple lines is less efficient.

Have I just missed it in the docs or can this be added?

Thanks,
Rory

**Comment by junedchhipa** [comment]
Yeah, I missed this basic property.
Just added it, will be available in the next release.

**Comment by rtybanana** [comment]
Many thanks

**Comment by rtybanana** [comment]
Hi @junedchhipa I'm having a different problem with annotations now which may be related to this addition.

The annotations.xaxis[...].x value isn't lining up with the datapoints on the chart, it appears instead to simply be a pixel value. I'm having to multiply and offset by an amount for the annotation to line up above my columns. Here is an image demonstrating the issue:

![image](https://user-images.githubusercontent.com/20663297/71683754-5223bf80-2d8b-11ea-961f-921177d7a0ae.png)

The annotation should appear directly above the slider below but it appears far left.
Thanks in advance for your help.

**Comment by junedchhipa** [comment]
Please create a codepen demo for me to reproduce the issue.

**Comment by rtybanana** [comment]
https://codepen.io/rtybanana/pen/gOboGrd

Click on the chart to increase the x value of the annotation by 5. As I understand it the x value should be the value on which to draw the annotation, but it appears to be something more similar to a pixel offset from the left of the chart.

Sorry for taking a while to get this CodePen sorted.

**Comment by junedchhipa** [comment]
The behavior is correct in your codepen (as tested on v3.15.2).

You have provided string categories on the xaxis. So, if you provide integer in xaxis annotation, it will place the annotation based on the pixel, not the actual value.
For category xaxis annotations, you should provide string in the `annotations.xaxis.x` property.

In your same demo, if you provide `x: 'Oct'`, it places annotation on the correct place.

If you want annotation based on numeric x-axis, convert the xaxis to a numeric type `xaxis.type: 'numeric'`.

**Comment by yuriv15** [comment]
Sorry, I'm having the same issue. I can't make the annotation line thicker. Can you help me please?

**Comment by osmanyasircankaya** [comment]
> Sorry @junedchhipa, I'm having the same issue. I can't make the annotation line thicker. Can you help me please?

you can use `borderWidth?: number`
check this: https://github.com/apexcharts/apexcharts.js/commit/d93f68b2e778e426947e6fd42a2532b4714d6ca0

**Comment by vLabayen** [comment]
@junedchhipa, borderWidth does not seem to be working in yaxis annotations when y2 is provided.
