### ISSUE TITLE
Chart height changes on updateSeries

### ISSUE THREAD

**Issue by ryryan** [apexcharts/apexcharts.js#1139]
Oddly the chart height changes when using `updateSeries`. See this [CodePen ](https://codepen.io/RyRyan/pen/vYEXwxd)for an example.

I can't understand why.

**Comment by junedchhipa** [comment]
If you insert the chart directly into `<body>` element, you will have to provide height to the `<body>`

```css
body {
  height: 90vh
}
```

Or, an another alternative is to wrap the chart in some parent element.
```html
<div id="wrap">
  <div id="chart"></div>
</div>
```

There is a bug when the chart is appended directly to the `body` element which doesn't have any height.

Your update [codepen example](https://codepen.io/apexcharts/pen/gObLayP)
