### ISSUE TITLE
Exported SVG contains unwanted dotted line

### ISSUE THREAD

**Issue by nevstyles** [apexcharts/apexcharts.js#1140]
When we export a chart to SVG, the resulting graphic contains a dotted line representing where the cursor last hovered over the chart plus sometimes a solid line where we've clicked the Download link, for example:

![ChartLines](https://user-images.githubusercontent.com/58939531/70903943-0259a000-1ff8-11ea-9010-1e27422c9325.png)

Is this a known issue or is there an obvious setting I am missing to stop these appearing?

Regards,
Neville

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.
