### ISSUE TITLE
Advanced timeline chart does not work as expected

### ISSUE THREAD

**Issue by ccarrascoml** [apexcharts/apexcharts.js#1144]
Codepen: https://codepen.io/ccarrascoml/pen/abzBMYG

I expect that each row has a different color and it's labels are referred to the row itself (e.g. the D for the D row, the E for the E row...).

Instead, as you can see, **rows D and E have a tooltip pointing to B, and they have the B color too**.

Am I doing wrong or is it a bug?

Thank you in advance

**Comment by junedchhipa** [comment]
This feature was released very recently, and it might be a bug.
I will check soon.

**Comment by junedchhipa** [comment]
Thanks, @sergkop for fixing it.

**Comment by ccarrascoml** [comment]
@junedchhipa I have tested the exact same case with the PR changes from @sergkop and the issue keeps happening.

Although the hover effect has disappeared.

**Comment by junedchhipa** [comment]
Here is the screenshot of your codepen after applying the latest changes.
![Screen Shot 2019-12-18 at 5 08 23 PM](https://user-images.githubusercontent.com/17950663/71083444-0e409000-21b9-11ea-8164-66ca6555fde7.png)

The fixes will be released soon (most probably this weekend)
