### ISSUE TITLE
Add max value for tickAmount: 'dataPoints'

### ISSUE THREAD

**Issue by drewrawitz** [apexcharts/apexcharts.js#1145]
Is there a way to specify a max value when I use:

```
xaxis: {
  tickAmount: 'dataPoints',
},
```

On some filters, I have way too many months to where the months in the X-axis get truncated and it looks messy. I'd like to have a maximum of 6 items.  If I set the `tickAmount` to 6, then that means I'll always get 6. I have some filters where only 3 months might show up, and so for those, I'd want to show 3.

I tried adding a computed property (I'm using Vue) to calculate the proper `tickAmount`, something like this:

```
tickAmount() {
  const MAX = 6;
  const count = this.visibleMonths.length;

  if (count > MAX) {
    return MAX;
  }

  return count || 0;
},
```

And that works great, but I end up losing my animations.  Here's a quick visual of what happens when I use that computed property: https://take.ms/8dy2T
If I take it out and use `'dataPoints'` or an arbitrary number, the animations work just fine.

Any ideas? Thanks so much!

**Comment by junedchhipa** [comment]
The way you have done it should work just fine.
Not sure, why the animation is lost.
A full working codepen/codesandbox (in Vue) would be helpful to debug.

**Comment by junedchhipa** [comment]
I tried it this way and it worked fine. You should move the whole chartOptions to `computed`

```javascript
computed: {
  tickAmount: function() {
    return 2
  },
  chartOptions: function() {
    return {
      xaxis: {
        type: 'category',
        tickAmount: this.tickAmount
      },
      tooltip: {
        shared: false,
        y: {
          formatter: function(val) {
            return (val / 1000000).toFixed(0)
          }
        }
      }
    }
  }
},
data: {
  series: [
    {
      name: 'XYZ MOTORS',
      data: dates
    }
  ]
}
```
