### ISSUE TITLE
Too many items in legend leads to broken layout 

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#115]
When `legend.position` is set to `right` and there are many items/categories provided the layout is broken

![image](https://user-images.githubusercontent.com/3078595/45744653-bc9d0480-bc07-11e8-8875-c166add7766f.png)

If there's no way to make a scrollable list in **SVG** then legend should be drawn via **HTML**

**Comment by junedchhipa** [comment]
Have you tried to make the legends smaller using legend formatter function? 

```javascript
legend: {
  formatter: function(val, opts) {
    return val.substring(0, val.indexOf("competitor-forms-windows-xp"))
  }
}
```

Another option is - for smaller screen sizes, you can put the legends below chart using [responsive](https://apexcharts.com/docs/responsive/) config.

I thought about drawing legend with HTML, but it will require a major code rewrite.

**Comment by pribilinskiy** [comment]
@junedchhipa truncating is not an option here and having a hundred of items will span the legend to even more columns eventuall hidden when not fit into chart's container

And there's also another bug that is related to this chart is when `xaxis.type` is `datetime` then only the hovered point's data is shown
![image](https://user-images.githubusercontent.com/3078595/45750064-5ec3e900-bc16-11e8-9549-e430d94b8828.png)

**Comment by pribilinskiy** [comment]
Looks like I'll have to do the custom filtering UI completely on my own :) like depicted on this mockup

![image](https://user-images.githubusercontent.com/3078595/45750279-11944700-bc17-11e8-822f-e16da5132289.png)

**Comment by junedchhipa** [comment]
@pribilinskiy Yeah, I think - you have a pretty interesting use case of so many series to show in 1 chart. 

Regarding the bug which you noticed (hovered data point), can you please create a codepen example for me to reproduce quickly?

Thanks

**Comment by pribilinskiy** [comment]
Added as separate issue https://github.com/apexcharts/apexcharts.js/issues/115
