### ISSUE TITLE
Tick Amount Doesn't work in Heatmap

### ISSUE THREAD

**Issue by lunchboxav** [apexcharts/apexcharts.js#1151]
## Codepen

https://codesandbox.io/s/heatmap-debug-xqngn

## Explanation

The tickAmount property on x-axis seems to be not working no matter how I set them up. I've used both the numeric and category type, but still none of them are working.

Some snippet that might help:
```
    this.state = {
      options: {
        xaxis: {
          type: 'category',
          tickAmount: 2
        },
      },
      series: [
        {"name":"0-99","data":[{"x":"10.20","y":11},{"x":"10.21","y":0},{"x":"10.22","y":0},{"x":"10.23","y":0},{"x":"10.24","y":0},{"x":"10.25","y":0},{"x":"10.26","y":0},{"x":"10.27","y":0},{"x":"10.28","y":0},{"x":"10.29","y":0},{"x":"10.30","y":0},{"x":"10.31","y":0},{"x":"10.32","y":0},{"x":"10.33","y":0},{"x":"10.34","y":0}]},
      ]
    };
```

**Comment by junedchhipa** [comment]
If you want to forcefully overwrite the tickamount for heatmap charts, you can use

```javascript
xaxis: {
  categories: ['x2', 'x3', 'x4', 'x5']
}
```
Now, the number of ticks will be equal to the number of categories.

Note: The xaxis tooltip will not work in this case if you provide less number of categories than the actual number. You might have to turn that off.

**Comment by BranthiBaulsen** [comment]
Hi,

I couldn't manage to apply tickAmount for Y-Axis. TickAmount is not working on Y-axis.

I have date values : (00:00, 01:00,02:00....23:00) . I want to use tick amount 4. So that only 00:00-04:00-08:00 is visible. How can I do it ? Is this possible ?

**Comment by imballinst** [comment]
hey @BranthiBaulsen—I think we can use `yaxis.labels.formatter` in that case (https://apexcharts.com/docs/options/yaxis). As noted in the doc:

```
yaxis: {
  labels: {
    /**
    * Allows users to apply a custom formatter function to yaxis labels.
    *
    * @param { String } value - The generated value of the y-axis tick
    * @param { index } index of the tick / currently executing iteration in yaxis labels array
    */
    formatter: function(val, index) {
      return val.toFixed(2);
    }
  }
}
```

In that case, probably what you want is to exclude elements that do not contain 00:00, 04:00, 08:00. Let me know if this helps!
