### ISSUE TITLE
rangeBar bars overlap

### ISSUE THREAD

**Issue by thellimist** [apexcharts/apexcharts.js#1153]
@junedchhipa 

Using the demo here, adding the following Test section to Bob, will make the bars looked merged

```
        {
          x: 'Test',
          y: [
            new Date('2019-03-08').getTime(),
            new Date('2019-03-12').getTime()
          ]
        },
```
Just in between two ranges. As you can see in the picture it looks like they are merged.

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/6690196/70861351-857ee580-1f67-11ea-8507-7ebf74fc0e53.png">

If there are any overlapses, it should show in a new row

**Comment by junedchhipa** [comment]
What if there are more than 2 items of the same row that overlaps? 
Creating n number of new rows for each overlap doesn't seem right.

**Comment by thellimist** [comment]
>  Creating n number of new rows for each overlap doesn't seem right.

Wonder what's your thought process? In my opinion losing visibility of data is worse than slightly more data. 

```
// Method 1
11111    222222
    3333333
```

```
// Method 2
11111    
         222222
    3333333
```

```
// Method 3
111133333332222
```
where each number represents a bar and it's length. In my opinion Method 1 > Method 2 > Method 3. Currently, rangeBar uses Method 3.

**Comment by junedchhipa** [comment]
Sure, I was just asking for an opinion.
I was thinking of squeezing everything in 1 row but that will result in loss of data.

Method 1 looks good to me, I will try that one.

**Comment by sergkop** [comment]
IMHO, it's a question of whether it should be the library or developer who handles such cases. I also see problem of dealing with such overlaps, but in my case I would prefer the overall chart to look nice (with the number rows being defined by the chart options and not changing from one series to another).

If method 1 or 2 gets implemented I think there should still be an option to use method 3.

**Comment by junedchhipa** [comment]
Yes, giving an option in the config whether to overlap the bars or to split those bars into two is a good way to let the develop control it.

Here is what I am thinking
![Screen Shot 2019-12-20 at 8 24 05 PM](https://user-images.githubusercontent.com/17950663/71262899-cc554c80-2366-11ea-8906-931eeff48432.png)

It looks a bit ugly but the data is not lost.

Adding a new row for the overlapping bars will require a good amount of rewriting the range-bar module.

**Comment by julianmcolina** [comment]
+1 for method 1 or 2

**Comment by thellimist** [comment]
Hi, may I ask when will this be released?

**Comment by thellimist** [comment]
https://codepen.io/thellimist/pen/mdypaOO

With commit https://github.com/apexcharts/apexcharts.js/commit/2214bfb6bc0304334bd2773aa0f0047e7ea54a63 empty data values are broken.

```
series: [
          {
            name: 'Bob',
            data: []
          },
          {
            name: 'Joe',
            data: [
              {
                x: 'Design',
                y: [
                  new Date('2019-03-02').getTime(),
                  new Date('2019-03-05').getTime()
                ]
              }
          }
      ]
```

Would not work anymore

**Comment by ccarrascoml** [comment]
Hello. This change in the rangeBar bars has completely broken how my layout was showing the information.

The overlap was desirable for me.

Is there an option to toggle the previous behaviour? This is the method 3 that @thellimist commented. If not, would it be hard to add one?

Thank you in advance.

**Comment by junedchhipa** [comment]
@ccarrascoml Sure, that's a valid point.
As @sergkop suggested, there needs to be an option to toggle the behavior.
I will address it soon.

**Comment by Irianne** [comment]
Bonjour,
Avec la demo du site sur le Timeline multiple range series, cela ne me donne pas le rendu souhaité au niveau des barres.
Par exemple pour Design, avec 2 dates différentes pour bob, cela ne me met pas 2 barres dans Design mais me met ma première date dans design et la 2eme dans code. (quand j'ai les 3 personnes d'active dans la légende).
Et quand jaffiche juste Bob, cela me créer 2 lignes Design au lieu que les barres soient rassemblés sur la même ligne, est ce normal ?

**Comment by Gari-sincere** [comment]
I am not sure how to apply this toggle.  Updating the following in my chart options object is not doing it.

plotOptions.rangeBar.allowOverlap

**Comment by pawanvivekananda** [comment]
This bar.rangeBarOverlap is not working.

Can u share an example.

**Comment by junedchhipa** [comment]
`plotOptions.bar.rangeBarOverlap: false`
![Screenshot 2020-10-03 at 6 04 43 PM](https://user-images.githubusercontent.com/17950663/94991792-efbe5080-05a2-11eb-9833-44c7e2ea3049.png)

`plotOptions.bar.rangeBarOverlap: true`
![Screenshot 2020-10-03 at 6 05 22 PM](https://user-images.githubusercontent.com/17950663/94991802-049ae400-05a3-11eb-9c71-09beee26057a.png)

**Comment by pawanvivekananda** [comment]
Can we get graph in single row for like method 3 (111133333332222) but the above graph looks like Method 2.

If that kind of graph is already available can u please the codepen link?

**Comment by pawanvivekananda** [comment]
Any inputs on how to configure graph for method 3?
