### ISSUE TITLE
Eventlist class field missing when used inside webcomponent/shadowDOM

### ISSUE THREAD

**Issue by chris-kruining** [apexcharts/apexcharts.js#1156]
Sorry I can't provide a codepen

I have the issue that when I use the lib inside of a webcomponent / shadowDOM that I run into a couple of issues:
- I need to wrap my chart element within another element as otherwise the lib encounters an issue with `ShadowRoot` not being an `Element` and therefor can't be used in `getComputedStyle` ([apexcharts.esm.js:27634](https://unpkg.com/browse/apexcharts@3.7.0/dist/apexcharts.esm.js))
- I needed to copy styling to a separate css file so it can be included in the shadowDOM's scope. this is already mentioned in #238 however I did not find a solution
- This one I have no clue to why it doesn't work inside shadowDOM, but does normaly. on [apexcharts.esm.js:28369](https://unpkg.com/browse/apexcharts@3.7.0/dist/apexcharts.esm.js) the event list does not exist, I can solve this by declaring it in the constructor.

I know I don't provide a reproducable environment, however I am very new to this lib. Therefor the possibility of me doing something wrong aren't small either, but I hope I provided enough information as to give a clue to what goes wrong

**Comment by junedchhipa** [comment]
The eventlist array exists in the latest version 3.11.1 - [apexcharts.js](https://unpkg.com/browse/apexcharts@3.11.0/dist/apexcharts.js)

Also, the CSS as you mentioned is included separately file - https://cdn.jsdelivr.net/npm/apexcharts@3.11.1/dist/apexcharts.css

Let me know if you face issues with the latest version too.

**Comment by chris-kruining** [comment]
awesome, latest update works flawlessly! Thanks!
