### ISSUE TITLE
grid: only show base-line instead of all grid-lines

### ISSUE THREAD

**Issue by KirderfOvane** [apexcharts/apexcharts.js#1159]
![apexchart_gridproblem](https://user-images.githubusercontent.com/49250135/71309901-ae8ef280-240d-11ea-84ff-786c4fd893cd.jpg)

I can't seem to find a way to hide(red crosses) all but the base-line(blue arrow) on the x-axis. 

I wan't an option under 

`grid: { xaxis:  {
                                                   lines: { 
                                                          show: true ,
                                                          startonly: true 
                                                          } 
                                                    }`
Alternatively unhinge lines from tickAmount under yaxis. Setting tickAmount to 0 can show only
base-line .
My temporary solution is for the moment to hide grid, set sparkline: {enabled: false} and 
use axisBorder with a manual offsetY so it fits into the 0-line-pos.
![apex_tempsolution](https://user-images.githubusercontent.com/49250135/71310212-b486d280-2411-11ea-91e7-cbcb88c5bbde.jpg)

**Comment by junedchhipa** [comment]
The manual offset position will not work correctly if the value in the yaxis changes.

So, here is what I suggest:
- Use annotations and draw a line on 0 value.
- Turn off all the xaxis and yaxis line

```javascript

annotations: {
  yaxis: [
    {
      y: 0,
      strokeDashArray: 0,
      borderColor: "#333",
      fillColor: "#c2c2c2",
      opacity: 0.8,
      offsetX: 0,
      offsetY: 0
    }
  ]
},
xaxis: {
  axisBorder: {
    show: false
  },
  axisTicks: {
    show: false
  },
},
grid: {
  yaxis: {
    lines: {
      show: false
    }
  }
}
```

Here is a full [codepen example](https://codepen.io/apexcharts/pen/oNgwvBK)

![Screen Shot 2019-12-24 at 1 38 23 PM](https://user-images.githubusercontent.com/17950663/71402373-aecbff80-2652-11ea-8107-166e493d259f.png)

**Comment by Baracoj** [comment]
It will better if you hide the value of the y axis
