### ISSUE TITLE
Do not hide xaxis when all series are hidden

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#116]
Hello,

xaxis becomes hidden when I toggle all series off as demonstrated [here](https://apexcharts.com/javascript-chart-demos/line-charts/null-values/) but I have some series that have just null values and xaxis gets displayed again only if I re-enable at least one series with not-all-null data which might be confusing for user so I want to have xaxis (ticks) displayed at all times. How to do that, please?

Thanks.

**Comment by junedchhipa** [comment]
Ok, I have fixed this in https://github.com/apexcharts/apexcharts.js/commit/1a4954cc7ffc5b84fc1b0bb3c860e8aa0b99a04a

The x-axis will be visible even when all series are collapsed in the next version

**Comment by pnemi** [comment]
Thanks. By the way, you don't build dist js files? Right now you fixed it but I see dist not updated.

**Comment by junedchhipa** [comment]
I update the dist only when I release a new version.
You should expect the next patch version in a couple of hours :)
