### ISSUE TITLE
Stacked bar columns and area chart

### ISSUE THREAD

**Issue by mcarpinter** [apexcharts/apexcharts.js#1160]
Hi. I need to create a stacked bar column at 100%, and also have an area chart, where each point of the line will be the dots where where one bar ends and the other starts (for example, if I have one red bar at 23%, and one bar at blue on 77%, the dot line would be at 23%.

**Describe alternatives you've considered**
I tried a stacked with lines, but I need to set the background below the line and I could not find out how to do it. If this is possible, it would be a nice solution. 
Currently, I also used the stacked with bars and lines, but when adding stacktype 100%, it does not work well.

![grafica1](https://user-images.githubusercontent.com/49532178/71375432-f7c17c80-259c-11ea-9e33-ef164de63d32.png)

**Comment by junedchhipa** [comment]
Sorry, stacked bar and line in the same chart is not possible currently.
