### ISSUE TITLE
tooltip y formatter invoked w/ different params, missing value

### ISSUE THREAD

**Issue by brandonburkett** [apexcharts/apexcharts.js#1161]
Hello,

Unsure if this is vue specific or not, but passing in the following `tooltip` options to a simple donut chart:
```
tooltip: {
  enabled: true,
  y: {
    formatter(val, opts) {
      console.log('formatter invoked', val, opts)
      return val
    }
  }
},
```

I can see the formatter called twice (on hover), BUT on one call, `val` (first param) is passed in, and the next val is undefined and `opts` (second param) is passed in (has series, seriesIndex, etc).

I noticed it because I am trying to use series, seriesIndex for formatting, but it is not set on every other function call.

---
**versions**
"apexcharts": "3.10.1",
"vue-apexcharts": "1.5.1",

**Comment by junedchhipa** [comment]
You're right.
It was invoked twice, fixed it.
