### ISSUE TITLE
Percent value for stacked chart not being displayed for small height

### ISSUE THREAD

**Issue by Xavier59** [apexcharts/apexcharts.js#1162]
I have trouble displaying the percent value.

With height = 120px :  

![image](https://user-images.githubusercontent.com/10245003/70752487-02754980-1d33-11ea-863a-ff3cae357cee.png)

With height = 300px :  

![image](https://user-images.githubusercontent.com/10245003/70752462-f5585a80-1d32-11ea-997c-5238e0346881.png)

Since width is the same, it should display percent the same way and not depends of height.

**Comment by junedchhipa** [comment]
You're right.
It was dependent on height instead of width.
Thanks for reporting, fixed it.

**Comment by abensoft-mauricio** [comment]
I'm having the same problem is there any solution?
@junedchhipa
