### ISSUE TITLE
Horizontal Bar Chart not working

### ISSUE THREAD

**Issue by patricknazar** [apexcharts/apexcharts.js#1166]
I've forked the stackblitz demo and made it a bar chart with the horizontal setting and it doesn't apply. I've looked at the code and I can't see why this wouldn't work

[Horizontal Bar Chart Demo](https://stackblitz.com/edit/ngapexcharts-demo-eiz426?file=src/app/app.component.html)

Any idea what's going on?

**Comment by junedchhipa** [comment]
Thanks for reporting. 
FIxed it in the last commit. The issue was in the core apexcharts lib, hence transferred it here.
