### ISSUE TITLE
Incomplete legend when xaxis.type is datetime

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#117]
When `xaxis.type` is `datetime` then only the hovered point's data is shown

![image](https://user-images.githubusercontent.com/3078595/45750064-5ec3e900-bc16-11e8-9549-e430d94b8828.png)

**Comment by pribilinskiy** [comment]
Example https://codepen.io/anon/pen/bxOExB

**Comment by junedchhipa** [comment]
You have to turn on `shared` tooltip property to show all the series's data.

```javascript
tooltip: {
  shared: true
}
```

**Comment by pribilinskiy** [comment]
@junedchhipa also `tooltip.x.title.formatter` is seems to be ignored. Updated example

**Comment by junedchhipa** [comment]
The shared tooltip will only work correctly when all series has same "x" values. (I updated the docs stating it recently - https://apexcharts.com/docs/options/tooltip/#shared)

In your example, you have a missing "x" value in the first series.

To make the shared tooltip work correctly, you can pass a `y: null` value for a dataPoint where you don't have any data for that datetime. I have updated your example by including the missing "x" value and giving `y: null` for that particular point.

https://codepen.io/apexcharts/pen/YOdEee

Regarding, `tooltip.x.title.formatter`, it was fixed just a couple of hours ago. Will be working fine in the next release.

**Comment by pribilinskiy** [comment]
@junedchhipa Great! 
This issue can be closed then
