### ISSUE TITLE
Logarithmic Scale on Category Chart

### ISSUE THREAD

**Issue by ftischhauser** [apexcharts/apexcharts.js#1175]
## Codepen

https://codepen.io/ftischhauser/pen/rNaYBoJ

## Explanation

- What is the behavior you expect?
_All series should be drawn on the chart by default. The y-axis should resize to fit all data values._
- What is happening instead?
_Only the first series is drawn correctly._
- What error message are you getting?
_None_

Thanks for looking into this!

**Comment by junedchhipa** [comment]
Thanks for reporting.
Fixed it.
