### ISSUE TITLE
CSV multi series export

### ISSUE THREAD

**Issue by Redirts** [apexcharts/apexcharts.js#1177]
**Is your feature request related to a problem? Please describe.**
CSV export

**Describe the solution you'd like**
When exporting CSV on a chart with multi series, all the series are written sequentially
It would be nice to have the series values appear in a separate column.

Also date column should be formatted to a readable date format if possible.

**Additional context**
Currently:
![image](https://user-images.githubusercontent.com/23477559/71672664-95236a00-2d6e-11ea-9089-f9a8d22f4d78.png)

Desired:
![image](https://user-images.githubusercontent.com/23477559/71672722-b7b58300-2d6e-11ea-8e3d-6f731fadeaf1.png)

if no value exists for the x value then it should be left blank

**Comment by junedchhipa** [comment]
Thanks for the suggestion. Implemented it, will be available in the next patch release.
