### ISSUE TITLE
How do I change tooltip position to be always on top?

### ISSUE THREAD

**Issue by simzikov** [apexcharts/apexcharts.js#1178]
By default Apex Charts tooltip positioning is calculated automatically: https://codepen.io/apexcharts/pen/xYqyYm. According to the docs, you can only change it to fixed and put in one of the corners:

```
Apex.tooltip = {
    fixed: {
      enabled: true
    }
  };
```
How do I change it to be always centered on top of the marker?

**Comment by Simpleqode** [comment]
In case anyone wants to change the position of tooltips without creating a custom one (cause it poses new difficulties). I am 100% sure there is a better way to do this, but here is my solution: 

```
Apex.chart = {
    events: {
        mouseMove: function(event, chartContext, config) {
            var tooltip = chartContext.el.querySelector('.apexcharts-tooltip');
            var pointsArray = config.globals.pointsArray;
            var seriesIndex = config.seriesIndex;
            var dataPointIndex = config.dataPointIndex === -1 ? 0 : config.dataPointIndex;

            if (seriesIndex !== -1) {
                var position = pointsArray[seriesIndex][dataPointIndex];

                tooltip.style.top = position[1] + 'px';
                tooltip.style.left = position[0] + 'px';
            }
        }
    }
};
```
Then you can center it with CSS and `transform`.

**Comment by kamaladenalhomsi** [comment]
I am in the same situation here, I am putting the chart in a small box, and sometimes on some data points the tooltip position goes down like that
![image](https://user-images.githubusercontent.com/16209653/83349165-ec843100-a332-11ea-99c8-c0bd50bb400e.png)

**Comment by kamaladenalhomsi** [comment]
@Simpleqode 
it worked for me very good!
Thank you

**Comment by EeeDotZee** [comment]
I wanted to achieve something similiar to what most of the mobile app charts look like (to have a tooltip floating on the top of the chart).
I altered the code from @simzikov a little bit, you can check out this [codepen](https://codepen.io/eliazzz/pen/ExyJaYw). It works fine on a touch device for me. 
Note: It's a bit hacky for sure, also tooltips will clip over the menu, but i didn't need the menu for mobile charts so it works fine if you deactivate it.

**Comment by Loque18** [comment]
any news on this issue ?

**Comment by rromikas** [comment]
```
    tooltip: {
      shared: true,
      fixed: { enabled: true, position: "topLeft" },
      custom: (props) => {
        const seriesIndex = 0;
        const left = props.w.globals.seriesXvalues[seriesIndex][props.dataPointIndex];
        const top = props.w.globals.seriesYvalues[seriesIndex][props.dataPointIndex];
        return `<div style="left: ${left}px; top: ${top}px;" class=" bg-white rounded-md shadow-[0px_2px_7px_rgba(0,0,0,0.1)] p-2 absolute transform translate-x-[50%] translate-y-[-50%]">Content</div>`;
      },
    },
```
