### ISSUE TITLE
How do i create a dynamic annotation in line chart with annotation section ? 

### ISSUE THREAD

**Issue by vijayrawat86** [apexcharts/apexcharts.js#1180]
By default Apex Charts displayed static annotation under line chart section . we want to create a dynamic annotation along x-axis. is there any way to achieve this functionality ?

**Comment by junedchhipa** [comment]
If you want to create annotations on run time, you can call the[ addXaxisAnnotation()](https://apexcharts.com/docs/methods/#addxaxisannotation) method.

```javascript
var chart = new ApexCharts(el, options);
chart.addXaxisAnnotation({
  x: 40,
  label: {
    text: 'Lorem Ipsum'
  },
})
```
