### ISSUE TITLE
Error in synced tooltips

### ISSUE THREAD

**Issue by ajhansen** [apexcharts/apexcharts.js#1181]
This is difficult to re-produce in a Codepen but I hope the issue can be clarified a bit here without at first. Otherwise, I will make a Codepen if it's an absolute must.

I have two graphs, but there a supposed to be 7 when I'm done.
Both graphs have 3 datasets.
1. 176 elements
2. 8 elements
3. 14 elements

Set 1 is different for the two graphs but they both have the same X (numeric) values. Set 2 & 3 are the same for both graphs.

## Explanation

- What is the behavior you expect?
I expected this to hover on the same two X values.
Like this: https://apexcharts.com/react-chart-demos/line-charts/syncing-charts/

- What is happening instead?
Most of the time it hovers on two different X values, but if I zoom in, a lot, it's possible to get the correct behavior. See the attached image.

- What error message are you getting?
None, but I'm getting a different behavior than expected.

![hover_bug](https://user-images.githubusercontent.com/229590/71724319-31617580-2e30-11ea-8958-953b98c01870.png)

**Comment by junedchhipa** [comment]
Thanks for reporting the issue.
I would appreciate it if you can create a codepen as this seems like an issue with data and it's difficult to reproduce it without the series.

**Comment by junedchhipa** [comment]
Closing as no response.
Feel free to re-open if you're able to reproduce the issue in a codepen.

**Comment by ajhansen** [comment]
I reproduced in this pen: https://codepen.io/ajhansen/pen/rNavZYd
Usually, I have 2 more series on some charts but this illustrates the problem.
