### ISSUE TITLE
When every data in series has only 1 value, all series data are bound to the first category value of xaxis

### ISSUE THREAD

**Issue by dev-debug** [apexcharts/apexcharts.js#1182]
I have a column apex chart. When every series data has 1 value, the chart are bound to the first categories value of xaxis.

I have a series like this

>  series: [{
            name: 'Bikes',
            data: [16240314.115]
        }, {
            name: 'Bikes',
            data: [9520869.049]
        }, {
            name: 'Bikes',
            data: [27832356.658]
        }, {
            name: 'Bikes',
            data: [532399.178]
        }, {
            name: 'Clothing',
            data: [1598657.794]
        }, {
            name: 'Clothing',
            data: [135523.664]
        }, {
            name: 'Accessories',
            data: [4347678.462]
        }, {
            name: 'Accessories',
            data: [376470.596]
        }],
   
And categories for xaxis as 

>  xaxis: {
          categories: ['2011', '2012', '2013', '2014',' 2013', '2014', '2013', '2014'],
        }

Then every series data are bound to 2011 in the chart(and not to any other years in the categories)

**_This scenario happens with every kind of apex chart available on your website_**

**_I've the data in this format only, how do i create an apex chart(any apex chart) with the present data_**

And how do i define the data gap of Y-axis(my data are hugh and I want to give some custom smaller gap format for Y-axis)?

The entire code is below including codepen

`  <div id="chart" style="float:left;"></div>

var options = {
               series: [{
            name: 'Bikes',
            data: [16240314.115]
        }, {
            name: 'Bikes',
            data: [9520869.049]
        }, {
            name: 'Bikes',
            data: [27832356.658]
        }, {
            name: 'Bikes',
            data: [532399.178]
        }, {
            name: 'Clothing',
            data: [1598657.794]
        }, {
            name: 'Clothing',
            data: [135523.664]
        }, {
            name: 'Accessories',
            data: [4347678.462]
        }, {
            name: 'Accessories',
            data: [376470.596]
        }],
   
        chart: {
          type: 'bar',
          height: 650,
          width:900
        },
        plotOptions: {
          bar: {
            horizontal: false,
            columnWidth: '55%',
            endingShape: 'rounded'
          },
        },
        dataLabels: {
          enabled: false
        },
        stroke: {
          show: true,
          width: 2,
          colors: ['transparent']
        },
        xaxis: {
          categories: ['2011', '2012', '2013', '2014',' 2013', '2014', '2013', '2014'],
        },
        yaxis: {
          title: {
            text: '$ (thousands)'
          }
        },
        fill: {
          opacity: 1
        },
        tooltip: {
          y: {
            formatter: function (val) {
              return "$ " + val + " thousands"
            }
          }
        }
      };

      var chart = new ApexCharts(document.querySelector("#chart"), options);
      chart.render();
    
    
    

`

[Codepen for this issue](https://codepen.io/dev-debug/pen/ExabEbG)

**Comment by junedchhipa** [comment]
Your built series is wrong.
You are inputting the same series name multiple times.

If each of your series has just 1 data-point, you can look into distributed column charts - https://apexcharts.com/javascript-chart-demos/column-charts/distributed/
