### ISSUE TITLE
Final xaxis label missing on bar chart

### ISSUE THREAD

**Issue by rcoundon** [apexcharts/apexcharts.js#1184]
## Codepen

Using vue-apexcharts, in the current version of apexcharts (3.12.0) the final xaxis label doesn't display (in 3.8.0 - the sandbox default, it works)

See an example here: https://codesandbox.io/s/vue-basic-example-fzyq2

## Explanation

- What is the behavior you expect?
I expect all xaxis labels to display
- What is happening instead?
The final label is missing
- What error message are you getting?
No error, just no final label

**Comment by mtinnes** [comment]
Maybe related bug, buy after upgrading to 3.12.0 our xaxis categories are not showing up at all. Labels are missing entirely.

**Comment by junedchhipa** [comment]
@mtinnes Can I get a codepen demo, please?

**Comment by junedchhipa** [comment]
Fixed in 3.13.1
