### ISSUE TITLE
Scaling option in Advanced Timeline Chart

### ISSUE THREAD

**Issue by Saurav-Jain** [apexcharts/apexcharts.js#1185]
In the advanced timeline chart, i want to change the scale for how we can do it in timeline chart?

Could you please provide me suggestionfor it?

**Comment by junedchhipa** [comment]
What do you mean by "change the scale"
x-axis scale? or the whole SVG scaling?

**Comment by Saurav-Jain** [comment]
I want to show the particular area by selection like zoom in. How can i enable in it?

**Comment by junedchhipa** [comment]
Sorry, zooming in timeline range-bar charts are not possible currently.
Might be added in the future.
