### ISSUE TITLE
Weird y-axis spacing

### ISSUE THREAD

**Issue by philfontaine** [apexcharts/apexcharts.js#1187]
## Codepen

The spacing of the y-axis is inconsistent when there is one x-axis vs multiple y-axis. This is problematic for me, as I am dynamically switching between having one and multiple.

https://codepen.io/philfontaine/pen/MWYrXry

Notice here how the y-axises are well spaced.

![image](https://user-images.githubusercontent.com/16233697/71837679-04f26700-3085-11ea-8928-3077d417ac46.png)

Notice here how the y-axis is really too close from the border

![image](https://user-images.githubusercontent.com/16233697/71837718-18053700-3085-11ea-801a-eb97bcaf6e5f.png)

If it helps, I think this behavior might have changed recently because I have not encountered this problem before. (I was on 3.10.1, and now using 3.12.0)

**Comment by junedchhipa** [comment]
If you need to have a fixed yaxis width no matter how many y-axes are there, you can use yaxis.labels.minWidth property - https://apexcharts.com/docs/options/yaxis/#minWidth

```javascript
yaxis: {
  labels: {
    minWidth: 100
  }
}
```
