### ISSUE TITLE
Line is not straight

### ISSUE THREAD

**Issue by philfontaine** [apexcharts/apexcharts.js#1188]
## Codepen

I have this almost straight line. Is it normal that is shows up as stairs?

![image](https://user-images.githubusercontent.com/16233697/71841010-78e43d80-308c-11ea-9e0e-6c3a39dc5190.png)

https://codepen.io/philfontaine/pen/yLypqab

Thanks

**Comment by junedchhipa** [comment]
Yes, the line looks straight but the data makes it looks like a staircase.
If you want to see a perfectly straight line, take a look at this example - https://apexcharts.com/javascript-chart-demos/mixed-charts/line-scatter/
