### ISSUE TITLE
Candlestick chart: How to remove gaps if there are no data (OHLC) on some date-time intervals

### ISSUE THREAD

**Issue by aptarmy** [apexcharts/apexcharts.js#1191]
Before submitting this issue, I have already read the docs about this problem but had no luck to find the option that let me remove gaps if some date-time intervals are missing.

**Is your feature request related to a problem? Please describe.**
When I plot stock price data, there are gaps in some DateTime intervals because stock price data is only available on the days that the market opens. There will be no candlestick data in the days market closes.

For example, if I plot stock prices in a range of the last 7 days, and the date-time interval is 1 day.  I would have gaps on Saturday and Sunday because these are the days market closes. 

**Describe the solution you'd like**
Allow us to remove or skip date-time intervals that there are no OHLC data. Something similar to `spanGaps` in Chart.js

**Additional context**
This is what the library does for me to render stock prices with a range of 7 days and 1-day intervals (no data on Sat. and Sun.)
See on Codepen here: [https://codepen.io/aptarmy/pen/VwYyoyj](https://codepen.io/aptarmy/pen/VwYyoyj)
![Apexcharts result](https://user-images.githubusercontent.com/6024196/71884343-ba4b1a80-316a-11ea-8fd1-d8ed239921f8.png)

This is the result I would like to have (skip those with no data)
![Expected result](https://user-images.githubusercontent.com/6024196/71885271-9983c480-316c-11ea-9308-e743c6c7ef86.png)

**Comment by Darek64** [comment]
Is there any chance to solve this problem in the near future?

**Comment by junedchhipa** [comment]
Currently, I have no idea how this can be achieved in the datetime xaxis.

One alternative is to use `xaxis.type: 'category'` but zooming isn't available there.
I will try to implement zooming in category xaxis of the candlestick and see if this problem can be solved.

**Comment by aptarmy** [comment]
I appreciate your time and efforts. Thanks @junedchhipa

**Comment by junedchhipa** [comment]
I have enabled zooming on category x-axis since v3.15.0 which will help to solve the issue of gaps.

Live example - https://apexcharts.com/javascript-chart-demos/candlestick-charts/category-x-axis/

**Comment by CleAurora** [comment]
@junedchhipa @aptarmy @Darek64 anybody was able to solve this issue with gaps?

**Comment by Alejandroem** [comment]
This is just what I needed thank you @junedchhipa

**Comment by BekNaji** [comment]
Hello. 
I made candlestick chart with apexcharts js. I used  type:category. All things are working good but as you can see the picture below.  The candlestick design not beautiful if has many data. But candlestick design very pretty if I use type: datetime. 
( Why I use (type: category) ? Reason is that I should remove weekends from canldestick.) 
Do you have any solution ?

Pictures: 
[Candlestick - type:category](https://cloud.mail.ru/public/A2NZ/Bae9etmum)
[Candlestick - type:category - zoomed - not pretty](https://cloud.mail.ru/public/yd2u/rCruyseZZ)
[Candlestick - type:datetime zoomed - should be like this](https://cloud.mail.ru/public/Pnfm/qyNBXaALJ)

My codes [here](https://gist.github.com/BekNaji/35eef69906b12b3c497c91ed05473b58)

**Comment by CreativeWarlock** [comment]
What setting precisely makes the candlestick chart not render gaps? I still see gaps from the 2 days on each weekend on my chart and I have taken the exact option parameters as given by your example here: https://apexcharts.com/javascript-chart-demos/candlestick-charts/category-x-axis/

Anyone else having the same issues or am I just missing out something that is very very obvious to everyone else? :D

**Comment by CreativeWarlock** [comment]
For many (if not most) users, the request is to use the candlestick chart **with datetime**, not categories.

If in case your company has not planned this feature, please let me know if we can support realizing this feature with a donation.
