### ISSUE TITLE
Enhanced annotations style

### ISSUE THREAD

**Issue by sebastialonso** [apexcharts/apexcharts.js#1193]
**Is your feature request related to a problem? Please describe.**
I don't know if this is fully implemented, but as far as the documentation is concerned, I think I can't. 
I'm trying to achieve labels like the ones in the reference image.

**Describe the solution you'd like**
I'd like to be able to supply custom html code (or a component if we are thinking in React) for the label

**Describe alternatives you've considered**
I've tried using the `cssClass` in the label, but that only let's you style the text of the label.
Maybe I'm missing something important, so any insight will be appreciated.

**Additional context**
[Reference image:](https://i.imgur.com/olOuLPs.png)

Thank you for your hard work. This is a really great library!

**Comment by rafaelkloss** [comment]
I have the same issue with "cssClass", does't work.
