### ISSUE TITLE
How to remove gaps if there are no data on some date-time intervals for stacked column chart

### ISSUE THREAD

**Issue by Dineshbha** [apexcharts/apexcharts.js#1194]
Facing issues with a stacked column chart if the difference between minX (leftmost datetime) and maxX (rightmost datetime) is large.  It is plotting the empty data points.

Describe the solution you'd like
Allow us to remove or skip date-time intervals that there is no data. 

https://codepen.io/dineshbha/pen/LYEQJaG

**Comment by junedchhipa** [comment]
Sorry, removing intervals in the xaxis scale is not possible with datetime xaxis.
The only solution is to convert the `xaxis.type` to `category`.

If you need zooming functionality in category xaxis, it will be released in the next update.

**Comment by ftahery-teleo** [comment]
Hello @junedchhipa Thank you so much for an amazing library.

I have tried making the `xaxis.type` to `cateogry  ` in datetime xaxis chart. But I can still see gaps in the charts.

Can you help me with this?
