### ISSUE TITLE
When do you introduce zooming for xaxis.type = 'category'?

### ISSUE THREAD

**Issue by michaeljakob** [apexcharts/apexcharts.js#1195]
**Is your feature request related to a problem? Please describe.**
It has been clear that one of the biggest problems of apexcharts is that 'category' type charts are not zoomable. - and I know of more than 10 users that dropped it for that reason and we are on the verge of dropping it completely and never look back.

We need all the critical features that come with 'category' type charts: 
- tickPlacement: 'on' (instead of default 'between')
- show the year for all items on the x-axis, not just every 5th year

**Describe the solution you'd like**
Enable zooming for xaxis.type='category' charts.

**Additional context**
Our current solution is a 'datetime' with hundreds of hacks, and it still looks buggy. We will definitely drop apexcharts in the next weeks if we can't solve this, which makes us really sad.

I'm attaching two screenshots that illustrate problems with 'datetime'.
We have a financial charts and want to show annual data for each year, e.g. 2018, 2019, 2020
1) Problem #1: Data should be ON the tick, not somewhere randomly inbetween -- looks buggy
2) Problem #2: Show EVERY year, not randomly every nth year -- huge bummer for our users
<img width="811" alt="截屏2020-01-0821 12 45" src="https://user-images.githubusercontent.com/3597595/71980749-c8c52f00-325b-11ea-811b-4bbbf9499964.png">

3) Problem 3: Again, show EVERY year, especially the most recent year (2019)
<img width="805" alt="截屏2020-01-0821 12 50" src="https://user-images.githubusercontent.com/3597595/71980756-ca8ef280-325b-11ea-91fd-1fb1ccc96053.png">

How are your plans/roadmap for resolving this major issue?

**Comment by michaeljakob** [comment]
I want to highlight how some other parts of 'datetime' are severely broken.
Again: using xaxis.type='category' is exactly what we're looking for and solves all issues at once. The only downside is: we can't zoom!

4) Critical Problem #4: Hovering on year 2016 shows tooltip for 2016. Hovering on year 2010 shows tooltip for 2011.
<img width="803" alt="截屏2020-01-0821 18 57" src="https://user-images.githubusercontent.com/3597595/71981100-9d8f0f80-325c-11ea-9e53-8cf1d9b97497.png">
<img width="808" alt="截屏2020-01-0821 18 48" src="https://user-images.githubusercontent.com/3597595/71981102-9f58d300-325c-11ea-8e50-96f4c45685f4.png">

**Comment by junedchhipa** [comment]
Hi @michaeljakob 
The timescale generation on ApexCharts is basically done this way.
1. Grab the min X data-point
2. Grab the max X data-point
Depending on how much the interval is between the min and max, the ticks are generated in this way.
 **Yearscale** - The first day and first month (01 Jan) becomes the tick for the year-scale
 **Monthscale** - The first day and the 15th of every month are generated for month-scale
 **Dayscale** - Depending on how many days can fit, ticks are generated for day-scale and similarly, hour scale is generated.

I spent last week to allow zooming in the category axis and faced some issues, but most of them will be resolved soon.

Here is what's coming in the next release (hopefully tonight or tomorrow once I test it enough)
- Zooming will be enabled by default for line charts even in category axis.
- For bar charts, zooming will be disabled by default but can be enabled easily by changing 2 properties
   `xaxis.tickPlacement: 'on'` and `chart.zoom.enabled: 'true'`. Also, there are some issues with multiple series in a bar chart that part of the bars gets cropped when `xaxis.tickPlacement` is 'on'. So, you will need to adjust the `grid.padding.left` and `grid.padding.right` if this happens.

![Screen Shot 2020-01-08 at 7 09 14 PM](https://user-images.githubusercontent.com/17950663/71982399-6152b380-324a-11ea-98ec-b640c5bdedf8.png)


The reason why I want to disable zooming for bar charts by default is to prevent a breaking change.
I will document all these things on the website after the release so there is no confusion left.

Thanks for your support.

**Comment by junedchhipa** [comment]
Here's a GIF. You can see the bars get cropped in the zooming. I haven't been able to find a good solution for it yet, but some manual workarounds should make it work.
![cat-zoom](https://user-images.githubusercontent.com/17950663/71982826-71b75e00-324b-11ea-864a-d2ec71b66356.gif)

**Comment by michaeljakob** [comment]
Hi Juned,
wow, I'm honestly amazed by the response speed. Your example with revenue/net profit/free cashflow is pretty much exactly what we are building. The GIF looks perfect to me, I'm confident I can fix the right padding/left padding you bring up.
All the other aspects of ApexChart are really great, looking forward to the upcoming release!

**Comment by michaeljakob** [comment]
Hey Juned,

I saw that there was an update to vue-apexchart (1.5.2) yesterday. I tried changing xaxis.type from datetime to 'category', but I still wasn't able to see zooming here. 

*Could you please ping me when zooming will be enabled in vue-apexcharts? :D*

FYI our 'zooming code' (works great with datetime!):

zoom: {
type: 'x' ,
enabled: true ,
autoScaleYaxis: true
},
toolbar: {
show: (window.innerWidth > 700 ),
autoSelected: 'zoom' ,
tools: {
zoomin: false ,
zoomout: false ,
pan: false ,
zoom: true , //'<svg/>', // don't show any icon, but still enable zoom :)
download: false ,
reset: '<svg fill="#333" style="fill:#333" height="24" viewBox="0 0 24 24" width="24" xmlns=" http://www.w3.org/2000/svg "> <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"></path> <path d="M0 0h24v24H0z" fill="none"></path> </svg>'
}
},

**Comment by junedchhipa** [comment]
Hi Michael,
You will have to update the core apexcharts version to 3.14.0 from npm - https://www.npmjs.com/package/apexcharts 

```
npm install apexcharts --save
```

For bar charts, you will have to manually enable zooming
```javascript
chart: {
  zoom: {
    enabled: true
  }
},
xaxis: {
  tickPlacement: 'on'
}
```

Unfortunately, the zooming is still not perfect and I am still working on the margin/padding issues. Once it is done, I will close this thread and update it here.

**Comment by michaeljakob** [comment]
Hi Juned,

I've updated both apexcharts (3.14.0) and vue-apexcharts (1.5.2), yet I can't find the proper controls for zooming. Do you have an example for that?

I have attached our production code (stripped down to the relevant parts) where we did not get the zooming controls visible, nor the "drag and drop with mouse to zoom in" to be enabled. The padding issue you mentioned wouldn't be a huge problem for us :).

**Comment by junedchhipa** [comment]
Sure,

I am going to update the docs with some examples soon.

**Comment by junedchhipa** [comment]
Released v3.15.0 with the zooming enabled on category x-axis.
Example - https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/

Doc: https://apexcharts.com/docs/zooming-in-category-x-axis/

**Comment by Eskimo111** [comment]
Hi Juned,
I noticed that the columns resize when you zoom in on the gif you previously uploaded; is there any way I can replicate that effect? 
I've tried a lot of things, such as switching the version and redrawing the chart on zoom or pan, but nothing seems to work.

**Comment by emailnikola** [comment]
@Eskimo111 Columns resize when x-axis is "timeline" instead of "category".
