### ISSUE TITLE
Annotations crash

### ISSUE THREAD

**Issue by davisriska** [apexcharts/apexcharts.js#1196]
From version 3.11.3, every time I try to add an annotation to a line chart with addXaxisAnnotation, this error appears - 
`TypeError: Cannot read property 'getBoundingClientRect' of null
    at t.value (apexcharts.esm.js:6)
    at t.value (apexcharts.esm.js:6)
    at t.value (apexcharts.esm.js:6)
    at t.value (apexcharts.esm.js:16)`

I tried reproducing it in a codepen, but sadly couldn't figure out how to. 
Im using ng-apexcharts. 
When I go back to version 3.11.2 the error disappears and annotations get added correctly.

**Comment by KarmaBlackshaw** [comment]
Im still seeing at **vue-apexcharts** version **1.5.3**

**Comment by Didza** [comment]
I also get this error on v3.19.0

**Comment by junedchhipa** [comment]
Need more information when this occurs.
Please provide a working Codepen example.
