### ISSUE TITLE
Append label?

### ISSUE THREAD

**Issue by jicihome** [apexcharts/apexcharts.js#1197]
In Radial Bar we can append serie using: chart.appendSeries([44]) for example. But how can we add label?

**Comment by jicihome** [comment]
For now, I'm using chart.w.config.labels.push('new label') before appendSeries. But was wondering if there's a way todo it directly with appendSeries method.

**Comment by junedchhipa** [comment]
For radial-bar, pie and donut charts, it's better to use `updateOptions()` method to update all at once.
Pushing in chart.w.config.labels.push('new label') may work but looks hacky.

```javascript
chart.updateOptions({
  series: [32, 3, 12],
  labels: ['A', 'B', 'C']
})
```
Although here, you are updating the whole series, not appending. So you will need to get access to the previous series in `w.globals.series.slice()` and then push into it. The same goes for labels.

**Comment by jicihome** [comment]
Ok Thanks. What is the difference between appendData and update Options behavior?

**Comment by junedchhipa** [comment]
`appendData` preserves the previous series data and pushes new data on top of it in the series.
While `updateOptions` overwrites the existing data and creates a fresh chart (animates the change though so it doesn't look unnatural)
