### ISSUE TITLE
Bug: Legend margin horizontal and vertical flipped

### ISSUE THREAD

**Issue by Christilut** [apexcharts/apexcharts.js#1203]
## Codepen

https://codepen.io/Christilut/pen/oNgdLEd?editors=1010

## Explanation

- What is the behavior you expect?
```
    legend: {
      itemMargin: {
        vertical: 20
      }
    },
```
Is controlling horizontal margin and vice versa.

**Comment by junedchhipa** [comment]
Yes, it was wrong. Fixed it.
Thanks
