### ISSUE TITLE
Data points not corresponding to the scale of the Y axis in the datetime-x-axis chart

### ISSUE THREAD

**Issue by htmfilho** [apexcharts/apexcharts.js#1204]
## Codepen

It's actually an example I found at:

https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis/

I tested it on Firefox and Chrome.

## Explanation

I'm evaluating Apexcharts for a project. While navigating in the demos and looking carefully at the Timeseries charts, I noticed that, sometimes, values in the chart don't correspond to the scale of the Y axis. In the image below the popup shows 36.90, but this point is below the 36.00 line.

![apexcharts-bug-datetime-x-axis](https://user-images.githubusercontent.com/200272/72173721-2feefa80-33a6-11ea-971e-ef5b1dd5b2ae.png)

- What is the behavior you expect?

We certainly expect the Y axis to be precise in relation to the data points.

- What is happening instead?

The data points are not always corresponding to the scale of the Y axis.

**Comment by Christilut** [comment]
I was about to report this exact issue.

![image](https://user-images.githubusercontent.com/3471363/72176936-de636180-33df-11ea-81b2-b5d1dd944996.png)

y axis is correct if it's not `datetime`.

**Comment by junedchhipa** [comment]
related to #718

**Comment by junedchhipa** [comment]
Thanks for raising the issue. Yes, it can be clearly seen that it doesn't match the y-axis.
I will take a closer look soon.
