### ISSUE TITLE
Most recent library will not render in IE11

### ISSUE THREAD

**Issue by dougnewnham** [apexcharts/apexcharts.js#1205]
Sorry if I am asking an old question but is IE11 still supported.  The most recent download does not appear to render at all.

**Comment by junedchhipa** [comment]
IE11 needs some polyfill libraries to be loaded first before rendering ApexCharts as specified in the [README](https://github.com/apexcharts/apexcharts.js#using-it-with-ie11)

Please load these polyfills before loading ApexCharts and report back if it works after loading these.
- [promise-polyfill](https://github.com/taylorhakes/promise-polyfill)
- [classlist.js](https://github.com/eligrey/classList.js/)
- [blob.js](https://github.com/eligrey/Blob.js)

**Comment by dougnewnham** [comment]
I have added these to both my original working use of ApexCharts and also tried adding them to the samples but it still does not render correctly.  Adding the Polyfills does seem to make a change and I can see the chart "body" but no grids, data or labels etc.

**Comment by junedchhipa** [comment]
Thanks for the update. I don't have windows at the moment.
But, I will soon test and update this thread.

**Comment by dougnewnham** [comment]
Thanks for the quick response.  I am relatively new to JavaScript so I'm not sure if I've incorporated those polyfills correctly.  I've placed them above the ApexCharts.js but i've not added anything else beyond that.

**Comment by parkyeonkyu** [comment]
I also have the same issue so my site can't run
let me know how to solve this problem plz.
thank you

**Comment by Harkonnen13** [comment]
I included all polyfills u said, but it still doesn't work, because ApexCharts use insertAdjacentHTML method, IE 11 has this method implemented only for base HTMLElement. And i have no idea how to solve this

**Comment by junedchhipa** [comment]
Fixed the issues and released new version 3.15.1

Please upgrade the library to the latest version and then include these polyfills

```html
<script>
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill@1.2.20171210/classList.min.js"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/blob-polyfill"><\/script>');		
</script>
```

It should work now.

**Comment by dougnewnham** [comment]
![Current Version](https://user-images.githubusercontent.com/46853545/72477810-8051d680-3844-11ea-80aa-d51693d16d5d.JPG)
![LastWorking](https://user-images.githubusercontent.com/46853545/72477819-86e04e00-3844-11ea-8c9e-e4f4bdb1b499.JPG)

Great work! It is rendering again now as you can see but annotations and labels have disappeared.  With these two screenshots the only difference is the CSS and the library

**Comment by dougnewnham** [comment]
Note that what appear to be gridlines are actually annotation lines.

**Comment by perren** [comment]
So close! There's some type of off by 1 glitch happening for me with IE11. Screenshot attached of stock bar chart demo code.

![Screen Shot 2020-01-15 at 4 32 31 PM](https://user-images.githubusercontent.com/530099/72483214-13433000-37b5-11ea-8913-f556a8c27762.png)

**Comment by junedchhipa** [comment]
Thanks for the feedback.
I don't have windows machine at the moment.
Can anyone suggest a place where I can test IE11 remotely?

**Comment by perren** [comment]
You can do 1hr a month for free here:

https://www.lambdatest.com/

**Comment by junedchhipa** [comment]
@perren That looks promising. Thanks!

**Comment by IlyaChubko** [comment]
> Fixed the issues and released new version 3.15.1. Please upgrade the library to the latest version
> 
> Add these IE11 polyfills in the header
> 
> ```
> <script>
>   window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"><\/script>');
>   window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill@1.2.20171210/classList.min.js"><\/script>');
>   window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"><\/script>');
>   window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/blob-polyfill"><\/script>');		
> </script>
> ```
> 
> It should work now.

Hello! After included https://cdn.jsdelivr.net/npm/blob-polyfill I have error (apexcharts.amd.js 3.15.1) in Chrome:
![image](https://user-images.githubusercontent.com/6832799/72547317-7c05d780-389d-11ea-852b-ade4eef5b944.png)
Can you help me?

**Comment by junedchhipa** [comment]
@IlyaChubko You may remove blob.js polyfill as it doesn't work as expected. I will find another alternative.

**Comment by junedchhipa** [comment]
Released v3.15.2
Removed IE11 incompatible code.
Let me know if the latest version works.

**Comment by IlyaChubko** [comment]
Thank you! 3.15.2 fix a lot of bugs IE11. It works for me

**Comment by junedchhipa** [comment]
Awesome!
Closing this thread.

**Comment by OlegBalabukh** [comment]
> So close! There's some type of off by 1 glitch happening for me with IE11. Screenshot attached of stock bar chart demo code.
> 
> ![Screen Shot 2020-01-15 at 4 32 31 PM](https://user-images.githubusercontent.com/530099/72483214-13433000-37b5-11ea-8913-f556a8c27762.png)

@perren did you fix this issue? I have the same with bar chart in IE
