### ISSUE TITLE
Candlestick bug

### ISSUE THREAD

**Issue by Derbakias** [apexcharts/apexcharts.js#1206]
The candlesticks  are overlapping each other is that normal?

![apexchart](https://user-images.githubusercontent.com/52934417/72200504-e27c9700-3452-11ea-8b4c-9b62f5be967b.png)

#candlestick

**Comment by junedchhipa** [comment]
No, it's not
Which version you're using?

**Comment by Derbakias** [comment]
> No, it's not
> Which version you're using?

The latest, I think..
through the cdn..

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

**Comment by junedchhipa** [comment]
Can I get a working codepen example, please?

**Comment by Derbakias** [comment]
Sure!! 
Here is the repo that I'm working on..
https://github.com/Derbakias/stockbox

**Comment by junedchhipa** [comment]
I meant a codepen demo like this - https://codepen.io/apexcharts/pen/xYqyYm
So, I can reproduce on my side easily.

**Comment by Derbakias** [comment]
Sorry about this.. I didn't understand

https://codepen.io/derbakias/pen/GRgdyyJ

I've tried everything from my side to see what is wrong but I can't find something..
The problem seems to be with the specific data-set format I think..

In my project I get also this error

apexcharts:6 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
D.a.on @ apexcharts:6
on @ apexcharts:6
t.init @ apexcharts:14
draggable @ apexcharts:14
value @ apexcharts:6
(anonymous) @ apexcharts:14
value @ apexcharts:14
(anonymous) @ apexcharts:14
value @ apexcharts:14
(anonymous) @ apexcharts:14
apexcharts:14 [Violation] 'setTimeout' handler took 85ms

**Comment by junedchhipa** [comment]
Thanks for the demo, it will be addressed soon.

**Comment by Derbakias** [comment]
You are very welcome!!

I think I found something which maybe is going to help..
The problem seems to be with data which is very recent.

The dataset1 gives the bug,
the dataset2 is the 'demo' data and it's working OK..

https://codepen.io/derbakias/pen/oNgdELj

**Comment by junedchhipa** [comment]
The dates have to be sorted in ascending order.
In your dataset1, the dates are in descending order which created overlaps in the chart.
