### ISSUE TITLE
Legend circles cut off since latest update (1.5.2 vue-apexcharts)

### ISSUE THREAD

**Issue by michaeljakob** [apexcharts/apexcharts.js#1208]
We've just updated from 1.5.1 to 1.5.2 and noticed that our legend-circles were slightly cut off at the top. Refer this screenshot:

<img width="1300" alt="Screen Shot 2020-01-12 at 20 20 10" src="https://user-images.githubusercontent.com/3597595/72219476-210c7180-3579-11ea-801f-a117dd72dc63.png">

I have tried adding paddings/margins around the `<apexcharts />` tag. However, the cutoff seems to happen somewhere in the SVG code.

**Comment by junedchhipa** [comment]
Fixed in apexcharts@3.15.0

**Comment by alkonaesc** [comment]
unfixed in apexcharts@3.20.1
I moved it from top to bottom of the chart cause I thought it is the chart being cut. 
![image](https://user-images.githubusercontent.com/70039729/92608480-9e8eaa00-f2df-11ea-9d6a-752b967abdb7.png)

**Comment by junedchhipa** [comment]
@alkonaesc Can you create a reproducible Codepen?
A small change in legend positioning might fix it.

**Comment by alkonaesc** [comment]
mhm. I am fine of fixing it on my own ☺

For an unknown reason escapeString is fed undefined
`function escapeString(str) `  => `function escapeString(str = '') `

the legend is fixed if you remove overflow:auto from 
`.apexcharts-legend {
    display: flex;
    /* overflow: auto; */`
it fixed things for me and works fine on all my other graphs. not sure about the rest

![image](https://user-images.githubusercontent.com/70039729/92613678-6e4a0a00-f2e5-11ea-803b-3c2c9cf8b9a0.png)
