### ISSUE TITLE
Annotations on stacked chart no dosen't work properly

### ISSUE THREAD

**Issue by tomernesimyan** [apexcharts/apexcharts.js#1209]
## Annotations on stacked table with seriesIndex dosen't render on top of the column

When I put annotation on stacked table with seriesIndex bigger than 0, 
The annotation height calculation ignore previous columns and then render it on the middle of the column.

Example code: 
This is the chart options - 
chartOptions = {
      annotations: {
        points: [{
          x: 'AVG',
          seriesIndex: 1,
          label: {
            borderColor: '#775DD0',
            offsetY: 0,
            style: {
              color: '#fff',
              background: '#775DD0',
            },
            text: 'Average',
          }
        }]
      },
      chart: {
        stacked: stacked,
        height: 350
      }
}

And the result is:
![image](https://user-images.githubusercontent.com/49777140/72226384-2f6a8580-3599-11ea-864c-d0da72e79594.png)

**Comment by junedchhipa** [comment]
Please create a codepen demo to easily reproduce the issue.
