### ISSUE TITLE
Error in synced tooltips

### ISSUE THREAD

**Issue by ajhansen** [apexcharts/apexcharts.js#1210]
Same as #1181 but re-opened here.

## Codepen

I reproduced in this pen: https://codepen.io/ajhansen/pen/rNavZYd
Usually, I have 2 more series on some charts but this illustrates the problem.

## Explanation

- What is the behavior you expect?
I expected this to hover on the same two X values.
Like this: https://apexcharts.com/react-chart-demos/line-charts/syncing-charts/

- What is happening instead?
Most of the time it hovers on two different X values, but if I zoom in, a lot, it's possible to get the correct behavior. See the attached image.

- What error message are you getting?
None, but I'm getting a different behavior than expected.

![hover_bug](https://user-images.githubusercontent.com/229590/72236530-9149e000-35d7-11ea-9d5e-805ae4bcb574.png)

**Comment by junedchhipa** [comment]
You will see this message in the console if you have sync charts
![Screen Shot 2020-01-13 at 11 13 15 PM](https://user-images.githubusercontent.com/17950663/72278685-8dab6d00-365a-11ea-871c-e902146fe136.png)

```javascript
yaxis: {
    labels: {
      minWidth: 45
    }
}
```

This is kinda hacky but providing yaxis width is essential to draw equal sized charts which help in getting the correct values in tooltips.
I hope this resolves the issue.
