### ISSUE TITLE
Area / Line chart doesn't grow to fill its container after v3.14.0

### ISSUE THREAD

**Issue by srcn** [apexcharts/apexcharts.js#1212]
## Codepen

Here's the minimal reproduction of the issue with v3.14.0:
[https://codepen.io/srcn/pen/abzKBab](https://codepen.io/srcn/pen/abzKBab) 

And this is the one that works correctly with v3.13.2:
[https://codepen.io/srcn/pen/GRgGNXE](https://codepen.io/srcn/pen/GRgGNXE)

## Explanation

- What is the behavior you expect?
The chart should fill the entire width of its container. It was working correctly until v3.14.0.

- What is happening instead?
There is always an extra space at the end of the chart.

- What error message are you getting?
There are no error messages.

**Comment by junedchhipa** [comment]
Yes, that's an issue that will be addressed soon.
Thanks for reporting.

**Comment by junedchhipa** [comment]
Fixed in 3.15.0
