### ISSUE TITLE
Error showing series from legend in stacked multi Chart

### ISSUE THREAD

**Issue by kylawamg** [apexcharts/apexcharts.js#1215]
## Codepen
Hi, 

First of all thanks for the library and all your work!

Here is the codepen with the example:

https://codepen.io/Kylawamg/pen/mdyjVYb

## Explanation
When I use a multiseries stacked label with one line and multiple bars and multiple yaxis (see the codepen's options) the legend show / hide series feature is not working fine. Series hide or show randomly and not with his legend's icon.

Im missing something in the options object? or is a bug?

Thanks in advance!

**Comment by gopalraju** [comment]
> ## Codepen
> Hi,
> 
> First of all thanks for the library and all your work!
> 
> Here is the codepen with the example:
> 
> https://codepen.io/Kylawamg/pen/mdyjVYb
> 
> ## Explanation
> When I use a multiseries stacked label with one line and multiple bars and multiple yaxis (see the codepen's options) the legend show / hide series feature is not working fine. Series hide or show randomly and not with his legend's icon.
> 
> Im missing something in the options object? or is a bug?
> 
> Thanks in advance!

Seems like a bug, I faced the same issue.

**Comment by mwanji** [comment]
I've seen this behaviour as well.

For example [here](https://codepen.io/genadis/pen/wZXRVv), if you remove series 3, series 4 will be removed as well.

In @kylawamg 's example, it's not random: if you remove Bar1, then Bar2, Bar3 and Bar4 are also removed. If you remove Bar2, then Bar3 and Bar4 are also removed. If you remove Bar3, then Bar4 is also removed.

**Comment by kylawamg** [comment]
Yes, @mwanji you are right. The bug only apply to Bar representation and only hide selected and the next bars, previous bars stay showing. Also if you click on Bar's legend the yaxis updates to wrong values (deleting the negatives ones), maybe this is a different bug case?.

Thanks guys for your help!
