### ISSUE TITLE
Number in multiline xaxis label causes rendering issue

### ISSUE THREAD

**Issue by mhgbrown** [apexcharts/apexcharts.js#1216]
The presence of a number in a multiline xaxis label causes the chart to render funky. If the xaxis labels are single line (not arrays), everything renders correctly.

I'm using apexcharts@3.14.0

## Codepen

https://codepen.io/mhgbrown/pen/eYmjzEY

## With "X Kg" in the second part of the xaxis label 
<img width="1163" alt="Screenshot 2020-01-14 at 20 43 16" src="https://user-images.githubusercontent.com/194112/72363654-9c535c00-370e-11ea-9835-36e3f0b36979.png">

## With "1 Kg" in the second part of the xaxis label
<img width="1170" alt="Screenshot 2020-01-14 at 20 43 37" src="https://user-images.githubusercontent.com/194112/72363655-9cebf280-370e-11ea-85b8-b178a046de0a.png">

## Explanation

- What is the behavior you expect?
The chart should be fully rendered

- What is happening instead?
The chart is not fully rendered. It looks like the xaxis is not fully lengthened.

- What error message are you getting?
`apexcharts.common.js?ba30:6 Error: <g> attribute transform: Expected number, "translate(NaN, 103.5)".`

**Comment by junedchhipa** [comment]
Thanks for reporting.
Yes, that's a bug that will be addressed soon.
