### ISSUE TITLE
Series hidden by default

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1217]
Hi,

I like the toggleSeries and show/hideSeries features, but one thing that makes them really difficult is if you have data you want hidden by default. To do this, you have to do the additional steps of verifying that the series is not already in the chart (which is kind of hacky in itself), and then adding the correct series. 

Is there anyway we can add a property on the series like `visible` that if set to false will prevent rendering the series at first? That way if we want to use the toggleSeries function and have series hidden by default, we don't have to go through the extra steps above?

**Comment by junedchhipa** [comment]
Data transformation makes the next updates difficult. So, if I remove the series initially when it is null needs additional checks at many places.
The best thing is to check the series when initializing the chart if it contains no data. Then, after the chart is rendered, immediately call the `toggleSeries()` method to hide the empty series.

**Comment by PhilJbt** [comment]
It means that charts with a lot of data and series has to be drawn once, and then redraw each times a serie is programmatically hidden. It's a [huge problem](https://github.com/apexcharts/apexcharts.js/assets/22506952/19b7fb53-8b4f-422e-8f95-f2b3890a0ab3) of performance.
Obviously, [deferring the action to the user](https://github.com/apexcharts/apexcharts.js/assets/22506952/d419a0d7-f035-495d-a898-23c7b5c803d5) doesn't change anything.

Unfortunately, this prevents me from using ApexCharts for a project.

> Data used: 4 series of 24*7 values each + 12 series of 24*4 values each

**Comment by PedroMTSilva** [comment]
> Data transformation makes the next updates difficult. So, if I remove the series initially when it is null needs additional checks at many places. The best thing is to check the series when initializing the chart if it contains no data. Then, after the chart is rendered, immediately call the `toggleSeries()` method to hide the empty series.

Would it be possible to instead add an event like `beforeMounted`? The problem i'm having is that everything works with the way you suggested, but the mount animation is not being applied, only when all series are on.
