### ISSUE TITLE
Allow Null in Line and Other Charts.

### ISSUE THREAD

**Issue by sasori7** [apexcharts/apexcharts.js#1219]
**Is your feature request related to a problem? Please describe.**
My data is date based, however, it's not entered every day and I want to plot it over a series of days, say a month. 

**Describe the solution you'd like**
By using Null for days that have no data, a line could span the previous and next data entry points without any breaks.

**Describe alternatives you've considered**
I've thought about inserting dummy data to fill gaps.

**Additional context**
I've seen this in scale-connected apps like Health planet.
![Screenshot_20200115_235523_jp healthplanet healthplanetapp](https://user-images.githubusercontent.com/12153571/72444020-a484c780-37f2-11ea-8ffb-0e20a38bbca9.jpg)

**Comment by junedchhipa** [comment]
Hi @sasori7 
This has been requested before and may come in the future, but I have no ETA for it.
Similar to #146
