### ISSUE TITLE
Performance issues in Microsoft EDGE

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#122]
Hey,

Apexcharts runs noticeably slower on MS EDGE (tested on version 42), especially hovering over graph and displaying tooltip.

**Comment by junedchhipa** [comment]
Yeah, the interactivity is not very smooth on Microsoft Edge / IE11. I am in the process of optimizing tooltip code (along with fixing the null values bug).
Thanks for reporting

**Comment by jchamb** [comment]
I'm also seeing performance issues In chrome when having multiple charts with large data sets. When series is injected, screen freezes and throws tons of http://take.ms/g84Dl

Above is on a screen with 6 line charts, all with 12 series with 90 data points each. (Categorization visit counts across 90 days.)

should also note that I'm using vue-apexcharts, with options and series generated through vuex-getters.  

`<apexcharts
                                width="100%"
                                height="300"
                                type="line"
                                :options="trafficCount.options"
                                :series="trafficCount.series"
                            ></apexcharts>`
