### ISSUE TITLE
Combination of stacked and unstacked bar/column series

### ISSUE THREAD

**Issue by rognales** [apexcharts/apexcharts.js#1220]
**Is your feature request related to a problem? Please describe.**
Can we create stacked and unstacked bar/column graph? Since the setting for stacked is not part of the series but part of the chartOptions

**Describe the solution you'd like**
A stacked property that can be set per series

**Describe alternatives you've considered**
another graph libarary

**Additional context**
None

**Comment by junedchhipa** [comment]
@rognales Thanks for the suggestion, this has been requested before.
Closing it in favor of #196
