### ISSUE TITLE
The line mixed chart doesn't work after upgrading to 3.15.1

### ISSUE THREAD

**Issue by macoto-liu** [apexcharts/apexcharts.js#1221]
This originally worked when I use "npm-asset/apexcharts": "3.8.5". 

It issue can be reproduced when
1. xaxis.categories let only 1 item
2. xaxis.type is not specified

## Codepen

https://codepen.io/macoto-liu/pen/jOEvVZL

## Explanation

- What is the behavior you expect?
Get this works 

- What error message are you getting?

in the browser console (I tested this in Chrome)
```
apexcharts:6 Error: <path> attribute d: Expected number, "M -Infinity 305.11…".
apexcharts:6 Error: <g> attribute transform: Expected number, "translate(Infinity, 40)".
```

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by macoto-liu** [comment]
![image](https://user-images.githubusercontent.com/10680110/72585563-8a013a00-3929-11ea-8fd4-3728ab4d4143.png)


![image](https://user-images.githubusercontent.com/10680110/72585569-8ff71b00-3929-11ea-9bef-bee857574887.png)


Could you pls help check IE with latest version 3.15.2?

1 .the console report error call attributes 'contains" on undefined or null object
2. the grid didn't show
3. the starting Yaxis is not strating from 0.
