### ISSUE TITLE
xaxis is not scaled properly when using min or max values

### ISSUE THREAD

**Issue by akostarek** [apexcharts/apexcharts.js#1222]
## Codepen

Scaling of xaxis is incorrect after setting values for min/max/range properties for xaxis of scatter chart. More chart types could be affected. TIP: After zooming in scale seems to be fine.
[check last point placement on chart vs xaxis values](https://codepen.io/akostarek/pen/VwYGmyo) 
The same issue can be found on official example of scatter chart on [your website](https://apexcharts.com/javascript-chart-demos/mixed-charts/line-scatter/)

## Explanation
- What is the behavior you expect?
All data points x values should be matching xaxis value

- What is happening instead?
First points values are in-line with xaxis, scale seems to be linearly incorrect. Last data point has x value **9.2** and is displayed between **9.6 and 10.8** tick label on x-axis [see screenshot](https://files.fm/thumb_show.php?i=q7xx4k7t)

- What error message are you getting?
No error messages

**Comment by junedchhipa** [comment]
Thanks for reporting.
Fixed it, a patch will be released soon.

**Comment by akostarek** [comment]
Perfect, thank you!
