### ISSUE TITLE
Chart cannot be destroyed after v3.15.1

### ISSUE THREAD

**Issue by srcn** [apexcharts/apexcharts.js#1223]
## Codepen

[https://codepen.io/srcn/pen/abzKBab](https://codepen.io/srcn/pen/abzKBab)

## Explanation

- What is the behavior you expect?
`destroy()` method should destroy the chart and it should stay that way.

- What is happening instead?
`destroy()` method looks like it's destroying the chart but on window resize chart re-renders and comes back.

- What error message are you getting?
No error messages on vanilla but getting some on Angular and React, they can be seen on this
[Stackblitz](https://stackblitz.com/edit/ngapexcharts-destroy-issue?file=src%2Fapp%2Fcomponents%2Froute1.component.ts). Changing the route and resizing window will print out the errors on the browser's console.

**Comment by junedchhipa** [comment]
Thanks for reporting.
Yes, the last refactor broke this.
I will take a look soon.
