### ISSUE TITLE
Mixed charts (line and bar) with a length of 2 data points are not showing xaxis labels and with 1 is not even drawn.

### ISSUE THREAD

**Issue by bruno02100** [apexcharts/apexcharts.js#1224]
## Code sandbox

With 2 datapoints:
https://codesandbox.io/s/react-basic-example-egcvl?fontsize=14&hidenavigation=1&theme=dark

With 1 datapoint: 
https://codesandbox.io/s/react-basic-example-buxi2?fontsize=14&hidenavigation=1&theme=dark

## Explanation

- What is the behavior you expect?
I expect it to be drawn as it would be with 3 or more datapoints.
- What is happening instead?
It is not drawing xaxis labels or even the whole series when it's 1 datapoint.
- What error message are you getting?
NONE

**Comment by junedchhipa** [comment]
Thanks for reporting
This is fixed in the last commits
