### ISSUE TITLE
x-axis date annotations doesn't show if x-axis type is category

### ISSUE THREAD

**Issue by Darek64** [apexcharts/apexcharts.js#1225]
I need help.
Can annotations x-axis be added when x-axis is of "categories" type?

**Comment by junedchhipa** [comment]
Yes, you can.

```javascript
annotations: {
  xaxis: [
    {
      x: 'Bananas',
      label: {
        borderColor: '#775DD0',
        offsetY: 0,
        style: {
          color: '#fff',
          background: '#775DD0'
        },
        text: 'Bananas are good'
      }
    }
  ]
},
xaxis: {
  categories: [
    'Apples',
    'Oranges',
    'Strawberries',
    'Pineapples',
    'Mangoes',
    'Bananas',
    'Blackberries',
    'Pears',
    'Watermelons',
    'Cherries',
    'Pomegranates',
    'Tangerines',
    'Papayas'
  ],
}
```

The above code works fine.

**Comment by Darek64** [comment]
Sorry, I would like to add.
I want to add this to your code candlestic-chart
"I have enabled zooming on category x-axis since v3.15.0 which will help to solve the issue of gaps."

Live example - https://apexcharts.com/javascript-chart-demos/candlestick-charts/category-x-axis/

**Comment by junedchhipa** [comment]
You're right.
That doesn't work. I will get on it soon.

**Comment by junedchhipa** [comment]
You will have to provide the date format for annotation in the same format as they appear on the xaxis.
![Screen Shot 2020-01-17 at 9 32 52 PM](https://user-images.githubusercontent.com/17950663/72626784-50542180-3971-11ea-9be2-1ca40126520b.png)


For eg., the screenshot above has the date in the format "Oct 06 04:00".
So, you will need to put the same in `annotations.xaxis`

```javascript
annotations: {
  xaxis: [
    {
      x: 'Oct 06 14:00',
      borderColor: '#00E396',
      label: {
        borderColor: '#00E396',
        style: {
          fontSize: '15px',
          color: '#fff',
          background: '#00E396'
        },
        offsetY: -10,
        text: 'Vertical'
      }
    }
  ]
}
```

**Comment by yoimnik** [comment]
@junedchhipa hey, it seems like xaxis annotations don't work if xaxis is category, the inputted data is string timestamps, and the tickPlacement is 'between'.

if i switch the tickPlacement to 'on', i see the xaxis annotation.

i think this is a bug

**Comment by fabnemEPFL** [comment]
(well there is a work-around: just pretending x-axis labels are shown, then set them with a font size of 0)
