### ISSUE TITLE
chart.updateSeries() doesn't update X Axis.

### ISSUE THREAD

**Issue by GalacticSun** [apexcharts/apexcharts.js#123]
I load in new data but the X axis values (the vertical values representing, in my case, price data values) don't update according to the new data.  Am I doing something wrong?  Thanks.

**Comment by junedchhipa** [comment]
Did you found the solution? Or you misconfigured something?

**Comment by GeoAbbey** [comment]
I'd appreciate if this issue can be addressed. I'm also facing the same issue and have a couple of folks experiencing such as well.

**Comment by junedchhipa** [comment]
Can you create a codepen demo for what you're experiencing?

**Comment by GeoAbbey** [comment]
I will do that right away and share as soon as possible.

Thanks

**Comment by GeoAbbey** [comment]
@junedchhipa Here is the codepen:

https://codepen.io/GeoAbbey/pen/BbKQYY

I look forward to your solution. Thanks

**Comment by junedchhipa** [comment]
That's a serious one! I will look into it asap, thanks for reporting.

**Comment by GeoAbbey** [comment]
> That's a serious one! I will look into it asap, thanks for reporting.

Thanks boss. I will be expecting your response soon.

**Comment by junedchhipa** [comment]
Well, no. That was not a bug in the chart. You forgot to provide chart.id in the main configuration.
Check the codepen - https://codepen.io/apexcharts/pen/xBVgRq

The `exex()` function expects a chartID, not DOM element :)

I will update the docs to make it clear to avoid confusion for other users.

**Comment by GeoAbbey** [comment]
Thanks so much @junedchhipa. I will effect it in my Vue app and give you feedback soon enough

**Comment by GeoAbbey** [comment]
@junedchhipa, the following is the screenshot of the error message I got when I implemented the same thing in my Vue app.


![error-message](https://user-images.githubusercontent.com/27980807/53679330-a376a480-3ccb-11e9-9d0c-ae541724d5fc.png)

**Comment by junedchhipa** [comment]
You don't need to call `exec()` method in Vue
If you update the props passed to that `<apexchart>` component, it should update series and options automatically.

Can you create a codesandbox example? Please use this Vue template - https://codesandbox.io/s/pwwz8009n0

Also, please specify which ApexCharts version you have used in your Vue app.

**Comment by GeoAbbey** [comment]
> You don't need to call `exec()` method in Vue
> If you update the props passed to that `<apexchart>` component, it should update series and options automatically.
> 
> Can you create a codesandbox example? Please use this Vue template - https://codesandbox.io/s/pwwz8009n0
> 
> Also, please specify which ApexCharts version you have used in your Vue app.

On it

**Comment by GeoAbbey** [comment]
Here is the Codesandbox link:

https://codesandbox.io/s/l7kwz0ow4m

**Comment by GeoAbbey** [comment]
> You don't need to call `exec()` method in Vue
> If you update the props passed to that `<apexchart>` component, it should update series and options automatically.
> 
> Can you create a codesandbox example? Please use this Vue template - https://codesandbox.io/s/pwwz8009n0
> 
> Also, please specify which ApexCharts version you have used in your Vue app.


@junedchhipa When I removed `exec() ` and tried to change the data directly, I got the same error message in my Vue app.

**Comment by junedchhipa** [comment]
I have updated versions (apexcharts@3.5.0 and vue-apexcharts@1.3.0)
Also, added `import ApexCharts from 'apexcharts'` at the top.

This has fixed the issue.
Codesandbox - https://codesandbox.io/s/pknk9j097x

**Comment by GeoAbbey** [comment]
Wow! This worked like magic. 

Thank you so much. It means a lot to me.

**Comment by GeoAbbey** [comment]
> I have updated versions (apexcharts@3.5.0 and vue-apexcharts@1.3.0)
> Also, added `import ApexCharts from 'apexcharts'` at the top.
> 
> This has fixed the issue.
> Codesandbox - https://codesandbox.io/s/pknk9j097x

One more thing. I don't know if you noticed that there is a mismatch of x-axis label and the chart area is clipped at both sides.

I tried to fix these by following the steps below:
1. I set `tickAmount: 'dataPoints'`, but it didn't work.
2. I set `tickPlacement: 'on'`, but it brought back the initial error you fixed.

I will appreciate if you can help look into this issue as well. Thanks

**Comment by junedchhipa** [comment]
It seems like a bug. Been trying for an hour, but doesn't seems fixable easily.
I will update the thread when the bug is fixed.

**Comment by GeoAbbey** [comment]
Alright. Thanks a bunch

**Comment by GeoAbbey** [comment]
> It seems like a bug. Been trying for an hour, but doesn't seems fixable easily.
> I will update this thread when the bug is fixed.

Hello @junedchhipa 
Have you found any way around the bug?
Our project is apparently on hold now because the project solely depends on the chart which we do not plan to change.
Please help us look into it. Thanks

**Comment by junedchhipa** [comment]
Can you please try v3.6.3 ?

**Comment by GeoAbbey** [comment]
Alright. I will try it out and give you feedback soon.
Thanks for your quick response.

**Comment by GeoAbbey** [comment]
> Can you please try v3.6.3 ?

Thank you so much, boss. Everything is working so well now.
Consider me as one of your biggest fan.

**Comment by GeoAbbey** [comment]
Hi @junedchhipa 

I have been enjoying the solution you provided on this issue until I tried to apply it to a bar chart with multiple data, and the problem reappeared.

The following is the codesandbox link to it: https://codesandbox.io/s/l7kwz0ow4m

Kindly help check it out. Thanks

**Comment by junedchhipa** [comment]
You had a configuration error in updateSeries method.
I have updated `series` directly in updateOptions method to avoid an additional call.

```javascript
    ApexCharts.exec("chart1", "updateOptions", {
        series: [
        {
          name: "Series1",
          data: [51, 42, 109, 38, 47]
        },
        {
          name: "Series2",
          data: [56, 90, 12, 32, 44]
        },
        {
          name: "Series3",
          data: [22, 43, 21, 100, 56]
        }
      ],
       xaxis: {
          categories: ["2015", "2016", "2017", "2018", "2019"]
        }
      });
```

Here is the update demo - https://codesandbox.io/s/vue-issue-with-x-axis-category-1h964

**Comment by beisong7** [comment]
i took a different approach and got it to work using the **chart** variable

```js
function changeData() {
  console.log('change data called')
  chart.updateOptions( {
    xaxis: {
      categories: ["A", "B", "C"]
    }
  });
  chart.updateSeries([
    {
      data: [32, 44, 31]
    }
  ])
}`

**Comment by himanshukk81** [comment]
> ```js
>  chart.updateOptions( {
>     xaxis: {
>       categories: ["A", "B", "C"]
>     }
>   });
>   chart.updateSeries([
>     {
>       data: [32, 44, 31]
>     }
>   ])
> ```



> Can you please try v3.6.3 ?



> i took a different approach and got it to work using the **chart** variable
> 
> ```js
> function changeData() {
>   console.log('change data called')
>   chart.updateOptions( {
>     xaxis: {
>       categories: ["A", "B", "C"]
>     }
>   });
>   chart.updateSeries([
>     {
>       data: [32, 44, 31]
>     }
>   ])
> }`
> ```

Thanku So much this save my one day.

**Comment by ssergiorivera30** [comment]
Final solution

https://stackoverflow.com/a/65821013/11302398

**Comment by mrabaev48** [comment]
<div class='customerChart' id='customerChart' ref='customerChart'></div>

this.chart?.exec('customerChart', 'updateOptions', {
         xaxis: {
            categories: options.xaxis.categories
         }
      })
      
      it doesn't work...
      I stored chart instance in a variable. When I tried update options I got an error:
      
      "[Vue warn]: Error in v-on handler (Promise/async): "TypeError: _a.exec is not a function""
      
      Could somebody give any tips?

**Comment by krishnadavuluri** [comment]
I am using grouped bar chart in react.
Parent component is sending different data on click of 3 different button to child component (which renders apex chart).
Chart is responding only two times but when I am consoling data , data is correct but not shown in the chart.
If you could solve this is issue would be great help for me.
Thanks

**Comment by lidiyaan** [comment]
ApexCharts with angular 2:
https://stackoverflow.com/a/68203219/9283313

**Comment by Mersal-Mohamed2** [comment]
to update horizontal bar chart and also area chart i use this techniques

this.horizontalBarOptions = {
                ...this.horizontalBarOptions, ...{
                    series: [{
                        data: data,
                        name: seriesName
                    }],
                    xaxis: {
                        categories: categories
                    }
                }
            }
            chart.updateSeries([{
                data: data,
                name: seriesName
            }])
            chart.updateOptions({
                xaxis: {
                    categories: categories
                }
            })

**Comment by AlbanRFC** [comment]
**> The `exex()` function expects a chartID, not DOM element :)**
> 
ApexCharts.exec('mixChart', "updateOptions", {
                        xaxis:
                            {
                                categories: ['2020', '2021',  '2022'],
                            },
                        series: [
                            {
                                name: 'data1',
                                data: [1,2,3],
                            },
                            {
                                name: 'data2',
                                data: [4,5,6],
                            },
                            {
                                name: 'data3',
                                data: [7,8,9],
                            },
                        ]
                    });
###

**Comment by Mendelski** [comment]
In docs: 

_In cases where you want to update both the series and options together, it is recommented to just call the updateOptions method as shown below._

```
chart.updateOptions({
  series: [{
    data: [{
      x: "02-02-2002",
      y: 44
    }, {
      x: "12-02-2002",
      y: 51
    }]
  }],
  xaxis: {
    position: 'top'
  }
}) 
```

Link: 
https://apexcharts.com/docs/methods/#appendSeries
