### ISSUE TITLE
Wrong annotation Xaxis

### ISSUE THREAD

**Issue by IlyaChubko** [apexcharts/apexcharts.js#1233]
Hello!
Annotations X-axis is wrong. I set x: 22, x2: 30, but line was drowing start with x = 2,5
https://codepen.io/ilyachubko/pen/wvBQgpe
![image](https://user-images.githubusercontent.com/6832799/72704647-7395f100-3b6a-11ea-8a61-80e8d7c19661.png)

**Comment by junedchhipa** [comment]
As your x values contain numeric values, you should change the xaxis type

```javvascript
xaxis: {
  type: 'numeric'
}
```

After changing the xaxis type, annotations should work as expected.

**Comment by IlyaChubko** [comment]
Thank you!!!
