### ISSUE TITLE
Multiple donut charts conflict each other

### ISSUE THREAD

**Issue by BrummbQ** [apexcharts/apexcharts.js#1234]
Hello, please check following pen:

https://codepen.io/brummbq/pen/OJPajQw

Issue:
1. click on any slice in first donut (shows label in the middle)
2. hover over second donut (anywhere) and move pointer outside again => the selection of the first donut is displayed in the second donut

So there seems to be some kind of link/duplicate id between the 2 separate charts

**Comment by junedchhipa** [comment]
Thanks for reporting the bug, just fixed it.
This fix will be shipped in the next patch release.
