### ISSUE TITLE
Format axis titles with commas denoting thousands, hundred thousands, etc.

### ISSUE THREAD

**Issue by ypatil12** [apexcharts/apexcharts.js#1236]
Codepen
https://codepen.io/srcn/pen/jOEeZzy
![chart_example](https://user-images.githubusercontent.com/40046473/72742326-78ad6d00-3b77-11ea-9a7e-d5c0e0301fce.JPG)

I have the chart above, and would like to format the y-axis labels such that they display "4,000" instead of "4000"

Explanation
**What is the behavior you expect?**
If I add the string "4,000" in the series chart would display 4,000 on the y-axis

**What is happening instead?**
The library reads "4,000" as 4 and also displays 4000 as 4000.

**Describe alternatives you've considered**
Could I write a custom function to do this?

**Comment by natequreshi** [comment]
hello, I am trying adding this into wpdatatables, but no luck, still not working any advice if I want to add this into wpdatatables for worpress so yaxis values can be shown with commas.

**Comment by VishalGugnani** [comment]
I want to Convert the Thousand Value to K for the Pie Chart., But unable to do that

 value: {
                                show: true,
                                fontSize: '21px',
                                fontFamily: '"Inter", sans-serif',
                                color: '#05004E',
                                fontWeight: 'bold',
                                offsetY: +5,
                                formatter: function (value) {
                                    let val = Math.abs(value)
                                    if (val >= 1000) {
                                        val = (val / 1000).toFixed(0) + ' K'
                                    }
                                    return val
                                }
                            },
                            total: {
                                show: true,
                                label: 'Total HIX',
                                fontFamily: '"Inter", sans-serif',
                                fontSize: '13px',
                                colors: '#222B45',
                                fontWeight: 400,
                                formatter: function (w) {
                                    // By default this function returns the average of all series. The below is just an example to show the use of custom formatter function
                                    return 3 + "k"
                                }

                            }
