### ISSUE TITLE
Custom label for bubble chart, instead of "Size"

### ISSUE THREAD

**Issue by billytunin** [apexcharts/apexcharts.js#1238]
Hi apexcharts team! Thanks for taking the time to read this.

When creating a bubble chart, I see no option to actually give a name to the third axis (Z). This series value is always called "Size". I know there are different ways to give different names to X 
 and Y values. For example, for x-axis, using the "name" property within each object of the "data" array of the "series" property. For y-axis, using the formatter function would suffice. So what I'm asking, esentially: is there a way to call the "bubble size" something other than "size". Is this possible? Or are the bubble charts made that way deliberately? Meaning... I shouldn't be trying to change that label?

I saw this issue that may be related: https://github.com/apexcharts/apexcharts.js/issues/846 -> but the issue there is trying to format the size value inside the dataLabels option. Meaning it would only format the value. On the other hand, I'm talking about naming the Z-axis "Size" something other than Size. For example "Discounts". So, in the tooltip, it would show "Discounts: _[value]_" instead of "Size: _[value]_"
![image](https://user-images.githubusercontent.com/15022688/72771003-4e42ca80-3bde-11ea-904d-d2075a1727db.png)

Does this question I'm doing make any sense?

**Comment by junedchhipa** [comment]
Sure, there is a property called `tooltip.z.title` which should help.

Can you try this?
```javascript
tooltip: {
  z: {
    formatter: function(val) {
      return val + '$'
    },
    title: 'Discount'
  }
}
```

**Comment by billytunin** [comment]
@junedchhipa awesome! That worked like a charm :D . Thank you very much.

Was this described anywhere at ApexCharts docs? (https://apexcharts.com/docs/) . I'm just asking to know if I missed it. Otherwise I think it would be a good idea to add this somewhere.

Once again, thanks for the fast response. We can now close this issue

**Comment by junedchhipa** [comment]
@billytunin Maybe I missed documenting this in the correct place.
It's mentioned in the tooltip section of options
https://apexcharts.com/docs/options/tooltip#ztitle

**Comment by ravicampbell** [comment]
Is there a way of doing this in non-bubble charts? I want to add a custom labeled parameter to my tooltip in a heatmap

**Comment by junedchhipa** [comment]
@ravicampbell You should try `tooltip.custom` property and build a customized HTML tooltip.
Docs: https://apexcharts.com/docs/options/tooltip/#custom
Codepen: https://codepen.io/apexcharts/pen/NBdyvV

**Comment by ravicampbell** [comment]
Ok great, could you provide the code for the tooltip for x,y,z series?
