### ISSUE TITLE
Show all series in a tooltip in a grouped column chart with multiple series.

### ISSUE THREAD

**Issue by C3maLi** [apexcharts/apexcharts.js#1240]
Hi's,  

I want to show the data series as an example below!
Is it possible to do this?
Thank you.

[(https://www.fusioncharts.com/charts/column-bar-charts/grouped-column-chart-with-multiple-series?framework=javascript)](url)

**Comment by junedchhipa** [comment]
Yes, take a look at this example 
https://apexcharts.com/javascript-chart-demos/column-charts/basic/

**Comment by C3maLi** [comment]
Thanks for your return,

The sample you provided does not exactly meet what I want.
I want to show it as a group.
I have 2 data series and I want to show them in a single tooltip. I want to see the information of two data series in the tooltip when I do column hover instead of hovering to each bar.

I'm milking the image below by making the chart type line, making the series types column and using the custom template.
But this is not a very health situation.

For example;

![Untitled](https://user-images.githubusercontent.com/3233264/72804813-6ceaa500-3c62-11ea-83bb-9ca982150a23.png)

**Comment by junedchhipa** [comment]
Try
```javascript
tooltip: {
  shared: true
}
```

**Comment by C3maLi** [comment]
> Try
> 
> ```js
> tooltip: {
>   shared: true
> }
> ```

Thank you, is working (:

**Comment by C3maLi** [comment]
I'm disturbing again

When I activate the shared tooltipe feature, the tooltip header appears in the column without data. It is not shown only because it has no content.

I want to hide the tooltip when two data series are empty. Is it possible to do this dynamically?

Sample;
`y: {
  formatter: function (val, data) {
    data.w.config.tooltip.enabled = false;
  }
}
`
![Untitled](https://user-images.githubusercontent.com/3233264/72980017-b36b0b80-3dea-11ea-84e7-d3bd61ea7a23.png)

**Comment by junedchhipa** [comment]
Seems like a bug.
I will take a look soon.

**Comment by C3maLi** [comment]
I encounter a situation like this is it normal?

I have a 2nd Indicator, no problem appears when both of them are active. When I passive my first indicator, all the series in the data set that is in the 2nd indicator are displayed as "null" and only the tooltip appears on the chart.

You can see more detailed from the image below.
![apexchart](https://user-images.githubusercontent.com/3233264/73050426-ef58ac00-3e90-11ea-9014-e98c6e2bacd7.gif)

**Comment by junedchhipa** [comment]
Can you please post a codepen demo to reproduce it easily on my side?

**Comment by C3maLi** [comment]
Here you can check it, when you make Legend 1 passive, you can see the problem I mean.

https://codepen.io/CemaLi/pen/jOEJOLr

**Comment by AshwinidBawankar** [comment]
(shared: true) is not working in custom tooltip

**Comment by AshwinidBawankar** [comment]
tooltip: {
  shared: true
}    is not working in custom tooltip

**Comment by mnkcoder** [comment]
for anyone who land here with the same issue, I was able to fix this with below settings for tooltip. Apparently I had to explicitly set intersect to false along with shared set to true

`tooltip: {
shared: true,
intersect: false
}`

**Comment by junedchhipa** [comment]
The original issue is no more reproducible, hence closing it.
