### ISSUE TITLE
Series index is always 0

### ISSUE THREAD

**Issue by Hurenka** [apexcharts/apexcharts.js#1241]
## Codepen
The problem is in seriesIndex, it's always 0. Tooltip `shared: false` didn't help. 

I would like each bar to be colored in color,  matching the series name on yaxis.
In this case, this is important because each "type" from yaxis can appear several times - thus multiple colored bars in a single row. If I put `distributed: true` that only brings each bar to be colored different, even those which belong to the same category. I've tried to color them with function, but faced the problem with index. 

https://codepen.io/catherin-waverly/pen/JjowdEr

## Explanation

Two of the bars are colored in yellow and red, and the rest are green.
But all bars are red.

**Comment by junedchhipa** [comment]
Fixed it.
Although, in your example, as you had just 1 series, seriesIndex being 0 if `distributed` false is correct. If `distributed` is true, seriesIndex and dataPointIndex will be the same.

I have modified your example a little bit which should work even if `distributed` is false.

```javascript
colors: [
  function({ value, seriesIndex, dataPointIndex, w }) {
    let i = w.config.series[0].data[dataPointIndex]['x']

    if (i === 'tari') {
      return '#e9184b'
    } else if (i === 'metrics') {
      return '#ff980b'
    } else {
      return '#689642'
    }
  }
]
```
![Screen Shot 2020-01-21 at 6 50 47 PM](https://user-images.githubusercontent.com/17950663/72809291-5dc71f80-3c81-11ea-820f-c45006b9d9eb.png)
