### ISSUE TITLE
Mixed Chart with both Column and Stacked Bar

### ISSUE THREAD

**Issue by thellimist** [apexcharts/apexcharts.js#1242]
Is there a way to have mixed charts with 
1. stacked bar
2. column
3. line 

charts together. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/6690196/72882217-32a20600-3d3d-11ea-8e50-45a45e71d178.png">

Is there a way to have column and stacked bar chart in the same graph with another line chart?

**Comment by junedchhipa** [comment]
Sorry, that's not achievable currently.
Grouped and Stacked column charts have been suggested before in this [thread](#196) and may come in the future.
Related to #196, #26

**Comment by JohnRomanski** [comment]
The way that another graphing library handles this is rather elegant.
For each series, you can pass in a stack id.
```
       <Bar dataKey="female" stackId="a" fill="#8884d8" />
       <Bar dataKey="male" stackId="a" fill="#82ca9d" />
       <Bar dataKey="uv" fill="#ffc658"/>
```
https://jsfiddle.net/alidingling/9hjfkp73/

**Comment by L1qu1d1c3** [comment]
+1 to this feature!

**Comment by NylePudding** [comment]
Likewise, I would really love this feature! Since you can specify the type of chart as part of the series, I would expect it to be possible to include some extra options such as stacked that only applies to that series/type combination. :)

**Comment by predam** [comment]
Hello guys, any update on this?

**Comment by fatmag8** [comment]
Hello guys, any update on this in 2022 :) ?

**Comment by AngelinaMagidova** [comment]
Hello guys!
Any updates?
I happy to use your library, but want to combine stacked bar chart with any charts...

**Comment by richard-ioi** [comment]
Hello guys !

Any updates on this ? Your library is so great and would be so perfect with this feature, it would be very useful.

**Comment by AntoineDrsl** [comment]
Hello ! I am also looking for this feature !

**Comment by yusuf-multhan** [comment]
+1

**Comment by code-zeen** [comment]
Hello! This would be an amazing feature that I would love to implement into my current project!

**Comment by rnenjoy** [comment]
Me too!!
