### ISSUE TITLE
Radial Bar Chart rendered differently on Firefox vs. Chrome

### ISSUE THREAD

**Issue by rvergar7** [apexcharts/apexcharts.js#1243]
Hello, thanks in advance for this great library. 

I'm currently working on a document where I need to import a Radial Bar Chart via the dataURI method. During this I noticed that the Radial Bar Chart is rendered differently on Firefox vs. Chrome. On Firefox there appears to be some extra whitespace below the chart. 

This doesn't cause too much of an issue using a browser but when I'm generating the document, if the user uses Firefox then the formatting is thrown off by this whitespace. I am using several different charts in the document and the Radial Bar Chart is the only one that has this behavior.

Codepen: https://codepen.io/rvergar7/pen/xxbMVjr 

**Chrome:**
<img width="451" alt="chrome render" src="https://user-images.githubusercontent.com/38929128/72934498-91a15400-3d18-11ea-9b6c-55a39c7bc79f.png">

**Firefox**
<img width="455" alt="firefox render" src="https://user-images.githubusercontent.com/38929128/72934508-9960f880-3d18-11ea-9038-2ce5c7f906c9.png">

**Comment by junedchhipa** [comment]
I checked in Firefox and confirm the bug.
It will be addressed soon.

**Comment by cymig** [comment]
HI @junedchhipa,

It feels like the bug is still there in apexcharts v3.19.2. There's still some extra whitespace below the chart on Firefox. In addition, Radial Charts have the bottom part cut off on Chrome. Not sure if this is a known bug?

Thanks

On my local project:
**Firefox (Version 76.0.1 (64-bit))**
![image](https://user-images.githubusercontent.com/27445300/83280625-f24c0c00-a1a4-11ea-9569-a015bdd8d895.png)

**Chrome (Version 83.0.4103.61 (Official Build) (64-bit))**
![image](https://user-images.githubusercontent.com/27445300/83280748-13146180-a1a5-11ea-813c-d10d5302d5e3.png)

This is replicable here on codepen for reference:
https://codepen.io/apexcharts/pen/VEGyGx

**Comment by junedchhipa** [comment]
@cymig Your codepen link is wrong. Please provide the correct codepen link.

**Comment by pierre-alain-b** [comment]
I have the same behavior: 
FF 88 gives:
![image](https://user-images.githubusercontent.com/386857/115979734-ec62d480-a587-11eb-96f1-5e0026ecbf60.png)

Chromium 89 gives:
![image](https://user-images.githubusercontent.com/386857/115979743-fab0f080-a587-11eb-95a3-e69ef91227e5.png)

**Comment by pierre-alain-b** [comment]
The issue vanished when I added
sparkline: { enabled: true }
in the chart options.

**Comment by pierre-alain-b** [comment]
I guess this issue can now be closed again.

**Comment by digitalmouse** [comment]
Noting this here: using apexcharts v3.33.0 in Node with Vue2

Bottom cutoff _still_ appears in latest Chrome 99.0.4844.51 (Official Build) (64-bit) but not in Firefox 98.0b10 (64-bit).

It seems to revolve around a negative startAngle, as combinations using positive numbers work just fine.

Using startAngle: -180, endAngle: 90 in plotOptions{} :

![chrome_GLTdU8FxrI](https://user-images.githubusercontent.com/458497/157424235-5241a57f-bd40-459b-91fe-309939af5687.png)

Oddly enough, the cutoff disappears when I change the endAngle to 103 :

![chrome_E7BfREDv2d](https://user-images.githubusercontent.com/458497/157425010-885f7f03-ed6f-4413-bde7-d85919007394.png)

As I experimented with reducing the endAngle back down from 110 to 90, the cutoff gradually gets smaller until around 103-104 it stops 'shrinking'.  At least enough that you never notice it. :)
