### ISSUE TITLE
killSVG function returning a promise

### ISSUE THREAD

**Issue by Blakko** [apexcharts/apexcharts.js#1245]
# Bug report

## Explanation

Currently the killSVG function (contained in `src/modules/helpers/Destroy.js`) returns a Promise:
```javascript
  killSVG(draw) {
    return new Promise((resolve, reject) => {
      draw.each(function(i, children) {
        this.removeClass('*')
        this.off()
        this.stop()
      }, true)
      draw.ungroup()
      draw.clear()
      resolve('done')
    })
  }
```

Looks like the promise is not needed here, but if it really is you should take care of it in the `clearDomElements` function (line 66) where `Paper` may be removed before the `killSVG` function gets executed
```javascript
this.killSVG(domEls.Paper)
domEls.Paper.remove()
```

**Comment by junedchhipa** [comment]
Good catch!
Fixed it
