### ISSUE TITLE
Add the tickAmount for datetime!

### ISSUE THREAD

**Issue by aryaroudi** [apexcharts/apexcharts.js#1246]
# Feature request

In the documentation is mentioned: 
`Note: tickAmount doesn’t have any effect when xaxis.type = datetime`

I don't understand why this has been removed and what is the workaround if you want to add a chart that works base on categories that contain an array of times:

![image](https://user-images.githubusercontent.com/43990136/73068906-aca4cd00-3eac-11ea-9022-d2642460f74a.png)

 and you just want to show the label for only each hour:

![image](https://user-images.githubusercontent.com/43990136/73068749-4750dc00-3eac-11ea-9ab8-c02cc5b6346f.png)

and then when you hover on the chart you'll be able to see them per 5 minutes. Is there any other way to achieve that?

**Comment by junedchhipa** [comment]
If you don't want auto-generated timescale x-axis, you can easily switch to `xaxis.type: 'category'` and the x-axis will display all the labels (the labels will only be hidden if they overlap).

The only downside to this is that you will have to format the x-axis labels using a 3rd party library (such as day.js) to make it look pretty.

**Comment by IlyaChubko** [comment]
Hello!
I changed xaxis.type to 'category' and my x-axis labels is unreadable.
![image](https://user-images.githubusercontent.com/6832799/73131890-e5b37d80-4023-11ea-8464-3ce645c81f3c.png)

Can I change duration to vertical and format text to 'dd.mm.yyyy hh:MM:ss'?

**Comment by junedchhipa** [comment]
For now, I recommend using a lightweight date library called [dayjs](https://github.com/iamkun/dayjs) to format the date and times in the category x-axis chart. 

In the future, I will add support for datetime formatting for category x-axis too.

To turn off labels rotation, you can do
```javascript
xaxis: {
  labels: {
    rotate: 0,
    trim: false
  }
}
```

**Comment by IlyaChubko** [comment]
After add labels rotate my x-axis labels is worse unreadable:
![image](https://user-images.githubusercontent.com/6832799/73132200-b3f0e580-4028-11ea-9e8b-fb38cacd0292.png)

**Comment by junedchhipa** [comment]
@IlyaChubko That's a bug. I will take a look soon.

**Comment by IlyaChubko** [comment]
I set this values:
							xaxis: {
								type: 'category',
								labels: {
									rotate: -90,
									trim: false
								}
							}

![image](https://user-images.githubusercontent.com/6832799/73140424-c9e2c280-4089-11ea-93e1-6624f52bea51.png)

**Comment by aryaroudi** [comment]
> If you don't want auto-generated timescale x-axis, you can easily switch to `xaxis.type: 'category'` and the x-axis will display all the labels (the labels will only be hidden if they overlap).
> 
> The only downside to this is that you will have to format the x-axis labels using a 3rd party library (such as day.js) to make it look pretty.

I have tried that but it doesn't seem it makes any change, still getting the same ticks amount = the series length.

I have a category of the array with 20 elements and series with the same elements inside. When the type is `category` and the tickAmout is 5, for example, logically it must show 4 ticks on the `xaxis` but I'm still getting 20 ticks

**Comment by danactive** [comment]
When I change my _datatime_ to _category_ then the **xaxis** **formatter** no longer provides defined values for 
`formatter: function(value, timestamp, index) {`
All three params are undefined for 90% of the chart

### Datetime
<img width="398" alt="Datetime" src="https://user-images.githubusercontent.com/1093286/82383449-a9e16100-99e2-11ea-91a6-e2870c2f5f4d.png">


### Category
<img width="416" alt="Category" src="https://user-images.githubusercontent.com/1093286/82383375-81f1fd80-99e2-11ea-8ad7-93c7b3e8f496.png">
