### ISSUE TITLE
Set color for a specific marker in series in a Scatter Chart

### ISSUE THREAD

**Issue by LaurenceM10** [apexcharts/apexcharts.js#1247]
Hello

Is there any way to set a different color for a specific marker in a scatter chart?
If there isn't, it would be genius to be added

**Comment by junedchhipa** [comment]
If you format your data-series in XY format, you can do it easily.


```javascript
series: [
  {
    name: 'Points',
    data: [
      {
        x: 1,
        y: 2.14
      },
      {
        x: 3.2,
        y: 5.8
      },
      {
        x: 3.8,
        y: 6.04,
        fillColor: '#111'
      },
      {
        x: 4.55,
        y: 6.77
      }
    ]
  }
]
```

**Comment by LaurenceM10** [comment]
I could not find this in the documentation

**Comment by junedchhipa** [comment]
Sure, I will add it.

**Comment by LaurenceM10** [comment]
@junedchhipa Thank you!

**Comment by xaah** [comment]
Hello,
Is this still possible to do? I'm not getting any results from adding `fillColor` to the XY data points. Is there a complete example that includes this that I could have a look at if possible?

**Comment by KLudvig** [comment]
Hi, old question but is there a possibility to do it like this but add a colorized border instead? 

Tried strokeColor: '#111' but didn't work.
