### ISSUE TITLE
Datalabels not transparent when hovering different legend 

### ISSUE THREAD

**Issue by bruno02100** [apexcharts/apexcharts.js#1250]
# Bug report

When hovering the legend of a specific serie the datalabel of other series when they have backgrounds are not getting the transparency.

In this case I am hovering the green legend and the other datalabels are as opaque as the one being hovered.

![image](https://user-images.githubusercontent.com/24684612/73140312-e249e180-4077-11ea-9741-05f893acc7b8.png)

## Explanation

- What is the behavior you expect?
Other datalabels should be as transparent as the lines or columns
- What is happening instead?
The datalabels are opaque
- What error message are you getting?
none

**Comment by junedchhipa** [comment]
Thanks for reporting.
It will be addressed soon.
