### ISSUE TITLE
Draw points in missing/null values chart

### ISSUE THREAD

**Issue by IlyaChubko** [apexcharts/apexcharts.js#1252]
Hello!
On chart with missing/null values don't draw separate points.
https://apexcharts.com/javascript-chart-demos/line-charts/null-values
Johnny {4: 12}

It display only with mouse over.
![image](https://user-images.githubusercontent.com/6832799/73156108-b5d0ac80-40ed-11ea-9092-a98e083010d9.png)
![image](https://user-images.githubusercontent.com/6832799/73156115-bbc68d80-40ed-11ea-950d-399509f257e9.png)

**Comment by junedchhipa** [comment]
Yes, I confirm the bug. It will be addressed soon.

**Comment by junedchhipa** [comment]
Fixed it in this [commit](https://github.com/apexcharts/apexcharts.js/commit/ec88e29fd503f08a1424764b77cf05dd027bf840)

Patch will be released soon.

**Comment by darlandieterich** [comment]
this so bad performance when set null points....in V3.19
