### ISSUE TITLE
YAxis of line chart not scaling to fit line chart after 3.15.2

### ISSUE THREAD

**Issue by dagstuan** [apexcharts/apexcharts.js#1253]
After upgrading apexcharts I noticed that some of my graphs are not scaling correctly anymore. The issue is related to charts where the min and max values are all between `0` and `1.99`. If the max value of a dataset is larger than `2` the graph scales correctly.

I reproduced a minimal case here: https://codesandbox.io/s/wispy-cloud-z1yeu

I believe this issue was introduced when attempting to fix #1222 and #1224 in https://github.com/apexcharts/apexcharts.js/commit/21995a9071325c0e6dbd7ad8a608a6063c3a85df#diff-b0f2f61199c8b822e9ea4d1bfc7b6e04L118

**Comment by dagstuan** [comment]
I also noticed that downgrading apexcharts in codesandbox to version `3.15.1` or earlier fixes the issue, so the bug was introduced in `3.15.2`

**Comment by junedchhipa** [comment]
Thanks for the report.
Fixed it.
