### ISSUE TITLE
Set interval for Y 1,000s or $2,000s and X by 5,000 and 10,000 dynamically in Scatter Chart

### ISSUE THREAD

**Issue by LaurenceM10** [apexcharts/apexcharts.js#1256]
Hi, guys

There is a way to set interval for Y 1,000s or $2,000s and X by 5,000 and 10,000 dynamically in Scatter Chart?

**Comment by junedchhipa** [comment]
If you meant setting the range of x-axis and y-axis scales dynamically, then, yes. 
Setting min and max values in x-axis and y-axis can be done dynamically using the `updateOptions()` method of ApecCharts.

**Comment by LaurenceM10** [comment]
@junedchhipa do you a react example of this?
