### ISSUE TITLE
How I fixe bar chart on center?

### ISSUE THREAD

**Issue by kielkow** [apexcharts/apexcharts.js#1257]
import React, { useState, useEffect } from 'react';
import Chart from 'react-apexcharts';
import { Container } from './styles';

export default function Dashboard() {
  const [options, setOptions] = useState({});

  const [series, setSeries] = useState([]);

  useEffect(() => {
    function chartData() {
      setOptions({
        chart: {
          id: 'basic-bar',
          height: 4000,
        },
        xaxis: {
          categories: [
            'Clientes Pagantes',
            'Anunciantes Pagantes',
            'Total Clientes',
            'Total Anunciantes',
            'Novos Clientes 7 dias',
            'Novos Clientes Hoje',
            'Novas Anunciantes 7 dias',
            'Novas Anunciantes Hoje',
            'Ofertas criadas',
            'Ofertas aceitas',
          ],
        },
      });

      setSeries([
        {
          name: 'Dashboard',
          data: [200, 400, 450, 500, 490, 600, 700, 910],
        },
      ]);
    }

    chartData();
  }, []);

  return (
    <Container className="app">
      <Chart
        options={options}
        series={series}
        type="bar"
        width="750"
        height="600"
      />
    </Container>
  );
}

**Comment by junedchhipa** [comment]
Please create a reproducible demo on [codesandbox](https://codesandbox.io/s/6yoqonyo7r).
Also, for any support questions related to React ApexCharts, please use [React ApexCharts Forum](https://apexcharts.com/forums/react-apexcharts/)
