### ISSUE TITLE
Chart minimap

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#126]
A very useful feature of charts is a small version of it for an overview of all data

Example:
![image](https://user-images.githubusercontent.com/3078595/45939591-4ec45480-bfdc-11e8-8889-a2d55eb55df2.png)

While [there's a way to sync apex charts](https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/) it's very cumbersome to replicate such a feature (one would need to hide labels, toolbar, disable tooltip) and it's buggy

![image](https://i.imgur.com/cltcVne.gif)

**Comment by junedchhipa** [comment]
Added a new option `chart.brush` which allows you to create this "chart minimap" easily.

[Docs](https://apexcharts.com/docs/options/chart/brush/)
[Demo](https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/)

**Comment by pribilinskiy** [comment]
Nice!

How to synchronize brush-chart with main chart when Toolbar is enabled?
Currently when you use any of the tools from the toolbar doesn't reflect position in the brush chart

**Comment by junedchhipa** [comment]
@pribilinskiy Currently panning on the main chart reflects selection on the brush chart. I think, I forgot the zooming part, I will take a look again.

**Comment by pribilinskiy** [comment]
@junedchhipa well, not really.
If you not specify `selection.xaxis` and zoom in in the brush chart, panning the main chart will not affect the brush chart
https://codepen.io/anon/pen/YJNOjz

**Comment by junedchhipa** [comment]
Right, ok. Thanks for catching.

**Comment by junedchhipa** [comment]
😍
