### ISSUE TITLE
Show tooltip only for last element in series

### ISSUE THREAD

**Issue by michaeljakob** [apexcharts/apexcharts.js#1261]
# Feature request
Is it possible to show the tooltip only for the final element in a series?

I have tried the following (without success):
` tooltip: {
          enabled: [false,false,false,false,false,false,false,true]
  }`

The `enabled` property only seems to accept true/false. We're currently only allowed to show the final values, so I'd really appreciate such a feature!

<img width="805" alt="Screenshot 2020-01-28 21 22 35" src="https://user-images.githubusercontent.com/3597595/73267608-5d47ff00-4214-11ea-9830-26f18ef2e8e1.png">

<img width="799" alt="Screenshot 2020-01-28 21 22 30" src="https://user-images.githubusercontent.com/3597595/73267609-5d47ff00-4214-11ea-9492-8f092c8ec44e.png">

**Comment by junedchhipa** [comment]
Sorry, that is not achievable.
There is a property called `enabledOnSeries: [2]` but that enables tooltip for all data-points of the selected series.
