### ISSUE TITLE
If the real-time line chart receive more than 5 minutes of data, the chart displays delayed.

### ISSUE THREAD

**Issue by ahnjs1987** [apexcharts/apexcharts.js#1264]
## Explanation
> I want to make real-time chart and the data is received every 500ms. When I stay on the chart page more than 5 minutes, the chart shows some delayed transition. There were not have any error message. Once I reload the page, the phenomenon is removed. This problem is same on your sample source page(https://apexcharts.com/javascript-chart-demos/line-charts/realtime/).

I think It occurred from data array on the chart. If there any method for flushing data array on chart nicely?

**Comment by EmanueleCoppola** [comment]
Hi @ahnjs1987, I am having the same problem, did you manage to find a fix?

I tried to overwrite the data periodically by removing the older points but the transition doesn't seem so nice.

Thanks in advance
