### ISSUE TITLE
Vertical charts

### ISSUE THREAD

**Issue by IlyaChubko** [apexcharts/apexcharts.js#1265]
Hello! I'm sorry for issue, but I want ask you if can I draw vertiacal charts with ApexCharts, such as:

![Screenshot_3](https://user-images.githubusercontent.com/6832799/73327445-1d5e3780-4267-11ea-8488-06bf4418064c.png)

Thank you.

**Comment by junedchhipa** [comment]
Sorry, vertical charts are not supported in ApexCharts.
