### ISSUE TITLE
Json retrieving data 

### ISSUE THREAD

**Issue by dabuionut** [apexcharts/apexcharts.js#1267]
Hi,
I tried to implement a json data / i copied the example from the apexcharts doc's and when i use the link from the example is working and when i use a different link to say local i have this error. 
![Capture2](https://user-images.githubusercontent.com/19206681/73342335-04fe1500-4287-11ea-8d94-8c54224f1752.JPG)

And when i put it online on a server I have this error .
![Capture3](https://user-images.githubusercontent.com/19206681/73342337-04fe1500-4287-11ea-96aa-68729f8fcabe.JPG)

Thx in advance for your help

**Comment by junedchhipa** [comment]
Hi @dabuionut 
It seems like there is some configuration error with your code which is not directly related to ApexCharts.
For more help with such issues, post your questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/apexcharts) with apexcharts tag or [ApexCharts forum](https://apexcharts.com/forums)

**Comment by dabuionut** [comment]
Hi @junedchhipa 
Thx for your response I made a ticket on ApexCharts froum .
