### ISSUE TITLE
Accept item index as an argument for formatter function

### ISSUE THREAD

**Issue by mestaritonttu** [apexcharts/apexcharts.js#127]
Currently [the formatter function](https://apexcharts.com/docs/options/xaxis/#formatter) takes value and timestamp. In Chartist, there is a [labelInterpolationFnc](https://gionkunz.github.io/chartist-js/examples.html#bi-polar-bar-interpolated) that takes value and index. This allows showing only certain label items like so:
`return index % 2 === 0 ? value : null;`
This is useful for getting stuff as minimal as possible on mobile.

**Comment by junedchhipa** [comment]
No problem, I can provide the third argument with extra details (seriesIndex / dataPointIndex, etc)

**Comment by junedchhipa** [comment]
Updated the docs too
https://apexcharts.com/docs/options/xaxis/#formatter

**Comment by yantavares** [comment]
Hi! Is this functionality still available? I could not find it
