### ISSUE TITLE
Remove specific series data from tooltip

### ISSUE THREAD

**Issue by gokhantaskan** [apexcharts/apexcharts.js#1270]
![2020-01-30_11-48-06](https://user-images.githubusercontent.com/45636599/73433849-a30ce080-4356-11ea-8929-1094038f8f12.png)

I want to remove the data shown within the red bordered box.

The code below removes the title but I also want to hide green label and the value.

```
tooltip: {
   y: {
     title: {
       formatter: seriesName => seriesName !== "Total" ? `${seriesName}` : null
    }
  }
},
```

**Comment by junedchhipa** [comment]
If you just want to hide tooltip on a certain series, you can use the `enabledOnSeries` property to include series on which you want the series to be enabled.

```javascript
tooltip: {
  enabledOnSeries: [0, 1, 2]
}
```
The above code hides the 4th series

**Comment by gokhantaskan** [comment]
Thank you!

**Comment by Lunkobelix** [comment]
> If you just want to hide tooltip on a certain series, you can use the `enabledOnSeries` property to include series on which you want the series to be enabled.
> 
> ```js
> tooltip: {
>   enabledOnSeries: [0, 1, 2]
> }
> ```
> 
> The above code hides the 4th series

Sorry for the stupid question, but where do I put this? Looks liek CSS to me but not sure what to do with it, beel looking everywhere for a way to hide one series from the tooltip.
