### ISSUE TITLE
A way to render both xAxis and yAxis crosshair

### ISSUE THREAD

**Issue by ltujiba** [apexcharts/apexcharts.js#1271]
Hello,

Is there a way to render the yaxis crosshair horizontally ?
Right now, when I put crosshair option both on the xaxis and yaxis, only one of them is being shown.

Below is my option:
`
 xaxis: {
          crosshairs: {
            show: true,
            width: 1,
            position: 'back',
            opacity: 0.9,
            stroke: {
              color: '#ff0000',
              width: 1,
              dashArray: 5,
            },
          },
          type: 'datetime',
        },
        yaxis: {
          crosshairs: {
            show: true,
            width: 1,
            position: 'front',
            opacity: 0.9,
            stroke: {
              color: '#00ff00',
              width: 1,
              dashArray: 0,
            },
          },
          opposite: true,
        },
`

**Comment by junedchhipa** [comment]
Please provide a full working [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example.

**Comment by ltujiba** [comment]
Yes, thank you.

This is the codepen example's [link](https://codepen.io/ltujiba/pen/zYxVdxZ).

**Comment by junedchhipa** [comment]
Sorry for the late response.

You will need to enable `yaxis.tooltip` (which is turned off by default) also to show the crosshair.

```javascript
yaxis: {
  tooltip: {
    enabled: true
  }
}
```

I will add this to the docs.
