### ISSUE TITLE
Heatmaps color range 0 no longer working after upgrading to 3.15.3 / 1.3.6.

### ISSUE THREAD

**Issue by ustincameron** [apexcharts/apexcharts.js#1273]
# Bug report
apexcharts: "^3.15.3",
react-apexcharts: "^1.3.6"

After updating to latest release in order to get CSV export, the heatmap now ignores the color ranges and shows the default rainbow color in every cell except where not 0.
Breaks the design and is unreleasable at the moment.

```
colorScale: {
                    ranges: [
                      {
                        from: 0,
                        to: 0,
                        name: 'none',
                        color: '#DADEDF'
                      },
```
## After:
![Screen Shot 2020-01-30 at 12 19 22 PM](https://user-images.githubusercontent.com/831521/73473443-c9347f80-435a-11ea-8af9-339631c6cab5.png)
## Before:
![Screen Shot 2020-01-30 at 12 20 01 PM](https://user-images.githubusercontent.com/831521/73473490-dfdad680-435a-11ea-9ef8-73ceb374016f.png)

## Explanation

- Expect heatmap color range: 0 to work or at least be white.
- Entire heat map turns rainbow mode besides the cells that == 1+
- No errors

**Comment by junedchhipa** [comment]
Can you please create a codepen demo to easily reproduce it?

**Comment by ustincameron** [comment]
Ah, I finally solved it by changing my 0 range.

**From**
`{
                        from: 0,
                        to: 0,
                        name: 'none',
                        color: '#DADEDF'
                      }`
**To**
`
                      {
                        from: 0,
                        to: 1,
                        name: 'none',
                        color: '#DADEDF'
                      },`

and now it's no longer giving me the rainbow.

**Comment by junedchhipa** [comment]
Nice!
Closing the issue then.
