### ISSUE TITLE
Legend height is not correct

### ISSUE THREAD

**Issue by architawr** [apexcharts/apexcharts.js#1274]
# Bug report

This problem (similar #724) appeared AFTER I reinstalled the dependencies NOT changing the version of apexcharts

It was BEFORE reinstalling
![image](https://user-images.githubusercontent.com/26203081/73477523-7df38e80-43a5-11ea-9e8f-1ba1c3f87cf2.png)

AFTER reinstalling
![image](https://user-images.githubusercontent.com/26203081/73477554-8c41aa80-43a5-11ea-969c-3873397e07a8.png)

Code didnt change
https://codesandbox.io/s/vue-basic-example-cl3fz

## Explanation

- What is the behavior you expect?
The legend will not hide under a donut
- What is happening instead?
The legend will hide under a donut
- What error message are you getting?
![Снимок экрана от 2020-01-30 20-58-43](https://user-images.githubusercontent.com/26203081/73477633-b1ceb400-43a5-11ea-86bb-642e63ef1378.png)

**Comment by junedchhipa** [comment]
The previous version had problems with `legend.floating`.

In your code, just set `legend.floating: false` and it should work fine.

**Comment by architawr** [comment]
> The previous version had problems with `legend.floating`.
> 
> In your code, just set `legend.floating: false` and it should work fine.

If i set `legend.floating: false` then the legend will “squeeze out” the donut.

![image](https://user-images.githubusercontent.com/26203081/73519369-f6903480-4411-11ea-9d16-a81191702650.png)

And I need all the donuts to be the same size WITHOUT the legend

**Comment by architawr** [comment]
I tried update apexcharts and vue-apexcharts to latest versions, but this bug has been appeared. And i dont have ideas how to fix it
