### ISSUE TITLE
Negative Y-value appear on Safari, while hidden on Chrome? [Line graph]

### ISSUE THREAD

**Issue by napzter13** [apexcharts/apexcharts.js#1275]
Hello,

First of, I love the simple-to-use graph framework!

I have this complication though, where I'm using negative Y-values in order to add a 'shifting' effect to multiple lines, so they're parallel, in order to make them visible. They're perfectly hidden on Chrome (also mobile), but realised that negative values are visible on Safari.

How can I make the graph look like the one in Chrome?

Thank you.

Safari:
![image](https://user-images.githubusercontent.com/25500827/73543167-a7102f80-4436-11ea-9f7c-4672fbd13792.png)

Chome:
![image](https://user-images.githubusercontent.com/25500827/73543207-babb9600-4436-11ea-813a-507752484430.png)

**Comment by junedchhipa** [comment]
Can you please provide a working codepen demo to easily reproduce it?
Also, please specify which version of Safari you tested in.
