### ISSUE TITLE
Dashboards with different container width

### ISSUE THREAD

**Issue by IlyaChubko** [apexcharts/apexcharts.js#1276]
Hello! Thank you for greatest js library.
I have a bug in working with dashboards with different width and the same charts group.
First chart select X=3, but second X=5
![image](https://user-images.githubusercontent.com/6832799/73607582-fa19ec00-45c8-11ea-9496-cfcf340e4be6.png)
https://codepen.io/ilyachubko/pen/wvBQgpe

**Comment by junedchhipa** [comment]
Unfortunately, grouped charts with different width won't work which is documented on the [Sync charts](https://apexcharts.com/docs/chart-types/synchronized-charts/) page.

You will need to make all grouped charts the same width to make it work.

**Comment by KarlKrabb** [comment]
Hi @junedchhipa, is there any work around for this? i am doing essentially the same thing as @IlyaChubko, a dashboard with different width charts..

@IlyaChubko Did you manage to come up with some solutions for your issue? any suggestions?
