### ISSUE TITLE
Missaligned and repeated xaxis datapoints when datetime and formatted

### ISSUE THREAD

**Issue by bruno02100** [apexcharts/apexcharts.js#1277]
https://codesandbox.io/s/react-basic-example-xd2iv?fontsize=14&hidenavigation=1&theme=dark

## Explanation

- What is the behavior you expect?
Datapoints on xaxis should represent the listed datapoints in the series.
- What is happening instead?
Datapoints are being duplicated and missaligned.
- What error message are you getting?
none

**Comment by junedchhipa** [comment]
If you get unpredicted results in `xaxis.type: 'datetime'`, try

```javascript
xaxis: {
  type: 'category'
}
```

It works fine with a custom formatter.
