### ISSUE TITLE
Single data point leads to annotations not rendering

### ISSUE THREAD

**Issue by wozzo** [apexcharts/apexcharts.js#1279]
# Bug Report
## Codepen
[Modified Codepen](https://codepen.io/wozzo/pen/povMxmL)
## Explanation
- What is the behavior you expect?
Annotations to always appear regardless of `data`
- What is happening instead?
When only a single data point in the series the annotation isn't appearing.
The annotations block has the following classes `apexcharts-xaxis-annotations apexcharts-element-hidden` leading to the annotations not being visible. Updating the options passed in after the initial render seems to get the annotations to appear again.
- What error message are you getting?
No error message

**Comment by wozzo** [comment]
As a workaround I've added a `useEffect` call which modifies something on the options
```
	useEffect(() => {
		setTimeout(() => {
			setDashboardChart({...dashboardChart,
				options: {
					...dashboardChart.options,
					markers: { size: 5}
				}})
		}, 0)
	// eslint-disable-next-line
	}, [])
```

**Comment by junedchhipa** [comment]
Thanks for the bug report.
I have fixed it and should work fine in the next patch release.

**Comment by wozzo** [comment]
Awesome. Cheers.
