### ISSUE TITLE
Add official localization templates

### ISSUE THREAD

**Issue by Calinou** [apexcharts/apexcharts.js#128]
[ApexCharts already supports localization](https://apexcharts.com/docs/options/chart/locales/), but as far as I know, no template files are provided.

It could be useful to add localization templates that could be imported when desired, similar to projects like [date-fns](https://github.com/date-fns/date-fns).

For example, here's one I wrote for French (feel free to use it if you wish):

```json
{
  "name": "fr",
  "options": {
    "months": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
    "shortMonths": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juill.", "août", "sept.", "oct.", "nov.", "déc."],
    "days": ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    "shortDays": ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
    "toolbar": {
      "download": "Télécharger au format SVG",
      "selection": "Sélection",
      "selectionZoom": "Sélection et zoom",
      "zoomIn": "Zoomer",
      "zoomOut": "Dézoomer",
      "pan": "Navigation",
      "reset": "Réinitialiser le zoom"
    }
  }
}
```

Those templates could be contributed by users and added to this repository :slightly_smiling_face:

**Comment by junedchhipa** [comment]
Good suggestion. I will add an option to import localization templates.

**Comment by junedchhipa** [comment]
v2.0.8 adds locales directory to `/dist`. 
Other users can contribute in `/src/locales`. Each build will copy the src locales to dist directory.
