### ISSUE TITLE
Feature Request: Radial bar Charts to support annotations

### ISSUE THREAD

**Issue by fmahmoo3** [apexcharts/apexcharts.js#1280]
I am creating a temperature chart for a system that has a maximum ambient temperature that can not survive above. To indicate this maximum value, I was hoping to add a small line on the radial chart to indicate this maximum ambient temperature to users on a dashboard.

**Comment by junedchhipa** [comment]
Can you please re-upload the image of how it should look?

**Comment by fmahmoo3** [comment]
![71B7A489-7BFD-42D4-85B4-3500C8192198](https://user-images.githubusercontent.com/28940538/73801065-1f505b00-477f-11ea-9ad8-99cbda989ec7.jpeg)

**Comment by laurent-brisbois** [comment]
Is that supported now ? I don't find it in the docs

**Comment by laurent-brisbois** [comment]
@junedchhipa Hello.
Any news about this ?
In my opinion it is necessary to have this option to this kind of graph.

**Comment by asumaran** [comment]
In my case I need to add a custom image to the end of the stroke 

<img src="https://user-images.githubusercontent.com/1025173/102578093-5db8e500-40c7-11eb-9d82-ca7acf1458e4.png" 
 width="200" />

Any ideas on how to do it?

**Comment by michaeldever** [comment]
This would be awesome for us as well.

**Comment by laurent-brisbois** [comment]
How is it going ? It's been more than a year now.
Just asking.

**Comment by lithiumlab** [comment]
still needed!

**Comment by Munaro** [comment]
Still needed.

**Comment by laurent-brisbois** [comment]
Give up guys they will never do it nor answer.
Instead switch to [Apache ECharts](https://echarts.apache.org/en/index.html).
Examples of gauges using Apache ECharts : https://echarts.apache.org/examples/en/index.html#chart-type-gauge

**Comment by Khan058** [comment]
any update on this

**Comment by b4ra0** [comment]
still needed

**Comment by MaxHay-dev** [comment]
This would still be a very appreciated effect
