### ISSUE TITLE
yaxis label colors style not working

### ISSUE THREAD

**Issue by zenichanin** [apexcharts/apexcharts.js#1281]
# Bug report

> For support questions, please use ApexCharts Forums - https://apexcharts.com/forums/.

## Codepen

https://codepen.io/zenichanin/pen/wvBVVGQ

## Explanation

- setting `yaxis.labels.style.colors` seems to have no effect.
- would expect the labels to behave the same way as `xaxis.labels.style.colors`

**Comment by junedchhipa** [comment]
The latest version 3.15.5 fixes this behavior.

**Comment by michaelparkadze** [comment]
I have this piece of code:

```js
     xaxis: {
        ...overrideOptions.xaxis,
        type: 'datetime',
        labels: {
          style: {
            colors: '#A7BDD1',
          },
        },
      },
      yaxis: {
        ...overrideOptions.yaxis,
        labels: { style: { colors: '#A7BDD1' } },
      },
```

xaxis works just fine changing the label's color but yaxis not doing anything? this is on angular, latest version.
