### ISSUE TITLE
Issue with missing/null values

### ISSUE THREAD

**Issue by Alin13** [apexcharts/apexcharts.js#1282]
Hello,

I need to show a line series which has some null values.

**- What is the behaviour you expect?**
All values should be displayed correctly, even if there are some isolated / single values (previous & next values are null)

**- What is happening instead?**
There are multiple problems:
1. with a basic configuration, the single values are not shown
https://codepen.io/alin13/pen/XWbrKNG?editors=0010

2. if I add **lineCap** config on stroke, the values are displayed, but you can see also the null values on the xAxis:
https://codepen.io/alin13/pen/PoqYNyZ?editors=0010

3. there is a workaround for this: splitting the data into two series: line & scatter - the problem here is that we have no option to hide one of the series from legend.

Any ideas how to fix this ?

Thank you for your time! :)

**Comment by AlexSceed** [comment]
Hi, everybody. I have the same problem. Hope for a fix

**Comment by IlyaChubko** [comment]
Hello!
Same ticket: https://github.com/apexcharts/apexcharts.js/issues/1252

**Comment by skiff2140** [comment]
Hi! I have the same problem too and not seen points on my chart

**Comment by junedchhipa** [comment]
I confirm the bug.
Closing it in favor of #1252 
Any updates will be continues in that ticket.

**Comment by tzagirov** [comment]
I had the same problem with unvisible points

**Comment by raja-mandal** [comment]
I think we can add animations object as false :

chart: {
        animations: {
          enabled: false,
        }
 },
