### ISSUE TITLE
[question] how to customize x-axis datetime font style?

### ISSUE THREAD

**Issue by davalapar** [apexcharts/apexcharts.js#1283]
Hi there, thanks a lot for the lib we love it :)

Just noob question, how to customize x-axis datetime font style?

We basically want to remove the bold highlight on `Feb '20`, any way it's possible?

![image](https://user-images.githubusercontent.com/41451953/73764111-61909100-47ad-11ea-8b60-b9357d6f97e1.png)

**Comment by junedchhipa** [comment]
Currently, you cannot change it through the config object, but you can change it using CSS

```CSS
.apexcharts-xaxis-label {
  font-weight: 400
}
```

**Comment by Nedpereira** [comment]
Is there another way to make the change?

**Comment by 4designing** [comment]
it's actually wrong value also , it should be 01 Feb, I'm facing the same bug on datetime type
