### ISSUE TITLE
Panning is broken in most cases

### ISSUE THREAD

**Issue by jaksim** [apexcharts/apexcharts.js#1287]
# Bug report

## Codepen
- Case 1 (series with numbers on x axis): https://codepen.io/jaksim/pen/QWbLoMQ
- Case 2 (series with datetime on x axis): https://codepen.io/jaksim/pen/GRJKeNq 

## Some of the official examples that are broken
- https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/ (case 2)
- https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/ (case 2)
- https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/ (case 2)
- https://apexcharts.com/javascript-chart-demos/line-charts/stepline/ (case 1)
- https://apexcharts.com/javascript-chart-demos/line-charts/gradient/ (case 2)
- https://apexcharts.com/javascript-chart-demos/area-charts/spline/ (case 2)
- https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis/ (case 2)
- https://apexcharts.com/javascript-chart-demos/area-charts/negative/ (case 2)
- https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/ (case 1)

### Case 1
- Click on zoom in button once.
- Switch to panning tool
- Now try to drag your view to the right.
- You will not be able to get the right most point into view again.

### Case 2
- Click on zoom in button once.
- Switch to panning tool.
- Try to drag your to the right.
- You will be teleported to 1970.

Through bisect, I've found that Case 2 was broken by commit 0849cc3c805a64205e64ded892bbf734f5e613cd
Case 1 doesn't seem to behave very well before that commit either, though I can at least see the last data point. Just the x axis labels show ugly fractions, but that seems to be solvable from client code.

**Comment by junedchhipa** [comment]
That's a major one.
Will look into it asap
