### ISSUE TITLE
Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by guillenotfound** [apexcharts/apexcharts.js#1288]
# Bug report

**Stacktrace:**
TypeError Unable to get property 'contains' of undefined or null reference 
    ../../node_modules/apexcharts/dist/apexcharts.common.js:6 value

It seems like an IE11  only related issue as BugSnag reports me, I've seen several issues related:
https://github.com/mdbootstrap/perfect-scrollbar/issues/830
https://github.com/Hacker0x01/react-datepicker/issues/499

**Comment by junedchhipa** [comment]
In one of those related issues, people solved it by loading this polyfill - https://github.com/WebReflection/dom4
Can you try loading that before ApexCharts and see if it fixes the issue?

**Comment by dguerroue** [comment]
Thanks, it solve my issue !
I also had to load the es6-promise polyfill

`<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js"></script>
`
