### ISSUE TITLE
seriesIndex returning -1

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1292]
Related to https://github.com/apexcharts/apexcharts.js/issues/1263

So this is happening in the same place the original issue was found, except this time around the dataPointIndex works and the seriesIndex is returning -1.

Seems like the fix for the last issue broke the seriesIndex.

**Comment by junedchhipa** [comment]
I can't reproduce it.
The same codepen in #1263  gives `seriesIndex: 0`

**Comment by junedchhipa** [comment]
@ThinkSalat  Closing it for now.
Feel free to open a new ticket is you see the issue again and reproduce it.
