### ISSUE TITLE
yaxis not scaling correctly when using brush chart and 2 or more series.

### ISSUE THREAD

**Issue by bruno02100** [apexcharts/apexcharts.js#1294]
https://codesandbox.io/s/react-basic-example-ww3gz?fontsize=14&hidenavigation=1&theme=dark

## Explanation
When using a brush chart the yaxis is not scaling properly with 2 or more lines (series).

- What is the behavior you expect?
The y axis to scale to the proper size.
- What is happening instead?
It cuts the yaxis of the chart.
- What error message are you getting?
none

**Comment by junedchhipa** [comment]
Disabled `autoScaleYaxis` in a brush chart for a multi-series chart.

For now, you can do
```javascript
chart: {
  brush: {
    autoScaleYaxis: false
  }
}
```

**Comment by vargemp** [comment]
Seems like the bug is still there: https://codepen.io/vargemp/pen/wvQjeGJ
