### ISSUE TITLE
Hiding Yaxis of a Horizontal Bar Chart Does Not Hide the Yaxis but Xaxis Categories

### ISSUE THREAD

**Issue by Nilaik** [apexcharts/apexcharts.js#1295]
## Codepen

[This codepen](https://codepen.io/nilaik/pen/YzXXNxM) demonstrates the problematic behaviour. 

Setting `yaxis: { show: false }` hides the category labels of the xaxis.

## Explanation

When setting the attribute show of the Yaxis to false I expect that the tick labels of the yaxis disappear. Instead the category labels disappear if the type of the chart is bar and as plotOptions of the bar plot is chosen as horizontal: true.

**Comment by junedchhipa** [comment]
In a horizontal bar chart, the axis labels get switched but technically, the y-axis still refers to the vertical axis, while the x-axis refers to the horizontal axis.

So, the behavior which you reported is the intended behavior.

**Comment by Nilaik** [comment]
@junedchhipa thanks for the update. But how could I remove the labels of the yaxis or in horizontal bar charts xaxis?

**Comment by Nilaik** [comment]
I just saw that there is the option `labels: {show: false}` for the xaxis which hides the yaxis or xaxis in horizontal bar charts. However it is not very straightforward and rather confusing.

**Comment by junedchhipa** [comment]
Yes, to hide xaxis labels, you can do
```javascript
xaxis: {
  labels: {
    show: false
  }
}
```

**Comment by CaramelHeaven** [comment]
@junedchhipa Why it is intended behavior ? The question was how to hide yaxis and not hide show xaxis ?
`But how could I remove the labels of the yaxis or in horizontal bar charts xaxis?`

**Comment by JalmariO** [comment]
I don't know how to get rid off y-axis in my horizontal bar chart.
My goal is to show only series-grid with tooltips, and hide everything else.
Y-axis labels are my Via Dolorosa...

![image](https://github.com/apexcharts/apexcharts.js/assets/7537088/c43fc1e9-7506-4bc0-ab50-4e5f0100ec46)

I'm using apexcharts 3.46 and ng-apexcharts 1.9.0 in angular application
