### ISSUE TITLE
Apexcharts It is a possibility that you may have not included 'data' property in series, Cannot read property 'labels' of undefined

### ISSUE THREAD

**Issue by csandreas1** [apexcharts/apexcharts.js#1297]
I get three errors

When the map is rendered for the first time  i get:

```
apexcharts:6 It is a possibility that you may have not included 'data' property in series
apexcharts:6 It is a possibility that you may have not included 'data' property in series
```
Then each time the map is rendered I get: 
`Uncaught (in promise) TypeError: Cannot read property 'labels' of undefined
`

My code:
```

var options = {
  theme: {
    mode: 'light', 
    palette: 'palette1', 
    monochrome: {
        enabled: false,
        color: '#31a7ec',
        shadeTo: 'light',
        shadeIntensity: 0.65
    }
},
  chart: {
    height: 450,
    type: 'bar',
  },
   plotOptions: {
    bar: {
      horizontal: true,
    }
  },
  dataLabels: {
    enabled: true
  },
  series: [{
    name: "Consumption"
  }],
  title: {
    text: 'AMR Consumption',
  },
  noData: {
    text: 'No Data'
  }
}
```

```
var chart = new ApexCharts(
  document.getElementById("AMRbarchart"),
  options
)
```

// then i do ajax requests and add / destroy the chart
```
//ajax 

```
      $.getJSON('http://10....',  response => {
                    chart.render()

                    chart.updateOptions({
                        title: {
                            text: 'Consumption by year (' + unit + ') for ' + feature_name
                        },
                        chart: {
                            height: 380
                        }
                    })

                    chart.updateSeries([{
                        data: response.yearly
                    }])
                })

```

**Comment by junedchhipa** [comment]
As the error suggests, you cannot have a `series` without a data property. Even if you don't have anything in data, you should pass an empty array

```javascript
series: [{
  name: "Consumption",
  data: []
}]
```

**Comment by guvenacar** [comment]
I have same error, what is wrong here? 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Gradient Line</title>

    <link href="Content/assets/styles.css" rel="stylesheet" />

    <style>
      
        #chart {
      max-width: 650px;
      margin: 35px auto;
    }
      
    </style>

    <script>
        window.Promise ||
            document.write(
                '<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"><\/script>'
            )
        window.Promise ||
            document.write(
                '<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill@1.2.20171210/classList.min.js"><\/script>'
            )
        window.Promise ||
            document.write(
                '<script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"><\/script>'
            )
    </script>

    
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    

    <script>
        // Replace Math.random() with a pseudo-random number generator to get reproducible results in e2e tests
        // Based on https://gist.github.com/blixt/f17b47c62508be59987b
        var _seed = 42;
        Math.random = function () {
            _seed = _seed * 16807 % 2147483647;
            return (_seed - 1) / 2147483646;
        };
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
     <div id="chart"></div>

    <script>
        
        var options = {
            series: [{
                name: 'istanbul',
                data: [11, 12, 20, 98, 47]
            },
                {
                    name: 'izmir',
                    data: [21, 19, 80, 18, 47]
                },
                {
                    name: 'payas',
                    data: [31, 12, 20, 98, 57]
                }],
            chart: {
                id: "Chart1",
                name:"Chart1",
                height: 350,
                type: 'line',
            },
            stroke: {
                width: 7,
                curve: 'smooth'
            },
            xaxis: {
                type: 'category',
                categories: ["2015", "2016", "2017", "2018", "2019"],
                tickAmount: 10 
            },
            
            fill: {
                type: 'gradient',
                gradient: {
                    shade: 'dark',
                    gradientToColors: ['#FDD835'],
                    shadeIntensity: 1,
                    type: 'horizontal',
                    opacityFrom: 1,
                    opacityTo: 1,
                    stops: [0, 100, 100, 100]
                },
            },
            markers: {
                size: 4,
                colors: ["#FFA41B"],
                strokeColors: "#fff",
                strokeWidth: 2,
                hover: {
                    size: 7,
                }
            },
            yaxis: {
                min: 10,
                max: 120, 
            }
        };

          
        var chart = new ApexCharts(document.querySelector("#chart"), options); 
        
        function Update() { 
           
            var Veri1, Veri2, Veri3;  

            $.getJSON('Content/ApexData/Test/Veri2.json', function (response) {
                Veri2 = response
            });
            $.getJSON('Content/ApexData/Test/Veri3.json', function (response) {
                Veri3 = response
            }); 
            $.getJSON('Content/ApexData/Test/Veri1.json', function (response) {
                Veri1 = response 
            });
         
            ApexCharts.exec("Chart1", "updateOptions", {
                series: [{
                    name: "istanbul",
                    data: Veri2
                },
                {
                    name: "izmir",
                    data: Veri1
                },
                {
                    name: "payas",
                    data: Veri3
                }
                ],
                xaxis: {
                    categories: ["2015", "2016", "2017", "2018", "2019"]
                }
            }); 
        }
         
        chart.render();
      
    </script>

    <button id="Update" onclick="Update();">Update</button> 
  </body>
</html>

**Comment by guvenacar** [comment]
Veri1.Json:
[ 
  {
    "x": "2015",
    "y": 10
  },
  {
    "x": "2016",
    "y": 33
  },
  {
    "x": "2017",
    "y": 31
  },
  {
    "x": "2018",
    "y": 98
  }
  {
    "x": "2020",
    "y": 71
  }
]
----------------

Veri2.Json:
[
  {
    "x": "2015",
    "y": 20
  },
  {
    "x": "2016",
    "y": 30
  },
  {
    "x": "2017",
    "y": 75
  },
  {
    "x": "2018",
    "y": 90
  },
  {
    "x": "2020",
    "y": 70
  }
]

-------------------------

Veri3.Json:
[
  {
    "x": "2015",
    "y": 15
  },
  {
    "x": "2016",
    "y": 35
  },
  {
    "x": "2017",
    "y": 90
  },
  {
    "x": "2018",
    "y": 10
  },
  {
    "x": "2020",
    "y": 100
  }
]

**Comment by nbtafelberg** [comment]
The problem is that the JSON calls are ASYNC so the system will hit ApexCharts.exec before the data. is loaded.

**Comment by arshdeepsingh2267** [comment]
> The problem is that the JSON calls are ASYNC so the system will hit ApexCharts.exec before the data. is loaded.

So what is the solution then. I am calling API and sending as a prop to apex react charts. data is being sent, but as you mentioned its async, I am getting this same error. What is the solution.

**Comment by rab101** [comment]
I am getting the same error and I am not using any async calls.  Just a simple example I pulled from the web.
<template>
  <div class="example">
    <apexchart
      ref="myChart"
      width="500"
      height="350"
      type="line"
      :options="chartOptions"
      :series="series"
    ></apexchart>
    <div>
      <button @click="updateChart">Update!</button>
    </div>
  </div>
</template>

<script>
export default {
  name: "LineExample",
  data: function() {
    return {
      chartOptions: {
        xaxis: {
          type: "datetime",
          categories: [
            "01/01/2003",
            "02/01/2003",
            "03/01/2003",
            "04/01/2003",
            "05/01/2003",
            "06/01/2003",
            "07/01/2003",
            "08/01/2003"
          ]
        }
      },
      series: [
        {
          name: "Series A",
          data: [30, 40, 45, 50, 49, 60, 70, 91]
        },
        {
          name: "Series B",
          data: [23, 43, 54, 12, 44, 52, 32, 11]
        }
      ]
    };
  },
  methods: {
    generateDayWiseTimeSeries(baseval, count, yrange) {
      var i = 0;
      var series = [];
      while (i < count) {
        var x = baseval;
        var y =
          Math.floor(Math.random() * (yrange.max - yrange.min + 1)) +
          yrange.min;
        series.push([x, y]);
        baseval += 86400000;
        i++;
      }
      return series;
    },
    updateChart() {
      this.$refs.myChart.appendSeries(
        [
          {
            name: "series-1",
            data: [10, 40, 5, 50, 0, 60, 70, 91]
          }
        ],
        true
      );
    }
  }
};
</script>

**Comment by rab101** [comment]
I found the issue and I will respond to my own question. The type for the appendSeries() should be an object ( i.e. {}) and not and array ([]) as it is the case in updateSeries(). In the code shown above, replace:
```
      this.$refs.myChart.appendSeries(
        [
          {
            name: "series-1",
            data: [10, 40, 5, 50, 0, 60, 70, 91]
          }
        ],
        true
      );
```
by

```
this.$refs.myChart.appendSeries(
          {
            name: "series-1",
            data: [10, 40, 5, 50, 0, 60, 70, 91]
          }
        true
      );
```

**Comment by devopsdeveloper1107** [comment]
// Video link https://www.youtube.com/watch?v=yxHp5t9gAsI&t=27s

import React,{useState, useEffect} from 'react';
import Chart from 'react-apexcharts';

function Linechart()
{
    const [sData, setSdata]= useState([]);
    useEffect( ()=>{
        const getvaluedata= async()=>{
            const newvalue=[];
            const reqData= await fetch('http://localhost/reactgraphtutorial/product/');
            const resData= await reqData.json();
            //console.log(resData);
            for(let i=0; i < resData.length; i++)
            {
                newvalue.push({name:resData[i].category_title, data:resData[i].value });   

            }
            setSdata(newvalue);

        }
        getvaluedata();
    },[]);   

    return(<React.Fragment>
        <div className='container-fluid mt-3 mb-3'>
          <h2>Line Chart- Using Apexcharts in React </h2>          
          <Chart type='line'
          width={1450}
          height={550}
          series={sData}
          options={{
            title:{ text:"Product sell in 2021"},
            xaxis:{
                title:{text:"Product Sell in Months"},
                categories:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
            },
            yaxis:{
                title:{text:"Product in K"}                 
            }          

        }}
          >
          </Chart>

        </div>
    </React.Fragment>);
}

export default Linechart;

**Comment by chadrackkyungu** [comment]
I fixed the issue by simple check if the array is undefined then return empty if not return the chart with my values
data: salary[0] === undefined ? [] : salary

**Comment by devopsdeveloper1107** [comment]
super #Chadrackkyungu
