### ISSUE TITLE
showForNullSeries for y-axis

### ISSUE THREAD

**Issue by luscl1** [apexcharts/apexcharts.js#1299]
The legend has a property showForNullSeries, but the y-axis doesn't. I have a multi-series diagram where I load one series as soon as the user clicks on a button.
But I couldn't find a way to only show the y-axis when there is data in the series. I think a property like the one in the legend would do the trick.

Do you have a solution for this?

Many thanks in advance!

**Comment by luscl1** [comment]
Any progress on the problem yet?

**Comment by junedchhipa** [comment]
Implemented it.
From the next release, you will be able to use

```javascript
yaxis: {
  showForNullSeries: false
}
```
