### ISSUE TITLE
Cut out points on edges

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#130]
Is there a way to fix this?

![sketch](https://user-images.githubusercontent.com/6877046/46005193-658ea800-c0bd-11e8-96fd-e0a486f2a550.png)

**Comment by jimfilippou** [comment]
Unfortunately, the padding happens from outside and this doesn't fix the problem. Another obvious solution would be to add -1 and 6 to the y-axis but this solution is way too hacky because i want the charts to start from 0

**Comment by junedchhipa** [comment]
Provided a new option in `options.grid.clipMarkers`
https://apexcharts.com/docs/options/grid/#clipMarkers

Will be available in v2.0.1

**Comment by junedchhipa** [comment]
Cropped markers issue is fixed.
From v2.1.9, you shouldn't set `grid.clipMarkers` property anymore as it is deprecated.

**Comment by hardik-143** [comment]
![Screenshot 2025-01-02 at 6 16 13 PM](https://github.com/user-attachments/assets/f01f8815-5664-49b7-b534-1b5a0dd2bc2b)
Used the **area** chart type with markers, but when certain data values are zero, the markers get cropped at the edges, including the bottom and other directions. 

```
markers: {
      size: [7, 0],
      colors: [white], // Color of markers
      strokeColors: [primary], // Border color of markers
      strokeWidth: [3, 0], // Border width of markers
      hover: {
        size: 7, // Marker size on hover
      },
},
```

**Comment by hardik-143** [comment]
already set clipMarkers property to false here

```
grid: {
      clipMarkers: false,
      borderColor: "#f1f1f4",
      strokeDashArray: 4,
},
```
