### ISSUE TITLE
Apexchart doesn't show xaxis last label when rotate is applied. (VueJS)

### ISSUE THREAD

**Issue by hackproject** [apexcharts/apexcharts.js#1301]
`xaxis: {
                    tickAmount: 5,
                    tickPlacement: 'between',
                    categories: this.xaxis,
                    labels: {
                        show: true,
                        rotate: -45,
                        trim: false,
                        hideOverlappingLabels: false,
                        showDuplicates: true,
                        minHeight: 180,
                        maxHeight: 100000,
                        style: {
                            colors:'#ffffff',
                            fontSize: '14px',
                            cssClass: 'apexcharts-xaxis-label',
                        },
                        formatter: function (value) {
                            return value;
                        },
                        rotateAlways:true,
                    },
                },`

![bugGraph](https://user-images.githubusercontent.com/18373173/74352027-4f56ba00-4d8e-11ea-9579-da407a5cca8b.PNG)

**Comment by junedchhipa** [comment]
Please create a full working codepen or codesandbox demo to easily reproduce it on our side.
