### ISSUE TITLE
Is it possible to change color of a label if its value matches a certain one? [Heatmap]

### ISSUE THREAD

**Issue by jota12x** [apexcharts/apexcharts.js#1303]
Hello, I was wondering about this particular usecase.
I want to change the color of each label that have the value 0. The others should be of different color.
<img width="210" alt="imagen" src="https://user-images.githubusercontent.com/6154802/74415115-1568df00-4e86-11ea-9135-bdafba3155fb.png">
According to the documentation, the _colors_ array controls them, but it's not a function so I can't pass the value
<img width="309" alt="imagen" src="https://user-images.githubusercontent.com/6154802/74415385-9de77f80-4e86-11ea-8ae9-3ede125fdf05.png">

I tried using the colorRanges but those only seem to control the background, not the datalabels properties 
<img width="262" alt="imagen" src="https://user-images.githubusercontent.com/6154802/74415466-c7081000-4e86-11ea-8859-8c3f9f2139fc.png">

Thank you so much in advance.

**Comment by junedchhipa** [comment]
Not possible currently, but I will add a `foreColor` property in the color ranges.

**Comment by jota12x** [comment]
Thanks!
