### ISSUE TITLE
t[n].data.map is not a function

### ISSUE THREAD

**Issue by iskabin** [apexcharts/apexcharts.js#1304]
Hey guys,

I'm receiving the following error when trying to render a chart, or updating one:

![image](https://user-images.githubusercontent.com/13689397/74566758-fab06c00-4f52-11ea-9a6d-9aea95402717.png)

I think it's related to my data since when my server returns an empty array, there is no error on the console and the chart is drawn empty, as expected, but I couldn't find whats wrong...

I used this doc to build it: [Doc](https://apexcharts.com/docs/chart-types/heatmap-chart/)

And I also made a pen to reproduce it: [CodePen](https://codepen.io/iskabin/pen/wvaMZeG)

Could you tell where I messed up, o maybe what I'm missing?

Thanks in advance!

**Comment by junedchhipa** [comment]
Here is the correct way to define series data

```javascript
var series = [
    {
      name: 'Luke Skywalker',
      data: [
        {
          x: 'Topico 1',
          y: 60
        }
      ]
    },
    {
      name: 'Rey Skywalker',
      data: [
        {
          x: 'Topico 1',
          y: 120
        }
      ]
    }
  ]
```

**Comment by iskabin** [comment]
Oh! That was so obvious! I'm sorry for that :/

Anyway, thank you very much for pointing this out! :D

**Comment by magarrent** [comment]
Hey! Thank you @junedchhipa !!

Btw I was looking at the Mixed chart, that's why I got the error. So this page is wrong then?

![image](https://github.com/apexcharts/apexcharts.js/assets/6561770/55d5158f-e1c8-4d51-81cd-dc72852d4426)
