### ISSUE TITLE
Trigger a click for a certain slice in the pie

### ISSUE THREAD

**Issue by Amosss** [apexcharts/apexcharts.js#1305]
Is there a way to trigger a click for a specific slice in the pie?

**Is your feature request related to a problem? Please describe.**	
I want to be able to select a pie slice when the page loads without a user interaction. 

**Describe the solution you'd like**	
Starts with slice X selected.

Thanks

**Comment by junedchhipa** [comment]
Use the `animationEnd` event of the chart which runs after every animation (keep in mind that it fires after every render, not just initial. So, keep a flag for just doing it for the initial render).

```javascript
chart: {
  type: 'pie',
  events: {
    animationEnd: function(ctx) {
      ctx.toggleDataPointSelection(3)
    }
  }
}
```

**Comment by Amosss** [comment]
Thanks a lot!
I also needed to use this: https://github.com/apexcharts/vue-apexcharts/issues/61
and both worked like a charm!

**Comment by Amosss** [comment]
OK, so it seems to be working but in the console, I see the following in Firefox
![image](https://user-images.githubusercontent.com/17168621/74982176-4e7ff100-543c-11ea-8690-d17cff8a7fd5.png)

and the following in Chrome
![image](https://user-images.githubusercontent.com/17168621/74982241-6b1c2900-543c-11ea-84e0-984729b9b89e.png)

The code is
```
animationEnd: (ctx) => {
   if (!this.setCurrentItem && this.user.itemIndex > -1) 
      ctx.toggleDataPointSelection(this.user.itemIndex);
   this.setCurrentitem = true;
}           
```
this.user is a computed function that takes information from the store. In debug (Chrome) this is the chart (maybe a debug bug?) but if I let it run, it does focus on the slice in itemIndex value as expected...
