### ISSUE TITLE
Please use ResizeObserver when available

### ISSUE THREAD

**Issue by re-thc** [apexcharts/apexcharts.js#1306]
This is implemented in modern browsers so it would be nice to detect this feature and use it before falling back to a reliable/efficient polyfill:
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

Thank you!

(replacing usage of DetectElementResize.js)

**Comment by junedchhipa** [comment]
ResizeObserver has very little support even in modern browsers.
Looking at the caniuse table, it seems browsers are just adopting it.

Let's wait for some more time before it is adopted by all the major browsers.

**Comment by hc-codersatlas** [comment]
The polyfills for ResizeObserver uses MutationObserver, which is still a better option than the current method. Should use ResizeObserver where available and fallback.
