### ISSUE TITLE
Upgrade to svgjs 3

### ISSUE THREAD

**Issue by hc-codersatlas** [apexcharts/apexcharts.js#1309]
Hi, svgjs has quite a few performance optimizations, esp. around animations. Can we upgrade to 3.x and/or at least backport the optimizations? Thanks.

**Comment by junedchhipa** [comment]
Hi there,

svg.js 3.0 has some breaking changes and is double in size. I see no big reason to update other than some performance optimization in animation.

Also, many of its plugins that are used in ApexCharts are not ready for 3.0.
I am following svg.js development and if I see everything ready for 3.0, I will surely move to it.

**Comment by hc-codersatlas** [comment]
Thanks. Good to know. Possible to just cherry pick the animation optimizations?

**Comment by junedchhipa** [comment]
I haven't looked into the source yet, but I may give it a shot.

**Comment by saurabhnemade** [comment]
@junedchhipa Can you please sync it with latest svg.js?

https://github.com/apexcharts/apexcharts.js/blob/4b46d339ca16c70751952e6b0f2facb8812fe643/src/svgjs/svg.js#L466
It seems to be missing a function named `A`. In latest version of svgjs https://cdnjs.cloudflare.com/ajax/libs/svg.js/3.0.16/svg.js it is available. 

This is leading to failure in jest.
I have managed to reach to this stage where my test case is passing but required function is missing from svgjs which in turn is terminating the test case.

<img width="1896" alt="Screenshot 2021-04-29 at 11 32 49 PM" src="https://user-images.githubusercontent.com/17445338/116597433-3dd1e180-a943-11eb-8fc6-e3f90e07e6c9.png">

I had to mock couple of things for this  to get it successful which are mentioned at https://github.com/apexcharts/react-apexcharts/issues/197.

It would be really helpful if we sync svg.js in this. It  might just pass my test cases..

**Comment by bzitzow** [comment]
Based on [this comment](https://github.com/apexcharts/react-apexcharts/issues/197#issuecomment-829468466), my understanding is that updating the library would resolve the error in when rendering in Jest Tests (node/jsdom): `s[t] is not a function`.
