### ISSUE TITLE
Memory leak in realtime chart

### ISSUE THREAD

**Issue by harconst** [apexcharts/apexcharts.js#131]
## Codepen

Using chrome, open the task manager and inspect the browser tab containing a realtime chart like [this codepen](https://codepen.io/harconst/pen/OoexXr) . You will notice that the memory footprint for the tab goes up by the second (sometimes 3MB/sec). Can also be seen in the realtime demo page.

## Explanation

- What is the behavior you expect?

I expected the memory footprint to be almost constant

- What is happening instead?

The memory footprint goes up much faster than expected.

- What error message are you getting?

No error messages

I haven't dove into the source yet, just thought to post my finding here first in case someone has spotted the same issue.

Regards

**Comment by junedchhipa** [comment]
@harconst 
Thanks for catching that. I tested the real-time charts and indeed the memory consumption goes crazy after 5 mins which may ultimately lead to the browser crash.

In the real-time example, at every 2 seconds, the chart is re-drawn by removing all previous DOM elements and event handlers attached to those elements when `appendData()` is called. 

Until now, I am not successful in tracing the exact reason of memory leak (svg.js does some heavy lifting in animation, so I need to test without animation too), but I am keeping an eye on this issue marking it as a high priority bug.

**Comment by junedchhipa** [comment]
Fixed the memory leak issues in the major release v2.0.0
There were DOM elements which were referenced even after destroy()
Removed all such references. Now if you watch the realtime demo example https://apexcharts.com/javascript-chart-demos/line-charts/realtime/ - the memory footprint doesn't increase crazily.

I tested with ~100 chart updates (at every 1 sec), and the Heat Snapshot increased from 21.3 MB to 21.4 MB
![screen shot 2018-10-01 at 1 18 42 pm](https://user-images.githubusercontent.com/17950663/46276149-cbc37100-c57c-11e8-9a81-9ad4f0611cd9.png)
