### ISSUE TITLE
[apex&vue-apexcharts] issue with multiline text in axes labels

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1311]
# Bug report
I'm using:
"apexcharts": "^3.15.5",
"vue-apexcharts": "^1.5.2",

## Codepen
https://codesandbox.io/s/vue-basic-example-gsli0

https://i.imgur.com/81iMdKw.png
https://i.imgur.com/gRZdOMy.png

## Explanation

- What is the behavior you expect?
I was expecting to be able to use on fontSize the calc(), but as soon as I use, it bugs out.

- What is happening instead?
It put everything in the same height (dy) value, so the text gets overlapped instead of look with a proper linebreak. It seems it can't calculate the dy value, since the calc() propbably didnt run yet.

- What error message are you getting?
No error message, its a visual bug. dy its 0.

**Comment by junedchhipa** [comment]
`calc()` is a CSS function (although you can use it with JavaScript when directly manipulating the style of an element). It doesn't work when setting font-size in ApexCharts.
So, you will have to either provide a string `14px` or a number `14`. It doesn't accept anything else.
