### ISSUE TITLE
Heatmap distributed - unexpected colors when row is zero

### ISSUE THREAD

**Issue by fintara** [apexcharts/apexcharts.js#1313]
# Bug report

## Codesandbox
https://codesandbox.io/s/cranky-moore-eknq6

## Explanation

- What is the behavior you expect?
When all values in a row are zeros or empty, the row should be white.

- What is happening instead?
The whole row is colored (in a random color?)

It seems that since version **3.11.2** heatmap with `distributed: true` looks different when all values are zero/empty. Prior to that version the whole row would be white. `distributed: false` also results in white row, as expected.

**Comment by junedchhipa** [comment]
You're right, I made a small mistake in 3.11.2
Fixing it soon.
