### ISSUE TITLE
Toolbar overlaps with Legend

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1314]
# Bug report
Hi there, I'm using Apex with vue-apex and I need to add this code to fix an issue:
![Image of Code](https://i.imgur.com/M4YXDsH.png)

Is there a way to position the toolbar with an offset?

## Explanation

- What is the behavior you expect?
![Image of Expected](https://i.imgur.com/v2tQUPt.png)

- What is happening instead?
![Image of Problem](https://i.imgur.com/8WvycCm.png)

- What error message are you getting?
No error, its visual.

**Comment by junedchhipa** [comment]
The toolbar shouldn't be overlapping legends in the first place.
Can you please paste the whole chart configuration you used?

**Comment by junedchhipa** [comment]
Ok, maybe if you put legend position to `top`, you may get such behavior.

I will add offset values to the toolbar to help with this.

**Comment by Daniel4Digital** [comment]
Exactly, that was what I did. I'll let here the codepen, I forgot to add, sorry:

https://codesandbox.io/s/vue-basic-example-tthxn
