### ISSUE TITLE
Tooltip offset missing?

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1315]
# Bug report
I'm using apex with vue-apex and the tooltip is too near the mouse, and I want to add an offset.
I wasnt able to find out a way to do it. At the moment I need to add this code to fix this problem:
![Image of Code](https://i.imgur.com/NNT5ZDm.png)

## Explanation

- What is the behavior you expect?
![Image of Expected](https://i.imgur.com/sR4vQfk.png)

- What is happening instead?
![Image of Problem](https://i.imgur.com/kC4UK5i.png)

- What error message are you getting?
None, it's a visual problem.

**Comment by Daniel4Digital** [comment]
Here is a codepen to help: https://codesandbox.io/s/vue-basic-example-tthxn

**Comment by Daniel4Digital** [comment]
Any news on this? Would be great to be able to add an offsetX and Y to the tooltip

**Comment by ryota-haramatsu** [comment]
I also cannot solve this problem...

**Comment by Daniel4Digital** [comment]
It seems to be a simple solution. Just a matter of fixing the calcualtion values on this function: https://github.com/apexcharts/apexcharts.js/blob/334bebabbe3506c312873a281388f147a5c7bf09/src/modules/tooltip/Intersect.js#L124
