### ISSUE TITLE
textAnchor ('start') not working

### ISSUE THREAD

**Issue by Heart1010** [apexcharts/apexcharts.js#1317]
# Bug report

I wanted to anchor the text to the left like it is shown in your example [here](https://apexcharts.com/javascript-chart-demos/bar-charts/custom-datalabels/)
On my test the text is always (near) center... not to the left/start.

## Codepen

Here is [my codepen example](https://codepen.io/heart1010/pen/vYOKOox) which demonstrates the problem.

Thanks

**Comment by loopingluke92** [comment]
Hi, I have the same problem. Did you already fix it?

**Comment by Heart1010** [comment]
> Hi, I have the same problem. Did you already fix it?

No

**Comment by hardik-kondhiya** [comment]
@Heart1010 

You can achieve that alignment by using plotOptions under options:

```
options: {
	plotOptions: {
		bar: {
			horizontal: true,
			dataLabels: {
				position: 'bottom' // use 'bottom' for left and 'top' for right align
			},
		}
	},
	dataLabels: {
		enabled: true,
		textAnchor: 'start' // use 'start' if left aligned and 'end' if right aligned
        }
}
```

**Comment by Heart1010** [comment]
position: 'bottom' did it... thanks 👍
