### ISSUE TITLE
Show more information in the tooltip

### ISSUE THREAD

**Issue by luscl1** [apexcharts/apexcharts.js#1319]
I have a multi-series diagram where the x-axis shows the date and the y-axis shows the quantity. In this diagram I have multiple scatter charts. One of the scatter charts is for appointments. For the appointments I have used an own scatter image, on the x-axis it shows the date when the appointment is and on the y-axis is only the number of appointments (which is mostly just 1).

I would like to have more information when I click on the scatter-image. I now just see a tooltip with the date on top and Appointment: 1, because the y-axis is 1.
I would like to see something like Appointment: Job interview -> where job interview is information that I have in my array and can send to the chart.

I tried to use the tooltip y formatter (https://apexcharts.com/docs/options/tooltip/) but I didn't find a solution as I could only show the value of the y-axis in my tooltip or show a standard text for all appointments (but there aren't only job interviews, I need different values).

Furthermore, I have a scatter chart with symptoms the patient had that day, often more than one. At the moment they look the same as the appointment, the y-axis value only shows how many symptoms the patient had. I would like to show the names of the symptoms somehow in the tooltip and not only the quantity. Another option would be that I click on the scatter image and it would change the page to a table with the different symptoms. But I couldn't find out how.

Many thanks in advance!

**Comment by junedchhipa** [comment]
Change the series format to `xy` and pass all extra information in each data-point

```javascript
series: [{
  data: [
    {
      "x": 1486771200000,
      "y": 50,
      "description": "k81gom"
    },
    {
      "x": 1486857600000,
      "y": 28,
      "description": "42plli"
    },
    {
      "x": 1486944000000,
      "y": 25,
      "description": "8tkd62"
    },
    {
      "x": 1487030400000,
      "y": 58,
      "description": "1qc5i8"
    },
    {
      "x": 1487116800000,
      "y": 40,
      "description": "5bnv7s"
    },
    {
      "x": 1487203200000,
      "y": 34,
      "description": "7rcq8t"
    },
    {
      "x": 1487289600000,
      "y": 24,
      "description": "vvv86e"
    },
    {
      "x": 1487376000000,
      "y": 30,
      "description": "oibjbi"
    },
    {
      "x": 1487462400000,
      "y": 26,
      "description": "ychd3"
    },
    {
      "x": 1487548800000,
      "y": 15,
      "description": "lnep2"
    }
  ]
}]
```

Now, use this description or whatever extra information in the custom tooltip like this

```javascript
tooltip: {
  custom: function(opts) {
    const series = opts
    return (
      opts.series[opts.seriesIndex][opts.dataPointIndex] +
      ' - ' +
      opts.w.config.series[opts.seriesIndex].data[opts.dataPointIndex]
        .description
    )
  }
}
```

Granted, you will have to dig the `opts` object a little bit but that stores all the essential information to display the relevant data.
