### ISSUE TITLE
Donut chart warning: Unexpected value 1  parsing stdDeviation attribute

### ISSUE THREAD

**Issue by lucafaggianelli** [apexcharts/apexcharts.js#132]
## Codepen

https://codepen.io/anon/pen/PyYYvV?editors=0011

## Explanation

When drawing a donut chart, a warning occurs on the console (actually 1 warn per donut slice).
The chart renders correctly, but I don't know if the warn is real or can be ignored

- What is the behavior you expect?
To have no warns in console

- What is happening instead?
Console warn

- What error message are you getting?
`Unexpected value 1  parsing stdDeviation attribute`

**Comment by lucafaggianelli** [comment]
No you get it as soon as the chart draws and it shows only in browser dev tools, not in code pen console. I'm using latest Firefox quantum. Anyway, just digging the web I saw that stdDeviation belongs to svg blur filters realm... I managed to get rid of the warn disabling the data labels drop shadow. Maybe this is browser dependant

**Comment by junedchhipa** [comment]
Right! I saw the warning in Firefox - and it indeed leads to svg.js drop shadow method.
Thanks for providing additional info, I will dig more.
