### ISSUE TITLE
pie chart with value 0

### ISSUE THREAD

**Issue by Amosss** [apexcharts/apexcharts.js#1321]
Hi

If the value of the pie slices is 0 for all, I see this
![image](https://user-images.githubusercontent.com/17168621/74822947-956fc880-530e-11ea-839c-502d92856d7e.png)

If I hover the white line (separator) I see the series name with 0. I think this white space should also invisible.

## Explanation
- What is the behavior you expect?
The separator should also be invisible

- What is happening instead?
There is a white space (separator) hanging out of conetxt

- What error message are you getting?
No error message

**Comment by pixieltron** [comment]
Im hitting this same issue
