### ISSUE TITLE
Cannot read property 'querySelector' of null when resizing the chart

### ISSUE THREAD

**Issue by alfredreyes14** [apexcharts/apexcharts.js#1323]
# Bug report

> I am updating the chart's width and height dynamically via vue-draggable-resizeable i'm just wondering if you encountered this error 'Cannot read property 'querySelector of null' when resizing the chart'. Attached below is the screenshot of the error and the way I insert the width and height to the chart,

![apexerror](https://user-images.githubusercontent.com/40394700/74913785-4dc76a80-53fc-11ea-85e4-0dcde320a7bf.PNG)

![bar](https://user-images.githubusercontent.com/40394700/74913825-5c158680-53fc-11ea-9cef-87d0cbea8059.PNG)

**Comment by junedchhipa** [comment]
Can you reproduce the error on [codesandbox](http://codesandbox.io/) ?
