### ISSUE TITLE
Height and width of a pie chart

### ISSUE THREAD

**Issue by Amosss** [apexcharts/apexcharts.js#1325]
Hi

The window of the app is divided into 3 parts horizontally and 2 parts vertically. the height is 45vh. On certain resolutions, the following occurs:
![image](https://user-images.githubusercontent.com/17168621/74987115-25af2a00-5443-11ea-854a-0d0f5852ff5c.png)

Also, if I resize the window to be shorter, the same happens.  I tried controlling the chart.height but it seems that the width controls the height no matter what.

- What is the behavior you expect?
The pie should fit itself to the parent's width/height

- What is happening instead?
The pie overflows its parent

- What error message are you getting?
No error, just a less nice pie :)

**Comment by Amosss** [comment]
I think the same happens with a bar chart
![image](https://user-images.githubusercontent.com/17168621/75081297-52347600-5517-11ea-87b1-e603ae0d52a5.png)

I did
```
chart: {
          height: '5%',
          stacked: true,
```

height of 5% and 100% changed nothing

**Comment by junedchhipa** [comment]
Can you please create codepen demos for both charts?

**Comment by Amosss** [comment]
This is for the second one, maybe it will be enough also for the first one, let me know if not
https://codepen.io/amosss/pen/qBdrPNX

**Comment by junedchhipa** [comment]
The column chart example you provided has empty space because the `height` prop was missing in the 
 vue <apexchart> component.

Regarding the width/height of a pie chart, you can try playing with the `grid.padding.top` and `grid.padding.bottom` properties to adjust the actual pie/donut size.

**Comment by MezzogoriNatisoft** [comment]
I did not resolve that bug. I tried to use these `fix grid.padding.top` and `grid.padding.bottom`, but nothing. Any idea?
