### ISSUE TITLE
[Documentation Error] Chart Events -> click repeated

### ISSUE THREAD

**Issue by Redirts** [apexcharts/apexcharts.js#1327]
# Bug report

Minor issue in documentation page:
https://apexcharts.com/docs/options/chart/events/

The click event entry is duplicated.

## Explanation

- What is the behavior you expect? Only one entry in this page for mouse click event
- What is happening instead? Two entries describing the function
- What error message are you getting? N/A

**Comment by junedchhipa** [comment]
Thanks for the heads up! Fixed it
