### ISSUE TITLE
White space between chart and legend on mobile

### ISSUE THREAD

**Issue by jakeweb** [apexcharts/apexcharts.js#1328]
# Bug report

## Codepen
https://codepen.io/yetanua/pen/MWwbKqy

## Explanation

- What is the behavior you expect?
I expect there is no white space between chart and legend.

- What is happening instead?
On PC in mobile mode it looks good, but on real device - not. 
Maybe worth to note: it looks better if legend contains small count of data, but with big count - it is not.

- What error message are you getting?
None.

![Screenshot_403](https://user-images.githubusercontent.com/17675830/75039560-9d239e80-54c1-11ea-968c-707e7e77682b.png)

**Comment by adam-marshall** [comment]
This is affecting me too.

It can be seen even on the ApexCharts official demo here: https://apexcharts.com/javascript-chart-demos/dashboards/modern/

The left chart is a screenshot of Chrome for Android. The right is Chrome for Desktop with developer tools mobile mode.
![image](https://user-images.githubusercontent.com/2521384/75330808-8f7f6780-5879-11ea-810d-dee8f8f31629.png)

The spacing seems to be linked to the number of items in the legend, the greater the height of the legend, the greater the height of the white space.

**Comment by junedchhipa** [comment]
This is a work-in-progress and will be addressed soon.
Closing this in favor of #636
