### ISSUE TITLE
PointAnnotations not hidden when hiding corresponding label/series

### ISSUE THREAD

**Issue by Redirts** [apexcharts/apexcharts.js#1329]
# Bug report

Point Annotations not hidden when series is hidden by clicking on graph

## Codepen

https://codepen.io/Redirts/pen/ExjNyOa

## Explanation

- What is the behavior you expect? When I click on legend to hide, the annotation should be hidden
- What is happening instead? Annotation is kept visible.
- What error message are you getting? N/A

**Comment by Redirts** [comment]
Seems fixed on current version

**Comment by GinaJemy** [comment]
I have the same issue. You can find my codepen here [https://codepen.io/ginajemy/pen/MWjvrEo](https://codepen.io/ginajemy/pen/MWjvrEo). The issue isn't clear in Redirts codepen as it only contains one series, but when there are multiple series and we only hide one, the annotations on the hidden series are still visible.

**Comment by aline-matos** [comment]
+1

**Comment by anuragg33** [comment]
+1
