### ISSUE TITLE
Donut/Pie chart height not working

### ISSUE THREAD

**Issue by lucafaggianelli** [apexcharts/apexcharts.js#133]
## Codepen

https://codepen.io/anon/pen/PyYYvV?editors=0011

## Explanation

when I set the height of a donut or pie chart to a finite number, the container has the requested size, but the chart takes the full width available ignoring the height, so it is cut off. When running the pen, please be sure that windows height is smaller than width.

- What is the behavior you expect?
I expect that the cart fit inside the container without being cut

- What is happening instead?
- What error message are you getting?

**Comment by junedchhipa** [comment]
Thanks for catching that @lucafaggianelli 
Just fixed it in https://github.com/apexcharts/apexcharts.js/commit/77fa8a7f5f9e4fbf95bb70b0c44a83e906814f65

**Comment by lucafaggianelli** [comment]
Great! Thanks
