### ISSUE TITLE
Distributed Bar Chart fill colors can't be set per bar when used in mixed chart

### ISSUE THREAD

**Issue by phivk** [apexcharts/apexcharts.js#1333]
# Bug report

## Codepen

https://codepen.io/phillchill/pen/zYGNgKO

## Explanation

- **What is the behavior you expect?**
On a regular Bar Chart I can set `plotOptions.bar.distributed` to `true` to set fill colors of individual bars by passing an array of colors to `options.colors`:

![Screenshot 2020-02-25 at 3 01 57 PM](https://user-images.githubusercontent.com/902958/75259832-ef79fd80-57e8-11ea-9905-0d1cacf854ac.png)

Now I'm creating a mixed chart with a bar and a line series.

When using `plotOptions.bar.distributed` = `true`, I expect to be able to use a combination of `options.colors`, `options.fill.colors` and/or `options.stroke.colors` to set individual bar colors by passing arrays of colors with the same length of `series`.

Ideally I'd like to:
1. set individual bar fill colors
2. separately set strokes for bar and line series
3. set series colors in legend

- **What is happening instead?**

![Screenshot 2020-02-25 at 4 04 52 PM](https://user-images.githubusercontent.com/902958/75259653-a2962700-57e8-11ea-9961-b3c0ac6c904a.png)

When passing a colorArray like `['#ccc', '#ccc', '#0F0', '#ccc']` with the same length of `series` I observe the following behaviour:

`options.colors` seems to set both:
- series color in legend
- bar stroke color (when `options.stroke` is not specified)

`options.fill` seems to be ignored

`options.stroke` seems to set:
- stroke of line series
- stroke of bar at index of color in colorArray
- fill of bars by repeating the value of the first 2 (number of series?) elements in the colorArray.

- **What error message are you getting?**

none.

- ps, potentially related to:
https://github.com/apexcharts/apexcharts.js/issues/341
https://github.com/apexcharts/apexcharts.js/issues/591

**Comment by NishaBuha** [comment]
Any new about this point?

**Comment by phivk** [comment]
@junedchhipa would you be able to investigate?

**Comment by talha2k** [comment]
Still no solution!
