### ISSUE TITLE
xaxis annotations locations are off

### ISSUE THREAD

**Issue by AmberWilliams** [apexcharts/apexcharts.js#1334]
# Bug report

## Codepen
https://codepen.io/amberwilliams/pen/QWbpLaj

## Explanation
Expect the x-axis annotation to be on May 20th. I've noticed this behavior only happens when you are labeling the xaxis points as it works here as expected - https://codepen.io/amberwilliams/pen/xxGgvmR

- What is happening instead?
Annotation is being put in between axis data points.

**Comment by AmberWilliams** [comment]
Update: Did some digging and noticed this issue started after the Version 3.11.3 release

**Comment by junedchhipa** [comment]
The annotation renders at the correct place in your codepen. As it is a datetime x-axis, the labels are auto-generated.
If you are not seeing the annotation label, you should set the `annotations.xaxis.label.text` property.

**Comment by AmberWilliams** [comment]
<img width="679" alt="Screenshot 2020-03-04 at 11 07 49" src="https://user-images.githubusercontent.com/51619139/75873793-75f59700-5e08-11ea-8bc5-88ac3b38f807.png">
Didn't really have much time to respond before you closed this. But no it is not in the correct place, I attached the picture of where the line should be (red) vs where it is (grey). 

And sorry for the confusion but I am not talking about the label text just reusing other peoples' code that represents this issue because mine is rather complex to post but it **absolutely** is not working correctly unless you revert back to 3.11.3. 

![image](https://user-images.githubusercontent.com/51619139/75874669-244e0c00-5e0a-11ea-9699-25e753b6c345.png)

![image](https://user-images.githubusercontent.com/51619139/75874788-5e1f1280-5e0a-11ea-916f-38979b840a91.png)

The only thing I changed between the two is using  ` "apexcharts": "3.11.2"` vs  `"apexcharts": "^3.11.2"`in the package.json

**Comment by junedchhipa** [comment]
In the codepen, you had set the annotation's x value as `20 May 2020`, so, the grey line is actually on 20 May 2020. Wile your red-line is on 01 May 2020.

The last digits ('20) is the year, not date. So, I still don't see any issue in the annotation placement.

**Comment by AmberWilliams** [comment]
I see yes you are right! Let me put together a code pen that better represents this issue when I have sometime
