### ISSUE TITLE
Log scale for multiple column chart

### ISSUE THREAD

**Issue by ericpresas** [apexcharts/apexcharts.js#1335]
# Bug report

I updated from version 13.10.1 to 13.15.6 and now i have the following bad behaviour.
## Codepen

[Reproduced in codepen](https://codepen.io/ericpresas/pen/OJVpJLV) 

## Explanation

- What is the behavior you expect?
The chart should be displayed.
- What is happening instead?
No columns in the chart and NaN values in yaxis when using logarithmic scale.
But it's working in linear scale.
This example worked for me in version 13.10.1.

- What error message are you getting?
No message error...

**Comment by junedchhipa** [comment]
Thanks for reporting, I just fixed it and will release an update soon.
