### ISSUE TITLE
Invert Y scale

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1337]
How do I invert the Y axis scale? The chart seems to assume that bigger numbers are greater, but in my case, the smallest number should be at the top of the scale. That is, I want my Y scale to be inverted. Setting min > max in the `yscale` options does not have the desired effect.

**Comment by junedchhipa** [comment]
`yaxis.reversed: true`
https://apexcharts.com/docs/options/yaxis#reversed

**Comment by Bilge** [comment]
Hi @junedchhipa. Thanks for drawing my attention to this setting, however, this is still not the correct behaviour for an area chart because it fills the chart above the line instead of continuing to fill below the line as normal.

**Comment by junedchhipa** [comment]
@Bilge I got your point and it's a valid point. However, the area chart just takes the yaxis scale and continues from min to max (drawing an inversed graph as you said).
There is no quick workaround as of now, but in the future, a new property "reverseFill" can be added to solve this issue.

**Comment by Bilge** [comment]
OK, so perhaps we can reopen this issue?

**Comment by mykcryptodev** [comment]
I would love a "reverseFill" option for this reason - any plans to implement?

**Comment by mykcryptodev** [comment]
actually, it looks like adding this solves the issue:
`    plotOptions: {
      area: {
        fillTo: 'end'
      }
    }`
 
got it from here: https://github.com/apexcharts/apexcharts.js/issues/1472
