### ISSUE TITLE
Bar Chart states filters not working in Firefox

### ISSUE THREAD

**Issue by phivk** [apexcharts/apexcharts.js#1338]
# Bug report

## Codepen

https://codepen.io/phillchill/pen/abOJwEP

## Explanation

- **What is the behavior you expect?**

I expect bar chart fill colors to change when a dataPoint state changes to `hover` or `active`. This works as expected in Chrome (2nd datapoint `active`, 4th datapoint `hover`):

![Screenshot 2020-02-26 at 10 00 56 AM](https://user-images.githubusercontent.com/902958/75329114-63ff7b80-587f-11ea-870d-01171e20da8c.png)

- **What is happening instead?**

State filters are not working in Firefox (2nd datapoint `active`, 4th datapoint `hover`):

![Screenshot 2020-02-26 at 10 01 15 AM](https://user-images.githubusercontent.com/902958/75329149-724d9780-587f-11ea-9d4b-283a569ffae5.png)

- **What error message are you getting?**

`TypeError: n is null`

**Comment by junedchhipa** [comment]
Fixed in #1913
