### ISSUE TITLE
tooltip.enabledOnSeries doesn't work as expected in irregular timeseries line charts

### ISSUE THREAD

**Issue by oherik** [apexcharts/apexcharts.js#1339]
# Bug report
I have found some inconsistent `tooltip.enabledOnSeries` behavior in irregular timeseries line charts.

## Codepen
Minimal working example:
https://codesandbox.io/s/vue-basic-example-0ibes?fontsize=14&hidenavigation=1&theme=dark

## Explanation
When using `tooltip.enabledOnSeries` I expect tooltips to be enabled on the series that have the corresponding indices, as specified in the docs. Right now I can't get it to work in my chart, which is a timeline line chart with different time ranges.

Example values of `enabledOnSeries` in the Codepen example, and what happens:

 - `enabledOnSeries: []`: tooltips disabled for all series
 - `enabledOnSeries: [0]`: tooltips enabled for all series
 - `enabledOnSeries: [1]`: tooltips disabled for all series
 - `enabledOnSeries: [0, 1]`: tooltips enabled for all series
 - `enabledOnSeries: [1, 2]`: tooltips disabled for all series

The key element seems to be if series 0 is included or not, in which case all series get tooltips.

**Comment by guillept** [comment]
@junedchhipa Is there any solution for this issue? I'm having the same problem: https://codepen.io/guille_pt/pen/vYNXpbL

**Comment by thellimist** [comment]
Same problem still exists. In my case it's not `irregular timeseries line`, rather it's a scatter chart with a line chart.

**Comment by www-chique** [comment]
Same here

**Comment by eladeyal-intel** [comment]
@junedchhipa this is still replicated for many including us in latest version. can the issue be re-opened? (and hopefully fixed). thanks

**Comment by ColemanDunn** [comment]
Facts. This doesn't work. In fact, another post about a bug with this option was fixed and is actually no longer working: https://github.com/apexcharts/apexcharts.js/issues/824

Take their codepen code in the link they provided and paste it here: https://codepen.io/apexcharts/pen/xYqyYm

observe that it doesn't work.

**Comment by hillcjames** [comment]
Just want to chime in, this is currently broken for multicharts.

**Comment by SDIjeremy** [comment]
Still broken

**Comment by hauard** [comment]
No fix  for this? Having the same issue

**Comment by functionpointer** [comment]
I am annoyed at this as well

**Comment by Jasper992** [comment]
push (working with apexcharts react)

**Comment by bosseDev** [comment]
Any update on this?

**Comment by quiquelhappy** [comment]
bump

**Comment by c0rnonthec0bb** [comment]
Same here

**Comment by c0rnonthec0bb** [comment]
Same here @junedchhipa

**Comment by SaswatPadhi** [comment]
Same here. Any plans on fixing this?

**Comment by mbnewsom** [comment]
bump

**Comment by AdamRidley** [comment]
This bug still exists, the issue needs to be reopened.

**Comment by vegetablesalad** [comment]
So is this a issue that is still not resolved 4 years later ?
I just stumbled upon the same result.

**Comment by djang0man** [comment]
I experienced this issue when using multiple charts with the same chart group. I resolved the issue by wrapping each of the charts in a wrapping div with CSS `overflow: hidden`. Something like: 

```
<div style="overflow: hidden">
  ...chart 1 goes here
</div>
<div style="overflow: hidden">
  ...chart 2 goes here
</div>
```

This prevents the tooltip from the neighboring charts from appearing over the hovered chart. Hope that helps some of you!

**Comment by jdegger** [comment]
As this issue is not being reopened, I have created a new one:

https://github.com/apexcharts/apexcharts.js/issues/4597

**Comment by jdegger** [comment]
@junedchhipa thanks for reopening!

Another reproduction link as mentioned in this issue still works:

https://codepen.io/guille_pt/pen/vYNXpbL

**Comment by jdegger** [comment]
@brianlagunas the requested reproduction link posted above
