### ISSUE TITLE
Zoom not working with logarithmic

### ISSUE THREAD

**Issue by Mariebel111** [apexcharts/apexcharts.js#1342]
## Codepen

https://codepen.io/mariebel111/pen/OJVWKZE

## Explanation

- What is the behavior you expect?
Zoom should also work when logarithmic option is set to true

- What is happening instead?
Nothing happens

- What error message are you getting?
Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by shukerullah** [comment]
Updates?

**Comment by mikkogozalo** [comment]
I am confirming this problem. I am getting the same error message as @Mariebel111
