### ISSUE TITLE
Tooltips not showing on 0% bars

### ISSUE THREAD

**Issue by Webling** [apexcharts/apexcharts.js#1344]
Hi guys,

thanks for the chart library. Our team really enjoys working with the charts.

I stumbled upon an issue in horizontal/vertical charts, where I have no chance to hover/click to show the tooltip, when the value of the bar is 0%.

Is there a way to make the tooltip visible on hovering over the datalabel or the "empty" bar?

Your help is really appreciated.

**Comment by junedchhipa** [comment]
Have you tried turning off `tooltip.intersect` flag and enabling a shared tooltip?

```javascript
tooltip: {
  shared: true,
  intersect: false
}
```

**Comment by Webling** [comment]
Thanks @junedchhipa, I tried that, but it has no effect since the Tooltips only open on hovering the bars.

Anyone else an idea?

**Comment by jbrtsnts** [comment]
`tooltip.shared: true` works for me

**Comment by NataliaSarosiek** [comment]
> Have you tried turning off `tooltip.intersect` flag and enabling a shared tooltip?
> 
> ```js
> tooltip: {
>   shared: true,
>   intersect: false
> }
> ```

Hi, this works but unfortunately only if the bar is not horizontal, see here: http://jsfiddle.net/uzqa8gLp/1/ , is this intended behaviour for horizontal bars?
