### ISSUE TITLE
Gradient Donut Chart demo doesn't show a gradient

### ISSUE THREAD

**Issue by adam-marshall** [apexcharts/apexcharts.js#1345]
See https://apexcharts.com/javascript-chart-demos/pie-charts/gradient-donut/
![image](https://user-images.githubusercontent.com/2521384/75434846-1439b680-594a-11ea-8dd1-6821555fd4fd.png)

## Explanation

The donut chart does not have a gradient, it has fill but is perhaps missing opacity configuration.

**Comment by junedchhipa** [comment]
Thanks, a change made recently disabled gradients.
Reverted it.

**Comment by romain130492** [comment]
> Thanks for reporting, a change made recently disabled gradients.
> Reverted it.

Hello, I do think it's still disabled on [vue-apexchart ](https://github.com/apexcharts/vue-apexcharts) for donut/pie   ,no ? 

Thanks!

**Comment by junedchhipa** [comment]
This was an issue with core-apexcharts. So, updating `apexcharts` to the latest should resolve it.
