### ISSUE TITLE
Grid for X axis line in Vertical is colliding with bar 

### ISSUE THREAD

**Issue by kkpriyankacoding** [apexcharts/apexcharts.js#1346]
#Grid for X axis line in Vertical is colliding with bar  with one element

> Please refer this link for my sandbox - https://codesandbox.io/s/apx-column-basic-22xis?fontsize=14&hidenavigation=1&theme=dark

## Explanation

- What is happening instead?
For Vertical its working like this. The Grid X axis line is overlapping with the bar 
![Screenshot from 2020-02-27 17-37-581](https://user-images.githubusercontent.com/39261701/75443753-1458a700-5988-11ea-86ed-ea04de2fe999.png).If a graph with more than one element grid lines are working . if it is having one element then it is overlapping

- What is the behavior you expect?
For horizontal its working Cool. The Grids X axis lines and Y axis lines are aligned properly . 
![Screenshot from 2020-02-27 17-40-362](https://user-images.githubusercontent.com/39261701/75444003-9517a300-5988-11ea-8788-52648913f5db.png). How can i make it work for X axis grid line with one element in graph.

**Comment by junedchhipa** [comment]
Thanks for reporting, just fixed it.
The patch will be released soon.

**Comment by kkpriyankacoding** [comment]
Thank you @junedchhipa  .i am super proud of our APEX.

**Comment by kkpriyankacoding** [comment]
When can we expect this release npm (ng-apexcharts) ? i can observe new build was released does it effects NPM's Ng-apexcharts

**Comment by junedchhipa** [comment]
You only need to update the core **apexcharts@3.16.1** for this fix. No need to update ng-apexcharts.

**Comment by kkpriyankacoding** [comment]
Hey @junedchhipa  i updated the core apexchart i encountered with another bug which the bar is overlapping the grid line . Please refer
 ###FIG 2
![Screenshot from 2020-03-13 11-54-56](https://user-images.githubusercontent.com/39261701/76595632-273faf80-6522-11ea-868a-817a3cfa7e5b.png)
