### ISSUE TITLE
Ability to make X and Y axis distinct from other grid lines

### ISSUE THREAD

**Issue by meetmangukiya** [apexcharts/apexcharts.js#1348]
**Is your feature request related to a problem? Please describe.**	
Trying to get the 0 point on the axis - the X and Y axis a different color than other grid lines.

**Describe the solution you'd like**	
Able to specify color for the X and Y axis

**Comment by junedchhipa** [comment]
Try `xaxis.axisBorder.color` & `yaxis.axisBorder.color`
https://apexcharts.com/docs/options/yaxis/#axisBorder

**Comment by meetmangukiya** [comment]
This doesn't make the origin lines / axis (x = 0, y = 0) 
![image](https://user-images.githubusercontent.com/7620533/75612773-b9bc7800-5b4c-11ea-99f3-87c1923871a3.png)

**Comment by junedchhipa** [comment]
You can do it with annotations

```javascript
annotations: {
  yaxis: [
    {
      y: 0,
      strokeDashArray: 0,
      borderColor: '#111',
      borderWidth: 1,
      opacity: 1
    }
  ],
  xaxis: [
    {
      x: 0,
      strokeDashArray: 0,
      borderColor: '#111',
      borderWidth: 1,
      opacity: 1
    }
  ]
}
```

Annotation Docs - https://apexcharts.com/docs/options/annotations/

**Comment by meetmangukiya** [comment]
This is great, thanks! Exactly what I was looking for

**Comment by Baracoj** [comment]
If you want just the line in the x axis, try this:
```
annotations: {
    yaxis: [
      {
        y: 0,
        strokeDashArray: 0,
        borderColor: "#80AAF8",
        borderWidth: 1,
        opacity: 1
      }
    ]
  },
```
![image](https://user-images.githubusercontent.com/10285973/153906813-72bd420f-c944-4a93-83d9-8ff247fd6fcc.png)
