### ISSUE TITLE
Column chart : custom the space between bars

### ISSUE THREAD

**Issue by eved42** [apexcharts/apexcharts.js#1350]
**Is your feature request related to a problem? Please describe.**	
I'm frustrated because I don't find the solution to manage easily the space between the bars.

![image](https://user-images.githubusercontent.com/12841417/75664091-35641500-5c72-11ea-9adb-05c1d86f384c.png)

**Describe the solution you'd like**	
A property to change the scale of x/y axes.
I would like to make thin & tight bars : 
![image](https://user-images.githubusercontent.com/12841417/75664524-e1a5fb80-5c72-11ea-8799-1668fe07c16b.png)

**Describe alternatives you've considered**	
I tried to change the `plotOptions` > `bar` > `columnWidth` property, testing with `stroke` property too, change the `grid` parameters...

**Additional context**	
Code : 
```
var totalChart = new ApexCharts(document.querySelector("#totalChart"), {
    series: [{
      name: 'Contrats',
      data: $('#totalChart').data('stats').split(',')
    }],
    chart: {
      type: 'bar',
      height: '170px',
      toolbar: { show: false },
      foreColor: '#657a8e',
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '20%',
        distributed: true,
        colors: {
          backgroundBarColors: ['#F2F4F6']
        },
      }
    },
    legend: { show: false },
    xaxis: {
      axisBorder: { show: false },
      axisTicks: { show: false },
      categories: [
        'Cadre', 'MPDV', 'Groupement', 'Indirect'
      ],
      labels: {
        style: {
          fontSize: '12px'
        }
      }
    },
    yaxis: { show: false },
    colors: ['#007BFF'],
    grid: {
      show: false,
    },
    tooltip: {
      y: {
        formatter: function (val) {
          return val;
        }
      }
    }
  });
```

**Comment by junedchhipa** [comment]
The `columnWidth` property should achieve the desired result.
Can you please post a codepen of what you've tried?

**Comment by eved42** [comment]
[See codepen](https://codepen.io/eved42/full/GRJvjjg)

I just noticed that I don't have the same result on Chrome and Firefox with codepen. I don't have a bug on the last label on Chrome in my real project, all the 4 labels is displayed.

No `columnWidth` just resize the width of the bars and not resize the space between each bar.

I know when the bars are heavy, there is less space between them but **I want thin bars and a small space between them**.

**Comment by StarryFire** [comment]
@eved42  did you fix your problem?

**Comment by eved42** [comment]
@StarryFire Unfortunately not. I did what I wanted with Bootstrap and progress bars. I don't use apexcharts.js anymore to build my chart.

**Comment by junedchhipa** [comment]
@StarryFire You can try playing with `chart.width` and `plotOptions.bar.columnWidth` both to get different results.

@eved42 If the chart's width is set to `100%`, then the bars will try to position themselves as widely as possible.

**Comment by StarryFire** [comment]
```
stroke: {
    colors: ['transparent'],
    width: 2,    
}
```

I was able to add space between the columns/bars using the above stroke property in options. Putting this here so it might help someone else.

**Comment by musasutisna** [comment]
Just add empty data to series and categories, check your first data before set into options.
Below an example using the minimum of ten data to show.

```javascript
let data = $('#totalChart').data('stats').split(',')
let categories = ['Cadre', 'MPDV', 'Groupement', 'Indirect']

for (var i = data.length; i <= 10; i++) {
  data.push(0)
  categories.push('')
}
```

**Comment by Dinuz** [comment]
The bar width behavior is inconsistent. Setting the columnWidth to 100%, should eliminate the gap between columns, instead the gap exist, it's small, but not constant between each columns (sometimes is 5px, sometimes is 3px, sometimes is 0px and sometimes is even -2px).

**Comment by anilkumarpc** [comment]
> ```
> stroke: {
>     colors: ['transparent'],
>     width: 2,    
> }
> ```
> 
> I was able to add space between the columns/bars using the above stroke property in options. Putting this here so it might help someone else.

but decreases the width of color bar

**Comment by jonzalez18** [comment]
So here is a decent solution. nothing above worked for me. It'll take a few steps and maybe some wierd ideas for responsiveness. Where you would like spaces add extra series for space the values must be {x: jan-dec, y: [0, 0]}.... options.legend.showForZeroSeries: false, is helpful to remove the legend for these values. now if you want to start to begin adjusting the size of the bars, where you are mapping your data. {x: jan-dec, y: [0, 0],  columnWidthOffset: -2.2}. start playing with this  columnWidthOffset until you get desired results. it's not simple but it took me a while before I came up with any reasonable solution. columnWidthOffset. will be positive if you want the bar to be bigger or negative for a reduction. Please try this or if you found a way to another chart for ease of use lol good job this was annoying. oh, before i forget. I'm going to probably create a react useState to set the columnWidth to the appropriate size based off the window width and apply this state into my data.columnWidthOffset to give me a more desirable result all on viewports.

**Comment by sergeyalikin** [comment]
I also encountered this problem in a vertical bar. I solved this by calculating the height depending on the number of elements. Adjust the number to give the expected distance between elements.

I hope this will be useful to someone.

```
...

const options: Props['options'] = {
   ...
  plotOptions: {
    bar: {
      barHeight: 32,
      ...
    },
  },
  ...
}
...

export const BarChart: React.FC = () => {
  const height = state[0].data.length * 45
  return (
    <Chart
      options={options}
      series={state}
      height={height}
      type='bar'
    />
  );
};
```

**Comment by HamzaNapollo** [comment]
#

![Image](https://github.com/user-attachments/assets/b47fd4eb-8d43-471c-9006-f5d4873317b9)

How i can reduce the gap/space between the bars so it can be very close to each other ?
I have tried many ways but nothing is working for that. Is there have any solution u guys ?
