### ISSUE TITLE
Bug - fontWeight doesnt work on axis

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1352]
if I add the fontWeight at the title in options, it works, but if I add it the title with fontWeight inside the axis, it doesnt work:

https://codesandbox.io/s/vue-basic-example-x7ftx

As we can see on that sandbox, it doesnt add the bold to the hello world on the yaxis

**Comment by junedchhipa** [comment]
Fixed the font-weight in the last commit.
The patch will be released soon.
