### ISSUE TITLE
How can i implement this type of mixed chart functionality   with the increase ratio of data between the bars

### ISSUE THREAD

**Issue by kkpriyankacoding** [apexcharts/apexcharts.js#1355]
How can i implement a bar chart with some statistics and badge with the increase ratio of data between the bars

Please do refer the image

![Screenshot from 2020-03-03 14-30-24](https://user-images.githubusercontent.com/39261701/75759570-d37fda00-5d5b-11ea-96e6-0828d9fc1d67.png)

**Comment by junedchhipa** [comment]
Unfortunately, such customizations are not supported out of the box.
You might have to play with annotations, calculate the increase of percentage and plot them accordingly after offsetting the positions of annotations. I am not even sure if it is achievable, just giving out some pointers.

Thanks!
