### ISSUE TITLE
toggleDataPointSelection not showing tooltip when selected

### ISSUE THREAD

**Issue by apeter10** [apexcharts/apexcharts.js#1361]
# Bug report
I'm using the line chart. When I hover some point, tooltips are shown, a vertical line is drawn on the chart to show the hovering point, the marker's current point change size accordingly to the options.

If I wanna trigger this effect without hovering manually the chart but by hovering some other element in the page, how to do I implement that feature?

The toggleDataPointSelection method should show the name and value of the series, but currently only highlight the marker.

## Codepen

https://codepen.io/apeter/pen/XWbeOyL?editors=0010

## Explanation

- What is the behavior you expect?
<img width="653" alt="截圖 2020-03-06 上午6 44 59" src="https://user-images.githubusercontent.com/4221247/76033246-bd9a3100-5f76-11ea-8ac9-093330f3283b.png">
- What is happening instead?
<img width="650" alt="截圖 2020-03-06 上午6 44 51" src="https://user-images.githubusercontent.com/4221247/76033219-ad825180-5f76-11ea-99ba-e5be9e10d60d.png">

**Comment by junedchhipa** [comment]
The tooltip only shows when the user directly interacts with the chart.
It doesn't get displayed on the data-point selection. It's not a bug but the feature you're expecting isn't there.

**Comment by p19ky** [comment]
Has this feature been added since 2020 or not yet?

**Comment by ryuzakii29** [comment]
found a solution for this issue, you can clone the tooltip on datapointselection event, here's a sample of the code https://codepen.io/ryuzakii29/pen/zYjZGxR
