### ISSUE TITLE
Y and Z-axis options for bubble charts

### ISSUE THREAD

**Issue by dorarad17** [apexcharts/apexcharts.js#1366]
Is it possible to have time of day on the Y-axis (e.g. 8:00 at the lower end to 24:00 at the upper end) and where can you edit the z-axis options (e.g. label of z value when you hover over each bubble)?

**Comment by junedchhipa** [comment]
You can customize the y-axis labels with 
```javascript
yaxis: {
  labels: {
    formatter: function(val) {
      return val + ":00"
    }
  }
}
```

To change the z label of the tooltip, you can do

```javascript
tooltip: {
  z: {
    title: 'Custom Label:'
  }
}
```
