### ISSUE TITLE
Chart is not responsive to its container or window

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#137]
## Explanation

- What is the behavior you expect?
SVG element should resize and chart should redraw https://codepen.io/anon/pen/rqVyWm 

- What is happening instead?
Chart just has fixed width leading to either being small or overflowing its container or window https://codepen.io/anon/pen/ZqGezO 

- What error message are you getting?
None

**Comment by junedchhipa** [comment]
Fixed in v2.0.5

**Comment by jimfilippou** [comment]
I can confirm this is fixed since I had the same issue 🎆
