### ISSUE TITLE
Mixed chart y-axis scaling issue (with stacked true) 

### ISSUE THREAD

**Issue by vincemat** [apexcharts/apexcharts.js#1371]
# Bug report

## Codepen
Please look at [this codepen](https://codepen.io/vincemat/pen/dyoJzjj). 

## Explanation

- What is the behavior you expect: 
I expect the y-axis to be set (near) to the max value (sum of area data or highest value of line data)
- What is happening instead:
The y-axis is scaled based on the sum of the area + line data which lead to a wrong scaling of the chart
- What error message are you getting:
No error message, just a question of visualisation of data

**Comment by JohnRomanski** [comment]
I think all 3 need to be `area` to stack

https://codepen.io/vincemat/pen/dyoJzjj
```
          name: 'TEAM B',
          type: 'area',

```

**Comment by vincemat** [comment]
Yes, I understand that the scaling is based on the stacked of the 3 but in my case I would like to have a mixed chart (line+area stacked) without the scaling being the sum of the three but the max(A+C, B)...

**Comment by JohnRomanski** [comment]
What you are expecting makes sense now, maybe you can add that to the issue description?
In terms of your request, this seems to be an outstanding bug based on https://github.com/apexcharts/apexcharts.js/issues/26#issuecomment-527659244

**Comment by Adriien-M** [comment]
@vincemat did you find any workaround to solve this issue?

**Comment by vincemat** [comment]
Indeed, the only solution is to specify a max option in yAxis properties...

**Comment by oliveli** [comment]
Setting a fixed max value doesn't work in all cases, since with it you loose the charts ability to dynamic adjust the Y-axis when a series is hidden via clicking the legend.

So IMHO it would be best to calculate Y-Axis max value like this:
- determine _max-value_ of each data series (i.e. line/area/bar) in the chart
- if type (line/area/bar) **is stacked**: calculate **sum** of _max-value_ of all series of the same type
- if type is **not stacked**: determine max _max-value_ of all series of the same type 
- set y-Axis.max to  max of all _max-values_ of each series type

best regards

**Comment by iameddz** [comment]
I have the same problem. Has anyone already found a workaround (without loosing the ability to dynamic adjust the Y-axis)?
The ticket #531 from 2019 had already described the same behavior.

**Comment by PaulKujawa** [comment]
In our case we are stacking positive and negative numbers:

```js
yaxis: {
     max: incomes.reduce((max, curr) => Math.max(max, curr)),
     min: expenses.reduce((min, curr) => Math.min(min, curr)),
 },
 ```
seems to solve it for us:
<img src="https://user-images.githubusercontent.com/2843557/128502321-66085415-8814-4118-af90-133e5f755723.png" height="200px" /> <img src="https://user-images.githubusercontent.com/2843557/128502188-9214fe4e-6788-4874-a2ad-f79280365797.png" height="200px" />

**Comment by vincemat** [comment]
I did not find any workaround yet... But I'm totally open to any idea because I'm quite stuck with this...
