### ISSUE TITLE
Data messing up with negative values in stacked area graph

### ISSUE THREAD

**Issue by vincemat** [apexcharts/apexcharts.js#1372]
# Bug report

## Codepen

Please look at [this codepen](https://codepen.io/vincemat/pen/yLNpRyM). 

## Explanation

- What is the behavior you expect: 
When removing a serie from the visualisation by clicking on it on the legend, the value of this serie is disapearing but the result data on the graph is wrong.
- What is happening instead:
If I click on 'west', the graph is showing data for 'north' and 'south' but the graph is not in line anymore with the real data: in 2004 the sum of south (318) and north (-156) is 162 but the graph is showing negative value for the total.

![image](https://user-images.githubusercontent.com/12695531/76306999-39261600-62c8-11ea-9c4e-fd601013650d.png)

**Comment by junedchhipa** [comment]
You're right, I confirm the issue and will look into it soon.
