### ISSUE TITLE
Datetime line graph inserts null datapoint

### ISSUE THREAD

**Issue by joshleblanc** [apexcharts/apexcharts.js#1374]
![image](https://user-images.githubusercontent.com/1729810/76366971-44019a80-630a-11ea-8336-12c87e1f29f2.png)

codepen: https://codepen.io/ThirdSign/pen/ExjQjVQ

I have a line graph with a number of series. Each series has 1 data point, and they're not sharing any x-axis points. Apex charts is inserting, or at least thinks there is, a null data point at the same X position as *some* of the data points. Not all of them. 

In the code pen you can see this happening on the right most point. You'll have to wave your mouse around a bit to find it, but you'll notice you'll have a hard time focusing the right-most data point at all, which I assume is related.

**Comment by ger-pakon** [comment]
Hey,

I've got the same issue, that the chart is breaking, when I use the "datetime" type for a multiple line chart.

In fact, the behavior is a little bit different. I try to render multiple lines in the chart, the first one showing. If I change the order of the linecharts, more than one is showing. When I switch to "category" as type, all lines are showing, but the xaxis is not really sorted (as expected).

I can provide output to a developer when needed.

Thank you.

Cheers,
Pakon

**Comment by mohammadsyuhada** [comment]
<img width="1276" alt="Screenshot 2024-09-30 at 2 12 19 PM" src="https://github.com/user-attachments/assets/81c4e27d-afe7-473f-a572-0e59c8712674">

Issue is still present in the latest version 3.54.1

**Comment by junedchhipa** [comment]
The original issue is not reproducible in the latest version as tested on v4.3.0.
