### ISSUE TITLE
multiple backgroundBarColors seems not to work

### ISSUE THREAD

**Issue by nicmare** [apexcharts/apexcharts.js#1375]
# Bug report

i passed several hex codes to plotOptions->bar->colors->backgroundBarColors but it just uses first entry color

## Codepen

https://codepen.io/nicmare/pen/vYOdxpj

**Comment by Densevoid** [comment]
Confirming the problem. I got the desired result by correcting the source code, but I don't think I did it in a good way.

First on line 18466 I add `j` argument to sending object:
```
this.barHelpers.barBackground({
          bc: bc,
          i: i,
          j: j,
          x1: barXPosition,
          x2: barWidth,
          elSeries: elSeries
        });
```

And then on line 6180 I changed 
```
if (bc >= this.barCtx.barOptions.colors.backgroundBarColors.length) {
    bc = 0;
}
var bcolor = this.barCtx.barOptions.colors.backgroundBarColors[bc];
```
to
```
if (j >= this.barCtx.barOptions.colors.backgroundBarColors.length) {
    j -= this.barCtx.barOptions.colors.backgroundBarColors.length;
}
var bcolor = this.barCtx.barOptions.colors.backgroundBarColors[j];
```

But it's actual for stacked column charts. Another type of bar-charts need changes in another places.

**Comment by junedchhipa** [comment]
@Densevoid Thanks for the hint. I tried your code and it worked fine.
Will fix it soon.
