### ISSUE TITLE
Apex cut off max value in graph

### ISSUE THREAD

**Issue by KiddingMe42** [apexcharts/apexcharts.js#138]
## Codepen

[Example](https://codepen.io/apexcharts/pen/QrbEQg)

## Explanation

There is no error. The problem is just the view. If the max value of y-axis are not at the end of the series entries and the stroke curve is set to smooth, then the graph is not shown correctly.

**Comment by KiddingMe42** [comment]
Hi @jimfilippou,

this works for me, but if the min value > 0 the gradient of the area charts will end under the xaxis. Do you have any idea?

**Comment by jimfilippou** [comment]
Please provide a codepen so i can help you more accurately. However, there is a `startFromZero` option which may or may not help

**Comment by junedchhipa** [comment]
I think I understood the issue that the gradient is getting stretched to value 0 even if yaxis.min > 0.
A codepen example will be helpful though to avoid misunderstanding

**Comment by junedchhipa** [comment]
Fixed the gradient in area charts which was stretched to 0 even yaxis > 0

**Comment by KiddingMe42** [comment]
@junedchhipa Yeah you the bug. Do you still need the codepen? I was starting the pen right now before I saw your mail.
Thank you!

**Comment by junedchhipa** [comment]
@KiddingMe42 No, I don't need the codepen now (unless the issue is still not fixed).
Please try updating to the latest version 2.0.9 and let me know if it works
