### ISSUE TITLE
Mixed Charts (Column/Column/Line) render issue

### ISSUE THREAD

**Issue by jammesjoe** [apexcharts/apexcharts.js#1389]
## Codepen

https://codepen.io/jammes/pen/NQRJXx?editors=1010
(apexcharts version: ^3.8.1)
(vue-apexcharts version: ^1.4.0)

## Explanation

This is happening when I try to use this layout:
Series A - type: column
Series B - type: column
Series C - type: line

Whenever C has all null values, A and B are shown, but the graph seems to not load properly.
If C has one or more values that are not null, the graph renders without issues.

- What is the behavior you expect?
The graph should render, even though C has all null values.
- What is happening instead?
A and B data are shown, but the graph does not render properly and I get an error message.
- What error message are you getting?
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined.

Layout - column/column/column - works under same circunstances.

Please help me to resolve this issue.

Thank you!

**Comment by sneko** [comment]
@junedchhipa ,

In my case that's kind of same issue:
- I have my original line (X points)
- I want to add a "minimum" straight line (2 points)
- I want to add a "maximum" straight line (2 points)

But as soon as I add the third line (either "min" or "max"), I get:
```
Cannot read property 'indexOf' of undefined
```

That's weird because if I chose to switch only display one of the min/max it works (so no issue with formatting).

Context:
* vue-apexcharts: 3.19.0

Thank you,

**Comment by maeglindeveloper** [comment]
Hey everyone, 

Have the same issue than @sneko on my side.
@junedchhipa is there any reason we experiment that behaviour ?
thanks :)

**Comment by junedchhipa** [comment]
I have fixed the original issue posted by @jammesjoe and it will soon be released in the next update.
@sneko, @maeglindeveloper If that fixes your issue, please report it when the next version is released.
If it doesn't, kindly open a new issue with a reproducible codepen.

**Comment by maeglindeveloper** [comment]
@junedchhipa any news from a new release ?
Is it common to the vue apex chart library as well ?
