### ISSUE TITLE
Add text inside the donut chart 

### ISSUE THREAD

**Issue by myshinjio** [apexcharts/apexcharts.js#1392]
Now i can add text in plotOptions function its will show on click
But i can't custom my text inside donut chart.

**Comment by junedchhipa** [comment]
What have you tried? And what result do you expect?

**Comment by haizad** [comment]
See Donut Labels
https://apexcharts.com/docs/chart-types/pie-donut/

The expected result might be as follows: 
![image](https://user-images.githubusercontent.com/23258127/98616442-c3cb8300-2337-11eb-89dc-4524307c7ba0.png)

**Comment by hernanramirez** [comment]
let options = {
  series: [44, 55, 41, 60],
  labels: ["Transport", "Shopping", "Energy use", "Food"],
  chart: {
    type: 'donut',
  },
  plotOptions: {
    pie: {
      donut: {
        labels: {
          show: true,
          total: {
            show: true,
            label: '',
            formatter: () => 'Text you want'
          }
        }
      }
    }
  }
};

const chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
