### ISSUE TITLE
Radar Chart: TypeError: s.elGrid is null

### ISSUE THREAD

**Issue by appreciated** [apexcharts/apexcharts.js#1394]
### Bug report
There seem to be issues with the basic radar chart and the radar chart with polygon-fill in the new version. 
As soon as you hover over dots in the chart the error occurs, also the popup with the data will not show up.

### Demo
[The issue can also be obeserved in the offical demo](https://apexcharts.com/javascript-chart-demos/radar-charts/basic/)

### Console
```
TypeError: s.elGrid is null
```

**Comment by junedchhipa** [comment]
This was an issue with the previous versions of apexcharts.
Can you please upgrade to the latest version and test again?

**Comment by appreciated** [comment]
From my understanding I am running 3.16.1. Is there already a newer version?

**Comment by appreciated** [comment]
Can you confirm this issue?

**Comment by junedchhipa** [comment]
Sorry, actually it was [fixed](https://github.com/apexcharts/apexcharts.js/commit/0919a741d25fb49ec8f3dff944968199fc13bf70) but never released.
A new version is on the way in a couple of days.

**Comment by appreciated** [comment]
Ah I see thank you very much!
