### ISSUE TITLE
docs website is slow

### ISSUE THREAD

**Issue by csandreas1** [apexcharts/apexcharts.js#1395]
Since you are using WordPress, you can use wp-fastest-cache to speed up the website. It's very easy to setup.

**Comment by junedchhipa** [comment]
We just transferred the website to another hosting provider 12 hours ago.
The cache was cleared and hence it may take some time to get the cache build again.

**Comment by csandreas1** [comment]
Normally when i visit a page should be stored in cache

**Comment by vmoosCode** [comment]
we are 2023 and the problem still exist
