### ISSUE TITLE
Vertical gridline appears through bar/column

### ISSUE THREAD

**Issue by kkpriyankacoding** [apexcharts/apexcharts.js#1397]
Hey @junedchhipa  i updated the core apexchart i encountered with another bug which the bar is overlapping the grid line . Please refer FIG 2 from #1346 
 ### FIG 3
![Screenshot from 2020-03-13 11-54-56](https://user-images.githubusercontent.com/39261701/76595632-273faf80-6522-11ea-868a-817a3cfa7e5b.png)

**Comment by junedchhipa** [comment]
Yes, this is a known bug.
For the time being, I would suggest you increase the opacity of the fill to avoid the gridline appear through the bar.

```javascript
fill: {
  opacity: 1
}
```

The issue will be addressed soon.

**Comment by kkpriyankacoding** [comment]
It didnt worked for me grid line still apears. 
This is chart options configuration
export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  dataLabels: ApexDataLabels;
  plotOptions: ApexPlotOptions;
  yaxis: ApexYAxis;
  xaxis: ApexXAxis;
  grid: ApexGrid;
  stroke: ApexStroke;
  subtitle: ApexTitleSubtitle;
  colors: string[];
  states: ApexStates;
  title: ApexTitleSubtitle;
  legend: ApexLegend;
  tooltip: any; //ApexTooltip;
  theme:ApexTheme;
  fill:ApexFill
};

Can you tell me how i can make vertical gridline with opacity 1?
