### ISSUE TITLE
dataLabels formatter not working on Radar chart

### ISSUE THREAD

**Issue by xxxKOTxxx** [apexcharts/apexcharts.js#1398]
Hi!
You have  `text: w.globals.series[i][j],` [here](https://github.com/apexcharts/apexcharts.js/blob/20143ae53d8c02d3ad659c4192859f816154f72a/src/charts/Radar.js#L247), but need something like [this](https://github.com/apexcharts/apexcharts.js/blob/20143ae53d8c02d3ad659c4192859f816154f72a/src/charts/Pie.js#L324)
Can You fix it?

**Comment by xxxKOTxxx** [comment]
I can be wrong, but for me works this code:
`
            if (w.config.dataLabels.enabled) {

              var formatter = w.config.dataLabels.formatter;

              var text = formatter === undefined
                ? w.globals.series[i][j]
                : text = formatter(w.globals.series[i][j], {
                  seriesIndex: j,
                  dataPointIndex: i,
                  w: w
                });

              var dataLabelsConfig = w.config.dataLabels;
              dataLabels.plotDataLabelsText({
                x: dataPointsPos[j].x,
                y: dataPointsPos[j].y,
                text: text,`

**Comment by junedchhipa** [comment]
Can you please elaborate on what isn't working by creating a codepen?

**Comment by xxxKOTxxx** [comment]
I think it's obvious, that if You ignore dataLabel formatter in Your codebase and pass data directly to label content, it should not work.  

There is an [example](https://codepen.io/xxxkotxxx/pen/JjdZJdv) how it fails.  
 
Just add formatter call if it's specified.

**Comment by junedchhipa** [comment]
It might be obvious and I may have missed many checks at different places in the codebase.
The reason I ask for a codepen every time is to easily reproduce the issue on my side.
Thanks for providing a codepen.

**Comment by xxxKOTxxx** [comment]
> It might be obvious and I may have missed many checks at different places in the codebase.
> The reason I ask for a codepen every time is to easily reproduce the issue on my side.
> Thanks for providing a codepen.

Nothing.
I think label text assignment can be an abstraction with default formatter usage. It will prevent such issues in future.

One more question. I tried to create workaround but have a problem with configutation. Can i set different styles for axis label and data labels? When i set zero opacity to some datalabels axis labels also dissapears :(

**Comment by junedchhipa** [comment]
Fixed the data-labels formatter issue. A patch will be released soon.
Yes, you can set different styles for x-axis labels and datal-abels. What issues are you facing there?

**Comment by xxxKOTxxx** [comment]
> Yes, you can set different styles for x-axis labels and data-labels. What issues are you facing there?
As far as i remember I tried to use show labels by number of area (number[]) and opacity, but they was applied to data labels and axis labels (i tried to create 2 areas with fill color and 2 transparent with data labels, it worked, but was shown only firrst 2 axis labels from 7)
