### ISSUE TITLE
How to set chart's height to 100%

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#140]
### Question
According to https://apexcharts.com/docs/options/chart/height/, you can set the height to a fixed number, but is there a way to make it 100% height of it's parent?

**Comment by junedchhipa** [comment]
Just corrected it.
Previously `height: 100%` didn't work as expected even though parent height was provided.

You will have to give the parent element some height and then if you give `options.chart.height: 100%`, then the chart will take the parent's height
