### ISSUE TITLE
autoScaleYaxis not working on Area Chart Mouse Zoom

### ISSUE THREAD

**Issue by himmxt** [apexcharts/apexcharts.js#1400]
# Bug report
When a user zooms with a mouse click (or JS event), y axis scaling does not update

How to reproduce: 
![image](https://user-images.githubusercontent.com/8166432/76891568-73eaf980-6846-11ea-8fea-cdef0f9f7b3b.png)

## Codepen
https://codepen.io/apexcharts/pen/vYOjqpB

## Explanation

- When I zoom in, I expect the chart to expand to fill up most of the available height.
- Instead, the chart only uses 30%~ of the available height.
- No error messages

**Comment by sohyunkim01** [comment]
it seemed working when using chart.zoom.type: 'xy'

**Comment by himmxt** [comment]
chart.zoom.type: 'xy' does not seem to fix the issue on
https://codepen.io/himmxt/pen/vYOjVNd

thank you for your help,

Himmat

**Comment by junedchhipa** [comment]
Found the issue. The series was in descending order, and hence autoScaleYaxis didn't work as expected.
A new property `xaxis.sorted` added which will sort a numeric/datetime axis that will fix the issue. For now, just reverse() your series data and it will work fine.
