### ISSUE TITLE
Uncaught TypeError: t.map is not a function

### ISSUE THREAD

**Issue by bluetechdev** [apexcharts/apexcharts.js#1401]
## Codepen
https://codepen.io/btdev/pen/gOpKMKa
## Explanation

My user is able to select the data the graph receives and update the graph with the new data. I use getjson to retreive this data and then the updateSeries method to update the series with the newly chosen data. Unfortunately it returns me the error 't.map is not a function'
- What is the behavior you expect?
It should update the graph with the new series I provided.
- What is happening instead?
It doesn't update the graph and gives me an error instead.
- What error message are you getting?
t.map is not a function

![image](https://user-images.githubusercontent.com/57758491/76893975-89cfdd00-688d-11ea-9462-4200e16fc38d.png)

This is the error I get on my localhost, the main error is the same, the errors underneath are slightly different.

**Comment by junedchhipa** [comment]
Your provided codepen isn't enough to reproduce the issue.
My best guess is that the series is not in the format which ApexCharts expects.

**Comment by bluetechdev** [comment]
> Your provided codepen isn't enough to reproduce the issue.
> My best guess is that the series is not in the format which ApexCharts expects.

I found the fix, the json needs to be sent as an array and not a string.

**Comment by sudsin95** [comment]
can you tell me how u have update series from json string in jquery

**Comment by Ariel-55** [comment]
Please, I want to update a treemap by clicking a square, I got the same error t.map is not a function. Can you share your solution, please?
        chart: {
            events: {
                dataPointSelection: (event, chartContext, config) => {

                chart.updateSeries({
                    data: data1
                });
            }
        },

**Comment by MinSomai** [comment]
In my case all was fine, except in pie reports.

It was because labels was array of numbers `[1, 2, 3, 4]`. 

I had to convert to string for this to work. like so `['1', '2', '3', '4']`

**Comment by meritshm441** [comment]
I'm having this issue 
![apex](https://github.com/apexcharts/apexcharts.js/assets/75949112/4086d9fa-a6e3-4a16-a8e0-e021bd9094d2)
