### ISSUE TITLE
tooltip.inverseOrder has no effect on stacked series

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1402]
Although `legend: { inverseOrder: true }` reverses the legend order in a stacked chart, `tooltip: { inverseOrder: true }` does not do the same. Setting the value to true or false has no effect on the order.

[CodePen](https://codepen.io/bilge-the-encoder/pen/abvbExa).

**Comment by Bilge** [comment]
@junedchhipa Added [CodePen](https://codepen.io/bilge-the-encoder/pen/abvbExa).

**Comment by washingtonsoares** [comment]
Is there any update on this ?

**Comment by junedchhipa** [comment]
Fixed it.
A new patch version will be released soon.
