### ISSUE TITLE
fill not working for individual bars in bar chart

### ISSUE THREAD

**Issue by vinothmarieswaran** [apexcharts/apexcharts.js#1409]
# Bug report

I m trying to use different bar colors based on the index,
 but i m getting error like `'string' is not assignable to type 'string'`
Please help me on this

fill: {
  colors: [function({ value, seriesIndex, w }) {
    if(seriesIndex==0) {
        return '#7E36AF' as string;
    } else if (seriesIndex==1) {
        return '#164666' as string;
    } else {
        return '#D9534F' as string;
    }
  }]
}

**Comment by junedchhipa** [comment]
Please create a codepen to reproduce the issue.

**Comment by junedchhipa** [comment]
Closing as no response

**Comment by EduardoEncinaLuna** [comment]
Same here, angular 8.2^

https://codesandbox.io/s/apx-column-stacked-td44z?file=/src/app/app.component.ts

we are missing something? it's the same function posted here https://apexcharts.com/docs/options/fill/

**Comment by junedchhipa** [comment]
@EduardoEncinaLuna Your codesandbox produces the correct result.
Please update to the latest version (apexcharts/ng-apexcharts) and post what result you're expecting.

**Comment by EduardoEncinaLuna** [comment]
Yes it does, but i can't build the project cause this error

![error](https://user-images.githubusercontent.com/22559836/80286151-5a638a00-86ef-11ea-8173-c3ae95b153fe.png)

codesandbox updated references still the same, doing the color changes but still throwing the error

https://codesandbox.io/s/apx-column-stacked-hmx4k

------------------------------------------------------------------------------------------------------------
While i was writting this comment i found the solution

![image](https://user-images.githubusercontent.com/22559836/80286305-394f6900-86f0-11ea-83da-c59aaa47133a.png)

It's mostly a typescript error with types. Awesome library btw
