### ISSUE TITLE
Four-digit hex codes do not work as expected in annotations

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1410]
Four-digit hex codes, e.g. `#000A` do not produce a transparent background. However, 8-digit hex codes `#000000AA` and `rgb(0, 0, 0, .5)` work as expected.

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by Heart1010** [comment]
@junedchhipa should this work for annotations in a line chart?

When I do it with

```
annotations: {
  yaxis: [{
    y: 458,
    borderColor: "rgb(254,176,25)", 
    label: {
      borderColor: "rgb(254,176,25)",
      style: {
        color: '#fff',
        background: "rgb(254,176,25)",
      },
      text: 'Ø Durchschnitt',
    }
}, 
```
![image](https://user-images.githubusercontent.com/1481680/77847895-b0acde00-71c0-11ea-8481-87f75c060b3e.png)

it works... but when I do the same with `rgb(254,176,25,.5)` the annotation is not shown

```
annotations: {
  yaxis: [{
    y: 458,
    borderColor: "rgb(254,176,25,.5)", 
    label: {
      borderColor: "rgb(254,176,25,.5)",
      style: {
        color: '#fff',
        background: "rgb(254,176,25,.5)",
      },
      text: 'Ø Durchschnitt',
    }
}, 

```
![image](https://user-images.githubusercontent.com/1481680/77847906-ce7a4300-71c0-11ea-8690-997999c1822e.png)

**Comment by junedchhipa** [comment]
@Heart1010 Replace rgb with rgba if you want the alpha to work
```
rgba(254,176,25,.5)
```

**Comment by Heart1010** [comment]
omg my fault sorry - copy pasted the rgb from 1st post above :blush:
