### ISSUE TITLE
Problem with Series Title Text when Stacked is true

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1411]
# Bug report

I've 3 series. 1 line and 2 columns.
1st serie on the left. 2nd and 3rd on the right.
When I click on any of the serie legends to hide/disable that serie, the yaxis title text doesnt hide.

This odd behavior happens when I've "stacked: true," to the chart object.
If I put stacked: false it works perfectly.

## Codepen
https://codesandbox.io/s/vue-basic-example-4mk4h

## Explanation

- What is the behavior you expect?
It should work exactly as with stacked: false

- What error message are you getting?
No errors.

**Comment by JohnRomanski** [comment]
In this codepen, the scales for both the y- axis seem to be off. it seems like the stacked bar with line is still an issue as described here https://github.com/apexcharts/apexcharts.js/issues/625

**Comment by Daniel4Digital** [comment]
Still having the same issue with last version :( 
Using type: line with stacked: false, it works as it should, if I change to stacked: true, it all falls apart

**Comment by junedchhipa** [comment]
This issue is not produced in the latest version of ApexCharts (as of v3.49.1)
