### ISSUE TITLE
Stacked charts have double toolbar margin compared to non-stacked

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1414]
![image](https://user-images.githubusercontent.com/470626/77269417-b9715180-6ca0-11ea-98ba-1e5e97d1da64.png)

Stacked charts waste 10px of vertical height in excessive padding between the chart and the toolbar.

[CodePen](https://codepen.io/bilge-the-encoder/pen/yLYLMZo)

**Comment by junedchhipa** [comment]
Digging out further, the problem is not due to the stacked property.
The difference is due to the presence of the legend in 1 chart.
This will be addressed soon.
