### ISSUE TITLE
Multi Series side by side not one after another

### ISSUE THREAD

**Issue by DevChrisDev** [apexcharts/apexcharts.js#1418]
**Is your feature request related to a problem? Please describe.**	
No, just want this feature to have better screen view

**Describe the solution you'd like**	
in multi-series timeline graph, graphs shows at the bottom of another, want it to be beside the first graph

![image](https://user-images.githubusercontent.com/40389722/77330665-41fbfa80-6d52-11ea-99b2-8b3954d8b078.png)

want that to be beside eachother

**Comment by junedchhipa** [comment]
It was that way previously (side by side) but caused visibility issues when the bars overlapped.
I think an additional flag to draw the bars `column-wise` instead of `row-wise` would be a good idea to allow this to be controlled by the user.

**Comment by zergeborg** [comment]
Just wanted to note that the stacked bars in the timeline chart are also causing positioning issues to the datalabels. I will open a separate issue, but I thought I would comment here so that this new feature will take into account positioning too.

**Comment by kgram007** [comment]
I am in need of this feature too. I made changes for this feature on local and tested it. Can I contribute?
