### ISSUE TITLE
Can't download  PNG, SVG from any apexCharts demos and also from my local website

### ISSUE THREAD

**Issue by Mukhammadali** [apexcharts/apexcharts.js#1419]
# Bug report
ApexChart any chart demo
https://apexcharts.com/javascript-chart-demos/area-charts/stacked/
## Explanation

- What is the behavior you expect?
 I would like to be able to download png and SVG attachments for a particular chart
- What is happening instead?
It is not triggering download and throwing error. You can try this on any ApexChart demos
- What error message are you getting?
![image](https://user-images.githubusercontent.com/22298895/77342943-c2baf680-6d52-11ea-9b60-8d849f3ff647.png)

**Comment by junedchhipa** [comment]
Released v3.17.1 which fixes this.
