### ISSUE TITLE
x-axis tooltip hides the actual x value on hover

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#142]
I'm using a custom formater and specificly this
```javascript
tooltip: {
      enabled: true,
      x: {
        formatter: (val) => {
          return 'Total transactions'
        }
      }
    }
```

It works correctly but when i hover over a day, it hides that day and displays the value that it got. This is normal behavior but how can i fix it?

![image](https://user-images.githubusercontent.com/6877046/46407981-4de89c80-c719-11e8-83a7-d62268daa677.png)

The problem in the above image is that Wednesday is hidden behind Total transactions in the X axis

**Comment by mitul-srashtasoft** [comment]
It will override but not change dynamically while scoll, it's stick on the same situations

**Comment by mitul-srashtasoft** [comment]
> A new property `xaxis.tooltip.formatter` will be provided - which will override the default `tooltip.x` formatter function

It will override but not change dynamically while scoll, it's stick on the same situations
