### ISSUE TITLE
Chart fill color doesn't accept RGBA colors

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#1420]
The chart fill color doesn't seem to accept RGBA colors while the chart color does accept RGBA colors. It looks like that only the 'fill color' has this issue.

Codepen:  https://codepen.io/thimows/pen/poJxvRP
In this pen you can see that the same RGBA color is used for the chart color and for the fill color. But the fill color is black instead of purple.

<img width="1051" alt=" 2020-03-23 om 22 56 14" src="https://user-images.githubusercontent.com/62159496/77367079-aec6c300-6d59-11ea-8fc4-dff102adc833.png">

**Comment by Thimows** [comment]
After some more testing it seems that this behaviour only happens to gradients. Changing the fill type to 'solid' shows the expected behaviour. Any help would be highly appreciated!

**Comment by Thimows** [comment]
@junedchhipa I would really appreciate if you could confirm if this is a bug or not.

**Comment by junedchhipa** [comment]
@Thimows Yes, I can see the issue. it seems that `rgba` isn't accepted in some places.

It will be address soon.

**Comment by Thimows** [comment]
Great! Thank you!
