### ISSUE TITLE
Wrong y-axis zoom behavior

### ISSUE THREAD

**Issue by wielski** [apexcharts/apexcharts.js#1422]
# Bug report

## Codepen
https://codepen.io/wielski/pen/LYVgGbX

## Explanation
- What is the behavior you expect?
When zoom type is set to "y" chart should zoom only by y-axis

- What is happening instead?
It shows right zoom selection, but chart is zooming by x-axis too

- What error message are you getting?
No errors

**Comment by wielski** [comment]
I also tried to fix it with beforeZoom event, but I getting error "Cannot read property 'constructor' of undefined":

```
  public beforeZoom(options: ApexOptions): ApexOptions {
    if (this.zoomType === ZoomType.x) {
      return {
        xaxis: options.xaxis,
      };
    }

    if (this.zoomType === ZoomType.y) {
      return {
        yaxis: options.yaxis,
      };
    }

    return {
      xaxis: options.xaxis,
      yaxis: options.yaxis,
    };
  }
```

**Comment by junedchhipa** [comment]
You're correct, I confirm the bug.
It will be addressed soon.
