### ISSUE TITLE
Missing values of multiple data series

### ISSUE THREAD

**Issue by davehowson** [apexcharts/apexcharts.js#1423]
# Bug report

When using multiple data series with values missing in the first series, but present in the second series, data is rendered incorrectly.

For example, the following JSON is not displayed correctly.

```
  {
   "name":"Market 1",
   "data":[
      {
         "x":"Apple",
         "y":54
      },
      {
         "x":"Orange",
         "y":66
      }
   ]
},
{
   "name":"Market 2",
   "data":[
      {
         "x":"Orange",
         "y":54
      },
      {
         "x":"Mango",
         "y":99
      },
      {
         "x":"Apple",
         "y":66
      }
   ]
},

```

This JSON should display 99 for Mango, but instead, 99 is displayed for Orange in a rather broken way. Check the codepen for a better understanding.

## Codepen

https://codepen.io/davehowson/pen/bGdmgRZ

**Comment by junedchhipa** [comment]
Although this seems like a bug, this should be taken care of before injecting data into ApexCharts.

So, if there is a missing value, it should be supplied as `null`

```javascript
 {
   "name":"Market 1",
   "data":[
      {
         "x":"Apple",
         "y":54
      },
      {
         "x":"Orange",
         "y":66
      },
     {
         "x":"Mango",
         "y": null
      }
   ]
},
{
   "name":"Market 2",
   "data":[
      {
         "x":"Apple",
         "y":66
      },
      {
         "x":"Orange",
         "y":54
      },
      {
         "x":"Mango",
         "y":99
      },
   ]
},
```
Also, note that the order of `x` keys has to maintained in all the series. Otherwise, it may produce the wrong results.
