### ISSUE TITLE
Multiple X-Axis

### ISSUE THREAD

**Issue by SudharsanK2308** [apexcharts/apexcharts.js#1425]
Hi,
  This is in reference to #601  . Are there plans to support Multiple x axis feature ? 

   # Use case #
          Number of visitors grouped by region & country . Work-around is to concat these dimensions using some character , but not many would like to see it that way .

**Comment by junedchhipa** [comment]
Sorry, no plans as of now.

**Comment by SudharsanK2308** [comment]
Ok . Thanks @junedchhipa

**Comment by KhushiJain1305** [comment]
I wanted to express my gratitude for creating the ApexCharts library, the simplicity and elegance of ApexCharts have made graphing and charting a seamless experience. I want to represent the graph having multiple x-axis. As this is possible now using ApexCharts ? If not, then there is any other alternate way to do this using apex-chart.
