### ISSUE TITLE
Incorrect datetime x-axis labels

### ISSUE THREAD

**Issue by grindpride** [apexcharts/apexcharts.js#1426]
Code example: 
https://codesandbox.io/s/ancient-butterfly-7ycrb
Look at the chart below for the date of March 1.
Why is the nearest date on the time axis 20th of March?

![apex2](https://user-images.githubusercontent.com/25076736/77535993-a763fe80-6eac-11ea-95f5-ccb49b8be199.png)
![apex1](https://user-images.githubusercontent.com/25076736/77535995-a7fc9500-6eac-11ea-8582-6343513edeee.png)
This was on vue-apexchart. But same problem on pure apexchart 
https://codepen.io/grindpride/pen/rNVQBrb

**Comment by junedchhipa** [comment]
It's actually March 2020, not 20th March.
If you wish to use  custom formatter, you can use a 3rd party datetime library such as day.js and format it

```javascript
xaxis: {
  labels:{
    formatter: function(val) {
        return moment(val).format("DD/MM")
    }
  }
}
```
