### ISSUE TITLE
 the second line disappear when there is a lot of data

### ISSUE THREAD

**Issue by elmaniakos** [apexcharts/apexcharts.js#1429]
# Bug report

i use three data series with 624 records in everyone, and everything work like a charme
<img width="1180" alt="Capture d’écran 2020-03-25 à 4 45 17 PM" src="https://user-images.githubusercontent.com/62660749/77557028-89e96180-6eb9-11ea-8cf9-2a912a37d47f.png">
but when i use three data series with 1982 records in everyone, the second line disappear
<img width="1182" alt="Capture d’écran 2020-03-25 à 4 44 58 PM" src="https://user-images.githubusercontent.com/62660749/77557121-aa192080-6eb9-11ea-9bc9-68a4219a9345.png">
Is there some limitations with high number of data ?

**Comment by junedchhipa** [comment]
No, there isn't a limit to the number of data-points (although a huge number > 10000 would impact performance).
There must be something else going on. Can I see a codepen of what you are trying?

**Comment by elmaniakos** [comment]
this is my code:
`
function apexchart(humList, dateList, tempList) {
      new Vue({
        el: '#chart',
        components: {
          apexchart: VueApexCharts,
        },
        data: {
          series: [{
              name: "Température",
              data: tempList
            },
            {
              name: 'Humidité',
              data: humList
            },
          ],
          chartOptions: {
            chart: {
              animations: {
                enabled: false,
              },
              toolbar: {
                show: true,
                tools: {
                  download: true,
                  selection: true,
                  zoom: true,
                  zoomin: true,
                  zoomout: true,
                  pan: true,
                },
                autoSelected: 'zoom'
              },
            },
            dataLabels: {
              enabled: false
            },
            stroke: {
              curve: 'straight',
              width: [2, 2],
            },
            colors: ['#ff6347', '#1565c0'],
            title: {
              text: 'Capteur N°:3456789',
              align: 'left'
            },
            grid: {
              row: {
                colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
                opacity: 0.5
              },
            },
            yaxis: [{
                axisTicks: {
                  show: true
                },
                axisBorder: {
                  show: true,
                  color: "#FF1654"
                },
                labels: {
                  style: {
                    colors: "#FF1654"
                  }
                },
                title: {
                  text: "Température (°C)",
                  style: {
                    color: "#FF1654"
                  }
                },
              },
              {
                opposite: true,
                axisTicks: {
                  show: true
                },
                axisBorder: {
                  show: true,
                  color: "#247BA0"
                },
                labels: {
                  style: {
                    colors: "#247BA0"
                  }
                },
                title: {
                  text: "Humidité (%)",
                  style: {
                    color: "#247BA0"
                  }
                }
              }
            ],
            xaxis: {
              type: 'datetime',
              categories: dateList,
              labels: {
                rotate: -90,
                rotateAlways: true,
                hideOverlappingLabels: true,
                showDuplicates: false,
                trim: false,
                minHeight: 50,
                maxHeight: 50,
                style: {
                  colors: [],
                  fontSize: '8px',
                  fontFamily: 'Helvetica, Arial, sans-serif',
                  fontWeight: 400,
                  cssClass: 'apexcharts-xaxis-label',
                },
                datetimeFormatter: {
                  year: 'yyyy',
                  month: 'MMM \'yy',
                  day: 'dd MMM',
                  hour: 'HH:mm'
                }
              }
            },
            legend: {
              position: 'top',
              onItemHover: {
                highlightDataSeries: true
              },
              labels: {
                colors: undefined,
                useSeriesColors: true
              },
            },
          },
        },

      })
    }
`

**Comment by elmaniakos** [comment]
As you can see in this case i have 503 records per axis after filtring database records, i think the problem come from irregular datetime interval, isn't it ?

<img width="1434" alt="Capture d’écran 2020-03-26 à 8 28 29 AM" src="https://user-images.githubusercontent.com/62660749/77621364-9236b080-6f3c-11ea-9d0b-d69afd49e232.png">

**Comment by elmaniakos** [comment]
I tried to use only one data serie with basic chart, same problem:
`
      new Vue({
        el: '#chart',
        components: {
          apexchart: VueApexCharts,
        },
        data: {
          series: [{
            name: "Desktops",
            data: humList
          }],
          chartOptions: {
            chart: {
              height: 350,
              type: 'line',
              zoom: {
                enabled: false
              }
            },
            dataLabels: {
              enabled: true
            },
            stroke: {
              curve: 'straight'
            },
            title: {
              text: 'Product Trends by Month',
              align: 'left'
            },
            grid: {
              row: {
                colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
                opacity: 0.5
              },
            },
            xaxis: {
              categories: dateList,
            }
          },
        },
      })
`
<img width="1436" alt="Capture d’écran 2020-03-26 à 8 55 47 AM" src="https://user-images.githubusercontent.com/62660749/77623211-fad35c80-6f3f-11ea-8c5b-dc2b3dc23606.png">

**Comment by elmaniakos** [comment]
I found the problem, the issue come from unset(nan) or null data (nan) or invalid number format (12.54Rtd)
