### ISSUE TITLE
Cant handle more than 4 series

### ISSUE THREAD

**Issue by tcarlsen** [apexcharts/apexcharts.js#143]
Trying to add more than 4 series results in this error: 

```
Unhandled Promise rejection: colorSeries.push is not a function ; Zone: <root> ; Task: null ; Value: TypeError: colorSeries.push is not a function
```

```
     if (colorSeries.length < len) {
        var diff = len - colorSeries.length;
        for (var i = 0; i < diff; i++) {
          colorSeries.push(colorSeries[i]);  // heres where it fails
        }
      }
```

*adding more than 4 colors in my colors array. didn't help*

**Comment by junedchhipa** [comment]
I cannot reproduce this.
Can you please create a codepen?

**Comment by tcarlsen** [comment]
I'm so sorry about this issue. for some reason, I had only 1 color in property `colors` in`dataLabels`.  and this causes the chart to fail on more than 4 series.

```
...
dataLabels: {
  enabled: true,
  style: {
    colors: '#000'
},
...
```

**Comment by lukaszahorec** [comment]
old issue, but I have the same problem in bubble chart. When colors is set to string eg "#000" I get error: TypeError: t.push is not a function, but when I set it to array like ["#000"], It works as expected. It's not a problem to set it like that, but find what causing that error is not clear.
