### ISSUE TITLE
Annotation point not displaying correctly with logarithmic

### ISSUE THREAD

**Issue by shukerullah** [apexcharts/apexcharts.js#1431]
Annotation point `y` position is not accurate when `yaxis` is set to logarithmic

**Comment by Finn-but** [comment]
@junedchhipa this issue still occurs in the latest version. (v3.35.5)
All points get positioned at the bottom regardless of their 'y' value.

It can be replicated in the annotations demo by setting the y-axis to logarithmic.
https://codepen.io/apexcharts/pen/GXOJXQ
