### ISSUE TITLE
autoScaleYAxis works on mouse zoom, but not on updateOptions({xaxis minmax})

### ISSUE THREAD

**Issue by himmxt** [apexcharts/apexcharts.js#1433]
# Bug report
(Forums seem to be down)

## Codepen
https://codepen.io/himmxt/pen/PoqaNvv

## Explanation

- What is the behavior you expect?
When the user clicks "View recent 6 months" I expect the yaxis to autoscale (like it does if you zoom in on the most recent 6 months using your mouse)

- What is happening instead?
Yaxis is not autoscaling on updateOptions

- What error message are you getting?
No errors

To reproduce the bug:
1. Click "view recent 6 months" and you will see that the yaxis does not adjust its scale
2. Use your mouse to zoom the same most recent 6 months of data, and you will see how the way the graph SHOULD look

Notes:
- The suggested fix for the yaxisautoscale bug report I submitted last week, did fix this issue for mouse zoom
- This bug also seems to be observable in the "YTD" button on https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis/

**Comment by junedchhipa** [comment]
Adding a new property `yaxis.forceAutoScale` which when enabled will scale the yaxis automatically based on xaxis range.

**Comment by junedchhipa** [comment]
`autoScaleYAxis` is originally intended to work in zoom and hence it is provided under the `zoom` property.
Calling the `updateOptions()` method externally isn't aware whether the update function's intention is to set the x-axis's min/max.

Hence, removing the bug tag and keeping this ticket open re-tagging it as a new feature.

**Comment by junedchhipa** [comment]
Related to #1443

**Comment by junedchhipa** [comment]
Added [zoomX](https://apexcharts.com/docs/methods/#zoomX) method which will autoScale the y-axis when called.
