### ISSUE TITLE
Confusing X and Y axes configuration

### ISSUE THREAD

**Issue by DavidSvetlik** [apexcharts/apexcharts.js#1434]
Hello, so issue has been already reported here yet closed without being really solved.

https://github.com/apexcharts/apexcharts.js/issues/87

It's a problem with vertically oriented charts (horizontal bars etc.).

Thing is, mostly `yaxis` config is for real Y-axis and `xaxis` config is for X-axis, but then you have "categories" - ( https://apexcharts.com/javascript-chart-demos/bar-charts/basic/ ) which for some reason are set as an xaxis configuration, yet display on Y-axis. You cannot be serious.

Sensible configuration is totally fundamental thing and the way axes are set is honestly confusing at least. First thing is that configuration should be same for X and Y axes (allowing multiple of them).

I would love to use your library very much, but this is a dealbreaker. I know it's for free, but nobody will return me those hours I tried to implement it and then had to give up.

Hopefully you can do something about it, thank you for your efforts.

Regards,
David S.

**Comment by junedchhipa** [comment]
I have provided my answer in the thread you mentioned as well as giving an example of why horizontal bar charts require such configuration.

Instead of putting categories, you can also put the key/values in `series.data` itself
```javascript
series: [
  {
    name: 'Series 1',
    data: [
      {
        x: 'Team 1',
        y: 21
      },
      {
        x: 'Team 2',
        y: 32
      },
      {
        x: 'Team 3',
        y: 20
      }
    ]
  }
]
```

The main reason to avoid a totally different configuration for horizontal bar charts (vertical and horizontal bar charts share almost the same configuration) is to avoid duplicate code and reusing the same code for both kinds of charts. Several examples of horizontal bar charts on the website should be helpful in getting started easily.

**Comment by DavidSvetlik** [comment]
@junedchhipa Thank you for your answer, however there is strong misunderstanding I think because I'm totally for the SAME configuration for both axes (so there's not duplicate code).

But it's not the current situation when yaxis can also be array etc. etc. I mean, what's really preventing you to make it completelly the same?

Also, the example you put there (with x and y values) where x is actually value for vertical (y) axis - could you please tell me how is that intuitive and sensible? Because I don't think it is.

**Comment by junedchhipa** [comment]
@DavidSvetlik x-axis and y-axis have huge differences in terms of available options if you take a look at the docs. There are so many properties in the y-axis that don't apply to the x-axis and vice-versa.

Here is a list of options applicable to just y-axis
```javascript
  showAlways: false,
  showForNullSeries: true,
  seriesName: undefined,
  opposite: false,
  reversed: false,
  logarithmic: false,
  forceNiceScale: false,
  decimalsInFloat: undefined
```
while the x-axis has many options such as datetime formatter, additional labels options and so on. Y-axis has support for multi-axes while x-axis don't.

There are around 8+ different chart types, and only the horizontal bar-chart is an exception where things are a little bit confusing. I agree, `xaxis.categories` is confusing in a horizontal bar chart as categories are actually displayed on the y-axis. But other than that, I don't see any major confusion.

Now, coming to the point, what's stopping me to make this change:
A horizontal bar chart is the most widely used chart, and making the change you are suggesting will be a breaking change for most of the users. Also, the change looks simple in theory, but it is actually a big one.

I hope, that answers your question.

**Comment by DavidSvetlik** [comment]
@junedchhipa Understand. Thank you for your answers.
