### ISSUE TITLE
Stacked create issue with stroke width

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1435]
# Bug report

I've a graph with stacked true, and I've 3 series, with a stroke: [5,0,0], but  the 2nd bar is losing 5px.

## Codepen

https://codesandbox.io/s/vue-basic-example-bu8ne

## Explanation

As you can see on the codepen, I tried with an bar type and line type, both with different problems.

In my project I am using the type line, and the downside is that the bar 2nd serie (green bar) is losing width of 5px.

if I put stroke with all 0, it works fine. But I want to add stroke to the 1st serie.

EDIT: This bug on the type line was introduced on the last version 3.17.0

**Comment by junedchhipa** [comment]
I confirm the issue.
It will be addressed soon.
