### ISSUE TITLE
Zoom Tools do not appear and Zoom is disabled in Bar Charts

### ISSUE THREAD

**Issue by Ahmed-Elkholy** [apexcharts/apexcharts.js#1436]
# Bug report

## Codepen

https://codepen.io/ahmed-elkholy/pen/bGdQmYR

## Explanation

- What is the behavior you expect?
I am expecting that I should be able to zoom in bar charts and zoom tools appear.
- What is happening instead?
Zooming is disabled and zoom tools do not appear in toolbars.
- What error message are you getting?
No Errors

**Comment by junedchhipa** [comment]
Sorry, zooming is not available in horizontal bar charts.

**Comment by Ahmed-Elkholy** [comment]
@junedchhipa The example I have attached is a vertical one not horizontal.

**Comment by junedchhipa** [comment]
Very sorry, I didn't even look at codepen as I had to deal with so many issues today. 
You will have to add the following config for category bar charts.

```javascript
xaxis: {
  tickPlacement: 'on'
}
```

Even then, if your chart has just 2 categories, zooming won't work. You need at least 3 or more categories to zoom into.

**Comment by Ahmed-Elkholy** [comment]
@junedchhipa thank you so much!

**Comment by rubenjonk** [comment]
This has been a solution for me too. I was wondering if this could be added to the documentation, I could not find it. Possibly just in the example of the column charts. I copied the stacked column chart in which this was not set

**Comment by IndyVC** [comment]
Couldn't find it in the docs too. @junedchhipa would it be possible to add it?
