### ISSUE TITLE
Zoom is disabled in a Vertical Bar Chart

### ISSUE THREAD

**Issue by Ahmed-Elkholy** [apexcharts/apexcharts.js#1437]
# Bug report

## Codepen

https://codepen.io/ahmed-elkholy/pen/bGdQmYR

## Explanation

- What is the behavior you expect?
I am expecting that I should be able to zoom in vertical bar charts
- What is happening instead?
Zooming is disabled and zoom tools do not appear in toolbars.
- What error message are you getting?
N/A

**Comment by junedchhipa** [comment]
Closing as duplicate of #1436
