### ISSUE TITLE
Apexcharts with Pjax

### ISSUE THREAD

**Issue by noriellecruz** [apexcharts/apexcharts.js#1438]
I'm using pjax on my project and also apexcharts but when navigating to a different page and going back, the styles and svg of apexcharts are getting duplicated. 

If there's a way to bind the svg and styles inside a container like div, I think we'll be able to just refresh the contents in it every pjax request. Any other solutions for this? I don't think this is a bug.

**Comment by augusl** [comment]
How to solve it, can you share.thanks

**Comment by botscripts** [comment]
@augusl 

I embedded the chart as an iframe from a separate page, a bit dirty but it works lol.

**Comment by noriellecruz** [comment]
@augusl 

I embedded the chart as an iframe from a separated page, a bit dirty but it works lol.

**Comment by augusl** [comment]
ok.thanks
