### ISSUE TITLE
Stacked bar 100% does not work with one value

### ISSUE THREAD

**Issue by DavidGOrtega** [apexcharts/apexcharts.js#1439]
# Bug report
I cant specify only one percentage in the 100% stacked bar. If I do so my value get 100%

## Codepen
https://codesandbox.io/s/react-basic-example-zcbml

## Explanation

- What is the behavior you expect? Only one value should paint a value percentage
- What is happening instead? The bar is filling the 100%
- What error message are you getting? None

**Comment by junedchhipa** [comment]
That's the correct behavior, maybe you need to re-configure the series and x-axis to produce something like this.
![Screen Shot 2020-03-27 at 7 42 24 PM](https://user-images.githubusercontent.com/17950663/77764718-1be09e00-7063-11ea-9d32-4dbcb7a7415e.png)


[Codesandbox](https://codesandbox.io/s/react-stacked-bar-chart-100-epcji)

**Comment by DavidGOrtega** [comment]
This is the data for your consideration.

```js
Customer satisfaction: {
email: '70%',
chat: '80%',
voice: '90%'
}

```

I don't want to show the stack of the three, but the customer satisfaction scoring as a percentage individually. 
Now I understand that the chart is calculating the percentage itself, thats why it reach the 100%, I was thinking that It was just only a cosmetic display where you were giving the percentages calculated by yourself. Would be indeed a very useful helper since I imagine. there is a lot of people showing percentages instead of values.

**Comment by junedchhipa** [comment]
Then, you don't need a 100% stacked bar chart. A simple bar chart with '%' in the formatters would work fine.

![Screen Shot 2020-03-27 at 10 46 17 PM](https://user-images.githubusercontent.com/17950663/77782132-cd3ffd80-707c-11ea-9810-ebcbd7fe6e73.png)

Here is a [codepen example](https://codepen.io/apexcharts/pen/abOPBKM)
