### ISSUE TITLE
Changing range with updateOptions on datetime x-axis doesn't rescale Y-axis

### ISSUE THREAD

**Issue by azivkovi** [apexcharts/apexcharts.js#1443]
What is the behavior you expect?

- When I change the timeframe using `updateOptions` which updates x-axis `min` and `max`, `min` and `max` on y-axis adjust to the new dataset. I would like Y-axis to behave like with x-axis zoom and `autoScaleYaxis: true`.

What is happening instead?

- Y-axis remains the same as on original dataset. I tried adding to `updateOptions` zoom for x-axis with `autoScaleYaxis: true` which doesn't do anything. I tried loading the whole y-axis and just `min` and `max`, both which also don't work.

Codepen: https://codepen.io/azivkovi/pen/eYNbQVw (change timeframe between 1M and All)

What error message are you getting?

- No errors.

**Comment by junedchhipa** [comment]
I am planning to add a new method `zoomX` which will help with this.
The syntax will be

```javascript
chart.zoomX(minX, maxX)
```

I will update this thread when ready.

**Comment by junedchhipa** [comment]
Added [zoomX](https://apexcharts.com/docs/methods/#zoomX) method which will autoScale the y-axis when called.

**Comment by azivkovi** [comment]
Thank you for the added method. I have another related issue, in same codepen https://codepen.io/azivkovi/pen/eYNbQVw .

Now when I select one month, the zoomX does the job, but when I try to reset to full dataset y-axis stays zoomed in the one month scale.

Maybe I am missing something obvious, your help would be appreciated.

**Comment by junedchhipa** [comment]
@azivkovi  I saw the codepen now.
You don't need to call the `updateOptions` if you call the `zoomX` method.
`zoomX` already updates the chart with new min/max

**Comment by flobaader** [comment]
Hi @junedchhipa,

I have the same problem. I load new data when the chart is zoomed and manually set the y-axis bounds in the options.
Would it be possible to just update the y-axis if the y-axis bounds change in the options?
