### ISSUE TITLE
Data messing up with negative values in stacked area graph

### ISSUE THREAD

**Issue by vincemat** [apexcharts/apexcharts.js#1445]
# Bug report
I'm re-opening the issue [#1372 ](https://github.com/apexcharts/apexcharts.js/issues/1372#issue-578503719) because I think the new release resolve the issue when there is three area charts but not if there is more.

## Codepen

I did modify [this codepen](https://codepen.io/vincemat/pen/yLNpRyM) to demonstrate the problem with one more area.

## Explanation

![image](https://user-images.githubusercontent.com/12695531/77850551-acd68700-71d3-11ea-9ca3-fdb023c22922.png)

- What is the behavior you expect:
When removing a serie from the visualisation by clicking on it on the legend, the value of this serie is disapearing but the result data on the graph is wrong.
- What is happening instead:
If I click on 'west' and 'south' (yellow), the graph is showing data for 'north' and 'south' (red) but the graph is not in line anymore with the real data: in 2004 the sum of south (318) and north (-156) is 162 but the graph is showing negative value for the total.

**Comment by JohnRomanski** [comment]
This seems to work if you don't use North as the first series.

**Comment by JohnRomanski** [comment]
I have spent about an hour going through the code, which is not enough time, to be sure.
My theory for this and the other stacked series bugs is that the Scale and min and max should not exist on the series, but on the axes. Series should all have the scale, min, max and offset of the axes they are on.

This could be accomplished by passing in an array of seriesNames to the axes:
```
        yaxis: [
          {
            seriesName: 'Line',
            opposite: true
          },
          {
            seriesNames: ['Bar1','Bar2','Bar3','bar4'],
          },
        ],
```

this part isn't right, it does the min/max but not the scale, but then in `setMultipleYScales` we could check for this option, and do the math there, adding up all the values for the positive and negatives separately.

```

      cnf.series.forEach((s, si) => {
        // NEW CODE  
        // if seriesNames exists in the axes, we add the values from all those series
        // to determine the maximum and minimum values
        if (yaxe.seriesNames !== undefined && yaxe.seriesNames.indexOf(s.name)!==-1){
          index = si
          var posMax = posTotals.SumPositiveArray(s.data)
          posTotals = posMax
          var negMax = negTotals.SumNegativeArray(s.data)
          negTotals = negMax
        }
        // END
        // if seriesName matches and that series is not collapsed, we use that scale
        // fix issue #1215
        // proceed even if si is in gl.collapsedSeriesIndices
        else if (s.name === yaxe.seriesName) {
```

**Comment by junedchhipa** [comment]
@JohnRomanski Thanks for your insights, I will surely try your suggestions.

**Comment by JohnRomanski** [comment]
Here is a code pen (modified from the source) to illustrate the issue that I was noticing.

https://codepen.io/johnromanski/pen/Poqvraq

You are welcome very much. I started reading the code from top to bottom last night, and I might take another approach to it. The stack info could be added to this series as an option. You'd have to preprocess and sum all the linked series before calculating any ranges. Using this approach, you might have a solution to add this feature issue too: #1294 

stacked chart bugs that could be resolved: #1411, #625, #1414, #1371, #1209
possibly #860 (and its open dupe #1173)

**Comment by JohnRomanski** [comment]
Not sure this is related, but what is up with this box in the lower left? https://codepen.io/johnromanski/pen/Poqvraq

<img width="585" alt="extra data point" src="https://user-images.githubusercontent.com/382382/78451021-c868e400-7650-11ea-84bf-488bfe2ce7c7.png">

**Comment by junedchhipa** [comment]
> The stack info could be added to this series as an option. You'd have to preprocess and sum all the linked series before calculating any ranges.

That's the approach I have thought too. This will also help to resolve #196 which is requested by many people. I will give this a try.

**Comment by junedchhipa** [comment]
The lower left box seems like a bug that shouldn't be there.
I guess it was missed out because it only appears when zoomed out.

**Comment by JohnRomanski** [comment]
One more comment on the source for this codepen: [Adding an axis for each series and then hiding](https://github.com/apexcharts/apexcharts.js/blob/master/samples/vanilla-js/column/stacked-column-with-line.html#L275-L289) it feels a little hacky to me. Ideally people should not have to do this to get the chart to work (or know how to do this.) 

The approach above would help clean up the code and make it easier to write. Again, just my 2 cents. I think its amazing what you have come up with!

I will follow this issue for any updates. If you have a dev branch in progress, I would be happy to review the code and offer feedback.

**Comment by junedchhipa** [comment]
> One more comment on the source for this codepen: Adding an axis for each series and then hiding it feels a little hacky to me. Ideally, people should not have to do this to get the chart to work (or know how to do this.)

I have got the same feedback from a lot of people (especially people coming from chartjs). The only reason I do not want to change this behavior right now because it invites a lot of breaking changes. The current scale calculation is done ignoring the series <-> y-axis association and asks the user to associate the series with the y-axis in a multi-axis chart.

**Comment by JohnRomanski** [comment]
I can understand not wanting to make any breaking changes. Maybe part of 4.0 release? 😆

**Comment by junedchhipa** [comment]
Sure 😁 
There is no timeline for 4.0, but things like these can go in the next major version.

**Comment by vincemat** [comment]
Hi @junedchhipa , do you have any view on nex major version and if you think of solving this bug ?
Thanks a lot !

**Comment by karis** [comment]
i think 
i have same issue,stacked with negative value, while i mix with line

<img width="1423" alt="Screenshot 2023-05-08 at 10 33 11" src="https://user-images.githubusercontent.com/1776951/236727990-0c568a2c-8f97-4a66-a9cd-0c26f43f69a6.png">

**Comment by karis** [comment]
> i think i have same issue,stacked with negative value, while i mix with line
> 
> <img alt="Screenshot 2023-05-08 at 10 33 11" width="1423" src="https://user-images.githubusercontent.com/1776951/236727990-0c568a2c-8f97-4a66-a9cd-0c26f43f69a6.png">

i already update my library
and i comment on some config. finally it works, as i expect.
<img width="1423" alt="Screenshot 2023-05-08 at 11 16 20" src="https://user-images.githubusercontent.com/1776951/236732665-9dd88aff-d991-4306-add0-2853a151b8c5.png">

`<script setup>
const chartOptions = {
  chart: {
    height: 350,
    type: 'line',
    stacked: true,
  },
  dataLabels: {
    enabled: false,
  },
  stroke: {
    width: [0.2, 0.3, 3],
  },
  title: {
    text: '',
    align: 'left',
    offsetX: 110,
  },
  xaxis: {
    categories: ['01 Jan 2024', '02 Jan 2024', '03 Jan 2024', '04 Jan 2024', '05 Jan 2024', '06 Jan 2024', '07 Jan 2024', '08 Jan 2024', '09 Jan 2024', '10 Jan 2024', '11 Jan 2024', '12 Jan 2024'],
  },
  yaxis: [
    // {
    //   axisTicks: {
    //     show: true,
    //   },
    //   axisBorder: {
    //     show: true,
    //     color: '#008FFB',
    //   },
    //   labels: {
    //     style: {
    //       colors: '#008FFB',
    //     },
    //   },
    //   title: {
    //     text: 'Income (thousand crores)',
    //     style: {
    //       color: '#008FFB',
    //     },
    //   },
    //   tooltip: {
    //     enabled: true,
    //   },
    // },
    // {
    //   seriesName: 'Income',
    //   opposite: true,
    //   axisTicks: {
    //     show: true,
    //   },
    //   axisBorder: {
    //     show: true,
    //     color: '#00E396',
    //   },
    //   labels: {
    //     style: {
    //       colors: '#00E396',
    //     },
    //   },
    //   title: {
    //     text: 'Operating Cashflow (thousand crores)',
    //     style: {
    //       color: '#00E396',
    //     },
    //   },
    // },
    // {
    //   seriesName: 'Revenue',
    //   opposite: true,
    //   axisTicks: {
    //     show: true,
    //   },
    //   axisBorder: {
    //     show: true,
    //     color: '#FEB019',
    //   },
    //   labels: {
    //     style: {
    //       colors: '#FEB019',
    //     },
    //   },
    //   title: {
    //     text: 'Revenue (thousand crores)',
    //     style: {
    //       color: '#FEB019',
    //     },
    //   },
    // },
  ],
  //   tooltip: {
  //     fixed: {
  //       enabled: true,
  //       position: 'topLeft', // topRight, topLeft, bottomRight, bottomLeft
  //       offsetY: 30,
  //       offsetX: 60,
  //     },
  //   },
  legend: {
    horizontalAlign: 'left',
    offsetX: 40,
  },
}

const series = [
  {
    name: 'Income',
    type: 'bar',
    data: [440, 505, 414, 671, 227, 413, 201, 352, 752, 320, 257, 160],
    width: 20,
  },
  {
    name: 'Expense',
    type: 'bar',
    data: [-140, -105, -114, -171, -127, -113, -101, -52, -105, -120, -107, -116],
  },
  {
    name: 'Profit',
    type: 'line',
    data: [123, 142, 135, 127, 143, 122, 117, 131, 122, 122, 112, 116],
  }]
</script>

<template>
  <ClientOnly>
    
    <apexchart
      width="100%"
      height="400px"
      type="line"
      :options="chartOptions"
      :series="series"
    />
  </ClientOnly>
</template>
`

**Comment by junedchhipa** [comment]
The original issue is fixed with the latest releases of ApexCharts (checked with v3.49.1)
