### ISSUE TITLE
Panning on logarithmic chart breaks: opts.series is undefined

### ISSUE THREAD

**Issue by mcrider** [apexcharts/apexcharts.js#1446]
I went through the stack trace and can't see where opts gets a series attribute added to it? And then at the following line the chart breaks whenever I try to pan left or right. Panning works properly on a non-logarithmic scale.

I'll keep investigating to see if its just a configuration error on my end (to state the obvious, my options object does have a series set, and is displaying fine).

https://github.com/apexcharts/apexcharts.js/blob/5a27cd0f9b0ca75e5d5b96e5fd944669dd6757ec/src/modules/settings/Config.js#L188

**Comment by junedchhipa** [comment]
Thanks for reporting, I found the issue and it will be fixed soon.

**Comment by mcrider** [comment]
Amazing, thank you Juned. And thanks for the hard work you're putting in on this project!
