### ISSUE TITLE
Width to big when rendering the chart

### ISSUE THREAD

**Issue by dabuionut** [apexcharts/apexcharts.js#1451]
Hi ,
I have some issues with one of my apexchart , when is rendering is go to way outside the box , 
I have multiple charts on the page but not all have this error .
Here is a caption of the error, I saw that it have a 545 width , and the other have 395.
![Capture](https://user-images.githubusercontent.com/19206681/78043186-b39ffe00-737b-11ea-94ab-781827072d2d.JPG)

Br

**Comment by JohnRomanski** [comment]
Could you please provide a code pen so that this can more easily be reviewed?

**Comment by dabuionut** [comment]
Resolved the Issue , it was from the bad loading of the page 
Thx
