### ISSUE TITLE
CSV Export - Last row duplicate

### ISSUE THREAD

**Issue by badhrudeen** [apexcharts/apexcharts.js#1452]
# Bug report
While exporting the file as CSV, the last row getting duplicated. Apexchart Version:  ApexCharts v3.16.1
**Attached:**
![duplicate-row](https://user-images.githubusercontent.com/20681708/78050662-30da6b80-739a-11ea-8780-b671782cf2f8.PNG)

## Explanation

- What is the behavior you expect? No duplicate rows must exist while csv export happen
- What is happening instead? Getting duplicate  of last rows in the exported csv
- What error message are you getting? NA

**Comment by AlexJangam** [comment]
Please fix this.

**Comment by junedchhipa** [comment]
@AlexJangam The issue is already tagged as `bug` and is on the roadmap to be fixed.
Please refrain from posting unnecessary comments which don't add anything to the discussion.
You may simply give a 👍  to the original comment, so I know other people are facing the same issue as well.

**Comment by badhrudeen** [comment]
Thanks Junedchhipa! Awesome work. Appreciate your quick help.
