### ISSUE TITLE
Datetime line brush displays wrong 1:00AM instead of midnight

### ISSUE THREAD

**Issue by fracz** [apexcharts/apexcharts.js#1453]
# Bug report

## Codepen

I have modified [the brush chart codepen](https://codepen.io/apexcharts/pen/rqWeBX). The only things I changed are: the interval of the datapoints (from 86400 to 600), the start date is set to `2020-03-31T22:00:00+02:00`, and the tooltip format has ben changed to display hours instead of dates.

https://codepen.io/fracz/pen/jOPJLoO

## Explanation

When you open the codepen, the midnight date is displayed correctly as a `1 Apr`.

![image](https://user-images.githubusercontent.com/3918865/78074792-9aab4300-73a3-11ea-952e-d60a1670459e.png)

Then, if you move the brush selection slightly to the right the midnight label is being set to `1:00`.

![image](https://user-images.githubusercontent.com/3918865/78074884-ca5a4b00-73a3-11ea-81b0-dcbf98ebfda6.png)

If you keep moving the selection and pass the next hour, the label is getting back to `0:00` (but not `1 Apr`) in the codepen:

![image](https://user-images.githubusercontent.com/3918865/78074975-f83f8f80-73a3-11ea-967a-7194b40e2094.png)

The tooltip always shows the correct data even when the x-label are messed up.

![image](https://user-images.githubusercontent.com/3918865/78075276-861b7a80-73a4-11ea-9e2d-ecfe871ab6b5.png)

Not a big deal, hovever in my application the labels are not fixed when moving right, so all of the labels are shifted by one hour, and it is much bigger problem. Could not reproduce such behavior in the codepen, though.

**Comment by junedchhipa** [comment]
Yeah, I can see the bug in your modified codepen.
I will take a look soon, thanks for reporting.

**Comment by villeraikko** [comment]
Any progress on this? I'm experiencing this one as well, except that in our code the bug happens everytime on a specific timeframe. Also on the initial load.

<img width="627" alt="Screenshot 2021-11-17 at 21 35 29" src="https://user-images.githubusercontent.com/30502048/142270405-c9742b40-bcfd-4af8-a51e-a6707b5a8ccf.png">
.

**Comment by schotime** [comment]
> Have you been able to look at this? We also experience this using only 24H time it skips 00:00 when zoomed in. :)

Getting this as well. Its skipping 00:00

**Comment by schotime** [comment]
I thought it was just the 24H too but it happens for both. Seems to be when the range is selected between 1-2 hours before midnight then midnight seems to get dropped as show in the images below.

![image](https://user-images.githubusercontent.com/202923/143834740-d910fdc8-6a00-4917-81f4-19a2fd6e7885.png)
![image](https://user-images.githubusercontent.com/202923/143834786-b81e2939-a764-4d0c-b282-1d6e1cf0a2b1.png)

**Comment by V1CTOR-cloud** [comment]
Got same problem with time line charts
