### ISSUE TITLE
Changelog ist outdated

### ISSUE THREAD

**Issue by Calamari** [apexcharts/apexcharts.js#1454]
# Bug report

## Expected behavior

Current version is 3.17.1 and I somehow expect that, if there is a `CHANGELOG.md` file in the repository, it contains all the relevant changes up to the current version.

## Current behavior

The `CHANGELOG.md` only contains data from 2018 and earlier, ignoring all the updates afterwards.

So, could this please get updated, so people do not waste time wondering if they are in the right repository?
Either that, or just delete the file altogether?

**Comment by junedchhipa** [comment]
Yes, changelog file needs to be deleted, thanks for pointing that out.

Instead, all the updates are not in [Release Notes](https://github.com/apexcharts/apexcharts.js/releases)

**Comment by junedchhipa** [comment]
Deleted
