### ISSUE TITLE
Cant download radar chart image (SVG and PNG)

### ISSUE THREAD

**Issue by JorgenSolli** [apexcharts/apexcharts.js#1458]
# Bug report
## Explanation
Downloading a radar chart as either SVG og PNG fails and throws a console error
![image](https://user-images.githubusercontent.com/14874283/78243836-c84bd580-74e4-11ea-8c33-4638347e4d22.png)

You can replicate this from the documentation itself https://apexcharts.com/javascript-chart-demos/radar-charts/radar-with-polygon-fill/

Thank you for an amazing package and your hard work!

**Comment by junedchhipa** [comment]
Thanks for reporting, I confirm the issue.
It will be addressed soon.
