### ISSUE TITLE
Interpolate or duplicate missing data values

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#146]
AFAIK currently there's no way to draw lines on missing data on line charts, only points are drawn.
https://codepen.io/anon/pen/WaxKdp

This doesn't look alright when there's many missing data
![image](https://user-images.githubusercontent.com/3078595/46536391-0730a900-c8b7-11e8-80c8-89720fac0cda.png)

Although one can fill that data by specifying interpolated values or repeating former value it would be nice to have an option to just have an Apex charts option on how these `null` values should be handled. 

And there's no way to set a different stroke for such "filled" line segments. 

I would suggest the following:

```
options:
  nullValues: {
    fill: false | 'interpolate' | 'repeat',
    stroke: {
      width: 2,
      dashSpacing: 5,
    }
  }
```

Alternative option title could be `seriesNulls` or `seriesEmptyValueHandling`

**Comment by eLvErDe** [comment]
+1, you can still pre-process data to drop null value, but that's definitely a required feature

**Comment by junedchhipa** [comment]
Replacing null values with the former values while drawing seems like an appropriate way to handle it. I will research more on what are other options and see the possibilities of adding this feature.

**Comment by eLvErDe** [comment]
Check python pandas interpolate documentation if you want to see more options ;-)

Le 12 mars 2019 09:09:43 GMT+01:00, Juned Chhipa <notifications@github.com> a écrit :
>Replacing null values with the former values while drawing seems like
>an appropriate way to handle it. I will research more on what are other
>options and see the possibilities of adding this feature.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/apexcharts/apexcharts.js/issues/146#issuecomment-471897530

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by digows** [comment]
+1

**Comment by muehling** [comment]
+1

This would be very helpful!

**Comment by jofftiquez** [comment]
Similar to #747 with more details on how this feature would look like.

**Comment by arpit016** [comment]
@junedchhipa any update on this issue?

**Comment by ngranja19** [comment]
+1.

**Comment by AshConnolly** [comment]
Is there any plans to add a feature improvement for this?
It seems this issue links to #747, and vice versa, with no clear resolution or intention.
Thanks! 😃

**Comment by FlorianMarcon** [comment]
+1

**Comment by Filaind** [comment]
Fuck bots :(

Implement this feature please

**Comment by johnwinkcq** [comment]
+1

**Comment by pokhrelashok** [comment]
+1 switching to recharts because of this

**Comment by rozium** [comment]
+1

**Comment by Gobot1234** [comment]
Just came to this now. There's now a way to do this with the connectNulls prop which is passed to Line

**Comment by jofftiquez** [comment]
> Just came to this now. There's now a way to do this with the connectNulls prop which is passed to Line

Oh wow, really? That's nice!

**Comment by northrhino** [comment]
> Just came to this now. There's now a way to do this with the connectNulls prop which is passed to Line

i dont this is true? are you confusing this with echarts?
