### ISSUE TITLE
Adjust Radar Spoke Width / Weight?

### ISSUE THREAD

**Issue by heyconor** [apexcharts/apexcharts.js#1460]
I can't seem to find a way to adjust the thickness / weight of the axis spokes for a radar chart. I want to make them thicker and a different color.

Please note this is for the axis spokes, not the plotted shape.

**Comment by junedchhipa** [comment]
Currently, you can change the colors of the spokes using
```javascript
plotOptions: {
  radar: {
    polygons: {
      strokeColors: '#111'
    }
  }
}
```

I will add a new property `strokeWidth` in plotOptions.radar.polygons to control the thickness too.

Meanwhile, you can use CSS as a workaround
```CSS
.apexcharts.canvas polygon {
    stroke-width: 4;
}
```

**Comment by heyconor** [comment]
Thanks for the quick response!

FYI - on the following page you quote `{ polygons: { strokeColor: '#e8e8e8' }` (i.e. `strokeColor` instead of `strokeColors`) and you also don't mention `connectorColors`. Perhaps update the page?

https://apexcharts.com/docs/chart-types/radar/

**Comment by junedchhipa** [comment]
Good catch. Yeah, that will be added too.
