### ISSUE TITLE
Skip empty dataset for candlestick chart

### ISSUE THREAD

**Issue by CodeMyWorld** [apexcharts/apexcharts.js#1461]
Usually, candlestick is used for showing stock data. But there is no trading data on holiday, and the candlestick chart still renders an empty part for that time. It would be awsome if the chart only renders the date which has trading data.

**Comment by junedchhipa** [comment]
Unfortunately, this is not possible with `xaxis.type: 'datetime'`.
You can use `xaxis.type: 'category'` and format the x-axis labels using `xaxis.labels.formatter` to achieve the result.

**Comment by CodeMyWorld** [comment]
Thank you so much. I have achieved what I want!
