### ISSUE TITLE
toggleDataPointSelection causes error in pie chart

### ISSUE THREAD

**Issue by vitalcrazz** [apexcharts/apexcharts.js#1464]
# Bug report

`toggleDataPointSelection` causes error in a pie chart in latest 3.18.0 version
while in 3.17 version it works just fine.

## Codepen

https://codesandbox.io/s/vue-basic-example-5t1jf

## Explanation

I'm using a donut chart and I call `toggleDataPointSelection(0)` method a long time after the chart is loaded (after user clicks a button).
I get the following error and a donut piece is disappearing instead of selecting.
`<path> attribute d: Expected number, "M NaN NaN A NaN Na…".`

**Comment by vitalcrazz** [comment]
![2](https://user-images.githubusercontent.com/6044393/78506958-fac82d80-7785-11ea-896a-8b992625d8c0.png)
![1](https://user-images.githubusercontent.com/6044393/78506964-fe5bb480-7785-11ea-8b0d-9adfe16fbc03.png)
![3](https://user-images.githubusercontent.com/6044393/78506967-0287d200-7786-11ea-925d-6b1b84550b9a.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, the issue will be address soon.

**Comment by poddarkhushbu07** [comment]
What is the cause of this error. I am also getting the same issue.

**Comment by DasunMuthuruwan** [comment]
Any update on this? I'm facing this issue too

**Comment by khoanld-2442** [comment]
Hí anh em

**Comment by Mominjon** [comment]
![image](https://user-images.githubusercontent.com/78495004/185737189-6709183c-e62c-41e0-b6c4-5841651b5cd8.png)

is there any fix for this i am having big problems

**Comment by AlexParton** [comment]
I have solved all those errors by destroying the chart when component unmounts.
I did it on sveltekit, and there the chart needs to be renderen inside the onMount method and binding the html container element with bind:this to avoid another annoying error (window is not defined), and to be able to identify the chart inside the onDestroy method a callback function needs to be created where the chart is rendered (onMount).
So the workaround gets like this:

` let graphContainer: HTMLElement;
  let destroyer: any;

  onMount(async () => {
    const ApexCharts = (await import('apexcharts')).default
    const container = graphContainer;
    const chart = new ApexCharts( container, setOptions(pairData))
    chart.render();
    destroyer = () => chart.destroy()
  })

  onDestroy(async () => {
    destroyer()
  })`

**Comment by Rao-Mudasir** [comment]
any fix
