### ISSUE TITLE
Question: Support/Example for 100% Stacked Area Chart?

### ISSUE THREAD

**Issue by smrubin** [apexcharts/apexcharts.js#1465]
This is a question. Is there support for, or an example of a 100% Stacked Area Chart?

I have tried the following chart options:
```                   
chart: {
  type: 'area',
  stacked: true,
  stackType: '100%',
}
```

But it does not normalize the data to 100%. Could always normalize myself, but was curious if the stackType prop can be applied to area charts. Thanks!

**Comment by junedchhipa** [comment]
Unfortunately, 100% stacked charts are only available for bar/column charts currently.

**Comment by smrubin** [comment]
Thanks for the response, much appreciated.

**Comment by hjfrun** [comment]
I also need this too, do you plan to add this feature?

**Comment by claytonsands** [comment]
I also need! I go change my chats api to get this result.

**Comment by lodu** [comment]
Would be nice if this were added!

Maybe tag this as a `feature-request`?
