### ISSUE TITLE
Legend not clickable with Line type & Panning

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1474]
# Bug report
I am using an apexchart type="line" and with panning enabled, the legends stops working.
We're unable to unselect any element on the legend.
If I change the type to bar, it works.

## Codepen
https://codesandbox.io/s/vue-basic-example-28od9

## Explanation

- What is the behavior you expect?
I am expecting the same behavior as type bar with type line. Even with panning enabled, still being able to unselect/select any legend element.

- What is happening instead?
When clicking on any legend item, nothing happens, it doesnt unselect it.

- What error message are you getting?
None.

**Comment by rdasilva84** [comment]
I have a similar problem. My chart is an area chart.
When I click on panning, I can't export png, svg or excel.
I'm using the react wrapper.

**Comment by junedchhipa** [comment]
I confirm the bug. It will be addressed soon.

**Comment by Daniel4Digital** [comment]
> When I click on panning, I can't export png, svg or excel.

Me too. Lets hope next release has that addressed. :)
