### ISSUE TITLE
Set thickness of donut chart

### ISSUE THREAD

**Issue by lkavetskiy** [apexcharts/apexcharts.js#1476]
Is it possible to set (increase) the thickness of the donut chart?
![3](https://user-images.githubusercontent.com/44438582/78721468-49193000-7930-11ea-8352-25200fcd9099.png)

**Comment by aprilmintacpineda** [comment]
Hi @lkavetskiy you can use `plotOptions` on the options.

```js
plotOptions: {
  pie: {
    donut: {
      size: '40%'
    }
  }
}
```

https://apexcharts.com/docs/chart-types/pie-donut/

Docs is not friendly. It's actually barely informative :(

**Comment by lkavetskiy** [comment]
@aprilmintacpineda THANKS!
