### ISSUE TITLE
Annotation stem drawn at wrong position when at start of series

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1478]
![image](https://user-images.githubusercontent.com/470626/78759887-3a566b80-7978-11ea-9597-ce8375198709.png)

When the release is October 2012, which occurs at the start of the time series, the annotation is actually drawn at the November 2012 position, presumably to make space for the label.

![image](https://user-images.githubusercontent.com/470626/78760832-9e2d6400-7979-11ea-8e92-cfc933c4a014.png)

The stem of the annotation must occur at the correct position. If there isn't enough space to draw the label to the left of the stem, it should flip automatically to be drawn on the right.

[CodePen](https://codepen.io/bilge-the-encoder/pen/PoPYgBq)

**Comment by junedchhipa** [comment]
I see your point, I would appreciate a codepen so I can quickly reproduce.

**Comment by Bilge** [comment]
I'll see if I can do that. I don't really know how to codepen.

**Comment by Bilge** [comment]
@junedchhipa Hi, I think I got a pen for you: https://codepen.io/bilge-the-encoder/pen/PoPYgBq

**Comment by junedchhipa** [comment]
Thanks @Bilge 
That was helpful, will be fixed soon.

**Comment by Bilge** [comment]
@junedchhipa Thanks! I went ahead and added CodePens to [all my outstanding bug reports](https://github.com/apexcharts/apexcharts.js/issues/created_by/Bilge) (but not feature requests).
