### ISSUE TITLE
Improve exec method documentation

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#148]
In both apexcharts and wrapper libs (e.g. vue-apexcharts) please add an example on how to specify additional parameters, e.g. `redrawPaths`, `animate` for `updateOptions`

## In details

The `updateOptions` has 3 parameters:

```
updateOptions (newOptions, redrawPaths, animate)
```

The `exec` has only one parameter for method parameters

```
exec (chartID, method, params)
```

[There's an example](https://apexcharts.com/docs/methods#exec)

```js
ApexCharts.exec(chartID, 'updateOptions', {
  xaxis: {
    labels: {
      show: false
    }
  }
});
```

But there's no mention on how to specify `redrawPaths` and `animate` parameters

**Comment by pribilinskiy** [comment]
In [this codepen](https://codepen.io/anon/pen/MPbQed) I'm trying both ways, by adding `false` as extra argument and by adding `animate: false` to the `params` objects.
None of them works

**Comment by junedchhipa** [comment]
I will elaborate the params, thanks for catching.

**Comment by junedchhipa** [comment]
Digging into the code, the additional parameters (like `animate, redraw`) were ignored in `exec` method.

I have fixed that in the commit below.
Also updated the documentation example for `exec` method which states that the parameters have to be passed in the same order as they are passed while calling the method directly.

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/78530aa3ad3b32992559d44cb9c134c625fd4ba9 fixes it. Will be available in the next patch release.
