### ISSUE TITLE
Multi Axis Chart: set the display of tooltip of one specific y axis

### ISSUE THREAD

**Issue by niklashaug** [apexcharts/apexcharts.js#1482]
Hi. I am working with a Multi Axis line chart.
Is there a way to set the display of a tooltip of one specific y axis?
I can't see an option such as enabledOnSeries so I tried the following:

https://codepen.io/niklhs/pen/OJyyzoa

Is there any possibility to do this right now?

Thanks.

**Comment by niklashaug** [comment]
To be more precise: I want the tooltip of the y axis that is not shown (index 2 of the yaxis array) to hide.

**Comment by junedchhipa** [comment]
```javascript
tooltip: {
    enabledOnSeries: [0, 1]
}
```
This should work.

**Comment by niklashaug** [comment]
Unfortunately it doesn't work for me (unless I'm doing something wrong)
`{
    seriesName: 'TEAM A',
    showAlways: true,
    title: {
      text: 'A-Axis'
    },
    tooltip: {
      enabledOnSeries: [0, 1]
    }
  }`

This is the configuration of my first yaxis or do I have to move the tooltip object somewhere else?

Updated pen:
https://codepen.io/niklhs/pen/yLYBeJb

**Comment by niklashaug** [comment]
@junedchhipa could you please provide an example/update my existing codepen?

**Comment by junedchhipa** [comment]
I'm sorry, I misunderstood the question and thought you were talking about the normal tooltip.

I just checked your codepen, and it looks like the y-axis tooltip cannot be disabled in a multi-yaxis chart.
I will address the bug soon.

**Comment by junedchhipa** [comment]
Fixed it.
From the next version, this will work fine

```javascript
yaxis: [
  {
    show: true,
    tooltip: {
      enabled: true
    }
  },
  {
    show: false,
    tooltip: {
      enabled: false
    }
  }
]
```

**Comment by niklashaug** [comment]
Thank you very much @junedchhipa!
When can we expect the new version to roll out?
Will it also be available in apexcharts-vue?

**Comment by junedchhipa** [comment]
A new release is coming in 2 days.
You will just have to update `apexcharts`, not `vue-apexcharts`

**Comment by MadhuSingarapu** [comment]
Hi, I need a tooltip for y-axis label names for the apex bar chart.
