### ISSUE TITLE
x-axis label is different in chrome and safari

### ISSUE THREAD

**Issue by Babyshalini1995** [apexcharts/apexcharts.js#1485]
Awesome library with many feature.. Thanks for the library. loved it:) Keep continue your good work..

# Bug report
 x-axis labels are incorrect in chrome and safari

## Codepen
https://codepen.io/drpuur/pen/ExaQWGx

## Explanation

- What is the behavior you expect?
For same time zone, x -axis labels displayed are different in chrome and safari
- What is happening instead?
For same time zone, x-axis label in chrome has local time zone and in safari has utc

**Comment by Gari-sincere** [comment]
Does switching options.xaxis.labels.datetimeUTC to false make it consistent?

**Comment by Dreyerized** [comment]
> Does switching options.xaxis.labels.datetimeUTC to false make it consistent?

I have the same issue, and have that option set to false already. What's even worse is in chrome and firefox it displays the correct local value, but in Safari, the local value is offset further (for example, in UTC-4, if the local time was 8am, it would show as 4am)
