### ISSUE TITLE
Add support for different color on below x-axis

### ISSUE THREAD

**Issue by hosseind2** [apexcharts/apexcharts.js#1487]
we want to have ability to show the line in a different color when it is under 0 in chart

<img width="701" alt="Screen Shot 2020-04-11 at 8 29 02 AM" src="https://user-images.githubusercontent.com/57390535/79034913-b0541000-7bce-11ea-83ff-03d6af448275.png">
like this
but now thee whole part of line goes to red color
we want if in next labels we have positive data, show it in different color

**Comment by junedchhipa** [comment]
Has been suggested before. Currently, not possible, but may come in the future.
Related to #585

**Comment by Fusseldieb** [comment]
Would be amazing if possible :D

**Comment by NikicaCh** [comment]
no way to do it yet ?

**Comment by alexp4dev** [comment]
Any news about that ?

**Comment by Fusseldieb** [comment]
Don't stale
