### ISSUE TITLE
Cannot set selection after upgrade to v3.18 

### ISSUE THREAD

**Issue by fracz** [apexcharts/apexcharts.js#1488]
# Bug report

## Codepen

I have modified the [brush chart codepen](https://codepen.io/apexcharts/pen/rqWeBX). Did not change anything in the chart code. Only added a new `changeSelection` function at the end of the JS script, that uses `chart2.updateOptions()` function to update the selection to something random. Also, added a button below the chart that invokes the new function.

https://codepen.io/fracz/pen/JjYoBXo

## Explanation

* open the [codepen](https://codepen.io/fracz/pen/JjYoBXo)
* click the *Change selection* button a few times - it works and the selection is being changed
* now drag the selection on brush chart to some other position
* the button does not work anymore (i.e. the selection does not change after calling the updateOptions).

This broke in my application after upgrading to v3.18.0. v3.17.1 works correctly.

**Comment by junedchhipa** [comment]
I confirm the issue.
It will be addressed soon.
