### ISSUE TITLE
Radar Polygon Stroke Color Property Not Working

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#1490]
I am implementing the radar chart, but I run into an issue. When the polygon 'stroke color' property of the radar chart gets changed, the polygon stroke color stays the default color. No errors are visible. This is the property:

```
plotOptions: {
        radar: {
          size: 140,
          polygons: {
  ->      strokeColor: "#000000",
            fill: {
              colors: ["#f8f8f8", "#fff"]
            }
          }
        }
      },
```
**Here is a pen that shows the issue:**
https://codepen.io/thimows/pen/poJxvRP

Hopefully this bug can be confirmed and fixed.

**Comment by junedchhipa** [comment]
It's actually `polygons.strokeColors`
You missed the `s`.
It accepts an array as well - [docs](https://apexcharts.com/docs/options/plotoptions/radar#radarpolygonsStrokeColor)

**Comment by Thimows** [comment]
Thank you so much! That fixed it! I think there is a typo on the docs page [here](https://apexcharts.com/javascript-chart-demos/radar-charts/radar-with-polygon-fill/) (here it is polygons.strokeColor -> without the 's').

**Comment by junedchhipa** [comment]
Thanks for pointing that out.

**Comment by Thimows** [comment]
Hi @junedchhipa I have one last question (hope you don't mind). I am trying to change the Y-axis label font color of the Radar chart, but it doesn't seem to work (while it works for the x-axis).

```
yaxis: {
      show: true,
      labels: {
          show: true,
          align: 'right',
          minWidth: 0,
          maxWidth: 160,
          style: {
 --->      colors: ["#ffffff"],
              fontSize: '12px',
              fontFamily: 'Helvetica, Arial, sans-serif',
              fontWeight: 400,
              cssClass: 'apexcharts-yaxis-label',

}, 
}
}
```

**Here is the pen to illustrate the issue:** 
https://codepen.io/thimows/pen/poJxvRP

Hope that this is as easy to fix as the last issue (;

**Comment by Thimows** [comment]
Do you think that this could be a bug or should I create a separate post for this issue?

**Comment by junedchhipa** [comment]
It's a bug in ApexCharts - a minor typo which I have missed in y-axis labels for radar-charts
