### ISSUE TITLE
Hovering y-axis shows x-axis tooltip

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1495]
# Bug report

## Codepen

[CodePen](https://codepen.io/bilge-the-encoder/pen/yLYLMZo).

## Explanation
Hovering over the y-axis shows the x-axis tooltip, even if it's uninitialized (such as immediately after loading). If the tooltip has already been loaded and shown at another location, the tooltip is revealed at the last known location with the previous values. 

![image](https://user-images.githubusercontent.com/470626/79132279-f31a1180-7da1-11ea-9ca7-df0f491aaa12.png)

It seems to me that since the y-axis has nothing to do with the x-axis tooltip, it should not be revealed or interact with the y-axis in any way (i.e. it should stay hidden).

**Comment by junedchhipa** [comment]
It's actually not an x-axis tooltip, but the location makes it seem so.
It is an unloaded normal tooltip.

**Comment by junedchhipa** [comment]
Although, this needs to be avoided, hence tagging as a bug.

**Comment by junedchhipa** [comment]
No more an issue as tested on v3.52.0
