### ISSUE TITLE
Annual x-series markers misrepresent start of the annum

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1496]
# Bug report

## Codepen

[CodePen](https://codepen.io/bilge-the-encoder/pen/yLYLMZo).

## Explanation

- What is the behavior you expect?
Annual x-series markers (e.g. 2013, 2014, 2015, ...) should demarcate the start of that year.

- What is happening instead?
The annum marker appears in October, 10 months after the start of the year.

![image](https://user-images.githubusercontent.com/470626/79138743-f2d34380-7dac-11ea-817d-0c389d8dfa4f.png)

**Comment by junedchhipa** [comment]
This bug was fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/9adf6d5240f40e7816db49cd852324ca605b7f9b) while #1478  was fixed.
Let's keep the issue open until the next patch version is released and close it after testing.

**Comment by Bilge** [comment]
@junedchhipa Good idea. I'll test it as soon as it's released!

**Comment by Bilge** [comment]
Confirmed this is fixed in 3.19.2.
