### ISSUE TITLE
Rendered chart is 1 day delayed

### ISSUE THREAD

**Issue by noriellecruz** [apexcharts/apexcharts.js#1499]
# Bug report
Rendered chart is 1 day delayed

## Explanation
I'm not sure if this is a bug but the columns are rendered with delay of 1 day even though the last timestamp is "1586793600000", it's showing as april 13 and april 13 timestamp as april 12 and so on.

This is the array of data returned with ajax, as you can see all of it are valid timestamp but apex is showing it wrong when being rendered.

`[1586188800000,40],[1586102400000,26],[1586016000000,2],[1586275200000,21],[1586361600000,14],[1586448000000,4],[1586534400000,4],[1586620800000,22],[1586707200000,5],[1586793600000,7]`

Am I missing any configs to fix this or is this a bug? Thanks.

- What is the behavior you expect?
  No delay when representing timestamp arrays
- What is happening instead?
  1 day delay when data are getting displayed
- What error message are you getting?
  None

**Comment by fracz** [comment]
X-Axis displays datetimes in UTC by default. Try turning off the `datetimeUTC` https://apexcharts.com/docs/options/xaxis/
