### ISSUE TITLE
Can categories be displayed via dataLabels?

### ISSUE THREAD

**Issue by diomed** [apexcharts/apexcharts.js#150]
I see that series can, but how would I display categories in bar as well?

**Comment by junedchhipa** [comment]
@diomed I failed to understand what you mean. Can you please elaborate?
Are you looking for something like this?
![screen shot 2018-10-09 at 7 27 21 pm](https://user-images.githubusercontent.com/17950663/46674277-5e0cea00-cbf9-11e8-8c65-f55ea67a0611.png)

**Comment by diomed** [comment]
yes

**Comment by junedchhipa** [comment]
I will put the above example in website demo pages soon.

For now, you can try the following code to achieve the same result

```javascript
{ 
  plotOptions: {
    bar: {
      horizontal: true,
      dataLabels: {
          position: 'bottom'
      },
    }
  },
  dataLabels: {
    enabled: true,
    textAnchor: 'start',
    style: {
        colors: ['#fff']
    },
    formatter: function(val, opt) {
        return opt.globals.labels[opt.dataPointIndex] + ":  " + val
    },
    offsetX: 0,
  },
  yaxis: {
    labels: {
      show: false
    }
  }
}
```

**Comment by junedchhipa** [comment]
Added example on website https://apexcharts.com/javascript-chart-demos/bar-charts/custom-datalabels/
