### ISSUE TITLE
How to Display json data value in stacked bar chart?

### ISSUE THREAD

**Issue by iamrraj** [apexcharts/apexcharts.js#1508]
Hey i am trying to implement json API data value in stacked bar chart but i don't know how to do it here is json api  http://www.mocky.io/v2/5e96ff763000006500b6da20 and its look like ``` ``` 
{"topology": [
        {
            "label": "living_street",
            "value": 0.010549953326361517
        },
        {
            "label": "tertiary",
            "value": 0.767246375468044
        },
        {
            "label": "primary",
            "value": 0.21522791175081937
        },
        {
            "label": "service",
            "value": 0.006975759454774865
        }
    ]
}

and here is my code that i did so far
```

`fetchData() {
    fetch(`http://www.mocky.io/v2/5e96ff763000006500b6da20`)
      .then(response => response.json())
      .then(dat => {
        const dat1 = dat.map(c => {
          return c.label;
        });
        const dat2 = dat.map(c => {
          return c.value;
        });
        const newXaxis = dat1;
        const newSeries = [];
        newSeries.push({
          data: dat2,
          name: this.state.series.labels
        });
        this.setState({
          series: newSeries,
          options: {
            ...this.state.options,
            labels: newXaxis,
            xaxis: { ...this.state.options.xaxis, categories: newXaxis }
          }
        });
      });
  }

  componentDidMount() {
    this.fetchData();
  }`

...

 return (

        <Chart
          options={this.state.options}
          series={newSeries}
          type="bar"
          height="150px"
        />
}
```

but it did  not show in stacked chart is shows like this 

![Screenshot 2020-04-15 at 14 40 48](https://user-images.githubusercontent.com/37672067/79338174-1d490c00-7f27-11ea-9530-1482b89dd659.png)

and i want to display like this. 
![Screenshot 2020-04-15 at 14 43 54](https://user-images.githubusercontent.com/37672067/79338405-892b7480-7f27-11ea-89ca-b743a2ee2351.png)

**Comment by iamrraj** [comment]
I have resolve this issue.

**Comment by MauroCandido** [comment]
> I have resolved this issue.

What did you do ? I've been trying to solve this too !

**Comment by iamrraj** [comment]
const MakData = data.map((c, label) => ({
              label: c.label,
              value:Value,
 }));
const SeriesData = [];
for (let i = 0; i &lt; MakData.length; i++) {
        SeriesData.push({
                name: data1[i].label,
                data: data1[i].value,
        });
}
 <Chart
                  style={{ marginTop: "-40px" }}
                  options={this.state.options}
                  series={SeriesData}
                  type="bar"
                  height="150px"
 />

**Comment by MauroCandido** [comment]
Hi Rahul, thank you for your assistance

I tried and did not work, can you please see what I am doing wrong here ? This is my code:

<script>

    var options = {
        series: [{
            name: 'Engine block',
            data: [44]
        }
         ,
          {
            name: 'Pistons',
            data: [13]
        }, {
            name: 'Cylinder head',
            data: [18]
        }, {
              name: 'Crankshaft',
            data: [21]
            }, {
                name: 'Valves',
                data: [29]
            }
        ],

        series: [{
            data: []
        }],
        chart: {
            type: 'bar',
            height: 110,
            stacked: true,
            toolbar: {
                show: false
            },
            zoom: {
                enabled: false
            }
        },
        dataLabels: {
            enabled: true,
            textAnchor: 'start',
            style: {
                colors: ['#fff'],
                fontSize: '20px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                fontWeight: 'bold',
            },
            formatter: function (val, opt) {
                return  val
            },
            offsetX: 0,
            dropShadow: {
                enabled: true
            }
        },
        plotOptions: {
            bar: {
                horizontal: true,
                borderRadius: 5
            },
        },
        xaxis: {
           // categories: ['Engine block', 'SEI LA 2', 'SEI LA 3', 'SEI LA 4'],
            min: 0,
            //max: max,
            labels: {
                show: false
            }

        },
        yaxis: {
            labels: {
                show: false
            }
        },
        fill: {
            opacity: 1
        }
    };


        var chartBarPartNo = new ApexCharts(document.querySelector("#barChartAccessoriesPartNo"), options);
        chartBarPartNo.render();
        var controllerUrl = '@Url.Action("BarCharMonitorAspex",  controllerName: "barChart")';

        var data2 = {
        "data2": [
                    { "Part": "EB", "Description": "Engine Block", "Quantity": 52 },
                    { "Part": "CH", "Description": "Cylinder head", "Quantity": 49 },
                    { "Part": "OP", "Description": "Oil pan", "Quantity": 8 }
                 ]
                }

        a_data = data2;
        var produce = []
        //loop through return data
        $(a_data.data2).each(function (i, v) {
            //push values as x & y
            produce.push({
                "x": v.Part,
                "y": v.Quantity
            })
        })

        chartBarPartNo.updateSeries([{
            name: produce,
            data: produce
            }])

</script>





________________________________

**Comment by iamrraj** [comment]
Here is the Working example, I hope this will help you to find your solution.

https://codesandbox.io/s/empty-hooks-1ovlq?file=/src/App.js
