### ISSUE TITLE
Add multiple Charts into Jspdf 

### ISSUE THREAD

**Issue by lieyongchang** [apexcharts/apexcharts.js#1510]
**Is your feature request related to a problem? Please describe.**	
I want to add multiple charts into Jspdf without having to call multiple ApexCharts.exec

**Describe the solution you'd like**	
Have a function that allows me to add multiple charts as 1 image into Jspdf	

**Describe alternatives you've considered**	
Currently I am calling multiple ApexCharts.exec just to add multiple charts into Jspdf

**Additional context**	
![1](https://user-images.githubusercontent.com/62921597/79360704-dd117a00-7f76-11ea-87f2-8d80a711a94c.PNG)

Current version: "apexcharts": "^3.17.1",
                           "jspdf": "^1.5.3",

**Comment by lieyongchang** [comment]
Description: The red box shows an unintented situation.
Expected outcome: it should only drawText once on each page.
What is actually happening: This happens because, of multiple charts being add one the same page.
![error](https://user-images.githubusercontent.com/62921597/79361554-0383e500-7f78-11ea-8426-2eac8876d1e9.PNG)

**Comment by junedchhipa** [comment]
I would appreciate it if you can provide a codepen demo to easily reproduce it.

**Comment by lieyongchang** [comment]
I will to reproduce it on codepen, if cant, I will show u a snipshot of my code

**Comment by lieyongchang** [comment]
Below is  the code snipshot of the code that is rendering the text. Notice also i have to call Apexcharts.exec mutiple times just to include that amount of charts

![codesnipet](https://user-images.githubusercontent.com/62921597/79431693-5ce22780-7ffd-11ea-89c2-4b4a27047198.PNG)

**Comment by lieyongchang** [comment]
is there a cleaner way to do it ? or a method allow me to store mutiple charts and add as 1 image?

**Comment by junedchhipa** [comment]
Unfortunately, there is no single method to collect all the charts and produce a single dataURI.
I would like to see what is up with the muddled text. Are those chart titles of every chart?
As I said, a basic codepen will be really helpful to get to the root of the issue faster.

**Comment by lieyongchang** [comment]
will there be such a method in the future?

**Comment by lieyongchang** [comment]
how do i add jspdf into the codepen ?? because the drawText function utilize functions from jspdf

**Comment by junedchhipa** [comment]
> will there be such a method in the future?

No, not planned yet.


Our partner FusionCharts provides a premium addon for it. If you would like to try, here is [FusionExport](https://www.fusioncharts.com/fusionexport?utm_source=ac.github%2Fnpm&utm_medium=banner&utm_campaign=apexcharts&utm_content=fusionexport)

**Comment by junedchhipa** [comment]
> how do i add jspdf into the codepen ?? because the drawText function utilize functions from jspdf

You can add JSPDF script into codepen just like you added ApexCharts script

**Comment by lieyongchang** [comment]
This is the codesandbox that illustrate the muddy text problem 

https://codesandbox.io/s/react-datauri-stackoverflow-60110892-4p873

**Comment by junedchhipa** [comment]
Thank you for providing a codepen.
As I see, the text issue is not caused by ApexCharts directly. That text is drawn using jsPDF so there is some other issue going on.
Unfortunately, a single method for collecting all charts into a single dataURI method will not be possible.

**Comment by lieyongchang** [comment]
However I tried to use a for loop and html2canvas to generate multiple charts into the page, but i am facing an issue of not being able to insert the different div in alternate page.

see below codepen link for example
https://codesandbox.io/s/falling-shadow-zugol?file=/src/App.js
