### ISSUE TITLE
Add category index to colors function

### ISSUE THREAD

**Issue by mika76** [apexcharts/apexcharts.js#1511]
Currently the colors function has available seriesIndex, dataPointIndex, and value (from https://apexcharts.com/docs/options/colors/ and some console logging) - could you add categoryIndex as well?

This would help color stacked bar charts different colors depending on what you are showing...

**Comment by mika76** [comment]
Still a valid request 😊

**Comment by mika76** [comment]
Still a valid request

**Comment by mika76** [comment]
Still a valid request

**Comment by mika76** [comment]
Still a valid request

**Comment by mika76** [comment]
(sigh) still valid...

**Comment by mika76** [comment]
still valid

**Comment by ky-cloudprinter** [comment]
Hi,
This feature can be really useful

**Comment by mika76** [comment]
still needed please

**Comment by mika76** [comment]
still needed

**Comment by mika76** [comment]
🙏

**Comment by mika76** [comment]
That's a great solution thanks @junedchhipa
