### ISSUE TITLE
TypeError: e[0] is undefined

### ISSUE THREAD

**Issue by lieyongchang** [apexcharts/apexcharts.js#1512]
# Bug report
Hi.

I use apexcharts with React without React-apexcharts.
I noticed a problem when creating a graph with the 'donut' type.

## Codepen
The error occurs in a local environment, so I will show screenshots to explain the problem

## Explanation

- What is the behavior you expect?
add the pie chart image into my pdf when I call the ApexChart.exec
- What is happening instead?
it keep saying that my chart id is undefined
![errormessage1](https://user-images.githubusercontent.com/62921597/79406846-ab2a0300-7fca-11ea-8607-192993f1ca81.PNG)
![errormessagePNG](https://user-images.githubusercontent.com/62921597/79406917-d44a9380-7fca-11ea-9540-56c2f400cca1.PNG)

but I have already define my chart id
![chart id](https://user-images.githubusercontent.com/62921597/79406899-cbf25880-7fca-11ea-9f50-266d31c8cca4.PNG)

- What error message are you getting?
see screen shot

**Comment by junedchhipa** [comment]
Which version of ApexCharts are you using?
This was an issue in older versions, so make sure you use the latest version and try again.

**Comment by lieyongchang** [comment]
"apexcharts": "^3.17.1", I am sure this is the latest

**Comment by junedchhipa** [comment]
No, 3.18.1 is the latest.
Please try the latest one and report back.

**Comment by lieyongchang** [comment]
Yesss !!!! updating to 3.18.1 resolve the issue !! Thanks
