### ISSUE TITLE
 please make column name 'category' in csv-export configurable

### ISSUE THREAD

**Issue by AdminMonika** [apexcharts/apexcharts.js#1514]
In the generated CSV file you will find 'category' as the first entry.
Is it possible to change this entry in the title of the xaxis, e.g. in 'period' or take a new field?

in apexcharts\src\modules\Export.js exportToCSV in line 258 this is hardcoded :(
columns.push('category')

**Comment by gp-manishverma** [comment]
this is what i am also looking for.

**Comment by drjwatson** [comment]
Also looking for this ability

**Comment by jaimestuardo** [comment]
I have just faced the same problem. It should be configurable, not only considering that the name is not meaningful in some cases but also when users do not speak English.

**Comment by junedchhipa** [comment]
I added a property called `headerCategory` in the options. You can use it like this

```javascript
chart: {
  toolbar:{
    export: {
      csv: {
        headerCategory: 'category',
        headerValue: 'value',
      }
    }
  }
}
```

Docs: https://apexcharts.com/docs/options/chart/toolbar#headerCategory

**Comment by engrajibulhasan** [comment]
```
charts:{
	toolbar: {
			export: {
			  csv: {
			    filename: "File Name,
			    columnDelimiter: ',',
			    headerCategory: 'category',
			    headerValue: 'value'
			  },
			  svg: {
			    filename: undefined,
			  },
			  png: {
			    filename: undefined,
			  }
			}
		       }
		      }
```

**Comment by engrajibulhasan** [comment]
```
charts:{
	toolbar: {
		export: {
		  csv: {
		    filename: "File Name",
		    columnDelimiter: ',',
		    headerCategory: 'category',
		    headerValue: 'value'
		  },
		  svg: {
		    filename: undefined,
		  },
		  png: {
		    filename: undefined,
		  }
		}
	}
}
```
