### ISSUE TITLE
Is it possible to create this chart?

### ISSUE THREAD

**Issue by ronaklalwaniii** [apexcharts/apexcharts.js#1516]
Hello, I want to create a create like the attached image. Is it possible to increase the height of bars to 100% like in the image?
![Column Chart](https://user-images.githubusercontent.com/44769573/79570365-edd90180-80d6-11ea-92e9-65c747817184.png)

**Comment by junedchhipa** [comment]
[100% Stacked column charts](https://apexcharts.com/javascript-chart-demos/column-charts/stacked-column-100/)
