### ISSUE TITLE
showSeries method doesn't work with stacked bar charts

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#1517]
The showSeries method doesn't seem to work with stacked bar charts while the hideSeries method works fine. This issue seems only to affect the stacked bar charts, because when you set 'stacked' to false it works again. I have created a pen to illustrate the issue:

**Codepen:** https://codepen.io/thimows/pen/OJyNqGX

Would really appreciate to know if this is a bug.

**Comment by Thimows** [comment]
@junedchhipa  After some more testing it really looks like there is a bug with the 'stacked' options for bar charts and the showSeries method. The toggleSeries method also doesn't show the stacked bar chart.

**Comment by junedchhipa** [comment]
I confirm the bug.
It will be addressed soon.

**Comment by Thimows** [comment]
Great, thank you so much!

**Comment by Thimows** [comment]
@junedchhipa Thank you so much for the fix! Do you know when the new version will be released? Thanks!

**Comment by junedchhipa** [comment]
In the next 12 hours
