### ISSUE TITLE
Annotations at start of X-axis overlap Y-axis labels 

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1519]
# Bug report
There are two parts to this:

1. Annotations near the Y-axis will overlap the axis labels, making them difficult to read.
2. Annotations can appear outside the chart if their value is less than the start of the X-axis.

## Codepen

[CodePen](https://codepen.io/bilge-the-encoder/pen/eYpzvPX). In this pen, the first chart represents (1) and the second chart represents (2).

## Explanation

For (1) the solution should be to flip the label so it appears on the right-side of the stem instead of the left. For (2) the solution should be to occlude the label (hide it) since it appears outside the valid charting area, perhaps with a warning in the console that this is happening.

**Comment by radilr1** [comment]
I also have the same issue here is a screenshot:
<img width="542" alt="Screenshot 2020-09-23 at 13 18 53" src="https://user-images.githubusercontent.com/1165581/94000095-58395080-fd9f-11ea-9ec5-be69b7bfeb49.png">
