### ISSUE TITLE
Stacked series with gradient fill are not occluded

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1521]
# Bug report

Stacked series are rendered on top of each other, so for gradient fills, the colours merge together which may often be undesirable. Each graph should occlude the other such that the colours do not merge. In this example, the negative graph (red) comprises the majority but it still looks green because the positive graph is predominantly showing through from underneath.

## Codepen

[CodePen](https://codepen.io/bilge-the-encoder/pen/eYpzvPX) (lower chart).

## Explanation

This chart should appear mostly red.

![image](https://user-images.githubusercontent.com/470626/79641317-b332a000-818e-11ea-9fe0-c6fb85944445.png)

However, the small amount of positive review stacked on top of it cause discolouration, making it look more green that it should be.

![image](https://user-images.githubusercontent.com/470626/79641313-a6ae4780-818e-11ea-88e2-bbc38d51946b.png)

Since this is a stacked series, it should only be filled as far down as the graph underneath it, not the entire area under the line.

**Comment by junedchhipa** [comment]
This, unfortunately, cannot be avoided.
The whole path draws from the base of the chart, so coloring on the stacked part is not possible.

Please use solid color in such a case or increase the opacity.

**Comment by Bilge** [comment]
@junedchhipa Can I apply a custom fill to just one of the line graphs (the red one) and not the other?

**Comment by fredriklengstrand** [comment]
@junedchhipa The green color still affects the red color even when I use solid fill.

```
fill: {
    type: 'solid'
}
```

Am I missing a setting to fully remove the transparency?
