### ISSUE TITLE
Getting the first and last values after update

### ISSUE THREAD

**Issue by npomfret** [apexcharts/apexcharts.js#1523]
Some advice pls.

I'm trying to read the first and last displayed data pints of my chart.  I have zoom and scroll enabled and a brush chart.  It looks like the `updated` event gets fired after any of these features are used.  But the event doesn't appear to contain the data I need, at least I can't find it.  How do I find what the first and last displayed values are?

**Comment by junedchhipa** [comment]
At which place/event you're trying to get the information?
If you can post more code (or post a codepen example), I can suggest the place to look for the first and last labels.

**Comment by npomfret** [comment]
Thanks for the response.  I found it.  The _updated_ event has a `config` param which in turn has another `config` object inside it.  From there I can get the _min_ and _max_ from the xaxis, and then I search my original dataset for the nearest matching value.
