### ISSUE TITLE
dataLabels are not working properly on bar charts with negative values

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#1524]
When you create a bar chart with data labels and (partly) negative data the data labels are expected to be in the middle of each bar, but the data labels of the negative values are under the bar. The data labels on the positive values have the correct placement.

**Codepen:** https://codepen.io/thimows/pen/pojbOEp

**Comment by Steven1284** [comment]
I have the exact issue. Really weird. Is there a way to solve this @junedchhipa? For now I think it is the best not use data labels with bar charts.

**Comment by Thimows** [comment]
Yeah, I noticed that this also happens with charts with multiple bars ):

**Comment by junedchhipa** [comment]
@Steven1284 Yeah, I confirm the issue.
It will be addressed very soon as it is a major bug.

**Comment by Steven1284** [comment]
You are the best! Hope the update gets released soon.

**Comment by Thimows** [comment]
Thank you again!

**Comment by niravpatel2008** [comment]
> @Steven1284 Yeah, I confirm the issue.
> It will be addressed very soon as it is a major bug.

https://codepen.io/niravpatel2008/pen/dyNmQJK

can you please check this codepan ? its not working for negative value can you please help?
