### ISSUE TITLE
Pie chart display series-1 depite assigning one string to it

### ISSUE THREAD

**Issue by lieyongchang** [apexcharts/apexcharts.js#1526]
# Bug report
on the pie chart label, it shows series-1 instead of the intended string

## Codesandbox
below is the codesandbox, line 97 - 99 is the line of code where i insert the string
https://codesandbox.io/s/funny-fermat-wos51?file=/src/App.js

options.labels did not update accordingly, it shows series-1 instead
## Explanation

- What is the behavior you expect?
render the intented string onto the data label
- What is happening instead?
series 1 instead

**Comment by junedchhipa** [comment]
Please ask basic react questions on Stackoverflow.
ApexCharts will update the chart automatically if the state is updated. In your example of the pie chart, you are not using a state, but a local variable.
