### ISSUE TITLE
Customizable CSV export

### ISSUE THREAD

**Issue by Peter-Reimer** [apexcharts/apexcharts.js#1527]
1. Set the name of the Downloaded CSV file. Currently files are always called like the chart(ID).
2. I have categories / legends that can contain commas, so I need a way to change the delimiter.
3. Change the category and value column name in the CSV Data.
4. Second category/text on the right side of the data in the CSV File.
5. An extra column in the first line (similar to a title) above the CSV data.

**Describe the solution you'd like**	
The column names and delimiters are hard-coded in the exportCSV function.
Maybe you could specify these strings in the ChartOptions so that the export can is more customizable?

**Comment by djdance** [comment]
+1

**Comment by junedchhipa** [comment]
Sure, I will add these options.

**Comment by shinygucci** [comment]
What do 'headerCategory' and 'headerValue' do? I'm trying to add another row as a header, but changing those values aren't doing anything.

**Comment by junedchhipa** [comment]
@shinygucci These options were added recently and not been released to npm.
Please wait for v3.19.3 to use these properties.

**Comment by marianskrisa** [comment]
Is it possible to remove csv option from the list and also have an option to change the png and svg filename?

**Comment by Kosardev** [comment]
@junedchhipa when I use brush chart and export CSV file the first cell is the value of selection xaxis minimum value but the first row values are for first datas for whole chart , I mean first value of first point in xaxis of chart and first columns are just from selection xaxis minimum till maximum value , but other columns have entire data.

**Comment by 4lena** [comment]
Hello, 

Is there any way to add extra columns in the exported CSV file?

Thanks

**Comment by tanuj1811** [comment]
is this feature available in react-apexcharts also. Can anyone show the example, how to add extra column in export csv that will be sum of last two column. or anything
