### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by Christilut** [apexcharts/apexcharts.js#1528]
# Bug report

I received a few of these errors in Sentry. I don't know how to reproduce them but I wanted to report them just in case.

I have a pie chart that uses the legend, so I'm guessing the error occurs there. The pie chart has been online for months and this is the first time this happened.

Feel free to close if this is not enough information. 

## Codepen

```
TypeError: Cannot read property 'node' of undefined
  at pathMouseDown(./node_modules/apexcharts/dist/apexcharts.common.js:1617:29)
  at toggleDataSeries(./node_modules/apexcharts/dist/apexcharts.common.js:16364:20)
  at apply(./node_modules/apexcharts/dist/apexcharts.common.js:16211:14)
  at HTMLDivElement.r(./node_modules/@sentry/browser/esm/helpers.js:71:23)
```

Extra info from Sentry:
```
[{currentTarget: div > div#apexchartspffwvyaj.apexcharts-canvas.apexchartspffwvyaj.dark, isTrusted: [Circular ~], target: div.apexcharts-legend-series > span.apexcharts-legend-text, type: click}]
```

Chrome 81
"apexcharts": "^3.7.1",
"vue-apexcharts": "^1.3.5",

**Comment by junedchhipa** [comment]
I can trace the error, but I also cannot reproduce it.
If you can reproduce in a codepen or identify when exactly it occurs, I will take a closer look.
