### ISSUE TITLE
wishlist: togglePanning() and toggleZoomSelection() for synchronized charts

### ISSUE THREAD

**Issue by az143** [apexcharts/apexcharts.js#1530]
**Is your feature request related to a problem? Please describe.**	
showing N toolbars on each of N synchronized charts is pretty ugly, given that zoom or pan actions do apply to all N charts. 
i'd like to show the toolbar only for the first chart, and have its buttons apply to all charts. 
for zoom in/zoom out/reset that works out of the box (with v3.18.1), but for switching to pan or  zoom by dragging it doesn't.

**Describe the solution you'd like**	
i think that extending togglePanning() and toggleZoomSelection() to use getSyncedCharts()  to find and then apply the changes to all grouped charts would be a straightforward solution.

**Comment by junedchhipa** [comment]
Thanks for the suggestion.
Implemented it.
