### ISSUE TITLE
backgroundBarRadius not working

### ISSUE THREAD

**Issue by ronaklalwaniii** [apexcharts/apexcharts.js#1531]
Hello, 
I want the column chart's background radius to be 20% rounded. I tried using  `backgroundBarRadius`
but it is not working. Can you help me out. Below is my code and result:

```
`{
      chart: {
        height: 400,
        type: 'bar',
        stacked: true,
        toolbar: {
          show: false
        }
      },
      plotOptions: {
        bar: {
          columnWidth: '15%',
          colors: {
            backgroundBarColors: ['#daddff'],
            backgroundBarRadius: 20
          }
        }
      },
      dataLabels: {
        enabled: false
      },
      legend: {
        show: false
      },
      colors: [config.colors.primary, chartColors.primary.light_100, chartColors.primary.light_200],
      stroke: {
        show: true,
        colors: ['transparent']
      },
      grid: {
        xaxis: {
          lines: {
            show: true
          }
        }
      },
      series: [
        {
          name: 'Series 1',
          data: [400, 400, 400, 400, 400, 400, 400, 400, 400]
        },
        {
          name: 'Series 2',
          data: [200, 255, 170, 220, 210, 320, 280, 250, 300]
        },
        {
          name: 'Series 3',
          data: [170, 220, 90, 150, 180, 220, 195, 175, 200]
        }
      ],
      xaxis: {
        categories: ['7/12', '8/12', '9/12', '10/12', '11/12', '12/12', '13/12', '14/12', '15/12']
      },
      fill: {
        opacity: 1
      }
    }`
```
![chart](https://user-images.githubusercontent.com/44769573/79859463-af9d5400-83ee-11ea-9936-1992caa1cba3.PNG)

Thanks in advance

**Comment by junedchhipa** [comment]
The property works fine on my side.
Which version of apexcharts are you using? The property was added recently, so make sure you update to the latest version.

**Comment by ronaklalwaniii** [comment]
Thanks for the quick reply i am using the latest version. Maybe something is wrong in my code did you check my code?

![package](https://user-images.githubusercontent.com/44769573/79865192-63efa800-83f8-11ea-98b5-56292b02e01d.PNG)

**Comment by junedchhipa** [comment]
Yeah, I checked out your code. Please note that the background bars color won't show in 100% stacked column chart, but it will show up in a normal stacked column chart.

![Screen Shot 2020-04-21 at 7 01 03 PM](https://user-images.githubusercontent.com/17950663/79871854-9f8f6f80-8402-11ea-8000-364cefb05c69.png)

The above screenshot shows the gray-colored background bars with borderRadius: 10

**Comment by ronaklalwaniii** [comment]
I fixed it by removing node_modules and yarn.lock and reinstalling them. 
I am closing this issue.
Thanks for the help 🙂.
