### ISSUE TITLE
Heatmap series option "from-color" and "to-color"

### ISSUE THREAD

**Issue by Risingson** [apexcharts/apexcharts.js#1532]
**Is your feature request related to a problem? Please describe.**	
I did not find a way to fade from black instead of white with heatmaps. The charts are on a black background and should get colored from black to the color i set for the series.

**Describe the solution you'd like**	
define a _from-color_ and a _to-color_

**Describe alternatives you've considered**	
Maybe i am missing out on a setting to achieve this?

**Additional context**	
Also null values should be black.
![image](https://user-images.githubusercontent.com/5108701/79868001-904afa80-83df-11ea-8fbc-10b4cb27ba22.png)

**Comment by Risingson** [comment]
for the time being i modded the `shadeRGBColor `and `shadeHexColor `functions
changed the lines `t = percent < 0 ? 0 : 255,` to `t = percent < 0 ? 0 : 0,`

**Comment by short2strings** [comment]
Thanks @Risingson for the workaround tip -- it helped narrow things down.

**Comment by junedchhipa** [comment]
Closing this issue as the PR from @short2strings fixed this (heatmap on darker theme will get colored from dark to light).
Thanks to both of you.
