### ISSUE TITLE
ColorScale: cells of my heatmap did not follow the color code I set

### ISSUE THREAD

**Issue by lieyongchang** [apexcharts/apexcharts.js#1539]
# Bug report
After I specify my Upper/Lower limit of the range, the cells o f my heatmap did not follow the color code I set

## CodeSandBox
 https://codesandbox.io/s/apexchart-heatmap-rv7rt?file=/src/App.js

## Explanation
In the [doc](https://apexcharts.com/javascript-chart-demos/heatmap-charts/color-range/), the cells color are render correctly accordingly to the range it set, 
but not for my case.

Any help will be greatly appreciated

**Comment by ywiyogo** [comment]
@lieyongchang did you solve this issue? If yes, what was the cause?
