### ISSUE TITLE
toggleDataSeries in StackedBarChart not working properly @3.19.0

### ISSUE THREAD

**Issue by EduardoEncinaLuna** [apexcharts/apexcharts.js#1552]
# Bug report
ToggleDataSeries leaves transparent spaces in StackedBarChart

Version: Apexcharts 3.19.0

## Codepen

https://codepen.io/eduardoencinaluna/pen/GRpENra

## Explanation

- What is the behavior you expect?

click the data series one by one till the last series and expecting a blank chart

- What is happening instead?

After click one series and then another one, the chart renders transparent spaces for the clicked series

- What error message are you getting?

No message

## Reference Images
![image](https://user-images.githubusercontent.com/22559836/80434267-04454100-88bf-11ea-8716-3f35451f6007.png)

first one clicked
![image](https://user-images.githubusercontent.com/22559836/80434297-12935d00-88bf-11ea-8e16-d65fafc4d8af.png)

then second one
![image](https://user-images.githubusercontent.com/22559836/80434328-29d24a80-88bf-11ea-94a6-0c6482b081df.png)

**Comment by lluuz** [comment]
Yep, I'm having the same problem.

**Comment by junedchhipa** [comment]
Fixed in 3.19.3
