### ISSUE TITLE
NaN point value makes series disappear@3.19.0

### ISSUE THREAD

**Issue by jasmynn** [apexcharts/apexcharts.js#1559]
Toggling one legend on the demo shown on below link seems to toggle all series at once. Experience this when library is deployed on production environment only. On local library seems to work as expected. Kindly look into the link below and try toggling the legends. This is the same scenario that happens on live prod environment.

_https://apexcharts.com/javascript-chart-demos/line-charts/null-values/_

- What is the behavior you expect?
Toggle series selected only.

- What is happening instead?
Toggling one legend on the demo shown on below link seems to toggle all series at once. Then after clicking the legend again did not show all the data points again.

**Comment by jasmynn** [comment]
Having same issues on project I am working on. Found out that ApexChart will not be able to display line chart when some of its values are NaN.

**Comment by jasmynn** [comment]
See sample data here. Line chart with legends.

[{
		name: "Secondary Task 1 Actual",
		data:
		[{
				x: "04-11-2020 00:00 GMT",
				y: NaN
			}, {
				x: "04-13-2020 01:00 GMT",
				y: NaN
			}, {
				x: "04-15-2020 02:00 GMT",
				y: 47
			}, {
				x: "04-17-2020 03:00 GMT",
				y: 20
			}, {
				x: "04-26-2020 04:00 GMT",
				y: 10
			}, {
				x: "04-30-2020 05:00 GMT",
				y: 11
			}
		],
		type: "line"
	}, {
		name: "Secondary Task 1",
		data:
		[{
				x: "04-11-2020 00:00 GMT",
				y: NaN
			}, {
				x: "04-13-2020 01:00 GMT",
				y: 15
			}, {
				x: "04-15-2020 02:00 GMT",
				y: 6
			}, {
				x: "04-17-2020 03:00 GMT",
				y: 10
			}, {
				x: "04-26-2020 04:00 GMT",
				y: 60
			}, {
				x: "04-30-2020 05:00 GMT",
				y: 100
			}
		],
		type: "line"
	}, {
		name: "Task 3",
		data: [{
				x: "04-11-2020 00:00 GMT",
				y: 39
			}, {
				x: "04-13-2020 01:00 GMT",
				y: 508
			}, {
				x: "04-15-2020 02:00 GMT",
				y: 478
			}, {
				x: "04-17-2020 03:00 GMT",
				y: 208
			}, {
				x: "04-26-2020 04:00 GMT",
				y: 108
			}, {
				x: "04-30-2020 05:00 GMT",
				y: 118
			}
		],
		type: "line"
	}, {
		name: "Task 4",
		data: [{
				x: "04-11-2020 00:00 GMT",
				y: 39
			}, {
				x: "04-13-2020 01:00 GMT",
				y: 505
			}, {
				x: "04-15-2020 02:00 GMT",
				y: 475
			}, {
				x: "04-17-2020 03:00 GMT",
				y: 250
			}, {
				x: "04-26-2020 04:00 GMT",
				y: 105
			}, {
				x: "04-30-2020 05:00 GMT",
				y: 115
			}
		],
		type: "line"
	}
];

**Comment by jkohlin** [comment]
I have a variant of this (apexcharts 3.19.0). When I click a legend to toggle the series (or call the method to toggle it) My lines dissapear
## Before click on legend
![image](https://user-images.githubusercontent.com/4112881/80596664-04f8e700-8a27-11ea-9f6b-9a98ab3e3e91.png)

## After clicking the legend
![image](https://user-images.githubusercontent.com/4112881/80596466-b0ee0280-8a26-11ea-8236-4e56f2f168ab.png)

Rolling back to 3.18.1 fixes the issue.

**Comment by jasmynn** [comment]
Hi I found similar issue that causes this on another library. My API returns "Null" if it's value is Null or NaN. But upon looking at console log of config.gobal.seriesLog it shows NaN instead of Null. Not sure why.

Below is where I am logging: 

  legendClick: (chartContext, seriesIndex, config) => {
                        console.log(config, "configGraph")
                        ApexCharts.exec(lineChart, 'toggleSeries', config.config.series[seriesIndex].name)

Please see this link for more reference of this issue: 
https://github.com/highcharts/highcharts/issues/3571

Title: NaN point value makes series disappear

If an area or line series has a point with 'NaN' value, the whole line disappears. In the previous example you can see the points, but for series with hundreds of points you can only see the tooltip.

**Comment by jkohlin** [comment]
For some reason, my issue seems to be gone in 3.19.2

**Comment by junedchhipa** [comment]
Yeah, this was fixed in the latest release.

**Comment by DavidMendes91** [comment]
I doing the backend stuff in python as was passing in numpy.nan as filler values, so that the shared tooltip would work.
This was resulting in JS's NaN, which was hiding the series.

passing python's None to JSON resulted in JS's null, which works correctly :)

**Comment by devlaam** [comment]
The problem seems to be back at version 3.46 , if i take [this example](https://codepen.io/apexcharts/pen/JpWmNe) and replace the code with:
```javascript
var x1 = Math.sqrt(-1);
var x2 = 42.2;
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "line",
    animations: {
      initialAnimation: {
        enabled: false
      }
    }
  },
  series: [
    {
      name: "Series 1",
      data: [
        [1486684800000.34, 34.7], 
        [1486771200000.45, 43.1], 
        [1486857600000, x1] , 
        [1486944000000, 43.6], 
        [1487030400000, x2], 
        [1487116800000, 52.0],
        [1487136800000, null],
        [1487176800000, 52.0],
        [1487196800000, 32.0]
      ]
    }
  ],
  xaxis: {
    type: 'datetime'
  }
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```
The line disappears:
<img width="654" alt="Screenshot 2024-02-24 at 17 11 04" src="https://github.com/apexcharts/apexcharts.js/assets/1237717/4b2e3e0e-df59-4d7d-8bad-99e94b13d158">

 However, with `type: "area"` it works as advertised. Btw `null` values are handled correctly.
