### ISSUE TITLE
Can't download CSV when some series are incomplete?

### ISSUE THREAD

**Issue by mattwensing** [apexcharts/apexcharts.js#1568]
Using 3.19, the "Download CSV" option goes away when I include a series with data that does not cover the same time range as other series.  Is this expected behaviour?

This is for a chart of type 'area'.

**Comment by sermeor** [comment]
Same issue here. Did you find a solution?

**Comment by mattwensing** [comment]
Never did!  Hid the option.

**Comment by niwsa** [comment]
For me same issue with "line" type

**Comment by weech3r** [comment]
Got the same issue.

**Comment by DavidMendes91** [comment]
Any updates on this ?

**Comment by RichardBH** [comment]
I am finding the same issue. Any updates on this?

**Comment by ericcirone** [comment]
I am having the same issue. The "Download CSV" button does not show up when any series contains 0 data points. When I remove those series, it then works. Also an issue i see is that if you have some series that don't have data for certain days, then the CSV file will omit those days, even if other series has data on those days.

**Comment by weech3r** [comment]
There are many limitations of CSV export in Apex. I decided to create my own exporter by using https://www.npmjs.com/package/export-to-csv and adding custom icon to Apex chart toolbar - it works perfectly and without any limitations so I recommend you to go this way.

**Comment by juan-carvajal** [comment]
The issue still exists in 2022...

**Comment by Teyken** [comment]
The issue still exists in 2023...

**Comment by OlegChuev** [comment]
The issue still exists. Any updates on this?

**Comment by roeszler** [comment]
Jun 2023 - The issue still exists. Any updates on this?

**Comment by DespuesLeeWallace** [comment]
I have the problem that the csv download button disappears when there is more than one dataset on the plot

**Comment by AniaKru95** [comment]
Please reopen, exporting to csv does not work for multiple charts

**Comment by mogmachine** [comment]
+1 ... so annoying as i need this to work.
