### ISSUE TITLE
Feature request: Custom annotation icon content

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right know I can add axis annotation which is a line with text annotation and rect background. I would love to be able to provide custom SVG content to draw instead of that text and rect, for example an icon.

**Describe alternatives you've considered**
No way to draw an anno icon right now.

**Additional context**
Providing SVG content in a var or callback which would return my content for Apexcharts to draw would be sufficient.

**Comment by junedchhipa** [comment]
Added an option to add custom SVG in point-annotations.
The feature will be available in 3.6.0

**Comment by Chelsea-Essam** [comment]
Is version 3.6.0 available to download yet?  
When I tried downloading the library from the official site it shows me it's v3.50.0
