### ISSUE TITLE
Area chart with a null value: filled area color is not uniform and animation is strange

### ISSUE THREAD

**Issue by adrienrenaud** [apexcharts/apexcharts.js#1570]
# Bug report

When having a `null` value in an area chart series, the filled area color is not uniform and the animation is strange.

## Codepen

https://codepen.io/adrienrenaud/pen/xxwXbqx

## Explanation

- What is the behavior you expect?

The filled area should have a uniform color.
The animation should be similar to the one without `null` value.

- What is happening instead?

The filled area does not have a uniform color. 
The animation looks strange.

- What error message are you getting?

No error message.

**Comment by philipp-schmidt** [comment]
Same problem here. Any solution?
