### ISSUE TITLE
New yaxis min and max options are ignored

### ISSUE THREAD

**Issue by 6XGate** [apexcharts/apexcharts.js#1578]
# Bug report

## Codepen

https://codepen.io/6XGate/pen/bGVabVM

## Explanation

- What is the behavior you expect?

The `yaxis` `min` and `max` would be updated based on the new chart options.

- What is happening instead?

The `yaxis` `min` and `max` changes are ignored.

- What error message are you getting?

None, the component seems to silently ignore the changes to the options.

**Comment by mikelga** [comment]
Hi!
I have the same problem. Have you managed to fix it?
Thanks!

**Comment by 6XGate** [comment]
Just an FYI to other users till this is fixed, version `3.10.1` is the latest version that does not have this issue.

**Comment by guillaume-vernet** [comment]
Hi,
the provided codepen works (min max are updated)
In pen settings, 
https://unpkg.com/apexcharts@3.19.3 -> not working
https://unpkg.com/apexcharts@3.20.0 -> working

So I guess the issue was fixed in `3.20.0`

**Comment by 6XGate** [comment]
Yes, awesome.
