### ISSUE TITLE
Bar width, datetime, data overlap

### ISSUE THREAD

**Issue by Redbom** [apexcharts/apexcharts.js#1583]
Hello.
I programing chart with real time data.
Data arrives at different intervals.

https://codesandbox.io/s/vue-basic-example-hmxov?file=/src/components/Chart.component.vue

Look at the picturie:
![GIT_APEX_example](https://user-images.githubusercontent.com/40491881/81061917-daeb6d00-8edd-11ea-996f-f93b1d1c304a.png)

1 - how make width 100%?
2 - date in the wrong place
1588661399 = 2020-05-05T06:49:59+00:00 almost 06:50:00
1588661452 = 2020-05-05T06:50:52+00:00 much further 06:50:00
3 - data overlap.
4 - where date? (date sometimes appears in wrong place)

The difference in data between 2 charts is only 1 value at 1588661496000

Can i set interval manualy (1sec, 5min, 1day) for prevent nr3 - data overlap?

**Comment by junedchhipa** [comment]
If the bars are overlapping, one thing that might be causing is the dates not being sorted in ascending order. Make sure that the dates you provide are coming in ascending order.

Also, upgrade apexcharts to 3.19.0 to fix the width issue.

**Comment by Redbom** [comment]
Many thanks!
Sorting in ascending order has solved many problems.
But one problem remained.
Incorrect date position.

https://codesandbox.io/s/vue-basic-example-vw0m4?file=/src/components/Chart.component.vue:3107-3117

![Screenshot_15](https://user-images.githubusercontent.com/40491881/83108451-7d0b0900-a0c8-11ea-9d8c-e88d4007e503.png)
