### ISSUE TITLE
Enable theme mode dark for heatmap

### ISSUE THREAD

**Issue by konradstrek** [apexcharts/apexcharts.js#1596]
Is there any method to change default heatmap fill ```#fff``` to ```#192734```
?
```
theme: {
   mode: 'dark',
},
```
Not working for heatmap. Preview:

![ice_screenshot_20200508-162951](https://user-images.githubusercontent.com/37452287/81415758-26ee1a00-9149-11ea-98dc-470570372c90.png)

**Comment by junedchhipa** [comment]
Related to #1532

**Comment by junedchhipa** [comment]
PR #1666 fixes this.
