### ISSUE TITLE
 [React] datetime xaxis labels with stacked turns into hours?

### ISSUE THREAD

**Issue by MerApelsin** [apexcharts/apexcharts.js#1597]
# Bug report
Hope this is the right place for this and I'm using react with latest version of both libs.

It seems like when using a nested series (having both x and y values in an array, can be seen below) makes datetime type act a bit strange, as I'd like the result to be the same as `type: category` gives the chart.

Some screenshots;
Using categories:
[img](https://i.imgur.com/BQyOTrg.png)
and using datetime:
[datetime img](https://i.imgur.com/VPJ061W.png)

The series looks as following:
```
[
	{name: "applied", data: [{x: "2020-01-01", y: 8},{x: "2020-01-02", y: 7},{x: "2020-01-03", y: 4}]},
	{name: "uploaded", data: [{x: "2020-01-01", y: 3},{x: "2020-01-02", y: 2},{x: "2020-01-03", y: 5}]},
	{name: "recommended", data: [{x: "2020-01-01", y: 3},{x: "2020-01-02", y: 1},{x: "2020-01-03", y: 1}]}
]
```
## Codepen

Just change the xaxis type to 'category' in options to see it as expected, current is datetime.
Codepen of issue [is here](https://codesandbox.io/s/apexchart-react-datetime-stacked-dxj2y)

## Explanation

- I expect it to look the same as Category except getting the flexibility of datetime
- I get hours as labels instead

**Comment by junedchhipa** [comment]
To fix the x-axis labels to a particular format, use
```javascript
xaxis: {
  labels: {
    format: 'dd-MM-yyyy'
  }
}
```

Or If you need a custom formatter to be applied to the labels, use
```javascript
xaxis: {
  labels: {
      formatter: function(value, timestamp, index) {
          return moment(new Date(timestamp)).format("DD MMM YYYY")
      }
  }
}
```
