### ISSUE TITLE
Clipmarkers on left and right of the grid are not working

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#160]
Here is the Codepen https://codepen.io/jimfilippou-the-animator/pen/WavEeV

![sketch 1](https://user-images.githubusercontent.com/6877046/46837492-3024d280-cdbe-11e8-9463-8d15462ed9f0.png)

Take a look at the above image, I believe the markers shouldn't be like this.

**Comment by junedchhipa** [comment]
If you are using numeric xaxis as shown in your screenshot, you might want to change `xaxis.type = 'numeric'` which will be introduced in v2.1.5

Once, you do that, the grid paddings will adjust automatically to make space for the markers.

**Comment by junedchhipa** [comment]
Cropped markers on the left and right of the grid are fixed.
From v2.1.9, you won't need `xaxis.clipMarkers` property anymore.
