### ISSUE TITLE
Download icon is always in the foreground

### ISSUE THREAD

**Issue by luscl1** [apexcharts/apexcharts.js#1604]
# Bug report
The download icon is always in the foreground. It doesn't matter if I use the default icon or my own. I have datepicker on the page over the icon and when I open it, I still see the download icon.
## Explanation
I would expect that the icon isn't visible when I open my datepicker. But at the moment I still see the icon even though the datepicker is opened. And the icon is also over my titlebar when I scroll the page.
I have a picture of my datepicker attached in which you can see the download icon at the top right corner. And I also have picture attached where you can see the download icon over my v-app-bar at the top of my application.

![image](https://user-images.githubusercontent.com/20835288/81820738-4615ee80-9531-11ea-819c-a01d00fb595b.png)
![image](https://user-images.githubusercontent.com/20835288/81820918-84131280-9531-11ea-9643-6c69523d7eb2.png)

**Comment by junedchhipa** [comment]
You may change the z-index of the toolbar

```CSS
.apexcharts-toolbar {
  z-index: 0 !important;
}
```
