### ISSUE TITLE
Brush chart selection event

### ISSUE THREAD

**Issue by andriiryzhyi** [apexcharts/apexcharts.js#1606]
If added selection event then first chart load all data:

https://codepen.io/andrii-ryzhyi/pen/BaoVzrr

If do updateOption after render and update selection event, then loads right selection data in first chart but change selection don't work.

**Comment by skywalker788** [comment]
Facing the same issue.
It seems that if you define an handler for the selection event on the brush chart you lose the default behaviour.
It doesn't happen if you define, for example, an handler on the the zoomed event for the main chart.

**Comment by geomatupen** [comment]
Having similar issue. After dragging/moving  the selection, chart stops updating dynamically which is perfectly working before dragging/moving the selection.

**Comment by slara** [comment]
I'm facing the same issue too. Is there any way to get `{ xaxis, yaxis }` without loosing the default behaviour?

**Comment by junedchhipa** [comment]
The solution provided by @slara caused an infinite loop issue.
Hence, I am going to add a new event `chart.events.brushScrolled` which will provide the new x-axis and y-axis information when the brush is scrolled.

This will help when you also want to use a brush chart but also want to get the xaxis/yaxis info when scrolled.

**Comment by samal-rasmussen** [comment]
`chart.events.brushScrolled` mostly fixes this, but it doesn't fire on drag on the start and end of the selection.
