### ISSUE TITLE
sorting by data number

### ISSUE THREAD

**Issue by diomed** [apexcharts/apexcharts.js#161]
is there a way to sory by data number?

https://codepen.io/diomed/pen/BqWBPr

I'd like to be able to sort graph from smallest number to largest

also what could I do to increase height, and to display full text of what is written in bar, 
since it gets cut if amount is too small?

**Comment by junedchhipa** [comment]
Sorting data items is a good suggestion, but in my opinion, needs to be handled externally before injecting data into the chart.

Regarding your second query, there is currently no way to manipulate text other than using label formatters. Also, you can display full text in the tooltip if it gets cropped in the bar data-labels

**Comment by diomed** [comment]
as you can see, I already have tooltip, so that saves it.

how would this be handled externally?

**Comment by junedchhipa** [comment]
Something like this

```javascript
var series = [{
  data: [{
    x: "Apples",
    y: 20
  }, {
    x: "Bananas",
    y: 24
  }]
}]
series[0].data.sort(function(a, b){
  return a.y > b.y;
});
```

After you sort it, you can then pass that data to the ApexCharts series.
