### ISSUE TITLE
Set minimum height or width for bar charts

### ISSUE THREAD

**Issue by fakhamatia** [apexcharts/apexcharts.js#1616]
If data is very lower than others, it's almost like zero, and the user can't click or hover because it's too small.
How can I set a minimum height or width for small numbers?
I really search for it.

![Vq8Za](https://user-images.githubusercontent.com/20030910/82151997-c90db080-9873-11ea-95e6-f9732ed9122c.png)

![Peek 2020-05-18 02-00](https://user-images.githubusercontent.com/20030910/82160556-73ed9100-98ab-11ea-82e9-8b8e0725212f.gif)

**Comment by fakhamatia** [comment]
Can anyone help?
I search in issues but can't find anything.

**Comment by john1999v** [comment]
@fakhamatia  u can check this here
[https://echarts.apache.org/en/option.html#series-bar.barMinHeight](https://echarts.apache.org/en/option.html#series-bar.barMinHeight)

**Comment by JayBox325** [comment]
@fakhamatia did you ever find a resolution for this?

**Comment by fakhamatia** [comment]
@JayBox325  find a resolution? I don't get it, this problem it's for all resolutions
Photos that users send me

![8c26f6da-a798-4c6b-bd0d-d988fb72b645](https://user-images.githubusercontent.com/20030910/94342911-5bdc0a00-0021-11eb-985e-0a242b753426.jpeg)
![463fa4b0-7bdb-4d10-b324-b03c97288238](https://user-images.githubusercontent.com/20030910/94342912-5e3e6400-0021-11eb-8db6-cefff6666c73.jpeg)
![6950ab22-a048-4b37-8e2c-cccb5958b645](https://user-images.githubusercontent.com/20030910/94342917-60082780-0021-11eb-9f93-50ce4a47aa69.jpeg)

**Comment by JayBox325** [comment]
I mean did you find a fix, or was it ever 'resolved'.

I managed to get around it using the responsive options so I set all my charts to me 350px tall on mobile. Then from tablet up, they use the sizes they need.

**Comment by fakhamatia** [comment]
@junedchhipa
Any help?

**Comment by SunKD** [comment]
@junedchhipa Could you fix this issue please?

**Comment by fakhamatia** [comment]
Its work on ApexCharts v3.22.0 bar chart
Thank you @alirezaftekhari

[https://stackoverflow.com/a/65171735/10695748](https://stackoverflow.com/a/65171735/10695748)

**Comment by ekhmoi** [comment]
Hey!
I was facing the same problem but for horizontal bars.
I found a workaround that works for my case. Feel free to give it a try.

The idea is to store the chart data in some property and map it to apex-charts with minimum width configured. Then add dataLabel formatter to display correct text.

```typescript
    chartData = [100, 20, 123, 4,0, 0];
    initChart() {
      const NO_VALUE_MIN_WIDTH = 1; // to display something when value is falsy. I need this, because I display hover 
      const MIN_WIDTH = 50;
      this.chartOptions.series = [
        {
          // Map this.chartData to series data
          data: this.chartData.map((value) => !value ? NO_VALUE_MIN_WIDTH : value >= MIN_WIDTH ? value : MIN_WIDTH),
        },
      ];
    }
```
Now you need to configure the formatter for datalables to display the correct text.

```typescript

    this.chartOptions.dataLabels.formatter = (_, opt) => {
      const name = opt.w.globals.labels[opt.dataPointIndex];
      const val = this.chartData[opt.dataPointIndex];
      return val ? `${name} (${val})` : '';
    }
```


Hope it helps someone out there!

**Comment by praveenpuglia** [comment]
This works out well for charts that have purely positive values or purely negative values. For charts that gets a mix, it's hard to define what the size of bars should be and in which direction.

Love the workaround though.

@junedchhipa Please add a simple option to add a min bar height in pixel so no matter what we can click on on it. At Voicezen we use apex to let people do data exploration and drilldowns. In many cases we have found users want to know what a zero value drills down into so they can find out WHY it was zero.

Allowing to have markers like we can on line charts on bar chart, no matter what the value is can also be another solution.

**Comment by fakhamatia** [comment]
Any News?

**Comment by litera** [comment]
I have a suggestion for zero values that doesn't require any *monkey patching* processing and zero values will always display with the same size regardless of the yaxis range (compared to solution @ekhmoi suggested).
Use `goals` to display a marker at `value: 0` with a predefined height/width and use the same colour as the series.
```
data: [{
    x: 123
    y: 0,
    goals: [{ value: 0, strokeColor: '#336699', strokeWidth: 3 }]
}, ... ]
```

**Comment by PeterBaptista** [comment]
I've built a workaround to this problem:
```js

const MIN_HEIGHT = 50;

const formattedSeries = series.map((item) => ({
    ...item,
    name: item.name,
    data: item.data.map((dataItem: any) => ({
      ...dataItem,
      y: !dataItem?.y
        ? 0
        : dataItem.y >= MIN_HEIGHT
          ? dataItem.y
          : MIN_HEIGHT,
      meta: { value: dataItem?.y },
    })),
  }));
 ```
 
-  I've put the real value in the meta field, but you have use the customs fields whenever you want to access the `real value`:
 
 ```js
 
  dataLabels: {
      enabled: true,
      offsetY: -35,

      formatter: (_, opts) => {
        // Access the series and data point index
        const seriesIndex = opts.seriesIndex;
        const dataPointIndex = opts.dataPointIndex;

        // Access the meta field for the current data point
        const value = Number(
          opts.w.config.series[seriesIndex].data[dataPointIndex].meta.value,
        );

        if (Number(value) < 1) {
          return '' as any;
        }

        return value.toLocaleString('en-US', {
          // add suffixes for thousands, millions, and billions
          // the maximum number of decimal places to use
          maximumFractionDigits: 2,
          // specify the abbreviations to use for the suffixes
          notation: 'compact',
          compactDisplay: 'short',
        });
      },
    },
```    


Another example you should do to tooltip:

```js
    tooltip: {
      custom({ series, seriesIndex, dataPointIndex, w }) {
        // Access the meta field for the current data point
        const value =
          w.config.series[seriesIndex].data[dataPointIndex].meta.value;

        return `<div class='p-2 flex gap-3 items-center'>\n
          <div style='background-color:${w.globals.colors[seriesIndex]}; width: 14px; height:14px;  border-radius: 9999px; '></div> \n
            <span>\n
              ${w.globals.seriesNames[seriesIndex]}:\n
            </span>\n
            <span >\n
              <span class='font-bold'>\n
                ${value}\n
              </span>\n

            </span>\n
          </div>`;
      },
    },
```

this is only necessary, because the real value is not on the expected value way, we are basically using a MinValue to set a MinHeight ou MinWidth to the bars

I hope it helps! :)
