### ISSUE TITLE
Tooltip marker fillColor array

### ISSUE THREAD

**Issue by dantelex** [apexcharts/apexcharts.js#1618]
When i put an array of colors in the tooltip marker fillColor, it only applies the first color in the array to everything.

I expect it to work the way legend marker fillColor works with array and use he array of colors passed.

I noticed this only happens when i add `shared: true` to tooltip

```
tooltip: {
    marker: {
       fillColors: [],
     },
}
```

<img width="471" alt="Screen Shot 2020-05-18 at 12 15 34 PM" src="https://user-images.githubusercontent.com/631543/82207411-b04bdc00-9901-11ea-8a41-87cab40dabef.png">

**Comment by junedchhipa** [comment]
Can you please create a [codepen](https://codepen.io/apexcharts/pen/xYqyYm) so I can easily reproduce it?

**Comment by junedchhipa** [comment]
Fixed it. A new patch release 3.19.3 will be released with this fix.

**Comment by dilipBadal** [comment]
I have the same issue. I am passing an array of colors and it always takes the first color.

I'm using - "apexcharts": "^3.32.1"
