### ISSUE TITLE
"beforeZoom" and "zoomed" events does not work correctly

### ISSUE THREAD

**Issue by XAHTEP26** [apexcharts/apexcharts.js#162]
1. **beforeZoom** event callback always throw error: _Uncaught TypeError: Cannot read property 'xaxis' of undefined_.
2. **beforeZoom** and **zoomed** events not fired when the selection goes beyond the block boundary with the schedule.

[Demo on Codepen](https://codepen.io/XAHTEP26/pen/rqYOmK)

**Comment by junedchhipa** [comment]
Fixed in 2.1.7.
