### ISSUE TITLE
Export image cuts x-axis labels

### ISSUE THREAD

**Issue by marinsagovac** [apexcharts/apexcharts.js#1621]
# Bug report

## Scenario
![pixels](https://user-images.githubusercontent.com/8504733/82317051-fcfce900-99cd-11ea-98b6-c3a11388e5d6.png)

When export image from toolbar it cuts x-axis label data.

## Explanation

Show image besides on image content, do not crop over x-axis labels.
That should keep and maintain by content of image.

Is it possible to add padding or margin?

**Comment by marinsagovac** [comment]
X-Axis is cropped only on export. There are not cropped in general.

**Comment by tahnoonn** [comment]
Also facing this issue on VueApexCharts.

**Comment by Teyken** [comment]
still an issues in 2023, crops x-axis labels in both sides.
