### ISSUE TITLE
Column Color should align to Column only.

### ISSUE THREAD

**Issue by gtl-alpesh** [apexcharts/apexcharts.js#1622]
Column color should be align to particular column only. 

![Column-Chart](https://user-images.githubusercontent.com/19168337/82325840-807fff80-99f9-11ea-9122-2cb4ceadbcbb.jpg)

via Grid Section, 
 grid: {
          borderColor: '#999',
          position: 'back',
          row: {
             colors: ['red', 'transparent'],
          }, 
          column: {
             colors: ['gray', 'transparent'],
          }, 
          xaxis: {
            lines: {
              show: true
            }
          }
},

- If we add Color in Grid, It works perfectly in Row only. 
- If we apply color to the column, Color should be apply to the particular column only.
- It is not aligned with column it goes out from the column.

Image attached for more References

**Comment by junedchhipa** [comment]
I am unable to reproduce this with your provided code. Can you please provide a [codepen](https://codepen.io/apexcharts/pen/xYqyYm)?

**Comment by junedchhipa** [comment]
Closing due to no response.
