### ISSUE TITLE
tickAmount behaves inconsistently on area chart with two Y series

### ISSUE THREAD

**Issue by caracabe** [apexcharts/apexcharts.js#1623]
# Bug report

## Codepen

https://codepen.io/caracabe/pen/xxwmELB

## Explanation

- What is the behavior you expect?
  - I expect the tickAmount to apply consistently to all views (both series of data or either separately)
- What is happening instead?
  - When tickAmount is set to 4 on the yaxis:
    - four segmentations of data are displayed when both series are viewed
    - series 1 alone shows 6 segmentations
    - series 2 alone shows 5 segmentations
  - When tickAmount is set to 5, all three views show 6 segmentations
- What error message are you getting?
  - n/a

**Comment by robertogonzalezdelarosa** [comment]
Hello

I was struggling with the same problem, but mine was a little more confusing. The thing is if you are going to share the same y-axis for two or more series you have to convert the y-axis to array of objects instead a single object.

the order as you put the series in the array must match with the order of the y-axis array and have to share the same seriesName property and the property tickAmount must be the same for both series 

I modified a little bit your code to make it work, I hope you find it useful


`var options = {
 chart: {
  toolbar: {
   show: false
  },
  background: '#222222',
  zoom: {
   enabled: false
  }
 },
 series: [{
   name: "Series2",
   type: 'line',
   data: [900, 954, 960, 975, 993, 1000, 1100, 1130, 160, 175, 180, 200]
  },
  {
   name: "Series1",
   type: 'line',
   data: [2000, 2300, 3400, 3500, 4600, 4700, 5800, 5900, 6000, 7100, 8200, 8500]
  }
 ],
 dataLabels: {
  enabled: false
 },
 stroke: {
  curve: 'straight'
 },
 labels: ["2020-04-19", "2020-04-20", "2020-04-21", "2020-04-22", "2020-04-23", "2020-04-24", "2020-04-25", "2020-04-26", "2020-04-27", "2020-04-28", "2020-04-29", "2020-04-30"],
 xaxis: {
  type: 'datetime',
  labels: {
   style: {
    colors: 'white'
   }
  }
 },
 yaxis: [{
  seriesName: 'Series1',
  opposite: true,
  labels: {
   style: {
    colors: 'white'
   }
  },

  tickAmount: 10
 }, {
  seriesName: 'Series1',
  opposite: true,
  show: true,
  labels: {
   style: {
    colors: 'white'
   }
  },
  tickAmount: 10
 }],
 legend: {
  horizontalAlign: 'center',
  position: 'top',
  fontSize: '11px',
  fontWeight: 400,
  labels: {
   colors: 'white'
  }
 },
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();`






my english is terrible i know LOL

**Comment by robertogonzalezdelarosa** [comment]
var options = {
 chart: {
  toolbar: {
   show: false
  },
  background: '#222222',
  zoom: {
   enabled: false
  }
 },
 series: [{
   name: "Series2",
   type: 'line',
   data: [900, 954, 960, 975, 993, 1000, 1100, 1130, 160, 175, 180, 200]
  },
  {
   name: "Series1",
   type: 'line',
   data: [2000, 2300, 3400, 3500, 4600, 4700, 5800, 5900, 6000, 7100, 8200, 8500]
  }
 ],
 dataLabels: {
  enabled: false
 },
 stroke: {
  curve: 'straight'
 },
 labels: ["2020-04-19", "2020-04-20", "2020-04-21", "2020-04-22", "2020-04-23", "2020-04-24", "2020-04-25", "2020-04-26", "2020-04-27", "2020-04-28", "2020-04-29", "2020-04-30"],
 xaxis: {
  type: 'datetime',
  labels: {
   style: {
    colors: 'white'
   }
  }
 },
 yaxis: [{
  seriesName: 'Series1',
  opposite: true,
  labels: {
   style: {
    colors: 'white'
   }
  },

  tickAmount: 10
 }, {
  seriesName: 'Series1',
  opposite: true,
  show: true,
  labels: {
   style: {
    colors: 'white'
   }
  },
  tickAmount: 10
 }],
 legend: {
  horizontalAlign: 'center',
  position: 'top',
  fontSize: '11px',
  fontWeight: 400,
  labels: {
   colors: 'white'
  }
 },
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
