### ISSUE TITLE
Incorrect color for tooltip

### ISSUE THREAD

**Issue by tipputhynhean** [apexcharts/apexcharts.js#1624]
# Bug report
On the chart, it's showing yellow tooltip on top of blue line.
![image](https://user-images.githubusercontent.com/20786858/82441593-5b0df700-9ac8-11ea-912e-8b496c492214.png)

## Codepen
https://codesandbox.io/s/apx-area-irregular-timeseries-6o7cz

This can also be seen on the site demo: https://apexcharts.com/javascript-chart-demos/area-charts/irregular-timeseries/

## Explanation

- What is the behavior you expect?
  Tooltip color should be the same as the line
- What is happening instead?
  Different color is showing
- What error message are you getting?
  No error message

**Comment by junedchhipa** [comment]
Missed it as it happens only on Firefox. Thanks for reporting.

**Comment by t-o-o-m** [comment]
Still doesn't work for me.
See 
![grafik](https://user-images.githubusercontent.com/29979066/86625024-aae74580-bfc4-11ea-922d-c8ca73b53310.png)
Screenshot taken from https://apexcharts.com/javascript-chart-demos/line-charts/dashed/

**Comment by tlloydukdev** [comment]
confirmed, still happening for me too
