### ISSUE TITLE
Apex charts dataLabel styling is not working

### ISSUE THREAD

**Issue by hussein661** [apexcharts/apexcharts.js#1625]
## Codepen
I want to add a style for those dataLabels.

![donut-datalabels](https://user-images.githubusercontent.com/43033301/82460597-0c5d5e80-9ac2-11ea-8e32-af417b146c12.png)

**I tried out this as mentioned in the docs**

```
options : {
...
 dataLabels: {
  enabled: true,
  enabledOnSeries: undefined,
  formatter: function (val, opts) {
      return val
  },
  textAnchor: 'middle',
  distributed: false,
  offsetX: 0,
  offsetY: 0,
  style: {
      fontSize: '14px',
      fontFamily: 'Helvetica, Arial, sans-serif',
      fontWeight: 'bold',
      colors: undefined
  },
  background: {
    enabled: true,
    foreColor: '#fff',
    padding: 4,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#fff',
    opacity: 0.9,
    dropShadow: {
      enabled: false,
      top: 1,
      left: 1,
      blur: 1,
      color: '#000',
      opacity: 0.45
    }
  }
  },
...
}
```
both style and background are not working !!

**Comment by junedchhipa** [comment]
It seems background for the pie/donut labels doesn't work in pie/donut charts.

For the forecolors, you can try
```javascript
dataLabels: {
  style: {
    colors: ['#111', '#555', '#999']
  }
}
```

**Comment by hussein661** [comment]
@junedchhipa  styles colors is working. (only colors).
what to do to change the background color,borderRadius,add icons or links ?!

**Comment by junedchhipa** [comment]
As I said, background isn't working for pie/donut data-labels.
It will be addressed soon.

**Comment by jfayad** [comment]
hello @junedchhipa It's not really clear if that is a bug or a new feature ?

According to the doc. it seems that this should be working so this issue seems like a bug to me. If that's the case, shouldn't this issue stay open till the bug is addressed and merged ?

Thanks

**Comment by napomj** [comment]
Does dataLabels styling also not work on TreeMaps? I cannot get it to work.

It would be helpful to have specification for which Charts the styling works for. It's nice there's lots of configuration options but if it were separated into each category based on which chart is being used then that would be great.

**Comment by ayami123** [comment]
Same issue, it is still not working

**Comment by WaelWafik** [comment]
This is really silly, I spent hours debugging the JS though the problem was very simple the CSS overrides the Colors in the JS so when you have your graph DIV make sure it looks like this 
 <div id="line_chart_datalabel" dir="ltr"></div>
not like this
<div id="line_chart_datalabel" class="apex-charts" dir="ltr"></div> 

so the theme default doesn't overrides your settings by applying the class apex-charts

**Comment by WaelWafik** [comment]
> Same issue, it is still not working
> 
> the styling of datalabels it still gray =_=
> 
> no matter what I changed ![image](https://user-images.githubusercontent.com/17733287/168429713-b3bd9a3f-26a6-47e5-a622-eb94cbff9cb1.png)
> 
> > this.pieChartOptions = {
> > chart: {
> > type: 'pie',
> > height: 320
> > },
> > colors: themeColors,
> > labels: labels,
> > series: series, //must be the total quantity
> > legend: {
> > itemMargin: {
> > horizontal: 2
> > },
> > },
> > dataLabels: {
> > style: {
> > fontSize: '14px',
> > fontFamily: 'Helvetica, Arial, sans-serif',
> > fontWeight: '1',
> > colors: ['#40C057', '#40C057', '#40C057']
> > },
> > dropShadow: {
> > enabled: false,
> > top: 1,
> > left: 1,
> > blur: 1,
> > color: '#40C057',
> > opacity: 0.45
> > },
> > },
> > responsive: [{
> > breakpoint: 576,
> > options: {
> > chart: {
> > width: 300
> > },
> > legend: {
> > position: 'bottom'
> > }
> > }
> > }]
> > }`
> 
> ```
> Whatever color I change its the same
> gray
> ```
> 
> Is this bug of angular or yours ?

This is really silly, I spent hours debugging the JS though the problem was very simple the CSS overrides the Colors in the JS so when you have your graph DIV make sure it looks like this
not like this

so the theme default doesn't overrides your settings by applying the class apex-charts

**Comment by nizzam** [comment]
this issues has been fixed or not ?
what is the workaround ?

**Comment by kevin4dhd** [comment]
any solution?

**Comment by importjeremy** [comment]
> ## Codepen
> I want to add a style for those dataLabels.
> 
> ![donut-datalabels](https://user-images.githubusercontent.com/43033301/82460597-0c5d5e80-9ac2-11ea-8e32-af417b146c12.png)
> 
> **I tried out this as mentioned in the docs**
> 
> ```
> options : {
> ...
>  dataLabels: {
>   enabled: true,
>   enabledOnSeries: undefined,
>   formatter: function (val, opts) {
>       return val
>   },
>   textAnchor: 'middle',
>   distributed: false,
>   offsetX: 0,
>   offsetY: 0,
>   style: {
>       fontSize: '14px',
>       fontFamily: 'Helvetica, Arial, sans-serif',
>       fontWeight: 'bold',
>       colors: undefined
>   },
>   background: {
>     enabled: true,
>     foreColor: '#fff',
>     padding: 4,
>     borderRadius: 2,
>     borderWidth: 1,
>     borderColor: '#fff',
>     opacity: 0.9,
>     dropShadow: {
>       enabled: false,
>       top: 1,
>       left: 1,
>       blur: 1,
>       color: '#000',
>       opacity: 0.45
>     }
>   }
>   },
> ...
> }
> ```
> 
> both style and background are not working !!

I was also having this issue with the pie chart. After I added the following style to my page:

```css
.apexcharts-pie text {
     fill: revert-layer;
}
```
 I was able to configure the label color using dataLabels.style.colors in my chart component.

```javascript
dataLabels: {
  style: {
    colors: ['...'],
  },
}
```
This was using version 3.54.1

**Comment by Kody458** [comment]
Still not working...

**Comment by can-guven** [comment]
not working...
