### ISSUE TITLE
multiline text in axes labels is bugged

### ISSUE THREAD

**Issue by josezu** [apexcharts/apexcharts.js#1628]
I was reading whole documentation and i dont get fix to this issue..

I dont know why it didnt work, if you can help me, thx

![categories-bug](https://user-images.githubusercontent.com/10341806/82633146-051c7a80-9bc0-11ea-9e03-f6e32b97f37e.jpg)

![bug-reported](https://user-images.githubusercontent.com/10341806/82633083-e0c09e00-9bbf-11ea-9695-b990dc76538a.jpg)

**Comment by junedchhipa** [comment]
Can you please post a [codepen](https://codepen.io/apexcharts/pen/xYqyYm) demo of the issue you're facing?

**Comment by dcrystalj** [comment]
@junedchhipa 
https://codepen.io/dcrystalj/pen/JjwmRbX

looks like bug is on fontSize setting.
