### ISSUE TITLE
Encoding in a csv document

### ISSUE THREAD

**Issue by Holenvik** [apexcharts/apexcharts.js#1629]
I have an issue with my downloaded csv document from chart
I think the problem with encoding, I didn't try to use chart data in English, coz all data in my chart in Russian

This is my chart:
![image](https://user-images.githubusercontent.com/38699425/82661291-68e08b00-9c34-11ea-83ed-b30276660066.png)

Downloaded CSV document:
![image](https://user-images.githubusercontent.com/38699425/82661372-8e6d9480-9c34-11ea-84d0-b0ea3a64b272.png)

But I can open it in a notepad in Windows and all will be okay
![image](https://user-images.githubusercontent.com/38699425/82661449-b65cf800-9c34-11ea-96bc-adb69ee26819.png)

**Comment by junedchhipa** [comment]
Can you please create a codepen so I can easily reproduce?

**Comment by Holenvik** [comment]
> Can you please create a codepen so I can easily reproduce?

Yep, check link below
[codepen](https://codepen.io/holenvik/pen/RwrrZWB)

**Comment by Holenvik** [comment]
> Can you please create a codepen so I can easily reproduce?

Did you check example

**Comment by nam98nd16** [comment]
I'm facing the same problem with Japanese.

**Comment by Holenvik** [comment]
Up

**Comment by soyaMonkey** [comment]
Is this issue resolved? I'm facing the same problem with Korean...

**Comment by waveciou** [comment]
I'm facing the same problem with Traditional Chinese.
