### ISSUE TITLE
Interactive functionallity is broken when using datetime values

### ISSUE THREAD

**Issue by SWW13** [apexcharts/apexcharts.js#1637]
# Bug report

## Codepen

Codepen doens't allow unregistered saves / shares, so here is the changed JS part (can be copied into [this codepen](https://codepen.io/apexcharts/pen/bxzgZJ)):
```
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "line"
  },
  xaxis: {
    type: 'datetime'
  },
  series: [
    { 
      name: 'series-1',
      data: [
        [new Date('2020-01-01'), 30],
        [new Date('2020-01-02'), 40],
        [new Date('2020-01-03'), 35],
        [new Date('2020-01-04'), 50],
        [new Date('2020-01-05'), 49],
        [new Date('2020-01-06'), 60],
        [new Date('2020-01-07'), 70],
        [new Date('2020-01-08'), 91]
      ]
    },
    {
      name: 'series-2',
      data: [
        [new Date('2020-01-01'), 35],
        [new Date('2020-01-02'), 45],
        [new Date('2020-01-03'), 35],
        [new Date('2020-01-04'), 55],
        [new Date('2020-01-05'), 49],
        [new Date('2020-01-06'), 65],
        [new Date('2020-01-07'), 75],
        [new Date('2020-01-08'), 91]
      ]
    }
  ]
};
var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
```

**Note:** other variations to specify the data series such as an `Object` with `x` and `y` also don't work.

## Explanation
- What is the behavior you expect?
I can use the interactive functions such as the `home` button or the hiding data series (click on the bottom label) function when using series with a datetime.

- What is happening instead?
The data is only shown once and vanishes on any interaction.
![apexcharts-fresh](https://user-images.githubusercontent.com/1280142/82841379-1cb47580-9ed6-11ea-904e-35e7a2bfe087.png)
![apexcharts-vanished](https://user-images.githubusercontent.com/1280142/82841381-1f16cf80-9ed6-11ea-90dc-70554930d1a5.png)

- What error message are you
 getting?
No error as far as i can see.

**Comment by junedchhipa** [comment]
You should either provide a timestamp or a date string instead of providing a JavaScript date object.

So, to convert your date to timestamp, you can just do `new Date('2020-01-01').getTime()` or you can simply ignore everything and just provide a date string `2020-01-01`

Below are valid ways
```javascript
data: [
  [new Date('2020-01-01').getTime(), 30],
  [new Date('2020-01-02').getTime(), 40],
  [new Date('2020-01-03').getTime(), 35],
  [new Date('2020-01-04').getTime(), 50],
  [new Date('2020-01-05').getTime(), 49],
  [new Date('2020-01-06').getTime(), 60],
  [new Date('2020-01-07').getTime(), 70],
  [new Date('2020-01-08').getTime(), 91]
]
```

OR

```javascript
data: [
  ['2020-01-01', 40],
  ['2020-01-02', 34],
  ['2020-01-03', 24]
]
```

**Comment by ricky11** [comment]
if the user zooms in or zooms out to view dates by day, hour or minutes, will the y values data be combined according to the date?
