### ISSUE TITLE
xaxis.labels.formatter does not work when xaxis.type set to 'datetime'

### ISSUE THREAD

**Issue by XAHTEP26** [apexcharts/apexcharts.js#164]
[Demo on Codepen](https://codepen.io/XAHTEP26/pen/dgmOjW)

If I comment out the line `type: 'datetime'`, the formatter will work.

I also noticed that when xaxis.type is set to 'datetime' the points on the graph do not coincide with the points on the x axis.

P. S. Sorry for my English

**Comment by junedchhipa** [comment]
Thank you for reporting. Yes, the formatter doesn't work when xaxis.type is datetime.
Just fixed it.

And, when you set the xaxis.type to datetime, the points on the yaxis are not calculated based on the number of points. It is calculated based on the difference of dates between the left end of the x-axis and right end of the x-axis.
