### ISSUE TITLE
Is it possible stack and unstack or specific series 

### ISSUE THREAD

**Issue by shibins** [apexcharts/apexcharts.js#1642]
**Is your feature request related to a problem? Please describe.**	
I have graph with multiple types example Line and Bar charts . Now I would like enable    stacking for each type (preferably a category   ) .  so each type/category should start from 0

**Describe the solution you'd like**	
Should be able say start stack group by categories 

**Describe alternatives you've considered**	
None

**Additional context**	
 None

**Comment by junedchhipa** [comment]
Sorry, a mixture of stacked and unstacked graphs is not possible.
