### ISSUE TITLE
Toolbar can't be hidden in Area Charts.

### ISSUE THREAD

**Issue by b0y2k** [apexcharts/apexcharts.js#1644]
# Bug report
Firstly, thank you for a great charting tool :)

I am trying to hide the toolbar in an area spline chart and it's ignoring the toolbar:show option.
I am using the vue component but i have also tried it in vanilla and the results are the same.

## Codepen
https://codepen.io/b0y2k/pen/xxwoeWR

**Comment by junedchhipa** [comment]
The `toolbar` is a nested property which should go under `chart`.

```javascript
chart: {
  height: 350,
  type: "area",
  toolbar: {
    show: false,
  }
}
```
