### ISSUE TITLE
Convert Date from Unix Time Stamp when exporting CSV

### ISSUE THREAD

**Issue by paullegrand** [apexcharts/apexcharts.js#1647]
**Is your feature request related to a problem? Please describe.**	
When I try to export CSV content that uses a date as the "x" value, it leaves the date in the Unix Time Stamp instead of converting it to a date for excel or other csv software to parse.

**Describe the solution you'd like**	
Either A) it converted Unix timestamps to a different date format that is compatible with Excel, or B) the ability to pass a formatting function that the data would be filtered through on export

**Describe alternatives you've considered**	
I've considered converting the timestamps to a string and passing that as the "x" value instead of the timestamp

**Additional context**	
Example Chart: 
![image](https://user-images.githubusercontent.com/20803574/83429073-81edf680-a401-11ea-8e7d-67da7310fc81.png)

What the CSV currently shows:
![image](https://user-images.githubusercontent.com/20803574/83429103-89ad9b00-a401-11ea-95a2-c234893cc973.png)

What I would like the CSV to show:
(I used the excel formula `=(SOURCE_CELL  / 86400 / 1000) + DATE(1970,1,1)` if that helps
![image](https://user-images.githubusercontent.com/20803574/83429287-d2655400-a401-11ea-9afe-72c160da3ee1.png)

**Comment by junedchhipa** [comment]
Added `chart.toolbar.export.csv.dateFormatter` function.

**Comment by paullegrand** [comment]
Thank you @junedchhipa!
