### ISSUE TITLE
[BUG] Pie chart update only after window resize

### ISSUE THREAD

**Issue by eposwiatny** [apexcharts/apexcharts.js#1648]
Hello,

Today I noticed small bug in Apexchart. 

I used Pie chart in my project and everything works fine. The only issue was chart updating. When I'm passing new value to :options, I don't see new value in chart. 

Chart update when I resize browser window or on div size change. 

I'm using Vue apex chart v.1.5.3

**Comment by eposwiatny** [comment]
I used 
this.series[0] = 10 
instead of 
this.series = [10]

**Comment by claudiusnascimento** [comment]
@eposwiatny , before you update de chart values, destroy chart!

```
try {
            chart.destroy();
     } catch (error) {}
```

**Comment by sergioLemon** [comment]
Me pasa en angular
