### ISSUE TITLE
when clicking to pie chart plot, get the clicked plot id.

### ISSUE THREAD

**Issue by Dakshinads** [apexcharts/apexcharts.js#1649]
can this requirement in this version?

**Comment by Dakshinads** [comment]
can this requirement in this version?

**Comment by junedchhipa** [comment]
Can you please elaborate on what are you trying to achieve?

**Comment by Dakshinads** [comment]
when clicking the pie chart one plot, showing the plot-related Label on alert or whatever. Actually  I want to drill-down when clicked the pie chart, showing clicking plot-related data popup another chart. How to do it? 
Thank you.

**Comment by Dakshinads** [comment]
I am using legendclick event to elaborate my requirement.
Thank You.

**Comment by junedchhipa** [comment]
```javascript
chart: {
  events: {
    legendClick: function(chartContext, seriesIndex, config) {
      console.log(seriesIndex)
    }
  }
},
```

**Comment by Esinel** [comment]
> ```js
> seriesIndex
> ```

Hi Juned, any idea why do i get -1 seriesIndex no matter which pie-slice i click?

**Comment by ARedmanDodd** [comment]
Is there a similar event for pie charts for when the user clicks on a pie segment itself rather than the legend? (It's more intuitive to click the pie rather than the legend).
