### ISSUE TITLE
Really weird error that i can't think of a proper issue title

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#165]
## Codepen

https://codepen.io/jimfilippou-the-animator/pen/yRKxLM

## Explanation

- What is the behavior you expect?
The chart to be rendered.

- What is happening instead?
The chart is not rendered

- What error message are you getting?
TypeError: a.globals.seriesNames[v].replace is not a function

I don't know where the error is happening since I'm using a minified version. This error fix is urgent since it breaks the chart (not a minor issue). Thanks in advance 😃

**Comment by junedchhipa** [comment]
You are inputting a numeric value for series name 😀 
Although, I have added a check now - you should pass a String there.

**Comment by jimfilippou** [comment]
Fixed on my end as well!
