### ISSUE TITLE
How disable box on hover?

### ISSUE THREAD

**Issue by darlandieterich** [apexcharts/apexcharts.js#1653]
Hi everyone!
How disable bottom and side box on hover in timeline? _(I don't know the name of these boxes)_

![disable box apex char](https://i.imgur.com/qTfysFP.png)

**Comment by junedchhipa** [comment]
```javascript
xaxis: {
  tooltip: {
    enabled: false
  }
},
yaxis: {
  tooltip: {
    enabled: false
  }
}
```
