### ISSUE TITLE
datalabels background custom

### ISSUE THREAD

**Issue by walnut02** [apexcharts/apexcharts.js#1655]
I want to put the datalabel on the background image. I can only change the background color in the Option, but can't I use the background image? I want to make it look like a reference image. 

![aaa](https://user-images.githubusercontent.com/65809299/83707282-95dd6680-a654-11ea-9e42-a782e6471f0c.png)

**Comment by junedchhipa** [comment]
Sorry, you cannot use a background-image behind a data label. There is no easy way to achieve it.
