### ISSUE TITLE
Get current Y-Axis Hovered Value

### ISSUE THREAD

**Issue by KarmaBlackshaw** [apexcharts/apexcharts.js#1656]
I'm currently stuck on how to get the current  point Y data. I thought it was in the **chart events**, (hovered, click, etc...). I'm currently using the **mouseMove** event and is looking at the 3rd parameter **config**. But the y-axis value is not present.

To have a clear representation of what I'm trying to get, here a picture below. I'm trying to get y-axis label **0.6547**

![image](https://user-images.githubusercontent.com/40014179/83738452-ea013e80-a686-11ea-9865-dd79e73c3665.png)

I'm hoping that you can add a property of the hovered data for Y if not yet implement. I've already found the hovered data for X axis

**Update**
I have found a way to get Y data. Using `tooltip.y.formatter`, I'll just assign to a variable the last value the formatter received however, the value I'm receiving is inaccurate. And it changes based on when I move my cursor horizontally (based on x axis). 

**Another update**
I've found another way to get Y data. Using **yaxis.labels.formatter**. This is working for me now. But I still wish to put this in the `config` params in events.

**Comment by dIvYaNshhh** [comment]
yes, you can get the value from the config parameter only. For that, you need use your series data like below.
` events: {
            mouseMove: function(event, chartContext, config) {
              const points = dataXY[config.dataPointIndex];
            }
          }`
Where `dataXY` is a data array of your series. In that, you will get X and Y points.

I hope that will solve your problem.

**Comment by dfiorini** [comment]
> yes, you can get the value from the config parameter only. For that, you need use your series data like below.
> ` events: { mouseMove: function(event, chartContext, config) { const points = dataXY[config.dataPointIndex]; } }`
> Where `dataXY` is a data array of your series. In that, you will get X and Y points.
> 
> I hope that will solve your problem.

Hi, how can I select a specify chartContext ?
