### ISSUE TITLE
Problem with display on IE 11

### ISSUE THREAD

**Issue by fnnzzz** [apexcharts/apexcharts.js#1657]
IE11 has a number of problems with charts visualization:

- columns do not respect the y axis and climb on her (especially bad it looks on horizontal bar chart)
- X axis is shifted up

I attach screens with these problems, you can see it live at http://rabota.ua/prozora
![image](https://user-images.githubusercontent.com/3502507/83738957-a2b28800-a65d-11ea-978b-21837428fbf6.png)
![image](https://user-images.githubusercontent.com/3502507/83738972-a80fd280-a65d-11ea-8383-4b5d7188f96c.png)
![image](https://user-images.githubusercontent.com/3502507/83738985-aba35980-a65d-11ea-8fd7-7c2b1b8f7d6d.png)

**Comment by junedchhipa** [comment]
Have you followed the guidelines on how to make the charts compatible with IE11?
If you need to make it work with IE11, you need to include these polyfills before including ApexCharts

[promise-polyfill](https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js)
[classlist.js](https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill)

Docs - https://github.com/apexcharts/apexcharts.js#using-it-with-ie11

**Comment by fnnzzz** [comment]
yah, it worked, thank you very much.

I did not expect that in readme there will be tips on IE11, so I did not look there, litter for my carelessness. Thanks again!
