### ISSUE TITLE
Draw series combination of solid and dashed line

### ISSUE THREAD

**Issue by bishtNaveen** [apexcharts/apexcharts.js#1658]
I want to create line graph with combination of dashed and solid line as per x-axis zone wise, for example after 8 point there will dashed line, else solid line
Is This feature available in current version of Apex chart in Angular ? If yes then how ?
![combine-solid-and-dash-line](https://user-images.githubusercontent.com/20103440/83742304-e1a10780-a676-11ea-8bd4-a753c701722c.png)

**Comment by junedchhipa** [comment]
Sorry, but this is not possible with ApexCharts.

**Comment by Mihailoff** [comment]
+1

**Comment by sanchitd5** [comment]
+1

**Comment by quentingosset** [comment]
@junedchhipa is stop impossible or do we have a possibility now ?
