### ISSUE TITLE
Series based Colors

### ISSUE THREAD

**Issue by Chazza** [apexcharts/apexcharts.js#1659]
**Is your feature request related to a problem? Please describe.**	
I have 2 series, one for an individual and one for an organisation, It's frustating to see it alternating colours instead of using the desired colour per series (e.g. for a quick glimpse).

**Describe the solution you'd like**	
Allow us to specify colours per series, meaning quick chart glimpses show the colour and what it does.

**Describe alternatives you've considered**	
Keeping empty charts, but covers space.

**Additional context**	
https://i.imgur.com/k7Blsvr.png

**Comment by junedchhipa** [comment]
You can build your series this way to provide a color for individual data-point

```javascript
series: [
    {
      data: [
        {
          x: "2011",
          y: 1292
        },
        {
          x: "2012",
          y: 4432
        },
        {
          x: "2013",
          y: 5423,
          fillColor: "#EB8C87",
        },
        {
          x: "2014",
          y: 6653
        },
        {
          x: "2015",
          y: 8133,
          fillColor: "#EB8C87",
        },
        {
          x: "2016",
          y: 7132
        },
        {
          x: "2017",
          y: 7332
        },
      ]
    }
  ]
```
![8gk5bccsf](https://user-images.githubusercontent.com/17950663/83765037-4e78c980-a698-11ea-9d5b-d25f4df8ec18.png)


Full codepen example - https://codepen.io/apexcharts/pen/eYJmzJd?editors=0010

**Comment by Chazza** [comment]
@junedchhipa I use 2 different series, I thought setting the colour usually applies this to each series?

**Comment by junedchhipa** [comment]
Your screenshot doesn't seem like there are 2 series, there is 1 series with 4 data-points (although the legend is named differently than the series).

There is 1 more option - `plotOptions.bar.distributed: true` which applies different color to each data-point.
You may decide to use whatever option based on how the series is built.

**Comment by Chazza** [comment]
> 
> 
> Your screenshot doesn't seem like there are 2 series, there is 1 series with 4 data-points (although the legend is named differently than the series).
> 
> There is 1 more option - `plotOptions.bar.distributed: true` which applies different color to each data-point.
> You may decide to use whatever option based on how the series is built.

When I hover it shows a different colour, e.g. if I'm using stacked and certain elements don't have a value, it ends up messing up hover, even when I set a fillColor.
