### ISSUE TITLE
critical css issue - `hidden` class crashing my app

### ISSUE THREAD

**Issue by albanafmeti** [apexcharts/apexcharts.js#166]
- I am using `hidden` class in my code with `display: none`, and you are using it with `opacity: 0` without putting apexchart parent class or something else. This is crashing my app from normal behaviour.

![capture](https://user-images.githubusercontent.com/11160896/47253457-4d5b4000-d453-11e8-9563-8a287cf97040.PNG)

- You need to use `hidden` class there with an apexchart namespace. It should not affect other code.

**Comment by junedchhipa** [comment]
Ouch! I am sorry. 
Being a CSS nerd, I am surprised why I did that initially 😀 
I will fix that very soon, thanks for reporting

**Comment by junedchhipa** [comment]
No, I will release a patch update on npm in the next week.
Till then, you can use the GitHub [dist](https://github.com/apexcharts/apexcharts.js/tree/master/dist) files of the master branch which I updated couple of minutes ago.
