### ISSUE TITLE
Valid value between null values ​​is not rendered

### ISSUE THREAD

**Issue by pamelasouza** [apexcharts/apexcharts.js#1664]
# Valid value between null values ​​is not rendered

## Codepen

[this codepen](https://codepen.io/pamqk/pen/dyGowNw) 
example:
` [null],
   [valor],
   [null],
   [null],`

<img src="https://uploaddeimagens.com.br/images/002/695/138/original/Screen_Shot_2020-06-07_at_13.08.41.png?1591548256">
<img src="https://uploaddeimagens.com.br/images/002/695/141/original/Screen_Shot_2020-06-07_at_13.08.48.png?1591548388">

## Explanation

- What is the behavior you expect?
I expect it to render the line that contains value on the y-axis, even if it is between two null values

- What is happening instead?
Does not render, just passing the mouse.

- What error message are you getting?
No message

**Comment by junedchhipa** [comment]
As tested on v3.46.0, this is fixed
