### ISSUE TITLE
Using FillColors shows wrong Hover Color

### ISSUE THREAD

**Issue by Chazza** [apexcharts/apexcharts.js#1668]
# Bug report

## Codepen
https://codepen.io/ChazzaBoi/pen/LYGpMBX?editors=0011

## Explanation

As the colours have been set, and fill color per bar - it's showing the incorrect colour when hovering over, which in turn looks confusing to visitors.

**Comment by Chazza** [comment]
Bump

**Comment by junedchhipa** [comment]
Sorry for the delay.
Fixed it, a new version will be released very soon.

**Comment by Chazza** [comment]
Thank you lots!
