### ISSUE TITLE
Dark theme not properly supported for export

### ISSUE THREAD

**Issue by sauterl** [apexcharts/apexcharts.js#1669]
# Bug report

## Codepen

See [this codepen](https://codepen.io/sauterl/pen/eYJpbeE) to explore it yourself.

## Explanation

Basically the title:

When using the dark theme, PNG and SVG exports end up with a mix of dark and light theme, which renders them unusable. As far as I can tell, the main issue is the background being rendered white.

The resulting PNG download:

![actual](https://user-images.githubusercontent.com/1503249/84133421-7163fe80-aa47-11ea-93d9-c544a7d8819e.png)

The screenshot, hence expected behaviour:

![expected](https://user-images.githubusercontent.com/1503249/84133519-9193bd80-aa47-11ea-9400-a5234aba1792.png)

This happens for the SVG as well, however, using an SVG editor, one can post-process the font colors there.

**Comment by junedchhipa** [comment]
I confirm the issue. It will be addressed soon.
