### ISSUE TITLE
The bubble chart animation is running at every render

### ISSUE THREAD

**Issue by YakimchykNadzeya** [apexcharts/apexcharts.js#1670]
Hi!

I am using a Bubble chart with React UI.

The problem is that animation is running at every render, not only when the chart options or data have been updated.

Is it possible to make animaеion available only in case the chart itself has been updated?

Thanks a lot for your help!

Kind regards,
Nadzeya Yakimchyk.

**Comment by junedchhipa** [comment]
You're right. FIxed it.
