### ISSUE TITLE
Tooltips and menu doesn't work inside web-component

### ISSUE THREAD

**Issue by JonatasMonteiro** [apexcharts/apexcharts.js#1672]
# Bug report

## Codepen

Can't reproduce my environment in a codepen.

## Explanation

- What is the behavior you expect?

Well basically I'm using VueApexCharts in a project, and this project is then built as a Web-Component in another project. What I expected was that even using as a webcomponent, everything would work fine. It worked fine when I was just building for development, not as a web-component.

- What is happening instead?

What I've been able to notice is that the tooltips of each chart, and also the menu have stopped working. Meaning that hovering the chart doesn't show anything, and clicking on the menu won't open the download options.

- What error message are you getting?

There is no error message, it simply does not work.
- What I've tried:

Based on issue 42 from the [VueApexCharts](https://github.com/apexcharts/vue-apexcharts/issues/42) git page, I was able to fix the menu by adding an event listener to the click on the icon. But I'm lost to what would be the fix to the tooltip mouseover issue using this same strategy.

- Additional info:
Command to build the WC I've used: `vue-cli-service build --target wc --name project-name  --inline-vue`

**Comment by dazraf** [comment]
HI @JonatasMonteiro  did you figure out a resolution to this please? I'm having a similar issue but with attempting to embed ApexCharts within a LitElement component.
