### ISSUE TITLE
Reset/Home button doesn't work correctly and hide the data in candlestick chart.

### ISSUE THREAD

**Issue by MrMohamedAbdallah** [apexcharts/apexcharts.js#1679]
# Bug report.
The reset button should set the zoom value to it's original instead it hides the data.
This issue in the official website as well.
https://apexcharts.com/angular-chart-demos/candlestick-charts/basic/

![reset-issue](https://user-images.githubusercontent.com/51543900/84374197-f254fe80-abdd-11ea-8bd6-19ff9683bc2c.gif)

**Comment by junedchhipa** [comment]
Thanks for reporting the issue, it will be addressed soon.
