### ISSUE TITLE
Cannot set rgba color nor opacity for particular data in line chart

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#168]
https://codepen.io/anon/pen/BqPbMP

In order to dim/highlight particular data in a chart we need to increase transparency of such lines. 

When applying a color in `rgba` format the lines appear gray on the chart, although such colors appear correctly in legend and tooltip.

```
  colors: [
    'rgba(42, 158, 251, .3)'
  ],
```

**Comment by junedchhipa** [comment]
If it works in legend, then I need to take a look why it doesn't work for paths.

**Comment by junedchhipa** [comment]
This [commit](https://github.com/apexcharts/apexcharts.js/commit/a71533101c06dfeea897848f658b15586f8f846f) fixes it.
Now, colors will accept rgba
