### ISSUE TITLE
Wraping of long text doesnt work in apexchart

### ISSUE THREAD

**Issue by Hurmatullah** [apexcharts/apexcharts.js#1683]
Wraping of long text doesnt work in apexcharts ? 
How to solve this ?

![error](https://user-images.githubusercontent.com/31663895/84491413-5b2d8c80-ac59-11ea-8648-dbec631f87d4.PNG)

My Code : 
    xaxis: {
      categories: [
        'Apples',
        'Strawberries',
        'Pineapples',
        ["Sugar","Baby", "Watermelon"],
        ['Prickly', 'Pear'],
        'Pears',
        ['Quararibea', 'cordata'],
        'Pomegranates',
        'Tangerines'
      ],
      labels: {
        style: {
          colors: colors,
          fontSize: '14px',
          cssClass : '.apexcharts-margin'
        },
        show: true,
        rotate: 0,
        rotateAlways: true,
        minHeight: 100,
        maxHeight: 2000,
      },
    }

**Comment by junedchhipa** [comment]
The below x-axis configuration worked fine

```javascript
  xaxis: {
    categories: [
      "Apples",
      "Strawberries",
      "Pineapples",
      ["Sugar", "Baby", "Watermelon"],
      ["Prickly", "Pear"],
      "Pears",
      ["Quararibea", "cordata"],
      "Pomegranates",
      "Tangerines"
    ],
    labels: {
      style: {
        fontSize: "11px",
        cssClass: ".apexcharts-margin"
      },
      hideOverlappingLabels: false,
      show: true,
      rotate: 0,
      rotateAlways: false,
      minHeight: 100,
      maxHeight: 2000
    }
  }

```

Full example - https://codepen.io/apexcharts/pen/VweaBYL

**Comment by Hurmatullah** [comment]
I did but still doesnt work fine 
![bug](https://user-images.githubusercontent.com/31663895/84561662-3261d180-ad03-11ea-935d-3aff2bb64fde.PNG)
