### ISSUE TITLE
why one label showing black colour and other labels are white colour?

### ISSUE THREAD

**Issue by Dakshinads** [apexcharts/apexcharts.js#1684]
Same issue in pie chart and donut chart
![pie chart issue](https://user-images.githubusercontent.com/53216423/84627557-c2229e00-af04-11ea-8a32-001cb8647147.png)

**Comment by junedchhipa** [comment]
Can you create a codepen so I can reproduce the issue easily?

**Comment by Dakshinads** [comment]
https://codepen.io/dakshina/pen/wvMzPYq?editors=0001
