### ISSUE TITLE
Gaps in stacked bar chart. 

### ISSUE THREAD

**Issue by FollowJack** [apexcharts/apexcharts.js#1686]
# Bug report

![image](https://user-images.githubusercontent.com/7950343/84781112-b60f0d00-afe6-11ea-8e1b-c4e1ad43fe25.png)

## Codepen
https://codepen.io/yoro123/pen/qBbaJgy

## Explanation

- What is the behavior you expect?
When deselecting 2 or more of the categories from the legend, I would expect to have stacked columns without gaps in between.
Also when hovering over the deselected area it seems to miss always one of the categories from the legend. That definitely is a bug. 

- What is happening instead?
While deselecting Product A and B there is a gap in between.

- What error message are you getting?
None

Is this possible to have a fix for this? 
May there be an option I did not see.

**Comment by junedchhipa** [comment]
Fixed it, thanks for reporting.
A new release will be published soon.
