### ISSUE TITLE
Add custom text on radialBar Chart

### ISSUE THREAD

**Issue by lsjzzang17** [apexcharts/apexcharts.js#169]
Hi I do not speak English well but this radialBar has been used so beautifully
This radialBar is very good.
So, i used my project.
i need radialBar xaxis So, i tried
Where is xaxis on radialBar ?

plz, your answer
 thank you

![default](https://user-images.githubusercontent.com/29587169/47327937-fbf8be00-d6a9-11e8-8fbf-d30311e32449.jpg)

**Comment by junedchhipa** [comment]
There is no direct option to draw labels as you described in the image.

But, you can use ApexChart's `addText()` method to draw custom text elements on chart area.
Here is a c[odepen example](https://codepen.io/apexcharts/pen/VEGyGx) which produces this result.
![screen shot 2018-10-23 at 11 41 33 am](https://user-images.githubusercontent.com/17950663/47339359-9fe96600-d6b8-11e8-8dc8-215a1bc5a0bc.png)

The code for generating these labels
```javascript

var chartAreaBounds = chart.w.globals.dom.baseEl.querySelector('.apexcharts-inner').getBoundingClientRect();

chart.addText({
  x: chartAreaBounds.width / 2,
  y: 10,
  text: "0",
  fontSize: 16,
  textAnchor: "middle"
});

chart.addText({
  x: chartAreaBounds.width - 5,
  y: chartAreaBounds.height / 2 + 10,
  text: "90",
  fontSize: 16,
  textAnchor: "start"
});

chart.addText({
  x: chartAreaBounds.width / 2,
  y: chartAreaBounds.height + 30,
  text: "180",
  fontSize: 16,
  textAnchor: "middle"
});

chart.addText({
  x: 5,
  y: chartAreaBounds.height / 2 + 10,
  text: "270",
  fontSize: 16,
  textAnchor: "end"
});

```

**Comment by suhailkc** [comment]
@junedchhipa 

I have tried your answer. but I got an error: (in codepen example also)

`chart.addText is not a function`

Is there any solution to this?

**Comment by EduardChernyak** [comment]
Hi @junedchhipa,

I have the same problem with the latest release.

**Comment by dfiorini** [comment]
> @junedchhipa
> 
> I have tried your answer. but I got an error: (in codepen example also)
> 
> `chart.addText is not a function`
> 
> Is there any solution to this?

I don't see anything either in the codepen example
