### ISSUE TITLE
Getting rid of the useless space on the left of a chart

### ISSUE THREAD

**Issue by simonc** [apexcharts/apexcharts.js#1694]
Hi! 👋 

I'm trying to get rid of the space added to the left of a bar chart. I tracked it down to the apexcharts-inner element being translated but I didn't find why this was happening and how to get rid of it.

You can find a JS Bin example here: https://jsbin.com/quyutarori/edit?html,output

Is there any way to have the chart without any space around, be it top, sides or bottom?

Thanks! ❤️

**Comment by junedchhipa** [comment]
You can play with the following configuration to adjust the left padding of the chart

```
grid: {
  padding: {
    left: -15
  }
}
```

**Comment by simonc** [comment]
@junedchhipa Ok thank you! Is that left space an expected behavior when the yAxis is hidden?
