### ISSUE TITLE
tickAmount issue in Safari

### ISSUE THREAD

**Issue by igsm** [apexcharts/apexcharts.js#1695]
# Bug report

## Codepen
https://codepen.io/igsm/pen/jOWBwgB

## Explanation
tickAmount property of xAxis is ignored in Safari. I checked Chrome and Firefox and it seems to work as expected.

Here are again screenshots of the issue I face in my app due to this bug.

How it should be (tickAmount set to 25)
<img width="967" alt="Screenshot 2020-06-21 at 14 59 34" src="https://user-images.githubusercontent.com/12541683/85226241-dcfa8400-b3d6-11ea-8b1a-c303af56891c.png">

How it is in Safari (tickAmount set to 25)
<img width="968" alt="Screenshot 2020-06-21 at 15 00 02" src="https://user-images.githubusercontent.com/12541683/85226243-dec44780-b3d6-11ea-8b69-068d09685f5a.png">

**Comment by nplaviola** [comment]
I am having a similar issue except the tick amounts don't work in **Chrome**, but do work in FF and Safari

**Comment by nplaviola** [comment]
@igsm I managed to fixed my issue by adding the following setting to the xAxis options:
```
xaxis: {
    type: 'numeric',
    tickAmount: 7
},
```

Hopefully that does the trick for you

**Comment by igsm** [comment]
> @igsm I managed to fixed my issue by adding the following setting to the xAxis options:
> 
> ```
> xaxis: {
>     type: 'numeric',
>     tickAmount: 7
> },
> ```
> 
> Hopefully that does the trick for you

Thank you. That worked for me too.

**Comment by igsm** [comment]
Now, with formatter and numeric type, all works as expected:
`formatter: val => Math.floor(Number(val)).toString()`
