### ISSUE TITLE
setting stacktype to '100%' when using stacked bar graphs will result in no % being shown if value is 1 or 2

### ISSUE THREAD

**Issue by willparky93** [apexcharts/apexcharts.js#1698]
# Bug report

## Codepen
https://codepen.io/willparky93/pen/RwrpeOM

## Explanation

In our stacked graphs; any paired value that has [1,0], [2,0], [1,1] ,[2,2] (and the variations between) fail to show the % on the chart.

For example, in my codepen we should expect 2011 Q1 to be displaying 50%, 50% but because the values are 1 and 1, it doesnt want to display. It should display like 2012 Q4. Likewise with 2011 Q2. This should show 100% like it does in 2012 Q1, but it's actually displaying no %

Not getting any error messages from what I can tell. Only happens with 1's and 2's.

**Comment by willparky93** [comment]
Hi guys, do you have an update on this?

**Comment by chlxorhkd123** [comment]
I also had a problem, but it was solved.
plotOptions bar option add hideOverflowingLabels false option
