### ISSUE TITLE
If one item data is very small, it will be ignored

### ISSUE THREAD

**Issue by fundon** [apexcharts/apexcharts.js#17]
See https://codepen.io/fundon/pen/bjjedz

**Comment by junedchhipa** [comment]
It is not ignored, but the 1px stroke makes it look like it doesn't exist.
I removed the stroke, and I can see the tiny value
https://codepen.io/apexcharts/pen/PBBmMa

**Comment by junedchhipa** [comment]
I have removed the rounding of the values when calculating angles. This will fix the percentage calculations
