### ISSUE TITLE
X-axis label is missing for first column from a 12 month data set.

### ISSUE THREAD

**Issue by LifeSource** [apexcharts/apexcharts.js#1702]
# Bug report

## Codepen
[codepen](https://codepen.io/LifeSource/pen/ZEQyEyb)

## Explanation

- What is the behavior you expect?
The first column's (January) data label is missing in this 12 months data set.

- What is happening instead?
Only the first label is missing, rest is working fine.

- What error message are you getting?
No errors.

Something to note:

- Changing the first value to **2019-01-01** but other values like 2019-01-03 (Jan 02.... onwards) does not. This is not ideal if this data is coming from an API or some other external database.

Apexcharts version used:

Codepen version and also **v3.19.2** minified version via CDN

**Comment by junedchhipa** [comment]
It's expected behavior because, for **Jan' 19** to be printed precisely, it has to be the first day of the month.
A quick fix would be to set the x-axis.min

```javascript
xaxis: {
  type: 'datetime',
  min: new Date('2019-01-01').getTime()
},
```
