### ISSUE TITLE
reverseNegativeShade = true results in only dark shading

### ISSUE THREAD

**Issue by gregorycarter** [apexcharts/apexcharts.js#1704]
Hello, firstly thank you for the awesome charts library.  I love ApexCharts!

# Bug report

## Codepen

https://codepen.io/gregorycarter/pen/mdVwXEP

## Explanation

- What is the behavior you expect?

When reverseNegativeShade: true, more negative colours should receive a darker shade, and less negative numbers should receive a lighter shade.

- What is happening instead?

All cells receive the same maximum dark shade, regardless of value.

<img width="680" alt="Screenshot 2020-06-25 at 11 36 24" src="https://user-images.githubusercontent.com/46213/85704701-70ce9780-b6d8-11ea-9433-837b53dc1b07.png">

- What error message are you getting?

No error message.

Thanks

**Comment by JoeyChuuichi** [comment]
Also found the same problem. 
Have you solved it?

**Comment by gregorycarter** [comment]
> Also found the same problem.
> Have you solved it?

No, I'm running the latest version (3.20.0) and the incorrect behaviour is still there.

I assume it is something to do with [the logic in here](https://github.com/apexcharts/apexcharts.js/blob/7174742055cfcaa5ff1012110a6689f2b5c61aaa/src/charts/HeatMap.js#L84), but I'm no JS expert and so not sure how to go about debugging this.

**Comment by idanamit** [comment]
I'm also experiencing this issue.
Have you got a solution?

**Comment by idanamit** [comment]
After a bit of investigating I've found out that this bug was created on version 3.15.6 as the previous version 3.15.5 has this behavior working as intended

**Comment by sureshd21** [comment]
if (w.config.plotOptions[chartType].reverseNegativeShade) {
    if (colorProps.percent < 0) {
                  colorShadePercent = (_**1 +**_ colorProps.percent / 100) * (shadeIntensity * 1.25);
                }

1+ is missing in the colorProps.percent to generate colorShadePercent for negative numbers. its working fine after made this change.

**Comment by idanamit** [comment]
Can you maybe create a PR with this fix @sureshd21?
It might get added in the next version

**Comment by dfiorini** [comment]
Hi, how can I change edge color of heatmap squares ?

**Comment by dvdvck** [comment]
> Hi, how can I change edge color of heatmap squares ?

by setting: 
```
...
plotOptions: {
  heatmap: {
    useFillColorAsStroke: false,
  }
},
stroke: {
  colors: ['hexcolor'],
},
...
```
