### ISSUE TITLE
Apexchart Pie - Combining Small Slices into "Other"

### ISSUE THREAD

**Issue by hnc01** [apexcharts/apexcharts.js#1705]
We started using ApexChart recently to create all the graphs on our reporting platform. We were using another library before and it had a nice feature where we could set a percentage threshold and the library would automatically combine all the slices under that threshold into 1 slide and label it as "Other".

This featured is mentioned in one of your blogs: https://apexcharts.com/tag/pie-chart/

However, it's not mentioned anywhere in the documentation. Can anyone tell me how to achieve the combined effect in a pie chart?

**Comment by junedchhipa** [comment]
The feature is not available in ApexCharts, the blog article is just a recommendation you can follow.
You will have to calculate the grouped totals and manually create the series/labels.

Here's a full example - https://codepen.io/apexcharts/pen/rNxzBKP

**Comment by mohammad-aqajani** [comment]
any automated way to group only small slices if pie chart is over capacity?
