### ISSUE TITLE
Grouped bar chart zero value gap issues

### ISSUE THREAD

**Issue by royallsilwallz** [apexcharts/apexcharts.js#1708]
![image](https://user-images.githubusercontent.com/51167861/85830482-65e53700-b7ac-11ea-95bd-414447ecdcfa.png)

I made a grouped bar chart that has some data values equivalent to zero which creates unusual gap between the bars. Is there any way to remove the gaps that has value 0 without violating the categories?

**Comment by junedchhipa** [comment]
Unfortunately, there is no way to remove the gaps for 0 values.

**Comment by HugoP27** [comment]
Hi, I'm stuck with the same issue, did you find any solution?

**Comment by Rao-Mudasir** [comment]
any update

**Comment by windoo2809** [comment]
any update
