### ISSUE TITLE
Add option to always show legend

### ISSUE THREAD

**Issue by passcod** [apexcharts/apexcharts.js#171]
**Is your feature request related to a problem? Please describe.**

We have a fixed set of series but we filter the empty ones. So we'll have A, B, C, D... but if A and C are empty we'll only give B and D to apexcharts. That's so it does less work.

We have legend enabled, so it can be seen easily which series is which. That usually works great. However, when we have only one series displayed, the legend is hidden. So the user doesn't know whether that one series is A, B, C, or D.

**Describe the solution you'd like**

Add an option to always show the legend, even if there is only one series.

Perhaps: `{ legend: { show: 'always' } }`

**Comment by junedchhipa** [comment]
Sure, this is an important enhancement. I will provide this option.

**Comment by passcod** [comment]
Great, thanks!
