### ISSUE TITLE
Language in locales

### ISSUE THREAD

**Issue by sirdree** [apexcharts/apexcharts.js#1711]
Hello,
can you please add the Albanian language on the next release please.
i have translated the json file for the locales, called it as sq.json
here is the json content for Albania language:
----------------------------------------------
{
  "name": "sq",
  "options": {
    "months": [
      "Janar",
      "Shkurt",
      "Mars",
      "Prill",
      "Maj",
      "Qershor",
      "Korrik",
      "Gusht",
      "Shtator",
      "Tetor",
      "Nëntor",
      "Dhjetor"
    ],
    "shortMonths": [
      "Jan",
      "Shk",
      "Mar",
      "Pr",
      "Maj",
      "Qer",
      "Korr",
      "Gush",
      "Sht",
      "Tet",
      "Nën",
      "Dhj"
    ],
    "days": [
      "e Dielë",
      "e Hënë",
      "e Martë",
      "e Mërkurë",
      "e Enjte",
      "e Premte",
      "e Shtunë"
    ],
    "shortDays": ["Die", "Hën", "Mar", "Mër", "Enj", "Pre", "Sht"],
    "toolbar": {
      "exportToSVG": "Shkarko SVG",
      "exportToPNG": "Shkarko PNG",
      "exportToCSV": "Shkarko CSV",
      "menu": "Menu",
      "selection": "Seleksiono",
      "selectionZoom": "Seleksiono Zmadhim",
      "zoomIn": "Zmadho",
      "zoomOut": "Zvogëlo",
      "pan": "Spostoje",
      "reset": "Rikthe dimensionin"
    }
  }
}
----------------------------------------------
Thanks in advance and keep the great work up.

**Comment by sirdree** [comment]
[sq.zip](https://github.com/apexcharts/apexcharts.js/files/4837043/sq.zip)

**Comment by junedchhipa** [comment]
Thanks for the contribution, @sirdree.
I will surely add this in the next release.
