### ISSUE TITLE
Realtime chart x axis not moving with data

### ISSUE THREAD

**Issue by ernestp** [apexcharts/apexcharts.js#1716]
# Bug report

Realtime chart x axis not moving with data

## Codepen

https://codepen.io/cemujax/pen/WWRQjW

## Explanation

- What is the behavior you expect?
X axis scale moving alongside with data

- What is happening instead?
X axis scale jumping from time to time

- What error message are you getting?
nope

**Comment by junedchhipa** [comment]
Unfortunately, the x-axis is not animated at the moment along with the series.
It's not a bug, but it was never implemented.
