### ISSUE TITLE
T.Push is not a function error

### ISSUE THREAD

**Issue by rsenina** [apexcharts/apexcharts.js#1717]
I have an chart.appendSeries() inside a loop to add series that constantly updating every other time., After iterating im getting this error.

apexcharts.min.js:6 Possible Unhandled Promise Rejection: TypeError: t.push is not a function

**Comment by junedchhipa** [comment]
I guess this answers the question - https://stackoverflow.com/a/62633281/1247864

**Comment by meritshm441** [comment]
I was having this issue 
![image](https://github.com/apexcharts/apexcharts.js/assets/75949112/bd16a545-2b03-42e4-a825-c1a87d4eed81)
