### ISSUE TITLE
can't hide 0 values of columns in the column chart

### ISSUE THREAD

**Issue by Dakshinads** [apexcharts/apexcharts.js#1719]
I want to hide 0 values in columns. how do it?

I have a lot of data. but some data value of 0. Because the chart width is going to more.

https://codepen.io/dakshina/pen/JjGrxax

![2020-06-30 (2)_LI](https://user-images.githubusercontent.com/53216423/86085721-79024a80-babd-11ea-92ee-c395143213fd.jpg)

**Comment by junedchhipa** [comment]
Sorry, you cannot skip drawing a column if it contains 0 values.

**Comment by Dakshinads** [comment]
Do you have any solution for this?

**Comment by jEstevezRod** [comment]
some solution?

**Comment by emololftw** [comment]
any solution?

**Comment by jEstevezRod** [comment]
> any solution?

yes, we changed to e-charts. good luck with apex

**Comment by saadwaseem** [comment]
This might be too late to reply but I hope will save someones time who encounter the same issue with apexCharts. The library is great indeed and handles zeros as real numbers.

If you want zero to be ignored then you must replace the digit 0 with null that would probably solve your zero lables issue on the chart. Hope that helps.

**Comment by BogdanGanciulescu** [comment]
Saved my life. Thanks @saadwaseem !

**Comment by hasan-py** [comment]
Another solution i tried! Which work like .

You can give the value  -0.0001 or neg number like -1. And then in options you can update the formating like bellow

`
<Chart
                  options={{
                    chart: {
                      height: 350,
                      type: "bar",
                    },
                    plotOptions: {
                      bar: {
                        borderRadius: 5,
                        dataLabels: {
                          position: "top",
                        },
                      },
                    },
                    dataLabels: {
                      enabled: true,
                      formatter: function (val) {
                        if (+val <= 0) {
                          return "$0";
                        }

                        return "$" + val;
                      },
                      offsetY: -20,
                      style: {
                        fontSize: "10px",
                        colors: ["#304758"],
                      },
                    },

                    xaxis: {
                      categories: columnChartLabels,
                      position: "top",
                      axisBorder: {
                        show: false,
                      },
                      axisTicks: {
                        show: false,
                      },
                      crosshairs: {
                        fill: {
                          type: "gradient",
                          gradient: {
                            colorFrom: "#D8E3F0",
                            colorTo: "#BED1E6",
                            stops: [0, 100],
                            opacityFrom: 0.4,
                            opacityTo: 0.5,
                          },
                        },
                      },
                      tooltip: {
                        enabled: true,
                      },
                    },
                    yaxis: {
                      axisBorder: {
                        show: false,
                      },
                      axisTicks: {
                        show: false,
                      },
                      labels: {
                        show: false,
                        formatter: function (val) {
                          if (val <= 0) {
                            return "$0";
                          }

                          return "$" + val?.toFixed(2) + " USD";
                        },
                      },
                    },
                    title: {
                      text: "Monthly Sales",
                      floating: true,
                      offsetY: 330,
                      align: "center",
                      style: {
                        color: "#444",
                      },
                    },
                  }}
                  series={[
                    {
                      name: "Sales",
                      data: columnChartValues,
                    },
                  ]}
                  type="bar"
                  height={350}
                />

`

**Comment by harsh7800** [comment]
> This might be too late to reply but I hope will save someones time who encounter the same issue with apexCharts. The library is great indeed and handles zeros as real numbers.
> 
> If you want zero to be ignored then you must replace the digit 0 with null that would probably solve your zero lables issue on the chart. Hope that helps.

it still show the label on the xaxis
