### ISSUE TITLE
Showing NaN in date time x-axis

### ISSUE THREAD

**Issue by cola119** [apexcharts/apexcharts.js#1720]
# Bug report
Related: https://github.com/apexcharts/apexcharts.js/issues/1448#issuecomment-640987907
Thank you for your development. We fixed https://github.com/apexcharts/apexcharts.js/issues/1448 on v3.19.3.

## Codepen

https://codesandbox.io/s/gracious-varahamihira-tbl4t?file=/src/index.js

## Explanation

However, It still shows NaN when the total value of the second series is zero.
![image](https://user-images.githubusercontent.com/22386678/86087908-43228d80-bae0-11ea-9756-bee46ec33598.png)

This is because we can't get the correct`activeIndex` of the second series because of `total !== 0` condition.
https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/tooltip/Utils.js#L177-L184

I don't think this condition(`total !== 0`)  is necessary, do you?

**Comment by junedchhipa** [comment]
I checked it and it seems it's not necessary now as it is similar to the previous condition which we removed (seriesHaveSameValues) in the last PR.
I will remove this too.

**Comment by cola119** [comment]
Thanks!
