### ISSUE TITLE
Show Pattern Fill in Legend Marker

### ISSUE THREAD

**Issue by rtybanana** [apexcharts/apexcharts.js#1721]
I'm using a combination of solid and pattern series with the same colour as in the below image.

![image](https://user-images.githubusercontent.com/20663297/86031632-00a07880-ba2e-11ea-8a79-bca506dee10f.png)

Would it be possible to display the pattern in the legend marker to differentiate between the two series?

**Comment by tedorian** [comment]
This would be a great addition - we would need this for our system

**Comment by ccarlosm** [comment]
Any updates on this? 
We would need it as well. It would be great if added!

Thanks very much!!

**Comment by FPEPOSHI** [comment]
Hi there, is there any plan in the near feature to have this?
