### ISSUE TITLE
Regression: dots are shown in reversed colours

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1725]
# Bug report

Between v3.18 and v3.19, a regression was introduced that swapped the colours for the dots over the charting line. In this example, the red dot appears on the green line and vice versa.

![image](https://user-images.githubusercontent.com/470626/86230789-7c630800-bb89-11ea-9ffe-ac064e7c690a.png)

## Codepen

[CodePen](https://codepen.io/bilge-the-encoder/pen/OJMOQOP)

**Comment by Bilge** [comment]
This is still not fixed in 3.20.0.

**Comment by junedchhipa** [comment]
Which browser?
I cannot reproduce.

**Comment by Bilge** [comment]
Since updating the version in the CodePen, it seems fixed. However, it is not in working [here](https://club.steam250.com/app/960990) for some reason...
