### ISSUE TITLE
X-Axis datetime Safari Timezone

### ISSUE THREAD

**Issue by Matthewloughton** [apexcharts/apexcharts.js#1726]
First of all. Apex charts is incredible. It is so featureful and look and feel is amazing. THANK YOU

I will try and be as verbose as possible. I know how painful some users can be with reporting issues ;)

We are using a date time graph with option: datetimeUTC set to false

xaxis: {
              type: 'datetime',
              labels: {
                datetimeUTC: false
              }
            }

It works perfectly in Chrome but the timezone is out in Safari. I am from UTC+2 and in safari it seems to become +4. The tooltips are fine though. Images below

Chrome (correct):
![image](https://user-images.githubusercontent.com/15347125/80480457-fb9d4b00-8950-11ea-91b0-ef49fd6ec981.png)

Safari (incorrect):
![image](https://user-images.githubusercontent.com/15347125/80480515-1e2f6400-8951-11ea-8c77-ba9d8150cce1.png)

I took the liberty of looking around about the issue and came across this:
https://stackoverflow.com/questions/41338821/incorrect-timezone-in-safari-compared-to-chrome-ff-using-javascript-date

I went into your src and I've got a feeling it's got to do with something in your DateTime.js line 24. "getTimeStamp()"

Let me know if I can help further

**Comment by junedchhipa** [comment]
Sorry, this went unnoticed.
Many users have reported similar issues. Hence, tagging them all here so this can be addressed soon.
Related to #1544, #1485, #1255

**Comment by minkasu-kuppusamy** [comment]
if datetimeUTC:false , how you formatted the code to local timezone ? for me graph not at all displaying in safari , but working fine in chrome.

**Comment by alex-stumpfl** [comment]
Same here on iOS. Seems like the `Date`, that `DateTime` should render, is already wrong.
(s. https://github.com/apexcharts/apexcharts.js/blob/e10827ac8bb4e36e1d592e308a4cda038d766d23/src/modules/TimeScale.js#L725)
