### ISSUE TITLE
First label is missing on the x-axis bar graph when it is datetime type

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [apexcharts/apexcharts.js#1730]
# Bug report
I am not able to see the first label on x-axis with datetime type.

My configuration is like below
<img width="429" alt="Screenshot 2020-07-01 at 10 27 55 PM" src="https://user-images.githubusercontent.com/9896335/86271218-24102280-bbea-11ea-992d-d465d1b20db5.png">

## Codepen

Here is the example [this codepen](https://codepen.io/rajeshwarpatlolla/pen/LYGOXrV) to demonstrate the problem i have.

## Explanation

- What is the behavior you expect?
It should show the label properly on x-axis.

- What is happening instead?
It is not showing the label properly on x-axis.
<img width="694" alt="Screenshot 2020-07-01 at 10 33 34 PM" src="https://user-images.githubusercontent.com/9896335/86271669-ed86d780-bbea-11ea-9401-095f70f56a11.png">

- What error message are you getting?
No error

**Comment by alekbless** [comment]
I'am experiencing the same issue.

**Comment by nikolaifischer** [comment]
Me too! I was able to make the first bar appear by setting the x-axis min value to 1 millisecond before the first value. Now the bars are not completely centered in the grid anymore though.

**Comment by jkblgithub** [comment]
Hi, I am also having this issue. The workaround suggestedd by @junedchhipa is not working for me. Any ideas on how to fix?
