### ISSUE TITLE
Error with single toolbar on synchronized charts

### ISSUE THREAD

**Issue by AxelBayle** [apexcharts/apexcharts.js#1732]
## Explanation

- What is the behavior you expect?
 
   I have two synchronized charts and I want only one toolbar to zoom, move ,etc... So in the option of the second graph I set 
`toolbar: {
          show: false }`  

- What is happening instead?
  
   Nothing append on the graph side but I've got an error on the console 
    

- What error message are you getting?
![image](https://user-images.githubusercontent.com/43752046/86340096-b77e3d80-bc54-11ea-9729-b5c1977e84ce.png)

**Comment by Stuhl** [comment]
I found a workaround. You can hide the toolbars by setting the CSS display properties to none.

First you need to catch the events "mounted" and "update" from the chart where you want to hide the toolbar.

```js
chart: {
      events: {
        mounted: eventHandler,
        updated: eventHandler
      },
```

Then you get the toolbars elements you want to hide and set `display: hidden;`

```js
const eventHandler = (chartContext, props) => {
    const t = chartContext.toolbar
    const toolbarItems = [t.elMenu,
        t.elMenuIcon,
        t.elPan,
        t.elSelection,
        t.elZoom,
        t.elZoomIn,
        t.elZoomOut,
        t.elZoomReset]

    for (let item of toolbarItems) {
      item.style.display = "none"
    }
  }
```
