### ISSUE TITLE
Question: how can I toggle the data series back on for Radar Charts once they are toggle offer programatically?

### ISSUE THREAD

**Issue by LifeSource** [apexcharts/apexcharts.js#1733]
To keep this short, I had to create custom legends to my radar chart, so I had to do the toggle **programmatically** for the data series.

I've used `chart.toggleSeries('seriesName')` to turn off a radar chart series but when you click the label again it doesn't come back on.

**Expected result:** it should come back on.

**Actual result:** it turns it off (so toggle is half working) but not back on.

The interesting thing is, the function below is working for `axis` type charts such as `line`, `bar`, `area` and `mixed` combo. Seems to fail on `radar` I suspect `pie` will have the same issue.

```
function toggleDataSeries(event) {
    const { target } = event;
    const seriesName = target.innerText;
    target.classList.toggle('inactive');
    this.chart.toggleSeries(seriesName);
}
```

How can I toggle the series back on for `radar` and `pie` charts? I couldn't find anything in the documentation regarding it so that why I'm asking here.

**Comment by junedchhipa** [comment]
Can you please create a codepen so I can quickly reproduce?

**Comment by LifeSource** [comment]
> Can you please create a codepen so I can quickly reproduce?

@junedchhipa I've created a CodePen https://codepen.io/LifeSource/pen/qBbxyzz

You can see it's a very simple demo, that adds an event listener to toggle the series using the `innerText`. However the toggle only works 1 way, it doesn't bring it back if I click it a second time. 

Basically I expected to toggle it on/off if I click the custom labels, that's what I'm trying to do. (programmatically).

You might ask why I'm not using the out of the box one, it's partly due to the integration with other tools and other reasons I can't go into specifics.
