### ISSUE TITLE
Pie chart UpdateSeries Not working

### ISSUE THREAD

**Issue by Dakshinads** [apexcharts/apexcharts.js#1739]
When clicking the change button not showing colours and plots. Earlier it's working but not working now.

https://codepen.io/dakshina/pen/pogppGz?editors=1111

**Comment by junedchhipa** [comment]
Update `series` and `options` both in a single call instead of calling `updateSeries` and `updateOptions` one after the other.
So, try doing

```javascript
  ApexCharts.exec("pc1", "updateOptions", {
    series: [50, 60, 70, 80, 90, 100, 50, 70],
    labels: [
      "T-shirt",
      "Denim",
      "shorts",
      "Shirt",
      "shoes",
      "shocks",
      "aaa",
      "bbbb"
    ],
    title: {
      text: "main_title"
    }
  });
```

**Comment by Dakshinads** [comment]
Thank you

**Comment by gokhantaskan** [comment]
Vue.js component has a problem with pie charts, too. 

I updated the latest version `"apexcharts": "^3.19.3"`, `"vue-apexcharts": "^1.5.3"`.

The chart shows "Loading" text. Bar chart is working properly.
