### ISSUE TITLE
Min yaxis not rendering correctly

### ISSUE THREAD

**Issue by laurencei** [apexcharts/apexcharts.js#174]
## Codepen

https://codepen.io/anon/pen/QZYdQE?editors=0010

## Explanation

When setting a `min` on the `yaxis`, if an area of the chart goes below that, it doesnt render correctly.

This is what currently renders:
![image](https://user-images.githubusercontent.com/1210658/47563463-9fc5c080-d96d-11e8-86a4-103b7419d55a.png)

But this is what I would expect (note that nothing appears below "50")

![image](https://user-images.githubusercontent.com/1210658/47563501-bb30cb80-d96d-11e8-85f7-a26e69690533.png)

_p.s. this is an amzing charting library - keep up the great work!_

**Comment by junedchhipa** [comment]
Try
```javascript
grid: {
     clipMarkers: true
}
```

Updated [codepen](https://codepen.io/junedchhipa/pen/ePxgby?editors=0010)

I will make this as a default behavior to prevent drawing outside the grid area.

**Comment by laurencei** [comment]
Thanks @junedchhipa - works perfectly!
