### ISSUE TITLE
Pie chart color repeat issue

### ISSUE THREAD

**Issue by vikramparihar** [apexcharts/apexcharts.js#1740]
Hello I am using apex pie chart. and i have more then 6 series . In this case series color is repeted. and i am unable to find proper view report.

![ril-camera](https://user-images.githubusercontent.com/5202442/86442580-e03d1c00-bcc2-11ea-8da4-3706f451856f.png)

This is generated chart, report 3.9 and 49.7 has same color. 
This series may be increase in future. So color will not be unique.

I dont want want to use color property of chart, because its not dynamic.

**Comment by junedchhipa** [comment]
If you do not want to use default colors, define your own colors.

```javascript
options = {
  colors: ['#008FFB', '#00E396', '#FEB019', '#FF4560', '#775DD0', '#3f51b5', '#03a9f4', '#4caf50', '#f9ce1d', '#FF9800']
}
```

**Comment by junedchhipa** [comment]
I just read that you do not want to define colors too because of the dynamic pie chart.
You can generate random colors like this

```javascript
let colors = new Array(50)
for (let i = 0; i < colors.length; i++) {
  colors[i] = '#' + (((1 << 24) * Math.random()) | 0).toString(16)
}

var options = {
  colors: colors
}
```

**Comment by vikramparihar** [comment]
@junedchhipa Thank you ! this approach looks good. let me try.
