### ISSUE TITLE
Feature Forward Email Charts?

### ISSUE THREAD

**Issue by niftylettuce** [apexcharts/apexcharts.js#1743]
Hey - I made some pretty neat charts, one is a heatmap like GitHub style with MongoDB pulled aggregated data.  Rendered with days of the week, etc.

https://forwardemail.net/en/open-startup

Interested in featuring this somewhere?  I'm just here to share.  Really like using Apex charts so far.

Also one minor bug perhaps - I noticed that the dates in the line charts aren't grouped, and when local testing they are.  Not sure if anyone knew why.  The source code is all on our GitHub @forwardemail.

**Comment by junedchhipa** [comment]
Nice work there, looks clean :)
Unfortunately, I don't have any plans to add featured content currently. I will think about it in the future.

I didn't understand your last point about the dates being grouped in the line chart. If you can create a Codepen, please do it, I will take a look.

**Comment by niftylettuce** [comment]
@junedchhipa Can you go here https://forwardemail.net/en/open-startup and hover over the dates in the line cart?  It should be grouped I think?  It was doing it locally at some point, but then it stopped working and doesn't show in production. Source is at <https://github.com/forwardemail/forwardemail.net/blob/7059d84a107b2993f397f4fee3f187cfb62a5844/app/controllers/web/open-startup.js#L56-L112>.
