### ISSUE TITLE
Combining different series on one chart

### ISSUE THREAD

**Issue by enmalafeev** [apexcharts/apexcharts.js#1744]
**Is your feature request related to a problem? Please describe.**	
I have multiple yaxis series. 
Xaxis is:
```
xaxis: {
          type: "datetime",
          categories: this.chartCategories,
          labels: {
            datetimeUTC: false
          }
        },
```
Where first series is:
```
{
  type: "area",
  data: [Array of data]
},
```
Secons series is: 
```
{
  type: "line", 
  data: [ { x: 0, y: 0 }, { x: last value x-axis, y: value } ] 
},

Is straight line from point {0, 0} to point {last value x-axis, value}.
```
How can I combine this series on one chart with the same xaxis ?

**Comment by enmalafeev** [comment]
I fixed this by using for first chart series array of objects [{ x: value1, y: value1 }, { x: value2, y: value2 }, ...], like other 2 series.

**Comment by junedchhipa** [comment]
Glad you found a workaround.
