### ISSUE TITLE
Timeline chart grid column colors are not working

### ISSUE THREAD

**Issue by zergeborg** [apexcharts/apexcharts.js#1745]
# Bug report
When using the timeline chart if I want to customize the grid column colors, Apexcharts doesn't allow me to do so. This only happens when the `xaxis` type is set to `datetime`.

## Codepen

Demonstration of the issue [HERE](https://codepen.io/fogetti/pen/VweQNpa). Note that the timeline chart grid columns don't change even though the column colors array is defined.

Now if we change the `xaxis` type to `category` for example, then column colors are properly set. Also note that this seemingly only impacts the grid `column` and not the grid `row`.

## Explanation

- What is the behavior you expect?
I expect the column colors to change

- What is happening instead?
The column colors don't change

- What error message are you getting?
None

**Comment by U-OK** [comment]
@junedchhipa I was get it issue too. Can you help, please?
