### ISSUE TITLE
Tick amount not working on yaxis

### ISSUE THREAD

**Issue by laurencei** [apexcharts/apexcharts.js#175]
## Codepen

https://codepen.io/laurencei/pen/LgqxgM

## Explanation

So maybe I'm misunderstanding - but I though `tickamount` is the amount of each grid displayed.

i.e. if I set `yaxis: { tickamount: 25 }` - then I would expect 'ticks' (or grid lines) at 0, 25, 50, 75 etc.

Instead setting this variable seems to have no noticeable effect?

Am I missing something?

**Comment by junedchhipa** [comment]
There's a typo in your config
It should be `tickAmount` and not `tickamount`

What `tickAmount does`? 
It creates a number of lines/ticks between min and max values.
For eg., `tickAmount: 20` will create 20 intervals in the y-axis like the below image.

![screen shot 2018-10-26 at 6 02 50 pm](https://user-images.githubusercontent.com/17950663/47566520-a6dad780-d949-11e8-8aaf-524f3b1349e0.png)

**Comment by laurencei** [comment]
oh wow - sorry @junedchhipa for that mistake - I've been looking at it for 30mins
