### ISSUE TITLE
The label in the y-axis is not shown completely

### ISSUE THREAD

**Issue by github-rj** [apexcharts/apexcharts.js#1752]
# Bug report

## Codepen

https://codepen.io/github-rj/pen/xxZWWPz

## Explanation

- What is the behavior you expect?
 The labeling on the y-axis should be fully displayed
![image](https://user-images.githubusercontent.com/21079928/86803102-f9085180-c075-11ea-897b-add07d6fa20a.png)

- What is happening instead?
If not all labels on the Y-axis are the same length, the text will be cut
![image](https://user-images.githubusercontent.com/21079928/86801916-cb6ed880-c074-11ea-88a9-773970bab9ff.png)

**Comment by junedchhipa** [comment]
The `yaxis` don't support non-numeric values and hence it gets the wrong width.
You should add a minWidth in the yaxis labels to avoid it

```javascript
yaxis: {
  labels: {
    minWidth: 40,
  }
}
```
