### ISSUE TITLE
Bar Column width and height

### ISSUE THREAD

**Issue by shashircciit** [apexcharts/apexcharts.js#1754]
Hey,  is there any way to fix the min-width and min-height of the bar. If you see here I have multiple columns that are coming too thin and height is also small which is hardly possible to see.

I want to report one issue  [https://codepen.io/shashircciit/pen/abdYRey] where June'20 I am getting at the x-axis in place of date like 1 June.

<img width="1140" alt="Screenshot 2020-07-08 at 2 25 17 AM" src="https://user-images.githubusercontent.com/31244667/86842191-7954a400-c0c2-11ea-87c1-e36e36d4e1fa.png">

**Comment by violacambie** [comment]
Hey @shashircciit  how did you fix it in the end?
I'm having the same issue..
