### ISSUE TITLE
curve smoothing and null data series

### ISSUE THREAD

**Issue by Heartz66** [apexcharts/apexcharts.js#1756]
If you have `'stroke.curve': 'smooth'` enabled and try to display an empty data serie (array with `null` only), it will throw the following error:

`Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined`

Please see my codepen, simply remove the `stroke.curve` property to make it work: https://codepen.io/Heartz66/pen/KKVRdbW

**Comment by junedchhipa** [comment]
This is fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/27156b00a3a5e272da3eecea3a6c4dd7560e1cf7) and an update will be released soon.
