### ISSUE TITLE
 Coloring x-axis and y-axis applies to only first item in categories array

### ISSUE THREAD

**Issue by sarah-sk1203062** [apexcharts/apexcharts.js#1757]
# Bug report
Hello! I'm using ApexCharts with Vue.js. I'm trying to make my page responsive to dark and light modes. When I try to apply a style to an axis, it only applies to the first item in the categories array and ignores the rest. This sometimes happens to the x-axis and sometimes to the y-axis. 
Now, this is what I am doing: 

`xaxis: {
     labels: {
        style: {
            colors: this.$vuetify.theme.dark ? ['#b9babb'] : ['#606162'],
        }
    }
}`

Any way to fix this? 

I have used the documentation provided to re-color them. [https://apexcharts.com/docs/options/xaxis/ & https://apexcharts.com/docs/options/yaxis/].

Screenshots: 
<img width="916" alt="Screen Shot 2020-07-08 at 3 05 25 PM" src="https://user-images.githubusercontent.com/17256896/86928495-4a2f4880-c13d-11ea-929c-0ccbdcacaefd.png">
<img width="131" alt="Screen Shot 2020-07-08 at 5 00 51 PM" src="https://user-images.githubusercontent.com/17256896/86928500-4bf90c00-c13d-11ea-89aa-65a6b03f883d.png">

## Explanation

- What is the behavior you expect?
I am expecting the whole axis to be colored. 

- What is happening instead?
Only the first category item is responding and coloring according to the mode. The rest does not. 

- What error message are you getting?
No errors.

**Comment by junedchhipa** [comment]
Instead of passing an array, just provide a string to apply the color to all labels.

```javascript
xaxis: {
  labels: {
    style: {
      colors: '#333'
    }
  }
}
```
