### ISSUE TITLE
Changing the color of label lines in a radialBar chart

### ISSUE THREAD

**Issue by rinogo** [apexcharts/apexcharts.js#1758]
**Is your feature request related to a problem? Please describe.**	
I have a radialBar chart that looks like this:
![image](https://user-images.githubusercontent.com/3732514/86939562-f9006400-c0fe-11ea-93d8-7f743902ed37.png)

**Describe the solution you'd like**	
Is it possible to change the color of the lines in the label? I'd like the "Posts" line to remain the same color while the "(30 days)" color is changed to a lighter gray.

**Describe alternatives you've considered**	
I've looked at the code and it seems that this might not be possible, but I'm not sure. Can someone please confirm whether or not this is currently possible?

**Additional context**	
(None)

**Comment by junedchhipa** [comment]
I'm sorry, but that's not achievable.
You may find the element via inspector and apply CSS to it.

```css
.apexcharts-datalabel-label tspan:nth-child(2) {
   fill: #888;
}
```

![Screenshot 2020-07-08 at 10 35 36 PM](https://user-images.githubusercontent.com/17950663/86948831-5df1a380-c16b-11ea-8e56-d33b12969581.png)

Full example - https://codepen.io/apexcharts/pen/WNrJGdX

**Comment by rinogo** [comment]
Awesome! I didn't think about changing the color via CSS - thank you!
