### ISSUE TITLE
Draw only one series in staight area and line charts 

### ISSUE THREAD

**Issue by varrodani** [apexcharts/apexcharts.js#176]
Dear developoers,
I want to report a bug issue.
 
## Codepen
https://codepen.io/anon/pen/gBqBPX
## Explanation
I want to display a countinous chart line with two series. In the first series last element nulled and the second series elements nulled until before last.
I created a two data series and the chart only the first data series drawed in the chart. The data source is ok because if I change the series order have a same problem.

Please fix it, if possible.
Thanks.

**Comment by junedchhipa** [comment]
Dear @varrodani, thanks for raising an issue. I understood the problem and this will be fixed in the next release.

**Comment by varrodani** [comment]
I almost forgot.
I would not want to use datetime on the x axis

**Comment by junedchhipa** [comment]
Cool, I will take that into account

**Comment by varrodani** [comment]
Yes, I want to see this!
Thank you very much!

**Comment by junedchhipa** [comment]
Ok, this is fixed ☺️ 
I will release a new update tomorrow

**Comment by fhrryDeveloper** [comment]
Hi, @junedchhipa 
I need your help in apex chart

**Comment by fhrryDeveloper** [comment]
please check this issue
https://stackoverflow.com/questions/66113577/apex-chart-line-not-displaying-only-one-line
