### ISSUE TITLE
Wrong marker color for first marker.

### ISSUE THREAD

**Issue by Boldonglen** [apexcharts/apexcharts.js#1762]
When setting the colors of the markers within the series it seems like the first maker is not getting the correct value.
As you can see from the first maker in the codepen below it should be red but its being coloured green.

https://codepen.io/boldonglen/pen/YzwvOPB

## Explanation

- What is the behavior you expect?
The first marker should be red
- What is happening instead?
The first maker is green
- What error message are you getting?
N/A

**Comment by junedchhipa** [comment]
This is fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/c33c24451d81b668e03b61ccb844f321fdbd0ed3).
The patch will be released on npm soon.
