### ISSUE TITLE
rotating the title on y axis is displaying an error in the console

### ISSUE THREAD

**Issue by devpgcs** [apexcharts/apexcharts.js#1766]
Hi there,

I'm rotating the title on y axis but it is displaying an error on console, I've tryed to change it  as string, even not using rotate property and passing a transform: "rotate(x)" on style property inside of title but that didn't work. This is my code:

`options: {
      title: { text: "Distribución de oferta para propiedades similares", align: "center" },
      chart: {
        parentHeightOffset: 10,
        animations: {
          enabled: false,
        },
        type: "bar",
        height: 140,
        stacked: true,
        offsetY: 0,
        toolbar: {
          show: false,
        },
      },
      plotOptions: {
        bar: {
          horizontal: true,
        },
      },
      annotations: {
        xaxis: [
          {
            x: range,
            borderColor: "#775DD0",
            offsetX: 8,
            label: {
              style: {
                color: "#41C8A2",
              },
              text: "Tu propiedad",
              position: isMobile ? "bottom" : "top",
              orientation: isMobile ? "vertical" : "horizontal",
              offsetY: 0,
              offsetX: 8,
            },
          },
        ],
      },
      toolbar: {
        show: false,
      },
      stroke: {
        width: 0,
        colors: ["#fff"],
      },
      colors: ["#28849F", "#88D4C5", "#9A9A9A", "#CAD35C"],
      noData: {
        text: "Loading...",
      },

      yaxis: {
        labels: {
          show: true,
          align: "right",
          minWidth: 55,
          maxWidth: 160,
        },
        show: false,
        title: {
          text: "Propiedades",
          rotate: -90, // Here ir my problem
          offsetX: 10,
          style: {
            color: undefined,
            fontSize: "10px",
            fontFamily: "Helvetica, Arial, sans-serif",
            fontWeight: 600,
            cssClass: "apexcharts-yaxis-title",
          },
        },
        axisBorder: {
          offsetX: 0,
          offsetY: 0,
        },
        minPadding: 40,
        maxPadding: 60,
      },
      xaxis: {
        type: "category",
        labels: {
          show: true,
        },
      },
      fill: {
        opacity: 1,
      },
      legend: {
        position: "bottom",
        horizontalAlign: "center",
      },
    },`

![Captura de pantalla de 2020-07-14 23-32-53](https://user-images.githubusercontent.com/62974150/87504211-b1606780-c62b-11ea-8df3-c4948ee973ac.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by devpgcs** [comment]
Hi again and sorry for bother you :( 

I did delete my node_modules folder, uninstall and reinstall apexcharts but it's given me the same error, so I did search my new node_modules folder and I saw that the changes that you have added are not there

![Captura de pantalla de 2020-07-15 13-59-25](https://user-images.githubusercontent.com/62974150/87584995-fde78980-c6a3-11ea-92f4-b900aa36bf78.png)
![Captura de pantalla de 2020-07-15 13-58-47](https://user-images.githubusercontent.com/62974150/87584998-ff18b680-c6a3-11ea-8e4b-88be87b4712c.png)
![Captura de pantalla de 2020-07-15 13-58-00](https://user-images.githubusercontent.com/62974150/87585000-ffb14d00-c6a3-11ea-89e6-85b24de24ef7.png)

It's something that I have to do? :(

**Comment by junedchhipa** [comment]
Sorry, I should have mentioned that the changes will be reflected when a new version is released on npm.
Please expect a new release 3.19.4 next week or by the end of this week.
Keep an eye on the [releases](https://github.com/apexcharts/apexcharts.js/releases) and when the new version is out, upgrade to the latest one.

**Comment by devpgcs** [comment]
Okey okey! I really appreciate your help and fast attention
