### ISSUE TITLE
text in two lines not ellipsis

### ISSUE THREAD

**Issue by MedinaGitHub** [apexcharts/apexcharts.js#177]
**Describe the solution you'd like**
text in two lines

**Describe alternatives you've considered**
texto mas pequeño

**Additional context**

Lorem 
ipsum

not 
Lorem...

**Comment by junedchhipa** [comment]
I assume you're talking about labels in x-axis which are truncated by ellipsis. 
If yes, I will think about that option. 
Also, this will be possible in category axis charts and not datetime. One option is to provide category labels in array format like this:

```javascript
categories: ['Apples', ['Blueberries', 'Strawberries'], 'Mangoes']
```
The array labels can then be drawn in separate lines.

**Comment by egisberto** [comment]
Can I have x-axis labels in two lines ?
