### ISSUE TITLE
Y-Axis, always show tick for 0 value

### ISSUE THREAD

**Issue by rafaoliverce** [apexcharts/apexcharts.js#1771]
**Is your feature request related to a problem? Please describe.**	
I need to always show the tick for zero value on the y-axis.

**Describe the solution you'd like**	
Some option that could enforce the zero tick to show on the y-axis.

**Describe alternatives you've considered**	
...

**Additional context**	
![image](https://user-images.githubusercontent.com/55211969/87614324-0e205880-c6e6-11ea-8aa7-256c7baa2cdd.png)

**Comment by junedchhipa** [comment]
You can use `annotations` to draw y-axis lines at specific points.
Take a look at this example - https://codepen.io/apexcharts/pen/GXOJXQ

```javascript
annotations: {
  yaxis: [{
    y: 0
  }]
}
```

**Comment by rafaoliverce** [comment]
Thanks @junedchhipa! The annotation works but it was not what I was searching for.

But I've found the solution!

For anyone with the same problem, what I needed to to was to use force nice scale `true`.
So even when the values goes negative, the 0 line will always appear.

**Comment by rafaoliverce** [comment]
> @rafaoliverce can you please show an example code?

It's being a long time since I touched the chart I showed in the example so I'm not sure if it still works, but the options is this one:

```
yaxis: {
  ...
  forceNiceScale: true,
  ...
}
```
