### ISSUE TITLE
Tooltip disappears when updating (bar) chart

### ISSUE THREAD

**Issue by Stealthmate** [apexcharts/apexcharts.js#1772]
# Bug report

## Codepen

https://codepen.io/stealthmate/pen/OJMBVaW

## Explanation

- What is the behavior you expect?

If, after updating the series, the mouse is still over a bar (or the respective element for other chart types), the tooltip should get updated as well instead of simply disappearing. I'm working on a 100% stacked chart that gets updated every second. The ratios stay mostly the same and I want the user to be able to see the real values when mousing over. I can do this with a formatter, however the problem is that whenever the chart updates, the tooltip disappears and that defeats its purpose. 

In the codepen above, there's the bottom part of the chart (series named `const`) that stays relatively the same each second, but when I mouse over it the tooltip only appears until the next update, and I want it to be shown continuously.

Having a stacked chart in the 

- What is happening instead?

Tooltip disappears and you have to move the mouse to display it again.

- What error message are you getting?

None.

**Comment by auoa** [comment]
Same here... I have a line chart with 3 series. On data update the tooltip disappears. Any progress on that issue/behaviour?

**Comment by junedchhipa** [comment]
Sorry, this is not fixable easily.
The whole chart re-renders and it's not possible to keep the tooltip intact on update.

**Comment by auoa** [comment]
I figured out, that just clicking the chart without moving the mouse lets the tooltip re-appear. Thus, I tried something like `this.$refs.apexchart1.$el.click();` in the context of _Vue_. However, this did not work for me. Any suggestions on how this can be solved? It is not necessary to solve this inside Apex Charts, a workaround would already meet my requirements.

**Comment by yohainnn** [comment]
same here

**Comment by Jack-Bailey** [comment]
Same issue here, works really well for static data but its really annoying having it disappear on each update

**Comment by Sandr0oo** [comment]
I, too, faced this problem. How can this be solved?

**Comment by Sandr0oo** [comment]
@auoa Please tell me how you solved this problem?

**Comment by auoa** [comment]
@Sandr0oo As you can read in the history, I have not solved the problem yet.

**Comment by jcramb** [comment]
Just ran into this same issue trying to use it for real-time data, very disappointing that this wasn't considered in the design.

**Comment by Qaiser45** [comment]
if area chart then use chart.updateSeries([{ name: "Sales", data: GraphData }]); instead of chart.updateSeries(GraphData);
