### ISSUE TITLE
Problem with different type synchronized charts

### ISSUE THREAD

**Issue by bibekrimal** [apexcharts/apexcharts.js#1774]
# Bug report

I am using ApexCharts.js to create a graph which should be associated with another graph. There's the feature of sync charts but turns out if used line and bar, it's not working as expected. Here is the fiddle https://jsfiddle.net/moviecrew/eL76yfkr/7/

I have used group: 'group name' and id to link those 2 charts.

In the fiddle, you can notice how the linked chart doesn't work when we hover on line chart but it works good if hovered on bar chart.

If bar chart is changed to Line, it works as well. but i need it to be bar.
Thank you

**Comment by Nachtgesicht** [comment]
Hello, i have the same problem.
Fiddle: https://jsfiddle.net/p79ztu8x/

The synchonization works with two line charts, but not with a bar chart and and a line chart.

**Comment by Kristschene** [comment]
Hi folks,
I have the same issue as described above. 
Would be very nice when this will be fixed.

Thank you in advance :)
