### ISSUE TITLE
Trigger selection mode at initial load

### ISSUE THREAD

**Issue by paulpestov** [apexcharts/apexcharts.js#1775]
**Is your feature request related to a problem? Please describe.**	
I want to create a (time series) chart with the possibility to select a certain range on the x-axis. Although it is possible enter the selection mode from the toolbar I'd like have the selection mode initially and omit the toolbar completely.

**Describe the solution you'd like**	
Being able to set how the selection mode should be triggered. For example:
`selection: {
    enabled: true,
    trigger: 'initial' | 'toolbar'
}`

**Describe alternatives you've considered**	
Having the possiblity to assign the internal toolbar button click handler to another callback.

**Comment by EvanJ0hnson** [comment]
Hi @paulpestov, it's possible to enable `selection` by default even if `toolbar` itself is hidden. This could help:
```…
  toolbar: {
    show: false,
    autoSelected: 'selection',
  },
  selection: {
    enabled: true,
  },
…
```

See https://apexcharts.com/docs/options/chart/toolbar/ for details

**Comment by paulpestov** [comment]
Thanks, didn't notice this option!
