### ISSUE TITLE
Rounded corners on stacked bar chart

### ISSUE THREAD

**Issue by naime-hossain** [apexcharts/apexcharts.js#1779]
Any chance to see Rounded Corner working on stacked bar charts? Currently the rounded corners are applied to the bottom bar as well. There should be a rule to apply the rounded corners only for the top bar if there are more that 1 bar on top of each other.
![n1i7wdkj](https://user-images.githubusercontent.com/12586039/87824404-00f69b80-c897-11ea-905c-ba1a741e4558.png)
Thanks

**Comment by StarryFire** [comment]
any updates on this? I want to have rounded tops on stacked bar charts...

**Comment by IsaacSomething** [comment]
Here is an alternative solution using `clip-path`

https://github.com/apexcharts/apexcharts.js/issues/2097

**Comment by junedchhipa** [comment]
Since v3.26.0, there is a property for border-radius which works in stacked bar charts. (It applies the border-radius on the top-most bar)

```
plotOptions: {
  bar: {
    borderRadius: 5
  }
}
```

**Comment by blueeDeveloper** [comment]
@junedchhipa - I have "apexcharts": "^v3.26.1" and i added borderRadius as mentioned by you.  The error is still visible. 
As you can see border radius only gets applied to the last element of the "series" option. If there is no last element in the chart, the border radius doesnot get applied on that bar chart. 
plotOptions: {
  bar: {
    borderRadius: 5
  }
}

<img width="1552" alt="Screen Shot 2021-09-25 at 8 13 17 PM" src="https://user-images.githubusercontent.com/79240323/134792063-351f384c-9ed1-44b7-b27f-82675d4c1c36.png">

**Comment by technika7** [comment]
You can use javascript for this though. Example based on 2 series only.

```
let target = document.querySelectorAll('.apexcharts-series:nth-of-type(1) > path')
  // previous data = prev
  prev.forEach((d, i) => {
  if (d == 0) target[i].classList.add('apex-bar')
})
```

and css

`
.apex-bar {
  clip-path: inset(0% 0% -4px 0% round 4px);
}
`

**Comment by mahmouds12** [comment]
> prev

what is prev?

**Comment by jacky-le-goldenowl** [comment]
> > prev
> 
> what is prev?

This is how I followed technika7's idea. It works for me:

`
const borderRadiusColumns = (id) => {
  const chartEl = document.getElementById(id);
  const target1 = chartEl.querySelectorAll(
    '.apexcharts-series:nth-of-type(1) > path',
  );
  const target2 = chartEl.querySelectorAll(
    '.apexcharts-series:nth-of-type(2) > path',
  );

  target2.forEach((d, i) => {
    if (d.getAttribute('val') === '0' || !d.getAttribute('val'))
      target1[i].classList.add('apex-bar');
  });
};
`

**Comment by mario-hs** [comment]
Based on technika7's solution I did:
`
:deep(div svg g path) {
  clip-path: inset(0% 0% 0px 0% round 33px);
}
`

**Comment by zanzlender** [comment]
Fixed this by filtering out the data that is 0. Just the presence of an element in the array (even if its 0) will create a bar chart section.

e.g. a bar chart which has the section A, B, C, D where it's represented with an array like: [0, 0, 100, 24]

when doing:

```ts
const filteredData = array.filter(x => x !== 0); 
this.chart.updateSeries(filteredData);
```

**Comment by sakilanwar12** [comment]
don't need extra functionality - appex chart already give you the solution :
Follow the link: https://apexcharts.com/docs/options/plotoptions/bar/
``
 plotOptions: {
              bar: {
                borderRadius: 8
       }
``
