### ISSUE TITLE
Make Chart Margins and Padding Optional/Adjustable

### ISSUE THREAD

**Issue by benhaynes** [apexcharts/apexcharts.js#178]
**Is your feature request related to a problem? Please describe.**

We have removed the left axis labels, but can't left-align the chart because the entire element has been translated: 

```
<g class="apexcharts-inner apexcharts-graphical" transform="translate(20, 30)">
```

![screen shot 2018-10-28 at 1 11 05 pm](https://user-images.githubusercontent.com/522079/47619270-3c45ab00-dab3-11e8-8e77-90f343b0bd89.png)

* Red Line: This is the left SVG bound, where we would like to align the chart.
* Green Line: This is where the chart begins because of the translate. Margin should be optional
* Blue Line: This is where the series data starts, this data should also be optional
* Orange Lines: The same data padding on the right side should be optional

**Describe the solution you'd like**

Give options to remove/adjust these margins/padding (currently the only way is to use Sparklines, but this limits other options)

**Describe alternatives you've considered**

Forking repo; manual/external CSS overrides; masking with external elements; etc

**Additional context**

n/a

**Comment by benhaynes** [comment]
Awesome, thank you!

**Comment by junedchhipa** [comment]
Ah! Just checked out one of your repository - **directus**, and I'm really impressed. Keep up the great work.

**Comment by benhaynes** [comment]
Thanks, and likewise! APEXCHARTS has been a pleasure to work with so far!

**Comment by benhaynes** [comment]
Excellent! This seems to be working on our side. Thank you so much for the quick turn-around!

Keep up the great work!

**Comment by navotera** [comment]
Here the result : 
I think there are white space (not very good look)
![image](https://user-images.githubusercontent.com/1424851/57565290-cde08e80-73ed-11e9-8d80-315b68591650.png)

Is there any config to achive like this : 
![image](https://user-images.githubusercontent.com/1424851/57565299-f6688880-73ed-11e9-8f60-f9b236a2fab3.png)


Great Library, Thank

**Comment by junedchhipa** [comment]
@navotera 
Please post a codepen of your example.

**Comment by yairEO** [comment]
@junedchhipa - I found a "bug" or at least an inconsistency regarding your tip to remove padding.

It does not work for a bar chart which has `horizontal: true` in the `plotOptions`

----

I write this because of another bug found for that configuration which I have opened but nobody addressed it... https://github.com/apexcharts/apexcharts.js/issues/815

:(

**Comment by Niall-Kenny** [comment]
Hi there,

just wondering how to remove the whitespace on the left of the graph in react. 
![Screenshot_20191009_121549](https://user-images.githubusercontent.com/45692434/66476895-a1a96680-ea8e-11e9-8a00-42139404b3e8.png)

**Comment by inoda** [comment]
Is there a way to keep the y-axis labels but still remove the extra padding on the left? It's unideal that the only way to get rid of it is by removing helpful labeling.

**Comment by michaeljakob** [comment]
I have the exact same bug. How to remove all the margin there?

**Comment by michaeljakob** [comment]
We fixed it by adding the following CSS to `<apexchart />' in VueJS.

`
#the_chart {
  left: -10px;
  position: relative;
}
`

**Comment by junedchhipa** [comment]
One more way to adjust the left spacing of the y-axis

```javascript
yaxis: {
  labels: {
    offsetX: -10
  }
},
grid: {
  padding: {
    left: -5
  }
}
```

**Comment by internationalhouseofdonald** [comment]
This worked well for me when trying to get a chart to fit inside of a `300px` block-level element.

      yaxis: {
        labels: {
          offsetX: -25,
          rotate: -90,
        },
      },
      grid: {
        padding: {
          left: -25,
        },
      },

![image](https://user-images.githubusercontent.com/20768148/80559664-f3223000-89a3-11ea-975c-ceec394feec2.png)

**Comment by stonehubvn** [comment]
Check it: https://github.com/apexcharts/vue-apexcharts/issues/44#issuecomment-456072048
A full example of your updated [jsfiddle](http://jsfiddle.net/phe7s4Lg/)

**Comment by pacocom** [comment]
I have same problems @Niall-Kenny https://github.com/apexcharts/apexcharts.js/issues/178#issuecomment-539956398.
Imposible to remove this margin!
This library has a lot of bug.

**Comment by junedchhipa** [comment]
@pacocom I have posted a possible solution for the left margin in this [comment](https://github.com/apexcharts/apexcharts.js/issues/178#issuecomment-617360081)

**Comment by pacocom** [comment]
@junedchhipa Thank!

Now, In my case I try
```js
grid: {
  padding: {
    left: -16
  }
}
```
and it works, but I don't know why in another case is letf: -5.

Thanks!

**Comment by menooa25** [comment]
> ```js
>  labels: {
>     offsetX: -10
>   }
> ```

thank you so much for this <3

**Comment by belcorpRaguirre** [comment]
> @junedchhipa - I found a "bug", or at least an inconsistency, regarding your tip to remove padding.
> 
> It does not work for a bar chart which has `horizontal: true` in the `plotOptions`:
> 
> Demo: https://codepen.io/vsync/pen/XvMPGq
> 
> I write this because of another bug found for that configuration which I have opened but nobody addressed it... #815
> 
> :(

hi i have the same problem, any solution for this?

![image](https://user-images.githubusercontent.com/92326891/170785890-08bda2da-f63a-4208-b973-7021980e4740.png)

**Comment by belcorpRaguirre** [comment]
> Here the result : I think there are white space (not very good look) ![image](https://user-images.githubusercontent.com/1424851/57565290-cde08e80-73ed-11e9-8d80-315b68591650.png)
> 
> Is there any config to achive like this : ![image](https://user-images.githubusercontent.com/1424851/57565299-f6688880-73ed-11e9-8f60-f9b236a2fab3.png)
> 
> Great Library, Thank

same problem 

![image](https://user-images.githubusercontent.com/92326891/170786221-595e318b-1433-443e-9ee6-28320df8ef55.png)

**Comment by omerzirh** [comment]
Same problem @junedchhipa 

<img width="1017" alt="Screenshot 2022-06-13 at 14 50 45" src="https://user-images.githubusercontent.com/26231557/173357603-9cd09459-052b-4d4e-ba35-7fba7556d02a.png">

**Comment by omerzirh** [comment]
Same issue  @junedchhipa 

<img width="1029" alt="Screenshot 2022-06-13 at 14 52 29" src="https://user-images.githubusercontent.com/26231557/173357948-ef16e58e-6e45-4232-a507-03aab81c856f.png">

**Comment by HunterSandlin** [comment]
> Same issue @junedchhipa
> 
> <img alt="Screenshot 2022-06-13 at 14 52 29" width="1029" src="https://user-images.githubusercontent.com/26231557/173357948-ef16e58e-6e45-4232-a507-03aab81c856f.png">

Can you share a codepen?

**Comment by omerzirh** [comment]
Sorry, I dont have code anymore. It's resolved by teammate.

**Comment by HunterSandlin** [comment]
Darn, I'm working on a similar thing and want to add those gaps to a bar chart. Thanks for responding anyway! Glad you solved it!

**Comment by eUunice** [comment]
Hi All,
How to delete the blank space after ?

![image](https://user-images.githubusercontent.com/98146166/203730734-6c1f0c62-1e1b-45a7-844e-20c3ae756c2a.png)

**Comment by Viridiris** [comment]
I think some people are responding here with the same issue that I am having. I would like more space to drag the zoom tool. 
I am unable to capture the edge points with the drag zoom tool that you can find here; https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/

I have used padding and it didn't work because the selection does not start until you hit the grid. And adding blank X values also did not really give me the result I wanted, and seems inelegant anyways. Let me know if that is really the only solution here. 

Here is an image of graph and the options object. 
![image](https://user-images.githubusercontent.com/60015291/207426399-2464fc72-f924-4f50-83ce-7953f49bd63c.png)


`var options = {
            colors: ["#FDD023", "#FDD023"],
            series: [{
                name: 'Total KWh',
                data: data_points
            }],
            dataLabels: {
                enabled: false
            },
            stroke: {
                curve: 'straight'
            },
            title: {
                text: 'Billing data by ' + graph_type,
                align: 'middle'
            },
            grid: {
                show: true,
                yaxis: {
                    lines: {
                        show: true
                    }
                },
                borderColor: '#008ffb',
                strokeDashArray: 1,
                padding: {
                    top: 0,
                    right: 50,
                    bottom: 0,
                    left: 50
                },
            },
            chart: {
                type: 'line',
                'options': {
                    spanGaps: true // this is the property I found
                },
                stacked: false,
                height: 350,
                zoom: {
                    type: 'x',
                    enabled: true,
                    autoScaleYaxis: false
                },
                toolbar: {
                    autoSelected: 'zoom'
                },
                events: {
                    markerClick: function(event, chartContext, { seriesIndex, dataPointIndex, config}) {
                        // The last parameter config contains additional information like `seriesIndex` and `dataPointIndex` for cartesian charts
                        console.log('Event!');
                        console.log(dataPointIndex);
                    }
                }
            },
            xaxis: {
                labels: {
                    formatter: function (value) {// The formatter function overrides format property
                        const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
                        let datetime = new Date(value);
                        return months[datetime.getMonth()] + ", "+datetime.getFullYear()

                    },
                },
                axisTicks: {
                    show: true,
                    borderType: 'solid',
                    color: '#78909C',
                    height: 6,
                    offsetX: 0,
                    offsetY: 0
                },
            },
            yaxis: {
                labels: {
                    formatter: function (value) {
                        return Math.round(value * 100) / 100 + " KWh";
                    }
                },
                title: {
                    text: "Total Kilowatt hours",
                    rotate: -90,
                    offsetX: 0,
                    offsetY: 0,
                    style: {
                        color: undefined,
                        fontSize: '12px',
                        fontFamily: 'Helvetica, Arial, sans-serif',
                        fontWeight: 600,
                        cssClass: 'apexcharts-yaxis-title',
                    },
                },
            },
            tooltip: {
                custom: function({series, seriesIndex, dataPointIndex, w}) {
                    var data = w.globals.initialSeries[seriesIndex].data[dataPointIndex];
                    console.log(data);

                    return `<div class="panel-heading">
                                <h1 class="panel-title">
                                    ` + data.xtitle + `
                                </h1>
                            </div>
                            <div class="panel-body">
                                <div class="totals-data-body">
                                    <strong>Total KWh: </strong> ` + data.y + `
                                </div>
                            </div>`;
                }
            }
        }`
        
I ha

**Comment by Seppelec-ntj** [comment]
> > Here the result : I think there are white space (not very good look) ![image](https://user-images.githubusercontent.com/1424851/57565290-cde08e80-73ed-11e9-8d80-315b68591650.png)
> > Is there any config to achive like this : ![image](https://user-images.githubusercontent.com/1424851/57565299-f6688880-73ed-11e9-8f60-f9b236a2fab3.png)
> > Great Library, Thank
> 
> same problem
> 
> ![image](https://user-images.githubusercontent.com/92326891/170786221-595e318b-1433-443e-9ee6-28320df8ef55.png)

Hi,
In my case to solve the spaces I used the minimum and maximum. I passed the date of my first value and the date of my last value. 
I put this code:
xaxis: {
      type: 'datetime',
      min: initialDatetime,
      max: finalDatetime,
    },
I hope that helps.
Best regards.

**Comment by MizuBishi** [comment]
I am still having the the same problem. I tried everything which was mentioned in this chat. I cannot set fixed negative values (grid - padding- left) because therefore it depends on the screensize and fits not properly. Has anybody a solution to this?

**Comment by guestisp** [comment]
any idea on how to fix this ?
having the white margin is not beautiful. as workaround i'm adding empty points but that's not good

**Comment by Naiimtj** [comment]
In my case, I added the "min" option to xaxis, importing the first starting value. In this case, it's for time. I hope that helps you :)

Example: 
`xaxis: {
      type: 'datetime',
      min: initialDatetime,
      labels: {
        datetimeUTC: false,
        offsetY: 3,
        formatter(value) {
          const mydate = new Date(value);
          const minuts = mydate.getMinutes(value) < 10 ? `0${mydate.getMinutes(value)}` : mydate.getMinutes(value);

          const mydatestr = `${mydate.getHours()}:${minuts}`;
          return mydatestr;
        },
      },
      title: {
        text: t('Time'),
      },
    },`
