### ISSUE TITLE
Chart does not re-render when parent width changes 

### ISSUE THREAD

**Issue by paulgeorge92** [apexcharts/apexcharts.js#1780]
# Bug report

I am using react version of apexcharts and I am rendering a line chart in a div with 100% width. I have a menu drawer that is expended by default. When I collapse the drawer, the apex chart does not re-render and when I expand the drawer, chart overlaps with sibling contents. I have set the redrawOnParentResize as true. 

Codepen: https://codepen.io/paul_george/pen/yLeQJaq

**Comment by chinna2580** [comment]
`<div style={{ width: '97%' }}>
                                <ApexChart
                                  options={this.setGraphData(null, 'graphStyle')}
                                  series={this.setGraphData(currentAssetFieldValues, 'graphValues')}
                                  type="area"
                                  height="40"
                                />
                              </div>`
enclose the component inside div set the width to less than 100%

**Comment by junedchhipa** [comment]
@paulgeorge92 You were actually changing the width of the chart itself, not the parent.
I tried
```javascript
document.getElementById('chart').style.width="50%"
```
and it worked fine.
