### ISSUE TITLE
Alt tag on x-axis showing commas

### ISSUE THREAD

**Issue by sandeept07** [apexcharts/apexcharts.js#1784]
Hello,

I have 2 questions.

1. When I move mouse over the values on x-axis, it shows alt/title tag. Can this be avoided?
Note: This doesn't happen with values on y-axis.

2. For longer x-axis labels, alt/title tag shows up as comma separated values. Can this be avoided?
Please [click here](https://prnt.sc/tkm4a7) to see screenshot.

Thanks,
Sandeep

**Comment by junedchhipa** [comment]
Apparently, it's a bug that will be addressed soon.
Thanks for reporting.

**Comment by junedchhipa** [comment]
[Commit](https://github.com/apexcharts/apexcharts.js/commit/ae373f07aba85f2bca0f207d931073e146347728) fixes it. A patch will be released soon.

**Comment by sandeept07** [comment]
Thanks @junedchhipa for the prompt reply.
But, I am not using Angular, Vue or React libraries. I have used JS library which requires only **apexcharts.min.js** for now to run graphs.

Note : I need only basic graphs like bar, line etc. for now. So, I have not added other js files in my code to keep file size to minimum.

Is there any fix to be done in apexcharts.min.js?

Thanks,
Sandeep

**Comment by junedchhipa** [comment]
Are you loading Apexcharts using this [CDN](https://cdn.jsdelivr.net/npm/apexcharts)?
If yes, you don't have to do any changes. When a new update is released, the above file will be automatically updated.

**Comment by sandeept07** [comment]
Yes, you are right.
I'll wait for the update.

Thanks a lot, @junedchhipa for the prompt response :) and keep up the great work !!

Thanks,
Sandeep

**Comment by sandeept07** [comment]
Hello,

I updated apexcharts.min.js ([CDN](https://cdn.jsdelivr.net/npm/apexcharts)) file.
The problem is gone.

Thanks,
Sandeep
