### ISSUE TITLE
Bar chart tooltip not aligned properly

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#179]
## Codepen

https://codepen.io/jimfilippou-the-animator/pen/pxBEeP

## Explanation

Using version `2.1.8`, when hovering above bar charts, you can see that the tooltip is not aligned properly.

- What is the behavior you expect?
Proper alignment

- What is happening instead?

![untitled](https://user-images.githubusercontent.com/6877046/47640772-0e24a180-db6d-11e8-9d11-d819c37d7172.png)

- What error message are you getting?
No error message.

**Comment by junedchhipa** [comment]
I remember the change I did for it. Will revert.
It's difficult to catch these UI things with unit tests. I will set up more e2e tests using puppeteer in the future.
