### ISSUE TITLE
Slice amount of data points + categories to x number

### ISSUE THREAD

**Issue by cryptobench** [apexcharts/apexcharts.js#1793]
Hello. I have a graph displaying countries and a value related to that country, so the total amount of data points will always equal the amount of countries. This however can cause the graphs text and bars to get really small due to the amount of countries. Is there any way that I can limit it to show x countries?

I'm trying to create a bar chart if that's relevant.

Here's an example of the thing i'm experiencing:
![image](https://user-images.githubusercontent.com/33448819/88355547-4b7b8a80-cd65-11ea-9eda-1de449d9ef24.png)

Here's what I **want** to achieve:
![image](https://user-images.githubusercontent.com/33448819/88355574-60f0b480-cd65-11ea-955e-2db7337854e1.png)
The above was done by slicing the array received by the API, but i'd rather do this natively as i limits the data output of the **Download CSV** button

**Comment by junedchhipa** [comment]
You can use the xaxis.min and xaxis.max to create a range and omit drawings of the other bars.
Along with that, you will need to change xaxis.tickPlacement: 'on'

```javascript
xaxis: {
  tickPlacement: 'on',
  min: 1,
  max: 4
}
```

![Jul-24-2020 15-41-29](https://user-images.githubusercontent.com/17950663/88381504-2e29d900-cdc4-11ea-91d6-2b54c64daf13.gif)

```javascript
function showAllCountries() {
  chart.updateOptions({
    xaxis: {
      min: undefined,
      max: undefined
    }
  })
}
```

Full example - https://codepen.io/apexcharts/pen/abdMqQW

**Comment by cryptobench** [comment]
Hi, thanks for the reply. It worked.

Only thing is that when I have a lot of data and I use the min max values to limit the amount shown, it will still make the bars very thin even though there's space for thicker bars. Is there any way I can make it thicker?

Example of the thing i'm experiencing - Text is not rendered properly due to thin bars
![image](https://user-images.githubusercontent.com/33448819/88412292-9b943480-cdd9-11ea-8780-add8cf6d37de.png)

When all countries are shown the bars are pretty much identical width:
![image](https://user-images.githubusercontent.com/33448819/88412670-35f47800-cdda-11ea-8bdc-792cc79a9b49.png)

If I limit the dataset by slicing the array as my own previous methods, then the bars are rendered thick and proportional to the graph. Is this intentional or can I do something about this?

**Comment by junedchhipa** [comment]
Yeah, the width of the bar is decided based on the total number of data-points initially (which should be changed based on x-axis min/max, but that's not possible currently).
Hence, I would suggest you manually slice the data as a workaround.

**Comment by cryptobench** [comment]
Noted down. Thanks for the response :-)

**Comment by paulovpereira** [comment]
Hello @junedchhipa, I am facing same problem as stated in this issue and I am trying to implemented the recommended workaround. 

Is there any intent to fix this on future releases? I noticed that for `datetime` xaxis type the bar widths are corrected resized. The problem seems to be related to `category` type.
