### ISSUE TITLE
Timeline chart horizontal bars are only taking proportional part of available space

### ISSUE THREAD

**Issue by zergeborg** [apexcharts/apexcharts.js#1799]
# Bug report
When using the timeline chart if the series only have two different names, let's say `A` and `B` and the data `x` values are all different respectively, then the bar will be rendered taking proportionally small part of the available space only.

## Codepen

Demonstration of the issue [HERE](https://codepen.io/fogetti/pen/ZEQNWqz).

## Explanation

- What is the behavior you expect?
I expect the bars to fill all the available space

- What is happening instead?
The bars don't take all space

- What error message are you getting?
None

**Comment by Danita** [comment]
I have the same problem. My ranges are guaranteed to not overlap, so I need to show all series for the same role on the same "track". I've tried setting `plotOptions.bar.rangeBarOverlap` to `true` and it makes no difference.

![imagen](https://user-images.githubusercontent.com/754783/91350709-73736900-e7bd-11ea-8876-ea91211eb1f9.png)

**Comment by mamiaro** [comment]
Any update on this ?

**Comment by pawanvivekananda** [comment]
Same here, Any update ?

**Comment by junedchhipa** [comment]
This is fixed in this [PR](https://github.com/apexcharts/apexcharts.js/pull/1924/)
The new property will be `plotOptions.bar.rangeBarGroupRows`

It will be released in **v3.22.0**

**Comment by junedchhipa** [comment]
https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

**Comment by junedchhipa** [comment]
`plotOptions.bar.rangeBarGroupRows: false`
![uyyuhdo1](https://user-images.githubusercontent.com/17950663/95425235-974fd000-0961-11eb-90a8-5a7f3ca0e873.png)

`plotOptions.bar.rangeBarGroupRows: true`
![wcp3qcsu](https://user-images.githubusercontent.com/17950663/95425278-a8004600-0961-11eb-87d2-ffdb44b63728.png)
