### ISSUE TITLE
Zoom by default

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#18]
Would be nice to auto-select the Zoom tool after initialization

**Comment by junedchhipa** [comment]
Good suggestion. Taken into consideration. 
Will be given as an option - `options.chart.toolbar.autoselected = 'zoom'`
This way user can have zoom/pan whatever they prefer

**Comment by pribilinskiy** [comment]
@junedchhipa Nice! From the plethora of charting libraries Apex stands out with user-friendly API, modern UI, nice docs, and now even quick dev response. Keep up the good work

**Comment by junedchhipa** [comment]
Thanks for the kind words!
