### ISSUE TITLE
Setting the states.active.filter.type to 'none' does not work

### ISSUE THREAD

**Issue by johuhype** [apexcharts/apexcharts.js#180]
Type 'none' for the active state does not work:

                        states: {
                            active: {
                                 filter: { type: 'none', value: 1 }
                            }
                        }

Instead of nothing happening, the selected item will get highlighted.

However, it is possible to use type-darken and value 1 as long as its not working. This will get the desired none effect:
                        states: {
                            active: {
                                 filter: { type: 'darken', value: 1 }
                            }
                        }

**Comment by junedchhipa** [comment]
I cannot reproduce this issue.
Setting `filter.type: none` works as expected.

Can you create a codepen, please?

**Comment by johuhype** [comment]
https://codepen.io/anon/pen/RemGxm

You need to enable the responsive mode in chrome. Then try to click the blue circle with the round mouse cursor. The hover effect will become active. 

I can fix this by changing type none to darken or if I also put 

```
                             hover: {
                                 filter: { type: 'none' }
                             }
```

there. But the hover effect should probably not be activated by clicking.

**Comment by junedchhipa** [comment]
The hover effect is not activated by the click, but it is activated when you move the mouse over the path.

So, if you don't want any states, then turning off both active and hover is the correct configuration.
```javascript
states: {
    hover: {
       filter: {
        type: 'none'
       }
    },
    active: {
      filter: { type: 'none' }
    },
  }
}
```

**Comment by johuhype** [comment]
No, in responsive mode, there is no hover (as of touch mode with smart devices).

I agree that hover will be activated when you are in desktop mode and just move the mouse over the path.
When you are in touch mode, it is not activated which is correct as there is no "mouse over". 
However it will get activated there when you click it in the right spot of the blue circle color. Which is not correct I think.

**Comment by junedchhipa** [comment]
@johuhype I misunderstood your previous comment. It's clear now.
I will make the corrections, thank you.
