### ISSUE TITLE
To be able to grab and move data points across the Canvas.

### ISSUE THREAD

**Issue by zekageri** [apexcharts/apexcharts.js#1800]
I have seen on others charts that you can grab and move data points in the grid system.

I have searched for that feature inside apexcharts but i can't find it anywhere.
It would be really awesome if the user would be able to create the data just like this, when grabbing data points and moving it to another location inside the chart.

**Comment by junedchhipa** [comment]
Sorry, but that's not possible currently.

**Comment by zekageri** [comment]
Thank you!
