### ISSUE TITLE
Problem with scale of Y-Axis 

### ISSUE THREAD

**Issue by github-rj** [apexcharts/apexcharts.js#1801]
# Bug report
the second serie dosnt use  the scale of the first serie. if two series have the same axis and max property was set.  

## Codepen
https://codepen.io/github-rj/pen/qBbGVMo

## Explanation

- What is the behavior you expect?
![image](https://user-images.githubusercontent.com/21079928/88676569-84608a00-d0ec-11ea-96be-7900b93c0f20.png)

- What is happening instead?
![image](https://user-images.githubusercontent.com/21079928/88676419-52e7be80-d0ec-11ea-8065-9aa2bc60c84a.png)

In this example, i have two series :

- serie-1 and serie-2 have axis 0.

serie-1 has Y-Axis Properties: 
` {
      seriesName: "Serie1",
      max :41
    }`
serie-2 has Y-Axis Properties:
`{
      show: false,
      seriesName: "Serie1",
    }`

I expected Series-2 to be the same scale as Series-1.

**Comment by blahbla** [comment]
I have been struggling with the same bug as I need zoom functionality on a shared multi axis. I tried manually setting min and max in the zoomed event. It almost worked except for when specifying the "max" property it seems to detach the series from the shared y axis. Specifying "min" works as expected.
(If you remove "max :41" in the example it behaves as expected)

**Comment by junedchhipa** [comment]
This is no longer an issue as tested on v3.54.1
