### ISSUE TITLE
Cannot set height on any chart

### ISSUE THREAD

**Issue by akmur** [apexcharts/apexcharts.js#1803]
# Bug report

## Codesandbox

[Codesandbox](https://codesandbox.io/s/react-basic-example-r91xf?file=/src/App.js)

## Explanation

- What is the behavior you expect?
I expect to be able to determine the height of the stacked horizontal bar using the "height" option.
I also tried to set the height of the chart through the parent's div, by setting a fixed height, but it seems to not work.

- What is happening instead?
The height of the stacked horizontal bar in the example cannot be set. Everything is always "responsive". I also tried with a Pie chart and I also cannot set the height there.

- What error message are you getting?
No error message, but I can't resize the height of the chart.

## Note
In this CodePen (not using the react wrapper) it seems to be working, but I am not sure if the issue is the react wrapper or something else.
Also, in your basic example trying to add a height doesn't work.

[Codesandbox](https://codesandbox.io/s/react-basic-example-106dq)

**Comment by akmur** [comment]
I have found a solution in setting the `height` in the Component, so like:

```
          height="200px"
          options={options}
          series={series}
          type="bar"
```

So the problem is solved in this way, but I still don't understand if the `height` option in the config should work or not :)

**Comment by junedchhipa** [comment]
In Vue/React, the height prop in the component overrides the `height` key in options.
So, the behavior is correct. Glad you solved it.
