### ISSUE TITLE
zooming on synced charts do not trigger events on whole group

### ISSUE THREAD

**Issue by willsalz** [apexcharts/apexcharts.js#1809]
# Bug report
![zoom sync event](https://user-images.githubusercontent.com/1295795/88972862-0c6c9e00-d26b-11ea-84c5-925d23c6da9c.gif)

## Codepen
Link [here](https://codepen.io/willsalz/pen/YzwoBoN). All code taken directly from the [synched charts demo](https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/), with the addition of some 'console.debug' lines to demonstrate the bug.

## Explanation

- What is the behavior you expect?
when I zoom on one of the synced charts, I expect the zoom events to trigger for all charts in the sync group.

- What is happening instead?
zoom events do not trigger events on charts except for the chart that the user is interacting with. caveat: resetting the zoom with the 'home' button _does_ trigger zoom events 🤷 .

- What error message are you getting?
no error message

**Comment by willsalz** [comment]
cc @ rafaoliverce

**Comment by ColeTown** [comment]
Has anything ever been done about this issue? I am attempting to utilize a zoom event to reload the series so I can maintain resolution at multiple Zoom levels. I can only trigger my series update from a zoom event on the chart that was interacted with, and the rest of the charts in the group maintain their lower/higher resolution but just change their viewport. Any work around?
