### ISSUE TITLE
legend-mouseover-inactive states are being reset after chart update

### ISSUE THREAD

**Issue by ondrej-vipo** [apexcharts/apexcharts.js#1816]
# Bug report

## Codepen

https://codepen.io/ovipo/pen/QWNLYvd
(based on realtime demo from apexcharts website)

## Explanation

- What is the behavior you expect?
   - When I hover the series name in the legend the other lines should fade out and stay like this until the mouse is moved.

- What is happening instead?
   - The other series reset to default view after chart update

- What error message are you getting?
   - No error message

**Comment by philippks** [comment]
The same happens when I click on one item in the legend. The corresponding line first disappears, but comes back on update.

**Comment by topisani** [comment]
I am having this issue as well - most importantly, when i hide some series, they come back the next time updateSeries is called
