### ISSUE TITLE
Remove colon from tooltip

### ISSUE THREAD

**Issue by madza91** [apexcharts/apexcharts.js#1818]
# Bug report

This is a very minor issue of chart hint without "name".

## Codepen

- [3.19.2 demo](https://codesandbox.io/s/vue-basic-example-pzbvr)
- [3.19.3 demo](https://codesandbox.io/s/vue-basic-example-45bl5)

## Explanation

- What is the behavior you expect?
Hint over chart bar needs to be able to show value without `name` option
- What is happening instead?
When `name` option in `series` prop is an empty string, it shows colon before the value
When `name` doesn't exist in `series`, it shows some generated name as `series-1`

### More details
In version 3.19.2 everything works fine, but in v3.19.3 is something changed and I found [this commit change](https://github.com/apexcharts/apexcharts.js/commit/2d39d2c39551f687e2245ebf18ddf3d85cedbbd6#diff-e6f0764199d7a809812507d70cefeb7cR3756) in `dist/apexcharts.js`

In this [3.19.2 demo](https://codesandbox.io/s/vue-basic-example-pzbvr) you can see that Hint is showing properly with an empty string as name key for `series` prop.

In this [3.19.3 demo](https://codesandbox.io/s/vue-basic-example-45bl5) you can see colon before value if `name` is an empty string, but if you remove `name`, then you will get `series-1` as hint title before the colon.

My question is, is there any way to show chart hint without `name` - with value only or this is an issue?

Thanks!

**Comment by junedchhipa** [comment]
Do this

```javascript
tooltip: {
  y: {
    title: {
      formatter(seriesName) {
        return seriesName
      }
    }
  }
}
```
