### ISSUE TITLE
Improve bar chart borderRadius

### ISSUE THREAD

**Issue by pacocom** [apexcharts/apexcharts.js#1821]
As you can see, the endingShape & startingShape are very ugly for bar chart.
```js
plotOptions: {
  bar: {
    horizontal: false,
    columnWidth: '50%',
    distributed: true,
    endingShape: 'rounded',
    startingShape: 'rounded',
  },
},
```
![image](https://user-images.githubusercontent.com/7735329/89524635-3121c200-d7e5-11ea-9ed5-fa76c389938f.png)
![image](https://user-images.githubusercontent.com/7735329/89524651-3979fd00-d7e5-11ea-994f-e835957e7ef3.png)

Please change 'flat' or 'rounded' to number (or add the possibility to use number) to create custom border radius for bar column.
For example (similar in HighCharts):
https://github.com/highcharts/rounded-corners & https://jsfiddle.net/BlackLabel/tdp1y0wb
or
https://github.com/bellstrand/highcharts-border-radius

**Comment by diwakarsingh95** [comment]
@junedchhipa any progress on this? Can you please give an option to set border radius for vertical bars same as backgroundBarRadius option in bar plotOptions? 
![Screenshot from 2020-09-23 19-20-12](https://user-images.githubusercontent.com/42492536/94021829-15dd3700-fdd2-11ea-9180-2fd32c189427.png)

**Comment by IsaacSomething** [comment]
there is a little css trick you can use here with css `clip-path` , You will have to tweek it so meet your specific styling needs and you have to disable animations on the chart ( you might be able to keep animations if you apple the style after the animations have been set with something like `renderer2`

```
.apexcharts-bar-series.apexcharts-plot-series
  .apexcharts-series:nth-child(1)
  path {
  clip-path: inset(0% 0% -31% 0% round 8px);
}
```

This specific style was using with a stacked bar, it might be a bit different with a normal bar chart

**Comment by junedchhipa** [comment]
Since v3.26.0, there is a new property called `borderRadius` which allows setting the rounded borders manually.

```javascript
plotOptions: {
  bar: {
    borderRadius: 5
  }
}
```

**Comment by marssantoso** [comment]
Can borderRadius accept percentage @junedchhipa? The current implementation looks weird especially when the column width changes.

Here is what I want. Basically perfect round corners.

![image](https://user-images.githubusercontent.com/21955316/112792349-7bfe8b80-908d-11eb-9505-6404027971f7.png)

But here it is when the column width becomes too large.

![image](https://user-images.githubusercontent.com/21955316/112792594-f8916a00-908d-11eb-9067-4a44110f07a5.png)

It gets even weirder when the column width gets too small.

![image](https://user-images.githubusercontent.com/21955316/112792699-2aa2cc00-908e-11eb-95d2-87bf281f5222.png)

Thx for the great lib btw.

**Comment by Thimows** [comment]
+1 

Percentages for the borderRadius will make way more sense. Having these same issues as well.
