### ISSUE TITLE
Any click on chart button makes the page scrol to top

### ISSUE THREAD

**Issue by EnzoKilm** [apexcharts/apexcharts.js#1825]
# Bug report

There is my diagram :
![image](https://user-images.githubusercontent.com/20820044/89636700-51b35000-d8a9-11ea-8b01-275294714545.png)

## Explanation

- What is the behavior you expect?
When I click for example on a line label, the line should disappear and nothing more should happen.
- What is happening instead?
The line disappear but the page automatically scrolls up for no reason. This not happen only when I click on a label but also when I click on the zoom in/out buttons and so on.
- What error message are you getting?
I'm getting no error message.

**Comment by junedchhipa** [comment]
Can you reproduce this in a codepen?

**Comment by EnzoKilm** [comment]
> Can you reproduce this in a codepen?

Might be a little complicated, my whole chart is automated by database queries and twig variables (I work under Symfony 5). Tell me what else can I do ?

**Comment by bn3t** [comment]
I have the same problem: Here is my code sandbox which reproduce it: https://codesandbox.io/s/react-apexcharts-bar-show-hide-serie-x35jt?file=/src/App.js

You just have to make the window small enough so that there are scroll bars, scroll to the bottom, activate/deactive legends. It scroll to the top each time the chart renders.

**Comment by fredli74** [comment]
I am experiencing the same problem with one of my applications where I have a chart that updates on a timer. On every update, it scrolls the page to the top.

This was a bug introduced in Apexcharts version 3.19.3, my workaround has been pinning the version to 3.19.2 in my package.json file.

I tested it in your codesandbox and it seems to solve the click problem as well.

`  "apexcharts": "3.19.2",`

**Comment by junedchhipa** [comment]
Thanks for reproducing it. I will take a look soon.
