### ISSUE TITLE
Since 3.20: Bar chart throws exception in case of duplicate x values

### ISSUE THREAD

**Issue by Michi-4G** [apexcharts/apexcharts.js#1826]
# Bug report

## Codepen
[https://codepen.io/Crossing/pen/ZEWGBjL](https://codepen.io/Crossing/pen/ZEWGBjL)

## Explanation

- What is the behavior you expect?
The 'old' behavior as of version 3.19.3:
![Screen Shot 2020-08-09 at 12 56 09](https://user-images.githubusercontent.com/1016675/89730554-f7002c80-da3f-11ea-9c0f-681724eb5a81.png)

- What is happening instead?
Subsequent labels are not rendered anymore. Exception is thrown.
![Screen Shot 2020-08-09 at 12 55 43](https://user-images.githubusercontent.com/1016675/89730557-00899480-da40-11ea-8955-13dfdad7d634.png)

- What error message are you getting?
![Screen Shot 2020-08-09 at 12 55 55](https://user-images.githubusercontent.com/1016675/89730571-15febe80-da40-11ea-826d-cb481a85f07b.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it

**Comment by Michi-4G** [comment]
Wow, that was fast! Thanks a lot for the fix and the great work you are doing here 😊
