### ISSUE TITLE
Bars are cutting out when zoom icons are enabled

### ISSUE THREAD

**Issue by sandeept07** [apexcharts/apexcharts.js#1827]
Hello,

When I enable zoom icons, bars on left & right cut out.

`xaxis:{
	tickPlacement: 'on'
}`

Note : This problem is not seen when I have 3 or 4 bars in each group. This one has 6 bars in each group.

[Multiple bar - zoom disabled - graph looks right](https://prnt.sc/twlp9w)

[Multiple bar - zoom enabled - graph cuts out on left & right](https://prnt.sc/twlphi)

Is there any solution?

Thanks,
Sandeep

**Comment by junedchhipa** [comment]
Try adding grid padding to the left and right

```javascript
grid: {
  padding: {
    left: 50,
    right: 50
  }
}
```

**Comment by sandeept07** [comment]
Works well !!
Thanks @junedchhipa :)
