### ISSUE TITLE
Pie Error path attribute

### ISSUE THREAD

**Issue by Aab19** [apexcharts/apexcharts.js#1829]
![image](https://user-images.githubusercontent.com/23131387/89755660-617d9f00-db0a-11ea-967e-b1ee5f98febd.png)

![image](https://user-images.githubusercontent.com/23131387/89756717-8cb5bd80-db0d-11ea-9bb5-a09b077ab668.png)

The pie chart does not appear, only labels in vue apexcharts.
Apexcharts and Vue Apexcharts installed is latest version.

`<apexchart type="pie" width="380" :options="chartOptions" :series="series"></apexchart>`

`series: [44, 55, 13, 43, 22],
		chartOptions: {
			chart: {
				width: 380,
				type: 'pie',
			},
			labels: ['Team A', 'Team B', 'Team C', 'Team D', 'Team E'],
		},
`

**Comment by junedchhipa** [comment]
I cannot reproduce this.
Please create a codesandbox to allow easy reproduction.

**Comment by Aab19** [comment]
> I cannot reproduce this.
> Please create a codesandbox to allow easy reproduction.

https://codesandbox.io/s/vue-basic-example-oivdh?file=/src/components/Chart.component.vue

In sandbox apexcharts working fine,but in my nuxt project pie chart couldn't working.
