### ISSUE TITLE
Reverse Y Axis Values

### ISSUE THREAD

**Issue by blakeyc** [apexcharts/apexcharts.js#183]
Couldn't find anything in the docs, is it possible to reverse the Y axis so values go from high to low instead of the usual low to high?

**Comment by junedchhipa** [comment]
Currently, no direct option to flip the Y-axis, but can be easily achieved by tweaking the data-values and y-axis formatter.

Here is something I tried by inverting all data-values, then formatting `yaxis.labels.formatter`
```javascript
var seriesData = [10, 41, 35, 51, 49, 62, 69, 91, 148];
var inversedData = seriesData.map((s) => {
  return s * -1
})

var options2 = {
    chart: {
        type: 'line',
    },
    series: [{
        data: inversedData
    }],
    yaxis: {
        labels: {
        formatter: function(val) {
            return val * -1;
        }
        }
    }
}
```

![screen shot 2018-10-31 at 1 04 22 am](https://user-images.githubusercontent.com/17950663/47745164-09fd9e80-dca9-11e8-82c5-5d64e02cf04e.png)


[Codepen Demo](https://codepen.io/junedchhipa/pen/ePaqOZ)

**Comment by blakeyc** [comment]
Thanks will give this a try.

**Comment by junedchhipa** [comment]
An option to reverse flip y-axis is added in v3.6.0.
So, now you can just do
```javascript
yaxis: {
  reversed: true
}
```

**Comment by haktansuren** [comment]
guys @junedchhipa provided correct information. stop down voting it please :)

Source: https://apexcharts.com/docs/options/yaxis/

**Comment by ilkou** [comment]
`v3.31.0` and it's not working !

**Comment by SanjayK277** [comment]
This is wrong answer

**Comment by myone1010** [comment]
> An option to reverse flip y-axis is added in v3.6.0. So, now you can just do
> 
> ```js
> yaxis: {
>   reversed: true
> }
> ```

it works well. Thanks
