### ISSUE TITLE
Datalabels not always shown on scatter chart

### ISSUE THREAD

**Issue by megerlie** [apexcharts/apexcharts.js#1831]
https://codepen.io/megerlie/pen/MWywLRb

here is codepen illustrating the problem. I assume that datalabels should always be visible. My guess it that chart calculate which labels to display, but do it in a bit strange way. Here is real usage screenshot:
![image](https://user-images.githubusercontent.com/50179041/89798130-796a1880-db34-11ea-8e80-2c779108781a.png)

**Comment by junedchhipa** [comment]
The data-labels display fine as of v3.49.1 for the submitted codepen.
Closing as no more relevant.
