### ISSUE TITLE
Heatmap: setting dataLabel fontSize to "inherit" removes label

### ISSUE THREAD

**Issue by DavidSvetlik** [apexcharts/apexcharts.js#1838]
# Bug report

## Explanation

I want to enable dataLabels in heatmap with:

```
options.dataLabels = {
	enabled: true,
	style: {
		fontFamily: "inherit",
		fontSize: "inherit"
	}
};
```

Problem is with that `fontSize` property and its value - when set to `inherit`, label disappears. It's strange because everywhere else I used it (axes, tooltips), `inherit` works just fine.

Thank you for any help,
David Svetlik

**Comment by junedchhipa** [comment]
Thanks for reporting the bug.
Can you please set up a [codepen](https://codepen.io/apexcharts/pen/abdMqQW) demo, so I can reproduce the issue easily?

**Comment by DavidSvetlik** [comment]
@junedchhipa 

There you go:

https://codepen.io/davidsvetlik/pen/mdPPvPO

If you remove `fontSize: "inherit"` line, dataLabels reappear.
