### ISSUE TITLE
How can I draw an area chart from y.min to y.max values (Range Area Charts)

### ISSUE THREAD

**Issue by Dimanoid** [apexcharts/apexcharts.js#184]
Basic area charts are drawn from x-axis (from zero) to some value, but I need to draw an area of min-max ranges. Someshing like on the attached picture. Can I achieve that with apexcharts?
![area](https://user-images.githubusercontent.com/1387749/47773988-334c1800-dd05-11e8-9f9e-311c8ca4d3f3.PNG)

**Comment by Dimanoid** [comment]
Yes, I was not sure how this kind of charts are "officially" called :)
Would be nice to have such charts, thx.

**Comment by crazyTweek** [comment]
Hi @junedchhipa ! 
Do you plan to support this feature in the future? :) 
best, Florian

**Comment by pvictor** [comment]
+1 😃 🙏

**Comment by bennycode** [comment]
This would be super helpful to chart technical indicators, like Bollinger Bands. 🤩

**Comment by Florian-Gate** [comment]
+1

**Comment by contepas** [comment]
+1

**Comment by benbenik** [comment]
Range Area Chart, exactly what I am looking for. From a data[] perspective, I reckon that it would be a neater solution to use the 'confidence interval' approach (i.e. Issue #51). The reason being that one data[{x: 1, y:10,15}] structure for the Range area chart (high, low) and another for a line in between (e.g. data[{x:1, y:12.5}]) seems less tidy than allowing a data[{x: 1, y:12.5,10,15}] which represents both the line and the confidence interval/area. If one does not want to use the line (in the middle), null could be used. There could be use cases where the confidence interval may not be symmetrical. Of course many solutions could be thought of, but after some thought I wanted to both reflect on this issue and say that ApexCharts is awesome! Currently trying to put a Standard deviation cone projecting into the future over stock charts... An 'inverted fill area' (filling up instead of down) doesn't exist, which brings me here :) Keep up the great work, performance, MIT license, structure and awesome documentation!

**Comment by NetZissou** [comment]
This will be really useful to plot confidence intervals from the predictive model output. Please consider adding this feature in the near future! Great development! Thank you!

**Comment by mspinelli** [comment]
Prediction / Confidence interval bands are necessary for plotting forecasts. Can I suggest making it possible to do different bands (e.g. 80% in a lighter color and 95% in a darker color) like the following:

![image](https://user-images.githubusercontent.com/651748/126841262-3af6b04e-2139-42a7-905b-0d5b20d450c5.png)

**Comment by NetZissou** [comment]
I have a workaround by customizing the area charts' opacity. The result looks like this:
![image](https://user-images.githubusercontent.com/48858129/126905996-24e03db9-be4c-443d-b9e1-fb445b9ecda0.png)

**Comment by ManPhamQuang** [comment]
@NetZissou Hello, your workaround looks really good 👍, could you share how you achieved this? I'm looking to implement something similar to this.

**Comment by acegikmedia** [comment]
+1 to have this officially supported.   I did manage to come up with a workaround in the meantime.

I plotted the upper and lower bounds using a line chart.  Then wrote a short script to find the d attribute for each of the two paths.  You can then merge the XY points to generate a polygon and add it back into the chart SVG.  This gets regenerated on every 'updated' event, and so far has worked out rather well.

![Screenshot](https://user-images.githubusercontent.com/23068600/135368510-7ac9c56b-5c4a-42be-8f48-a3baaaf28014.png)

**Comment by mspinelli** [comment]
> +1 to have this officially supported. I did manage to come up with a workaround in the meantime.
> 
> I plotted the upper and lower bounds using a line chart. Then wrote a short script to find the d attribute for each of the two paths. You can then merge the XY points to generate a polygon and add it back into the chart SVG. This gets regenerated on every 'updated' event, and so far has worked out rather well.
> 
> ![Screenshot](https://user-images.githubusercontent.com/23068600/135368510-7ac9c56b-5c4a-42be-8f48-a3baaaf28014.png)

Can you share this script (or generalize it and share)?

**Comment by teleksterling** [comment]
My issue is that I am using stacked area charts with transparent fill, but the upper series' fill is visible through the lower series one. I suspect that a solution to this issue (allowing area fill to be bounded by something other than x-axis i.e. another series) would/could be applied to address mine. 

From a logistics/etiquette point of view - should I open a new issue?

**Comment by juanmiguel431** [comment]
Why is this request closed? 
I was trying to migrate from Telerik to Apex Chart but now I'm facing this issue.

![image](https://user-images.githubusercontent.com/10950943/181372620-75a4ddf1-aebc-464f-850d-b9b837035031.png)

**Comment by placid2000** [comment]
It looks like Apexchart does not propose any api to create Range Areas yet, which would be very nice feature. Can this issue be reopened?

**Comment by MyNameIsAlaa** [comment]
is this type of charts possible yet?

**Comment by mspinelli** [comment]
@junedchhipa Thanks for reopening this!! Would love to see the ability to have confidence/prediction intervals added as a ranged area.

**Comment by junedchhipa** [comment]
It's coming very soon. The next release (v3.36.0) will have this.

<img width="650" alt="Screenshot 2022-10-08 at 12 04 36 PM" src="https://user-images.githubusercontent.com/17950663/194693507-d5104036-99fe-4cbc-b816-3d10c53a19a4.png">

**Comment by junedchhipa** [comment]
Released v3.36.0
https://apexcharts.com/javascript-chart-demos/range-area-charts/basic/

**Comment by HansHan111** [comment]
hello, can you give me range area chart sample code, please?

**Comment by benbenik** [comment]
> hello, can you give me range area chart sample code, please?

@HansHan111, did you visit the link junedchhipa posted? It's not like you earn a hundred bucks, like the show Jeopardy where you get the answer and then ask a question in reply.

**Comment by lewisjr** [comment]
I managed:

![image](https://github.com/user-attachments/assets/159d9f68-6c2c-4c9c-9109-c4e8e3891c31)

You can get the ApexProvided range code [here](https://apexcharts.com/javascript-chart-demos/range-area-charts/combo/). What you need to understand is the order of your data in the `series` param and the number of said series'; That way you can tweak the opacity of each line/range in `fill.opacity`, the colour of each line/range in `colors`, and the thickness of each line/range in `strole.width`.

For me the scale was really small given the ranges(called spread in the image above) between both lines are less than 1, so I added a `min` and `max` to `y-axis` for better visualisation.
