### ISSUE TITLE
Bumpy graphs with the "smooth" line option

### ISSUE THREAD

**Issue by Narcha** [apexcharts/apexcharts.js#1844]
**Is your feature request related to a problem? Please describe.**	
The "smooth" line option's interpolation produces a bumpy line for linearly increasing data.

**Describe the solution you'd like**	
It should produce a straight line, like chart.js.

**Describe alternatives you've considered**	
If possible, use a different interpolation algorithm that produces smoother output lines.

**Additional context**
This is a test dataset with linearly increasing values. chart.js produces a straight line, ApexCharts adds a bump on every data point.
This issue is always noticable if a dataset has repeated changes in the same direction (multiple increases or decreases after eachother)
![apexcharts interpolation](https://user-images.githubusercontent.com/42248344/90529516-1c91e200-e174-11ea-93c1-42f8aa0038ac.png)

**Comment by Fingel** [comment]
This is especially apparent when trying to do something like plotting a regression line over data.
<img width="578" alt="Screen Shot 2020-11-05 at 12 58 26 PM" src="https://user-images.githubusercontent.com/3046397/98295605-a75dce00-1f66-11eb-9224-884388ab477b.png">

**Comment by fintara** [comment]
I think [catmullRom](https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline) looks much smoother. Even though there are no plans in adding more curve options (#821), how feasible is it to change the interpolation algorithm behind `smooth`?

**Comment by gbenchanoch** [comment]
I am loving ApexChart, but the line smoothing is a huge issue for dashboard creation. I've never seen a chart presented like this in any capacity, whether it be in academia or corporate. Is there any plan for improving the smooth line to something closer to ggplot, or is this a non-starter for the devs?

**Comment by chipimix** [comment]
I am loving ApexCharts as well but the line interpolation really needs some extra love!
Here's an example of a sine function with linear ('straight') interpolation versus 'smooth' interpolation (blue line)

straight:
![imagem](https://user-images.githubusercontent.com/15652959/141289318-7b1e3e54-ef13-437e-90a9-62e76395ea49.png)

smooth:
![imagem](https://user-images.githubusercontent.com/15652959/141289335-0486c46e-96e0-4630-b8f1-91a86090205d.png)


As you can see, **the straight line option actually looks smoother than the smooth line option**.
It's a shame there are no plans to add more curve options :'(

**Comment by daviddavid** [comment]
Bumping this issue to keep it alive. I think it's essential for ApexCharts to offer smooth lines. The current "smooth" implementation is worthless, for anything but controlled examples, and straight lines only look good if you happen to have lots of smooth data points.

**Comment by LuKaa** [comment]
Any update on this? Maybe there is a setting we are missing?

**Comment by JorgenSolli** [comment]
I'd also love for this to be improved. Currently having to opt for straight lines, sadly :(

**Comment by Narcha** [comment]
Bumping this for the same reasons as last time

**Comment by FrnchFrgg** [comment]
I think that [Monotone cubic interpolation](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation) would be a much better interpolation for `apexcharts`. It respects extrema and since the chosen tangent (before correction) is parallel to the line joining the two neighboring points, it avoids squiggling in the example cases here.

**Comment by FrnchFrgg** [comment]
Note that https://github.com/apexcharts/apexcharts.js/blob/main/src/charts/Line.js#L615 says that the algorithm `apexcharts` uses is based on `chartist` which implements monotone cubic interpolation here: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/interpolation.js#L240

Maybe that interpolation was added afterwards, but since the `apexcharts` dev seem familiar with the `chartist` implementation it may help implementing monotone cubic interpolation here. I tried to make sense of the `apexcharts` smoothing code, but AFAICT as it is it only passes two points to the smoothing routine (the two extremities of a segment) where monotone cubic needs four (the leftmost point of the segment to the left, and the rightmost point of the segment to the right, in addition to those already passed).

AFAICT again, the current `apexcharts` smoothing code handles segments separate from each other, and thus has to chose an horizontal tangent for continuity purposes. This is of course the best when the point is an extremum, but it is also the reason for the artifacts seen here.

**Comment by JorgenSolli** [comment]
> Note that https://github.com/apexcharts/apexcharts.js/blob/main/src/charts/Line.js#L615 says that the algorithm `apexcharts` uses is based on `chartist` which implements monotone cubic interpolation there: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/interpolation.js#L240
> 
> Maybe that interpolation was added afterwards, but since the `apexcharts` dev seem familiar with the `chartist` implementation it may help implementing monotone cubic interpolation here. I tried to make sense of the `apexcharts` smoothing code, but AFAICT as it is it only passes two points to the smoothing routine (the two extremities of a segment) where monotone cubic needs four (the leftmost point of the segment to the left, and the rightmost point of the segment to the right, in addition to those already passed).
> 
> AFAICT again, the current `apexcharts` smoothing code handles segments separate from each other, and thus has to chose an horizontal tangent for continuity purposes. This is of course the best when the point is an extremum, but it is also the reason for the artifacts seen here.

Thanks for this! I might jus be migrating to Chartist for this. At least until, hopefully, this is added to ApexCharts...
`lineSmooth: Chartist.Interpolation.cardinal` seems to work wonderfully with my dataset.

**Comment by Narcha** [comment]
This is still relevant.

**Comment by JaspervanderSter** [comment]
Is there any way to contribute to this by implementing alternative smoothing algorithms, so one can choose one like in chartist? (`lineSmooth: Chartist.Interpolation.monotoneCubic`)

**Comment by kimdanielarthur** [comment]
Thanks for a great charting library! Would be awesome with additional interpolation options in order to communicate well the underlying data

**Comment by Tiagolm** [comment]
Yes, a real smoothing would be appreciated, we have to rely on the straight lines for now

**Comment by Narcha** [comment]
This is still relevant.

**Comment by PeterMarkley-iTickets** [comment]
So do I understand correctly that one of the holdups on this is the amount of data getting passed to the interpolation routine, as FrnchFrgg mentioned [here](#issuecomment-1184448807)? So a new interpolation option would require a refactor that allows two extra data points?

Adding my voice to those affected by this issue and looking forward to a solution. 🙂

**Comment by katemccubbins** [comment]
Looking forward to a solution! I might not be able to use this library without the option of a smoother line.

**Comment by aaronguostudio** [comment]
The same here, I am building a chart for financial application, users for sure want to see the trend is going upward without the bumps :)

**Comment by katemccubbins** [comment]
> The same here, I am building a chart for financial application, users for sure want to see the trend is going upward without the bumps :)

I ended up using Chart.js for my application. The lines were perfect!

**Comment by junedchhipa** [comment]
A new option has been added since v3.42.0.

```
stroke: {
  curve: "monotoneCubic"
}
```
https://apexcharts.com/docs/options/stroke/#curve

**Comment by OliverRomhagen** [comment]
Will it be possible in the future to have null values in the data for the line graph without it falling back from monotoneCubic to straight?

**Comment by junedchhipa** [comment]
@OliverRomhagen Now, it doesn't falls back to 'straight' if there are null values.

**Comment by OliverRomhagen** [comment]
@junedchhipa great work :)

**Comment by OliverRomhagen** [comment]
@junedchhipa I dont know if you want this to be reported as another issue in the vue3-apexcharts repo. But I saw this is working fine with vue-apexcharts but still not in vue3-apexcharts. 

https://codesandbox.io/p/sandbox/vue-basic-example-forked-rf398w?file=%2Fsrc%2Fcomponents%2FChart.component.vue%3A17%2C4

You can toggle the import I commented out in Chart.component.vue to see it :)
