### ISSUE TITLE
Categories dont work in dateseries

### ISSUE THREAD

**Issue by andre-gasparin** [apexcharts/apexcharts.js#1847]
# Bug report

Can i use dataseries chart with pre-defined categories?
![image](https://user-images.githubusercontent.com/55391441/90644066-b3a97900-e20a-11ea-9db6-9cb1eb657b0b.png)
I tried several ways like: 

` categories: [new Date('23 DEC 2017').getTime(), new Date('23 DEC 2017').getTime()]`
` categories: ['Dec 29 2017' ... ]`
` categories: ['1348437600000' ... ]`
` categories: ["02-15-2017" ... ]`

## Codepen

https://codepen.io/andre-gasparin/pen/NWNRgYo

## Explanation

- What is the behavior you expect?
that use only my categories

- What is happening instead?
Nothing

- What error message are you getting?
no error msg

**Comment by junedchhipa** [comment]
Have you tried changing the `xaxis.type: 'category'`?
That way, ApexCharts won't automatically format the DateTime values.
