### ISSUE TITLE
Tooltips are not correct when chart is scaled with transform

### ISSUE THREAD

**Issue by Linkaynn** [apexcharts/apexcharts.js#1849]
# Bug report

## Codepen

https://codepen.io/linkaynn/pen/RwaGvVP

## Explanation

When you scale a chart the tooltip position and information is not correct, when scale is `> 1` it takes the points at the right from mouse position and if scale is `< 1` takes the left points

**What is the behavior you expect?**

That tooltips takes correct positions and information

**Comment by junedchhipa** [comment]
This is not a bug, but a limitation.
All the dimensions get changed when you transform the whole chart element and it is difficult to get the precise location.
I recommend you don't scale, but manually set the height/width of the chart to make it smaller.

**Comment by Linkaynn** [comment]
@junedchhipa I already send a PR solving the limitation if you can see whats change: https://github.com/apexcharts/apexcharts.js/pull/1850
