### ISSUE TITLE
Gradient min max

### ISSUE THREAD

**Issue by LudovicLemaire** [apexcharts/apexcharts.js#1853]
**Is your feature request related to a problem? Please describe.**	
Not related to a problem, just a limitation.

**Describe the solution you'd like**	
Is it possible to use gradient over a defined min max instead of the min/max of the line (radial bar/else).
In vertical gradient.

So, with a radient line of green -> red.
Actually the vertical higher of the line is red, and bottom is green.

The requested feature is to have the gradient set to predefined value.
As example, in multiple gradient line, bottom color of lines would be green/cyan.
And will get into orange if the value is superior to let's say 50.

So bottom of 50 is green/cyan and top is orange/red (colors are example ofc).

Is it already possible to achieve something like this ? Looked at the options of **fill**, but didn't there isn't min/max value.
I can provide some illustration if it is not clear.

**Comment by LudovicLemaire** [comment]
I more clear explanation with context https://github.com/apexcharts/apexcharts.js/issues/568#issuecomment-626731175

**Comment by SHASTRYSUHAS** [comment]
I am looking for this feature as well.
