### ISSUE TITLE
Interactivity with Chart on Safari and Firefox does not work properly

### ISSUE THREAD

**Issue by doanhtu07** [apexcharts/apexcharts.js#1856]
On both Safari and Firefox, whenever I use an interaction (any kind), the window automatically scrolls to the top of the chart, which is quite annoying since I can no longer see the graph right below. I need to scroll back down from time to time.

On Safari only, when I use Zoom In, Zoom Out, and Reset, it throws an error: 
- Error: TypeError: null is not an object (evaluating 'e.target.parentNode.classList')
- Related File: apexcharts.common.js:6

If anyone knows a solution to these problems, please tell me. Thank you very much!

**Comment by idpaterson** [comment]
The console errors can be seen on the [Zoomable Timeseries demo](https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/) in Safari. Click and drag to select a time range which will trigger the error once on drag release. Use the pan tool to move through the timeline which will trigger the same error repeatedly.

I have not noticed it causing any problems with interactivity or scrolling the chart into view, however. In my case this just blows up our error tracker if someone pans a chart in Safari. Perhaps the scrolling and console error should be tracked as separate issues.

**Comment by takoyaro** [comment]
I'm having the same issue here

**Comment by chenhaiyun** [comment]
Before:
`
 <div id="chart" style={{ paddingLeft: 10 }}>
      <Chart options={chartData.options} series={chartData.series} type="line" height={height - 20} />
    </div>
`
After:
`
 <div id="chart" style={{ paddingLeft: 10, height: height - 20 }}>
      <Chart options={chartData.options} series={chartData.series} type="line" height="100%" />
    </div>
`
It works for me

**Comment by chenhaiyun** [comment]
Before:
```
<div id="chart" style={{ paddingLeft: 10 }}>
     <Chart options={chartData.options} series={chartData.series} type="line" height={height - 20} />
 </div>
```
After:
```
<div id="chart" style={{ paddingLeft: 10, height: height - 20 }}>
      <Chart options={chartData.options} series={chartData.series} type="line" height="100%" />
    </div>
```
It works for me.

**Comment by praneetloke** [comment]
The other variation of this is on mobile Safari (on iOS devices), I can reproduce this 100% of the time by simply scrolling the page while I tap and hold somewhere on the graph and then let go. As @idpaterson pointed out, it seems to be with related to click and dragging on a graph on Safari on desktop and mobile.

**Comment by adrianhand** [comment]
Seeing the same behaviour here - it doesn't hurt anything but it would be nice for the error not to be thrown, I don't see a problem with adding a null check there.
