### ISSUE TITLE
trigger interactivity without toolbar

### ISSUE THREAD

**Issue by gxara** [apexcharts/apexcharts.js#1859]
I would like to trigger interactivity functionalities like selection and zooming using custom buttons outside the chart.

The reason for that is that I've already coded some buttons like: insert/remove annotations and insert a new data serie. It would be awesome to keep all tools of interaction on the same place.

![image](https://user-images.githubusercontent.com/33765053/90983810-2ab27a80-e547-11ea-8e96-3ff70744d34f.png)

I've tried to apply something using events but got no results.

**Comment by yeahoni** [comment]
any update? need this too
