### ISSUE TITLE
Feature request: display data labels on line/area charts for extremums only

### ISSUE THREAD

**Issue by Dimanoid** [apexcharts/apexcharts.js#186]
If you have lot of data (say 1000+ points) its good to see labels only for maximums and/or minimums.
See attached picture (not the best realization, just to illustrate the idea).
![image](https://user-images.githubusercontent.com/1387749/47803798-b80e5480-dd4c-11e8-80df-e7b17339d2f5.png)

Also it would be nice to have more "intelligent" data labels which will be placed not just by text align and offset options but positioned depending on other labels and graphs on the same chart to avoid overlaying each over.

**Comment by junedchhipa** [comment]
@Dimanoid Good suggestions.

Regarding overlapping data labels, I have already tried not to overlap dataLabels when there is a lot of data as shown below.
![screen shot 2018-11-01 at 6 40 52 am](https://user-images.githubusercontent.com/17950663/47826985-3268c400-dda1-11e8-9d6e-ac643569420f.png)

Regarding intelligent dataLabels, I can provide an option in dataLabels config to only show max/min values and hide all. But, I think - annotations (point annotations to be specific) would be better suited in these scenarios. An example of this 

```javascript
chart.render().then(() => {
    const lowest = chart.getLowestValueInSeries(0)
    const highest = chart.getHighestValueInSeries(0)

    chart.addPointAnnotation({
        x: new Date(chart.w.globals.seriesX[0][chart.w.globals.series[0].indexOf(lowest)]).getTime(),
        y: lowest,
        label: {
            text: 'Lowest: ' + lowest,
            offsetY: 2
        },
    })

    chart.addPointAnnotation({
        x: new Date(chart.w.globals.seriesX[0][chart.w.globals.series[0].indexOf(highest)]).getTime(),
        y: highest,
        label: {
            text: 'Highest: ' + highest,
            offsetY: 2
        },
    })
});
```
![screen shot 2018-11-01 at 9 04 59 am](https://user-images.githubusercontent.com/17950663/47831133-3c94bd80-ddb5-11e8-8ecb-9240b220e00a.png)

**Comment by Dimanoid** [comment]
About maximum/minimum - not exactly what I mean. Not the global maximum or minimum, but local ones. May be I found a better illustration.
![image](https://user-images.githubusercontent.com/1387749/47838840-a87d2300-ddc1-11e8-949b-66ab908cd855.png)

As for overlapping of data labels, please look at this example https://stackblitz.com/edit/angular6-apexcharts-14dvla

**Comment by junedchhipa** [comment]
Thank you for better illustration, I got your point.
And yes, overlapping looks bad in multi-series chart with lots of data-points. Need to find a more intelligent way to manage data-labels for such scenarios.

**Comment by alvinwoon** [comment]
addPointAnnotation doesn't seem to work for me. More specifically, chart.w.globals.seriesX is an empty array for some reason. I do see seriesXvalues though.

https://hotinfluencer.com/user/7b87c59b71ca5a2c2e0124d9663c1e6914

**Comment by junedchhipa** [comment]
Can you please create a codepen demo in a new issue? Your provided link doesn't contain any chart.

**Comment by alvinwoon** [comment]
![image](https://user-images.githubusercontent.com/1026383/49921721-70512000-fee9-11e8-9756-05273b746f4d.png)
hmm super weird. The chart is there but I will try to recreate a sample on codepen. Thanks for the swift reply.

**Comment by prutheus** [comment]
> @Dimanoid Good suggestions.
> 
> Regarding overlapping data labels, I have already tried not to overlap dataLabels when there is a lot of data as shown below. ![screen shot 2018-11-01 at 6 40 52 am](https://user-images.githubusercontent.com/17950663/47826985-3268c400-dda1-11e8-9d6e-ac643569420f.png)
> 
> Regarding intelligent dataLabels, I can provide an option in dataLabels config to only show max/min values and hide all. But, I think - **annotations** (point annotations to be specific) would be better suited in these scenarios. An example of this
> 
> ```js
> chart.render().then(() => {
>     const lowest = chart.getLowestValueInSeries(0)
>     const highest = chart.getHighestValueInSeries(0)
> 
>     chart.addPointAnnotation({
>         x: new Date(chart.w.globals.seriesX[0][chart.w.globals.series[0].indexOf(lowest)]).getTime(),
>         y: lowest,
>         label: {
>             text: 'Lowest: ' + lowest,
>             offsetY: 2
>         },
>     })
> 
>     chart.addPointAnnotation({
>         x: new Date(chart.w.globals.seriesX[0][chart.w.globals.series[0].indexOf(highest)]).getTime(),
>         y: highest,
>         label: {
>             text: 'Highest: ' + highest,
>             offsetY: 2
>         },
>     })
> });
> ```
> 
> ![screen shot 2018-11-01 at 9 04 59 am](https://user-images.githubusercontent.com/17950663/47831133-3c94bd80-ddb5-11e8-8ecb-9240b220e00a.png)

@junedchhipa can you give an example how to achieve what you showed in your first screenshot?
