### ISSUE TITLE
Disabled chart responsive

### ISSUE THREAD

**Issue by ducvietsqt** [apexcharts/apexcharts.js#1860]
**Disabled chart responsive**	
I have a issue with my chart when browser resize, chart responsive but not  with chart configs responsive

**Comment by junedchhipa** [comment]
Can you elaborate on the issue?
Maybe create a codepen to demonstrate the problem?

**Comment by mitya33** [comment]
I would also like a way to disable responsive. I suspect this is behind another issue I raised re: chart height not taking effect. Something is pinning my chart to a particular height via the style attribute, and if I turn this off (in dev tools) it gets automatically re-added, as though some JS is listening.
