### ISSUE TITLE
Stacked Area Graph - when all data values for a "Line" in a series are 0 and it is the only visible line on the graph, users can no longer properly interact with the graph and the tooltip is not properly displayed

### ISSUE THREAD

**Issue by kylepinkertonyoui** [apexcharts/apexcharts.js#1865]
# Bug report

## Codepen

https://codesandbox.io/s/react-basic-example-forked-4e80h?file=/src/App.js

### Reproduction Steps:

Open the given codesandbox example and do the following:
1. Hover over the given lines in the graph, notice how you can properly interact/hover over the three lines and the tooltip renders correctly (with the correct x-axis value)
2. Now click on the "Line 1" and "Line 2" keys in the Legend to disable these lines.
3. Notice how you can no longer properly interact/hover over the "Line 3 - All Data Values 0" line and the tooltip no longer renders correctly (x-value shows as undefined) when it is the only line visible. 

GIF for context: 
<a href="https://gyazo.com/7e230d9d3425d3a9c32a9ab3cdb29f3e"><img src="https://i.gyazo.com/7e230d9d3425d3a9c32a9ab3cdb29f3e.gif" alt="Image from Gyazo" width="506"/></a>

Notice how if we change one of the data values for the "Line 3" series to a non-zero value, this unexpected behaviour stops occurring: 

<a href="https://gyazo.com/3741b8be9db81a62917a034655471051"><img src="https://i.gyazo.com/3741b8be9db81a62917a034655471051.gif" alt="Image from Gyazo" width="496"/></a>

- What is the behavior you expect?

You should be able to properly interact with the graph and the tooltip should be properly displayed (with the correct x-axis value) when the only line visible has all 0 data values.

- What is happening instead?

You can not properly interact with the graph and the tooltip is not displayed correctly (with the correct x-axis value) if the only line visible has all 0 data values.

- What error message are you getting?

n/a

**Comment by KylePinkerton** [comment]
This actually seems to have been fixed by 13c1f0fc3a00846ab8a253607513437956e3b0e4.
Also, as shown by the codesandbox https://codesandbox.io/s/react-basic-example-forked-g2bdp, the expected behaviour is still occurring in version `3.21.0`:
<a href="https://gyazo.com/f43722fa7058e1a33060819ca9b7e9bf"><img src="https://i.gyazo.com/f43722fa7058e1a33060819ca9b7e9bf.gif" alt="Image from Gyazo" width="506"/></a>

This issue should be fine to close.

**Comment by junedchhipa** [comment]
Thanks for the update
