### ISSUE TITLE
Change date format of tooltip title

### ISSUE THREAD

**Issue by ws420** [apexcharts/apexcharts.js#1866]
How can I change the date format of the tooltip's title?
![image](https://user-images.githubusercontent.com/48076840/91510889-56699380-e8ac-11ea-8e9a-d2612b45ecee.png)
In this example I would like to display "October 2016" instead of just "01 Oct"

Thanks for the great charts

**Comment by junedchhipa** [comment]
```javascript
tooltip: {
  x: {
    format: 'MMMM yyy'
  }
}
```
