### ISSUE TITLE
Axis border overlaps actual chart when multiple axes are used

### ISSUE THREAD

**Issue by ekhaled** [apexcharts/apexcharts.js#187]
## Codepen

https://codepen.io/anon/pen/gBVyre

## Explanation

Might be related to #98 
But, this was a problem before that issue was closed.

When multiple axes are used, not adding a `title` attribute causes the yAxis border on the left to overlap the chart.

When the axis has a title, it renders fine.

**Comment by junedchhipa** [comment]
I can notice that. I will take care of it.
