### ISSUE TITLE
Chart click event error: "Cannot read property 'classList' of null"

### ISSUE THREAD

**Issue by AshConnolly** [apexcharts/apexcharts.js#1871]
# Bug report

When clicking on a chart I am using a custom click event that is throwing an error. This event is created inside a react component and updates the react component state. This event is added to the Apex Chart Options object.

## [CodeSandbox here](https://codesandbox.io/s/mystifying-gould-8fmoh?file=/src/components/ItemChart.js) in a React Next.js Environment

(note this error also occurs in a non-next.js React environment)

- Click on the chart to see the error. 

![image of error](https://i.imgur.com/p6H0AF5.png "image of error")

I get the error - `TypeError: Cannot read property 'classList' of null`. I believe its coming from this if statement where it checks for a class list: 
```js
if (
  (e.shiftKey
    ? ((this.shiftWasPressed = !0),
      s.enableZoomPanFromToolbar("pan" === n ? "zoom" : "pan"))
    : this.shiftWasPressed &&
      (s.enableZoomPanFromToolbar(n), (this.shiftWasPressed = !1)),
  !(
    e.target.classList.contains("apexcharts-selection-rect") ||
    e.target.parentNode.classList.contains("apexcharts-toolbar")
  ))
) {
}
```
When I log out `e.target.classList` and `e.target.parentNode.classList` in the click event, the console log without issue or error.

## Explanation

- What my app is doing:   
I have a `ItemChart` React component in which the chart options object is generated. This options object has a custom click event. 

   
- What is the behavior you expect?   
I expect the chart to fire the out the passed click event function (`chartData.options.chart.events.click`) without error. 
- What is happening instead?   
The custom click event fires but an uncaught error is thrown.
- What error message are you getting?   
`TypeError: Cannot read property 'classList' of null`

I'm about to release a production app that use this lib so any help would be greatly appreciated! Thanks for the great lib @junedchhipa! 😃 👍

**Comment by junedchhipa** [comment]
Hi @AshConnolly 
Your Codesandbox isn't running on the first try
![Screenshot 2020-09-01 at 11 57 18 AM](https://user-images.githubusercontent.com/17950663/91809317-64236e00-ec4a-11ea-9668-b91d6051ce4d.png)

Can you please set up a minimal reproducible example, so I can quickly jump in and fix the issue?
I am planning a new release soon. So, if this is a small bug, the fix can be shipped with that.

**Comment by AshConnolly** [comment]
Hi @junedchhipa 😃
Thanks for looking at this so promptly!

Sorry for that [its working fine now](https://codesandbox.io/s/mystifying-gould-8fmoh?file=/src/components/ItemChart.js)! I have found that this issue is not present in a normal React environment. But in a Next.js environment it is. Which is strange as I'm importing the lib client side [as recommend by Next.js](https://nextjs.org/docs/advanced-features/dynamic-import).

I understand its not your responsibility to ensure it works with Next.js, but if you could have a look and share any guidance on it, I'd be hugely grateful! 

I've nearly finished a chart based app and would love to continue using ApexCharts. Also Next.js is hugely popular so I suspect others might run into this issue.

Thanks @junedchhipa!

**Comment by junedchhipa** [comment]
I forked your sandbox, updated **apexcharts@3.20.0** and the error no longer appears.
Can you confirm?

**Comment by AshConnolly** [comment]
Confirmed!! ✅
Updating to latest fixed it for me too! Sorry about that mate, I thought I was on the latest, I should have tried that first! Pleased to see the latest release fixed this bug, great work! Thanks for the help! 😃
