### ISSUE TITLE
Add more info on data values

### ISSUE THREAD

**Issue by Reluigi** [apexcharts/apexcharts.js#1873]
Hi I'm trying to display on data labels or tooltips more info than just y axis value. For example I would like to insert something like:

```
{
              x: 2
              y: [
                new Date() //some date
                new Date() //another date
              ],
              extraInfo: {
                   name: 'John',
                   age: '27'
              }
  }
```

Is there a way to do something like that? Or otherwise, is there a way to connect data to external objects?

**Comment by joaofsa2000** [comment]
Hey, did something similar to what you want but i created a json in a way that dynamically has the same size as the data array of the chart. In my case i needed to show custom data in the tooltip related to the datapoint.  

So i created this json for example:

```javacript
let jsonEx = {
    "Series1": [{                               
        "overload": 31,  
        "isOverloaded": false,
        "effort": 81,
        "hours": 13,
        "trucks": 4,
        "delta": -0.75
    }, {
        "overload": 28,
        "isOverloaded": true,
        "effort": 17,
        "hours": 19.83,
        "trucks": 30,
        "delta": -25.04
    }, {
        "overload": 29,
        "isOverloaded": true,
        "effort": 12,
        "hours": 14.92,
        "trucks": 30,
        "delta": -26.27
    }]
};
```
And then inside the tooltip option i set a custom function for it
```javascript

custom: function({ series, seriesIndex, dataPointIndex, w }) {
                    return (
                        '<div class="arrow_box">' +
                            "<span> SomeValue : " +
                        jsonEx[w.globals.seriesNames[seriesIndex]][dataPointIndex].overload" +
                        "</span>" +
                        "</div>"
                    );
                }
```

the object **w** can also be accessed outside of the function if you have a chart variable: 

```javascript
     let chart = new ApexCharts(document.querySelector("#somediv"), options);

    let series = chart.w.globals.seriesNames;
```
Hope this workaround helped you in some way

**Comment by Reluigi** [comment]
Thank you @joaofsa2000, you saved my day!
Thanks to your suggestion I made something very similar that works perfectly for what I need.

**Comment by junedchhipa** [comment]
@joaofsa2000 Thank you for the suggestion.
Closing this.
