### ISSUE TITLE
Something is wrong with responsiveness (maybe)

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [apexcharts/apexcharts.js#1875]
I think some changes need to be provided for responsiveness. When I read docs for responsiveness [https://apexcharts.com/docs/options/responsive/](https://apexcharts.com/docs/options/responsive/), I have found example demo [https://codepen.io/apexcharts/pen/ajpqJp](). I tried to resize the screen to breakpoint 1000px (as provided in config), as a result legend changed position to 'bottom'. When I have resized the screen back to the default size (screen width > 1000px), the legend stayed at bottom. I am as a regular developer think that something is wrong in that behavior. I think that when user resize screen from 1000px to default size (screen width > 1000px), then only default options should be applied.

**Comment by junedchhipa** [comment]
You're absolutely correct. The latest build might have broken this.
I will take a look, thanks for reporting.
