### ISSUE TITLE
Last xaxis label hidden in bar chart

### ISSUE THREAD

**Issue by pacocom** [apexcharts/apexcharts.js#1876]
# Bug report
Need to show all datatime labels in bar charts.

## Codepen
https://codesandbox.io/s/area-datetime-x-axis-forked-v9cuu

## Explanation

- What is the behavior you expect?
All labels displayed
- What is happening instead?
Last labels is not displayed
- What error message are you getting?
None

**Comment by twdrake-ap** [comment]
I have this same issue.

**Comment by twdrake-ap** [comment]
Based on other issues submitted it seems that this behavior is intentional. It would be great to have the ability to toggle a flag on the x-axis config object to disable hiding the first and last label in when the x-axis type is set to `datetime`.

**Comment by junedchhipa** [comment]
The issue mentioned by @pacocom in the original codesandbox doesn't seem to be happening with the latest version 3.21.0
![Screenshot 2020-09-29 at 11 30 39 PM](https://user-images.githubusercontent.com/17950663/94597953-e20b8100-02ab-11eb-8d04-12ea61fc1264.png)

**Comment by pacocom** [comment]
@junedchhipa you can see the problem with versuib 3,21.0 https://codesandbox.io/s/area-datetime-x-axis-forked-v4u3u

![image](https://user-images.githubusercontent.com/7735329/94649531-253e1200-02f5-11eb-82cb-f2be729de8be.png)

**Comment by twdrake-ap** [comment]
I misread this originally, my b. My issue is specifically line charts.

**Comment by karesztrk** [comment]
v3.21.0 solved the issue on `datetime` type. The last date is shown on the `xaxis`.
![image](https://user-images.githubusercontent.com/5886428/118118493-4b7c7200-b3ed-11eb-810f-cd47c37feff8.png)
