### ISSUE TITLE
Cropped x-axis labels regardless of the value of maxHeight option

### ISSUE THREAD

**Issue by nam98nd16** [apexcharts/apexcharts.js#1880]
# Bug report

## Codepen

https://codepen.io/nam98nd16/pen/MWyOogN

## Explanation

- What is the behavior you expect?
All x-axis labels should be displayed properly without being cropped.
- What is happening instead?
Some x-axis labels are cropped regardless of the value of maxHeight option.
- What error message are you getting?
Literally no error messages.

**Comment by junedchhipa** [comment]
Instead of `maxHeight`, try `xaxis.labels.minHeight`

```javascript
xaxis: {
  labels: {
      minHeight: 200
  }
}
```

**Comment by nam98nd16** [comment]
> Instead of `maxHeight`, try `xaxis.labels.minHeight`
> 
> ```js
> xaxis: {
>   labels: {
>       minHeight: 150
>   }
> }
> ```

I'm so ashamed of being confused about these 2 options. Thank you so much, my friend. You saved my day.

**Comment by junedchhipa** [comment]
No worries :)

**Comment by nam98nd16** [comment]
Since you are one of the creators of this library, can I ask you one more question: How can I know if the labels on the x-axis are being rotated? I mean, I probably need that to adjust the aforementioned `minHeight` property according to whether the x-axis labels are being rotated or not. Thank you in advance, bro!

**Comment by junedchhipa** [comment]
The labels are rotated when they do not fit in the given space. Unfortunately, there is no way to know externally when this happens.

Is it fine if the labels are always rotated?
There is a property `xaxis.labels.rotateAlways` which creates a consistent experience.

**Comment by nam98nd16** [comment]
Yeah, will definitely try that. Thanks for your help, bro!
