### ISSUE TITLE
Highlight legends programmatically like wordpress woocommerce 

### ISSUE THREAD

**Issue by yalmazkhalil** [apexcharts/apexcharts.js#1886]
Do we have any option to make legends outside the chart`s wrapper, or create legends programmatically like woocommerce in wordpress, and when the user move the mouse on an legend it highlights inside the chart.

For example, in VueJS we can create a list of items and trigger mouse over event on each item which will execute a method and trigger an event to chart object to highlight related  series.

Screenshot of woocommerce report chart: 
![apex](https://user-images.githubusercontent.com/38337239/92305276-6b21e780-ef8e-11ea-8a3b-9eba006f8505.JPG)

**Comment by SamLewis0602** [comment]
Agreed, it would be nice to have a `highlightDataset` like there is a `toggleDataset` method!

**Comment by sledoux** [comment]
+1

**Comment by Carlitox7** [comment]
+1

**Comment by ReddicoJack** [comment]
+1

**Comment by visini** [comment]
+1

**Comment by gerbenqikker** [comment]
I'd also like this 👍

**Comment by alon-loris** [comment]
+1 for adding a way to highlight a series programatically (maybe "toggleSeriesHighlight").
This is needed for creating a custom legend from scratch. We have the `toggleSeries` method for recreating the `onItemClick` behavior, but there's no method for recreating the `onItemHover` behavior.

**Comment by sjmc11** [comment]
+1. I have a custom legend, being able to re-create the series hover effect using a onItemHover behaviour would be great.

**Comment by daniel-ilan** [comment]
+1 This is really a desired feature

**Comment by Avladd** [comment]
I want to punch that bot for closing this again and again. +1 request for this feature.

**Comment by kinan-almoalm** [comment]
+1
