### ISSUE TITLE
Stacked bar chart, multiple series, named data

### ISSUE THREAD

**Issue by mestaritonttu** [apexcharts/apexcharts.js#189]
I did a lot of digging and it seems we do not have a way to create multiple stacked bars containing named data. I mean a scenario where all the datapoints have unique names and values.
So with a pseudo-syntax:
```
series1: [{"name":"A1a","data":[71]},{"name":"A1b","data":[54]},{"name":"A1c","data":[12]}],
series2: [{"name":"A1d","data":[17]},{"name":"A1e","data":[21]}],
series3: [{"name":"A2a","data":[97]},{"name":"A2b","data":[43]},{"name":"A3a","data":[81]},{"name":"A3b","data":[96]}]
```
Am I missing something? Does this make sense or is it too much of a corner case to even consider?

**Comment by mestaritonttu** [comment]
Ah, I don't mean like that. In your example, the series A, B and C are mixed in the same bars. I would like one series per bar.
What drove me to this is a single bar having too many data points and thus wanting to split it (per meaningful categories, nonetheless) to make the data readable at a glance.

**Comment by mestaritonttu** [comment]
Yeah, I think it might be too painful to do in this case as the series would have different numbers of items. Just thinking about reordering my data makes my head hurt :)
I will experiment with multiple charts. Thanks!

**Comment by sanketkarandikar** [comment]
Hello @junedchhipa, i struggled a lot to get this but at the time i just cant find any proper solution. I want to create a chart where 1 column is stacked with 2 dataSeries and 1 column is seperate. I have created a fiddle where i am showing three separate columns. Instead what i would like to do is stack first 2 data series and keep 3rd in separate column.
Codepen for the same - [https://codepen.io/sanket-karandikar/pen/OKaZYE](url)
Now how can i stack green and orange bar together and keep red separate?

TIA

**Comment by HammSoftware** [comment]
> Ah, I don't mean like that. In your example, the series A, B and C are mixed in the same bars. I would like one series per bar. What drove me to this is a single bar having too many data points and thus wanting to split it (per meaningful categories, nonetheless) to make the data readable at a glance.

Is this possible now, three years later?

**Comment by CaramelHeaven** [comment]
@HammSoftware do u find an answer ? )

**Comment by CaramelHeaven** [comment]
Okay, here -> https://apexcharts.com/docs/datalabels/

**Comment by HammSoftware** [comment]
> @HammSoftware do u find an answer ? )

We decided to migrate to Highcharts in the end.
