### ISSUE TITLE
"Cannot read property 'removeEventListener' of null"

### ISSUE THREAD

**Issue by peteichuk** [apexcharts/apexcharts.js#1891]
# Bug report

"Cannot read property 'removeEventListener' of null"

[Angular](https://github.com/apexcharts/ng-apexcharts/issues/91) Issue
[Vue](https://github.com/apexcharts/vue-apexcharts/issues/275) Issue
[React](https://github.com/apexcharts/react-apexcharts/issues/208) Issue

**Version 3.20.0**

**Comment by junedchhipa** [comment]
I just released v3.20.1
Please test and report if that fixes the issue.

**Comment by toverux** [comment]
I can confirm that the patch release fixes the problem. Thanks!

**Comment by OberstK** [comment]
I can also confirm that the problem is fixed. Thanks for that!
