### ISSUE TITLE
TypeError: Cannot read property 'ToString' of undefined when bar chart is rendering with data.

### ISSUE THREAD

**Issue by JCFalter** [apexcharts/apexcharts.js#1898]
Codepen: https://codepen.io/jfalter/pen/rNedKOw

Whenever I attempt to render a bar chart with data, I get the following error message:

`Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined`
    `at Function.value (apexcharts:6`
    `at t.value (apexcharts:6)`
    `at t.value (apexcharts:6)`
    `at t.value (apexcharts:14)`
   ` at t.create (apexcharts:6)`
    `at apexcharts:14`
    `at new Promise (<anonymous>)`
    `at t.value (apexcharts:14)`
    `at apexcharts:6`
    `at Array.forEach (<anonymous>)`

When I look at the Apexcharts Javascript file, I see this throwing an error:

> key: "escapeString",
            value: function(t) {
                var e = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : "x"
                  , i = t.toString().slice();  //This is what's throwing the error.
                return i = i.replace(/[` ~!@#$%^&*()_|+\-=?;:'",.<>{}[\]\\/]/gi, e)
            }

Note that it works fine if I render with empty data and category arrays.

**Comment by maxi512** [comment]
I have the same error! I thought that I was the only one.

**Comment by junedchhipa** [comment]
Thanks for reporting.
It's a major bug and I had to immediately release a patch version as this might have broken many existing charts.

Please upgrade to **v3.20.2**

**Comment by JCFalter** [comment]
Works now!  Thanks!

**Comment by RaviganeshR** [comment]
Thanks.it's working.

**Comment by MohammadMerhi** [comment]
Upgraded to v3.20.2 
Still showing 
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined

**Comment by junedchhipa** [comment]
@MohammadMerhi Can you create a Codepen?

**Comment by Lucascoorek** [comment]
Had this error when trying to add undefined value to label. 
Label has to be a string.

**Comment by NAVIKNITIN** [comment]
occuring same problem of undefined.

**Comment by Saicasm** [comment]
Any update on this ?

**Comment by swasti4evrurs** [comment]
Getting the same error when giving dynamic height to chart .
"Unhandled Promise rejection: Cannot read properties of undefined (reading 'toString') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'toString')"

**Comment by ArtemKoshevoi** [comment]
In my case I've added field **width** and error is gone     <```
Chart
      height={420}
      width={700}
      options={options}
      series={series}
      type="area"
    /> 
```

**Comment by wrappixelTeam** [comment]
> In my case I've added field **width** and error is gone
> 
> ```
>     <Chart
>       height={420}
>       width={700}
>       options={options}
>       series={series}
>       type="area"
>     />
> ```

How to make it responsive with the fixed width?

**Comment by tonyjara** [comment]
What solved it for me was having the width in numbers rather than using strings.

**Comment by jsvelte** [comment]
it's truly is width is required! but not included in the docs

**Comment by mateusabelli** [comment]
> > In my case I've added field **width** and error is gone
> > ```
> >     <Chart
> >       height={420}
> >       width={700}
> >       options={options}
> >       series={series}
> >       type="area"
> >     />
> > ```
> 
> How to make it responsive with the fixed width?

I've managed to use it with `width: "100%"`. It seems to both fix that _TypeError: Cannot read property 'ToString' of undefined_, and keep my graph responsive.

**Comment by cassioseffrin** [comment]
@mateusabelli your workaround have worked 100% !

**Comment by hmtcelik** [comment]
if someone still looking here, yo should also give `height` prop:

```js
      <ApexChart
        options={options}
        series={series}
        type="pie"
        width={500}
        height={320} // after adding height, it working now
      />
```

**Comment by Joginder462** [comment]
adding width will solve problem 
<ReactApexChart
  options={options}
  series={state.series}
  width={"100%"}
  height={300}
  type="donut"
/>

**Comment by MatheusEli** [comment]
@Joginder462 your solution have worked for me! Thanks!

**Comment by Capta1nRaj** [comment]
> In my case I've added field **width** and error is gone
> 
> ```
>     <Chart
>       height={420}
>       width={700}
>       options={options}
>       series={series}
>       type="area"
>     />
> ```

Buddy, thank you very much, I was harassed by this bug for past 6 hours.

**Comment by Joginder462** [comment]
> > In my case I've added field **width** and error is gone
> > ```
> >     <Chart
> >       height={420}
> >       width={700}
> >       options={options}
> >       series={series}
> >       type="area"
> >     />
> > ```
> 
> Buddy, thank you very much, I was harassed by this bug for past 6 hours.

same I had faced

**Comment by Vituli** [comment]
`
  return <Chart options={chartOptions} series={chartSeries} type="pie" width="500" />;
`

I also try to add width but still get error when i hover on the labels
<img width="670" alt="Screenshot 2024-09-03 at 12 07 02" src="https://github.com/user-attachments/assets/1c05d0e4-6759-4d58-8a3b-732d31d11571">

**Comment by Capta1nRaj** [comment]
> `return <Chart options={chartOptions} series={chartSeries} type="pie" width="500" />;`
> 
> I also try to add width but still get error when i hover on the labels <img alt="Screenshot 2024-09-03 at 12 07 02" width="670" src="https://private-user-images.githubusercontent.com/130680989/363915986-1c05d0e4-6759-4d58-8a3b-732d31d11571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTQ5OTUsIm5iZiI6MTcyNTM1NDY5NSwicGF0aCI6Ii8xMzA2ODA5ODkvMzYzOTE1OTg2LTFjMDVkMGU0LTY3NTktNGQ1OC04YTNiLTczMmQzMWQxMTU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwOTExMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTUzNzQ4ZmQyYTkyOGU1MDJlYzk1YjExYjQwZWRmYTg4MTdhMGFiYTU5MTQzNGY2YThiY2ViMzA4Mjc0ODhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kojlGjV-RGzUQ10xvkVHIINlgRGqnFTNXrsEv9DefBI">

Remove the build folder, & retry to build please.

**Comment by necipsunmaz** [comment]
> `return <Chart options={chartOptions} series={chartSeries} type="pie" width="500" />;`
> 
> I also try to add width but still get error when i hover on the labels <img alt="Screenshot 2024-09-03 at 12 07 02" width="670" src="https://private-user-images.githubusercontent.com/130680989/363915986-1c05d0e4-6759-4d58-8a3b-732d31d11571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTA5OTAsIm5iZiI6MTcyNjE5MDY5MCwicGF0aCI6Ii8xMzA2ODA5ODkvMzYzOTE1OTg2LTFjMDVkMGU0LTY3NTktNGQ1OC04YTNiLTczMmQzMWQxMTU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMTI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGI5NjNlNjZmNmUyZGZhNjhmMWI5MTA4YWQxZjQ4ZWVjMjU4NTExNzFmZTgzNzVlNTE2ZDBjOTBkMDZhOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LGP0B-fzS2eBwZZw6G4L6yOsHFV8J91S_88sa3i1hno">
> 
> I am using "react-apexcharts": "^1.4.1",

I have tried adjusting to width and all other solutions but it doesn't work. When I downgraded the Apexchart version to **“3.44.0”** it worked fine. I think this bug reappeared in newer versions. 

**Solution:** 
> Downgrade Apexchart version to version “3.44.0” (make sure it is not “^3.44.0”).

**Comment by tad27** [comment]
> > `return <Chart options={chartOptions} series={chartSeries} type="pie" width="500" />;`
> > I also try to add width but still get error when i hover on the labels <img alt="Screenshot 2024-09-03 at 12 07 02" width="670" src="https://private-user-images.githubusercontent.com/130680989/363915986-1c05d0e4-6759-4d58-8a3b-732d31d11571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTA5OTAsIm5iZiI6MTcyNjE5MDY5MCwicGF0aCI6Ii8xMzA2ODA5ODkvMzYzOTE1OTg2LTFjMDVkMGU0LTY3NTktNGQ1OC04YTNiLTczMmQzMWQxMTU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMTI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGI5NjNlNjZmNmUyZGZhNjhmMWI5MTA4YWQxZjQ4ZWVjMjU4NTExNzFmZTgzNzVlNTE2ZDBjOTBkMDZhOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LGP0B-fzS2eBwZZw6G4L6yOsHFV8J91S_88sa3i1hno">
> > I am using "react-apexcharts": "^1.4.1",
> 
> I have tried adjusting to width and all other solutions but it doesn't work. When I downgraded the Apexchart version to **“3.44.0”** it worked fine. I think this bug reappeared in newer versions.
> 
> **Solution:**
> 
> > Downgrade Apexchart version to version “3.44.0” (make sure it is not “^3.44.0”).

3.44.0

**Comment by ReetiMauryaCrest** [comment]
I am having the same issue with pie chart, it is throwing error when we are hovering over label list. Can anyone tell me how can I resolve it?

**Comment by Simulanis-Dev-Varun** [comment]
Thanks a lot. 3.44.0 worked for me
this is the solution everyone is waiting the new version is not compatible with dealing with the single data value 

which is data =[ { name:'random_name',data:[10]}]
the old version will work fine
