### ISSUE TITLE
Better documentation for "Dashboards" section of guide

### ISSUE THREAD

**Issue by CodeSpent** [apexcharts/apexcharts.js#1899]
**Is your feature request related to a problem? Please describe.**	
The dashboards at https://apexcharts.com/javascript-chart-demos/dashboards/ look great, but I have no clue what those are in the top row and I'd like to use them. Without any documentation or even annotations, I'm left searching element by element in the docs then still coming up empty as I don't see them listed. What are these dashboards? What is needed to use the elements and themes within them? How can this be recreated? This section just boasts a bit about capabilities with no explanation of them.

**Describe the solution you'd like**	
Clear documentation accompanying this section so it is clear what elements are used and how they're used.

**Comment by junedchhipa** [comment]
I understand your issue.
I just added the direct link to Code in all the dashboards just now.

Here are the links for your reference
- [Dashboard Modern](https://github.com/apexcharts/apexcharts.js/tree/master/samples/vanilla-js/dashboards/modern)
- [Dashboard Dark](https://github.com/apexcharts/apexcharts.js/tree/master/samples/vanilla-js/dashboards/dark)
- [Dashboard Material](https://github.com/apexcharts/apexcharts.js/tree/master/samples/vanilla-js/dashboards/material)
- [Dashboard Realtime](https://github.com/apexcharts/apexcharts.js/tree/master/samples/vanilla-js/dashboards/realtime)
