### ISSUE TITLE
markers not updated (updateOptions)

### ISSUE THREAD

**Issue by grishnyakov** [apexcharts/apexcharts.js#190]
When do updateOptions with param: {markers: { size: N }}
(N- any number 0-5)  - chart would be refreshed, but points(markers) size will stay unchanged. 

let value = {markers: { size: N }};
this.$apexcharts.exec("chart2", "updateOptions", value, true, true);

**Comment by junedchhipa** [comment]
Thanks for reporting, just fixed it.
