### ISSUE TITLE
chart.hideSeries() does not work in 3.20.1 or later.

### ISSUE THREAD

**Issue by hankei6km** [apexcharts/apexcharts.js#1901]
# Bug report

An error occurred when calling `chart.hideSeries(seriesName)` in apexcharts.js 3.20.1 or later
and the specified series has not been hidden.

in 3.20.0
![chart hideSeries_in_3 20 0](https://user-images.githubusercontent.com/1386689/93044582-36014d80-f690-11ea-87ed-5fd5ce1bcfe5.png)

in 3.20.1 or later
![chart hideSeries_in_3 20 1](https://user-images.githubusercontent.com/1386689/93044598-3d285b80-f690-11ea-8e08-e1fffee79460.png)

## Codepen

https://codepen.io/hankei6km/pen/ExKRZzz

## Explanation

- What is the behavior you expect?
The specified series will been hidden.

- What is happening instead?
The specified series is not hidden.

- What error message are you getting?
No message outputed in codepen console.
However, below message was outputed in browser console.

```
apexcharts:6 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at t.value (apexcharts:6)
    at t.value (apexcharts:6)
    at t.value (apexcharts:14)
    at pen.js:23
value	@	apexcharts:6
value	@	apexcharts:6
value	@	apexcharts:14
(anonymous)	@	pen.js:23
```

**Comment by thccorni** [comment]
I am experiencing this issue too. It seems that the attribute `data:realIndex` is not present on the `.apexcharts-legend-series` element, which, as I understood, is used later to locate the series in the dom. Maybe that helps a little bit…

**Comment by junedchhipa** [comment]
You're right.
It was selecting legend instead of series in querySelector. Thanks for the hint.

**Comment by hankei6km** [comment]
Thank you for the quick fix.

**Comment by andreajsfullstack** [comment]
Sorry I didn't understand how you solved it

**Comment by andreajsfullstack** [comment]
> 
> 
> You're right. It was selecting legend instead of series in querySelector. Thanks for the hint.

Sorry I didn't understand how you solved it
