### ISSUE TITLE
[Feature] Export Size

### ISSUE THREAD

**Issue by Chazza** [apexcharts/apexcharts.js#1903]
**Is your feature request related to a problem? Please describe.**	
When exporting graphs, they often end up across random different sizes depending on my browser.

**Describe the solution you'd like**	
I'd like the ability to specify the export size that I want (as an override) within the chart JS.

**Describe alternatives you've considered**	
There isn't any, sadly.

**Additional context**	
Our charts are often used by senior management within the workplace, these charts get exported for showing in presentations, excel sheets etc. It would be perfect to actually set their size fully, to keep it consistant.

**Comment by junedchhipa** [comment]
Sorry, but this is not easily achievable.
The export function captures whatever is drawn on the screen.

**Comment by Chazza** [comment]
> Sorry, but this is not easily achievable.
> The export function captures whatever is drawn on the screen.

Thank you, is it possible we can export with the legend?

**Comment by junedchhipa** [comment]
The legend doesn't show when exported? 
Or if you meant exporting when clicking on legend, then you can try the legend click event
```javascript
chart: {
  events: {
    legendClick: function(ctx) {
      ctx.exports.exportToSVG()
    }
  }
}
```

**Comment by Chazza** [comment]
> The legend doesn't show when exported? 
> 
> Or if you meant exporting when clicking on legend, then you can try the legend click event
> 
> ```javascript
> 
> chart: {
> 
>   events: {
> 
>     legendClick: function(ctx) {
> 
>       ctx.exports.exportToSVG()
> 
>     }
> 
>   }
> 
> }
> 
> ```

Essentially, when I use the export button (hamburger menu) it gives me png, svg etc but it doesn't include the legend.

Is there any way round this?

**Comment by junedchhipa** [comment]
Which browser are you testing on?
Chrome/Firefox works fine.

**Comment by fferlito** [comment]
I have the same issue with v3.35.1, in both Chrome and Firefox
