### ISSUE TITLE
Tooltip doesn't show for a bar chart with value zero

### ISSUE THREAD

**Issue by dgandhi1993** [apexcharts/apexcharts.js#1904]
# Bug report

## Codepen
[Example](https://codepen.io/dgandhi1993/pen/WNwKBZW)

## Explanation

- In a bar chart tooltip should appear on every bar area, even if its value is zero. If this is because tooltip appears on actual bars, can we have a provision to show tooltips on labels as well for such cases?
- No tooltip appears at the moment for series value of zero. Refer the codepen link.

**Comment by junedchhipa** [comment]
Try this
```javascript
tooltip: {
    shared: true,
    intersect: false
}
```
