### ISSUE TITLE
Grid lines overlaps floating legend

### ISSUE THREAD

**Issue by ashlanderr** [apexcharts/apexcharts.js#1907]
# Bug report

## Codepen

https://codepen.io/ashlanderr/pen/VwaGpVa

## Explanation

- What is the behavior you expect?

Floating legend should be in front layer. It must not be overlapped by the rest of the chart.

- What is happening instead?

The legend is under the grid lines of the chart:

![image](https://user-images.githubusercontent.com/25693223/93453830-d8187400-f8e2-11ea-9c70-b7042bfb1459.png)

With single series I can use `offsetY` to shift the legend, but with multiple and unknown number of series that doesn't work. I tried to use the `z-index` property, but it doesn't work in SVG.

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by KylePinkerton** [comment]
@junedchhipa I think the fix 7af7b30221d2ea8470250c0c329d83098da2a425 causes a regression where tooltips and filter functions no longer "work" correctly. For example, when building the library from that commit (7af7b30221d2ea8470250c0c329d83098da2a425) the following behaviour can be observed:
<a href="https://gyazo.com/0bd82c67218d496d10109add026051c7"><img src="https://i.gyazo.com/0bd82c67218d496d10109add026051c7.gif" alt="Image from Gyazo" width="866"/></a>

However, when building the library from the previous commit 7113e8860cd25eb8e072fb28e1c759ef8c90201b the unexpected behaviour can no longer be observed:
<a href="https://gyazo.com/aa86d6130b7653864c57953ec0bee8e1"><img src="https://i.gyazo.com/aa86d6130b7653864c57953ec0bee8e1.gif" alt="Image from Gyazo" width="852"/></a>

The code used in above examples is:
``
import React, { Component } from "react";
import Chart from "react-apexcharts";

const colorArray = ["#0490FD", "#2EBCA7", "#C73583", "#FFBB4B", "#8033BA"];

var options = {
  series: [
    {
      name: "Series 1",
      data: [1, 2, 3]
    },
    {
      name: "Series 2",
      data: [1, 2, 3]
    },
    {
      name: "Series 3",
      data: [1, 2, 3]
    },
    {
      name: "Series 4",
      data: [1, 2, 3]
    },
    {
      name: "Series 5",
      data: [1, 2, 3]
    }
  ],
  colors: colorArray,
  states: {
    hover: { filter: { type: "darken", value: 0.85 } }
  }
};

class App extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div className="app">
        <div className="row">
          <div className="mixed-chart">
            <Chart
              options={options}
              series={options.series}
              type="bar"
              width="600"
            />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
```

**Comment by junedchhipa** [comment]
@KylePinkerton Thanks for the heads up.
I was going to release a new version in a few hours and this really helped.
Looking into this.

**Comment by KylePinkerton** [comment]
No worries! Thanks for all your hard work on this awesome project!

**Comment by ashlanderr** [comment]
Hello. Is there any updates about the issue? Maybe I can help fix it?

**Comment by ashlanderr** [comment]
@junedchhipa could you please look at this issue again?

**Comment by drashtipatoliyaARIS** [comment]
is there any update on floating legend overlapped by gridlines? I am facing the same issue. 
Attaching code of legend config:
 legend: {
      show: true,
      showForSingleSeries: true,
      position: 'left',
      horizontalAlign: 'left',
      floating: true,
      fontSize: '12px',
      offsetX: 20,
      offsetY: -4,
      markers: {
        width: 15,
        height: 2,
        radius: 0,
        offsetY: -3
      },
      tooltipHoverFormatter: function (seriesName, opts) {
        return seriesName + ' - <span style="color: #212529;font-weight:600;">' + opts.w.globals.series[opts.seriesIndex][opts.dataPointIndex]?.toFixed(2) + ' %' + '</span>'
      }
    }
![image](https://github.com/apexcharts/apexcharts.js/assets/109167206/8b994e35-095b-4182-9757-c815b2aae3b9)
