### ISSUE TITLE
Apex Global Configuration

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [apexcharts/apexcharts.js#1909]
# Bug report
Something is wrong with global configuration. I'm using react-apexcharts. I want to set some default settings for all charts. Somewhere i found that i can do it by using window.Apex. But i have problem: i set default settings using window.Apex inside my App component, then some component that has chart is loaded (for example lazy loaded with routing, apexCharts script also will be loaded to page) and that object (window.Apex) is overridden by empty object. I have found place where window.Apex is setted to empty object: 
![image](https://user-images.githubusercontent.com/12056012/93504015-8b07c280-f921-11ea-8cc4-a5558befb0fc.png)
I think you need to check if object already exists, or maybe I'm trying to set default configuration incorrectly, please let me know.

**Comment by junedchhipa** [comment]
You're right.
I didn't take into consideration the lazy loading thing.
I will implement your suggestion of checking window.Apex existence before making it null.
Thanks for reporting the bug.

**Comment by junedchhipa** [comment]
Fixed it.
A new version will be released this weekend which will have this fix.
