### ISSUE TITLE
Heatmap bug in 3.21.0

### ISSUE THREAD

**Issue by konradstrek** [apexcharts/apexcharts.js#1916]
Using version: 3.21.0

Hover on squares is bugged - some squares are too much to left and right and some are at the center
Color - Empty value have is now filled, previously was white

Preview: https://ibb.co/txBjsvs

**Comment by junedchhipa** [comment]
Can you please create a Codepen so it can be reproduced easily?

**Comment by junedchhipa** [comment]
You're right. I have corrected the shade for the heatmap.
Will be available in next release.
