### ISSUE TITLE
Marker "Discrete" API documentation

### ISSUE THREAD

**Issue by brockelmore** [apexcharts/apexcharts.js#192]
**Is your feature request related to a problem? Please describe.**
I want to be able to modify individual markers in a series - it seems that it is possible with the "discrete" label in Markers.js, but there is no documentation and it is a bit confusing to work out what it does. 

**Describe the solution you'd like**
If you could give me just one example of usage that would be great.

**Describe alternatives you've considered**
I can add new series, but if it is an area chart with markers, and I set stroke to smooth, the points will be slightly off the line. I have considered trying to implement a similar logic to that used for creating the smoothing of a line and offset the point that way but it seems like a lot of extra work.

**Comment by brockelmore** [comment]
Never mind i figured it out...

For those who look for this later: 
`
	markers: {
			discrete: [{i:1, j:3, strokeColor:"#FFF", fillColor:"#000", size:12}],
			size: [0,3],
			strokeColor: ["#fff","#fff"],
			strokeWidth: 3,
			strokeOpacity: 1,
			fillOpacity: 1,
			hover: {
				size: 6
			}
		}
`
Where i = seriesIndex, j is the specific marker's index, with fill, stroke, and size as available to change. Above, this changes the 3rd marker in the second series (as the series are indexed from 0), and sets the fill to black, stroke to white, and size to 12.

**Comment by junedchhipa** [comment]
Hi, thanks for bringing this to attention. I am going to change the property names in the discrete markers to something meaningful. `i`, `j` doesn't make sense.
So, proposed values will be

```javascript
markers: {
  discrete: [{
    seriesIndex: 1,
    dataPointIndex: 3,
    ...
    ...
  }]
}
```

The change will be done in 2.2.1
The docs will be updated too, thanks.

**Comment by junedchhipa** [comment]
Updated the documentation for `markers.discrete` - https://apexcharts.com/docs/options/markers/#markerDiscrete
Make sure, you update the params to reflect the latest props.

```javascript
markers: {
  discrete: [{
    seriesIndex: 0,
    dataPointIndex: 7,
    fill: '#e3e3e3',
    stroke: '#fff',
    size: 5
  }, {
    seriesIndex: 2,
    dataPointIndex: 11,
    fill: '#f7f4f3',
    stroke: '#eee',
    size: 4
  }]
}
```
