### ISSUE TITLE
Point annotations in stacked horizontal bar chart not working as expected

### ISSUE THREAD

**Issue by CarlHenrik** [apexcharts/apexcharts.js#1920]
# Bug report

## Codepen

https://codepen.io/Scopperloit/pen/MWyzzYM

## Explanation

- **What is the behavior you expect?**
I want to be able to set point annotations in horizontally stacked bar charts, where the vertical y-axis represent categories, and the horizontal x-axis represents the bar values. It appears that the x-axis and y-axis are swapped for horizontal bar chart. Ideally, the point annotation's coordinates should be on the format `P = { x: numerical value, y: category string }
`
- **What is happening instead?**
The point's x-coordinates are aligning along the horizontal x-axis by categories, even though the categories are on the vertical y-axis. The point's y-coordinates appears to be determined by the numerical value, even though these values are on the horizontal x-axis. It appears the point coordinates does not take into account that the x-axis and y-axis are swapped for horizontal charts.

- **What error message are you getting?**
None.

**Comment by siumingdev** [comment]
I have faced same problem... although I am using react-apexcharts

**Comment by DanielBlsn** [comment]
Even with the latest version of ApexCharts, this bug is still present. Has anyone figured out a workaround? Thanks!

**Comment by Dblsn01** [comment]
This bug is still present in the latest version, has anyone found a workaround? Thanks

**Comment by marnunez** [comment]
Same here

**Comment by dkgkejdrb** [comment]
same here... is there any solution?
