### ISSUE TITLE
Data labels displaying log value in logarithmic scale instead of actual value

### ISSUE THREAD

**Issue by vishmay-AF** [apexcharts/apexcharts.js#1925]
# Bug report
Data labels showing log value in a logarithmic scale

## Codepen
https://codepen.io/ericpresas/pen/OJVpJLV
Turn datalabels flag to true and see the result

## Explanation

- What is the behavior you expect?
Actual value of y axis, not log value
- What is happening instead?
log value is displayed
- What error message are you getting?
no error message

**Comment by junedchhipa** [comment]
You're correct. I will look into this soon.

**Comment by Shreyaschorge** [comment]
@junedchhipa 
Any updates on this?
