### ISSUE TITLE
Get annotation details upon the click on it.

### ISSUE THREAD

**Issue by wiadev** [apexcharts/apexcharts.js#1927]
Hi
I've been using apexchart for a while and I've been very enjoying it. Thanks for a great plugin.

Recently, I had one issue which I couldn't figure it out.
![Screenshot at Sep 23 05-20-24](https://user-images.githubusercontent.com/18234060/94011789-c27cd180-fd5c-11ea-8d87-df9abfee09b1.png)
I need to remove the annotation when I click on it but I can't figure out an annotation click event for this.

Any suggestions?

Thanks

**Comment by junedchhipa** [comment]
There is no special event for annotation click.
You may try the `click` event of ApexCharts and check which element is clicked on. Based on that, you may remove annotation.

```javascript
options = {
  chart: {
    events: {
      click: function (e, ctx, options) {
        // check e.target here
      }
    }
  }
}

**Comment by wiadev** [comment]
Hi @junedchhipa . is there any way to figure out which item was selected in annotations array?

```
limit.forEach(value => {
          if (value.startDate && value.endDate) {
            xaxis.push({
              x: new Date(value.startDate).getTime(),
              x2: new Date(value.endDate).getTime(),
              fillColor: "#22C6C9",
              opacity: 0.2,
            });
          }
        })
```

As you can see, I have several annotations and I need to know which item(or index) was selected. 
Thanks
