### ISSUE TITLE
Sync selection on scatter charts

### ISSUE THREAD

**Issue by kanchev** [apexcharts/apexcharts.js#193]
**Is your feature request related to a problem? Please describe.**
Syncing diagrams within a dashboard on mouse hover events is really nice. What's actually missing is syncing the selection as well. This would be really useful for scatter plots which contain dense areas of points.

**Describe the solution you'd like**
Allow charts to be rendered with preselected data points. This way it'd would be possible to at least manually sync charts across a dashboard.  (e.g. Graphics.pathMouseDown())

**Describe alternatives you've considered**
Sync charts selection within a given group they way the mouse hover is being synced.
(like the dashboard demos)

**Comment by junedchhipa** [comment]
Do you mean - if you make a selection in 1 chart - you want to load data in other charts based on that?

Like this?
![screen shot 2018-11-13 at 3 09 43 pm](https://user-images.githubusercontent.com/17950663/48404438-3825b880-e756-11e8-9d5c-bb9114ed86c9.png)

A live example of the above image from plot.ly - https://codepen.io/plotly/pen/EPEGyE

Or- 
Do you mean, when you make the selection in 1 chart - all other charts in the group should have the same selection? I don't think - this is very useful.

If you meant the former, then it is indeed a very good suggestion. I can think of providing some additional examples to make use of this event https://apexcharts.com/docs/options/chart/events/#selection in synced/grouped charts.

**Comment by kanchev** [comment]
I guess it's a common thing what I'm doing since you already described it.

My first chart is similar to your first example but it's bar chart. When a bar is selected then the second and third scatter charts are loaded (so inverted chart types for your example). The scatter charts are loaded with same  x-axis but different y-axis as they display different values for the x-points. The scatter charts might contain areas with high density (depending on the zoom level) so that it'll be nice to mark multiple points in one scatter chart and then go to the next one(s) and analyze the selection/markers there.

I was thinking to implement this with markers as a workaround but actually what I'm looking for is kind of a different views (y-axis) for my x-points where I can analyze them in the different charts and select/deselect them, so that the selection at the end is just one set which would be the result of my analysis.

**Comment by junedchhipa** [comment]
I was confused between `selection` and `dataPointSelection` events.
My previous answer was based on the `selection` which you can see on this demo - https://apexcharts.com/javascript-chart-demos/area-charts/github-style/

But, now it's clear that you meant [dataPointSelection](https://apexcharts.com/docs/options/chart/events/#dataPointSelection) where you click on markers of 1 chart and based on that, select the markers of other charts.

I will take a look at how feasible is this new feature; keeping this ticket open.

**Comment by junedchhipa** [comment]
@kanchev 
I already thought of the same way you described. At one point, I had this option in the config object, but currently, you will find that it is commented out - as it didn't work out as I expected - (chart.selection.selectedPoints in /settings/Options.js)

I will give another try to allow the user to have preSelected dataPoints. Thanks for the input.
