### ISSUE TITLE
My Chart Annotation is weird

### ISSUE THREAD

**Issue by ariefumarjati** [apexcharts/apexcharts.js#1930]
# Bug report

![image](https://user-images.githubusercontent.com/20533130/94127862-a32c9400-fe83-11ea-9e8e-2b20c40cd485.png)

How to fix this?

## Explanation

- What is happening instead?
- What error message are you getting?

**Comment by Biskit1943** [comment]
I have a similar problem using vue-apexcharts, here is a fiddle to reproduce:

https://jsfiddle.net/69hs2vr3/

apexcharts: 3.20.2
vue-apexcharts: 1.6.0
vue: 2.6.12

**Comment by junedchhipa** [comment]
Your data series should be sorted into ascending order if you are using `datetime` or `numeric` x-axis scale.
ApexCharts doesn't sort the data.

So, please make sure your data is into ascending order and the strange drawing issue will be solved.
