### ISSUE TITLE
Add custom annotations with picture

### ISSUE THREAD

**Issue by gsaada** [apexcharts/apexcharts.js#1931]
Please help!
I'm trying to create this chart with no success.
Should I use annotations? can I add pictures to annotations?
Tried to add images with appendTo but Don't have class selector for specific annotation 

![image](https://user-images.githubusercontent.com/6073519/94142825-87bb8c00-fe77-11ea-85af-6e15f02352a0.png)

**Comment by junedchhipa** [comment]
Use point annotations.
Here is a complete example - https://codepen.io/apexcharts/pen/GRZzMXq

**Comment by gsaada** [comment]
Thanks @junedchhipa for you response.
I tried point annotation but as you can see my design include a stroke from the picture down to Xaxis.
As far as I know Point don't have stroke option.

Any suggestions?
Maybe I can combine Xaxis annotations and point annotation?

**Comment by abyshake-anand** [comment]
> Use point annotations. Here is a complete example - https://codepen.io/apexcharts/pen/GRZzMXq ![Screenshot 2020-09-24 at 6 41 21 PM](https://user-images.githubusercontent.com/17950663/94149352-69648900-fe95-11ea-8beb-12c7ced75a82.png)

In the example you shared, if I try downloading a png for the chart, the point icon gets replaced by an blank image placeholder.
