### ISSUE TITLE
plotted on wrong category

### ISSUE THREAD

**Issue by selient** [apexcharts/apexcharts.js#1932]
# Bug report

## Codepen

https://codepen.io/ycalcalcal/pen/OJNdGOq

## Explanation

- What is the behavior you expect?
Series A should be plotted on "A" and "C"
- What is happening instead?
Series A is plotted on "A" and "B"
- What error message are you getting?
no

**Comment by selient** [comment]
it seems that categories is calculated on first series

```js
var options = {
  chart: {
    height: 350,
    type: "line",
  },
  series: [
    {
      name: "Series B",
      data: [{x: 'A', y: 22},{x: 'B', y: 11},{x: 'C', y: 21}]
    },
    {
      name: "Series A",
      type: "column",
      data: [{x: 'A', y: 1},{x: 'C', y: 2}]
    },
  ],
  xaxis: {
    type: "category"
  },
};


```

**Comment by selient** [comment]
it's not working even I set
```js

  xaxis: {
     categories : ["A","B","C"]
  },
```

**Comment by CarlHenrik** [comment]
Indeed. It appears the categories array of the first series is applied also to the second series, even to the series tooltip, despite having explicitly specified it's own array of categories.

**Comment by simplecommerce** [comment]
I am encountering the same issue on my end.

Did you guys manage to find a solution for this?
