### ISSUE TITLE
Mixed line column chart with negative values is not drawn properly

### ISSUE THREAD

**Issue by AchoArnold** [apexcharts/apexcharts.js#1939]
# Bug report

I'm trying to create a mixed line column chart 

## Codepen

[Link To CodePen](https://codepen.io/najela/pen/zYqXwOZ)

```javascript
var options = {
    series: [{
        name: 'Website Blog1',
        type: 'column',
        data: [440, -505, 414]
    }, {
        name: 'Social Media',
        type: 'line',
        data: [23, 42, 35]
    },
    {
        name: 'Website Blog2',
        type: 'column',
        data: [440, 505, 160]
    }],
    chart: {
        height: 350,
        type: 'line',
    },
    stroke: {
        width: [0, 4]
    },
    title: {
        text: 'Traffic Sources'
    },
    dataLabels: {
        enabled: true,
        enabledOnSeries: [1]
    },
    labels: ['01 Jan 2001', '02 Jan 2001', '03 Jan 2001'],
    xaxis: {
        type: 'datetime'
    },
    yaxis: [{
        title: {
            text: 'Website Blog',
        },

    }, {
        opposite: true,
        title: {
            text: 'Social Media'
        }
    }]
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
```

## Explanation

I want to create a mixed/combo chart consisting of 1 line chart and 2 column charts. When creating 2 column charts, If 1 chart has `negative` data values and the other chart does not, the rendering is weird such that the bar chart without negative values seems to start from the lowest point in the chart instead of starting at zero as shown in the image below

<img width="710" alt="Schermafbeelding 2020-09-28 om 12 02 39" src="https://user-images.githubusercontent.com/4196457/94419337-ea1bd180-0182-11eb-8b90-900b5ae7ffc9.png">

- What is the behavior you expect?

I will expect the `Website Blog2` chart to always start from `0`

- What is happening instead?

The chart starts from the lowest point in the y-axis

- What error message are you getting?

None

**Comment by AchoArnold** [comment]
Keep alive

**Comment by 88solution** [comment]
The same issue to me.
the negative column chart work in pure bar charts.
But, In the mixed line & column chart, the negative column chart doesn't work.

I added the following option to draw the negative column with line chart.
But, it's ignored for the negative values
```
plotOptions: {
    bar: {
        colors: {
            ranges: [{
                from: 0,
                to: 100
                color: '#FF0000'
            },{
                from: -100,
                to: 0
                color: '#00FF00'
            }]
        }
    }
}
```

**Comment by gustavoberwian** [comment]
Hi! I had the same problem here and the solution was very simple but hard to find.

In my case it was just one setting: on chart config I just set stacked option to false.

```js
var options = {
    series: [{
        name: 'Website Blog1',
        type: 'column',
        data: [440, -505, 414]
    }, {
        name: 'Social Media',
        type: 'line',
        data: [23, 42, 35]
    },
    {
        name: 'Website Blog2',
        type: 'column',
        data: [440, 505, 160]
    }],
    chart: {
        height: 350,
        type: 'line',
        stacked: false
    },
    stroke: {
        width: [0, 4]
    },
    title: {
        text: 'Traffic Sources'
    },
    dataLabels: {
        enabled: true,
        enabledOnSeries: [1]
    },
    labels: ['01 Jan 2001', '02 Jan 2001', '03 Jan 2001'],
    xaxis: {
        type: 'datetime'
    },
    yaxis: [{
        title: {
            text: 'Website Blog',
        },

    }, {
        opposite: true,
        title: {
            text: 'Social Media'
        }
    }]
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
```
