### ISSUE TITLE
[Scatter] When changing the amount of data in series the chart breaks if there are more series than before

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/apexcharts.js#194]
## Codepen

https://codepen.io/anon/pen/xQqjzG

## Explanation

- What is the behavior you expect?
When updating a series with a new one with a greater length, the chart should update correctly.

- What is happening instead?
Chart breaks and throws an error

- What error message are you getting?
`TypeError: Cannot read property '0' of undefined`

**Comment by junedchhipa** [comment]
Thanks for reporting, @JCQuintas 
Fixed it
