### ISSUE TITLE
Document how to use DateTime

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#1941]
**Is your feature request related to a problem? Please describe.**	
We can use `formatter` to override `format` with a programmable value, but it might be expected that we would want to reuse the same functionality ApexCharts uses internally, especially `DateTime`, but it seems this object is neither documented nor accessible.

**Describe the solution you'd like**	
Document how to use `DateTime` to format dates in a formatter callback.

**Describe alternatives you've considered**	
I could use a whole other extra library to format dates, but why when one comes bundled with ApexCharts?

**Additional context**	
```js
new DateTime
```
>Uncaught ReferenceError: DateTime is not defined

**Comment by junedchhipa** [comment]
Good suggestion, I will provide the context of DateTime Class in the formatter callback so it can be utilized.

**Comment by junedchhipa** [comment]
Here you go

```javascript
xaxis: {
  labels: {
    /**
    *
    * @param { String } value - The default value generated
    * @param { Number } timestamp - In a datetime series, this is the raw timestamp 
    * @param { object } contains dateFormatter for datetime x-axis
    */
    formatter: function(value, timestamp, opts) {
      return opts.dateFormatter(new Date(timestamp)).format("dd MMM")
    }
  }
}
```

Docs: https://apexcharts.com/docs/options/xaxis#formatter
