### ISSUE TITLE
Clear box-selection

### ISSUE THREAD

**Issue by FelixWaigner** [apexcharts/apexcharts.js#1943]
**Is your feature request related to a problem? Please describe.**	
When i created a selection with the box-selection form the toolbox, i can't find a way to clear it.

**Describe the solution you'd like**	
Ideally, it would be possible to clear a selection by simply clicking outside of the selection area on the chart.

**Describe alternatives you've considered**	
A reset button for clearing the selection

**Additional context**	
I want to select multiple datapoints.

**Comment by junedchhipa** [comment]
Provided a solution in #1094
