### ISSUE TITLE
 Is there any way to show the column ( bar chart ) of value 0 ?

### ISSUE THREAD

**Issue by Khanh-Ngy** [apexcharts/apexcharts.js#1945]
> I saw that and just corrected it.
> When the value was 0, it was getting ignored.
> 
> Thanks for reporting

I need to show the columns of value 0 and their labels. But got nothing. How can i do it ?
![image](https://user-images.githubusercontent.com/71876037/94636251-ce3d3a80-02fe-11eb-8d9b-ca318f302663.png)

_Originally posted by @Khanh-Ngy in https://github.com/apexcharts/apexcharts.js/issues/65#issuecomment-701119900_

**Comment by junedchhipa** [comment]
Here's an example - https://codepen.io/apexcharts/pen/ExKzQbX

![Screenshot 2020-09-30 at 12 15 28 PM](https://user-images.githubusercontent.com/17950663/94651782-a4900d80-0316-11eb-9c24-aaef957d4076.png)
