### ISSUE TITLE
Multi-line (word wrapping) for xaxis labels do not work when using paired-values series

### ISSUE THREAD

**Issue by paulovpereira** [apexcharts/apexcharts.js#1949]
# Bug report

## Codepen

https://codepen.io/paulovpereira/pen/mdPYQpJ

## Explanation

- What is the behavior you expect?

When `x` value is an array, the multi-line (word wrapping) behaviour should be applied for xaxis labels. I expected same behaviour as stated in the documentation: https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/

- What is happening instead?

Instead of breaking lines for the labels, the items from array are being added in the same line separated by commas.

- What error message are you getting?

 No error messages, just wrong behaviour.

**Comment by GinaJemy** [comment]
I'm having the same issue

**Comment by paulovpereira** [comment]
Amazing, thanks @junedchhipa!

**Comment by okuja** [comment]
Same issue  exists on ng-apex charts 1.7.1   and apex charts 3.35.2  when using Angular 13

**Comment by paulovpereira** [comment]
@junedchhipa please, check the codepen that I created again. The behavior is still wrong, but different now. The values in each line is the whole array separated by comma, instead of the position in the array matching the line index.

**Comment by eduardo-amaro-maciel** [comment]
I'm also having this problem, I had implemented the chart code last week and this Monday it had this bug

**Comment by junedchhipa** [comment]
This issue is fixed in the latest version [apexcharts@3.35.3](https://www.npmjs.com/package/apexcharts/v/3.35.3)

**Comment by lbgm** [comment]
@junedchhipa thank for your reply. but it seems that the bug appears when i build the project for production. i tried [apexcharts@3.35.3](https://www.npmjs.com/package/apexcharts/v/3.35.3) before create my fix and nothing, but i prefer my own fix. Thanks for all
