### ISSUE TITLE
Feature Request: Sankey Diagram

### ISSUE THREAD

**Issue by kkontagion** [apexcharts/apexcharts.js#195]
Are there any new chart types being added? I'm particularly interested in the Sankey diagram.

**Comment by junedchhipa** [comment]
New chart types are being added, unfortunately, Sankey isn't one of them.
No plans to implement in the near future.

**Comment by andyg2** [comment]
3 years, 4 months, 23 days ago Sankey charts were not on the horizon.
I'm just wondering/hoping that might have changed given how popular they are now a days.

**Comment by vazkir** [comment]
> 3 years, 4 months, 23 days ago Sankey charts were not on the horizon. I'm just wondering/hoping that might have changed given how popular they are now a days.

Me 2!

**Comment by fabiot21** [comment]
x3!!

**Comment by vazkir** [comment]
@junedchhipa, is there any chance that since nov 2018 your mind might have changed on a Sankey diagram implementation? It would be appreciated very much by a lot of people, especially since the only real alternative [costs $500 dollars from React Extreme....](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/SankeyChart/React/Light/)

**Comment by andyg2** [comment]
> @junedchhipa, is there any chance that since nov 2018 your mind might have changed on a Sankey diagram implementation? It would be appreciated very much by a lot of people, especially since the only real alternative [costs $500 dollars from React Extreme....](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/SankeyChart/React/Light/)

These have a very similar data structure and quite a few more options.
https://echarts.apache.org/examples/en/index.html#chart-type-sankey

**Comment by adhikari-anish** [comment]
x4

**Comment by glmn** [comment]
x5

**Comment by amonsour** [comment]
x6!

**Comment by valentinoConti** [comment]
x7

**Comment by glmn** [comment]
x100

**Comment by maxkozlowski** [comment]
x11

**Comment by ishwark7** [comment]
x101

**Comment by ishwark7** [comment]
4 years, 9 months, 7 days and counting!

**Comment by brianlagunas** [comment]
> 4 years, 9 months, 7 days and counting!

And not a single PR from anyone 🤷‍♂️

**Comment by ishwark7** [comment]
@junedchhipa still no plan?

**Comment by Luke20w** [comment]
Would also be very interested in sankey. That is the the only thing holding me back from switching my company over to Apex

**Comment by jahrling** [comment]
FWIW, someone integrated Apex into Bubble (a no-code platform) and included Sankey in there.
https://sankeydemo.bubbleapps.io/version-test
