### ISSUE TITLE
Stacked Bar -> Percentage Not Shown on dataLabels 

### ISSUE THREAD

**Issue by acar-murat** [apexcharts/apexcharts.js#1951]
# Bug report

## Codepen

In stacked bar chart that stacked type is "100%", datalabels not shown for this range `1<=value<= 2` [Here](https://codepen.io/murat-acar/pen/JjXQemw) is the codepen example. 
Also same problem in vue side

**Comment by junedchhipa** [comment]
You're right.
This will be addressed soon.
