### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' (apexcharts.min.js:6)

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [apexcharts/apexcharts.js#1952]
Hello!
How can I improve to prevent the browser from showing such messages?

Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by simonmaass** [comment]
+1 totally agree

**Comment by junedchhipa** [comment]
Duplicate of #937
