### ISSUE TITLE
Graph does not render using bootstrap tabs

### ISSUE THREAD

**Issue by victorLessa** [apexcharts/apexcharts.js#1954]
It doesn't smell like a bug, but I would like some help
I have an apex set separated by tabs using bootstrap
I render the graph without the data and do a search via axes to update the apex options and show the values, however when I load the page and jump to the second tab and I hope to load all the graphs and go back to the initial tab I realize that the graphics that were still loading simply disappear
there is a blank screen space
Could you tell me why?
Obs: Console does not show error

**Comment by junedchhipa** [comment]
Is this the same issue? https://stackoverflow.com/questions/53074619/

**Comment by VictorLessa** [comment]
No, the problem with stackoverflow is that the chart does not load when clicking on a tab
In my case it loads normally, but if I change the tab before the graph loads completely and then go back to the tab that had the graphs loading, these graphs do not appear / do not render

**Comment by Codemonkey1973** [comment]
I just had a problem that may be similar to this and found a workaround that works for me.

I have a page that loads, then depending on the content of some data retrieved in JSON format, some bootstrap tabs (actually nav-pills in my case) are dynamically created with javascript and then charts are added to the tabs.

I can then click through the tabs/pills and all looks good, the charts appear on all tabs. However, lets say I do the following:

1) Refresh the page, the default first tab loads and all charts are rendered.
2) I then click to the second tab, again all charts are rendered.
3) Whilst remaining on the second tab, I then click a button that retrieves data covering a different timespan and update all of the charts on all tabs using the .updateOptions() function.

The charts on the current tab get updated and rendered correctly. However, if I now click back to the first tab, the charts are blank (although I can get them to be re-rendered correctly by slightly resizing the browser window).

If I were to click on any other tabs, charts that have as yet never been displayed DO get shown correctly.

I added an event handler for the bootstrap tab change and in there tried a number of things. Calling the .render() function worked but was incredibly slow, much slower than generating the whole page initially, so then I started looking at how I could trigger the window resize event for the chart and found the function _windowResize(). I added a call to this for each chart about to be displayed in the event handler and for me this works fine, though I think it would be better if I didn't have to do this so would consider it a bug in the library.

My event handler is included here, though you'd probably have to change a[data-toggle="pill"] to a[data-toggle="tab"] 

`

    $(document).on('shown.bs.tab', 'a[data-toggle="pill"]', function (e) {

          var target = $(e.target).attr("href");
          var idx;
          for(idx = 0; idx < lineCharts.length; idx++){
              if((lineChartOptions[idx] != null) && (lineChartOptions[idx].chart.group == target)){
                  console.log("Re-rendering line chart " + idx + " " + lineChartOptions[idx].series[0].name);
                  lineCharts[idx]._windowResize();
              }
          }

           for(idx = 0; idx < barCharts.length; idx++){
               if(barCharts[idx] != null && barChartOptions[idx].chart.group == target){
                   console.log("Re-rendering bar chart " + idx);
                   barCharts[idx]._windowResize();
               }
           }
      });
`
Hope this is helpful!

**Comment by matzexcom** [comment]
It seems hidden elements/charts will not be rendered, my workaround is

`        var chart = new ApexCharts(
          document.querySelector("#chart"),
          options
        );

        chart.empty = true;

        $("[data-toggle='tab']").bind("shown.bs.tab", function () {
          if (chart.empty) {
            chart.render();
            chart.empty = false;
          }
        });`
