### ISSUE TITLE
Getting ESM build back

### ISSUE THREAD

**Issue by guillaume-vernet** [apexcharts/apexcharts.js#1955]
Since release v3.20.0, the ESM build was removed. I understand this was because library wrappers didn't need it and it caused them problems.

I'm involved in several Polymer 3 based projects, where I do use Apexcharts as esm module. So I'm now stuck with version 3.19.3.

Is it possible to get back the ESM build? Or do you have pointers on how proceed ?
NB: related esm build feature-request: #221

Thanks in advance,
(and many thanks for this great charting library!)

Guillaume

**Comment by junedchhipa** [comment]
So, the ESM build doesn't cause any issues in your projects?

The reason I discontinued was that it was not needed in the wrapper libraries anymore (SVG.js exposed a global variable which was exported as the default one).
I can continue bundling the ESM build along with the rest of the files from the next version.

**Comment by guillaume-vernet** [comment]
Yes, the ESM build is running fine.

Looking forward to next release
Thanks

**Comment by theuone** [comment]
Is this fixed? I see an esm file in the latest version, but when I add 
import ApexCharts from 'apexcharts';
I get
Uncaught SyntaxError: The requested module '../node_modules/apexcharts/dist/apexcharts.common.js' does not provide an export named 'default'

**Comment by pijusn** [comment]
```javascript
import ApexCharts from 'apexcharts/dist/apexcharts.esm.js'
```
and 
```html
<link rel="stylesheet" href="/node_modules/apexcharts/dist/apexcharts.css">
```

Works for me with Polymer3 modules.

**Comment by junedchhipa** [comment]
Re-added ESM build from v3.22.1
