### ISSUE TITLE
How to make yAxis show integers with floating point series

### ISSUE THREAD

**Issue by thellimist** [apexcharts/apexcharts.js#1960]
# Bug report

## Codepen

https://codepen.io/thellimist/pen/vYKBPMb

![image](https://user-images.githubusercontent.com/6690196/95230187-219a1600-0834-11eb-9a9a-28993e6aa162.png)

## Explanation

- What is the behavior you expect?
yAxis should show 1,2,3,45
- What is happening instead?
yAxis is showing 1,2,2,2,3,3,3,3...

How can we show integer values using floating point series

https://codepen.io/thellimist/pen/BazBEBy

![image](https://user-images.githubusercontent.com/6690196/95230815-ed732500-0834-11eb-80d0-ddd9e1f5fa65.png)

this version is with  `return value.toFixed(1);`. It's slightly more readable but I want them to be integers not floating points

**Comment by junedchhipa** [comment]
Fixed it.

**Comment by AndreaMinato** [comment]
Hi @junedchhipa .
As always thank for your work and your speed.
May I ask when this fix will be published with a new version?
