### ISSUE TITLE
Marker hover doesn't work behind annotation point

### ISSUE THREAD

**Issue by wiadev** [apexcharts/apexcharts.js#1961]
Hi
I have a line chart and I need to change the certain color of the marker(data point) but I don't think we can change the color of certain points(correct me if I'm wrong, please.)

![image](https://user-images.githubusercontent.com/18234060/95327600-245b3200-0859-11eb-9da1-4cc625e073f6.png)

So I figured that I need to draw an annotation point over the point but after that, hovering on the marker doesn't work because of the annotation.

I saw a couple of demos with annotation but still behind marker hover tooltip works but it's not working on my end even after I follow the demo.

Any thoughts?

Thanks.

"ng-apexcharts": {
      "version": "1.5.4",
}

**Comment by stashaway** [comment]
I'm working on a similar issue (coloring certain markers). Have you looked in to the 'discrete' array in the markers config? It lets you specify an index and a different color. Might solve your overlay issue. Good luck!
