### ISSUE TITLE
radial multiple chart data in percentage not accurate

### ISSUE THREAD

**Issue by FanaticJK** [apexcharts/apexcharts.js#1968]
I want to implement radial multiple chart but the result is like [this](https://codepen.io/regolithsjk/pen/vYKEeLE)

what i have done is 

`<div id="chart"></div>`

js

> var options = {
>   chart: {
>     height: 350,
>     type: "radialBar"
>   },
>   plotOptions: {
>     radialBar: {
>       dataLabels: {
>         name: {
>           fontSize: "22px"
>         },
>         value: {
>           fontSize: "16px"
>         },
>         total: {
>           show: false,
>           label: "Total",
>           formatter: function (w) {
>             return [15327, 1041].reduce((a, b) => a + b, 0);
>           }
>         }
>       }
>     }
>   },
>   series: [15327, 1041],
>   labels: ["test", "test2"],
> };
> var chart = new ApexCharts(
>   document.querySelector("#chart"),
>   options
> );
> 
> chart.render();
>

**Comment by junedchhipa** [comment]
Radial-bar charts only accept values between 0 and 100
So, you will have to calculate the percentages and then input them.
It's more like a progress-bar.
