### ISSUE TITLE
showing NaN% on donut chart, top/left corner when series with zero values

### ISSUE THREAD

**Issue by visaru** [apexcharts/apexcharts.js#197]
## Codepen

https://codepen.io/anon/pen/WYOweJ

## Explanation

- Clean disaplay showing 0 as total on the donut chart
- Showing _aN%_ on the **top/left** of the div on donut chart
- console is full of NaN errors
`apexcharts:1 Error: <path> attribute d: Expected number, "M NaN NaN A 64.731…".`

BTW how can I remove Total as a label? how can I show just the total number instead on donut chart

**Comment by junedchhipa** [comment]
Thanks for reporting, just fixed it.
Release version 2.2.2 - in which the donut labels are hidden by default as many users suggested of hiding them in first place. So, make sure you enable them again in `plotOptions.pie.donut.labels.show` if you want to show. 

You can control the `total` label in `plotOptions.pie.donut.labels.total`
More info in the docs - https://apexcharts.com/docs/options/plotoptions/pie/#total
