### ISSUE TITLE
Toolbar menu z-index is to high

### ISSUE THREAD

**Issue by Madeindreams** [apexcharts/apexcharts.js#1971]
The icons from the toolbar menu are showing over my elements. How can I reduce it's value? I have tried 99999999 on my element and they are still over it.

**Comment by junedchhipa** [comment]
`.apexcharts-toolbar` z-index is set to 11.
Which elements are covered by the toolbar? Can you reproduce the issue in a Codepen?

**Comment by Madeindreams** [comment]
Actually i have a element with no z-index containing other elements with higher z-index. But because the parent element had none the z-index of 11 could get above them all. I have fixed my issue!

**Comment by nurhamsah1998** [comment]
> `.apexcharts-toolbar` z-index is set to 11. Which elements are covered by the toolbar? Can you reproduce the issue in a Codepen?

work for me :
`.apexcharts-toolbar {
  z-index: 0 !important;
}`
