### ISSUE TITLE
Selection not stopping after releasing click on Firefox

### ISSUE THREAD

**Issue by rrrazvann** [apexcharts/apexcharts.js#1981]
When I am trying to select an interval, it looks like the mouseup event is not triggered, and the selection does not stop even if I am not holding click anymore. The only way to stop, is by releasing the click on the expanding zone (little square). I also observed that this only reproduced when selecting from left to right, not from right to left.

Browser: Firefox 81.0.2 (64-bit)
OS: MacOs Catalina 10.15.6

![Screen Recording 2020-10-16 at 12 56 55](https://user-images.githubusercontent.com/36448915/96245039-8df0e400-0faf-11eb-8cfc-651ddad1f423.gif)

**Comment by gabrielburich** [comment]
I have the same issue, any solution or workaround?

**Comment by KristofVDB1** [comment]
This still remains an issue. Any possible fixes planned for this?

**Comment by KristofVDB1** [comment]
I'm a bit disappointed that over the course of a full year, there hasn't even been a single reply. Is this something you guys can look into or at least give us an update about? 

Thanks!

**Comment by brianlagunas** [comment]
Being new to this repo, I can say that for the past couple of years, there has only been one person managing this extremely popular project. As you can imagine, he does not have time to answer and respond to every issue or question posted. There are literally thousands of them.

I'm a bit disappointed that the community has not stepped up to help address any of these issues in over a year. I mean, the code is freely available and PRs are always welcomed.

This project needs the community to step up and help wherever they can.

**Comment by githubEnjoer1** [comment]
Is there any known WA for this issue?

**Comment by Charlvdm1** [comment]
Hey Everyone

Sorry I know this was closed. but has anyone got a workaround for this?
