### ISSUE TITLE
Legend is hiding below the Radial bar chart, how to control the Z index of the legend so that I can place on top of radial Bar chart 

### ISSUE THREAD

**Issue by raghunayudurayapudi** [apexcharts/apexcharts.js#1986]
Hi 
I am working on Displaying the Radial bar chart inside a material ui Paper component , i am using the floating option of        (floating: true) for legend configuration but the radialBar is overalpping the legend. how can i make legend to display on top of radial bar chart 

below is the config i am passing to apex charts
const config = {
  series: [76, 67, 61, 300],
  options: {
    chart: {
      type: 'radialBar',
    },
    plotOptions: {
      radialBar: {
        offsetY: 0,
        startAngle: 0,
        endAngle: 360,
        hollow: {
          margin: 5,
          size: '10%',
          position: 'back',
          background: 'transparent',
          image: undefined,
        },
        // track: {
        //   strokeWidth: '70%'
        // },
        dataLabels: {
          name: {
            show: false,
          },
          value: {
            show: false,
          }
        }
      }
    },
    colors: ['#108ECB', '#009FAE', '#4CB944', '#95190C'],
    labels: ['Claims Completed/Paid', 'Claims Pending', 'Claims Pending, Approved To Pay', 'Claims Denied'],
    legend: {
      show: true,
      floating: true,
      fontSize: '12px',
      offsetX: '50%',
      horizontalAlign: 'right',
      position: 'right',
      labels: {
        useSeriesColors: false,
      },
      markers: {
        size: 0
      },
      formatter(seriesName, opts) {
        return `${seriesName}:  ${opts.w.globals.series[opts.seriesIndex]}`;
      },
      itemMargin: {
        vertical: 3
      }
    },
    responsive: [{
      breakpoint: 480,
      options: {
        legend: {
          show: false
        }
      }
    }]
  }
};

component ---  

           <Paper className={clsx(classes.claims, classes.paper)}>
            <Typography className={classes.header}>
              Claims Summary
            </Typography>
  <Chart options={config.options} series={config.series} type="radialBar" height="100%" />
          </Paper>

---- output --
![image](https://user-images.githubusercontent.com/25806691/96540593-1e5b4d00-126c-11eb-93fa-f733c93db731.png)

**Comment by rjacobson16** [comment]
Was there ever a solution for this issue?
