### ISSUE TITLE
Scatter markers don't show in mixed chart

### ISSUE THREAD

**Issue by thellimist** [apexcharts/apexcharts.js#1988]
# Bug report

## Codepen

https://codepen.io/thellimist/pen/NWrRqbe?editors=1111

## Explanation

- What is the behavior you expect?
Scatter markers to show

- What is happening instead?
Scatter markers don't show but you can hover over them

**Comment by junedchhipa** [comment]
You had a typo in your config. It has to be `markers`

```javascript
markers: {
  size: [0, 5, 5, 5],
  hover: {
    size: 10,
    sizeOffset: 3
  }
}
```
