### ISSUE TITLE
Apex Chart's - Mouse Position wrong when Scale Transform is used

### ISSUE THREAD

**Issue by jogibear9988** [apexcharts/apexcharts.js#1991]
# Bug report

Mous Position does not work when shown in a transformed Container.
Problem is, the site I use, zooms outside of ApexCharts.

## Codepen

https://codepen.io/jogibear9988/pen/PozGOJM

## Explanation

- What is the behavior you expect?
Tooltip Shown on MousePosition

- What is happening instead?
Tooltip Position is wrong

**Comment by jogibear9988** [comment]
Problem also is, Chart is embedded in other side, so I cannot remove the transform.

**Comment by W4G1** [comment]
Also having this problem. Any updates on this?

**Comment by jogibear9988** [comment]
still active

**Comment by W4G1** [comment]
active

**Comment by patryk-zielinski93** [comment]
I also have this problem. I would like to implement fullscreen option that would also enlarge chart with transform: scale.

**Comment by jogibear9988** [comment]
is still relevant

**Comment by jogibear9988** [comment]
still open

**Comment by ArminVanBuuren** [comment]
I have same problem, any solutions?

**Comment by jogibear9988** [comment]
We switched away from apex charts
