### ISSUE TITLE
Need to show all xasix labels

### ISSUE THREAD

**Issue by Khanh-Ngy** [apexcharts/apexcharts.js#1995]
I want to show all x-asix labels on days having null value ( Ex: 1/13, 1/15, 1/17 ... doesn't appear )

https://codepen.io/khanh-ngy/pen/QWNPGdy
![image](https://user-images.githubusercontent.com/71876037/96989514-fb70b780-154f-11eb-93da-6d660d4265f5.png)

my data 
 data: [{x:'2020/01/01 GMT',y:30},{x:'2020/01/03 GMT',y:33},{x:'2020/01/05 GMT',y:45},
                          {x:'2020/01/06 GMT',y:45},{x:'2020/01/06 GMT',y:45},{x:'2020/01/07 GMT',y:45},
                           {x:'2020/01/08 GMT',y:45},{x:'2020/01/09 GMT',y:45},{x:'2020/01/10 GMT',y:45},
                           {x:'2020/01/11 GMT',y: null},{x:'2020/01/28 GMT',y:45}
                          ]
                },
                ],

**Comment by junedchhipa** [comment]
```javascript
xaxis: {
    type: 'datetime',
    labels: {
      hideOverlappingLabels: false,
    },
  }
```

**Comment by Khanh-Ngy** [comment]
@junedchhipa Hi 
I want to ask more: ' How can I show labels every 2 days or n days ? '
 For example :
10/03 - 10/05 - 10/07 ....
