### ISSUE TITLE
Question: Custom object shape in series

### ISSUE THREAD

**Issue by clluiz** [apexcharts/apexcharts.js#1996]
Reading the docs about the series property I can see that it accepts object with format { x, y }. 
My question is: can we use others objects shapes? Like use some kind of format function to tell the chart what are the x and y fields?

Something like:

`series={[{
                  name: 'Amaggi',
                  data: [{ value:19, label:'Label' }]
                }]}`

Rather than:

`series={[{
                  name: 'Amaggi',
                  data: [{ y:19, x:'Label' }]
                }]}`

**Comment by junedchhipa** [comment]
@clluiz Sorry, it doesn't accept custom name strings in the series data.
You will have to `.map` the original values and convert to x/y format.
