### ISSUE TITLE
Decouple max values within series

### ISSUE THREAD

**Issue by L-U-C-K-Y** [apexcharts/apexcharts.js#1997]
**Is your feature request related to a problem? Please describe.**	
We would like to show data from multiple data sources within a chart that have a big difference in values. 

**Describe the solution you'd like**	
A prop/setting that allows that each series in a chart would be decoupled from each other. 

This would mean that if one chart's highest value is 10000 and the other's 100, they have the same hight. 

Even better would be if we could set the max ceiling for each series. 

**Describe alternatives you've considered**	

Overlaying multiple charts, but this would most likely not work properly. 

**Additional context**	
-

**Comment by junedchhipa** [comment]
Why not try a logarithmic y-axis scale for a big difference in the values?

```javascript
yaxis: {
    logarithmic: true
}
```
