### ISSUE TITLE
Cannot read property 'yRatio' of null

### ISSUE THREAD

**Issue by mlapeyre3** [apexcharts/apexcharts.js#1998]
# Bug report

## Codepen
https://codesandbox.io/s/vue-yratio-issue-with-treemap-dmct4

## Explanation
I wanted to create a Vue treemap chart from the example in https://apexcharts.com/vue-chart-demos/treemap-charts/distributed/.

If you look at the codepen, you can see that there is the following error:
`Cannot read property 'yRatio' of null`

If you simply change the type of the chart to something like **bar**, it will work ...

**Comment by hev0n** [comment]
@mlapeyre3 Please ensure that you are using the current  version 3.22. Treemap was added in version 3.21.

[Release: 3.21.0](https://github.com/apexcharts/apexcharts.js/releases/tag/3.21.0)

 In your example you are using version 3.19.

`"apexcharts": "3.19.3",`

Please let me know if a `npm update apexcharts` helped.

**Comment by junedchhipa** [comment]
Yes, upgrading to 3.21 will fix it.
