### ISSUE TITLE
Chart updates

### ISSUE THREAD

**Issue by Sile25** [apexcharts/apexcharts.js#200]
How can i update every chart? And do updates work on Candlestick charts too?

**Comment by junedchhipa** [comment]
https://apexcharts.com/docs/methods/#updateSeries

Yes, `updateSeries()` method works on candlestick charts too

**Comment by Sile25** [comment]
> 
> 
> https://apexcharts.com/docs/methods/#updateSeries
> 
> Yes, `updateSeries()` method works on candlestick charts too
> 
> ```js
> chart.updateSeries([{
>   data: [{
>     x: new Date(2016, 01, 01),
>     y: [51.98, 56.29, 51.59, 53.85]
>   },
>   {
>     x: new Date(2016, 02, 01),
>     y: [53.66, 54.99, 51.35, 52.95]
>   }]
> }])
> ```

Awesome, thank you!
