### ISSUE TITLE
Selection in the bar type starts with spacing to the right

### ISSUE THREAD

**Issue by guigattidev** [apexcharts/apexcharts.js#2000]
# Bug report
When type is area, that is the behavior with I expect
![error-selection-01](https://user-images.githubusercontent.com/1514876/97190553-9ce04f00-1784-11eb-8b95-6d401c70ab61.png)

When type is bar, starts with spacing to the right
![error-selection-02](https://user-images.githubusercontent.com/1514876/97190334-58ed4a00-1784-11eb-97b1-195462e4e978.png)

**Comment by junedchhipa** [comment]
What are your x-axis categories?
Can I see a CodePen?

**Comment by guigattidev** [comment]
https://codesandbox.io/s/sweet-stallman-2sxgb?file=/src/App.js

**Comment by Yonatani** [comment]
Hey, 
This is still happening, if you use x-axis datetime the mouse click has an offest from the selection area

**Comment by dmtrmrtnv** [comment]
The issue also appears in the zoom selection as well. 
A workaround could be disabling a grid.
Then the selection tool works as expected, without spacing to the right.

```
// Options
grid: {
        show: false,
}
```
