### ISSUE TITLE
Is it possible to make the download option menu item tab-able/keyboard navigation for assistive technology?

### ISSUE THREAD

**Issue by LifeSource** [apexcharts/apexcharts.js#2002]
**Is your feature request related to a problem? Please describe.**	
When the download menu opens up for the different format, **SVG**, **PNG** and **CSV**, currently the users cannot get into those menu item **_via the keyboard_** to download the items. 

This will be very useful/help for people using assistive technologies such as screen readers and other devices from an accessibility point of view.

**Describe the solution you'd like**	
Ideally these item would be keyboard focus-able using the `tab` key and also be able to download the items using the **enter** key on item selected.

Another way is to allow the custom DOM and event handlers to be added from a programming point of view, that way devs can override the default behaviour.

**Additional context**
Currently we're using Apexcharts in one of our project and this download menu has been flagged as an accessibility issue. By make it keyboard focus-able and download, this will make the charts more **accessible** for a wider audience.

**Comment by junedchhipa** [comment]
I will think about the custom DOM implementation where I will expose these methods to the public so you can call them directly.

**Comment by ceciCoding** [comment]
I have the same issue, I could make the download icon tabable by wrapping it in a button, but the dropdown menu is not reachable by keyboard.
