### ISSUE TITLE
Radial charts are not working in IE 11

### ISSUE THREAD

**Issue by SandeepKapalawai** [apexcharts/apexcharts.js#2004]
Not sure this is a bug or issue at my end.

I went through the documentation mentioned for IE 11 in order to work, so i have include the 3 polyfills  in my index,html as below 

As mentioned in the documentation and as per above @sarathcs comments, i have include those polyfills in my index.html file as below :

`<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill"></script> <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"></script>S <title>React App</title>
`
and in my index.js file i have included below polyfills

```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```

But i still didnt see it is loading correctly in IE, is there anything i am missing or any thing to be corrected ?

Thank you

![image](https://user-images.githubusercontent.com/5252966/97406195-d77def00-191e-11eb-823e-11e83acf396b.png)

**Comment by junedchhipa** [comment]
Are there any errors in the developer tools?

**Comment by SandeepKapalawai** [comment]
Hi @junedchhipa  Thank you for the prompt response

yes i am getting promise error as below in IE
Unhandled promise rejection TypeError: Unable to get property 'add' of undefined or null reference

**Comment by SandeepKapalawai** [comment]
Hi @junedchhipa will it be resolved in next release?

**Comment by junedchhipa** [comment]
@SandeepKapalawai Hi Sandeep, I don't have IE11 right now to debug the issue.
Hence, I don't have an ETA for this fix.

**Comment by PatrickStephansen** [comment]
I've run into this issue too. It doesn't seem to be specific to a particular kind of chart. The issue is that IE doesn't support the classList property on SVG elements. I was able to fix it for my project by installing and importing the [svg-classlist-polyfill](https://www.npmjs.com/package/svg-classlist-polyfill) package.

**Comment by junedchhipa** [comment]
IE11 support has been ended
