### ISSUE TITLE
Can't build angular multiple series - group rows timeline chart example

### ISSUE THREAD

**Issue by ErikSimonsen** [apexcharts/apexcharts.js#2005]
Hi, i have a problem building the [example](https://codesandbox.io/s/apx-rangebar-timeline-multiple-series-grouped-rows-u4drh?from-embed=&file=/src/app/app.component.ts) from the homepage with `ng build`.

As already seen in the sandbox the rangeBarGroupRows property can't be found (app.component.ts line 223), altough all package-versions are up to date.
It seems the property was not added to ng-apexcharts (as can be seen when you go to the declaration of the ApexPlotOptions class) just yet? The only way of successfully solving this issue is manually adding the property to the apex-types.d.ts in the node module folder for ng-apexcharts.

Would be happy about any help regarding this.

Best regards

**Comment by junedchhipa** [comment]
Fixed and released ng-apexcharts@1.5.5
