### ISSUE TITLE
Tooltips stop working on line graph when tooltip or y axis labels are formatted

### ISSUE THREAD

**Issue by skyshak** [apexcharts/apexcharts.js#2006]
# Bug report
When having a multiple line graph and formatting either the tooltip or y axis labels to include commas in the number using toString(). If user deselects a series from the legend, the hover tooltip will no longer work

## Codepen
https://codesandbox.io/s/vue-basic-example-forked-jywi9

## Explanation
- What is the behavior you expect?
    When deselecting a series, the tooltip should still display when hovering over the series data still selected
- What is happening instead?
    The tooltip hover does not display at all and gives an error in the console
- What error message are you getting?
   Uncaught TypeError: Cannot read property 'toString' of undefined
     at Object.formatter [as yLbFormatter]

**Comment by jxmot** [comment]
I had the exact same problem. It isn't a bug but perhaps the documentation could be clearer.

In the formatter function you need to check the `val` argument. When a series is deselected the internal code still iterates through that series and calls the formatter but `val` is undefined. The result is an error and nothing is rendered. 

This might fix the problem for you:
```
formatter: function (val) {
    if (typeof val !== 'undefined') {
        return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    } else return null;
}
```

**Comment by skyshak** [comment]
Just tried this out and it has fixed my problem!

Thanks a bunch, very much appreciated 👍  I will close this as you have mentioned it is not a bug.

**Comment by skyshak** [comment]
@jxmot Hi there, I recently updated some of my graphs and have come across a similar issue and was wondering if you had experienced it before. 

The situation now is that I have a data series which may be null at some points, this results in a similar issue where the tooltip will no long show when there is a formatter.

**Comment by jxmot** [comment]
@skyshak  I believe that the formatter must return something. So if your series contain the value `null` you will probably need to test for it and have the formatter function return something that isn't `null` or `undefined`.
