### ISSUE TITLE
Fixed tooltip dont work on pie charts

### ISSUE THREAD

**Issue by mamiaro** [apexcharts/apexcharts.js#2007]
# Bug report
Fixed tooltip dont work on pie chart

## Codepen
https://codepen.io/mamiaro/pen/ExyQNrg

## Explanation

- What is the behavior you expect?
I want fix the tooltip on pie chart

- What is happening instead?
the tooltip always follow de cursor

**Comment by junedchhipa** [comment]
Sorry, the fixed tooltip is not available in radial/pie charts
