### ISSUE TITLE
Having troubles with data offset x-axis axisBorder

### ISSUE THREAD

**Issue by nastykeller** [apexcharts/apexcharts.js#2009]
I'm trying to stylize my chart like this - need to implement data offset on x-axis, but no luck :(

![image](https://user-images.githubusercontent.com/20418695/97548846-17a9a400-19e9-11eb-8a3c-e6bc0fb9fafc.png)

Also try to add 
```
xaxis: {
 axisBorder: {
    offsetX: -200
  }
}
```
but it's working only for left side like this, i'm need both sides with offset

![image](https://user-images.githubusercontent.com/20418695/97549837-53913900-19ea-11eb-8472-28df08fad3ea.png)

any ideas? thnx
awesome library, btw😉

**Comment by junedchhipa** [comment]
```javascript
axisBorder: {
    offsetX: -200,
    width: '150%'
}
```

**Comment by nastykeller** [comment]
@junedchhipa yaay, it's working:) but how i can handle annotation line width?

```
annotations: {
   yaxis: [
     {
       offsetX: -80,
       width: '110%',
     }
   ]
}
```

![image](https://user-images.githubusercontent.com/20418695/97667811-269c5f00-1a9a-11eb-9cb7-03234e1a0e22.png)

**Comment by junedchhipa** [comment]
Sorry, the width property is not available for y-axis annotation.
I will add it soon.

**Comment by nastykeller** [comment]
got it. thanks for quick response:)

**Comment by pradnya2196** [comment]
There is no property annotation line width for x-axis. I'm trying to handle the width for x-axis. Can you please add it for x-axis as well? @junedchhipa 
![image](https://user-images.githubusercontent.com/35449921/147949610-a07c6b71-072b-46c6-84b8-ea689956cc99.png)

**Comment by Sharvinqw** [comment]
> ```js
> axisBorder: {
>     offsetX: -200,
>     width: '150%'
> }
> ```

can you give me more details on where exactly to put the code?
