### ISSUE TITLE
Change color of yaxis labels at horizontal bar chart don't work

### ISSUE THREAD

**Issue by punkt2** [apexcharts/apexcharts.js#201]
The setting for yaxis label color is not applied for horizontal bar chart (vertical bar chart works) 

Here is the codepen. Yaxis label should be green, but they are not.
https://codepen.io/punkt2/pen/ZmJVdR

**Comment by punkt2** [comment]
As far i understand your change, it fixes the color for the title not the labels, right?
I checked our master and the color is still not applying for yaxis labels.

**Comment by junedchhipa** [comment]
Hi @punkt2 
Sorry for not updating this thread, but the change isn't pushed to npm. When I will create the new build 2.2.3 - this will be working for labels and titles both
https://github.com/apexcharts/apexcharts.js/commit/40cd62fcc196f9568e82c6dcf50a7054433a2537#diff-68a9703f7bce197c9e7ed170e3704aed shows the changes in `src/modules/axes/XAxis.js` - maybe you got confused as Horizontal Bar Chart's Y-axis is drawn in Xaxis file (as technically it is just an inversed X-Axis) :)

**Comment by punkt2** [comment]
True, i didn't have the latest changes. Anyway, thanks and I will wait for the next release.

**Comment by lkovesdi** [comment]
Hi this isn't working on Y axis 

but it **does** work on X axis

working with "apexcharts": "^3.15.2",
React

**Comment by metalsadman** [comment]
still can't change Y axis label color, using version ^3.15.6, anything on this? i need it for when changing theme from light to dark.

**Comment by junedchhipa** [comment]
```javascript
yaxis: {
  labels: {
    style: {
      colors: '#111'
    }
  }
}
```

This should work even in a horizontal bar chart.

**Comment by lkovesdi** [comment]
@metalsadman 

We recently updated our web-pack. Not entirely sure what change there was but now the Y axis is working for us.

**Comment by forcmti** [comment]
the color of yaxis title not working with apepx charts.pls help

**Comment by shinygucci** [comment]
Is there a way to change the color depending on a condition?
i.e. if the value is higher than 50 then color red if not then color black

**Comment by K-zimm** [comment]
> ```js
> yaxis: {
>   labels: {
>     style: {
>       colors: '#111'
>     }
>   }
> }
> ```
> 
> This should work even in a horizontal bar chart.

This worked for me, thank you!

**Comment by mh4ck** [comment]
> > ```js
> > yaxis: {
> >   labels: {
> >     style: {
> >       colors: '#111'
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should work even in a horizontal bar chart.
> 
> This worked for me, thank you!

Didn's work for me, is there any workaround? Can i fix this by adding some css or so?

**Comment by Deepu1307** [comment]
For changing the x-axis label - font-size, font-weight, font-family, color etc. I used this.

.apexcharts-yaxis-label tspan, .apexcharts-xaxis-label tspan {
    fill: #0F1012;
    font-size: 16px;    
    font-weight: 500;
}
