### ISSUE TITLE
point annotations where xaxis labels are an array

### ISSUE THREAD

**Issue by elliotashton** [apexcharts/apexcharts.js#2012]
# Bug report
I'm 100% sure if this is a bug (or a lack of capability on my part) but I am unable to add an annotation to a stack bar chart where the xaxis categories are an array for each category (used to create line feeds for long labels). I've confirmed that I am able to do this with a single string value for each category.

this is what I get for a string

![image](https://user-images.githubusercontent.com/33450214/97798460-6a4dbf00-1c7a-11eb-9bb3-502eba768890.png)

this is what I get for an array

![image](https://user-images.githubusercontent.com/33450214/97798577-6f5f3e00-1c7b-11eb-8135-fed2bcc89e67.png)

Note that the annotation no longer appears. It seems that the x value needs to be a string to match. I've tried to pass an array matching the category array but not achieved a match. This is the array that describes the xaxis categories:
![image](https://user-images.githubusercontent.com/33450214/97798697-8a7e7d80-1c7c-11eb-84c6-3059aeeab8b0.png)

## Explanation

- I expect that the point annotation x value can match for an array 
- The annotation is not finding an xaxis category match where the xaxis category is an array 
- no error message

**Comment by junedchhipa** [comment]
I guess, this is a bug but I need a Codepen to confirm. Can you please create a Codepen example?

**Comment by elliotashton** [comment]
I've created a pen [here](https://codepen.io/testmetestme/pen/vYKrBGY). Note that the xaxis hasn't rotated even though the attribute is set.
