### ISSUE TITLE
bug in document images

### ISSUE THREAD

**Issue by patrickmonteiro** [apexcharts/apexcharts.js#2013]
# Bug report

The documentation is not the image of the graphics.

## Explanation

- What is the behavior you expect?
graphics image
- What is happening instead?
blank cards with console error
- What error message are you getting?

Cannot read property 'querySelectorAll' of null
<img width="606" alt="Captura de Tela 2020-11-01 às 19 01 59" src="https://user-images.githubusercontent.com/13258255/97816536-ba298780-1c74-11eb-91ea-2849394b5974.png">

<img width="1006" alt="Captura de Tela 2020-11-01 às 18 59 21" src="https://user-images.githubusercontent.com/13258255/97816478-5c953b00-1c74-11eb-9a33-0982d604ee10.png">

**Comment by junedchhipa** [comment]
@patrickmonteiro Thanks a lot for the heads up!
Fixed it.
