### ISSUE TITLE
Random Charts Breaking

### ISSUE THREAD

**Issue by Chazza** [apexcharts/apexcharts.js#2016]
Hey,

I reported to you a bit ago but thought to make a new one, since 3.20.1 version a few charts randomly broke which has held me from being able to upgrade.

What did you change in this version that would break a few charts? They seem to be no different to other charts.

Link: https://codepen.io/ChazzaBoi/pen/XWKqyEX?editors=1111

**Comment by Chazza** [comment]
So, good news! In your new update you never disclosed that `responsive` config object had changed, that kicked out my charts.

**Comment by junedchhipa** [comment]
@Chazza `responsive` configs were never changed. Can you give more info on what is broken? Your CodePen looks fine to me.

**Comment by Chazza** [comment]
When I removed the responsive part my charts are now working.

**Comment by junedchhipa** [comment]
Can you please add back, and reproduce the error?
Would be helpful to know if there are any issues.

**Comment by Chazza** [comment]
> 
> 
> Can you please add back, and reproduce the error?
> Would be helpful to know if there are any issues.

Updated, see how suddenly it breaks, this only broke from v3.20.1+, never existed previously.

**Comment by junedchhipa** [comment]
Thanks.
The issue was not due to responsive configs. But, you were calling `updateSeries` and `updateOptions` immediately after `render`.

You should wait for the `render` and then if you want to update both `series` and `options`, you should do it in 1 call
`updateOptions`

I have illustrated it in the Codepen - https://codepen.io/apexcharts/pen/xxOjBed

I will also update the docs to mention this.

**Comment by Chazza** [comment]
> Thanks.
> 
> The issue was not due to responsive configs. But, you were calling `updateSeries` and `updateOptions` immediately after `render`.
> 
> 
> 
> You should wait for the `render` and then if you want to update both `series` and `options`, you should do it in 1 call
> 
> `updateOptions`
> 
> 
> 
> I have illustrated it in the Codepen - https://codepen.io/apexcharts/pen/xxOjBed
> 
> 
> 
> I will also update the docs to mention this.

In my dashboard I have it like this and it worked as soon as I removed the responsive config object.

I think it's that, not that part

**Comment by junedchhipa** [comment]
@Chazza I understood your point. Removing the responsive part worked.
But the reason why it worked previously and not now with your current code was that `updateSeries` and `updateOptions` were called at the same time. I have updated the docs stating it's not recommended to do that otherwise it breaks other things.

**Comment by Chazza** [comment]
> @Chazza I understood your point. Removing the responsive part worked.
> 
> But the reason why it worked previously and not now with your current code was that `updateSeries` and `updateOptions` were called at the same time. I have updated the docs stating it's not recommended to do that otherwise it breaks other things.

Oh right I see, thank you - how can I get round this? Just delaying this?

**Comment by junedchhipa** [comment]
Yes, `updateOptions` and `updateSeries` both try to update the chart at the same time, hence issues occured.

You can do it as I illustrated in the Codepen

```javascript

chart.render().then(() => {
  chart.updateOptions({
    series: [
      {
        name: "Total Paid",
        data: [1, 2, 3, 4, 5, 6]
      },
      {
        name: "Total Incurred",
        data: [1, 2, 3, 4, 5, 6]
      },
      {
        name: "Percent Difference",
        data: [1, 2, 3, 4, 5, 6]
      }
    ],
    xaxis: {
      type: "text",
      categories: ["a", "b", "c", "d", "e", "f"],
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    }
  });
});

```
