### ISSUE TITLE
Reduced vertical margin for small graphs

### ISSUE THREAD

**Issue by bobdamit** [apexcharts/apexcharts.js#2017]
I am trying to use apex charts (bar and line) as a very tiny "thumbnail" graph which can be viewed larger in another view.  I've set my height to 60 and the parentHeightOffset to 0.  That sizes the overall control to what I want, however the drawing size of the lines and bars is only 9px high.  It seems that it is leaving room above the plot for the toolbar even though I have that disabled. There is also a lot of padding under the x axis and I am wondering if there is any way to control or reduce that.

My chart options are as follows:
```
this.lineChartOptions = {
	series: [
		...
	],
	chart: {
		height: 60,
		type: "line",
		zoom: {enabled: false},
		toolbar: {show : false},
		parentHeightOffset : 0

	},
	legend : {show:false},
	dataLabels: {enabled: false},
	stroke: {
		curve: "straight",
		width:1
	},
	grid: {show:false,},
	xaxis: {
		categories: [""],
		tooltip: {enabled:false},
		labels: { show: false },
		axisBorder : { show:true},
		axisTicks : { show :false }
	},
	yaxis: [{show:false}]
};
this.barChartOptions = {
	series: [...
	],
	chart: {
		type: "bar",
		height: 60,
		toolbar: {show : false},
		parentHeightOffset : 0
	},
	legend : {show:false},
	grid: {show:false},
	plotOptions: {
		bar: {horizontal: false}
	},
	dataLabels: {enabled: false},
	xaxis: {
		categories: [
			"Foo",
			"Bar",
			"Quality"
		],
		tooltip: {enabled:false},
		labels: { show: false },
		axisBorder : { show:true},
		axisTicks : { show :false }
	},
	yaxis: [{show:false,min:0,max:1000},{show:false,min:0,max:1},{show:false,min:0,max:1}]
};
```

Here are some images showing illustrating what I am seeing.   Any advice welcome and appreciated
![2020-11-02_10-30-25](https://user-images.githubusercontent.com/7861551/97886580-c35b3880-1cf6-11eb-8a28-345086d06f5a.png)
![2020-11-02_10-17-30](https://user-images.githubusercontent.com/7861551/97886024-1a144280-1cf6-11eb-92f2-0ea0ce04f036.png)
![2020-11-02_10-22-37](https://user-images.githubusercontent.com/7861551/97886025-1aacd900-1cf6-11eb-9f6e-7cc7e6f7fe7c.png)

**Comment by junedchhipa** [comment]
Try
```javascript
chart: {
  sparkline: {
    enabled: true
  }
}

```

**Comment by bobdamit** [comment]
Brilliant!  Thank you.  Exactly what I needed!
