### ISSUE TITLE
Trying to destroy chart second time gives TypeError: this.zoomPanSelection is null

### ISSUE THREAD

**Issue by mestaritonttu** [apexcharts/apexcharts.js#202]
## Codepen

https://codepen.io/anon/pen/aQLMzz

## Explanation

Click twice the button that says "Click to recreate chart". On the second click you will get in the console TypeError: this.zoomPanSelection is null.

It is hitting the this.zoomPanSelection.destroy() function in this apexcharts.js code block:

```
key: 'clear',
value: function clear() {
    this.zoomPanSelection.destroy();
    if (this.toolbar) {
    this.toolbar.destroy();
    }
```

**Comment by junedchhipa** [comment]
@mestaritonttu Thanks for reporting, I confirm this bug.
Will be fixed in the next release.
