### ISSUE TITLE
Issue with color when hovering on the radial bar chart type in the Safari. 

### ISSUE THREAD

**Issue by sparklingW** [apexcharts/apexcharts.js#2021]
Hello, I have an issue with radial bar chart when I hover on it, it makes chart more lighter then in the chrome or mozila. I didn't modify anything. Also I tried to use property { states: { hover: { filter } } } and it didn't help me. Why this issue might be occurred?

**Comment by junedchhipa** [comment]
Can you create a Codepen, please?

**Comment by sparklingW** [comment]
Yes, just a moment.

**Comment by junedchhipa** [comment]
![Screenshot 2020-11-04 at 6 34 00 PM](https://user-images.githubusercontent.com/17950663/98115134-513c4c80-1ecc-11eb-911b-3d1a37c47770.png)

In Safari, I tried hovering over the red bar in the above screenshot and it looks fine

**Comment by sparklingW** [comment]
<img width="362" alt="Знімок екрана 2020-11-04 о 3 05 19 пп" src="https://user-images.githubusercontent.com/36714951/98115231-2abbe880-1eaf-11eb-822a-94a6a67eb617.png">
this is safari

**Comment by sparklingW** [comment]
<img width="359" alt="Знімок екрана 2020-11-04 о 3 05 48 пп" src="https://user-images.githubusercontent.com/36714951/98115267-3a3b3180-1eaf-11eb-834e-923600a78dd1.png">
this is chrome

**Comment by sparklingW** [comment]
<img width="659" alt="Знімок екрана 2020-11-04 о 3 07 25 пп" src="https://user-images.githubusercontent.com/36714951/98115411-75d5fb80-1eaf-11eb-9e83-6c79d0274d7d.png">
funny fact I took this example from apexcharts examples, and it is safari. 

And this is chrome. 
<img width="650" alt="Знімок екрана 2020-11-04 о 3 08 15 пп" src="https://user-images.githubusercontent.com/36714951/98115476-92723380-1eaf-11eb-9f70-9c1f765c5bf9.png">

Maybe the problem is occurring because of the browser.

**Comment by sparklingW** [comment]
I forgot to mention that this is react-apexchart

**Comment by sparklingW** [comment]
@junedchhipa Hello, did you find out what is the problem?
