### ISSUE TITLE
 Download PNG button does not work when yaxis.labels.formatter is set to "currency"

### ISSUE THREAD

**Issue by guuicorrea** [apexcharts/apexcharts.js#2022]
**Codepen with issue**
https://codepen.io/guuicorrea/pen/abZjZRv

**Codepen without issue**
https://codepen.io/guuicorrea/pen/PozBzxR
**Explanation**
When I apply the following custom formatting to yaxis.labels, the "Download PNG"button stop working and some weird error appears on SVG image exported.
` formatter: function (value) {return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });`

if I change the custom formatting to `formatter: function (value) {return value.toLocaleString("pt-BR", {minimumFractionDigits: 2 });},` all these functions works again.

There is some way to define custom currency formatting to yaxis without generating this error?
 
Thanks in advance!

**Comment by Nickinthebox** [comment]
Might be linked to https://github.com/apexcharts/apexcharts.js/issues/1671
