### ISSUE TITLE
Line chart color not changing when using updateOptions()

### ISSUE THREAD

**Issue by ntohq** [apexcharts/apexcharts.js#2024]
# Bug report

## Codepen

Modify [this codepen](https://codepen.io/apexcharts/pen/bxzgZJ) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem. Issues/bug reports without reproducible example will be given least priority, so make sure you include one.

If you are using vue-apexcharts, and want to create a demo in Vue environment, use [CodeSandbox Vue template](https://codesandbox.io/s/pwwz8009n0)
If you are using react-apexcharts, and want to create a demo in React environment, use [CodeSandbox React template](https://codesandbox.io/s/6yoqonyo7r)

## Explanation

- What is the behavior you expect?
- What is happening instead?
- What error message are you getting?

**Comment by junedchhipa** [comment]
Please provide additional information.

**Comment by ntohq** [comment]
I have a chart that has the ability to switch from a candlestick chart to a line chart and visversa.
Candlestick chart:
![image](https://user-images.githubusercontent.com/11604664/98382047-4985c080-2010-11eb-979c-bd49ca89b174.png)
Line chart:
![image](https://user-images.githubusercontent.com/11604664/98382141-6f12ca00-2010-11eb-8349-3acec88536a8.png)
here is the block of code I use when I change from a candlestick chart to line chart:
![image](https://user-images.githubusercontent.com/11604664/98382280-9c5f7800-2010-11eb-8a1b-198a7f464171.png)

**Comment by junedchhipa** [comment]
You cannot update just the type of a series using `updateSeries` function. `updateSeries` is used to change the data of a chart.

You should just use the `updateOptions` function but still provide both the series data and type.

```js
updateOptions({
  colors: [...],
  series: [{
    type: 'line',
    data: newData
  }]
})
```
