### ISSUE TITLE
Column chart - Column is sometimes too big 

### ISSUE THREAD

**Issue by Khanh-Ngy** [apexcharts/apexcharts.js#2031]
I don't know why sometimes I got big column.
![image](https://user-images.githubusercontent.com/71876037/98538082-d2288900-22bc-11eb-95b8-5e16ac72e604.png)

And sometimes not :
![image](https://user-images.githubusercontent.com/71876037/98538106-dc4a8780-22bc-11eb-8d7e-b310fea00859.png)

Data is normal.
```
                plotOptions: {
                    bar: {
                        horizontal: false,
                        columnWidth: '35%',
                        barHeight: '70%',
                        endingShape: 'rounded'
                    },
                },
```
Please help me explain this. So many thanks.

**Comment by junedchhipa** [comment]
The column width in a linear chart is dependant on how many bars are actually present.
