### ISSUE TITLE
showDuplicate not working

### ISSUE THREAD

**Issue by ligiaandreica** [apexcharts/apexcharts.js#2032]
# Bug report
When `showDuplicates` is set to false, duplicate xAxys values are still displayed after upgrading from `3.19.3` to `3.20.1`.
Also reproducible with the latest version `3.22.2`.
Possibly a side effect of https://github.com/apexcharts/apexcharts.js/commit/40671eab076d814f8717c9060f1425b3bb201a0a.

## Codepen
https://codesandbox.io/s/react-basic-example-forked-5s0lh?file=/src/App.js
![image](https://user-images.githubusercontent.com/59609285/98578400-38a9a900-22b5-11eb-81b9-7e030cc8c364.png)

## Explanation

- What is the behavior you expect?
xAxys shouldn't duplicated label when showDuplicates is set to false.
- What is happening instead?
Multiple labels with the same value are shown
- What error message are you getting?
No error message

**Comment by aathirag** [comment]
I am also facing the same issue. 

**JSFiddle**

https://jsfiddle.net/athisandy/pbvedkty/24/
![image](https://user-images.githubusercontent.com/14194040/106847714-7c098d00-66d5-11eb-8b15-24e78185f006.png)

**Comment by haposan06** [comment]
Hello, any news regarding this issue? We also had this issue in our scatter chart

**Comment by aathirag** [comment]
check the answer which I tried https://stackoverflow.com/questions/66015355/in-heatmap-apexcharts-how-can-we-remove-duplicate-x-axis-labels

**Comment by ZahidChandio** [comment]
I couldn't allow duplicate labels for y-axis. In the image below y-axis has the days of week.

![image](https://github.com/user-attachments/assets/22b2c775-139a-4e7c-a0f6-fcbe6aa9e4d1)

I tried all the options, but couldn't resolve this.

![image](https://github.com/user-attachments/assets/8c33a618-e7aa-4cd1-9f7d-fd2b4b0fb7d0)
