### ISSUE TITLE
Setting custom width of labels

### ISSUE THREAD

**Issue by bubnenkoff** [apexcharts/apexcharts.js#2035]
I googled a lot, and read docs, only what I found mention that very long text can be splitted for lines by putting it in array. 

I need to display full label text or at last to extend current size that it's too small.

Example: https://jsfiddle.net/swLpynua/

I tried different approaches. Like:
```
labels: {
    style: {
       fontSize: '12px',
           },
       rotate: -5,
      minWidth: 430,
       minWidth: 610
     },
```
but it does not do any affect.

So it's seems that currently it's not possible. 

If anybody know how to fix it -- i would be very thankful for solution!

**Comment by junedchhipa** [comment]
```js
yaxis: {
  labels: {
     maxWidth: 250
  }
}
```
