### ISSUE TITLE
Feature request: box plots

### ISSUE THREAD

**Issue by newmanne** [apexcharts/apexcharts.js#204]
Takes in five arguments (max, upper quartile, median, lower quartile, min). Similar in many ways to candlestick charts, but with a median and does not assume a datetime axis. One example is [this](https://www.highcharts.com/demo/box-plot). I would want to plot outliers as a scatter plot on the same graph, so ideally that would work too.

**Comment by DOOMitru** [comment]
@junedchhipa Any progress on this feature?

**Comment by junedchhipa** [comment]
@DOOMitru Not yet. You can expect in a couple of weeks.

**Comment by ceds** [comment]
Waiting for this as well...

**Comment by iminguez** [comment]
+1

**Comment by gilbert-jolly** [comment]
+1

**Comment by markhm** [comment]
+1

**Comment by Darkproduct** [comment]
+1

**Comment by trebor74hr** [comment]
+1

**Comment by axtg** [comment]
+1

**Comment by mgpwilson** [comment]
+1

**Comment by rouuuge** [comment]
> Yes, as candlestick is already implemented, it won't be a hassle to generate box-plots with the same logic.
> Thanks for the suggestion, this goes in my roadmap.

Any progress on this feature?

**Comment by junedchhipa** [comment]
Yes, there is some progress on this feature.
The next major version v.3.25.0 will have the box plots.

**Comment by junedchhipa** [comment]
Released v3.25.0
https://apexcharts.com/javascript-chart-demos/box-whisker-charts/
