### ISSUE TITLE
Add padding in sparkline

### ISSUE THREAD

**Issue by altyx** [apexcharts/apexcharts.js#2041]
**Is your feature request related to a problem? Please describe.**	
When we hover a sparkline graph, the top data point is not completly display (see the screen below).
I use apexcharts in chrome and IE 11

**Describe the solution you'd like**	
It is possible to add some padding that the point is correctly diplayed 

![Sans titre](https://user-images.githubusercontent.com/5872427/98961087-756bdf00-2505-11eb-8f65-4bbf35e1fd95.png)

**Comment by dgknca** [comment]
You can try this

```js
yaxis: {
  min: (min) => {
       return min - min / 100; 
  },
  max: (max) => {
       return max + max / 100;
  },
}
```

**Comment by Flowman** [comment]
Yes we need some padding as all low and high values get cut.

![image](https://user-images.githubusercontent.com/212680/123538128-cdd6b080-d765-11eb-9d41-ea0364a71139.png)
