### ISSUE TITLE
Customizable export

### ISSUE THREAD

**Issue by marianskrisa** [apexcharts/apexcharts.js#2042]
Set the name of the downloaded CSV, PNG, SVG file. 
Choose which option is displayed in the export menu.
(e.g. svg or png only)

**Comment by jxmot** [comment]
@marianskrisa I'm not sure if this will help you or not. But I've been working on the same things for one of my projects. I've got it working but it requires a _modified_ version of v3.22.1.

I've created a CodePen that demonstrates the changes - https://codepen.io/jxmot/pen/jOrJpdb

**Comment by marianskrisa** [comment]
@jxmot Thank you, works perfect, exactly what I needed.

**Comment by junedchhipa** [comment]
@jxmot Good suggestion, I have implemented the same.
Next time, you can create a PR for such things and I will happily review it.
