### ISSUE TITLE
There is no example with range or scroll bar

### ISSUE THREAD

**Issue by darshanmarathe** [apexcharts/apexcharts.js#2046]
In the ApexChart Website we see a video 
https://apexcharts.com/features/

We see 
https://apexcharts.com/wp-content/themes/apexcharts/videos/interactive.mp4

Video on features page
But where is the example for this 

Want to implement similar functionality

Also guide me how to contribute example of ApexCharts with WebComponents as i am trying to build the same

**Comment by junedchhipa** [comment]
@darshanmarathe The scroller was removed as it has some memory leaks.
I might revisit the scroller code and add it back in the future.
