### ISSUE TITLE
How to apply padding to xaxis?

### ISSUE THREAD

**Issue by dgknca** [apexcharts/apexcharts.js#2047]
![Capture](https://user-images.githubusercontent.com/38227845/99244042-976da600-2812-11eb-8b8e-f55892a283d0.PNG)

I want to apply padding left & right to xaxis but I didn't find any option for that. Is there any way?

**Comment by junedchhipa** [comment]
Padding only to the x-axis labels is not possible because the positions are calculated based on the data-points.
You may try changing the padding of the whole chart inner area
```js
grid: {
  padding: {
    left: 30,
    right: 20
  }
}
```
