### ISSUE TITLE
Website documentation, Options: tooltip content not visible

### ISSUE THREAD

**Issue by jxmot** [apexcharts/apexcharts.js#2049]
# Bug report

The documentation page for tooltip documentation is not visible. The content is there but not visible, the links work enough to move the page. It was working a few days ago.

https://apexcharts.com/docs/options/tooltip/

I've tried it in Chrome, Firefox, and Edge. All have the same issue.

**Comment by davehowson** [comment]
Can confirm. This issue is still there.

![image](https://user-images.githubusercontent.com/26568721/99348736-45835980-28c0-11eb-88ac-05593728b4af.png)

**Comment by davehowson** [comment]
If anyone needs a quick workaround to view the documentation before it is fixed, inspect the page via the developer tools in the browser, copy the `<aside>` element and paste it in an empty HTML file to view it. Or use an online HTML viewer like [this](https://codebeautify.org/htmlviewer/)

![image](https://user-images.githubusercontent.com/26568721/99349421-fa6a4600-28c1-11eb-9055-b50ce1e879d9.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by jxmot** [comment]
Thank you!
