### ISSUE TITLE
Get datas from a database

### ISSUE THREAD

**Issue by bee-interactive** [apexcharts/apexcharts.js#205]
Hi!

I'm struggling to get datas injected dynamically into my basic bar chart.. I'm always facing this error: Uncaught (in promise) TypeError: Cannot read property 'x' of undefined the trying to fill the series.

Is there any example on how format the incoming datas from an ajax request? I'm trying to fetch some json response but nothing comes into my graph.

Here are my datas from the json response:

![datas](https://user-images.githubusercontent.com/1703353/48789599-b7366600-eced-11e8-9d3e-485d09423534.png)

And here is my code that export the data to my json response:

![code](https://user-images.githubusercontent.com/1703353/48789745-07152d00-ecee-11e8-991b-df28ddf71f58.png)

I'm using Laravel and VueJS.

Thanks in advance for your help!

**Comment by junedchhipa** [comment]
Hi @bee-interactive 
Can you put your data into a text-format for me to copy-paste easily and re-produce the issue on my side?
I would like to see the final `datas` you generate to see if it in the correct format.

**Comment by bee-interactive** [comment]
Hi @junedchhipa !

Sure!

Here's the code:

My VueJS Component:

```
export default {
    components: {
        'apexcharts': VueApexCharts,
    },
    data () {
        return {
            dates: [],
            count: [],
            dateRangeOptions: {
                startDate: format(subDays(new Date(), 7), 'YYYY-MM-DD'),
                endDate: format(new Date(), 'YYYY-MM-DD'),
                format: 'MM/DD/YYYY',
            },
            series: [{
                name: 'sales',
                data: [this.count]
            }]
        }
    },
    methods: {
        fetchData() {
            return axios.post(`/get-sales/${this.range[0]}/${this.range[1]}`).then((response) => {
                this.dates = response.data.dates.dates
                this.count = response.data.dates.count
            })
        }
    }
}
```

My controller:

```
public function getSales(Request $request, $start = null, $end = null)
{
        $datas = [];

        $dates = new \DatePeriod(
            new \DateTime($start),
            new \DateInterval('P1D'),
            new \DateTime($end)
        );

        foreach($dates as $date) {
            $datas['days'][] = [
                'day' => $date->format("Y-m-d"),
            ];

            $datas['count'][] = [
                // Here I just fetch all my orders that was made on that given day and get the count of the rows found
                'count' => $this->getSalesByDay($date->format("d")),
            ];
        }

        $datas['dates'] = [
            'dates' => collect(array_values($datas['days']))->implode('day', ', '),
            'count' => collect(array_values($datas['count']))->implode('count', ', '),
        ];

        return json_encode($datas);
}
```

Hope this will help!

**Comment by junedchhipa** [comment]
I think, it's more of a Vue issue.
I suggest, you move your `series` property from `data` to `computed` as it depends on your `count` prop.

```javascript
computed: {
  series: function() {
      return [{
           name: 'sales',
           data: [this.count]
       }]
  }
}
```

If you can create a working demo with fake data on [codesandbox vue-template](https://codesandbox.io/s/pwwz8009n0), it would be helpful.

I suspect, that the series prop isn't getting the new data, so the re-render isn't happening. Try updating the `series` prop directly by 

```javascript
this.series = [{
  name: 'sales',
  data: response.data.dates.count
}]
```
and see if re-rendering happens

**Comment by bee-interactive** [comment]
@junedchhipa It worked like a charm with the computed data! Thank you so much!

**Comment by pkrabhi** [comment]
can anyone help me with apexchat?
i want to get data from API and push it into bar chart.. on a stateless component.
i need example

thanks
