### ISSUE TITLE
Tooltip for a line chart

### ISSUE THREAD

**Issue by edgar-koster** [apexcharts/apexcharts.js#2052]
I've some line and bar charts on a dashboard, as well as a pie chart. I would like the tooltip for the line/bar charts to be the same as for the pie chart.

Donut:
![image](https://user-images.githubusercontent.com/24190040/99386443-c1869d00-28d2-11eb-91f9-eb9951201de8.png)

Bar:
![image](https://user-images.githubusercontent.com/24190040/99386466-c9ded800-28d2-11eb-9c14-19f9691aa5d3.png)

So in this example, the second tooltip would be blue with 'Verwerker: 5'

Is it possible to do this? I would say that if there is only 1 series, you can achieve this. I found somewhere in tooltip.js where the tooltip is generated, but don't want to start changing things if it might already be possible.

**Comment by weech3r** [comment]
You can write your own custom tooltip and then use it for both pie and bar charts. https://apexcharts.com/docs/options/tooltip/

**Comment by edgar-koster** [comment]
Thanks solved this.
