### ISSUE TITLE
set Marker stroke color as the color of the line itself

### ISSUE THREAD

**Issue by lior-fortifieddata** [apexcharts/apexcharts.js#2054]
more kind of a question, which I haven't found a solution:

Is there a way to configure the stroke color to be on the same color of the line? (instead of red)

![image](https://user-images.githubusercontent.com/59799643/99644116-333b2400-2a56-11eb-920c-4ab743abe958.png)

```
markers: {
      size: 5,
      strokeOpacity: 1,
      fillOpacity: 1,
      showNullDataPoints: false,
      colors: "#ffffff",
      strokeColors: "red",
    },
```

**Comment by junedchhipa** [comment]
You have an answer to your question itself in your code. Change the `strokeColors` property to blue

```js
markers: {
  size: 5,
  colors: '#fff',
  strokeColors: '#008FFB',
  strokeWidth: 3
}
```

**Comment by lior-fortifieddata** [comment]
What if i have 5 line series(which receives colors automatically from the library)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by junedchhipa** [comment]
Here are the default 5 colors which are set automatically

```js
strokeColors: ['#008FFB', '#00E396', '#FEB019', '#FF4560', '#775DD0']
```
