### ISSUE TITLE
Pricing/License - fusioncharts.com

### ISSUE THREAD

**Issue by ivanjaros** [apexcharts/apexcharts.js#2055]
Apexcharts say they are open source and list MIT license but when I want the Vue integration it redirects me to fusioncharts-based vue component which requires the fusioncharts core library which costs at least 500$ a year. So what's up with apex then? Is is free or not?

**Comment by junedchhipa** [comment]
ApexCharts is completely free while FusionCharts is our partner who has sponsored ApexCharts.
If you simply want Vue integration of ApexCharts, it's [here](https://github.com/apexcharts/vue-apexcharts).

**Comment by ivanjaros** [comment]
ok, thanks for clarifying. i was confused because on the official website, the vue links to the fusioncharts vue component which lead me onto weird path :D
