### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by tol64** [apexcharts/apexcharts.js#2060]
An error is generated when drawing a Heatmap-type chart:
**Uncaught (in promise) TypeError: Cannot read property 'split' of undefined**

![image](https://user-images.githubusercontent.com/50295805/99915692-43812680-2d16-11eb-9524-74fb4de9616e.png)

![image](https://user-images.githubusercontent.com/50295805/99915733-7deac380-2d16-11eb-9771-d8583682f4da.png)

//---

This error is not always reproduced. Sometimes immediately after a page is loaded, and sometimes after a graphic update.

**Comment by yousselg** [comment]
Four years later, I find myself encountering the same issue. I've realized that when I use six colors, it's thrown, but reducing the colors resolves it. Posting this here in case someone else encounters a similar problem

**Comment by noobkisser** [comment]
Same issue encoutered. Completely random, after 6 months of use with no issue it suddenly pops up
