### ISSUE TITLE
series is not synced with xaxis

### ISSUE THREAD

**Issue by lior-fortifieddata** [apexcharts/apexcharts.js#2064]
# Bug report

**Example:** https://jsfiddle.net/h3awb5po/

 
 

## Explanation

- What is the behavior you expect?
the green series will by synced with xaxis, and that the tooltip will be shred to all serieses

- What is happening instead?
it's showing the 21 Nov on the 19 Nov

- What error message are you getting?

![image](https://user-images.githubusercontent.com/59799643/99952997-3a7d6d00-2d89-11eb-877a-e0587912c40d.png)

**Comment by lior-fortifieddata** [comment]
its seems to work fine, if you put the line series at the end of the series array

**Comment by lior-fortifieddata** [comment]
Do u guys know this issue? Is that a bug or configuration issue?

**Comment by junedchhipa** [comment]
It's a bug, will be fixed soon.
