### ISSUE TITLE
Tooltip lags on hover

### ISSUE THREAD

**Issue by neosheps** [apexcharts/apexcharts.js#2066]
# Bug report
My code is too large, so i will attach the video. If it necessary, i will transfer my code to the codepen.

[Video](https://imgur.com/a/nFTnKxj)

When hovering over an area, the tooltip jumps and freeze. I use area with multiply datasets so that each series is painted in a different color depending on the value

## Explanation

- What is the behavior you expect?
Smooth tooltip movement

- What is happening instead?
Tooltip jumps and freeze

- What error message are you getting?
None

**Comment by weech3r** [comment]
How many data point are you showing?

**Comment by neosheps** [comment]
@weech3r around 800 points, but I have a lot of datasets (as you can see on video, each color is new dataset)

**Comment by weech3r** [comment]
I haven't test that but I believe this large amount of datasets might be a problem. Did you try to test it with smaller amount of datasets?

**Comment by neosheps** [comment]
@weech3r yeap, everything works fine when I only have 1 dataset. But I need to change the fill color which depends on the data. didn't find any other option (and library) how this can be done

**Comment by weech3r** [comment]
So the reason why it lags is the number of displayed datasets. I would display it as a  bar chart from single dataset then. There is an option to calculate the color based of the value so maybe that could be the solution?
https://apexcharts.com/docs/options/colors/
![image](https://user-images.githubusercontent.com/6155180/101057454-53a5cb00-358c-11eb-8bd0-7d63174fd749.png)

**Comment by neosheps** [comment]
Unfortunately it doesn't work that way :( 
`>Colors for the chart’s series. When all colors of the array are used, it starts from the beginning
`
As I understand it, there is no way to apply different colors for one data set.
