### ISSUE TITLE
Can ApexCharts make a Funnel type chart?

### ISSUE THREAD

**Issue by Adrek** [apexcharts/apexcharts.js#2067]
Good day,
I am starting to use ApexCharts in my projects and congratulated them because it helps a lot.

A client has request us to display a chart specifically with the Funnel type. I have seen that the closest thing is to start from the horizontal bar graph, but I do not know how to make the bars are centered.

I give you an example of the funnel chart:
https://i.imgur.com/MQE1ebM.png

**Comment by AirMike** [comment]
Are there plans to add funnel chart type?
