### ISSUE TITLE
Candlestick + line chart - Mixed support

### ISSUE THREAD

**Issue by Alejandroem** [apexcharts/apexcharts.js#2068]
**Is your feature request related to a problem? Please describe.**	
I can't mix candlestick with other chart

**Describe the solution you'd like**	
Support  for candlestick mixed charts

**Additional context**	
This was mentioned in two issues but both got closed:

https://github.com/apexcharts/apexcharts.js/issues/883

**Comment by junedchhipa** [comment]
https://apexcharts.com/javascript-chart-demos/candlestick-charts/candlestick-with-line/

**Comment by Alejandroem** [comment]
Thank you I'm already using that, but I would love to have the feature in chart.js

**Comment by Nireus79** [comment]
That is essential. Some indicators need to be presented with the candles to make sense. Like EMA. I have the same problem.
