### ISSUE TITLE
Radial Bar Data lables

### ISSUE THREAD

**Issue by 01bswide** [apexcharts/apexcharts.js#2069]
For Radial Bar charts, is it possible to display the values inside the bars like so:

![image](https://user-images.githubusercontent.com/60698233/100259132-c638fa00-2f3f-11eb-98b8-c31f5f197d42.png)

Thank you!

**Comment by 01bswide** [comment]
Also if I wanted to use an array based on a prop inside the legend.formatter function, would that be possible? (I am using react-apexcharts)

**Comment by junedchhipa** [comment]
Sorry, this is not easily achievable.
