### ISSUE TITLE
Make Pie/Radia charts accept array of objects just like Series/Line charts

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/apexcharts.js#207]
**Is your feature request related to a problem? Please describe.**

In some of my projects I have the same data that I want to present differently in each widget. But for it to work both on Line charts and Radial charts I have to proccess the data in completely different shapes.

**Describe the solution you'd like**

Have Pie charts accept array of object data like:

```
const oldWaySeries = [0, 1]
const oldWayLabels = ["Name 1", "Name 2"]

const newWay1 = [
  {
    data: [0],
    name: "Name 1"
  }, 
  {
    data: [1],
    name: "Name 2"
  }, 
]
```

**Comment by junedchhipa** [comment]
Yes, I have already thought of this, but I am afraid this might be a breaking change for pie/radialbar charts. Will implement it for the next major update v3.0

**Comment by junedchhipa** [comment]
Yes, I agree that keeping the existing logic is essential for backward compatibility and also easier for simple use-cases.
