### ISSUE TITLE
Add series isolation on double click

### ISSUE THREAD

**Issue by kkmagician** [apexcharts/apexcharts.js#2073]
**Is your feature request related to a problem? Please describe.**	
Some BI solutions and charting libraries allow users to exclude series on legend single clicks, while also giving an option to leave only one selected series when its legend marker is double clicked. It is very handy when you have only many lines, but for a particular task only one is needed. Current solution only dims the other series on legend hover: while it looks nice, the chart may still look cluttered.

**Describe the solution you'd like**	
When you double click a series in the legend, all other series become turned off. After that, single clicks on other series restores them. Examples from another JS library: https://plotly.com/javascript/line-charts/

**Describe alternatives you've considered**	
It can be implemented using legend events (for double clicks with setTimeout or similar) + toggleSeries() method. It requires a lot of work on the front end for each chart for each app, I reckon performance may suffer.

**Comment by Mantej-Singh** [comment]
I would like this feature too, just like plotly
