### ISSUE TITLE
Select segment by index and apply 'active' state

### ISSUE THREAD

**Issue by b3023630** [apexcharts/apexcharts.js#2075]
Hi, I need to be able to select a segment in a pie/donut chart based on the index in the series. I have this [codepen ](https://codepen.io/jplatford/pen/QWEPzMy) where I use the dataPointSelection event to expand a matching accordion to the right of the chart. Basically, I need the reverse of this, where a user can click on the accordion title and have the corresponding segment in the chart be set to 'active'.

It would be great if there was a similar function to updateSeries() where the index could be passed in to set the segment matching that index as 'active'. The following function is in the JS of the codepen linked above, and it would be great if it was possible to set the active segment via this function somehow:
```
$(".accordion-title[data-chart-index]").on("click", function(){  
  $(".accordion-title").parent().removeClass("active");
  $(this).parent().addClass("active");
  var indx = $(this).attr("data-chart-index");  
})
```

Short of that, I need a way to be able to set the style of one of the segments as the same as 'active' when the corresponding accordion is clicked and then set that to the 'normal' state styling when a different segment is clicked or different accordion title is clicked.

**Comment by deantek** [comment]
check
