### ISSUE TITLE
multiple lines added to a stack bar chart also stack

### ISSUE THREAD

**Issue by elliotashton** [apexcharts/apexcharts.js#2076]
# Bug report
When adding multiple lines to an existing stack bar chart, the lines are also stacked rather than being expressed independently. That is, where line series 1 has a value of 10 and line series 2 has a value of 5 series 2 will be plotted at 15, not 5.

A secondary issue for lines is where there is not a value for a data point the line chart is unable to connect to the next data point requiring the addition of an intermediary data point (which is incorrect for the purpose of the chart). It would be preferable to be able to in/exclude connections where null values exist (refer dashed line in CodePen).

I suspect the ability to specify the type and subtype (i.e. stacked, continuous line, etc) at the series level is the answer.

## Codepen
https://codepen.io/testmetestme/pen/vYKrBGY

## Explanation

- What is the behavior you expect?
I'm trying to add non stacked lines to a stacked bar chart. A single line is fine, however the addition of a second line stacks rather than being drawn 

- What is happening instead?
The line series of the chart are also being stacked (note that the chart is globally designated as being stacked) and the line series cannot be made to have a continuous line where there is a null value.

- What error message are you getting?
No error message as it works as designed. This can be worked around by calculating the line series values to achieve the placement, however the tooltips will be incorrect.

**Comment by iameddz** [comment]
This issue is still present. #907
