### ISSUE TITLE
Logarithmic scale on radar charts

### ISSUE THREAD

**Issue by FloZdra** [apexcharts/apexcharts.js#2078]
# Bug report
When using the logarithmic scale on a radar chart, the scale is great, but points plotted on the chart follow a linear scale.

## Codepen
https://codepen.io/flozdra/pen/oNzgPyX

## Explanation

- What is the behavior you expect?
I'm trying to get the values on radar chart on a logarithmic scale

- What is happening instead?
Values don't follow the logarithmic scale

- What error message are you getting?
No error message is shown.

**Comment by RobsonMi** [comment]
This issue is still not fixed in 3.35.5. Values to not appear on chart. Probably because maxY and minY values are taken from globals which there is no documented way on how to set them?
