### ISSUE TITLE
Timeseries min and max is one hour off

### ISSUE THREAD

**Issue by EeeDotZee** [apexcharts/apexcharts.js#2079]
# Bug report

I'm having a little issue with the display values of a timeseries diagram. Basically when I'm starting with a value at 5:00:00 the first xaxis label displays 4:00:00 instead. When I'm setting a min and max it doesn't fix the issue.

In my codepen demonstration i want to display a full day from 00:00 to 24:00, but the xaxis starts with 23:00 which is misleading.

If this is not a bug and i'm just doing anything wrong sorry in advance!

## Codepen

https://codepen.io/eliazzz/pen/Exgjapz

## Explanation

- What is the behavior you expect?
The xAxis label to start with 00:00 and end with 24:00
- What is happening instead?
The xAxis label starts with 23:00
- What error message are you getting?
None

**Comment by eliasplatekdkt** [comment]
This is related to the timezone of your x values, all of your input dates should be UTC format. If you want to manage the timezone manually, your dates should all have the same timezone, and set the property `xaxis.labels.datetimeUTC` to `false`

**Comment by EeeDotZee** [comment]
@eliasplatekdkt 
Thank you! That fixed my issue. Instead of the timeformat above in my codepen i changed it to a UTC format. 
If anyone is curious, this is the format i needed: `"yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'"`
