### ISSUE TITLE
Cannot read property 'yRatio' of null in Treemap React JS

### ISSUE THREAD

**Issue by sam-munjewar** [apexcharts/apexcharts.js#2081]
# Bug report

## Here is my code

const testData = {          
            series: [
              {
                data: [
                  { x: 'New Delhi', y: 218 },
                  { x: 'Kolkata', y: 149 },
                  { x: 'Mumbai', y: 184 },
                  { x: 'Ahmedabad', y: 55 },
                  { x: 'Bangaluru', y: 84 },
                  { x: 'Pune', y: 31 },
                  { x: 'Chennai', y: 70 },
                  { x: 'Jaipur', y: 30 },
                  { x: 'Surat', y: 44 },
                  { x: 'Hyderabad', y: 68 },
                  { x: 'Lucknow', y: 28 },
                  { x: 'Indore', y: 19 },
                  { x: 'Kanpur', y: 29 }
                ]
              }
            ],
            options: {
              legend: { show: false },
              chart: { height: 350, type: 'treemap' },
              title: { text: 'Basic Treemap' }
            }, 
        }

![image](https://user-images.githubusercontent.com/42339316/100623658-747dde80-3348-11eb-8277-cfcc869f8db9.png)

**Comment by junedchhipa** [comment]
Your code renders fine on my side.
Are you using React/Vue?
Which version of ApexCharts are you using?

**Comment by sam-munjewar** [comment]
**React Js
Apexcharts Version : ^3.22.2**

**Comment by iesta** [comment]
FY, I add the same error with Vue and apexcharts@^3.10.1 but it works with 3.22.2

**Comment by aman-marstracktechnology** [comment]
how to solve this

**Comment by jomiklos** [comment]
sorry for necro-posting -> in case someone hits the same error, i think i identified problem/solution...
I hit same error today with latest `vue3-apexcharts`. 
It is caused by not setting or setting invalid value of `type` property of apex chart component. 
It seems that one can not set type of chart via `options` prop, but has to set the `type` property explicitly.
(same "issue" may apply to other options that are mapped to explicit props in vue3/react/other templating engine...)

**Comment by garrett-stewart-gs** [comment]
omg thank you jomiklos! I am using nextjs v18 and apexcharts v3.54.0 ( with react-apexcharts v1.4.1). I was setting type inside the options object (options.chart.type = "line") and running into error reading null (yRatio), displaying the empty charts skeleton, no data. However, if I didn't reload but saved any change to my code file, it would load the data fine. So weird!

Anyways I fixed this exactly how you said: use type="line" explicitly as a prop. So, I am Instantiating the chart with <Chart type={'line'} options={options} series={series} width={700} />.
