### ISSUE TITLE
Change marker color

### ISSUE THREAD

**Issue by JulieWilhelmine** [apexcharts/apexcharts.js#2083]
# Bug report

## Codepen
https://codesandbox.io/s/react-basic-example-forked-rygpg?file=/src/App.js

## Explanation

- What is the behavior you expect?
I want to change the color of the points/markers to red (#9A1F10).

- What is happening instead?
No matter what I try as far as colors, fill etc. goes I can only manage to change the outline stroke color - the inside/fillcolor stays default blue no matter what I try.

- What error message are you getting?
There is no error message.

**Comment by junedchhipa** [comment]
This configuration works

```js
this.state = {
  options: {
    chart: {
      id: "basic-bar"
    },
    xaxis: {
      categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
    },
    colors: ["#F9CA47"],
    markers: {
      size: [3, 0],
      strokeColors: "#9A1F10",
      strokeWidth: 2,
      strokeOpacity: 0.6,
      fillOpacity: 1,
      shape: "circle",
      radius: 2,
      hover: {
        size: undefined,
        sizeOffset: 3
      }
    }
  },
  series: [
    {
      name: "series-1",
      data: [30, 40, 45, 50, 49, 60, 70, 91]
    }
  ]
}
```

You had to define `colors` inside the options property as done above, not in the state.
