### ISSUE TITLE
yaxis logarithmic chart shifts down

### ISSUE THREAD

**Issue by mkantz84** [apexcharts/apexcharts.js#2084]
# Bug report

## Codepen

Here is [codesandbox](https://codesandbox.io/s/unruffled-babbage-5glg6?file=/src/components/GoodChart.jsx)

## Explanation

I'm using logarithmic `react-apexcharts` chart, and in some cases the chart is "shifting" a little bit down and messes the UI.
It seems like when the numbers in the yAxis are big, the issue does not occure.
Also, when `yaxis.logarithmic` is `false` the issue does not occure.

![image](https://user-images.githubusercontent.com/22270407/100837116-42b86500-3479-11eb-886d-0cacb1fdc3f5.png)

I also posted an [issue](https://github.com/apexcharts/react-apexcharts/issues/242) in `react-apexcharts` repo

`apexcharts` version: 3.22.2
`react-apexcharts` version: 1.3.7

**Comment by junedchhipa** [comment]
There's an update to the logarithmic code recently, so keep an eye on the next release (3.22.3)
Once a new version is published, report here if it fixes the issue.

**Comment by mkantz84** [comment]
> There's an update to the logarithmic code recently, so keep an eye on the next release (3.22.3)
> Once a new version is published, report here if it fixes the issue.

Sure thanks!

**Comment by junedchhipa** [comment]
Does upgrading to version 3.22.3 fixes the issue?

**Comment by mkantz84** [comment]
Seems like the main issue has been fixed.
BUT, what happened to the `yaxis.min`?
Does it stopped affecting `logarithmic` graph?

**Comment by junedchhipa** [comment]
Yes, yaxis.min in a log scale was causing issues, hence it was removed.
