### ISSUE TITLE
Timestamp 0 incorrectly parsed by x axis

### ISSUE THREAD

**Issue by guylan-dieu** [apexcharts/apexcharts.js#2088]
# Bug report

When the date "1970-01-01 00:00" (which is timestamp 0) is passed in x axis, the chart considers this date as "1999-12-31 23:00".

![image](https://user-images.githubusercontent.com/66561144/101162922-4394f680-3633-11eb-939b-6f380fc1f3d7.png)

## Codepen

https://codepen.io/guylan-dieu/pen/mdrVGKN

## Explanation

- What is the behavior you expect?
The column for the year 1970 must be correctly placed.

- What is happening instead?
The column for the year 1970 is placed the 1999-12-31 23:00.

- What error message are you getting?
No error message.

**Comment by eliasplatekdkt** [comment]
This is related to the timezone of your browser, all of your input dates should be UTC format. If you want to manage the timezone manually, your dates should all have the same timezone, and set the property `xaxis.labels.datetimeUTC` to `false`
