### ISSUE TITLE
Hiding xaxis labels hide grid lines

### ISSUE THREAD

**Issue by pvictor** [apexcharts/apexcharts.js#2089]
# Bug report

## Codepen

https://codepen.io/pvictor-r/pen/qBabJaG

## Explanation

When hiding xaxis labels with `xaxis: {labels: {show: false}}`, grid lines on xaxis are hidden despite setting : 

```
grid: {
  xaxis: {
    lines: {
      show: true
    }
  }
}
```

Would it be possible to keep grid lines when hiding labels ?

Thank you !

**Comment by junedchhipa** [comment]
Sure, fixed it
