### ISSUE TITLE
Datetime in xaxis has an offset of one day 

### ISSUE THREAD

**Issue by lukasleitsch** [apexcharts/apexcharts.js#209]
## Codepen

In the documentation I found this example: https://codepen.io/apexcharts/pen/eVvjZx 

## Explanation

The dates on the x axis will not be shown exactly in the graph. E.g. the data array contains a couple with the date 02-11-2017. If you hover over this point in the graph the tooltip show the 10 Feb. On day before the defined. I expect that the tooltip shows the same date that was defined in the data array.

The following screenshot shows the offset between the defined date and the date in the tooltip:

![bildschirmfoto 2018-11-21 um 11 16 30](https://user-images.githubusercontent.com/3009245/48834858-0aa4c480-ed7f-11e8-9aaf-b93b96bc23aa.png)

**Comment by lukasleitsch** [comment]
I see. Adding GMT in the x value works for me. Thanks for you very fast reply.

**Comment by danielthedifficult** [comment]
Just wanted to say that I ran into this problem and am very grateful to have found this post...
