### ISSUE TITLE
Set z-order for individual data points / markers

### ISSUE THREAD

**Issue by ChristophBraunNebumind** [apexcharts/apexcharts.js#2092]
**Is your feature request related to a problem? Please describe.**	
I have a Plot (Scatter/Line) with many DataPoints. I use fillcolor to modify the color of each point individually. As the points are close to each other, it is likely, that they cover each other.  Some DataPoints are more important, so I want to stress them. I managed to set the size and the opacity for each DataPoint / Marker, but I was not able to put the more important DataPoints in the foreground.

**Describe the solution you'd like**	
Setting the z order of markers / DataPoints by giving a number, which is automatically ordered. Maybe another setting in discrete markers.

**Describe alternatives you've considered**	
Setting the z order of markers / DataPoints by setting a bool, comparable to the position option (https://apexcharts.com/docs/options/yaxis/) but for individual / discrete marker. 

**Additional context**

**Comment by duclt47** [comment]
same issue :(
