### ISSUE TITLE
Rendering multiple line chart with large dataset in single page

### ISSUE THREAD

**Issue by sathishkumar1848** [apexcharts/apexcharts.js#2093]
Hello everyone,
    I am rendering multiple linechart in same page with 2000 data. Each chart takes 2 secs for render. Each graph have 100's data its work fine but i try to add thousands of data its takes too much of time. If any possible to reduce rendering time?

My code:
    linedata = [{ x: "Sep 30 12:03", y: 181 },{ x: "Sep 30 12:03", y: 182 }..etc]
    var options = {
              series: [{
                name: field1.isensr_name,
                data: linedata,
              }],
              chart: {
                height: 300,
                type: 'line',
                zoom: {
                  enabled: true
                },
                animations: {
                  enabled: false,
                },
              },
              dataLabels: {
                enabled: false
              },
              markers: {
                size: 0
              },
              stroke: {
                show: true,
                curve: 'smooth',
                width: 2,
              },
              title: {
                text: Id1,
                align: 'left'
              },
              grid: {
                row: {
                  colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
                  opacity: 0.5
                },
              },
              xaxis: {
                type: 'category',
                tickAmount: 5,
                labels: {
                  trim: false,
                  rotate: 0,
                  minHeight: 40,
                  hideOverlappingLabels: true,
                },
              }
            };
    var lctnlineChart = new ApexCharts(document.querySelector("#chart-id1+""), options);
    lctnlineChart.render();

**Comment by junedchhipa** [comment]
I see you have already disabled animations and set the marker's size to 0.
Other than this, unfortunately, there are no ways to improve performance.
