### ISSUE TITLE
allowMultipleDataPointsSelection option not working on Treemaps

### ISSUE THREAD

**Issue by inghuguesboni** [apexcharts/apexcharts.js#2096]
Hi.
I'm working on a treemap with single data point selection (e.i mutualially exclusive data point selection). According to the documentation I should use allowMultipleDataPointsSelection (https://apexcharts.com/docs/options/states/). But when I tried it on treemap it doesn't seem to work. Here are the options I used.

const chartOptions = {
          states: {
              active: {
                 allowMultipleDataPointsSelection: false
              }
          },
          legend: {
            show: true
          },
          chart: {
            height: 300,
            id: 'treemap-raph',
            type: 'treemap'
          },
          title: {
            text: 'Basic Treemap'
          },
          plotOptions: {
            treemap: {
              distributed: true,
              enableShades: false
            }
          }
        }

What I'm I doing wrong? Thank you for your help.

**Comment by junedchhipa** [comment]
You're doing nothing wrong. That was a bug in ApexCharts which I just fixed.
Please wait for the next release.
