### ISSUE TITLE
Stacked bar chart border radius

### ISSUE THREAD

**Issue by marghoobahmad0344** [apexcharts/apexcharts.js#2097]
# Bug report

## Codepen

click on given link to view the issue  [this codepen](https://codepen.io/marghoobahmad0344/pen/YzGWjLN)
issue on reactjs [this codepen](https://codesandbox.io/s/react-basic-example-forked-dp1xi)

## Explanation

- I want to make only top border rounded instead of each stack entity
- here is every stack stack entity shows rounded border
- No error message

**Comment by IsaacSomething** [comment]
Add

```
.apexcharts-bar-series.apexcharts-plot-series  .apexcharts-series:nth-child(3) path {
    clip-path: inset(0% 0% -11% 0% round 8px);
  }
```
  
  in your codepen example ( I can save the codepen )
  
  disable the animations
 
```
chart: {
    height: 380,
     animations: {
          enabled: false
     },
```

and remove horizontal - I did this in a vertical chart - and remove the rending shape

This technique can work for horizontal you just need to tweek the clip-path to suite your needs

**Comment by praneetloke** [comment]
@IsaacSomething your suggestion mostly works until I hover over the bar and it looks like this:

![Screen Shot 2021-03-02 at 13 47 14](https://user-images.githubusercontent.com/1466314/109719664-d45d6e80-7b5d-11eb-84e1-23bdbf0b385f.png)

**Comment by IsaacSomething** [comment]
@praneetloke I think you might have to remove the hover state and active state. It should still show the tooltip 

```

states: { 
    hover: {
        filter: {
            type: 'none',
        }
    },
    active: { 
        filter: {
            type: 'none', 
        }
    },
}

**Comment by praneetloke** [comment]
Ah gotcha. Unfortunately, that won't work for me. I'd like to keep the hover state for accessibility reasons.

**Comment by junedchhipa** [comment]
Since v3.26.0, there is a new property for border-radius

```
plotOptions: {
  bar: {
    borderRadius: 5
  }
}
```

**Comment by ambikak10** [comment]
How to make both the sides of the bar rounded?

**Comment by KarimLeeKarim** [comment]
> How to make both the sides of the bar rounded? borderRadius works only on one side?

@ambikak10 hi buddy, see below code for both sides:
.apexcharts-series path {
                                        clip-path: inset(5% 5% 5% 0% round 8px);
 }
or
.apexcharts-bar-series.apexcharts-plot-series .apexcharts-series path {
                                        clip-path: inset(5% 5% 5% 0% round 8px);
}

**Comment by mahmouds12** [comment]
this still has an issue... if one of the columns doesn't have values for all item... the top most part will not be rounded
check:
![image](https://user-images.githubusercontent.com/15720804/190984010-7a7c87de-0ff7-4275-b01a-b461d764df7b.png)

**Comment by technika7** [comment]
https://github.com/apexcharts/apexcharts.js/issues/1779#issuecomment-1251632683

**Comment by technika7** [comment]
You can try this solution in until we get a fix.

https://github.com/apexcharts/apexcharts.js/issues/1779#issuecomment-1251632683

**Comment by SalmaWael** [comment]
> Since v3.26.0, there is a new property for border-radius
> 
> ```
> plotOptions: {
>   bar: {
>     borderRadius: 5
>   }
> }
> ```

![image](https://user-images.githubusercontent.com/83821396/231426863-ab3e7255-4751-4aeb-b03a-d18d54765091.png)
![image](https://user-images.githubusercontent.com/83821396/231427046-28f0afca-757f-4fea-841b-cc02d7ec5783.png)

I got this behavior but I want the top to have a border-radius not both top and bottom like this 

![image](https://user-images.githubusercontent.com/83821396/231427762-09b65358-a52d-47ad-8fe3-c3fd70504ef2.png)

**Comment by mwinner313** [comment]
![Capture](https://github.com/apexcharts/apexcharts.js/assets/16043883/8b95da1f-13ee-4e71-bb1b-6c18cf191d48)
can any body help me with this?
