### ISSUE TITLE
Area chart not rendering on mobile devices

### ISSUE THREAD

**Issue by Sttorgen** [apexcharts/apexcharts.js#2099]
Hello,

Since last update area charts don't rendering when I first load the page, only after several page refresh. This problem is only on mobile devices, on desktop everithing is ok.

![IMG_20201210_093626](https://user-images.githubusercontent.com/75777294/101755330-6749b800-3add-11eb-9c03-72c6406e0732.jpg)
![IMG_20201210_102121](https://user-images.githubusercontent.com/75777294/101755333-67e24e80-3add-11eb-9c64-fbebe4035d6f.jpg)

**Comment by junedchhipa** [comment]
Can you post your code?
What are your options?

**Comment by Sttorgen** [comment]
now i checked on desktop. Same problem like on mobilde devices, need few refresh.

these are the options. it is enough?

var options_48_tomeg = {
          series: [
          {
            name: '<?php switch($nyelv){
                           case 1: echo "Weight"; break;
                           case 2: echo "Greutate"; break;
                           case 3: echo "Tömeg"; break;
                           default: echo "Greutate"; break;}?>',
            data: [<?php echo $suly_apex; ?>]
          }
          ],
        chart: {
          height: '100%',
          id: 'area-datetime',
          type: 'area',
          dropShadow: {
            enabled: true,
            color: '#000',
            top: 18,
            left: 7,
            blur: 10,
            opacity: 0.2
          },
          toolbar: {
                show: true,
                offsetX: 0,
                offsetY: 15,
                    tools: {
                        download: false |'<b class="fas fa-bars"></b>',
                        selection: true,
                        zoom: '<button class="fas fa-search-plus"></button>',
                        zoomin: false | '<b class="fas fa-minus-circle"></b>',
                        zoomout: false | '<b class="fas fa-plus-circle"></b>',
                        pan: '<button class="far fa-hand-paper" style="font-size: 23px;"><button>',
                        reset: '<b class="fas fa-home"></b>',
                        customIcons: []
                    },
                    export: {
                      csv: {
                        filename: 'cantar',
                        columnDelimiter: ',',
                        headerCategory: 'Date',
                        headerValue: 'value',
                        dateFormatter(timestamp) {
                          return new Date(timestamp).toDateString()
                        }
                      }
                    },
                autoSelected: 'zoom' 
            },
        },
        colors: ['#18e7c4'],
        dataLabels: {
          enabled: false,
        },
        stroke: {
            show: true,
            curve: 'smooth',
            lineCap: 'butt',
            colors: undefined,
            width: 4
        },
        title: {
          text: '<?php switch($nyelv){
                           case 1: echo "Weight:"; break;
                           case 2: echo "Greutate:"; break;
                           case 3: echo "Tömeg:"; break;
                           default: echo "Greutate:"; break;}?>  <?php echo $suly; echo ' kg' ?>',
          align: 'center',
          offsetX: 0,
          offsetY: 10,
          style: {
            fontSize:  '16px',
            fontWeight:  'regular',
            fontFamily:  undefined,
            color:  'white'
          }
        },
        grid: {
          borderColor: '#bfbfbf',
          row: {
            colors: undefined,
            opacity: 0.5
          },
        },
        markers: {
          size: 4.5,
          strokeWidth: 2,
          strokeColors: '#1D3159',
          hover: {
               sizeOffset: 1
          }
        },

        tooltip: {
          enabled: true,
          fillSeriesColor: false,
          style: {
            fontSize: '12px',
            fontFamily: undefined
          },
          x: {
            format: 'dddd HH:mm'
          },
          y: {
            formatter: function(value, { series, seriesIndex, dataPointIndex, w }) {
              return value + " kg"
            },
            title: {
              formatter: (seriesName) => false
            },
          }
        },

        fill: {
          type: 'gradient',
          gradient: {
            gradientToColors: ['#1D3159'], 
            shadeIntensity: 1,
            opacityFrom: 0.7,
            opacityTo: 0,
            stops: [0, 100]
          }
        },

        xaxis: {
          type: 'datetime',
          tooltip: {
            enabled: false
          },
          categories: [<?php echo $ido_apex; ?>],
          labels: {
            datetimeUTC: false,
            style: {
              colors: '#ffffff',
              fontSize: '12px',
              fontFamily: 'Helvetica, Arial, sans-serif',
              fontWeight: 400,
              cssClass: 'apexcharts-xaxis-label',
          },
          }
        },
        yaxis: {
            formatter: function (value) {
                return value
            },
            labels: {
                show: true,
                style: {
                    colors: '#ffffff',
                    fontSize: '12px',
                    fontFamily: 'Helvetica, Arial, sans-serif',
                    fontWeight: 400,
                    cssClass: 'apexcharts-yaxis-label',
                },
            },
        },
//****************************************************************RESPONSIVE***************************************************
        responsive: [
            {
              breakpoint: 850,
              options: {
                series: [
                {data: [<?php echo $suly_apex_24; ?>],}],
                plotOptions: {
                  bar: {
                    horizontal: false
                  }
                },
                chart: {
                    toolbar: {
                            show: false,
                    },
                },
                stroke: {
                    show: true,
                    curve: 'smooth',
                    lineCap: 'butt',
                    colors: undefined,
                    width: 2.5
                },
                xaxis: {
                    categories: [<?php echo $ido_apex_24; ?>],
                },
                markers: {
                  size: 3,
                  strokeWidth: 2,
                  strokeColors: '#1D3159',
                  hover: {
                      sizeOffset: 1
                  }
                }
              }
            }
          ]
        };

        var chart1 = new ApexCharts(document.querySelector("#chart_48_tomeg"), options_48_tomeg);
        chart1.render();

**Comment by Sttorgen** [comment]
> Can you post your code?
> What are your options?

i cannot write all text as code. maybe is too long, sorry

**Comment by junedchhipa** [comment]
Difficult to guess what is the issue without a reproducible example.
Can you tell me which last version works correctly and since which version it breaks?

**Comment by junedchhipa** [comment]
I guess `height: 100%` is causing issues.
Can you set a fixed height and check if it works?

**Comment by Sttorgen** [comment]
> Difficult to guess what is the issue without a reproducible example.
> Can you tell me which last version works correctly and since which version it breaks?

I will try later when I arrive home. Until sunday night everithing was ok. This problem is from monday morning. Bucharest time

**Comment by Sttorgen** [comment]
This is the website:
https://cantarapicol.ro/cantartest.php

**Comment by Sttorgen** [comment]
> I guess `height: 100%` is causing issues.
> Can you set a fixed height and check if it works?

hi,

i changed height to fix, 300 px. didnt solve the problem. You can try it. if you enter to my website charts are blank, if you make an inspect and resize the width of page, the chart will render. https://cantarapicol.ro/cantartest.php

**Comment by Sttorgen** [comment]
if i download a code of previous version from change log, if i upload to my server, how can i include? i did't find a way

**Comment by Sttorgen** [comment]
i istalled version Version 3.22.1 and everything is ok. so i resolved my problem :) but i think that last version have a bug

**Comment by thinklim** [comment]
I had same problem on web (with javascript), first chart rendering not perfect working well...
![image](https://user-images.githubusercontent.com/51071806/102172664-8f218d00-3edc-11eb-81a5-9e46e94d3873.png)
![image](https://user-images.githubusercontent.com/51071806/102172717-abbdc500-3edc-11eb-978d-1f45be74465c.png)


So I did downgrade latest version(3.22.3, 2020-12-15) to 3.22.2 version and first chart rendering perfect working well!
![image](https://user-images.githubusercontent.com/51071806/102172769-d0b23800-3edc-11eb-8521-1043f229e2a5.png)
![image](https://user-images.githubusercontent.com/51071806/102172807-e7588f00-3edc-11eb-848c-f90f17989485.png)

**Comment by bgwaltney** [comment]
For those who run into this in the future, for me it had to do with formatting the dates instead of leaving them as date objects.

**Comment by Sanan4li** [comment]
Surprised to see this issue is closed but not fixed.

**Comment by playanth95978** [comment]
Not resolved yet

**Comment by playanth95978** [comment]
Even on your official documentation, tooltip are not displayed in your example here https://apexcharts.com/angular-chart-demos/pie-charts/simple-donut/ 
. 
With chrome, and dev tools, mobile screen choice.
