### ISSUE TITLE
Don't resize graph on legend click

### ISSUE THREAD

**Issue by jkohlin** [apexcharts/apexcharts.js#2100]
My problem is that when I click a legend in a line graph it resizes ( see video )

**Fix**
It would be great if there was an option to not resize the graph

**Additional context**	
It's the Apex vue component

![apex-grow](https://user-images.githubusercontent.com/4112881/101885009-d258c480-3b99-11eb-8f57-e0a2a4f34f06.gif)

![apex-grow-code](https://user-images.githubusercontent.com/4112881/101885471-73477f80-3b9a-11eb-9081-acf2db12df70.gif)

**Comment by junedchhipa** [comment]
Can you provide a reproducible example? Codepen?

**Comment by jkohlin** [comment]
Ihaven't been able to reproduce it in codepen. Will see what I can do. The apexchart vue component is destroyed and remounted when I click a legend because I'm saving the change to database in a function that set's the loading state to true for a short while and that's when it resizes. It only happens if the size of the parent container is not a golden ratio size. And that is the ratio it resizes to. If I lock the parent container to a fixed height, I just get a scroll in the chart component.

**Comment by jkohlin** [comment]
It turned out I had height set to auto in chart options 😱.
