### ISSUE TITLE
Can't export CSV on line graphs, getting errror "i.split is not a function"

### ISSUE THREAD

**Issue by leroybm** [apexcharts/apexcharts.js#2101]
# Bug report

## Codepen

https://codepen.io/asksuite-leroy/pen/NWRbEGR

## Explanation

- What is the behavior you expect?

 The CSV to be exported

- What is happening instead?

Nothing happens when the export button is clicked, and a error is thrown on the console.
This seems to happen only on our production environment, we're using ng-apexcharts, but the error occurs on the codepen as well.

- What error message are you getting?

```
apexcharts:6 Uncaught TypeError: i.split is not a function
    at g (apexcharts:6)
    at apexcharts:6
    at apexcharts:6
    at Array.map (<anonymous>)
    at t.value (apexcharts:6)
    at t.value (apexcharts:6)
```

**Comment by junedchhipa** [comment]
Fixed it, thanks for reporting.

**Comment by leroybm** [comment]
Thank you! 😄

**Comment by leroybm** [comment]
@junedchhipa Is there any way that you could release a new version with this fix?

**Comment by lyvewave** [comment]
I'm actually getting this same error, but when using paired values both in the form of tuples and {x, y} data points. I have the latest release of apexcharts (3.23.1) with react-apexcharts 1.3.7.

**Comment by bn3t** [comment]
As this issue is closed, I created another one for my problem specifically which is happening when the categories are in the form of an array of strings.

**Comment by a-davityan** [comment]
The error is still there - https://codepen.io/albert-davityan/pen/KKNYoxr

**Comment by asi-devp** [comment]
> The error is still there - https://codepen.io/albert-davityan/pen/KKNYoxr

I'm get this error also where Yaxis is date in my project. is there any fix for this?
thanks

**Comment by jonathanteranbln** [comment]
I am getting this error also when there are 2 or more series, where there is only 1 that works perfectly

**Comment by keenanm500** [comment]
This issue still exists
