### ISSUE TITLE
mouseEnter config property for Treemap returns NaN for 'seriesIndex'

### ISSUE THREAD

**Issue by Steven1284** [apexcharts/apexcharts.js#2103]
The 'seriesIndex' inside the config object for the Treemap chart is in all my cases 'NaN'. I would really appreciate if someone has a solution or if someone can confirm the bug.

Let me know if you need any more information!

<img width="504" alt=" 2020-12-12 om 22 52 51" src="https://user-images.githubusercontent.com/64090951/101995826-2adcae80-3ccd-11eb-930f-9457bddadecc.png">

**Comment by junedchhipa** [comment]
Can you please create a Codepen so it can be easily reproduced?
