### ISSUE TITLE
X-Axis Time and chart are not coordinated

### ISSUE THREAD

**Issue by DebasisBehera123** [apexcharts/apexcharts.js#2104]
![Screenshot from 2020-12-14 12-44-16](https://user-images.githubusercontent.com/40021924/102051820-29190500-3e0b-11eb-80e1-cd0a75d5f3dd.png)

![Screenshot from 2020-12-14 12-44-30](https://user-images.githubusercontent.com/40021924/102051812-26b6ab00-3e0b-11eb-9ed2-227c7cf639b7.png)
![Screenshot from 2020-12-14 12-44-39](https://user-images.githubusercontent.com/40021924/102051819-28806e80-3e0b-11eb-9230-e02e3bfaa192.png)

The chart is not placing in the appropriate place.

@junedchhipa 
Will you please help me out with this?

**Comment by eliasplatekdkt** [comment]
This is related to the timezone of your browser, all of your input dates should be UTC format. If you want to manage the timezone manually, your dates should all have the same timezone, and set the property `xaxis.labels.datetimeUTC` to `false`
