### ISSUE TITLE
CSV Download: Configure Decimal Separator

### ISSUE THREAD

**Issue by Venlious** [apexcharts/apexcharts.js#2106]
**Is your feature request related to a problem? Please describe.**	
In some languages (Dutch) the decimal separator is a comma `,` instead of a `.` period. When clients try to import their exported `.csv` files these into Microsoft Excel it messes with their output and requires additional configuration in order to work.

**Describe the solution you'd like**	
It would be nice if under `chart.toolbar.export.csv` we could configure what decimal separator to use.

**Describe alternatives you've considered**	
I have tried changing the `columnDelimiter` to a tab instead of a comma, hoping this would bypass the issue. Unfortunately this is not the case.

**Comment by cendro93** [comment]
Right now i'm having the same problem.
The csv file contains numeric values written with "dot" separator.
Both Excel and Libre Office expect numeric values to be separeted with "comma".
Please provide an option to change separator or add formatter for each column.

**Comment by mariokandut** [comment]
This would be a great feature addition when localizing the chart. Currenlty only `.` separation is possible. BUMP!

**Comment by VSridhar78** [comment]
I have the same problem too, is there any solution/fixes for this issue ?

**Comment by SalvatoreSA** [comment]
I find myself having the same problem; did anyone find a workaround or another component that can do this?
