### ISSUE TITLE
panning on timeline charts do not work. 

### ISSUE THREAD

**Issue by raresachin** [apexcharts/apexcharts.js#2111]
https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

panning on timeline charts do not work.

**Comment by LaKing** [comment]
Indeed

**Comment by geferon** [comment]
This is an important issue for the last version, I rely on zooming and panning, dunno if this could be fixed soon?

**Comment by junedchhipa** [comment]
This is fixed and a new version will be released soon.
