### ISSUE TITLE
DataLabels not widely visible in crowded bubble chart

### ISSUE THREAD

**Issue by mapringg** [apexcharts/apexcharts.js#2118]
# Bug report

## Codepen

https://codesandbox.io/s/react-basic-example-forked-ur8jz

## Explanation

- What is the behavior you expect? I expect more dataLabels to be visible.
- What is happening instead? Many dataLabels is not visible unless I bring the fontSize down to 1px.
- What error message are you getting? Nothing.

![Screen Shot 2020-12-18 at 15 10 19](https://user-images.githubusercontent.com/15067237/102593230-28ec7280-4147-11eb-94b7-3b84bfad3cbc.png)
![Screen Shot 2020-12-18 at 15 10 44](https://user-images.githubusercontent.com/15067237/102593234-2c7ff980-4147-11eb-8694-0ea3e15fa9ce.png)

**Comment by CRamos132** [comment]
Any updates on this issue? I'm also having this problem on version "3.20.2"
