### ISSUE TITLE
On selecting a bar fade other bars

### ISSUE THREAD

**Issue by AlokMishra051298** [apexcharts/apexcharts.js#2119]
@junedchhipa Is there any property for that in Apex? I had looked into the documentation if there is any way to do that please suggest. 
![image](https://user-images.githubusercontent.com/46258899/102635036-bd22fd80-4178-11eb-92e5-b6918d947744.png)

**Comment by junedchhipa** [comment]
Sorry, this is not available in ApexCharts.

**Comment by AlokMishra051298** [comment]
Can we add this feature?
