### ISSUE TITLE
minWidth for labels do not work

### ISSUE THREAD

**Issue by bubnenkoff** [apexcharts/apexcharts.js#2120]
## Codepen
https://jsfiddle.net/vfk13e8q/

## Explanation

I need to display long text in label. I know there is option that allow to split long text to lines like: `["some", "long", "text"]`. But it's not suitable for me. I need to simply increase labels size and show more text.

Option `minWidth` do not work.

**Comment by junedchhipa** [comment]
`maxWidth` should be set instead of `minWidth`.
The default `max-width` of a y-axis label is 160, so that should be increased.

Try

```js
yaxis: {
  labels: {
    maxWidth: 250
  }
}
```

**Comment by bubnenkoff** [comment]
@junedchhipa if set to 200 it's cutting from both sides.

**Comment by bubnenkoff** [comment]
@junedchhipa how to fix this issue? https://jsfiddle.net/9t4vfLnp/ the text is going is going outside bounds.
