### ISSUE TITLE
How create chart of temperature with gradient?

### ISSUE THREAD

**Issue by Feduch** [apexcharts/apexcharts.js#2125]
Hi!

ApexCharts it is very cool chart, thanks!

How can create chart like on screenshot?

![multi-colored_line_chart_with_gradient_fill](https://user-images.githubusercontent.com/5888590/103132482-c69af100-46b5-11eb-9e6e-0c642a87ea49.png)

I have  ranges of temperatures:

0 - 40 C  - #0ACEF9
40 - 50 C- #FFE663
50 - 60 C - #F9440A
60 - 100 C - #F9440A

I want show it on chart. Can I do it with ApexCharts?

**Comment by junedchhipa** [comment]
```js
  fill: {
    type: "gradient",
    gradient: {
      type: 'vertical',
      shadeIntensity: 1,
      opacityFrom: 1,
      opacityTo: 1,
      colorStops: [
        {
          offset: 40,
          color: "#0ACEF9",
          opacity: 1
        },
        {
          offset: 50,
          color: "#FFE663",
          opacity: 1
        },
        {
          offset: 60,
          color: "#F9440A",
          opacity: 1
        }
      ]
    }
  }
```

Full example - https://codepen.io/apexcharts/pen/wvzPgvq?editors=0010
![2n68pklj](https://user-images.githubusercontent.com/17950663/103133921-6450e900-46d3-11eb-8da8-8b63de30eea3.png)

**Comment by junedchhipa** [comment]
⚠️   Please note that the gradient stops don't actually correspond to the actual values.
The gradient-stops corresponds to the height of the line series drawn.

**Comment by Feduch** [comment]
>  Please note that the gradient stops don't actually correspond to the actual values.
> The gradient-stops corresponds to the height of the line series drawn.

Yes, I see. I need that the gradient stops  actually correspond to the actual values. Is it possible?

**Comment by junedchhipa** [comment]
Sorry, no. That is a different feature which has been suggested [here](#596), but not yet implemented

**Comment by Feduch** [comment]
I see, thanks!

**Comment by Feduch** [comment]
Temporary resolve:

Dynamicaly add colors to colorStops. 


```
let colorStops = []

if (isHot) {
  colorStops.push({
    offset: 0,
    color: "#F9440A",
    opacity: 1
  })
}

if (isMiddle) {
  colorStops.push({
    offset: 40,
    color: "#FFE663",
    opacity: 1
  })
}

if (isCold) {
  colorStops.push({
    offset: 100,
    color: "#0ACEF9",
    opacity: 1
  })
}
```

**Comment by gowdhamGM** [comment]
@Feduch @junedchhipa Gradient stops actually correspond to the actual values. Is it possible right now? Similarly, I'm now stuck.
Hi @Feduch you have mentioned temporary solution. how to define that if condtions of isCold, isMiddle and isHot?
I have ranges of temperatures:
-35C to 120C range
Different colors for this range 
-35 to -20 red 
-20 to 30 yellow
30 to 70  blue
70 to 100 yellow
100 to 120 red
