### ISSUE TITLE
How to show the floating yaxis values?

### ISSUE THREAD

**Issue by iAmShakil** [apexcharts/apexcharts.js#2129]
When taken out of the plotting area by using floating: true, the yaxis ticks are not visible on the page anymore. How to make them visible?

**Comment by junedchhipa** [comment]
```javascript
yaxis: {
  labels: {
    offsetX: 30
  }
}
```

**Comment by iAmShakil** [comment]
Anyone who's trying to show the floating yAxis without dragging it into the plotting area, use the CSS property overflow: visible on the SVG element.
