### ISSUE TITLE
When saving PDF, colored balls in series selector buttons are not displayed

### ISSUE THREAD

**Issue by PippoApps** [apexcharts/apexcharts.js#2130]
# Bug report
JS ApexCharts, displays properly in page, but when printing the coloured balls besides series name are not displayed. PDF is saved using "save as PDF" from latest chrome on mac.

This is how it shows in browser:
![image](https://user-images.githubusercontent.com/29799572/103259979-0dca0000-499c-11eb-8f7f-8172bab296e2.png)

This is on exported PDF (as you can see the coloured indicators are missing):
![image](https://user-images.githubusercontent.com/29799572/103260397-be84cf00-499d-11eb-8138-a252afc8ef71.png)

**Comment by junedchhipa** [comment]
How are you generating the PDF? Which library are you using?

**Comment by PippoApps** [comment]
I am exporting on client it using print as pdf in Google chrome.
