### ISSUE TITLE
Brush Chart - preventDefault React

### ISSUE THREAD

**Issue by ChenNingRui** [apexcharts/apexcharts.js#2132]
# Bug report

## Explanation
React > Line Charts > Brush chart

Every time I click the Brush chart (the bottom one), the bug shows up. 

Unable to preventDefault inside passive event listener invocation.  | push../node_modules/apexcharts/dist/apexcharts.common.js.t.start | @ | apexcharts.common.js:14

**Comment by ChenNingRui** [comment]
let optionsOne = {
        chart: {
            id: 'chart2',
            height: 230,
            toolbar: {
                autoSelected: 'pan',
                show: false
            }
        },
        animations: {
            enabled: true,
            easing: 'easeinout',
            speed: 800,
            animateGradually: {
                enabled: true,
                delay: 150
            },
            dynamicAnimation: {
                enabled: true,
                speed: 350
            }
        },
        xaxis: {
            type: 'datetime'
        },
        colors: ['#fdbf6f', '#1f78b4'],
        stroke: {
            width: 2
        },
        dataLabels: {
            enabled: false
        },
        fill: {
            opacity: 1,
        },
        yaxis: [
            {
                axisTicks: {
                    show: true
                },
                axisBorder: {
                    show: true,
                    color: "#fdbf6f"
                },
                labels: {
                    style: {
                        colors: "#fdbf6f"
                    }
                },
                title: {
                    text: "Temperature",
                    style: {
                        color: "#fdbf6f"
                    }
                }
            },
            {
                opposite: true,
                axisTicks: {
                    show: true
                },
                axisBorder: {
                    show: true,
                    color: "#1f78b4"
                },
                labels: {
                    style: {
                        colors: "#1f78b4"
                    }
                },
                title: {
                    text: "Observations",
                    style: {
                        color: "#1f78b4"
                    }
                }
            }
        ],
    };

    let optionsTwo = {
        chart: {
            id: "chart1",
            height: 130,
            foreColor: "#ccc",
            brush: {
                target: "chart2",
                enabled: true
            },
            selection: {
                enabled: true,
            }
        },
        animations: {
            enabled: true,
            easing: 'easeinout',
            speed: 800,
            animateGradually: {
                enabled: true,
                delay: 150
            },
            dynamicAnimation: {
                enabled: true,
                speed: 350
            }
        },
        colors: ["#FF0080"],
        stroke: {
            width: 2
        },
        grid: {
            borderColor: "#444"
        },
        markers: {
            size: 0
        },
        xaxis: {
            type: "datetime",
            tooltip: {
                enabled: false
            }
        },
        yaxis: {
            tickAmount: 2
        },
    };

**Comment by andrei-gheorghiu** [comment]
`apex-charts` has [svg.draggable.js](https://github.com/svgdotjs/svg.draggable.js/releases/tag/2.2.2) - `v2.2.2` as dependency. Upgrading it to `v3.0.2` is likely going to fix it, according to [this issue](https://github.com/svgdotjs/svg.draggable.js/issues/110).

**Comment by renatojmsantos** [comment]
I have this issue now... i already upgrade the svg.draggable.js to the last version

**Comment by rando128** [comment]
Same here with JS implementation

**Comment by Art77** [comment]
То же самоеДо версии 3.22.2

**Comment by Art77** [comment]
Also
Before version 3.22.2 there is no error, the next version (3.22.3) starts to appear stably
Google Chrome 97.0.4692.71

**Comment by Art77** [comment]
same error in documentation https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/

**Comment by jl8n** [comment]
I can confirm this issue exists in the latest version of ApexCharts

**Comment by dungdao191299** [comment]
me too, is there way to fix it?

**Comment by scharf** [comment]
I am also getting this error when dragging the brush: `Unable to preventDefault inside passive event listener invocation.`

**Comment by alailsonribeiro** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/12869444/204796789-32907be8-8a3b-4135-9e86-88d743de0407.png">

I have the same error, when I move in Brushed Graph

**Comment by alailsonribeiro** [comment]
The same in page of demo https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/12869444/204798993-8560f35b-a681-49a3-94bd-d9b3b44ba4fa.png">

**Comment by alailsonribeiro** [comment]
Erros in chrome 107.0.5304.121  In firefox last version the message is:
<img width="974" alt="image" src="https://user-images.githubusercontent.com/12869444/204799922-b5ad4b68-e402-42ab-b959-665d8ec9d5a5.png">

**Comment by alailsonribeiro** [comment]
No errors in Safari last version
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/12869444/204800313-b5d0b211-e2d7-4dd6-8d47-94a9539b6f43.png">

**Comment by alailsonribeiro** [comment]
The same error in Microsoft Edge Versão 107.0.1418.62 (Compilação oficial) (x86_64) 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/12869444/204800946-07aaef92-2eb2-4808-81ec-0aa2d3972c1d.png">

I hope help :-)

**Comment by junedchhipa** [comment]
For the 23 people who reacted to this and never got an answer: **this was fixed in v3.47.0**, and nobody told you. Apologies.

It's the same bug as #3533, which I've just closed with the full bisection. Short version, counting Chrome's intervention messages on one fixed page with only the library file changing:

| version | click on the brush selection | after dragging |
|---|---|---|
| 3.36.3 | 2 | 6 |
| 3.44.0 | 2 | 6 |
| 3.46.0 | 2 | 6 |
| **3.47.0** | **0** | **0** |
| 4.x / 6.10.0 | 0 | 0 |

The vendored svg.js `on()` helper defaulted every listener it attached to `passive: true`, so the draggable plugin's own `preventDefault()` was always illegal, which is why the stack trace looked anonymous and unrelated to anything in your app. Fixed in 6a300a50e, a commit about `autoScaleYaxis` that mentions this only in passing, which is exactly why neither this issue nor #3533 was ever linked to it.

There is now an interaction test covering the click, the drag, the wheel and a real touch drag on a brush chart, so it can't come back unnoticed.

If you are on 3.47.0 or later and still see it, please open a new issue with a repro rather than commenting here, since this thread is closed and predates several rewrites of the event handling.
