### ISSUE TITLE
Skip few x-axis label and jump to another label.

### ISSUE THREAD

**Issue by gtl-alpesh** [apexcharts/apexcharts.js#2138]
![apexchart](https://user-images.githubusercontent.com/19168337/103639331-36da2a00-4f74-11eb-8c5c-97475e9e4870.png)

This is a simple line Apexchart I have setup with Month & Sales number in X & Y, Now, Sometime There is the possibility that sales didn't happen for a particular month and next month it is. So my line needs to be straight to the particular month only. 
I.e. 
Jan - 10 Sales
Feb - 0 Sales
Mar - 0 Sales
Apr - 51 Sales

Now according to that, I want to draw my line from "Jan" to "Apr" straight. No, Any point needed in between. can anyone please suggest me on something, I have tried like this.

***data: [10, null, null, 51, 49]***

null value breaks the line, but I want to be straight until the next point.  for better understanding, Red line into the picture is my requirement.

Any help..!! Thanks in advance.

**Comment by shubh1996** [comment]
have the same requirement. Any update here?

**Comment by gtl-alpesh** [comment]
> have the same requirement. Any update here?

No, I have Work around with different method/option/design, but for particular this one, No Update.
