### ISSUE TITLE
Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by avil13** [apexcharts/apexcharts.js#215]
Hi.

I use apexcharts with Vue without Vue-apexcharts.
I noticed a problem when creating a graph with the `'area'` type.
Created an example with an error, in CodPen the error is not tracked.

## Code

Watch only `mounted()` method.

[https://codesandbox.io/s/2855n9x4j](https://codesandbox.io/s/2855n9x4j)

## Explanation 

- __What is the behavior you expect?__
    - No errors when creating chart.

- __What is happening instead?__
    - The chart is drawn, but we get an error message.

- __What error message are you getting?__
    - > Cannot read property 'setAttribute' of undefined

**Comment by junedchhipa** [comment]
@avil13 
I copied the same code of your codesandbox in my Vue-application, but the error occurs only on codesandbox. 
Can you reproduce the error in a local environment?

**Comment by avil13** [comment]
Maybe it has something to do with the rendering of Vue. If I can locate the problem, describe it in more detail

**Comment by avil13** [comment]
Even without a Vue wrapper, working with a chart is convenient.

**Comment by avil13** [comment]
I made mistakes more readable, but they are not clear to me anyway.

If you can reproduce and correct, I will be very grateful.

![image](https://user-images.githubusercontent.com/1606172/49702559-879ebd80-fc0a-11e8-893e-7543a6eb31ec.png)

![image](https://user-images.githubusercontent.com/1606172/49702583-c59be180-fc0a-11e8-85cf-926948c759f6.png)

**Comment by junedchhipa** [comment]
Thank you for the screenshots.
I will look into it.

**Comment by junedchhipa** [comment]
Fixed it in 2.4.2
