### ISSUE TITLE
Wrong Tooltip when hovering between datetimes (Showing first datapoint tooltip)

### ISSUE THREAD

**Issue by RitaVale** [apexcharts/apexcharts.js#2155]
# Bug report
Using your example at :https://apexcharts.com/javascript-chart-demos/mixed-charts/line-column-area/
The issue is better documented via the GIF below.

![EJJjV5ZB1u](https://user-images.githubusercontent.com/72170626/104297591-f5d59e80-54ba-11eb-891f-3e10ce712c0a.gif)

## Explanation

- What is the behaviour you expect?
The correct tooltip to be shown (or none, when not hover a valid time)
- What is happening instead?
January 1 is showing instead of the correct tooltip value
- What error message are you getting?
None

**Comment by gemmagarcias1** [comment]
Same in MultiAxis Chart

**Comment by AaronPowell96** [comment]
Is this not because you have a shared tooltip and you're hovering over data because of the green area  chart data? Plus looks like theres a crosshair so it will follow team c. Toggle of b and c and see if it still does it?

**Comment by RitaVale** [comment]
@AaronPowell96 I think if that was the case then it should jump to the previous data point and not the initial one, just like it does when hovering between May and Jun.

**Comment by RuneNyhuus** [comment]
Have this been fixed? i have same problem?
When i using 1year span with this year start. Then tooltip shows Dec, Jan then Jumps to March... Pretty werid, because X Axis show the right Month names.?

**Comment by matthetherington** [comment]
Still an issue for me @RuneNyhuus

**Comment by nodahikaru** [comment]
Same issue
