### ISSUE TITLE
dataLabels isn't working correctly

### ISSUE THREAD

**Issue by romachne** [apexcharts/apexcharts.js#2157]
# Bug report

## Codepen
https://codepen.io/romachne/pen/RwGevbz
I'm using React, but this bug is also reproduced on JS

## Explanation

- What is the behavior you expect?
I want the dataLabels to be in the correct position on the bars, like here
![image](https://user-images.githubusercontent.com/40444580/104450730-5e5b7300-55c2-11eb-8d58-3c9f790a1be9.png)

- What is happening instead?
DataLabels are in the wrong position
![image](https://user-images.githubusercontent.com/40444580/104450639-39670000-55c2-11eb-8eca-c45ced94c068.png)

- What error message are you getting?
No error message

**Comment by junedchhipa** [comment]
What is the use-case to use a date like this?
```
new Date(1, 1, -7500)
```

**Comment by romachne** [comment]
I want to create a historical timeline, so i need to use BC dates
