### ISSUE TITLE
Bug after update

### ISSUE THREAD

**Issue by Rogue85** [apexcharts/apexcharts.js#216]
Updated apexcharts on the latest version. After that markers on all charts are not displayed. Tried to remove chartOptions that default settings were exposed, but it did not help. Also the line which appears when targeting is not displayed.

![default](https://user-images.githubusercontent.com/6161136/49226575-16842c80-f3f8-11e8-8dc6-8712c434e512.png)

**Comment by junedchhipa** [comment]
Couldn't reproduce on my side. Markers displays as expected on all my sample charts.

Can you create a codepen so I can look at the configuration?

**Comment by Rogue85** [comment]
Solved. The new version do not work with numbers as strings.
