### ISSUE TITLE
Colors set for negative values aren't respected (bar chart)

### ISSUE THREAD

**Issue by stianmandarin** [apexcharts/apexcharts.js#2163]
# Bug report

## CodeSandbox

[See CodeSandbox](https://codesandbox.io/s/vue-basic-example-forked-dqm5l?file=/src/components/Chart.component.vue)

## Explanation

- What is the behavior you expect?
    - For the negative value to be colored red
- What is happening instead?
    - It remains blue (which I guess is the default)
- What error message are you getting?
    - None

Colors are set under `plotOptions.bar.colors.ranges`

**Comment by IAL32** [comment]
I encountered this same problem some time ago.

I discovered that `from` and `to` do not follow the "natural" direction when acting on negative values.

The example shows something like:

```json
ranges: [
  {
    from: 0,
    to: -9999,
    color: '#CD363A',
  },
  {
    from: 0.1,
    to: 9999,
    color: '#52B12C',
  }
]
```

You should instead:

```json
ranges: [
  {
    from: -9999,
    to: 0,
    color: '#CD363A',
  },
  {
    from: 0.1,
    to: 9999,
    color: '#52B12C',
  }
]
```

An example of this is here: https://apexcharts.com/javascript-chart-demos/treemap-charts/color-range/

Hope this helps!
