### ISSUE TITLE
Font not used when exporting to png, svg

### ISSUE THREAD

**Issue by patrickhener** [apexcharts/apexcharts.js#2166]
# Bug report

## Codepen
[Font Example - Codepen](https://codepen.io/patrickhener/pen/MWjLrdw)

## Explanation

- What is the behavior you expect?
I would expect the exported png to have the Universe Font I chost within the css file.

- What is happening instead?
Font gets replaced with a generic one

- What error message are you getting?
None

**Comment by filipe-damasceno** [comment]
I have the same problem here. set globally `chart: {fontFamily: 'dm sans'`.... Works in page view, but download PNG,SVG changes font.

**Comment by patrickhener** [comment]
Nope never.

**Comment by HoseinGhanbari** [comment]
Is there any plan/solution on fixing this issue?

**Comment by filipe-damasceno** [comment]
@HoseinGhanbari no solution so far.

**Comment by fakhamatia** [comment]
Any solution?

**Comment by ChamkhiAnas** [comment]
> 

did u find any solution for this problem brother ?

**Comment by ChamkhiAnas** [comment]
@fakhamatia  any solution ?

**Comment by dvdhoek** [comment]
Same issue here, any update if there will be a fix for this?

**Comment by Thimows** [comment]
Running into the same issue, any solution for this issue?
