### ISSUE TITLE
X-axis labels don't show the same values.

### ISSUE THREAD

**Issue by santiblanko** [apexcharts/apexcharts.js#217]
## Issue
X-axis labels are not printed when the value is same / duplicated

Codepen [this codepen](https://codepen.io/anon/pen/aQQeaV) 

## Explanation

- What is the behavior you expect?
Please see this fiddle to see my error in xaxis.
- What is happening instead?
I need the same value in the step.
- What error message are you getting?
I dont see errors.

**Comment by junedchhipa** [comment]
There is a property called `xaxis.labels.showDuplicates` which you should set to true to allow xaxis labels to show the same values.

```javascript
  xaxis: {
        labels: {
          showDuplicates: true,
          formatter: function() {
           return 1
         } 
      }
   }
```

**Comment by santiblanko** [comment]
Thanks!! Sorry for the false issue. 👍
