### ISSUE TITLE
Updating a hidden chart crashes on Firefox

### ISSUE THREAD

**Issue by rjimenezda** [apexcharts/apexcharts.js#2170]
# Bug report

## Codepen

https://codepen.io/rjimenezda/pen/gOwELLQ

## Explanation

- What is the behavior you expect?
I can safely update a chart even if it is not visible (on Chrome it works just fine)

- What is happening instead? 
Calling updateOptions on a chart that has display: none crashes on Firefox

- What error message are you getting?
```javascript
Uncaught (in promise) TypeError: e is null
    create https://cdn.jsdelivr.net/npm/apexcharts:6
    screenCTM https://cdn.jsdelivr.net/npm/apexcharts:6
    toParent https://cdn.jsdelivr.net/npm/apexcharts:6
    ungroup https://cdn.jsdelivr.net/npm/apexcharts:6
    each https://cdn.jsdelivr.net/npm/apexcharts:6
    ungroup https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:14
    <anonymous> pen.js:73
    EventListener.handleEvent* pen.js:71
```

I believe this might be related to this **9 year old** firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=756985

Also, I think it might be the same error as reported here: https://github.com/apexcharts/react-apexcharts/issues/234, but it has nothing to do with react, as the codepen shows.

**Comment by alejandroeclair** [comment]
i have this same issue in Firefox on Mac with react-apexcharts 1.3.7

**Comment by kimchristiansen** [comment]
Same with vue-apexcharts@1.6.0
I could solve the problem by adding a v-if around the parent tag:

<div v-if="hasData">
 <apexchart type="pie" width="380" :options="chartOptions" :series="chartData"></apexchart>
</div>

**Comment by NekuSakuraba** [comment]
I solved this issue by calling the apexcharts' destroy method once the component's cycle is over.

**Comment by mvtm-dn** [comment]
Same problem. Apexchart 3.22.3
