### ISSUE TITLE
Pie chart: legend colors incorrect

### ISSUE THREAD

**Issue by Pluuk** [apexcharts/apexcharts.js#2172]
# Bug report

## Codepen
https://codepen.io/DiesiteLuuk/pen/BaLbdjw

## Explanation

- What is the behavior you expect?
I expect that the dot in the legend for series-6 would be grey.
- What is happening instead?
The dot is the default color for this series index instead of grey
- What error message are you getting?
No error message

**Comment by junedchhipa** [comment]
Instead of `fill.colors`, use the `colors` property

```js
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "pie"
  },
  colors: ['#008ffb', '#00e396', '#feb019', '#ff4560', '#775dd0', '#9d9d9d'],
  series: [30, 40, 45, 50, 49, 60]
};
```
