### ISSUE TITLE
Display day of the month on X-axis, but full date in tooltip

### ISSUE THREAD

**Issue by lucavallin** [apexcharts/apexcharts.js#2174]
Hi, I would like to create a line chart where the X-axis represents the day of the month, but I should be able to display the full date on the tooltip. Is there already a way to do this? 

The chart currently uses unix timestamps on the X-axis, which I formatted to only render the day of the month. The two lines should be "in sync by day", but I want to have the full date available to show on the tooltip.
![image](https://user-images.githubusercontent.com/14332663/105152884-0b287980-5b08-11eb-86c6-b04d8c86be3b.png)

**Comment by dfiorini** [comment]
Can you share this tooltip ? It will be very useful, thanks
