### ISSUE TITLE
Lines in line charts not drawing

### ISSUE THREAD

**Issue by iamdanielp** [apexcharts/apexcharts.js#2175]
Hi,

I'm trying to create a line chart in my application. The chart is created and everything except the actual lines are drawn. I've tried with several examples from the docs and the site without any luck.

I found this Codepen that gives a good example of my problem:
https://codepen.io/junedchhipa/pen/zmbGPG

This example works fine when running in Codepen. But If I copy the code to my own application and run it, it won't draw the lines. If I change the chart type to "bar" everything works. I can download the chart as a PNG image and the image will show the lines. I've also tried several other chart types and they all work. I've tested in several browsers without any difference so it's not browser specific.

So obviously the problem only seems to occur in my environment. If no charts was working it would have been easier to suspect a problem with a polyfill or some weird global override. But for now Apexcharts works like a charm, except the line chart.

To exclude any potential problems with the actual canvas drawing I've tried Chart.js which works. I also tried creating a custom canvas and drew lines on it which also works.

I've spent quite a lot of time trying to figure this out but without luck so I'm getting desperate.

Anyone here have any idea what might be causing this?

**Comment by isameersanjeewe** [comment]
This is a bug in apex charts, If you load the chart in bar and then update the state to line. You will only see markers, wont see the lines. There's no fix for this from the chart library in my research. We need to somehow refresh or use the bar and line chart option separately.  I have tried everything and this is the only proof I could derive.

**Comment by oknatyrtubiking** [comment]
Anyone find the fix ?
