### ISSUE TITLE
Question: How to expand a specific series in the pie chart?

### ISSUE THREAD

**Issue by lakarpusky** [apexcharts/apexcharts.js#2177]
Hi guys

I am trying to show a particular series in a pie chart expand without using the click just like the image below:
![image](https://user-images.githubusercontent.com/25494196/105523696-b6723380-5cac-11eb-82c9-39571a4dc1b7.png)

There is a particular setup that can help me to: 
1. Keep a series always expanded?
2. Modify the size of the expanded area?

Any help will be appreciated.
Regards.

**Comment by marcusmaialima** [comment]
Hi @gabomontero89.

By default it expands when clicking on any chart data. Take a look at the documentation for the link:

https://apexcharts.com/angular-chart-demos/pie-charts/simple-pie/

I hope I helped in your question :)

**Comment by gabomontero89** [comment]
> Hi @gabomontero89.
> 
> By default it expands when clicking on any chart data. Take a look at the documentation for the link:
> 
> https://apexcharts.com/angular-chart-demos/pie-charts/simple-pie/
> 
> I hope I helped in your question :)

Hi @marcusmaialima
Thanks for your reply.

I am aware of the expand on click, but what I need is to get the series always expanded without using the click.

**Comment by ar-lk** [comment]
@lakarpusky Still needed to know how, try

chart: {
  type: 'pie',
  events: {
    animationEnd: function(ctx) {
      ctx.toggleDataPointSelection(2)
    }
  }
}

**Comment by lakarpusky** [comment]
> @lakarpusky Still needed to know how, try
> 
> ```
> chart: {
>     type: 'pie',
>     events: {
>        animationEnd: function(ctx) {
>           ctx.toggleDataPointSelection(2)
>        }
>      }
> }
> ```
> 
> [more info](https://github.com/apexcharts/apexcharts.js/issues/16)
Thank you @ar-lk :+1:

**Comment by lakarpusky** [comment]
solved!

**Comment by canblt** [comment]
the first part of the question has been solved, but what about the second question
2. Modify the size of the expanded area?
