### ISSUE TITLE
Mixing Scatter and Lines series breaks chart 

### ISSUE THREAD

**Issue by Genarito** [apexcharts/apexcharts.js#2178]
# Bug report

## Codepen

[Codepen](https://codepen.io/Genarito/pen/gOwJWpG)

When mixes Scatter series with Line series it only works when there's only one Scatter serie. If you add another one the Line breaks showing its values and also the tooltip stop working for the extra Scatter plot series (in the case of my CodePen the one named `Points 2`). If you click quickly to hide/show the legends of that serie the points appear in chart for less than a second

## Explanation

- What is the behavior you expect? Show all the Scatter series correctly with the Line one
- What is happening instead? Showing only one scatter and breaking the tooltip of the extra Scatter series
- What error message are you getting? In my own console (but not in CodePen, I don't know why) it's throwing:

> Uncaught TypeError: n[e] is undefined

On `apexcharts.common.js:6:245715`

**Comment by Genarito** [comment]
It was not a bug, it was a misunderstanding on my part about the `markers.size` option: I was setting a fixed value of `[6, 0]` so it hid some scatter values and shows the dots of the Line chart.

I fixed it generating a marker size array dinamically from the number of series I had, setting the Line chart size to 0 always

**Comment by mtuzenko** [comment]
In my case, by setting marker size to 0 was creating an odd behaviour of shared tooltip (when hovering on line tooltip was appearing in the corner). The solution/hack was to set `shared: false` `intersect: true` and in my "marker size adding function" setting line marker size to 0.00001.
