### ISSUE TITLE
Add a full dark theme

### ISSUE THREAD

**Issue by steebchen** [apexcharts/apexcharts.js#218]
For dark themes, there's the `tooltip.theme` option. It looks nice, but it would be very cool if the whole thing could have a dark mode.

![selection_999 482](https://user-images.githubusercontent.com/5013932/49320673-3eac8200-f503-11e8-957b-c74c82a37a3f.jpg)

With some minor tweaks like setting the text color to white and adding dark colors to the menu, it could look like this

![selection_999 484](https://user-images.githubusercontent.com/5013932/49320772-d1e5b780-f503-11e8-8a26-931039078470.jpg)

I would suggest to use a top-level `theme` (or `chart.theme`) option, add a class `dark` to `.apexcharts-canvas` and style all other elements with css selectors accordingly.

I could send a PR for this if my proposal seems like a good idea (although not in the next few days).

BTW, huge thanks to this project. The charts are so clean and even mobile touch "swiping" of the charts always renders the correct tooltip. This is so cool!

**Comment by junedchhipa** [comment]
Thanks for the kind words!
Sure, there is already a property called `theme` in the main configuration - https://apexcharts.com/docs/options/theme/

Maybe we can add `theme.mode: 'light' / 'dark'` in the same property and carry on that.

**Comment by elbojoloco** [comment]
Has this been released yet? Looking for an easy way to switch dark/light themes aswell, using with Vuetify atm.

**Comment by junedchhipa** [comment]
Not released yet, but coming soon.

**Comment by pilotaids** [comment]
@junedchhipa any chance you can explain how to modify the charts to show properly when using vuetify dark mode?
I have the problem @steebchen shows in the first pic, but I cannot find the proper options I need to modify to create the layout in the second picture above (where you can see the text).
Thank you in advance

**Comment by steebchen** [comment]
I abandoned this project so I'm not sure but I'm sure you can use:
```css
svg text {
	fill: white;
}
```

**Comment by junedchhipa** [comment]
@steebchen May I know the reason why you abandoned?
@pilotaids What have you tried to change the theme? Did you updated this option [theme.mode](https://apexcharts.com/docs/options/theme/#mode)?

**Comment by steebchen** [comment]
I meant I abandoned my own project, not using apexcharts (although that results in it). In general, it seems I'm quickly transitioning into Angular (100% Typescript, powerful testing, DI, intellisense, ...).

**Comment by junedchhipa** [comment]
Ah! thanks for clarifying!
Good luck with Angular. I'm sure you'll enjoy it too along with ng-apexcharts ;)

**Comment by steebchen** [comment]
Ah well, good to know ;) Will definitely use it when I need charts in Angular!

**Comment by bubuamu** [comment]
i want to add background image on the chart. Do anyone know how

**Comment by junedchhipa** [comment]
@bubuamu Please create a new ticket for it.

**Comment by sorxrob** [comment]
You can now achieve this by using the dark property inside tooltop property.

```javascript
tooltip: {
   theme: 'dark',
}
```
https://i.imgur.com/RieNEzl.png

**Comment by chitgoks** [comment]
![apex](https://user-images.githubusercontent.com/3955470/79036096-51ef5780-7bf7-11ea-82b5-f88b1520e823.png)

question. how come the background for the charts is not dark gray? i didnt set any background color either.

the dark gray color below is a material table in dark mode which is correct.

**Comment by kamilcglr** [comment]
> ![apex](https://user-images.githubusercontent.com/3955470/79036096-51ef5780-7bf7-11ea-82b5-f88b1520e823.png)
> 
> question. how come the background for the charts is not dark gray? i didnt set any background color either.
> 
> the dark gray color below is a material table in dark mode which is correct.

Hello, did you find a solution ?

**Comment by chitgoks** [comment]
> > ![apex](https://user-images.githubusercontent.com/3955470/79036096-51ef5780-7bf7-11ea-82b5-f88b1520e823.png)
> > question. how come the background for the charts is not dark gray? i didnt set any background color either.
> > the dark gray color below is a material table in dark mode which is correct.
> 
> Hello, did you find a solution ?

no. not going to. this is a personal project anyway so ill just wait for them to fix it.

**Comment by junedchhipa** [comment]
I have changed the default dark color to `#424242`

**Comment by kamilcglr** [comment]
> I have changed the default dark color to `#424242`

Ok thank you very much for the quick response. 
But, is there any way to change this color ourselves? 

I would like to put it transparent so that the background color is the same as the vuetify color.
It doesn't work when I do : 
```
chart: {
            background: 'transparent'.
 }
```

Anyway, great job on that library.

**Comment by lkovesdi** [comment]
Yeah is there a way to remove the dark mode background? I have my charts on dark already.
<img width="310" alt="Screen Shot 2020-04-28 at 3 24 26 PM" src="https://user-images.githubusercontent.com/16272957/80543722-60ae6c00-8964-11ea-9355-3882178fcdfa.png">

**Comment by sauterl** [comment]
For those that came here, like myself or the previous comment, put 

```div.apexcharts-canvas.apexcharts-theme-dark {
  background: transparent !important;
}
```

in your css file somewhere (in case of an angular app, `style.css`).

**Comment by hothvictor** [comment]
`svg.apexcharts-svg {
  background: transparent !important;
}`

**Comment by dmytrostrembetskyi** [comment]
you can achieve this by this
```
chart: {
    background: 'rgba(0, 0, 0, 0)'
}
```

**Comment by YousufAhmedGDS** [comment]
what should we do If there is both theme dark and light what should we do for text color?

**Comment by vinosamari** [comment]
This hack works with vuetify to show white text in dark mode. Place it inside the `app.vue` file so that it's not a scoped style.
```css
.theme--dark svg text {
  fill: white !important;
}
.theme--dark .apexcharts-legend-text {
  color: white !important;
  fill: white !important;
}
```

**Comment by surister** [comment]
> This hack works with vuetify to show white text in dark mode. Place it inside the `app.vue` file so that it's not a scoped style.
> 
> ```css
> .theme--dark svg text {
>   fill: white !important;
> }
> .theme--dark .apexcharts-legend-text {
>   color: white !important;
>   fill: white !important;
> }
> ```

Did not work for me for  `"vuetify": "^3.0.0"` , the actual class name is `.v-theme--dark`
