### ISSUE TITLE
Type `area` doesn't properly display the filled area if any data is `null` in a `datetime` chart

### ISSUE THREAD

**Issue by RomRider** [apexcharts/apexcharts.js#2180]
# Bug report

## Codepen

https://codepen.io/RomRider/pen/mdrZPxB

## Explanation

On a `datetime` chart, if smoothing is enabled and the serie type is `area`, if any of the data is `null` in the timeserie, there is a glitch in the filled area (it seems misaligned by some pixels whenever it has a point to display) and also the initial animation is broken.

![image](https://user-images.githubusercontent.com/21064206/105639706-123de780-5e7a-11eb-9810-9abbe5220066.png)

It works well if you change the line type to `straight` or replace the `null` entry in the dataset with a real value.
* With `straight`:
  ![image](https://user-images.githubusercontent.com/21064206/105639744-40232c00-5e7a-11eb-93dd-ddba9364d4a4.png)

* Without `null` in the dataset:
  ![image](https://user-images.githubusercontent.com/21064206/105639773-6052eb00-5e7a-11eb-98c6-12beb103aad2.png)

No error message displayed.

**Comment by RomRider** [comment]
This is still an issue

**Comment by rosco54** [comment]
This issue is fixed in 3.49.0 and above.
