### ISSUE TITLE
Brush does not work for category type of axis

### ISSUE THREAD

**Issue by amandaluniz** [apexcharts/apexcharts.js#2183]
# Bug report

When trying to create a brush chart on category type of X axis, the selection and zooming just doesn't come up.

## Explanation

- What is the behavior you expect?
I would expect the brush to behave the same way it does for datetime type of series. I would also expect the brush to work on Y axis, since I want to accomplish something like the following.

<img width="533" alt="Screenshot 2021-01-25 at 12 27 51" src="https://user-images.githubusercontent.com/4599753/105705915-c25a3180-5f08-11eb-81cd-b56ca3cedb61.png">

- What is happening instead?
The brush doesn't allow selection and the target chart does not get "zoomed in".

- What error message are you getting?
No error, just doesn't work.

**Comment by amandaluniz** [comment]
I would still like this feature included

**Comment by harshil-aivid** [comment]
Any hacks to achieve this thing ?
