### ISSUE TITLE
DataLabels background not working inside Heatmaps

### ISSUE THREAD

**Issue by lukaszahorec** [apexcharts/apexcharts.js#2188]
# Bug report

Hi, 
background in Datalabels inside Heatmaps not working. If you have white font color and low value in data it is not readable. [codepen](https://codepen.io/luk-z-horec/pen/WNoNwdO)

**Comment by junedchhipa** [comment]
One solution is to provide a function for `dataLabels.style.colors` array, so the text color can be tweaked based on the value.

```javascript
dataLabels: {
  style: {
    colors: [
      function(opts) {
        return opts.series[opts.seriesIndex][opts.dataPointIndex] > 50
          ? '#333'
          : '#fff'
      }
    ]
  }
}
```
