### ISSUE TITLE
Make one grid line wider

### ISSUE THREAD

**Issue by Gollam** [apexcharts/apexcharts.js#2195]
**Is your feature request related to a problem? Please describe.**	
I cannot easily see where is the 0 grid line in a given chart.

**Describe the solution you'd like**	
It would be great if the 0 grid line could somehow be made more wider than the others, or to be able to configure a different color for it, etc. This way it could be easily seen for example if the temperature went below zero.

**Comment by Gollam** [comment]
For example here, the 0 grid line is a bit thicker than the others:

![image](https://user-images.githubusercontent.com/765342/106477981-0a4cfb80-64a9-11eb-8b6e-1a47cef3d453.png)

**Comment by junedchhipa** [comment]
You can add an annotation to the chart to distinguish the 0 line

```javascript
annotations: {
  yaxis: [
    {
      y: 0,
      borderColor: '#333'
    }
  ]
}
```
