### ISSUE TITLE
Candlestick x-axis recalculate barwidth on selection / zoom 

### ISSUE THREAD

**Issue by aon108** [apexcharts/apexcharts.js#2197]
When I load a large data set (400 points) into the candlestick chart using category x-axis, then use the selection / zoom tool to view only a few datapoints - the barwidth remains the same size as when it was zoomed out. As per below image.

![image](https://user-images.githubusercontent.com/2944604/106638489-d4c51280-657b-11eb-82e4-41e9fc665bc9.png)

Other charting platforms automatically adjust the width of the bars when a different number of datapoints are visible.

I have tried my best to figure out how the charting engine works, and i think it has something to do with the barwidth is being calculated by the total number of datapoints rather that `this.barCtx.visibleItems`

**Comment by keqhash** [comment]
Any update on this?

**Comment by nojomyth-dev** [comment]
Push

**Comment by vstefan22** [comment]
Did you solve the problem, I have the same issue

**Comment by marcuscastelo** [comment]
Same problem here
