### ISSUE TITLE
Display Column chart in percentage but not Stacked

### ISSUE THREAD

**Issue by shukla2103** [apexcharts/apexcharts.js#2198]
![image](https://user-images.githubusercontent.com/31451584/106640833-89772800-65ac-11eb-8503-16dd2f4f61a1.png)
The above image is taken from an example I want the chart should not be stacked .

I want like this but it is not showing percentage when stacked=false

![image](https://user-images.githubusercontent.com/31451584/106641256-04d8d980-65ad-11eb-98da-534950063bcc.png)

Please help me how to achieve it. I explored the documentation but couldn't find something

**Comment by junedchhipa** [comment]
You have to change the data-labels formatter.

```javascript
dataLabels: {
  formatter: function(val) {
    return val + '%'
  }
}
```

**Comment by shukla2103** [comment]
> You have to change the data-labels formatter.
> 
> ```js
> dataLabels: {
>   formatter: function(val) {
>     return val + '%'
>   }
> }
> ```

This is only appending the percentage.
My requirement is percentage should be calculated like above 1st chart calculates 65% and so on  hence  display like the second chart

**Comment by junedchhipa** [comment]
Sorry, that is not available in a normal bar chart.
You will have to find the percentages and create the series in percent values.
and then apply data labels with percentage formatter.

**Comment by shukla2103** [comment]
Thanks :)
