### ISSUE TITLE
dataPointSelection/dataPointMouseEnter/selection event not working for Zoomable Timeseries

### ISSUE THREAD

**Issue by michalpietruszka** [apexcharts/apexcharts.js#220]
I use an example from repository of zoomable timeseries chart, and I want to know with data point user clicked. Any of events dataPointSelection/dataPointMouseEnter/selection doesn;t work (nothing is happen).
I attached my code below:
```

<body>
  <div id="chart">

  </div>


  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
  <script src="../../assets/irregular-data-series.js"></script>

  <script>
    var ts2 = 1484418600000;
    var dates = [];
    var spikes = [5, -5, 3, -3, 8, -8]
    for (var i = 0; i < 120; i++) {
      ts2 = ts2 + 86400000;
      var innerArr = [ts2, dataSeries[1][i].value];
      dates.push(innerArr)
    }
	console.log(dates[0])

    var options = {
      chart: {
	   locales: [{
      "name": "en",
      "options": {
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "shortMonths": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        "shortDays": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        "toolbar": {
            "exportToSVG": "Download SVG",
            "exportToPNG": "Download PNG",
            "menu": "Menu",
            "selection": "Selection",
            "selectionZoom": "Selection Zoom",
            "zoomIn": "fdsZoom In",
            "zoomOut": "Zoom Out",
            "pan": "Panning",
            "reset": "Reset Zoom"
        }
      }
    }],
        type: 'area',
        stacked: false,
        height: 350,
        zoom: {
          type: 'x',
          enabled: true
        },
        toolbar: {
          autoSelected: 'zoom'
        },
		events: {
     selection: function(chartContext, { xaxis, yaxis }) {
      console.log(xaxis);
	   console.log(yaxis);
    }
  }
      },
      plotOptions: {
        line: {
          curve: 'smooth',
        }
      },
      dataLabels: {
        enabled: false
      },
      series: [{
        name: 'name',
        data: dates
      }],
      markers: {
        size: 0,
        style: 'full',
      },
      //colors: ['#0165fc'],
      title: {
        text: 'name1',
        align: 'left'
      },
      fill: {
        gradient: {
          enabled: true,
          shadeIntensity: 1,
          inverseColors: false,
          opacityFrom: 0.5,
          opacityTo: 0,
          stops: [0, 90, 100]
        },
      },
      yaxis: {
        min: 20000000,
        max: 250000000,
        labels: {
          formatter: function (val) {
            return (val / 1000000).toFixed(0);
          },
        },
        title: {
          text: 'number'
        },
      },
      xaxis: {
        type: 'datetime',
      },

      tooltip: {
        shared: false,
        y: {
          formatter: function (val) {
            return (val / 1000000).toFixed(0)
          }
        }
      }
    }

    var chart = new ApexCharts(
      document.querySelector("#chart"),
      options
    );

    chart.render();
	
	function rt()
  {
  }
  </script>
</body>
```
Thanks for your help!

**Comment by junedchhipa** [comment]
Datapoint events works when markers size is greater than 0

When the market’s size is 0, no datapoint is drawn on the chart, and hence it is difficult to track the position in this case.

I will keep this issue open and try to implement a better way to fire event in such cases.

**Comment by michalpietruszka** [comment]
I see, but when I increase a marker size to 1, this events still doesnt
work for me.
Do you have any tips why?

pon., 3.12.2018, 10:04 użytkownik Juned Chhipa <notifications@github.com>
napisał:

**Comment by junedchhipa** [comment]
Oh! 
Please create a codepen demo so that I can reproduce it easily

**Comment by michalpietruszka** [comment]
Ok, great:)
At the end I need to get start and end date of selection (period of time)
and handle click specific value.
Code below:
https://codepen.io/michalpietruszka/pen/NEJmGy?editors=1111

pon., 3 gru 2018 o 16:02 Juned Chhipa <notifications@github.com> napisał(a):

**Comment by junedchhipa** [comment]
Sorry for asking you to create demo again. You already had the code in the first comment which I missed completely.

I will look soon.

**Comment by michalpietruszka** [comment]
To sum up,
1. There is no tool to get the date range. When we can expect it?
 2. Single point selection should work for size> 0, but this doesnt work in
my code

pon., 3 gru 2018 o 19:11 Juned Chhipa <notifications@github.com> napisał(a):

**Comment by junedchhipa** [comment]
1. Yes, the dragged event will provide the range (start/end). Expect it in the next release (next week probably)
2. Didn’t get a chance to test it. But you’re right, dataPointSelection for markers.size > 0 should work

**Comment by junedchhipa** [comment]
Regarding dataPointSelection, my bad - didn't document it clearly.
You have to set
```javascript
tooltip: {
  intersect: true,
  shared: false
},
markers: {
  size: 4
}
```

Just updated the docs stating the same

**Comment by michalpietruszka** [comment]
Yeah,it works for example:) But don't work in my codepen, something went
wrong in my case because markers even don't show up.
Thanks, and waiting for dragged event - it will be cool

wt., 4 gru 2018 o 15:50 Juned Chhipa <notifications@github.com> napisał(a):

**Comment by michalpietruszka** [comment]
Ok, I fixed my case - now I am only waiting for 'dragged':)

wt., 4 gru 2018 o 19:31 Michał Pietruszka <michalpietruszka123@gmail.com>
napisał(a):

**Comment by junedchhipa** [comment]
Just realized that the `zooming` and `panning` by default prevents the `dragged` event to be fired correctly.

Maybe you can try the [selection](https://apexcharts.com/docs/options/chart/events/#selection) event which will also provide the min/max of the x-axis.

Example - https://apexcharts.com/javascript-chart-demos/area-charts/github-style/

**Comment by junedchhipa** [comment]
Closing this as couldn’t add the event on top of zooming/panning
