### ISSUE TITLE
WITH REFERENCE TO #2198 

### ISSUE THREAD

**Issue by shukla2103** [apexcharts/apexcharts.js#2200]
> You have to change the data-labels formatter.
> 
> ```js
> dataLabels: {
>   formatter: function(val) {
>     return val + '%'
>   }
> }
> ```

This is only appending the percentage.
My requirement is percentage should be calculated like above 1st chart calculates 65% and so on  hence  display like the second chart.

Its not about how to display percentage sign but about percentage calculation as happens in the first stacked chart. 

![image](https://user-images.githubusercontent.com/31451584/106646122-4f5d5480-65b3-11eb-9aa7-6102495c55cd.png)
 You can see its just append the % sign but does not show the percentage as in stacked one

_Originally posted by @shukla2103 in https://github.com/apexcharts/apexcharts.js/issues/2198#issuecomment-771862362

#2198

**Comment by junedchhipa** [comment]
Please continue on that same thread.
