### ISSUE TITLE
HTML for tooltip is rendering as string

### ISSUE THREAD

**Issue by bibekrimal** [apexcharts/apexcharts.js#2202]
# Bug report
**HTML for tooltip is rendering as string.**

## Codepen
https://codepen.io/bibekr/pen/xxRwGYp

## Explanation
After the last update, the tooltip html as shown in the codepen coming from x-axis categories is returned as string.
with the use of previous version it looks like this https://tppr.me/CRBk3 and that is the behavior required. This bug came from **version 3.23.1**

**Comment by RomRider** [comment]
Same for legend also with 3.24.0. Used to work with 3.23.1
![image](https://user-images.githubusercontent.com/21064206/107236176-bb154680-6a25-11eb-81c6-cb80489b6ee7.png)

**Comment by junedchhipa** [comment]
Re-opening this due to Cross-site Scripting (XSS) - DOM vulnerability

**Comment by jontelov** [comment]
Facing this issue with 3.27.1
![html_string_modified](https://user-images.githubusercontent.com/30627018/121162454-99eb2800-c856-11eb-9039-7e9408a1b564.png)

**Comment by tale** [comment]
Hey, could an alternative solution be introducing an optional flag that allows you to bypass the DOM sanitization?
That way the default behaviour is still safe, but the option to supply direct HTML is possible if necessary.

**Comment by jontelov** [comment]
Sure, will try this

**Comment by junedchhipa** [comment]
HTML tooltip will not be supported due to XSS vulnerability.

**Comment by RomRider** [comment]
Can you at least make this an opt-in feature with explicit warning?
