### ISSUE TITLE
DataLabel is off by 1 hour vs xAxis for Line Chart when using DateTime type

### ISSUE THREAD

**Issue by PrzemyslawKlys** [apexcharts/apexcharts.js#2208]
# Bug report

## Codepen

https://codepen.io/MadBoyEvo/pen/JjbYzoZ

## Explanation

- What is the behavior you expect? 

X-Axis should match highlighting dates

- What is happening instead?

When you check the chart - the X-axis says, for example, 5th of February - but when you highlight points on chart the day is 4th of February. 

Also:

- categories: ["02.04.2021", "02.05.2021", "02.06.2021", "02.09.2021"]

![image](https://user-images.githubusercontent.com/15063294/106872739-ed484080-66d3-11eb-8eaf-2f8dec8cdceb.png)

![image](https://user-images.githubusercontent.com/15063294/106873194-80817600-66d4-11eb-8fbe-3cf1a5e68c3f.png)

- What error message are you getting?

No error message

**Comment by PrzemyslawKlys** [comment]
It seems that the data label problem comes from the time being exactly 1 hour off.

https://codepen.io/MadBoyEvo/pen/xxReVve

![image](https://user-images.githubusercontent.com/15063294/111229711-af014380-85e6-11eb-88e8-8a14569a13bf.png)

Once you force the DateTime to be +1 hour everything works correctly.

```
"xaxis": {
        "type": "datetime",
        "categories": ["2021-03-16 01:00:00", "2021-03-17 01:00:00", "2021-03-18 01:00:00", "2021-03-19 01:00:00", "2021-03-20 01:00:00", "2021-03-21 01:00:00", "2021-03-22 01:00:00", "2021-03-23 01:00:00", "2021-03-24 01:00:00"]
},
```
Is this by design? Or a bug?

**Comment by PrzemyslawKlys** [comment]
Maybe don't close it - if not fixed?

**Comment by PrzemyslawKlys** [comment]
Not fixed still. Please do not close.

**Comment by PrzemyslawKlys** [comment]
I'm still active. Do not close ;p Maybe some day you little bot - this will get fixed.

**Comment by junedchhipa** [comment]
Not a bug. 
You should provide the date values in ISO format
```
categories: ['2021-02-04', '2021-02-05', '2021-02-06', '2021-02-09']
```

Here's the updated [codepen](https://codepen.io/apexcharts/pen/VwMorLo)
