### ISSUE TITLE
Heatmap Y axis annotation issues

### ISSUE THREAD

**Issue by andy3blender** [apexcharts/apexcharts.js#2209]
Hi there,
I discovered this library and have been testing it these days and it really looks great to me.

My problem is that I have tried to create annotations but the Y axis value is showing in a different place than the one trying to plot. With the X axis I have had no problems.

<img width="942" alt="HeatError" src="https://user-images.githubusercontent.com/73072602/106924451-14574000-66dd-11eb-805b-5a4537dfe9eb.png">

Please your help maybe I am making a mistake in the code.

I attach the codepen: https://codepen.io/andy3blender/pen/PoboBYW

Thank you in advance for your help.

**Comment by catarina-57502** [comment]
If anyone is still looking for a solution to this problem, I found that defining minimum and maximum values on the y-axis can work:

```
yaxis: {
        min: 1,
        max: 5,
} 
```
With this, we can put values from 1 to 5 in the y-point annotation to be in the expected heatmap square.
