### ISSUE TITLE
column width bug when colors are functions

### ISSUE THREAD

**Issue by RomRider** [apexcharts/apexcharts.js#2213]
# Bug report

## Codepen

https://codepen.io/RomRider/pen/NWbNbdO

## Explanation

- What is the behavior you expect?

When using color functions to determine the color of a column vs using a plain color string, only the color should change.
In the codepen:
--> top chart: using color functions, width is weird
--> bottom chart: using plain color, width is normal

![image](https://user-images.githubusercontent.com/21064206/107122013-b91c7d80-6895-11eb-8cb5-997dc2b9c665.png)

- What is happening instead?

When using plain color, the columns widths are fine, when using color functions, the width of each bar gets reduced

- What error message are you getting?

None

**Comment by junedchhipa** [comment]
Breaks since v3.15.3.
Will be looked into soon.

**Comment by junedchhipa** [comment]
As a workaround, set stroke.width to 0
```
stroke: {
  width: 0
}
```
