### ISSUE TITLE
HTML no longer parsed in tooltip formatter

### ISSUE THREAD

**Issue by Bilge** [apexcharts/apexcharts.js#2214]
# Bug report

## Codepen

https://codepen.io/bilge-the-encoder/pen/YzpqLPo

## Explanation

In previous versions, HTML was processed as HTML. Now, it appears to be escaped and thus printed literally. This is a breaking change and not desired. Broken since `3.24.0`.

![image](https://user-images.githubusercontent.com/470626/107142957-25e15780-692a-11eb-9a86-36b8ce38157c.png)

**Comment by junedchhipa** [comment]
Duplicate of #2202

**Comment by junedchhipa** [comment]
Re-opening this due to Cross-site Scripting (XSS) - DOM vulnerability

**Comment by junedchhipa** [comment]
HTML parsing will not be supported due to XSS vulnerability.

**Comment by Bilge** [comment]
LOL. I'm glad I abandoned this library.
