### ISSUE TITLE
Missing Series Value Does not Display DataLabels 

### ISSUE THREAD

**Issue by gaurav2103** [apexcharts/apexcharts.js#2215]
I am using the 100% Stacked Column Chart.
For Some Years or the week, the Value is missing I want neither the data nor data labels display onto the chart and the chart to get adjusted(i.e. the year which has value should be displayed).

![image](https://user-images.githubusercontent.com/31451584/107177618-3d871180-69f8-11eb-8b68-adb9add1487c.png)

in the above image 2011 Q2 value is missing and I want that empty column should not be displayed and the chart gets adjusted and 2011 Q3 comes at that place.

**Comment by shukla2103** [comment]
@junedchhipa, please help
