### ISSUE TITLE
hideOverlappingLabels option on datalabels

### ISSUE THREAD

**Issue by Reluigi** [apexcharts/apexcharts.js#2219]
I'm trying to hide labels that are overlapping on each others, but I can't find a way to do it.	
Is it possible to add an option similar to the hideOverlappingLabels in xaxis?

Also, some of my datalabels are written outside the graph, how do I prevent this from happening? Is it something to be implemented?

Thank you!

**Comment by ferogot** [comment]
+1

I have same problem, this happens on timeline chart with options 

```
  chart: {
    type: 'rangeBar',
  },
  xaxis: {
    type: 'datetime',
  },
  plotOptions: {
    bar: {
      horizontal: true,
      rangeBarGroupRows: true,
    }
  },
  dataLabels: {
    enabled: true,
  }
```

In this case dataLabels ugly overlap eachover when it's series hided (after zoom or pan).

Seems like it can't fixed by any options, need help.

**Comment by ferogot** [comment]
there is [codepen](https://codepen.io/ferogot/pen/GRWxXBx). After some zoom in you will see overlapping.

**Comment by AFICION007** [comment]
Hey folks, this is an important issue and needs to be solved soon. I am also facing the same problem. Why can we have hideOverlappingLabels in dataLabels?? Or is there a property I am unaware of?
I am attaching the picture of my chart, the bottom 3 series' dataLabels are completely overlapping. 
Can somebody help please?

<img width="1237" alt="Screenshot 2024-12-03 at 11 06 36 AM" src="https://github.com/user-attachments/assets/63105dd2-e5b1-4ad3-86af-469aafd36134">

**Comment by 313ava** [comment]
I have same problem with large amount of data.
