### ISSUE TITLE
Expose svgUrl and imgURI as outputfunction for reuse in jPDF

### ISSUE THREAD

**Issue by alexkleinwaechter** [apexcharts/apexcharts.js#222]
Hi,
we need to get your fabulous charts together with other data in a pdf file. It would be nice to have your export function for downloading the chart accessable in javascript. 
I found this fiddle for another charting solution: http://jsfiddle.net/canvasjs/cm1qyk2L/

If you could expose svgUrl and imgURI out of your "exportToSVG" and "exportToPng" functions in your API it would be really great!

Best regards,
Alex

**Comment by travisbotello** [comment]
Good idea...I'd like to use these functions for an overview page to give a short preview of each chart before entering detail page with interactive features.

**Comment by junedchhipa** [comment]
`svgUrl()` doesn't works as expected.
So, going to provide a new method `dataURI()` which will be easier to integrate with jsPDF
