### ISSUE TITLE
Column stacking breaks when passing in data outside of temporal range

### ISSUE THREAD

**Issue by danbramall** [apexcharts/apexcharts.js#2222]
When plotting values on stacked bar chart with a datetime x axis, using a min and max x axis range, stacking of series breaks when the data passed in falls outside the min/max date range.

You can see the issue on this Codepen: [https://codepen.io/danb1/pen/JjbbXaj](https://codepen.io/danb1/pen/JjbbXaj) — it works fine initially but when you uncomment the first data object you see that the columns no longer stack correctly.

- What is the behavior you expect?

I expect that if a data object is passed to Apex which falls outside of the min/max x axis range it should not impact the rendering of the data that falls within range - effectively it should be silently ignored.

- What is happening instead?

When an object is passed into the data object which contains a date that is earlier than the min x axis range, it breaks the stacking of data that falls within range.

- What error message are you getting?

There are no error messages, just the stacking of the columns breaks.

**Comment by JDNik** [comment]
I have same problem. Have you solve this problem ?
