### ISSUE TITLE
global.labels undefined on datetime

### ISSUE THREAD

**Issue by Blooderis** [apexcharts/apexcharts.js#2223]
In custom tooltips I have problem with w.globals.labels[dataPointIndex]
This works only for first 6 labels.
So its works for
w.globals.labels[0]
w.globals.labels[1]
w.globals.labels[2]
w.globals.labels[3]
w.globals.labels[4]
w.globals.labels[5]

But if I have index more than 5 so Im getting **undefined** value.
This problem is only if I have label format **datetime**

**Comment by junedchhipa** [comment]
Can you create a Codepen so the issue can be reproduced easily?

**Comment by Blooderis** [comment]
> Can you create a Codepen so the issue can be reproduced easily?

Dear
Here is Codepen
https://codepen.io/blooderis/pen/rNWWoxW

**Comment by Blooderis** [comment]
still not fixed?
