### ISSUE TITLE
Legend hover event

### ISSUE THREAD

**Issue by dmitrymaslov99** [apexcharts/apexcharts.js#2225]
Is it possible to handle an event when hovering over a chart legend?
<img width="233" alt="Снимок экрана 2021-02-12 в 00 01 29" src="https://user-images.githubusercontent.com/36110676/107698338-76a7d600-6cc5-11eb-94cf-1261eaf76c2d.png">

**Comment by Loque18** [comment]
did u find a solution ?

**Comment by dmitrymaslov99** [comment]
Not

**Comment by Loque18** [comment]
> Not
for anyone else struggling with this issue here is a parcial solution I found, the only problem left is that access to chart data needs to be done manually 
```
const elms = document.querySelectorAll('.apexcharts-legend-series');

const elmsArr = Array.from( elms );

elmsArr.map( (elm, i) => {
    elm.addEventListener('mouseenter', e => {
        const seriesname = elm.getAttribute('seriesname').replace(/x/g, " ");

    });                
});
```
