### ISSUE TITLE
Click event returns -1 for dataPointIndex and seriesIndex

### ISSUE THREAD

**Issue by szydan** [apexcharts/apexcharts.js#2230]
# Bug report
 In below codepen I have a simple piechart with click event 
 When I click on any segment of the piechart 
 the **dataPointIndex** and **seriesIndex** are always -1
 
 tested on version 3.25.0
 
https://codepen.io/szydan/pen/abBJWXQ

## Explanation

I would expect that the the values would be different depends on which segment on the pie you click

**Comment by vessivanov** [comment]
I have the same issue with area chart, but only on IOS app. I trigger the click event on my chart and almost everytime the value of dataPointIndex is -1. On safari, chrome or android app the the value of dataPointIndex works properly.

```
events: {
  click: function(event, chartContext, config) {
    const dp = config.dataPointIndex
    console.log(dp) // -1
  }
}
```
