### ISSUE TITLE
Toolbar is not shown when there are no data

### ISSUE THREAD

**Issue by gdenhez42** [apexcharts/apexcharts.js#2237]
When the series all contain 0 data, the toolbar disappear. This is an issue for us since our toolbar contains custom icons like a refresh. Is it possible to have at least an option that would make the toolbar appear no matter what?

**Comment by amitmittal** [comment]
This is a real problem. There must be an option to show toolbar custom icons even if there is no data in chart. Something like this: 
![image](https://user-images.githubusercontent.com/5319694/117945068-95048880-b32b-11eb-93ed-0251933799d9.png)

**Comment by Madushankumarasiri** [comment]
This issue still exists

**Comment by Brandon-Ballard25** [comment]
It would be wonderful to be able to keep it

**Comment by fabianboerner** [comment]
This is still the case?

**Comment by Brandon-Ballard25** [comment]
Yes

**Comment by Brandon-Ballard25** [comment]
> This is still the case?

Yes

**Comment by RafaelCENG** [comment]
bump

**Comment by bglasgo** [comment]
I had this issue today, and my workaround for this was to add a check for my data before it gets loaded into the series array.  If I ask for a particular time range from my database where no readings were taken, I may get an empty result.  So if it is empty, add two data points for the start and end timestamps i was trying to use, with null values, or whatever value may be suited to you as the y value, to each series array.  null y values will show up as NaN and not draw a line, but you can use 0 to have a line at 0 if you want.  This gives the chart something to use to keep the x axis showing the range we would expect, and keeps the toolbar visible.    I'm not sure if the toolbar disappearing is deliberate or a bug, but you can prevent the cause, which is the x axis having nothing.
