### ISSUE TITLE
startingShape/endingShape altertives

### ISSUE THREAD

**Issue by beau-gosse** [apexcharts/apexcharts.js#2238]
As noted in #422 it was previously possible in `v.3.17.0` to add rounded shapes to bar charts, but that feature is now deprecated as of `v3.24.0`. 

I was curious if there are alternatives or hacks to consider. From a purely UI standpoint, this was a rather useful feature.

**Comment by robert1508** [comment]
Yes, we need this !!!!!!!!!

**Comment by and-mine** [comment]
Please please..... allow to set borderRadius manually!!!

**Comment by AndrewZelaya** [comment]
+1 can we please add this?

**Comment by mtr1990** [comment]
+1

**Comment by beau-gosse** [comment]
Closing as this is [fixed](https://github.com/apexcharts/apexcharts.js/issues/2291#issuecomment-799695874) in the latest release `3.26.0` 

```
plotOptions: {
  bar: {
    borderRadius: 20 // or any number 
  }
}
```

Thanks for the great work @junedchhipa!

**Comment by david-induro** [comment]
There's some bugginess to this. If you have a stacked chart, and the top series has a null value somewhere in the series, the border radius is not applied to next lower series.

DEMO:
https://codepen.io/david-induro/pen/JjNdbxx

@beau-gosse Should I make a new Issue for this?
