### ISSUE TITLE
Radial Bar Charts Label (value and name) fontWeight not setting properly 

### ISSUE THREAD

**Issue by jimmybanegas** [apexcharts/apexcharts.js#2239]
# Bug report

## Codepen

[Codepen link](https://codepen.io/jimmybanegas93/pen/rNWmgOM) 

## Explanation
 RadialBar "dataLabel.value" and "dataLabel.name" taking the same fontWeight 

- What is the behavior you expect?
  RadialBar datalabels name and value to have different font size
- What is happening instead?
  They both take the "dataLabel.value" fontWeight
- What error message are you getting?
 None, see screenshot
![image](https://user-images.githubusercontent.com/2421080/108266426-b4768580-712f-11eb-88ab-e3f80535c643.png)

**Comment by lucasrdrgs** [comment]
I've been facing the same issue. I've tried adding this to plotOptions.radialBar:
```
dataLabels: {
  name: {
    fontWeight: 1200 // also tried '1200', 'bold'...
  },
 value: {
    offsetY: 5
  }
}
```
But it does not work at all. The weight is always the default one. I'm using the React integration.
