### ISSUE TITLE
Multiple track Colors in Radialbar Chart Multiple

### ISSUE THREAD

**Issue by kumaranc** [apexcharts/apexcharts.js#224]
## Multiple track Colors in Radialbar Chart Multiple

Hi, We are trying to make a design like each bar has unique track color instead of common colors in multiple bars, But i didnt find further documents in documentation so kindly provide any idea to make it.

**Comment by junedchhipa** [comment]
@kumaranc Currently, not easily achievable, but I have just updated the `plotOptions.radialBar.track.background` to accept array also.
So, in the next release, you will be able to do

```javascript
plotOptions: {
  radialBar: {
    track: {
      background: ['#f3f3f3', '#e4e4e4']
    }
  }
}
```
