### ISSUE TITLE
I want all legends to be visible without scroll bar.

### ISSUE THREAD

**Issue by MrMohamedAbdallah** [apexcharts/apexcharts.js#2246]
I want to show all legends without scroll bar because the scroll appears in the downloaded image and it cuts the rest of the legends.
![apex_scroll](https://user-images.githubusercontent.com/51543900/108613444-d5263000-73fa-11eb-9fbe-016c7475cd35.jpg)

**Comment by abhishekTraitFit** [comment]
any solution to this?
