### ISSUE TITLE
Incorrect x-axis labels with type = 'numeric'

### ISSUE THREAD

**Issue by pvictor** [apexcharts/apexcharts.js#2249]
# Bug report

## Codepen

With last version, incorrect labels are displayed on x-axis : 

https://codepen.io/pvictor-r/pen/abBLyBX

![image](https://user-images.githubusercontent.com/4415580/108734995-4fa49c00-7530-11eb-9b0a-2ad2f479660f.png)

With a previous version (tested with 3.10.0), labels are correct:

https://codepen.io/pvictor-r/pen/eYBGLBK

![image](https://user-images.githubusercontent.com/4415580/108735118-719e1e80-7530-11eb-8a60-e5087aeede0f.png)

Both charts have same config: 

```
var options = {
  "chart": {
    "type": "line"
  },
  "series": [
    {
      "name": "y",
      "data": [[1,0], [2,1], [3,0]]
    }
  ],
  "stroke": {
    "curve": "straight",
    "width": 2
  },
  "xaxis": {
    "type": "numeric"//,  "tickAmount": 4
  }
} ;
```

## Explanation

Incorrect labels are displayed on x-axis, but value in tooltip is correct.

If `xaxis.tickAmount` is provided, bug seems to disappear

**Comment by pvictor** [comment]
The bug first appear in 3.15.4

**Comment by junedchhipa** [comment]
This [commit](https://github.com/apexcharts/apexcharts.js/commit/0847eebc1c6510c7a518c2e3d4118e70a7817e7f) fixes the issue.
