### ISSUE TITLE
Click events doesn't generate dataPointIndex and seriesIndex for Pie Charts

### ISSUE THREAD

**Issue by PrzemyslawKlys** [apexcharts/apexcharts.js#2251]
# Bug report

## Codepen

https://codepen.io/MadBoyEvo/pen/ExNbVeo

## Explanation

- What is the behavior you expect?

Both dataPointSelection and click event should return dataPointindex or/and series for all types of events correctly. 

- What is happening instead?

Following code behaves differently for different charts. For Pie charts only dataPointSelection provides dataPointIndex, but click event always return -1, -1. Click event for bar chart works correctly so I'm assuming this is a bug, not a feature. Maybe other chart types have the same issue.

```html
events: {
    dataPointSelection: function (event, chartContext, config) {
        console.log(config.dataPointIndex + " " + config.seriesIndex);
    },
    click: function (event, chartContext, config) {
        console.log(config.dataPointIndex + " " + config.seriesIndex);
    }
}
```

- What error message are you getting?

No error message.

**Comment by karagog** [comment]
This issue is also preventing me from detecting double-click events on a pie chart, since I apparently can't access the data point index that was clicked.

**Comment by gbenga504** [comment]
Yeah this is a bug. I think you can get around this by using `event.target.parentElement.getAttribute("data:realIndex")`

i.e 

```
 chart: {
      type: 'pie',
      events: {
        click: function(event, chartContext, config) {
            console.log(event.target.parentElement.getAttribute("data:realIndex"))
        }
      }
    },
```

**Comment by PrzemyslawKlys** [comment]
Please fix not close.

**Comment by PrzemyslawKlys** [comment]
Not stale.

**Comment by bn3t** [comment]
I have the same issue but I will use the trick with `event.target.parentElement.getAttribute("data:realIndex")`
