### ISSUE TITLE
Add chart double click event, and perhaps default it to "Home"

### ISSUE THREAD

**Issue by DannyBen** [apexcharts/apexcharts.js#2252]
**Is your feature request related to a problem? Please describe.**	

No problem.

**Describe the solution you'd like**	

I would love to have an easier access to the "Home" (reset zoom) feature, that does not require the toolbar to be visible. Many charting libraries I have used, use either the double click event for it, or some use the "mouse drag from right to left" to do it (as opposed to dragging from left to right to left to zoom).

I was looking at the events section, and noticed there is no such event. So, even if the collaborators of this repository do not agree to implementing a "double click to zoom out", perhaps expose a double click event for us?

So we could do:

```javascript
chart: {
  toolbar: {
    autoSelected: 'zoom'
  },
  events: {
    doubleClick: function(event, chartContext, config) {
      chart.resetSeries();
    }
  }
},
```

**Describe alternatives you've considered**	

I have tried using the `click` event for it, but it will not work, since it immediately triggered after zooming.

**Additional context**	

None.

**Comment by DannyBen** [comment]
wow... issue count is snowballing...

**Comment by brianlagunas** [comment]
Yeah, we have actually started managing the issues 😄 

I like the idea behind this feature request. However, I would like to avoid having to click around and use a more natural mouse interaction for zooming... the Mouse Wheel.  I would like to be able to intuitively zoom in and out without having the toolbar visible.

What do you think about using the mouse wheel instead?

**Comment by DannyBen** [comment]
Heh, yeah, I was hoping this charting library is still under active development, since I love it.

Also - I agree this feature is totally not a high priority, but when there is a pesky bot marking issues as stale, it just might cause good feature requests or bugs to be lost forever.

I suggest, send that bot to the scrapyard...

About the feature itself - any way to "reset" the chart that does not involve clicking on some icon, would be great. Double click is one intuitive way, mouse wheel up (like "all the way up") is also a good way, with only the disadvantage that if you are too much zoomed in, you need to do multiple rolls.

**Comment by DannyBen** [comment]
> If the issue has been open for over 60 days, then either the maintainers don't have time for it

So the solution is to throw away the time and effort that some people invested on reporting and suggesting an issue in the first place? 

There is no harm in keeping the issues open - other than people seeing a large number of issues.

But, to each his own.

**Comment by brianlagunas** [comment]
People complain when an issue has been left open indefinitely with no response or guidance, and people complain if you close it letting them know you aren't going to address the issue. No matter what, people will complain. So it's best for the maintainers to take the approach that works best for them.

**Comment by illoin** [comment]
@DannyBen , you can use this code
```js
events: {
  click: function(event, chartContext, config) {
    if (event.detail === 2) chart.resetSeries();
  }
}
```
Reset zoom by double click code example on [CodePen.io ](https://codepen.io/AlexScH/pen/XWVEdrV)

**Comment by DannyBen** [comment]
thanks @illoin - seems like a reasonable solution.
