### ISSUE TITLE
Responsive chart with weird spaces.

### ISSUE THREAD

**Issue by y0nd0** [apexcharts/apexcharts.js#2256]
# Bug report

## Codepen

[CodePen Demo](https://codepen.io/y0nd0/pen/oNYpZJR)

**DOM Inspector**

```xml
<g 
  id="SvgjsG1011" 
  class="apexcharts-inner apexcharts-graphical" 
  transform="translate(0, 30)">
</g>
```

## Explanation

How to remove the `translate(0, 30)`? And the bottom? (Yellow marked)
I think it's 30px top and 15px bottom.
Click on the graph to display the toolbar and line. You can see weird spaces.
Can I already remove it? Otherwise, we should fix that.
Sorry I cannot find a solution.

The goal is to have a full responsive chart with no gaps and perfect fit to container.
Without any text or lines.

![demo](https://user-images.githubusercontent.com/68586847/109201659-63efcf80-77a2-11eb-9ad4-2e1b96e2f974.gif)

Note: `padding` is already set to `0` (zero).

**Options**

<details>
  <summary>Click to view options</summary>
 
---
```js
var options = {
  responsive: [{ breakpoint: undefined, options: {} }],
  series: [
    {
      name: 'Data',
      data: demoData,
    },
  ],
  chart: {
    background: 'transparent',
    type: 'area',
    height: '100%',
    zoom: {
      enabled: false,
    },
    toolbar: {
      show: false,
    },
  },
  dataLabels: {
    enabled: false,
  },
  xaxis: {
    type: 'datetime',
    labels: { show: false },
    axisBorder: { show: false },
    axisTicks: { show: false },
    crosshairs: { show: true },
    tooltip: { enabled: false },
  },
  yaxis: {
    opposite: true,
    show: false,
  },
  stroke: {
    curve: 'straight',
  },
  grid: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    xaxis: {
      lines: {
        show: false,
      },
    },
    yaxis: {
      lines: {
        show: false,
      },
    },
  },
  theme: {
    mode: 'dark',
    palette: 'palette1',
  },
};
```
---
</details>

My current workaround is: 

```scss
apx-chart {
  position: absolute;
  display: block;
  width: 100%;
  // Remove gaps.
  top: -30px;
  bottom: -15px;
}
```

Another solution: Switch to another chart lib like "ECharts" (ngx-echarts), etc.

**Comment by BeKnowDo** [comment]
Same here - I have so much additional white space all around the component and haven't figured out why yet
