### ISSUE TITLE
Error when updating series while slice is selected - donut chart

### ISSUE THREAD

**Issue by cvakodobro** [apexcharts/apexcharts.js#2258]
# Bug report

## Codepen

https://codepen.io/cvakodobro/pen/poNpQNX

To replicate the error just select slice and click randomize button. You will see an error in the console log. 

## Explanation

- What is the behavior you expect?

No error when updating series while slice is selected.

- What is happening instead?

An error is thrown every time you update the series while a slice is selected. I'm experiencing this [issue](https://github.com/apexcharts/vue-apexcharts/issues/323) using vue-apexchart but I've noticed that the same issue happens with JS apexchart.

- What error message are you getting?

`Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null".`

**Comment by karagog** [comment]
I am also seeing this error under similar circumstances (when calling updateOptions() on a chart that has a slice selected). The donut chart appears to be working fine otherwise, but spams the following error:

Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null".

I'm going to assume I can safely ignore this, because it does appear to be working fine despite the error. But maybe it indicates a bug somewhere in the code?

**Comment by Androvski93** [comment]
I am using apexchart with Typescript and Angular 12 and I am having the same issue.

**Comment by htimran** [comment]
I am using ApexChart with React Js, and I am facing this error just with the region change to the UK, and the graph is not showing correctly and throws this error
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null".
Else on other Regions, it is working fine with no errors.
Can anyone help me out on this?

**Comment by daniiprado** [comment]
I am using apexchart with Vue 2 and I am having the same issue.

![Captura de Pantalla 2021-09-15 a la(s) 9 46 09 p  m](https://user-images.githubusercontent.com/12104660/133541156-7499e105-4a46-4bad-8352-0972a30154d1.png)

When I resize the browser or collapse the dashboard sidebar the chart lose data and plotted empty

![PjMQWf9SGy](https://user-images.githubusercontent.com/12104660/133540511-03b976d3-ec40-4610-b09e-a9b82960802a.gif)

```js
data: () => ({
  population_chart: {
      series: [0, 0, 0],
      chartOptions: {
        chart: {
          type: 'donut',
        },
        legend: {
          position: 'bottom',
        },
        colors: ['#1ab7ea', '#0084ff', '#39539E'],
        labels: [
          'Label 1',
          'Label 2',
          'Label 3',
        ],
        responsive: [
          {
            breakpoint: 480,
            options: {
              legend: {
                fontSize: '10px',
              },
            },
          },
        ],
      },
    },
}),
mounted() {
    this.api
      .get()
      .then((response) => {
        this.$refs.chart.updateSeries(
            response.data.chart // => [33, 34, 33]
          )
      })
},
```

**Comment by Mangor1no** [comment]
Any new progress on this issue?

**Comment by yeongbin-jo** [comment]
Still have this issue.

apexchart==3.28.3
react-apexcharts==1.3.9

**Comment by junedchhipa** [comment]
In the original Codepen https://codepen.io/cvakodobro/pen/poNpQNX provided by @cvakodobro, the issue doesn't happen with the latest version 3.33.0

**Comment by yeongbin-jo** [comment]
The same problem is occurring in the latest version, but I will first review whether it is my own problem,
and if it is not my problem, I will post an example code that can reproduce the error.

**Comment by 1001v** [comment]
> In the original Codepen https://codepen.io/cvakodobro/pen/poNpQNX provided by @cvakodobro, the issue doesn't happen with the latest version 3.33.0

Please select a data-point and you will see the issue.

**Comment by gyoogle** [comment]
> In the original Codepen https://codepen.io/cvakodobro/pen/poNpQNX provided by @cvakodobro, the issue doesn't happen with the latest version 3.33.0

Same here

**Comment by gbermudezjc** [comment]
I'm having this issue using "apexcharts": "^3.33.0" and "vue": "^2.6.12".

**Comment by Sabih-KL** [comment]
still having issues [ "apexcharts": "^3.36.0", "react-apexcharts": "^1.4.0"]

**Comment by karthickprasathmb** [comment]
If anyone using next js, adding `swcMinify: false` in next.config.js makes it work.

Ref: https://github.com/chartjs/Chart.js/issues/10673

**Comment by Sabih-KL** [comment]
> If anyone using next js, adding `swcMinify: false` in next.config.js makes it work.
> 
> Ref: [chartjs/Chart.js#10673](https://github.com/chartjs/Chart.js/issues/10673)

thanks!

**Comment by SeanParkTiz** [comment]
I am using apexchart with Vue 3 and I am having the same issue.

![image](https://user-images.githubusercontent.com/93113890/205836606-24856714-acdb-47e7-ad17-113c0d794b1f.png)

**Comment by AdinoWayne** [comment]
my version "3.33.0" and nuxtjs "2.15.7" This problem still occurs. anyone, please tell me how to fix it?

**Comment by Sabih-KL** [comment]
> my version "3.33.0" and nuxtjs "2.15.7" This problem still occurs. anyone, please tell me how to fix it?

swcMinify: false in next.config.js
