### ISSUE TITLE
Point annotation marker offsetX/Y

### ISSUE THREAD

**Issue by mhgbrown** [apexcharts/apexcharts.js#226]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As with the general `markers` setting, I'd like to be able to set an offsetX and/or Y with point annotation markers e.g.
```javascript
    points: [
      {
        x: new Date("27 Nov 2017").getTime(),
        y: 8500.9,
        marker: {
          size: 6,
          fillColor: "#fff",
          strokeColor: "#2698FF",
          radius: 2,
          offsetY: -10 // <== Offset
        },
       ...
      }
    ]
```

**Describe alternatives you've considered**
1) Using annotation text with some whitespace character (but no way to make circle)
2) Using another series with just the annotation point (but then the markers offset is applied globally, `discrete` offsetX/Y is also ignored). Would also be nice to assign markers settings per series.

**Additional context**
Going for something like this ultimately:
<img width="563" alt="screenshot 2018-12-07 at 14 46 00" src="https://user-images.githubusercontent.com/194112/49651209-dbed4600-fa2e-11e8-8242-7dbdb8cd9528.png">

Thanks for making a great lib, esp with Vue integration 😍

**Comment by junedchhipa** [comment]
Sure, just added it.
Wait for the next release to use it :)

**Comment by mhgbrown** [comment]
Hell yeah! I'll watch for the next release.
