### ISSUE TITLE
reformate Y axis returned infinity value with null value

### ISSUE THREAD

**Issue by manonaSamir** [apexcharts/apexcharts.js#2267]
When I try to format  Y axis label value it returns infinity with zero Value

**My js code**
`                   yaxis: {
                        show: true,
                        labels: {
                            formatter: function (val, index) {
                                return Math.abs(Number(val)) >= 1.0e+9
                                    ? Math.abs(Number(val)) / 1.0e+9 + "B"
                                    : Math.abs(Number(val)) >= 1.0e+6
                                        ? Math.abs(Number(val)) / 1.0e+6 + "M"
                                        : Math.abs(Number(val)) >= 1.0e+3
                                            ? Math.abs(Number(val)) / 1.0e+3 + "K"
                                            : Math.abs(Number(val)) < 1.0e+3 ? Math.abs(Number(val))
                                                : Math.abs(Number(val));}
                        },`

**it worked with data but when all data equal zero chart be like this img**
![Image 22](https://user-images.githubusercontent.com/36510244/109642494-b989fa80-7b5b-11eb-8ca4-b8df8dc4606f.png)

**before add formatter function all Chart appear like this** 
![Image 23](https://user-images.githubusercontent.com/36510244/109642772-11c0fc80-7b5c-11eb-9372-4b3e34444fc4.png)

**Comment by poddarkhushbu07** [comment]
I am also facing similar issue.

I have kept y axis max value as 100. And when data is not available, y axis  labels shows infinity

![image](https://user-images.githubusercontent.com/31128078/109787607-689a0500-7c34-11eb-8a75-2b394e9799df.png)

**Comment by manonaSamir** [comment]
> I am also facing similar issue.
> 
> I have kept y axis max value as 100. And when data is not available, y axis labels shows infinity
> 
> ![image](https://user-images.githubusercontent.com/31128078/109787607-689a0500-7c34-11eb-8a75-2b394e9799df.png)

I Don't prefer to set max value because may be value be more than 100

**Comment by poddarkhushbu07** [comment]
@manonaSamir it is part of my requirement. Y value range cannot exceed 100

**Comment by manonaSamir** [comment]
> @manonaSamir it is part of my requirement. Y value range cannot exceed 100

So put min value your problem will solve
