### ISSUE TITLE
Add support for specifying fontweight

### ISSUE THREAD

**Issue by sacki5** [apexcharts/apexcharts.js#227]
**Is your feature request related to a problem? Please describe.**
I would like to be able to style the charts to fit in more with my project. It´s nice that you have added support for font-family. But i would like to have more customisation. More precisely specifying font-weight. 

**Describe the solution you'd like**
I would like to be able to specify the font-weight of the title. 

**Describe alternatives you've considered**
As far as i can see svg.js support font weight. So it should be similar to implementing the font-family.

**Comment by junedchhipa** [comment]
I may include it in the future releases.
For now, you can also target elements with CSS

```css
.apexcharts-title-text {
  font-weight: 600
}
```

All the elements of ApexCharts have specific classes added to them, so you can easily modify design properties with CSS if you don't find an option to specify in JS config. Doing with CSS also helps in applying styles globally unlike specifying each and every option in each chart config.
