### ISSUE TITLE
Error: <path> attribute d: Expected number, "M NaN NaN A NaN Na…"

### ISSUE THREAD

**Issue by prajwolonta** [apexcharts/apexcharts.js#2270]
I have this vue component where apexchart is being loaded. Inside the component the charts are switchable. Every time i switch from bar chart to pie or pie to bar chart I get this issue: 

![image](https://user-images.githubusercontent.com/922680/109906435-96df1980-7cf4-11eb-852b-de84fd9d1c42.png)

but switching from bar chart to line chart doesn't throw any errors. I think its a bug in the system. 
This is how I've been switching the chart types: 

![image](https://user-images.githubusercontent.com/922680/109906526-c42bc780-7cf4-11eb-8672-22dfdff35874.png)

**Comment by netzpixel** [comment]
I have a very similar error but without switching chart types. I just switch between vue router pages and get this error:

`6000 Error: <path> attribute d: Expected number, "M 0 NaN".`

**Comment by exitlol** [comment]
Similar but with angular
`Error: <path> attribute d: Expected number, "…878048784 0 0 1 NaN NaN"` It's displaying when I navigate to a route that contains charts (mainly a dashboard type page)

**Comment by ilkou** [comment]
Similar but with react
<img width="815" alt="Screenshot 2021-08-10 at 17 45 38" src="https://user-images.githubusercontent.com/48165230/128900013-70abbcf7-c531-4e9e-b1ae-c41222cb3b49.png">

**Comment by discry** [comment]
I am encountering this same error with p5js and p5.js-svg@1.0.7 trying to create a golden ratio spiral

**Comment by PhilipArchifact** [comment]
I have this error on resizing the window/viewport in certain situations. Mostly when switching to a new dynamically loaded graph. seems like the previous chart in apex not destroyed resulting in non existing graph, Apex should check on resize if a chart object still exists and if not remove the chart from the cached collection.

I made a demonstration in the [following jsbin](https://jsbin.com/gufovuy/edit?html,output)

**Comment by sylveryte** [comment]
I'm also facing the same issue in angular.

**Comment by SpartanTech** [comment]
same issue, how has everyone solved this?

**Comment by pvh-archifact** [comment]
[Created a new test page on jsbin](https://jsbin.com/bazevid/8/edit?js,output). 
Check browser console for the errors.

The ApexCharts engine is missing checks for removed charts or charts that does not exists anymore on the page. 
Being by a removed parent container, chart element or change of content where chart(s) are inside.

**Comment by alboom25** [comment]
Also experiencing the same. Unfortunately, no substantial help can be found anywhere.

**Comment by pvh-archifact** [comment]
I tried to clean up the left over chart on window.onbeforeunload but its not always working.  Especially if you have multiple charts on the page or load charts dynamically inside the page and replace them on the fly or empty the chart(s) container. With multiple charts on the page i cache the container id's in a global var and go over them in obeforeunload and look if there is a chart attached to it and remove it. Again this is not always working.

See destroy chart method in my [previous example](https://jsbin.com/bazevid/edit?js,output)

The real fix would be that in the Apex code actually checks if the chart is still (visible) in the dom before going over resizing/updating etc. on a no longer existing chart.

**Comment by klucass** [comment]
@pvh-archifact thank you so much! It worked here with Vue3. 

I created an array like `let chartCollection = [];` and then `chartCollection.push(chart);` inside my function

```
function renderChart() { 
  let options = {...}
  (...)
  
  let chart = new ApexCharts(document.querySelector("#chart"), options);
  chartCollection.push(chart);
  chart.render(); 

  (...)
}
```
 
and then inside the hook function onUnmounted, call destroy() using the collection.

`
onUnmounted(() => {
    chartCollection[0] ? chartCollection[0].destroy() : "";
  });
`

and it's working like a charm.

**Comment by ArmantoArisRoutsis** [comment]
I had a similar issue with React. I was defining the height and width of the chart as `100%`. Changing it to `px` fixed the error.

**Comment by Faiizii** [comment]
@klucass your example perfectly working on initial render. when i try to update the series I am facing the similar error. I tried `updateSeries` and `ApexChart.exec` and no success.

**Comment by sujonifty** [comment]
I'm also facing this problem in react.

**Comment by ktomasic-margins** [comment]
In my case, this issue occurred when any of the values passed to the series were `NaN`.

**Comment by theibd56** [comment]
![image](https://github.com/apexcharts/apexcharts.js/assets/84173880/6d3b6117-5b26-4b7c-a4f2-5ab8307af2e5)

**Comment by KentuckyMC** [comment]
We've the same errors in console as above. How can this issue be marked as 'closed' while it's actually still happening? We're using apexcharts together with Vue3, and it seems like on resizing, other charts from previous route are still trying to resize? Any ideas?

**Comment by pvh-archifact** [comment]
I pulled the repo and rebuild the dist with the 5c3bba0 fix. And deployed it into my application and it seems to fix the nan and node errors of removed graph elements and does not throw these errors anymore on resizing the window.

**Comment by eProcureparth** [comment]
<img width="976" alt="Image" src="https://github.com/user-attachments/assets/370023be-016a-433f-85a7-ef489fbd4d50" />

<img width="1493" alt="Image" src="https://github.com/user-attachments/assets/d0c0d6ad-4dc4-471a-b2b5-4e48e701b5bb" />

when i use  legend: { show: false, },  when i use https://www.npmjs.com/package/react-apexcharts.

**Comment by MehbubRashid** [comment]
For anyone who is switching chart types and facing this issue in 'react-apexcharts', assign a unique 'key' to your ReactApexChart component call.

```js
<ReactApexChart 
    key={`pie-${uniqueID}`}
    options={{...pieChartOptions}}
    series={[...pieChartOptions.series]}
    type="pie" 
    height={350} 
/>
```
