### ISSUE TITLE
Custom tooltip on annotations, or a way to customize annotations further

### ISSUE THREAD

**Issue by sinaa** [apexcharts/apexcharts.js#2273]
**Is your feature request related to a problem? Please describe.**	

Apexcharts offers the great option to add annotation vertical lines, such as below:

![image](https://user-images.githubusercontent.com/1182185/110009330-c43bbf80-7d14-11eb-88f8-dbf4802111d0.png)

However, sometimes there is little space to expand on the annotation text, or there is a need to provide more information on it.

There seems to be no way to customize a title on hover, or to show a custom tooltip on the annotation.

----

**Describe the solution you'd like**	

Ideally, a mechanism to allow a tooltip on hover or click would be great, so that we can provide more details about what the annotation means (e.g., to provide details about a specific event which happened in a timeline).

----

**Describe alternatives you've considered**	

Another option could be to provide an interface to at least customize the svg of the annotation.

**Comment by jesusgn90** [comment]
I'm facing the same issue. Any news on this issue? thanks, it's a nice charts library guys!

**Comment by sinaa** [comment]
Any chance this could be looked at? Neither myself nor the commenter above got any response

**Comment by brianlagunas** [comment]
This is not a feature we plan on implementing at this time.

**Comment by tomasz-grzesik** [comment]
> This is not a feature we plan on implementing at this time.

now maby?
