### ISSUE TITLE
Bar chart / Wrong Y axis

### ISSUE THREAD

**Issue by dev31337** [apexcharts/apexcharts.js#2276]
Hi,

As you can see in the screenshot below the Y axis is wrong, you can see that "5" is shown twice and the Y axis horizontal lines are not aligned with the bars. (The 6 bar for example is half between the 5 and 6 Y axis line).

![image](https://user-images.githubusercontent.com/29877494/110330113-ad031780-801d-11eb-918c-a539c3a1fb8d.png)

Regards.

**Comment by widecr0w** [comment]
+1 
Also noticed this with certain linecharts.
