### ISSUE TITLE
Bart Chart / Y axis hidden / first bar X axis label issue

### ISSUE THREAD

**Issue by dev31337** [apexcharts/apexcharts.js#2277]
Hi,

If you hide the Y axis then the first bar has no X axis label displayed as you can see below:

![image](https://user-images.githubusercontent.com/29877494/110335493-361d4d00-8024-11eb-930c-dcf707efdb4d.png)

The reason is probably because the function that computes if the X label is displayed does not take into account when the Y axis is hidden.

Regards.

**Comment by junedchhipa** [comment]
Fixed in 3.26.1
