### ISSUE TITLE
How to update last candlestick data and make a real-time candlestick chart?

### ISSUE THREAD

**Issue by mehdighassemi** [apexcharts/apexcharts.js#2290]
Hi guys,
I want to make a real time candlestick chart like the cryptocurrency exchanges. In this issue, the last candle must be update by data stream on every 2 second. Is this possible by Apexcharts and if yes, how? 
Thanks.

**Comment by fractalgod** [comment]
it is possible just use [updateSeries ](https://apexcharts.com/docs/methods/#updateSeries)

**Comment by mehdighassemi** [comment]
@fractalgod 
Thanks for your reply. I read the samples, but could not adapt them to my project. In candlestick chart, we have 30 candle for example that they added to series data via array like below before chart render. After the chart rendered, I must be update 29th data index by data stream from my exchange every 2 seconds and after the time frame (1 day for example) end, I must add a new candle and updated it every 2 seconds and so to the end. Now,  my problem is how to implement this situation? 

`series: [
            {
                data: [
                    { x: new Date(data[0]['time']), y: [data[0]['open'], data[0]['high'], data[0]['low'], data[0]['close']] },
                     ....
                    { x: new Date(data[29]['time']), y: [data[29]['open'], data[29]['high'], data[29]['low'], data[29]['close']] } ,
                          ],
            },
        ],`

**Comment by aydafield22** [comment]
how about this? I also need to draw last bar realtime via price from websocket?

**Comment by mahdi-ghassemi** [comment]
@aydafield22 
I solved this issues by usage the [tradingview free widgets](https://www.tradingview.com/widget/).

**Comment by aydafield22** [comment]
@mahdi-ghassemi thank your response. But free widget of TradingView cannot be feed custom data source from our own.
