### ISSUE TITLE
Events (beforeMount, zoomed) option to set series/data dynamically? 

### ISSUE THREAD

**Issue by DJanoskova** [apexcharts/apexcharts.js#2294]
**Is your feature request related to a problem? Please describe.**	

No. It's not a feature request, it's a question

**Describe the solution you'd like**	

When working with chart's events (beforeMount, zoomed etc.) is there a way to filter the data?
Let's say I'm rendering 10 000 points in a scatter chart and I want to filter them before the rendering phase is initiated. I can get into my series using the config parameter in the beforeMount() method, however when I set series (config.config.series = []) there to [] the chart still renders with my 10 000 points. What I'm asking is is there a way to set the data before the rendering phase begins?

**Comment by junedchhipa** [comment]
Sorry, you cannot change the data in the events. You can only change the series/data by calling the update methods outside the event config.
