### ISSUE TITLE
Heatmap colors shades are not showing correctly

### ISSUE THREAD

**Issue by lucafaggianelli** [apexcharts/apexcharts.js#2297]
# Bug report

I have a heatmap chart with data values varying in a large range, but some cells look almost white or anyway un-readable. With the `distributed` option the chart is better but still hard to read:

```
plotOptions: {
  heatmap: {
    distributed: true
  }
}
```

![image](https://user-images.githubusercontent.com/4471043/111619256-a2970980-87e5-11eb-917e-1160f93ef6bd.png)

I don't think this is normal, maybe I'm missing some config.

Check also these specific cases in the images:
- 3rd row, 2nd column: the value is 5 but it shows very light, check also the cells above (3) and below (7)
- check the highlighted cell with value 35 which looks very light with respect to other cells with similar values

## Explanation

- What is the behavior you expect? To correctly see colors
- What is happening instead? Some cells are white or almost white
- What error message are you getting? No errors

**Comment by shubhambattoo** [comment]
I am facing a similar issue. Can this be reopened?
