### ISSUE TITLE
Toggle Multiple Series Simultaneously

### ISSUE THREAD

**Issue by charlieml** [apexcharts/apexcharts.js#2298]
Hello,

Is there a way to toggle multiple series simultaneously in the same method call ? 
I ask this because I have a toggle button where I want to hide multiple series (5 in my example), but doing it one by one seems to be taking a visible amount of time.
I have also tried hide series and show series and it is also a bit slow.

Regards,

**Comment by kailasb10** [comment]
having the same problem hide series & show series are too slow to plot a graph.
I've also tried with mount event but it's not showing the graph until the hide series loop is completed
