### ISSUE TITLE
Offset background color support

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#23]
![sketch](https://user-images.githubusercontent.com/6877046/43822647-5e124d18-9af5-11e8-9e66-659dcb95ea00.png)

Is there any way to make the gray background of the 3 datasets transparent?

**Comment by junedchhipa** [comment]
You can hide the tracks instead of giving a transparent background
![screen shot 2018-08-08 at 1 25 46 pm](https://user-images.githubusercontent.com/17950663/43824075-9fa5f392-9b0e-11e8-89cb-092ce558f092.png)

Example: https://codepen.io/apexcharts/pen/YjJOgB

**Comment by jimfilippou** [comment]
Thank you @junedchhipa, that worked fine!
