### ISSUE TITLE
When you call `destroy`, the groups are not deleted.

### ISSUE THREAD

**Issue by avil13** [apexcharts/apexcharts.js#230]
Hi.

When deleting a group using the `destroy` method, the array storing the list of groups is not cleared.

And when recreating the chart, we get the error:
```
Cannot read property 'querySelector' of null
```
Because we are trying to access the tooltip that was destroyed.

---
## Codepen

_Press the `refresh` button twice_

Example:
https://codepen.io/avil13/pen/aPzzxq

The error can be seen in the browser console:
https://codepen.io/avil13/full/aPzzxq

--- 

Perhaps the problem can be solved in this section of the code by clearing the list of groups there.
https://github.com/apexcharts/apexcharts.js/blob/c155b0dae62dc5e38933a48e16dd1c79dbbfb345/src/modules/Toolbar.js#L363

---

## Explanation

- When `destroy` charts groups, they remove from `ApexCharts`

- Charts groups stay in a local variable which causes the error

- Error: `Cannot read property 'querySelector' of null`

There are only two graphics exist
![image](https://user-images.githubusercontent.com/1606172/49737383-c893e200-fc9d-11e8-8f00-4b3fed1fbdfe.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, just fixed the issue.

**Comment by sandeepmohil** [comment]
Same issue happens when you draw multiple charts with multiple series & then try the combination of following while charts are grouped : Zoom In\Out , add remove series rigorously on this line.

t.w.globals.dom.baseEl.querySelector(".apexcharts-tooltip")

with error can not find "querySelector" of null. Not able to find any solution for this yet.

**Comment by rodpatulski** [comment]
@avil13 how did you manage to get a proper sourcemapped stack trace working?
