### ISSUE TITLE
Gradient area opacity per series

### ISSUE THREAD

**Issue by garac** [apexcharts/apexcharts.js#231]
It would be really useful with an option to specify opacity on gradients per series. Right now solid fill can have a specific opacity per series by supplying an array of opacities, however gradients do not seem to permit this, i.e. opacityFrom and opacityTo do not accept arrays. 

Since colors in gradients can be set per series, it would make sense to be able to set opacity in a similar way.

Alternatively, it would help to be able to specify an alpha channel in the colors used in gradients. This seems to fail.

The feature will add flexibility in designing great looking area charts, including allowing the scenario where a gradient area chart is shown with a line graph without an area.

**Comment by junedchhipa** [comment]
Sure, that's a valid requirement.
I just fixed the code to allow gradient `opacityFrom` and `opacityTo` to accept an array.
Wait for the next patch release to use it.

**Comment by garac** [comment]
Wow that was extremely fast! Thank you very much!
