### ISSUE TITLE
Use an image/icon as label.

### ISSUE THREAD

**Issue by gabibianconi** [apexcharts/apexcharts.js#2312]
**Is your feature request related to a problem? Please describe.**	
It would be great if we could use img or icons for labels.

**Describe the solution you'd like**	
![image](https://user-images.githubusercontent.com/25694348/112527166-8402b680-8d81-11eb-962f-0ed7a05dcd45.png)

**Comment by mtinnes** [comment]
This would be nice - for example we have a chart with one axis corresponding to countries. It would be great to be able to use the country flag as a label rather than the text.
