### ISSUE TITLE
Brush Chart: ApexCharts is not defined

### ISSUE THREAD

**Issue by kinekt4** [apexcharts/apexcharts.js#2315]
# Bug report

## Codepen

I'm trying to implement the following Brush Chart into my project:

https://codepen.io/apexcharts/pen/rqWeBX

## Explanation

- What is the behavior you expect? Be able to reproduce the Brush Chart
- What is happening instead? Only first (top) graph is rendering. Second graph (bottom) does not render
- What error message are you getting?
```
Uncaught (in promise) ReferenceError: ApexCharts is not defined
    at apexcharts.common.js:6
    at Array.forEach (<anonymous>)
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:14)
    at t.create (apexcharts.common.js:6)
    at apexcharts.common.js:14
    at new Promise (<anonymous>)
    at t.value (apexcharts.common.js:14)
    at HTMLDocument.<anonymous> (brush.js:129)
```

## Usage
I'm using `apexcharts`with `webpack`
```
// brush.js
import ApexCharts from 'apexcharts';

document.addEventListener("DOMContentLoaded", function (event) {

    // Start: https://codepen.io/apexcharts/pen/rqWeBX
    ...
    var options1 = {
        chart: {
            id: "chart1",
        },
        ...
    };
    var chart1 = new ApexCharts(document.querySelector("#chart-area"), options1);
    chart1.render();
    ...
    var options2 = {
        chart: {
            id: "chart2",
            brush: {
                target: "chart1",
                enabled: true
            },
        },
        ...
    };
    var chart2 = new ApexCharts(document.querySelector("#chart-bar"), options2);
    // Error is triggered in the following line
    chart2.render();
    ...
    // End: https://codepen.io/apexcharts/pen/rqWeBX

});
```
**Note**: To avoid confusion, I've switched the chart-id's around so that they match the chart variables
## Environment
ApexGraph: v3.26
OS: Fedora 33
Browsers Tested: Opera, Chrome, Firefox

**Comment by kinekt4** [comment]
Error disappeared after removing the following from `options2`:
```
brush: {
  target: "chart2",
  enabled: true
},
```

**Comment by kinekt4** [comment]
I'm guessing there might be a race condition, where `chart1` (id: `chart2`) hasn't fully rendered and then `chart2` (id: `chart1`) tries to access that element, causing it to error.

But then again, I don't know why it works in the codepen and fails in my project.

**Comment by dagilleland** [comment]
@kinekt4 - Did you ever find a way to get the brush working for you? I'm running into the same behavior in Svelte when I try to use the brush.

**Comment by moonclimber1** [comment]
I'm running into the same problem also when using BrushChart together with Svelte...

**Comment by moonclimber1** [comment]
A dirty workaround I found in svelte is to import the script tag version of ApexCharts instead of the module version. However this introduces other problems and is not a good solution in many cases.

```
<svelte:head>
	<script src="https://cdn.jsdelivr.net/npm/apexcharts" on:load={initCharts}></script>
</svelte:head>
```

**Comment by moonclimber1** [comment]
@junedchhipa Can you reopen this issue?

**Comment by CropWatchDevelopment** [comment]
@ash-davies had the right idea, using Sveltekit, this solved my problem.

**Comment by fzzarf220** [comment]
Guys, this is still an issue when using Brush charts.  This was super annoying of a bug.  

Please fix!!

**Comment by Lars-Sommer** [comment]
Having the same problem with vue3.

**Comment by francescob** [comment]
Same problem using stimulus.js, anyone found a solution?
