### ISSUE TITLE
Annotation is behind labels (z-index) even when set to 'front'

### ISSUE THREAD

**Issue by stanislavromanov** [apexcharts/apexcharts.js#2318]
# Bug report

## Codepen

https://jsfiddle.net/6veyj0ca/

## Explanation

The `position: 'front'` property of annotations does not seem to apply relative to axis labels.

- What is the behavior you expect?
I would expect the annotation to be on top of axis label.

- What is happening instead?
The axis label is in front of annotation label.

- What error message are you getting?
None.

![image](https://user-images.githubusercontent.com/4534725/112847541-7877fe00-90a7-11eb-83fe-ae560dd507a8.png)

**Comment by stanislavromanov** [comment]
I mean, the bug still exists.

**Comment by Sandr0oo** [comment]
The error has still not been fixed(
![изображение](https://user-images.githubusercontent.com/61181414/221491309-75df3c4b-bf72-4c69-97e6-e26b5a003c54.png)

**Comment by Sandr0oo** [comment]
@stanislavromanov Did you manage to solve this problem?
