### ISSUE TITLE
No margin between labels and x-axis when hover on line chart.

### ISSUE THREAD

**Issue by wondertalik** [apexcharts/apexcharts.js#2319]
# Bug report
No margin between labels and x-axis when hover on line chart.

![image](https://user-images.githubusercontent.com/1611064/112866127-b8e07780-90b9-11eb-8105-96799d144f9b.png)

## Codesandbox
[Bug demonstration](https://codesandbox.io/s/energy-dashboard-bug-274lw)

**Comment by wondertalik** [comment]
Up. v3.26.2 still has this issue.

**Comment by junedchhipa** [comment]
The issue can be fixed with following configuration

```js
legend: {
  height: 40
}
```
