### ISSUE TITLE
Curved line area chat extends too much on right side

### ISSUE THREAD

**Issue by programmierstube** [apexcharts/apexcharts.js#232]
As can be seen in the examples, a curved line area chart is not clipped in a straight line on the right hand side of the chart. The curve kind of shoots over the expected area which could be confusing for users.

Problem visible here: https://apexcharts.com/javascript-chart-demos/mixed-charts/line-area/

I would expect a clean vertical clipping like on the left side of the chart.

**Comment by junedchhipa** [comment]
Thanks for reporting.
This is fixed in this commit - https://github.com/apexcharts/apexcharts.js/commit/df10c05073499b7ce57406cf5cf84d2df9be3654 and will be released along with the next patch version.
