### ISSUE TITLE
Disable hover effect on Donut chart

### ISSUE THREAD

**Issue by pererasudarshani** [apexcharts/apexcharts.js#2321]
I set a string[] to total, to display it in the middle of the chart. I need to display it always like this
![image](https://user-images.githubusercontent.com/762161/112886376-7c2f7300-90ef-11eb-8a51-f2c839e8ec65.png)

But when the mouse hovers, it displays like this.
![image](https://user-images.githubusercontent.com/762161/112886504-a6813080-90ef-11eb-8447-9a8ad68c0c49.png)

![image](https://user-images.githubusercontent.com/762161/112887504-d977f400-90f0-11eb-8426-43d0efea47ac.png)

**Comment by ductmOfficial** [comment]
I got the same issue

**Comment by marcinsta** [comment]
I am experiencing the same issue. I'd like to display static label that never changes, eg show single value only, no matter what is clicked or hovered. It shows all right initially but line break is removed when hovered over chart.

My configuration:

```plotOptions: {
      pie: {
        startAngle: -90,
        endAngle: 270,
        expandOnClick: false,
        donut: {
          size: '75%',
          labels: {
            show: true,
            total: {
              show: true,
              showAlways: true,
              formatter: (w) => [`${w.config?.series?.[3] || 0}%`, 'Complete'],
            },
            value: {
              show: true,
              color: theme.palette.neutral[400],
              fontSize: oneRem * 0.7,
              offsetY: -oneRem*0.1,
              fontWeight: 600
            },
            name: {
              show: false
            }
          }
        }
      }
    },

**Comment by ericlara22** [comment]
> I am experiencing the same issue. I'd like to display static label that never changes, eg show single value only, no matter what is clicked or hovered. It shows all right initially but line break is removed when hovered over chart.
> 
> My configuration:
> 
> ```
>       pie: {
>         startAngle: -90,
>         endAngle: 270,
>         expandOnClick: false,
>         donut: {
>           size: '75%',
>           labels: {
>             show: true,
>             total: {
>               show: true,
>               showAlways: true,
>               formatter: (w) => [`${w.config?.series?.[3] || 0}%`, 'Complete'],
>             },
>             value: {
>               show: true,
>               color: theme.palette.neutral[400],
>               fontSize: oneRem * 0.7,
>               offsetY: -oneRem*0.1,
>               fontWeight: 600
>             },
>             name: {
>               show: false
>             }
>           }
>         }
>       }
>     },
> ```
> 
> Edit: Disabling css pointer events in wrapping element makes the job done.

worked perfectly. Thanks!
