### ISSUE TITLE
Group Multiple Y-Axis  chart 

### ISSUE THREAD

**Issue by shibins** [apexcharts/apexcharts.js#2326]
**Is your feature request related to a problem? Please describe.**	
I would Like to group multiple Series on Y-Axis . For example If I have "Number of Requests" , "Number of Users"  using a Y-Axis with  values as counts . Then I want another y-Axis average response time which is in seconds (Time) . Currently i don't see option tp group them 

**Describe the solution you'd like**	
 The seriesName attribute for yAxis should be array so that we can group  

**Describe alternatives you've considered**	
Currently i have 3 yaxis 

**Additional context**	
None

**Comment by joeyJsonar** [comment]
Needed by us too. I'll try to make a PR for this if I can't somehow hack this for my current feature.
