### ISSUE TITLE
Line Chart - Stepline

### ISSUE THREAD

**Issue by Phmager** [apexcharts/apexcharts.js#2334]
Hi, thanks for the awesome library,

is it possible to define how the stepline should behave? I have the issue, that the steps are drawn directly on the point. I would like to behave it like the red line

![image](https://user-images.githubusercontent.com/9350951/113410347-808bb280-93b3-11eb-81b4-38e8f480acaa.png)

In the example it is drawn correctly, the only difference I see is that im using dates for the x-axis
![image](https://user-images.githubusercontent.com/9350951/113410333-78cc0e00-93b3-11eb-8605-88070df66c73.png)

**Comment by Sandst4** [comment]
I'm also having the same issue. The stepline is reversed while the example shows it correctly. I'm also using dates on the x axis. Does anyone know who to fix it? Thanks!

**Comment by chris-doco** [comment]
This issue happens when you use "datetime" for the xaxis.
I have a fix on my fork: https://github.com/chris-doco/apexcharts.js
