### ISSUE TITLE
[Pie/Donut] Can't wrap  text (Line breaks) in Donut Label

### ISSUE THREAD

**Issue by KhanhVanCong** [apexcharts/apexcharts.js#2335]
# Bug report
In Pie-donut chart, I have some labels and Total Label with long text, they can't be wrap text. I tried to use Array String to wrap follow this[ link ](https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/) but it didn't work.
## Codepen
https://codepen.io/pysyren/pen/eYgWxrQ

## Explanation

- What is the behavior you expect? I expect that the long text can be line breaks.
![image](https://user-images.githubusercontent.com/34101200/113497758-100aa000-9531-11eb-884f-96aa85436f8f.png)

- What is happening instead? Now they can't be drop line.
![image](https://user-images.githubusercontent.com/34101200/113497777-47794c80-9531-11eb-9e44-1fbd9a021fb2.png)

- What error message are you getting? No, I don't see any error messages, I don't see any documentation for this issue.

You have a good library, I hope to hear from you soon.
Thank you,

**Comment by bhaveshpatel200** [comment]
Warp text (Line break) not working while hover on slice in donut chart.

**Comment by Tiago-Manuel** [comment]
Any chance we can reopen this? im having the same issue
