### ISSUE TITLE
"Reset zoom" and "Legend show: false" not working

### ISSUE THREAD

**Issue by Osolemio44** [apexcharts/apexcharts.js#2339]
First of all thanks for this amazing library.

I am trying to make a grafic with both zoom and brush ON. 

- I have not been able to get the "reset zoom" button to work. 

- Nor have I been able to hide the captions in the graph below.

Codepen code: [https://codepen.io/DivineNutella/pen/gOgRjWG](https://codepen.io/DivineNutella/pen/gOgRjWG)

![chrome_Qxo67OT19Q](https://user-images.githubusercontent.com/55595063/113596032-0f116580-963a-11eb-8bd8-f5074d2323ab.jpg)

**Comment by Osolemio44** [comment]
I just realized that "dataLabels: {enabled: false}" is not working on the bottom chart (brush chart) either.

**Comment by junedchhipa** [comment]
You have misplaced the legend configuration. It should be placed under options directly, not under `chart` property

```js
options = {
  chart: {
    // ...
  },
  legend: {
    show: false
  }
}
```

**Comment by Osolemio44** [comment]
thanks. What about reset option in toolbar. I checked the documentatión and it look i writed it correctly but still not working.
