### ISSUE TITLE
Tainted Canvas

### ISSUE THREAD

**Issue by msantelices** [apexcharts/apexcharts.js#234]
I'm getting the following error: 'Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported at Image.r.onload' when trying to download a chart as a PNG. As a SVG it works.

It happens both on local and on hosting.

I'm using Vue 2.5.17 and the Vue version of apex charts.

**- What is the behavior you expect?**
Download the chart as a PNG image

**- What is happening instead?**
The download isn't working and I'm getting an error message

**- What error message are you getting?**
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported at Image.r.onload

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by eLvErDe** [comment]
Hello,

For me it's not fixed, I'm getting the same message with fresh 3.5.1 download and Chromium 72
