### ISSUE TITLE
Unable to find info about Range bar

### ISSUE THREAD

**Issue by Osolemio44** [apexcharts/apexcharts.js#2340]
Hi. i am trying to implement the range bar, but i was unable to find any info or example on how to do it. Any help would be apreciated.
![chrome_4udeUmmJ9i](https://user-images.githubusercontent.com/55595063/113596725-053c3200-963b-11eb-9711-d4ce6229108b.jpg)

**Comment by junedchhipa** [comment]
The scroller was removed back in 2019 as it had heavy memory leaks.
It may come back again in the future, but I cannot give any ETA.
