### ISSUE TITLE
Scatter chart with 4 quadrants background

### ISSUE THREAD

**Issue by ronniegchagas** [apexcharts/apexcharts.js#2341]
Hi,
I am using the scatter plot on a 4-quadrant model.

Is there a method to draw each quadrant with a color?
In none of the features did i find a viable solution.

The option **Chart > Background** did not work as I wanted because it took the entire area of the chart.
[](https://apexcharts.com/docs/options/chart/background)

And with the **Annotations** I can make the quadrants on the left but not the right, as in the code below.
[](https://apexcharts.com/docs/options/annotations/#yaxis)

`options: {
      annotations: {
        position: 'back',
        yaxis: [
          {
            label: {
               text: ' ',
            },
            y: 50,
            y2: 100,
            width: '50%',
            fillColor: 'green',
          },
          {
            label: {
              text: ' ',
            },
            y: 0,
            y2: 50,
            width: '50%',
            fillColor: 'yellow',
          },
        ],
      }
}`

**Comment by junedchhipa** [comment]
Can you post a full Codepen of what you've tried
