### ISSUE TITLE
Curved and Triangle Columns / Bar Chart

### ISSUE THREAD

**Issue by Dinuz** [apexcharts/apexcharts.js#2343]
**Is your feature request related to a problem? Please describe.**	
It would be extremely cool to be able to shape the bars/columns as curved and/or triangular.
The only thing that is possible doing right now is adding a border radius but the overall shape remains rectangular.

**Describe the solution you'd like**	
Triangle and curved shaped bar/columns are very similar (2 node on the base and a middle vertex node), the only difference will be the tension in the vertex to generate the curvature.

I would suggest to have only symmetric shapes, meaning the curvature on the left and the right, in the vertex, are the same.

We could add an option in Columns / Bar that activate the curvature, and an option that determine the curvature value.

```
curvature: {
show: boolean
magnitude: number
}	
```

**show**: this activate/deactivate the curvature/triangular shape. It would collapse the two top nodes in one single vertex when activated.

**magnitude**: numeric value ranging from 0, a triangle, to half the base length, max possible curvature (more will just deform the shape, inverting the derivative along the side, it will flex).

**Additional context**	
the screenshot should be self explanatory of what I am trying to obtain:
![Screen Shot 2021-04-06 at 1 25 42 PM](https://user-images.githubusercontent.com/1139472/113753031-a1b61100-96db-11eb-8740-0df34815e34e.png)

screenshot explaining the magnitude:
![Screen Shot 2021-04-06 at 1 33 51 PM](https://user-images.githubusercontent.com/1139472/113753995-c1016e00-96dc-11eb-991f-c083ed2e6f65.png)
![Screen Shot 2021-04-06 at 1 35 05 PM](https://user-images.githubusercontent.com/1139472/113754133-e9896800-96dc-11eb-860c-efb0934f7b3e.png)

**Comment by Dinuz** [comment]
I developed the code to generate both, would you like to integrate it?

**Comment by junedchhipa** [comment]
Hey, this is very interesting. I would like to know how much size this functionality will add to the library.
Can you create a PR so I can take a look at the code, please?
