### ISSUE TITLE
X-axis ticks are misplaced when using Bar chart with datetime x-axis.

### ISSUE THREAD

**Issue by gauravgb21** [apexcharts/apexcharts.js#2344]
I plotted a bar chart with datetime xaxis but the axis ticks are showing over wrong dates.
here is the codepen for the same 
[https://codepen.io/gauravgb21/pen/XWpeKNo](url)

Below is the screenshot.

<img width="749" alt="Screenshot 2021-04-07 at 11 53 18 AM" src="https://user-images.githubusercontent.com/20303329/113853226-08f6c280-97bb-11eb-8e1f-8c49b741bfd4.png">

**Comment by ThomasO02** [comment]
For this, you need to change xaxis.tickplacement to 'on', default is 'between'
https://apexcharts.com/docs/options/xaxis/#tickPlacement

**Comment by jdegger** [comment]
xaxis.tickPlacement does not work for type `datetime`. Any other solutions for this?
