### ISSUE TITLE
Heatmap doesn't display range legend with one row

### ISSUE THREAD

**Issue by tan-yaka** [apexcharts/apexcharts.js#2350]
See attached images

![guzn8pv2](https://user-images.githubusercontent.com/7068443/112464409-615da700-8d5b-11eb-87ff-6a5f062fe751.png)
![fc77nt43](https://user-images.githubusercontent.com/7068443/112464412-628ed400-8d5b-11eb-9c8c-7e34a728c682.png)

**Comment by junedchhipa** [comment]
```javascript
legend: {
  showForSingleSeries: true
}
```
