### ISSUE TITLE
Problem changing chart type programmatically

### ISSUE THREAD

**Issue by jaimestuardo** [apexcharts/apexcharts.js#2352]
# Bug report

## Codepen

<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="js,result" data-user="jaime-stuardo" data-slug-hash="xxgYovy" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="ApexCharts Template">
  <span>See the Pen <a href="https://codepen.io/jaime-stuardo/pen/xxgYovy">
  ApexCharts Template</a> by Jaime Stuardo (<a href="https://codepen.io/jaime-stuardo">@jaime-stuardo</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>

## Explanation

- Notice when Ajax Chart is initialized, it contains 2 points. In that case, "scatter" chart type is used (showing 2 dots). Then, you can press the button `Change Type (more elements)` and the chart type will change to line, however, the scatter dots are still shown.

- When line chart type is chosen in initialization, no dots are shown.

The expected behaviour is that when the chart type is changed, from scatter chart type, dots should not be shown.

Regards
Jaime

**Comment by junedchhipa** [comment]
This is more of a configuration issue in your code. You have to disable markers in a line chart.

```js
markers: {
   size: arrValues.length === 2 ? 6 : 0
}
```
