### ISSUE TITLE
Treemap chart does not render when series is updated

### ISSUE THREAD

**Issue by kryogenyk** [apexcharts/apexcharts.js#2356]
I am using the treemap chart for a project.

Firstly, I have no data in my chart, then I generate the first dataset / update on button press. This is how everything is configured so far:

```
  chart: ApexCharts;
  chartData: any[] = [];
  chartOptions: Partial<ChartOptions>;
```
In the constructor I initialize the chartOptions:

```
this.chartOptions = {
      series: [
        {
          data: this.chartData
        }
      ],
      legend: {
        show: false
      },
      title: {
        text: "Distribution of time estimates",
        align: "center"
      },
      chart: {
        height: 400,
        type: "treemap",
      },
      colors: [],
      noData: {
        text: 'Press the generate chart button!'
      },
      plotOptions: {
        treemap: {
          distributed: true,
          enableShades: false
        }
      }
    };
```

Then I initialize the chart in a separate function, on OnInit():
```

this.chart = new ApexCharts(document.querySelector('#chart'), this.chartOptions);
this.chart.render();
```

The chart is being displayed without a problem, as expected.

![image](https://user-images.githubusercontent.com/9081225/114907431-ba34d280-9e23-11eb-86f4-562699198863.png)

Then, when pressing the Generate chart button, I do the following actions:

```
     this.chartData = this.myListOfObjects.map(p => ({
      x: p.name, //string
      y: p..estimatedTime //number
    }));

    let chartColors = [];

    //dont mind this, here is some code to generate better random colors
    for (let i = 0; i < this.chartData.length; i++) {
      const h = Math.random();
      chartColors.push(HSVtoHEX(h, 0.6, 0.95));
    }

    this.chartOptions.series = [{
      data: this.chartData
    }];

    this.chartOptions.colors = chartColors;
    this.chart.updateOptions(this.chartOptions);

    this.chart.updateSeries([{
      name: 'Time Estimates',
      data: this.chartData
    }]);
```
Now is where the fun part begins: I receive a console error which says:
_TypeError: can't access property 0, i.globals.previousPaths[o] is undefined_

The chart looks like this at this stage:
![image](https://user-images.githubusercontent.com/9081225/114907996-53fc7f80-9e24-11eb-9228-69bd30518bf0.png)
Each time I call this method, the same error appears. 

**If I resize the window**, the chart appears as it should and my update method works. 

![image](https://user-images.githubusercontent.com/9081225/114908515-d9802f80-9e24-11eb-9d2b-42fb53abb78b.png)

What am I doing wrong? Am I misusing the library?

I am using Angular 11 and the latest version of apex-charts.

EDIT - this is my html code:
```

           <div id="chart" >
                <apx-chart [series]="chartOptions.series" [chart]="chartOptions.chart"
                    [dataLabels]="chartOptions.dataLabels" [plotOptions]="chartOptions.plotOptions"
                    [title]="chartOptions.title" [colors]="chartOptions.colors" [noData]="chartOptions.noData">
                </apx-chart>
            </div>
```

**Comment by patrick-g-p** [comment]
@junedchhipa running into this issue still with `"apexcharts": "^3.41.1"` and `"vue3-apexcharts": "^1.4.4"`

**Comment by VirendraMaheta7** [comment]
I am also facing the same issue, while resizing the window chart gets displayed. Is there any update on this?

**Comment by VirendraMaheta7** [comment]
I have added class="d-block" in <apx-chart> and now charts are visible without resizing window.
