### ISSUE TITLE
How to add series name on Polar Area Chart ?

### ISSUE THREAD

**Issue by thatflow** [apexcharts/apexcharts.js#2359]
Hi,

We can add series name in legend or tooltip, but how can we add series name at the top of data (on the x-axis, around the circle) ?
Like this:
![35781995-73d3bd20-09bf-11e8-9dd5-93e35b7b637d](https://user-images.githubusercontent.com/17432231/115412886-0baeda00-a1f5-11eb-8dde-17426a2402c2.png)

Thank

**Comment by VincentVanclef** [comment]
Would love this feature, is there any news on this?
