### ISSUE TITLE
plotOptions > radialBar > offsetX

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#236]
## Codepen

https://codepen.io/anon/pen/ebgbaG

## Explanation

**What is the behavior you expect?**
Move circle to sides

**What is happening instead?**
Nothing, stays centralized

**What error message are you getting?**
Not a visible error

**Comment by junedchhipa** [comment]
Confirmed the bug, thanks for reporting.
For now, you can also use

```javascript
var options = {
  chart: {
    offsetX: 20
  }
}
```

**Comment by junedchhipa** [comment]
Fixed the radialBar.offsetX/Y issue.
The fix will be released in the next patch.

**Comment by juliorosseti** [comment]
> Fixed the radialBar.offsetX/Y issue.
> The fix will be released in the next patch.

Thank you for your agility, you are a God! ❤
