### ISSUE TITLE
An option to get rid of all this empty space inside the SVG for limited height environments

### ISSUE THREAD

**Issue by davidv171** [apexcharts/apexcharts.js#2362]
**Is your feature request related to a problem? Please describe.**	
So currently, when drawing apex charts on very small surface, the actual chart with the data only takes up about 60% (eye test) of the actual SVG surface. This leads to having to resize parent divs into unreasonable heights, just to fit in the chart in its entirety. ![image](https://user-images.githubusercontent.com/26347830/115863468-c4635c00-a435-11eb-9611-d1652836fc8d.png) . This is an example of what I'm talking about. The height of the parent is 100 here. I say it could fit into 75. Maybe even less, if the SVG wasn't so high. 

**Describe the solution you'd like**	
A flag to just clear the white space for timeline charts when there is only one category. 

**Describe alternatives you've considered**	
I tried negative offsets, but that does not really work on it. It still has an oversized SVG on which it draws, so I'm stuck. 

**Additional context**	
No additional context needed

**Comment by meZim** [comment]
@davidv171 Hi !

Facing the same problem as you did. How did you fix it ? 

<img width="333" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/48595385/ac12f949-3162-48dd-9e74-f5b27883ef3d">

**Comment by davidv171** [comment]
@meZim It's been a long time, but from what I remember, I was playing around with the style sheet, negative margins, etc. Until it looked good. A hacky "solution", but it turned out fine.

**Comment by meZim** [comment]
Yep, i guess it's still the only solution. Thanks

I'll update this comment if i manage to get the result i need
