### ISSUE TITLE
Achieve a linear animation on line graph

### ISSUE THREAD

**Issue by peopledrivemecrazy** [apexcharts/apexcharts.js#2363]
How do I set up configurations for animations for a graph that tends to the last point on the data?

Example of chartjs [here](https://www.chartjs.org/docs/latest/samples/animations/progressive-line.html) this is what I would like to achieve.

**Comment by arazzz** [comment]
This might be helpful, https://apexcharts.com/javascript-chart-demos/line-charts/realtime/

**Comment by peopledrivemecrazy** [comment]
Yes, there isn't an inbuilt one.
