### ISSUE TITLE
ApexCharts.exec() not working in graph "RadialBar"

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#237]
## Codepen

https://codepen.io/anon/pen/vvxjJr

## Explanation

**What is the behavior you expect?**
Change the chart series values.

**What is happening instead?**
An error has occurred in the console, the bars not populated, the series data not updated.

**What error message are you getting?**
62 Error: <path> attribute d: Expected number, "….75 58.75 0 0 1 NaN NaN".

**Comment by junedchhipa** [comment]
Sorry, this is nor documented the best way. But the radialBar chart series doesn't accept the `series.data`. It just accepts a plain array with a set of values.
Doc: https://apexcharts.com/docs/series/#data-for-pie-donuts

So, your update code becomes
```javascript
ApexCharts.exec('chartID', 'updateSeries', [44, 33]);
```

**Comment by juliorosseti** [comment]
Thanks Chhipa! Works fine!
