### ISSUE TITLE
Y-axis title gets cropped if labels have different length

### ISSUE THREAD

**Issue by beakoe** [apexcharts/apexcharts.js#2377]
# Bug report

## Codepen

https://codepen.io/beakoe/pen/PoWvOwQ

## Explanation

_- What is the behavior you expect?_
Even if the labels contain strings with different length the y-axis title should not be cropped or pushed out of view.

_- What is happening instead?_
If one or more labels (number of characters) are shorter / longer than the others, the y-axis title gets cropped or pushed out of view. It gets worse the higher the difference between the shortest and longest labels is. We also tried adding spaces to the strings shorter than the longest one, but this doesn't really work since most of the characters don't share the same width.

**Comment by aavezel** [comment]
I have a similar problem. The chart cuts the display boundaries of XAxis for some reason, placing some of it outside the SVG element
![photo_2021-09-13_20-11-01](https://user-images.githubusercontent.com/577004/133127291-91224889-1846-4298-92dd-060b99531a21.jpg)
