### ISSUE TITLE
ShadowDOM support

### ISSUE THREAD

**Issue by Pupix** [apexcharts/apexcharts.js#238]
**Is your feature request related to a problem? Please describe.**
The apexcharts js file adds CSS styles into the document's header. This makes the graph break when the chart is used in a webcomponent as the styles never reach the DOM nodes because of shadowDOM.

**Describe the solution you'd like**
I think the CSS styles should either exposed as a file in the dist directory or add them to the shadowRoot node OR to the document's header

Cheers,
Pupix

**Comment by junedchhipa** [comment]
Exporting CSS file separately in the `dist` directory will break all existing installations and everyone will have to import them.
Can you give more details about the alternatives you have stated?

**Comment by Pupix** [comment]
After taking a closer look at it seems that the webpack `style-loader` just dumps the CSS file https://github.com/apexcharts/apexcharts.js/blob/master/src/assets/apexcharts.css into the header.

The master branch of that loader allows for a parent node to be assigned https://github.com/webpack-contrib/style-loader/blob/master/lib/addStyles.js#L26, which in your dist doesn't seem to appear https://github.com/apexcharts/apexcharts.js/blob/master/dist/apexcharts.js#L31534. Maybe outdated version ?

The chart's element's (this.el in the library) root node should be passed through the style loader as *parent*, so if the element is inside a shadowDOM then the shadow-root will be used, if the element is just sitting in the document then the document will be used.

To get an element's root node all it needs to be done is the following
```js
this.el.getRootNode();
```

For now I extracted the style from `/src/assets/apexcharts.css` and imported it myself in the shadowRoot.

**Comment by Pupix** [comment]
There's also this function that should be doing the same thing https://github.com/apexcharts/apexcharts.js/blob/master/src/utils/DetectElementResize.js#L52

**Comment by junedchhipa** [comment]
I have started copying the `apexcharts.css` from `src` to `dist` in case someone wants to use it from there.
Unfortunately, your suggestion didn't work great as the chart's element cannot be known prior to chart rendering and specified in Webpack.

**Comment by mikaelkaron** [comment]
I'm having the same problems as above with shadow dom.

- I see the `css` file in `dist` here on github, but it's not included during a regular `npm install` so not sure what's up there.
- Was there any problem with having apexcharts detecting if running inside a shadow and append styles to the shadow document instead?

**Comment by mikaelkaron** [comment]
A quick googling showed [`geRootNode'](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) that would return the elements owner document, however I see that styles are injected from `styleInject` which does not have access to the current element (as it's executed on library load).

If you want to support shadow dom we have to add the styles where we have access to `this.el`, probably somewhere during initialization.

If you _don't_ want to add the css there would it be possible to generate a bundle _without_ the css included (so we can avoid the duplicate bytes as you now have to include on your own) alongside the standard build?

**Comment by LeaVerou** [comment]
> If you want to support shadow dom we have to add the styles where we have access to `this.el`, probably somewhere during initialization.

That would be good practice *regardless* of Shadow DOM. You don't want to be injecting styles if Apex Charts is not used on the page.
As a general principle, it's good to try for modules that do not produce side effects if imported and not used.

**Comment by LeaVerou** [comment]
> A quick googling showed [`geRootNode`](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) that would return the elements owner document, however I see that styles are injected from `styleInject` which does not have access to the current element (as it's executed on library load).
> 
> If you want to support shadow dom we have to add the styles where we have access to `this.el`, probably somewhere during initialization.
> 
> If you _don't_ want to add the css there would it be possible to generate a bundle _without_ the css included (so we can avoid the duplicate bytes as you now have to include on your own) alongside the standard build?

I'd be happy to investigate fixing this, but I cannot find where the styles get injected. Could you point me to the right direction?

**Comment by mikaelkaron** [comment]
Based on my old comment the `styleInject` function did this, I'm not able to (quickly) find that anymore...

As for web-component support, are you by any chance using https://github.com/apexcharts/stencil-apexcharts/ for that?

**Comment by LeaVerou** [comment]
FWIW, [this seems to be the line importing it](https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/helpers/InitCtxVariables.js#L33). It's [`rollup-plugin-postcss`](https://github.com/egoist/rollup-plugin-postcss) that seems to bundle styleInject and injects this.

I suppose the way around this would be to do the injection manually. I imagine something along these lines, in the constructor:
- Are we in a shadow DOM context? if not, check if already injected. If not, inject in `<head>`. 
- If so, inject in shadow root

Happy to send a PR, though I'll wait for my previous PR to be reviewed first — wouldn't want to flood the maintainers with too much to review at once 🙂

**Comment by LeaVerou** [comment]
Until this is fixed, here's a workaround for anyone who — like me — is trying to use this in Shadow DOM:

Right after the import:
```js
// Find Apex Charts injected CSS, remove it, and store the code for later usage in Shadow DOM
// See https://github.com/apexcharts/apexcharts.js/issues/238
let apexCSS;

for (let style of document.querySelectorAll("head > style[type='text/css']")) {
	let code = style.textContent;
	if (code.includes(".apexcharts-canvas")) {
		// We found it!
		style.remove();
		apexCSS = code;
		break;
	}
}
```

Then just use `cssCode` in a `<style>` element in our Shadow DOM, e.g.:

```js
this.shadowRoot.innerHTML = `
	<style>${apexCSS}</style>
	<div id=chart></div>
`;
```

**Comment by junedchhipa** [comment]
@LeaVerou Thanks for the PR on ResizeObserver. 
Happy to accept a PR on this as well.

**Comment by LeaVerou** [comment]
> @LeaVerou Thanks for the PR on ResizeObserver. Happy to accept a PR on this as well.

Done! https://github.com/apexcharts/apexcharts.js/pull/2767
