### ISSUE TITLE
Customize tooltip for type boxPlot

### ISSUE THREAD

**Issue by 7aklhz** [apexcharts/apexcharts.js#2381]
**Is your feature request related to a problem? Please describe.**	
I'm using a chart of type "boxPlot" and I would like to customize the tooltip content, using formatter. I can't seem to find the information in your docs. Is this possible ?

**Comment by jaypinho** [comment]
Can we please reopen this? I am unable to use the tooltip formatter function as described in the docs for the boxPlot chart type.

I'm either doing something wrong, or tooltips for the boxPlot chart type are perhaps not customizable? I have yet to successfully format a tooltip on this chart type where multiple values (min, 25th, median, 7th, and max) all show up in my preferred formatting.

Example:

```
                tooltip: {
                  theme: "dark",
                  y: [
                    {
                      formatter: function(value, { series, seriesIndex, dataPointIndex, w }) {
                        return value;
                      }
                    }
                  ]
                }
```
