### ISSUE TITLE
"Combo" Chart with only one column data series is displayed as a line

### ISSUE THREAD

**Issue by nikolaifischer** [apexcharts/apexcharts.js#2388]
# Bug report
Starting with version 3.25.0 Combo chart consisting of lines and bars are not displayed correctly when there's only one 'column' data series. When a second column series is added they are both displayed correctly as bars.
## Codepen
https://codesandbox.io/s/apx-combo-line-column-forked-piitu

## Explanation

- What is the behavior you expect?
The series "Website Blog" is displayed as type: "column"
- What is happening instead?
The series "Website Blog" is displayed as type: "line"
- What error message are you getting?
None

**Comment by RomRider** [comment]
I have the same behavior.

**Comment by RomRider** [comment]
Hi, any update on this?

**Comment by RomRider** [comment]
This blocks me from updating to the latest version. Any update on this bug?
