### ISSUE TITLE
Render chart inside hidden element

### ISSUE THREAD

**Issue by lucafaggianelli** [apexcharts/apexcharts.js#239]
## Codepen
https://codepen.io/lucafaggianelli/pen/ZVKVvY?editors=1010

## Explanation

I have a donut chart inside a menu, which is hidden at startup and as soon as the app starts, the chart throw an error. I'm using VueApexCharts, so from Vue I was able to use a variable to `v-if` the `<apexcharts>` component and render it 500ms after the menu is open... it works but only the first time the menu is open.

This is not really a bug. It makes sense that you cannot draw a chart if you don't know the size of your container, but how would you handle this situation? Moreover I also noticed that the issue happens only if you don't set the width of the chart (I only set the height).

thank you
Luca

**Comment by lucafaggianelli** [comment]
I add that setting the chart width is not fully and always working, or at least it does only in codepen example but it messes up the legend

**Comment by junedchhipa** [comment]
This looks very similar to this issue of chart not rendering in `v-if` condition or a popup - https://github.com/apexcharts/vue-apexcharts/issues/25

I have already started working on it, will be fixed very soon.

**Comment by lucafaggianelli** [comment]
yes it seems related, I also noticed that the chart renders correctly if I resize the container

**Comment by junedchhipa** [comment]
Fixed the issue. Will be released along with 2.5.1
