### ISSUE TITLE
Autoscale of Y-axis on Zoom for Multiple Series not working

### ISSUE THREAD

**Issue by clavid87** [apexcharts/apexcharts.js#2390]
# Bug report

## Codepen
https://codepen.io/clavid87/pen/yLMLJeP

## Explanation

- **What is the behavior you expect?** When I select a part of the graph to x-axis zoom, the y-axis should autoscale so that the most extreme values (out of the multiple series) set the guidelines for the max and min on the y-axis.
- **What is happening instead?** When I select a part of the graph to zoom (try near July 2018) the y-axis range is way too wide (max: 100% / min: -500%). The extreme values from the multiple series is closer to max: 20% min: -10%
![image](https://user-images.githubusercontent.com/2322403/117187038-55b8c380-ad90-11eb-99f8-0f39f8ef86fc.png)

Note: The autoscaling seems to work fine when I try with just a single series

- **What error message are you getting?** None

**Comment by vandelpavel** [comment]
Same problem for me. Have you found any solution or work around? @clavid87
