### ISSUE TITLE
Treemap percentage

### ISSUE THREAD

**Issue by dfiorini** [apexcharts/apexcharts.js#2397]
Is it possible show in tooltip of treemap squares the size in percentage to total value ?

**Comment by dfiorini** [comment]
I'm trying to access the Series data to do some stats but it tells me undefined from the console. I'm using this code and I don't know why it not works:
let data_series = chart.w.globals.seriesData; 
console.log(series2)

**Comment by junedchhipa** [comment]
Can you post a Codepen of what have you tried?

**Comment by dfiorini** [comment]
https://codepen.io/davideffe/pen/ZEKXxbe?editors=0010 here is my codepen 

1) i would like to put COUNTRY NAME in x tooltip
2) idk why my percentage values don't reach 100% in some countries or exceeds in others

**Comment by MichaelCurrin** [comment]
Worked for me.

```js
  const options = {
    // ...
    tooltip: {
      y: {
        formatter: _percentageFormatter
      },
    },
  };
```
