### ISSUE TITLE
DataLabels are displayed out of the chart

### ISSUE THREAD

**Issue by Http400** [apexcharts/apexcharts.js#2399]
### Bug report

`dataLabels` are displayed out of the chart, on the left of y-axis. 

I've prepared comparison (using the same options and data) between `ReactApexCharts` and pure `ApexCharts` and the difference is significant.

How to reproduce:
1. Zoom in a bit
2. Select _Panning_ option and slowly move from side to side

Image:
![datalabels_issue](https://user-images.githubusercontent.com/16990967/117681610-92325800-b1b2-11eb-97a9-dda08d2e5fb6.png)

CodePen:
https://codepen.io/woi/pen/XWMbwMJ

**Comment by junedchhipa** [comment]
Should be fixed in v3.26.2.
Related to #2264
