### ISSUE TITLE
The values in X axis label formatter are in 24 minute intervals (stacked timeline chart)

### ISSUE THREAD

**Issue by davidv171** [apexcharts/apexcharts.js#2400]
# Bug report

I'm currently hacking into a whole lot of behavior to mimic a xAxis "reverse" option, like in Chartjs. Which means I have to format labels. However, the behavior without and with a formatter is very confusing.

https://apexcharts.com/docs/options/xaxis/#formatter

Without a formatter (default option undefined), the labels go from 04:00 -> 04:00 in 3 hr interval. Very sane, very logical. 

However, with a formatter, these values become very strange.

04:00 -> 06:24 -> 08:48 -> .. 01:36 -> 04:00

Minimum and maximum values are set by the configuration to be 04:00. This can be easily reconstructed with codepen. 

## Codepen

Two pure JS examples of with and without formatters:

*without formatter*

https://codepen.io/davidv171/pen/oNZjERe

*with formatter*

https://codepen.io/davidv171/pen/abJvqqd

Looking at the console logs, the values seem to be going at a random step when a formatter is defined, and the "timestamps" are sometimes pure numbers (check the 10-0), and sometimes timestamps. These two facts combined means you cannot use the formatter to just transform values from one format to another, as they result in different values. 

2 hours, 47 minutes and 0 seconds is the difference between each step. Very strange, and results in strange graphs. 

## Explanation

- What is the behavior you expect?
Input values of any formatting function to be expected, and comparable to outputs without a formatter
- What is happening instead?
Explained above, the input value of the formatting functions are off, and strange
- What error message are you getting?
No error message. 
Opts is undefined, but that's a problem unto itself.

**Comment by karesztrk** [comment]
I've switched to `numeric` on the X-axis with the `tickAmount` defined. Timestamp was not OK for me either. v3.11.0
