### ISSUE TITLE
Not zoom in Basic Column Chart & toolbar position

### ISSUE THREAD

**Issue by dfiorini** [apexcharts/apexcharts.js#2401]
# Bug report
I don't know if it is a bug but there is no zoom on Basic columns chart ? I set zoom: {
      enabled: true, } 
But the option doesn't seem to be available on the map, the only thing I can do from the toolbar is to export the map.

**Comment by dfiorini** [comment]
https://codepen.io/davideffe/pen/jOBWqQd look at this, I set zoom true but it doesn't appear, why?

**Comment by dfiorini** [comment]
Ok, I set xaxis.tickPlacement: 'on' and it works, thank you so much

**Comment by dfiorini** [comment]
After zoom there is a option to enlarge rectangles? otherwise there is a lot of white space between them after zooming

**Comment by dfiorini** [comment]
![Uploading Screenshot 2021-05-12 at 11.47.21.png…]()

**Comment by junedchhipa** [comment]
In a category chart, the bars will not expand to fill the white space. It happens only in the numeric/datetime x-axis.

To change the toolbar position, try setting CSS

```css
.apexcharts-toolbar {
  right: auto;
  left: 0
}
```
