### ISSUE TITLE
X-axis showing additional dates

### ISSUE THREAD

**Issue by graingerkid** [apexcharts/apexcharts.js#2403]
It would seem that when you have a small number of dates the charts attempt to fill in additional dates. For example:

![imp (4)](https://user-images.githubusercontent.com/3381276/118113701-84611a80-b3de-11eb-8c12-060e755d421b.png)

This doesn't look too bad but if you have say a weekly duration where your dates are spares 7-days apart you get this:

![imp (5)](https://user-images.githubusercontent.com/3381276/118113800-a78bca00-b3de-11eb-8864-f45906a1ef4d.png)

Is there a way to stop it doing this?

Example:
https://codepen.io/caddyman/pen/PopZgvz

**Comment by graingerkid** [comment]
If I remove xaxis: {type: 'datetime'} then it looks like this - which is what I'm hoping for but with the formatted date etc :
![imp (6)](https://user-images.githubusercontent.com/3381276/118114910-1fa6bf80-b3e0-11eb-9773-824b3368d6c1.png)

**Comment by graingerkid** [comment]
Look like your examples are wrong also:
https://apexcharts.com/javascript-chart-demos/line-charts/gradient/

**Comment by lukemorales** [comment]
+1, I'm also looking to stop this behavior on the line chart
