### ISSUE TITLE
ApexCharts not works with Sticky div 

### ISSUE THREAD

**Issue by dfiorini** [apexcharts/apexcharts.js#2406]
# Bug report

## Codepen

This codepen explain the bug. Apexcharts don't match with Sticky header, but they go further.
https://codepen.io/davideffe/pen/QWpNqgQ

Another example of this bug see as gif:
![Screen Recording 2021-05-14 at 10 16 06](https://user-images.githubusercontent.com/77637795/118242458-a79ecf00-b49d-11eb-889d-728d75977db1.gif)

## Explanation
Apexcharts don't count of the sticky header

**Comment by junedchhipa** [comment]
This is a general CSS issue and not related to ApexCharts directly.
