### ISSUE TITLE
Alternative to endingShape in bar chart?

### ISSUE THREAD

**Issue by jd-solanki** [apexcharts/apexcharts.js#2413]
**Is your feature request related to a problem? Please describe.**	
In older versions of apex charts there were options `startingShape` and `endingShape` which are now removed in latest version of apex charts. I am able to get top border-radius using `borderRadius` property but it only rounds the top boder.

**Describe the solution you'd like**	
Accepting `borderRadius` as Array instead of a number for top and bottom border-radius of some property as flag.

**Describe alternatives you've considered**	
For now, I am only getting a top border-radius. For bottom, I don't have any workarounds.

**Additional context**	
Current:
![image](https://user-images.githubusercontent.com/47495003/118474282-89003880-b728-11eb-9689-19e36520ee57.png)

Desired Result:
![image](https://user-images.githubusercontent.com/47495003/118474355-9ae1db80-b728-11eb-9dac-71f2afbbca29.png)

Regards.

**Comment by jd-0001** [comment]
Also if series have a lower value (so bar won't show up) then the top border radius is not applied to the first top bar.

![image](https://user-images.githubusercontent.com/47495003/118490607-c15d4200-b73b-11eb-8fb8-79c0e9171a78.png)

**Comment by jd-0001** [comment]
Buddy keep it open

**Comment by brianlagunas** [comment]
This has been partially implemented with PR #2614. The `borderRadius` property now takes an array that lets you set a borderRadius on all series.

However, there is still no bottom border radius. I could see us addingf a new property called `borderRadius-bottom`

**Comment by jd-0001** [comment]
It will be great and help others create beautiful charts.

Also, I want to point out that people now liking the roundish design, and having a square in roundish design mess up everything.

Regards.

**Comment by weissingerh** [comment]
Any news on a bottom borderRadius option?

**Comment by jd-0001** [comment]
@brianlagunas Can you please add some label so bot don't close this issue

**Comment by tammaroivan** [comment]
Any other way to implement the bottom border radius?

**Comment by jd-0001** [comment]
![annoyed-icegif](https://user-images.githubusercontent.com/47495003/159626958-d5a60af4-79d3-4ca0-8bff-ee162cc147f8.gif)

**Comment by jd-0001** [comment]
Please keep it open

**Comment by jd-0001** [comment]
Any updates?

**Comment by alokVishu** [comment]
Any updates?

**Comment by jd-solanki** [comment]
@junedchhipa ભાઈ કરી આપ ને કઈ થાય એવું હોય તો આમા PR મારી પણ અમને ફાવતુ નથી

**Comment by jd-solanki** [comment]
.

**Comment by jd-solanki** [comment]
.

**Comment by jd-solanki** [comment]
Can anyone please keep it open?

**Comment by jd-solanki** [comment]
Hi,

As we have a new implementation for rounding corners, can we have this feature back?

https://github.com/apexcharts/apexcharts.js/releases/tag/v3.37.0

**Comment by Naveen-2504** [comment]
Hi,

This issue is not fixed in npm i react apexcharts

**Comment by mario-hs** [comment]
I got a simpler solution

[#1779](https://github.com/apexcharts/apexcharts.js/issues/1779#issuecomment-1733963773)
