### ISSUE TITLE
Radar Chart Fill option opacity color not working in iphone

### ISSUE THREAD

**Issue by suresh5** [apexcharts/apexcharts.js#2416]
# Bug report
Radar Chart Fill option opacity color not working in iphone
 
 
![mobileissue](https://user-images.githubusercontent.com/12095043/118587756-c44b4780-b7ba-11eb-95f0-a81d24b8b964.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12095043/118587760-c6150b00-b7ba-11eb-916b-fb1c5316e76a.png)

**Comment by MatheusNascimentoti99** [comment]
I'm with the same problem.
