### ISSUE TITLE
Legend label is not showing after setting position of legend 'bottom' in simple pie chart

### ISSUE THREAD

**Issue by dream-sky12** [apexcharts/apexcharts.js#242]
## Codepen

https://codepen.io/Dream_Sky12/pen/qLXqrP

## Explanation

I added the 'bottom' position of legend in the pie chart. But the pie chart do not show the legend.

![1111](https://user-images.githubusercontent.com/26947221/50468934-40277800-09e5-11e9-9a19-9b0346fe7006.PNG)
![22222](https://user-images.githubusercontent.com/26947221/50468941-46b5ef80-09e5-11e9-8f61-9f6e0625b115.PNG)
After that, I pressed F12 and checked the element in the chrome. It shows that the legend has a style of 'bottom: -30px' and it did not show in the page. I think the style of bottom should have a value not less than zero.  So, I want to ask that it is normal or bug?  Thanks!
![33333](https://user-images.githubusercontent.com/26947221/50468947-4ae20d00-09e5-11e9-9e83-302df094f6d5.PNG)

**Comment by junedchhipa** [comment]
It is a bug. 
Thanks for reporting, it will be fixed in the next release.
