### ISSUE TITLE
Remove gap between empty periods when using datetime

### ISSUE THREAD

**Issue by lukemorales** [apexcharts/apexcharts.js#2423]
I have the following chart in my project, it receives several data based on datetime to show stocks quotation, however, there are hours that the stocks stops receiving data.
The chart receives the last data of the past day at 6pm, and receives the next data only on the next day at 10am, but that time gap between 6pm and 10am is represented by a flatline on the chart and I don't want that behavior. Is there a solution to this behavior?

![Screen Shot 2021-05-12 at 13 54 51](https://user-images.githubusercontent.com/14251143/118014634-cda36280-b329-11eb-92eb-cc5ddca3031c.png)

**Comment by Matthewn7** [comment]
Bump

**Comment by dineshnirali** [comment]
any solution how to fix

**Comment by FernandoBonfimArctica** [comment]
any solution?
<img width="1049" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/124902356/351997d3-a912-4103-a247-c7ed3fef1bc3">
