### ISSUE TITLE
Show a tooltip on an annotation

### ISSUE THREAD

**Issue by tran-simon** [apexcharts/apexcharts.js#2424]
**Is your feature request related to a problem? Please describe.**	

For a point annotation, I would like to display lots of information on hover, that would take too much space in an annotation label

**Describe the solution you'd like**	

Add a tooltip to an annotation just like a regular point

**Describe alternatives you've considered**	

Use a series for my annotaitons. This is the workaround I'm currently using, but annotations would be better

----

Thank you!

**Comment by ZeemZach** [comment]
Is this feature has been added to Apex Chart Or You have found an alternative?

**Comment by Hareloo** [comment]
Is there a way to do this?

**Comment by shubham-tam** [comment]
Did anyonen find a way ?

**Comment by tomasz-grzesik** [comment]
?

**Comment by yberkut-gbi** [comment]
Would be great to have a tooltip on hover over annotation with ability to customize it.
