### ISSUE TITLE
Blurry Text on hover

### ISSUE THREAD

**Issue by Phmager** [apexcharts/apexcharts.js#2426]
# Bug report

When hovering a chart the text gets blurry on high dpi displays

https://apexcharts.com/javascript-chart-demos/heatmap-charts/multiple-series/

## Explanation

- What is the behavior you expect?
The text should not get blurry
- What is happening instead?
The text gets blurry

https://user-images.githubusercontent.com/9350951/119223981-989ec900-bafc-11eb-8221-cd903cd4ac98.mp4

**Comment by solova** [comment]
The problem is real numbers.
Chrome autofixes blurry state in the normal state, but we see this 0.5px offset during transition.
When I force GPU to use acceleration text becomes blurry not in hover state only.
`.apexcharts-xcrosshairs, .apexcharts-ycrosshairs {
    transform: translateZ(0);
}`
