### ISSUE TITLE
Column stacked show Null values

### ISSUE THREAD

**Issue by mgarcia96** [apexcharts/apexcharts.js#243]
## Explanation

I'm using a bar stacked graph, but if I insert null values it appears like this:
If I have a null value I don't want to display that null...

![image](https://user-images.githubusercontent.com/6561770/50478359-0187c280-09d1-11e9-8712-f8fe6d6f0c6f.png)

```
options: {
	"chart": {
		"stacked": true,
		"toolbar": {
			"show": true
		},
		"zoom": {
			"enabled": true
		}
	},
	"responsive": [{
		"breakpoint": 480,
		"options": {
			"legend": {
				"position": "top",
				"offsetX": -10,
				"offsetY": 0
			}
		}
	}],
	"plotOptions": {
		"bar": {
			"horizontal": false
		}
	},
	"xaxis": {},
	"legend": {
		"position": "bottom"
	},
	"fill": {
		"opacity": 1
	}
},

series : [{
	"name": "En espera",
	"data": [3, 1, 2]
}, {
	"name": "Perdidas",
	"data": [1, 1, 2]
}, {
	"name": "Salientes",
	"data": [null, 1, 1]
}, {
	"name": "Entrantes",
	"data": [null, null, 2]
}]
```

**Comment by junedchhipa** [comment]
You’re right, this shouldn’t happen.
May I ask which version of ApexCharts are you using?

**Comment by mgarcia96** [comment]
> You’re right, this shouldn’t happen.
> May I ask which version of ApexCharts are you using?

I'm using apexcharts with Vue:

"apexcharts": "^2.2.4",
"vue-apexcharts": "^1.2.7",

**Comment by junedchhipa** [comment]
Can you please try apexcharts@2.5.0?

**Comment by mgarcia96** [comment]
> Can you please try apexcharts@2.5.0?

Woow great! Thx!!!

![image](https://user-images.githubusercontent.com/6561770/50487288-f9924780-09fd-11e9-966b-bd9d8925da50.png)
