### ISSUE TITLE
SVG export is black and white

### ISSUE THREAD

**Issue by geekthought** [apexcharts/apexcharts.js#2430]
# Bug report
SVG export is black and white. 

## Codepen

`var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "line"
  },
  series: [
    {
      name: "Series 1",
      data: [1,2]
    }
  ]
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();`

## Explanation

A colored svg?!

**Comment by ordago** [comment]
Hey there! It also happens with the codepen from the docs.

https://codepen.io/apexcharts/pen/xYqyYm

It depends on the svg viewer. In Chrome/Firefox it works well. Inkscape shows the bars fully black.

I opened the svg markup to see if could guess what it could be.

The color is specified this way:

`fill="rgba(0,143,251,0.85)"`

I edited the svg with Inkscape and it modified the markup to this:

`style="fill:#0cff1a;fill-opacity:0.2701613"`

Maybe it could work setting fill color and transparency separately

https://stackoverflow.com/questions/6042550/svg-fill-color-transparency-alpha

**Comment by trannel** [comment]
Hey, did you by any chance find a way to automatically convert the svg images? I'm also currently dealing with this issue, and manually converting dozens of images is not feasible for me. I need them in LaTeX, and the svg package in LaTeX uses inkscape, which cannot handle rgba values without manual conversion.
For reference, here is the open issue regarding inkscape and rgba: https://gitlab.com/inkscape/inbox/-/issues/1195
