### ISSUE TITLE
Line/Area charts with annotations, display on y-axis label area

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#244]
## Codepen

https://codepen.io/apexcharts/pen/GXOJXQ

## Explanation

When we zoom in on a chart with annotations, the annotations leave the chart area and are displayed on the y-axis label area :
![image](https://user-images.githubusercontent.com/46166884/50479331-51b55380-09d6-11e9-9508-1f8be8fccff4.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, confirmed the bug. 
Will be fixed soon
