### ISSUE TITLE
Is it possible to plot 2 charts synchronized horizontally?

### ISSUE THREAD

**Issue by luisfrossi** [apexcharts/apexcharts.js#2446]
Hello, 

Is it possible to plot two charts synchronized horizontally? I could find the vertical example but could not figure out some way to make it the same way using the Y-Axis. 

Something like the following I did on Plotl.ly

![image](https://user-images.githubusercontent.com/5166358/120092365-90402280-c0e8-11eb-92c7-d16121984fd6.png)

Thanks

**Comment by ordago** [comment]
Is this what you mean?

https://codepen.io/ordago/pen/KKWyqBj

**Comment by luisfrossi** [comment]
Thanks a lot, that helped. My question was related if it is possible to keep both scales exactly aligned as plot.ly subplot. I could make that using fixed height for both plots, but not sure if that will be robust. Anyway should work for now.
