### ISSUE TITLE
chart event click is not working with Swiper.js (Angular)

### ISSUE THREAD

**Issue by chechang1223** [apexcharts/apexcharts.js#2449]
# Bug report
The chart event is not triggered with Swiper.js.

## Codepen
https://codesandbox.io/s/area-datetime-x-axis-forked-52hs4?file=/src/app/app.component.html
or
https://stackblitz.com/edit/swiper-apexchart?file=src/app/app.component.ts

## Explanation
I also change Swiper parameters `preventClicks` and `preventClicksPropagation` as false, but It is still not working.
```
<swiper [preventClicks]="false" [preventClicksPropagation]="false">
```
without Swiper.js, it works fine.

**Comment by brianlagunas** [comment]
Integration with 3rd party components is outside the scope of apexcharts. I would submit an issue on the swiper repo for help with their product
