### ISSUE TITLE
Selection and pan not working in mobile view

### ISSUE THREAD

**Issue by divakarmanivel** [apexcharts/apexcharts.js#245]
Hi, I am using apex charts in one of my projects and its really awesome. One issue I faced is that selection and zoom are not working in mobile view. Touch is not working to be exact. Is there any alternative to that?

**Comment by junedchhipa** [comment]
Panning and Selection Zoom doesn't work correctly on touch devices yet.
Note: The toolbar icons for pan and selection zoom should be hidden in touch devices as it doesn't work. I will hide the pan and selection-zoom icons until I get better solutions for those.

**Comment by divakarmanivel** [comment]
Hi thanks for the quick reply. Also is it possible to set zoom level dynamically? I have 2 seperate charts but when I zoom on one the other chart should also zoom the same level. Currently I don't see an option to set zoom level dynamically.

**Comment by junedchhipa** [comment]
If you just want to `sync` multiple charts, you should look at this example - https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/

If you want to control zoom levels dynamically, you can use the `beforeZoom` event - https://apexcharts.com/docs/options/chart/events/#beforeZoom

**Comment by divakarmanivel** [comment]
Ok I'll be sure check those out!

**Comment by ryanhassan71** [comment]
toolbar: {
              tools: {
                download: true, // Enable download button
                selection: true, // Enable selection tool
                zoom: true, // Enable zoom tool
                zoomin: true, // Enable zoom-in button
                zoomout: true, // Enable zoom-out button
                pan: true, // Enable pan functionality
                reset: true, // Enable reset button
              },
            },
