### ISSUE TITLE
yAxis.min value is not correct on scatter charts

### ISSUE THREAD

**Issue by abdullRahman95** [apexcharts/apexcharts.js#2450]
## Codepen
https://codepen.io/abed-abu-salah/pen/vYxpvqv
 
 In the codepen, I log the `yAxis.min` and `yAxis.max` values to the console. So make sure your console is open.
 
 ## Explanation
 * What is the behavior you expect?
   Scatter chart `yAxis.min` value should be the minimum value of the current `yAxis`.
 * What is happening instead?
   `yAxis.min` is always `5e-324` no matter what the data is. `yAxis.max` works correctly. 
 * What error message are you getting?
   There are no error messages.

**Comment by dominikkurbiel** [comment]
I have the same :/
