### ISSUE TITLE
Tooltip shows [object Object[

### ISSUE THREAD

**Issue by sandneyfarias** [apexcharts/apexcharts.js#2451]
# Bug report

## Image
![apex](https://user-images.githubusercontent.com/1819378/120375914-ad940d00-c2f1-11eb-9282-fd05b82043b5.png)

## Explanation
I'm using Angular ApexChart and when I hover the mouse over any value, a tooltip appears over the chart title

- What is the behavior you expect?
Don't show tooltip over the chart title.

**Comment by junedchhipa** [comment]
Can you create a Codepen/Codesandbox example?

**Comment by hacongsang16ck** [comment]
I'm having the same problem. This error won't appear when i don't use options.tooltip

**Comment by hacongsang16ck** [comment]
> Can you create a Codepen/Codesandbox example?

I'm having the same problem. This error won't appear when i don't use options.tooltip

**Comment by sandneyfarias** [comment]
I used this example https://codesandbox.io/s/apx-bar-custom-datalabels-9vb1j?from-embed as reference, just changing the data origin. I'm using Angular CLI: 8.3.29, Node: 14.16.0, OS: win32 x64, Angular: 8.2.14 and Apexcharts 3.26.3. I'd made some tests changing the Apexcharts version, but the problem was not solved.

**Comment by jaballogian** [comment]
I have the same issue but I'm using ```react-js```.

Here are the code and screenshots in my case https://stackoverflow.com/questions/68172536/line-chart-from-react-apex-chart-returns-object-object-in-custom-tooltip

**Comment by brianlagunas** [comment]
I see this issue has been resolved via the StackOverflow post.

**Comment by hacongsang16ck** [comment]
> I see this issue has been resolved via the StackOverflow post.

Can I have a link?
