### ISSUE TITLE
Chart Responsiveness

### ISSUE THREAD

**Issue by fluorspar20** [apexcharts/apexcharts.js#2459]
### **Problem**
So what I'm trying to achieve is to display this line chart as it is in mobile view, without compromising on the tickAmount of the x-axis. 

![Screenshot from 2021-06-08 15-37-16](https://user-images.githubusercontent.com/59736770/121174000-14c43b00-c877-11eb-884a-2de090abe544.png)

The xaxis labels are overlapping, which is undesirable, and I also don't want to hide the overlapping labels. 
### **Possible Fix**
I just want to know if there's a way by which I can view the entire chart, by allowing the chart to be internally scrollable along the horizontal direction, so that it renders the chart with the original tickAmount and the overflowing part can be seen by scrolling horizontally. I searched the docs but I couldn't find anything useful. The responsive property wasn't of any help either.  Any help would be appreciated.

**Comment by fluorspar20** [comment]
This doesn't help. 

![Screenshot from 2021-06-08 20-28-28](https://user-images.githubusercontent.com/59736770/121209008-1f42fc80-c898-11eb-80dd-20c7ee5a7857.png)

Is there a way by which I can specify the margin between each label, so that way the chart looks clean, and I also get to see the data for each label (by scrolling it along horizontal).

**Comment by fluorspar20** [comment]
I found a work-around for this. Closing the issue.

**Comment by azakero** [comment]
> I found a work-around for this. Closing the issue.

hey man. I'm facing the same issue. How did you solve this?
