### ISSUE TITLE
v3.27.0 release breaks functionality for returning html from formatters

### ISSUE THREAD

**Issue by tonyalaribe** [apexcharts/apexcharts.js#2463]
# Bug report

- What is the behavior you expect?
Before v3.27.0 release, I was returning HTML from the formatters, to print more interesting legends
![image](https://user-images.githubusercontent.com/6564482/121734314-e5bafd00-caf4-11eb-98c1-98c1c931729a.png)

- What is happening instead?
Now the HTML string is printed.
![image](https://user-images.githubusercontent.com/6564482/121734618-4d714800-caf5-11eb-95ac-df3c9e02a431.png)

- What error message are you getting?
There are no related error messages in the console
![image](https://user-images.githubusercontent.com/6564482/121734714-7265bb00-caf5-11eb-8809-1014ae9396ed.png)

**Comment by alekbless** [comment]
Same, formatter is not rendering html entities

**Comment by juliorosseti** [comment]
!up - Same, formatter is not rendering html entities

**Comment by idoshr** [comment]
Same, formatter is not rendering html entities
Please help!!!

**Comment by brianlagunas** [comment]
@junedchhipa What changed with v3.27.0 that cause this? Was is a design decision or a regression bug?

**Comment by brianlagunas** [comment]
@tonyalaribe @justineKlimato @alekbless @juliorosseti @idoshr 

Can anyone provide a reproduction app via a codepen? Preferably one that works using the older version and one that's broken sig the newest version.

Thanks

**Comment by junedchhipa** [comment]
@brianlagunas This was a decision taken in response to a vulnerability https://snyk.io/vuln/SNYK-JS-APEXCHARTS-1062708

**Comment by EchopixUser** [comment]
I understand the XSS vulnerability but my input is not coming from the user... How do I get the formatter to stop escaping the html now? Besides downgrading the lib?

**Comment by brianlagunas** [comment]
@EchopixUser there are many ways to use XSS that don't include input from a user. ApexCharts is a client side library and is easily manipulated by anyone that's not the original programmer. XSS does not need user input in order to be taken advantage of.

**Comment by EchopixUser** [comment]
> @EchopixUser there are many ways to use XSS that don't include input from a user. ApexCharts is a client side library and is easily manipulated by anyone that's not the original programmer. XSS does not need user input in order to be taken advantage of.

Anything on client side can be altered. What's your point. The only thing this fix achieved is forcing people to downgrade to prior versions to keep the desired behavior.

**Comment by EchopixUser** [comment]
> So what is the solution for custom rendering in tooltip???

There isn't any. Downgrade to 3.26.3 is your easiest option.

**Comment by brianlagunas** [comment]
After speaking with @junedchhipa, we think we have some ideas to help sanitize the html markup to help eliminate the XSS vulnerability.

We will reopen this and see if you can safely implement this.  If anyone has any ideas, please share them

**Comment by junedchhipa** [comment]
The new sanitize function allows HTML tags while removing any other special attrs supplied in it.
The next release will have this fixed.

**Comment by pvh-archifact** [comment]
I tested / implemented the 4cbc7c6 (SantizeHtml) patch above in the 3.42.0 release. But this implementation is also added to the tooltip function / domhandler, there the sanitize check is applied and fires on every mouse move event and eats away 380ms every move of the mouse. making the tooltip crawl. 
 
 I suggest to sanitize the tooltip data before domhandling.
