### ISSUE TITLE
Toolbar overlaps legend text

### ISSUE THREAD

**Issue by Dazix** [apexcharts/apexcharts.js#247]
## Codepen
https://codepen.io/DazixCZ/pen/yGvOeE

## Explanation

- Toolbar overlaps legend text when you use following settings instead of side by side alignment.
```
legend: {
    position: 'top',
    horizontalAlign: 'right',
},
```

**Comment by junedchhipa** [comment]
This is kinda tricky as both elements are absolutely placed and such elements make it difficult to check for every possible combination that may arise.

Hence, for such scenarios, I suggest tweaking some `CSS` properties to fix it as those are plain HTML elements.

```css
.apexcharts-legend {
    right: 40px !important;
}
```

**Comment by Dazix** [comment]
You have right there is no simple solution. I already use this solution with overriding style but it's a kind of hack. 
Is there any reason for absolute positioning? I think that flexbox containers could be better solution for this case.

**Comment by junedchhipa** [comment]
The legend is actually drawn inside SVG as foreignObject, while toolbar resides outside SVG if you check in developer tools elements.
Hence, it becomes impossible to place them side-by-side.

I already tried a lot of alternatives before coming to this conclusion, so I left it on the users to set certain styles via `CSS`
