### ISSUE TITLE
Weird empty tooltip appears

### ISSUE THREAD

**Issue by andrew-filippov** [apexcharts/apexcharts.js#2475]
# Bug report

## Explanation

- What is the behavior you expect?
Tootltip with some useful information should be appeared when user has mouse moved over the chart (regards to provided chart's options)

- What is happening instead?
If user has just opened page with chart and move page from the left side to right, once when cursor will be over chart's container (but not over data seria yet), empty tooltip is appeared (see screenshot)

![image](https://user-images.githubusercontent.com/22343164/122740980-2f41df80-d28d-11eb-9116-aae5132b3540.png)

If user try to make the trick by moving mouse from right side - it doesn't appear. 
Also if tooltip was appeared with correct content before, it will be appeared with latest correct content until cursor will be over another seria's datapoint.

Related issue (or maybe, it is not an issue?)  (reproduced with **apexcharts ver. 3.21.0** and  **react-apexcharts ver. 1.3.7**): while user is going to reproduce prev. issue, default tooltip is rendered - even tooltip: { custom: <some_function>} is defined  in the options. When cursor is achieving any datapoint - custom one is rendered then. (custom function is not called when tootltip is triggered over chart's container, so it is no chance to prevent empty tooltip from be shown from here.)

- What error message are you getting?
No errors.

**Comment by vrebble** [comment]
we are experiencing the exact same problem. After the chart is intialized and you hover the y-axis (most interestingly does not happen for the x-axis) BEFORE hovering the value-area you get this small empty tooltip.

the easy fix would be to exclude the y-axis from the area that triggers the tooltip.
