### ISSUE TITLE
TypeError in Mozilla Firefox

### ISSUE THREAD

**Issue by jajosheni** [apexcharts/apexcharts.js#2478]
# Bug report

## Explanation

- What is the behavior you expect?
I expect to see apexcharts on my dashboard.

- What is happening instead?
Some error happens `
![image](https://user-images.githubusercontent.com/23244572/122879993-c9f7f800-d339-11eb-8411-2c95cd92ca2b.png)
`
And this happens only on Firefox.

What is the error:
```
TypeError: e is null
apexcharts.min.js:6
```

**Comment by AuspeXeu** [comment]
Same issue. I can confirm it does not happen in Google Chrome.

**Comment by jajosheni** [comment]
The problem was actually triggered by sentry or some other common library between apexchart and sentry.
solution: try to update the packages to a newer version.
