### ISSUE TITLE
Heatmap - Get clicked element

### ISSUE THREAD

**Issue by yurik94** [apexcharts/apexcharts.js#248]
Hello,

I can't find data about clicked element inside that amazing heatmap.
```
function (event, chartContext, config) {
   console.log('click', chartContext);
}
```

Happy new year 🎉

**Comment by junedchhipa** [comment]
Yes, `event.target` is the correct way to grab the html element.

I just realized that the `dataPointSelection` event doesn't work for Heatmap charts.
I will trigger the event when heatmap square is clicked so you can get more info when the element is clicked.

**Comment by yurik94** [comment]
> Yes, `event.target` is the correct way to grab the html element.
> 
> I just realized that the `dataPointSelection` event doesn't work for Heatmap charts.
> I will trigger the event when heatmap square is clicked so you can get more info when the element is clicked.

Thanks!

**Comment by junedchhipa** [comment]
You can get it from those attributes. I will provide an example soon

**Comment by junedchhipa** [comment]
v2.6.0 allows dataPointSelection event to be called on heatmap.

**Comment by maorkavod** [comment]
This works for me 

config.w.globals.labels[event.target.attributes['j'].value]
