### ISSUE TITLE
Order tooltip entries by value

### ISSUE THREAD

**Issue by AuspeXeu** [apexcharts/apexcharts.js#2480]
**Is your feature request related to a problem? Please describe.**	
I would like the order of entries within the tooltip of a line chart to be ordered by the values instead of the name of the series.

**Describe the solution you'd like**	
An option for the tooltip configuration.

**Describe alternatives you've considered**	
Making a custom tooltip, however it never follows the design of apexchart so it would be great to have an option instead.

**Example**
![image](https://user-images.githubusercontent.com/2115696/123064451-91761e00-d40e-11eb-8c21-af4b0a860cd4.png)

Instead of order: green, lime, blue, red > blue, red, green, lime

This order should update dynamically depending on the hovered datapoint(s).

**Comment by AuspeXeu** [comment]
bump

**Comment by brianlagunas** [comment]
Thank you for the suggestion, however this is not a feature that we will be implementing. Having the tooltip order change for each data point would not result in an expected or consistent behavior. It would make the chart more difficult to read.
