### ISSUE TITLE
Unable  to rename the SVG and PNG file , however i can rename the CSV downloadable file as per my requirement .

### ISSUE THREAD

**Issue by Shruthi-Factana** [apexcharts/apexcharts.js#2483]
# Bug report
Unable to rename the PNG and SVG file name , auto generated names will be assigned ex: abcdxxxxx.png, i am able to rename the CSV files

 export: {
          csv: {
            filename: "Avalilability",
            columnDelimiter: ',',
            headerCategory: 'category',
            headerValue: 'value',
            dateFormatter(timestamp) {
              return new Date(timestamp).toDateString()
            }
          }

## Explanation

- What is the behavior you expect?
- i should be able to rename the downloadable files PNG and SVG.
- What is happening instead?
- Its throwing the Error
- What error message are you getting?
-  The expected type comes from property 'export' which is declared here on type '{ show?: boolean; offsetX?: number; offsetY?: number; tools?: { download?: string | boolean; selection?: string | boolean; zoom?: string | boolean; zoomin?: string | boolean; zoomout?: string | boolean; pan?: string | boolean; reset?: string | boolean; customIcons?: { ...; }[]; }; export?: { ...; }; autoSelected?: "...'
![Capture](https://user-images.githubusercontent.com/70931555/123261330-421a1580-d514-11eb-8427-8aae8b689d31.PNG)
![Capture](https://user-images.githubusercontent.com/70931555/123261391-5827d600-d514-11eb-99e6-1de716fafe5f.PNG)

**Comment by Shruthi-Factana** [comment]
Any Update on this issue??

**Comment by mathiash98** [comment]
I can confirm that this is working using vue3-apexcharts, but without any typesafety when sending chart config into the chart, this issue seems to be related to the typings you are using. You should provide a context to what packages you are using

**Comment by Shruthi-Factana** [comment]
Hi Mathias,

Thanks for the reply, I can rename CSV file , and not PNG may I know why this is happening.


Regards,

Shruthi Savitha Nagaraj,

UI/UX Developer,

Factana Computing | INDIA | USA.

[A close up of a sign  Description automatically generated]


________________________________

**Comment by mathiash98** [comment]
> Hi Mathias, Thanks for the reply, I can rename CSV file , and not PNG may I know why this is happening.

Yes we know, you stated so in the first comment...

For your info: I am not a part of the apexchart project, I am only a random person on the internet seeing your issue.

This issue is happening due to some typescript error on your setup. I checked the typedef in apexchart and it is correct. You should provide info with you setup, and preferably a reproduction in a codesandbox link.
- At least provide a full copy of your config object.

It is impossible for people to help you without more information.

**Comment by Shruthi-Factana** [comment]
Okay , im sharing the configuration please  let me know where im making mistake.


Regards,

Shruthi Savitha Nagaraj,

UI/UX Developer,

Factana Computing | INDIA | USA.

[A close up of a sign  Description automatically generated]



________________________________

**Comment by mathiash98** [comment]
@Shruthi-Factana Hmm, I am not fluent in angular world, but it seems like your config is correct, and the typings in ng-apexcharts is correct as well so it should be allowed.
- Typing source: https://github.com/apexcharts/ng-apexcharts/blob/53a5fa02439ea9debd80d4aa0a1995e7810ee261/projects/ng-apexcharts/src/lib/model/apex-types.ts#L109-L123

Are you using latest version of ng-apexchart?

**Comment by Shruthi-Factana** [comment]
Im Currently using   "ng-apexcharts": "^1.5.6",


Regards,

Shruthi Savitha Nagaraj,

UI/UX Developer,

Factana Computing | INDIA | USA.

[A close up of a sign  Description automatically generated]


________________________________

**Comment by MMohesen88** [comment]
Still here not working using `"apexcharts": "^3.27.1"` and `"react-apexcharts": "^1.3.9"`

**Comment by Shruthi-Factana** [comment]
Yes , It's the same issue even now.


Regards,

Shruthi Savitha Nagaraj,

UI/UX Developer,

Factana Computing | INDIA | USA.

[A close up of a sign  Description automatically generated]


________________________________

**Comment by martinraquion** [comment]
@Shruthi-Factana 
Hi Shruti! Found a workaround on this. Instead of renaming the "filename" under the SVG or png object, rename the "id" under the chart object. I also concatenated a Date timestamp on the id to make it unique.

https://apexcharts.com/docs/options/chart/id/

**Comment by fL-safi** [comment]
I have a solution for this.
You can add a line of id: string (name of your choice)
i.e In my case percentage is my custom file name

chart: {
      id: 'Percentage',
      height: 380,
      width: '100%',
      type: 'area',
      zoom: {
        enabled: true,
        autoScaleYaxis: true,
        drag: {
          enabled: false
        }

      },
      animations: {
        initialAnimation: {
          enabled: false
        }
      }
    },

**Comment by wastu01** [comment]
> rename the "id" under the chart object. I also concatenated a Date timestamp on the id to make it unique.

I an going this way. May I  see any example ?
