### ISSUE TITLE
Pie/Donut Chart: problem to set thickness of slices

### ISSUE THREAD

**Issue by pleinx** [apexcharts/apexcharts.js#2488]
Greetz!

Can somebody help me what im doing wrong? I just want to make slim slices:
https://codepen.io/pleinx/pen/vYxobjx

As you can see, the slices are slim but my values (series) are gone.

**Comment by junedchhipa** [comment]
To control the thickness of the donut slices, you have to use this config.

```
  plotOptions: {
    pie: {
      donut: {
        size: '80%'
      }
    }
  }
```
