### ISSUE TITLE
Maximum amount top & bottom line is cut off in sparkline enabled chart

### ISSUE THREAD

**Issue by vaishali-shm** [apexcharts/apexcharts.js#2495]
![image](https://user-images.githubusercontent.com/86353179/124105874-4947a300-da81-11eb-8dd9-4487ba930e61.png)
Hi I am facing this issue where my chart cuts off when I have sparkline enabled. It looks like horizontal gridlines are overlapping or y axis tickAmounts are not calculated properly. I have tried setting tickAmounts  in chart configuration but that does not work for every random dataset we might get in our project.

Any help will be useful.

**Comment by twigs67** [comment]
I'm facing this exact same issue.

**Comment by junedchhipa** [comment]
Can you create a Codepen example?

**Comment by twigs67** [comment]
Not ideal, but I was able to fix this by adding...
```
/*To fix overflow issue on line in reports*/
.apexcharts-canvas > svg {
  overflow: visible;
}
```

**Comment by vaishali-shm** [comment]
@junedchhipa  I hope this pen helps, as you can see chart is cut off from top & bottom edges
https://codepen.io/vaishali-sharma-the-encoder/pen/BaRKgXz


![image](https://user-images.githubusercontent.com/86353179/124861655-9ec80680-dfd1-11eb-9de0-0292b5610ebf.png)

**Comment by vaishali-shm** [comment]
@twigs67 this css fix seems to work for  me as well
