### ISSUE TITLE
Remove stroke if data is 0

### ISSUE THREAD

**Issue by alimoncul** [apexcharts/apexcharts.js#2498]
# Bug report

## Codepen

https://codepen.io/alimoncul/pen/zYwrNxW

## Explanation

Values like 0 should not have a stroke. In big charts user thinks there is a value but the real value is equal to 0. Maybe add a default value for chart, and if data is equal to that default do not render it.

**Comment by alimoncul** [comment]
Could someone add labels?

**Comment by Jarkovato** [comment]
I have the same problem

**Comment by johnvitor0220** [comment]
I can confirm this is still an issue (at least on v3.53). So I ask, is there a way to avoid this behavior with the right config, or is it in fact a bug?

<details>
<summary>Image</summary>
![2024-11-28_09-37](https://github.com/user-attachments/assets/07b98cb3-ac88-4db9-ae17-7c2d041a8151)

</details>

<details>
<summary>Image</summary>
![2024-11-28_09-42](https://github.com/user-attachments/assets/840f25ae-96b7-4073-961c-68bdc422b4ec)

</details>
