### ISSUE TITLE
The chart has too much space between donut chart and legends

### ISSUE THREAD

**Issue by berkbaski** [apexcharts/apexcharts.js#2499]
# Bug report

## Codepen
https://codepen.io/berkbaski/pen/ZEKQqop

## Explanation

Some android devices have too much space between donut chart and legends. The iOS devices I tried never had this problem. I don't know how to fix this.

Should be like this (iOS)
![IMG_3CAC9EB9339A-1](https://user-images.githubusercontent.com/25839586/124569876-043fba00-de4f-11eb-85bd-9be5d87fd838.jpeg)

<hr/>

This is how it works on problematic devices.
Device info: Huawei Mate 20 Lite

Native browser
![Screenshot_20210706_112358_com android chrome](https://user-images.githubusercontent.com/25839586/124570343-76b09a00-de4f-11eb-8ed2-4da0c54094c3.jpg)

Chrome
![Screenshot_20210706_112914_com android chrome](https://user-images.githubusercontent.com/25839586/124570378-7d3f1180-de4f-11eb-98dd-f903483242aa.jpg)

**Comment by alimoncul** [comment]
Could someone add labels?

**Comment by berkbaski** [comment]
Could someone help me?

**Comment by jhoonb** [comment]
solution?
