### ISSUE TITLE
Loss of performance with series which have null values 

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#250]
## Codepen

https://codesandbox.io/s/18vx35nn2q

To reproduce the issue, you need to copy the content of  [this file](https://drive.google.com/open?id=1oc_kEVbCmFXzDNpTxlCaxUeK_JnwMOr6) and paste it on the first input. Then, copy the content of  [this file](https://drive.google.com/open?id=18q6dfCkh32yLkGBawKHJoqEXnVa8c0uI) and paste it on the second input. This allows you to reproduce the issue with my data.

Here is the exemple : 
![image](https://user-images.githubusercontent.com/46166884/50653804-0fb67f80-0f8b-11e9-9d16-62233ea015c1.png)

## Explanation

As you can see, once the two series are paste, there is a big lack of performances because of the second serie (it's composed of null values).
If I replace null values by 0, there is no lack of performance anymore.
You can test by replacing the second serie with [this file](https://drive.google.com/open?id=1Qxv043bseswvjYKaYyBs4hz2RtzzpDS-)

Any way to prevent this ? (I need the second serie to have null values)
I notice there is nevertheless a loss of performance with only the second series but less than with the two series.

**Comment by junedchhipa** [comment]
When you have null values in a series, the path is broken into single bits for each data-point as it cannot be drawn as a single path.

If you switch to `line` chart for such a scenario, you will notice a significant improvement in the performance. Also, changing `fill.type: 'solid'` will make a slight difference in performance.

**Comment by junedchhipa** [comment]
I think, instead of breaking path when null values are present, an option should be provided to join the null values. I will think about it.

**Comment by AurelReb** [comment]
> If you switch to `line` chart for such a scenario, you will notice a significant improvement in the performance. Also, changing `fill.type: 'solid'` will make a slight difference in performance.

thank you very much, it works perfectly !


> I think, instead of breaking path when null values are present, an option should be provided to join the null values. I will think about it.

Personally, I use the null values so that the line is cut at certain points.
Indeed, it can be a good idea of additional option

**Comment by vinoth1989** [comment]
I have data points of 1000+ in some scenarios most of the points are null values for their respective dates. I'm using a line chart with time series. performance of the graph is very low while getting more null points. sometimes page went to unresponsive mode.

**Comment by dalmenar** [comment]
+1
