### ISSUE TITLE
Stacked bar chart show zero values on chart, using current v3.27.1

### ISSUE THREAD

**Issue by Q-u-y** [apexcharts/apexcharts.js#2503]
Since the old thread was closed, I want to bring attention to this issue again since I don't believe it was fixed. I'm using v3.27.1 but the problem still showing up.

_Originally posted by @Q-u-y in https://github.com/apexcharts/apexcharts.js/issues/2454#issuecomment-862643046_

**Comment by junedchhipa** [comment]
Please post a codepen

**Comment by turkhero** [comment]
@Q-u-y is right. The problem still showing up

@junedchhipa codepen:
https://codepen.io/turkhero/pen/abJYymO

**Comment by vdechef** [comment]
The problem is still showing up in 3.27.3

**Comment by brianlagunas** [comment]
I confirmed this issue is still present. I will reopen the original issue.
