### ISSUE TITLE
error in apexchartjs

### ISSUE THREAD

**Issue by Sodiqmirzo** [apexcharts/apexcharts.js#2505]
![image](https://user-images.githubusercontent.com/65369403/124746578-79d48480-df3a-11eb-88c5-bfcfe437d54b.png)

![image](https://user-images.githubusercontent.com/65369403/124746634-8b1d9100-df3a-11eb-984f-30f22e071e76.png)

![image](https://user-images.githubusercontent.com/65369403/124746744-a6889c00-df3a-11eb-8eb5-588d50a0d3d7.png)

![image](https://user-images.githubusercontent.com/65369403/124746811-b86a3f00-df3a-11eb-8e12-5f520bca8be6.png)

please help me.

**Comment by junedchhipa** [comment]
`series.data` needs to be an array, not a number.
Please change
```javascript
this.series.push({ name: '...', data: [55] })
```

**Comment by Sodiqmirzo** [comment]
thank you bro))
