### ISSUE TITLE
Bug: Heatmap colors faded out?

### ISSUE THREAD

**Issue by anzuj** [apexcharts/apexcharts.js#2508]
# Bug report

## Codepen
[This codepen](https://codepen.io/anzuj/pen/rNmLxJo) demonstrates the color problem.

## Explanation
I have made a heatmap with series values ranging between 1-6 (often with 1 decimal) and a colorScale with 3 colors.

**What is the behavior you expect?**
I expect to see a heatmap with fully saturated hues between green/yellow/red as seen on the legend.
**What is happening instead?**
Chart has watered down colors. 
![chart demo](https://user-images.githubusercontent.com/36598337/124913179-1c4e3f80-dfef-11eb-9d7f-80643c28d47b.jpg)
**What error message are you getting?**
No error messages

**Comment by ScreamPlasmax** [comment]
Hello,
I encountered this problem too, you have to declare a color for the value 0 in one of your objects in plotOptions.heatmap.colorScale
