### ISSUE TITLE
Print/Download Multiple Charts in a pdf.

### ISSUE THREAD

**Issue by nikhilkumawat** [apexcharts/apexcharts.js#251]
**Is your feature request related to a problem? Please describe.**
I want to print multiple charts while click the button like dashboard report. 

**Describe the solution you'd like**
I searched multiple printing libaeries (jsPDF, etc) but couldn't got the proper Solulation. 
while we directly print the charts then for charts format is changed.

![image](https://user-images.githubusercontent.com/15088180/50675169-4e434d00-1012-11e9-938d-10c30e1caa4f.png)

Thanks

**Comment by junedchhipa** [comment]
This won't be possible directly.
You can try manual PDF generation by calling `svgUrl()` method of ApexCharts https://apexcharts.com/docs/methods/#svgUrl and then using it in jsPDF

**Comment by junedchhipa** [comment]
Closing this as exporting multiple charts to a single PDF is not directly achievable.

**Comment by junedchhipa** [comment]
Also, the `svgUrl()` method is deprecated and replaced with a new method `dataURI()`.
The `dataURI()` method will allow achieving PDF generation more easily.
Docs: https://apexcharts.com/docs/methods/#dataURI

**Comment by prasad1791** [comment]
@junedchhipa `dataURI()` method generates png image ,but how can we generate svg image using external functionality ?

**Comment by nelsoncelis** [comment]
Hi, how can I get the "dataURI" with react-apexcharts?

**Comment by junedchhipa** [comment]
@nelsoncelis An example of using `dataURI` with react can be accessed on this [codesandbox](https://codesandbox.io/s/react-datauri-stackoverflow-60110892-iryeq) demo

**Comment by lieyongchang** [comment]
is there any new method to Print/Download mulitple charts to jspdf ?

**Comment by PippoApps** [comment]
The codesandbox example triggers an error:
![Uploading image.png…]()

**Comment by V1CTOR-cloud** [comment]
It works perfectly, thanks
