### ISSUE TITLE
Error: <g> attribute transform: Expected number, when trying to resize windows browser on material tab

### ISSUE THREAD

**Issue by chicky095** [apexcharts/apexcharts.js#2514]
hi guys, I have problem when using apexchart on different material tab, when i try to resize the browser on different tab (not the tab displaying the chart) , it will hit Error: attribute transform: Expected number.
Seems like the apexchart responsive not working when im in different tab.
I have try both redraw method, but the error is show before i able to redraw.
Is there any workaround on this issues? Appreciate any possible solutions. Thanks

**Comment by guptarenu240489** [comment]
Getting same error. Any updates? @junedchhipa

**Comment by siddjellali** [comment]
Any update here ? please reopen
