### ISSUE TITLE
Having line chart and scattered chart together, data is not displayed on the chart

### ISSUE THREAD

**Issue by NITISH1-1** [apexcharts/apexcharts.js#2516]
I am using both scattered and line chart together, but it throws error. When I remove the line chart series JSON, charts successfully display data f scatter . Here is the attached error. Kindly help
![Screenshot (205)](https://user-images.githubusercontent.com/51140695/125404710-8cd0d400-e3d4-11eb-824e-727a9c966170.png)

**Comment by brianlagunas** [comment]
We will need a reproduction app to help.
