### ISSUE TITLE
Bar Chart Does not Show Markers

### ISSUE THREAD

**Issue by chrissyalbert** [apexcharts/apexcharts.js#2517]
# Bug report

## Codepen

 [Basic JS example](https://codepen.io/chrissyalbert/pen/jOmyVZz) This code works for regular javascript

Not working in Vue.js [CodeSandbox Vue example](https://codesandbox.io/s/vue-basic-example-forked-hf121)

## Explanation

- What is the behavior you expect?
- - I need it to work in Vue.js
- What is happening instead?
- - The markers do not show, also only get "Actual" in legend, not "Actual" "Expected"
- What error message are you getting?
- - No error messages

`<template>
  <div id="chart">
    <apexchart type="bar" height="350" :options="chartOptions" :series="series"></apexchart>
  </div>
</template>

<script>

import VueApexCharts from 'vue-apexcharts'
export default {
  name: 'Experiment',
  components: {
    apexchart: VueApexCharts,
  },
  data: () => ({
    series: [
      {
        name: 'Actual',
        data: [
          {
            x: '2011',
            y: 12,
            goals: [
              {
                name: 'Expected',
                value: 14,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          },
          {
            x: '2012',
            y: 44,
            goals: [
              {
                name: 'Expected',
                value: 54,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          },
          {
            x: '2013',
            y: 54,
            goals: [
              {
                name: 'Expected',
                value: 52,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          },
          {
            x: '2014',
            y: 66,
            goals: [
              {
                name: 'Expected',
                value: 65,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          },
          {
            x: '2015',
            y: 81,
            goals: [
              {
                name: 'Expected',
                value: 66,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          },
          {
            x: '2016',
            y: 67,
            goals: [
              {
                name: 'Expected',
                value: 70,
                strokeWidth: 5,
                strokeColor: '#775DD0'
              }
            ]
          }
        ]
      }
    ],
    chartOptions: {
      chart: {
        height: 350,
        type: 'bar'
      },
      plotOptions: {
        bar: {
          horizontal: true,
        }
      },
      colors: ['#00E396'],
      dataLabels: {
        formatter: function(val, opt) {
          const goals =
                  opt.w.config.series[opt.seriesIndex].data[opt.dataPointIndex]
                    .goals
            
          if (goals && goals.length) {
            return `${val} / ${goals[0].value}`
          }
          return val
        }
      },
      legend: {
        show: true,
        showForSingleSeries: true,
        customLegendItems: ['Actual', 'Expected'],
        markers: {
          fillColors: ['#00E396', '#775DD0']
        }
      }
    },
  }),
}
</script>`

compiles as

![Bar Chart Not Showing Markers](https://user-images.githubusercontent.com/16495155/125510530-ee0c9713-2e4a-4437-be01-26dcfa863cf1.png)

**Comment by brianlagunas** [comment]
We need a reproduction app that can replicate the issue.
