### ISSUE TITLE
Update Single Object Within Series Removes Others

### ISSUE THREAD

**Issue by lkgamor** [apexcharts/apexcharts.js#2519]
Hi all,

Please I have a 100% Stacked Bars Chart example.
I am currently trying to update an object within my series:

> 
       
     let dataValue = 1

     const option = {
		series: [
                   {
                    name: 'Louis',
                    data: [dataValue]
                   },
                   {
                    name: 'James',
                    data: [dataValue]
                   }
                ],
		chart: {
		type: 'bar',
		height: 120,
		stacked: true,
		stackType: '100%'
	  },
	  plotOptions: {
		bar: {
		  borderRadius: 4,
		  horizontal: true,
		  dataLabels: {
			position: 'top',
		  },
		}
	  },
	  dataLabels: {
		enabled: false,
		style: {
		  fontSize: '18px',
		  colors: ['#fff']
		}
	  },
	  yaxis: {
		labels: {
			show: false
		}
	  }
	}
 
      const barChart = new ApexCharts(document.querySelector('#chart'), option )
       barChart.render()

      setTimeout(()=> {
          dataValue++
          barChart.updateSeries([
		{
			name: 'Louis',
			data: [dataValue]
		}
	  ])
    }, 2000)

 but what happens is when I call the updateSeries method with an updated data value for one of the entries, the other entry is taken out of the chart.

Can anyone please assist with how to update just an entry of the stacked bar chart without having to pass both entries all over again.

**Comment by ordago** [comment]
https://apexcharts.com/docs/methods/#updateSeries

>Allows you to update the series array **overriding the existing one**

That's how it works. You can keep the series in a variable outside the options object and update the values there and then call `updateSeries`

**Comment by lkgamor** [comment]
That's a great suggestion @ordago 
Will try that out.

**Comment by brianlagunas** [comment]
Thanks for the suggestion @ordago
