### ISSUE TITLE
Sync charts have a shift wth the selection

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#252]
## Codepen

https://codesandbox.io/s/2pny3vvy8r

## Explanation

![image](https://user-images.githubusercontent.com/46166884/50683566-bdb93c80-1012-11e9-8486-360cd21c70f5.png)

When the y-axis legends of two sync charts are not the same size, it could be a shift between the selected point of the two charts. I think it's because sync selections are calculated compared to the distance from the left and not by timestamp sync

**Comment by junedchhipa** [comment]
Yes, exactly. You're right.
I need to document it on the website.

So, if you have a huge difference in yaxis labels size, you should fix the yaxis labels width with
```options
yaxis: {
  labels: {
    minWidth: 100
  }
}
```
for both charts

**Comment by AurelReb** [comment]
thanks for the workaround ! it works

Le ven. 4 janv. 2019 à 11:55, Juned Chhipa <notifications@github.com> a
écrit :
