### ISSUE TITLE
Y-axis label hiding in horizontal barchart

### ISSUE THREAD

**Issue by adhikari-anish** [apexcharts/apexcharts.js#2524]
I'm using apexcharts with vue (vue-apexcharts 1.6.1) and making horizontal barchart for UHD resolution (3840 x 2160). Right now the y-axis label font size is 40px and the labels are hiding. 
When I checked the devtools, **apexcharts-inner apexcharts-graphical** group is overflowing the svg. 

![image](https://user-images.githubusercontent.com/35035442/126298915-6f50cef0-0061-4f01-8e12-d0be4c035129.png)
![image](https://user-images.githubusercontent.com/35035442/126302183-a3599053-c774-4f61-ae1c-d79c4689bb13.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/35035442/126300530-476fdb1d-9f4c-4422-9041-ada320ca48fc.png)

How can I adjust my chart so that the apexcharts-inner doesn't overflow and full label is shown to match my design?
Is it possible to control width of my bar wrapper and y-axis label wrapper individually? 

My code:
```vue
<template>
  <div>
    <apexchart height="820" type="bar" :options="options" :series="series"></apexchart>
  </div>
</template>
```
```js
options() {
  return {
    chart: {
      type: 'bar',
      width: "100%",
      height: 820,
      toolbar: {
        show: false
      }
    },
    legend: {
      show: false
    },
    xaxis: {
      categories: this.categoryData,
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      },
      labels: {
        show: false
      }
    },
    yaxis: {
      opposite: true,
      labels: {
        style: {
          colors: ["#BEBFCB"],
          fontSize: "40px"
        }
      }
    },
    fill: {
      colors: ["#0E5CAD", "#EA5455", "#0396FF", "#7367F0", "#D939CD"],
      type: "gradient",
      gradient: {
        shade: "light",
        gradientToColors: [
          "#79f1a4",
          "#feb692",
          "#abdcff",
          "#ce9ffc",
          "#f6ceec"
        ],
        shadeIntensity: 1,
        type: "diagonal1",
        opacityFrom: 1,
        opacityTo: 1,
        stops: [0, 100]
      }
    },
    plotOptions: {
      bar: {
        horizontal: true,
        distributed: true,
        borderRadius: 10,
        barHeight: "70%",
        colors: {
          ranges: [
            {
              from: 0,
              to: 0,
              color: "pink"
            }
          ],
          backgroundBarColors: "#272A52",
          backgroundBarRadius: 10
        }
      }
    },
    dataLabels: {
      enabled: false
    },
    tooltip: {
      enabled: false
    },
    responsive: [
      {
        breakpoint: 3199,
        options: {
          chart: {
            height: 300
          },
          yaxis: {
            opposite: true,
            labels: {
              style: {
                colors: ["#BEBFCB"],
                fontsize: "14px"
              }
            }
          },
          plotOptions: {
            bar: {
              borderRadius: 4,
              colors: {
                backgroundBarRadius: 4
              }
            }
          }
        }
      }
    ]
  };
}
```

Thanks

**Comment by junedchhipa** [comment]
Does it work fine if the y-axis is not opposite?

**Comment by adhikari-anish** [comment]
@junedchhipa Thank you for your quick response. I tried it too, but the label is also hidden when the label is not opposite.

![image](https://user-images.githubusercontent.com/35035442/126307743-7b8daf50-0211-42c9-9e98-1d60c5af15e0.png)

**Comment by adhikari-anish** [comment]
I solved this issue by giving maxWidth to [yaxis](https://apexcharts.com/docs/options/yaxis/) labels and by manipulating my x-axis categories to be in [multiline](https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/#).

```vue.js
yaxis: {
          opposite: true,
          labels: {
            maxWidth: "auto",
            style: {
              colors: ["#BEBFCB"],
              fontSize: "40px"
            }
          }
        },
```

Thanks @junedchhipa
