### ISSUE TITLE
Mixed Chart Error - Line & Column

### ISSUE THREAD

**Issue by joecollett** [apexcharts/apexcharts.js#2525]
Been wracking my brain trying to workout why my chart has suddenly stopped working when no code has been changed - I've tried rolling back to a couple of the most recent versions to see if that makes any difference (react-apexcharts and apexcharts) but no luck.

Pretty much in this example you have two series which works great and the chart renders - https://apexcharts.com/javascript-chart-demos/mixed-charts/line-column/

But if you remove the line chart from the series nothing renders as you can see here - https://codepen.io/joecollett/pen/gOWxowR

This was previously working and I need to start with just a column chart and then the user can add the line charts when required.

The examples above are in javascript on the code pens but the having the exact same issue in the react code base as well.

**Comment by junedchhipa** [comment]
It renders but the stroke width was set to 0
Try this

```
stroke: {
  width: 4
}
```
