### ISSUE TITLE
React - bug in mixed chart, bar graph ball is not showing

### ISSUE THREAD

**Issue by alexandrermo** [apexcharts/apexcharts.js#2526]
Codepan example: https://codesandbox.io/s/react-basic-example-forked-ohq87?file=/src/App.js:2242-2253

- What is the behavior you expect?
 That the bar graph ball appeared on top of it

- What is happening instead?
Bar graph ball is not showing

- What error message are you getting?
None

**Comment by brianlagunas** [comment]
What do you mean by "bar graph ball"?
