### ISSUE TITLE
Tooltip always visible in realtime chart

### ISSUE THREAD

**Issue by vandercijr** [apexcharts/apexcharts.js#2528]
**Is your feature request related to a problem? Please describe.**
I would like to keep tooltip visible even when state change. In a realtime chart if I view an tooltip from a point, when data change tooltip has been hidden.	

**Describe the solution you'd like**	
If I want to read something in tooltip it should be visible until I move out mouse from data points 

**Additional context**

**Comment by narek00** [comment]
@vandercijr any updates? :)
