### ISSUE TITLE
Native legend class names conflict with native Foundation off-canvas class names

### ISSUE THREAD

**Issue by ultra86** [apexcharts/apexcharts.js#2529]
### Problem 

Foundation 6.x off-canvas (https://get.foundation/sites/docs/off-canvas.html) defines class names position-right, position-left, position-top, position-bottom globally. Thus, the Apex Charts legends do not display properly if using Foundation 6.x with off-canvas enabled because Apex is using those class names internally. The result is the legend positioning is incorrect (it's entirely not visible). Took me a while to figure out what's going on here.

### Solution for my case

- remove all definitions for position-bottom from foundation-sites/scss/components/_off-canvas.scss

### Recommended solution for Apex Charts development team:

- make the position-right, position-left, position-top, position-bottom class names more unique so they do not conflict with Foundation (IE apex-position-right, apex-position-left, etc.)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it in this [commit](https://github.com/apexcharts/apexcharts.js/commit/f88f9146517676623e0f0779eef69d497dbe727c)
