### ISSUE TITLE
svgjs.com link used as default namespace links to a scummy poker site

### ISSUE THREAD

**Issue by Ratsbew** [apexcharts/apexcharts.js#2530]
Although #2435 is fixed, svgjs.com is still used as default namespace in the current version. 

**This links to this page:**

<img width="1280" alt="Bildschirmfoto 2021-07-23 um 19 40 28" src="https://user-images.githubusercontent.com/87870776/126861445-b56c2451-5640-46ac-b101-86d6fe46056e.png">

**Related:** svgdotjs/svg.js#1202

<img width="1272" alt="apexcharts-demo" src="https://user-images.githubusercontent.com/87870776/126817759-bd357693-e6db-479c-875a-03fbe52f013a.png">

**Comment by brianlagunas** [comment]
This has been addressed. Thanks for reporting it.
