### ISSUE TITLE
How can i hide y and x axis on radar

### ISSUE THREAD

**Issue by piolet** [apexcharts/apexcharts.js#2533]
Hi all,

How can i hide this two lines on radar chart :
<img width="796" alt="Capture d’écran 2021-07-26 à 17 05 33" src="https://user-images.githubusercontent.com/2697871/127012906-c414c9f7-d646-475e-9818-b8fd37b514a9.png">

i tried with grid options and show false and some kind of parameters without success.

Do you have an idea ?
Thx

I use the last apexcharts's version and vue-apexcharts

**Comment by seyedrezamirkhani** [comment]
Hi, I used the pure JavaScript version of apexcharts and the y-axis labels disapears using

yaxis: { show: false }

However I face the same issue as piolet when trying to hide the yaxis label using angular-apexcharts . Please help
