### ISSUE TITLE
error get png image using dataURI method

### ISSUE THREAD

**Issue by zmarsel1** [apexcharts/apexcharts.js#2536]
# Bug report
the error occurs when trying to get a png image using the dataURI method (apexcharts.js 2.37.3 vestion)
note: works correctly in 2.36.3 

```
  const plotid = 'test';
      const { imgURI, blob } = await this.$apexcharts.exec( plotid, "dataURI", {});
```

## Explanation

- What is the behavior you expect?
  get imgage uri
- What is happening instead?
 return Incomplete or corrupt PNG file, blob is undefined
- What error message are you getting?
Error: <svg> attribute width: Expected length, "NaN".
Error: <svg> attribute height: Expected length, "NaN".
![2021-07-28 092958](https://user-images.githubusercontent.com/19661626/127275389-bb8a0c95-2d1e-4be3-ab56-b540a41a9c08.png)

**Comment by brianlagunas** [comment]
please provide a reproduction app
