### ISSUE TITLE
TypeError : e is null for firefox 

### ISSUE THREAD

**Issue by SandeepKapalawai** [apexcharts/apexcharts.js#2537]
Hi there @junedchhipa ,

i have a dashboard where i am displaying the apex charts and up on clicking on the side nav bar , i will be loading other page , so when ever i load another page from the dashboard in firefox , i m getting below error type error specific to firefox only 

![image](https://user-images.githubusercontent.com/5252966/98040935-28be3f00-1e47-11eb-9929-495bc68eb2c4.png)

Is there any solution for this, Thank you.

**Comment by Enase** [comment]
@junedchhipa any chance to make a release?

**Comment by mvtm-dn** [comment]
I apologize, but when we will get a new release with this issue fixed? Or, at least, could you please regenerate ./dist folder that we can install via npm i 'git+https://...'?

**Comment by morijenab** [comment]
hi @junedchhipa  does it fixed in the latest release ?
thanks
