### ISSUE TITLE
Unable to link annotation point to series via seriesIndex

### ISSUE THREAD

**Issue by dopla-dev** [apexcharts/apexcharts.js#2540]
# Bug report

I'm using react-apexcharts and am having trouble getting annotation points linked to a specific series on a multiseries line chart.

No matter what number I pass in for 'seriesIndex', the annotation point is linked to all series.

Additionally, on my code (but not on the codepen below), any seriesIndex > 0 throws the error : TypeError: Cannot read property 'seriesName' of undefined.

## Codepen

https://codesandbox.io/s/react-basic-example-forked-08i96?file=/src/App.js

## Explanation

- What is the behavior you expect?
- If we have series data structured like this: 

      series: [
        {
          name: "series-1",
          data: [30, 40, 45, 50, 49, 60, 70, 91]
        },
        {
          name: "series-2",
          data: [35, 45, 50, 55, 54, 67, 78, 100]
        }
      ]

And an annotation property in options which looks like this:

```
  annotations: {
    points: [
      {
        x: 1,
        y: 35,
        seriesIndex: 1
      }
    ]
  }
```

Then I would expect that to associate this annotation point with the series that is index 1 in the series array (series-2).

- What is happening instead?

No association is being made. If you toggle series-1 or series-2 on or off, the annotation point remains.

**Comment by Neophen** [comment]
Can confirm:
running with:
```
"apexcharts": "^3.28.1",
"vue-apexcharts": "^1.6.2",
```

This issue still exists, althougth the supposed fix from [https://github.com/apexcharts/apexcharts.js/pull/2444](https://github.com/apexcharts/apexcharts.js/pull/2444)
 is merged for them
