### ISSUE TITLE
Tooltip wrong with null values

### ISSUE THREAD

**Issue by aahahocevar** [apexcharts/apexcharts.js#2541]
In [this example](https://apexcharts.com/javascript-chart-demos/line-charts/null-values/) 

When I try to get the tooltip for the places 3, 4 or 5 always getting  the tooltip for 2 place 
![valuesNullTooltip](https://user-images.githubusercontent.com/2762732/127868631-96fd405a-f554-45a4-a568-7f7a239afb7c.gif)

It should get the tooltips of position 3, 4, and 5 respectively

**Comment by OlaAlsaker** [comment]
Happens to me as well. For some reason it only happens when my cursor is on the bottom part of the chart. If I start with my cursor _above_ the chart, and then move it down, the issue does not occur.
