### ISSUE TITLE
chart.updateSeries() giving error in chart series

### ISSUE THREAD

**Issue by tnsankaran** [apexcharts/apexcharts.js#2545]
This is my code and I am getting error while update the chart series using windows.interval. Can you help me what wrong with the config. The code using google app script 

Sample data format and error is as provided in the link.

data format is:
![image](https://user-images.githubusercontent.com/60739853/128603159-1326af29-8f6e-4ec2-a84a-eca105d216b0.png)

actual chart result
![image](https://user-images.githubusercontent.com/60739853/128603128-2bfc3eda-d83c-403b-ab0a-4648144bd3d7.png)

after update series
![image](https://user-images.githubusercontent.com/60739853/128603093-cd42aa4f-36f1-47a4-b347-41388cbfbadb.png)

Code : 
`<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

<script>
var datas = []
var cat = []

async function func() {
  const e = await new Promise(r => {
    google.script.run.withSuccessHandler(r).getGA_all();
  });
  
 e.map(function(r) {

  datas.push(r)

 })
  console.log(e);

}
func()

var options = {
          series: [{
          data: datas,
          name: "Sessions",
           type: 'line',
        },
        ],
          chart: {
          id: 'realtime',
          height: 350,
         
          animations: {
            enabled: true,
            easing: 'linear',
            dynamicAnimation: {
              speed: 1000
            }
          },
          
          toolbar: {
            show: false
          },
          zoom: {
            enabled: false
          }
        },
        dataLabels: {
          enabled: false
        },
        stroke: {
          curve: 'smooth',
          width: [3, 6],
        },
        title: {
          text: 'Radio Ad. Campaign Chart',
          align: 'left'
        },
        xaxis: {
        type: 'datetime'     
        },
   
        dataLabels: {
          enabled: true,       
        },
        yaxis: {
          title: {
            text: 'Sessions',
          }
          },
        legend: {
          show: true,
           position: 'top',
      horizontalAlign: 'center',
      showForSingleSeries: true
        }
  }
  
 
        var chart = new ApexCharts(document.querySelector("#chart"), options);
        chart.render();
      

        window.setInterval(function () {

        google.script.run.withSuccessHandler(function(data){

            datas.push([data[0],data[1]])

        
      

        }).latestdata();

        chart.updateSeries([{
          data: datas
          }],true)
      
         console.log(options)
      }, 60000)
</script>

`

**Comment by brianlagunas** [comment]
Please provide a reproduction app that can duplicate the problem.
