### ISSUE TITLE
17th Aug instead of 1 Aug displayed under graph

### ISSUE THREAD

**Issue by Shelvadim** [apexcharts/apexcharts.js#2549]
# Bug report
It shows 17th Aug instead of 1 Aug under graph

![image](https://user-images.githubusercontent.com/27940206/129072453-00919861-2eca-46ae-909b-5ec9ed638cc1.png)

## Codepen
https://codepen.io/apexcharts/pen/rqWeBX

## Explanation
- What is the behavior you expect?
It should show 01 Aug.

- What is happening instead?
it shows 17 Aug
- What error message are you getting?
no error messages

**Comment by junedchhipa** [comment]
It's Aug 2017
Can be changed with date formatters.
