### ISSUE TITLE
With multiple breakpoints, options are not applied hierarchically

### ISSUE THREAD

**Issue by mestaritonttu** [apexcharts/apexcharts.js#255]
## Codepen

https://codepen.io/anon/pen/BvxNmL

## Explanation

I have tweaked our trusty responsive codepen to have two breakpoints, 481 and 1000. Datalabels are displayed by default and the 1000 bp hides them. However, if you resize from desktop width directly to 480 px, the datalabels will remain visible (and the bars will not change to vertical).

More detailed steps:

1. In your browser's responsive design view, set the width to 480.
2. Exit the responsive design view.
3. Enter the responsive design view again and observe the issue.

A curious behaviour is that if you go to 999 px width and then to 480, the chart will render as expected. Only direct resizing to 480 will guarantee seeing the issue.

**Comment by junedchhipa** [comment]
I had a quick look at the codepen, and indeed something looks wrong.
Will have a detailed look, and get back soon.
