### ISSUE TITLE
Bug with dotnut chart

### ISSUE THREAD

**Issue by FrantzUml** [apexcharts/apexcharts.js#2551]
Creating a 'dotnut' chart, i get error "Uncaught (in promise) TypeError: this.xyRatios is null".

And when i create a 'pie' chart whith same options, all is correct.

I use ApexCharts v3.27.3 and my code is :
let options1 = { labels: ["cat 1","cat 2","cat 3"], series: [44, 55, 41], legend: {position: 'bottom'},
          chart: {type: 'dotnut', width: '100%', height:'350px'}, plotOptions: {pie: {dotnut: { size: '30%'}}} };
let chart1 = new ApexCharts(document.getElementById("fortest"), options1);
chart1.render();

Changing to 'pie' chart, all is correct :
let options1 = { labels:  ["cat 1","cat 2","cat 3"], series: [44, 55, 41], legend: {position: 'bottom'},
          chart: {type:'pie',width:'100%',height:'350px'} };

**Comment by junedchhipa** [comment]
Chart type should not  be`dotnut`, it has to be `donut`
