### ISSUE TITLE
Have multiseries column chart with different width and origin to each series

### ISSUE THREAD

**Issue by danieljames-dj** [apexcharts/apexcharts.js#2557]
Hi, I would like to request a feature - by which we can have multiseries column with different width and origin to each series.

Here is my use case:
I want a multiseries column chart with 2 series, out of which 1 series should have half width of the other one and should be placed in the middle of first one.

**Comment by brianlagunas** [comment]
There is not enough context or information in your request for us to determine what exactly you are asking for or expecting.
