### ISSUE TITLE
toggleSeries by yaxis in rangeBar chart

### ISSUE THREAD

**Issue by fortionfortune** [apexcharts/apexcharts.js#2559]
In rangeBar charts `toggleSeries` method by name works well.
But there is a lack of an intuitive option - filter series by clicking on the legend on the yaxis.
I had to do this manually by filtering (with JS `map` and `filter` functions) series data array in each `x` value.
![image](https://user-images.githubusercontent.com/63502694/129492086-0f92dc49-1fc4-48d4-9e7a-dc31d6e816a9.png)

**Comment by brianlagunas** [comment]
Those are labels, not a legend. They are provided by your data. Therefore you cannot simply toggle them to remove them from your data.
