### ISSUE TITLE
Compilation error TS1122 in apexcharts.d.ts

### ISSUE THREAD

**Issue by Vvelghe** [apexcharts/apexcharts.js#256]
## Issue

I can't import apexcharts on my angular 5.2 project

## Explanation
After doing 
`npm install apexcharts --save`

When i tried to import the module 
`import {ApexCharts} from 'apexcharts'`

I've got an error : 

> TS2305: Module '"apexcharts"' has no exported member 'ApexCharts'.

![apexchart_error_exported_member](https://user-images.githubusercontent.com/8938939/50771362-bbf9ae00-128a-11e9-97f0-5483c55728a3.png)

So i tried to import all the module
`import * as ApexCharts from 'apexcharts'`

But now, i've another error because the `apexcharts.d.ts` contains an error, it is not compiling.

> ERROR in node_modules/apexcharts/apexcharts.d.ts(526,16): error TS1122: A tuple type element list cannot be empty.

![apexchart_error](https://user-images.githubusercontent.com/8938939/50771192-2f4ef000-128a-11e9-9f19-3a3b0e39c587.png)

**Comment by junedchhipa** [comment]
Can you try the default import ?
```javascript
import ApexCharts from 'apexcharts'
```

Also, I have fixed the issue in typings `colors: string[]`

**Comment by junedchhipa** [comment]
Closing this and also added some new types in the apexcharts.d.ts file.
If you find any more issues, please let me know.

**Comment by sugihartolim** [comment]
I'm running into the same problem with Angular 7.
`import ApexCharts from 'apexcharts' ` 
will show 
`[ts] Module '"apexcharts"' has no default export. [1192]`

**Comment by junedchhipa** [comment]
```javascript
import * as ApexCharts from 'apexcharts';
```
should work if the typings don't have any compilation errors.

**Comment by sugihartolim** [comment]
> import * as ApexCharts from 'apexcharts';
should work if the typings don't have any compilation errors.

Just tried this, no compilation errors, but this error message showed up on the console:

`ERROR TypeError: apexcharts__WEBPACK_IMPORTED_MODULE_2__ is not a constructor
    at HomeComponent.push../src/app/home/home.component.ts.HomeComponent.ngAfterViewInit 
`

The offending line is 

`const chart = new ApexCharts(document.querySelector('#chart'), this.options);`

**Comment by sugihartolim** [comment]
https://webpack.js.org/guides/author-libraries/#expose-the-library

I wonder if this is the problem...

**Comment by ivelfan** [comment]
I use Angular 7 and I do this thing : 
```ts
// @ts-ignore
import ApexCharts from 'apexcharts';
```
It'a a bit tricky but compiler let me in.

**Comment by junedchhipa** [comment]
@sugihartolim 
ApexCharts is also exported as `commonjs` in the dist directory.

Can you also please try 
```javascript
import ApexCharts from 'apexcharts/dist/apexcharts.common.js'
```

**Comment by sugihartolim** [comment]
That one didn't work. It compiles just fine, but vscode gives the following warning on the import: 

> Could not find a declaration file for module 'apexcharts/dist/apexcharts.common.js'. '[redacted]/node_modules/apexcharts/dist/apexcharts.common.js' implicitly has an 'any' type.  Try `npm install @types/apexcharts` if it exists or add a new declaration (.d.ts) file containing `declare module 'apexcharts/dist/apexcharts.common.js';`ts(7016)

The console shows this error message, and the charts didn't show up: 

> ng:///AppModule/HomeComponent_Host.ngfactory.js:5 ERROR TypeError: apexcharts_common_js_1.default is not a constructor

**Comment by junedchhipa** [comment]
An angular wrapper for ApexCharts has just released 3 days ago - https://github.com/morrisjdev/ng-apexcharts

Maybe, that brings an end to all the import issues?

**Comment by osnoser1** [comment]
Hello, add to `angular.json`:  `"node_modules/apexcharts/dist/apexcharts.min.js"` and import into the component this way: `import 'apexcharts';`

**Comment by sugihartolim** [comment]
@osnoser1  Thank you for the additional solution. It works fine out of the box with angular 7 cli. 

@junedchhipa  The angular wrapper doesn't work when i tried it this week. Didn't have time to dig around yet. Maybe we shouldn't recommend the thing on the front page until the kinks are worked out first? Thanks.

**Comment by DiegoVeronezi** [comment]
> Thanks @sugihartolim. I reply to this config and works for me. 

tsconfig.json:
```
"compilerOptions": {
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "es2015"
  }
```
* 'module: es2015' It's working!

**Comment by lixaotec** [comment]
@DiegoVeronezi can you share your package.json?
I´ve been struggling to get it compiled with aot, 

ERROR in ./node_modules/ng-apexcharts/fesm5/ng-apexcharts.js
Module build failed: Error: Debug Failure. False expression.

"apexcharts": "~3.11.2",
"ng-apexcharts": "~1.2.1",

**Comment by mwassAndroid** [comment]
> @DiegoVeronezi can you share your package.json?
> I´ve been struggling to get it compiled with aot,
> 
> ERROR in ./node_modules/ng-apexcharts/fesm5/ng-apexcharts.js
> Module build failed: Error: Debug Failure. False expression.
> 
> "apexcharts": "~3.11.2",
> "ng-apexcharts": "~1.2.1",

@DiegoVeronezi  did you manage to build for production, am also getting the same error though it runs with ng serve

**Comment by apsonshrestha** [comment]
this worked for me:
adding "**scripts": ["node_modules/apexcharts/dist/apexcharts.min.js"]** on angular.json as below

"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            ...
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              **"node_modules/apexcharts/dist/apexcharts.min.js"**
            ]
          },
          "configurations": {
            ...
          }
        },
        "serve": {
          ...
        },
        "extract-i18n": {
          ...
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            ...
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [**"node_modules/apexcharts/dist/apexcharts.min.js"**]
          }
        },
        "lint": {
		...
        },
        "e2e": {
          ...
        }
      }

**Comment by subash01** [comment]
I am getting this error in the compilation of my Angular app while using apex js.
![image](https://user-images.githubusercontent.com/29374169/158170553-0854c827-c3b8-4aa9-ab2f-d519726eeec1.png)
I checked a lot of resource I could not find what I need to resolve it, kidly guide me

**Comment by hiteshprasad23** [comment]
I have updated my project from Angular 8 to Angular 9.

I am getting the below error after "ng serve"

<img width="718" alt="apx" src="https://user-images.githubusercontent.com/48951478/207036456-f6442c74-1e80-4234-b48a-82a208280109.png">

**Comment by dsa-davoudi** [comment]
add this into your Project 
import * as ApexCharts from 'apexcharts';
instead : 
import ApexCharts from 'apexcharts';
