### ISSUE TITLE
Reset zoom doesn't rescale Y-Axis after updateOptions() has been called

### ISSUE THREAD

**Issue by veitvw** [apexcharts/apexcharts.js#2560]
steps to reproduce:
1. open https://codepen.io/Bongobernd/pen/vYmwNoe
2. click "update" button to update series and color via updateOptions()
3. zoom in on some values
4. click "Reset Zoom" button
--> X-Axis is rescaled, y-axis isn't until you click "Reset Zoom" button again

**Comment by brianlagunas** [comment]
This is working as expected. Your updateOptions call changes the data set, which results in a recalculated y axis minimum. If you want the same minimum y-axis scale, just set it via your options.
