### ISSUE TITLE
Line Chart fills when colors are used

### ISSUE THREAD

**Issue by EdwardCaulfield** [apexcharts/apexcharts.js#2562]
# Bug report

Using apexcharts 3.27.3

When using the line chart, if I have only one line and I use a pre-defined pallete, then it shows the line just fine.
```
      @chart_options = {
        noData: {
          text: I18n.t('not_enough_data', scope: 'data_analyses.report'),
          align: 'center',
          verticalAlign: 'middle',
          offsetX: 0,
          offsetY: 0,
          style: {
            # color: undefined,
            fontSize: '14px',
            # fontFamily: undefined
          }
        },
        theme: 'palette1',
        fill: {
          opacity: 0.0
       }
      }
```

![grafik](https://user-images.githubusercontent.com/2613598/129741832-a5c66b90-864e-4bf7-9c83-c960a1d2e8da.png)

 However, if I change the colors with parameters:
```
      @chart_options = {
        noData: {
          text: I18n.t('not_enough_data', scope: 'data_analyses.report'),
          align: 'center',
          verticalAlign: 'middle',
          offsetX: 0,
          offsetY: 0,
          style: {
            # color: undefined,
            fontSize: '14px',
            # fontFamily: undefined
          }
        },
        theme: 'palette1',
        colors: [DARK_BLUE, AJAX_CHARTS_GREEN, AJAX_CHARTS_ORANGE],
        fill: {
          opacity: 0.0
       }
      }

```

I get a fill pattern under the line.

![grafik](https://user-images.githubusercontent.com/2613598/129741656-371dae51-bf0a-4099-b176-94ba7e880259.png)

## Explanation  

- What is the behavior you expect?  

  I expect that if I add colors that override a template, that either the line chart doesn't create a fill below the line or I have some means of stopping this with a configuration parameter.

- What is happening instead?  

  I am getting a fill pattern under the line on the chart.

- What error message are you getting?  
No error messages are received.

**Comment by brianlagunas** [comment]
Please provide a reproduction app

**Comment by xantha01** [comment]
did you find a solution, also getting the same issue
![Annotation 2025-01-05 173244](https://github.com/user-attachments/assets/b3f461d8-308b-469e-be3a-89c54f0177a9)

**Comment by RoccoKing98** [comment]
I am sorry - I think we determined a solution but it has been so long that I don't remember what we did. I also no longer work at the company where this issue was experienced, so I no longer have access to the code to dig out our solution.
