### ISSUE TITLE
DonutChart: remove reliable spacing/padding from chart

### ISSUE THREAD

**Issue by pleinx** [apexcharts/apexcharts.js#2568]
# Bug report
![image](https://user-images.githubusercontent.com/11060882/130221937-36c5efe1-5773-440a-8439-cc1ab7b518da.png)

## Codepen

https://codepen.io/pleinx/pen/gOWVjbY

## Explanation

- What is the behavior you expect?
A chart without any useless padding/spacing on every side

- What is happening instead?
Generates spacing. If you try to make this responsive, the spacing is dynamic so its inpossible to workaround with negative positioning/spacings.

**Comment by welly** [comment]
Wanted to open this up again as I'm curious as to how this can be done with radialBar charts.

Thanks!
