### ISSUE TITLE
toggleSeries not working on Pie Chart

### ISSUE THREAD

**Issue by Micene09** [apexcharts/apexcharts.js#257]
## Codepen

https://codepen.io/Micene09/pen/REJBWW

## Explanation

Labels and serie names are correctly defined but, toggleSeries is not working and the serie selected in the example provided never disappear.
Looking at the debugger, seems that there is something wrong about a `data:realIndex` attribute...

**Comment by junedchhipa** [comment]
`toggleSeries` is intended to hide/show series in a multi-series chart.
Currently, pie/donut charts of ApexCharts are not multi-series. Those are just dataPoints of a single series.
Also, if you notice that in axis charts (line/column), clicking on legend hides/shows the series, but not in the case of pie/donuts.
Hence, `toggleSeries` will not work in those charts.

Maybe, in the future, we will implement it based on the feedback.

**Comment by Micene09** [comment]
So, the only way to make it work should be remove the dataPoint from the original serie and `updateSeries`...

**Comment by junedchhipa** [comment]
Yes, I was going to suggest that 😀

**Comment by Micene09** [comment]
Generally works but, i have 2 charts (pie + bar) with an external-shared Legend.
In this use-case, it works good for data and legend but colors are misaligned...

It's just a work-around...and i hope you will fix this issue soon.

**Comment by junedchhipa** [comment]
Alright, I will add this to the roadmap

**Comment by CSondergaard** [comment]
Any update on when this will be implemented?

**Comment by akmur** [comment]
I agree this would be nice and good looking.

Can anyone perhaps give me a working example of how to use the updateSeries in React?

When I try to simply setState, I get an error in console, although the series and the graph is updated correctly.

```
can't access property "getAttribute", t.parentNode is null
```

**Comment by bakuryukhanh** [comment]
any update on this feature

**Comment by vuckele** [comment]
Hope that this will become an option

**Comment by veco9** [comment]
Any update on this feature?

**Comment by mcsantos7** [comment]
Still waiting for this feature... Any update?
