### ISSUE TITLE
Performance draining when using dropshadows to charts

### ISSUE THREAD

**Issue by ar-lk** [apexcharts/apexcharts.js#2570]
# Bug report

## Explanation

I'm creating react dashboard for show dynamic data visualization (not real time updating). I'm using drop shadow option for all of my ApexCharts (ex- I'm using Bar, Pie, Line charts). when charts rendering it's using lots of CPU performance to render charts. it causes app to lagging when charts loading. Is there any solution for this? how can i fix this?

**Comment by brianlagunas** [comment]
Drop shadows are inherently very expensive. Without a repdouction app, we can't help you.
