### ISSUE TITLE
Radial Bar Animations to lower numbers snappy and inconsistent depending on value

### ISSUE THREAD

**Issue by fresh4** [apexcharts/apexcharts.js#2578]
### Description

The animations, at least for the radial gauge, follow the animation duration property sometimes, but other times is just either transitions way faster than expected, or just blinks to the second point.
For example: 0 to 100 transitions as expected.
100 to 0 the bar just disappears immediately.
0-50 works. 50 to 10 moves way too quickly.
I'm not certain on the pattern, but it looks like the further from a high number down to a low number it transitions, the jankier/jumpier the animation. 
I'm also not sure if it's just my animation variables, but I kinda doubt it.

### Steps to Reproduce
Using the below codepen, just test out various transition values
1. Use the text box in the upper left corner to enter a number (100) and press the button. It'll transition smoothly
2. Enter the number 0 and press the button. It'll just disappear.
3. Test any transition range. Large numbers going down to a lower number will jump or glitch.

### Expected Behavior
A smooth transition from a large to small number as it is from a small to a large number
### Actual Behavior
Jumpy cuts from high to low numbers, but smooth transitions from low to high numbers.
### Reproduction Link
https://codepen.io/Fresh4/pen/XWgbzmm

**Comment by junedchhipa** [comment]
As tested on the latest version 3.54.1, this is fixed
