### ISSUE TITLE
Special Markers doesnt work when markers.

### ISSUE THREAD

**Issue by PatrykMaternicki** [apexcharts/apexcharts.js#2579]
### Description

When developer want to special-markers, but he set zero size for markers  and for special markers set eq: seven size. The graph didn't display special markers. 

Example: https://codepen.io/shiroUmizake/pen/KKqVKLP

### Steps to Reproduce

1. Change size of marker to zero.
2. For special markers set size eq: 4
3. Start rendering function

### Expected Behavior
Special markers should be display.

### Actual Behavior
Special markers didn't show it.

### Reproduction Link
https://codepen.io/shiroUmizake/pen/QWgywLe

**Comment by brianlagunas** [comment]
The marker is there, it's just located at 0,0 which is off screen.  Change the x and y values to position the annotation and you'll see it render properly. In this example `x: 3, y: 3`

![image](https://user-images.githubusercontent.com/835562/132734963-b178188b-9de1-483c-8b49-4a3897562122.png)
