### ISSUE TITLE
Bar Chart bar Crop after zoom at x - category enable

### ISSUE THREAD

**Issue by AfzaalAhmadCodeDesk** [apexcharts/apexcharts.js#2580]
Description
When  want to create bar chart with x category using zoom option bar are cropped and data labels are not shown.
Example : https://codepen.io/AfzaalAhmadCodeDesk/pen/abwdvVd

In my client website i have got the issue that is also attached in which same issue

![After Zoom Labels and Bars are not shown](https://user-images.githubusercontent.com/89778514/131328644-812a7a6c-1af0-40af-ae80-047fcbc23638.PNG)

In the official documentation just given the padding option using grid but i want to show 2 to 3 chart in one row like attached screen short.
How i can handle this

![No of Bar Charts](https://user-images.githubusercontent.com/89778514/131327251-f245fc67-e871-4643-8643-c80d29da7218.PNG)

**Comment by AfzaalAhmadCodeDesk** [comment]
Hey i hope your are fine. Please guide me about this issue how i can fix bar crop issue

**Comment by brianlagunas** [comment]
This is a known issue which is documented here: https://apexcharts.com/docs/zooming-in-category-x-axis/

You'll need to set the left and right padding to a greater number. In your example 50, 50 works.

**Comment by AfzaalAhmadCodeDesk** [comment]
hey
I hope you are doing well
Thanks for your response
In my case series no is dynamic means no of series are one,two,three or more than three 
Everything is amazing just after zoom bar is cropping and i can't handle this using padding option
Please guide me any other way can i  fix bar crop issue against dynamic no of series
Thanks in advance
