### ISSUE TITLE
Timeline chart grid column color not working

### ISSUE THREAD

**Issue by GeorgEduard** [apexcharts/apexcharts.js#2591]
On  any chart, if xaxis  type is set to 'datetime', grid column customisation is not working. If xaxis type has no setting, or other than 'datetime', there is no issue.

### Steps to Reproduce

In the options, set the xaxis type to 'datetime';
In the grid column section, add some colors or other styling -  nothing happens;
Remove xaxis type, or set type="category" - styling is now appearing;

### Expected Behavior

The columns should change color, or whatever valid setting I add there.

### Actual Behavior
Nothing happens if you change something there.

### Reproduction Link

https://codepen.io/georgedy/pen/OJgXPeG

**Comment by rhysdavies1994** [comment]
+1; I'm seeing this same issue. Colors are not being set for 'datetime' type.

It seems as though the grid lines are being set correctly for 'datetime' axis when `grid.xaxis.lines` is set to true;
Though colours are not being set when using `grid.column.colors` with the 'datetime' axis

**Comment by cx-keeko** [comment]
+1

**Comment by cx-keeko** [comment]
+1 - Issue occurs exclusively with `type: "datetime"`.

**Comment by annLiu310** [comment]
+1 - Issue occurs exclusively with type: "datetime".

**Comment by annLiu310** [comment]
+1 - Issue occurs exclusively with type: "datetime".
