### ISSUE TITLE
Panning movement is not working smoothly

### ISSUE THREAD

**Issue by kailasb10** [apexcharts/apexcharts.js#2596]
I've shown the area chart in the bootstrap model popup. When I zoom the data & moving with pan it not moving smoothly

### Steps to Reproduce

1. Apex area chart is shown in the popup 
2. Click on zoom OR zoom specific area
3. Click on hand/pan to move horizontally left OR right it move smoothly. after relating of mouse click then it moved.

### Expected Behavior
It should move smoothly right OR left while moving the mouse.

### Actual Behavior
It not moving with mouse selection it moved when the mouse release.

**Comment by brianlagunas** [comment]
No reproduction link provided

**Comment by kailasb10** [comment]
Does it work smoothly for you? & chart moves when you move the mouse?

**Comment by kailasb10** [comment]
I've reproduced it & recorded a video.
the image is given from [URL](https://github.com/apexcharts/apexcharts.js#interactivity) like this it moves smoothly with mouse movement.

- In the video, I've changed the bar graph to area
- Then zoom some area
- Selected pan and try to move the graph but it works on mouse release, not with mouse movement.

![image](https://user-images.githubusercontent.com/82386026/132450845-2b6a8f66-6664-4ef1-968d-6b7d8d1b9d22.png)
https://user-images.githubusercontent.com/82386026/132451158-09decd8c-ad2c-42b2-b73f-2784c0bfc674.mp4

**Comment by kailasb10** [comment]
> No reproduction link provided

Does it work smoothly for you? & chart moves when you move the mouse?

**Comment by kailasb10** [comment]
> No reproduction link provided

I've reproduced it & recorded a video.
the image is given from [URL](https://github.com/apexcharts/apexcharts.js#interactivity) like this it moves smoothly with mouse movement.
![image](https://user-images.githubusercontent.com/82386026/132450845-2b6a8f66-6664-4ef1-968d-6b7d8d1b9d22.png)

**Reproduce Steps:**
- In the video, I've changed the bar graph to area
- Then zoom some area
- Selected pan and try to move the graph but it works on mouse release, not with mouse movement

https://user-images.githubusercontent.com/82386026/132451158-09decd8c-ad2c-42b2-b73f-2784c0bfc674.mp4

**Comment by kailasb10** [comment]
you are not answered in the previous post. that's why created it here. I think you are interested in the issues posted by developers. without giving a proper reply to the post. 

At least give a proper response so I can understand it. non of your replied useful.
