### ISSUE TITLE
Append data to candlestick chart doesn't work 

### ISSUE THREAD

**Issue by FernandesWilliam** [apexcharts/apexcharts.js#2599]
Hi, 
First sorry if my english is not well.

I've got a problem with adding data on candlestick chart. 
When I try to insert a new data to existing chart. 
This is my existing data. It work I fill 20 candles when this is called 
<img width="705" alt="Capture d’écran 2021-09-08 à 10 57 07" src="https://user-images.githubusercontent.com/57043613/132479484-8cff35bf-89b0-4151-87e4-5c39b0f801fe.png">
then 1 minutes after I try to add another ( the latest ) 
<img width="635" alt="Capture d’écran 2021-09-08 à 10 59 30" src="https://user-images.githubusercontent.com/57043613/132479532-3cba8744-2ce6-41ab-acc5-96d9638c959f.png">
And i got this in the inspector 
![Capture d’écran 2021-09-08 à 10 58 35](https://user-images.githubusercontent.com/57043613/132479723-f421fcb3-4b99-4978-a084-c4dfd691d0c2.png)
![Capture d’écran 2021-09-08 à 10 58 42](https://user-images.githubusercontent.com/57043613/132479734-7a7f8c44-16b1-42a6-be74-dcb756431f5d.png)

I've got 0 errors, only when i check the option data's  chart, I can see that all my datas are redirected in the x-axis array.
I can't understand why this happen

**Comment by brianlagunas** [comment]
No reproduction link provided
