### ISSUE TITLE
Bar chart rendering is causing a lot of "Style recalculation"

### ISSUE THREAD

**Issue by mamasselin** [apexcharts/apexcharts.js#260]
## Description

Bar chart rendering is causing a lot of "Style recalculation". The style recalculation seems mostly caused by the `getBBox` call.

For a simple layout:

- 730 datapoints
- Screen is locked for about 1.5 seconds

![image](https://user-images.githubusercontent.com/16145977/50910366-a952b680-13fb-11e9-9f68-3496d379669d.png)

Zoomed to one "Style recalculation" span:

![prolier-details-alone](https://user-images.githubusercontent.com/16145977/50909205-5d067700-13f9-11e9-8950-069a2258a7da.png)

It is even worst when having a chart inside a Vuetify `v-card` (I assume because of the more complex layout).

- 730 datapoints
- Screen is locked for about 10 seconds

![image](https://user-images.githubusercontent.com/16145977/50910588-1bc39680-13fc-11e9-846d-dc916ebecfd8.png)

Zoomed to one "Style recalculation" span:

![profiler-details-in-card](https://user-images.githubusercontent.com/16145977/50909195-5a0b8680-13f9-11e9-8961-54d91662b0dc.png)

## Artifacts

Example: https://codesandbox.io/s/ppvxyl6p57

Profiling results: [apex-profiler.zip](https://github.com/apexcharts/apexcharts.js/files/2741468/apex-profiler.zip)

**Comment by junedchhipa** [comment]
`getBBox` is a function of SVG.js. 
If it is causing performance issues, I will try some native alternatives.

**Comment by mamasselin** [comment]
Please check out PR #347

**Comment by junedchhipa** [comment]
Closing this for now. 
I am going to update to the latest version of `svg.js` where they have performance improvements.
