### ISSUE TITLE
Panning not working smoothly

### ISSUE THREAD

**Issue by kailasb10** [apexcharts/apexcharts.js#2602]
Ref [#2596](https://github.com/apexcharts/apexcharts.js/issues/2596)
I've reproduced it & recorded a video. I've 5K+ records on x-axis. 
Is the Number of records will make any difference?
Like this example I want it to move smoothly on pan selection
https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis/

**Reproduce Steps:**
- In the video, I've changed the bar graph to area
- Then zoom some area
- Selected pan and try to move the graph but it works on mouse release, not with mouse movement

https://user-images.githubusercontent.com/82386026/132451158-09decd8c-ad2c-42b2-b73f-2784c0bfc674.mp4

_Originally posted by @kailasb10 in https://github.com/apexcharts/apexcharts.js/issues/2596#issuecomment-914929392_

**Comment by brianlagunas** [comment]
Please do not double post

**Comment by kailasb10** [comment]
you are not answered in the previous post. that's why created it here. I think you are interested in the issues posted by developers. without giving a proper reply to the post. 

At least give a proper response so I can understand it. non of your replied useful.

**Comment by kailasb10** [comment]
you are not answered in the previous post. that's why created it here. I
think you are interested in the issues posted by developers. without giving
a proper reply to the post.

At least give a proper response so I can understand it. non of your replies
are useful.
