### ISSUE TITLE
Bar Graph are showing too thin

### ISSUE THREAD

**Issue by kailasb10** [apexcharts/apexcharts.js#2603]
Bar chart is build with multiple series for only 81 records/points but the bar is showing too thin

### Steps to Reproduce

1. Codepen link given

### Expected Behavior
The bar should be at least show with proper width.
should be view like in this image at least
![image](https://user-images.githubusercontent.com/82386026/132656194-c8b6da9e-3707-4500-b05e-b6960a5eaec4.png)

### Actual Behavior
Showing too thin
![image](https://user-images.githubusercontent.com/82386026/132656374-2c308aa4-6ae7-429a-be34-08cc65f265e8.png)

### Reproduction Link
https://codepen.io/kailas-b-insnapsys/pen/RwgpabK

**Comment by brianlagunas** [comment]
This is not a bug. The bar chart is correctly representing your data based on the x axis scale. If you zoom in you can see the time x-axis correctly shows your data

![image](https://user-images.githubusercontent.com/835562/132920782-b2a3e07c-28d7-4dd2-a2f6-0c206a68618a.png)

Maybe you want to try a different chart type like an "area" chart to represent your data?

**Comment by kailasb10** [comment]
I'm using a bar chart. thanks for the response.
