### ISSUE TITLE
Don't rerender the chart while user is clicking on the brush

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#261]
Is there any way to wait the user stop clicking on the brush chart to rerender the main chart ?
When ther is big series, scrolling or zooming with the brush chart can be slow because of constant rerendering of the main chart.
Maybe by adding an option in "selection" waiting for a mouseup to perform the associated function

**Comment by junedchhipa** [comment]
Turning off the `chart.animations.dynamicAnimation : false` in the target chart will improve performance.

**Comment by vitalijm** [comment]
I agree, this feature will be very usefull.
