### ISSUE TITLE
Feature Request: Range annotations / Highlight region

### ISSUE THREAD

**Issue by mamasselin** [apexcharts/apexcharts.js#263]
It would be cool to have the ability to create "range annotations" to display regions on the chart. It would use min/max values instead of a single value. 

Maybe also a fillColor/fillOpacity to add flexibility, or simply re-use the current borderColor with lowered opacity as the fill color.

Example:

![image](https://user-images.githubusercontent.com/16145977/50917898-c3e15b80-140c-11e9-8507-6946f197c3df.png) 

Ref: https://github.com/chartjs/chartjs-plugin-annotation

**Comment by junedchhipa** [comment]
Good suggestion. This goes to the roadmap.

**Comment by lixaotec** [comment]
Dear fellows,

Was about to open a issue to question this.

Would be nice to have this on blocks, as in Dygraphs library.

![image](https://user-images.githubusercontent.com/40803484/51678928-b0192600-1fc4-11e9-8807-03f9cb960ad8.png)

Dygraphs is a great tool for time series, but lack of vue support, I wish to find all their power in here. Any toughts?

Thanks

**Comment by junedchhipa** [comment]
I am also a fan of Dygraphs and I take inspiration for some of the unique features it provides when it comes to interaction.

There will be some difference in terms of performance and look as Dygraphs is canvas based and ApexCharts is SVG based, but I'll try to integrate the good parts of it into ApexCharts if they seem feasible to implement.

Thanks for the suggestion.

**Comment by mamasselin** [comment]
Hi! I created a PR for this feature request. Please check it out and let me know if anything!

**Comment by junedchhipa** [comment]
Closing this. I will soon add examples in the website as well as write docs for it. Thanks again @mamasselin
