### ISSUE TITLE
Chart configuration horizontal true and shared tooltip false not showing the correct values for all the bars

### ISSUE THREAD

**Issue by ajinkya14feb** [apexcharts/apexcharts.js#2633]
### Description
 Chart configuration like horizontal=true and shared tooltip=false and chart type=bar is not showing the correct values in the tooltip. It only show the only first value where in shared=true it shows 3 value. Expected is it should show correct x axis value in tooltip.

### Steps to Reproduce

1.  Create a bar chart using apex chart
2.  Set horizontal=true and shared tooltip=false and chart type=bar
3.  Check tooltip it show only first tooltip from X axis values

### Expected Behavior
It should show single series but corrected one same like when horizontal is set to false 
### Actual Behavior
In tooltip it shows only first value in when its single and non stacked bar chart and horizontal is true.
Expected same behavior in horizontal is false as well
### Screenshots
See here My cursor is at purple line but tooltip show always blue value.
![image](https://user-images.githubusercontent.com/62745936/133600239-a625c0bd-5aed-4f66-ade7-0e2510afe52a.png)

**Comment by brianlagunas** [comment]
The required reproduction link was not provided
