### ISSUE TITLE
updateOptions does not return a promise.

### ISSUE THREAD

**Issue by inkasadev** [apexcharts/apexcharts.js#2642]
### Description

updateOptions does not return a Promise, as the documentation says.

### Steps to Reproduce

1.  Use the updateOptions to update your chart.
2.  Use console.log to check if a Promise is returned.

### Expected Behavior

updateOptions return a Promise.

### Actual Behavior

updateOptions does not return a Promise.

### Reproduction Link

https://codepen.io/hilty/pen/JjJLNrE
(check the console)

**Comment by junedchhipa** [comment]
Thanks for reporting the bug. It has been fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/d7ca6582bf57c1650130527f51f6109bbd05f26c)
The fix will be released soon.
