### ISSUE TITLE
In a bar chart containing three series, trims the columns.

### ISSUE THREAD

**Issue by abvas** [apexcharts/apexcharts.js#2644]
### Description:
If a bar chart contains three series and each series has two values, then the outer columns are truncated.
Now I use ApexCharts v3.28.3, but it was the same on earlier versions.

### Expected Behavior:
All columns should be fully displayed.

### Screenshot:
![Image 4](https://user-images.githubusercontent.com/47285364/133978986-f1768237-549e-4234-a718-2ceb05e4151a.png)

### Reproduction Link:
https://codepen.io/abvas/pen/LYLmPML

**Comment by stratosEft** [comment]
@abvas You are missing labels `labels: ['1','2']` *make sure data type to be string. X-axis type must be 'categorical'. Also tickPlacement can result in same bug for me.

**Comment by junedchhipa** [comment]
The provided codepen doesn't illustrate the issue.
