### ISSUE TITLE
not hover text after fomatter legend (added new tag html)

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#265]
## Codepen

https://codepen.io/anon/pen/JwaxwM

## Explanation

**What behavior do you expect?**
When passing "mouse", that "hover" happens

**What is happening instead?**
Hover doesn't work

**What error message are you receiving?**
None

**Comment by junedchhipa** [comment]
Thanks for reporting, I confirm that the legend formatter prevents the hover effects of legend. I will look into it soon.
