### ISSUE TITLE
Tooltip for stacked bar chart is messed up once deployed to QA or PROD environment. 

### ISSUE THREAD

**Issue by blueeDeveloper** [apexcharts/apexcharts.js#2669]
### Description
I have created a stacked bar chart and i am using a custom tooltip. My local version shows custom tooltip whenever i drag any place on the bar. But when this same code gets deployed to QA or PROD version, the tooltip shows below the bar chart and it remains in that position. The data shows differently when i hover over different bars on the chart but the position of the tooltip remains there at the bottom. I have checked everywhere and i dont know where i am going wrong. Please suggest. 

This is localhost version
<img width="1530" alt="Screen Shot 2021-09-22 at 12 45 44 PM" src="https://user-images.githubusercontent.com/79240323/134411826-88014875-3d1c-4d3d-81a2-83cc2a7861b7.png">

This is QA and prod version
<img width="1512" alt="Screen Shot 2021-09-22 at 12 45 57 PM" src="https://user-images.githubusercontent.com/79240323/134411849-49b12cba-d0f8-4922-a66e-b52b6aaf2fd0.png">

### Steps to Reproduce

My chart state information is as follows 

const projects = {      
    series: [
      { name: 'SUCCESS', data: result.success }, { name: 'FAILURE', data: result.failure }, 
      { name: 'SKIP', data: result.skip }, { name: 'NOT TESTED', data: result.untested }
    ],
    options: {
      colors: ['#63bb63', '#dc5f5f', '#202084', '#f9cd53'],
      chart: { type: 'bar', height: 200, stacked: true, stackType: '100%', toolbar: { show: false, tools:{ download:false } }
      },
      zoom: { enabled: false },
      dataLabels: {
        enabled: true,
        formatter: (value, { seriesIndex, dataPointIndex, w }) => {
          if(value === 100 && seriesIndex === 3) return 'X'
          else return value.toFixed()
        }
      },
      plotOptions: { bar: { horizontal: false, endingShape: 'rounded', columnWidth: result.success && result.success.length < 3 ? '5%':'10%' } },
      xaxis: { categories: projectNames, title: { text: "PROJECTS" }, labels: { show: true, rotate: -45, rotateAlways: true, maxHeight: 120 } },
      yaxis: { show: true, labels: { show: true }, title: { text: "PASS %", rotate: -90, offsetX: 0, offsetY: 0 } },
      fill: { opacity: 1 },
      tooltip: {
        followCursor: true,
        onDatasetHover: {
          highlightDataSeries: true,
        },
        custom: ({ series, seriesIndex, dataPointIndex, w }) => {
          const currObj = getCurrentPreviousObj(w.globals.labels[dataPointIndex].toString(), response)
          const setId = currObj.set_id ? currObj.set_id: ''
          const runtype = currObj.run_type ? currObj.run_type.toUpperCase(): ''
          const env  = currObj.environment ? currObj.environment.toUpperCase(): ''
          const runTime = currObj.run_time ? currObj.run_time: ''
          let notTested = ''
          let perct = series[seriesIndex][dataPointIndex] + '%' 
          if(currObj.not_tested === 100) {
            notTested = setId ? ("Not tested in " + setId): ("Not tested")
            perct = ''
          }
          return (
            '<div class="custom-tooltip">' +
              '<div claass="tooltip-header">' + 
                currObj.vertical_name.toUpperCase() +
                "-" +
                currObj.name.toUpperCase() + 
              "</div>" +
              '<div class="horiz-bar-dropdown">' +
              "</div>" +
              "<div>" +
              notTested +
              "</div>" +
              '<div class="parent-div">' +
                  "<span class='span-left'>" +
                  setId + 
                  "</span>" +
                  "<span class='span-left-runType'>" + 
                  runtype +
                  "</span>" +
              "</div>" +
              '<div class="parent-div-2">' +
                  "<span class='span-middle-env '>" +
                  env + 
                  "</span>" +
                  "<span class='span-middle'>" + 
                  runTime +
                  "</span>" +
              "</div>" +
              "<span class='last-div'>" +
              perct +
              "</span>" +
            "</div>"
          );
        }
      },
      legend: { show: false },
      states: {
        normal: { filter: { type: 'none', value: 0 } },
        hover: { filter: { type: 'none', value: 0 } },
        active: { allowMultipleDataPointsSelection: false, filter: { type: 'none', value: 0 }
      },
    }
    },
  };

**Comment by brianlagunas** [comment]
Closing as the required reproduction app link has not been provided.

**Comment by blueeDeveloper** [comment]
> Closing as the required reproduction app link has not been provided.

@brianlagunas - the code works fine when i run at my local but it messes up when deployed to QA or PROD. Wanted the team's important feedback on why this could go wrong after deployments.

**Comment by blueeDeveloper** [comment]
> Closing as the required reproduction app link has not been provided.

@brianlagunas  - the code works fine when i run at my local but it messes up when deployed to QA or PROD. Wanted the team's important feedback on why this could go wrong after deployments.
