### ISSUE TITLE
Xaxis annotations not rendered when the label does not show.

### ISSUE THREAD

**Issue by ines-steamdatasuite** [apexcharts/apexcharts.js#2671]
Hello,
By design Apexcharts hides xaxis labels to show a more pleasing xaxis.
But if I add an annotation to a specific label that is not displayed, the annotation does not show.

Here in the code pen you have two annotations:
- 19 Nov 2017 (this does not show)
- 24 Nov 2017 (this one show)

https://codepen.io/ines-pereira/pen/PojdoPO

Thanks for your help.

**Comment by junedchhipa** [comment]
In a category chart, it is not possible to determine the annotation position as the x-axis is not linear. The string can appear anywhere on the x-axis and hence ApexCharts uses actual label.
If you use a timeline or a numeric x-axis, the annotation will show even if the actual label is not present on the x-axis.
