### ISSUE TITLE
Bar chart logarithmic yaxis labels start at 1 instead of 0.001

### ISSUE THREAD

**Issue by pepobit** [apexcharts/apexcharts.js#2673]
### Description

I am draw a bar chart with a logarithmic y-axis. I have values from 0.001 to 100 and I want the labels 0.001 - 0.01 - 0.1 - 1 - 10 - 100 to appear on the y-axis. When generating the chart only 1 - 10 - 100 appear. How can I force the rest of the labels to appear? Or is it really a bug in the library?

### Steps to Reproduce

1. Define yaxis:

`yaxis: {
  title: {
    text: "Icorr"
  },
  max: 100,
  min: 0.001,
  tickAmount: 6,
  logarithmic: true
}`

2. Generate chart and only show labels 1   -    10    -   100 y axis. 

### Expected Behavior
Show five labels with values 0.001 - 0.01 - 0.1 - 1 - 10 - 100
### Actual Behavior
Generate chart and only show labels 1   -    10    -   100 y axis.

**Comment by brianlagunas** [comment]
No reproduction link provided

**Comment by brianlagunas** [comment]
Thanks for the link

**Comment by rubenstolk** [comment]
Running into the same issue, I can't show 0 values with logarithmic enabled...

**Comment by rubenstolk** [comment]
@brianlagunas would be great if you can review and update my PR, not much time to do the validations but this seems to be a logical fix.
