### ISSUE TITLE
Stacked bar chart -  border radius applied to last element of series only

### ISSUE THREAD

**Issue by blueeDeveloper** [apexcharts/apexcharts.js#2676]
### Description
Suppose i have a series as shown below. If "NOT TESTED" data is 0, then border radius should be applied to the previous series element. i.e. SKIP. That is not the case happening in my codepen. 

series: [
      { name: 'SUCCESS', data: result.success }, { name: 'FAILURE', data: result.failure }, 
      { name: 'SKIP', data: result.skip }, { name: 'NOT TESTED', data: result.untested }
    ],

### Expected Behavior
Stacked bar chart should have border radius to top most element in all scenarios. Even if last element of chart series is empty, border radius should be applied to the next last element. 

### Screenshots

1. As you can see, the border radius is absent when the last element of the series is 0. 
<img width="720" alt="Screen Shot 2021-09-25 at 8 49 00 PM" src="https://user-images.githubusercontent.com/79240323/134792863-6b66734e-ae06-4a5c-851c-e155eb1c5e96.png">

2. When i apply below css, border radius gets applied to every series. I wanted it to get applied only the topmost. 

.apexcharts-bar-series.apexcharts-plot-series  .apexcharts-series path {
  clip-path: inset(0% 0% -11% 0% round 16px);
}

<img width="692" alt="Screen Shot 2021-09-25 at 8 49 27 PM" src="https://user-images.githubusercontent.com/79240323/134792911-8a4cfdba-14e7-4401-bbe8-11fc493fc900.png">

### Reproduction Link
CODEPEN LINK BELOW 
https://codepen.io/a166617/pen/NWgOQNe

**Comment by Tim260399** [comment]
I have the same problem by vue-apexchart

**Comment by blueeDeveloper** [comment]
> I have the same problem by vue-apexchart

Hi @Tim260399 - have you raised a similar bug issue elsewhere ?

**Comment by brianlagunas** [comment]
As a workaround you can try using the new borderRadius feature that applied a border to all series by defining it as an array.

`borderRadius: [5]`

However, in this case do not use a very large border radius or it can impact the chart accuracy

**Comment by blueeDeveloper** [comment]
@brianlagunas thanks for suggesting the workaround. It somehow hides the border radius of the charts at the middle but the overall percentage bar shows reduced too and that will be very confusing for the end user. :(
![Uploading Screen Shot 2021-09-29 at 9.13.56 AM.png…]()

**Comment by brianlagunas** [comment]
don't forget to remove the 
```.apexcharts-bar-series.apexcharts-plot-series  .apexcharts-series path {
  clip-path: inset(0% 0% -11% 0% round 16px);
}
```

I get this:
![image](https://user-images.githubusercontent.com/835562/135310813-893eae28-c99d-4356-b602-1a006eb064f5.png)

**Comment by blueeDeveloper** [comment]
@brianlagunas - True, its similar to not having border radius. Can you please let us when the fix be available ?

**Comment by alexprey** [comment]
Still an issue for 3.33.2

**Comment by danicaus** [comment]
Having the same problem here. Still an issue for 3.35.3.

**Comment by gyurielf** [comment]
And still in 3.36.0

**Comment by junedchhipa** [comment]
There is a new property

```
plotOptions: {
  bar: {
    borderRadiusApplication: "around", // "around" / "end" 
    borderRadiusWhenStacked: "last" // "all"/"last"
  }
}
```

Docs: https://apexcharts.com/docs/options/plotoptions/bar/#borderRadiusApplication

**Comment by gyurielf** [comment]
> There is a new property
> 
> ```
> plotOptions: {
>   bar: {
>     borderRadiusApplication: "around", // "around" / "end" 
>     borderRadiusWhenStacked: "last" // "all"/"last"
>   }
> }
> ```
> 
> Docs: https://apexcharts.com/docs/options/plotoptions/bar/#borderRadiusApplication

Yep, thy!
I found it, a little while ago.

But, i think the part of the question is: on the first attached img, the second ant 3rd colums should be rounded as well.
Because those are last (shown) items.

**Comment by satishreddykoppella** [comment]
I have tried this configuration but didn't solve the problem. 
    
plotOptions: {
  bar: {
    borderRadiusApplication: "around",
    borderRadiusWhenStacked: "last" 
  }
}

**Comment by gyurielf** [comment]
> @gyurielf I have tried below plotOptions for stacked bar chart but didn't solve the problem. I don't see border radius applied. can you please let me know if it works for you ?
> 
> plotOptions: { bar: { borderRadiusApplication: "around", borderRadiusWhenStacked: "last" } }
> 
> <img alt="Screenshot 2022-11-08 at 9 36 50 AM" width="1241" src="https://user-images.githubusercontent.com/17969783/200636034-e419339f-cc90-4fd0-a894-c9f2833b4898.png">

https://codepen.io/gyurielf/pen/VwdPLQM

**Comment by satishreddykoppella** [comment]
@gyurielf I have edited details of codepen and attaching screenshot here
- Product D can have zero for some index. In that case how can i apply border radius last product ( can be any Product Not necessarily Product D) in each bar graph.

<img width="1760" alt="Screenshot 2022-11-08 at 10 52 31 PM" src="https://user-images.githubusercontent.com/17969783/200759728-ace52ead-3838-4232-9558-fafca6a66523.png">

**Comment by gyurielf** [comment]
@satishreddykoppella 

That is the problem, we can't.

**Comment by developOleg250** [comment]
You can use next code

```
    plotOptions: {
        bar: {
          horizontal: false,
          borderRadius: 10,
          borderRadiusApplication: "end",
          borderRadiusWhenStacked: "last",

          dataLabels: {
            total: {
              enabled: true,
              style: {
                fontSize: "13px",
                fontWeight: 900,
              },
            },
          },
        },
      },
```
![image](https://user-images.githubusercontent.com/101716582/216019134-e864e0dd-4d17-4faf-8d7a-f97afaa2f4fe.png)

**Comment by satishreddykoppella** [comment]
> You can use next code
> 
> ```
>     plotOptions: {
>         bar: {
>           horizontal: false,
>           borderRadius: 10,
>           borderRadiusApplication: "end",
>           borderRadiusWhenStacked: "last",
> 
>           dataLabels: {
>             total: {
>               enabled: true,
>               style: {
>                 fontSize: "13px",
>                 fontWeight: 900,
>               },
>             },
>           },
>         },
>       },
> ```
> 
> ![image](https://user-images.githubusercontent.com/101716582/216019134-e864e0dd-4d17-4faf-8d7a-f97afaa2f4fe.png)

I have tried didn't work for me. Can you please share some implemented codepen link ?

**Comment by wentaoGather** [comment]
I also get the same issue here, is there any solution for this?

**Comment by Lunkobelix** [comment]
I got help from a friendly soul and this worked for me:

```
plotOptions:
    bar:
      horizontal: false
      borderRadius:
        - 5
        - 5
      borderRadiusApplication: end
      borderRadiusWhenStacked: all
```

**Comment by satishreddykoppella** [comment]
@Lunkobelix I have implemented the changes you suggested. But I could see some style issue. can you please share some implemented codepen link  ?
<img width="906" alt="Screenshot 2023-03-28 at 12 35 57 PM" src="https://user-images.githubusercontent.com/17969783/228348069-49c9653c-6615-4733-9c62-0c22d988d9e8.png">

**Comment by Lunkobelix** [comment]
`type: custom:apexcharts-card
header:
  title: ''
  show: false
  show_states: true
  colorize_states: false
graph_span: 24h
now:
  show: false
  color: orange
  label: nu
span:
  start: day
stacked: true
apex_config:
  forceNiceScale: true
  tooltip:
    enabledOnSeries:
      - 0
    enabled: true
    x:
      format: HH:00
    'y':
      show: false
  label: Now
  grid:
    show: false
    borderColor: rgba(255, 255, 255, 0.1)
    strokeDashArray: 4
    position: back
  xaxis:
    tooltip:
      enabled: false
    axisBorder:
      show: false
    axisTicks:
      show: true
      offsetX: 0
    labels:
      show: true
      style:
        colors: white
        fontSize: 9px
        fontFamily: Arial
  chart:
    height: 150
  legend:
    show: false
  dataLabels:
    enabled: true
    offsetY: -9
    background:
      foreColor: white
      dropShadow:
        enabled: true
        opacity: 1
        top: 1
        left: 1
        color: '#404040'
    style:
      fontSize: 9px
      fontFamily: Arial
  stroke:
    width: 0
  plotOptions:
    bar:
      horizontal: false
      borderRadius:
        - 5
        - 5
      borderRadiusApplication: end
      borderRadiusWhenStacked: all
yaxis:
  - min: 0
    max: ~2
    show: true
    apex_config:
      forceNiceScale: true
      decimalsInFloat: 1
      tickAmount: 3
      labels:
        style:
          colors: '#ffffff'
          fontSize: 9px
          fontFamily: Arial
series:
  - entity: sensor.nordpool_kwh_se3_sek_2_10_025
    name: Elpris
    type: column
    time_delta: +30m
    color: rgba(240, 240, 240, 1.0)
    float_precision: 2
    unit: kr
    extend_to: now
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        const nu = new Date()
        const series_entry = new Date(entry.start)
        if(nu.getHours() == series_entry.getHours())
          {return [series_entry, 0]}
        return [series_entry, entry.value+parseFloat(hass.states['sensor.elpris_paslag'].state)];
        });
  - entity: sensor.nordpool_kwh_se3_sek_2_10_025
    name: Elpris
    type: column
    time_delta: +30m
    color: '#ffa04d'
    float_precision: 2
    unit: kr
    show:
      datalabels: true
    extend_to: now
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        const nu = new Date()
        const series_entry = new Date(entry.start)
        if(nu.getHours() == series_entry.getHours())
          {return [series_entry, entry.value+parseFloat(hass.states['sensor.elpris_paslag'].state)]}
        return [series_entry, 0];
        });
`

I hope this example can help you.

**Comment by mizinin** [comment]
Same problem here. If last data set have a zero value, no border radius is applied. No working solution yet :(

**Comment by guillaume-caulier** [comment]
Same problem.

**Comment by jgwinner** [comment]
Why is this closed? We ran into the same issue.

If you use `borderRadiusWhenStacked: "last"  ` as proposed it looks weird. This is what we're trying to avoid. 

Reproducible sample with the proposed solution (that didn't work for us):

![image](https://github.com/apexcharts/apexcharts.js/assets/10425170/dc105400-4034-4cee-ada0-050f9f148fd2)

**Comment by yevhenii-f** [comment]
I'd propose to reopen this issue with regards to latest comments. I'm facing the same issue and `borderRadiusWhenStacked: "last"` does not solve an issue if top data points contain 0 value.

**Comment by dima-kov** [comment]
still an issue

**Comment by fernandolangaro** [comment]
I used @brianlagunas css property to create a solution. This is how I did it, it works great, you might need to tweak it a bit to fit your needs:

first get this data from your chart:
`const seriesElements = document.querySelectorAll('#yourChartId .apexcharts-bar-series.apexcharts-plot-series .apexcharts-series')`

then determine the length of chart data, based on your first serie, running this:
`const seriesDataLength = seriesElements.value[0].querySelectorAll('.apexcharts-bar-area').length`

finally iterate over all of them and set the border to the last one:

    for (let i = 0; i < seriesDataLength; i++) {
      const lastElements = []

      seriesElements.forEach((serie) => {
        const bar = serie.querySelectorAll('.apexcharts-bar-area')[i]
        if (bar && bar.getAttribute('barHeight') !== '0') {
          lastElements.push(bar)
        }
      })

      const lastElement = lastElements[lastElements.length - 1]

      if (lastElement) {
        lastElement.setAttribute('clip-path', 'inset(0% 0% -100% 0% round 4px)')
      }
    }

**Comment by mwinner313** [comment]
![Capture](https://github.com/apexcharts/apexcharts.js/assets/16043883/5f1c9f9f-a612-447c-b94c-b893d7941289)
can any body help me with this?

**Comment by PedroMTSilva** [comment]
Still an issue. I'm working with ng-apexcharts 1.7.7 and Angular13. Also, the options for 'borderRadiusApplication' and 'borderRadiusWhenStacked' just don't work at all.

**Comment by PedroMTSilva** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/16043883/316449228-5f1c9f9f-a612-447c-b94c-b893d7941289.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzA3NTAsIm5iZiI6MTcxNTE3MDQ1MCwicGF0aCI6Ii8xNjA0Mzg4My8zMTY0NDkyMjgtNWYxYzlmOWYtYTYxMi00NDdjLWI5NGMtYjg5M2Q3OTQxMjg5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEyMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MWMwODMzMDc4MzgyNmZjODJhM2ExMzQ1OWEzOWIwZjZhYjI0NGY0YWUyOWMzMTQwMzUyNjc1YTQ3ZTEzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1YSZHOOlqGqXSLJ8inndqvzUAjtLFVWc6daEzKOS6nE) can any body help me with this?

How did you even get the radius to happen the the bottom elements?

**Comment by FrenchMajesty** [comment]
@junedchhipa  As of July 2024, still an issue. See attached screenshot:
<img width="447" alt="Screenshot 2024-07-29 at 3 43 56 PM" src="https://github.com/user-attachments/assets/9868933b-3a81-4ab0-a904-61a1bfb422b5">

**Comment by ibrahimelement** [comment]
This is still an issue, why has this not been fixed?

**Comment by brunofuentes** [comment]
hi. having the same issue. Is it expected to be fixed anytime soon? thanks.
