### ISSUE TITLE
Exception calling dataURI(): globals.dom.baseEl is null while trying to call getElementsByClassName 

### ISSUE THREAD

**Issue by rjunior273** [apexcharts/apexcharts.js#2679]
### Description

Trying to generate a data URI of any chart causes an exception. Bumped into this while trying to generate the data URI of the charts onto a report page for PDF generation. On my code, if the user navigates to the report, the javascript code calls render() so he/she sees the chart. Within a background job, for generating a PDF of the same page, the render() call is skipped and the dataURI should be called instead so a static image is used.

The PDF are generated using Puppeteer and all the javascript events fires OK. If I leave the render() call on it, it does render normally, except for some padding and size issues with the chart. That's why I want to use dataURI to have a static image instead (easier to deal with and position).

It also happens on the simple codepen example.

### Steps to Reproduce

1. Edit the codepen provided ( https://codepen.io/apexcharts/pen/bxzgZJ )
2. Comment the render call and try to log the data URI:

```
//chart.render();
var dataUrl = chart.dataURI().then(({ imgURI, blob }) => {
  console.log(imgURI);
});
console.log(dataUrl);
```

### Expected Behavior
Console log the data URI of the chart.

### Actual Behavior

```
apexcharts:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at t.value (apexcharts:6)
    at apexcharts:6
    at new Promise (<anonymous>)
    at t.value (apexcharts:6)
    at t.value (apexcharts:14)
    at pen.js?key=pen.js-6f92ef02-dd17-03cd-2ce7-94bf3486f1b0:86
```
...globals.dom.baseEl is null at that moment.

### Reproduction Link

https://codepen.io/apexcharts/pen/bxzgZJ

**Comment by sajeevamil** [comment]
any update on this bug?

**Comment by junedchhipa** [comment]
The method dataURI() cannot be called without calling the render method. So, this is not a bug.
