### ISSUE TITLE
Custom icons index not working properly

### ISSUE THREAD

**Issue by nospoon** [apexcharts/apexcharts.js#2691]
When trying to add custom buttons to the toolbar, the index attribute should allow for setting the position of the custom element. But it does not work as intended. The index of existing default elements does not get shifted to accommodate for the new elements, making it impossible to properly position them.
For example, when adding a custom element with index 1, it gets placed at the second position from the left. When index is set to 0, it is placed all the way to the right. I had limited success with negative indexes, but I also noticed the the toolbar seems to have a limited predefined space available and adding new elements shifts the entire toolbar to the right to the point where it runs out of space and items start overlapping.
Also it doesn't seem possible to put an element on the left corner of the diagram window away from the default controls.

**Comment by brianlagunas** [comment]
You did not follow the issue template and did not provide a reproduction app
