### ISSUE TITLE
My chart fails to update, and disappears instead (donut)

### ISSUE THREAD

**Issue by Minipada** [apexcharts/apexcharts.js#2692]
### Description
I am trying to update a donut with data coming every X seconds. Instead of updating, the donut disappears. I tried the "updateSeries" and "updateOptions" to update the series, and I have the same result with both.
I am using javascript and tested it on chromium and Firefox

### Steps to Reproduce

1. Load the codepen

### Expected Behavior
A donut is displayed. and 3 seconds after updated.

### Actual Behavior
The donut disappears.

### Reproduction Link

https://codepen.io/minipada/pen/GREbmpZ

**Comment by Minipada** [comment]
The syntax was wrong, when updating series, use
```
ApexCharts.exec("my-donut", 'updateSeries',
    [55, 45]
)
```

**Comment by pawandeore** [comment]
@Minipada  how to update labels
