### ISSUE TITLE
Force chart to 100% of Parent's Div?

### ISSUE THREAD

**Issue by alc32** [apexcharts/apexcharts.js#27]
Tried height: '100%', Is there any way to make the chart height-responsive?

**Comment by junedchhipa** [comment]
If you do give `height: 100%`, the chart gets the parent element's height and sets the fixed height - which doesn't change when width changes. 

So, setting `height: 100%` doesn't actually makes it responsive but makes the chart fill the available height which is set by parent div.

To make it responsive, only `width: 100%` should be set and height should be left out.

Another proposal for different aspect ratios is discussed in this [thread](https://github.com/apexcharts/apexcharts.js/issues/20) and I have already taken into consideration.

Thank you
