### ISSUE TITLE
Radialbar/Gauge : add visual thresholds

### ISSUE THREAD

**Issue by laurent-brisbois** [apexcharts/apexcharts.js#2701]
## Summary

With apexcharts radialbar/gauge chart, we should be able to had visual thresholds to see if we are close to reach a particular limit.

## Intended Use Case

Here are some pictures to illustrate :

![image](https://user-images.githubusercontent.com/48165976/136772831-7af70164-41dc-451f-bbaa-e220904e7767.png)
![image](https://user-images.githubusercontent.com/48165976/136772908-78de6abd-3e42-4443-ad8f-5542fd2fcec4.png)

You got the idea :-)

The (visually) cleanest solution to me is to have a second thin gauge with 3 colors like on the second picture I gave.

**Comment by praveen-vishnu** [comment]
@laurent-brisbois  thanks for pointing out .. even i'm also trying to achieve same as @ApexCharts. please get back to this

**Comment by laurent-brisbois** [comment]
I switched library to Apache ECharts. It is way better and maintained.

**Comment by laurent-brisbois** [comment]
@praveen-vishnu 
I switched library to Apache ECharts. It is way better and maintained.
