### ISSUE TITLE
Boxplot with categorical xaxis shows the outliers wrongly

### ISSUE THREAD

**Issue by lucianolorenti** [apexcharts/apexcharts.js#2706]
Hi! I have this issue when trying to use the boxplots and show the outliers at the same time. I tried following the library code to see when the problem is but I couldn't figure it out. 
I tried changing the input of the data of the scatter to `{ x: the_label, y: Array<number> }` and forcing the list of categories, but these things didn't solve it.

### Description

A boxplot with outliers using a categorical label shows the outliers in different x positions. The first outlier shares the x-position with the boxplot, but the next ones have an increasing x-position. 

### Steps to Reproduce

1.  Create one boxplot with the x-variable being a categorical label
2. Add outliers using in the x component the same categorical label 

### Expected Behavior
All outliers should be located in the same x coordinate

### Actual Behavior
The x positions of the outliers increment as the thumber of outliers grows

### Screenshots

[Screenshot](https://ibb.co/MGHkTq8)

### Reproduction Link

[Link to the example](https://codesandbox.io/s/react-basic-example-forked-9kpus?file=/src/App.js)

**Comment by EdwinArgudo** [comment]
The issue is still there if you use more than one boxplot:

<img width="514" alt="Screen Shot 2022-01-11 at 5 00 17 PM" src="https://user-images.githubusercontent.com/35999849/149028474-e43cf660-911f-45ce-9acc-b583838f5063.png">

Link to codepen:
[Link](https://codesandbox.io/s/react-basic-example-forked-6snyy)
