### ISSUE TITLE
Does not work on IE11

### ISSUE THREAD

**Issue by steambap** [apexcharts/apexcharts.js#271]
## Explanation

- What is the behavior you expect?
Apex chart should work on IE11, at least the demo page: https://apexcharts.com should be working.

- What is happening instead?
Demos does not work on IE11.

- What error message are you getting?
No error message can be seen in the console.

**Comment by mestaritonttu** [comment]
As IE11 support has been abandoned, I don't know why the demo page should work with it: https://github.com/apexcharts/apexcharts.js#how-do-i-make-it-work-in-ie11

**Comment by junedchhipa** [comment]
I will fix the website by loading polyfills for IE11.

**Comment by junedchhipa** [comment]
Re-enabled IE11 support directly without any polyfills.

**Comment by steambap** [comment]
Download PNG / SVG does not work on IE11

**Comment by johncarlo3910** [comment]
Is there a solution to this? I still can't render the chart in IE11. hope someone would help. thanks

**Comment by junedchhipa** [comment]
Fixed IE11 issues in https://github.com/apexcharts/apexcharts.js/commit/44de94c4c2d890df6e35314d0ff55c299cf5eccf

**Comment by johncarlo3910** [comment]
Hi,

I saw the fix already
https://github.com/apexcharts/apexcharts.js/commit/44de94c4c2d890df6e35314d0ff55c299cf5eccf
at
version 3.6.5 but I can't still make it work in IE11.

Am I referencing the correct js files?
1. apexcharts.min.js
2. apexcharts.common.js

It works perfectly fine in Chrome

Thanks
Regards,
John Carlo

**Comment by junedchhipa** [comment]
Can you create a codepen demo so I can open it directly in IE11 and see any issues.

**Comment by johncarlo3910** [comment]
Hi, 

I found the error, It turns out the .toFixed() I used in formatting labels is not working in IE11.

Thanks for helping.
Regards,
Carlo

**Comment by leem32** [comment]
The `toFixed()` method was added in Internet Explorer 5.5, so it should be working for IE11.

**Comment by BogdanDima** [comment]
Hi,

Not that I'm a fan of IE but this simple Apex chart doesn't work at all on IE11: https://jsfiddle.net/3yesf7j5/

**Comment by SandeepKapalawai** [comment]
I am using the latest version of package but still i was able to see the IE 11 having, i have seen some where it was mentioned add polyfills before using the apex starts but that still gives an error for me, any work around for this please ?
`import React, { Component } from 'react';
import './eligrey-classlist-js-polyfill';
import './findindex_polyfill_mdn';
import './polyfill.min.js';

import Chart from 'react-apexcharts';`

**Comment by red-lilith** [comment]
Hi, @SandeepKapalawai , were you abled to make it work?

**Comment by ritwickd35** [comment]
Can anyone tell me what features don't work on IE10?
