### ISSUE TITLE
Incorrect Param Example

### ISSUE THREAD

**Issue by caribeedu** [apexcharts/apexcharts.js#272]
## Explanation

In legend options reference have an wrong param.
This issue it's just a warn. Close this when you want.

## Print
![image](https://user-images.githubusercontent.com/28613091/51126362-130efe00-180a-11e9-91b9-bd02c6274292.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, just fixed the wrong property reference in the `drawLegends()` method.
