### ISSUE TITLE
Lack of documentation to reproduce examples from README.md

### ISSUE THREAD

**Issue by mvtm-dn** [apexcharts/apexcharts.js#2726]
Still searching for solution for this. I saw this example in README file, but can't find it in documentation and examples.
https://github.com/apexcharts/apexcharts.js#interactivity

_Originally posted by @wsjscss in https://github.com/apexcharts/apexcharts.js/issues/1563#issuecomment-626840234_

**Comment by yangsijie666** [comment]
It's a pity
