### ISSUE TITLE
Cannot stop default donut slice from exploding

### ISSUE THREAD

**Issue by WhiteRaBot17** [apexcharts/apexcharts.js#273]
Hey, where is the option to stopping the animation from exploding the donut slice on click?

Cannot find anything relevant in the documentation to this issue.

**Comment by junedchhipa** [comment]
Forgot to add the option to documentation. Just added it now - https://apexcharts.com/docs/options/plotoptions/pie/#expandOnClick

```javascript
plotOptions: {
 pie: {
   expandOnClick: true,
  }
}
```

**Comment by WhiteRaBot17** [comment]
> Forgot to add the option to documentation. Just added it now - https://apexcharts.com/docs/options/plotoptions/pie/#expandOnClick
> 
> ```js
> plotOptions: {
>  pie: {
>    expandOnClick: false,
>   }
> }
> ```

Thanks my friend!
