### ISSUE TITLE
Assigning colours for specific label values on pie/donut chart

### ISSUE THREAD

**Issue by nospoon** [apexcharts/apexcharts.js#2736]
## Summary

When using donut/pie chart it does not currently seem possible to assign specific colours for certain label values. This is a big issue when presenting data that doesn't always come in predefined order.

For example: 
I have a donut chart representing number of phone calls grouped by their return status. There are 5 possible status values which should have constant colours associated with them. However I cannot use a predefined list of colours that rely on array index values, because the data cannot be expected to always be in the same order and contain all of the possible statuses (e.g. a given status may have never been triggered so it is not present in the dataset).

## API Changes

Add ability to specify a colour to be used for given data label.

## Intended Use Case

Consistent presentation of data on donut/pie charts

**Comment by ajaymakwana888** [comment]
Hi @nospoon 
Do you get any solution for this?

I'm getting the same problem with the donut chart.
Actually, I have 6 values in the donut chart. so it automatically takes the same color for two of them.

Can anyone help with this case?

Thanks

**Comment by Chindara** [comment]
I also have the same issue. When colors load according to the availability order. How to specify color for the label?
