### ISSUE TITLE
React apexcharts not allow to set borderRadius on both sides of bar (timeline chart, type:rangeBar)

### ISSUE THREAD

**Issue by AndreyPrasolov** [apexcharts/apexcharts.js#2740]
## Summary

It needs to be borderRadius for both sides on rangeBar

`
"apexcharts": "^3.29.0",
"react-apexcharts": "^1.3.9",
`

When i'm trying to set border radius, it works only on one side

`
plotOptions: {
        bar: {
          horizontal: true,
          borderRadius: 4,
        },
      }
`

Result:

![Screen Shot 2021-11-01 at 17 44 09](https://user-images.githubusercontent.com/26552703/139699721-7c5f8364-e6d7-4b67-abd7-6c128e6e6a65.png)

**Comment by nanhaibo** [comment]
你可以使用数组替代字符串，就可以解决这个问题
you could use Array instead of String, like this:  
`borderRadius: [8, 8]`

**Comment by jellederijke** [comment]
Thanks for your comment, @nanhaibo. Using an array didn't seem to work for me. Still only the ends of the timeline bars are rounded. Not the beginning. Any suggestions are highly appreciated.

**Comment by Aravinth04-bit** [comment]
Hi ,
 I want border radius top bar and bottom bar radius with that in Apex chart .how i am found that? Please tell me![Screenshot_2022-07-06-21-31-37-365_com.android.chrome.jpg](https://user-images.githubusercontent.com/88648492/177594319-c00dbdd8-ccfd-4f26-b2ae-13064cd39478.jpg)

**Comment by dparvanov** [comment]
This is still not resolved, any sugggestions?

**Comment by syldysnya** [comment]
@jellederijke hey, were you able to figure it out?
