### ISSUE TITLE
Radial Bar Chart not rendering correctly Firefox

### ISSUE THREAD

**Issue by duecknoah** [apexcharts/apexcharts.js#2742]
### Description
It seems the following works correctly in Chrome but not in Firefox. Having the chart div within a flex container
causes issues rendering. Specifically when the padding-left or padding-right values are set, the parent container is a flex container, and the child (chart) container doesn't have the flex property set

### Steps to Reproduce

1. Create a Radial bar chart anywhere on the page. I used the exact one of the [radial bar demo page](https://apexcharts.com/javascript-chart-demos/radialbar-charts/basic/)
2. Create a flex container the contains our 'chart' container within it.
3. Set the padding-left and padding-right for the chart div to some values other than 0 (ex. 12px)
4. Open up the page using that chart and don't resize it. The bar chart will only render partially.

### Expected Behavior
The Radial bar chart renders completly and the animation of the bar 'filling up' to the desired value

### Actual Behavior
The Radial bar chart renders partially and most is cut off.

### Screenshots
![chrome_working](https://user-images.githubusercontent.com/19723275/139745606-8e484ee8-1843-4c41-b787-cb552520f713.png)
![firefox_issue](https://user-images.githubusercontent.com/19723275/139745608-03de8480-cd6c-41c2-837c-da0cf3a5d490.png)

### Reproduction Link
Setting the 'flex' property (the one thats commented out in the codepen) for the child (chart) seems to make the radial bar render correctly.
https://codepen.io/duecknoah/pen/BadmjNB

**Comment by junedchhipa** [comment]
As tested on v3.54.1, this works fine now
