### ISSUE TITLE
ESM leaks to the global scope

### ISSUE THREAD

**Issue by LeaVerou** [apexcharts/apexcharts.js#2743]
### Description

Even the ESM version of Apex Charts leaks two globals to the global scope: `addResizeListener()` and `removeResizeListener()`.
These seem to originate here: https://github.com/apexcharts/apexcharts.js/blob/e9e7fefc7fcd5d94b6ad23eda3e19da07d250a83/src/utils/DetectElementResize.js

Furthermore, the very same script [causes errors when Apex Charts is used in Shadow DOM](https://github.com/apexcharts/apexcharts.js/issues/1332).

I'd suggest ditching this altogether and using [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) with a [polyfill](https://github.com/juggle/resize-observer/) for older browsers (it's already [supported natively for 92% of users](https://caniuse.com/resizeobserver)).

### Reproduction Link

https://codepen.io/leaverou/pen/rNzYdXj?editors=0010
but literally any snippet would demonstrate the issuse.
In this pen I'm also logging the globals though.

**Comment by junedchhipa** [comment]
Ah! this was the reason the ESM build was failing in some frameworks.
Thanks for pointing this out, we will look into this further.
