### ISSUE TITLE
Dark mode should not set a default background

### ISSUE THREAD

**Issue by AlmogBaku** [apexcharts/apexcharts.js#2747]
### Description

Currently, when setting dark-mode, there's a default background.

### Steps to Reproduce

1.  Create a chart
2. Set its theme mode to `dark`

### Expected Behavior
It should behave similarly to the light mode - enabling the user to control the background only if he want to

### Actual Behavior
The graph has a default background

### Workaround
as a workaround, you can set the `chart.background` to `none`

**Comment by brianlagunas** [comment]
No repro link provided

**Comment by AlmogBaku** [comment]
@brianlagunas not sure why did you close it?

You can see an example here: https://apexcharts.com/javascript-chart-demos/dashboards/dark/

**Comment by brianlagunas** [comment]
I explained why I closed it in my reply. You did not follow the bug template and did not provide a reproduction app using the provided codepen links. Linking to a sample is not considered a reproduction app.

**Comment by devcircus** [comment]
@AlmogBaku Thanks for the workaround you mentioned. This confused me for almost an hour before I came here.
