### ISSUE TITLE
Prototype of Chart Type Pareto

### ISSUE THREAD

**Issue by caribeedu** [apexcharts/apexcharts.js#275]
**Idea and concept**
I maked an tiny script for create pareto chart, he receive an array of numbers and sort decrescent, after, sum them and finally get the average for each array position. (It's just a ideia, one time Pareto's chart it be so interesting).

**How this works?**
Just  have an options with two series, the first (in this case series[0]) with the data and the second (in this case [1]) with already existing properties.

**Code Example**
```
          options.chart.type= "line";
          options.series[0].type = "bar";
          options.series[1].type = "line";

          options.series[0].data.sort(function(a, b){return b-a});

          let totalSerie = 0;
          for(var i=0;i < options.series[0].data.length;i++) {
            totalSerie += options.series[0].data[i];
          }

          let paretoSerie = [];
          for (let i = 0; i < options.series[0].data.length; i++) {
            if (i == 0) {
              paretoSerie.push(parseFloat(((options.series[0].data[0] / totalSerie) * 100).toFixed(2)));
            }
            else {
              let newPercent = ((options.series[0].data[i] / totalSerie) * 100) + paretoSerie[i-1];
              paretoSerie.push(parseFloat(newPercent.toFixed(2)));
            }
          }

          options.series[1].data = paretoSerie;

          options.yaxis = [
            { 
              title: {
                text:"Amount"
              },
              labels: {
                formatter: function(val, index) {
                  return val;
                }
              }
            },
            {
              opposite: true,
              max: 100,
              labels: {
                formatter: function(val, index) {
                  return val + "%";
                }
              }
            }
          ];
```

**Print**
![image](https://user-images.githubusercontent.com/28613091/51184347-26c66d00-18bb-11e9-9ed4-9b9c6723acc2.png)
*Detail, I deleted the xaxis categories because is a personal project, but works normally with them.*

**Comment by junedchhipa** [comment]
Thanks for the prototype of Pareto Charts.
I will try to implement in the future releases of ApexCharts.

**Comment by brakop** [comment]
Just my $0.02 on this,
1) Yes, I would vote for Pareto Charts! They would be nice, though the mixed charts suits just fine.
2) The image example above isn't quite correct. Pareto do use dual Y-axis, but both axes are scaled, mean the right is to 100 because it's the percentage (as above), but the left is to the SUM(VALUES), which results in the top of the first bar and the first data point always aligning. A minor fix, but just something to keep in mind if you do end up adding Pareto formally.
