### ISSUE TITLE
Select color for dataset

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#276]
**Is your feature request related to a problem? Please describe.**
I'd like to choose which colors a series shows up in. 

In my case, what I'm trying to accomplish is a multichart with line and bar graphs, and trendlines which match the color of the dataset it is based off of. This is not possible currently

**Describe the solution you'd like**
I'd like to be able to add a parameter to the series object which 

**Describe alternatives you've considered**
Other chart libraries allow this, but ApexCharts fits my needs more.

I'd be willing to do a PR but I honestly wouldn't even know where to start. If someone would be willing to give me a push in the right direction then I'm sure it wouldn't be too difficult.

**Comment by jchang19** [comment]
@junedchhipa I've created a PR for this feature: https://github.com/apexcharts/apexcharts.js/pull/1736
