### ISSUE TITLE
Legend Shapes not reflecting custom Marker Shapes

### ISSUE THREAD

**Issue by moreturkey** [apexcharts/apexcharts.js#2764]
I had tried adding different shapes for Markers in Scatter chart with below code for 2 data series,
```

markers: { 

  shape: ['circle', 'square'] 

}

```

I am able to view markers as expected. But the legend is still both series names prefixed with circle in contrary to display 1st series name with circle shape and 2nd series name with square shape.

Screenshots
<img width="166" alt="Untitled" src="https://user-images.githubusercontent.com/86817677/140952158-00fcf74c-4f33-4553-8531-4f6ee5175da3.png">

Reproduction Link
https://codepen.io/moreturkey/pen/LYjrWax

**Comment by junedchhipa** [comment]
Fixed with version 3.50.0
