### ISSUE TITLE
Stacked column barchart- onclick on Xaxis label feature 

### ISSUE THREAD

**Issue by blueeDeveloper** [apexcharts/apexcharts.js#2766]
Hi,
I wanted to know if there is a onclick feature for the xaxis label in a stacked barchart
for e.g. below codepen
https://codepen.io/markhm/pen/ExjqYbV

If i click on '02 Jan', '03 Jan' and so on, is there any onclick event handling for this. Please let me know. 

<img width="729" alt="Screen Shot 2021-11-09 at 11 02 17 AM" src="https://user-images.githubusercontent.com/79240323/140988032-6032671a-3fa3-41d2-b137-82e6342138ec.png">

**Comment by softy2k** [comment]
Still searching for this label click event.

Something new ? Or another way?
