### ISSUE TITLE
Black box once download image with selection true

### ISSUE THREAD

**Issue by karishmampatel** [apexcharts/apexcharts.js#2769]
![issue](https://user-images.githubusercontent.com/94121156/141309181-2baa7433-c2af-4198-876f-8493311a21dc.png)

as per image if i have enable selection and than select download png option than downloaded image comes with black box instead of selected area

![j5u0xq3g (8)](https://user-images.githubusercontent.com/94121156/141309370-1e302f59-abb3-4dec-b9fd-1367fd44c0aa.png)

if anyone have solution than help me to resolve it

**Comment by brianlagunas** [comment]
Did not follow the issue template

**Comment by karishmampatel** [comment]
is there any wa to resolve it?
