### ISSUE TITLE
chart.events.dataPointSelection() - Not work in radialBar type

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#279]
## Codepen

https://codepen.io/anon/pen/oJrVxO?editors=0010

## Explanation

**What is the behavior you expect?**
```
Object {
  dataPointIndex: 0
  selectedDataPoints: [Array(1)]
  seriesIndex: 0
  w: {config: {…}, globals: {…}}
  __proto__: Object
}
```
**What is happening instead?**
```
Object {
  dataPointIndex: NaN
  selectedDataPoints: [NaN: Array(2)]
  seriesIndex: NaN
  w: {config: {…}, globals: {…}}
  __proto__: Object
}
```
**What error message are you getting?**
None

**Comment by juliorosseti** [comment]
Hi JC 🖐🏼,

When will be released the version with this fix?

**Comment by junedchhipa** [comment]
Tomorrow, hopefully. 😀

**Comment by juliorosseti** [comment]
Uhuhuhuhu, tkss! 🎉🙌👌

**Comment by tapanparekh** [comment]
Is this issue resolved?

**Comment by tapanparekh** [comment]
I am getting this error in treemap chart
