### ISSUE TITLE
ApexChart doesn't work at IE11

### ISSUE THREAD

**Issue by parkyeonkyu** [apexcharts/apexcharts.js#2790]
### Description

Apex Line chart(js) I used on my web doesn't work suddenly.
so I downloaded demo project and I ran the demo and then it works on Chrome but doens't work on IE11
Do u decided not to support IE? or What should I do to rescue my Apex Line Chart(js) 
Please help me~~~~~~~~~~ I have to use IE.. please make it work on IE~~~~~~~~~~~

### Steps to Reproduce

1.  Apex Line chart(js) I used on my web doesn't work suddenly.
2.  so I downloaded demo project and I ran the demo and then it works on Chrome but doens't work on IE11
3.  Do u decided not to support IE? or What should I do to rescue my Apex Line Chart(js) 
4.  Please help me~~~~~~~~~~ I have to use IE.. please make it work on IE~~~~~~~~~~~~~

**Comment by brianlagunas** [comment]
IE 11 is not a browser we are willing to support and the browser itself is officially end of life in June 2022. You should move to a new browser within the next 6 months.

**Comment by parkyeonkyu** [comment]
> IE 11 is not a browser we are willing to support and the browser itself is officially end of life in June 2022. You should move to a new browser within the next 6 months.

Can u provied me previous version file?   I am gonna change my web but I have to use it until the job finish

**Comment by brianlagunas** [comment]
All previous releases can be found under the Release section of the repo.

**Comment by parkyeonkyu** [comment]
> All previous releases can be found under the Release section of the repo. Or you can install previous versions using npm

Thank you sir!!
