### ISSUE TITLE
Keep tooltip visible if it is hovered

### ISSUE THREAD

**Issue by Karpengold** [apexcharts/apexcharts.js#2794]
I would like to provide user ability to copy value from tooltip, but when mouse pointer goes outside of chart to tooltip, tooltip disappears. Is it possible to keep it if it is hovered?

**Comment by saber-mekki** [comment]
Hi @Karpengold ! Did you solve this issue? we have the same need !

**Comment by saber-mekki** [comment]
@Karpengold i use this : 
```
.apexcharts-tooltip {
     opacity: 1 !important;
 }
```
but i can't Interact With it !

**Comment by Karpengold** [comment]
@saber-mekki I found this solution as well, but I don't want to keep tooltip always visible, only if user hovers it
