### ISSUE TITLE
Highly unserious link in code (svgjs.com)

### ISSUE THREAD

**Issue by jojozg7** [apexcharts/apexcharts.js#2797]
This problem has been reported 3 times, the first time 6 months ago. The link is still included in the bundle, which can be downloaded via the link https://apexcharts.com/downloads/apexcharts-bundle.zip on the website https://apexcharts.com.

Is anyone here really taking this seriously?

Honestly, respect for the project or not, what is this nonsense?

**Comment by brianlagunas** [comment]
We have tried addressed this before. It’s possible we missed a spot. It would be more helpful if you could point to the line of code where this exists, or where on the website the exists exactly. Help us find it so we can fix it.

**Comment by jojozg7** [comment]
But there are 2 links in my post. If you download apexcharts-bundle.zip from the website, you will find the link to svgjs.com in the source.
