### ISSUE TITLE
Donut chart labels not hiding

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#28]
using this configuration
```javascript
const config = {
	chart: {
      width: 380,
      type: 'donut',
    },
    series: [44, 55, 41, 17, 15],
    legend: {
      show: false
    },
    plotOptions: {
      pie: {
        dataLabels: {
          name: {
            show: false
          },
          value: {
            show: false
          }
        }
      }
    }
}
```

This comes out 
![sketch](https://user-images.githubusercontent.com/6877046/43955621-b1da76d6-9ca9-11e8-8c9c-4e22ddd21d9a.png)

Any idea how to hide labels?

**Comment by junedchhipa** [comment]
Hi @jimfilippou 
The dataLabels configuration which you have written is only applicable for radialBar charts (name/value).

For a global dataLabels configuration, you have to set the options in
`options.dataLabels.enabled = false`

The `options.dataLabels` is applicable to all chart type and you can read more here https://apexcharts.com/docs/options/datalabels/

**Comment by kaynetpc** [comment]
_if you're dealing with react js `legend` maybe excluded and it will also work fine_ 

`const config = {
    chart: {
      width: 380,
      type: 'donut',
    },
    series: [44, 55, 41, 17, 15],
   
    dataLabels: {
      enabled: false
    }
}
`
