### ISSUE TITLE
Candlestick Char, First and Last bar cropped!!

### ISSUE THREAD

**Issue by vaio286** [apexcharts/apexcharts.js#280]
Sorry to bother you guys, but how i can fix this weird issue: 
![startcandlecropped](https://user-images.githubusercontent.com/3382529/51433311-25c86f00-1c1e-11e9-8165-b8d8730313bf.png) ![lastcandlecropped](https://user-images.githubusercontent.com/3382529/51433446-7e990700-1c20-11e9-8e5e-48e0e060a601.png)

This happen to the first and the last bar of the chart, on the console editing  this element width and x:
`<clipPath id="gridRectMaskq60bzkb5"><rect id="SvgjsRect2919" width="1803.25" height="502.34799999999996" x="-0.5" y="-0.5" rx="0" ry="0" fill="#ffffff" opacity="1" stroke-width="0" stroke="none" stroke-dasharray="0"></rect></clipPath>`

for example adding 10 to width and -2 to x the bars are displayed fine.

Trying to access those elements thru css is pointless because the Id is different every time the page is loaded, also tried other config within the chart options and by the life of me i cant fix the issue, that's why I'm here asking for help or if you can point me in the right direction to fix the issue, sorry if this is not the best place to ask for help and ty in advance.

**Comment by junedchhipa** [comment]
Thanks for reporting, I have fixed this issue and will be releasing a patch soon.

**Comment by mattkhaw** [comment]
@junedchhipa I know this is a very old issue but still, candlestick seems to crop the first and last bars. I'm using the latest release by the way.
