### ISSUE TITLE
Dark mode switch light mode style failure

### ISSUE THREAD

**Issue by duxphp** [apexcharts/apexcharts.js#2801]
### Steps to Reproduce

When switching theme.mode through window.apex using vue etc., it will not take effect immediately, if you use the refresh component to switch from dark to light mode, the style will be invalid when switching from light to dark mode.

### Expected Behavior

Dynamically update window.apex to switch between light and dark mode, or switch from dark to light and change color normally

### Actual Behavior

Dark color switch to light color style failure

**Comment by duxphp** [comment]
window.Apex.tooltip.theme toggle normal
window.Apex.theme.mode toggle disabled

**Comment by brianlagunas** [comment]
You did not provide the required reproduction app.
