### ISSUE TITLE
Adding Treemaps in version 3.21.0 broke "Inverse" functionality for Distributed color Heatmap

### ISSUE THREAD

**Issue by jaks6** [apexcharts/apexcharts.js#2808]
### Description
Inverse functionality seems to break since version 3.21.0 incase "Distributed" option is also used on a heatmap. The described issue does not exist in version 3.20.2!

### Steps to Reproduce

1. Create a heatmap in version 3.21.0 or newer, It needs to have   **_plotOptions.heatmap.distributed_** - **true**.  Example: https://codesandbox.io/s/apexcharts-examples-forked-9uzw0?file=/src/heatmap.js .
2. Try to switch **_plotOptions.heatmap.colorScale.inverse_** between "true" and "false"

### Expected Behavior
When toggling the  **_inverse_** option, expect to see the coloring be row-based or column-based

### Actual Behavior
Coloring remains column-based for both values.

### Reproduction Link

https://codesandbox.io/s/apexcharts-examples-forked-9uzw0?file=/src/heatmap.js .

**Comment by junedchhipa** [comment]
Thanks for reporting. The bug will be fixed with the release of next version.
