### ISSUE TITLE
Multiple color gradient in line chart

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/apexcharts.js#282]
Hi, I want to add multiple color in my line chart with gradient.
I tried everyting I can but chart is only getting 2 colors.

Example is [here](http://jsfiddle.net/jsinh0001/8ekw7hsq/9/)

What I want:
Multiple gradient colors. Like below
![mul](https://user-images.githubusercontent.com/31243533/51530147-5566b980-1e60-11e9-8fd0-f48a123f3aac.PNG)

**Comment by jsinhSolanki** [comment]
OK @junedchhipa

Thanks

**Comment by cardiv** [comment]
I need custom colors for gradients too.

**Comment by junedchhipa** [comment]
Multiple gradient stops will be available in v3.3.2

**Comment by junedchhipa** [comment]
Released 3.4.0
The multi-stops gradient is now available

![screen shot 2019-02-17 at 9 48 47 am](https://user-images.githubusercontent.com/17950663/52908308-4aede300-3299-11e9-822f-a48ae92accaa.png)

[Codepen example](https://codepen.io/apexcharts/pen/RvqdPb)

**Comment by alon-loris** [comment]
How can I give the markers the relevant color as well?

**Comment by Scarecr0w9758** [comment]
> How can I give the markers the relevant color as well?
**I found out how you can do it.** 
### 1) Use discrete markers 
<img width="615" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/132538423/aa47c5a9-a8f7-49ef-ab49-8137a2d55b25">
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/15378ab1-aaf4-4063-a1d5-cd82ad50c4cf)

### 2) Check how much data you need to place on chart (my case - 12 is max count, but you can pass data.length)
My series variable:
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/cfa11fa6-052c-4899-ae9a-073782782f47)


### 3) Create your array of discrete markers (I'm using Vue3 composition API). In this array you create objects that will be placed to charts option. Here you can pass the color using data indexes from your server
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/0ff1f5d9-4f48-4a0d-84ce-6e967e17bca6)

I wrote a switch-case function to get colors using my needs:
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/84fcb9cf-de97-4c2d-9202-43dcd2c68e70)

### 4) Apply your discrete markers to options: 
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/7d2d4670-646f-4364-b449-ced319f07aaf)


### 5) So i got smth like that: 
![image](https://github.com/apexcharts/apexcharts.js/assets/132538423/656a4858-ee4e-49ef-a5cc-ac83cc6fdb56)


### !!! Note that markers inside tooltip would be not that cool)
<img width="785" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/132538423/19d29797-41d0-401f-ae87-7a63c621f1cb">
