### ISSUE TITLE
Allow multiple lines on a stacked combo column chart without them stacking

### ISSUE THREAD

**Issue by BFalls158** [apexcharts/apexcharts.js#2821]
## Summary
As the title suggests, allowing multiple lines on the same column chart (specifically stacked in my case) would be wonderful.

## Intended Use Case
I am using a combo column/line chart to display different sales goals by category (as different lines) as well as total revenue by category (as stacked columns). Currently, the first line works wonderful, but when adding another it tries to stack on top of the other line graph (ie, two line data points at 100 and 150, the first is at 100 the second at 250).

**Comment by MarcelFranken** [comment]
+1
