### ISSUE TITLE
How to reverse default behavior of legend onItemClick?

### ISSUE THREAD

**Issue by faizalami** [apexcharts/apexcharts.js#2824]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/2823

<div type='discussions-op-text'>

<sup>Originally posted by **faizalami** December 13, 2021</sup>
Hello, the current behavior of legend onItemClick is to hide the selected series and keep the other to display, but what I need is the opposite, I need to only display the series that I clicked and hide the other.

I found a bad solution that use looping and call [hideSeries method](https://apexcharts.com/docs/methods/#hideSeries) for each series names that must to be hidden, but of course this solution will be bad at performance, the chart will be re render each hideSeries called.

So, is there any method to hide mass/batch series? or how to do that?

why something as simple as series: {data: [...], name: 'a series', **show: false**} didn't exist?</div>

**Comment by brianlagunas** [comment]
This is already a discussion. Please do not double post.
