### ISSUE TITLE
Charts not shown immediately on Bootstrap inactive tabs

### ISSUE THREAD

**Issue by nplatis** [apexcharts/apexcharts.js#2825]
### Steps to Reproduce

1. Please visit https://codepen.io/nplatis/pen/dyVNQgd
2. Each tab has one chart. The chart on the first tab ("Home") immediately appears.
3. Go to the "Profile" tab"; the chart does not appear.
4. Go back to the "Home" tab and then again to the "Profile" tab; the chart now appears correctly.

This happens with ApexCharts version 3.30 or 3.31; it does not happen with version 3.28.2 back to 3.26 at least (you may change the version used through the CodePen JS Settings).

The above CodePen is in conjuction with Bootstrap 4 tabs. Also tested with Bootstrap 5 tabs, see https://codepen.io/nplatis/pen/poWRGpZ

**Comment by InkyuJung** [comment]
I had a same issue with you. did you find the solution? or anyone else can help for better way to solve it?

**Comment by brianlagunas** [comment]
Wow! This is great @PlippiePlop. Thanks for taking the time to look into this issue and provide a solution. As proven by your solution, this is not a problem with apex charts, but rather the DOM behavior of tabs and their content.

Thanks again for the solution.

**Comment by nplatis** [comment]
I am sorry, but I think that the proposed code is just a _workaround_, a _hack_ that one has to devise in order to have charts appear correctly. The code I had used is completely legitimate and any other content in tabs works fine without pre-loading it; only apexcharts do not appear, and, in addition, they used to work in previous versions of the library.

As I mentioned, some code committed for version 3.30.0 affects this, since 3.28.2 works fine.

**Comment by PlippiePlop** [comment]
I see, 

ApexChart 3.33.0 has the same issue. 3.29 is ok 3.30 is not, so it happens between 3.29 <> 3.30.
So I traced it back to the replacement of the 'Detect Element Resize'  function in 3.29 and replaced in 3.30. for a new much more simplified resize detection handler addResizeListener (ResizeObserver) function.

So for now, if you don't need 3.30 and up stick to 3.29.

**Comment by brianlagunas** [comment]
Thanks for following up and confirming the issue is indeed related to apex charts.

**Comment by muriloime** [comment]
same issue here. Thanks @nplatis  @PlippiePlop for pointing out working versions.
