### ISSUE TITLE
Chart height and width issues in v3.30.0+

### ISSUE THREAD

**Issue by dopoto** [apexcharts/apexcharts.js#2829]
### Description

We are displaying an Apex Chart in a container. Everything was working fine in 3.29.0, but after updating to 3.32.0, the chart no longer occupies the full height and width of its container. However, when resizing the browser window, the chart redraws itself and the problem is corrected.

When inspecting it in DevTools, it looks like the style attribute highlighted in red in the image below is only set when resizing the window:

![image](https://user-images.githubusercontent.com/12781714/146196264-76b2e40e-29f9-4ab6-8de9-3ed150dfb583.png)

**Comment by brianlagunas** [comment]
Closing as you did not follow the issue template and provide a required reproduction app.
