### ISSUE TITLE
Donut Charts not showing when providing plotOptions

### ISSUE THREAD

**Issue by visaru** [apexcharts/apexcharts.js#283]
## Codepen
https://codepen.io/anon/pen/pGoqRd demonstrates the problem clearly
## Explanation

- I should see a donut chart
- Donut Chart not showing when providing plotOptions, copied from Docs of the appexcharts website?
- No error messages

**Comment by junedchhipa** [comment]
Sorry, the documentation for customScale default value was a bit wrong.
Change  `customScale` from 0 to 1
```
customScale: 1
```
