### ISSUE TITLE
Bar chart does not display integer values on x axis

### ISSUE THREAD

**Issue by gitgkk** [apexcharts/apexcharts.js#2835]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/2827

<div type='discussions-op-text'>

<sup>Originally posted by **gitgkk** December 15, 2021</sup>
I'm using bar chart from ApexCharts in vue but I the problem is basic and has to do with ApexCharts. 
The horizontal x axis has counts of items. When the number goes too low like 1, 2, the axis shows intermediate decimal values which doesn't make sense. The x axis shows floating point values, which is not the desirable output. How to display only integer values only with ticks at integer intervals like in second image?

Thanks for helping resolve this issue.

![ApexChartIssue](https://user-images.githubusercontent.com/22524880/146143650-c55328db-5104-450e-a7b6-cb60ba68db86.png)

[https://stackoverflow.com/questions/70336097/apexcharts-how-to-force-an-axis-in-bar-chart-to-display-integer-values-only](url)

`<apexchart ref="ratingChart" width="450" height="250" :options="ratingData.options" :series="ratingData.series" ></apexchart>`

`data: function () { return { ratingData: { options: { chart: { id: "item-rating", type: "bar", }, title: { text: "Item by Rating", align: "center", margin: 10, offsetX: 0, offsetY: 0, floating: false, style: { fontSize: "14px", fontWeight: "normal", fontFamily: "Arial", color: "#595959", }, }, noData: { text: "Loading...", }, xaxis: { categories: ["Very High", "High", "Medium", "Low", "Eliminated"], type: "category", tickPlacement: "on", labels: { rotate: 0, rotateAlways: false, }, decimalsInFloat: 0, }, colors: ["#E53935", "#FFA726", "#FDD835", "#7CB342", "#29B6F6"], dataLabels: { enabled: true, }, plotOptions: { bar: { distributed: true, borderRadius: 0, horizontal: true, }, }, }, series: [ { name: "itemCount", data: [10, 4, 8, 9, 3], //data: [1, 2, 2, 1, 3], // for low counts }, ], }, } }`
</div>

**Comment by brianlagunas** [comment]
Please do not double post your questions as issues.

**Comment by gitgkk** [comment]
> Please do not double post your questions as issues.

@brianlagunas I understand this aspect. Nobody responded to this question and I need a quick answer. Should I close it in the discussion and repost it?
