### ISSUE TITLE
Small charts not supported?

### ISSUE THREAD

**Issue by ivanjaros** [apexcharts/apexcharts.js#2838]
I want to create a small chart that is 75px * 25px but apex will not render it unless i get near 100px. Is there some internal limitation for the size that apex can generate? Based on the link below, that is not true, when i measure real dimensions. So the limitation must be somewhere else and therefore I think it is possible but am not sure why this behaviour happens to begin with.

Also this is directly related to https://github.com/apexcharts/apexcharts.js/discussions/2836

**Comment by brianlagunas** [comment]
If you feel you have found a bug, please provide the required information as described in the Bug Issue template. Especially the required reproduction app. Closing until those requirements have been met.

**Comment by ivanjaros** [comment]
Not much to add.
The vue version is:
`<apexchart width="W" height="H" type="line" :options="chartOptions" :series="series"></apexchart>`

where width is not necessary but height will not render anything if it is 60 or less. 61 and upwards will work.
