### ISSUE TITLE
Colors attribute does not work with functions

### ISSUE THREAD

**Issue by ivanjaros** [apexcharts/apexcharts.js#2839]
According to the [documentation](https://apexcharts.com/docs/options/colors/) the **colors** attribute should support function to provide dynamic coloring based on the values of each tick. But when used, the line is not visible at all and only basic hex color values work. In other words, when function is provided, I can see it is called and with expected arguments but often the value will show as undefined and the result is not used at all and the line is not visible at all.

I have apex charts 3.32.0 for vue.

**Comment by brianlagunas** [comment]
Closing as you did not follow the issue template and did not provide the required reproduction app.
