### ISSUE TITLE
"3 series with 2 scales" problem leads to no scale when some of series are hidden

### ISSUE THREAD

**Issue by dzek69** [apexcharts/apexcharts.js#2842]
### Description

I'm not really sure if I should report it as a bug (it seems like a bug from user perspective) or a feature request (because that's simply a thing you can't do).

### Steps to Reproduce

1. Follow the docs example: https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/#3-series-2-scales
2. On example click `Column A` and `Line C`  to hide them, leave `Column B` visible.

### Expected Behavior

1. Left scale should stay on the chart.
Please notice that example code shown in `How to associate a series with a Y-axis?` section of the docs are different than example code above the demo. The real demo maps series to scales as [AAC], while example above as [ABB]. That's why I expect left scale to stay on the real demo.

### Actual Behavior

1. All scales are hidden.

### Screenshots

![image](https://user-images.githubusercontent.com/4936805/146681555-c2e07af6-5725-4a31-96ab-0ab2ce0eaa49.png)

### Reproduction Link

https://codepen.io/junedchhipa/pen/wYOzjd - this is just the link from the docs, nothing is modified

### Proposed solution

Let `seriesName` of yaxis accept an array, which in result should tie multiple series to single yaxis

**Comment by Yokii908** [comment]
I'm having the same issue and the proposed solution makes a lot of sense. Allowing seriesName to be an array would make things much simpler for multi-series graphs.

**Comment by junedchhipa** [comment]
You can use `showAlways` property of the y-axis to prevent this from happening

```javascript
yaxis: [
    {
      seriesName: 'Column A',
      showAlways: true,
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
      },
      title: {
        text: "Columns"
      }
    },
    {
      seriesName: 'Column A',
      show: false
    }, {
      opposite: true,
      seriesName: 'Line C',
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
      },
      title: {
        text: "Line"
      }
    }
  ],
  
```
