### ISSUE TITLE
Set fixed animation duration for radial chart

### ISSUE THREAD

**Issue by bartrikersnp** [apexcharts/apexcharts.js#2846]
## Summary

For radial charts, we would like to be able to set a fixed animation duration, so we can control how long an animation takes.
Currently, it is only possible to set an animation speed, but the actual animation duration is calculated based on the value, so the animation for a low value is very fast, and the animation for a high value is slower.

## API Changes

Either the way the duration of the radial chart animation is calculated should be changed to a fixed duration (which could be configured via the speed setting), instead of calculating it based on the values. Or you should be able to configure whether you want to set a fixed duration or use a relative speed.

## Intended Use Case

Currently, when you have a radial chart, the animation duration is dependent on the value of the chart and the speed setting. For a low value, the animation is very fast; for a higher value, the animation takes longer. 

The problem here is that when there is a lower value, there is actually less to animate (the radial chart is filled less), and it takes less time to fill it. So when you have a lower value, the animation is so fast, it is hardly noticeable. Of course you could increase the speed setting, but that would time charts with a higher value would take too long to animate. So imo, setting a fixed duration would be better: animating takes 800 ms, for example.

In our use case, we also have multiple radial charts on the same page, each with different value, and thus each now have a different duration. It would be much easier on the eyes if the duration for all these charts would be the same, regardless of the value. So a chart with a low value, animates slower, and a chart with a higher value, animates faster. But they all have the same duration, so they're all finished animating at the same time.

So in this example, I want both charts to be finished animating at the same time
![radial chart](https://user-images.githubusercontent.com/88193355/147117785-ed99d595-8f17-4805-8671-f93710a02e0c.gif)

Like this:
![radial chart fixed](https://user-images.githubusercontent.com/88193355/147457810-14d4dc63-a87d-4ed0-81ff-06845f6914e6.gif)

The work around currently would be to calculate the speed needed for a fixed duration: https://codepen.io/bartrikers/pen/PoJEZEp

PS: I'm not familiar with other chart types, so I don't know if this also applies for other chart types.

**Comment by junedchhipa** [comment]
You're right. The current implementation is wrong as it shouldn't take the value into consideration and just finish the animation by the speed set by the user.
I will correct this behavior, thanks for pointing this out!
