### ISSUE TITLE
Clear chart data?

### ISSUE THREAD

**Issue by mgarcia96** [apexcharts/apexcharts.js#285]
Hey there, I have a Stacked Columns and I append data to the chart via Ajax, but how can I clear the data on every Ajax call?

**Comment by junedchhipa** [comment]
You should use the [updateSeries](https://apexcharts.com/docs/methods/#updateSeries) to modify the data / clear the data.

```javascript
           chart.updateSeries([{
                name: 'Series A',
                data: []
            }])
```

The above will render a blank chart
