### ISSUE TITLE
Brush out of sync on chart after click

### ISSUE THREAD

**Issue by Diego-AC** [apexcharts/apexcharts.js#2850]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/2847

<div type='discussions-op-text'>

<sup>Originally posted by **Diego-AC** December 22, 2021</sup>
Clicking the brush causes the chart to go out of sync. it changes the xaxis in a large proportion and only at the first click.
I have seen different examples of brushes and I noticed that they all have a movement after the first click on the brush.

From the documentation I have been able to capture the movement of the brush through the method [brushScrolled](https://apexcharts.com/docs/options/chart/events/#brushScrolled) .I understand that through the method I can capture the **chartContext** and the final **xaxis** of the brush, then it is possible to calculate the time difference.

Is it possible to avoid this behavior by modifying parameters in chartContext?

![Error-brush-apexchart](https://user-images.githubusercontent.com/52457234/147156194-6f5c3cb0-f023-4d90-9941-4b20ca3175b5.gif)

</div>

**Comment by brianlagunas** [comment]
Please do not cross post discussions as issues. If you believe you have found a bug please follow the bug issue template and provide all required information.
