### ISSUE TITLE
Scrollable charts for large data set

### ISSUE THREAD

**Issue by bahung1221** [apexcharts/apexcharts.js#2853]
## Summary

For the large data set, we need a scrollbar to allow users to interact with the chart on a small width/height container. And also when we scroll the chart, the xaxis/yaxis should be sticky.

Sample from Highcharts: https://www.highcharts.com/docs/chart-concepts/scrollbar
Jsfiddle: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

## API Changes

I'm not sure about the API changes, I think we must split the axes and the chart into different containers and then make the chart `overflow: scroll`, so the chart will be scrollable and the axises still sticky on the front of the chart.

## Intended Use Case

For large data sets which can't be displayed well in a small container.

There is a related issue here: https://github.com/apexcharts/apexcharts.js/issues/543

A usage sample for heatmap:
![Screen-Recording-2021-12-26-at-1](https://user-images.githubusercontent.com/27690861/147403089-025d93d4-a0c1-4ce1-9e05-ab0208a23a64.gif)

Thanks a lot 🍻

**Comment by bahung1221** [comment]
Still waiting for this feature, so don't close it, pls.

**Comment by patryk-zielinski93** [comment]
This is a great idea because if there is a lot of data bar charts become unreadable. 
E.g.: https://codepen.io/zielu701/pen/poLrPaQ
Some of the x axis labels are hidden also data labels on bars are unreadable. Scrolling ability will solve these issues.

**Comment by cverster** [comment]
Please re-open this! This would be a great feature.

**Comment by markoueis** [comment]
Need this feature as well +1

**Comment by VaidehiShrivastava** [comment]
I need to implement the same feature request in production but couldn't introduce a vertical scroll inside chart area with fixed x axis. Please suggest some way through which it can be achieved.

**Comment by asboldyrev** [comment]
This is a very necessary function. I have to write very bad code to implement something similar.

**Comment by buildsomethingdifferent** [comment]
still waiting on this thing

**Comment by sandermanneke** [comment]
Also interested to see this added

**Comment by Praveen-Kumar-sekar** [comment]
@sandermanneke  is this feature enabled?? can you share me the docs or sandbox / codepen for this ?

**Comment by KamaMakh** [comment]
Need this feature as well

**Comment by dev-externlabs** [comment]
https://github.com/apexcharts/apexcharts.js/issues/1563#issuecomment-770955610

Solved my issue

**Comment by CJ-rogue** [comment]
waiting for this feature.

**Comment by misgana96** [comment]
Waiting for this feature

**Comment by jschank** [comment]
I would like this also.

**Comment by huannguyenbnk** [comment]
Is this feature available yet?

**Comment by kabir-ripik** [comment]
Stil not available?

**Comment by iamifechi** [comment]
I think having options to make either the x or y axis sticky while the other axis overflows might solve this issue.
For my own case I've been able to get it to scroll on the x-axis inside a parent container with a max-width and overflow-x-auto but I lose track of the y-axis as I scroll.

Interested in this feature though.
