### ISSUE TITLE
Legend Colours not updating

### ISSUE THREAD

**Issue by psambit9791** [apexcharts/apexcharts.js#287]
Codepen: https://codepen.io/psambit9791/pen/aXvNwx

Problem: 
On changing the stroke color of the line on the chart, the legend does not seem to automatically update the new colors. Moreover, any changes being made to the markers on legend options does not seem to get reflected.

Expected behaviour:
On defining the markers option with the relevant colors (list of colors), the new legend colors should be updated on the chart.

**Comment by junedchhipa** [comment]
You should set the primary `colors` and everything else will inherit from there.
Your updated example - https://codepen.io/apexcharts/pen/VgvaGa

**Comment by AdrianoFSilva1** [comment]
Hello, Im with the same problem and your solutiuon didn't work for this. Here you have a [CodePen](https://codepen.io/Adriano01/pen/jOOEjQv) where is occurring the problem. I tried to change the stroke color and it works but I can't change for the legend.

**Comment by psambit9791** [comment]
Based on my experience, apex can deal with 5 datasets without any specific color description because it automatically selects the colors from a  pre-defined list. Beyond the top five, it repeats the same colors again. In such cases, the specific colors need to be defined within the options.

Check this codepen: https://codepen.io/psambit9791/pen/QWWNjdN

**Comment by AdrianoFSilva1** [comment]
It works! Thank you!

**Comment by bibhash772** [comment]
Hello Everyone,

Hope all are doing well.

I have an issue with Apex chart. i need to show maximum 5 legends on chart horizontally as i am having 100s of legends. can anybody please share an example of codepen.

Thanks
CHintesh k.

**Comment by llanero7** [comment]
It Worked!
