### ISSUE TITLE
console error occurs when selecting to download svg file, please fix

### ISSUE THREAD

**Issue by usermeme** [apexcharts/apexcharts.js#2871]
REOPEN [2465](https://github.com/apexcharts/apexcharts.js/issues/2465)
### Description

When downloading svg file function getSvgString will be executed without required argument - scale, thereby width and height will be NaN

### Steps to Reproduce

1. open console
2. download svg 

vue-apexcharts 1.6.2 + apexcharts 3.32.0

**Comment by brianlagunas** [comment]
Please do not create a new issue just to request to open an existing issue
