### ISSUE TITLE
Markers are Missing on Hover When size is zero

### ISSUE THREAD

**Issue by avishairoi** [apexcharts/apexcharts.js#2872]
### Description

While using the line chart, I was trying to not have any marker points unless I will hover over the chart.
When the Y-axis will contain values greater than 0, it works perfectly fine. But, if the Y-axis value equals 0, the markers will not show up at all.

### Steps to Reproduce

1. Create a line chart.
2. Use data that contains 0 values in y-axis.
3. Set markers size = 0.
4. Set markers hover size = 3.

```
markers: {
        size: 0,
        colors: ["#ffffff"],
        strokeColors: [baseColor],
        strokeWidth: [2],
        hover: {
          size: 3,
        },
      },
```

### Expected Behavior
Hovering zero values should show the marker points as it is shown when the y axis value is greater than zero.

### Actual Behavior
Hovering zero values does not show the marker points as it shows when the y axis value is greater than zero.

### Screenshots

![image](https://user-images.githubusercontent.com/54622738/148381439-eb1d8f07-8511-49ac-9394-e12ff0d6d6a3.png)
But here...
![image](https://user-images.githubusercontent.com/54622738/148381566-5b36f78a-cd06-4721-90e8-22104acaadad.png)

### Reproduction Link
https://codepen.io/avishairoi/pen/MWEXMjz

**Comment by avishairoi** [comment]
@junedchhipa could you please at least explain why did you close this issue?

**Comment by junedchhipa** [comment]
@avishairoi I closed the issue with a fix. Please check the commit I have linked above.
The fix will be released in the next patch version (probably this week)

**Comment by avishairoi** [comment]
Hi, thanks for your reply,
I missed it. Thanks!
