### ISSUE TITLE
TypeScript Types: Allow Newtypes for Axes

### ISSUE THREAD

**Issue by toastal** [apexcharts/apexcharts.js#2877]
## Summary

Currently the axes and their formatter functions take a `number` as a first argument. This is prohibitive for people that want stronger types as that doesn't explain what _kind_ of number, strings, dates these represent.  This extends to some other types with formatters as well, but these two are getting in my way.

## API Changes

All types allow power users to override, while not breaking current code. Example:

```typescript
declare module ApexCharts<X = number, Y = number> {
  export interface ApexOptions {
    // ...
    xaxis?: ApexXAxis<X>
    yaxis?: ApexYAxis<Y> | ApexYAxis<Y>[]
    // ...
  }
}

export interface ApexXAxis<X = number> {
  // ...
  formatter?(val: X, opts?: any): string
  // ...
}
}

export interface ApexYAxis<Y = number> {
  // ...
  formatter?(val: Y, opts?: any): string | string[]
  // ...
}
```

Maybe this would required an additional, optional `getter` (ala Lenses, `function toNum(a: A): number { .. }` with our default being `identity` since the default is a `number`) because you need a `number` for the data, but that's a small price to pay to be able to specify real types for the axes.

I am quite new to TypeScript so I don't know what sort of implications this change has or if this syntax is entirely correct.

## Intended Use Case

In PureScript/Haskell, I would use Newtypes to 'wrap' my `number`s so the wrong type of number doesn't go into the wrong function.

```purescript
newtype USD = USD Number
newtype EUR = EUR Number

-- Pattern matching on the USD wrapper, print USD as string
printUSD ∷ USD → String
printUSD (USD usd) = implementation usd -- suppose Intl.NumberFormat
```

_You can do this exact pattern with [`newtype-ts`](https://github.com/gcanti/newtype-ts) from the `fp-ts` sphere, but the code is much less terse._

In this example my `printUSD` function does _not_ allow `number`s as input _and_ it doesn't allow Euros, only US dollars as my type says. This is perfect for my formatter on my axes. If I have a chart with an access that contains `USD`, want the appropriate formatter to match, I can guarantee my formatter matches. With this example I could do something like

```typescript
// `Percent` & `USD` are Newtypes wrapping `number`
const myOpts: ApexOptions<Percent, USD> = {
  xaxis: {
    formatter: printPercentage,
  },
  yaxis: {
    formatter: printUSD.
  }.
}

function printPercentage(percent: Percent): string {
   const f = new Intl.NumberFormat(undefined, { style: "percent" })
   return f.format(percent)
}

function printUSD(usd: USD): string {
   const f = new Intl.NumberFormat(undefined, { currency: "USD", style: "currency" })
   return f.format(usd)
}
```

**Comment by toastal** [comment]
Stalebots are bad. Issues don't go just bad.
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by brianlagunas** [comment]
Thank you for submitting your idea, but this not something we will be adding.

**Comment by david-induro** [comment]
I'm saddened by this response from the maintainers. For one, the type currently defined for `ApexOptions.tooltip.x.formatter` 
```ts
{
  formatter?(val: number, opts?: any): string
}
```
is incorrect in more instances than it is correct. `ApexXAxis.type` allows for category, datetime, and numeric. 
And the `ApexXAxis.labels.formatter` takes a string as it's value, 
```ts
{
  formatter?(value: string, timestamp?: number, opts?:any): string | string[]`)
}
```

If you use an array of strings for your x categories, then `ApexOptions.tooltip.x.formatter`'s first argument comes in as a string, but cannot be handled as it's true type without ugly type assertions. Typescript Types are meant to provide value to the developer, not put up roadblocks. In this specific case, the end user would've been better off even if the `val` argument was `any`. 

I hope the team reconsiders this position.
