### ISSUE TITLE
Annotation points missing data points

### ISSUE THREAD

**Issue by mrblur** [apexcharts/apexcharts.js#288]
## Codepen

https://codepen.io/mrblur/pen/vbNZbR

## Explanation

- What is the behavior you expect?
As suggested in #286, tried annotating specific point on linear graph with simple array as input.

- What is happening instead?
I am having serious problems with targeting right point on screen :laughing: 
No annotation points point the same pixel on screen that data points from data series. So it's impossible to target a data point with annotation label.
[Demo](https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/) seems ok. Tried on my codepen with different stroke/size combinations with no luck. Applying `offsetX` to marker does change rendering, but requires different value with every "X" step.
What am I missing?

- What error message are you getting?
No errors, just working differently than expected :)

**Comment by junedchhipa** [comment]
There was a bug for which a fix has been done on github but is not released to npm (a new release will be done tomorrow).

So, I just temporarily fixed the issue by assigning
xaxis.type = ‘numeric’

Here is a complete codepen https://codepen.io/anon/pen/zevdLR

Hopefully, in the next release, you won’t have to apply this hack.

**Comment by mrblur** [comment]
Thanks, closing as it's already fixed. Can't wait for next release!
