### ISSUE TITLE
Active Date

### ISSUE THREAD

**Issue by Rukeeo1** [apexcharts/apexcharts.js#2888]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/2887

<div type='discussions-op-text'>

<sup>Originally posted by **Rukeeo1** January 12, 2022</sup>
<img width="1079" alt="Screenshot 2022-01-12 at 19 54 38" src="https://user-images.githubusercontent.com/44168306/149203862-23772fe0-cea9-466b-89aa-044f68bb1536.png">

Hello, above is a sample of what my x-axis looks like using date-time graph. 

There are two issues:

1. the current date/day (Wednesday), which is represented by the green is not bold. I want to increase the font-weight.
2. Saturday is bold by default...I don't want this. Just incase I discovered Saturday is the first day of the year 2022.  I don't want any day outside the current selected date to be bold</div>

**Comment by brianlagunas** [comment]
Please do not double post. When submitting an issue you must follow the issue template.

**Comment by Rukeeo1** [comment]
Hello @brianlagunas  thanks. 

Please where can I find the issue template.

And since I already asked the question in the Q/A section can you help with suggestions there?

**Comment by brianlagunas** [comment]
You pick which template to use when you create a new issue. If you already asked your question as a discussion, then there is no need to double post it. Just wait for the community to answer your question.

**Comment by Rukeeo1** [comment]
thanks
