### ISSUE TITLE
Error when updating an area chart series reactively when stroke.show = false

### ISSUE THREAD

**Issue by oller** [apexcharts/apexcharts.js#289]
I'm not sure if this is an issue with the vue wrapper components or the core apexcharts lib, but there's a bug nevertheless. So feel free to move this issue to the other repo.

See the example here:

https://codesandbox.io/s/z21243ppjl

Chart updates correctly when shuffle data button is hit, then go to HelloWorld.vue and uncomment the stroke.show = false flag and shuffle the data again.

Excellent lib, only issue i've found so far!

**Comment by junedchhipa** [comment]
The issue is with the core-lib. 
Thanks for reporting, will look into the issue soon.
