### ISSUE TITLE
(!) Memory Leak in website demo page

### ISSUE THREAD

**Issue by GitSquared** [apexcharts/apexcharts.js#29]
I am experiencing a critical memory leak issue when trying to access https://apexcharts.com/javascript-chart-demos/

I'm using Firefox Developer Edition 62.0b15 (64-bit), on Debian 9.5 "Stretch".

Here is a [video proof](https://www.youtube.com/watch?v=_IpTUAQOszY) (youtube link). You can clearly see the CPU going crazy at around 15 to 20 seconds in the video, only a few moments after loading the page. Then, the memory starts filling up rapidly, eventually eating through swap space, at that point i have no choice but to kill Firefox to keep my system stable.

I do have a few addons installed on the browser, but i do not believe that they have any impact on the issue.

Is anyone able to reproduce this behavior?

**Comment by arkhenstone** [comment]
Yup, tried on two computer, RAM usage gone wild, had to restart my PC. Tried on Firefox Linux and Chrome Windows.

**Comment by paulocoghi** [comment]
> Is anyone able to reproduce this behavior?

Yes, same issue here. Firefox 62.0b15 (64-bit) _(non-developer)_ on Ubuntu 16.04.5 64bit

**Comment by junedchhipa** [comment]
@GitSquared Confirmed the bug.
The memory leak is due to the mixed chart. I disabled each chart one by one and disabling mixed charts made the page responsive. Otherwise, my firefox was also crashing every time I loaded the demo page.

I will investigate the mixed chart rendering, thanks for reporting

**Comment by GitSquared** [comment]
@junedchhipa It's working for me now. Thanks for the quick response. Closing.

**Comment by arkhenstone** [comment]
@junedchhipa Dashboard demo has the same problem

**Comment by junedchhipa** [comment]
@arkhenstone I will check the Dashboard too. Combo chart (line/area/column) seems the main culprit. I will try to fix it quickly so I don't have to go to each and every place to disable Mixed Charts ;)

**Comment by GitSquared** [comment]
I believe @arkhenstone reported this issue to also happen in Chrome, nah?

> Tried on Firefox Linux and Chrome Windows.

Is this still true or is this issue really Firefox-specific?

**Comment by junedchhipa** [comment]
Ah! right. If the same problem persists in Chrome as well, then this is not browser specific. Reverting title change

**Comment by junedchhipa** [comment]
I have fixed the issues which were crashing Firefox when viewing demo pages.

@arkhenstone can you please test the demo page as well as the dashboards?
@GitSquared can't reproduce the "heatmap" issue in firefox/chrome. Can you please test again and if error persists, give more info?

Thanks
