### ISSUE TITLE
Dashed crosshair doesn't render properly

### ISSUE THREAD

**Issue by dror-weiss** [apexcharts/apexcharts.js#290]
I'm trying to use "crosshairs" feature on the x-axis in a multiple charts graph.

The rendered dashed "crosshair" doesn't look good, as you can see in the attached image. 
It depicts two-part rendering for the "crosshair", one within the column and another outside of it, making the outside part's dash twisted.
 
<img width="207" alt="screen shot 2019-01-29 at 11 37 00" src="https://user-images.githubusercontent.com/38240585/51900165-48e0e480-23bd-11e9-9f0c-6b3c43827f01.png">

**Comment by junedchhipa** [comment]
Yeah, it looks like there has to be a correct combination of dashArray and dashOffset. I will play with different values and maybe provide an additional option `dashOffset` along with `dashArray` to control the spacings/size of the dashed line.

**Comment by junedchhipa** [comment]
Fixed it. 
When `crosshairs.width = 1`, it will draw a line instead of a rect which will prevent 2 borders.
