### ISSUE TITLE
border radius is not responsive

### ISSUE THREAD

**Issue by Revan99** [apexcharts/apexcharts.js#2901]
when I add border radius to the bars in the bar chart it's not responsive 

it become like this when the screen get's smaller 
![image](https://user-images.githubusercontent.com/46955286/149920574-18255183-125f-4540-9365-e906215d5b33.png)

and like this when the screen gets larger it loses border radius 100%
![image](https://user-images.githubusercontent.com/46955286/149920809-5e0c00ea-61c8-40c2-b150-17371b8242c8.png)

**Comment by brianlagunas** [comment]
You did not follow the required issue template
