### ISSUE TITLE
Pie charts does not display all series data Chrome, Edge

### ISSUE THREAD

**Issue by jdecarlo** [apexcharts/apexcharts.js#2905]
Pie chart has 1 series with 10 floats and displays all 10 items in the legend, but only shows 4 items in the pie in one scenario and 8 of 10 in another.

Browsers tested:
- Chrome on macOS (Big Sur/Monterey) - Not working
- Chrome on Windows 10 - Not working
- Edge on Windows 10 - Not working
- Firefox on macOS (Big Sur/Monterey) - Working as expected
- Safari on macOS (Big Sur/Monterey) - Working as expected

Environment:
- Apex Charts 3.32.1
- Vue 2.6.11
- Vue-ApexCharts 1.6.2
- Vuetify - 2.3.13

**Comment by brianlagunas** [comment]
You did not provide the required reproduction app.
