### ISSUE TITLE
BarChart dataLabels offsetX incorrect alignment

### ISSUE THREAD

**Issue by rod-stuchi** [apexcharts/apexcharts.js#2918]
### Description

Tested versions `"apexcharts": "^3.33.0"` with `"react-apexcharts": "^1.3.9"`.

When the offsetX is a negative value, it not keep aligned with the label

### Steps to Reproduce

1. Set `dataLabels` to 
```javascript
    dataLabels: {
      enabled: true,
      textAnchor: 'start',
      offsetX: -20,
      offsetY: -25,
      dropShadow: {
        enabled: false,
      },
    },
```

### Expected Behavior
Applying a negative value on offsetX, should keep all the data labels aligned with the same `x` value

### Actual Behavior
Applying a negative value on offsetX, makes each label with a different `x` value (misaligned)

### Screenshots

![screenshot 2022-01-24T15 57 42](https://user-images.githubusercontent.com/19471811/150853112-8ee4a866-11ae-4569-827c-a7121fde8757.png)
![screenshot 2022-01-24T15 59 23](https://user-images.githubusercontent.com/19471811/150853115-507d154e-2ba3-4880-ad74-806f96f4d360.png)

### Reproduction Link

https://codepen.io/rodstu/pen/qBVWJJo

**Comment by junedchhipa** [comment]
This looks fixed with v4.3.0
