### ISSUE TITLE
Boxplot with categorical xaxis shows the outliers wrong if there's more than one boxplot on the graph

### ISSUE THREAD

**Issue by EdwinArgudo** [apexcharts/apexcharts.js#2919]
### Description

This relates to an issue which was recently closed ([link](https://github.com/apexcharts/apexcharts.js/issues/2706))
If you have more than one boxplot on a graph, and have outliers in each graph, the outliers will show incorrectly.

### Steps to Reproduce

1. Create a graph with 2 boxplots
2. Add an array of outlier data points to each boxplot

### Expected Behavior

I should see all of the outlier data points on the same vertical axis as the boxplot

### Actual Behavior

I see only one data point rendered on the same vertical axis as the boxplot

### Screenshots

<img width="514" alt="Screen Shot 2022-01-11 at 5 00 17 PM" src="https://user-images.githubusercontent.com/35999849/149028474-e43cf660-911f-45ce-9acc-b583838f5063.png">

### Reproduction Link

Link to codepen:
[Link](https://codesandbox.io/s/react-basic-example-forked-6snyy)

**Comment by EdwinArgudo** [comment]
Any updates?

**Comment by mmassetti** [comment]
I have the same problem!

**Comment by Abhiknav** [comment]
Even i m facing the same issue, any updates on how to fix this issue ?

**Comment by pvictor** [comment]
+1 ❤️

**Comment by tiamfei** [comment]
I'm facing the same issue and waiting for the fix.

**Comment by loveetsuko** [comment]
i'm having the issue with apex chart v3.52.0. anyone has idea on how to solve this?

**Comment by MarceloEmmerich** [comment]
Same problem, any update?
