### ISSUE TITLE
Radial Bar Chart 

### ISSUE THREAD

**Issue by AdabanyaChinedu** [apexcharts/apexcharts.js#2940]
### Description

The default plot/track direction of Radial bar chart is clockwise. Is there a way to change the direction to Anti-clockwise. I have tried to tweak startAngle and endAngle to see if I can achieve that but all effort made was futile. In Rechart(react.js chart library), this can easily be achieved by manipulating startAngle and endAngle.

### Steps to Reproduce

1. 
2. 
3.

**Comment by MeisterBob** [comment]
I was also looking for the anti-clockwise Radial Bar Charts. Would it be possible to add that feature?
