### ISSUE TITLE
Discrete marker are not working with sparkling chart

### ISSUE THREAD

**Issue by Yamin-lawar** [apexcharts/apexcharts.js#2941]
### Description
I am using sparkline line chart and I want marker at the end of the my chart. For that I have configure chart with the discrete configuration as suggested in [doc](https://apexcharts.com/docs/options/markers/#). 

`markers: {
  size: 0,
  discrete: [{
    seriesIndex: 0,
    dataPointIndex: 7,
    fillColor: '#e3e3e3',
    strokeColor: '#fff',
    size: 5,
    shape: "circle" // "circle" | "square" | "rect"
  }]
}`

But it doesn't work because size 0 will hide all the marker & if I add size it add marker on every data points. 

Also When using marker in spark-line it cut the marker I tried to increase height and width but it didn't worked 

<img width="119" alt="Screenshot 2022-01-28 at 8 06 01 PM" src="https://user-images.githubusercontent.com/10362512/151565406-d53800de-ffee-42bf-824d-9edecc5ce7dc.png">

**Comment by brianlagunas** [comment]
You did not follow the issue template and did not provide the required reproduction app
