### ISSUE TITLE
Can we have to set personalized datalabels in rangeBar chart?

### ISSUE THREAD

**Issue by bulhoes1998** [apexcharts/apexcharts.js#2946]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/2945

<div type='discussions-op-text'>

<sup>Originally posted by **bulhoes1998** February  2, 2022</sup>
I want set a personalized dataLabel for my range Bar chart, but the documentation indicate that i could only set datalabels that origins from the parameters x and y, but the values that i have to set are in another variable. How can i set this datalabel? 
![photo_2022-02-02_14-12-19](https://user-images.githubusercontent.com/90818840/152203847-6328dc36-be4a-4f6c-8bee-cef424e2fe46.jpg)

</div>

**Comment by brianlagunas** [comment]
Please do not double post.
