### ISSUE TITLE
Synced charts padding variation (causes hover issues)

### ISSUE THREAD

**Issue by elbojoloco** [apexcharts/apexcharts.js#295]
## Explanation

The labels are exactly the same on both charts. The only difference is the value of X. Not many custom options are set other than the markers and some tooltip/label formatting. The charts are also exactly the same width/height.

- What is the behavior you expect?
The padding to be synced so that the hover position matches precisely.

- What is happening instead?
Padding seems to be also dependant on `x` value

- What error message are you getting?
None

![syncnotverysync](https://user-images.githubusercontent.com/7912315/51996009-3a292900-24b4-11e9-9f85-c7e0f19a8c41.gif)

I just found out this issue is also present in the docs sync example: https://apexcharts.com/vue-chart-demos/line-charts/syncing-charts/

![syncnotvoscserysync2](https://user-images.githubusercontent.com/7912315/52041602-2ecd1080-253b-11e9-9ec1-6a6995333d19.gif)

I've added rulers to try visualize the problem more, apperantly the extra padding is only on the left side of the chart. The right side is still in sync. [https://imgur.com/a/JWntKF4](https://imgur.com/a/JWntKF4)

**Comment by junedchhipa** [comment]
@elbojoloco Thank you for digging out the issue.
One option is to ask the user to provide a `min-width` for all grouped charts and it has to be the same for all grouped charts. Another option is to automatically set the `min-width` for y-axis when the charts are grouped.

I will look more into which option is more feasible.
Thanks for reporting.

**Comment by junedchhipa** [comment]
Maybe something else is interfering. May I get a working codepen example?
I just checked out the `yaxis.labels.minWidth` for the syncing charts example, and it works fine.

**Comment by elbojoloco** [comment]
I was checking the <svg> element for the labels, i see the minWidth just places them more to the right now. It works :)

**Comment by junedchhipa** [comment]
@elbojoloco That's what I was thinking about. I will implement this in the upcoming releases.

**Comment by junedchhipa** [comment]
Re-opening this until a fix is released.

**Comment by junedchhipa** [comment]
Added a `console.warn` which asks the user to provide `yaxis.labels.minWidth` when charts are grouped. Setting the width automatically required a lot of calculations for all charts, so decided to add a console.warn

**Comment by junedchhipa** [comment]
Docs require update stating this requirement.

**Comment by junedchhipa** [comment]
Added docs for the synced charts - https://apexcharts.com/docs/chart-types/synchronized-charts/

**Comment by jesseglab** [comment]
Hey,

Having the same issue and warning pop up despite setting minWidth and declaring global values. none of these seem to work.
