### ISSUE TITLE
any chat not works with firefox + linux

### ISSUE THREAD

**Issue by RodrigoDornelles** [apexcharts/apexcharts.js#2950]
### Description

I've tested it on about 4 different linux machines, with different versions of firefox, but not so outdated, and none of them the graphics are displayed.

In any other browser it will work.

### Steps to Reproduce

1. Use linux
2. Use firefox

### Screenshots

| ![image](https://user-images.githubusercontent.com/29123479/152794854-7abdccb3-7156-4df2-9cda-e16a90ac05de.png) | ![image](https://user-images.githubusercontent.com/29123479/152795067-753763c6-caff-46aa-bb11-26b042ca09bd.png) | ![image](https://user-images.githubusercontent.com/29123479/152795435-59524f46-2633-47ac-b00a-d047fe038400.png) | 
| :-: | :-: | :-: |

**Comment by brianlagunas** [comment]
You did not follow the issue template
