### ISSUE TITLE
Zoom chart programmatically

### ISSUE THREAD

**Issue by skerit** [apexcharts/apexcharts.js#296]
After creating my timeseries chart, I want to manually zoom in to the data of the last 2 weeks, but I can't seem to find any information on zooming in programmatically in the documentation.

Could someone shed some light on this?

**Comment by junedchhipa** [comment]
To zoom the time-series programmatically, the recommended way is to call the `updateOptions()` method with the specified xaxis.min and xaxis.max

Here is a complete demo of programmatically updating the xaxis so it looks like the chart is zoomed in/out.
Vue/React demos are also on the website if you are using those frameworks.

**Comment by skerit** [comment]
Ah, didn't know the zoom worked that way. That does the trick indeed, thanks!

**Comment by junedchhipa** [comment]
Added the demo URL in the original comment which got removed.

**Comment by jatindumka** [comment]
@skerit @junedchhipa zooming effect not working for heatmap.

**Comment by Saurav-Jain** [comment]
I want to Zoom in apex advanced timeline chart but zoom in not work. Any suggestion why zoom in not work

chart: {
          height: 350,
          type: 'rangeBar',
          stacked: false,
          zoom: {
            type: 'xy', 
            enabled: true,
            autoScaleYaxis: true,
            toolbar: {
                autoSelected: 'zoom',
                tools: {
                    download: true,
                    selection: true,
                    zoom: true,
                    zoomin: true,
                    zoomout: true,
                    pan: true,
                    reset: true
                },
            }

          }
          
        }



this is full code of it

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    
    <title>chart</title>
	
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

	
	

  </head>
  
  
  <body>
  
  <div id="chart">
</div>
  
  
  <script>
  
	var options = {
        series: [
          {
            data: [
              {
                x: 'Code',
                y: [
                  new Date('2019-03-02').getTime(),
                  new Date('2019-03-04').getTime()
                ]
              },
              {
                x: 'Test',
                y: [
                  new Date('2019-03-04').getTime(),
                  new Date('2019-03-08').getTime()
                ]
              },
              {
                x: 'Validation',
                y: [
                  new Date('2019-03-08').getTime(),
                  new Date('2019-03-12').getTime()
                ]
              },
              {
                x: 'Deployment',
                y: [
                  new Date('2019-03-12').getTime(),
                  new Date('2019-03-18').getTime()
                ]
              }
            ]
          }
        ],
        chart: {
          height: 350,
          type: 'rangeBar',
          stacked: false,
          zoom: {
            type: 'xy', 
            enabled: true,
            autoScaleYaxis: true,
            toolbar: {
                autoSelected: 'zoom',
                tools: {
                    download: true,
                    selection: true,
                    zoom: true,
                    zoomin: true,
                    zoomout: true,
                    pan: true,
                    reset: true
                },
            }

          }
          
        },
        plotOptions: {
          bar: {
            horizontal: true
          }
        },
        xaxis: {
          type: 'datetime'
        }
      };

      var chart = new ApexCharts(document.querySelector("#chart"), options);
      chart.render();
  
  </script>
  
  
  </body>
  
  
  </html>

**Comment by junedchhipa** [comment]
@Saurav-Jain Timeline charts don't support zoom yet.

**Comment by ChuckzM** [comment]
I know this is closed but I've been trying to use zoomX on a time series chart using "exec".

`ApexCharts.exec('charID', 'zoomX', new Date('2020-04-04  01:00:00').getTime(), new Date('2020-04-04  12:00:00').getTime());`

But it seems to not be working and I can't find documentation on how to use zoomX within an exec.

**Comment by junedchhipa** [comment]
@ChuckzM Have you tried upgrading ApexCharts to the latest version (3.19.3)?

**Comment by shruti-reddy** [comment]
Hi, I'm using line chart in apex, but its completely zoomed in once its loaded. I'm not sure why this is happening. can someone please help me with this I really don't need zooming

**Comment by mudy649** [comment]
@junedchhipa 
Hi ,
Advance Time Series Chart height not accepting "100%", is it not possible that we can set Bar height fixed. If more Bar add then all Bar squeeze.

**Comment by RealTimeShepherd** [comment]
@junedchhipa Hi, are you planning on implementing the zoom feature for heatmaps/timelines?
