### ISSUE TITLE
Enable auto dark mode

### ISSUE THREAD

**Issue by steebchen** [apexcharts/apexcharts.js#2974]
## Summary

As a follow up on #218, it would be actually great to be able to set the theme.mode to `auto` instead of dark/light, so that it would switch depending on the OS setting.

## API Changes

```js
theme: {
  mode: 'auto',
},
```

## Intended Use Case

Right now I have to do the following manually:

```js
theme: {
  mode: window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light',
},
```

Also, if the mode would change while on the site, I'd additionally need to listen for changes and update it:

```js
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    const newColorScheme = event.matches ? "dark" : "light";
});
```

So it would be great if one could just set `mode: 'auto'` and let apexcharts handle it.

**Comment by steebchen** [comment]
not stale

**Comment by Arthur-adrenalead** [comment]
Please add this features !!!1
