### ISSUE TITLE
[Question] Does apex support angular JS ? 

### ISSUE THREAD

**Issue by sanymochi** [apexcharts/apexcharts.js#298]
1. We are planning to use Angular JS with apex. Does apex support angular JS ? if yes, which version it supports.
2. Which is best supporting JS for apexchart in terms of flexibility and performance like Angular, ReactJs etc ?

**Comment by junedchhipa** [comment]
1. People have been using ApexCharts with Angular 2+ without any major issues. Typings are provided in the `types` directory.
2. ApexCharts will not have any difference in terms of performance or usability whether it is used in Angular/Vue/React. The React/Vue plugins which are created just make it easier to fit in their respective eco-system.

ApexCharts.js has been created as a framework agnostic library without keeping any particular framework in mind, hence it should be treated as such.
