### ISSUE TITLE
Tooltip colors for Pie/Donut charts don't reflect custom colors

### ISSUE THREAD

**Issue by stanimirivanovde** [apexcharts/apexcharts.js#2980]
### Description
Can't seem to change the color of the tooltip and the donut labels displayed inside the chart. I updated the colors for the legend and the actual slices but not the tooltip and inside label.

### Steps to Reproduce

1. Pass in custom colors for the chart 
2. Modify the legend and tooltip to use them
3. See that the tooltip is not reflected including the labels 

Chart options that reproduce the issue:
```javascript
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "donut",
    labels: ["Apple", "Orange", "Mango"]
  },
  fill: {
    colors: ["#f44336", "#ff9800", "#4caf50"]
  },
  series: [1, 5, 10],
  legend: {
    // Show the legend
    show: true,
    markers: {
      // Set the legend colors as the ones passed in
      fillColors: ["#f44336", "#ff9800", "#4caf50"]
    }
  },
  tooltip: {
    enabled: true,
    fillSeriesColor: true
  }
};
```

### Expected Behavior
The tooltip and the inside labels should use the same colors as the chart slices and legend.

### Screenshots
<img width="276" alt="Screen Shot 2022-02-14 at 11 42 22" src="https://user-images.githubusercontent.com/16974967/153910480-fca092bc-fea9-496d-b013-bd08352a3085.png">

### Reproduction Link
See the code here:
﻿https://codepen.io/stanivanov/pen/WNXZvZE

**Comment by GonzaloBlanco7** [comment]
Had the same problem when forcing chart colours as you did.
To fix this issue I had assigned the same colours array used in options.fill.colors to options.colors

```javascript
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "donut",
    labels: ["Apple", "Orange", "Mango"]
  },
  fill: {
    colors: ["#f44336", "#ff9800", "#4caf50"]
  },
  series: [1, 5, 10],
  legend: {
    // Show the legend
    show: true,
    markers: {
      // Set the legend colors as the ones passed in
      fillColors: ["#f44336", "#ff9800", "#4caf50"]
    }
  },
  tooltip: {
    enabled: true,
    fillSeriesColor: true
  },
  colors: ["#f44336", "#ff9800", "#4caf50"]
};
```

**Comment by V1CTOR-cloud** [comment]
> Had the same problem when forcing chart colours as you did. To fix this issue I had assigned the same colours array used in options.fill.colors to options.colors
> 
> ```js
> var options = {
>   chart: {
>     height: 380,
>     width: "100%",
>     type: "donut",
>     labels: ["Apple", "Orange", "Mango"]
>   },
>   fill: {
>     colors: ["#f44336", "#ff9800", "#4caf50"]
>   },
>   series: [1, 5, 10],
>   legend: {
>     // Show the legend
>     show: true,
>     markers: {
>       // Set the legend colors as the ones passed in
>       fillColors: ["#f44336", "#ff9800", "#4caf50"]
>     }
>   },
>   tooltip: {
>     enabled: true,
>     fillSeriesColor: true
>   },
>   colors: ["#f44336", "#ff9800", "#4caf50"] //Add this line
> };
> ```

Thanks it helps me a lot

**Comment by stanimirivanovde** [comment]
> ```js
> colors: ["#f44336", "#ff9800", "#4caf50"]
> ```

This does not work for me. Are you using the latest version of apexcharts? I am and I still see the problem. Can you try fixing it in the link I posted in the description of the issue?

**Comment by stanimirivanovde** [comment]
Actually, I just fixed the issue by also including the `color` array in the `tooltip` options. Note that this is not documented. The only documented option is the `fillSeriesColor` which doesn't seem to work.

In other words this doesn't work to change the tooltip color of the Pie graph:

```javascript
tooltip: {
    enabled: true,
    fillSeriesColor: true,
}, 
```
But this does and fixes the issue:
```javascript
tooltip: {
    enabled: true,
    colors: ["#f44336", "#ff9800", "#4caf50"]
},
```
