### ISSUE TITLE
"Ticks" in Pie/Donut

### ISSUE THREAD

**Issue by handhikadj** [apexcharts/apexcharts.js#2996]
## Summary

amCharts has "ticks" on each of the datalabels

<img width="593" alt="Screen Shot 2022-02-21 at 5 53 01 PM" src="https://user-images.githubusercontent.com/22522638/154941256-3e80453a-6ffc-4076-babb-9e09a6218773.png">

(or go to: https://codepen.io/dhika345/pen/ExbEBrd)

it would be cool if ApexCharts has this

## API Changes
Example code: https://codepen.io/dhika345/pen/ExbEBrd

## Intended Use Case

it would be cool if ApexCharts has this

**Comment by junedchhipa** [comment]
Hey @handhikadj 
Thank you for the suggestion, but we have no plans to add this feature into ApexCharts.
