### ISSUE TITLE
Hide y axes

### ISSUE THREAD

**Issue by timbarclay** [apexcharts/apexcharts.js#30]
Is it possible to entirely hide y axes and have the chart plot area fill the whole space?

I've tried using a yaxis config like this:

```
{
  axisTicks: {
    show: false
  },
  axisBorder: {
    show: false
  },
  labels: {
    show: false
  },
  title: {
    text: ""
  }
}
```

That hides the y axes but leaves a blank space. I've tried setting various width properties to 0 too, but it comes out the same. Is there a way to hide the y axis (or axes) completely and have the chart plot area fill the whole horizontal space?

**Comment by junedchhipa** [comment]
Try this

```javascript
{
  floating: true,
  axisTicks: {
    show: false
  },
  axisBorder: {
    show: false
  },
  labels: {
    show: false
  },
  title: {
    text: ""
  }
}
```

The floating option will take the yaxis area out of chart's plotting area. It is similar to `position: absolute` in CSS :)

**Comment by timbarclay** [comment]
Perfect, thanks.
I missed this because I didn't realise there were more config options beyond the ones in the sample object at the top of the page at https://apexcharts.com/docs/options/yaxis/. Thanks very much for pointing this out.

**Comment by junedchhipa** [comment]
It should be in the docs. Don't know I how missed it.
Thanks for pointing out that page!

**Comment by iAmShakil** [comment]
Anyone who's trying to show the floating yAxis without dragging it into the plotting area, use the CSS property overflow: visible on the SVG element.

**Comment by fareed13** [comment]
Hope you are doing well, 
i used all these floating: true,
  axisTicks: {
    show: false
  },
  axisBorder: {
    show: false
  },
  labels: {
    show: false
  },
but x and y axis of bar chart with negative value is not hide , i just want to hide all axis only show bar line
<img width="937" alt="issue" src="https://user-images.githubusercontent.com/75368987/195215265-a09ee9d9-30b9-488d-846d-d68c1f5bd474.PNG">
