### ISSUE TITLE
Chart Option -> DropShadow Color options

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/apexcharts.js#300]
Hi,
Your charts are excellent and I am glad to use them in my project. Great Flexibility.
However with that `dropshadow` option provided in `chart options`, it will be great and will look beautiful if you add support for dropshadow's `color` property.

like [here](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow)

**Comment by junedchhipa** [comment]
Thanks for the suggestion.
Implemented it. Will be available in 3.2.2

**Comment by oneezy** [comment]
hi, is this feature available yet? I'm not seeing it in [Docs](https://apexcharts.com/docs/options/chart/dropshadow/)

**Comment by oneezy** [comment]
ahhh just tested it and it works :)

```
    dropShadow: {
      enabled: true,
      top: 0,
      left: 0,
      blur: 3,
      opacity: 0.5,
      color: 'yellow'
    }
```
