### ISSUE TITLE
forecastDataPoints at start of series

### ISSUE THREAD

**Issue by AJCWhite** [apexcharts/apexcharts.js#3017]
## Summary

I would like to use the dashed line fill for the initial data points followed by a solid line. I can achieve the opposite with forecastDataPoints but if I enter a negative number it does not allow me to use the count from the start of the series

## API Changes

forecastDataPoints

## Intended Use Case

It would be used for older data points in a timeseries

forecastDataPoints: {
      **count: -4,**
      fillOpacity: 0.5,
      strokeWidth: undefined,
      dashArray: 4,
    },

**Comment by jschuur** [comment]
Came here looking for this ability too.
