### ISSUE TITLE
Uncaught TypeError: a.w.globals.tooltip is null

### ISSUE THREAD

**Issue by stanimirivanovde** [apexcharts/apexcharts.js#3018]
### Description
I use multiple Line graphs in a Vue + Quasar app. Graphs are spread on different pages. Some of the graphs use the same group to synchronize their tooltips, others have multiple data series. Every graph uses it's own chart ID.

Bug: after some navigation between the interfaces the tooltip on some of the graphs disappear and I see `Uncaught TypeError: a.w.globals.tooltip is null` in the console log. I assume this is caused by some dirty global state. The error is logged many times as it depends on the mouse movement. The graphs show the correct data but the tooltip is not displayed any longer. If I refresh the page it starts working again with no problem but sooner or later after navigating back and forth I see it again. Some of the graphs have on-click events to emit an index of the data series on click.

### Steps to Reproduce
Create a page that defines 3 line graphs in a group. Make sure they have a shared tooltip.
Create a new page with a single line graph with 3 data series. Make sure they also display a tooltip. Associate an on-click event to emit a signal when a point in the graph is clicked.
Create third page with two line graphs that emit a signal on click. All graphs should display a tooltip but the graphs should not be in the same group.

After loading the different pages and clicking on the graph suddenly the tooltip would disappear and you'll see the error in the console.log

### Expected Behavior
The tooltip will correctly show on all graphs at all times no matter how I navigate between the pages or click on the graphs.

**Comment by brianlagunas** [comment]
Close as the required repo app was not provided

**Comment by prachi-ec** [comment]
Facing similar issue. 
 
got error: `TypeError: Cannot read properties of null (reading 'ttItems')` on navigating between pages. 

On inspection got directed to the file apexcharts.common.js?53db:formatted and found source of issue in 
` {
        key: "seriesHover",
        value: function(t, e) {
            var i = this;
            this.lastHoverTime = Date.now();
            var a = []
              , s = this.w;
            s.config.chart.group && (a = this.ctx.getGroupedCharts()),
            s.globals.axisCharts && (s.globals.minX === -1 / 0 && s.globals.maxX === 1 / 0 || 0 === s.globals.dataPoints) || (a.length ? a.forEach((function(a) {
                var s = i.getElTooltip(a)
                  , r = {
                    paths: t.paths,
                    tooltipEl: s,
                    tooltipY: t.tooltipY,
                    tooltipX: t.tooltipX,
                    elGrid: t.elGrid,
                    hoverArea: t.hoverArea,
                    ttItems: a.w.globals.tooltip.ttItems     //source of error
                };
             `

**Comment by robbykrlos** [comment]
Similar issue here. Any ideas?

**Comment by jschuur** [comment]
Similar issue here. apexcharts 3.35.5, react-apexcharts 1.4.0.

Same symptom as @stanimirivanovde: If navigate between data  sets (which are loaded in via react-query and then passed in via proper to a chart component), sometimes (after 3-4 changes of the data set), the hover state stops appearing and my console is full of stuff like this:

```
26c44d60f.5d4cf761d3a89dc1.js:1 Uncaught TypeError: Cannot read properties of null (reading 'ttItems')
    at 6c44d60f.5d4cf761d3a89dc1.js:1:294934
    at Array.forEach (<anonymous>)
    at t.value (6c44d60f.5d4cf761d3a89dc1.js:1:294755)
    at 6c44d60f.5d4cf761d3a89dc1.js:1:294468
```

The library code it seems to be hitting when this happens:

```
s.globals.axisCharts && (s.globals.minX === -1 / 0 && s.globals.maxX === 1 / 0 || 0 === s.globals.dataPoints) || (a.length ? a.forEach(function(a) {
  var s = i.getElTooltip(a)
      , r = {
        paths: t.paths,
        tooltipEl: s,
        tooltipY: t.tooltipY,
        tooltipX: t.tooltipX,
        elGrid: t.elGrid,
        hoverArea: t.hoverArea,
        ttItems: a.w.globals.tooltip.ttItems
      };
```

If it is indeed a dirty state issue, I wonder if there is away to hook into an event (update?) and reset something explicitly (inspired by [this comment](https://github.com/apexcharts/react-apexcharts/issues/187#issuecomment-912570934))?

**Comment by stanimirivanovde** [comment]
I think this has to do with the data provided to apexcharts. If it is undefined or null it can cause the issue. Special care should be taken to pass an empty array at a minimum. I think this would fix the issue.

**Comment by jschuur** [comment]
> I think this has to do with the data provided to apexcharts. If it is undefined or null it can cause the issue. Special care should be taken to pass an empty array at a minimum. I think this would fix the issue.

I've tried either making sure it's at least an empty array or return null for my whole chart component when the series data is null, but neither caused my errors to go away.

Disabling tooltips seems to get rid of the `ttItems` (not suprisingly, given the 'tt' part in the name), but that makes my charts a lot less useful and still leaves another (less frequent) error involving `getPreviousPaths`:

```
6c44d60f.5d4cf761d3a89dc1.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getPreviousPaths')
    at 6c44d60f.5d4cf761d3a89dc1.js:1:383907
    at Array.forEach (<anonymous>)
    at 6c44d60f.5d4cf761d3a89dc1.js:1:383784
    at new Promise (<anonymous>)
    at t.value (6c44d60f.5d4cf761d3a89dc1.js:1:383639)
    at t.value (6c44d60f.5d4cf761d3a89dc1.js:5:42468)
    at t.value (229.b854d690932a3d00.js:1:3417)
    at oa (framework-7751730b10fa0f74.js:9:99013)
    at e (framework-7751730b10fa0f74.js:9:111710)
    at framework-7751730b10fa0f74.js:9:111721
``` 

This ocurrs near (but not exactlyt on) a line in the minified JS that accesses series data:

```js
                    s && r.series.getPreviousPaths()),
```

I thought maybe it's getting tripped up trying to animate  from old, nonexistent data, but even disabling animation didn't help.

At this point, I'm stumped and feel pretty frustrated, because I'm not sure how to debug this any further or even know if this is a bug in my code or Apexcharts.

**Comment by stanimirivanovde** [comment]
@jschuur the apexcharts guys closed this issue since I didn't provide a playground example with a link. Do  you mind creating one and opening a new issue? Otherwise they won't act on it.

**Comment by Lobbyism** [comment]
Hello. There appears to be a workaround for this problem in VueApexCharts. In VueJS, the [`key`](https://vuejs.org/api/built-in-special-attributes#key) attribute is described as follows
> The `key` special attribute is primarily used as a hint for Vue's virtual DOM algorithm to identify vnodes when diffing the new list of nodes against the old list.

This [issue](https://github.com/apexcharts/react-apexcharts/issues/235#issuecomment-1031255717) concerns a different problem. The workaround suggested is to set the `key` to `Math.random()`. This solved these two errors
`Uncaught TypeError: Cannot read properties of null (reading 'ttItems')`
`TypeError: Cannot read properties of null (reading 'getPreviousPaths')`
