### ISSUE TITLE
Force yaxis to start at 0

### ISSUE THREAD

**Issue by elbojoloco** [apexcharts/apexcharts.js#302]
**Is your feature request related to a problem? Please describe.**
I'm making a chart where the data becomes hard to understand when it doesn't start at 0.

**Describe the solution you'd like**
Add an option (like `yaxis.startAtZero: true|false`) to force the chart to start drawing at 0.

**Describe alternatives you've considered**
none

**Additional context**
Seems like a pretty simple fix, in the part where it decides to not start at 0, do it only when the option is set to false.

**Comment by junedchhipa** [comment]
Have you tried `yaxis.min: 0` ?

**Comment by elbojoloco** [comment]
That does exactly what I needed, it does give some weird numbers in the yaxis though. How do I use this while still maintaining nice and round numbers? 
![image](https://user-images.githubusercontent.com/7912315/52265210-d54a5480-2933-11e9-8497-70de484298b7.png)

**Comment by junedchhipa** [comment]
```javascript
  yaxis: {
    labels: {
      formatter: function(val, index) {
        return Math.round(val);
      }
    }
  }
```

**Comment by elbojoloco** [comment]
I mean round like `150` instead of `166` and `420` instead of `416` for example, like the default behavior

**Comment by junedchhipa** [comment]
I just realized this is not possible currently. Thanks for pointing it out.
Fixed it. Will be available in the next patch release.

**Comment by junedchhipa** [comment]
The new property will be
```javascript
yaxis: {
  forceNiceScale: true
}
```
