### ISSUE TITLE
Clickable annotations

### ISSUE THREAD

**Issue by placid2000** [apexcharts/apexcharts.js#3038]
## Summary

Making annotations clickable and knowing which annotation by getting for example its xaxis index and/or timestamp would be very handy for some use cases.

## API Changes

For example introduce an event called annotationClick() which allows to access different properties of that annotation **as well as its y or x axis index or timestamp to be able to identify them**.

## Intended Use Case

There are anomalies marked with annotations. A click would allow to validate them or add some additional text information.

**Comment by ampodobas** [comment]
This would be **extremely** useful

**Comment by trylaarsdam** [comment]
This would be great- there seems to already be handlers for mouseEnter and mouseLeave, so it'd be super nice if there was a mouseClick one as well to allow for a popup to show

**Comment by trylaarsdam** [comment]
Actually just realized you can grab the event of a click on any part of the chart using this handler to accomplish this functionality (example in vue2):
```js
var options = {
  chart: {
    events: {
      click: function (e, ctx, options) {
        // check e.target here
        console.log(e.target.innerHTML) // logs the content of the annotation, could be cross referenced with a separate list of annotations to get more info, etc.
      }
    }
  },
}
```

**Comment by robyedlin** [comment]
@trylaarsdam The problem is that you cannot easily get the annotation context through the chart click event.

@junedchhipa would it be a problem to add the following to `PointsAnnotation.js`?
```
    if (anno.click) {
      point.node.addEventListener(
        'click',
        anno.click.bind(this, anno)
      )
    }
```
I think this would be extremely useful, and would be happy to open a PR for it.

**Comment by trylaarsdam** [comment]
Yeah agreed, that would be nice.

I believe I just included a short ID in the text of the annotation to determine which one was clicked, but that is a bit of a bodge

**Comment by robyedlin** [comment]
It’s also possible to add a meaningful class to the marker or label, but not the image.

**Comment by trylaarsdam** [comment]
I'd like for this to remain open since #3318 doesn't fully address the issue because it only adds a click handler for x-axis labels.

**Comment by junedchhipa** [comment]
Since v3.35.4, click events on annotations are added.
Here are the docs - https://apexcharts.com/docs/options/annotations/
