### ISSUE TITLE
ApexCharts.exec() not working in graph "Bar"

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#304]
## Codepen

https://codepen.io/anon/pen/RvLrzv?editors=0010

## Explanation

**What is the behavior you expect?**
Change the chart series values.

**What is happening instead?**
An error has occurred in the console, the bars not populated, the series data not updated.

**What error message are you getting?**
```
apexcharts:6 Uncaught TypeError: Cannot read property 'chart' of undefined
    at Function.value (VM2546 apexcharts:6)
    at Function.value (VM2546 apexcharts:6)
    at VM2547 pen.js:52
```

**Comment by mestaritonttu** [comment]
You need to have an id defined for the chart in the options:

```
  chart: {
    id: "chart",
    height: 380,
    width: "100%",
    type: "bar"
  },
```

**Comment by junedchhipa** [comment]
Exactly.
 exec() method requires a chart ID to find the chart from all available chart instances.
