### ISSUE TITLE
Not Showing All Data Labels

### ISSUE THREAD

**Issue by ZeemZach** [apexcharts/apexcharts.js#3043]
### Description
All data Labels should be shown in the chart there are many missing point where data is not available. For more understanding, please refer to the given screenshot.

### Screenshots
![image](https://user-images.githubusercontent.com/49615125/158009250-0e57f533-60f1-4d61-b37c-2ad957c005f3.png)

**Comment by brianlagunas** [comment]
No reproduction app provided
