### ISSUE TITLE
Height of bars isn't aligned with height of ticks when using logarithmic scale

### ISSUE THREAD

**Issue by Ben0909** [apexcharts/apexcharts.js#3045]
### Description
When using logarithmic scale, it seems that the height representing the "ticks" is not correspond to the height of the bars,
seems as the calculation of representing the "ticks" values is slightly wrong.

### Steps to Reproduce

1. Create a chart with series values of integers : [2,4,8,16]
2. Set the y-axis to logarithmic.

### Expected Behavior
For the series : [2,4,8,16] with logarithmic scale set to base 2:
![image](https://user-images.githubusercontent.com/43224373/158049376-24bbd55b-865a-49e8-a7a7-6fb0f6d7bb68.png)

### Actual Behavior
For the series : [2,4,8,16] with logarithmic scale set to base 2:
![image](https://user-images.githubusercontent.com/43224373/158049937-b5f8a218-b176-4607-84db-871dad55817d.png)

**Comment by brianlagunas** [comment]
Reproduction app not provided
