### ISSUE TITLE
Panning is not working

### ISSUE THREAD

**Issue by SebstianSchwemer** [apexcharts/apexcharts.js#3047]
Hey,
I really like your chart tool but i'm using it mostly on mobile devices.
Is it still not possible to use panning on mobile devices? I think for many people it's the reason to choose apexcharts.
I would also be happy if i could just turn the tooltips off and use the panning tool instead.

https://github.com/apexcharts/apexcharts.js/issues/245
https://github.com/apexcharts/apexcharts.js/issues/86

Sincerely,
Sebastian

**Comment by MelanieRiche** [comment]
Hello! I second this request. 
It would be really nice to be able to use the panning feature on mobile. Thank you for your work!

**Comment by AleXSR700** [comment]
+1

**Comment by StefanKellerAC** [comment]
yes, panning on mobile is really missing.

**Comment by pastry777** [comment]
We have been waiting for several years... Please add this feature, if not with a touch, even with buttons... Thank you!!!

**Comment by brianlagunas** [comment]
We accept PRs

**Comment by AleXSR700** [comment]
> We accept PRs

I think it is a matter of no longer disabling touchdevices support in toolbar.js

```
    const zoomSelectionCtrls = (z) => {
      if (this.t[z] && w.config.chart[z].enabled) {
        toolbarControls.push({
          el: z === 'zoom' ? this.elZoom : this.elSelection,
          icon:
            typeof this.t[z] === 'string'
              ? this.t[z]
              : z === 'zoom'
              ? icoZoom
              : icoSelect,
          title: this.localeValues[
            z === 'zoom' ? 'selectionZoom' : 'selection'
          ],
          class: w.globals.isTouchDevice
            ? 'apexcharts-element-hidden'
            : `apexcharts-${z}-icon`
        })
      }
    }
    zoomSelectionCtrls('zoom')
    zoomSelectionCtrls('selection')

    if (this.t.pan && w.config.chart.zoom.enabled) {
      toolbarControls.push({
        el: this.elPan,
        icon: typeof this.t.pan === 'string' ? this.t.pan : icoPan,
        title: this.localeValues.pan,
        class: w.globals.isTouchDevice
          ? 'apexcharts-element-hidden'
          : 'apexcharts-pan-icon'
      })
    }
```
Happy to support if I can but have not built apexcharts for mobile yet. I am using the Home Assistant apexcharts card which uses your source code. :)
Are there build instructions for gitpod?
