### ISSUE TITLE
Connect values between null points in Line Chart

### ISSUE THREAD

**Issue by doricohen4** [apexcharts/apexcharts.js#3048]
### Steps to Reproduce

1. created mixed chart with bars and line
2.  provide data var options = {
  chart: {
    height: 350,
    type: "line",
    stacked: true
  },
  dataLabels: {
    enabled: false
  },
  colors: ["#FF1654", "#247BA0"],
  series: [
    {
       type: 'column',
      name: "Series A",
      data: [1.4, 2, 2.5, 1.5, 2.5, 2.8, 3.8, 4.6]
    },
    {
      name: "Series B",
      data: [20 ,58]
    }
  ],
  stroke: {
    width: [4, 4]
  },
    markers: {
    size: [4, 4] //per each chart type display the size of points in line chart
  },
  plotOptions: {
    bar: { 
      columnWidth: "20%"
    }
  },
  xaxis: {
    type:'numeric',
    categories: [10, 20, 30, 40, 50, 60, 70, 80]
  },
  yaxis: [
    {
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
        color: "#FF1654"
      },
      labels: {
        style: {
          colors: "#FF1654"
        }
      },
      title: {
        text: "Series A",
        style: {
          color: "#FF1654"
        }
      }
    },
    {
      opposite: true,
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
        color: "#247BA0"
      },
      labels: {
        style: {
          colors: "#247BA0"
        }
      },
      title: {
        text: "Series B",
        style: {
          color: "#247BA0"
        }
      }
    }
  ],
  tooltip: {
    shared: false,
    intersect: true,
    x: {
      show: false
    }
  },
  legend: {
    horizontalAlign: "left",
    offsetX: 40
  }
};
3. 

### Expected Behavior
 for line data i would like to have the option  that the line will spread to enitre chart   from start to end 

### Actual Behavior

because the bar chart has

### Reproduction Link

https://codepen.io/doriman1234/pen/xxpbpyd

**Comment by doricohen4** [comment]
any estimation when will this feature be ready?
tnx

**Comment by brianlagunas** [comment]
No, we have too many bugs right now. Chances of getting any new features are slim.

**Comment by tomcrofty** [comment]
It seems the best strategy here would be to apply some backend functionality to interpolate data between points here, not ideal but it's the only solution atm.

**Comment by MVoikolesco** [comment]
I really like how ApexCharts works so I would like to know if it would be possible to add such a feature, which from what I've seen has been requested for a long time now.

**Comment by julienlaglasseadhzm** [comment]
+1

**Comment by hari401** [comment]
Is it possible to add this feature ?

**Comment by antoinemcx** [comment]
+1
