### ISSUE TITLE
xaxis last label is trimmed

### ISSUE THREAD

**Issue by Epithumia** [apexcharts/apexcharts.js#305]
## Codepen

[Showcase codepen](https://codesandbox.io/s/k90z9o7x3)

## Explanation

The showcase codepen uses the current versions of Vue-ApexCharts and ApexCharts.js, the expected behavior uses v1.1.0

- What is the behavior you expect?

[Correct result codepen](https://codesandbox.io/s/8yrn3pq0w9)

The x axis sets the first and last point to be at the edge of the grid in the current version of Vue-ApexCharts, whereas the version showcased in the demos (that's where I picked the initial code) correctly sets the labels and the datapoints to have enough offset on both sides so that no clipping occurs.

- What is happening instead?

Edge points and labels are clipped.

- What error message are you getting?

None.

Edit: Let me know if I should submit this to the Vue-ApexCharts repo instead.

Edit2: after fiddling with codepen, I can say this is an apexcharts issue, not the Vue component. [This codepen](https://codesandbox.io/s/ww5k8kjz88) uses apexcharts v3.1.0 and displays fine. It breaks starting with 3.2.0.

Edit3: I found that a property was added in 3.2.0 (xaxis.tickPlacement), which defaults to 'on', whereas the old behavior for a line chart was to have it as 'between'. The documentation isn't reflecting this, nor does it mention the existence of xaxis.tickPlacement. May I suggest that:
1) Default for line should be set to 'between'
2) Documentation should be updated ?

**Comment by junedchhipa** [comment]
Thanks for reporting the issue.
I think, providing some padding on the right side when the last label is long will prevent it being cropped. 
I will surely update the docs too.

**Comment by junedchhipa** [comment]
I reverted `xaxis.tickPlacement: between` as this seems to be the easiest fix for now.

**Comment by jchamb** [comment]
@junedchhipa Looks like this is still an issue with datetimes that include month. Saw in the docs that tickPlacement does not affect the datetime. Any tricks to get around it cutting that last label on the right?

https://codesandbox.io/s/o2j3znx0q

**Comment by junedchhipa** [comment]
Re-opening this if datetime labels still have an issue with the last label.

**Comment by HorizonShadow** [comment]
If you use a custom formatter function, the labels will still break out of the rendering area.

https://codesandbox.io/s/vue-basic-example-2dw9c

**Comment by ciornav** [comment]
Hello, the issue persists, but in my case on the first value. 'between' option works well for categorical variables but as the doc says not for numerical.
Would be very grateful to fix this.

**Comment by travisbotello** [comment]
Still seeing the same issue with 3.8.5

![Screenshot 2019-09-02 17 10 41](https://user-images.githubusercontent.com/1157380/64123463-bd8d5e80-cda4-11e9-8cae-adfdb89c0c53.png)

**Comment by AlexandraPechueva** [comment]
![break labels chart](https://user-images.githubusercontent.com/33789169/68457060-68d8ea80-0210-11ea-8e97-4087f1ac6fc5.png)

when I use "min: new Date('01-01-2019').getTime()" in xaxis to display chart from the start of the year, first column and label  cropped. 

apexcharts 3.10.1
ng-apexcharts 1.1.1

**Comment by dtahir57** [comment]
Everyone please do the following. It should work 

`xaxis: {
     tickPlacement: 'between',
}`

This should solve the problem. 

I am using 
"apexcharts": "^3.10.1",
"vue-apexcharts": "^1.5.1",

**Comment by ricardobr001** [comment]
Same problem here, the last date on the bottom corner in the right is cropped =(

My options for `xaxis` are
```json
xaxis: {
      title: {
        text: xaxisTitle,
        style: {
          fontSize: 20,
          color: '#ffffff'
        }
      },
      labels: {
        formatter: value => {
          return moment(new Date(value)).format('MM-YYYY')
        },
        style: {
          fontSize: 20
        }
      },
      tickAmount: 5,
      tickPlacement: 'between'
  }
```

![image](https://user-images.githubusercontent.com/18339710/71547756-059f4500-2983-11ea-96bb-902ccbbc5952.png)

**Comment by pengiundev** [comment]
Still having that issue with `datetime` on version` 1.3.16`

**Comment by alexandrehsd** [comment]
Guys, after studying this issue, it happened to me that when I converted the datetimes to milliseconds, somehow the program interpreted those datetimes in GMT timezone, and then converted it to my timezone (UTC -3). Consequently, I always got the date of the last day which led me to think that the last date was being cropped.

My solution was to simply add up 3 hours (or 3*3.6e6 milliseconds) to my timestamps.

**Comment by gabrielnvg** [comment]
This did the trick for me:

`xaxis: { tickPlacement: 'on', }`

**Comment by sebastiaanluca** [comment]
![Screen Shot 2020-04-20 at 13 43 26](https://user-images.githubusercontent.com/711940/79747999-ed29b080-830c-11ea-903a-b122d06cdfda.png)

Still an issue and no fix at the moment. Using a `datetime` type and `moment.utc(item.created_at).valueOf()`.

**Comment by kakarukeys** [comment]
This issue should not be closed. I am seeing this bug on fresh installation of latest apex chart `3.20.0` and vue-apexcharts `1.6.0`, with `datetime` type `x` data on a `line` chart. I used the workaround

```css
.apexcharts-xaxis-label:nth-last-child(2) {
  transform: translateX(-20px)
}
```

**Comment by sebastiaanluca** [comment]
Had to add an entire day to each of my datetime x-axis entries just to get the last month to show up. January still doesn't show.

```javascript
moment.utc(item.date, 'Y-MM', true).add(1, 'day').valueOf(),
```

Using a `numeric` x-axis shows January and December double. Tried to tweak it, but either it shows them double or not at all.

**Comment by quninnd** [comment]
![image](https://user-images.githubusercontent.com/69043484/127845564-a3b1259f-951d-4f2b-a360-285121d3c0e3.png)
I have the same problem

**Comment by junedchhipa** [comment]
Those who are still facing the issue, please post a Codepen/Codesandbox demo to reproduce.
The original Codesandbox has this issue fixes, so please post your own.

**Comment by alon-loris** [comment]
This issue persists. The last date on the x-axis is cut:
![image](https://user-images.githubusercontent.com/71207393/150687943-938d5022-91da-4714-a3d0-9743b01eee84.png)

Tried @kakarukeys workaround above, and it works sometimes, but unfortunately not always, because sometimes the trimmed label is indeed the 2nd-to-last `apexcharts-xaxis-label` element as mentioned in the workaround (for some reason there's another empty label after it), but sometimes the trimmed label is really the last `apexcharts-xaxis-label` element, and in that case the css would apply to the wrong element.

Any plans to fix this?
Or any workaround that covers all cases?

https://codepen.io/alon-loris/pen/QWqRYRa

**Comment by cbutler90** [comment]
Still an issue, see @alon-loris post above. This is happening with every type of label (the last one on the X axis), not just Date/Time format

**Comment by ya3ya6** [comment]
I Fixed the issue by adding some padding to the right of chart (now it has enough space to be shown):
```
grid: {
  padding: {
    left: 20,
    right: 40
  },
},
```

**Comment by carbonrider** [comment]
Check this fiddle as well 

https://jsfiddle.net/carbonrider/2rc863xw/22/

It doesn't display labels on xaxis for last 2 items. Also hovering over the graph and xaxis labels are far away from each other.

**Comment by ryanmaffey** [comment]
I'm also having this issue. Here's my example: https://codepen.io/ryanmaffey/pen/YzvBvJv?editors=0010

**Comment by montanari2019** [comment]
apexcharts people just ignored the problem kkkkkk.

"If I don't see a problem, the problem doesn't exist"
- Team apexcharts

Ps: I'm being ironic

**Comment by parautenbach** [comment]
If you don't have anything constructive to contribute, find another outlet for your frustration. You have no right to demand anything from an open source project.

**Comment by Gunjansokal07** [comment]
> Check this fiddle as well
> 
> https://jsfiddle.net/carbonrider/2rc863xw/22/
> 
> It doesn't display labels on xaxis for last 2 items. Also hovering over the graph and xaxis labels are far away from each other.

Hi @carbonrider ,

Have you found a solution to make the last label appear on the x-axis?

**Comment by maxtrunk** [comment]
Change the x rotation to 90 will resolve this issue

**Comment by iskendev** [comment]
@junedchhipa hey Juned! Would be great to get fix of this issue?! Please give it some attention

**Comment by thuyetnguyen95** [comment]
> I Fixed the issue by adding some padding to the right of chart (now it has enough space to be shown):
> 
> ```
> grid: {
>   padding: {
>     left: 20,
>     right: 40 // Also you may want to increase this (based on the length of your labels)
>   },
> },
> ```

Perfect, it's work for me!

**Comment by mustakim** [comment]
> I Fixed the issue by adding some padding to the right of chart (now it has enough space to be shown):
> 
> ```
> grid: {
>   padding: {
>     left: 20,
>     right: 40 // Also you may want to increase this (based on the length of your labels)
>   },
> },
> ```

Thanks a lot
