### ISSUE TITLE
Something other than text as data label.. even unicode would be nice

### ISSUE THREAD

**Issue by rchancey** [apexcharts/apexcharts.js#3052]
most all charts will allow at least a unicode character for datalabels.. little diamonds or stars..etc.. something not just text. The code generates a <text> tag and it swallows the unicode. Is there a way around that?
I simply want to use a diamond in a heat map as the data label.. 
I consider this a bug since its pretty common behavior....why hard code the datalabel to be text???

**Comment by brianlagunas** [comment]
Not a bug.

**Comment by rchancey** [comment]
So you just close it without commenting on how to do it.. that's not nice..
