### ISSUE TITLE
Broken Typescript typings

### ISSUE THREAD

**Issue by pierretasci** [apexcharts/apexcharts.js#306]
The default typings that were recently added make supporting apexcharts with Typescript near impossible. Many of the options are not nullable by default (end in a ?). For example, the radar option in plotOptions was added but is not nullable. That means in order for Typescript to not complain, I have to define radar options even if that isn't my intended chart type.

I propose that all options be made optional.

**Comment by junedchhipa** [comment]
Thank you for the suggestions. Honestly, I have zero experience with Typescript and many of the typings were provided by different users.
I will try to make the "required" typings optional if it is not required. I think, 95% of the typings are not required, so the majority of it will need the *?* to be removed.

The only ones which are mandatory are 
*series*
*type*

A Pull Request is welcome.
