### ISSUE TITLE
Angular6 TypeError 

### ISSUE THREAD

**Issue by lcatania** [apexcharts/apexcharts.js#307]
Hi, 

i wanted to try out the library in my angular6 project and dont really know how get the library to work with the typings. 

I get this Error Messeng:

`ERROR TypeError: apexcharts__WEBPACK_IMPORTED_MODULE_5__ is not a constructor`

Can someone give me an hint or solution ?

Best regards lcatania

**Comment by lcatania** [comment]
Found the solution .

 I changed the import from `import * as ApexCharts from 'apexcharts'` to `import  ApexCharts from 'apexcharts'`

**Comment by junedchhipa** [comment]
Glad you found the solution yourself.
Closing it.
