### ISSUE TITLE
Annotation, Markers display on outside grap area

### ISSUE THREAD

**Issue by dungdao191299** [apexcharts/apexcharts.js#3073]
I am using Apexchart.js in for draw chart with Annotations feature. But when anotation get value at outside range of chart, it can display over other component of chart eg: yaxis, xaxis,...
https://codepen.io/apexcharts/pen/GXOJXQ?editors=1010
![image](https://user-images.githubusercontent.com/54898195/160531126-8f84c213-cdeb-4819-8bbe-c31f14821c0b.png)
Markers feature too when i try this example
https://codepen.io/apexcharts/pen/rqWeBX?editors=1010
![image](https://user-images.githubusercontent.com/54898195/160531323-651242f3-262b-451f-b6f2-ea0bd253eb6f.png)
Does anyone know how to fix it?

**Comment by vipansh-alyve** [comment]
<img width="529" alt="Screenshot 2022-06-05 at 9 36 12 AM" src="https://user-images.githubusercontent.com/95841509/172035237-f789a84e-f09d-44b8-8a00-d6473f5acd43.png">
I am also having this issue / any one have any solution ?

**Comment by RCelty** [comment]
This issue happen to me to 
![image](https://user-images.githubusercontent.com/71772102/185596468-3d468e35-cf6c-4e7c-8776-777594c754bc.png)

**Comment by VictorAdamovich** [comment]
also faced this problem
![Screenshot 2023-05-10 at 15 15 51](https://github.com/apexcharts/apexcharts.js/assets/77265974/a3cf2526-b7a0-475a-b6c8-fb2e298bf92d)

**Comment by arealclimber** [comment]
It happens to me still. The marker is supposed to stick to the last data point of the line graph.
![image](https://github.com/apexcharts/apexcharts.js/assets/20677913/7e2620cb-c9d4-4afc-873f-f6075766f5db)
