### ISSUE TITLE
Xaxis label not display

### ISSUE THREAD

**Issue by dungdao191299** [apexcharts/apexcharts.js#3074]
I am using apexchart.js in my project. Everything working nomaly, but today all xaxis label not display. I try some example in codepen but the xaxis label not display too.
https://codepen.io/apexcharts/pen/GXOJXQ?editors=1010
![image](https://user-images.githubusercontent.com/54898195/160877971-c6a2c022-949f-4214-a3d2-9b5c8cb4e756.png)
i try add "show : true" to xaxis option but it is not working.
Anyone see this bug like me?

**Comment by dungdao191299** [comment]
> I can replicate this issue. Looking at the DOM I can see the label div being rendered but has inner value.
> 
> If I pass a formatter then the date is rendered but of course you lose the auto scaling functionality

Yes, as far as i see, this problem only appear from today. I think have some bug in lastest version

**Comment by tobycatlin** [comment]
Rolling back to 3.33.0 fixes this problem

**Comment by dungdao191299** [comment]
> Rolling back to 3.33.0 fixes this problem

yes, it's a situational solution. but how can i rolling back to 3.33 version in vanilaJS?

**Comment by tobycatlin** [comment]
You can download a zip from the releases page
https://github.com/apexcharts/apexcharts.js/releases

Inside the zip there is a dist folder with the minified file. You could probably get it from some CDN too.

**Comment by junedchhipa** [comment]
@DavidMarquezF Can you take a look what went wrong?
