### ISSUE TITLE
Stacked Bar Charts rendering thinly with date xAxis

### ISSUE THREAD

**Issue by jchamb** [apexcharts/apexcharts.js#308]
## Codepen
https://codepen.io/anon/pen/xMXeNX

## Explanation
Even with columnWidth 100% it seems like the width calculation on stacked bar charts is extremely thin when your xAxis is of type datetime. May be a new bug as I don't remember them being this way before, and I only noticed after I updated to most recent version.

I dug through the docs but didnt spot any options that allowed to adjust the spacing more.

When columnWidth 100% is set i'd expect all bars to be touching. no matter what the xAxis data type is. Here is a screen shot of the issue on a larger generated chart. http://take.ms/b1ucd With how thin the bars get generated it's basically impossible to see the data without zooming in.

**Comment by junedchhipa** [comment]
You're right. Recently, a change was made to avoid bars in datetime to overlap over one another. Maybe I missed the `columnWidth` option while fixing that.
I will take another look.

**Comment by jchamb** [comment]
I did take a quick look at the stackedBar. looks like the options is there (Line 237).  Didn't dig to far to see where this.minXDiff ,  this.xRatio is set but their division seems like it is culprit.  if I do 
`barWidth = xDivision / this.seriesLen * parseInt(this.barOptions.columnWidth) / 20;`
 instead of dividing by 100 it gets closer to what I would expect. http://take.ms/JK7eZ

**Comment by jchamb** [comment]
@junedchhipa  Did any props change from 3.6.4 to 3.6.5... I updated app today to latest and now my stacks are overlapping. downgrading 1 at a time until reach 3.6.4 where they went back to correct width.

**Comment by jchamb** [comment]
closing looks like 3.6.7 had fix for this. #507

**Comment by y-nk** [comment]
still a problem in `3.8.6` ; can we reopen ?

**Comment by rogerioufjf** [comment]
Same problem here with version 3.8.6

**Comment by junedchhipa** [comment]
@rogerioufjf Have you tried updating to the latest versions 3.17.1?

**Comment by yst138451** [comment]
> @rogerioufjf Have you tried updating to the latest versions 3.17.1?

I just did, and problem still there...

**Comment by hronnie** [comment]
I'm also experiencing the same problem

**Comment by rogerioufjf** [comment]
> @rogerioufjf Have you tried updating to the latest versions 3.17.1?

Yes @junedchhipa, updating to the latest version 3.17 solved the problem for me. I just had to set the columnWidth property to 40%. Thanks!
