### ISSUE TITLE
Brush Chart target multiple charts

### ISSUE THREAD

**Issue by Snazzie** [apexcharts/apexcharts.js#3083]
## Summary
Bumping https://github.com/apexcharts/apexcharts.js/issues/1979 as its closed.

Allow brush chart to target multiple charts.

## API Changes

brush: {
target: ["chart1", "chart2"]
}

**Comment by Snazzie** [comment]
bump

**Comment by maheshaccel** [comment]
Getting lag issue when i targeting the many charts.
