### ISSUE TITLE
Groups for TreeMap 

### ISSUE THREAD

**Issue by askfarzad** [apexcharts/apexcharts.js#3086]
Please add an ability for Grouped Treemap...

something like https://coin360.com

**Comment by ndizazzo** [comment]
It doesn't render the legend "around" the series directly in the chart, but check out the demo for [Treetop Multiple Series](https://apexcharts.com/react-chart-demos/treemap-charts/treemap-multiple-series/), it's pretty close to the asset breakdown chart you linked.

**Comment by mattxyzeth** [comment]
This would be very useful. We are looking for this type of solution. It would probably require a new type of series that supports nested series.
