### ISSUE TITLE
Components does not initially render, unless you resize the browser or leave and come back to the page

### ISSUE THREAD

**Issue by rodpatulski** [apexcharts/apexcharts.js#3087]
### Steps to Reproduce

1. Install version 3.30.0 or greater
2. Render a component on two different pages (page 1 and page 2)
3. Start at page 1 
4. Go to page 2 (component on page 2 should render, it doesn't)
5. Go back to page 1 (or resize browser window)
6. The component now renders

### Expected Behavior
The component should render initially

### Actual Behavior
Component only renders after leaving page or resizing of browser

### Screenshots
First page visit:
<img width="426" alt="1" src="https://user-images.githubusercontent.com/26654985/161406358-ca51fd91-23a1-41fd-a4bb-fd8c25111a5e.png">
Visit page 2: No chart visible
<img width="446" alt="2" src="https://user-images.githubusercontent.com/26654985/161406360-5104a201-c955-45e7-92ea-cbe367e97a77.png">
Back to page 1:
<img width="470" alt="3" src="https://user-images.githubusercontent.com/26654985/161406361-b1c84865-d9d0-436d-a7ba-c50cfd74c0a3.png">
Back to page 2: Chart now appears
<img width="432" alt="4" src="https://user-images.githubusercontent.com/26654985/161406362-728a81d9-2db4-4c7e-b19d-5c0987942642.png">
The red circle is a just a simple svg component to show that this only happens with apexcharts. 

I'm using react-apexcharts but this issue shows it also happens with vue
https://github.com/apexcharts/vue-apexcharts/issues/185

This does not happen with version 3.29.0. 

I am using ionic tabs with my project but as the issue above shows, this is also occuring in plain js with no frameworks.

**Comment by rodpatulski** [comment]
Please reopen. Codepen link provider here:
https://codesandbox.io/s/github/rodpatulski/apexcharts_bug

**Comment by brianlagunas** [comment]
Since you are using a custom component, try loading the chart when the tab changes.

```
const Tab2: React.FC = () => {

  const [ initialData, setInitialData] = useState({
    options: {},
    series: []
  })

  useIonViewDidEnter(() => {
    setInitialData({
      options: {
        chart: {
          id: "basic-bar2",        
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999]
        }
      },
      series: [
        {
          name: "series-1",
          data: [130, 40, 45, 50, 49, 60, 70, 91]
        }
      ]
    })
  });
  
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 2</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen >
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 2</IonTitle>
          </IonToolbar>
        </IonHeader>
        <Chart options={initialData.options} series={initialData.series} type="bar" />
      </IonContent>
    </IonPage>
  );
};
```
