### ISSUE TITLE
Be able to hide the download options

### ISSUE THREAD

**Issue by edgren** [apexcharts/apexcharts.js#309]
Hi!

I really enjoy this function, but I really don't want to have the ability to download the chart in some image types. Please add so I can hide this feature from my charts.

**Comment by junedchhipa** [comment]
Sure,
I will add options to hide toolbar as well as toolbar menu options in the next release.

**Comment by junedchhipa** [comment]
We already have the option to hide the `download` options from the toolbar, I just forgot it.

```javascript
chart: {
    toolbar: {
        tools: {
            download: false
        }
    }
}
```

**Comment by atulpand3y** [comment]
How to diable CSV download option
