### ISSUE TITLE
ApexChart cannot be used as a JSX component

### ISSUE THREAD

**Issue by wonjin-dev** [apexcharts/apexcharts.js#3091]
### Description

***The graph is drawn normally, but an error message is output in macOS only***

```
- 'ApexChart' cannot be used as a JSX component.
- Its instance type 'ReactApexChart' is not a valid JSX element.
- The types returned by 'render()' are incompatible between these types.
- Type 'React.ReactNode' is not assignable to type 'import("~/node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
- Type '{}' is not assignable to type 'ReactNode'.
```

### Steps to Reproduce

1. ***yarn***(npm i) & ***yarn start*** (npm run start) in ***macOS***

### Expected Behavior
no error

### Actual Behavior
drawn normally, but an error message is output 

### Screenshots

<img width="901" alt="스크린샷 2022-04-10 오후 7 06 20" src="https://user-images.githubusercontent.com/82315118/162613160-4bcd7ee0-d096-4f2e-9968-e12b12730baa.png">

### Reproduction Link

***https://github.com/wonjin-dev/1coin/tree/master/src***

**Comment by OptimusOpus** [comment]
I also get this when trying to build via GitHub actions

**Comment by wonjin-dev** [comment]
Look the error logs, I suspect that there is a conflict with Styled-components. i'd appreciate your advice

**Comment by OptimusOpus** [comment]
I hadn't committed my `yarn.lock`, once I added that to GH the build worked fine and I didn't get this message

**Comment by blingblin-g** [comment]
I have same issue, but import path is little bit different. 

`Type 'React.ReactNode' is not assignable to type 'import("~/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.`

full log is below
```
'ApexChart' cannot be used as a JSX component.
  Its instance type 'ReactApexChart' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("~/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
```

**Comment by blingblin-g** [comment]
I've just solved this problem with `// @ts-ignore` on the component `<ApexChart />` like this below.

```typescript
        // @ts-ignore
        <ApexChart
          type="line"
```

I think it has an issue with React v18 and TypeScript in ApexChart.
I guess ApexChart is made up with JavaScript and it's type doesn't look like appropriate in React18

**Comment by raphaeljoer** [comment]
I also get this error!

**Comment by GusMartins499** [comment]
> I've just solved this problem with `// @ts-ignore` on the component `<ApexChart />` like this below.
> 
> ```ts
>         // @ts-ignore
>         <ApexChart
>           type="line"
> ```
> 
> I think it has an issue with React v18 and TypeScript in ApexChart. I guess ApexChart is made up with JavaScript and its type doesn't look like appropriate in React18

This works for me
