### ISSUE TITLE
Heatmap: invert color scale range

### ISSUE THREAD

**Issue by MarkWestside** [apexcharts/apexcharts.js#311]
**Is your feature request related to a problem? Please describe.**
Color scale ranges on heat maps always go from light to dark.
Example: two ranges, red from 0 to 1 and green from 1 to 2. Right now, 0.1 is light red and 0.8 dark red.
So the transition from 0 to 2 would be light red > dark red > light green > dark green.

**Describe the solution you'd like**
Option to invert color scale for individual ranges.
Example: 0.1 should be dark red and 0.8 light red.
Transition should be dark red > light red > light green > dark green.

**Additional context**
Am I missing something and this is already implemented?

**Comment by gazsi3** [comment]
Hi,

this feature would be greatly appriciated.
Do you have any idea when it could be done?

Thank you also in advance!

**Comment by sasipannon** [comment]
Any update on this yet?
I really wish this feature will come soon.
