### ISSUE TITLE
Custom Text - addText is not a function

### ISSUE THREAD

**Issue by rrredirect** [apexcharts/apexcharts.js#3114]
Hello,

Thanks for such a great charting library. I am looking to add custom text to my charts, and found an earlier issue [#169](https://github.com/apexcharts/apexcharts.js/issues/169) that pointed to the addText method to achieve this. I am currently experiencing what others in that issue later posted - an error saying "addText is not a function". In the codepen example from issue #169 that originally worked, the addText function is not generating any text:
[Codepen Example](https://codepen.io/apexcharts/pen/VEGyGx)

Do you know a fix for this, or other ways to add custom text beyond a simple annotation? Many thanks for your help.

**Comment by brianlagunas** [comment]
I am not sure of the history of this method, but it does not currently exist on the chart object.  

https://github.com/apexcharts/apexcharts.js/blob/main/src/apexcharts.js

It is also not a documented method

https://apexcharts.com/docs/methods/

**Comment by ianinazarenko** [comment]
Just in case it can help anyone: I've found out that addText() method has been removed in version 3.16.1 (you can check it here - https://github.com/apexcharts/apexcharts.js/releases/tag/v3.16.1). Which is quite sad btw
