### ISSUE TITLE
Latest version of Apex Charts does not work on iOS 13

### ISSUE THREAD

**Issue by Svensky16** [apexcharts/apexcharts.js#3115]
### Description

We were running version 1.5.9 and it worked as intended, apart from the fill.gradient feature so I decided to update thinking that the issue may have been sold in a newer version. I was welcomed by empty cards with no charts, then decided to see if the apex demo charts work and to my surprise they don't. On the latest os at the time ( iOS 15 ) the graphs work as intended. iOS 13 was launched in late 2019 so it is not that old that it doesn't represent an issue for us.

### Steps to Reproduce

1.  Open any of the apex charts examples with a phone that has iOS13 (tested with iPhone 7 iOS 13.3 Safari and Chrome)

### Expected Behavior
The charts should render normally.

### Actual Behavior
Nothing is shown in place of the charts. 

### Screenshots

![image0](https://user-images.githubusercontent.com/37862194/165299030-655e4a89-75b7-4116-b713-7cf982299a6b.png)

![image1](https://user-images.githubusercontent.com/37862194/165299264-dac422bb-fd5b-44cb-9e8b-14f2ee0dfbcf.png)

### Reproduction Link

You can just try the demos on the website
https://apexcharts.com/javascript-chart-demos/line-charts/basic/

Same story with a basic code pen: 
https://codepen.io/davidcostin/pen/oNprpyY

You can let me know if you need any help regarding testing on the actual hardware.

**Comment by brianlagunas** [comment]
Unable to reproduce.
