### ISSUE TITLE
Y-axis log scale to respect "min" and "forceNiceScale" options

### ISSUE THREAD

**Issue by 04alband** [apexcharts/apexcharts.js#3125]
## Summary

Have logarithmic y-axes respect the given `min` option, and only use 'nice' values when the `forceNiceScale` option is true.

Currently, when using a [logarithmic y-axis](https://apexcharts.com/docs/options/yaxis/#logarithmic), the [`min`](https://apexcharts.com/docs/options/yaxis/#min) option isn't really used (except checking if it's 0) and the [`forceNiceScale`](https://apexcharts.com/docs/options/yaxis/#forceNiceScale) option doesn't do anything.

I'd like it if the scale always used the given min/max values if given and if `forceNiceScale=false`. When `forceNiceScale=true`, the generated scale would simply use the multiples of the base above and below the data's highest and lowest y values.

## API Changes

The API would be the same, though it might make sense for `forceNiceScale` to default to `true` if the axis is set to logarithmic, as this would be closest to current behavior? Though I'm not sure if the `forceNiceScale` default value can depend on another option's value?

## Intended Use Case

I had some data that was logarithmic but was roughly between 300-2000. I could only get the axis to go between 1 and 2000 which left most of the graph empty and made it hard to see what my data was doing. With my changes it's much easier.

**Comment by 04alband** [comment]
I've tried to follow [these guidelines](https://github.com/apexcharts/apexcharts.js/blob/845c0538cb156eb941308e9b0ee53dfc993abf9c/CONTRIBUTING.md) and have forked, committed my proposal in a new branch and created a pull request #3126 . Though this is my first time contributing to a public repo, and doing a PR (and doing node.js stuff!) so apologies if I've scuffed something.

**Comment by joshribakoff-sm** [comment]
Looks like this issue can be closed?

**Comment by 04alband** [comment]
Yeah, I agree. There's still a couple of tests that fail from that PR (related to multiple y-axes) due to another issue but I've explained those in the PR and they can be tracked there or separately. If I get time I'd like to end up using multiple y-axes so may bump into it again and have another look but for the moment, no time!
