### ISSUE TITLE
Polar Area Charts ignores tooltip options

### ISSUE THREAD

**Issue by 4eveRS** [apexcharts/apexcharts.js#3128]
### Description
Currently, polarArea charts are not obeying the parameters passed over the tooltip options (followCursor, fixed, etc.)

### Steps to Reproduce

1. Hover the cursor over any series
2. followCursor is set to false and yet the tooltip is following the user cursor

### Expected Behavior

The polarArea chart should abide by all tooltip options.

### Actual Behavior

The polarArea chart is not following the parameters passed over the tooltip options.

### Reproduction Link
[Codepen Reproduction Link](https://codepen.io/4eveRS/pen/mdXJXoR)

**Comment by junedchhipa** [comment]
`followCursor` doesn't work for pie/donut/polar-area charts as of now (v3.35.0).
