### ISSUE TITLE
I have a chart with Apexchart and I am getting this error(Cannot read properties of undefined (reading 'filter')) why?

### ISSUE THREAD

**Issue by ibrahimozdenkotic** [apexcharts/apexcharts.js#3129]
There is a code structure as seen on this site, and while working on this site without any problems, I am getting this error on my own computer, why?

Uncaught TypeError: Cannot read properties of undefined (reading 'filter')

https://codepen.io/Gahzee/pen/OJzezPm

[There is such an error in the console.](https://i.stack.imgur.com/Fk7ip.png)

I explained the problem in more detail here and the codes are also here.(https://stackoverflow.com/questions/72033165/item-selected-from-dropdown-item-not-opening-on-first-click)

**Comment by junedchhipa** [comment]
As tested on v3.54.1, this is no longer an issue.
