### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by edgren** [apexcharts/apexcharts.js#313]
Hi!

I am trying to add ApexCharts to my project for real now (just tested it before), but now I can't get it to work as before. I have added `<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>` to the `head` tag and added the following "Starter Guide" code to my JavaScript file, which is included to every page I visit in my project:

```JS
	import ApexCharts from 'apexcharts'
	var options = {
		chart: {
		  type: 'bar'
		},
		series: [{
		  name: 'sales',
		  data: [30, 40, 35, 50, 49, 60, 70, 91, 125]
		}],
		xaxis: {
		  categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999]
		}
	  }
	  
	  var chart = new ApexCharts(document.querySelector("#chart"), options);
	  chart.render();
```

And in the HTML code, I've added `<div id="graph"></div>`.

But I am keep on getting `SyntaxError: import declarations may only appear at top level of a module` in the console. What have I missed?

**Comment by junedchhipa** [comment]
```javascript
import ApexCharts from 'apexcharts'
```
The import line is used when you load ApexCharts in a module system and is not required if you load ApexCharts via script. 
So, remove it and try again.
Also, please look into the `samples` directory provided to learn how to use ApexCharts with vanilla-js, vue / react.
