### ISSUE TITLE
XAnnotation needs to match label not the value

### ISSUE THREAD

**Issue by mreiche** [apexcharts/apexcharts.js#3137]
### Description

In relation to https://github.com/apexcharts/apexcharts.js/issues/2671
An annotation doesn't show up, when it's x value doesn't match the formatted X-Axis-label.

### Steps to Reproduce

1. Open the codepen (link below).
2. See that the "this shows up" annotation shows up.
3. See that "this not" annotation doesn't show up.
4. Changing the annotation's x value to `-6-` instead of `6` "fixes" that.

### Expected Behavior

<img width="664" alt="Bildschirmfoto 2022-05-09 um 19 29 50" src="https://user-images.githubusercontent.com/572453/167464864-4549ece2-0a3f-47ac-94b6-9cf0dac0a6f9.png">

Annotations should shown for a value, not the formatted x label.

### Actual Behavior

<img width="668" alt="Bildschirmfoto 2022-05-09 um 19 27 12" src="https://user-images.githubusercontent.com/572453/167464728-350824b6-de7c-43c9-b002-4da7d047c42e.png">

Annotations x value need to match the formatted x label.

### Reproduction Link

https://codepen.io/mreiche/pen/LYQNyjr

**Comment by junedchhipa** [comment]
In a category chart, it is not possible to determine the annotation position as the x-axis is not linear. The string can appear anywhere on the x-axis and hence ApexCharts uses actual label.
If you use a timeline or a numeric x-axis, the annotation will show even if the actual label is not present on the x-axis.
