### ISSUE TITLE
Multiline x-axis categories text duplicated for each line

### ISSUE THREAD

**Issue by kdeds** [apexcharts/apexcharts.js#3138]
### Description
Multiline category names are rendering on multiple lines, however each line contains the full text. This makes the text appear duplicated for as many line breaks as you have entered. I can reproduce this beginning with version 3.35.1. It is not present in 3.35.0.

### Steps to Reproduce

1. Create a bar chart with line breaks in the x-axis categories as specified in the documentation here: https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/
2. Render the chart and view the category labels.

### Expected Behavior
Category labels are broken up by the entries in the array. Ex:   
["A really", "long category name"] displays as    
A really   
long category name

### Actual Behavior
Full label is displayed on each line, including the comma.
["A really", "long category name"] displays as 
A really, long category name   
A really, long category name

### Screenshots
![image](https://user-images.githubusercontent.com/2187441/167480944-e1a04a14-3adf-4b84-bb9c-9c7ed9f02ac0.png)

### Reproduction Link
https://codepen.io/kdeds/pen/ZErWJoY

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed the issue. A new patch will be released soon.

**Comment by kdeds** [comment]
Thank you for the quick fix @junedchhipa ! Do you have a date you plan to release the patch?
