### ISSUE TITLE
Download chart with different options

### ISSUE THREAD

**Issue by MarkWestside** [apexcharts/apexcharts.js#314]
**Is your feature request related to a problem? Please describe.**
Download chart downloads chart with current options.
Example: On a website with dark background, the chart uses white text. When downloaded, the text is also white.

**Describe the solution you'd like**
Being able to specify options for the chart when downloaded (same structure as chart options where values in the download options overwrite the regular options).
Example: Render chart on a website with dark background with white text and specify the text color in the download options so that the downloaded chart uses black text (or different color scheme, or different font sizes, etc.)
Maybe even add allow to use download links (like print version) that use the download options and the regular links, where the chart is downloaded as currently rendered.

**Comment by junedchhipa** [comment]
You can make the chart's background dark 
```javascript
chart: {
   background: '#000'
}
```

When you download with this setting, the chart's background color will be preserved.

**Comment by MarkWestside** [comment]
I meant like two different versions of the chart in general: One that is rendered on the website and another that is specific for download (or a print version so to speak).
If the chart is rendered to be used on a dark website (maybe a dark mode) the downloadable chart should be readable on white background (to be used in PowerPoint for example).

Right now to achieve a different download chart, the chart has to be rerendered with the download options (different color scheme, dark text, light background, etc) and reverted to the original after  download.

**Comment by junedchhipa** [comment]
Overriding chart options this way and getting back to the original after download will be difficult (and prone to errors). 
Sorry, this cannot be integrated into the core chart library.
