### ISSUE TITLE
First and last column cropped in bar chart

### ISSUE THREAD

**Issue by lucismedia** [apexcharts/apexcharts.js#3140]
Hi, I'm building a bar chart with multiple columns. The first and last column are cropped when using 'datetime' as type on the x-axis. See screenshot. When I switch to, for example, 'category' or 'numeric' as x-axis type, there is no issue.

![apex-column-issue-2](https://user-images.githubusercontent.com/8280863/167972505-77f6e7e1-69d3-498c-af7a-8372c3f05d02.png)

It's similar to these previous issues: #540 and #280.

Is this a bug or can I fix it with adapting the styling?

Thanks so much.

**Comment by Maryam0187** [comment]
I am using the latest version of  "vue-apexcharts": "^1.6.2", and still facing this cropped issue @brianlagunas @lucismedia
