### ISSUE TITLE
Support Multi Colors in Negative Area Charts

### ISSUE THREAD

**Issue by cgibson-swyftx** [apexcharts/apexcharts.js#3142]
## Summary

Please support different colours for positive and negative area charts like the below.
![image](https://user-images.githubusercontent.com/102004594/168175843-08971e83-ffce-4124-908b-8bec6c63301e.png)

## API Changes

The code should the same as other multi-color charts:
```
colors: [function({ value, seriesIndex, w }) {
  if (value < 55) {
      return '#7E36AF'
  } else {
      return '#D9534F'
  }
}, function({ value, seriesIndex, w }) {
  if (value < 111) {
      return '#7E36AF'
  } else {
      return '#D9534F'
  }
}]
```

## Intended Use Case

Currently Apex only supports 1 colour for negative area charts. This limits its use as the negative area with the same colour as the positive can be misleading when using the colour as a visual aid.

**Comment by Geovanek** [comment]
I need this feature to.

**Comment by benstahl** [comment]
Apparently this issue has been closed, but I'd like to see it revisited. This would be really useful for finance charting.
