### ISSUE TITLE
Error: <svg> attribute height: Expected length, "NaN".

### ISSUE THREAD

**Issue by i23098** [apexcharts/apexcharts.js#3144]
### Description
Exporting SVG gives error in console:
​ Error: <svg> attribute height: Expected length, "NaN".

### Steps to Reproduce

1. Create chart
2. Go to menu and export to SVG
3. Error in console

### Expected Behavior
Export to SVG with no error in console

### Actual Behavior
Export to SVG is done but there's an error in console:
​ Error: <svg> attribute height: Expected length, "NaN".

### Screenshots
![image](https://user-images.githubusercontent.com/4552524/168297865-c725109e-dabd-4863-b1ad-2beaca17fb49.png)

### Reproduction Link

https://codepen.io/kevflood/pen/MWrdPme

**Comment by junedchhipa** [comment]
This is no longer an issue as tested on v3.54.0
