### ISSUE TITLE
Line breaks and multiline text in axes labels is not working

### ISSUE THREAD

**Issue by Guillescas** [apexcharts/apexcharts.js#3145]
### Description
When you want to break line in xaxis, it's not possible. Even passing a correct configuration object, the labels don't break the line.

### Steps to Reproduce
1. Mount an basic configuration object.
2. In "categories", pass an array of string, but in one position pass another array of string.
3. Save and see that the graph will duplicate the label and not break lines, as expected

### Expected Behavior
The label must break line

### Actual Behavior
The label stay duplicated and don't break line

### Screenshots
<img width="628" alt="Screen Shot 2022-05-13 at 10 48 59" src="https://user-images.githubusercontent.com/59893752/168297828-b32e0b20-285c-4d5e-9c84-bbf3ca279376.png">

### Reproduction Link
https://codepen.io/guillescas/pen/MWQbYqz

**Comment by eduardo-amaro-maciel** [comment]
I'm also having this problem, I had implemented the chart code last week and this Monday it had this bug

**Comment by jaredhabeck** [comment]
Confirmed in 3.35.0 - downgrading to 3.34.0 fixed the issue in my case. Thanks for your hard work contributors!

**Comment by eduardo-amaro-maciel** [comment]
@jaredhabeck how do I have a link (Direct <script> include) with the desired version?

**Comment by kelly-howard-rh** [comment]
@eduardo-amaro-maciel You can just add "@3.35.0" to the end of the url. Just had to do this for our sites as well. FWIW, I found the issue in 3.35.1, and 3.35.0 was fine.

**Comment by kelly-howard-rh** [comment]
Also, @junedchhipa corrected this issue after my bug report here: https://github.com/apexcharts/apexcharts.js/issues/3138 
but has not done another release for it yet.

**Comment by eduardo-amaro-maciel** [comment]
@kelly-howard-rh thanks!!!!!

**Comment by junedchhipa** [comment]
Released 3.35.3 which fixes this issue
