### ISSUE TITLE
Lines chart with multiple series/lines broken?

### ISSUE THREAD

**Issue by Osiris-Team** [apexcharts/apexcharts.js#3147]
### Description

![image](https://user-images.githubusercontent.com/59899645/168439824-d87ca822-1b52-490a-a511-24631181a51e.png))

### Steps to Reproduce
1. Open code pen: https://codepen.io/osiris-team/pen/jOZVxPm and voila

**Comment by brianlagunas** [comment]
Please create a functioning code pen.

**Comment by Osiris-Team** [comment]
@brianlagunas what do you mean? The screenshot I took is from the codepen?

**Comment by Osiris-Team** [comment]
@brianlagunas created my own codepen, if thats what u meant.

**Comment by Osiris-Team** [comment]
Looks like the order of the data is important.
The array of dates I was using, was not in ascending order, which caused the issues.
