### ISSUE TITLE
Error when categories receive a multidimensional array

### ISSUE THREAD

**Issue by FLopes-14** [apexcharts/apexcharts.js#3150]
### Description

When the categories receive a multidimensional array, the xaxis show duplicate data on two lines.
On the previous versions (like 3.34.0) this was working, but when i update to last version this stopped working well.
Hope you can help me with that.

### Steps to Reproduce

1. Exemple: let categories = [
        ["Ter", "01\/02"],
        ["Qua", "02\/02"]
      ];

### Expected Behavior
![image](https://user-images.githubusercontent.com/58472032/168854207-f8634d4f-f40f-403c-8a82-70edb43e0b2d.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/58472032/168849478-31389280-dfe6-480a-95f1-50d2a30d1dd8.png)

### Reproduction Link
https://codepen.io/flopes-14/pen/VwQpPzy

**Comment by eduardo-amaro-maciel** [comment]
I'm also having this problem, I had implemented the chart code last week and this Monday it had this bug, how do I have a link (Direct <script> include) with the desired version?

**Comment by FLopes-14** [comment]
I was testing last versions until find the desired version :D 
https://www.npmjs.com/package/apexcharts?activeTab=versions

**Comment by eduardo-amaro-maciel** [comment]
Do you used npm or direct link for html? 
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script> 
or
npm i apexcharts

**Comment by FLopes-14** [comment]
npm i apexcharts

And i use Vue.js

**Comment by junedchhipa** [comment]
Released 3.35.3 which fixes this

**Comment by FLopes-14** [comment]
Thanks
