### ISSUE TITLE
Legend not rendered when collapsing last non-empty series

### ISSUE THREAD

**Issue by Sabientje65** [apexcharts/apexcharts.js#3156]
### Description

Upon collapsing the final series containing data within a chart containing multiple series, some with, and some without data, Apex stops rendering the legend. This results in the inability to expand the collapsed series again. 

The root cause seems to be Apex not taking into consideration collapsed series upon deciding whether or not to render the legend. From what I've seen, upon collapsing a series, it's moved to a `collapsedSeries` collection alongside the original data. The `series` item itself then gets its `data` collection replaced by an empty collection. Upon determining whether to render the legend or not, Apex only sees empty data collections, and thus decides to skip rendering the legend.

After a little tinkering with the source, I've found altering the following code in the `ApexCharts` class to fix the issue.  

Original:
```
    // legend is calculated here before coreCalculations because it affects the plottable area
    // if there is some data to show or user collapsed all series, then proceed drawing legend
    if (
      !gl.noData ||
      gl.collapsedSeries.length === gl.series.length ||
      w.config.legend.showForSingleSeries
    ) {
      this.legend.init()
    }
```

Fixed:
```
    // legend is calculated here before coreCalculations because it affects the plottable area
    // if there is some data to show or user collapsed all series, then proceed drawing legend
    if (
      !gl.noData ||
      gl.collapsedSeries.length === gl.series.length ||
      gl.collapsedSeries.some((s) => s.data && s.data.length !== 0) ||
      w.config.legend.showForSingleSeries
    ) {
      this.legend.init()
    }
```

Notice the addition of also checking whether the collapsed series contain data or not. I'm not familiar enough with Apex to be able to tell whether this breaks other use cases however, hence the lack of a PR accompanying the bug report. :-)

### Steps to Reproduce

1. Collapse series containing data by clicking on the legend item
2. Watch legend disappear into nothingness, rendering the user unable to expand the series containing data

### Expected Behavior

The legend should be rendered when all series containing data have been collapsed, leaving only series without data expanded.

### Actual Behavior

The legend does not get rendered upon collapsing the final series with data while having at least one series without data expanded.

### Screenshots

![image](https://user-images.githubusercontent.com/8700443/169514621-a6b780ca-2d26-413c-94f8-f5b0f2e7d04d.png)
![image](https://user-images.githubusercontent.com/8700443/169503856-261f531c-8561-4215-accc-f046432d563c.png)

### Reproduction Link

https://codepen.io/dnx_db/pen/GRQENJK

**Comment by junedchhipa** [comment]
Not an issue anymore as tested on v4.1.0
