### ISSUE TITLE
It is a possibility that you may have not included 'data' property in series.

### ISSUE THREAD

**Issue by leo4444** [apexcharts/apexcharts.js#316]
Surely it is not an error but when I try to implement a dynamic diagram (https://apexcharts.com/javascript-chart-demos/column-charts/dynamic-loaded-chart/) when implementing the code found in the example of the page returns the error "It is a possibility that you may have not included 'data' property in series." ...

When analyzing the code I realized that it does not have a data generator (makeData ()) so I developed the following function to generate random data but the error persists, could someone tell me what could be wrong?

const makeData = function () {
      const arg = [53, 61, 27, 54, 43, 19, 46];
      const array = arg.slice ();
      let currentIndex = array.length,
        temporaryValue, randomIndex;

      while (0! == currentIndex) {

        randomIndex = Math.floor (Math.random () * currentIndex);
        currentIndex - = 1;

        temporaryValue = array [currentIndex];
        array [currentIndex] = array [randomIndex];
        array [randomIndex] = temporaryValue;
      }

      return array;
    };

From already thank you very much!

**Comment by junedchhipa** [comment]
Oops! I should have included a dependent file in the same example.
Please include code from this file - https://raw.githubusercontent.com/apexcharts/apexcharts.js/master/samples/vanilla-js/column/data.js


```javascript
/**
 * Randomize array element order in-place.
 * Using Durstenfeld shuffle algorithm.
 */
function shuffleArray(array) {
  for (var i = array.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var temp = array[i];
    array[i] = array[j];
    array[j] = temp;
  }
  return array;
}

var arrayData = [{
  y: 400,
  quarters: [{
    x: 'Q1',
    y: 120
  }, {
    x: 'Q2',
    y: 90
  }, {
    x: 'Q3',
    y: 100
  }, {
    x: 'Q4',
    y: 90
  }]
}, {
  y: 430,
  quarters: [{
    x: 'Q1',
    y: 120
  }, {
    x: 'Q2',
    y: 110
  }, {
    x: 'Q3',
    y: 90
  }, {
    x: 'Q4',
    y: 110
  }]
}, {
  y: 448,
  quarters: [{
    x: 'Q1',
    y: 70
  }, {
    x: 'Q2',
    y: 100
  }, {
    x: 'Q3',
    y: 140
  }, {
    x: 'Q4',
    y: 138
  }]
}, {
  y: 470,
  quarters: [{
    x: 'Q1',
    y: 150
  }, {
    x: 'Q2',
    y: 60
  }, {
    x: 'Q3',
    y: 190
  }, {
    x: 'Q4',
    y: 70
  }]
}, {
  y: 540,
  quarters: [{
    x: 'Q1',
    y: 120
  }, {
    x: 'Q2',
    y: 120
  }, {
    x: 'Q3',
    y: 130
  }, {
    x: 'Q4',
    y: 170
  }]
}, {
  y: 580,
  quarters: [{
    x: 'Q1',
    y: 170
  }, {
    x: 'Q2',
    y: 130
  }, {
    x: 'Q3',
    y: 120
  }, {
    x: 'Q4',
    y: 160
  }]
}];

function makeData() {
  var dataSet = shuffleArray(arrayData)

  var dataYearSeries = [{
    x: "2011",
    y: dataSet[0].y,
    color: colors[0],
    quarters: dataSet[0].quarters
  }, {
    x: "2012",
    y: dataSet[1].y,
    color: colors[1],
    quarters: dataSet[1].quarters
  }, {
    x: "2013",
    y: dataSet[2].y,
    color: colors[2],
    quarters: dataSet[2].quarters
  }, {
    x: "2014",
    y: dataSet[3].y,
    color: colors[3],
    quarters: dataSet[3].quarters
  }, {
    x: "2015",
    y: dataSet[4].y,
    color: colors[4],
    quarters: dataSet[4].quarters
  }, {
    x: "2016",
    y: dataSet[5].y,
    color: colors[5],
    quarters: dataSet[5].quarters
  }];

  return dataYearSeries
}
```

**Comment by leo4444** [comment]
wow! That was very fast!
Thank you very much, you are a genius!
I thank you very much, it's working now
