### ISSUE TITLE
Weighted Polar Chart

### ISSUE THREAD

**Issue by JawadJaber** [apexcharts/apexcharts.js#3172]
## Summary

I have a situation where I want to use Polar Charts, but I have noticed that the pies in the polar charts are equally added, which means they have same angle. I need to change this angle based on the item weight. I assume the summation of all weights must be 100, or 360, etc

## Intended Use Case

In nested models where for example a tree node and a weight for all its children and the children have weights also, I would be able to present the parent and its (weighted) children together using polar chart.

**Comment by stephane-ruhlmann** [comment]
@JawadJaber Hi, I have a similar usecase for my current project. Did you find any solution?
