### ISSUE TITLE
apexcharts:6 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by jaimestuardo** [apexcharts/apexcharts.js#3177]
Hello, please see this CodePen:

https://codepen.io/jaime-stuardo/pen/oNEqbNJ

In browser developer tools, console tab, this error appears:

```
apexcharts:6 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at apexcharts:6:196329
    at Array.filter (<anonymous>)
    at t.value (apexcharts:6:196300)
    at t.value (apexcharts:14:46778)
    at apexcharts:14:21841
    at new Promise (<anonymous>)
    at t.value (apexcharts:14:21629)
    at pen.js?key=pen.js-e964954a-1e05-641a-113d-5680a16fc25a:118:7
```

What's wrong with the options I have passed or is this a bug? This also occurs in my development site with ApexCharts v3.18.0

Thanks
Jaime

**Comment by ordago** [comment]
```
    "locales": [
            null
        ],
```

You're not giving locales to the graph. I needs them or they should be set globally. Error goes away if you give the necesary locales.

**Comment by brianlagunas** [comment]
Thanks for the solution @ordago! We appreciate your contribution.
