### ISSUE TITLE
Bar graph: SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Mamric** [apexcharts/apexcharts.js#318]
## Codepen

I'm sorry, I'm pretty new to github still, and I'm not fully sure how to properly set up a Codepen example.

## Explanation

-Expected to get the chart to load. Nothing is loading in, and getting errors in console (more info below). It was working fine as of yesterday. Been using Apex for a few months, and haven't had any troubles. No changes to the code on my end.

-nothing loading in. Just blank on the screen where the chart should be.

-Getting and 'Uncaught SyntaxError: Unexpected end of input' on line: 'apexcharts:6' in the console. Right after that, getting an 'Uncaught ReferenceError: ApexCharts is not defined' in the console. The first error will only appear in the console if I copy and paste the code from the https://cdn.jsdelivr.net/npm/apexcharts website into a js file on my own computer, and edit the html to src that file, just so you know.

**Comment by junedchhipa** [comment]
Sorry, the last build (3.3.0) on **jsdelivr** was somehow corrupted when deployed, although tested successfully on local after the build. I don't know the reason for it, so I have created new build files and released a new version 3.3.1

Please use this link - https://cdn.jsdelivr.net/npm/apexcharts@latest to get the latest release.

Thanks for reporting the issue.
