### ISSUE TITLE
Multiple time style include in the same files

### ISSUE THREAD

**Issue by alokVishu** [apexcharts/apexcharts.js#3180]
### Description
I have noticed that when I used multiple charts in the same page there is multiple same style override. It is due to style including multiple times. 

### Steps to Reproduce

1. Try to use multiple charts on the same page
2. Try to use legend in all chart 
3. Now you can see, that the apex-chart style includes multiple times

### Expected Behavior
Style should not include multiple times when you use multiple charts on the same page. 
### Actual Behavior
There is multiple style overrides due to multiple includes.
### Screenshots
![image](https://user-images.githubusercontent.com/80033712/171175164-a5877723-b730-4c4f-97a8-e33e1496c792.png)

### Reproduction Link
https://apexcharts.com/javascript-chart-demos/dashboards/modern/

**Comment by brianlagunas** [comment]
Please provide a codepen reproduction.
