### ISSUE TITLE
Toggle series of Area Apex charts from another component

### ISSUE THREAD

**Issue by Anthony-D11** [apexcharts/apexcharts.js#3189]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/3188

<div type='discussions-op-text'>

<sup>Originally posted by **Anthony-D11** June  5, 2022</sup>
Hi everyone,
I'm a beginner in Angular and I'm working on Apexchart in Angular. I have 2 component: NavigationBarComponent and DashboardComponent. The chart is in DashboardComponent and it has 3 series. I need a way to let users click at one menu item in NavigationBarComponent to toggle 2 series and export the chart with only one series. Could you suggest me anyway to achieve that?</div>

**Comment by Anthony-D11** [comment]
Why is it closed ?

**Comment by brianlagunas** [comment]
You double posted in discussions and as an issue.

**Comment by Anthony-D11** [comment]
> You double posted in discussions and as an issue.

Where should I post ?
