### ISSUE TITLE
[Question] we need some specific requirements which is possible using library or not..?

### ISSUE THREAD

**Issue by sanymochi** [apexcharts/apexcharts.js#319]
1.	We need scrollbar in the chart area so is there any way to achieve this? (Screenshot_1). (Please note that we don’t need zoom and panning functionality here.)
![screenshot_1](https://user-images.githubusercontent.com/40659606/52689734-30f28e80-2f81-11e9-81c0-bcdba44805b3.png)

2.	Is that possible we can use zoom with category?

**Comment by junedchhipa** [comment]
1. Scroller was present prior apexcharts v2.0 but was removed due to buggy behavior.
2. No, currently zooming on category axis is not supported, but may come in future.
