### ISSUE TITLE
Docs site getting down sometimes

### ISSUE THREAD

**Issue by kalaomer** [apexcharts/apexcharts.js#3194]
### Description

Docs site getting down sometimes. I keep getting this error lately.

### Screenshots

<img width="1439" alt="Screen Shot 2022-06-08 at 12 16 52" src="https://user-images.githubusercontent.com/2925345/172580630-4a90531e-e942-48b7-8779-75a7dc167f42.png">

**Comment by brianlagunas** [comment]
The site is up now. Thanks for reporting this.

**Comment by vildar** [comment]
@brianlagunas This is a recurring issue.

**Comment by brianlagunas** [comment]
We know. Please see this comment: https://github.com/apexcharts/apexcharts.js/issues/3212#issuecomment-1210783837
