### ISSUE TITLE
Increase radialbar stroke-width / thickness

### ISSUE THREAD

**Issue by rsamQ** [apexcharts/apexcharts.js#320]
The stroke-width scales with the size of the chart, which makes it very hard to spot, if the chart is smaller. I want to use the radial bar chart as a sort of indicator, so it would be pretty small. I know u can adjust the width of the track, but i couldn't find a solution on how to increase the stroke-width of the bar.

![image](https://user-images.githubusercontent.com/47593875/52705424-1f11eb00-2f83-11e9-8caa-9ab3bb0fe5c0.png)
( left is size: 100, right is size: 50 )

Is there any possibility to manipulate the stroke-width of the bar? Would be more than happy if someone could give me a lead.

**Comment by junedchhipa** [comment]
Try these settings to make the bars thick

```javascript
    plotOptions: {
        radialBar: {
          hollow: {
            size: '30%', // percentage
          },
          track: {
            margin: 1, // margin is in pixels
          }
        }
     }
```

**Comment by rsamQ** [comment]
It's working just right. Thank you very much!
