### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by AntonyChiossi** [apexcharts/apexcharts.js#3212]
### Description

The website have some db related issue making the doc unavailable.

https://apexcharts.com/docs/formatting-axes-labels/

### Steps to Reproduce

1. visit https://apexcharts.com/docs/formatting-axes-labels/

### Expected Behavior
Being able to read the doc
### Actual Behavior
Error message
### Screenshots
![image](https://user-images.githubusercontent.com/26548787/173547566-32620e5f-2913-4355-b6b3-82ed71fcc1b8.png)

### Reproduction Link

https://apexcharts.com/docs/formatting-axes-labels/

**Comment by clounie** [comment]
Working now.

**Comment by brianlagunas** [comment]
Yeah, we are currently on a shared host. We are looking at moving to a more reliable host to prevent this from happening again.

**Comment by V1CTOR-cloud** [comment]
> Working now.

Sometimes work sometimes not, just wait to move the host xd

**Comment by Mersal-Mohamed2** [comment]
every day it should get down more than one time 
today also sandbox examples is down

**Comment by V1CTOR-cloud** [comment]
> Any update on new hosting? Docs down more often than not, it seems. Would like to use apexcharts in projects but can't do it without the documentation. Otherwise, would you let me clone the wordpress site?

I don't work as apex charts programmer or something, but i guess so, in her license says you can pick the code with totally freedom, but the docs xd, in my opinion just wait and reload the docs until you can see it, sometimes doesn't work and sometimes does, just wait but no all the docs are avaliable, i found the answers to my questions in:

> https://apexcharts.com/
> https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877
> https://stackoverflow.com/

If you are building a big proyect or you need so especific docs about how it works something related with apex you can find it there and doing some test on HTML or something, anyways i don't think the docs work fine in a long way so...

Hope my post could help folks.

**Comment by placid2000** [comment]
Any news on this? Any known deadlines?

**Comment by brianlagunas** [comment]
There are no updates o this. Everyone must keep in mind that as an OSS project, we do not make any money off this project, yet we have expenses to pay such as hosting. Currently we are on a shared host to keep our personal costs down. As soon as we have another option, we'll update everyone.

**Comment by damianstasik** [comment]
@brianlagunas would you accept a PR that would contain the whole documentation converted to use some static site generation? This way you could just host the built documentation on GitHub Pages or Netlify for free + if for some reason GH or Netlify would not be available, there is plus of having documentation readable as markdown here in the repo. I would be willing to work on it if you would be willing to redesign&refactor your homepage.

**Comment by brianlagunas** [comment]
@damianstasik If we were to move the site, it would have to be in it's entirety. This would be a large effort and not something anyone has time for right now. If/when we decided to start that process we will definitely be reaching out to the community for help. Thank you for volunteering to participate in such a huge effort.

**Comment by KalinaStefanova** [comment]
Our team is experiencing the same issue.

**Comment by brianlagunas** [comment]
@KalinaStefanova I'm excited to hear that a big insurance company is thinking of using our OSS project. Maybe you can ask them to make a donation to the project so we can afford to upgrade our hosting. Let me know what they say.

**Comment by KalinaStefanova** [comment]
> @KalinaStefanova I'm excited to hear that a big insurance company is thinking of using our OSS project. Maybe you can ask them to make a donation to the project so we can afford to upgrade our hosting. Let me know what they say.

Well, it is quite strange for a Microsoft MVP, that works for Infragistics to beg for donations in github.

**Comment by brianlagunas** [comment]
@KalinaStefanova I would always recommend that companies pay for the components they use in their products. The problem with OSS is that the people working on the project don't get paid for it, and they have to work fulltime day jobs and fit in the OSS work when they have time. It makes it very difficult to keep things reliable especially when no one else steps up to help such as these companies that have the funds to help keep projects sustainable, but refuse to do so.

**Comment by KalinaStefanova** [comment]
> @KalinaStefanova I would always recommend that companies pay for the components they use in their products. The problem with OSS is that the people working on the project don't get paid for it, and they have to work fulltime day jobs and fit in the OSS work when they have time. It makes it very difficult to keep things reliable especially when no one else steps up to help such as these companies that have the funds to help keep projects sustainable, but refuse to do so.

Actually, many paid component suits were free components in the beginning. And making something reliable and solid from the start makes sense, because it is an investment for the future. The future of these people you describe - they can be free of their full-time job some day.

**Comment by brianlagunas** [comment]
@KalinaStefanova I wish that were true. I've been working on OSS since 2008, and I'm still stuck in my day job because companies still want everything for free. My main project has over 35 million downloads. If only I had 50 cents for every download 😄

**Comment by placid2000** [comment]
@brianlagunas Have you considered implementing donation possibilities?

**Comment by brianlagunas** [comment]
@placid2000 It's already implemented

![image](https://user-images.githubusercontent.com/835562/188896760-20232d98-316f-455f-b9c0-6aa19a0bc8f6.png)

**Comment by hilmia** [comment]
I'm noticing this issue often, today the docs were down for about an hour as well. I hope that it can be stabilised, it's an amazing chart library!

**Comment by brianlagunas** [comment]
We have finally moved to a new host and should no longer has these issues. Please give the site a try and let us know if you run into any more issues.

Thank you everyone for your patience as we worked through this process.

**Comment by hilmia** [comment]
Unfortunately it's not fixed. The docs are down right now

**Comment by finnley-morris** [comment]
The docs are down currently. I keep getting "502" bad gateway

**Comment by Calvinv99** [comment]
Hi, the docs are down currently. Been getting "502" bad gateway

**Comment by kaualandi** [comment]
Hi, the docs are down currently. Been getting "502" bad gateway
