### ISSUE TITLE
Disable hover effect with selection enabled false

### ISSUE THREAD

**Issue by envision** [apexcharts/apexcharts.js#322]
Is there currently any way to disable mouse hover behaviour with configuration? In this case with a radialBar chart.

I was assuming `selection: enabled: false` would also have disabled hover styles...

**Comment by junedchhipa** [comment]
```javascript
states: {
    hover: {
        filter: {
            type: 'none',
        }
    },
```

**Comment by envision** [comment]
Thank you @junedchhipa, this worked! :)

**Comment by jobayer977** [comment]
tooltip: {
        enabled: false,
}
