### ISSUE TITLE
Hide all series

### ISSUE THREAD

**Issue by PierreArn** [apexcharts/apexcharts.js#3222]
## Summary

Please provide a brief summary of your proposal. Two to three sentences is best here.
I'd like to hide a bunch of series by their seriesName, however, the following technique has a slow execution:
["Series1", "Series2", "Series3"].forEach((series) => chart.hideSeries(series));

## Intended Use Case

I'd like to use a method called hideAllSeries(seriesArray), or an update of the current hideSeries, that takes an array of possible series currently rendered, and hide them programmatically.

**Comment by ordago** [comment]
```javascript
['Series 1', 'Series 2', 'Series 3',]
    .forEach(s => {
        chart.hideSeries(s);
    });
```

https://apexcharts.com/docs/methods/#hideSeries

**Comment by PierreArn** [comment]
That is just what i said, this technique has a slow execution cause the chart update every time this method is called.
So i need a method to not use a loop.

**Comment by ordago** [comment]
Sorry, I don't know how I missed that. 😅 

There were previous issues about this before:

#3062

#1787

So maybe your best chance is to PR it.
