### ISSUE TITLE
Syncing only works when chart types are same

### ISSUE THREAD

**Issue by jptissot** [apexcharts/apexcharts.js#3225]
### Description
First, thanks for this awesome library, we have been using successfully and it works really well and is easy to use.

Issue described below

### Steps to Reproduce

1. Create two charts, one line chart on top and a bar chart below 
2. Set the proper settings for them to be synced (see below)
3. Hover and see the charts not synced

### Expected Behavior
Chart tooltip should sync when hovering on either charts 

### Actual Behavior
Chart tooltip only sync when hovering on the bar chart

### Screenshots

Here is a gif showing the issue: 
![apex_sync_chart_bug](https://user-images.githubusercontent.com/4681586/174662647-cfd7ea8c-bd1c-45d9-bc24-0fd3128f7926.gif)

Here is the repro: 
https://codepen.io/jptissot3/pen/QWQRdXL

**Comment by kngai** [comment]
I too am getting this issue as of version `3.41.0`. Hoping there is an update or fix soon.

**Comment by yoimnik** [comment]
also having this issue @junedchhipa any ideas here?

**Comment by gazzoy** [comment]
having the same issue. Most likely this occurs when we sync different types of charts?

ping @junedchhipa

**Comment by Pymous** [comment]
Using `3.49.1`, I'm having the same issue, here is a few infos about the context it's running in : 
- I'm using the "core/base" library, in a Vue Component
- I have an area chart and a bar chart
- Both have the same labels array, but I also have the issue if I dont specify a `xaxis` object at all
- When I hover the first graph, it works as intended, when I hover the second one, the tooltip from the first point on the first graph is displayed, but not synced

Good luck !

**Comment by junedchhipa** [comment]
For a quick workaround, add this config to your bar chart when syncing with other line charts

```javascript
options = {
  tooltip: {
    shared: true,
    intersect: false
  }
}
```

**Comment by Pymous** [comment]
Thanks a lot for the fix and the quick workaround !
I can confirm that the workaround work in my use-case !
