### ISSUE TITLE
Animate color change

### ISSUE THREAD

**Issue by envision** [apexcharts/apexcharts.js#323]
I need to produce a singular radialBar chart which has a solid color, as picked from a gradient at the percentage value. I would also need to animate that solid color from the gradients' starting color up to the color at the percentage value.

Is it possible to implement this with Apexchart currently?

**Comment by juliorosseti** [comment]
This what you wanted?

https://apexcharts.com/samples/vanilla-js/radialBar/circle-gradient.html

**Comment by envision** [comment]
Thanks @juliorosseti for the example, but the issue with this demo and my requirements is that Apexcharts has an insufficient implementation of gradient configuration.

Gradient config allows only two-stop gradients whereas I'm needing a 0-25-50-75-100 gradient (with 5 colors). Also this demo chart is not color-animated as it's just 'stretching' the gradient.

Currently I've achieved gradient color by percentage value like so:
````
const d3 = Object.assign({}, require('d3-scale')); // Limit only to needed deps
const linearGradient = d3.scaleLinear()
  .domain([0, 25, 50, 75, 100])
  .range(['#FFFFFF', '#AAAAAA', '#999999', '#555555', '#222222']);

const value = 77;
const color = linearGradient(value);

**Comment by junedchhipa** [comment]
Since version 3.4.1, gradient supports multiple color stops.
https://apexcharts.com/docs/options/fill/#colorStops

**Comment by Lunaricku** [comment]
hello, Now i can use colorstops or not (v3.26.3)

**Comment by NikicaCh** [comment]
Can you just switch between 2 colors, avoid too long gradient switch from one to another color ?
