### ISSUE TITLE
bug radar more 6 axes

### ISSUE THREAD

**Issue by robertopascual** [apexcharts/apexcharts.js#324]
## Codepen
series: [
					{
					 name: 'Competencias académicas',
					 data: [30, 25, 35, 70, 75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'Competencias sociales',
					 data: [0, 0, 0, 0, 75, 75, 50, 50, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'autonomía',
					 data: [0, 0, 0, 0, 0, 0, 0, 0, 47, 77, 45, 75, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'apertura',
					 data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 42, 47, 60, 55, 0, 0, 0, 0]
					}, {
					 name: 'hábitos de trabajo',
					 data: [30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 35, 50, 45, 52]
					},
					
					{
					 name: 'Competencias académicas',
					 data: [30, 25, 30, 90, 75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'Competencias sociales',
					 data: [0, 0, 0, 0, 75, 90, 35, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'autonomía',
					 data: [0, 0, 0, 0, 0, 0, 0, 40, 40, 90, 45, 80, 0, 0, 0, 0, 0, 0, 0, 0]
					}, {
					 name: 'apertura',
					 data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 35, 40, 60, 55, 0, 0, 0, 0]
					}, {
					 name: 'hábitos de trabajo',
					 data: [30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 25, 30, 35, 30]
					}
				]
## Explanation

Radar graphics don't  works for more than 6 axes.

i have change on file apexcharts.js line 3616 from

colors: ['#a8a8a8'],
To
colors: ['#a8a8a8']

and it works!!
thanks

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed in the recent commit

**Comment by robertopascual** [comment]
Great!!! You are fantastyc!!!



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Juned Chhipa <notifications@github.com>
Fecha: 13/2/19 18:25 (GMT+01:00)
Para: "apexcharts/apexcharts.js" <apexcharts.js@noreply.github.com>
Cc: robertopascual <robertoph@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [apexcharts/apexcharts.js] bug radar more 6 axes (#324)


Thanks for reporting, fixed in the recent commit
