### ISSUE TITLE
Can't export CSV getting errror "i.split is not a function" when series name is an array

### ISSUE THREAD

**Issue by ordago** [apexcharts/apexcharts.js#3247]
### Steps to Reproduce

1. Open sandbox
2.  click toolbox
3.  click Download CSV

### Expected Behavior

Downloads CSV

### Actual Behavior

Error in console: "i.split is not a function" 

### Screenshots

![image](https://user-images.githubusercontent.com/6376814/177044084-d0683b52-58b8-42f7-8252-d9cf23c45667.png)

### Reproduction Link

https://codesandbox.io/s/bitter-browser-5z3qc8

**Comment by AndreFra96** [comment]
I'm having the same error with this:

https://codepen.io/andreabrioschi/pen/PoRNXKr

**Comment by brianlagunas** [comment]
@ordago Why are you setting the name of the series to an array? It should be a string. The series name is not expecting an array.

@AndreFra96 the name is expecting a string, not a number.

**Comment by ordago** [comment]
@brianlagunas  I remember seeing in the docs somewhere. Using an array for series whose name were too long would place the second item on the array in a new line.

**Comment by brianlagunas** [comment]
@ordago I was unable to find any code that handled the name as an array. If you can find that doc, I would appreciate it. It's possible is was a feature that wasn't implemented fully.

**Comment by ordago** [comment]
hey @brianlagunas, maybe I mixed series names with categories

https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/

**Comment by brianlagunas** [comment]
@ordago yeah, it looks like it. Glad we figured it out.
