### ISSUE TITLE
Click annotations, return Annotation Object

### ISSUE THREAD

**Issue by jchamb** [apexcharts/apexcharts.js#325]
**Is your feature request related to a problem? Please describe.**
I'm looking to reproduce Google analytics charts annotations functionality. Clicking an annotation will open a table underneath for a full comment. I know I can pull the "clicked" annotation svg element from the event, butIi dont really have a way to relate that SVG element to an annotation object. I had thought that I could add a class to the SVG element placing in the id, however I noticed that the markers do not have the option to add a class.

**Describe the solution you'd like**
Independent click method for the annotations that would pass that annotations object to the handler. That way "extra data" could be stored along with the object.

**Describe alternatives you've considered**
Quick dirty solution would be to allow classes to be added the markers like you can the labels. so we could at least pull the class name from the elem to match objects.

**Comment by junedchhipa** [comment]
Added cssClass for now. Will think later if click event handlers need to be attached to such elements.
Thanks for the PR.

**Comment by thijscrombeen** [comment]
@jchamb

Do you have an example on how to get the annotation based on the click event?

Thanks
