### ISSUE TITLE
Set the position of tooltips

### ISSUE THREAD

**Issue by alon-loris** [apexcharts/apexcharts.js#3257]
Currently the tooltip's position is determined automatically and can't be controlled through configuration. 
For example in the following screenshot the tooltip is positioned to the top-left of the marker.
![image](https://user-images.githubusercontent.com/71207393/178022077-983408d7-2992-472e-9e47-21d375db0fed.png)

If I want the tooltip to be centered above the marker like in the screenshot below this is not possible.
![image](https://user-images.githubusercontent.com/71207393/178022415-d4c7e38c-9055-425e-adb0-fbaead9d2de0.png)

Since the tooltip is rendered as html it would have been possible at least to change the position with css, but since the automatic positioning is inconsistent (sometimes to the left of the marker, sometimes to the right etc) It's not possible to give the element css that will handle all cases.

I suggest adding the ability to set the tooltip's position as centered relative to the marker in a selected direction (top, bottom, left, right)

**Comment by caocuong2404** [comment]
Same issue with this case
