### ISSUE TITLE
areachart not showing on VMware Airwatch Browser

### ISSUE THREAD

**Issue by Txxkirsch** [apexcharts/apexcharts.js#3259]
Hey everyone,

we are using the **Airwatch Browser by VMware** on our corporate IPhones and I noticed that apexcharts isn't showing anything.
It also doesn't throw any kind of error.
The given <div> just stays blank and has dimensions of 0 by 0 pixels.
Every other browser I tried works fine.

I know the description lacks of information but I can't get any errormessages or similar.
A screenshot of just blank space would be useless I guess.

The HTTP_USER_AGENT says following (if this helps anything):
**Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Version/15.5 Safari/605.1.15 (AirWatch Browser v22.07)**

```

<div id="apexchart" style="/* width:500px; height:300px; */"></div>
var options = {
		chart: {
			type: 'area'
		},
		series: [{
			name: 'sales',
			data: [
				[1990, 5],
				[1991, 15],
				[1992, 5],
				[1993, 4],
				[1994, 15],
				[1995, 1],
				[1996, 10],
			]
		}],
	}

	var chart = new ApexCharts(document.querySelector("#apexchart"), options);
	chart.render();
```

**Comment by brianlagunas** [comment]
Without any error messages or the inability to reproduce this issue on a dev machine, we will not be able to help here. If you can create a reproduction that can be debugged locally, then feel free to continue the conversation.
