### ISSUE TITLE
Cutting of labels with high and low values

### ISSUE THREAD

**Issue by timclausen** [apexcharts/apexcharts.js#327]
# Codepen
https://codepen.io/difedk/pen/wNYpVw

# Explanation

The first graph cuts of the percentage label
The second last group: negative bar labels lays over the bottom year labels.

I've tried all sort of configurations to avoid this.

# Question
Is this a bug or am I overseeing something?

**Comment by junedchhipa** [comment]
The offsets are causing issues. So, I have allowed the `yaxis.min` and `yaxis.max` to accept a function which you can modify to give some padding.

Eg.,
```javascript
     yaxis: {
        show: false,
        max: function(value) {
            return value * 1.25
        }, 
        min: function(value) {
            return value * 2.5
        }
      },
```
which will produce the following result for your same example
![screen shot 2019-02-16 at 7 28 25 pm](https://user-images.githubusercontent.com/17950663/52900835-58678680-3221-11e9-9446-70089d3efd3b.png)

The modified yaxis.min/max will be available in v3.3.2 (will be released tomorrow)

**Comment by junedchhipa** [comment]
Released 3.4.0

**Comment by timclausen** [comment]
Thanks.. Could you help me with the issue in the right side as well? Bars overlay the line-label. Cant see how I could solve this with available parameters.

**Comment by junedchhipa** [comment]
You can try offsetting the y annotation with this property - https://apexcharts.com/docs/options/annotations/#ylabelOffsetY

```javascript
 annotations: {
      position: 'front' ,
      yaxis: [{
          y: 0,
          y2: null,
          label: {
              offsetX: 0,
              offsetY: 0,
          }
      }]
}
```
