### ISSUE TITLE
JS Import Failed

### ISSUE THREAD

**Issue by psambit9791** [apexcharts/apexcharts.js#328]
Importing apexchart from npm using https://cdn.jsdelivr.net/npm/apexcharts yield error:
SyntaxError: "" literal not terminated before end of script

- Previously was working (tested on 5th February)
- Error shows up
![error](https://user-images.githubusercontent.com/25612092/52855331-fe7b9980-3118-11e9-8464-165a20538c61.png)

- As far as I have seen the source code, it ends very abruptly like this:
("apexcharts-legend-marker");if("hea

**Comment by junedchhipa** [comment]
Please try the latest verion https://cdn.jsdelivr.net/npm/apexcharts@latest
