### ISSUE TITLE
Apex Charts Website Down

### ISSUE THREAD

**Issue by prodkt** [apexcharts/apexcharts.js#3305]
![image](https://user-images.githubusercontent.com/101760605/183579237-e63e09f4-d54e-44d3-b1a1-70fed0a04fab.png)

### Steps to Reproduce

1. 
2. 
3.

**Comment by brianlagunas** [comment]
Duplicate

**Comment by gagwithgaffer** [comment]
A more important question, what is happening with the whole site of which most of it is also down, when might we expect to see it back up again? thx
