### ISSUE TITLE
Series with hash char(#) object name breaks CSV export

### ISSUE THREAD

**Issue by iampluque** [apexcharts/apexcharts.js#3310]
Hi guys, 

When I setup series where objects names contains hash char(#), CSV exports are exporting up to the faulting column name.

![image](https://user-images.githubusercontent.com/48191373/184141489-639a7e6e-d7b6-4dda-9130-9e6246baf2d8.png)

**Comment by iampluque** [comment]
Will be fix in next release ?

**Comment by brianlagunas** [comment]
No, it was closed because you did not follow the Issue template directions.

**Comment by iampluque** [comment]
haha ok!
