### ISSUE TITLE
Pie/Donut chart, unable to disable clicking on slices

### ISSUE THREAD

**Issue by vesper8** [apexcharts/apexcharts.js#3314]
I want to disable all interactivity with pie/donut charts. I have tried

```

        chartOptions: {
          chart: {
            type: 'pie',

            selection: {
              enabled: false,
            },
            animations: {
              enabled: false,
            },
            zoom: {
              enabled: false,
            },
          },
```

Can't figure out how to disable clicking/all interactivity.. none of the above seem to have any effect.

Thanks

**Comment by brianlagunas** [comment]
Please ask questions in discussions. If you feel you have found a bug you must provide all required information.

**Comment by vesper8** [comment]
Wrapped my chart with a `<div class="pointer-events-none"></div>` and that solved the problem for me.
