### ISSUE TITLE
Markers overflow on yaxis when zoom in with area/line chart

### ISSUE THREAD

**Issue by RCelty** [apexcharts/apexcharts.js#3320]
### Description
Markers always overflow out of the yaxis whenever I set the min option for the xaxis or zoom in.

### Steps to Reproduce

1. Create apex chart area/line type, xaxis type 'datetime', show marker.
2. Zoom in the middle or the end of the chart.

### Expected Behavior
Markers in front of the zooming area do not overflow.

### Actual Behavior
Markers in front of the zooming area overflow.

### Screenshots
![image](https://user-images.githubusercontent.com/71772102/185594872-1c77ca0e-21bf-4f56-b870-d791b7fcca45.png)
![image](https://user-images.githubusercontent.com/71772102/185595127-11bbd1bd-5135-41e0-a749-35c1ac01d2f1.png)

### Reproduction Link
I can't give you the data series because it is private, but here is my chart option:
codepen: https://codepen.io/RCelty/pen/LYdqGEb

**Comment by brianlagunas** [comment]
Your sample does not reproduce the issue you are reporting. Please update the code pen to reproduce the issue or this will be closed.

**Comment by RCelty** [comment]
I have updated codepen, please check it https://codepen.io/RCelty/pen/LYdqGEb

**Comment by RCelty** [comment]
Do you have any plan on fixxing this issue yet?

**Comment by karolskolasinski** [comment]
when you add an axis border on the y-axis, then the markers are outside that axis:
![image](https://github.com/user-attachments/assets/6baecd6a-f96f-4f92-ba4c-b1dcf70d1ccb)

what's more, when zoomed in, the entire graph goes off the axis:
![image](https://github.com/user-attachments/assets/48a369ec-2b66-41e5-8a8f-971b21b416e9)

data for chart from official docs (https://apexcharts.com/javascript-chart-demos/area-charts/spline/)
Just try to add 
```
        yaxis: {
          axisBorder: {
            show: true,
            color: "black",
          },
        },
```
to example chart on official docs site. 
Please fix this error, it is crucial.

**Comment by karolskolasinski** [comment]
@brianlagunas @joadan
