### ISSUE TITLE
Labels for series data

### ISSUE THREAD

**Issue by xHyroM** [apexcharts/apexcharts.js#3323]
## Summary

It would be good if I could set a name (label) for each entry, so it would show the name instead of the number.

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

```js
series: [
    {
        data: [
            {
                x: "category"
                y: 150,
                label: "150.00"
            }
        ]
    }
]
```

## Intended Use Case

I want to use this in my benchmark where I want to see formatted numbers in the chart.

**Comment by brianlagunas** [comment]
You can format your tooltips: https://apexcharts.com/docs/tooltip/

**Comment by xHyroM** [comment]
I don't want format it, I want statically set it.
