### ISSUE TITLE
Firefox, mouse over tooltip spams console with CSS errors: Opacity & Font Weight

### ISSUE THREAD

**Issue by mdennett** [apexcharts/apexcharts.js#3324]
### Steps to Reproduce

1. Use Firefox browser (Chrome does not appear to have this issue)
2. Mouse over tool tip
3. Observe console errors:

- Error in parsing value for ‘font-weight’.  Declaration dropped.
- Error in parsing value for ‘opacity’.  Declaration dropped.

EDIT: Trying firefox browser on another machine DOES NOT produce this error.

Problematic machine / browser is running Firefox 103.0.2 (64-bit) - Windows.

Error is still produced with all extensions disabled.

### Expected Behavior
This does not occur.

### Actual Behavior
Per screenshot below, mouse over tooltip spams console with CSS errors: Opacity & Font Weight.

### Screenshots

![image](https://user-images.githubusercontent.com/9095528/185878659-d5a7000b-f882-48f7-a6cc-093999bee023.png)

### Reproduction Link

https://964b544d.mortagecalc.pages.dev/ - Apex-react package.

**Comment by brianlagunas** [comment]
Please provide a codepen that shows all the code needed to reproduce this issue or this will be closed.

**Comment by stayce** [comment]
This seems to be old, but I also have the issue with thousands of these logging in firefox v129

**Comment by junedchhipa** [comment]
No codepen provided.
