### ISSUE TITLE
[Question] Range slider for timeseries?

### ISSUE THREAD

**Issue by capslockoff** [apexcharts/apexcharts.js#333]
I noticed, there is a range slider in the timeseries interactivity example in the main README.md page. How do I enable that? I don't see it in the codepen example?

![image](https://user-images.githubusercontent.com/47658699/52888218-c0d63b00-312f-11e9-9508-cec72af3cac3.png)

**Comment by junedchhipa** [comment]
The scroller was available prior v2.0 but was removed due to memory leaks and other bugs. I decided to remove it until I come up with a better version of it.
Maybe it will come again in the future.

**Comment by AntoinedeChassey** [comment]
Hey @junedchhipa 
Any update on this? Would be nice to have this feature!
Thx
