### ISSUE TITLE
attribute d: Expected number, "M NaN NaN A NaN Na…

### ISSUE THREAD

**Issue by jsosavega** [apexcharts/apexcharts.js#3331]
### Hello everyone, we are currently developing a platform that makes use of its apexcharts component, which is a single-page application and we use requirejs. However, since we cannot provide stability through amd, we opted for the use of import through the tag. In a global form. When loading the dependencies and generating the graphs, the processor works correctly, however when we change routes to other micro views it sends us a series of errors in the console indicating the following message

apexcharts:6 Error: <path> attribute d: Expected number, "M NaN NaN A NaN Na…".
attr @ apexcharts:6
attr @ apexcharts:6
value @ apexcharts:6
value @ apexcharts:6
value @ apexcharts:6
value @ apexcharts:6
value @ apexcharts:6
value @ apexcharts:14
(anonymous) @ apexcharts:6
(anonymous) @ apexcharts:14
value @ apexcharts:14
(anonymous) @ apexcharts:14
setTimeout (async)
value @ apexcharts:14
value @ apexcharts:14
(anonymous) @ apexcharts:14

This error persists in each change of view since the object of the graphics is no longer in the instance that was invoked.
![Captura de Pantalla 2022-08-24 a la(s) 18 49 07](https://user-images.githubusercontent.com/5216022/186543553-b22112bb-84d2-4a51-97f2-0f32ad39871b.png)

![Captura de Pantalla 2022-08-24 a la(s) 18 49 38](https://user-images.githubusercontent.com/5216022/186543608-1bb3426f-09a0-4952-8dd7-792b084200d8.png)

Any idea what is causing the error?

`var options = {
				series: data.series,
				chart: {
					height: 350,
					type: 'line',
					toolbar: {
						show: false,
					}
				},
				dataLabels: {
					enabled: false
				},
				stroke: {
					width: 4,
					curve: 'smooth',
					dashArray: 0
				},
				legend: {
					fontFamily: 'Lufga-Regular,sans-serif',
					tooltipHoverFormatter: function(val, opts) {
						return val;
					}
				},
				markers: {
					size: 0,
					fontFamily: 'Lufga-Regular,sans-serif',
					hover: {
						sizeOffset: 6
					}
				},
				xaxis: {
					fontFamily: 'Lufga-Regular,sans-serif',
					categories: data.categories
				},
				tooltip: {
				y:{
					title: {
						formatter: function (val) {
							return val
						}
					}
					}
				},
				grid: {
					borderColor: '#f1f1f1',
				}
			};
		
			let lineChart=document.getElementById(`${data.idChart}`)

			if(lineChart){
				var chart = new ApexCharts(document.querySelector('#${data.idChart}'), options);
				chart.render();
			}`

**Comment by MG-Sky** [comment]
having now the same issue 130k errors in the browser - and site is not responsive
apexcharts-card.js?hacstag=331701152201:1 Error: <path> attribute d: Expected number, "M 0 NaN".

**Comment by rock-climber** [comment]
Add route listener and use v-if
