### ISSUE TITLE
Add option to only show first and last x axis

### ISSUE THREAD

**Issue by heychazza** [apexcharts/apexcharts.js#3339]
## Summary

It would be awesome if we could enable an option to only show the first and last value on the X-axis. However, this would still show the x axis values on hover, but would prevent clutter.

## API Changes

```js
{
  xaxis: {
     showType: 'boundary' // defaults to 'all', allows for 'even', 'odd' etc
  }
}
```

## Intended Use Case

I use ApexCharts heavily in my analytics SaaS ([Analyse](https://analyse.net)) and I often have many data points. I'd like to be able to only show the first and last, but still show them on hover.

Current Dash:
<img width="518" alt="CleanShot 2022-08-27 at 3 32 06@2x" src="https://user-images.githubusercontent.com/47271716/187034809-caf9526b-24c5-408c-a29f-d42fe828d09d.png">

**Comment by heychazza** [comment]
I'd also be happy to donate (GitHub Sponsor) in return for adding this.

**Comment by AKhaled-peakbeing** [comment]
I implemented this feature by leveraging the overwriteCategories property in the xaxis configuration. Here's how:

Passed all x-axis values (e.g., ['day1', 'day2', 'day3', ...]) into the categories array.
Used the overwriteCategories property to specify only the first and last categories (categories[0] and categories[categories.length - 1]).
This ensures that only the first and last labels are displayed on the x-axis, while still showing all labels in the tooltip on hover.
Here’s the relevant code snippet:
`
if (chartProps.showMarginsOnly) {
  chartOptions["xaxis"]["overwriteCategories"] = [
    chartProps.xaxis[0],
    chartProps.xaxis[chartProps.xaxis.length - 1],
  ];
}
`
This approach effectively reduces clutter on the x-axis while maintaining interactivity.
