### ISSUE TITLE
dataPointSelection not working in Area Chart

### ISSUE THREAD

**Issue by edbasti** [apexcharts/apexcharts.js#3347]
### Steps to Reproduce

This code does not seem to work when using Area Chart:

chart: {
      events: {
        dataPointSelection: (event, chartContext, config) => {
          console.log(config);
          }
        },
      },
    },

**Comment by Qaiser45** [comment]
Currently, the dataPoint-Selection event works for line charts where the marker size is more than 0 and tooltip.intersect = true

So, this configuration would work for capturing the event

var options = {
  chart: {
      height: 380,
      type: 'line',
      events: {
          dataPointSelection: function(e, chart, opts) {
              console.log(e, opts)
          },
      },
  },
  series: [{
      name: "Desktops",
      data: [30, 41, 35, 51, 49, 62, 69, 91, 126]
  }],
  grid: {
      row: {
          colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
          opacity: 0.5
      },
  },
  xaxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
  },
  tooltip: {
      intersect: true,
      shared: false
  },
  markers: {
    size: 6,
  }
}
