### ISSUE TITLE
Expose isSeriesHidden to check if a series is hidden

### ISSUE THREAD

**Issue by benne** [apexcharts/apexcharts.js#3350]
## Summary

Like the methods `showSeries` and `hideSeries`, it would be nice to have a method to read out the hidden state of a series.
As of now the only possible (official) way I can find is to use `toggleSeries`, read the return value, and then toggle the series again to get it back to the original state. This is not performant at all for even smaller charts.

## API Changes

There is an internal method, [isSeriesHidden](https://github.com/apexcharts/apexcharts.js/blob/ff248b4a38ee21e993e38ef9a3e1318e59a6ea32/src/modules/Series.js#L30) on the `Series` object. Exposure of this functionality on the same level as `showSeries`, `hideSeries`, `toggleSeries` etc. would help determine the hidden state of the object, if it is shown or not, without either duplicating internal code in the local project or using `toggleSeries`.

The signature could be something like:

`static bool isSeriesHidden(seriesName)`

## Intended Use Case

Currently we intercept the click on the legend for showing/hiding data series through the `legendClick` event, to save the current show/hide settings for the user. We have the series index but when determining if the series has been switched on or off, we toggle hidden the state of the series to determine what has happened. This introduces a noticeable lag and race conditions when the user triggers the `legendClick` event multiple times in succession.

With the introduction of a `isSeriesHidden` method, that exposes the internal functionality to check for if a series is hidden, we can just peek at the answer instead of toggling everything on and off all the time.

**Comment by cythrawll** [comment]
Just ran across this today as I need to figure out to toggle annotations if associated series are hidden by user.

**Comment by benne** [comment]
I had to give up on the toggle-method to read the hidden state of a series - it was simply too slow, which frustrates the user. So, I just copied the internal logic from the internal method `isSeriesHidden` for now. It is not pretty, and it will probably break at some point + it is kind of finickily to work with.

I would much more prefer an actual implmentation.

**Comment by moonclimber1** [comment]
for anyone interested how to implement the workaround, here is the code:

Global Array representing the state of for example 3 series
`let seriesShown = [true, true, true]`  

In chart.events add  
`legendClick: (chartContext, seriesIndex, config) => {seriesShown[seriesIndex] = ! seriesShown[seriesIndex]}`

**Comment by trandaison** [comment]
You can check if a serie is hidden or not in `chart.w.globals.collapsedSeries`, identify the serie by its `index`.
