### ISSUE TITLE
IE 11 y-axis not scaling correctly

### ISSUE THREAD

**Issue by travisbotello** [apexcharts/apexcharts.js#336]
Demo: https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/

IE 11:
![screenshot 2019-02-20 11 47 28](https://user-images.githubusercontent.com/1157380/53086449-6ceb9d80-3505-11e9-9809-7b0fe4eed193.png)

Chrome/Firefox:
![screenshot 2019-02-20 11 47 34](https://user-images.githubusercontent.com/1157380/53086464-7543d880-3505-11e9-83f3-cca9bb3ffc2f.png)

## Explanation

- What is the behavior you expect?
y-axis should be scaled automatically, or at least show same range in cross browsers

- What is happening instead?
In IE 11 y-axis min value is not correctly calculated and always starting at 0

- What error message are you getting?
None

**Comment by junedchhipa** [comment]
Thanks for reporting, I will soon look into it.

**Comment by junedchhipa** [comment]
Fixed in https://github.com/apexcharts/apexcharts.js/commit/f5aedeea3c47827326e2024669ec85db2e278611
