### ISSUE TITLE
Empty csv file when first series of multiple series chart is not visibile on chart.

### ISSUE THREAD

**Issue by w4ller** [apexcharts/apexcharts.js#3365]
### Description

Deselecting first series name of multiple series chart and trying downloading csv file will produce a csv file with only columns names.

### Steps to Reproduce

1. Deselect first series from legend on a chart with multiple series displayed
2. Navigate to "download CSV" and click it
3. Open csv file downloaded.
4. The file will only have columns name with no data of any series displayed in the chart

### Expected Behavior
Downloading csv file should include all data of visibile series on chart.

### Actual Behavior
When first series is not visibile on chart cause we deselected it from legend, downloading csv file will have only columns name and no data will be present.

### Reproduction Link
https://codepen.io/luca-tognazzi/pen/bGMdvzv

**Comment by junedchhipa** [comment]
fixed by #3376
