### ISSUE TITLE
"Error establishing a database connection" error

### ISSUE THREAD

**Issue by falbech** [apexcharts/apexcharts.js#3378]
### Description

Sometimes some site URLs are returning an "Error establishing a database connection" error. 
This issue is not tied only to the https://apexcharts.com/docs/installation/ url, but with any of the links present in the documentation.

### Screenshots

![image](https://user-images.githubusercontent.com/5686789/189674835-8906127d-22fb-4d24-a989-ab4500048982.png)

### Reproduction Link

https://apexcharts.com/docs/installation/

**Comment by brianlagunas** [comment]
Duplicate
