### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by anesboz** [apexcharts/apexcharts.js#3380]
### Steps to Reproduce

1. Acess to [the official website of ApexCharts](https://apexcharts.com/react-chart-demos/pie-charts/monochrome-pie)

### Expected Behavior
See and consulting the website
### Actual Behavior
Error message :  "Error establishing a database connection" <br/> 
This error occurs many times a day, but not allways

**Comment by brianlagunas** [comment]
Duplicate
