### ISSUE TITLE
Document Page is Down

### ISSUE THREAD

**Issue by kmkhami** [apexcharts/apexcharts.js#3385]
### Description

The [document page](https://apexcharts.com/docs/creating-first-javascript-chart/#) is down currently. 

### Steps to Reproduce

1. Go to https://apexcharts.com/docs/
2. See you cannot load it
3. Realize that the docs page is down

### Expected Behavior

Be able to access the documentation 

### Actual Behavior

Timeout when attempting to access doc page. 

### Screenshots

![image](https://user-images.githubusercontent.com/15804464/191065767-dd416996-51cc-4dd3-b551-9416e9e48eba.png)

**Comment by brianlagunas** [comment]
Not for me it's not

**Comment by kmkhami** [comment]
> Not for me it's not

Seems to be back up now.

**Comment by kmkhami** [comment]
> Not for me it's not

It is down again.

**Comment by kmkhami** [comment]
Up again. Why is this so inconsistent @brianlagunas ?

**Comment by guillaumerxl** [comment]
Same issue for me in Firefox 104.0.2 since yesterday. The error is SSL_ERROR_NO_CYPHER_OVERLAP
