### ISSUE TITLE
Chart - dark mode & light mode. background-color doesn't change.

### ISSUE THREAD

**Issue by devfrankkim** [apexcharts/apexcharts.js#3387]
### Description

*background color doesn't change.*
`style="background: rgb(66, 66, 66);` still stays on the light mode.
 
```js
<div id="apexchartszr2atjrhh" class="apexcharts-canvas apexchartszr2atjrhh apexcharts-theme-light" >
    <svg id="SvgjsSvg2262" width="348" height="350" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink class="apexcharts-svg apexcharts-zoomable" xmlns:data="ApexChartsNS" transform="translate(0, 0)" style="background: rgb(66, 66, 66);" />
</div>
```

### Steps to Reproduce

    1. start with dark mode.
    2. toggle the button.
    3. background-color doesn't change.
    4. start with light mode
    6. toggle the button
    7. background-color doesn't change. 

    * background-color depends on starting point of dark mode state
    * It is not consistent.
    * Especially if the state is saved on local storage, it would look different every time user comes back to the app.
   

### Expected Behavior

`style="background: rgb(66, 66, 66);` should not appear on the light mode. 

```js
  theme: {
          mode: isDarkMode ? "dark" : "light",
        },
  chart: {
          type: "area",
          height: 350,
  },
    stroke: {
      curve: "smooth",
    },
```

### Actual Behavior
`style="background: rgb(66, 66, 66);` still stays on the light mode.
*background color doesn't change.*

### Screenshots

<img width="1012" alt="lightmode" src="https://user-images.githubusercontent.com/49273582/191658802-600f96f2-bc03-40f2-9475-a77b35e20726.png">

### Reproduction Link

[Codepen link](https://codesandbox.io/s/react-apex-chart-using-hooks-forked-jyiuvs?file=/src/MyChartComponent.js)

**Comment by efitzkiwi** [comment]
Temporary CSS class to place on the parent element:
```
.apexcharts-canvas > svg {
    background-color: transparent !important;
}
```

**Comment by juanvve** [comment]
Hello, it is a solution??
I have this problem with my global state and does not recognize the changes

**Comment by junedchhipa** [comment]
[Commit](https://github.com/apexcharts/apexcharts.js/commit/9936ffc3b038d064b63bbc544c4869ad005a9c1f) fixes it
