### ISSUE TITLE
Destroy method is not working as expected

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [apexcharts/apexcharts.js#3393]
### Description

I don't know why, but this lib create `<svg />` and insert it into end of body tag when we call `chart.render()`  
That's OK!  
But when i call `chart.destroy()` this svg never remove from DOM !!  

### Steps to Reproduce

1. Render chart
2. Try to destroy it
3. DOM will not clear as we expected

### Expected Behavior

We must have a clean DOM after calling `chart.destroy()`

### Actual Behavior

`<svg />` will remain in `<body />` even after calling `chart.destroy()`

### Reproduction Link

https://cdpn.io/SaeedPooyanfar/fullpage/LYmQqJV
https://codepen.io/SaeedPooyanfar/pen/LYmQqJV

Click on `ApexCharts#destroy` button and check DOM

**Comment by AlexParton** [comment]
Hello, I see the <svg> being removed on button click as expected. I used your codepen link.

**Comment by brianlagunas** [comment]
I also cannot reproduce using your codepen link. It works as expected.

**Comment by Saeed-Pooyanfar** [comment]
@AlexParton 
@brianlagunas 
The chart itself yes
But look at the latest tag in body
I see a SVG element there that created by the lib.

**Comment by rodpatulski** [comment]
This is causing problem running unit tests (with jest) https://github.com/apexcharts/react-apexcharts/issues/427
