### ISSUE TITLE
Pointing cursor on wanted markers not accurate if have a lot of data

### ISSUE THREAD

**Issue by Cristian9828** [apexcharts/apexcharts.js#3406]
"apexcharts": "^3.35.5"

### Steps to Reproduce

1. Create an area chart with apexchart with 30 or more labels and series data.
2. Try to point a specific marker with the cursor.
3. See that it isn't accurate. You'll have to point on millimeters before to see the tooltip you want.

### Expected Behavior
Point on exact marker to see the tooltip I want.

### Screenshots
The red "x" represents where I'm pointing with the cursor.
![apexchart](https://user-images.githubusercontent.com/51407503/194237705-2b7c0906-edff-4090-aada-48582facdfa3.png)

**Comment by brianlagunas** [comment]
No repro provided
