### ISSUE TITLE
Stroke color array on bar chart

### ISSUE THREAD

**Issue by disagol** [apexcharts/apexcharts.js#341]
When building a bar chart with distributed enabled the stroke color array seems to be omitted. I really don't know if this is expected, but a combination of color and stroke array worked in a pie chart. Here https://codepen.io/anon/pen/vbwJmw just the first color defined in the stroke array is used.

Thanks for the wonderful lib.

**Comment by junedchhipa** [comment]
This is not the expected behavior. For distributed bar charts, the stroke color array should be different for each bar.
Thanks for reporting.

**Comment by disagol** [comment]
Anytime.
