### ISSUE TITLE
Add customisable donut labels in donut chart.

### ISSUE THREAD

**Issue by Kay-Yuan** [apexcharts/apexcharts.js#3414]
## Summary

Could we add more customise for donut labels? Currently, it seems only has one format that one row for string and one row for value. Is that possible to offer a way just display the string as a title? 

## API Changes

```ts
 options = {
    plotOptions: {
      pie: {
        donut: {
          labels: {
            show: true,
            name: {
              ...
            },
            value: {
              ...
            }
          }
        }
      }
    }
  }
```
or 
```ts
options = {
  title: {
    ...
}
}
```
## Intended Use Case

I am using Donut Chart in the Angular project. Is there any way to the custom Donut labels in the inner circle? I found it can be set for displaying a selected piece of chart or Total. Both of them are displayed in below red box. (Upper line for string, bottom for number)
<img width="563" alt="image" src="https://user-images.githubusercontent.com/34876651/194805622-275aec46-59e4-432a-8f74-587433374af1.png">
I need a single-string label like this.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/34876651/194805847-07fa0fd0-d15b-46cb-84cd-0e984c0daa19.png">
A modified style gets this in the browser. But we can not customise the SVG <g> element directly in CSS.

**Comment by YusufFauziyan** [comment]
```
options = {
    plotOptions: {
      pie: {
        donut: {
          labels: {
            show: `true,`
            **total: {
                     show: true,
                     label: "January",
             }**
            name: {
              ...
            },
            value: {
              ...
            }
          }
        }
      }
    }
  }
```


Add total and label

**Comment by arimariojesus** [comment]
Is there a way to add html to label or value?

**Comment by varunumraliya** [comment]
![Image](https://github.com/user-attachments/assets/4d86115f-4b64-452c-8437-167e21beaeaa)

How can i fix this issue of overlapping data labels?
