### ISSUE TITLE
RangeBar not grouping when horizontal: false

### ISSUE THREAD

**Issue by Joshua-White-TRP** [apexcharts/apexcharts.js#3419]
### Description
RangeBar charts with grouping and overlap options set to true work display as expected when horizontal is set to true. The grouping and overlap functionality is not maintained if you set horizontal to false.

### Steps to Reproduce
1. Create a rangeBar chart
2. Provide series in the format [{ name, data: [{ x, y: []}, ...] }, ...]
3. Set rangeBarGroupRows: true and rangeBarOverlap: true
4. Set horizontal: false

### Expected Behavior
When rangeBarGroupRows and rangeBarOverlap are set to true, the bars should be grouped regardless of horizontal being true or false.

### Actual Behavior
The rangeBar chart only handles the grouping correctly if horizontal is set to true. It doesn't group the bars inline when horizontal is set to false.

### Screenshots
horizontal: true
![image](https://user-images.githubusercontent.com/56763774/195042846-0b4fbfa3-91e5-42ed-8352-1ab24b8f5153.png)

horizontal: false
![image](https://user-images.githubusercontent.com/56763774/195042975-fcb96e52-6236-4296-8e54-25b55915d2fe.png)

### Reproduction Link
Edit plotOptions.bar.horizontal between false and true values to see the difference:
https://codepen.io/TRP_Kazel/pen/zYjMQzY

**Comment by jimbol** [comment]
Would really like this fixed, its exactly what I'm looking for

**Comment by junedchhipa** [comment]
This is fixed (as tested on version 3.42.0)

**Comment by KristenGlover** [comment]
thank you @junedchhipa - much appreciated
