### ISSUE TITLE
Annotations positioning doesn't work on logarithmic axis.

### ISSUE THREAD

**Issue by Finn-but** [apexcharts/apexcharts.js#3421]
When using a logarithmic y-axis annotations get positioned at the bottom regardless of their 'y' value.

Before setting to logarithmic:
![image](https://user-images.githubusercontent.com/115542802/195297948-f3eed6a3-58b3-4e95-9dcb-d70932418a2c.png)

After:
![image](https://user-images.githubusercontent.com/115542802/195297576-20c4663d-4566-455d-8888-cad657989550.png)

It can be replicated in the annotations demo by simply adding the following:

```
yaxis: {
    logarithmic: true,
    forceNiceScale: true
  }
```

https://codepen.io/apexcharts/pen/GXOJXQ

**Comment by denxorz** [comment]
Another example: https://codesandbox.io/s/vue-basic-example-forked-4w9puu?file=/src/components/Chart.component.vue
Setting `logarithmic` back to `false` will move the yaxis-annotation back up again from zero. Also downgrading the package to 3.19.3 works.

**Comment by hbenkhay** [comment]
I am having the same issue, the y-annotation line is always at y=0 for a logarithmic scale. I downgraded to older versions, but it didn't work

**Comment by joshribakoff-sm** [comment]
Same issue, cloned one of your code sandbox and replicated it - it sometimes works, but as you edit the values to get larger it replicates the bug - https://codepen.io/joshribakoff/pen/dyqJvNx

**Comment by Muuzzyy** [comment]
Got the same issue, does anyone has a solution to provide ? 
Thank you,
