### ISSUE TITLE
Multi-series chart no longer accepts an array of fill types in bar/column charts 

### ISSUE THREAD

**Issue by siebird** [apexcharts/apexcharts.js#3432]
### Description

When using a multi-series chart its possible to pass in an [array of fill types](https://apexcharts.com/docs/options/fill/) `type: ['solid','pattern','gradient']` to use a combination of fills. This was working in previous versions before `3.36.0`

### Expected Behavior

The first series should be a `solid` color, the second series should be a `slantedLines` fill, and the third should be a `gradient` fill

Use this codepen for an example. Change versions at the top of the JS panel to `3.35.0` for the bug-free example: https://codepen.io/siebird/pen/xxjeQxN

**Comment by bchellingworth** [comment]
This is also the case for colors: []

**Comment by zmutawy** [comment]
@siebird is there an update on this? its been almost a year

**Comment by Blackglade** [comment]
Experiencing the same issue!

**Comment by leoosa** [comment]
any updates ?

**Comment by jrp255** [comment]
Hello, any update on this issue? I am using v3.41.0 and still seeing it. Thanks!

**Comment by antonioandrade** [comment]
Unfortunately this bug [no support for array of fill types] is still present on v3.45.2 for area series.
