### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by nicolasSoares** [apexcharts/apexcharts.js#3437]
### Steps to Reproduce

1. Go to documentation https://apexcharts.com/docs/installation/
2. Try to click on anything to see the rest of the docs, open an other page or deploy dropdowns
3. Nothing happens

### Expected Behavior
We should be able to always access your documentation easily even when you are not capable of keeping your website working,
Could you not make a static version hosted on your github page ?

### Actual Behavior
Nothing is happening

**Comment by sanzhar1310** [comment]
![image](https://user-images.githubusercontent.com/33378911/196648854-1f5fe423-f3a0-4970-9109-17abe88b7468.png)

**Comment by sanzhar1310** [comment]
![image](https://user-images.githubusercontent.com/33378911/196649007-e6919892-2cf4-4640-a744-0a44ebed4dd6.png)

**Comment by pfinkbeiner** [comment]
Any known source of documentation duplicate?

**Comment by brianlagunas** [comment]
The site is back up
