### ISSUE TITLE
Show a tooltip on an annotation

### ISSUE THREAD

**Issue by sacalata** [apexcharts/apexcharts.js#3438]
## Summary

Possibility to display a tooltip when hovering an annotation.

## API Changes

Add 'tooltip' property to the annotations

## Intended Use Case

Display extra information related to the annotation when hovering it.

**Comment by Ankcorn** [comment]
Hey, this would be great to have? Would it be okay to re-open this feature request!

**Comment by sumitaney** [comment]
Can anyone update on this?
