### ISSUE TITLE
Error in documentation!

### ISSUE THREAD

**Issue by CaioSerpaUTFPR** [apexcharts/apexcharts.js#3450]
### Description

In documentation i found this on **max** property description:
The function accepts an argument which by default is the **smallest** value in the y-axis. **function(max) { return max }**

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

by default is the **biggest** value in...

### Actual Behavior
by default is the **smallest** value in...

**Comment by brianlagunas** [comment]
You provided no actionable information

**Comment by CaioSerpaUTFPR** [comment]
Do I need to correct the documentation? how do I do it ? @brianlagunas

**Comment by CaioSerpaUTFPR** [comment]
@brianlagunas here we have

**Comment by junedchhipa** [comment]
Fixed, thank you for reporting.
