### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by CaioSerpaUTFPR** [apexcharts/apexcharts.js#3451]
### Description

In documentation, on property :  plotOptions ->bar ->  datalabels : {}
   is missing **total** property, this is a new property of last version, i guess =)

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
property total inside plotOptions ->bar ->  datalabels : {}
### Actual Behavior
is missing property total inside plotOptions ->bar ->  datalabels : {}

**Comment by brianlagunas** [comment]
Please provide a link to the doc topic.

Also, please provide a code snippet of what you think should be added to the docs

**Comment by CaioSerpaUTFPR** [comment]
@brianlagunas =)
Here we dont have "Total" property like i told in description!

[https://apexcharts.com/docs/options/plotoptions/bar/](url)

![image](https://user-images.githubusercontent.com/52009630/198067428-76fd1318-cc55-459e-9b26-4de7c67d9feb.png)

But i found this property in another example out for docs and i'm using this!!
my exemple using:

![image](https://user-images.githubusercontent.com/52009630/198068805-44d9e3f4-38fc-4782-8314-73e5250ee8eb.png)

And I had to update the apex library to work
![image](https://user-images.githubusercontent.com/52009630/198068608-d4d27470-21f5-49c3-9bc9-f6631d7d6996.png)

**Comment by junedchhipa** [comment]
Updated the doc page - https://apexcharts.com/docs/options/plotoptions/bar/
