### ISSUE TITLE
Wrong date for x-axis if dataset begins from one last date of month. 

### ISSUE THREAD

**Issue by flxb-awm** [apexcharts/apexcharts.js#3466]
### Description

there is Graph with datetime data:

```
{
  "legend": {
    "show": false
  },
  "series": [
    {
      "name": "Delivered quantity",
      "data": [
        {
          "x": "2022-10-31",
          "y": 7.5
        },
        {
          "x": "2022-11-01",
          "y": 0
        },
        {
          "x": "2022-11-02",
          "y": 0
        },
        {
          "x": "2022-11-03",
          "y": 0
        },
        {
          "x": "2022-11-04",
          "y": 0
        },
        {
          "x": "2022-11-05",
          "y": 0
        },
        {
          "x": "2022-11-06",
          "y": 0
        }
       
    }  
  ],
  "chart": {
    "zoom": {
      "enabled": false
    },
    "height": 332,
    "type": "bar",
    "animations": {},
    "toolbar": {
      "show": false
    },
    "stacked": true
  },
  "xaxis": {
    "type": "datetime",
    "labels": {
       format: 'ddd'
    },
    "min": 1667174400000,  
  },
  "yaxis": {
    "labels": {},
    "tooltip": {
      "enabled": false
    }
  },
  "tooltype": {
    "x": {}
  }
}

```

set of data begin from 2022-10-31 and finished for 2022-11-06 (one weeks)
and 

### Steps to Reproduce

1. run the graph with the options

### Expected Behavior
there is graph with one column and x axis with name of weekdays abbreviation names begin from Monday
`Mon Tue Wed Thu Fri Sat San`
### Actual Behavior
there is graph with one column and x axis with name of weekdays abbreviation names begin from Saturday
`Sat Tue Wed Thu Fri Sat San`

### Screenshots

![Снимок экрана 2022-10-31 в 16 12 42](https://user-images.githubusercontent.com/117089047/199016006-6ccdd59d-199b-455d-a677-1cc3c2cacd4b.png)

### Reproduction Link

https://codepen.io/F-Tulpan/pen/poKjBGR

**Comment by flxb-awm** [comment]
if change the formatLabel for x-axis to 'dd/MM'

![Снимок экрана 2022-10-31 в 16 18 33](https://user-images.githubusercontent.com/117089047/199017122-a3b6e7d9-ce4f-4cb3-9271-6f72c211128c.png)

it looks like the first date is spoiled.

https://codepen.io/F-Tulpan/pen/JjZYeMK

**Comment by jhemak** [comment]
Did you ever figure out a fix or workaround for this?

**Comment by nara1111** [comment]
Hey, this bug is still ALIVE!!!!

**Comment by salil-01** [comment]
@junedchhipa any update on this issue, this bug still persists..

- As a workaround - instead of giving datetime as a type on `xAxis` of bar charts, give the type `numeric` with `tickAmounts` and use formatter in labels to format the datetime.

```
// example of formatting in locale 
formatter: function (value) {
  const date = new Date(value);
  const formatter = new Intl.DateTimeFormat("en", {
    day: "2-digit",
    month: "short",
  });
  return formatter.format(date);
},
```

**Comment by jhemak** [comment]
Has this fix been released?  I am seeing the problem still in version 2.1.2.
