### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'elGridBorders')

### ISSUE THREAD

**Issue by pistou** [apexcharts/apexcharts.js#3472]
### Description
When creating a Pie / Donut chart, there is a JS error in the console, at least in Chrome (not tested on other browsers):

> apexcharts:14 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'elGridBorders')
    at apexcharts:14:39293
    at new Promise (<anonymous>)
    at t.value (apexcharts:14:38212)
    at apexcharts:14:36155
    at new Promise (<anonymous>)
    at t.value (apexcharts:14:21675)
    at pen.js?key=pen.js-e5bd07f8-3986-d368-51d8-6535df40c060:14:7

### Steps to Reproduce

1. Create a basic Pie / Donut chart

### Reproduction Link

[https://codepen.io/TouPye/pen/KKeMoKq](https://codepen.io/TouPye/pen/KKeMoKq)

**Comment by JamieWotter** [comment]
Happening for me on the Polar Area chart as of about 2 hours ago also., seems to be an issue with the tooltips.

**Comment by mdevDE** [comment]
I experience the same problem for Polar Area Charts and RadialBar Charts

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'elGridBorders')
    at apexcharts.min.js:14:39185
    at new Promise (<anonymous>)
    at t.value (apexcharts.min.js:14:38205)
    at apexcharts.min.js:14:36153
    at new Promise (<anonymous>)
    at t.value (apexcharts.min.js:14:21668)
    at VueComponent.init (vue-apexcharts.js:123:1)
    at VueComponent.mounted (vue-apexcharts.js:69:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at callHook (vue.runtime.esm.js:4235:1)

**Comment by TangoPJ** [comment]
How did you solve this problem? I have the same one

**Comment by TangoPJ** [comment]
I solved this problem via update the version, thank you :)

**Comment by Jani-Instrive** [comment]
Updated apexCharts from 3.36.3 to 3.37.0 but still facing same issue

**Comment by m3di** [comment]
i have the same issue, is it resolved?

"apexcharts": "^3.46.0",
"vue3-apexcharts": "^1.5.2",
