### ISSUE TITLE
offset label for small pie slices

### ISSUE THREAD

**Issue by dodumosu** [apexcharts/apexcharts.js#349]
For pie (and donut) charts, small slice labels are obscured/unclear, for example, [this](https://output.jsbin.com/maciqu/)

If possible, a configurable option to offset labels like the ECharts example in #16

**Comment by junedchhipa** [comment]
You can try this property to move the dataLabels outside so they don't overlap

```javascript
plotOptions: {
   pie: {
     dataLabels: {
        offset: 30
      }
   }
}
```

https://apexcharts.com/docs/options/plotoptions/pie/#dataLabelsOffset

**Comment by dodumosu** [comment]
thanks!
