### ISSUE TITLE
Feature Request: Localization of datetime

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#35]
There is some UI elements in apexcharts that are locked into english, like date format. Even if we can configure the way it's displayed, we can't have the config format the date in another language. 

Just let the datetimeFormatter object takes the localization token.

Vanilla JS takes it like with a simple string like 'FR-fr' as parameter of toLocaleString()

[MDN toLocaleString function documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)

**Comment by junedchhipa** [comment]
@arkhenstone Tested the date.toLocaleString() function and it looks like it returns the full date and time in this format `20/12/2012 03:00:00` 
This will result in more work for me to split the string and re-calculate label count and determine if years/months/day should be displayed.

I suggest, using the `options.xaxis.labels.formatter` function to override dates/times to suit your needs.
Here is an example using moment.js in `formatter`
https://codepen.io/apexcharts/pen/MBRrbX

and here is an example of how you can use .toLocaleString() in `options.xaxis.labels.formatter` function
https://codepen.io/apexcharts/pen/oMOdBv

**Comment by Carniatto** [comment]
I checked your example and the `date` passed to the formatter is already formatted before. If you put two different years in the series it gets all wrong.

**Comment by junedchhipa** [comment]
I have provided an additional parameter in `options.xaxis.labels.formatter` as a timestamp which you can use to format dates as per your needs.

Example:
```javascript
xaxis: {
  tickAmount: 6,
  labels: {
    formatter: function(val, timestamp) {
      return val;
    }
  }
},
```
Note that here - tickAmount will respond to the value you provide.
Read more - https://apexcharts.com/docs/options/xaxis/#formatter

With this update, I have also provided localization options which you can set in `options.chart.cultures`
Read more - https://apexcharts.com/docs/options/chart/cultures/

So, from now on: you will be able to set your preferred language strings in some elements.

Cheers

**Comment by junedchhipa** [comment]
Can we close this if I have not missed anything regarding localization?
