### ISSUE TITLE
The X-axis time label will cross the line when Y-axis opposite is set to true

### ISSUE THREAD

**Issue by yidianier** [apexcharts/apexcharts.js#3509]
### Description

The X-axis time label will cross the line when Y-axis opposite is set to true

### Reproduction Link

[The X-axis time label will cross the line](https://codesandbox.io/s/elegant-aryabhata-xqxylg?file=/src/App.tsx)

![image](https://user-images.githubusercontent.com/4156606/203512992-554389ab-877b-4a99-abaa-14b19a7d1813.png)

**Comment by brianlagunas** [comment]
Unable to duplicate

![image](https://user-images.githubusercontent.com/835562/203619714-44866aa3-d676-4799-9aee-3cdbd9bc0c7b.png)
