### ISSUE TITLE
console.log left in production build

### ISSUE THREAD

**Issue by mikaelkaron** [apexcharts/apexcharts.js#351]
Looks like there's a `console.log` still around [here](https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/Range.js#L165).

**Comment by junedchhipa** [comment]
Hey, thanks for reporting, just fixed it.

**Comment by junedchhipa** [comment]
I will use this plugin to strip console.logs from builds - https://github.com/rollup/rollup-plugin-strip
