### ISSUE TITLE
Current Date Marker for Timeline Charts

### ISSUE THREAD

**Issue by jayshah1232** [apexcharts/apexcharts.js#3511]
## Summary

I suggest that there be a way to display the current date in a timeline chart. This may be in the form of a vertical line that goes down the length of the chart to line up with the date on the x axis.

## API Changes

I'm not exactly sure what API changes would have to be made but I imagine a new option would have to be added for developers to enable or disable the new marker. This option could also contain a flag to toggle the marker depending on if all the data is in the past or not. This would be useful for cases where the data is being pulled from a database and not hardcoded into the chart.

## Intended Use Case

I am developing a timeline chart for projects selected by the user. The user can select multiple or a single project from a list and generate a timeline chart to visualize deadline and progress data. Being able to see the current date as a marker on the chart would make the chart even more useful to my users. Having a flag that allows me to set the marker to only be displayed if the data included present or future dates would make sure that when the user selects a project completed in the past, the data does not get warped to the very left of the chart while the current date is shown on the very right side.

Here's an example of what I am hoping can be accomplished by this feature:

![image](https://user-images.githubusercontent.com/27381013/203651519-e45235bc-6e93-4dc5-86c5-f3e3a7556547.png)

The long red line would represent the current date.

**Comment by vadimffe** [comment]
Was about to post same request, but it has been already added here. Upvote!

**Comment by junedchhipa** [comment]
You can use the [annotations](https://apexcharts.com/docs/options/annotations/) feature to accomplish this.
