### ISSUE TITLE
RangeArea Tooltips don't format datetime values

### ISSUE THREAD

**Issue by delphi-sucks** [apexcharts/apexcharts.js#3514]
### Description

When trying to use a **RangeArea**-Chart with a datetime-x-axis, the tooltip label for the x-axis doesn't get formatted like expected.

### Steps to Reproduce

1. Create a RangeArea-Chart with datetime-Values for the x-axis
2. Set the x-axis type to `datetime`
3. Enable the tooltip
4. Hover over a datapoint to display the tooltip

### Expected Behavior

The tooltip label for the x-axis gets formatted like the x-axis label.

### Actual Behavior

The tooltip label for the x-axis just gets casted to string.

### Screenshots

![chrome_aU3lRJSibO](https://user-images.githubusercontent.com/17913239/203787357-cf0e78ed-952d-4d7f-8980-06cb56b97961.png)

### Reproduction Link

[https://codepen.io/moddesteni/pen/eYKrYJz](https://codepen.io/moddesteni/pen/eYKrYJz)

**Comment by denxorz** [comment]
Worked around it like this for now:

https://codepen.io/denxorz/pen/LYrBoEq
```
  tooltip: {
    y: {
      formatter: (val) => {
        return isNaN(+val)
          ? `${new Date(parseInt(val)).toLocaleDateString()}:`
          : +val;
      }
    }
  },
```
