### ISSUE TITLE
Stacked charts in timeseries with missing values are incorrectly displayed

### ISSUE THREAD

**Issue by mamasselin** [apexcharts/apexcharts.js#352]
Stacked charts are not stacking properly when having timeseries with missing values. This was partially addressed as per #199 and #225.

However, issue is still present with latest version.

## Codepen

https://codepen.io/mamasselin/pen/vPEdYR

## Explanation

- What is the behavior you expect?

    I would expect the bars to stack correctly

- What is happening instead?

    Bars are overlapping each others and don't seem to stack properly. Not that this also happens with stacked area charts.

- What error message are you getting?

    None.

**Comment by mamasselin** [comment]
I've started playing around with the stacked line/area and made a fix similar to what was in #353 . However the hover of the points seem broken, but I'm not sure why though.. Is there a separate logic for the points/hovering ? See below

![2019-02-27_09-12-28](https://user-images.githubusercontent.com/16145977/53496496-2ac7dc00-3a70-11e9-9e13-263af35d662e.gif)

**Comment by mamasselin** [comment]
Ok, I think it's just because the datapoints were too close to each other. If I bump the value of 8, the hover works as expected:

![2019-02-27_09-20-11](https://user-images.githubusercontent.com/16145977/53496900-fc96cc00-3a70-11e9-8972-44476abe2189.gif)

**Comment by junedchhipa** [comment]
The function to determine the closest values is named as "getNearestValues" and is located in `src/modules/tooltip/Utils`.
I will take another look, the function became very complex and needs some refactoring.

**Comment by junedchhipa** [comment]
Closing this until I decide to start working on it again.

**Comment by AlexandraPechueva** [comment]
Hi!  We are using in our project ng-apexcharts 1.1.0 (apexcharts 3.10.0 ) and there is a problem with missing timeseries in bar stacked charts, which is fixed in  #353 pull request. When could you include those fixes into release?

**Comment by iProGamer** [comment]
bump
