### ISSUE TITLE
RangeArea with null value removes fill color

### ISSUE THREAD

**Issue by DennisNurtio** [apexcharts/apexcharts.js#3525]
### Description

When a RangeArea chart contains a null x-value, the range will no longer be filled. It does not matter if this null-x-value is part of the rangeArea series or a combined series like the line.

### Steps to Reproduce

1. Have at least one rangeArea
2. Set one of the x-values to null

### Expected Behavior

RangeArea series keeps being filled.

### Actual Behavior

RangeArea series is not filled at all.

### Screenshots

Without null value (OK):
![image](https://user-images.githubusercontent.com/70628966/204575178-10d65a7d-a2a8-4a98-b083-95b0c824f32a.png)

With a null value (NOT OK):
![image](https://user-images.githubusercontent.com/70628966/204575247-663e19d7-d690-4044-9995-38bd730cddfa.png)

### Reproduction Link
Without null value (OK) : https://codepen.io/denxorz/pen/PoaBvOG
With null value (NOT OK): https://codepen.io/denxorz/pen/XWYBwex

**Comment by svgr-slth** [comment]
Experiencing a similar issue here
The series i'm comparing are being aligned on the X values (datetimes)
Everything works fine when both datasets are the same length, but if some data is missing at the end or beginning of one of the series, range areas start to look glitchy.

Example: 
lets say my first series is longer than my second
```
// first series
[
  {
    x: "11-10-2022",
    y: [1, 3],
  },
  {
    x: "11-11-2022",
    y: [2, 4],
  },
  {
    x: "11-12-2022",
    y: [3, 5],
  }
];

// second series
[
  {
    x: "11-10-2022",
    y: [1, 3],
  },
  {
    x: "11-11-2022",
    y: [2, 4],
  }
];
```

Before rendering the chart, i "align my series" by filling the values with `null` like so:
```
// first series
[
  {
    x: "11-10-2022",
    y: [1, 3],
  },
  {
    x: "11-11-2022",
    y: [2, 4],
  },
  {
    x: "11-12-2022",
    y: [3, 5],
  }
];

// second series
  {
    x: "11-10-2022",
    y: [1, 3],
  },
  {
    x: "11-11-2022",
    y: [2, 4],
  },
  {
    x: "11-12-2022",
    y: [null, null],
  }
];
```

Here is what the chart looks like (values are not the exact same, but the use case is):
![image](https://user-images.githubusercontent.com/92316565/204788447-2ebce770-2e6e-4411-b05c-0674f00bbe1d.png)
