### ISSUE TITLE
Set min height or width via chart property

### ISSUE THREAD

**Issue by Crystalskulls** [apexcharts/apexcharts.js#3535]
## Summary

We use in a web application vue-apexcharts 3.36.0 to visualize the number of orders from different item categories.

If there are a lot of orders from one category then for categories with very few orders the number label is no longer visible in the stacked bar. In the attached screenshot, you can see that the number of orders for the category 'Decoration' can no longer be displayed, because the height of the stack is too small.

Therefore, we would like to have a way to set the minimum height or width for a stack via the chart options.

![example_chart](https://user-images.githubusercontent.com/25111875/205879725-7c9447a0-79cd-4c0e-ba87-83d4e1b4d88f.JPG)

Related similar issues: [#1616 ](https://github.com/apexcharts/apexcharts.js/issues/1616)

**Comment by Crystalskulls** [comment]
Unfortunately, I have not received any feedback from the developers yet.

**Comment by pramodchoudhari** [comment]
How to set fixed height to bar chart irrespective of data values? or how to make it responsive?  
![image](https://user-images.githubusercontent.com/5083043/235448066-307f3b06-d8f8-46e5-8cf3-ff19da780d3e.png)

**Comment by KatuGT** [comment]
any news?
