### ISSUE TITLE
Expand Datapoint on hover option for Pie/Donut Charts

### ISSUE THREAD

**Issue by Beatriz-Sanchez** [apexcharts/apexcharts.js#3538]
I would like the options to Expand a datapoint on hover, on Pie/Donut Charts

There already is an option to "expandOnClick". I would like the same effect on hover:

<img src="https://apexcharts.com/wp-content/uploads/2019/01/expanded-donut-slice.png">

I have been using vue-apexcharts and have tried to that in multiple ways, but couldn't get the result I wanted

**Comment by Ashish558** [comment]
Did anyone figure out how to do it ?

**Comment by sFarkhod** [comment]
@Ashish558 Hello Mr Ashish. I know it's a little bit late for an answer )). But this is a [workaround for this](https://stackoverflow.com/a/78624946/27175469) . And here is a small [example](https://codesandbox.io/p/devbox/apexchart-pie-donut-example-ldhzlw) . Just make sure you don't disable the expandOnClick: false, like so.
