### ISSUE TITLE
Demos not working, jsdelivr.net apexcharts@latest cuts short

### ISSUE THREAD

**Issue by ivuorinen** [apexcharts/apexcharts.js#354]
### What is the behavior you expect?

Expected to see nice looking charts

Examples:
- https://apexcharts.com/javascript-chart-demos/line-charts/basic/
- https://apexcharts.com/vue-chart-demos/line-charts/basic/
- https://apexcharts.com/react-chart-demos/line-charts/basic/

### What is happening instead?

Charts are not loading, browser console filling with errors. Happens with all (JS, Vue and React) examples.

### What error message are you getting?

Here's few:
```
[Vue warn]: Error in mounted hook: "TypeError: t is not a constructor"

TypeError: "t is not a constructor"

SyntaxError: missing } after function body
```

Looks like jsdelivr.net CDN mirror is borked, the final "line" is

```js
for(var o=0;o<s.length;o++)s[o].classList.remove("legend-mouseover-inactive")}},{key:"highlightRangeInSeries",value:function(t,e){var i=this.w,s=i.globals.dom.baseEl.queryS
```

I'm guessing `i.globals.dom.baseEl.queryS` should continue as `...querySelector`

**Comment by ivuorinen** [comment]
Weird, cdn address without `@latest` returns full minified source. Both are `v3.5.0`

- https://cdn.jsdelivr.net/npm/apexcharts
- https://cdn.jsdelivr.net/npm/apexcharts@latest

**Comment by junedchhipa** [comment]
Works fine on my end. Also flushed cache on cdnjs as there was an issue for 3.4.0
3.5.0 should work fine.

**Comment by ivuorinen** [comment]
Looks like jsdelivr.net people purged the cache too: https://github.com/jsdelivr/jsdelivr/issues/18131#issuecomment-467847657

Closing the issue as solved.
