### ISSUE TITLE
Legends are not aligned properly and are hidden behind graph

### ISSUE THREAD

**Issue by VAsh19** [apexcharts/apexcharts.js#3540]
I am using apex chart version 3.28.3 in my react(17.0.2) project .
when I am working on my local machine it shows legends are properly aligned with X-axis but when i am deploying it to server legends are over riding the graph area.
 
![Screenshot (215)](https://user-images.githubusercontent.com/73327898/206356304-c9022505-ace7-448d-a648-b90719f89bfd.png)
![Screenshot (216)](https://user-images.githubusercontent.com/73327898/206356324-237d41b3-9d12-4515-ab02-8b9aed1345dc.png)

I have not changed anything in code and also not able to find the solution why this is happening.`   const label = [];
    const salesData = [],
      orderCountData = [];
    topStores.forEach((eachStore) => {
      label.push(eachStore.storeName);
      salesData.push(eachStore.totalSale.toFixed(2));
      orderCountData.push(eachStore.totalOrderCount);
    });
    setChartOptions({
      series: [
        {
          name: "Total Sales",
          data: salesData,
        },
        {
          name: "Total Orders",
          data: orderCountData,
        },
      ],
      options: {
        chart: {
          type: "bar",
          height: 430,
          // stacked: true,
        },
        plotOptions: {
          bar: {
            dataLabels: {
              position: "top",
            },
          },
        },
        dataLabels: {
          enabled: false,
          offsetX: -6,
          style: {
            fontSize: "12px",
            colors: ["#fff"],
          },
        },
        stroke: {
          show: true,
          width: 1,
          colors: ["#fff"],
        },
        tooltip: {
          shared: true,
          intersect: false,
        },
        xaxis: {
          categories: label,
          title: {
            text: "Stores",
            style: {
              fontSize: "14px",
              fontFamily: "Public Sans, sans-serif",
              fontWeight: 700,
            },
            offsetX: -30,
          },
        },
        yaxis: {
          title: {
            text: "Total Sales ($) and Total Orders",
            style: {
              fontSize: "14px",
              fontFamily: "Public Sans, sans-serif",
              fontWeight: 700,
            },
          },
          labels: {
            formatter: function (val, e) {
              return e?.seriesIndex == "0"
                ? `$${numberWithCommas(val.toFixed(2))}`
                : numberWithCommas(val.toFixed(0));
            },
          },
        },
      },
    });
  }, [topStores]);
`

**Comment by brianlagunas** [comment]
Did not follow issue template instructions.
