### ISSUE TITLE
Home Assistant - Line Graph - "transform" function not working with "+" (sum)

### ISSUE THREAD

**Issue by jvanhambelgium** [apexcharts/apexcharts.js#3569]
### Description

I need to add a certain fixed value to a existing sensor value before plotting.

### Steps to Reproduce

1. Create a Line-chart of a sensor
2. In the code-editor, use the "transform function" like

series:
  - entity: sensor.vitodens_300_brander_starts
    **transform: "return x **+ 100**;"**

4. Look at what the graph is doing...

### Expected Behavior

One would expect the displayed value to increase with the integer value you want to "sum" / "add" to it.
Eg. if the value was 43 , then I would expect 143 to be plotted.

### Actual Behavior

It processes like a concatenation of the data. The "43" value now becomes "43100"
(like it handles this like a string value, not integer)

**It works just fine when you use other math-operators!
"/" (divide) works fine!
"*" (multiply) works fine!
"-" (substract) works fine!**

### Reproduction Link

See screenshots above, the codepen does not recognise the "transform" function? This is Home Assistant specific ?
-->

**Comment by jvanhambelgium** [comment]
[
![Screenshot from 2022-12-26 08-35-11](https://user-images.githubusercontent.com/60518313/209520447-83680d43-926f-4f33-9300-087ebfa767cc.png)
![Screenshot from 2022-12-26 08-39-08](https://user-images.githubusercontent.com/60518313/209520449-85a39d86-e74e-4638-ad0d-c34423ffc52e.png)
![Screenshot from 2022-12-26 08-39-01](https://user-images.githubusercontent.com/60518313/209520450-0be43518-375a-4831-9caf-a03a89416e42.png)
![Screenshot from 2022-12-26 08-38-54](https://user-images.githubusercontent.com/60518313/209520452-640f44b3-724f-4f10-918d-5f90619717a9.png)
![Screenshot from 2022-12-26 08-39-16](https://user-images.githubusercontent.com/60518313/209520453-7e30952f-4e44-4fdb-8c8e-89b45c60ef9b.png)
](url)

**Comment by brianlagunas** [comment]
No repo provided

**Comment by jvanhambelgium** [comment]
I'm running this one, v2.0.2
https://github.com/RomRider/apexcharts-card/releases/tag/v2.0.2

**Comment by brianlagunas** [comment]
Please create a stand alone app without home assistant that reproduces the issue.
