### ISSUE TITLE
Loading using Require.js (AMD) broken

### ISSUE THREAD

**Issue by Micene09** [apexcharts/apexcharts.js#357]
## Codepen

Just open [this codepen](https://codepen.io/Micene09/pen/vPOpWy) and check the dev-console (F12):

![image](https://user-images.githubusercontent.com/14896521/53502713-eb6cb000-3aae-11e9-9aac-6d941af5411f.png)

## Explanation

I think that `SVG is not defined` because there is something wrong on module bundler.
Do i need to include SVG.js as external library?

**Comment by junedchhipa** [comment]
The new module bundler configuration (rollup) has broken AMD support after v3.0.0

I will soon update the SVG version which should fix the SVG undefined issues.

**Comment by cstlaurent** [comment]
In the meantime I can add an AMD build output to the Rollup configuration see if it works.

**Comment by cstlaurent** [comment]
Looks like its not as plug and play as I thought, I'll investigate more when I have time.

**Comment by junedchhipa** [comment]
@cstlaurent Thanks!

The main issue I guess is `SVG.js` current way of exposing the global SVG variable, and this way has caused a lot of problems with the modern build systems (many users have reported it in the past).

They have released 3.0 which promises to fix these issues, and I am in the process of slowly migrating towards 3.0 (many breaking changes, hence getting delayed).

**Comment by Micene09** [comment]
any news  here? here we cannot update the library without this fix.

**Comment by thetinshusasi** [comment]
Hi I am facing the same iisue.

ReferenceError: SVG is not defined
apexcharts.esm.js:24146
    at c:\Dev\***Project Path***\node_modules\apexcharts\dist\apexcharts.esm.js:24146:1.

does anyone has the solution for this or any workaround?
I am using react-apexcharts in my project .

**Comment by junedchhipa** [comment]
@Micene09 Unfortunately, no update. I have contacted SVG.js authors regarding plugin compatibility with 3.0. Once, I get a solution, I will upgrade to svgjs@3.0 which hopefully will fix a lot of import issues.

**Comment by junedchhipa** [comment]
Adding the old Webpack configuration only for `amd` build as that seems to be the easiest fix for now.
The new file will be
`dist/apexcharts.amd.js`

Will be released in 3.7.0 this weekend

**Comment by Micene09** [comment]
Can you please add the min version of this file? It is about 1mb.

**Comment by Teisi** [comment]
This "workaround" don't work for me and yes the script is loades before i make my "new ApexCharts":

"Uncaught ReferenceError: ApexCharts is not defined at <anonymous>:1:1"

**Comment by byander** [comment]
@junedchhipa, the problem about loading using require is not working. If in the require I put apexcharts.js, the error is "Uncaught ReferenceError: SVG is not defined". If I put apexcharts.amd.js, the error is "ReferenceError: ApexCharts is not defined". Thank's

**Comment by junedchhipa** [comment]
@Micene09 
I have already put the `umdNamedDefine` in the Webpack configuration.
Also minified.

Are you also facing the same issue in the latest update?

@everyone else, can you please try downgrading and see if the previous versions work? 3.8.0 ?

**Comment by wicked539** [comment]
I stumbled across the same issues, here's my workaround:
```
require.config({
  baseUrl: ".",
  paths: {
    "ApexCharts": "https://cdn.jsdelivr.net/npm/apexcharts@3.10.1/dist/apexcharts",
    "svg": "https://cdn.jsdelivr.net/npm/svgjs@2.6.2/dist/svg.min"
  }
});

require(['svg', 'ApexCharts'], function (svg, ApexCharts) {
  var myChartOpts = {...};
  var myChart = new ApexCharts(document.querySelector("#myChart"), myChartOpts);
  myChart.render();
});
```

Hope this helps!

**Comment by junedchhipa** [comment]
`svg.js` is already bundled in the `apexcharts` file, so loading it again may cause issues.

I will shortly look into the Webpack configuration to see what went wrong.

**Comment by junedchhipa** [comment]
I have changed the Webpack config again and built a `umd` instead of `amd`.
The samples directory also includes a [requirejs](https://github.com/apexcharts/apexcharts.js/tree/master/samples/requirejs) demo.

The next release v3.12.0 along with this change will be released soon.

**Comment by ihordeyneka** [comment]
How is the progress with upgrading to version 4?
I have the same issue "SVG is not defined" in Angular when importing NgApexchartsModule. This works fine in regular Angular build, but does not work in AppShell build when building serverside in NodeJS environment.

**Comment by juniorschen** [comment]
Same problem with NgApexchartsModule

**Comment by juniorschen** [comment]
@junedchhipa 
how can I overcome this problem

**Comment by juniorschen** [comment]
@ihordeyneka the solution : https://github.com/apexcharts/ng-apexcharts/issues/78

**Comment by shadowintel** [comment]
> How is the progress with upgrading to version 4?
> I have the same issue "SVG is not defined" in Angular when importing NgApexchartsModule. This works fine in regular Angular build, but does not work in AppShell build when building serverside in NodeJS environment.

Yes it doesn't work in ssr

**Comment by cjholowatyj** [comment]
I'm still not seeing the resolution of this issue on my end. Perhaps it is my introductory knowledge of requireJS... I have a question up on StackOverflow which describes my current setup... *Any brave souls willing to help me resolve it?*

[Having trouble loading ApexCharts using RequireJS](https://stackoverflow.com/questions/66069310/having-trouble-loading-apexcharts-using-requirejs)

**Comment by rochapablo** [comment]
I'm also getting the same error trying to use apexcharts on Angular Universal SSR.

First I was getting `ReferenceError: window is not defined`, then I tried to 

```
const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync('dist/browser/index.html').toString();
const win = domino.createWindow(template);

global.window = win;
global.document = win.document;
global.DOMTokenList = win.DOMTokenList;
global.Node = win.Node;
global.Text = win.Text;
global.HTMLElement = win.HTMLElement;
global.navigator = win.navigator;
```

But now I'm getting `ReferenceError: SVG is not defined`

**Comment by epykure** [comment]
Is this issue fixed ? I am also facing this issue when I am trying to use ApexCharts from Jupyter.

Thanks
