### ISSUE TITLE
need to remove background on stacked chart bar hover

### ISSUE THREAD

**Issue by Mudassarali222** [apexcharts/apexcharts.js#3572]
@franklx 
@yangkun 
@rndmerle 
@zur4ik 

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
remove highlighted background color on hover
### Actual Behavior
hover on bar in stacked chart background show
### Screenshots
![Screenshot_git](https://user-images.githubusercontent.com/75826150/209634802-c3943703-198e-42ff-8028-b0c0f81ff682.png)

**Comment by brianlagunas** [comment]
Did not follow issue template instructions

**Comment by Mudassarali222** [comment]
@brianlagunas your reply not helpful for me. please explain

**Comment by Mudassarali222** [comment]
> Did not follow issue template instructions

with all due respect i even copied the code from the apexcharts site

**Comment by Mudassarali222** [comment]
here is solution
https://stackoverflow.com/questions/74863077/need-to-remove-sky-background-color-on-bar-hover-in-apexcharts
