### ISSUE TITLE
Grid lines for x-axis don't work after update from 3.35.0 to 3.36.3

### ISSUE THREAD

**Issue by serwerin** [apexcharts/apexcharts.js#3580]
### Description

Missing vertical lines (x-axis) in grid in line chart

### Steps to Reproduce

1. Create standard line chart
2. Add grid lines for x-axis in options (like in documentation):
grid: {
  xaxis: {
   lines: {
     show: true
   }
  }
 }

### Expected Behavior

Should display full grid, but still missing vertical lines

### Actual Behavior

Missing vertical lines

### Screenshots

In 3.35.0:

![image](https://user-images.githubusercontent.com/52240758/210212831-b8ea133b-87c0-4625-be03-def894b084db.png)

In 3.36.3:

![image](https://user-images.githubusercontent.com/52240758/210213109-20a6057e-902a-4ebe-a635-473f9dc5b4f7.png)

### Reproduction Link

https://codesandbox.io/s/vue-xaxis-grid-bug-sjkh9s

**Comment by drewbitt** [comment]
Yes, bug is with xaxis type `category`; `numeric` will show vertical grid.

**Comment by bazuka5801** [comment]
same bug, grid: {
xaxis: {
lines: {
show: true
}
}
} 


not working

**Comment by rmosias2** [comment]
I'm facing the same issue, try to downgrade but doesn't work, I'm using  
`"react-apexcharts": "^1.4.0",`
`"apexcharts": "^3.36.3",`

**Comment by canblt** [comment]
any updates ?

**Comment by drewbitt** [comment]
> any updates ?

This is fixed. I believe you should be contacting the libraries that have this as a dependency to update their version
