### ISSUE TITLE
Detailed legends

### ISSUE THREAD

**Issue by jboysen** [apexcharts/apexcharts.js#3597]
## Summary

We would love to see legends reflecting the lines in the chart. E.g. if different markers and lines are chosen, the single dot in the legend should show this (e.g. like in Excel).

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

We imagine a "legend.showLines" boolean and that the current dot automatically will reflect the marker chosen for a data-series.

## Intended Use Case

E.g. for this chart:
![image](https://user-images.githubusercontent.com/935849/212014915-984696fb-d355-468a-b6e8-10777957dc50.png)

It would be nice with a legend reflecting the data-series. Below is how it would somewhat look in Excel:
![image](https://user-images.githubusercontent.com/935849/212015062-21a10396-ea7c-42cd-a9cf-c92e6b0fb9ef.png)

**Comment by jboysen** [comment]
This is still a feature request, so please don't close.

**Comment by tothmarci25** [comment]
In the documentation it's written that we can use `legend.markers.customHTML` config as a callback function that returns a HTML string. But unfortunately it replaces all the markers of all series legend.

However based on the source code we also can use an array of functions which can return HTML strings. And indexes of this array correspond to the series indexes of the given legends.

```javascript
legend: {
    markers: 
        customHTML: [
           () => '<i class="fas fa-chart-pie"></i>',
           () => '<i class="fas fa-chart-simple"></i>',
           () => '<i class="fas fa-chart-scatter"></i>',
        ]
    },
}
```

But I don't know why it's not documented.  Is it not recommended to use like this maybe?

**Comment by jboysen** [comment]
Thanks a lot! That actually seems to do the job with some hackerish HTML.
