### ISSUE TITLE
Real time data causes render blinks

### ISSUE THREAD

**Issue by psambit9791** [apexcharts/apexcharts.js#360]
While working with real time data coming in through a websocket, the graph render becomes very jerky. It also causes blinks while rendering.

![test](https://user-images.githubusercontent.com/25612092/53580587-db6ad400-3b73-11e9-9426-3bb052072e74.gif)

- What is the behavior you expect?

The render needs to be smooth and without blinks. If there is any lower limit of refreshing beyond which the rendering becomes jerky, would be good to know.

**Comment by junedchhipa** [comment]
I have not experienced this yet. Can you please create a simpler version of it without web sockets?
Or maybe paste your chart configuration and updateSeries logic?

**Comment by psambit9791** [comment]
Problem was caused due to high data rate at the client end. Works seamlessly at a lower data rate. Closing the issue.

**Comment by mehdibahrami** [comment]
@junedchhipa Cloud you please check this one?
![Apex](https://user-images.githubusercontent.com/63710663/125204574-3b6cfb80-e293-11eb-9a0f-64eb40b040a0.gif)
I checked the data from WebSocket and it doesn't have a problem.
I'm using apex and vue3-apexcharts and my config is:
```
export const speedGaugeChartOptions = {
 plotOptions: {
    radialBar: {
      startAngle: -90,
      endAngle: 90,
      hollow: {
        size: "65%",
      },
      track: {
        show: true,
        strokeWidth: "20%",
      },
      dataLabels: {
        name: {
          offsetY: 25,
          color: "#6b7280",
          show: true,
        },
        value: {
          offsetY: -10,
          color: "#8a63a3",
          fontSize: "2rem",
          formatter(val) {
            return `${parseFloat(val)}`;
          },
        },
      },
    },
  },
  chart: {
    sparkline: {
      enabled: true,
    },
  },
  fill: {
    colors: [
      function ({ value }) {
        if (value <= SPEED_LIMIT) {
          return "#7ca363";
        } else {
          return "#AD6D6D";
        }
      },
    ],
    type: "solid",
  },
  labels: ["km/h"],
};
```
