### ISSUE TITLE
Display text when there is no data in the chart - UPDATE DOCS

### ISSUE THREAD

**Issue by junedchhipa** [apexcharts/apexcharts.js#361]
If the series is null, there needs to be an option to display a custom text (For eg., "Not enough data to display") in the chart area.

The functionality is already implemented, the docs need to be updated on the website.

**Comment by junedchhipa** [comment]
https://apexcharts.com/docs/options/nodata/

**Comment by deepak1828** [comment]
Can anyone provide an example of this. I tried implementing as per the documentation but getting error.

Thanks for your time.

**Comment by junedchhipa** [comment]
@deepak1828 
Please post what have you tried.

**Comment by deepak1828** [comment]
I am getting data from API from which am rendering the graph. Sometimes the API gives me no data. That time I need to show nodata message in the graph.
I don't know how to implement 'NODATA' as per docs. So can you give me an example.

**Comment by miguelerevu** [comment]
> I am getting data from API from which am rendering the graph. Sometimes the API gives me no data. That time I need to show nodata message in the graph.
> I don't know how to implement 'NODATA' as per docs. So can you give me an example.

You just need to add it to the chartOptions object, like: 

> chartOptions: {
                    title: {
                        text: 'MyChart',
                        align: 'left',
                        style: {
                            fontSize:  '16px',
                            color:  '#263238'
                        }
                    },
                    labels: [],
                    colors: ['#0288D1', '#00796B', '#689F38', '#C2185B'],
                    noData: {
                        text: "There's no data",
                        align: 'center',
                        verticalAlign: 'middle',
                        offsetX: 0,
                        offsetY: 0
                    }
                }

**Comment by azivkovi** [comment]
This is what I use for no data scenarios:

https://codepen.io/azivkovi/pen/BaaWqEQ

**Comment by BNRao** [comment]
I working on a Angular project I have an empty json object getting from backend, something looks like this 
data = { }


and my HTML file is below 

<apx-chart
#chart
[series]="form.value.series | series: form.value.type"
[xaxis]="{ type: 'datetime' }"
[chart]="{
height: form.value.height,
type: form.value.type,
zoom: {
enabled: true
},
toolbar: {
show: true,
tools: { download: downIcon, zoomin: true, zoomout: true }
},
shadow: {
enabled: true,
color: '#000',
top: 18,
left: 7,
blur: 10,
opacity: 1
}
}"
[title]="{ text: form.value.title }"
[stroke]="{
curve: 'straight',
width: 2
}"
[noData]="{
text: form.value.title,
align: 'center',
verticalAlign: 'middle',
offsetX : 0,
offsetY:0,
style: {
fontSize:'100px'
}
}"
[colors]="['#009fdb', '#0057b8', '#30d1ff']"
[dataLabels]="{ enabled: false }"
[autoUpdateSeries]="false"
[yaxis]="form.value.yaxis"
>
</apx-chart>
</div>
</div>


But I still cannot see the noData text in chart but an empty graph. I am new to Apexcharts , Can anyone please let me know what is it I am  doing wrong?

**Comment by ChristinaBayerl** [comment]
I was just facing the same issue and could solve it after some time. If anybody else is still wondering about why the noData text is not displaying, this could help you: It does not work if you set the `series.data` property to `undefined`, `null` or `{}`. It only displays if you set the `series.data`-property to an empty array `[]`.
