### ISSUE TITLE
Column width option does not work

### ISSUE THREAD

**Issue by mrovinsky** [apexcharts/apexcharts.js#3611]
### Description

The following setting:
```
plotOptions: {
                bar: {
                    columnWidth: '90%',
                },
            },
```
does not work as expected

We have a stacked bar chart of variable width (typically about 1200px) with variable number of bars (10 to 100, depending on the chosen time resolution).

### Expected Behavior
Each bar should take 90% of the available width.

### Actual Behavior
Sometimes it works but sometimes it does not (see the screenshots)

### Screenshots
<img width="718" alt="Screenshot 2023-01-22 at 11 58 41" src="https://user-images.githubusercontent.com/28759813/213909999-2dd2b5b1-10ab-4b26-bc78-e6031febb45e.png">

<img width="729" alt="Screenshot 2023-01-22 at 11 57 04" src="https://user-images.githubusercontent.com/28759813/213910020-91999601-8453-4750-95a8-a8644f0e9e7a.png">

<img width="723" alt="Screenshot 2023-01-22 at 11 58 23" src="https://user-images.githubusercontent.com/28759813/213910010-0bbe827d-2123-4e91-a3a7-f426f6ce0acb.png">

**Comment by brianlagunas** [comment]
Did not provide required reproduction
