### ISSUE TITLE
Font not used when exporting to png, svg 

### ISSUE THREAD

**Issue by ChamkhiAnas** [apexcharts/apexcharts.js#3612]
Bug report

Explanation
the problem here im using a different font-family for the chart it works in page view, but when i download PNG,SVG the font family change .

What is happening instead?
Font gets replaced with a generic one

What error message are you getting?
None

Page view : 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/59390833/213919528-f91b6fde-8cbc-4968-9b1d-955df35c0802.png">

Exported PNG+SVG  
<img width="897" alt="image" src="https://user-images.githubusercontent.com/59390833/213919545-3c963621-f0c4-4825-b818-700557dd28ff.png">

Any solution to this issue ?

**Comment by brianlagunas** [comment]
Did not provide required reproduction link
