### ISSUE TITLE
Error: <path> attribute d: Expected number, "MNaN NaNCNaN NaN...

### ISSUE THREAD

**Issue by mustela** [apexcharts/apexcharts.js#3615]
Hey all!
Im trying to understand if this is a bug or a problem on any of the settings of my chart.

The chart is being displayed but the console is showing lot of errors... All the datetime values and values are correct, so not really sure what's going on.

Here you can see the chart and the errors in the console.

https://codepen.io/erjankowski/pen/gOjvMVz

Any clue? 

Thanks a lot!

**Comment by Daniel-Uzcategui** [comment]
I'm having the same exact problem with range bar type using vue3, please if you find a solution let me know

**Comment by mustela** [comment]
Nothing yet, not really sure what's going on here :(

**Comment by dgolovko97** [comment]
I had the same problem. It was related to the fact that I was clearing the DOM node with the .html() method. To evaporate this, you need to call the ApexCharts.exec(el.id, 'destroy') method before clearing. This worked for me. The application is not vuejs, but SPA.

**Comment by Rao-Mudasir** [comment]
any solution for react

**Comment by thiagodias63** [comment]
Same problem on angular

**Comment by klucass** [comment]
Same problem using Vue3 with inertia.

**Comment by anuj-sunny** [comment]
> Hey all! Im trying to understand if this is a bug or a problem on any of the settings of my chart.
> 
> The chart is being displayed but the console is showing lot of errors... All the datetime values and values are correct, so not really sure what's going on.
> 
> Here you can see the chart and the errors in the console.
> 
> https://codepen.io/erjankowski/pen/gOjvMVz
> 
> Any clue?
> 
> Thanks a lot!

Hii same error 
Error: <path> attribute d: Expected number, "…A 130 130 0 1 0 NaN NaN".

**Comment by anuj-sunny** [comment]
![Screenshot (161)](https://github.com/apexcharts/apexcharts.js/assets/134368344/0f99466d-1ebf-4711-8d1e-452f3b831587)
