### ISSUE TITLE
`horizontalAlign` has no effect on `legend` (radialBar)

### ISSUE THREAD

**Issue by Knogobert** [apexcharts/apexcharts.js#3622]
### Description
Been using apexcharts for quite some time now, vue-apexcharts that is.
But this issue is in the core lib.

I have a reproduction link for the radialBar being used similar to how we have it. 
And as you can see, both in the original chart and the rendered base64 image. `legend.horizontalAlign: 'right'` is not applied as expected. 
Docs: https://apexcharts.com/docs/options/legend/

Or at least there should be some way for us to affect the `text-align` style of the legend in the options.

I too have the separate issue that is described here #3617 (font not being used in the rendered image)

### Steps to Reproduce

1. Go to reproduction link: https://codepen.io/Knogobert/pen/WNKJMZN
2. See that the legend text is aligning the text leftward (`text-align: left` pretty much)
3. See that the rendered image of the chart above is the same erroneous one.

### Expected Behavior
For the legend to be able to be `text-align: right`
And also keep that when being rendered via base64 image string

### Actual Behavior
The legend is always `text-align: left`

### Screenshots

Wrong/Actual:
![bild](https://user-images.githubusercontent.com/770560/214812352-47098623-0f27-40c7-ab5b-ef7ce9d87033.png)

Good/Expected:
![bild](https://user-images.githubusercontent.com/770560/214812522-3600d156-782e-4c14-a92f-10bab7140ef2.png)

### Reproduction Link
https://codepen.io/Knogobert/pen/WNKJMZN

**Comment by brianlagunas** [comment]
This is not a bug, it's by design. The alignment property is for the legend itself, not the text within the legend. To achieve what you want just create a style targeting the legend. Maybe something like this:

```css
div.apexcharts-legend.apx-legend-position-right {
  align-items: end;
}
```

**Comment by Knogobert** [comment]
That may be by design, tough to know by the documentation.

The issue is then rather that those CSS edits are not reflected in the rendered image.

As you can see here in this reproduction with your suggested solution: https://codepen.io/Knogobert/pen/LYBrRab
