### ISSUE TITLE
"Theme Palettes" page empty

### ISSUE THREAD

**Issue by Ledmington** [apexcharts/apexcharts.js#3632]
### Description
The page of the documentation "Theme Palettes", [here](https://apexcharts.com/features/theme-palettes/), is empty.

### Steps to Reproduce

1. open link [https://apexcharts.com/features/theme-palettes/](https://apexcharts.com/features/theme-palettes/)

### Screenshots
![image](https://user-images.githubusercontent.com/68538713/216454448-aee6be34-3687-4bcd-8376-236877f7d30f.png)
![image](https://user-images.githubusercontent.com/68538713/216454572-2d647d17-cb0d-402b-ad25-e5cf22443798.png)

**Comment by junedchhipa** [comment]
Redirected to relevant page
