### ISSUE TITLE
Include link to stencil-apexcharts

### ISSUE THREAD

**Issue by mikaelkaron** [apexcharts/apexcharts.js#364]
Hi.

I've been playing around with creating a [StencilJS](https://stenciljs.com) wrapper for ApexCharts and I have [something that resembles the React example](https://github.com/mikaelkaron/stencil-apexcharts) completed.

It's still a WIP but I'd love it if you can take a quick look so when the `ts` fixes (48b8b9d550b6d871a40d7251153558f39dbde952 and 6c7e9a1d768405e94b5fa068e30150bac67981fd)  are released I can push it to NPM.

If you have any feedback please reply here - I'd love to hear it.

**Comment by junedchhipa** [comment]
Sure, I will gladly put a link in the core-apexcharts README for this wrapper.

Good work there.

**Comment by junedchhipa** [comment]
Updated README
