### ISSUE TITLE
Drag and Drop annotation in xAxis?

### ISSUE THREAD

**Issue by Pyakz** [apexcharts/apexcharts.js#3640]
## Summary

An annotation might be draggable?

## Intended Use Case

Provide a detailed example of where your proposal would be used and for what purpose.

Example:
This annotation from xAxis should be draggable to another dates
 
![Screenshot 2023-02-07 at 10 44 11 PM](https://user-images.githubusercontent.com/49338297/217276759-58ea96b2-b055-4489-85c6-5b15be9595ba.png)

**Comment by jb824** [comment]
Annotation position can move dynamically with an input range slider. Currently working on clicking/dragging. 

Here's a codesandbox example: https://codesandbox.io/p/sandbox/odinproject-react-persons-assignment-935tpk?file=%2Fsrc%2Fcomponents%2FAreaChart.js%3A16%2C21
