### ISSUE TITLE
Missing null values at line chart

### ISSUE THREAD

**Issue by AitorMihashi** [apexcharts/apexcharts.js#3641]
### Description

The scatter dot dissapears when moving the cursor over the chart

### Steps to Reproduce

1. Open this [URL](https://apexcharts.com/javascript-chart-demos/line-charts/null-values/) 
2. Go to the chart and move around
3. You will see that the green point at X:4, Y:12 dissapears and move to the point where you leave the chart

### Expected Behavior

The green scatter point stays at it´s position even when you move your mouse over the chart.

### Actual Behavior

The scatter green point is dragged and dropped at a X point when you go out of the chart

### Screenshots

Chart when you load the page
![image](https://user-images.githubusercontent.com/6864044/217280601-eb167f8b-1d62-4ee4-af5f-fc1f14afc8df.png)

Chart when you move the mouse over
![image](https://user-images.githubusercontent.com/6864044/217281019-2b88e5ad-2e68-451f-8ea6-39b719cef959.png)

### Reproduction Link

https://apexcharts.com/javascript-chart-demos/line-charts/null-values/

**Comment by Guziq** [comment]
I've also noticed that, for some data points, the dots disappear completely. For example, this works fine:

```
{
  name: 'Peter',
  data: [null, 2000, null, 2000, null, 2000, null, 2000, null, 2000, null, null, null, 2000, null, null, 40, null],
}
```

However, when I replace the value `40` with null in the following dataset:

```
{
  name: 'Peter',
  data: [null, 2000, null, 2000, null, 2000, null, 2000, null, 351, null, null, null, 2000, null, null, null, null],
}
```

The graph disappears completely.

**Comment by AitorMihashi** [comment]
@Guziq Can you tell me with apexcharts version are you using?

**Comment by ledpup** [comment]
This is somewhat related to the issue above. In a chart with null values, there is some weird artefacting going on after the mouse leaves the chart.

If you look at the image below, the three dots I've circled in red shouldn't be there at all.

You can reproduce the issue by having 10 as the last x-axis value you were hovering on and then move the mouse outside of the chart.

![image](https://github.com/user-attachments/assets/302f8261-73ed-4009-9fca-4994cbbc03d7)

**Comment by ledpup** [comment]
> @Guziq Can you tell me with apexcharts version are you using?

They're using the demo page at https://apexcharts.com/javascript-chart-demos/line-charts/null-values/
