### ISSUE TITLE
All charts need custom ticks

### ISSUE THREAD

**Issue by davek1979** [apexcharts/apexcharts.js#365]
While I love radial charts, one thing that is seriously missing is custom ticks that could be spread across the chart. 

Simple array of objects accepting stroke thickness, length, color and position in the series with optional label would make this more usable.

**Comment by junedchhipa** [comment]
Hi @davek1979 
Would you elaborate where do you want the labels and ticks to be placed on the radial-bar chart? A simple illustration/example/more description would help.

Thanks!

**Comment by junedchhipa** [comment]
Closing as no response.

**Comment by davek1979** [comment]
I did not notice your original response, apologies.

What I mean is this

![apex](https://user-images.githubusercontent.com/13739999/54141957-9752bb80-441e-11e9-8c39-b406446873a2.png)

**Comment by junedchhipa** [comment]
Thanks for the response, I will see if it is feasible to implement this.

**Comment by JoshuaRack** [comment]
I'd also like to see this, would be useful for implementing general purpose gauges. Obviously the current value can be easily be read off from the label, but without at least some type of marked scale the bar circular bar is little more than eye candy.

**Comment by guikubivan** [comment]
Any updates on this, I'm wondering how easy or hard would it be to add ticks like this. Is that something someone new to Apex charts could figure out?

![Screenshot 2024-05-21 at 5 45 36 PM](https://github.com/apexcharts/apexcharts.js/assets/194133/52ce07b1-bd18-4d94-80a2-2202f26dae1d)
