### ISSUE TITLE
xaxis type category annotation  not working with new release. 

### ISSUE THREAD

**Issue by singhparamvir** [apexcharts/apexcharts.js#3650]
### Steps to Reproduce

1.  go the the link https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/
2. no annotation show up on xaxis for x: 'Bananas',
3. 

### Reproduction Link

var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "line",
  },
  xaxis: {
    type: "category",
    tickAmount: 11,
    categories: ["1991","1992","1993","1994","1995","1996","1997", "1998","1999","2000"],
  
  },
  series: [
    {
      name: "Series 1",
      data: ["1", "2", "3", "5", "6", "7", "8","9","10" ]
    }
  ],
   grid: {
          row: {
            colors: ['#fff', '#f2f2f2']
          }
        },
  annotations: {
  yaxis: [
    {
      y: "2",
      borderColor: '#ff0000',
      label: {
        style: {
         background: '#fff',
            color: '#777',
            fontSize: '12px',
            fontWeight: 400,
            fontFamily: undefined,
            cssClass: 'apexcharts-xaxis-annotation-label',
        },
        text: 'Y-axis annotation'
      }
    }
  ],
   xaxis: [
    {
      x: "1995",
      borderColor: '#ff0000',
      label: {
        style: {
          color: '#ff0000',
        },
        text: 'X-axis annotation'
      }
    }
  ]
}
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();

**Comment by ettoredn** [comment]
They messed it up bigly in the latest minor.

**Comment by brianlagunas** [comment]
Please provide a reproduction link to a codepen, or this issue will be closed.
