### ISSUE TITLE
Slow Resize Rate for the Chart

### ISSUE THREAD

**Issue by 1JunHuang** [apexcharts/apexcharts.js#3657]
After creating a line chart in my page, I found that when I resize the browser, the chart would not immediately resize. The chart only re-adapted to the page when I adjusted the browser window for a while.

I viewed the source code and found some comments:

```
this.w.globals.resizeTimer = window.setTimeout(function () {
          _this6.w.globals.resized = true;
          _this6.w.globals.dataChanged = false; // we need to redraw the whole chart on window resize (with a small delay).

          _this6.ctx.update();
        }, 150);
```

However, 150ms refresh is indeed slow, for those who have high requirements for user experience and interface, even if they sometimes ignore the performance - they want the chart to adapt to the page in a timely manner. The feeling that the chart is updated only after dragging for a while is really uncomfortable. When I changed 150 into a smaller number, the using experience was much better. Therefore, I kindly suggest adding a parameter to let developers freely choose the interval of this resize function.

**Comment by brianlagunas** [comment]
Changing to a feature request
