### ISSUE TITLE
Yaxis tooltip is slower than Xaxis

### ISSUE THREAD

**Issue by fffaria** [apexcharts/apexcharts.js#3659]
I have been using Apexchart and it has been a blast. I want to use a vertical tooltip to indicate wherever the user is hovering. However, when using Apexcharts', it is way slower than the horizontal one, making it look ever so sluggish, even with a small number of data. 

Demonstration:
https://codepen.io/apexcharts/pen/QrbEQg

1. Add Chart 
2. In your options, add 
```
{...
          yaxis: {
            tooltip: {
              enabled: true
            },
           }
}
```
Notice how faster the horizontal tooltip is if compared to the vertical one. The difference is even more noticeable if the height is bigger than the one shown below.

https://user-images.githubusercontent.com/9650859/219899288-e8c77a62-4f77-4e34-9520-acb9153361a0.mp4

Thanks!

**Comment by Thimows** [comment]
I am experiencing the same. @fffaria Did you find a solution in the meantime?

**Comment by fffaria** [comment]
I had to change the css and remove the transition time, iirc. It has been a while so I don't remember exactly. Sorry!

**Comment by junedchhipa** [comment]
Not noticing any difference or lag in the latest version v4.3.0.
