### ISSUE TITLE
toggleSeries + multiple yaxis

### ISSUE THREAD

**Issue by lukaszflorczak** [apexcharts/apexcharts.js#366]
Hi. I have a little problem with my chart. 
I have a multiple series (A-F) with axternal navigation and `toggleSeries()` methods to show/hide them. 

I also have two yaxis:
```
yaxis: [
  { seriesName: 'seriesA' },
  { seriesName: 'seriesA', show: false },
  { seriesName: 'seriesA', show: false },
  { seriesName: 'seriesA', show: false },
  { seriesName: 'seriesE', opposite: true },
  { seriesName: 'seriesE', opposite: true, show: false }
]
```

The problem is when I disable for example `seriesA`. Then I don't see left yaxis. Is there any easy way to toggle yaxis visibility too?

**Comment by junedchhipa** [comment]
There is a property in y-axis called showAlways which allows you to keep the axis always visible.

```javascript
yaxis: {
  showAlways: true
}
```

https://apexcharts.com/docs/options/yaxis/#showAlways

**Comment by lukaszflorczak** [comment]
The problem is I have left y-axis for 4 sesries. And I have external navigation to switch between each series. And now If I use `showAlways` the serrie is visible by default and I can turn it off, but I can not turn it back on.
