### ISSUE TITLE
toggleSeries + tooltip

### ISSUE THREAD

**Issue by lukaszflorczak** [apexcharts/apexcharts.js#367]
Hi!

If I have multiple series I see tooltip and points on lines for each one. 

<img width="373" alt="zrzut ekranu 2019-03-1 o 16 04 38" src="https://user-images.githubusercontent.com/1818979/53646604-eee17200-3c3b-11e9-982f-9f4cbf2ddf48.png">

If I toggle one of them, than each line is treated separately in tooltip. Is it normal? Can I change this?

<img width="278" alt="zrzut ekranu 2019-03-1 o 16 05 02" src="https://user-images.githubusercontent.com/1818979/53646648-0a4c7d00-3c3c-11e9-94e3-15bfd489c2b1.png">

**Comment by junedchhipa** [comment]
The tooltip will display only 1 series when any of the series in `series` array has a different x-axis than the rest.

If you look at this example - https://apexcharts.com/javascript-chart-demos/area-charts/stacked/ the tooltip displays correctly even after toggling through legend.

If your x-axis is the same for all series, I would suggest you create a codepen demo so I can take a look.

**Comment by lukaszflorczak** [comment]
Did you mean y-axis? I have different ones. Thank you for your response.

**Comment by lukaszflorczak** [comment]
Hi again!

Because I'm creating my chart in Vue projects I thought that would be better to describe it in vue-appexcharts repository: https://github.com/apexcharts/vue-apexcharts/issues/91
There is a CodePen demo too.
