### ISSUE TITLE
Add Mobile Pan and zoom

### ISSUE THREAD

**Issue by AleXSR700** [apexcharts/apexcharts.js#3675]
### Description

Apexcharts currently does not allow paning and zooming on mobile devices.
This issue is a re-opening of this feature request as it was closed. This FR is continuously getting +1s.
https://github.com/apexcharts/apexcharts.js/issues/86

In 2023 mobile devices are key for productivity. Be it mobile phones or tablets.

Paning and zooming are key features of Apexcharts and should work in mobile devices.

### Steps to Reproduce

1. Open chart on mobile device
2. Try to pan and/or zoom
3. 

### Expected Behavior

Working just like on desktop devices.

### Actual Behavior

Not working.

**Comment by AleXSR700** [comment]
@bot: tell the devs, that we are all waiting ;-)

**Comment by bridgecode** [comment]
Can confirm, +1
Please add this feature.

**Comment by fjmobile** [comment]
@bot: Please add this feature.

**Comment by pastry777** [comment]
We have been waiting for several years... Please add this feature, if not with a touch, even with buttons... Thank you!!!

**Comment by brianlagunas** [comment]
We accept PRs

**Comment by matheo** [comment]
This seems released in `v4.1.0`:
https://github.com/apexcharts/apexcharts.js/releases/tag/v4.1.0

**Comment by vingerha** [comment]
@iandi09 I am using this in Home assistant and there it does not work, also this states that the icons are hidden, can you possibly elaborate if this actually works ? https://github.com/apexcharts/apexcharts.js/issues/5062
