### ISSUE TITLE
Bug on click in legend marker

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#368]
## Codepen

https://codepen.io/anon/pen/GeoVzq?editors=0010

## Explanation

**What is the behavior you expect?**
That the graphic obeys the click on the legend marker

**What is happening instead?**
If I click on the legend marker "test 1", the graphics will disappear.
But, if I click on "test 2", the behavior is correct.

**What error message are you getting?**
Nothing

**Comment by junedchhipa** [comment]
@juliorosseti Thanks for reporting the bug, just fixed it.
