### ISSUE TITLE
y-axis tooltips wrongly positioned

### ISSUE THREAD

**Issue by joshribakoff-sm** [apexcharts/apexcharts.js#3682]
Copying from https://github.com/apexcharts/apexcharts.js/issues/2556

I'm assuming the author closed my previous issue requesting to re-open that issue because it didn't follow the template? If they had left a comment instead of just closing it, I wouldn't have to assume. Here I've copy pasted the original person's issue, since the author apparently does not entertain requests to re-open existing issues.  I felt it was reasonable to assume you'd prefer that over just filing duplicate issues. Without communication, I'm not quite sure if you just don't want to hear about the bugs or something.

----

 # Bug report
 ## Codepen
 CodePen example of issue: https://codepen.io/benben_ik/pen/WNjmWOb
 
 ## Explanation
 * What is the behavior you expect?
   When crosshairs are enabled for grouped charts: Only the Y-axis tooltip of the chart a user is hovering is shown on a grouped chart. I do not expect to see Y-axis tooltips of both the chart I'm hovering and Y-axis tooltips of other grouped charts that do not belong to the chart I'm hovering.
 * What is happening instead?
   Instructions (see codepen): Create two or more grouped charts and enable crosshairs and Y-Axis tooltips on each chart. This results in all Y-Axis showing all Y-Axis tooltips of all grouped charts on each Y-Axis when hovering one of the charts. This overlap makes Y-Axis tooltips unreadable and confusing. It seems that the Y-axis crosshair keeps on drawing outside its frame.
   Example:
   ![grouped-charts-yaxis-crosshair-tooltips](https://user-images.githubusercontent.com/22481715/129415538-7b65025f-df4b-433d-9060-00482e2948bb.png)
 * What error message are you getting?
   There is no error message, there is just unexpected behaviour.
 
 Thank you for your time.

**Comment by brianlagunas** [comment]
> I'm assuming the author closed my previous issue requesting to re-open that issue because it didn't follow the template? 

You would be correct. You may have had that thought due to the instructions in the issue template.

If an issue needs to be reopened, please request it on the issue itself. Do not recreate another issue just pointing to the original. That would have been preferred. I will reopen the older issue, but in the future please continue to conversation on the original issue and do not recreate old issues. I'm closing this one to avoid the duplicate.
