### ISSUE TITLE
`legend.labels.colors` is documented as an `array`, but only works with a `string`

### ISSUE THREAD

**Issue by lindapaiste** [apexcharts/apexcharts.js#3691]
### Description

Using the `legend.labels.colors` option as described in the documentation does not work.  The docs say that it should be *"an array of colors where each index corresponds to the series index"*.

![image](https://user-images.githubusercontent.com/28965286/223804952-5554ab32-5b61-4f24-8c1b-1bd5389b569f.png)

However the code takes the entire value of the `legend.labels.colors` property, eg. the `array`, and assigns it to the `elLegendText.style.color` property.  This means we have a `span` element with `style.color = ['red', 'blue']` which is invalid and won't do anything (I'm surprised there's no warning in the console).

You can see the troublesome code here:
https://github.com/apexcharts/apexcharts.js/blob/050546ef20880bcff5afce102f8c3abcd445e99f/src/modules/legend/Legend.js#L196-L204

### Steps to Reproduce

Add this to the `options` of a multi-series chart:
```
legend: {
    labels: {
      colors: ["red", "blue"]
    }
  }
```

### Expected Behavior

I expect the first label in the legend to be colored red and the second to be blue.

### Actual Behavior

Both legend labels are black (the default).

### Screenshots

![image](https://user-images.githubusercontent.com/28965286/223806475-d91ceee7-5849-424b-af20-3ca45fe33487.png)

I am able to change all series labels to the *same* color if I use a `string` value for `legend.labels.colors`.  This is not documented, so it may or may not be a behavior that's worth preserving.
```
legend: {
    labels: {
      colors: "red"
    }
  }
```
![image](https://user-images.githubusercontent.com/28965286/223807276-d3e3172f-de9b-43f1-90f2-e74fd0b4235d.png)

It is impossible to set each label to a *unique* custom color.

### Reproduction Link

https://codepen.io/linda-paiste/pen/KKxXLpL

**Comment by junedchhipa** [comment]
closes with [commit](https://github.com/apexcharts/apexcharts.js/commit/9db63e41734a1c6fe5429b24c26e2a449542b538)
