### ISSUE TITLE
unexpected numbers occur when update theme.mode with computed

### ISSUE THREAD

**Issue by jchalex** [apexcharts/apexcharts.js#3692]
### Steps to Reproduce

vue dashboard demo
just add 
```ts
xxOption = computed(() => ({
  theme: {
    mode: modeStore.state.dark ? 'dark' : 'light',
  },
  chart: {
...
```

### Screenshots

1. init
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/11224001/223903050-737af8bc-c487-4860-ad39-b4005b2fb3aa.png">

2. to dark
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/11224001/223903175-8b393634-2e30-4613-829b-5f628221b321.png">

there are so many numbers occur in the left when

**Comment by brianlagunas** [comment]
Require repro link not provided
