### ISSUE TITLE
Feature Request: Sparklines tooltip sync

### ISSUE THREAD

**Issue by ludovicthomas** [apexcharts/apexcharts.js#37]
When using the Sparklines (or others graphic in a dasboard for example), it would be nice to be able to display the tooltip at the same on other graphs sharing the same X Axis.

It's the case in the sample Sales / Expenses / Profits, where on hover, it's good to see the Profits, but it's hard to see if it's based on increase of Sales or Expenses:
![cleanshot 2018-08-16 at 10 18 32 2x](https://user-images.githubusercontent.com/154572/44196979-be256980-a13d-11e8-9b68-dfdb5273cab4.png)

I understand a combined graph could resolved it, but it will not be as beautiful as 3 sparklines.

Perhaps adding an event for tooltip, and the ability to display the tooltip on another chart (like the sync charts method with `updateOptions`?).

Thanks for the library very helpful.

**Comment by junedchhipa** [comment]
Good suggestion.
I am thinking of making easier to sync similar charts by providing chart-ID in `options.sync` and that way user can input chartID in that array to sync charts which share a lot of things (xaxis in your case).

**Comment by ludovicthomas** [comment]
Would be amazing! If you need help, let me know would be interested to contribute.

**Comment by junedchhipa** [comment]
Here is a sneak peak of the grouped charts where zooming/panning as well tooltip will sync for charts having the same group.
![synced-tooltips](https://user-images.githubusercontent.com/17950663/46164217-0db59400-c2ab-11e8-8bf8-ab75effaec1d.gif)

Will provide demo/samples once I release a new build

**Comment by ludovicthomas** [comment]
Great news! It will be really useful. Thanks.
