### ISSUE TITLE
Restrict zoom with min\max values of an axis

### ISSUE THREAD

**Issue by xobotyi** [apexcharts/apexcharts.js#3701]
## Summary

Now it is possible to zoom-out\zoom-in away from axis conigured min\max values.

![image](https://user-images.githubusercontent.com/6178739/224804622-ee54d42b-7cd5-4c2d-ad81-0dee895b7b95.png)

On the screenshot above chart has `yaxis.min` configured to 0, but zuuming allows plot to be "scrolled" to negative values.

## API Changes

Add option like `chart.zoom.x.restrict` and `chart.zoom.y.restrict` to enable\disable zoom restriction wth configured axis min\max values.
And\or add option to restricti zooming to edge values on corresponding axis.

## Intended Use Case

Any chart with enabled zoom

**Comment by xobotyi** [comment]
bump?

**Comment by david-at-solve** [comment]
Would be great to have that "behavior" fixed somehow...

**Comment by chaskett** [comment]
This would be useful. I've users confused when zooming from years to seconds!
