### ISSUE TITLE
Add new function: setActiveSeries

### ISSUE THREAD

**Issue by DMOAbove** [apexcharts/apexcharts.js#3704]
## Summary

I have a table component that when I hover a row, I need to set on Apexcharts the correspondent series as active. 
So basically I want to mimic apexcharts hover effects on the series names, outside of it on a diferent component.

When we hover an series, it makes the serie active and the others with a lower opacity, I wanted to acheive the same when hovering a row on a table. But I was not able to find a way to set the active series programmatically.

We can only show/hide and toggle series, but we can't make them active only.

**Comment by brianlagunas** [comment]
Please do not double post https://github.com/apexcharts/apexcharts.js/discussions/3702

**Comment by DMOAbove** [comment]
It was not double post. One was asking for an solution/hack. And here it was for creating a new function. A feature.

**Comment by brianlagunas** [comment]
One was asking a question, the other is rephrasing the same question into a feature request.

**Comment by DMOAbove** [comment]
yes, but one is intended for the team the other for the community, or isnt that what the discussion tab is?

**Comment by brianlagunas** [comment]
Asking a question in the discussions for community help, then not waiting for a response, but rather immediately posting an issue asking for the same help from the team is viewed as a double post.
