### ISSUE TITLE
How to provide a custom radius size to a particular slice in donut

### ISSUE THREAD

**Issue by Hangvlin** [apexcharts/apexcharts.js#3707]
## Summary

I want to know how to modify the size of the selected part of donut and make it more prominent and far from the center of the circle compared with other unselected parts

## Intended Use Case

<img width="274" alt="截屏2023-03-14 21 57 36" src="https://user-images.githubusercontent.com/73342945/225024270-b05dc84e-5d5d-4a78-b2d1-eacb88d97e14.png">
Look at this picture. How to change the height of the highlighted part to make it more prominent?
Let the selected part expand more

**Comment by brianlagunas** [comment]
This is a question, not a feature request.
