### ISSUE TITLE
zoomed event not correct after beforeZoom

### ISSUE THREAD

**Issue by atoy40** [apexcharts/apexcharts.js#371]
Hello,

If you use beforeZoom to alter the zoom range, the zoomed event receive the original xaxis range but not the one modified by beforeZoom.

Anthony.

**Comment by junedchhipa** [comment]
Are you using the following format?

```javascript
chart: {
  events: {
    beforeZoom: function(ctx, opts) {
      return {
        xaxis: {
          min: new Date('28 Jan 2013').getTime(),
          max: new Date('27 Feb 2013').getTime(),
        }
      }
    }
  }
}
```
The above method works as expected.

Please post a working codepen if you're experiencing issues.

**Comment by atoy40** [comment]
@junedchhipa this part works, but now, add a "zoomed" event, and check the xaxis object it receive as parameter. In my case I get the original range (the one you received in beforeZoom too) but not the range modified by berforeZoom.

Anthony.

**Comment by junedchhipa** [comment]
Got the point, thanks for the clarification. Just fixed it.
