### ISSUE TITLE
browser console error when rendering circular charts in Firefox and Chrome (TypeError: t[f] is null)

### ISSUE THREAD

**Issue by Thomas-1985** [apexcharts/apexcharts.js#3711]
### Description

npm: 3.37.0
browser: Firefox 110.0.1 (Chrome also throws an error)
vue: 2.6.11

I am using apexchars to display some circle charts and whenever i open the view in my app, the charts are displayed but there is an error on the browser console.

### Steps to Reproduce

```
import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.use(VueApexCharts)

Vue.component('apexchart', VueApexCharts)
```

chart.vue
```
<template>
  <apexchart
    type="donut"
    :options="options"
    :series="chartdata.series"
  ></apexchart>
</template>
<script>
export default {
  name: 'Chart',
  props: {
    chartdata: {
      type: Object,
      default: null
    },
    options: {
      type: Object,
      default: null
    }
  },
  data() {
    return {
    }
  }
};
</script>

<style lang="scss">
</style>

```

then i use it inside my component
```
...
<v-row>
  <v-col
    v-for="(item, i) in chartData"
    :key="i"
    class="chart-col"
  >
    <Chart
      :chartdata="item.chartData"
      :options="item.options"
    />
  </v-col>
</v-row>
```

### Expected Behavior
There should be the charts but no browser console error

### Actual Behavior
The charts are rendered but there is a browser console error

### Screenshots

![apexcharts bug](https://user-images.githubusercontent.com/9249624/225126022-6f0615b3-feb3-48eb-89ef-5aad230af2ff.png)

**Comment by brianlagunas** [comment]
required repro app missing
