### ISSUE TITLE
Series containing a value 0 throw error in 3.37.1

### ISSUE THREAD

**Issue by nicobatalla** [apexcharts/apexcharts.js#3712]
### Description
Charts containing series data with 0 value(s) throws error in console

### Steps to Reproduce

1.  Add a chart with a series containing a value with 0 count
2. Watch the console

### Expected Behavior
- Chart renders fine
- Console shows no error

### Actual Behavior
- Chart renders fine
- Console is throwing an error:

```
apexcharts:10 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at s (apexcharts:10:11993)
    at Et.a.PathArray.morph (apexcharts:10:12158)
    at create.initAnimations (apexcharts:6:410702)
    at create.startCurrent (apexcharts:6:410012)
    at create.start (apexcharts:6:409811)
    at create.dequeue (apexcharts:6:410335)
    at create.step (apexcharts:6:413282)
    at create.<anonymous> (apexcharts:6:409646)
```

### Screenshots
![image](https://user-images.githubusercontent.com/25337921/225147733-7fe4e808-9d24-49dd-8a47-d0194a2c0adb.png)

### Reproduction Link
https://codepen.io/nicobatalla/pen/BaOreNL

**Comment by RuSS-B** [comment]
Having same issue when I do Bar chart

**Comment by JulioC** [comment]
In the case show in this issue, it doesn't throw an error, instead it generates paths with invalid coordinates:

https://github.com/apexcharts/apexcharts.js/issues/1945

**Comment by nicobatalla** [comment]
There's no path or type error in `3.37.0`.

It is a regression on `3.37.1`
