### ISSUE TITLE
Tooltip options not working for pie, donut, radialbar charts

### ISSUE THREAD

**Issue by pvh-archifact** [apexcharts/apexcharts.js#3717]
### Description

Adding tooltip options to Pie/Donut and radialBar charts do not work as expected. If this is by design it should be noted in the documentation. If the tooltip options are only available to certain chart types, i would suggest to move the specific tooltip options object to the  plotOptions.[name-of-Chart] object.

### Steps to Reproduce

1.  Create a pie/donut/radialbar chart
2.  Add tooltip options: followCursor:false and/or fixed:{enabeld:true,position:'bottomRight'}
3.  hover over chart.

### Expected Behavior
Not following cursor when moving over chart, Fixed static position of tooltip on selected position on chart
### Actual Behavior
tooltip follows cursor while hovering over chart, no fixing tooltip position, tooltip always above cursor, PositionX or PositionY also has no effect. 

### Reproduction Link
[https://codepen.io/PlippiePlop/pen/Podadwa](Example)

**Comment by stepantsuk** [comment]
I have the same problem... is there any idea to solve it ? ))

**Comment by Shahekta51995** [comment]
I am also facing same issue.

**Comment by dlibis** [comment]
me too

**Comment by IlyaKorn** [comment]
any solutions? I have the same problem, some property works for donut tooltip, some aren't.

**Comment by BahirHakimy** [comment]
Any Updates?

**Comment by junedchhipa** [comment]
`followCursor` option doesn't have any effect in pie/donut/radialbar/treemap/heatmap charts.
Updated [docs](https://apexcharts.com/docs/options/tooltip#followCursor) mentioning the same.
