### ISSUE TITLE
Version 3.37.1 dealing with Zero

### ISSUE THREAD

**Issue by MaddestMax76** [apexcharts/apexcharts.js#3722]
### Description

Starting from  3.37.1 Zeros are not displayed anymore:

https://jsfiddle.net/Max1976/k5aqdzc8/1/ - Zeros are displayed
https://jsfiddle.net/Max1976/k5aqdzc8/2/ - No Zeros any more - columns are missing

You can see in the last two columns füor 'Tangerines' and 'sasfdsf'. Only change ist from 3.37.1 to 3.37.0

Same on codepen:
https://codepen.io/Max76/pen/RwYYgYR
-> i did not mange to alter this, but when you change the source same thing happens

Max

**Comment by nicobatalla** [comment]
I think this is related to https://github.com/apexcharts/apexcharts.js/issues/3712 and https://github.com/apexcharts/apexcharts.js/issues/3686
