### ISSUE TITLE
I'm having issues with mouseover on a line chart with null values.

### ISSUE THREAD

**Issue by renanloboz** [apexcharts/apexcharts.js#3732]
### Description
The lines are rendering perfectly fine. However, when I mouseover, the points disappear and when I move the mouse away from the chart, some points appear even though they don't exist in the data.

### Steps to Reproduce

1. Hover over the points to see information.
2. Move the mouse away from the chart.

### Expected Behavior
The single points should remain even after hovering over them. Also, when moving the mouse away from the chart, the display of information should continue as the initial rendering of lines and points.

### Actual Behavior
When hovering over the single points, they disappear. Additionally, when moving the mouse away from the chart, non-existent points appear in series.

### Screenshots
https://user-images.githubusercontent.com/120129007/227069160-9796065b-53a5-484e-a7e5-8e31889390e4.mov

### Reproduction Link
https://codepen.io/renanzucheratto/pen/mdGQmYQ

**Comment by BrunoAssis** [comment]
Same issue here!
