### ISSUE TITLE
isFormatXY Bug

### ISSUE THREAD

**Issue by mustafaomereser** [apexcharts/apexcharts.js#3739]
1.  click to hide 1. data set
2.  click to hide 2. data set
3.  click to hide 3. data set
4. and chart is gone

{
        key: "isFormatXY",
        value: function () {
          var t = this.w.config.series.slice()
            , e = new M(this.ctx);
          if (this.activeSeriesIndex = e.getActiveConfigSeriesIndex(),
            void 0 !== t[this.activeSeriesIndex].data && t[this.activeSeriesIndex].data.length > 0 && null !== t[this.activeSeriesIndex].data[0] && void 0 !== t[this.activeSeriesIndex].data[0].x && null !== t[this.activeSeriesIndex].data[0])
            return !0
        }

that to must

{
        key: "isFormatXY",
        value: function () {
          var t = this.w.config.series.slice()
            , e = new M(this.ctx);
          if (this.activeSeriesIndex = e.getActiveConfigSeriesIndex(),
            void 0 !== t[this.activeSeriesIndex].data && t[this.activeSeriesIndex].data.length > 0 && null !== t[this.activeSeriesIndex].data[0] && void 0 !== t[this.activeSeriesIndex].data[0]?.x && null !== t[this.activeSeriesIndex].data[0])
            return !0
        }

**Comment by mustafaomereser** [comment]
![image](https://user-images.githubusercontent.com/29175021/227526047-b91b1908-cf0f-49d9-a2d6-701bcb405ee5.png)
![image](https://user-images.githubusercontent.com/29175021/227526068-7f6ed607-1f90-4bec-b8ca-ca05990bb59e.png)
![image](https://user-images.githubusercontent.com/29175021/227526091-807ade57-3b45-4e6e-ae83-9434852bfddf.png)
![image](https://user-images.githubusercontent.com/29175021/227526112-6e135d8f-0158-4545-a4fb-f4c8be8a8d19.png)

when i click green one its gone... and i fix it like my solution

**Comment by brianlagunas** [comment]
Did not follow issue template instructions

**Comment by mustafaomereser** [comment]
> 

yeah but still have bug your code 👍
