### ISSUE TITLE
Custom Tooltip is blank/empty

### ISSUE THREAD

**Issue by ivorycoast** [apexcharts/apexcharts.js#3741]
Hello guys,

### Description

I use custom tooltips for my web application, but the tooltips are empty. After a page refresh, they appear...

I use this code to create custom tooltips
```
tooltip: {
  enabled: true,
  custom: function({series, seriesIndex, dataPointIndex, w}) {
    return '<div class="arrow_box">' +
      '<span>' + w.config.labels[seriesIndex] + '</span>' +
      '</div>'
  }
}
```
### Steps to Reproduce

1.  Use the code above

### Expected Behavior

Showing the content of the tooltip

### Actual Behavior

Nothing inside the tooltip

### Screenshots

![ratio](https://user-images.githubusercontent.com/2655756/201942587-5274e62d-fbb3-44ed-ab88-859b054c9cf4.png)

**Comment by brianlagunas** [comment]
Reproduction app not provided
