### ISSUE TITLE
Opposite y-axis ignored in a horizontal bar chart

### ISSUE THREAD

**Issue by ignaciojcano** [apexcharts/apexcharts.js#375]
## Codepen

https://codepen.io/anon/pen/OqRXGB?editors=0010

## Explanation

Want to render categories on the right side, they are currently on the left side (S Korea, Canada...)

- What is the behavior you expect?
Setting `yaxis: { opposite:true }` would render the categories on the right side.
- What is happening instead?
It rendered on the left side
- What error message are you getting?
None, but it only happens when: 
```javascript
bar: {
  horizontal: true 
},
```

**Comment by junedchhipa** [comment]
Opposite y-axis on a horizontal bar chart is not supported currently.

As the whole calculation to make bars would require a lot of code just to draw it inversed, this feature will not be implemented in the near future.

**Comment by ignaciojcano** [comment]
Any workarounds?

**Comment by junedchhipa** [comment]
Sorry, can't think of any way to achieve this with the current codebase.

**Comment by junedchhipa** [comment]
Hi, I just tried drawing the bars opposite way and it was really easy to tweak with some additional code :)

![screen shot 2019-03-08 at 3 30 37 pm](https://user-images.githubusercontent.com/17950663/54021863-1ba30580-41b7-11e9-9a08-5b95dc6918f3.png)

I will test some more, draw the y-axis to the opposite too and will release the feature soon.

**Comment by ignaciojcano** [comment]
Awesome! Thanks for the great work!

**Comment by junedchhipa** [comment]
Released in 3.6.1

**Comment by ignaciojcano** [comment]
Awesome, will take a look at it!
