### ISSUE TITLE
Border radius not working for stacked bar charts

### ISSUE THREAD

**Issue by pertzy18** [apexcharts/apexcharts.js#3753]
### Steps to Reproduce

1. Create a stacked bar chart
2. Specify a border radius greater than zero
3. Each segment of the bar is rounded instead of the entire bar

### Expected Behavior

![image](https://user-images.githubusercontent.com/113181020/229723671-bf590e19-1d2b-48b0-b5cc-174912bb1067.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/113181020/229723352-7b9be8f7-e16a-465b-bdb4-20ad0b327b85.png)

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
