### ISSUE TITLE
X-Axis border not working

### ISSUE THREAD

**Issue by valentinoConti** [apexcharts/apexcharts.js#3755]
### Description

On the last apex charts release (3.37) a bug was introduced: the xaxis axisBorder doesn't work.

### Steps to Reproduce

1) Save the following code as a HTML file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>X AXIS NOT WORKING EXAMPLE</title>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.36.0/dist/apexcharts.min.js"></script> -->
  </head>
  <body>
    <div id="chart"></div>
    <script>
      var options = {
        chart: {
          type: "area",
          height: 350,
          toolbar: {
            show: false,
          },
        },
        series: [
          {
            name: "Series 1",
            data: [31, 40, 28, 51, 42, 109, 100],
          },
        ],
        xaxis: {
          categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
          axisBorder: {
            show: true, // should show the X axis border, a big one
            color: "#78909c",
            height: 4,
            width: "100%",
            offsetY: -1,
          },
          labels: {
            show: true,
          },
        },
        yaxis: {
          axisBorder: {
            show: true, // show y-axis line
          },
          labels: {
            show: true, // show y-axis labels
          },
        },
        grid: {
          show: false, // hide grid
        },
        dataLabels: {
          enabled: false, // hide data labels
        },
        stroke: {
          curve: "smooth", // make the chart area smooth
        },
      };
      var chart = new ApexCharts(document.querySelector("#chart"), options);
      chart.render();
    </script>
  </body>
</html>
```

2) Open the HTML, observe the X axis not being visible.

3) Comment the script importing the library on its latest version, and uncomment the script importing the library on its 3.36.0 version

4) Open the HTML, the X axis border is there.

### Screenshots

Expected (3.36.0)
<img width="732" alt="Screenshot 2023-04-04 at 15 48 29" src="https://user-images.githubusercontent.com/41705567/229925725-b5534bab-b16e-44f1-b257-f286431f82f7.png">

Current (3.37.3)
<img width="731" alt="Screenshot 2023-04-04 at 15 48 53" src="https://user-images.githubusercontent.com/41705567/229925761-96ffa6b9-c53b-481b-b817-308875b22ede.png">

### More Info

I have not enough time for now to try to understand the codebase and find where the bug was introduced, but looking at the diff between the versions I think this looks like a big possibility:

<img width="1176" alt="Screenshot 2023-04-04 at 15 57 37" src="https://user-images.githubusercontent.com/41705567/229925367-85419387-0304-4d4b-b083-ade022e379da.png">

Also, I'm using apexcharts trough react-apexcharts, and after forcing the apexcharts version to 3.36.0, the x axis border started working, but the `strokeWidth` property on `xAxis: { axisBorder: { strokeWidth:` doesn't work, the border line it's always 1px, that is fine on my particular case but you maybe want to take a look on that too.

I'll stick the 3.36.0 version on my package.json for now but I'll keep an eye on this issue to update

Thanks for the amazing library! cheers 🥂

**Comment by brianlagunas** [comment]
Please provide the required reproduction link or this issue will be closed

**Comment by valentinoConti** [comment]
Uhmm ok, I guess I can copy paste the HTML on codepen for you

With newer version, current stuff: https://codepen.io/valentinoConti/pen/WNaeXBX
With previous version, expected stuff: https://codepen.io/valentinoConti/pen/JjmPOVQ

there you go 👍🏼
