### ISSUE TITLE
Panning is broken

### ISSUE THREAD

**Issue by csigmanek** [apexcharts/apexcharts.js#3757]
### Description

When panning, the chart first jumps slightly to the left, before sliding into the desired direction.
Furthermore, sliding is extremely laggy and slow when having about 5000 data points. It's getting only worse if you add more.

### Steps to Reproduce
1. zoom in
2. pan to left or right

### Expected Behavior
Chart should not jump.
Chart panning should be smooth. If fewer points are in the visible area, it should render faster than if there are more points in the viewing area.

### Actual Behavior
Chart jumps to the left before moving to the right when panning to the righthand side.
Chart panning is laggy. 3 Series with 5-10k points each and you will have about 1-2 FPS. It doesn't matter how far you zoomed in.

### Reproduction Link

// use this one to see the jumping to the left before sliding to the right while panning to the right. It's easier to see if you have a slow pc.
https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/

// disclaimer: At least on my pc, the codepen performs even worse than using it normally. You don't see any sliding there
https://codepen.io/szynja/pen/VwEwzdj
if you have any running instance, you can use these series for rendering a few points:
```
const serie1 = [];
  const serie2 = [];
  const serie3 = [];
  for (var i = 0; i < 10000; i++) {
    var base = 10 * Math.sin(i / 90.0);
    if (i > 2500) serie1.push([i, base]);
    serie2.push([i, i / 600 - 5]);
    serie3.push([
      i,
      -2.0008253015634962e-10 * i ** 3 + 0.0000029013204825015935 * i ** 2 + -0.00990651988235162 * i ** 1 + 5.009903618761952 * i ** 0,
    ]);
  }

// applying the series
.updateSeries([{ data: serie1 }, { data: serie2 }, { data: serie3 }]
```

**Comment by fracz** [comment]
The panning is broken on the column charts, too, but in a different way. At some levels of zoom it just does not react to panning.

Try this on e.g. https://apexcharts.com/javascript-chart-demos/column-charts/stacked/

1. Zoom only the last bar (with 92 on the toop).
2. Switch to pan tool. It works.
3. Zoom out with the minus button. Panning works.
4. Zoom out again. Panning does not work.

**Comment by csigmanek** [comment]
@fracz interesting to see. Aparently, line charts do have the same problem. Panning does not work on line charts if there are no known values on one side. Because of the jumping, you cannot pan to the righthand side, if there are no values on the lefthand side.
The column chart is jumping briefly to the left side too, when panning to the right.
