### ISSUE TITLE
Toggling first series on line chart causes chart width to shift/expand

### ISSUE THREAD

**Issue by joseph-simpkins-prft** [apexcharts/apexcharts.js#3766]
### Description

For a multi-series line chart (and bar chart), the chart changes size (right end shifts to the right) when toggling off the first series.  The issue first appeared in version 3.11.1, and has continued to be an annoyance since then.  We have tried all sorts of ideas to prevent the shift, but it seems to be an issue with the library itself.  (We are using the JS library.)

### Steps to Reproduce

Toggle the first series on and off to see the chart width shift back and forth.

### Expected Behavior

The chart width should not shift at all, when toggling any of the series.

### Actual Behavior

The chart width shifts when toggling the first series on/off.

### Screenshots

Refer to behavior on official demo pages.

### Reproduction Link

You can see the shifting behavior on the official demo pages here:
https://apexcharts.com/javascript-chart-demos/line-charts/dashed/
https://apexcharts.com/javascript-chart-demos/bar-charts/stacked/

**Comment by junedchhipa** [comment]
thanks for reporting, fixed it.
