### ISSUE TITLE
Scatter Chart Bug When Using XY properties

### ISSUE THREAD

**Issue by NicholaAlkhouri** [apexcharts/apexcharts.js#3768]
### Description

The Scatter chart display data points in a wrong way if passed as XY Properties. however when changed into numeric 2 dimensional array it works well
This happen for a specific set of values (I couldn't find a pattern).

### Steps to Reproduce
1- Add a simple scatter chart
2- Add a simple data series as XY properties `{x,y}`

Reproduction codepen : https://codepen.io/NicholaAlkhouri/pen/wvYWgRj

In the reproduction the "Sample B" data points are displayed wrongly, should be in 5 and 6 X coordinates, but displayed on the 1 and 2.
when changed to 2 dimensional array it works well

### Expected Behavior
The data points to be displayed in the correct position

### Actual Behavior
The data points are displayed in a weird random way

### Screenshots

This is Wrong
![Screenshot 2023-04-17 at 13 24 33](https://user-images.githubusercontent.com/6449090/232473696-3068bc16-6be6-4efd-9a90-356d67591839.png)

This is Correct
![Screenshot 2023-04-17 at 13 25 07](https://user-images.githubusercontent.com/6449090/232473736-8ab3b998-3578-4730-8d32-b8aa5e7af3ad.png)

### Reproduction Link

https://codepen.io/NicholaAlkhouri/pen/wvYWgRj

**Comment by kitro** [comment]
I have the same issue when specifying x, y, for example, using this series:
```
            series: [
                {
                    name: "Expenses",
                    color: 'red',
                    data: [
                        {
                            x: "02/2023",
                            y: 1200
                        },
                        {
                            x: "05/2023",
                            y: 100
                        },
                    ]
                },
                {
                    name: "Incomes",
                    color: 'green',
                    data: [
                        {
                            x: "01/2023",
                            y: 3000
                        },
                        {
                            x: "03/2023",
                            y: 50
                        },
                    ]
                }
            ],
``` 

The second series was rendered in the wrong x-axis and their x values were not represented at all in the x-axis.

<img width="1189" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/5256921/4dad7928-12a3-4622-af6c-723c0fa16286">

Using an array rendered an empty chart 
```
            series: [
                {
                    name: "Expenses",
                    color: 'red',
                    data: [
                        [
                            "02/2023",
                            1200
                        ],
                        [
                            "05/2023",
                            100
                        ],
                    ]
                },
                {
                    name: "Incomes",
                    color: 'green',
                    data: [
                        [
                            "01/2023",
                            3000
                        ],
                        [
                            "03/2023",
                            50
                        ],
                    ]
                }
            ],
```

<img width="1176" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/5256921/194b95ef-732a-42d2-a064-8c5da2fbcdeb">

Even when trying to force the categories in `option.xaxis.categories` 
``categories: ['01/2023', '02/2023', '03/2023', '05/2023']`` same first issue happened.

Thank you!

**Comment by junedchhipa** [comment]
The original issue seems to be fixed in the latest version of ApexCharts (tested with v3.49.1)
Closing it.
