### ISSUE TITLE
[BUG] [mixing] Multi line area with zero and negatives values - markers on hover doesn't exsist

### ISSUE THREAD

**Issue by aure369** [apexcharts/apexcharts.js#377]
Simple in area with multi line, negatives values or/and zero values is skipping as markers on hover. (a little was analyse source code). 

sorry for bad English. i am try write fast asap and explain this bug.

## Codepen

In codepen was added fully configuration of chart plus demo data what to me is buggy.

https://codepen.io/aure369/pen/pYNgJM

## solution

In function: getNearestValues

Where is to variables "seriesXValArr = seriesXValArr.map" and "seriesYValArr = w.globals.seriesYvalues.map"  assign value must be not filtered

> If i was friendly and helpful please follow me. :)

**Comment by junedchhipa** [comment]
Thanks for reporting. I have identified the bug and fixed it. The patch will be released soon.
