### ISSUE TITLE
yaxis inverted and bars not showing on mobile

### ISSUE THREAD

**Issue by ordago** [apexcharts/apexcharts.js#378]
## Codepen

https://codepen.io/ordago/pen/pYNNye

![photo6050688199791062835](https://user-images.githubusercontent.com/6376814/53820254-4a28a280-3f63-11e9-9f44-ae19cbf46870.jpg)

## Explanation

The codepen has the code how I have it in my project, but I don't see the problem when I opened the codepen on my phone.

- What is the behavior you expect?
To see it as seen when using Chrome responsive mode:

![chrome_2019-03-05_13-12-56](https://user-images.githubusercontent.com/6376814/53820574-f10d3e80-3f63-11e9-8ff1-083adf123e6a.png)

- What is happening instead?

The bars are not showing and the yaxis is inverted. In desktop works as expected.

- What error message are you getting?

None.

Edit: 

Changing the chart height to 550 made the chart bars appear and yaxis to have its normal direction but the chart is squeezed at the top and the legend way down below:

![photo6050688199791062868](https://user-images.githubusercontent.com/6376814/53823091-f7ea8000-3f68-11e9-8f57-9692e1b8fc35.jpg)

**Comment by junedchhipa** [comment]
I tested in mobile browsers (Android chrome as well as iPhone chrome) and the chart renders correctly on both the devices with legends taking up normal space. 

I suspect the problem is with legend calculation, so if it causing issues for you, try setting the height of each legend item with CSS as the legend is drawn with HTML.

**Comment by ordago** [comment]
Hi @junedchhipa , thanks for replying

I've got more clues. I used [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) with Chrome. 

> Error: <rect> attribute height: A negative value is not valid. ("-164.652")

The console says that and points to 

`"leading" == e ? this.leading && this.leading(i) : "string" == typeof a ? this.node.setAttributeNS(a, e, i.toString()) : this.node.setAttribute(e, i.toString()),`

---

There is a line in the css `line-height: 1.5em;` for h4 .h4 

It now works, this patched it:

```
<style>
    .apexcharts-legend-series {
        line-height: normal;
    }
</style>
```

**Comment by junedchhipa** [comment]
Thanks for the clue! I will apply the same patch and even look for the error > Error: attribute height: A negative value is not valid. ("-164.652")
