### ISSUE TITLE
one column occupying space of two

### ISSUE THREAD

**Issue by jvhk** [apexcharts/apexcharts.js#3782]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/3781

<div type='discussions-op-text'>

<sup>Originally posted by **jvhk** April 20, 2023</sup>
In some more specific situations in a distributed graph where there is column A and column B when column B has a value of 0% column B is occupying the width of the two columns instead of just occupying the width of itself. This way the datalabel is unconfigured. What configuration of [options.dataLabels](https://apexcharts.com/docs/options/datalabels/) could be generating this?

![image](https://user-images.githubusercontent.com/31265819/233494458-af688bae-56a2-42b7-bb34-8e72c3c707ca.png)
</div>

**Comment by jvhk** [comment]
why my issue was closed?

**Comment by brianlagunas** [comment]
Because you are trying to double post a discussion.

**Comment by jvhk** [comment]
ok, i understood. Thank you @brianlagunas
