### ISSUE TITLE
Misrendering dataLabel on stacked horizontal bar chart after deselecting series

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#379]
## Screenshot
![screen shot 2019-03-06 at 4 57 25 pm](https://user-images.githubusercontent.com/31082405/53924590-76125980-4031-11e9-92bc-0a6c9aebd88a.png)
series: [
{data: [{x: "blank", y: 72, numPatients: 552},
{x: "blank", y: 47, numPatients: 424},
{x: "blank", y: 33, numPatients: 353},
{x: "blank", y: 18, numPatients: 228},
{x: "blank", y: 16, numPatients: 177},
{x: "blank", y: 23, numPatients: 177},
{x: "blank", y: 13, numPatients: 146},
{x: "blank", y: 14, numPatients: 125},
{x: "blank", y: 14, numPatients: 109},
{x: "blank", y: 9, numPatients: 85},
 {x: "blank", y: 14, numPatients: 69},
 {x: "blank", y: 5, numPatients: 55},
 {x: "blank", y: 4, numPatients: 53},
 {x: "blank", y: 2, numPatients: 37},
 {x: "blank", y: 3, numPatients: 34},
 {x: "blank", y: 0, numPatients: 33},
 {x: "blank", y: 8, numPatients: 31},
 {x: "blank", y: 5, numPatients: 24},
 {x: "blank", y: 0, numPatients: 22},
 {x: "blank", y: 1, numPatients: 21},
 {x: "blank", y: 0, numPatients: 18},
 {x: "blank", y: 0, numPatients: 17},
 {x: "blank", y: 2, numPatients: 15},
 {x: "blank", y: 1, numPatients: 6},
 {x: "blank", y: 0, numPatients: 5},
 {x: "blank", y: 1, numPatients: 1}],
 name: 'complete health profile'},
{data: [{x: "blank", y: 480, numPatients: 552},
{x: "blank", y: 377, numPatients: 424},
{x: "blank", y: 320, numPatients: 353},
{x: "blank", y: 210, numPatients: 228},
{x: "blank", y: 161, numPatients: 177},
{x: "blank", y: 154, numPatients: 177},
{x: "blank", y: 133, numPatients: 146},
{x: "blank", y: 111, numPatients: 125},
{x: "blank", y: 95, numPatients: 109},
{x: "blank", y: 76, numPatients: 85},
 {x: "blank", y: 55, numPatients: 69},
 {x: "blank", y: 50, numPatients: 55},
 {x: "blank", y: 49, numPatients: 53},
 {x: "blank", y: 35, numPatients: 37},
 {x: "blank", y: 31, numPatients: 34},
 {x: "blank", y: 33, numPatients: 33},
 {x: "blank", y: 23, numPatients: 31},
 {x: "blank", y: 19, numPatients: 24},
 {x: "blank", y: 22, numPatients: 22},
 {x: "blank", y: 20, numPatients: 21},
 {x: "blank", y: 18, numPatients: 18},
 {x: "blank", y: 17, numPatients: 17},
 {x: "blank", y: 13, numPatients: 15},
 {x: "blank", y: 5, numPatients: 6},
 {x: "blank", y: 5, numPatients: 5},
 {x: "blank", y: 0, numPatients: 1}],
 name: 'incomplete health profile'}]
(blank is a removed name)

It seems that deselecting the first series causes issues with the y axis data labels and the sidebar labels.

**Comment by junedchhipa** [comment]
![screen shot 2019-03-07 at 6 33 11 pm](https://user-images.githubusercontent.com/17950663/53958587-711fd980-4107-11e9-8968-e022dcf07a47.png)

Works fine for me.
Can you create a codepen demo, please?

**Comment by ThinkSalat** [comment]
Hi @junedchhipa,

I wasn't able to replicate this in codepen. However, I can't seem to figure out why this could be happening. Where in the codebase could I look to see where tis is happening? For example, why would it be displaying the wrong information on the yaxis labels?

We're using React-dom v16.8.1 and react version 16.8.1 if that makes any difference.


the following message will contain what I get when  look at the w.config that is passed into the tooltip/legend formatter/renderer:

(Btw, I tried adding a custom tooltip function that just console logs the arguments that are passesd to it, and return a '<div>tooltip</div>', and it crashes saying it can't access 'show' of undefined)

**Comment by ThinkSalat** [comment]
annotations: {
      < /br>position: front; </br > yaxis: {
        < /br>}xaxis: { </br >
      }
      points: {
        < /br>}}chart: { </br > animations: {
          < /br>enabled: { </br >
        }
        easing: swing; < /br>speed: { </br >
      }
      animateGradually: {
        < /br>delay: { </br >
      }
      enabled: {
        < /br>}}dynamicAnimation: { </br > enabled: {
          < /br>}speed: { </br >
        }
      }
    }
    background: transparent; < /br>locales: { </br > 0: {
        < /br>name: en; </br > options: {
          < /br>months: { </br > 0: January; < /br>1: February; </br > 2: March; < /br>3: April; </br > 4: May; < /br>5: June; </br > 6: July; < /br>7: August; </br > 8: September; < /br>9: October; </br > 10: November; < /br>11: December; </br >
        }
        shortMonths: {
          < /br>0: Jan; </br > 1: Feb; < /br>2: Mar; </br > 3: Apr; < /br>4: May; </br > 5: Jun; < /br>6: Jul; </br > 7: Aug; < /br>8: Sep; </br > 9: Oct; < /br>10: Nov; </br > 11: Dec; < /br>}days: { </br > 0: Sunday; < /br>1: Monday; </br > 2: Tuesday; < /br>3: Wednesday; </br > 4: Thursday; < /br>5: Friday; </br > 6: Saturday; < /br>}shortDays: { </br > 0: Sun; < /br>1: Mon; </br > 2: Tue; < /br>3: Wed; </br > 4: Thu; < /br>5: Fri; </br > 6: Sat; < /br>}toolbar: { </br > exportToSVG: Download SVG; < /br>exportToPNG: Download PNG; </br > menu: Menu; < /br>selection: Selection; </br > selectionZoom: Selection Zoom; < /br>zoomIn: Zoom In; </br > zoomOut: Zoom Out; < /br>pan: Panning; </br > reset: Reset Zoom; < /br>}}}}defaultLocale: en; </br > dropShadow: {
            < /br>enabled: { </br >
          }
          enabledSeries: {
            < /br>}top: { </br >
          }
          left: {
            < /br>}blur: { </br >
          }
          opacity: {
            < /br>}}events: { </br > animationEnd: {
              < /br>}beforeMount: { </br >
            }
            mounted: {
              < /br>}updated: { </br >
            }
            click: {
              < /br>}legendClick: { </br >
            }
            selection: {
              < /br>}dataPointSelection: { </br >
            }
            dataPointMouseEnter: {
              < /br>}dataPointMouseLeave: { </br >
            }
            beforeZoom: {
              < /br>}zoomed: { </br >
            }
            scrolled: {
              < /br>}}foreColor: #373d3f; </br > fontFamily: Quicksand,
              Times New Roman,
              Times,
              serif,
              sans - serif; < /br>height: { </br >
            }
            id: {
              < /br>}offsetX: { </br >
            }
            offsetY: {
              < /br>}selection: { </br > enabled: {
                < /br>}type: x; </br > fill: {
                  < /br>color: #24292e; </br > opacity: {
                    < /br>}}stroke: { </br > width: {
                      < /br>}color: #24292e; </br > opacity: {
                        < /br>}dashArray: { </br >
                      }
                    }
                    xaxis: {
                      < /br>min: { </br >
                    }
                    max: {
                      < /br>}}yaxis: { </br > min: {
                        < /br>}max: { </br >
                      }
                    }
                  }
                  sparkline: {
                    < /br>enabled: { </br >
                  }
                }
                brush: {
                  < /br>enabled: { </br >
                }
                target: {
                  < /br>}}stacked: { </br >
                }
                stackType: normal; < /br>toolbar: { </br > show: {
                  < /br>}tools: { </br > download: {
                    < /br>}selection: { </br >
                  }
                  zoom: {
                    < /br>}zoomin: { </br >
                  }
                  zoomout: {
                    < /br>}pan: { </br >
                  }
                  reset: {
                    < /br>}}autoSelected: zoom; </br >
                  }
                  type: bar; < /br>updateOnElementResize: { </br >
                }
                width: {
                  < /br>}zoom: { </br > enabled: {
                    < /br>}type: x; </br > zoomedArea: {
                      < /br>fill: { </br > color: #90CAF9; </br>opacity: { </br>}}stroke: { </br>color: # 0 D47A1; < /br>opacity: { </br >
                    }
                    width: {
                      < /br>}}}}}plotOptions: { </br > bar: {
                        < /br>horizontal: { </br >
                      }
                      endingShape: flat; < /br>columnWidth: 70%; </br > barHeight: 70 % ; < /br>distributed: { </br >
                    }
                    colors: {
                      < /br>ranges: { </br >
                    }
                    backgroundBarColors: {
                      < /br>}backgroundBarOpacity: { </br >
                    }
                  }
                  dataLabels: {
                    < /br>position: center; </br >
                  }
                }
                candlestick: {
                  < /br>colors: { </br > upward: #00B746; </br>downward: # EF403C; < /br>}wick: { </br > useFillColor: {
                    < /br>}}}heatmap: { </br > radius: {
                      < /br>}enableShades: { </br >
                    }
                    shadeIntensity: {
                      < /br>}distributed: { </br >
                    }
                    colorScale: {
                      < /br>inverse: { </br >
                    }
                    ranges: {
                      < /br>}min: { </br >
                    }
                    max: {
                      < /br>}}}radialBar: { </br > size: {
                        < /br>}inverseOrder: { </br >
                      }
                      startAngle: {
                        < /br>}endAngle: { </br >
                      }
                      offsetX: {
                        < /br>}offsetY: { </br >
                      }
                      hollow: {
                        < /br>margin: { </br >
                      }
                      size: 50 % ; < /br>background: transparent; </br > image: {
                        < /br>}imageWidth: { </br >
                      }
                      imageHeight: {
                        < /br>}imageOffsetX: { </br >
                      }
                      imageOffsetY: {
                        < /br>}imageClipped: { </br >
                      }
                      position: front; < /br>dropShadow: { </br > enabled: {
                        < /br>}top: { </br >
                      }
                      left: {
                        < /br>}blur: { </br >
                      }
                      opacity: {
                        < /br>}}}track: { </br > show: {
                          < /br>}startAngle: { </br >
                        }
                        endAngle: {
                          < /br>}background: #f2f2f2; </br > strokeWidth: 97 % ; < /br>opacity: { </br >
                        }
                        margin: {
                          < /br>}dropShadow: { </br > enabled: {
                            < /br>}top: { </br >
                          }
                          left: {
                            < /br>}blur: { </br >
                          }
                          opacity: {
                            < /br>}}}dataLabels: { </br > show: {
                              < /br>}name: { </br > show: {
                                < /br>}fontSize: 16px; </br > fontFamily: {
                                  < /br>}color: { </br >
                                }
                                offsetY: {
                                  < /br>}}value: { </br > show: {
                                    < /br>}fontSize: 14px; </br > fontFamily: {
                                      < /br>}color: { </br >
                                    }
                                    offsetY: {
                                      < /br>}formatter: { </br >
                                    }
                                  }
                                  total: {
                                    < /br>show: { </br >
                                  }
                                  label: Total; < /br>color: #373d3f; </br > formatter: {
                                    < /br>}}}}pie: { </br > size: {
                                      < /br>}customScale: { </br >
                                    }
                                    offsetX: {
                                      < /br>}offsetY: { </br >
                                    }
                                    expandOnClick: {
                                      < /br>}dataLabels: { </br > offset: {
                                        < /br>}}donut: { </br > size: 65 % ; < /br>background: transparent; </br > labels: {
                                          < /br>show: { </br >
                                        }
                                        name: {
                                          < /br>show: { </br >
                                        }
                                        fontSize: 16 px; < /br>fontFamily: { </br >
                                      }
                                      color: {
                                        < /br>}offsetY: { </br >
                                      }
                                    }
                                    value: {
                                      < /br>show: { </br >
                                    }
                                    fontSize: 20 px; < /br>fontFamily: { </br >
                                  }
                                  color: {
                                    < /br>}offsetY: { </br >
                                  }
                                  formatter: {
                                    < /br>}}total: { </br > show: {
                                      < /br>}label: Total; </br > color: #373d3f; </br>formatter: { </br>}}}}}}colors: { </br>}dataLabels: { </br>enabled: { </br>}formatter: { </br>}textAnchor: middle; </br>offsetX: { </br>}offsetY: { </br>}style: { </br>fontSize: 12px; </br>fontFamily: { </br>}colors: { </br>0: # fff; < /br>1: #fff; </br >
                                    }
                                  }
                                  dropShadow: {
                                    < /br>enabled: { </br >
                                  }
                                  top: {
                                    < /br>}left: { </br >
                                  }
                                  blur: {
                                    < /br>}opacity: { </br >
                                  }
                                }
                              }
                              fill: {
                                < /br>type: solid; </br > colors: {
                                  < /br>}opacity: { </br >
                                }
                                gradient: {
                                  < /br>shade: dark; </br > type: horizontal; < /br>shadeIntensity: { </br >
                                }
                                gradientToColors: {
                                  < /br>}inverseColors: { </br >
                                }
                                opacityFrom: {
                                  < /br>}opacityTo: { </br >
                                }
                                stops: {
                                  < /br>0: { </br >
                                }
                                1: {
                                  < /br>}2: { </br >
                                }
                              }
                            }
                            image: {
                              < /br>src: { </br >
                            }
                            width: {
                              < /br>}height: { </br >
                            }
                          }
                          pattern: {
                            < /br>style: sqaures; </br > width: {
                              < /br>}height: { </br >
                            }
                            strokeWidth: {
                              < /br>}}}grid: { </br > show: {
                                < /br>}borderColor: #e0e0e0; </br > strokeDashArray: {
                                  < /br>}position: back; </br > xaxis: {
                                    < /br>lines: { </br > show: {
                                      < /br>}animate: { </br >
                                    }
                                  }
                                }
                                yaxis: {
                                  < /br>lines: { </br > show: {
                                    < /br>}animate: { </br >
                                  }
                                }
                              }
                              row: {
                                < /br>colors: { </br >
                              }
                              opacity: {
                                < /br>}}column: { </br > colors: {
                                  < /br>}opacity: { </br >
                                }
                              }
                              padding: {
                                < /br>top: { </br >
                              }
                              right: {
                                < /br>}bottom: { </br >
                              }
                              left: {
                                < /br>}}}labels: { </br >
                              }
                              legend: {
                                < /br>show: { </br >
                              }
                              showForSingleSeries: {
                                < /br>}showForZeroSeries: { </br >
                              }
                              floating: {
                                < /br>}position: bottom; </br > horizontalAlign: center; < /br>fontSize: 12px; </br > fontFamily: {
                                  < /br>}width: { </br >
                                }
                                height: {
                                  < /br>}formatter: { </br >
                                }
                                offsetX: {
                                  < /br>}offsetY: { </br >
                                }
                                labels: {
                                  < /br>colors: { </br >
                                }
                                useSeriesColors: {
                                  < /br>}}markers: { </br > width: {
                                    < /br>}height: { </br >
                                  }
                                  strokeWidth: {
                                    < /br>}strokeColor: #fff; </br > radius: {
                                      < /br>}customHTML: { </br >
                                    }
                                    offsetX: {
                                      < /br>}offsetY: { </br >
                                    }
                                    shape: square; < /br>size: { </br >
                                  }
                                }
                                itemMargin: {
                                  < /br>horizontal: { </br >
                                }
                                vertical: {
                                  < /br>}}onItemClick: { </br > toggleDataSeries: {
                                    < /br>}}onItemHover: { </br > highlightDataSeries: {
                                      < /br>}}}markers: { </br > discrete: {
                                        < /br>}size: { </br >
                                      }
                                      colors: {
                                        < /br>}strokeColor: #fff; </br > strokeWidth: {
                                          < /br>}strokeOpacity: { </br >
                                        }
                                        fillOpacity: {
                                          < /br>}shape: circle; </br > radius: {
                                            < /br>}offsetX: { </br >
                                          }
                                          offsetY: {
                                            < /br>}hover: { </br > size: {
                                              < /br>}sizeOffset: { </br >
                                            }
                                          }
                                        }
                                        noData: {
                                          < /br>text: { </br >
                                        }
                                        align: center; < /br>verticalAlign: middle; </br > offsetX: {
                                          < /br>}offsetY: { </br >
                                        }
                                        style: {
                                          < /br>color: { </br >
                                        }
                                        fontSize: 14 px; < /br>fontFamily: { </br >
                                      }
                                    }
                                  }
                                  responsive: {
                                    < /br>}series: { </br > 0: {
                                      < /br>data: { </br >
                                    }
                                    name: Complete Health Profile; < /br>}1: { </br > data: {
                                      < /br>0: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}1: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}2: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}3: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}4: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}5: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}6: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}7: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}8: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}9: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}10: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}11: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}12: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}13: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}14: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}15: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}16: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}17: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}18: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}19: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}20: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}21: { </br > x: blank - Castillo; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}22: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}23: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}24: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}25: { </br > x: blank; < /br>y: { </br >
                                    }
                                    numPatients: {
                                      < /br>}}}name: Incomplete Health Profile; </br >
                                    }
                                  }
                                  states: {
                                    < /br>normal: { </br > filter: {
                                      < /br>type: none; </br > value: {
                                        < /br>}}}hover: { </br > filter: {
                                          < /br>type: lighten; </br > value: {
                                            < /br>}}}active: { </br > allowMultipleDataPointsSelection: {
                                              < /br>}filter: { </br > type: darken; < /br>value: { </br >
                                            }
                                          }
                                        }
                                      }
                                      title: {
                                        < /br>text: { </br >
                                      }
                                      align: left; < /br>margin: { </br >
                                    }
                                    offsetX: {
                                      < /br>}offsetY: { </br >
                                    }
                                    floating: {
                                      < /br>}style: { </br > fontSize: 14 px; < /br>fontFamily: { </br >
                                    }
                                    color: {
                                      < /br>}}}subtitle: { </br > text: {
                                        < /br>}align: left; </br > margin: {
                                          < /br>}offsetX: { </br >
                                        }
                                        offsetY: {
                                          < /br>}floating: { </br >
                                        }
                                        style: {
                                          < /br>fontSize: 12px; </br > fontFamily: {
                                            < /br>}color: { </br >
                                          }
                                        }
                                      }
                                      stroke: {
                                        < /br>show: { </br >
                                      }
                                      curve: smooth; < /br>lineCap: butt; </br > width: {
                                        < /br>}colors: { </br >
                                      }
                                      dashArray: {
                                        < /br>}}tooltip: { </br > enabled: {
                                          < /br>}shared: { </br >
                                        }
                                        followCursor: {
                                          < /br>}intersect: { </br >
                                        }
                                        inverseOrder: {
                                          < /br>}custom: { </br >
                                        }
                                        fillSeriesColor: {
                                          < /br>}theme: light; </br > onDatasetHover: {
                                            < /br>highlightDataSeries: { </br >
                                          }
                                        }
                                        x: {
                                          < /br>show: { </br >
                                        }
                                        format: dd MMM; < /br>formatter: { </br >
                                      }
                                    }
                                    y: {
                                      < /br>formatter: { </br >
                                    }
                                    title: {
                                      < /br>formatter: { </br >
                                    }
                                  }
                                }
                                z: {
                                  < /br>formatter: { </br >
                                }
                                title: Size: ; < /br>}marker: { </br > show: {
                                  < /br>}}items: { </br > display: flex; < /br>}fixed: { </br > enabled: {
                                    < /br>}position: topRight; </br > offsetX: {
                                      < /br>}offsetY: { </br >
                                    }
                                  }
                                }
                                xaxis: {
                                  < /br>type: category; </br > categories: {
                                    < /br>}offsetX: { </br >
                                  }
                                  offsetY: {
                                    < /br>}labels: { </br > show: {
                                      < /br>}rotate: { </br >
                                    }
                                    rotateAlways: {
                                      < /br>}hideOverlappingLabels: { </br >
                                    }
                                    trim: {
                                      < /br>}minHeight: { </br >
                                    }
                                    maxHeight: {
                                      < /br>}showDuplicates: { </br >
                                    }
                                    style: {
                                      < /br>colors: { </br >
                                    }
                                    fontSize: 12 px; < /br>fontFamily: { </br >
                                  }
                                  cssClass: apexcharts - xaxis - label; < /br>}offsetX: { </br >
                                }
                                offsetY: {
                                  < /br>}format: { </br >
                                }
                                formatter: {
                                  < /br>}datetimeFormatter: { </br > year: yyyy; < /br>month: MMM 'yy; </br > day: dd MMM; < /br>hour: HH:mm; </br > minute: HH: mm: ss; < /br>}}axisBorder: { </br > show: {
                                    < /br>}color: #78909C; </br > width: 100 % ; < /br>height: { </br >
                                  }
                                  offsetX: {
                                    < /br>}offsetY: { </br >
                                  }
                                }
                                axisTicks: {
                                  < /br>show: { </br >
                                }
                                color: #78909C; </br>height: { </br>}offsetX: { </br>}offsetY: { </br>}}tickAmount: { </br>}min: { </br>}max: { </br>}range: { </br>}floating: { </br>}position: bottom; </br>title: { </br>text: { </br>}offsetX: { </br>}offsetY: { </br>}style: { </br>color: { </br>}fontSize: 12px; </br>fontFamily: { </br>}cssClass: apexcharts-xaxis-title; </br>}}crosshairs: { </br>show: { </br>}width: barWidth; </br>position: back; </br>opacity: { </br>}stroke: { </br>color: # b6b6b6; < /br>width: { </br >
                              }
                              dashArray: {
                                < /br>}}fill: { </br > type: gradient; < /br>color: #B1B9C4; </br > gradient: {
                                  < /br>colorFrom: #D8E3F0; </br > colorTo: #BED1E6; < /br>stops: { </br > 0: {
                                    < /br>}1: { </br >
                                  }
                                }
                                opacityFrom: {
                                  < /br>}opacityTo: { </br >
                                }
                              }
                            }
                            dropShadow: {
                              < /br>enabled: { </br >
                            }
                            left: {
                              < /br>}top: { </br >
                            }
                            blur: {
                              < /br>}opacity: { </br >
                            }
                          }
                        }
                        tooltip: {
                          < /br>enabled: { </br >
                        }
                        offsetY: {
                          < /br>}formatter: { </br >
                        }
                      }
                    }
                    yaxis: {
                      < /br>0: { </br > show: {
                        < /br>}opposite: { </br >
                      }
                      logarithmic: {
                        < /br>}logBase: { </br >
                      }
                      tickAmount: {
                        < /br>}max: { </br >
                      }
                      min: {
                        < /br>}decimalsInFloat: { </br >
                      }
                      floating: {
                        < /br>}seriesName: { </br >
                      }
                      labels: {
                        < /br>show: { </br >
                      }
                      minWidth: {
                        < /br>}maxWidth: { </br >
                      }
                      offsetX: {
                        < /br>}offsetY: { </br >
                      }
                      style: {
                        < /br>colors: { </br >
                      }
                      fontSize: 11 px; < /br>fontFamily: { </br >
                    }
                    cssClass: apexcharts - yaxis - label; < /br>}formatter: { </br >
                  }
                }
                axisBorder: {
                  < /br>show: { </br >
                }
                color: #78909C; </br>offsetX: { </br>}offsetY: { </br>}}axisTicks: { </br>show: { </br>}color: # 78909 C; < /br>width: { </br >
              }
              offsetX: {
                < /br>}offsetY: { </br >
              }
            }
            title: {
              < /br>text: { </br >
            }
            rotate: {
              < /br>}offsetY: { </br >
            }
            offsetX: {
              < /br>}style: { </br > color: {
                < /br>}fontSize: 11px; </br > fontFamily: {
                  < /br>}cssClass: apexcharts-yaxis-title; </br >
                }
              }
              tooltip: {
                < /br>enabled: { </br >
              }
              offsetX: {
                < /br>}}crosshairs: { </br > show: {
                  < /br>}position: front; </br > stroke: {
                    < /br>color: #b6b6b6; </br > width: {
                      < /br>}dashArray: { </br >
                    }
                  }
                }
              }
            }
            theme: {
              < /br>palette: palette1; </br > monochrome: {
                < /br>enabled: { </br >
              }
              color: #008FFB; </br>shadeTo: light; </br>shadeIntensity: { </br>}}}_chartInstances: { </br>}selection: { </br>enabled: { </br>}}

**Comment by junedchhipa** [comment]
You may try creating an example on [codesandbox](https://codesandbox.io/) as it allows working in React environment easily.

**Comment by junedchhipa** [comment]
Closing as no response
