### ISSUE TITLE
Poorly formatted color in series causes Axes and Toolbar to disappear and unhelpful error message

### ISSUE THREAD

**Issue by Alan-Hinton** [apexcharts/apexcharts.js#3792]
### Description
If you set the color of a series with trailing whitespace then you will see the following error in the console and the Axes and Toolbar will not appear

> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')

This error message gives no clue as to the problem and therefore, although the error is very easy to fix once you know what it is, it is very hard to know what is causing the error.

If the color is not a valid color at all, the chart will display correctly but with a default color.  This issue only arises when the color is valid but followed by whitespace
 
### Steps to Reproduce
1. Create a chart with at least one series that has a valid color followed by whitespace e.g. '#aaaaaa '
2. Render the chart

### Expected Behavior
The chart displays correctly with the series in the color specified, or a useful error message is displayed saying the the color is invalid.

### Actual Behavior
The chart displays without Axes or Toolbar, or in the worst case is completely blank. An unhelpful message is seen in the console.

### Screenshots
It is just a blank chart

### Reproduction Link
https://codepen.io/AlanHinton/pen/bGmWYeJ
I was able to recreate the error very easily by replacing line 10 of the js file with the following (note space at the end of the color).
```
      data: [1,3,2],
      color: '#aaaaaa '
```

**Comment by junedchhipa** [comment]
Not a bug. You have to validate the color string before passing it to ApexCharts.
