### ISSUE TITLE
Common label for range area with line

### ISSUE THREAD

**Issue by fracz** [apexcharts/apexcharts.js#3797]
## Summary

It would be nice to be able to show the label in range area with line combo for both area and the line at the same time.

See example in the docs: https://apexcharts.com/javascript-chart-demos/range-area-charts/combo/

If you hover the line, the tooltip shows the line value:

![image](https://user-images.githubusercontent.com/3918865/235081546-a49fef6a-a8ae-42fe-aea4-0f73d7983801.png)

If you hover the bootom part of the range, there is a range

![image](https://user-images.githubusercontent.com/3918865/235081662-9e651af3-ff3f-459b-96bd-7777406fea95.png)

If you hover the top part of the range, the label is for the line, too.

It feels a bit awkwards. IMHO, the tooltip should be able to show both values (i.e. for line and the range) in one tooltip regardless of what part you hover.

## API Changes

Don't know.

## Intended Use Case

Like in the summary.

**Comment by brianlagunas** [comment]
Thank you for the suggestion, but this is not a feature we will be adding.
