### ISSUE TITLE
When plotting large dataSets other than timeseries data, interactive feature need to be added.

### ISSUE THREAD

**Issue by surbhibh** [apexcharts/apexcharts.js#380]
**Is your feature request related to a problem? Please describe.**
In a category x-axis chart, zooming/panning is not enabled if xaxis.categories is defined as String values.

**Describe the solution you'd like**
If in case the dataType is string and the entire data is huge than the interactive functionality should be enable.

**Describe alternatives you've considered**
Enable zooming/panle for function for each datatypes.

**Additional context**

**Comment by surbhibh** [comment]
When plotting large dataSets other than timeseries data, zooming, panning and scrolling feature need to be added mainly in bar chart.

**Comment by junedchhipa** [comment]
Sorry, zooming/panning on category x-axis is not supported currently.
It might be added in the future release, no ETA.

**Comment by surbhibh** [comment]
Is there any plan to add this functionality.
