### ISSUE TITLE
Please update the Release page

### ISSUE THREAD

**Issue by sandrooco** [apexcharts/apexcharts.js#3802]
### Description
The current release on the [release tab](https://github.com/apexcharts/apexcharts.js/releases) is 3.37.0. On npm, there is a 3.40.0 release.
Developers have no idea, what changed, what to look out for when updating and even if these releases are legitimate.

### Expected Behavior
Every version on npm has it's own release on Github. Thanks!

**Comment by junedchhipa** [comment]
Not a bug.
Updated the latest release
