### ISSUE TITLE
Histogram is not working

### ISSUE THREAD

**Issue by joadan** [apexcharts/apexcharts.js#3807]
### Description
In the latest version histogram is not working.
Chart throws an error:  Cannot read properties of null (reading 'yRatio')
 Looks like the issue has been introduced in one of the later versions, It works in v3.36.2.

### Steps to Reproduce

1.  Create a histogram chart
2.  Check the console output

### Expected Behavior
The chart renders correctly

### Actual Behavior
Chart throws an error, Cannot read properties of null (reading 'yRatio')

### Reproduction Link
https://codepen.io/joadan-the-sasster/pen/OJBxQQX

**Comment by junedchhipa** [comment]
Histogram was technically not implemented correctly. It was just a visual configuration of drawing the bars without any gap in between.
A technically correct histogram would be drawn by calculating the frequency distribution of data points.
No ETA for this.

**Comment by junedchhipa** [comment]
To get the histogram "look" for a bar chart, you may suggest using this configuration

```javascript
  chart: {
    height: 380,
    width: "100%",
    type: "bar"
  },
  plotOptions: {
     bar: {
       columnWidth: '100%'
     }
  },
  stroke: {
    width: 1,
    colors: ['#fff']
  },
```

**Comment by joadan** [comment]
Hello,

Thank you for the update,

Just to be clear, this means that the chart type 'histogram' is no longer a valid option and documentation should be changed
https://apexcharts.com/docs/options/chart/type/, correct?

Thank you

**Comment by junedchhipa** [comment]
Thanks for the reminder, I will remove `histogram` from that list on the website.
