### ISSUE TITLE
Editor: Unable to create an account due to CORS

### ISSUE THREAD

**Issue by ssenior45** [apexcharts/apexcharts.js#3808]
### Description

The sign up page for the apexcharts online editor is broken.

### Steps to Reproduce

1. Visit https://editor.apexcharts.com/login
2. Click Sign Up
3. Enter name, username and password
4. Click Create Account

### Expected Behavior

A new user account is created.

### Actual Behavior

Javascript console shows CORS error. See screenshot.

### Screenshots

![Screenshot 2023-05-02 at 13 01 59](https://user-images.githubusercontent.com/6702942/235661191-4ab942ab-0018-45f8-8986-6c67dd380eb7.png)

**Comment by junedchhipa** [comment]
It might be a temporary issue when the server might be overloaded.
I don't see the issue now.
