### ISSUE TITLE
Ask about configuration

### ISSUE THREAD

**Issue by athmos-pedrocarvajal** [apexcharts/apexcharts.js#381]
Hi, I have a question, which I can not find in the documentation. in this picture -> "http://prntscr.com/muph7s" in picture 1 how do I change the colors? background for example .. and in table 2 it is possible to colcoar a date? instead of a number?

**Comment by junedchhipa** [comment]
You can change the background color of x-axis tooltip by CSS
```css
.apexcharts-xaxistooltip {
   background: '#333'
}
```

I didn't understand your second point. Did you mean that you need to format datetime in x-axis tooltip? You should try the function at `xaxis.tooltip.formatter` - https://apexcharts.com/docs/options/xaxis/#tooltipFormatter
