### ISSUE TITLE
It really starts to hurt

### ISSUE THREAD

**Issue by dev01111001** [apexcharts/apexcharts.js#3810]
![image](https://user-images.githubusercontent.com/127305857/236049158-32144869-6164-4c8c-9300-8e261fe61dc5.png)

Zooming extends over opposite y-axis' and multiple series still wont adjust y-axis when zooming.

Please let us know if you are fixing this otherwise i would have to use an other library which i really do not want to since i like apexcharts.
But this really starts to hurt.

**Comment by brianlagunas** [comment]
Did not follow bug issue template

**Comment by dev01111001** [comment]
fair enough. but did the message reach juned chihpa ?
