### ISSUE TITLE
Area chart not working well for large dataset. 

### ISSUE THREAD

**Issue by awaisalee** [apexcharts/apexcharts.js#3816]
### Description
While using the area chart for my client we have to display data between two dates. When the dataset size is smaller the chart working well but when the dataset size become large the chart does not plot the area but the data are displaying on both x-axis and y-axis.  

### Expected Behavior
The chart also plot the area for large dataset. 
### Actual Behavior
The chart not plotting the area but display the data on both axis.
### Screenshots
For one month data.
<img width="975" alt="Screenshot 2023-05-08 at 6 27 24 PM" src="https://user-images.githubusercontent.com/49532001/236841167-afde00c2-b409-4e55-a7aa-7e2c857ae2e2.png">

When we try to display the complete data the chart looks like this.
<img width="1015" alt="Screenshot 2023-05-08 at 6 27 12 PM" src="https://user-images.githubusercontent.com/49532001/236841814-259e1c6c-ed7a-4d01-bc80-fdf8850a9e85.png">

**Comment by brianlagunas** [comment]
Did not provide required reproduction link
