### ISSUE TITLE
Homepage: "Line Chart With Data Labels" for React has wrong URL (404)

### ISSUE THREAD

**Issue by rgwebcode** [apexcharts/apexcharts.js#3820]
On the [React Demo](https://apexcharts.com/react-chart-demos/line-charts/) page, the link to the the "Line Chart With Data Labels" is incorrect.
Currently it points to
`https://apexcharts.com/react-chart-demos/line-charts/line-with-data-labels/`

While it should be
`https://apexcharts.com/react-chart-demos/line-charts/data-labels/`

 (found out by looking at the URL for the vanilla JS demo)

**Comment by bosseDev** [comment]
Same issue on:

Currently i points to:
[[https://apexcharts.com/angualr}-chart-demos/line-charts/null-values/](https://apexcharts.com/angular-chart-demos/line-charts/null-values/)](https://apexcharts.com/angular-chart-demos/line-charts/null-values/)

While it should be:
[https://apexcharts.com/angular-chart-demos/line-charts/missing-null-values/](https://apexcharts.com/angular-chart-demos/line-charts/missing-null-values/)

same for React Demo

**Comment by junedchhipa** [comment]
Fixed both these missing pages.
