### ISSUE TITLE
Glitching with rangeArea and missing/null data

### ISSUE THREAD

**Issue by levmason** [apexcharts/apexcharts.js#3821]
### Description
I'm using rangeArea type, but whenever I have missing/null data points, the svg isn't drawn correctly. The glitch is different depending on whether I use smooth or straight curves. (I've attached screenshots of both below).

### Steps to Reproduce

1. Create a rangeArea plot with a gap where data is missing (null values)

### Screenshots
These screenshots all have line series plus a shaded rangeArea plot that should surround it. The more transparent colors are from the rangeArea series'.

straight curve
<img width="1167" alt="Screenshot 2023-05-09 at 4 18 21 PM" src="https://github.com/apexcharts/apexcharts.js/assets/25449248/aa46e236-1cdb-494d-ad66-4b8cac519170">
smooth curve
<img width="1152" alt="Screenshot 2023-05-09 at 4 22 04 PM" src="https://github.com/apexcharts/apexcharts.js/assets/25449248/f801ac5d-1024-460e-8afa-84193fa8cbbf">
smooth curve
<img width="1150" alt="Screenshot 2023-05-09 at 4 23 14 PM" src="https://github.com/apexcharts/apexcharts.js/assets/25449248/201aedae-b510-4ee0-8d28-324fc34a4c28">

### Reproduction Link

straight curve: https://codepen.io/Levi-Mason/pen/dygmaxe
smooth curve: https://codepen.io/Levi-Mason/pen/vYVRbqz

**Comment by DennisNurtio** [comment]
Might be related to: https://github.com/apexcharts/apexcharts.js/issues/3525

**Comment by mateuscardosogs** [comment]
same problem
