### ISSUE TITLE
Hide data labels on stacked bar chart

### ISSUE THREAD

**Issue by ben-ekw** [apexcharts/apexcharts.js#3824]
## Summary

The stacked bar chart has no option to disable data labels (only the total data label).

## API Changes

Can you add an `enabled` option on the `dataLabels` object itself (not just on the `total` child to `dataLabels`

## Intended Use Case

My stacked bar chart has a lot of segments, many of which are large enough to display a label but it makes the visual very busy. I'd like to hide all segment values and just keep a total value at the top and allow the user to hover over each segment to get the value.

![image](https://github.com/apexcharts/apexcharts.js/assets/105461985/bfc6d2c0-5750-414b-9666-1d51e35208e0)

**Comment by unvalley** [comment]
I guess this will work.
```ts
options: {
	// ...
    dataLabels: { enabled: false },
    // ...
}
```

https://apexcharts.com/docs/options/datalabels/

**Comment by ben-ekw** [comment]
Great, thanks!
