### ISSUE TITLE
Plotting a Box plot twice at same vertical line view 

### ISSUE THREAD

**Issue by Parthasj** [apexcharts/apexcharts.js#3829]
Hi,

Trying to plot the box plot twice(positive and negative values) at the same vertical line but can't able to plot it, please find the attachment.

![box](https://github.com/apexcharts/apexcharts.js/assets/15190065/7bee4014-becc-408f-afc4-4a02d9511743)

1. Top and bottom (zero is divider) view on the different lines. attached sample image for your reference.
2. Line plotting axis is different from the box plot axis.

Sample Image:
![sample-image](https://github.com/apexcharts/apexcharts.js/assets/15190065/d02ed134-767c-4336-9a95-cd6ff1c76c6b)

Actually, I'm trying to plot the above graph but the box plot view doesn't align properly. Can you please tell me, if is it possible to plot the same graph attached?

Link: https://codepen.io/partha_sj/pen/xxyjygZ

**Comment by brianlagunas** [comment]
You posted this same question in Discussions. Please do not double post.

**Comment by Parthasj** [comment]
Sure @brianlagunas, Need your inputs.
