### ISSUE TITLE
DataLabels don't show correctly when chart height is set

### ISSUE THREAD

**Issue by mbejda** [apexcharts/apexcharts.js#383]
## Explanation

- What is the behavior you expect?
I expected the data labels to show
- What is happening instead?
Data labels are not showing correctly

<img width="407" alt="screen shot 2019-03-08 at 7 08 54 am" src="https://user-images.githubusercontent.com/5429780/54027881-102ceb80-4171-11e9-80e5-baf4a031c8c7.png">

```
    plotOptions: {
      bar: {
        barHeight: '50%',
        dataLabels: {
          position: 'top', // top, center, bottom
        },
      }
    }

    dataLabels: {
      enabled: true,
      offsetY: -20,
      style: {
        padding: {
          top:30
        },
        fontSize: '15px',
        colors: ["#304758"]
      }
    }

  chart: {
      height: 200,
      toolbar: {
        show: false
      },
      type: 'bar'
    },
```

**Comment by junedchhipa** [comment]
For a temporary workaround, please add some padding to the grid by
```javascript
grid: {
  padding: {
    top: 15
  }
}
```
