### ISSUE TITLE
Column chart x-axis labels randomly bold

### ISSUE THREAD

**Issue by dmmartins** [apexcharts/apexcharts.js#3832]
### Description

when creating a column bar, some of the columns are rendered with a bold font

### Expected Behavior

x-axis labels should all be the same

### Screenshots

<img width="902" alt="Screenshot 2023-05-11 at 6 58 49 PM" src="https://github.com/apexcharts/apexcharts.js/assets/176215/683b8df6-f7fd-405b-97c3-6f78b416ee0a">

### Reproduction Link

https://codepen.io/dmmartins/pen/zYmarwJ

**Comment by brianlagunas** [comment]
This is by design. If the Jan label falls between a date range, it will be bolded to indicate the beginning of another year.

**Comment by dmmartins** [comment]
@brianlagunas is there a way to change that behavior on the chart config? is this mentioned on the docs anywhere?

**Comment by brianlagunas** [comment]
Not that I am aware of. I couldn't find anything that indicated this could be changed.

**Comment by jhemak** [comment]
@dmmartins were you able to find a way to turn this off or otherwise work around it?

**Comment by dmmartins** [comment]
We ended up not using dates on the x-axis. it doesn't do that with text labels.
but you can also override the css of the labels with something like this
```
 .apexcharts-xaxis-texts-g tspan {
  font-weight: 400;
}
```

**Comment by jhemak** [comment]
Thank you - that worked!  I found something similar [here](https://github.com/apexcharts/apexcharts.js/issues/1283).  Do you know what is the difference between these two approaches?  Both seem to work.

```
.apexcharts-xaxis-texts-g tspan {
  font-weight: 400;
}
```
and

```
.apexcharts-xaxis-label {
  font-weight: 400
}
```
