### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')

### ISSUE THREAD

**Issue by TheRealArtonn** [apexcharts/apexcharts.js#3838]
### Description

I'm currently building a tool with four buttons that updates the data of a single chart, each button will give the chart new data to show and it works perfectly. The trouble is when a user disabled a legend, turns it off. The chart can no longer receive new data and now just throws the error: Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed') in the console. Enabling the disabled legend, will make the chart function normally again.

### Steps to Reproduce

1. Populate chart with data through updateOptions
2. Have buttons to give different data to the same chart.
3. Press one of the legends to disable it and click on the next button to change chart data
4. Observe the error.

### Expected Behavior
I expected the legends to be reset, once you run updateOptions to update series and data generally.

### Actual Behavior
Old data persists and does not update the chart, at the same time the error Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed') is displayed. Enabling legend again, will allow for normal operation again.

### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/61601482/dee5ca80-2942-4e28-b17a-6c0763ebe8d3)

### Reproduction Link

Requires some time to do it, will soon.

**Comment by brianlagunas** [comment]
I will reopen when you have provided the required reproduction link.
