### ISSUE TITLE
Donut chart label click event

### ISSUE THREAD

**Issue by disagol** [apexcharts/apexcharts.js#384]
As always thank you very much for this library.
I wonder if it is feasible that when someone clicks on a slice in a donut chart the totals labels reacts to a 'click' event instead of a 'hover'. It seems more natural to me that if a donut slice is selected with the click event the total label shows the info for that slice no matter if mouse leaves the area. Is there a workaround for this behaviour?

Thanks once again.-

**Comment by junedchhipa** [comment]
Ok, I will add this in my to-do list of Feature-requests.

**Comment by disagol** [comment]
Thanks!
