### ISSUE TITLE
How to set datetime x-axis labels which are exactly on the timestamps in data series?

### ISSUE THREAD

**Issue by ghost** [apexcharts/apexcharts.js#3841]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/3809

Not sure if it's a bug. 
Any Ideas?

<div type='discussions-op-text'>

<sup>Originally posted by **bluebase-dev** May  3, 2023</sup>
Hi,

I'm trying to use datetime type for x-axis and there are unix timestamp numbers in the data series for it.

I thought the x-axis label would be the timestamp numbers in the data, but it seems like it automatically set the tick to 8 days.

How do I make it to show the exact date(timestamp) which are in the data?

<img width="779" alt="CleanShot 2023-05-03 at 14 33 39@2x" src="https://user-images.githubusercontent.com/117051738/235839204-27420640-1636-40fb-b23b-5954f0eff61d.png"></div>

**Comment by guestisp** [comment]
I need this too.
I don't see any reason why datetime shouldn't place the labels at least on each data point.

Would be much useful to skip some labels but at least one has to be on the point, not totally disconnected right now.
