### ISSUE TITLE
Credit on charts

### ISSUE THREAD

**Issue by balex25** [apexcharts/apexcharts.js#385]
Will be nice to able to add credit (text or custom URL and text) at the end or top of charts, like in the below image.

<img width="249" alt="chrome_WhsnqQvYvE" src="https://user-images.githubusercontent.com/37195461/54066037-d839ad00-4231-11e9-8bc2-b7259d416274.png">

**Comment by junedchhipa** [comment]
You can use `title` / `subtitle` to add additional text as displayed on this example - https://apexcharts.com/javascript-chart-demos/column-charts/column-with-data-labels/

Also, if you want to add text dynamically after chart has been rendered, you can use the `addText()` method - https://apexcharts.com/docs/methods/#addtext
