### ISSUE TITLE
Gradient fill colorstop chart alignment issue in x-axis type datetime

### ISSUE THREAD

**Issue by yogi9983** [apexcharts/apexcharts.js#3855]
mySeries.forEach((set, index) => {
      const seriesValue = set.data.map(e => e.y);

      const colorStops = [];

      seriesValue.forEach((value, i) => {
        let color = 'black';
        for (let j = 0; j < rangeValue?.length; j++) {
          if (value <= rangeValue[j].Range_End_Value) {
            color = rangeValue[j].Range_color.toLowerCase();
            break;
          }
        }
        colorStops.push({
          value,
          offset: i * (100 / (seriesValue?.length - 1)),
          color,
          opacity: 0.5
        });
     
 });

      options.fill.gradient.colorStops[index] = colorStops;
    });
   this is my code it apply colorstop based on range value we provide  and it is working perfectly only when we have less x-axis label but if we have more x-axis label like 5 days or 7 days label then color get placed  wrongly in chart  and i use x-axis type datetime but this issuse got resolved using x-axis type changed to category  but i want to use x-axis type to datetime

**Comment by brianlagunas** [comment]
Did not follow bug issue template instructions.
