### ISSUE TITLE
Pentest - Outdated Dependencies

### ISSUE THREAD

**Issue by agaluf** [apexcharts/apexcharts.js#3858]
In our latest Pentest Apexcharts library came up as one of the chief contributor of outdated dependencies thanks to svg.*.js in Version 2+. I have found this reply by Ryan Maffey in response to another topic: https://github.com/apexcharts/apexcharts.js/issues/3278#issuecomment-1361630629

Since we would like to keep on using the Apexcharts library, I would like to know if there's any plans of upgrading to svg.js 3+ (I take that's a no due to complexity involved?) or baking the dependencies directly into Apexcharts (which would also allow solving the other Issue). The way I see it, svg.js 2+ and plugins were not updated for years.

**Comment by junedchhipa** [comment]
Hey @agaluf 
I understand your concern. I already have the Svg.js core library baked into ApexCharts, but the plugins are imported from their respective repositories. Upgrading the Svg.js 3+ would break a lot of things, so I don't plan to update to the latest SVG.js unless they upgrade their plugins to make it Svg.js 3+ compatible.
