### ISSUE TITLE
X-AxisAnnotation always at X=0

### ISSUE THREAD

**Issue by Foxmaner** [apexcharts/apexcharts.js#387]
## Codepen

https://codepen.io/foxmaner/pen/MxoMzo

## Explanation

I´m creating a dynamic chart. Both the Y and X axis are updated regularly. Now I want one annotation for the x-axis. But whatever x value I input, it still adds the annotation at X=0. I don't get any errorMessages.  I think this might be due to me updating the X-Axis after the first render.
This is my first issue on GitHub. So hope I provided enough info :)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it.

**Comment by Foxmaner** [comment]
Thanks for the quick fix! Works perfectly now :) Just a heads-up. The bug is still there if you use apexcharts.min.js instead of apexcharts.js

**Comment by junedchhipa** [comment]
Are you loading ApexCharts from jsdelivr cdn?
Must be cache issue as I have uploaded both files while releasing.

**Comment by Foxmaner** [comment]
Looks like that was the problem. Thanks
