### ISSUE TITLE
 Incorrect Scaling Behavior when Modifying Minimum Value on Apex Radar Chart's Y-Axis

### ISSUE THREAD

**Issue by SheilaRoe** [apexcharts/apexcharts.js#3880]
Hello,

Description:
I have discovered an issue when adjusting the minimum value of the y-axis on the Apex Radar Chart. Instead of scaling the chart proportionally, the entire chart is being shifted, resulting in an inaccurate representation of the data. Here are the details:

Steps to Reproduce:
a. Navigate to the Apex Radar Chart feature.
b. Set the initial y-axis range between 0 and 500.
c. Observe that the data points are all at 200, and the chart is correctly displayed.
d. Attempt to modify the minimum value of the y-axis to 100.
e. Observe the chart behavior after adjusting the y-axis minimum value.

Expected Behavior:
When adjusting the minimum value of the y-axis to 100, the chart should scale accordingly, with the data points appearing closer to the center rather than closer to the chart borders. The data points should still be accurately represented within the new y-axis range of 100 to 500.

Actual Behavior:
The value is no longer represented as 200.

I have included visual examples for your reference:

Initial y-axis range: 0 to 500, with data points at 200
![image](https://github.com/apexcharts/apexcharts.js/assets/136568681/bf012bd7-3f0f-4c1a-b795-689c3f7c1627)

Modified y-axis range: 100 to 500, with shifted graph
![image](https://github.com/apexcharts/apexcharts.js/assets/136568681/9eec66be-da61-44cb-9e56-d2f41bae2f6a)

Please address this issue so that the Apex Radar Chart accurately reflects the data when modifying the y-axis minimum value. Let me know if you need any further information or clarification.

Thank you for your prompt attention to this matter.

Best regards,
[Sheila]

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
