### ISSUE TITLE
Menu isn't closed if you click outside a chart component.

### ISSUE THREAD

**Issue by damianmalinowski** [apexcharts/apexcharts.js#3881]
### Description

The menu doesn't close if you click beyond the chart component.

### Steps to Reproduce

1. Got to  https://apexcharts.com/angular-chart-demos/line-charts/basic/ and click on menu.
2. Click outside a chart component.
3. Menu still open.

### Expected Behavior

The menu should be closed if you click beyond a chart component.

### Actual Behavior

The menu is still open if you click beyond a chart component.
If you click on the chart component you will close menu.

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/18700400/45de2e68-0d8b-43b8-a33f-d192978e7166)

### Reproduction Link

https://apexcharts.com/angular-chart-demos/line-charts/basic/

**Comment by junedchhipa** [comment]
Not a bug.
The sample you linked is rendered as an iframe on the page. So, it is undetected if a click event happens outside the iframe. Try clicking inside anywhere around the chart and it should close.
