### ISSUE TITLE
Heatmap cell width does not fit for grid width.

### ISSUE THREAD

**Issue by tosintech-web** [apexcharts/apexcharts.js#3887]
### Steps to Reproduce

1.  create a heatmap series with  x: datetime, y: numeric
2.  set options: xaxis: type: 'datetime'
3. chart.render()

### Expected Behavior
heatmap cells are fiting for grid width.
![image](https://github.com/apexcharts/apexcharts.js/assets/75475434/3f6b7eca-a18e-4265-811d-0d19de339a6d)

### Actual Behavior
they are not fit for grid width.
![image](https://github.com/apexcharts/apexcharts.js/assets/75475434/554a68a4-bc28-4060-8895-dfe9656522e9)

**Comment by brianlagunas** [comment]
Did not provide required reproduction app
