### ISSUE TITLE
Adjust to amount that a slice expands on click

### ISSUE THREAD

**Issue by janniknilsson** [apexcharts/apexcharts.js#3888]
## Summary

When displaying a pie/donut chart with expandOnClick enabled, the slice expands 4px.  It would be nice to be able to change that number.

## API Changes

Add a expandOnClickSize to overwrite the value 4 on line 509 in the Pie.js file.
The chart should add padding so the slices aren't cropped off.

## Intended Use Case

I would like to be able to make the expanded slice more noticeable.

**Comment by janniknilsson** [comment]
Keeping it fresh

**Comment by canblt** [comment]
any update oder workaround to solve it. It would be great, if you would be able to scale it

**Comment by vuckele** [comment]
+1 for this feature

**Comment by MushuPlatypus** [comment]
bump
