### ISSUE TITLE
Range Area Chart dataPointIndex is always NaN for Events

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#3892]
### Description

The dataPointIndex value inside the config property of the events for the Range Area Chart is always NaN.

### Steps to Reproduce

1. Create a Range Area Chart
2. Add an event, for example the 'dataPointMouseEnter' event, and log the config property.
3. dataPointIndex appears to be NaN.

### Expected Behavior

It is expected to return the Index of the data point which is a number.

### Actual Behavior

It always returns NaN.

### Reproduction Link

Reproducible codepen: https://codepen.io/thimows/pen/rNQMqbb

**Comment by junedchhipa** [comment]
You can use the `mouseMove` event to catch the dataPointIndex accurately.
```javascript
         events: {
            mouseMove: function (event, chartContext, config) {
              document.querySelector('#dataPointIndex').innerText =
                config.dataPointIndex
            },
          },
```
