### ISSUE TITLE
How to change color on xaxis labels on grouped bar chart?

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#39]
![sketch](https://user-images.githubusercontent.com/6877046/44212210-69044a80-a173-11e8-9576-7967cb81b637.png)
How to change xaxis labels colors? 
I'm using this configuration 
```javascript
const options = {
	chart: {
      height: 200,
      type: 'bar',
    },
    plotOptions: {
      bar: {
        horizontal: true
      }
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      show: false,
      width: 1,
      colors: ['#fff']
    },
    series: [{
      name: 'Competition',
      data: [44, 55, 41, 64, 20]
    }, {
      name: 'Me',
      data: [53, 32, 33, 52, 10]
    }],
    colors: ['#F47B20', '#005596'],
    legend: {
      show: false,
      position: 'top'
    },
    grid: {
      show: false
    },
    xaxis: {
      categories: ['Alpha bank', 'Eurobank', 'Τράπεζα πειραιώς', 'Εθνική τράπεζα', 'Attica Bank'],
      labels: {
        show: true,
        style: {
          color: 'blue',
          fontSize: '12px'
        },
      }
    }
}
```

**Comment by junedchhipa** [comment]
Fixed the x-axis color setting which I missed for bar charts
Note that the name of the property is changed from color to colors `xaxis.labels.style.colors`
It accepts an array as well as a single string color. Here is the doc - https://apexcharts.com/docs/options/xaxis/#labelsColor

**Comment by nareshpatil031886** [comment]
![Screenshot (3)](https://github.com/apexcharts/apexcharts.js/assets/101571740/652f5eba-2888-4be0-a870-7cedefb34afb)
const ebChartData = {
    series: [
    {
      data: [17, 11],
      name: "PRODUCT A",
    },
    {
      data: [17,11],
      name: 'PRODUCT B',
    },
    {
      data: [17, 11],
      name: "PRODUCT C",
    },
    {
      data: [11, 17],
      name: 'PRODUCT D',
    },
    ],
    colors: ["#B7A0E0", "#EC99C2", "#FEBF89", "#FFE083","#C4F9CA", "#A3C4F3", "#98F5E1", "#FDE4CF"],
    chart: {
      type: "bar",
      stacked: true,
      toolbar: {
        show: false,
      },
    },
    xaxis: {
      categories: ["Assets", "Liabilities & Equity"],
    },
    fill: {
      opacity: 1,
    },
    legend: {
      show: false,
    },
    plotOptions: {
        bar: {

          horizontal: false,
          borderRadius:  10,
          borderRadiusApplication: "end",
          borderRadiusWhenStacked: "last",
          
        },
      },
  };
here i am pass 8 color but 4 colors are display for both bars i want 4 color for 1st and bar and another 4 for 2nd bar please give me the solution

**Comment by nareshpatil031886** [comment]
![Screenshot (3)](https://github.com/apexcharts/apexcharts.js/assets/101571740/5105ee3b-dc99-480b-beb6-7230d204135e)
here i am passed 8 color for each data item but its only show first 4 color for  both bar 1 and bar 2 i want to 4 colors for 1st bar and another 4 color for second bar  please give me the solution                                                                                                                            const ebChartData = {
    series: [
    {
      data: [17, 11],
      name: "PRODUCT A",
    },
    {
      data: [17,11],
      name: 'PRODUCT B',
    },
    {
      data: [17, 11],
      name: "PRODUCT C",
    },
    {
      data: [11, 17],
      name: 'PRODUCT D',
    },
    ],
    colors: ["#B7A0E0", "#EC99C2", "#FEBF89", "#FFE083","#C4F9CA", "#A3C4F3", "#98F5E1", "#FDE4CF"],
    chart: {
      type: "bar",
      stacked: true,
      toolbar: {
        show: false,
      },
    },
    xaxis: {
      categories: ["Assets", "Liabilities & Equity"],
    },
    fill: {
      opacity: 1,
    },
    legend: {
      show: false,
    },
    plotOptions: {
        bar: {

          horizontal: false,
          borderRadius:  10,
          borderRadiusApplication: "end",
          borderRadiusWhenStacked: "last",
          
        },
      },
  };
