### ISSUE TITLE
A comparison table and motivation behind this library would be great

### ISSUE THREAD

**Issue by xumix** [apexcharts/apexcharts.js#390]
It would be great to have a doc providing key differentiating/comparison points for this library.
For example: https://github.com/naver/billboard.js/wiki/Why-we-decided-to-start-billboard.js%3F
https://github.com/naver/billboard.js/wiki/Comparison-table

**Comment by junedchhipa** [comment]
Good suggestion, I will write a blog post on the website and link it on GitHub.

**Comment by junedchhipa** [comment]
Added a comparison table - https://apexcharts.com/javascript-charts-comparison/

**Comment by xumix** [comment]
I'm currently already using your awesome library, thanks for your great work!
Just a little correction: the table actually lacks your library benefits, key features/differences and motivation for creating/using this library. So someone like me could easily look at the table and choose apexcharts instead of C3 for example.

**Comment by junedchhipa** [comment]
I agree that the table doesn't do justice as it states the downloads, stars, size and license type.
I will include more info to the post later.
Thanks for the suggestion.
