### ISSUE TITLE
tickAmount for datatime

### ISSUE THREAD

**Issue by guestisp** [apexcharts/apexcharts.js#3902]
We rely on some datatime series on X, but the current tick interval doesn't make sense at all, most of the time, there isn't any tick connected to a data point, but only between them. This makes the data shown as label, useless (primary on mobile, as we don't know which time is related to the point, without hovering on the tooltip)

Any workaround ? i've tried with `category` type, but this breaks the ajax zoom/scroll because there isn't any starting/ending date sent to the server.

**Comment by guestisp** [comment]
Look at this
![image](https://github.com/apexcharts/apexcharts.js/assets/3944655/7d5926c2-191e-40f6-abd0-0232ef868f36)

the left points are for 23/06 13:09, but the label is showing 13:53. 
Then no label for the points on the right, it's impossible to know the time without the tooltip

So, what's the meaning for the current auto-generated labels in a datetime series, is the labels are wrong ?

**Comment by guestisp** [comment]
no reply in 2 months. probably it's a dead project

**Comment by brianlagunas** [comment]
Closing as this is not a feature request, but rather a questions disguised as a feature request. Please ask questions in the discussions so the community can help.

**Comment by guestisp** [comment]
i think it's mostly a bug
