### ISSUE TITLE
Chart Type Error: apexcharts.common.js:1452

### ISSUE THREAD

**Issue by ritzcod3** [apexcharts/apexcharts.js#3904]
### Description
I have been experiencing a chart type error recently when using Apex charts on React version 18.2. The error links back to apexcharts.common.js:1452. I am using Apex Charts with React and had no problems for quite some time but now when I add a new chart on the web app, there is a consistent "type" error. I have included the chart type options and have tested the charts as class extensions and functional components and still see the same issue. I was getting the same type error for any chart type but was able to resolve the other chart types aside from bar charts. 

Note: The chart still populates the data on the live site but returns uncaught runtime errors. I have multiple other Apex charts on the app and all work without any problems. The bug seems to be on any "new" chart additions to the web app. The old/pre-existing charts are working as is with no problems. If you ignore the error, the web app and chart still populates as it should but the message appears every time you refresh or render the component. 

### Repro Steps: 

1. Create a react-app - version 18.2
2. Install react-apexcharts npm
3. Add a basic bar chart, like this, to the web app – https://apexcharts.com/react-chart-demos/bar-charts/basic/
4. Make sure type is set to "bar"
5. Run the app

### Expected Behavior
Chart type error does not affect runtime performance.

### Actual Behavior
1. Yarn start 
2. "Uncaught runtime errors"when component is rendered.

### Screenshots
<img width="905" alt="apexBundleTypeErrror" src="https://github.com/apexcharts/apexcharts.js/assets/50591073/d647c66e-e285-453b-8b20-ef7f100dfe5e">
<img width="1013" alt="Error" src="https://github.com/apexcharts/apexcharts.js/assets/50591073/22d80377-75c2-4012-84c0-298bb61db5e3">

### Reproduction Link
- N.A. – Hosted locally (for now)

Codepen used: https://codesandbox.io/s/6yoqonyo7r

You can literally copy and paste the code into the react app and go from there. Any help here would be greatly appreciated. Thanks!

**Comment by brianlagunas** [comment]
The reproduction link does not reproduce the error. Please provide a sample app that can reproduce the error, or this issue will be closed.
