### ISSUE TITLE
Grouped Stacked Chart: Add group legend labels

### ISSUE THREAD

**Issue by kevin-moser** [apexcharts/apexcharts.js#3907]
## Summary

The newly added chart type for bar charts (grouped & stacked) has separated legend labels for each series, which get pretty long when having multiple series in a single chart. The ability to group legend labels by series with same names (?) would be nice.

## Intended Use Case

Better UI for legend labels for [grouped & stacked bar charts](https://apexcharts.com/javascript-chart-demos/column-charts/grouped-stacked-columns/) with same functionality of hiding the separate series.
Example of a UI mockup attached below:

Current legend layout:
![current](https://github.com/apexcharts/apexcharts.js/assets/137761326/a75efa05-3399-491b-bbf1-5d21e396ef3e)

Proposed grouped layout:
![grouped](https://github.com/apexcharts/apexcharts.js/assets/137761326/4306a304-defb-4186-b1ca-5b98d32262b1)

**Comment by mpkhr** [comment]
+1

@kevin-moser did you find a way to solve it?

**Comment by abalone49** [comment]
+1 Need that feature

**Comment by MaksSieve** [comment]
+1
any workarounds may be?

**Comment by junedchhipa** [comment]
Added new config for this
```js
options = {
  legend: {
    clusterGroupedSeries: true,
    clusterGroupedSeriesOrientation: "horizontal" // available options ["vertical", "horizontal"]
  }
}
```
which creates legend like below
![Screenshot 2024-11-29 at 12 46 46 PM](https://github.com/user-attachments/assets/d534f235-110f-4ee7-93a2-638d462c030c)

The new options will be available in the next release `v4.2.0`

**Comment by MaksSieve** [comment]
@junedchhipa thx! but could you also make it for v3.x.x? it's not possible to use version more than 3 with old projects that use Node v16

**Comment by MaksSieve** [comment]
@junedchhipa also another but related question: is it possible to add labels for groups on X-axis?
smth like this:
![image](https://github.com/user-attachments/assets/da8e1cbb-9a1a-4b1d-89d6-b4e652fc90e7)

**Comment by MaksSieve** [comment]
@junedchhipa any ideas?
