### ISSUE TITLE
Mixed chart multiple y-axes scaling bug

### ISSUE THREAD

**Issue by johannegger** [apexcharts/apexcharts.js#391]
Hi, 
thank you for the awesome work!

I think there is a bug when creating a mixed (bar + line) chart with multiple axes and supplying min/max. 
I tried to minimize my code to reproduce the behaviour [here]( https://stackblitz.com/edit/typescript-yebrvd).

As you can see the the datapoints of series2 are somewhere between ~30 and ~50 but on the according y-axes (to the right) the lie somewhere between 70 and 80.

interesting is also that when supplying a function for min and max which should use the min/max as an input it seems to use the min/max values of **series1** - i don't know if that's related or not.

**Comment by junedchhipa** [comment]
Thanks for reporting, I confirm the issue.
Will be fixed soon.

**Comment by mzf** [comment]
have same issue(3.6.2), when will be released version with fix?

**Comment by junedchhipa** [comment]
17 april

**Comment by junedchhipa** [comment]
Sorry, 17th March. This sunday

**Comment by mzf** [comment]
3.6.2 still

**Comment by junedchhipa** [comment]
3.6.3 is released yesterday. Can you update manually?

**Comment by mzf** [comment]
Thanks a lot! All works as expected
