### ISSUE TITLE
Safari: legend position will offset when zoom in Apexcharts in the Safari browser

### ISSUE THREAD

**Issue by VaibhavTessell** [apexcharts/apexcharts.js#3921]
### Description

This bug is same as: https://github.com/apexcharts/apexcharts.js/issues/2963
It got fixed in Version 3.37.2 but then I can see the regression in the recent versions. 

### Steps to Reproduce

1. 
2. 
3.

**Comment by VaibhavTessell** [comment]
@brianlagunas As per github rights, I'm not allowed to re-open issues opened by someone else and closed by the collaborator. Would you please re-open that issue?

![image](https://github.com/apexcharts/apexcharts.js/assets/109062808/201f8a63-e117-45f0-92c0-a6f423e4eaf8)

**Comment by brianlagunas** [comment]
That’s why I asked you to request to repopen. Please comment not on the post you want to reopen
