### ISSUE TITLE
how to unhide partially hidden first and last columns in Apex charts?

### ISSUE THREAD

**Issue by githubHemanth** [apexcharts/apexcharts.js#3925]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/3923

<div type='discussions-op-text'>

<sup>Originally posted by **githubHemanth** July 10, 2023</sup>
How to unhide partially hidden first and last bars in grouped-bar-chart of Apex charts ? I have tried using 'min' and 'offsetX' (unhides bars) but they rearrange the x-axis scale and bars. Is there any best way to unhide the columns with chart options ? (don't want to use css).
Or the above are only options we should use ?

`xaxis: {
    categories: ['<0 Days', '0-30 Days', '31-60 Days', '61-90 Days', '91-180 Days', '>180 Days'],
    labels: { style:{fontWeight: 800} },
  //min:0.9,
  //offsetX:-160,
    tickPlacement: 'on',           
        },`

<img width="949" alt="Untitled" src="https://github.com/apexcharts/apexcharts.js/assets/60767478/604836cc-bf11-471e-8df5-a41a3d421e01">
</div>

**Comment by brianlagunas** [comment]
Did not follow issue instructions

**Comment by githubHemanth** [comment]
> Did not follow issue instructions

Sorry, what are those instructions ?
