### ISSUE TITLE
Adjustable padding in timeline charts

### ISSUE THREAD

**Issue by Blobie1012** [apexcharts/apexcharts.js#3927]
## Summary

Somewhere between version 3.35.0 and 3.41.0 a padding was added to the timeline charts which cannot be changed. Would it be possible to make the padding adjustable?

Here are two screenshots showing how it looked before and after the changes.

##Old

![timeline_old](https://github.com/apexcharts/apexcharts.js/assets/65309474/08fdbc19-e09d-45ee-97eb-603a42ac7c32)

##New

![timeline_new](https://github.com/apexcharts/apexcharts.js/assets/65309474/7a4aa0ee-4493-4fdf-97fe-8b493c72c7bf)

**Comment by junedchhipa** [comment]
Can you create a codepen demo to reproduce this easily?

**Comment by Blobie1012** [comment]
https://stackblitz.com/edit/stackblitz-starters-b75a77?file=package.json

Here is a demo.

There are two empty timeline. And when you update apexcharts to version 3.41.0, each timeline has a padding which you cannot controlle.
