### ISSUE TITLE
Better position of data labels/markers

### ISSUE THREAD

**Issue by xumix** [apexcharts/apexcharts.js#393]
**Is your feature request related to a problem? Please describe.**
On line chart, when data text is long it may overlap with the chart line. Also long text gets truncated in the strt/end of the chart. See screenshots

**Describe the solution you'd like**
Maybe position  the text above/beyond depending of curve?

![2019-03-12-14-46-24_HXZrwDabCA](https://user-images.githubusercontent.com/250118/54197692-ab0d2900-44d5-11e9-8e50-3b95ff62660e.png)

**Comment by junedchhipa** [comment]
The truncating of the text definitely looks wrong as it gives wrong impressions.
Will look into it.

**Comment by xumix** [comment]
I suppose the text position can be calculated as
```const position = (f(x-1) > f(x) || !f(x-1)) && (!f(x+1) || f(x+1) > f(x)) ? "beyond" : "above"```

**Comment by xumix** [comment]
thanks!

**Comment by xumix** [comment]
![image](https://user-images.githubusercontent.com/250118/55322044-da370a80-5483-11e9-9c7c-54955792df9b.png)
Looks better, but still labels are trimmed :(
