### ISSUE TITLE
Ability to initialise a line chart with a preselected marker.

### ISSUE THREAD

**Issue by roflson** [apexcharts/apexcharts.js#394]
I would like to be able to control which markers are marked as selected.

I think it should be added to the markers options alongside the discrete setting.

At the moment there is no way for an external component or script to mark or unmark selected markers.

**Comment by junedchhipa** [comment]
```javascript
chart.toggleDataPointSelection(0, 1)
```
where 0 is the series-index and 1 is the data-point-index

https://apexcharts.com/docs/methods/#toggleDataPointSelection
