### ISSUE TITLE
Some xaxis lables offset when zooming in

### ISSUE THREAD

**Issue by demestav** [apexcharts/apexcharts.js#3953]
### Description

Under certain conditions, the xaxis time labels do not match the datapoint's time, when zooming in.

### Steps to Reproduce

1. Use the following code to reproduce:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ApexCharts Line Graph</title>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
</head>
<body>
  <div id="chart"></div>

  <script>
    var dataPoints = [];
    var currentDate = new Date();
    currentDate.setMinutes(currentDate.getMinutes() - 2 * 24 * 60); // Set to 7 days ago

    // Generating random data points for every 10 minutes for 7 days
    for (var i = 0; i < (7 * 24 * 60) / 10; i++) {
      dataPoints.push({
        x: new Date(currentDate.getTime() + i * 10 * 60 * 1000),
        y: Math.random() * 100 
      });
    }

    var options = {
      chart: {
        type: 'line',
        height: 350,
      },
      series: [{
        name: 'Random Data',
        data: dataPoints
      }],
      xaxis: {
        type: 'datetime',
      },
      yaxis: {
        min: 0,
        max: 100
      },
      tooltip: {
        x: {
          show: true,
          format: 'dd/MM/yy HH:mm' // Date format for the tooltip
        }
      }
    };

    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();
  </script>
</body>
</html>
```
2. Zoom on the chart. **The zoom time frame should start after 23:00 and before 00:00.** Zoom time frame should contain a few hours (close time frame at about 03:00, not critical for reproducing the bug).

### Expected Behavior
In the zoomed in view, the xaxis should reflect the data point's time stamp.
### Actual Behavior
After 00:00 the xaxis labels seem to be shifted to the right.
### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/1180929/a2e3c4cb-a41a-4ac9-8be7-e3ea945a4b1d)

**Comment by brianlagunas** [comment]
Reproducible codepen not provided

**Comment by demestav** [comment]
> Reproducible codepen not provided

I don't have a codepen account. The code I posted is complete and it just needs to copy and pasted and it works.
