### ISSUE TITLE
Labels stands on top of each other

### ISSUE THREAD

**Issue by timclausen** [apexcharts/apexcharts.js#396]
## Codepen
https://codepen.io/difedk/pen/wNYpVw
<img width="848" alt="Skærmbillede 2019-03-13 kl  10 15 39" src="https://user-images.githubusercontent.com/2226613/54267308-44d9e200-4579-11e9-907e-9e932f8e4c72.png">

## Explanation

- What is the behavior you expect?
The labels will at some point hit each other and stand on top. I've tried avoiding this with padding and offset etc.. however, this doesn't do the trick.. How can this be more logic so the labels not clutter together?

An other thing regarding this issue. Is it possible to set z-index to the line, so that it lays behind the bars?

**Comment by junedchhipa** [comment]
The y-axis annotation label cannot detect possible values around it and is unaware of the data labels. So it's difficult to prevent such a scenario.

Regarding your z-index query, you can try `annotations.position: 'back'` which puts annotation lines behind bars.

**Comment by junedchhipa** [comment]
You can also give the annotation label a background color so the text doesn't look jumbled.

**Comment by timclausen** [comment]
I tried the position back thing, but I didn't seem to make any difference?

Knowing that the y-axis annotation label cannot detect possible values around it, would it be possible to add a margin-left to the y-axis annotation label? That way it would always stay out of collissions. The offset parameter will make the label disappear out of the chart frame.

**Comment by timclausen** [comment]
?

**Comment by junedchhipa** [comment]
You can provide offsets to the annotation, but that would result in the wrong information. I suggest you provide background to the annotation label, so even though it would overlap, it won't look ugly.

```javascript
  annotations: {
    position: 'front',
    yaxis: [
      {
        y: 9.5,
        borderColor: "#111",
        
        label: {
          borderColor: "transparent",
          style: {
            fontSize: '14px',
            color: "#666",
            background: "#e7e7e7",
            padding: {
              left: 15,
              right: 15,
              top: 10,
              bottom: 12
            }
          },
          text: "9,5% p.a."
        }
      }
    ]
  }
```

![Screen Shot 2019-03-30 at 1 11 40 PM](https://user-images.githubusercontent.com/17950663/55273154-6f53cb00-52ed-11e9-8b94-12d9c9e148ae.png)

Codepen example https://codepen.io/apexcharts/pen/MRgBJw
