### ISSUE TITLE
apex legend formatter is not creating tspan when returning an array

### ISSUE THREAD

**Issue by dlibis** [apexcharts/apexcharts.js#3962]
### Steps to Reproduce

1. use the example from the docs   
  ```
 formatter: function(seriesName, opts) {
        return [seriesName, " - ", opts.w.globals.series[opts.seriesIndex]]
    }
```

### Expected Behavior
as seen here: https://github.com/apexcharts/apexcharts.js/issues/57#issuecomment-802794423

### Actual Behavior
all the output is inside span tag

### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/63005208/f9f4d303-b50e-4c96-824c-18115f04b1cf)

**Comment by brianlagunas** [comment]
Did not provide required codepen
