### ISSUE TITLE
Units for y axes to group them together

### ISSUE THREAD

**Issue by anatolsommer** [apexcharts/apexcharts.js#3963]
## Summary

My only problem with this awesome library so far, is that having multiple series of which some but not all are sharing the same unit makes you chose between
* using only one y axis with no labels or units displayed
* using multiple y axes, hide all but one with the same unit and
    * using fixed min and max values for all y axes with the same unit
    * implement a function that finds minY and maxY depending on the data (filtered by minX and maxX) and apply these to all axes using the same unit

This could be solved relatively easy by grouping axes together and use the existing functionality that dynamically calculates the minY and maxY but instead of doing this per y axis, doing it using a new property that can be used on multiple y axes.

## API Changes

A new property for y axis configuration called `unit`.

```js
{
  options:{
    yaxis:[{
      seriesName:'Living room',
      unit:'temp',
      show:true,
      showAlways:true,
      labels:{
        formatter:val => (typeof val === 'number' ? val.toFixed(1) + '°C' : '')
      }
    }, {
      seriesName:'Bed room',
      unit:'temp',
      show:false,
      labels:{
        formatter:val => (typeof val === 'number' ? val.toFixed(1) + '°C' : '')
      }
    }, {
      seriesName:'Outside',
      unit:'temp',
      show:false,
      labels:{
        formatter:val => (typeof val === 'number' ? val.toFixed(1) + '°C' : '')
      }
    }, {
      seriesName:'Wind',
      unit:'wind',
      show:true,
      showAlways:true,
      opposite:true,
      labels:{
        formatter:val => (typeof val === 'number' ? val.toFixed(1) + 'km/h' : '')
      }
    }]
  }
}
```

## Intended Use Case

This would be a simple way to use the same unit for multiple series without losing the benefit of dynamic min and max values when zooming or hiding series. This also seems the problem mentioned in #91 (that is closed for some reason, probably because "The design decision to keep the y-axis correlate with the series was taken pretty early on. So, a big chunk of code will need a rewrite if I change this.")

I think my solution might be a good way to solve that problem without having to rewrite that much code. For my specific needs this code (slightly simplified and adapted version because I'm using Vue3) did the job:

```js
function setMinMax() {
  var {minX, maxX} = chartContext.w.globals, units = {};
  data.forEach((series, i) => {
    var unit = options.yaxis[i].unit;
    units[unit] = units[unit] || {};
    if (chartContext.series.isSeriesHidden(series.name).isHidden) {
      return;
    }
    series.data.forEach(d => {
      if (d.x < minX || d.x > maxX) {
        return;
      }
      if (units[unit].minY === undefined || d.y < units[unit].minY) {
        units[unit].minY = d.y;
      }
      if (units[unit].maxY === undefined || d.y > units[unit].maxY) {
        units[unit].maxY = d.y;
      }
    });
  });
  Object.values(units).forEach(unit => {
    unit.minY = Math.floor(unit.minY);
    unit.maxY = Math.round(unit.maxY + 1);
  });
  options.yaxis.forEach(yaxis => {
    yaxis.min = units[yaxis.unit].minY;
    yaxis.max = units[yaxis.unit].maxY;
  });
  chartContext.updateOptions({
    yaxis:options.yaxis
  });
}
```
![image](https://github.com/apexcharts/apexcharts.js/assets/16275957/f4cec14e-3249-4679-8658-dd5265d98bd7)

Ofc I simply could use that code for every chart that has this problem but a general solution for everyone would improve this library even more. Thanks a lot for your great work, for reading this and considering an implementation.

**Comment by BahodurSaidov** [comment]
For those who are wondering, like me, how to set min and max for each yaxis without above function:
`yaxis: [
        {
            showAlways: true,
            min: 0,
            max: 100,
            axisTicks: {
                show: true,
            },
            axisBorder: {
                show: true,
                color: '#008FFB'
            },
            labels: {
                style: {
                    colors: '#008FFB',
                }
            },
            title: {
                text: "Temperature (˚F)",
                style: {
                    color: '#008FFB',
                }
            },
            tooltip: {
                enabled: true
            }
        },
        {
            min: 0,
            max: 100, show: false
        },
        {
            min: 0,
            max: 100, show: false
        }
]
`
each obj is order dependent, you can tune min max by trying whatever suits your data requirements.
