### ISSUE TITLE
 When I make a change of values ​​to render in the graph, the xaxis and graph values ​​disappear

### ISSUE THREAD

**Issue by GabrielRodriguesFerreira-TI** [apexcharts/apexcharts.js#3968]
### Description

This is the graphic right after the page refresh or the first rendering:
![image](https://github.com/apexcharts/apexcharts.js/assets/109962612/a738611f-1791-4c06-a5dc-a9947b37f7fb)

When I switch to any other option... the xaxis labels and chart values ​​disappear:
![image](https://github.com/apexcharts/apexcharts.js/assets/109962612/309b8a5a-8310-4289-b611-50ea04acc80f)

The code is being made in react:

export default function CardGraph({ series, seriesChar, labels, colors, idChart, name }) {

    const availableChar = [seriesChar]

    const allSeries = useMemo(() => {
        const newSeries = [
            {
                type: "area",
                name: name,
                data: series
            }
        ]

        return newSeries;
    }, [name, series]);

    const options = {
        chart: {
            id: idChart,
            type: 'area',
            toolbar: {
                show: true,
                offsetX: 0,
                offsetY: 0,
                tools: {
                    download: false
                },
                autoSelected: 'pan'
            },
        },
        colors: colors ?? [],
        labels: labels ?? [],
        stroke: {
            curve: 'smooth'
        },
        title: {
            text: `${name}`,
            align: 'left'
        },
        yaxis: [
            {
                labels: {
                    formatter: (val) => {
                        const char = availableChar[0]
                        return val.toFixed(0) + `${char}`
                    },
                },
            }
        ],
        legend: {
            show: false
        }
    }

    return (
        <div className="w-full relative flex flex-col gap-6">
            <ReactApexChart options={options} series={allSeries ?? []} type="area" height="350px" width="100%" />
        </div>
    )
}

And it is being called in this component:

const CardGraphMemoized = memo(CardGraph)

export default function CardView({ forecastsValuesDay, platformDetails }) {

    const { t } = useTranslation('climatic');

    const graphCardOptions = useMemo(() => [
        { label: t("translate.reactView.weatherForecast.tableView.greatness.airTemperature"), charRef: t("translate.reactView.weatherForecast.cardView.temperatureFormat.F"), key: "air_temperature", border: true },
        { label: t("translate.reactView.weatherForecast.tableView.greatness.rain"), charRef: "mm", key: "rain", border: true },
        { label: t("translate.reactView.weatherForecast.tableView.greatness.wind"), charRef: "km/h", key: "wind_speed", border: true },
        { label: t("translate.reactView.weatherForecast.tableView.greatness.relativeHumidity"), charRef: "%", key: "relative_humidity", border: false }
    ], [t])

    const [currentHourData, setCurrentHourData] = useState(null);
    const [selectedOption, setSelectedOption] = useState(graphCardOptions[0]);

    useEffect(() => {
        function updateHourlyData() {
            const currentHour = new Date().getHours();
            const dayData = forecastsValuesDay[0];

            let closestHourData = dayData.hoursOnDay[0];
            let closestHourDifference = Math.abs(currentHour - closestHourData.hour);

            dayData.hoursOnDay.forEach((hourData) => {
                const hourDifference = Math.abs(currentHour - hourData.hour);
                if (hourDifference < closestHourDifference) {
                    closestHourData = hourData;
                    closestHourDifference = hourDifference;
                }
            });
            setCurrentHourData(closestHourData);
        }

        updateHourlyData();

        const intervalId = setInterval(updateHourlyData, 60 * 60 * 1000);

        return () => clearInterval(intervalId);
    }, [forecastsValuesDay]);

    const formattedDay = useMemo(() => {
        const date = forecastsValuesDay[0].date
        let parsedDate = null

        if (i18n.language === "pt-BR") {
            parsedDate = parse(date, 'dd MMM', new Date(), { locale: ptBR });
        } else {
            parsedDate = parse(date, 'MMM dd', new Date(), { locale: enUS });
        }

        const formattedDayOfMonth = format(parsedDate, 'dd', { locale: i18n.language === 'pt-BR' ? ptBR : enUS });
        let formattedDayOfWeek = format(parsedDate, 'EEEE', { locale: i18n.language === 'pt-BR' ? ptBR : enUS });
        formattedDayOfWeek = formattedDayOfWeek.charAt(0).toUpperCase() + formattedDayOfWeek.slice(1)

        return {
            formattedDayOfMonth,
            formattedDayOfWeek
        }
    }, [forecastsValuesDay])

    const graphDataValues = useMemo(() => {

        const selectedOptionKey = selectedOption.key;
        const dayData = forecastsValuesDay[0];

        const optionValues = dayData.hoursOnDay.map((hourData) => hourData[selectedOptionKey]);
        const hours = dayData.hoursOnDay.map((hourData) => hourData.hour)

        return {
            optionValues,
            hours
        }

    }, [selectedOption])

    const handleOptionClick = (entry) => {
        setSelectedOption(entry);
    };

    return (
        <div className="w-full flex flex-col gap-28 px-24 pt-24">
            {currentHourData && (
                <>
                    <HeaderCard
                        currentHourData={currentHourData}
                        formattedDay={formattedDay}
                        platformDetails={platformDetails}
                    />

                    <Grid container spacing={2} className="flex flex-col gap-20">
                        <Grid item className="flex">
                            {graphCardOptions.map((entry) => (
                                <GraphOptionsContainer
                                    border={entry.border}
                                    key={entry.key}
                                    onClick={() => handleOptionClick(entry)}
                                >
                                    <StyledP className="text-16 font-500" selected={selectedOption.key === entry.key}>
                                        {entry.label}
                                    </StyledP>
                                </GraphOptionsContainer>
                            ))}
                        </Grid>
                        <Grid item className="w-full">
                            {selectedOption ? (
                                <CardGraphMemoized
                                    series={graphDataValues.optionValues || []}
                                    seriesChar={selectedOption.charRef || []}
                                    labels={graphDataValues.hours || []}
                                    colors={["#D04343"]}
                                    name={selectedOption.label}
                                    idChart="weatherForecastGraph"
                                />
                            ) : (
                                <div>
                                    loading...
                                </div>
                            )}
                        </Grid>
                    </Grid>
                </>
            )}
        </div>
    )
}

**Comment by brianlagunas** [comment]
Did not provide a reproduction sample app.
