### ISSUE TITLE
getChartByID throws exception

### ISSUE THREAD

**Issue by andrewgoz** [apexcharts/apexcharts.js#3975]
### Description

Calling ApexCharts.getChartByID() before any charts have been rendered generates an exception.

### Steps to Reproduce

1. Create a new HTML page, use the CDN for the library (or local).
2. Call ApexCharts.getChartByID('anythinghere')

### Expected Behavior

It should return undefined and not throw an exception.

### Actual Behavior

An exception is thrown "Cannot read properties of undefined (reading 'filter')"

### Reproduction Link

https://codepen.io/andrewg_oz/pen/ZEVGBEv?editors=1111

**Comment by junedchhipa** [comment]
fixed with [commit](2026bd6fce3946bc734b799ea6739695fa46008b)
