### ISSUE TITLE
Stacked Chart (Bar/Area) does not stack, but overlay

### ISSUE THREAD

**Issue by RichardSiebenmorgen** [apexcharts/apexcharts.js#3976]
### Steps to Reproduce

I use a data Array for the series which is in the following format:

// code
**SeriesDate stringfied:** 
[{"name":"Mobile BNT","type":"bar","data":[{"x":"2023-06-14T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-15T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-16T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-17T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-18T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-19T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-20T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-21T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-22T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-23T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-24T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-25T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-26T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-27T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-28T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-29T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-06-30T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-01T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-02T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-03T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-04T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-05T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-06T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-07T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-08T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-09T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-10T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-11T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-12T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-13T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-14T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-15T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-16T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-17T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-18T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-19T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-20T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-21T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-22T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-23T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-24T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-25T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-26T00:00:00.000Z","y":0.4880952380952381},{"x":"2023-07-28T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-07-29T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-07-30T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-07-31T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-01T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-02T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-03T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-04T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-05T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-06T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-07T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-08T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-09T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-10T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-11T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-12T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-13T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-14T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-15T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-16T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-17T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-18T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-19T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-20T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-21T00:00:00.000Z","y":2.7142857142857357},{"x":"2023-08-22T00:00:00.000Z","y":2.7142857142857357}]},{"name":"Festnetz BNT","type":"bar","data":[{"x":"2023-07-05T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-06T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-07T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-08T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-09T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-10T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-11T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-12T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-13T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-14T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-15T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-16T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-17T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-18T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-19T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-20T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-21T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-22T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-23T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-24T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-25T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-26T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-27T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-28T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-29T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-30T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-07-31T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-01T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-02T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-03T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-04T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-05T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-06T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-07T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-08T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-09T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-10T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-11T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-12T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-13T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-14T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-15T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-16T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-17T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-18T00:00:00.000Z","y":0.7070707070707082},{"x":"2023-08-21T00:00:00.000Z","y":3.1818181818181714},{"x":"2023-08-22T00:00:00.000Z","y":3.1818181818181714},{"x":"2023-08-23T00:00:00.000Z","y":3.1818181818181714}]}]

**Options**
var options = {
    series: [],
    chart: {
      id: crypto.randomUUID(),
      type: 'bar',
      stacked: true,
      height: 350,
      fontFamily: 'Poppins',
      animations: {
        enabled: true,
      },
      toolbar: {
        show: false,
      },
      redrawOnParentResize: false,
      redrawOnWindowResize: false,
    },
    stroke: {
      curve: 'smooth',
      lineCap: 'round',
      width: 2,
    },
    tooltip: {
      enabled: true,
      x: {
        show: true,
        // format: 'dd MMM <b>HH:mm</b>',
        // formatter: undefined,
      },
    },
    grid: {
      show: false,
    },
    dataLabels: {
      enabled: false,
    },
    legend: {
      itemMargin: {
        vertical: 30
      },
    },
    xaxis: {
      type: 'datetime',
      labels: {
        show: true,
        datetimeUTC: false,
        // datetimeFormatter: {
        //   day: 'dd MMM',
        //   hour: 'HH:mm'
        // },
        style: {
          colors: ['#333'],
          fontSize: '10px',
          fontFamily: 'Poppins',
        },
      },
    },
    yaxis: {
      min: 0,
      show: true,
      labels: {
        show: true,
        align: 'right',
        style: {
          colors: ['#333'],
          fontSize: '10px',
          fontFamily: 'Poppins',
        },
        formatter: (val) => { return val.toFixed(0) },
      },
    },
    colors: ['#6307a6', '#f5ae20']
  };
// code

The x-values are provided by a Date Object. 

When I render the chart or Update it I get the following result: 
<img width="683" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/142969618/6358ecf7-4ca7-4389-8c6a-0bd3d376c02a">

### Expected Behavior
The Chart shoud render with stacked Bars

### Actual Behavior
The bars overlay

### Screenshots
<img width="683" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/142969618/6358ecf7-4ca7-4389-8c6a-0bd3d376c02a">

**Comment by brianlagunas** [comment]
Required reproduction link not provided
