### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')     at t.value 

### ISSUE THREAD

**Issue by UAhmadSoft** [apexcharts/apexcharts.js#3992]
I want to showSeries on button click in react js with this code but facing error

window.ApexCharts.exec("earnings-chart", "showSeries",  "Total Earnings" )
I've also tried these variants
window.ApexCharts.exec("earnings-chart", "showSeries",   [ "Total Earnings" ])
window.ApexCharts.exec("earnings-chart", "showSeries",  { name  : "Total Earnings" } )
window.ApexCharts.exec("earnings-chart", "showSeries",  [ {"Total Earnings" }])

please me is there any wrong in syntax ?

**Comment by Reached** [comment]
I got the same problem
