### ISSUE TITLE
Could you add the first gauge chart in README to the demo page?

### ISSUE THREAD

**Issue by xianxingg** [apexcharts/apexcharts.js#4]
i mean the chart with a label of 'Percent'.
it seems that the color of this chart is linear-gradiented by the round path. I've done some research and was disappointed to find out that in modern browsers we cannot make that ( in android we may ) since the only two color gradients that v8 supports do not match this requirement.

**Comment by junedchhipa** [comment]
I will add the demo, but let me clarify that it is indeed just a linear gradient going from left to right, and not based on the path. It looks like the color starts with the start-angle and ends at another angle, but if you look closely, it is just a simple horizontal gradient applied to the whole area.
![screen shot 2018-07-30 at 12 16 18 pm](https://user-images.githubusercontent.com/17950663/43381474-6773c9a4-93f2-11e8-8035-88d3a2847c11.png)

**Comment by junedchhipa** [comment]
Here is the demo added to the website (with source)
https://apexcharts.com/javascript-chart-demos/radialbar-charts/gradient/

**Comment by xianxingg** [comment]
Really appreciate that :)

**Comment by junedchhipa** [comment]
Thanks for reporting. It was displaying correctly in chrome but in Safari, I noticed the same issue which you posted above. Commit https://github.com/apexcharts/apexcharts.js/commit/cf2688c77a8f140e78b4eaebc902b06cb153c5e4 fixed this issue.
