### ISSUE TITLE
 Chart not showing yAxis if draw after Sparkline

### ISSUE THREAD

**Issue by ludovicthomas** [apexcharts/apexcharts.js#40]
It seems to have an issue when a Sparkline chart is rendered first in a page, and then after a "classic" chart is rendered.

The "classic" chart will not display the yAxis, even if we force it with options, or changing properties.

I have created a CodePen to show the issue: https://codepen.io/lthomas/pen/djBedE
At the end of the JS section, there are the two lines that can be reversed to reproduced the issue:

By rendering the sparkline **after** the chart, everything looks fine.
```
chart.render();
sparkline.render();
```
![cleanshot 2018-08-16 at 18 23 59](https://user-images.githubusercontent.com/154572/44221391-8d672380-a181-11e8-9ecf-74f51e5fc378.png)

By rendering the sparkline **before** the chart, the chart does'nt display the yAxis.
```
sparkline.render();
chart.render();
```
![cleanshot 2018-08-16 at 18 24 10](https://user-images.githubusercontent.com/154572/44221398-95bf5e80-a181-11e8-97b3-9461d7b238a7.png)

**Comment by junedchhipa** [comment]
I looked at the demo, very strange!
I will get back to work to look more into it.

**Comment by junedchhipa** [comment]
Fixed it. I was setting sparklines default options where I disabled labels for sparklines, and that was causing the issue.

**Comment by ludovicthomas** [comment]
Amazing! 🥇You are quick to fix issues! Thanks a lot.
