### ISSUE TITLE
Synchronized charts with Candlestick and Line don't line up

### ISSUE THREAD

**Issue by yoimnik** [apexcharts/apexcharts.js#4002]
https://stackoverflow.com/questions/62933011/problem-with-different-type-synchronized-charts-apexcharts-js

This stackoverflow pretty much explains my issue. I also followed everything in the guide: https://apexcharts.com/docs/chart-types/synchronized-charts/

In my case though, I am using a candlestick chart and a line chart. In most mouse positions, it is off by one. If I carefully move the mouse a little bit and find a sweet spot, it's aligned. But that's rarely gonna happen in nearly all user use cases.

My data has no issue -- if i change the candlestick chart to a line chart, both the line charts sync up perfectly.

<img width="217" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/12193963/1086494c-f304-42f4-9ea9-9a81f39d2b95">

Small sweet spot found:
<img width="239" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/12193963/412b73cf-3c29-4090-a557-b51977fb84f8">

**Comment by brianlagunas** [comment]
Did not follow bug template instructions.
