### ISSUE TITLE
Barchart x-annotations are not displayed

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#401]
## Codepen

https://codesandbox.io/s/nrk6ro3krm?fontsize=14

## Explanation

- What is the behavior you expect?
two x-axis annotations as in the followed image
![image](https://user-images.githubusercontent.com/46166884/54301041-74f7a400-45be-11e9-98cc-f0b5b4576a15.png)

- What is happening instead?
nothing is displayed and there is an unhandled error in the console
![image](https://user-images.githubusercontent.com/46166884/54301118-9c4e7100-45be-11e9-93c4-bd96bf0a9d5e.png)
![image](https://user-images.githubusercontent.com/46166884/54315646-f0694d80-45de-11e9-8b08-587019207de2.png)

This issue occurred after the release of version 3.6.0 of apexcharts

**Comment by AurelReb** [comment]
Hi, I also noticed on the same example that the tooltip is no longer displayed since 3.6.0 release

**Comment by junedchhipa** [comment]
The tooltip issue is also fix in the same commit.
