### ISSUE TITLE
TreeMap Paddings

### ISSUE THREAD

**Issue by nadar** [apexcharts/apexcharts.js#4011]
### Description

The treemap diagrams have strange paddings/margins.

### Steps to Reproduce

We use the vue wrapper, but it seems to be a general problem. Event the diagrams on the apexcharts website does have that strange padding/margin to the right, see: https://apexcharts.com/javascript-chart-demos/treemap-charts/basic/

![image](https://github.com/apexcharts/apexcharts.js/assets/3417221/e02a82f1-9468-4460-a74d-3016e25af4b3)

afaik, its depending on the number of data items, sometimes there is no padding if there are a few items, if there are less or maybe non-round numbers, then there is this gap.

If this sounds legit, or there 

### Expected Behavior

No paddings/margins to the right.

### Actual Behavior

Here you can see my implementation where grey is the chart background, and there are strange paddings/margin to the right and top.

![image](https://github.com/apexcharts/apexcharts.js/assets/3417221/9410fe7e-9d5e-407c-82e8-bd7b811699a2)

### Codesandbox

https://codesandbox.io/s/treemap-padding-issue-2dtwpw here you can see the padding to the right. The apex chart is gray and has some padding to the right which is not expected.

![image](https://github.com/apexcharts/apexcharts.js/assets/3417221/4be71b23-22dc-4987-af22-69c0d411befb)

**Comment by nadar** [comment]
using

```
xaxis: {
          show: false,
          labels: {
            show: false,
          },
          axisBorder: {
            show: false,
          },
          axisTicks: {
            show: false,
          },
        },
```

settings, resolves the padding to the right

**Comment by ruchernchong** [comment]
> using
> 
> ```
> xaxis: {
>           show: false,
>           labels: {
>             show: false,
>           },
>           axisBorder: {
>             show: false,
>           },
>           axisTicks: {
>             show: false,
>           },
>         },
> ```
> 
> settings, resolves the padding to the right

What an interesting fix though
