### ISSUE TITLE
Exporting chart with image fill doesn't work

### ISSUE THREAD

**Issue by eric3119** [apexcharts/apexcharts.js#4016]
### Description

The example chart in the documentation does not export .png or .svg files correctly. The fill image is not rendered in the exported file.

https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-images/

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/30029009/42b513d1-7177-42ac-8b84-fa7c80d456e4)

#### Downloaded .png

![image](https://github.com/apexcharts/apexcharts.js/assets/30029009/d54b5f0e-d688-4778-a951-66e61599036f)

### Reproduction Link

Can be reproduced directly from official documentation:
https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-images/

**Comment by HamadTheIronside** [comment]
+1
