### ISSUE TITLE
Markers disappears if the value is same as yaxis.max

### ISSUE THREAD

**Issue by OliverRomhagen** [apexcharts/apexcharts.js#4017]
### Description
If a data point is the same value as the max value of the Y-Axis when a custom max is set it won't render the marker that is expected there. You can hack fix this by setting `y-axis: max: (max) => max + 0.01`.

### Steps to Reproduce

1. Set y-axis: max: (max) => max

### Expected Behavior
Show the marker even if it's the same value as the y-axis max value.
### Actual Behavior
Not showing the marker if it reaches y-axis max value.
### Screenshots
<img width="770" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/29176836/4b2ed9d6-a52f-42bb-9c2c-5cb9995c9ad0">

### Reproduction Link
https://codepen.io/oliverromhagen/pen/bGOrqQy

**Comment by junedchhipa** [comment]
The bug is not only on the "monotoneCubic" curve but for any kind of line chart

**Comment by Knogobert** [comment]
It seems fixed now in your latest version 3.44.0

Nice work @junedchhipa!

**Comment by OliverRomhagen** [comment]
Version 3.44.0 seemed to  have fixed issue shown in the codepen, Gj @junedchhipa!
