### ISSUE TITLE
null values making monotoneCubic line graphs fallback to straight curve

### ISSUE THREAD

**Issue by OliverRomhagen** [apexcharts/apexcharts.js#4018]
### Description
If there are any null values in the data when using a line graph with a montoneCubic curve, the lines will fallback to using a straight curve. 

### Steps to Reproduce

1. Create a line graph with a monotoneCubic curve.
2. Set one of the values in the data points to null

### Expected Behavior
Calculate each line to be monotoneCubic even if there's any null value in the data points

### Actual Behavior
Right now is falling back to using a straight curve for all lines if there's any null value.

### Screenshots
<img width="764" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/29176836/33e90bbc-acdf-4889-ad6f-723cc616eb4e">
<img width="770" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/29176836/70cc7f0d-7dd0-4513-bc70-730e71bbbbac">

### Reproduction Link
https://codepen.io/oliverromhagen/pen/NWevjLR

**Comment by junedchhipa** [comment]
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/d9d650d7e4028726c541a01228800aa40821d3e8)
