### ISSUE TITLE
Complex custom formatter for x-axis

### ISSUE THREAD

**Issue by oburlaca** [apexcharts/apexcharts.js#402]
**Is your feature request related to a problem? Please describe.**
I'd like to display two series with data related to different periods of time. Example: google analytics shows 2 lines, comparing This week stats with Previous week stats.
![image](https://user-images.githubusercontent.com/1470654/54300103-dde21a80-45c4-11e9-9352-8380e68e18f4.png)

For now I'll hide tooltips, it's ok. I understand such feature implies custom SVG elements, positioning etc and I don't expect to have a customSVGFormatter function, it's overkill. 

**Describe the solution you'd like**
I'm thinking of 'categories' in series, not in xaxis. Example:
`series: [
    {
        data: ....,
        categories: ['March 1', 'March 2', 'March 3'] 
    },
    {
        data: ....,
        categories: ['March 5', 'March 6', 'March 7'] 
    }
]
`

and in `xaxis` to specify which categories to display. The default x tooltip formatting will then handle the rest ;)

**Comment by junedchhipa** [comment]
Easy!
[Codepen example](https://codepen.io/apexcharts/pen/rRJxOx)
![Screen Shot 2019-03-14 at 2 59 25 PM](https://user-images.githubusercontent.com/17950663/54345960-20116780-466a-11e9-8e6d-439d3901f78d.png)


The tooltip is drawn with HTML elements allowing very flexible customization

**Comment by oburlaca** [comment]
Wow!!! Great!
Thanks for the cool example.
I was reading about tooltip.x.formatter but didn't notice the Custom Tooltip chapter!
P.S. That's really powerful! I can add my own custom data to the chart config, and then later in Custom Tooltop function, with the `w` variable, I can use that data. Having `series.categories` is a good example.

**Comment by techday84** [comment]
hello,  thanks for this example. I took this example exercise to update the values ​​by ajax but I don't know why if I update the chart data with **chart.updateOptions** it updates the chart fine but the tooltip shows the value of w.config.series[0].categories[dataPointIndex] like as undefined.

Does anyone know why this it happen?

I have a graph painted with 5 points, and then I update those values ​​by ajax with chart.updateOptions, if the new graph has 10 values, the first 5 show me the data correctly and the others appear as undefined.

```
...
success: function( data ) {
...
chart.updateOptions({
            xaxis: {
              type: "datetime",
              categories: data.days,
            },
            tooltip: {
              custom: function({ series, seriesIndex, dataPointIndex, w }) {
                return (
                  '<div>' +
                  '<div>' +
                  "<div><span>Current</span> <br />" +
                  w.config.series[0].categories[dataPointIndex] +
                  "</div>" +
                  '<div class="group1">Nº: ' +
                  series[0][dataPointIndex] +
                  "</div>" +
                  "</div>" +
                  '<div class="group">' +
                  "<div><span>Previous</span> <br />" +
                  w.config.series[1].categories[dataPointIndex] +
                  "</div>" +
                  '<div class="group2">Nº: ' +
                  series[1][dataPointIndex] +
                  "</div>" +
                  "</div>" +
                  "</div>"
                );
            }
          },
 })
...
```
