### ISSUE TITLE
X-axis datetime is in UTC timezone

### ISSUE THREAD

**Issue by andavb** [apexcharts/apexcharts.js#4022]
### Description
Using multiline chart the x-axis time is off as it's presenting UTC time and not the local one, `datetimeUTC: false` does not work in that case. 

### Steps to Reproduce

 Create [multiline chart](https://apexcharts.com/react-chart-demos/line-charts/null-values/) with datetime on x-axis 
This is xaxis object, with `datetimeUTC: false`, that should ignore UTC time: `xaxis: {
                type: 'datetime',
                tooltip: {
                    enabled: false,
                    datetimeUTC: false,
                },
            },`

### Expected Behavior
Using `datetimeUTC: false`, should take take the local time.

### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/39746660/b3dbc11f-1fa2-4ab9-a72b-e6f4a033849c)

**Comment by brianlagunas** [comment]
Did not provide required reproduction link

**Comment by brachya** [comment]
you need to write it like axis:{type:'datetime',labels:{datetimeUTC:false}}
