### ISSUE TITLE
bar chart data labels issue 

### ISSUE THREAD

**Issue by Vedantcm** [apexcharts/apexcharts.js#4024]
### Steps to Reproduce

1. suppose i have more than 25 columns in bar chart 
2. click on Zoom in (+) icon 
3. then one of the data labels value gets overlaped  outside the y-aixs

### Expected Behavior
data labels values should not overlaped outside the y-axis

### Actual Behavior
Data labels value gets overlaped outside the y-axis

### Screenshots
![Screenshot 2023-09-20 183418](https://github.com/apexcharts/apexcharts.js/assets/143481302/10da7ba3-b25c-466d-8c53-0a3a0595d08e)

**Comment by brianlagunas** [comment]
did not provide required codepen link
