### ISSUE TITLE
Background remains dark when switching from dark mode to light

### ISSUE THREAD

**Issue by scottchantry** [apexcharts/apexcharts.js#4028]
### Description

When first viewing a chart with the theme set to 'dark' and then later update the chart options and set the theme to light, the background of the chart remains dark but everything else seems to update properly.

### Steps to Reproduce

1. Initialize and render a chart with theme set to 'dark'
2. Call 'updateOptions' on the chart and set the theme to 'light', the background remains dark but everything else updates properly
3. Does not occur when the theme is first initialized to 'light'

### Expected Behavior
Background color should be white to conform to the light theme

### Actual Behavior
Background color remains dark

### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/1310463/10cfc9dc-aeba-499b-8f15-c7b9022c607e)

### Reproduction Link

(https://codepen.io/Scott-Chantry/pen/yLGvXBN)

**Comment by junedchhipa** [comment]
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/9936ffc3b038d064b63bbc544c4869ad005a9c1f)

**Comment by scottchantry** [comment]
This issue can still be reproduced in 3.43.0 so the issue has not been fixed.
