### ISSUE TITLE
The numbers on top-left graph not begin displayed in bubble graph

### ISSUE THREAD

**Issue by jon9090** [apexcharts/apexcharts.js#4031]
I am utilizing the [apexcharts library](https://apexcharts.com/javascript-chart-demos/bubble-charts/simple/) to create a custom bubble graph.

However, I've encountered an issue where the numbers in the top-left corner are not being displayed, despite the presence of values in that area.

Could this be due to a configuration oversight on my part?

[stackblitz demo](https://stackblitz.com/edit/typescript-wv7kmz?file=index.ts)

![image](https://github.com/apexcharts/apexcharts.js/assets/74149517/bea19a2d-8f21-4e3b-b70e-30f1771141b6)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it. A new version is on the way
