### ISSUE TITLE
Fixing Incorrect GridLine Intervals in Chart X and Y Axes

### ISSUE THREAD

**Issue by SubinAdhikariEverWorks** [apexcharts/apexcharts.js#4037]
### Description

The chart X interval and Y Interval GridLine is not correct

### Steps to Reproduce

1. https://codepen.io/SubinAdhikariEverWorks/pen/PoXajEe This is the correct Chart
2. https://codepen.io/SubinAdhikariEverWorks/pen/eYbKReY This is the one with Bug
3. the TWO and ONLY TWO difference between 1 and 2 is
      a. Series Data X value Starts with 4000 instead of 1
      b. xaxis.min and xaxis.max is removed because having value as 
              ```
                "min": 4000,
                "max": 4349,
              ```
         would not generate any chart at all.
4. This is the TEXT COMPARE results https://www.textcompare.org/?id=651c17c71949f6c64664279d ( will work for 1 year )         
### Expected Behavior
The Grid Lines Should have been just like the Correct Graph
### Actual Behavior
The Grid Lines are not correct.
### Screenshots
1. Bug Screenshot 
![image](https://github.com/apexcharts/apexcharts.js/assets/142034059/634b7736-e62f-4cbc-81a9-4417a7040661)
Correct Screen Shot
![image](https://github.com/apexcharts/apexcharts.js/assets/142034059/b8d1f798-9562-447b-b179-866fc93826f7)

### Reproduction Link

1. https://codepen.io/SubinAdhikariEverWorks/pen/PoXajEe This is the correct Chart
2. https://codepen.io/SubinAdhikariEverWorks/pen/eYbKReY This is the one with Bug

**Comment by aaditya129** [comment]
I've made some improvements to the ApexCharts configuration to enhance the X-axis representation in the chart:

- Added `tickPlacement: "between"` to align ticks between data points, providing a more precise representation of data.
- Set `min` to `4000` and `max` to `4349` for the X-axis to specify a custom range that suits the data I'm visualizing.

  xaxis: {
    title: {
      text: "Coil",
      align: "center"
    },
    tickAmount: 13,
    tickPlacement: "between",
    min: 4000,
    max: 4349,
    type: 0,
    decimalsInFloat: 1,
    convertedCatToNumeric: true
  }
  https://codepen.io/aaditya129/pen/jOXvJwZ 


These updates have resolved the issues  and improved the chart's readability. Please feel free to review and provide feedback.

**Comment by SubinAdhikariEverWorks** [comment]
@aaditya129 Indeed, tickPlacement Solved the issue.

**Comment by SubinAdhikariEverWorks** [comment]
@aaditya129 Indeed, tickPlacement Solved the issue.
