### ISSUE TITLE
Charts div not showing on safari mobile

### ISSUE THREAD

**Issue by Anesta94** [apexcharts/apexcharts.js#404]
Hi everyone, charts works perfectly on chrome/firefox. On IOS devices, with safari showing only transparent div without svg data. How can i solve?

![image](https://user-images.githubusercontent.com/41288508/54393998-fc6f1100-46ab-11e9-8641-fdcf81d30753.png)

**Comment by junedchhipa** [comment]
Please post a working example on codepen, so I can reproduce the error.

**Comment by Anesta94** [comment]
Sorry for late response, i solved it changing date format to ISO 8601. Thanks for support.
