### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by becasualle** [apexcharts/apexcharts.js#4043]
### Description

Most of the pages are not available and returns an error: 502 Bad Gateway

### Steps to Reproduce

1. Open any of this pages [1](https://apexcharts.com/vue-chart-demos/line-charts/basic/), [2](https://apexcharts.com/docs/datetime/), [3](https://apexcharts.com/vue-chart-demos/area-charts/datetime-x-axis/), [4](https://apexcharts.com/docs/options/xaxis/)

### Expected Behavior
Displays documentation page content

### Actual Behavior
Displays "502 Bad Gateway"

### Screenshots
<img width="1311" alt="Screenshot 2023-10-06 at 11 57 50" src="https://github.com/apexcharts/apexcharts.js/assets/54999899/e691016b-88fa-4af2-8a9b-419ad7949e1b">

### Reproduction Link

https://apexcharts.com/vue-chart-demos/area-charts/datetime-x-axis/

**Comment by pascaldaugeron** [comment]
Solved ?

**Comment by becasualle** [comment]
Solved, thanks @pascaldaugeron

**Comment by Mr-Steep** [comment]
https://apexcharts.com/javascript-chart-demos  502 error
many pages with 502 error

**Comment by MrSunshyne** [comment]
Documentation is still down...

**Comment by dmanjunath03333** [comment]
Documentation is still down. (**502 Bad Gateway**). Any information when issue will be resolved.
https://apexcharts.com/javascript-chart-demos/

**Comment by kaualandi** [comment]
Hi, the docs are down currently. Been getting "502" bad gateway

**Comment by kaualandi** [comment]
Hi, the docs are down currently. Been getting "502" bad gateway

**Comment by mjpvandenberg** [comment]
It's happening again.
