### ISSUE TITLE
Broken visualization of smooth curve on line chart

### ISSUE THREAD

**Issue by yungfox** [apexcharts/apexcharts.js#4044]
### Description

The new release 3.43.0 makes line charts with smooth curve look off. I tried rolling back to 3.42.0 and the issue disappears, so my best bet is that there's something in the new release that break the appearance of the smooth curve behavior.

### Steps to Reproduce
1. Set ```chart.type``` to ```'line'``` and ```stroke.curve``` to ```'smooth'``` in chart options object.

### Expected Behavior

Correct visualization as of version 3.42.0
![working](https://github.com/apexcharts/apexcharts.js/assets/82904935/dcbcb825-04e2-4ad1-a616-5d0055f1fd55)

### Actual Behavior

Janky visualization as of version 3.43.0
![not_working](https://github.com/apexcharts/apexcharts.js/assets/82904935/29ec95cd-c557-419c-9746-ef5fb4a47871)

**Comment by brianlagunas** [comment]
No reproduction link provided.
