### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by TimUnderhay** [apexcharts/apexcharts.js#4045]
I apologise for opening this as a bug report, but I'm unsure where else to report it. The Apexcharts documentation site has been down for more than a day.

![image](https://github.com/apexcharts/apexcharts.js/assets/15734900/4ed41ee2-6d46-4534-96e9-c2fcfc8d0132)

**Comment by jonmes** [comment]
I've been trying to access the docs, but it returns 502 Bad Gateway, it's been 3 days for me.

**Comment by ahsanmughal757** [comment]
Is there a quick way to continue my development? Is there any alternative to get access to docs?

**Comment by denniszon** [comment]
@ahsanmughal757 What I use at the moment to continue my development is the internet archive. It's a little bit slow but it kinda works: https://web.archive.org/web/20230703134218/https://apexcharts.com/docs/installation/

**Comment by ahsanmughal757** [comment]
> @ahsanmughal757 What I use at the moment to continue my development is the internet archive. It's a little bit slow but it kinda works: https://web.archive.org/web/20230703134218/https://apexcharts.com/docs/installation/

Thanks that helps alot.

**Comment by sheldon124** [comment]
This has been occurring a lot lately. Hope this is fixed since it is hindering our development.

**Comment by brianlagunas** [comment]
Fixed. Please try again and let me know if you still have issues.

**Comment by TimUnderhay** [comment]
Working now.  Thank you @brianlagunas !
