### ISSUE TITLE
Apexchart  website

### ISSUE THREAD

**Issue by drhardian** [apexcharts/apexcharts.js#4048]
### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/4046

<div type='discussions-op-text'>

<sup>Originally posted by **drhardian** October  9, 2023</sup>
Does the ApexChart website is down? when click to the next page like demo, docs, etc always shown 502 bad gateway.</div>

**Comment by ebaccon** [comment]
I confirm !
https://apexcharts.com/docs/installation
I have 504 Gateway Time-out

**Comment by brianlagunas** [comment]
Duplicate
