### ISSUE TITLE
Stacked bar/column chart variable in size

### ISSUE THREAD

**Issue by drw1g16** [apexcharts/apexcharts.js#4050]
### Description

I am trying to create a stacked bar chart based on the following design in my screenshot.

I want each stack to be variable in size.

I would assume the following data structure would be:
```
[
        [
          { name: "Item 1", data: [10, 5, 8] },
          { name: "Item 2", data: [6, 3, 5] },
	  { name: "Item 3", data: [9, 10, 5] },
	  { name: "Item 4", data: [1, 3, 6] },
        ],
        [
          { name: "Item 6", data: [4, 2, 3] },
          { name: "Item 7", data: [7, 4, 6] },
        ],
];
```

However doing this returns 
`It is a possibility that you may have not included 'data' property in series.` (so data structure is not correct)

So my question is; is this currently possible? if not then is this a feature request?

### Steps to Reproduce

1. Create column chart 
2. Attempt to have different number of stacks using code example above

### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/32523914/8c4cb2e6-f61c-40f3-8eef-bbe054cb5103)

**Comment by brianlagunas** [comment]
No reproduction link provided.
