### ISSUE TITLE
[Vue 3] Removal of synced chart causes multiple fatal errors.

### ISSUE THREAD

**Issue by sneakylenny** [apexcharts/apexcharts.js#4055]
#### Application context:

To simplify my issue I'll explain it in a blog context. 
Say I have a post that has comments. On my admin index page of the posts I want to show a list of my post with each post having a graph showing how many comments there were the past week on each day. I want them all synced up so when I hover over one graph I get to see it on all posts for that day. Like so:

![image](https://github.com/apexcharts/apexcharts.js/assets/60601502/854851bf-405e-483e-8667-802954a6b71a)

Everything works fine this is totally possible. I can even add a post and everything still works:

![image](https://github.com/apexcharts/apexcharts.js/assets/60601502/31f21dd1-3ab0-4426-a4f2-616673bfef09)

But whenever I remove one, it will throw a fatal error and all the charts will be come unresponsive except for the first one:

![image](https://github.com/apexcharts/apexcharts.js/assets/60601502/848baa7c-b3ae-4fb4-b6b1-2477b9c3b20b)

Hovering over the charts will produce errors when moving the cursor:

<details>
  <summary>Screenshot of the console errors</summary>
  
  
  ![image](https://github.com/apexcharts/apexcharts.js/assets/60601502/0a64cf5b-63ea-409f-9a0f-2226e1e651ce)
</details>

#### Case 1: Loop

1. Loop over any iterable in the template (v-for)
1. In each loop create a chart that has a unique chart id and a shared group key. Series should be filled, could be anything as it's not relevant to the issue.
1. If more than 2 loops, decrease the iterations by 1 (by removing an object from an array of objects or simply by decreasing the number of loops from x to x-1 )
1. The charts will produce unexpected errors and syncing will not work properly anymore

#### Case 2: v-if

1. Create 3 charts
1. Each chart has to have a unique chart id and a shared group key. Series should be filled, could be anything as it's not relevant to the issue.
1. Add a reactive boolean.
1. Add a v-if to one of the charts. This can either be on the chart element itself or a parent element. Use the reactive boolean as condition.
1. Toggle the reactive boolean.
1. The charts will produce unexpected errors and syncing will not work properly anymore

### Expected Behavior

I expected the charts to still be synced and work properly.

### Actual Behavior

The first chart seems to work fine but will produce errors when hovering over the chart and moving the cursor.
The other charts also produce errors but are not responsive and show no tooltips and not sync anymore.

### Screenshots

I supplied screenshots in the explanation of the issue.

### Reproduction Links

Case 1: Loop

https://codesandbox.io/s/apex-charts-remove-synced-chart-bug-gn4pcd?file=/src/App.vue

Case 2: v-if

https://codesandbox.io/s/apex-charts-remove-synced-chart-bug-2-xmcqgj?file=/src/App.vue

In the sandbox it wil freeze and throw:
> can't access property "querySelector", t.w.globals.dom.baseEl is null

But in my project it throws:
> Uncaught TypeError: can't access property "ttItems", a3.w.globals.tooltip is null

### Workaround
Don't sync the charts if you know one of the synced charts is going to be removed. 

### Additional info

Possibly related
#3018

Edits:
1. Added another case
2. Added "workaround"

**Comment by turkhero** [comment]
I am encountering the same issue.

**Comment by Lobbyism** [comment]
Hello. There appears to be a workaround for this problem in VueApexCharts. In VueJS, the [`key`](https://vuejs.org/api/built-in-special-attributes#key) attribute is described as follows
> The `key` special attribute is primarily used as a hint for Vue's virtual DOM algorithm to identify vnodes when diffing the new list of nodes against the old list.

This [issue](https://github.com/apexcharts/react-apexcharts/issues/235#issuecomment-1031255717) concerns a different problem. The workaround suggested is to set the `key` to `Math.random()`. This solved these two errors
`Uncaught TypeError: Cannot read properties of null (reading 'ttItems')`
`TypeError: Cannot read properties of null (reading 'getPreviousPaths')`

Note that is workaround is achievable through VueJS `key` built-in attribute. If you use the library without a wrapper or with another one, you may need to do it slightly differently.
