### ISSUE TITLE
some labels are removed from the graph when screen size reduced

### ISSUE THREAD

**Issue by Rajat1Ggc** [apexcharts/apexcharts.js#4059]
when this bar graph scree size reduced then x axis labels are removed one by one
<img width="249" alt="Screenshot 2023-10-11 at 9 23 16 PM" src="https://github.com/apexcharts/apexcharts.js/assets/91239988/7c009389-9ada-4661-be98-3f3701c3e956">
<img width="450" alt="Screenshot 2023-10-11 at 4 47 31 PM" src="https://github.com/apexcharts/apexcharts.js/assets/91239988/3ce0aa0b-36c8-4ea6-8669-69b0b1547837">
on large screen it works properly 
<img width="687" alt="Screenshot 2023-10-11 at 4 50 18 PM" src="https://github.com/apexcharts/apexcharts.js/assets/91239988/dcba8ca3-1ee5-46fa-99bb-77f895ca01b6">

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
