### ISSUE TITLE
erroneous data plotted in real time charts?

### ISSUE THREAD

**Issue by rudyspies** [apexcharts/apexcharts.js#4061]
I'm using asynchronous webserver on my ESP32 which has a real-time critical application to measure energy at exact set intervals. At first, I suspected my real-time routine was interrupted by the async server and hence giving erroneous data. However when I look at the data sent by my ESP to the web client, it can be seen in the attached screenshot which shows the browsers' console output, that the data sent is correct, however the chart shows a spike at 9h57. When I refresh the chart, the spike dissapears, leading me to believe there is a bug in the real-time Apexchart?
I'm using the following statement to append data to the chart. Also, this happens at a rate of maybe 1/50 samples. Anyone else having experienced this kind of problem.
chartLine1.appendData([
{
data: [[CHART1_time, AP1acc ]] }, {
data: [[CHART1_time, AP2acc ]] }, {
data: [[CHART1_time, AP3acc ]] }, {
data: [[CHART1_time, PWR.VAMX]]
}
])
I'm trying to attach an image to this post but seem to be unable to do so. I tried JPG and PNG, the file is only 80KB

**Comment by brianlagunas** [comment]
Did not follow bug template instructions and you double posted this same issue as a discussion

**Comment by rudyspies** [comment]
1. I tried to delete or move the comment from 'discussion' to 'issue'. Couldn't do it
2. I've been cautious and curtious in my report. I do respect ALL developers who publish software for free. I do appreaciate the time and effort they put into it. 
3. Not following the suggested (required) format is in my opinion not enough reason to dismiss the issue. I really think the issue is valid. If I could attach a picture, it would speak 1000 words... Following the required format and providing code on codepen (I do not use codepen at all, I find it pretty useless) also puts a lot of strain on the reporter. A picture would really show the problem

**Comment by rudyspies** [comment]
Please also understand that Github is not the most user friendly platform to use to a new user
