### ISSUE TITLE
New smooth curve causes time to warp for sparse data

### ISSUE THREAD

**Issue by Tankenstein** [apexcharts/apexcharts.js#4063]
### Description

The latest release (3.43.0) changed the "smooth" curve. This is an improvement and looks great for evenly spaced data, but when data is sparse and moves around a lot, it can cause the chart to temporarily flow backwards in time, or completely reverse and do a loop.

### Steps to Reproduce

1. Make a line or area chart with sparse erratic data (for example, `[{ x: 0, y: 11 }, { x: 1, y: 10 }, { x: 2, y: 18 }, { x: 13, y: 5 }, { x: 20, y: 100 }]`)
2. Set `stroke.curve` to `'smooth'`
3. Enjoy the show

### Expected Behavior

Line and area chart lines move relatively smoothly from one point to the next, but never going backwards in time.

### Actual Behavior

Line and area chart lines can go backwards in time.

### Screenshots

<img width="1028" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/9271565/e0c04bcc-a979-478f-8129-627239013443">

![image](https://github.com/apexcharts/apexcharts.js/assets/9271565/fd6a79ff-114b-458d-841e-161a9301c10b)

### Reproduction Link

https://codepen.io/Tankenstein/pen/ZEVZXeq

Related issue, closed because it was missing a repro link: https://github.com/apexcharts/apexcharts.js/issues/4044

**Comment by cedricvoinnet** [comment]
Version 3.44 doesn't fix the problem.

See the codepen linked in the issue: https://codepen.io/Tankenstein/pen/ZEVZXeq
