### ISSUE TITLE
Rendering issue. When there are only 3 values on the chart, and one of them is 70%.

### ISSUE THREAD

**Issue by olegpix** [apexcharts/apexcharts.js#4080]
### Description

Hello,
First of all, thanks for the great plugin!

I have a problem with the intersection of strokes when the segment value is 70% (this can be seen in the screenshot).

My options:

```
const options = {
    chart: {
      height: '100%',
      type: 'pie',
      zoom: {
        enabled: false
      }
    },
    series: [70, 18, 12],
    labels: ['Direct', 'Organic search', 'Referral'],
    title: {
      show: false
    },
    stroke: {
      width: 3,
      colors: ['rgb(255, 255, 255)']
    },
    dataLabels: {
      style: {
        fontSize: '20px',
        fontFamily: 'Inter, ui-sans-serif',
        fontWeight: '400',
        colors: ['#fff', '#fff', '#1f2937']
      },
      dropShadow: {
        enabled: false
      },
      formatter: (value) => `${value.toFixed(1)} %`
    },
    plotOptions: {
      pie: {
        dataLabels: {
          offset: -15
        }
      }
    },
    legend: {
      show: false
    },
    grid: {
      padding: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0
      }
    },
    tooltip: {
      enabled: false
    },
    states: {
      hover: {
        filter: {
          type: 'none'
        }
      }
    },
    colors: ['#4f46e5', '#67e8f9', '#e5e7eb']
  }
```

Thank you in advance!

### Screenshots

<img width="895" alt="_02" src="https://github.com/apexcharts/apexcharts.js/assets/20664129/ac7a00f1-0299-4cc9-91d0-03492ba0c3f8">

**Comment by brianlagunas** [comment]
Did not provide the required repro link.

**Comment by olegpix** [comment]
Sorry, the reproduction link is [https://codepen.io/olegpix/pen/yLZeBPQ](https://codepen.io/olegpix/pen/yLZeBPQ)

**Comment by junedchhipa** [comment]
Thanks for providing a CodePen. I have fixed this with the last commit and the end result would like like below.
<img width="596" alt="Screenshot 2023-10-27 at 8 42 41 PM" src="https://github.com/apexcharts/apexcharts.js/assets/17950663/3949ae63-ed58-42e5-8281-c6c8cd4775bd">

Please wait for the next release.
