### ISSUE TITLE
Some X-Axis properties modify Y-Axis behaviour in horizontal barRange chart type

### ISSUE THREAD

**Issue by jaimestuardo** [apexcharts/apexcharts.js#4084]
Pleae see this fiddle:

https://jsfiddle.net/desytec/cq2xog7f/32/

Look at these options:

    `xaxis: {
        type: 'category',
        categories: [
            "lunes",
            "martes",
            "mi\u00E9rcoles",
            "jueves",
            "viernes",
            "s\u00E1bado",
            "domingo"
        ],
        labels: {
            maxHeight: 20,
            rotate: 90
        },
        position: 'top'
    },
    yaxis: {
        min: 0,
        max: 24
    },`

You can see that Y-Axis range is numeric 0 to 24 as the `yaxis` option says. However, the `position` property in the `xaxis` option affects the Y-Axis option as well.

I have not checked the other options.

**Comment by brianlagunas** [comment]
Please provide more information about the issue. Please specific all the properties that modify the behavior, and how exactly does the behavior get modified?

**Comment by jaimestuardo** [comment]
You can check de JSFIDDLER I provided.

Full options are 

  `let options = {
    chart: {
        type: 'rangeBar'
    },
    plotOptions: {
        bar: {
            horizontal: true,
            barHeight: '30%'
        }
    },
    grid: {
        show: true,
        xaxis: {
            lines: {
                show: true
            }
        },
        yaxis: {
            lines: {
                show: true
            }
        },
    },
    xaxis: {
        type: 'category',
        categories: [
            "lunes",
            "martes",
            "mi\u00E9rcoles",
            "jueves",
            "viernes",
            "s\u00E1bado",
            "domingo"
        ],
        labels: {
            maxHeight: 20,
            rotate: 90
        },
        position: 'top'
    },
    yaxis: {
        min: 0,
        max: 24
    },
    series: [
        {
            data: [
              {
                  "x": "lunes",
                  "y": [
                      15,
                      18
                  ]
              },
              {
                  "x": "martes",
                  "y": [
                      15,
                      18
                  ]
              },
              {
                  "x": "mi\u00E9rcoles",
                  "y": [
                      15,
                      18
                  ]
              },
              {
                  "x": "jueves",
                  "y": [
                      15,
                      18
                  ]
              },
              {
                  "x": "viernes",
                  "y": [
                      15,
                      18
                  ]
              }
          ]
        }
    ]
  };`

See the `position: 'top' value applied to X-Axis. It is actually being applied to Y-Axis.

Regards
Jaime

**Comment by junedchhipa** [comment]
You should be using `xaxis.min` & `xaxis.max` in horizontal charts because the axis gets reversed in horizontal charts.
The configuration is correct in this case, hence closing this issue.

**Comment by jaimestuardo** [comment]
But I need Y Axis to be from 0 to 24 (this works). If setting Y Axis range (which is placed horizontally), intuitively, if I set position of Y Axis, it should made it.
