### ISSUE TITLE
Incorrect x-axis labels for candles when transition to winter time

### ISSUE THREAD

**Issue by olton** [apexcharts/apexcharts.js#4095]
### Description

If dates include the transition to winter  (summer) time, labels for x-axis is wrong.

### Screenshots
<img width="1695" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/365108/20324f81-bcc3-4f34-804c-d297e6ca9f6c">

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
