### ISSUE TITLE
Legends are not rendering as html tags. All are showing as string.

### ISSUE THREAD

**Issue by iamibrahimriaz** [apexcharts/apexcharts.js#4099]
### Steps to Reproduce

1. 
<img width="394" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/99108560/57fa77ac-465c-4af4-9972-094724bd3ed5">

2. 
<img width="241" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/99108560/8e91817e-f0df-40c3-b38e-595faa16ef23">
 
3.

**Comment by brianlagunas** [comment]
Did not follow issue template instructions
