### ISSUE TITLE
Mobile height / legends getting cropped

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#41]
Since the legend is part of the SVG, and you can't provide height and width altogether, on vertical screen on mobile, there is a lot of problems of readability on mobile phone. I've got a six lines chart on my page, and the legend is not displayed due to to the SVG not planning vertical space for it.

I could disable legends, but it would be hard to read which color is which line. An implementation of this would be to set a size to the legend group then add that size to a translate variable to the chart or the legend group depending the position of the legend.

To test on it, just use a small width for apexcharts, like 350px (95% width of my phone display).

Here the examples : 

![apexcharts-mobile-legend](https://user-images.githubusercontent.com/17592744/44266373-9e1fa400-a22a-11e8-9b43-734518cdca6a.png)

![apexcharts-mobile-no-legend](https://user-images.githubusercontent.com/17592744/44266378-a4158500-a22a-11e8-9ac9-a4dd47e36920.png)

**Comment by junedchhipa** [comment]
If you don't provide any height, then the default height = width / 1.6

But, you can give height along with width also. If you don't want to give fixed height for large screens, you can configure the responsive options to give height just for mobile screens.

Here is the picture with height set to "auto"
![screen shot 2018-08-17 at 6 45 22 pm](https://user-images.githubusercontent.com/17950663/44268017-e7351f80-a24d-11e8-9792-eb2aea40d87e.png)

and here is the picture with height set to 300 for mobile devices
![screen shot 2018-08-17 at 6 45 42 pm](https://user-images.githubusercontent.com/17950663/44268028-f2884b00-a24d-11e8-8d5c-01cc2647ffe7.png)

using this config
```javascript
{
  chart: {
    type: 'line',
    zoom: {
      enabled: false
    },
  },
  responsive: [{
    breakpoint: 480,
    options: {
      chart: {
        height: 300
      }
    }
  }],
}
```

**Comment by arkhenstone** [comment]
Even with that config, the legend overflow. Set more height, and the legend still overflow.

With height="300" : 

![screenshot_20180817-164242](https://user-images.githubusercontent.com/17592744/44272339-d16b2e80-a23c-11e8-979d-df9cbda6a2dc.png)

With height="400" : 

![400](https://user-images.githubusercontent.com/17592744/44272730-eb594100-a23d-11e8-8929-a772c2dba1e1.png)

**Comment by junedchhipa** [comment]
I will look into the legends getting cropped.
For a temporary solution, you can offset the whole legend area by
```javascript
{
  legend: {
    offsetY: -5
  }
}
```javascript
