### ISSUE TITLE
Duplicate y axis values

### ISSUE THREAD

**Issue by victorgdb** [apexcharts/apexcharts.js#410]
## Codepen

https://codepen.io/anon/pen/NJBLgv

## Explanation

- What is the behavior you expect?
Y axis should not have duplicated values
- What is happening instead?
1 and 4 are duplicated
- What error message are you getting?
No error message

Have I misunderstood something?
Thanks for your help!

Update: It seems to be related to the default tickAmount of 6. It would be great if the chart could know itself how to reduce this tickAmount number if there isn't enough data to display 6 points.

**Comment by junedchhipa** [comment]
Yeah, you're correct. The y-axis should automatically reduce the tickAmount if the range is too small to print non-duplicating round numbers.

**Comment by sheikh303** [comment]
this could be a work around here:
`yaxis: {
        min: 0,
        max: _maxYAxisValue_,
        tickAmount: _maxYAxisValue_,
}`

**Comment by nayanadas** [comment]
@sheikh303  @junedchhipa  how to avoid duplicate y-axis label values in real-time chart without setting min or max or tickAmount, will the labels automatically set based on the y-axis value?

![image (4)](https://user-images.githubusercontent.com/20011783/110115940-cd905f00-7ddc-11eb-8a5e-8d1321f6e46a.png)

**Comment by sheikh303** [comment]
> @sheikh303  @junedchhipa  how to avoid duplicate y-axis label values in real-time chart without setting min or max or tickAmount, will the labels automatically set based on the y-axis value?
> 
> ![image (4)](https://user-images.githubusercontent.com/20011783/110116117-0c261980-7ddd-11eb-8365-e1373d1b94d2.png)
> 

Y-axis doesn’t provide _showDuplicate: false_ configuration. Only X-axis has it. 
Using "Min, max, tickAmount" is only work around i guess.

**Comment by nayanadas** [comment]
@sheikh303 ok thanks for confirming

**Comment by Teyken** [comment]
Any news on this?
We have some pretty complex charts, so the workaround is very difficult to implement.

**Comment by ephraimlambarte** [comment]
this still happens in my line chart. my apexcharts version: 3.35.5

**Comment by kwalk2108** [comment]
> this could be a work around here: `yaxis: { min: 0, max: _maxYAxisValue_ + _offset_, tickAmount: _maxYAxisValue_+ _offset_, }`

Could you please expand on how the maxYAxisValue and offset are set? Are these values statically assigned because I don't think in any of those chart options, we have access to the y values to dynamically determine what those values should be.

**Comment by rocso** [comment]
I have this problem using the Apexcharts card in Home Assistant. Increasing the yaxis decimals value was one solution as, by observation only, it appears as if the grid/ticks are drawn to values proportionate to their spacing between the max/min values but the labelling of those values is simply rounded to the nearest decimals specification for labelling. I tried varying tickAmount also and observed that, although the grid/ticks were evenly spaced, the labelling was not duplicated but also not proportionate. E.g. in the image, the grid is evenly spaced and clearly the label increments: 0.03, 0.04, 0.03, are not proportional.

![Apexgraph-bug](https://github.com/apexcharts/apexcharts.js/assets/7076993/b3ea87ca-7745-472d-991a-58c85eef4f3f)

**Comment by henrytran9x** [comment]
Hi ! I using version latest Apexchart 3.46.. This issues still
this my codepen: https://codepen.io/henrytran/pen/rNREogO
