### ISSUE TITLE
Hide series before first draw

### ISSUE THREAD

**Issue by PhilJbt** [apexcharts/apexcharts.js#4102]
## Summary

Be able to set series hidden by default at startup would be appreciated.

## API Changes

**[ADD]** `hiddenAtStart` param to the [SERIE](https://apexcharts.com/docs/series/) section for charts configuration.
```
series:[{
  hiddenAtStart: true,
  data: [23, 51, ... , 43]
}]
```

## Intended Use Case

As @junedchhipa suggested in [this thread](https://github.com/apexcharts/apexcharts.js/issues/1217), I tried to programmatically hide series generally unused by the users. But this means that charts have to be fully drawn at startup, and redrawn each time a serie is hidden.

This is a [huge problem](https://github.com/apexcharts/apexcharts.js/assets/22506952/19b7fb53-8b4f-422e-8f95-f2b3890a0ab3) of performance for charts with a large amount of data and/or series. Obviously, [deferring the action to the user](https://github.com/apexcharts/apexcharts.js/assets/22506952/d419a0d7-f035-495d-a898-23c7b5c803d5) is not an option.

> Data used: 4 series of 24*7 values each + 12 series of 24*4 values each

**Comment by tqwewe** [comment]
I believe this is still an issue. In my particular case, the animations get glitched by immediately hiding some series right after rendering.

**Comment by litera** [comment]
`hidden` will be a series prop in 3.53.0
```
series = [{
    hidden: true,
    data: [...]
}]
```

**Comment by junedchhipa** [comment]
https://apexcharts.com/docs/hide-series-on-initial-render-in-a-multi-series-chart/

**Comment by litera** [comment]
@junedchhipa Thanks for releasing it so quickly after some quick questions.
