### ISSUE TITLE
reopening #4063 New smooth curve causes time to warp for sparse data

### ISSUE THREAD

**Issue by DamienGdn** [apexcharts/apexcharts.js#4108]
I am reopening post #4063 regarding the bug 'New smooth curve causes time to warp for sparse data,' which is still not fixed in ApexChart v3.44.0.

### Description
The latest release (3.43.0) changed the "smooth" curve. This is an improvement and looks great for evenly spaced data, but when data is sparse and moves around a lot, it can cause the chart to temporarily flow backwards in time, or completely reverse and do a loop.

### Steps to Reproduce
Make a line or area chart with sparse erratic data (for example, [{ x: 0, y: 11 }, { x: 1, y: 10 }, { x: 2, y: 18 }, { x: 13, y: 5 }, { x: 20, y: 100 }])
Set stroke.curve to 'smooth'
Enjoy the show
Expected Behavior
Line and area chart lines move relatively smoothly from one point to the next, but never going backwards in time.

### Actual Behavior
Line and area chart lines can go backwards in time.

### Screenshots
![](https://user-images.githubusercontent.com/9271565/274846516-e0c04bcc-a979-478f-8129-627239013443.png)
![](https://user-images.githubusercontent.com/9271565/274848692-fd6a79ff-114b-458d-841e-161a9301c10b.png)

Reproduction Link
https://codepen.io/Tankenstein/pen/ZEVZXeq

I have the same issue on my side, as you can see.
![MicrosoftTeams-image](https://github.com/apexcharts/apexcharts.js/assets/9105411/711af562-991a-4c53-a5fd-b1ff332ac047)

**Comment by azivkovi** [comment]
This is still an issue: https://codepen.io/azivkovi/pen/ZEwqOxG

**Comment by meixger** [comment]
Similar problem with null values and smooth: https://codepen.io/meixger/pen/XWGmaEJ

**Comment by mtuzenko** [comment]
Same issue here
![image](https://github.com/apexcharts/apexcharts.js/assets/138770862/38766176-192b-4620-ad8f-1c69cb04fc9d)
![image](https://github.com/apexcharts/apexcharts.js/assets/138770862/138f2d40-fbd2-483b-9475-cd712a622ad2)

**Comment by junedchhipa** [comment]
The previous `smooth` logic is re-added since v3.45.2

So, from now on, you have 4 curve options for stroke

```js
stroke: {
  curve: "smooth" // straight, smooth, monotoneCubic, stepline
}
```

Use either smooth or monotoneCubic to see whatever works for you.
