### ISSUE TITLE
How to remove hamburger menu?

### ISSUE THREAD

**Issue by Cookiewookie87** [apexcharts/apexcharts.js#411]
I am looking at docs for a long time but I cannot find any option to remove this hamburger menu. Am i just missing something or is this not an option?

**Comment by mamasselin** [comment]
Hi, you can hide the hamburger menu by setting the `chart.toolbar.show` option to `false`.

Ref: https://apexcharts.com/docs/options/chart/toolbar/

**Comment by aurelien-boubennec** [comment]
> Hi, you can hide the hamburger menu by setting the `chart.toolbar.show` option to `false`.
> 
> Ref: https://apexcharts.com/docs/options/chart/toolbar/

The hamburger menu is the icon on the very right in the toolbar. What you suggest will remove the whole toolbar.

**Comment by manisha-seclogic** [comment]
<img width="254" alt="apex" src="https://user-images.githubusercontent.com/64947641/91027886-4cc8fd00-e61a-11ea-8c4c-a7041a6462de.PNG">
only this menu icon is there in toolbar i want all the option in toolbar
Please help how can i do this
code:
 chart: {
        height: 350,
        type: "bar",
        toolbar: {
          show: true,
          tools: {
            download: true,
            selection: true,
            zoom: true,
            zoomin: true,
            zoomout: true,
            pan: true,
            reset: true
          },
        },
        zoom: {
          enabled: true
        }
      },

**Comment by manisha-seclogic** [comment]
> > Hi, you can hide the hamburger menu by setting the `chart.toolbar.show` option to `false`.
> > Ref: https://apexcharts.com/docs/options/chart/toolbar/
> 
> The hamburger menu is the icon on the very right in the toolbar. What you suggest will remove the whole toolbar.



Yes you can do this in this way
chart: {
        toolbar: {
          show: true,
          tools: {
            download: false,
}
}

**Comment by jacksonsophat** [comment]
Mine is still showing up
