### ISSUE TITLE
Line charts regression with `null` values being shown instead of hidden

### ISSUE THREAD

**Issue by Knogobert** [apexcharts/apexcharts.js#4112]
### Description

Line charts that have `null` in the middle of their data set used to leave an empty room in the middle of the graph in Apexcharts v3.39.0. After that, monotoneCubic came with great stuff, but regressed on this issue.

### Steps to Reproduce

1. Set the dataset to include `null` values, smooth curve & line chart (or just check codepen!)
2. See that the lines fill in to the next point, even if it should be left out completely.
3. Change the imported package from `https://cdn.jsdelivr.net/npm/apexcharts@3.44.0` to `https://cdn.jsdelivr.net/npm/apexcharts@3.39.0`
4. See it work like expected

### Expected Behavior
Skip null values from being filled out as lines.
(but with monotoneCubic lines <3)
![image](https://github.com/apexcharts/apexcharts.js/assets/770560/52e34a67-c2af-4e6e-8171-f92b187b495b)

### Actual Behavior
Filling out lines
![image](https://github.com/apexcharts/apexcharts.js/assets/770560/09ccc57e-fe8b-4b97-b91a-e7f87f68ca8b)

### Screenshots
☝️ 

### Reproduction Link
https://codepen.io/Knogobert/pen/mdvXogO?editors=0010

https://cdn.jsdelivr.net/npm/apexcharts@3.39.0
https://cdn.jsdelivr.net/npm/apexcharts@3.44.0

You're the boss @junedchhipa !

**Comment by mtuzenko** [comment]
Same thing is happening to me, I believe its an issue with current version . "Missing / null values" demo chart is using version 3.15.0, when I plug in my current version 3.44.2, it breaks just like in the picture.

**Comment by junedchhipa** [comment]
The previous `smooth` logic is re-added since v3.45.2

So, from now on, you have 4 curve options for stroke

```js
stroke: {
  curve: "smooth" // straight, smooth, monotoneCubic, stepline
}
```

Use the option "smooth" to allow gaps in the line when null data is present
