### ISSUE TITLE
Apply a border radius to the first and last elements of the stacked columns/bars.

### ISSUE THREAD

**Issue by Aksultan** [apexcharts/apexcharts.js#4113]
## Summary
There should be a way to round the first and last elements of stacked columns/bars. Currently, I can only apply border radius to either the last element or all elements in the stack. I aim to round only the first and last elements.

## API Changes
As per the documentation, the available options for the borderRadiusWhenStacked property are currently last and all. I propose adding an additional option called both or another suitable name. This new option would enable us to apply border radius to the first and last elements of the bar/column chart.
```
borderRadiusWhenStacked: "both",
```
With this change, we gain access to both ends of the chart. However, the radius application needs modification to set border-top radius for the last element and border-bottom radius for the first element. To achieve this, borderRadiusApplication needs to accept a single string with two values or an array with two string values.
Example:
```
chart: {
  type: "bar",
  stacked: true,
  plotOptions: {
      bar: {
        borderRadius: 15,
        borderRadiusApplication: "end start", // or  ["end, "start"]
        borderRadiusWhenStacked: "both",
      },
    }
  }
  }
```

## Intended Use Case
This enhancement can be utilized to create a "pill"-shaped stacked bar/column chart.

![image](https://github.com/apexcharts/apexcharts.js/assets/22559218/88471100-729b-45e7-9a7b-19e3edc3eaa2)

**Comment by AvaGivone** [comment]
@Aksultan are you working on this feature? If not, @junedchhipa is this unassigned? My group and I are interested in working on this feature.

**Comment by AvaGivone** [comment]
Great, thanks! We'll get started

**Comment by skorphil** [comment]
I vote for this feature also. Would be great to have it.

Meanwhile, is there any workaround to achieve this now?

**Comment by skorphil** [comment]
> > I vote for this feature also. Would be great to have it.
> > Meanwhile, is there any workaround to achieve this now?
> 
> @skorphil I have had a lot of progress on implementing this feature and have the "both" property implemented! The only thing I'm still working on is a way to rotate the first element in the stack upside down so that the radius is applied to the correct side.
> 
> In the interim, a workaround that I have found in my development is modeling the graph off of the negative-bar sample, but this would require that one of the data series is negative. Not sure if this is alright for your usage, otherwise I am hoping to have the both feature implemented in the next few days!

@AvaGivone 
Sound great!
I have also noticed strange animation behavior which can be related to this feature: https://github.com/apexcharts/apexcharts.js/issues/4142

**Comment by tanakatoo** [comment]
Hi, I noticed that applying `borderRadiusApplication:'around'` with `borderRadiusWhenStacked: 'last'` applies radius to all elements of the series instead of just the first and last elements. I think this is the same bug as this issue - is anyone working on it?

**Comment by junedchhipa** [comment]
Have you tried upgrading to v3.54.1? We fixed this issue in that version, so please try upgrading and see if it works.

**Comment by borjaa112** [comment]
> Have you tried upgrading to v3.54.1? We fixed this issue in that version, so please try upgrading and see if it works.

not working for me in 3.54.1
