### ISSUE TITLE
"'module' is not defined" when using rollup

### ISSUE THREAD

**Issue by mikaelkaron** [apexcharts/apexcharts.js#412]
I think I may be having a similar problem to #357 when trying to bundle this up with stencil (that uses rollup in the back).

I'm getting this error in Edge:

```
'module' is not defined
```

And after some light debugging it looks to be [coming from over here](https://github.com/apexcharts/apexcharts.js/blob/master/src/svgjs/svg.js#L18). I don't think it's something easy to patch (as it's 3rd party) but maybe an upgrade would help?

**Comment by junedchhipa** [comment]
I am slowly upgrading svg.js to 3.0 as it has many breaking changes.
`apexcharts@4.0.0` would include the latest SVG.js version which hopefully will fix all these bundling issues.

**Comment by junedchhipa** [comment]
Try the recent patch in the commit mentioned above and let me know if it works.

**Comment by mikaelkaron** [comment]
That does indeed fix the bug, could you cut a new release so I can bump `stencil-apexcharts`?

**Comment by junedchhipa** [comment]
Sure, I will. This weekend.
