### ISSUE TITLE
Series line does a loop if stroke curve is set to smooth and x-axis type is datetime

### ISSUE THREAD

**Issue by azivkovi** [apexcharts/apexcharts.js#4126]
### Description

When stroke curve is set to smooth and x-axis type is datetime, the line appears as if it is going back in time on some parts.

### Steps to Reproduce

I noticed this behaviour doesn't happen on every data set.

1. Set x-axis.type = datetime
2.  Set stroke.curve = smooth

If I delete `x-axis.type = datetime` option, the line is ok. Also, if `stroke.curve` is set to `straight`, the line is ok. Only when these two work in tanded it appears there is a problem.

### Expected Behavior
Line goes from left to right

### Actual Behavior
Line sometimes loops back left

### Screenshots
![xxx](https://github.com/apexcharts/apexcharts.js/assets/47382298/f983692d-bbb6-401b-8607-179a189509f0)

### Reproduction Link
https://codepen.io/azivkovi/pen/ZEwqOxG

**Comment by azivkovi** [comment]
Duplicate of #4108 , but with added info about `datetime` in x-axis.

**Comment by junedchhipa** [comment]
addressed in [commit](https://github.com/apexcharts/apexcharts.js/commit/360324f5ec55541f26fa2f03c84026f91aadbf88)

**Comment by jguillaume-wheere** [comment]
I have the same issu here. I used the angular version, I tried the 1.7.4-1.7.7 (can't test 1.6 as I have angular 16) and it's not woking much better. Any idea ?

**Comment by junedchhipa** [comment]
The previous `smooth` logic is re-added since v3.45.2

So, from now on, you have 4 curve options for stroke

```js
stroke: {
  curve: "smooth" // straight, smooth, monotoneCubic, stepline
}
```
