### ISSUE TITLE
Impossible to have transparent strokes on donut chart

### ISSUE THREAD

**Issue by SimonChatillon** [apexcharts/apexcharts.js#4129]
## Summary

I need to have transparent spaces between each slice, my background is a transparent glass effect panel with a gradient so I can't trick this by using a specific stroke color. 

![image](https://github.com/apexcharts/apexcharts.js/assets/11609715/5f77c971-d115-42d7-952d-76996cb9fb53)

I also tried using transparent strokes but it's not working because the fill colors always connect below the stroke. Maybe the fill color should not overlap the stroke color ?

**Comment by SankiVrajaDev** [comment]
I also have this problem, I would like to hear at least a workaround.

**Comment by virtuscoder** [comment]
I also have this problem, I would like to hear at least a workaround.
