### ISSUE TITLE
Trendlines for scatter chart

### ISSUE THREAD

**Issue by styd** [apexcharts/apexcharts.js#413]
Some charting libraries support trendlines for their scatter chart/plot. I couldn't find the word 'trendline' in this project.
Do you have a plan to make trendlines for scatter chart or is there already an easy way to do it?

**Comment by wdavies973** [comment]
Any progress on this @junedchhipa ?
Is there a way I could easily add the feature myself if you are pressed for time?

**Comment by wdavies973** [comment]
I figured out a temporary work around for this. 

Use a line chart, and provide two data sets for the series option.
One data set will be your actual scatterplot data, the other data set will be your trendline.
You will need to calculate out trendline points by doing the linear regression yourself, but you can use the stroke setting with `width: [0, 2]` to disable lines connecting your data set, but enable lines for your trendline. It comes out looking quite nice, and the tooltips will display both a value and its associated trendline value when mousing over.

@styd Let me know if you need more advice on how to do this.

**Comment by styd** [comment]
Hi, @wdavies973. If you know how to add trendlines dynamically by just providing the scatter chart dataset, why not make a PR?

**Comment by cverster** [comment]
Agree, please add the ability to add a tendline to scatter plots.

**Comment by adancalderon** [comment]
Hi @wdavies973 Interesting take on making your own trendline.

You got me a bit confuse on the line chart and the actual scatter plot. I sent you an email regarding it at: wdavies973@gmail.com

Hope I can read you soon.

Thanks!

**Comment by thellimist** [comment]
https://help.syncfusion.com/js/chart/trendlines

something like this would be great. Not just for scatter chart, but line chart too

**Comment by Genarito** [comment]
There's an example in https://apexcharts.com/vue-chart-demos/mixed-charts/line-scatter/

But I having troubles with multiple scatter data series. I opened a new [issue](https://github.com/apexcharts/apexcharts.js/issues/2178) about this
