### ISSUE TITLE
Stacked Area Charts Don't Stack

### ISSUE THREAD

**Issue by krcoats** [apexcharts/apexcharts.js#4132]
### Description
Prior to 3.44.1, stacked area charts would stack, even with a combo chart. I have a combo chart that has used stacked bars, stacked areas and a single line for over a year. But as of 3.44.1, the bars stack, but the areas do not stack. Even after removing all other series except for the areas and they still won't stack. Even Apexchart's website's demo for stacked areas doesn't stack now.

### Steps to Reproduce

1. Create a simple stacked area chart
2. Observe that chart does not stack (areas overlap instead of stacking)
3. Or review the apexcharts stacked area page (https://apexcharts.com/javascript-chart-demos/area-charts/stacked/) and observe that the areas are not stacked

### Expected Behavior
In the codepen/reproduction link, I would expect the values to stack and plot on the Y value at the sum of all values. For example, the last values in 1999 are 125 and 100, which, stacked, should plot at 225.

In the screenshot of the apex charts website, the values are 20, 11, 10, which stacked would plot at 41.

### Actual Behavior
"Stacked" areas (in codepen and apex charts website screenshot) are overlapping, not stacking.

### Screenshots
This is from the apex charts website to show even the demo is not functioning properly
![apex_charts_website_stacked_area_demo](https://github.com/apexcharts/apexcharts.js/assets/152906190/a15de424-d33b-42b2-84d7-ac9636e137ee)

### Reproduction Link
https://codepen.io/krcoats/pen/OJdrLKW

Thank you for the help.

**Comment by junedchhipa** [comment]
The issue is being addressed. Meanwhile, you can fix this by setting 
```js
options = {
  chart: {
    stacked: true,
    stackOnlyBar: false
  }
}
```

**Comment by rosco54** [comment]
If the type is removed from both series they will stack, even though stackOnlyBar is true (by default). This shouldn't happen.

**Comment by Tyrannas** [comment]
![image](https://github.com/apexcharts/apexcharts.js/assets/10096711/2dd0c854-3546-4d01-ab2e-7c9632c5baa7)
I'm facing the same problem, using vue3-chartjs. 
Tried the stackOnlyBar but it's not working either
