### ISSUE TITLE
当页面2个以上图表 xaxis type datetime 使用 appendData 方法追加数据时 图表显示数据一致 

### ISSUE THREAD

**Issue by 174001602** [apexcharts/apexcharts.js#4137]
### Steps to Reproduce

html:
<div class="col-4" id="kt_apexcharts_getloadavg_{{$list['uuid']}}" style="display:none;"></div>

chart:
var options_getloadavg = {
  chart: {
    height: 350,
    type: 'line',
    stacked: true,
    animations: {
      enabled: true,
      easing: 'linear',
      dynamicAnimation: {
        speed: 1000
      }
    },
    dropShadow: {
      enabled: true,
      opacity: 0.3,
      blur: 5,
      left: -7,
      top: 22
    },
    events: {
      animationEnd: function (chartCtx, opts) {
        const newData1 = chartCtx.w.config.series[0].data.slice()
        newData1.shift()
        const newData2 = chartCtx.w.config.series[1].data.slice()
        newData2.shift()

        // check animation end event for just 1 series to avoid multiple updates
        if (opts.el.node.getAttribute('index') === '0') {
          window.setTimeout(function () {
            chartCtx.updateOptions({
              series: [{
                data: newData1
              }, {
                data: newData2
              }],
              subtitle: {
                text: parseInt(getRandom() * Math.random()).toString(),
              }
            }, false, false)
          }, 300)
        }

      }
    },
    toolbar: {
      show: false
    },
    zoom: {
      enabled: false
    }
  },
  dataLabels: {
    enabled: false
  },
  stroke: {
    curve: 'straight',
    width: 5,
  },
  grid: {
    padding: {
      left: 0,
      right: 0
    }
  },
  markers: {
    size: 0,
    hover: {
      size: 0
    }
  },
  series: [{
    name: '1min',
    data:[]
  }, {
    name: '5min',
    data:[]
  }, {
    name: '15min',
    data:[]
  }],
  xaxis: {
    type: 'datetime',
  },
  title: {
    text: 'CPU Loadavg',
    align: 'left',
    style: {
      fontSize: '12px'
    }
  },
  legend: {
    show: true,
    floating: true,
    horizontalAlign: 'left',
    onItemClick: {
      toggleDataSeries: false
    },
    position: 'top',
    offsetY: -28,
    offsetX: 60
  },
}

var chart_getloadavg_{{$list['uuid']}} = new ApexCharts(document.getElementById("kt_apexcharts_getloadavg_{{$list['uuid']}}"), options_getloadavg);
chart_getloadavg_{{$list['uuid']}}.render();

function client_getloadavg(uuid,getloadavg,t){
    console.log(getloadavg);
    console.log(t);
    var getloadavg_Charts = 'chart_getloadavg_'+uuid;
    console.log(getloadavg[0])
    console.log(getloadavg[1])
    console.log(getloadavg[2])
    
    $("#kt_apexcharts_getloadavg_"+uuid).show();

    
    window[getloadavg_Charts].appendData([{
            data: [{
                x: t,
                y: getloadavg[0].toFixed(2)
              }]
          }, {
            data: [{
                x: t,
                y: getloadavg[1].toFixed(2)
              }]
          }, {
            data: [{
                x: t,
                y: getloadavg[2].toFixed(2)
              }]
          }
      ])
} 

### Expected Behavior

页面图表根据 div id 不同，根据id 追加不同的数据 图表曲线应该不同

### Actual Behavior

显示呈现的图表一样

### Screenshots

![QQ图片20231205201543](https://github.com/apexcharts/apexcharts.js/assets/58964152/8fb270fd-2564-4ca2-b876-d3019fdcba11)

### Reproduction Link

![url](https://github.com/apexcharts/apexcharts.js/assets/58964152/50731bff-99e7-4109-b36c-9b3b15576a86)

**Comment by junedchhipa** [comment]
no reproducible demo provided.

**Comment by 174001602** [comment]
url 
![url](https://github.com/apexcharts/apexcharts.js/assets/58964152/e47a68c6-6b4b-436e-8e0e-b8a00e0e80fc)
