### ISSUE TITLE
当页面2个以上图表 xaxis type datetime 使用 appendData 方法追加数据时 图表显示数据一致

### ISSUE THREAD

**Issue by 174001602** [apexcharts/apexcharts.js#4139]
### Steps to Reproduce

1. 页面插入多个图表 xaxis type datetime
2. 使用 appendData 方法追加数据

### Expected Behavior
页面图表根据 div id 不同，根据id 追加不同的数据 图表曲线应该不同
### Actual Behavior
显示呈现的图表一样
### Screenshots
![QQ图片20231205201543](https://github.com/apexcharts/apexcharts.js/assets/58964152/8fb270fd-2564-4ca2-b876-d3019fdcba11)

### Reproduction Link
https://codepen.io/174001602/pen/QWYzZqK

**Comment by junedchhipa** [comment]
Not a valid reproducible example.
Please provide a single chart with the issue explained properly (in English language)
