### ISSUE TITLE
Empty tooltip is shown for null values

### ISSUE THREAD

**Issue by Soutea** [apexcharts/apexcharts.js#4147]
### Description

     
When there are null values in a timeline chart, the tooltip is shown even if there is no data (y-value) for that that time stamp.

Is it not possible to have a shared tooltip for multiple values for each stamp without showing an empty tooltip for null values?

### Steps to Reproduce

1.  Have a multiple series timeline graph with null values [Vue3]
2. Have following tooltip configuration

```
            tooltip: {
              intersect: false,
              shared: true
            },
```

3.  Notice the behavior in the screenshot when selecting only one serie.

### Expected Behavior

When hovering on a chart, tooltip for values that are null should not be shown.

### Actual Behavior

Empty tooltip is shown for null values leading to confusing behavior.

### Screenshots

<img width="800" alt="image" src="https://github.com/Appva/web-common/assets/34288651/6b15802c-587a-45a6-a4d8-88701c1e8a63">

<img width="1170" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/34288651/279deb80-af14-4806-ba36-e0d138ded890">

### Reproduction Link

https://codepen.io/soutea/pen/KKJYXYV

**Comment by brianlagunas** [comment]
Please provide a proper reproduction link, or this issue will be closed.

**Comment by junedchhipa** [comment]
As tested on v4.3.0, this is no more reproducible.
