### ISSUE TITLE
Tooltip not show zero values on Line Chart

### ISSUE THREAD

**Issue by felipeemerson** [apexcharts/apexcharts.js#4149]
### Steps to Reproduce

1. Create a line chart with some zero values on series
2. Hover the mouse over the point with zero value

### Expected Behavior
I'm expecting to show the series name and 0.

### Actual Behavior
Blank text.

### Screenshots
![Captura de tela 2023-12-13 155250](https://github.com/apexcharts/apexcharts.js/assets/11932240/5ffa2236-3758-485e-b8b1-d8e2bf2b85f8)

### Reproduction Link
https://codepen.io/felipeemerson/pen/KKJLomz

**Comment by Nephim** [comment]
There is a property called hideEmptySeries which does this. Add it like this.
``` js
tooltip: {
   hideEmptySeries: false,
}
```

This seems to be missing from the docs:

https://apexcharts.com/docs/options/tooltip/

someone should probably fix that

**Comment by van123helsing** [comment]
Why is this not the default?

**Comment by Nephim** [comment]
> Why is this not the default?

Its not the default in the underlying JS implementation. This has been fixed as per #364.
