### ISSUE TITLE
Horizontal box plot with outliers?

### ISSUE THREAD

**Issue by ChloeH88** [apexcharts/apexcharts.js#4150]
## Summary

I saw there's a feature that supports outliers for [vertical box plots](https://apexcharts.com/javascript-chart-demos/box-whisker-charts/boxplot-scatter/), but I can't seem to apply it for horizontal box plots. The scatter plot is using x as category and y as value without flipping them:
<img width="878" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/90373791/2bdb0ef5-3310-42bb-b8be-5d907720d3a8">
My js code:
``` javascript
series: [
{
        type: 'boxPlot',
        data: ...
},
{
        type: 'scatter',
        data: {
          x: category,
          y: value
        },
}]
```

Is there something I can do on my end? Or we need some feature updates in the API?

**Comment by kevinbyrne303** [comment]
Please add this feature. This would be tremendously helpful for our organization.

**Comment by jtritell** [comment]
This would be useful for us too.

**Comment by Zordiac** [comment]
This issue is marked as closed, but it is not yet completed and working. See attached fiddle:
https://jsfiddle.net/uwmtzfk1/1/
Please reopen if possible

**Comment by brianlagunas** [comment]
@Zordiac you've already submitted #4780 so there is no need to reopen this.

**Comment by Zordiac** [comment]
@brianlagunas sorry man, I thought you guys wanted to have a new issue for that

**Comment by brianlagunas** [comment]
@Zordiac no problem, probably better you opened it as a bug because it will help us to look at it to determine if it is indeed a feature request or a bug.

**Comment by junedchhipa** [comment]
@Zordiac A scatter chart won't render correctly in horizontal axis. So, I have another way to solve the issue.
We will use ApexCharts' goals property to achieve this (similar to https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-markers/)

I am currently working on it and will ship it in the next release.

**Comment by Zordiac** [comment]
I have been able to work around this using point annotations for now.

awesome, thank you!
