### ISSUE TITLE
Ability to StackOnlyArea and be able to overly other line values

### ISSUE THREAD

**Issue by Corey-J** [apexcharts/apexcharts.js#4152]
## Summary
Introduce a new property to either chart, or onto each series that allows multiple of the same chart type to stack (In this case, area). While allowing other chart types to remain independent.

## API Changes
..

## Intended Use Case
My intended use case is i have a multi y-axis chart, that has 2 area series and 5 line series (One of the line charts is on the separate axis). The area charts are required to stack on each other, but the data for each of the line series must remain independent. The request is similar to the 'stackonlybar' option that exists, more info here (https://github.com/apexcharts/apexcharts.js/issues/4132)

**Comment by johnwheal** [comment]
I have the same requirement and was previously able to implement this but fix #4132 has broken my code

**Comment by sora0kuro** [comment]
Hi!
I would have the same requirement. Can we reopen this request? Is there any chance to implement it some day?
