### ISSUE TITLE
Weird behaviour of the area chart with datetime xaxis 

### ISSUE THREAD

**Issue by AleksandrZhukov** [apexcharts/apexcharts.js#4154]
### Description

seems this issued caused by https://github.com/apexcharts/apexcharts.js/commit/360324f5ec55541f26fa2f03c84026f91aadbf88

### Steps to Reproduce

1. open link https://codepen.io/Oleksandr-Zhukov/pen/XWOvOXy
2. press reset zoom icon

### Expected Behavior
chart has smooth line

<img width="670" alt="Screenshot 2023-12-18 at 5 04 55 PM" src="https://github.com/apexcharts/apexcharts.js/assets/8876116/dd6f7204-da7d-4219-8128-1db1bc2c299e">

### Actual Behavior

chart has weird line
<img width="659" alt="Screenshot 2023-12-18 at 4 58 17 PM" src="https://github.com/apexcharts/apexcharts.js/assets/8876116/22541e3e-5a46-43a4-9879-dbe1904af8ab">

### Reproduction Link

https://codepen.io/Oleksandr-Zhukov/pen/XWOvOXy

**Comment by munistt** [comment]
How can i use older version of this chart? Any possibility......Still showing line backward when using smooth and datetime

**Comment by junedchhipa** [comment]
The previous `smooth` logic is re-added since v3.45.2

So, from now on, you have 4 curve options for stroke

```js
stroke: {
  curve: "smooth" // straight, smooth, monotoneCubic, stepline
}
```
