### ISSUE TITLE
How to set text align in Y-axis labels text?

### ISSUE THREAD

**Issue by BunditSpace** [apexcharts/apexcharts.js#416]
![aligntext](https://user-images.githubusercontent.com/25604039/54660221-1bd0c880-4b08-11e9-9e04-4652b5859f73.png)

expected result 
![aligntext_expect](https://user-images.githubusercontent.com/25604039/54660233-2ab77b00-4b08-11e9-8b23-29c1d7d700c4.png)

Can I set text align xaxis ?

**Comment by junedchhipa** [comment]
Aligning the y-axis texts the way you described isn't possible yet.

**Comment by marghoobahmad0344** [comment]
yaxis:{
labels:{
show:true,
align:left
}
}
this is how you can align the text.

**Comment by abz121** [comment]
> yaxis:{ labels:{ show:true, align:left } } this is how you can align the text.

I can confirm this works. 

Make sure you add in "align:left" under the labels INSIDE yaxis, not a top level object item
