### ISSUE TITLE
Clipping bug on ipad

### ISSUE THREAD

**Issue by johannegger** [apexcharts/apexcharts.js#417]
Hi! 
On the ipad when specifying a y-axis minimum clipping doesn't seem to work right for bar charts. 
I'm attaching a screenshot that shows the problem. 

![IMG_0001](https://user-images.githubusercontent.com/7631765/54678066-a1eb1000-4b04-11e9-9ebb-2374120d84f8.PNG)

Please let me know if you don't have an ipad & need help testing a fix before merging and thanks again for the awesome work!

**Comment by junedchhipa** [comment]
Can you also create a codepen of the issue, please?
I will try to test on iPad emulators and see what is causing it.

**Comment by johannegger** [comment]
I just tried to put it in a codepen but wasn't able to replicate the behaviour easily. With just a chart and my data + settings the ipad rendered it just fine. Now I'm suspecting angular in combination with fxFlex to be causing the problem. The same goes for #418 btw. 
I'll try to create a more complete codepen later.

**Comment by johannegger** [comment]
Hi again! 
Small update on this bug: The problem still exists but unfortunately I wasn't able to provide a small enough codepen. However I managed to track down the problem: according to [caniuse](https://caniuse.com/#feat=css-clip-path) safari only partially supports the css-clip-path property. But if I understand correctly you'd need to use the -webkit- prefix. 
Would it be possible for you to add that?

Thanks again for the awesome work! 

Ps.  [418](https://github.com/apexcharts/apexcharts.js/issues/418) seems to suffer from the same problem - the safari apparently does not like the url with anchor

**Comment by junedchhipa** [comment]
Thanks for tracking down the problem.
Yeah, I have used `clip-path` attribute on SVG elements, but not as a CSS property. I am not sure if a prefix is required in HTML attrs.

**Comment by johannegger** [comment]
ah yeah, that makes sense. The strange thing is that all of the url with anchor problems i'm seeing seem to be a problem of the combination of angular + apexcharts. Whatever I try to reproduce in codepen it's just never the same as in my webapp. Next I'm going to try ng-apexcharts and see if that makes any difference.
