### ISSUE TITLE
Gradient area bug on ipad 

### ISSUE THREAD

**Issue by johannegger** [apexcharts/apexcharts.js#418]
Hi! 

On the ipad the gradient setting for areas does not show correctly:
![IMG_0003](https://user-images.githubusercontent.com/7631765/54680227-a2d27080-4b09-11e9-9732-98f1ba9e3f6b.PNG)
(expected result - on chrome)
![Capture](https://user-images.githubusercontent.com/7631765/54680422-14aaba00-4b0a-11e9-9a76-0a8f103d015c.PNG)

The configuration I'm using for options.fill atm is: 
```
{
  type: 'gradient',
  gradient: {
    colorStops: [
      [{
        opacity: 0.3
      }],
      [{
        opacity: 0.5
      }]
    ]
  }
}
```
I tried to play around with the parameters (changing colours etc)but the result was always the same. 

As mentioned in #417 if you need help testing on an ipad let me know.

**Comment by hellomattio** [comment]
@johannegger were you able to find a solution to this issue? 

I'm having the same problem - gradients work on Android devices, though I get a solid black fill on all iOS devices.

I'm using Ionic 4, Angular and Capacitor.

**Comment by johannegger** [comment]
@hellomattio no, sorry mate, I didn't find a soltion. right now I'm just using the opacity option which is good enough for my use case and works on the ipad. 
From your chart I can see that you also scale the y-axis. Just out of curiosity: when you switch the chart type to 'bar' do you also get the  [clipping problem](https://github.com/apexcharts/apexcharts.js/issues/417) in your setup?

**Comment by hellomattio** [comment]
@johannegger I actually get an x-axis clipping issue, it seems!

<img width="471" alt="Screen Shot 2019-05-21 at 08 45 48" src="https://user-images.githubusercontent.com/12060759/58056611-15f97100-7ba5-11e9-8142-c1052b196f18.png">

**Comment by johannegger** [comment]
@hellomattio ok, that might be a different issue, don't know. but here you are starting the y-axis at 0. Could you try to start it at a higher value and see if the bars overflow?

**Comment by hellomattio** [comment]
Ah yes, indeed they do @johannegger  - just as you've described in https://github.com/apexcharts/apexcharts.js/issues/417. 
Screenshot below has y-axis min set to `50`.

<img width="456" alt="Screen Shot 2019-05-22 at 09 01 19" src="https://user-images.githubusercontent.com/12060759/58136108-465a1180-7c70-11e9-9154-343dae46fa83.png">

**Comment by johndrew** [comment]
I had the same bug in desktop Safari: https://github.com/apexcharts/vue-apexcharts/issues/127. The routing we used was interfering with the CSS url property, which the svg uses to reference different svg elements. One fix was to manually update the fill in all path tags, but I'm hoping the apex team can suggest a solution or fix.

**Comment by Sitronik** [comment]
I too detect incorrect display area apexcharts on ios 13.2.2 but correct display on ios 14.4
