### ISSUE TITLE
Border radius is not applied when the last series contains a 0 value

### ISSUE THREAD

**Issue by jashaj** [apexcharts/apexcharts.js#4181]
### Description

For a stacked bar chart, the border radius is only applied to the last series. When that series contains a 0 value, the bar does not have a border radius. There seems to be no fallback to the closest series that has a value !== 0. 

### Steps to Reproduce

1. Create a stacked bar chart with multiple series
2. Apply a border radius > 0
3. Set one value of the last series to 0

### Expected Behavior

The border radius is applied to the closest series with a value to get rounded corners

### Actual Behavior

The bar has no rounded corner

### Screenshots

The second bar from the left lacks rounded corners 

![Stacked bar chart with missing rounded corners in one bar](https://github.com/apexcharts/apexcharts.js/assets/1112041/66745c10-c0da-425c-99c5-463048fbb83e)

### Reproduction Link

JSFiddle: https://jsfiddle.net/jasha/vjwk05ed/4/

**Comment by mizinin** [comment]
@junedchhipa this is a real annoying issue

**Comment by jeanchaneto** [comment]
+1 Any fixes yet?

**Comment by junedchhipa** [comment]
[commit](https://github.com/apexcharts/apexcharts.js/commit/b06abe8ef944add6b1c6a16790a35c3db9717f34) fixes this
