### ISSUE TITLE
Treemap with sparkline does not work 

### ISSUE THREAD

**Issue by jimmykane** [apexcharts/apexcharts.js#4182]
### Steps to Reproduce

1. Create treemap
2. Add sparkline to true
3. chart labels wont show

### Expected Behavior
Chart labels will show 

### Actual Behavior
They dont 

### Screenshots

<img width="1728" alt="Screenshot 2024-01-08 at 12 34 24" src="https://github.com/apexcharts/apexcharts.js/assets/1268723/2b2be82f-6a69-48d8-830f-a82eb8a66eb0">

### Reproduction Link

I dont want to login to another service with my data . 

Copy past this 

```
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "treemap",
    sparkline: {enabled: true}
  },
  series: [
    {
      name: "Series 1",
      data: [{x: 'test', y:100}]
    }
  ]
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```
-->

**Comment by brianlagunas** [comment]
The reproduction link is required as stated in the issue template.

**Comment by jimmykane** [comment]
Hi @brianlagunas  seriusly in the above link you only add a couple of lines and you see it. 

```
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "treemap",
    sparkline: {enabled: true}
  },
  series: [
    {
      name: "Series 1",
      data: [{x: 'test', y:100}]
    }
  ]
};
```

For this reason you close the issue and dont take the time to mark this like a bug? Its not a proper reaction from your side
