### ISSUE TITLE
YAxis labels not shown when formatted starts with 0

### ISSUE THREAD

**Issue by sergeydus** [apexcharts/apexcharts.js#4189]
### Description
If the formatter you pass into the yaxis.labels.format function formats text that starts with zero, it'll appear empty

### Steps to Reproduce
1. create a chart with a series
2. set yaxis.labels.formatter to ()=>'0 test'
3. on hover labels no longer appear

### Expected Behavior
hover labels should appear

### Actual Behavior
hover labels do not appear

### Screenshots
<img width="567" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/29180697/f8e57f6d-3952-4f3e-ba42-bd298b630058">

### Reproduction Link
https://codepen.io/sergeydus/pen/MWxJLOQ

**Comment by olgad0110** [comment]
I'm seeing this issue as well. 
If it's a float number starting with 0 it is working. But not if you want to format it with a comma instead of a dot.
- `()=>'0.25 test'` is working
- `()=>'0,25 test'` is not working

The same also applies when using `tooltip.y.formatter` function

**Comment by junedchhipa** [comment]
As a workaround for now, also set the `tooltip.y.formatter` when setting y-axis formatter.
```js
      tooltip: {
          y: {
            formatter: (val) => {
              return val
            }
          }
        }
```

**Comment by XamzatJR** [comment]
> As a workaround for now, also set the `tooltip.y.formatter` when setting y-axis formatter.
This workaround doesn't work for me when val equals zero. Have to use:
`if (val === 0) return '"0"'`

**Comment by junedchhipa** [comment]
This issue is no longer present. It was fixed with the latest releases.
Try upgrading apexcharts to 3.49.0
