### ISSUE TITLE
Smooth glitch in the time series line chart

### ISSUE THREAD

**Issue by ranawael1** [apexcharts/apexcharts.js#4199]
### Description
There is a glitch with the time series line chart when there is a gap between two points in the date. The smooth curve returns back on the time x-axis and then proceeds to the next point

![Screenshot from 2024-01-21 23-51-49](https://github.com/apexcharts/apexcharts.js/assets/42323978/d66634d8-8701-4753-b87f-b59283b18c42)

**Comment by brianlagunas** [comment]
Did not follow big template instructions
