### ISSUE TITLE
Shared tooltips do not work with Irregular Timeseries

### ISSUE THREAD

**Issue by jhuckaby** [apexcharts/apexcharts.js#420]
First of all, thank you for an awesome chart library.  I absolutely love ApexCharts!

## Codepen

This issue is actually illustrated perfectly on your **Irregular Timeseries** demo page, so no codepen is required:

https://apexcharts.com/javascript-chart-demos/area-charts/irregular-timeseries/

This demo has the following configuration for the tooltip:

```js
tooltip: {
	shared: true
},
```

However, as you can see in the demo, the tooltips are not showing as shared, even if you hover over a point intersecting multiple series.  Instead, it only shows a single series in the tooltip. 
 Screenshot:

<img width="277" alt="Screenshot 2019-03-20 17 27 25" src="https://user-images.githubusercontent.com/700765/54727515-72083080-4b35-11e9-8a99-5986ed332a0d.png">

### What is the behavior you expect?

I expect that when `tooltip.shared` is set to `true`, that all intersecting series will show in the tooltip hover.  This is indeed the case when all series start at the same timestamp (i.e. a "regular" timeseries).

### What is happening instead?

The tooltip hover is only showing one single series (the nearest one), even though multiple series intersect the X position of the mouse.

### What error message are you getting?

There is no error message.  This is just a visual issue.

I've noticed that when all my series data starts at the same timestamp (i.e. regular, not irregular) the shared tooltip works just fine.  This issue only occurs when one or more of the series starts at a different timestamp, as shown in your Irregular Timeseries demo.

**Comment by jhuckaby** [comment]
Here is codepen created from your Irregular Timeseries demo code, but I adjusted all three series to start at the same timestamp, and have the same array length:

https://codepen.io/anon/pen/EMdpmN

As you can see, the shared tooltip works just fine in this case.

**Comment by junedchhipa** [comment]
By default, a shared tooltip is turned off in an irregular time-series.
Until now, I haven't found a solution that would work elegantly in this case, hence I turned it off programmatically.

I will visit that part of code once again to see how it goes, thanks!

**Comment by petericebear** [comment]
Any updates on this? We have a similar issue in our graphs with 'missing' keys, but the days at the x-axes are equal.

**Comment by junedchhipa** [comment]
If the days at the x-axes are equal, you should create series with null values so that all `series` length stays equal.

```javascript
series: [
  {
    data: [
      {
        x: new Date('17 Jul').getTime(),
        y: 20
      },
      {
        x: new Date('18 Jul').getTime(),
        y: 30
      },
      {
        x: new Date('19 Jul').getTime(),
        y: null
      }
    ]
  },
  {
    data: [
      {
        x: new Date('17 Jul').getTime(),
        y: null
      },
      {
        x: new Date('18 Jul').getTime(),
        y: 23
      },
      {
        x: new Date('19 Jul').getTime(),
        y: 98
      }
    ]
  }
],
```

**Comment by onli** [comment]
Wouldn't it maybe be possible to optionally show the y value at the line position, instead of the datapoint? 

For context, in my example I only have data point when values are about to change. So the correct behaviour for a shared tooltip in those cases of an irregular timeseries would be to either show the y value of the all series lines at the date, or to show the y value of the closes data point of each series.

**Comment by niklashaug** [comment]
Any updates on this?

**Comment by niklashaug** [comment]
@junedchhipa can we expect an official fix for this sometime?

**Comment by betaanish** [comment]
i am stuck with this from past few days.....any update on this

**Comment by betaanish** [comment]
@junedchhipa ....please suggest any workaround

**Comment by matthew-williamson-sd** [comment]
@betaanish He's already suggested a workaround, just add the missing dates with null values

**Comment by alfonsrv** [comment]
The suggested fix doesn't work.

![Chart](https://i.imgur.com/IjShC2J.jpg)

```javascript

$(document).ready(function() {
    primary = [{
        x: "2020-01-05",
        y: null
    }, {
        x: "2020-10-01",
        y: 30
    }, {
        x: "2019-11-01",
        y: 15
    }, {
        x: "2020-11-02",
        y: 30
    }, ]
    secondary = [{
        x: "2020-01-05",
        y: 15
    }, {
        x: "2020-10-01",
        y: null
    }, {
        x: "2019-11-01",
        y: null
    }, {
        x: "2020-11-02",
        y: 30
    }, ]
    
    var options = {
        series: [{
            name: 'Primary',
            data: primary
        }, {
            name: 'Secondary',
            data: secondary
        }],
        chart: {
            type: 'line',
            stacked: false,
            height: 350,
            zoom: {
                type: 'x',
                enabled: true,
                autoScaleYaxis: true
            },
            toolbar: {
                autoSelected: 'zoom'
            }
        },
        dataLabels: {
            enabled: true
        },
        markers: {
            size: 0,
        },
        title: {
            text: 'Sample Series',
            align: 'left'
        },
        yaxis: {
            labels: {
                formatter: function(val) {
                    return val;
                },
            },
            title: {
                text: 'Amount'
            },
        },
        xaxis: {
            type: 'datetime',
        },
        tooltip: {
            shared: true,
            y: {
                formatter: function(val) {
                    return val;
                }
            }
        }
    };
    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();
});

```

**Comment by v360-eduardo-marques** [comment]
facing the same problem here.

any chances it'll be fixed anytime soon?

**Comment by Muqeet1** [comment]
The same issue here, any fix so far?

**Comment by faizalami** [comment]
hey everyone, I think I got the solution, and perhaps this solution will works for any case

so the key is using the "w.globals" context, and I used this flow to generate a correct tooltip:

1. store the hovered x-axis series value (in this case is date time in integer form)
2. find and map the index of similar time from another x-axis series from  w.globals.seriesX
3. print series value based on all x-axis points found with similar time
4. style the tooltip, you can format the hovered x-axis series value to readable date time format as tooltip title

```javascript
custom: ({ series, seriesIndex, dataPointIndex, w }) => {
      const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
      const hoverIndexes = w.globals.seriesX.map(seriesX => {
        return seriesX.findIndex(xData => xData === hoverXaxis);
      });

      let hoverList = '';
      hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
        if (hoverIndex >= 0) {
          hoverList += `<span>${w.globals.seriesNames[seriesEachIndex]}: ${series[seriesEachIndex][hoverIndex]}</span><br />`;
        }
      });
      const formatHoverX = this.dateFormat(new Date(hoverXaxis), 'YYYY-MM-DD HH:mm:ss');

      return `<div class="card">
        <div class="card-header p-1">${formatHoverX}</div>
        <div class="card-body p-1">
          ${hoverList}
        </div>
      </div>`;
    },
```

**Comment by Splinter0** [comment]
Hello everyone, follow up on the comment by @faizalami , this is my implementation to fix the issue. For context, I use the Vue wrapper.

```js
        customSharedTooltip({ series, seriesIndex, dataPointIndex, w }) {
            const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
            const hoverIndexes = w.globals.seriesX.map((seriesX) => {
                return seriesX.findIndex((xData) => xData === hoverXaxis);
            });

            let hoverList = "";
            hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
                if (hoverIndex >= 0) {
                    hoverList += `
                        <div class="apexcharts-tooltip-series-group apexcharts-active" style="order: 1; display: flex;">
                            <span class="apexcharts-tooltip-marker" style="background-color: ${
                                w.globals.markers.colors[seriesEachIndex]
                            };"></span>
                            <div class="apexcharts-tooltip-text" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
                                <div class="apexcharts-tooltip-y-group">
                                    <span class="apexcharts-tooltip-text-y-label">${
                                        w.globals.seriesNames[seriesEachIndex]
                                    }: </span>
                                    <span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
                                        series[seriesEachIndex][hoverIndex]
                                    )}</span>
                                </div>
                            </div>
                        </div>`;
                }
            });
            return `<div class="apexcharts-tooltip-title" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">${w.globals.tooltip.xaxisTooltip.innerText}</div>${hoverList}`;
        },
```
This is the method I defined, this way the rendering for the tooltip is identical to the default tooltip used by Apex. The `w.globals.tooltip.xaxisTooltip.innerText` is a little hacky but I could not find the function formatting the xvalues for the tooltip.
I really think this issue should be addressed in upstream.

**Comment by LukaButikashvili** [comment]
To solve this problem your **series datas** must have **equal lengths**. 
for example: 
series: [
			{
				name: 'smth1',
				data: [0, 0, 0, 0, 0, 0]
			},
			{
				name: 'smth2',
				data: [21, 21, 3, 4, 5, 6]
			},
			{
				name: 'smth3',
				data: [1, 2, 3, 4, 5, 0]
			}
]
all series (smth1, smth2, smth3) data lengths are same.

**Comment by dmitrypasyutin** [comment]
@Splinter0 thanks a lot!
by the way, there should be

`w.globals.yLabelFormatters[seriesEachIndex]`

instead of 

`w.globals.yLabelFormatters[0]`

**Comment by placid2000** [comment]
Thank you @Splinter0 and @dmitrypasyutin . This solution temporary solves the problem.
What I'm missing though, are the markers on each line when hovering. I think this might be related to the same issue.

Example: I would expect to have a marker on the green line as well:
![image](https://user-images.githubusercontent.com/699322/197996303-c47dc17e-2f5d-4c94-9a26-e6cac50b3cff.png)


Is there a way to improve this ?

**Comment by raoulspronck** [comment]
> Hello everyone, follow up on the comment by @faizalami , this is my implementation to fix the issue. For context, I use the Vue wrapper.
> 
> ```js
>         customSharedTooltip({ series, seriesIndex, dataPointIndex, w }) {
>             const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
>             const hoverIndexes = w.globals.seriesX.map((seriesX) => {
>                 return seriesX.findIndex((xData) => xData === hoverXaxis);
>             });
> 
>             let hoverList = "";
>             hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
>                 if (hoverIndex >= 0) {
>                     hoverList += `
>                         <div class="apexcharts-tooltip-series-group apexcharts-active" style="order: 1; display: flex;">
>                             <span class="apexcharts-tooltip-marker" style="background-color: ${
>                                 w.globals.markers.colors[seriesEachIndex]
>                             };"></span>
>                             <div class="apexcharts-tooltip-text" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
>                                 <div class="apexcharts-tooltip-y-group">
>                                     <span class="apexcharts-tooltip-text-y-label">${
>                                         w.globals.seriesNames[seriesEachIndex]
>                                     }: </span>
>                                     <span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
>                                         series[seriesEachIndex][hoverIndex]
>                                     )}</span>
>                                 </div>
>                             </div>
>                         </div>`;
>                 }
>             });
>             const parsed = new Date(hoverXaxis)
>                 .toDateString()
>                 .split(" ")
>                 .slice(1);
>             return `<div class="apexcharts-tooltip-title" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">${
>                 parsed[1] + " " + parsed[0] + " " + parsed[2]
>             }</div>${hoverList}`;
>         },
> ```
> 
> This is the method I defined, this way the rendering for the tooltip is identical to the default tooltip used by Apex. I really think this issue should be addressed in upstream.

Does anyone have this solution for React apexcharts?

**Comment by LaphazeMC** [comment]
One small fix for your custom code @Splinter0, if you have different series label formatter, you must change this line 
```
<span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
                                        series[seriesEachIndex][hoverIndex]
                                    )}</span>
```
to this 
```
<span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[seriesEachIndex](
                                        series[seriesEachIndex][hoverIndex]
                                    )}</span>
```

Full updated code :
```
customSharedTooltip({ series, seriesIndex, dataPointIndex, w }) {
            const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
            const hoverIndexes = w.globals.seriesX.map((seriesX) => {
                return seriesX.findIndex((xData) => xData === hoverXaxis);
            });

            let hoverList = "";
            hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
                if (hoverIndex >= 0) {
                    hoverList += `
                        <div class="apexcharts-tooltip-series-group apexcharts-active" style="order: 1; display: flex;">
                            <span class="apexcharts-tooltip-marker" style="background-color: ${
                                w.globals.markers.colors[seriesEachIndex]
                            };"></span>
                            <div class="apexcharts-tooltip-text" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
                                <div class="apexcharts-tooltip-y-group">
                                    <span class="apexcharts-tooltip-text-y-label">${
                                        w.globals.seriesNames[seriesEachIndex]
                                    }: </span>
                                    <span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
                                        series[seriesEachIndex][hoverIndex]
                                    )}</span>
                                </div>
                            </div>
                        </div>`;
                }
            });
            const parsed = new Date(hoverXaxis)
                .toDateString()
                .split(" ")
                .slice(1);
            return `<div class="apexcharts-tooltip-title" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">${
                parsed[1] + " " + parsed[0] + " " + parsed[2]
            }</div>${hoverList}`;
        },
```

**Comment by stalniy** [comment]
the code above still may not work if corresponding XValue is not found in other series. This fixed code finds not only equal but the most close value on X axis to the one which was hovered. Obviously this works only with numbers (e.g., timestamps) on X axis. For me this is more than enough:

```ts
function customTooltip({ series, seriesIndex, dataPointIndex, w }) {
    const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
    const hoverIndexes = w.globals.seriesX.map((seriesX) => {
      let min = Math.abs(seriesX[0] - hoverXaxis);
      let minIndex = 0;
      for (let i = 1; i < seriesX.length; i++) {
        const v = Math.abs(seriesX[i] - hoverXaxis);
        if (v < min) { 
          min = v;
          minIndex = i;
        }
       }
      return minIndex
    });

    let hoverList = "";
    hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
        if (hoverIndex >= 0) {
            hoverList += `
                <div class="apexcharts-tooltip-series-group apexcharts-active" style="order: 1; display: flex;">
                    <span class="apexcharts-tooltip-marker" style="background-color: ${
                        w.globals.markers.colors[seriesEachIndex]
                    };"></span>
                    <div class="apexcharts-tooltip-text" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
                        <div class="apexcharts-tooltip-y-group">
                            <span class="apexcharts-tooltip-text-y-label">${
                                w.globals.seriesNames[seriesEachIndex]
                            }: </span>
                            <span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
                                series[seriesEachIndex][hoverIndex]
                            )}</span>
                        </div>
                    </div>
                </div>`;
        }
    });
    const parsed = new Date(hoverXaxis)
        .toDateString()
        .split(" ")
        .slice(1);
    return `<div class="apexcharts-tooltip-title" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">${
        parsed[1] + " " + parsed[0] + " " + parsed[2]
    }</div>${hoverList}`;
}
```

**Comment by sebgutierrez** [comment]
> Hello everyone, follow up on the comment by @faizalami , this is my implementation to fix the issue. For context, I use the Vue wrapper.
> 
> ```js
>         customSharedTooltip({ series, seriesIndex, dataPointIndex, w }) {
>             const hoverXaxis = w.globals.seriesX[seriesIndex][dataPointIndex];
>             const hoverIndexes = w.globals.seriesX.map((seriesX) => {
>                 return seriesX.findIndex((xData) => xData === hoverXaxis);
>             });
> 
>             let hoverList = "";
>             hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
>                 if (hoverIndex >= 0) {
>                     hoverList += `
>                         <div class="apexcharts-tooltip-series-group apexcharts-active" style="order: 1; display: flex;">
>                             <span class="apexcharts-tooltip-marker" style="background-color: ${
>                                 w.globals.markers.colors[seriesEachIndex]
>                             };"></span>
>                             <div class="apexcharts-tooltip-text" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
>                                 <div class="apexcharts-tooltip-y-group">
>                                     <span class="apexcharts-tooltip-text-y-label">${
>                                         w.globals.seriesNames[seriesEachIndex]
>                                     }: </span>
>                                     <span class="apexcharts-tooltip-text-y-value">${w.globals.yLabelFormatters[0](
>                                         series[seriesEachIndex][hoverIndex]
>                                     )}</span>
>                                 </div>
>                             </div>
>                         </div>`;
>                 }
>             });
>             const parsed = new Date(hoverXaxis)
>                 .toDateString()
>                 .split(" ")
>                 .slice(1);
>             return `<div class="apexcharts-tooltip-title" style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">${
>                 parsed[1] + " " + parsed[0] + " " + parsed[2]
>             }</div>${hoverList}`;
>         },
> ```
> 
> This is the method I defined, this way the rendering for the tooltip is identical to the default tooltip used by Apex. I really think this issue should be addressed in upstream.

This worked really well for me! I had to modify this line so only the active series appear. Otherwise the hidden series value will show undefined.
```javascript
hoverIndexes.forEach((hoverIndex, seriesEachIndex) => {
    if (hoverIndex >= 0 && w.globals.collapsedSeriesIndices.includes(seriesEachIndex) === false) { ... } 
```

**Comment by junedchhipa** [comment]
The original issue is not reproducible in the latest version as tested on v4.3.0.
