### ISSUE TITLE
Scrollable charts for large data set

### ISSUE THREAD

**Issue by SammYeomans** [apexcharts/apexcharts.js#4202]
## Summary

For the large data set, we need a scrollbar to allow users to interact with the chart on a small width/height container. And also when we scroll the chart, the xaxis/yaxis should be sticky.

Sample from Highcharts: [https://www.highcharts.com/docs/chart-concepts/scrollbar]()
Jsfiddle: [https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea]()

## API Changes

I'm not sure about the API changes, I think we must split the axes and the chart into different containers and then make the chart overflow: scroll, so the chart will be scrollable and the axis still sticky on the front of the chart.

## Intended Use Case

For large data sets which can't be displayed well in a small container.

There is a related issue here: https://github.com/apexcharts/apexcharts.js/issues/543

A usage sample for heatmap:

https://user-images.githubusercontent.com/27690861/147403089-025d93d4-a0c1-4ce1-9e05-ab0208a23a64.gif

**Comment by mohdmujahithali** [comment]
@SammYeomans Is there any update on this feature request? Now my team also having the same feature (larger set on y-axis, and so need scrollable y-axis)
