### ISSUE TITLE
Data Labels are missaligned and the last x grid line is not wisible

### ISSUE THREAD

**Issue by clarisandev** [apexcharts/apexcharts.js#4206]
### Description

- Data labels are missaligned
- Although the last x label and tick are visible, the last x grid line is not 

### Steps to Reproduce

1. Create a _Multiple series – Group rows_ Timeline chart => https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/
2. Add to options: 
 ```
grid: {
    xaxis: {
      lines: {
        show: true
      }
    },
    yaxis: {
      lines: {
        show: false
      }
    },
},
dataLabels: {
    enabled: "true"
}
```

### Expected Behavior

- DataLabels should to be displayed inside the bars that they relate to.
- All x axis ticks should have a grid line

### Actual Behavior

- DataLabels are missaligned
- Last X-axis grid line is not shown

### Screenshots

- _Missing last x grid line_
![Screenshot from 2024-01-30 09-21-10](https://github.com/apexcharts/apexcharts.js/assets/54486868/9926a29d-b19e-4f75-9de8-3c962d01d4d4)

- _Missaligned data labels_
![Screenshot from 2024-01-30 09-20-54](https://github.com/apexcharts/apexcharts.js/assets/54486868/e96662f8-b4f7-4572-8eec-ec8089a09fcf)

### Reproduction Link

[CODEPEN](https://codepen.io/Clara-Sanchez-the-flexboxer/pen/ZEPvVra) => using the same example as the one provided in the docs: https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

**Comment by dilorenzoQRM** [comment]
Have the same issue with data labels. 
Seems to happen only when both values are negative

<img width="757" alt="ChartIssue" src="https://github.com/apexcharts/apexcharts.js/assets/150236217/2dfe2dfd-2f01-4019-8eb4-2f1bfac3ac3e">
