### ISSUE TITLE
Apexcharts legend markers not showing

### ISSUE THREAD

**Issue by Caspar2318** [apexcharts/apexcharts.js#4208]
### Steps to Reproduce

1.  Using react-apexcharts within nextjs project, the legend works great at localhost
2. After deployed to AWS and the legend markers disappeared suddenly
3. Cannot find the right way to solve it: added  markers: {
        fillColors: [],
        width: 12,
        height: 12,
        radius: 12,
      } 
within legend:{ } was not able to solve this issue.

### Expected Behavior
Looks perfect locally as this:
<img width="608" alt="Screenshot 2024-02-01 at 1 06 56 pm" src="https://github.com/apexcharts/apexcharts.js/assets/108163945/b0ebdcb5-a0df-4399-bb20-1cb44b39f252">

### Actual Behavior
But after deployment: 
<img width="855" alt="Screenshot 2024-02-01 at 1 08 11 pm" src="https://github.com/apexcharts/apexcharts.js/assets/108163945/0736eb0b-e610-4815-97f8-d09605d7fafd">

**Comment by brianlagunas** [comment]
Missing required reproduction link
