### ISSUE TITLE
Linechart of percentages with max value 100%

### ISSUE THREAD

**Issue by valeLib** [apexcharts/apexcharts.js#421]
I'm doing a line chart with percentages values, and I'd like to set 100% as maximum value in the Y axis, but when using forceNiceScale, the maximum value is auto generated and sometimes is higher than 100%, which for this kind of visualization is nonsense. 

Without forceNiceScale, if I set the maximum value, the values of the ticks in the Y axis get weird values, in an irregular scale.

[Example of a percentage visualization in codesandbox](https://codesandbox.io/embed/14vkoj526l?fontsize=14)

I'd like to know if there is a property for working with percentage visualizations, that fixes some of this issues.

**Comment by junedchhipa** [comment]
```javascript
yaxis: {
  forceNiceScale: false,
  max: 100,
  labels: {
    formatter: (value) => value.toFixed(0) +'%',
  },
}
```

**Comment by valeLib** [comment]
Your answer solves the problem with the amount of decimals in the tick values. But the following issue continues, by doing the fix you proposed, the ticks in the y axis have "irregular" values, like 81% instead of 80%. I'd like that this ticks have cleaner values, like the ones achieved by using forceNiceScale.

One solution I tried was defining the step manually, as well as the maximum and minimum value of the y axis, but the step ignores my defined range, and calculates the ticks based on the range of the given data.

**Comment by junedchhipa** [comment]
Yeah, tickAmount along with min and max would do the trick.

min: 50
max: 100,
tickAmount: 10

**Comment by valeLib** [comment]
Thanks, that solved my issue!
