### ISSUE TITLE
endingShape / Stroke bar chart

### ISSUE THREAD

**Issue by LucaCorcella** [apexcharts/apexcharts.js#422]
## Round end on bar chart

Hi my code for bar chart is.
let option = {
        chart: {
          type: 'bar',
          width: 200,
          height: 150,
          sparkline: {
            enabled: true
          }
        },
        plotOptions: {
          bar: {
            columnWidth: '40%',
            endingShape: 'rounded',
            dataLabels: {
                position: 'top',
              }
          }
        },
        series: series,
        labels: labels,
     dataLabels: {
            enabled: true,
            offsetY: -15,
            style: {
              fontSize: '8px',
              fontWeight: 'bold',
              fontFamily: 'sans-serif',
              colors: ['#000']
            },
            dropShadow: {
              enabled: false,
              top: 1,
              left: 0,
              blur: 1,
              opacity: 0.45
            }
          },
     stroke: {
        show: true,
        width: 1,
        colors: ['transparent']
    },
        xaxis: {
          crosshairs: {
            width: 1
          },
        },
        tooltip: {
          fixed: {
            enabled: false
          },
          x: {
            show: false
          },
          y: {
            title: {
              formatter: function (seriesName) {
                return ''
              }
            }
          },
          marker: {
            show: false
          }
        }
      }

## Explanation

- I would like a bar with rounded border on end
- But with the current version, it doesn't work, if I try with this version https://cdnjs.cloudflare.com/ajax/libs/apexcharts/1.4.6/apexcharts.min.js" it works fine!

**Comment by junedchhipa** [comment]
The `endingShape` property has been deprecated, and soon a new property `borderRadius` will be implemented.

**Comment by LucaCorcella** [comment]
so with version 3.6.3 I can't get bar rounded?.

Now I'm trying the 3.0.0 version and it works!

**Comment by junedchhipa** [comment]
It was removed recently in 3.6.0.
You may use 3.0.0 until borderRadius is released

**Comment by junedchhipa** [comment]
Closing as related to #414

**Comment by rileylnapier** [comment]
any update on borderRadius?

**Comment by astronati** [comment]
+1

**Comment by rileylnapier** [comment]
Btw, I went to recharts.  I can define my own shape.  Wanted to share in case anyone else was looking for alternatives.

**Comment by astronati** [comment]
@rileylnapier how?

**Comment by junedchhipa** [comment]
The [endingShape](https://apexcharts.com/docs/options/plotoptions/bar#endingShape) property has been added again.

**Comment by Thimows** [comment]
Any updates on the release of 'borderRadius'?

**Comment by junedchhipa** [comment]
Released v.3.17.0
A new property `plotOptions.bar.startingShape` added.
So, using `plotOptions.bar.startingShape` & `plotOptions.bar.endingShape`, you can have the desired effect of rounded borders in bar/column charts.

```javascript
plotOptions: {
  bar: {
    startingShape: 'rounded',
    endingShape: 'rounded'
  }
}
```
![Screen Shot 2020-03-18 at 11 17 44 PM](https://user-images.githubusercontent.com/17950663/76990906-b90a4b00-696e-11ea-92e2-60292e2241e6.png)

[Codepen](https://codepen.io/apexcharts/pen/JjdZaPV)

**Comment by lmrisdal** [comment]
@junedchhipa Just wondering, was the idea of a border-radius property scrapped? I have been looking for a way to make the corners only slightly rounded.

**Comment by csfeijo** [comment]
This rounded shape is a little bit "abnormal" - it´s possible to be really rounded instead a "sausage" bars ?

**Comment by junedchhipa** [comment]
Decreasing the height of the bars (in case of a horizontal bar chart) would provide some improvements in the rounded.

```javascript
plotOptions: {
  bar: {
    barHeight: '30%'
  }
}
```

while in case a vertical column chart,
```javascript
plotOptions: {
  bar: {
    columnWidth: '30%'
  }
}
```

**Comment by csfeijo** [comment]
Thanks @junedchhipa :

![image](https://user-images.githubusercontent.com/25899/78178440-06d68700-7436-11ea-9eeb-64911fd81f4b.png)

I´m using 30% for barHeight - less than that the legend inside the bars will be unreadable.

**Comment by junedchhipa** [comment]
In that case, there is no other alternative, sorry.
The rounded shape is drawn with `path` instead of `rect`, so it's difficult to get that natural border-radius.

**Comment by csfeijo** [comment]
Ok, no problem !!!
Thanks for your support, the ApexCharts is amazing, this is a minimal detail guys! 
Cheers,

**Comment by adibreaban** [comment]
Is this working also with pie charts?

**Comment by ajaypal911** [comment]
You can use borderRadiusApplication in plot options for bar in this. They have introduced this new key in new version. 

`borderRadiusApplication: "around",`
