### ISSUE TITLE
Bar chart padding to the left

### ISSUE THREAD

**Issue by qroft** [apexcharts/apexcharts.js#423]
## Codepen
https://codepen.io/anon/pen/WmLZpj

## Explanation
- What is the behavior you expect?
The Chart to be centered.
- What is happening instead?
The space to the left is bigger than the space to he right. You can see it clearly in the axes-border at the bottom.
- What error message are you getting?
None, i am just using it on mobile where one chart is below the other and there this small more-padded space breaks the whole layout making the charts look irregular.

THE COLORS OF THE ATTACHED SCREENSHOT ARE JUST TO MAKE IT MORE CLEAR!
The second chart (column bar chart) is more right aligned.
This could be due to the space left for labels, but i think that if you set labels als FALSE that said space should be gone.

![Screenshot_20190322-151151](https://user-images.githubusercontent.com/14896725/54833590-4b253800-4cb6-11e9-8dc7-37ac8fa2f1cc.png)

**Comment by junedchhipa** [comment]
You can adjust the padding by

```javascript
grid: {
  padding: {
    left: 5
  }
}
```
