### ISSUE TITLE
The possibility to have an array of series in seriesName of y-axis

### ISSUE THREAD

**Issue by MarieNuellas** [apexcharts/apexcharts.js#4237]
## Summary
It would be cool if we could select multiple series in seriesName so in a multiple y-axis chart we can target the scale of a y-axis from multiple series 

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.
With my proposal, y-axis options would pass from 
`seriesName: String`
to
`seriesNames: String | String[]`
or simply
`seriesNames: String[]`

## Intended Use Case
With my proposal, it would permit to add a scale for multiple groups of series, in the exemple there are 2 groups of series, original and compared. it would allow me to make a scale for the two groups
<img width="775" alt="Screenshot 2024-02-14 at 11 27 46" src="https://github.com/apexcharts/apexcharts.js/assets/145000510/8a500755-8c7e-43e7-9ff7-962ba0c8ca6c">

**Comment by rosco54** [comment]
@junedchhipa this request can be closed, unless you're waiting to document it.
