### ISSUE TITLE
chart line doesn't match with value when use logarithmic in yaxis option

### ISSUE THREAD

**Issue by insightn777** [apexcharts/apexcharts.js#4241]
### Steps to Reproduce

1. set { logarithmic: true } in yaxis option
2. line didn't match with value-Y
3. please see Reproduction Link

### Screenshots
![logchart](https://github.com/apexcharts/apexcharts.js/assets/39460495/7d319c69-e8d3-4f48-a2bc-4b3f3ea9795c)

### Reproduction Link

https://codesandbox.io/p/sandbox/log-chart-error-s4yk8v

**Comment by rosco54** [comment]
Remove the negative numbers from your data series'. Or perhaps a logarithmic chart is not the appropriate one to use for this data.
