### ISSUE TITLE
Stack bar miss align text

### ISSUE THREAD

**Issue by premysl-ftmo** [apexcharts/apexcharts.js#4244]
Another miss align text on a stack bar:
![image](https://github.com/apexcharts/apexcharts.js/assets/89512281/2c288503-8cdd-41bc-8ff3-de43dc531aa4)
![image](https://github.com/apexcharts/apexcharts.js/assets/89512281/76c4e52c-f969-4cbb-9d06-b5f505c59421)

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
