### ISSUE TITLE
Problem with overlapping labels on YAxis with LineChart

### ISSUE THREAD

**Issue by Lenny333333** [apexcharts/apexcharts.js#4263]
### Description
I ran into a problem when plotting a simple LineChart, code example is attached. Basically what happens is that by setting certain yaxis minimum values the number of label increases and they all overlaps. It happens on different series values, but the code attached replicates the bug on the standard example.

I took the snippet from the example "Product Trends by Month" on your site (https://apexcharts.com/javascript-chart-demos/line-charts/basic/) and simply added 

        `yaxis:{
          min:-365
        }`

![image](https://github.com/apexcharts/apexcharts.js/assets/160837099/a759cef6-9336-4585-b505-789842ec6510)

If you set the min value to -360 the problem disappears.

![image](https://github.com/apexcharts/apexcharts.js/assets/160837099/0765829d-8213-48b0-816c-5f70f1dd160a)

### Reproduction Link
https://codepen.io/Lenny333333/pen/WNmBXBK

**Comment by rosco54** [comment]
As ApexCharts 3.46.0 tries to compute "nice" tick label values it must conform to your settings. I will need to check why it's choosing 200 as the highest tick value but, in this case, the resulting number of ticks is turning out to be a prime number: 200 - (-365) = 565, and the only nice stepSize it can use is 5, which gives you 113 ticks (a prime number). 

You can use forceNiceScale: true to stop the overlapping, but with prime numbers of ticks to start with you'll just get one tick at 200 and one at -365.

If you try:

yaxis: {
  max: 200,
  min: -365
}

The algorithm will give up trying to produce nice tick labels to comply with your settings.

You could take full control in this situation and use something like this to ensure also that the zero tick is included:

yaxis: {
  max: 225,
  min: -375,
  stepSize: 75
}
