### ISSUE TITLE
timeline chart - panning causes zoom level change

### ISSUE THREAD

**Issue by RustyJoeM** [apexcharts/apexcharts.js#4265]
### Description

Panning of timeline chart changes zoom-level down to data being invisibly tiny.

### Steps to Reproduce

1. open the timeline chart example page: https://apexcharts.com/javascript-chart-demos/timeline-charts/basic/
2. click the "hand"/panning icon in the top right corner of chart 
3. try panning the chart with left mouse button by small amounts to left/right
4. observe how bars are "squished"/zoomed out down to invisibility as you continue panning

### Expected Behavior

Bars are moved around on horizontal axis without changing the zoom level/scale.

### Actual Behavior

Zoom level changes, making data look smaller & smaller...

**Comment by junedchhipa** [comment]
@rosco54 Can you take a look on this one?

**Comment by rosco54** [comment]
Yes, in a day or so.

**Comment by rosco54** [comment]
@junedchhipa this issue isn't arising with the PR 4266 changes included. Could you verify that and perhaps merge the PR?

This makes sense as the issue only shows up with horizontal charts.

**Comment by rosco54** [comment]
@junedchhipa the demos charts are still using 3.46.0. This issue is resolved in 3.47.0.
