### ISSUE TITLE
Version 3.46.0 causes Area Chart Gradient to "Glitch" when Hiding / Showing Data Series

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#4271]
### Description
When hiding or showing certain series in an Area chart, the gradient of the series starts to glitch and causes artifacts within the gradient of the series.

### Steps to Reproduce

1. Visit this codepen that renders a basic Area chart with 2 series:  https://codepen.io/thimows/pen/WNmVyWb
2. Use the legend to hide / show certain series
3. You will notice that hiding/showing series is glitchy and causes artifacts in the gradient of the series.

### Expected Behavior
The chart animates smoothly as seen on version 3.45.2 and below

### Actual Behavior
The charts renders correctly, but hiding/showing data series is very glitchy and causes artifacts in the gradient of the series

### Screenshots

Link to reproduce: https://codepen.io/thimows/pen/WNmVyWb

https://github.com/apexcharts/apexcharts.js/assets/62159496/726cdefb-7dc1-44f2-beed-3546331bd505

**Comment by rosco54** [comment]
Looking at this now. Just noting, as a clue to what might be going on, that it doesn't appear when the stroke curve is set to straight line.

**Comment by Thimows** [comment]
@rosco54 Thanks so much!

**Comment by Thimows** [comment]
@rosco54 Sorry to bother, but it seems like this is still happening on **version 3.48.0** when the data series contains null values as you can see in the updated codepen: https://codepen.io/thimows/pen/WNmVyWb

Is it possible that this edge case is not accounted for?

**Comment by rosco54** [comment]
I did not specifically consider that edge case. There were plenty of other
edge cases that were caught though but I needed to get the main fixes out.
This update closed 7 or 8 additional issues as well. I will take a look at
this one ASAP.

**Comment by rosco54** [comment]
@junedchhipa @Thimows this issue exists in all revisions since at least 3.40.0, so I'm not treating it as high priority for me, although I will probably not be able to resist pushing further with it. Just don't expect a PR on this one from me.
