### ISSUE TITLE
series cannot update to more items than initialized with

### ISSUE THREAD

**Issue by rakeden** [apexcharts/apexcharts.js#428]
Given the following pen: https://codepen.io/lukasleitsch/pen/VRqWam
It is not possible to update the series with more items than it was initialized with 

```
this.series = [{...}]
this.series = [{...}, {...}] == ERROR
```

You can reproduce the bug in the codepen.

**Comment by lukasleitsch** [comment]
Sorry, but your fix doesn't solve our issue. In the codepen the function `replaceWithFourSeriesTypes` still does not work. I also added a function to remove all series from the graph. This function also not working.
