### ISSUE TITLE
Wish to have yaxis 0 tick always showing, but forceNiceScale does not seem to work properly with min/max values -1 < value < 1

### ISSUE THREAD

**Issue by ehbats** [apexcharts/apexcharts.js#4283]
### Description
Hello guys,

I am currently facing a problem where I can't force my chart to always have the 0 tick on the y-axis. I can't set my min to 0 because my series has negative values. I tried using forceNiceScale but it does not seem to solve my problem when i pass custom min/max values. With custom min/max values (that are -1 < value < 1) the 0 tick behavior looks random and I haven't found a way to consistenly make the 0 tick appear. I tried taking a look at https://github.com/apexcharts/apexcharts.js/issues/1771 but using annotation does not really solve my problem, and my problem is not solved by the OP's solution _probably_ because of my very small values series.

### Steps to Reproduce

1. Create a Bar Chart with a series that includes values that are  -1 < value < 1 (having negative values is important).
2. Use custom dataLabels formatting that shows the labels above the bar as this is the desired appearance for the user
3. Use forceNiceScale in attempt to always show the 0 tick on the yaxis
4. Pass custom min/max values to better show the dataLabels
5. Notice how yaxis 0 tick seems to only randomly appear depending on the values of min/max when these values are very small.
6. See codepen links at the end for more detailed reproduction 

### Expected Behavior
Consistent yaxis always showing the 0 tick when passing min/max values and forceNiceScale

### Actual Behavior
Yaxis seems to randomly show the 0 tick when I pass min/max values that are 0 < value < 1

### Screenshots
Yaxis 0 tick not showing when i pass small min/max values:
![image](https://github.com/apexcharts/apexcharts.js/assets/127566201/f16a0b30-9b40-44db-9dab-f6061429a149)

Without the min/max values the 0 tick shows up, but my datalabels formatting on the -0.08% series value gets messy:
![image](https://github.com/apexcharts/apexcharts.js/assets/127566201/546fbfc9-5cef-47e7-a84a-33b3c1fe8bdf)

### Reproduction Link
This codepen shows how the chart does not properly show the y-axis 0 tick when I pass min/max values that are 0 < value < 1:
https://codepen.io/Eduardo-Batistella/pen/xxexqOQ
You may change the values of min/max and see how the yaxis ticks behavior looks a bit random with such small values.

This other codepen shows how the chart (apparently) correctly formats the y axis with the 0 tick when i do not pass min/max values:
https://codepen.io/Eduardo-Batistella/pen/xxexqYe
However, this is not good enough for me as it messes with my dataLabels formatting on the -0.08% value. The bar hits the limit of the y-axis and my label undesirely goes inside the bar.

Can you guys help me fix this problem please? I've been trying to fix it for a while now and haven't found a solution

**Comment by rosco54** [comment]
By setting max: 0.11 and min: 0.1, you set the range (0.21), and this must be divided into even spacings. So you get either 7 divisions of 0.03 (most likely) or 3 divisions of 0.07 (unlikely), and neither of those land on zero.

You could try the following:

max: 0.12,
min: -0.1
which is guaranteed to produce divisions that land on zero (range 0.22 = 11 divisions of 0.02 spacing, or

max: 0.12,
min: -0.12,
which is almost guaranteed to land on zero, or

**Comment by ehbats** [comment]
@rosco54 Thanks a lot for your quick answer! These infos will sure help me out a lot trying to figure this out. I tried tweaking my code a little bit more and noticed that even when nor min or max are passed, some of my charts with small values still don't land on 0. Do you think it would be a nice feature to have some way of forcing the 0 to show up? I think it would make some charts a lot easier to read. In this case i misstagged my issue and I apologize, it should have been a feature request. But still, do you think that would be possible?

**Comment by rosco54** [comment]
Yes, it would be nice, and the unrestricted auto scaling generally does that. Indirectly though, as a side effect of how it does the scaling, so it's not 100% guaranteed even when no user-defined options are present. The solution in that case, may be to increase the margin space on the chart area so that you don't have to try to make allowance for it using min or max settings.

**Comment by rosco54** [comment]
@ehbats Would you be able to add one of those "charts with small values [that] still don't land on 0" to this issue? One of those that don't include min or max. I would like to see how that is happening and I can't seem to conjure up an example of my own that doesn't land on zero.
