### ISSUE TITLE
Certain stacked bar doesn't stack but overlaid on another series

### ISSUE THREAD

**Issue by whiztech** [apexcharts/apexcharts.js#4287]
### Description

Certain stacked bar doesn't stack but overlaid on another series in the same category.

### Expected Behavior

The bars stacked like the bars in other categories.

### Actual Behavior

The bars doesn't stack but instead overlaid on another series in the same category.

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/159569/22d11bf0-712f-44b3-a059-fc723bc5294d)

### Reproduction Link

https://codepen.io/whiztech/pen/zYXYpPM

Thank you.

**Comment by brianlagunas** [comment]
Your data series have different numbers of array lengths. They should all have the same length. 

<img width="235" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/835562/010f3a1b-1cab-43cd-8d55-bb135ddbb593">


<img width="1043" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/835562/d2780e73-3bc7-48cb-90a6-ac97df156437">
