### ISSUE TITLE
How to set datetime just one day

### ISSUE THREAD

**Issue by smemamian** [apexcharts/apexcharts.js#429]
## Codepen
I want to use this sample chart:
https://apexcharts.com/react-chart-demos/line-charts/zoomable-timeseries/

## Explanation
I want to set just one day and hours.

            xaxis: {
              type: 'datetime',
            },

but I don't know How I can to do this.  
can you show me a sample data of just one day and hours?

**Comment by junedchhipa** [comment]
```javascript 
    xaxis: {
        type: 'datetime',
        labels: {
          format: 'dd HH:mm'
        }
      }
```

**Comment by consciousnessdev** [comment]
> ## Codepen
> I want to use this sample chart:
> https://apexcharts.com/react-chart-demos/line-charts/zoomable-timeseries/
> 
> ## Explanation
> I want to set just one day and hours.
> 
> ```
>         xaxis: {
>           type: 'datetime',
>         },
> ```
> 
> but I don't know How I can to do this.
> can you show me a sample data of just one day and hours?

Can you give example of your data series? i need build like this chart, but still not found how to implement it :cry: 
![image](https://user-images.githubusercontent.com/30996656/124454522-cb520780-ddb2-11eb-97f1-2fd590f7f0a5.png)
