### ISSUE TITLE
Upgrade to 3.46.0 leads to not taking into account tickAmount in xaxis

### ISSUE THREAD

**Issue by SamuelHassine** [apexcharts/apexcharts.js#4296]
### Description

with xaxis => tickamount: 1.

In 3.45.2:

![image](https://github.com/apexcharts/apexcharts.js/assets/1334279/52e7d02f-8171-442a-a496-35d57e7ae9c3)

In 3.46.0:

![image](https://github.com/apexcharts/apexcharts.js/assets/1334279/fbaa8e7a-c364-4360-abfe-05e7ddf6bd6f)

**Comment by rosco54** [comment]
That is fixed in the repository already so you should see it in the next release.
