### ISSUE TITLE
Spark line chart appendData logs "dfsfgdgdgdf" and is not updating the chart

### ISSUE THREAD

**Issue by robinwassen** [apexcharts/apexcharts.js#43]
I took the spark1 from the spark line demo and tried to append data by adding the following:

```
setInterval(function() {
  spark1.appendData({
    data: [ 20 ]
  });
}, 300);
```

The data is not appended and 'dfsfgdgdgdf' is printed to the console every 300:th ms. Looking in the source code there is a random console log there: https://github.com/apexcharts/apexcharts.js/blob/8281a078618c8330f291305321b83fce6b74a192/src/modules/ZoomPanSelection.js#L203

**Comment by robinwassen** [comment]
In addition to that `appendData()` documentation is inconsistent: https://apexcharts.com/docs/methods/#appendData

Name | Type | Default | Description
-- | -- | -- | --
newData | Array | [ ] | The data array to append the existing series datasets

While the example suggest that you send an object to `appendData()`

**Comment by robinwassen** [comment]
The documentation for https://apexcharts.com/docs/methods/#updateSeries is also wrong

```
chart.updateSeries([
  data: [32, 44, 31, 41, 22]
])
```

The argument in the example is an array with a named key which is invalid javascript, it is supposed to be:

```
chart.updateSeries([{
  data: [32, 44, 31, 41, 22]
}])
```

updateSeries actually works for the spark lines though.

**Comment by junedchhipa** [comment]
Thanks for bringing this to attention.

The documentation was indeed wrong for the `updateSeries()` and `appendData()` method, and I updated it on the website.

Also, removed the random console.logs.

I will check the appendData() with sparklines

**Comment by junedchhipa** [comment]
The `appendData()` method works correctly with the updated doc. It was missing the array parenthesis.
The correct format would be this as updated in the website docs recently

```javascript
setInterval(function() {
      spark3.appendData([{
        data: [20]
      }]);
    }, 1000);
```
Here's the result

![sparkline-update](https://user-images.githubusercontent.com/17950663/44311501-581f3780-a406-11e8-90b0-d83cb9f70d7c.gif)

**Comment by robinwassen** [comment]
@junedchhipa Thank you for the quick response, this solves my issues! 👍
