### ISSUE TITLE
X-Axis type says that the library doesn't support functions for dynamically calculating min and max

### ISSUE THREAD

**Issue by IgorMaj** [apexcharts/apexcharts.js#4301]
### Description
As the title says, it seems that the types are out of sync with the actual library. The types say that x axis doesn't support `(val: number) => number` for `min` and `max` attributes,  but it does (which is very useful for my use case). 

### Steps to Reproduce

1.  Using Typescript and (optional) react wrapper, try passing a function for calculating min or max for XAxis, inside the options object
2. Watch Typescript compiler complain, due to type mismatch
3.  Suppress the errors/warnings and watch it work well when types are disregarded

### Expected Behavior
The types accurately represent what the library accepts
### Actual Behavior
Typescript complains when passing a function

**Comment by brianlagunas** [comment]
No reproduction link provided
