### ISSUE TITLE
Apply border radius for stacked bar chart only for last and first items

### ISSUE THREAD

**Issue by nembence** [apexcharts/apexcharts.js#4302]
## Summary
There should be a way to round the first and last elements of stacked bar charts. Currently, I can only apply border radius to either the last element or all elements in the stack. I aim to round only the first and last elements.

The same issue was mentioned earlier here as well: https://github.com/apexcharts/apexcharts.js/issues/4113

## API Changes

I would propose the same API change as mentioned in #4113 issue. In this way the library can support rounded border radiuses.

```
borderRadiusWhenStacked: "both",
```

## Intended Use Case

I would like to achieve somewhat similar for the bar chart:

<img width="824" alt="Screenshot 2024-03-05 at 14 29 36" src="https://github.com/apexcharts/apexcharts.js/assets/57453541/4ecc8e47-9019-4e94-8116-13e9823e52a5">

**Comment by junedchhipa** [comment]
duplicate of #4113
