### ISSUE TITLE
HeatMap Chart Not Support rgba / 8HEX To RGBA error

### ISSUE THREAD

**Issue by leejongheon42** [apexcharts/apexcharts.js#4316]
### Description
When using a HeatMap Chart, rgba not supported.

### Steps to Reproduce
// RGBA Error
const DEFAULT_HEAT_MAP_COLOR_SCALE = [
    "rgba(99, 70, 155, 0.2)",
    "rgba(99, 70, 155, 0.4)",
    "rgba(99, 70, 155, 0.6)",
    "rgba(99, 70, 155, 0.8)",
    "rgba(99, 70, 155, 1)",
];

plotOptions: {
                heatmap: {
                    colorScale: {
                        ranges: DEFAULT_HEAT_MAP_COLOR_SCALE.map((color, index) => {
                            return {
                                from: index * colorScaleChunkSize,
                                to: (index + 1) * colorScaleChunkSize,
                                color: color
                            }
                        })
                    }
                }
            },
// HEX8 Error
const DEFAULT_HEAT_MAP_COLOR_SCALE = [
    "#63469B33",
    "#63469B66",
    "#63469B99",
    "#63469BCC",
    "#63469B",
];

plotOptions: {
                heatmap: {
                    colorScale: {
                        ranges: DEFAULT_HEAT_MAP_COLOR_SCALE.map((color, index) => {
                            return {
                                from: index * colorScaleChunkSize,
                                to: (index + 1) * colorScaleChunkSize,
                                color: color
                            }
                        })
                    }
                }
            },
Error Message
 key: "hexToRgba",
      value: function () {
        var t = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : "#999999",
          e = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : .6;
        "#" !== t.substring(0, 1) && (t = "#999999");
        var i = t.replace("#", "");
        i = i.match(new RegExp("(.{" + i.length / 3 + "})", "g"));
        for (var a = 0; a < i.length; a++) i[a] = parseInt(1 === i[a].length ? i[a] + i[a] : i[a], 16);
        return void 0 !== e && i.push(e), "rgba(" + i.join(",") + ")";
      }
### Expected Behavior
it present RGBA color 
### Actual Behavior
Not Supported RGBA / Its present RGB color
### Screenshots
![image](https://github.com/apexcharts/apexcharts.js/assets/110795484/1e1e9e06-d5c8-4891-b99c-783d6ba662ca)
![image](https://github.com/apexcharts/apexcharts.js/assets/110795484/db0b5154-7a48-414d-a1e3-7cab779dd6a6)

**Comment by Felix-Pi** [comment]
push
