### ISSUE TITLE
Add ability to pin tooltip on click

### ISSUE THREAD

**Issue by nedelcu28** [apexcharts/apexcharts.js#4318]
## Summary

I think there should be an option to make the tooltip stick after a single click.

## API Changes

New tooltip properties "onClick": boolean and "pinOnClick:boolean or something similar

## Intended Use Case

Tooltip should show on click not just on hover. When using the chart in a scrollable container, its easier to have the tooltip show on click for example

**Comment by Dreamlinerm** [comment]
The tooltip should stick after a click, this option would be useful, I agree

**Comment by alerubis** [comment]
+1
