### ISSUE TITLE
xaxis hideOverlappingLabels has no effect

### ISSUE THREAD

**Issue by punkt2** [apexcharts/apexcharts.js#432]
## Codepen

https://codepen.io/punkt2/pen/bZzqmb

## Explanation

xaxis hideOverlappingLabels option has no effect. The labels still overlap.

**Comment by junedchhipa** [comment]
I need to mention in docs that it works only for datetime series currently, as there is a higher chance of overlap in timescale.

**Comment by jatindumka** [comment]
hi @punkt2  did u achive it in any way. Other than datetime  option.
