### ISSUE TITLE
Multiple-yaxis-scales , 3 series with 2 scales demo broken in 3.47.0 (JS)

### ISSUE THREAD

**Issue by LeoMcH36** [apexcharts/apexcharts.js#4323]
### Description

Any multi axis chart that has multiple yaxis with the same seriesName cause it to crash instead of showing like the 2nd demo at https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/, even this demo doesnt work using 3.47.0, works fine in 3.46.0

### Steps to Reproduce

1.  Create a multi axis chart, e.g the second example at https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/ 
2. use apexchart@3.47.0
3. have multiple elements in yaxis option with the same seriesName e.g "Column A" appears twice in the demo

### Expected Behavior
Chart with multiple series sharing singular y-axis on left hand side displays like the demo
### Actual Behavior
chart does not display, bar the labels at the bottom, crashes with error " Cannot read properties of undefined (reading 'result')"
### Screenshots
error
![image](https://github.com/apexcharts/apexcharts.js/assets/57542982/07b39009-cf28-43b8-ab37-dad29b12daf0)
using apexcharts@3.46.0
![image](https://github.com/apexcharts/apexcharts.js/assets/57542982/c3dfef71-25ea-4c3d-b530-e0b7c08c053b)
using apexcharts@3.47.0
![image](https://github.com/apexcharts/apexcharts.js/assets/57542982/0d45db47-0ec3-4cbc-920f-03e7766b7d1d)

### Reproduction Link
https://codepen.io/rogueDovah/pen/eYozBLE

**Comment by abscolo77** [comment]
Same here.

In the meantime I solved this by blocking to the previous version

  <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.46"></script>

**Comment by rosco54** [comment]
Compatibility with existing charts needs to be fixed and I will look at this.

The solution is to use seriesName with an array (as of 3.47.0). Eg, to fix the demo, replace the existing yaxis array (three axes) with the following (two axes):

  yaxis: [
    {
      seriesName: ['Column A', 'Column B'],
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
      },
      title: {
        text: "Columns"
      }
    }, {
      opposite: true,
      seriesName: 'Line C',
      axisTicks: {
        show: true
      },
      axisBorder: {
        show: true,
      },
      title: {
        text: "Line"
      }
    }
  ],

With this, 3.47.0 will work, and you will also see that collapsing Column A no longer causes it's Y axis to hide prematurely while Column B is still visible.

The documentation and the demo needs to be updated.

Briefly: if you want two axes just define two axes, not three with one not shown. Then use seriesName: [] to reference all the series' that will reference it. You can still use seriesName with a string, or let ApexCharts distribute series. As a default, if you don't use seriesName in any yaxis it will distribute each series to each yaxis one for one, with any left over series referenced to the last yaxis.

**Comment by LeoMcH36** [comment]
Thanks, This approach also seems to have fixed the huge performance drop when toggling legends on this type of chart
