### ISSUE TITLE
Brush style

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#433]
Hi,
Is it possible to get a brush selection with the same style as in the following image :
![image](https://user-images.githubusercontent.com/46166884/54872644-7cd9f400-4dc7-11e9-8481-635c16c39cd5.png)

This image comes from https://apexcharts.com/features/
I didn't find any way to set a brush without a chart

Thanks

**Comment by junedchhipa** [comment]
The `scroller` was available prior to v2.0.0 but was removed due to buggy behavior and memory leaks.
Maybe, it will be added again in the future.

**Comment by jlil** [comment]
+1
any chance this can be revisited?
