### ISSUE TITLE
Touch support for onMouseMove event Broken

### ISSUE THREAD

**Issue by zee0786** [apexcharts/apexcharts.js#4330]
### Steps to Reproduce

1. Create a graph and open browser dev console with mobile view.
2. Try dragging graph crosshair across the data points

### Expected Behavior
the cross hairs should move 

### Actual Behavior
the cross hairs just crash and disappear when dragged

### Screenshots

working in 3.46.0 but broken in version 3.47.0

**Comment by brianlagunas** [comment]
This is why we require reproduction links. There could be something small like a single property that causes the issue that isn't being considered when someone tries to guess at how to replicate it. Closing until a reproduction link has been provided.

**Comment by zee0786** [comment]
Can you please try the following link 

https://ab0a-167-23-125-13.ngrok-free.app/

**Comment by zee0786** [comment]
@brianlagunas Hi, Do we have any update on this?

**Comment by zee0786** [comment]
Hi @rosco54 Can you please look into this. 
I'm not able to upgrade my version due to this broken change.

**Comment by rosco54** [comment]
I could not get your playcode link to work but there's an obvious suspect commit ([0419bb5](https://github.com/apexcharts/apexcharts.js/commit/0419bb51618ddff89a3a7a722a4143cbdb84fcd4)) that went into 3.47.0 that @junedchhipa might be able to look at.

**Comment by zee0786** [comment]
@rosco54 I have fixed the link. You may retry now


> I could not get your playcode link to work but there's an obvious suspect commit ([0419bb5](https://github.com/apexcharts/apexcharts.js/commit/0419bb51618ddff89a3a7a722a4143cbdb84fcd4)) that went into 3.47.0 that @junedchhipa might be able to look at.
> 
> PS. "Obvious" only because it matches keywords in the title of this report.
> 
> I also submitted a commit to 3.47.0 ([6a300a5](https://github.com/apexcharts/apexcharts.js/commit/6a300a50ef5cdd47cd069b9ee1cb31117d655efc)) that affects event listeners. It is in svg.js and was to fix an issue: from the commit message, `This change exposed the disableDefault in passive event listener common issue, which was resolved by setting "passive: false" in svg.js.`

**Comment by rosco54** [comment]
I get a chart now but it has only two points very close together. What are
we looking for that demonstrates the issue? How do I change the ApexCharts
version to compare. (I'm not familiar with REACT at all.)

**Comment by rosco54** [comment]
I have done as you describe in Chrome developer in mobile mode as well as
using an actual mobile phone (Samsung Galaxy S22 Ultra).  I see the same
behaviour on both playcode links.

In Chrome I click-drag the mouse and the crosshair moves between the two
points and does not disappear.

On my phone I use the stylus pen to pass over the points without making
contact with the screen and the crosshair appears then moves from one point
to the other and then stays on that point after moving the pen away from
the screen.

If I touch the screen with the pen or finger, the crosshair appears as if
the point is tapped then disappears if I drag to the other point.

I can't tell if this is correct behaviour or not but I don't see any
difference between the two versions of ApexCharts on either device.

**Comment by zee0786** [comment]
It is possibly because playcode is unable to keep different versions in different projects under one userid (possibly a bug with playcode). Hence it do not loads the dependencies on again on reload and picks from the browser storage possibly. (I found it in dev console's sources in apexcharts.common.js file). I cleared the application data and reloaded https://playcode.io/1840192
Hence now I can see apexcharts.common.js version again to 3.49.0. you may retry now.

**Comment by rosco54** [comment]
I see this at the top of apexcharts.common.js (after clearing out my browser cache as well):

```/*!
 * ApexCharts v3.46.0
 * (c) 2018-2024 ApexCharts
 * Released under the MIT License.
 */```

I will take your ApexCharts config from Area.js and try to run it from a vanilla html file, without all the playcode/REACT wrapping. But that's what I did previously IIRC.

**Comment by rosco54** [comment]
Apparently clearing the cache isn't enough, so an entirely new browser did the trick. The version is:

```
/*!
 * ApexCharts v3.49.0
 * (c) 2018-2024 ApexCharts
 * Released under the MIT License.
 */
```

In short, you're setting the wrong month in App.jsx:

```
  const graphValueChange = (z) => {setSelectedGraphValue(z)};
  useEffect(() => {
    setIsMounted(true);
    setTimeout(
      () =>
        setGraphData([
          { x: new Date("2024-04-09T18:30:00.000Z"), y: 35 },
          { x: new Date("2024-04-10T18:30:00.000Z"), y: 30 }
        ]),
      2000
    );
  }, []);
```

It should be:

```
  const graphValueChange = (z) => {setSelectedGraphValue(z)};
  useEffect(() => {
    setIsMounted(true);
    setTimeout(
      () =>
        setGraphData([
          { x: new Date("2024-05-09T18:30:00.000Z"), y: 35 },
          { x: new Date("2024-05-10T18:30:00.000Z"), y: 30 }
        ]),
      2000
    );
  }, []);
```

With that change it works just as it does it 3.46.0.

![Two points](https://github.com/apexcharts/apexcharts.js/assets/159597299/53a9efba-8183-419b-a5fd-8f69590eb4df)

**Comment by zee0786** [comment]
I agree the data belongs to the last month when I actually posted this bug. Apparently my issue is not related to display the markers. Instead my issue is it doesn't display the tooltip(with cross hairs) when the touch is dragged on the graph across the markers.The touch click is functional, but the touch move is not functional.

**Comment by rosco54** [comment]
Click drag did not work for me in either 3.46.0 or 3.49.0. I just don't see
any difference between the two versions.

**Comment by rosco54** [comment]
OK. I've reduced your example to the following html that I can run and debug and switch to different apexchart versions.

I can see the difference.

```
<!DOCTYPE html>
<html lang="en">

<head>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.46.0"></script>

</head>

<body>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10">
        <div id="chart"></div>
      </div>
    </div>
  </div>

  <script>

    const color = "#3c9d47";
    let options = {
    series: [{
            name: "Weight",
            type: "line",
            data: [[1715824799500, 35],[1716092639400, 30]]
        }],
        chart: {
            id: "chart",
            type: "line",
            foreColor: color,
            toolbar: {
                autoSelected: "pan",
                show: false
            },
        },
        colors: [color],
        dataLabels: {
            enabled: false
        },
        markers: {
            size: 3,
            strokeWidth: 1,
        },
        xaxis: {
            type: "datetime",
            min: 1715824799500 - 100000000,
            max: 1716092639400 + 100000000,
            tooltip: {
                enabled: true,
                offsetY: 0
            },
            labels: {
                show: true,
                formatter: (value) => new Date(value).getTime()
            }
        },
        yaxis: {
            min: 0,
            tickAmount: 3
        }
    };

    var chart = new ApexCharts(document.querySelector("#chart"), options);

    chart.render();

  </script>

</body>

</html>
```

**Comment by rosco54** [comment]
@junedchhipa @zee0786 @sama3926 Building 3.49.0 with commit ([0419bb5](https://github.com/apexcharts/apexcharts.js/commit/0419bb51618ddff89a3a7a722a4143cbdb84fcd4)) backed out restores the 3.46.0 behaviour, fixing this issue. I've referenced this back to @sama3936 as the author of the pull request #4240 that introduced this commit.

**Comment by zee0786** [comment]
@rosco54 Can you please mention here, when can I expect this to be fixed if it has been addressed at your end.

**Comment by rosco54** [comment]
@junedchhipa @sama3926 the description in pull request #4240 suggests that the associated commit ([0419bb5](https://github.com/apexcharts/apexcharts.js/commit/0419bb51618ddff89a3a7a722a4143cbdb84fcd4)) could be a workaround rather than a root-cause fix. It has broken previously relied upon functionality and to be fair should probably be reverted until it can be reviewed.

**Comment by junedchhipa** [comment]
Reverted PR #4240 with #4462 which should fix this issue
