### ISSUE TITLE
plotOptions.bar.barHeight doesn't work at all

### ISSUE THREAD

**Issue by mholt** [apexcharts/apexcharts.js#4335]
### Steps to Reproduce

1. Create a bar chart
2. Set `barHeight: '100%'`, or `barHeight: '1%'` (in plotOptions -> bar), nothing changes

### Expected Behavior

The bars should take the full height of the chart/grid area when set to 100%.

### Actual Behavior

The bar height doesn't change.

### Screenshots

Without `barHeight: '100%'`:

![image](https://github.com/apexcharts/apexcharts.js/assets/1128849/bd3a90e3-c7ee-4ec5-bd26-0ce801dec5c2)

With `barHeight: '100%'`:

![image](https://github.com/apexcharts/apexcharts.js/assets/1128849/64dabad1-64a4-4cbc-bd5f-668c5308f452)

### Reproduction Link

I don't have a CodePen account but paste this into the JS and you'll see what I mean:

```
const data = [{"x":"unknown","y":1},{"x":"message","y":88923},{"x":"social","y":16767},{"x":"location","y":120122},{"x":"media","y":1781}];

var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "bar"
  },
  series: [
    {
      name: "Series 1",
      data: data
    }
  ],
  plotOptions: {
    bar: {
      barHeight: '100%'
    }
  },
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```

**Comment by brianlagunas** [comment]
As mentioned in the docs: https://apexcharts.com/docs/options/plotoptions/bar/#barHeight

```
In horizontal bar charts, barHeight is the percentage of the available height in the grid-rect.
Accepts ‘0%’ to ‘100%’
```

**Comment by mholt** [comment]
I've read the docs, thanks. Can you help me understand why the bar does not in fact reach 100% height then?

**Comment by mholt** [comment]
This is just a horizontal bar chart right? On its side? Column charts are the same thing
