### ISSUE TITLE
xaxis rotate is invaild

### ISSUE THREAD

**Issue by JACK123wang** [apexcharts/apexcharts.js#434]
linechart  xaxis rotate is invaild,but yaxis is fine 
And xaxis tickPlacement: 'on' is also invaild,I had checked that the type of xaxis is category

**Comment by junedchhipa** [comment]
Can you please create a codepen?

**Comment by junedchhipa** [comment]
```javascript
xaxis: {
    labels: {
        rotate: -45,
        rotateAlways: true,
    }
}
```

**Comment by JACK123wang** [comment]
Thank you for your answer
code:
					  xaxis: {
						type: 'category',
						labels: {
						    rotate: -45,
							rotateAlways: true,
							style: {
								colors: "#ffffff",
								fontSize: '11px',
							},
						},
						axisBorder: {
							show: true,
							color: '#ffffff',
							height: 1,
							width: '100%',
							offsetX: 0,
							offsetY: 0
						},
						axisTicks: {
							show: true,
							borderType: 'solid',
							color: '#78909C',
							height:6,
						},
						tickAmount: count,	
						tickPlacement: 'on',			
					  },
However,it is not work.
Please help another problem that xaxis tickPlacement: 'on' is  invaild. 
Thank you!

![擷取](https://user-images.githubusercontent.com/47593069/54881178-39938a00-4e88-11e9-89e6-24e9d12f247b.PNG)

**Comment by junedchhipa** [comment]
Please create a codepen demo so I can reproduce.

**Comment by JACK123wang** [comment]
https://codepen.io/loldecqp/pen/qvgJmJ 
right?
css is style.css

**Comment by junedchhipa** [comment]
No, it doesn't work.
If you have problems with codepen, try this codesandbox template - https://codesandbox.io/s/pwwz8009n0

**Comment by JACK123wang** [comment]
https://codepen.io/loldecqp/project/editor/Xbwrbr
sorry, I check this codepen working.

**Comment by junedchhipa** [comment]
Thanks, I will look into the issue soon.

**Comment by junedchhipa** [comment]
When you initially push data into series, don't pass a blank string in "x" prop or else it will result in issues.

Please do this
```javascript
for(var i=0; i<count ;i++){
  lineData.push({
    x: getTime(),
    y: "0"
  })
}
```
