### ISSUE TITLE
zoom does not work in combination with logarithmic yaxis with more than one series

### ISSUE THREAD

**Issue by ms20de** [apexcharts/apexcharts.js#4344]
### Description

Zooming seems to be broken with logarithmic scaling.

### Steps to Reproduce

1. More than one series
2. Use yAxis for both series, happens automatically or via new seriesName Array
3. Set yAxis to logarithmic = true
4. Try to zoom by selecting area with mouse

### Expected Behavior

Zooming to selected area as normal

### Actual Behavior

Selected area is show, than freeze with exception in console:
apexcharts:6 Uncaught TypeError: Cannot read properties of undefined (reading 'niceMax')
    at apexcharts:6:246152
    at Array.forEach (<anonymous>)
    at i.value (apexcharts:6:246061)
    at i.value (apexcharts:6:240941)

Firefox: Selection can not be finished
Chrome: Freeze

Works if logarithmic is not set.

### Screenshots

Freeze after selection is finished.
![image](https://github.com/apexcharts/apexcharts.js/assets/57409043/62e48981-e614-4c19-9233-74c07d6d931e)

### Reproduction Link

https://codepen.io/ms20de/pen/LYvWgyV

**Comment by rosco54** [comment]
This is fixed in yesterdays pull request #4341, in response to issue #4340.
Apologies for not catching it in the initial versions of the seriesName-as-an-array feature. Zooming works in 3.48.0 with the traditional seriesName-as-a-string-only style.
