### ISSUE TITLE
There is a bug in ApexCharts v3.48.0

### ISSUE THREAD

**Issue by fox-15** [apexcharts/apexcharts.js#4346]
Hello!
There is an error in ApexCharts v3.48.0, the tooltip stopped working:
Uncaught ReferenceError: anno is not defined
  at t.value (apexcharts.min.js?v=-cagC7gYBHDzF6s5VmZnJFj3CZZYAb3ofFP6Qdv7k7E:6:279551)
  at t.value (apexcharts.min.js?v=-cagC7gYBHDzF6s5VmZnJFj3CZZYAb3ofFP6Qdv7k7E:6:289939)
  at t.value (apexcharts.min.js?v=-cagC7gYBHDzF6s5VmZnJFj3CZZYAb3ofFP6Qdv7k7E:6:288108)
  at t.value (apexcharts.min.js?v=-cagC7gYBHDzF6s5VmZnJFj3CZZYAb3ofFP6Qdv7k7E:6:287557)
  at apexcharts.min.js?v=-cagC7gYBHDzF6s5VmZnJFj3CZZYAb3ofFP6Qdv7k7E:6:286907

ApexCharts v3.40.0 worked without errors

**Comment by brianlagunas** [comment]
There is no repro step or required repro link provided.

**Comment by fox-15** [comment]
Version: ApexCharts v3.40.0
![image](https://github.com/apexcharts/apexcharts.js/assets/50137222/1f6db623-9697-4acb-978e-417e87fa1937)

Version: ApexCharts v3.48.0
![image](https://github.com/apexcharts/apexcharts.js/assets/50137222/00314ee9-69aa-4253-948b-1f7155757907)

**Comment by fox-15** [comment]
Sorry!

ApexCharts v3.48.0
![image](https://github.com/apexcharts/apexcharts.js/assets/50137222/be34098e-23fa-437b-a961-37a3e7f71dd9)

ApexCharts v3.40.0
![image](https://github.com/apexcharts/apexcharts.js/assets/50137222/83a95a6d-1e2c-4d85-9901-a61e519ee6f2)

**Comment by ccppoo** [comment]
@brianlagunas 

> There is no repro step or required repro link provided.

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/tooltip/AxesTooltip.js#L175

cannot find keyword `anno` used nor created looks like a typo
