### ISSUE TITLE
Version 3.48 breaks yaxis annotations when yaxis is hidden

### ISSUE THREAD

**Issue by DannyBen** [apexcharts/apexcharts.js#4349]
### Steps to Reproduce

1. Copy the below HTML (or see the codepen)
2. Open it in a browser, see that annotations are not displayed
3. Change the version to 3.47.0 - and see that annotations are working again
4. The culprit seems to be `yaxis: { show: false }` - in version 3.47, it did not cause the hiding of the annotations, but in 3.48 it does.

<details>
  <summary>Show HTML</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <title>General Settings</title>
    <link crossorigin="" href="https://fonts.googleapis.com" rel="preconnect" />
    
    <!-- Version 3.47.0 works / 3.48 fails -->
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.48.0"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
  </head>
  <body>
    <div style='height:90vh' id="chart"></div>
    <script>
      var series = [{"name":"Test","data":[["2024-02-21",130.56],["2024-02-22",130.73],["2024-02-23",130.73],["2024-02-24",130.73],["2024-02-25",130.85],["2024-02-26",131.0],["2024-02-27",131.0],["2024-02-28",130.44],["2024-02-29",130.39],["2024-03-01",130.39],["2024-03-02",130.39],["2024-03-03",130.94],["2024-03-04",131.18],["2024-03-05",131.49],["2024-03-06",131.67],["2024-03-07",131.81],["2024-03-08",131.81],["2024-03-09",131.81],["2024-03-10",131.72],["2024-03-11",131.86],["2024-03-12",132.21],["2024-03-13",132.18],["2024-03-14",132.02],["2024-03-15",132.02],["2024-03-16",132.02],["2024-03-17",132.18],["2024-03-18",132.49],["2024-03-19",132.44],["2024-03-20",132.97],["2024-03-21",133.1]]}]
      var id = "chart"
    </script>
    <script>
      (function() {
        $(function() {
          var chart, options;
          options = {
            series: series,
            chart: {
              animations: { enabled: false },
              type: 'area',
              height: '98%',
            },
            dataLabels: { enabled: false },
            markers: { size: 0 },
            xaxis: { type: 'datetime' },
            
            // yaxis annotations are hidden when yaxis is hidden 
            // this was not the case before 3.48.0
            yaxis: { show: false },

            annotations: {
              yaxis: [
                {
                  y: 133.1, 
                  borderColor: "#111111",
                  label: {
                    offsetX: 10,
                    position: "left",
                    textAnchor: "start",
                    borderColor: "#111111",
                    text: "Last"
                  }
                }
              ]
            }
          };
          chart = new ApexCharts(document.getElementById(id), options);
          return chart.render();
        });
      
      }).call(this);
      
    </script>
  </body>
</html>
```
</details>

### Expected Behavior

`yaxis` annotations should be visible even when `yaxis.show` is `false`.

### Actual Behavior

`yaxis` annotations are not visible when `yaxis.show` is `false`.

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/2405099/cb1a77d4-075c-4e6d-a96f-de398c9dec9d)

### Reproduction Link

https://codepen.io/Danny-Ben-Shitrit/pen/GRLmoep

**Comment by rosco54** [comment]
This was my change but I actually wasn't aware that axis annotations could be bound to series, so it needs to be revisited.

**Comment by rosco54** [comment]
@junedchhipa @DannyBen  Could you review the comments and alternative solution please and re-assess this issue's bug status. Thanks.

**Comment by DannyBen** [comment]
> PPS. Rather than yaxis.show: false, why not:
> 
> ```
> yaxis: {
>   floating: true,
>   labels: {
>     show: false
>   }
> }
> ```

I am confused by the difference between `yaxis.labels.show` and `yaxis.show`.

From user perspective, I do not see the relation between `yaxis.show = false` and the fact that the horizontal annotations are hidden. The way it behaved up until 3.47 was intuitive to me and reflects what I want to do: Hide the yaxis completely, and show horizontal annotations.

That said, using `yaxis.labels.show = false` instead of `yaxis.show = false` brings back the horizontal annotations.

**Comment by rosco54** [comment]
Historically, a yaxis[n] is hidden when the series[n] bound to it is collapsed via the legend etc. Internally, this is done by setting yaxis[n].show = false. The effect has been, and remains, that the chart is redrawn and rescaled. The annotations that reference the hidden yaxis[n] and the hidden series bound to it therefore will usually no longer be useful.

I agree, for your example it was useful and entirely intuitive because it worked, but it is positively unhelpful in other cases. Version 3.48.0 has changed the purpose of yaxis.show slightly to solve a number of other problems.

**Comment by DannyBen** [comment]
So, the only way to get the exact same thing that `yaxis.show = false` did before, is to use both `yaxis.labels.show = false` AND `yaxis.floating = true`? Is it weird only to me? I mean, The `floating` declaration seems "internal" - I don't want it to "float", I want it to not be there, and not occupy the several empty pixels it does without `floating = true`.

I would understand if `yaxis.labels.show = false` in 3.48 would replace `yaxis.show = false` - the `floating` bit does not sit right with me, especially since this is a common use case.

**Comment by junedchhipa** [comment]
@DannyBen There has been breaking changes with the last couple of releases to improve y-axis scales. Some downsides of those improvements are some of the things which you encountered.
In my opinion, I would expect the yaxis to be present to make the yaxis annotations work. If it is not present, the alternative provided by @rosco54 to hide yaxis.labels is a good workaround.

I will have to update the docs on the website to let the users know that in case of yaxis annotations, yaxis has to be shown. Otherwise, they can hide the labels with `yaxis.labels.show`

**Comment by DannyBen** [comment]
> Otherwise, they can hide the labels with yaxis.labels.show

That is perfectly acceptable. But can this setting be made to completely hide, without needing to add the `floating: true` bit?
Currently, not adding `floating: true`, means you get a larger white space margin where the axis is supposed to be.

If it is a problem, then I guess it will have to do as you know the code and the advantages of the new way better than I do.

**Comment by rosco54** [comment]
```yaxis.labels.show``` is only intended to hide the labels, so no, it
can't completely hide the whole axis.

I think there is a proper solution that will resolve this without users
having to make changes. So please put documentation changes in hold.

**Comment by rosco54** [comment]
@junedchhipa @DannyBen proposed change in logic:

Y axis annotations will be hidden only when:
the axis is hidden AND all series associated with the yaxis are collapsed.

Note: this is not supposed to be a feature or bug fix. It's specifically for backward compatibility. I'd also just note, there is no ```xaxis.show``` property and the only way hide the xaxis is by using ```xaxis.floating: true```. So, the alternative method suggested earlier is at least consistent with how you would achieve the same effect there.

Only Y axis annotations need to be treated this way. X axis annotations are always visible except when zoomed and panned away from view, and point annotations explicitly associate with both a yaxis and a series and are hidden when the series is collapsed.

Push request to follow, which also includes some refinements on previous merges to fill some gaps. See the commit comments in the PR for details.

**Comment by DannyBen** [comment]
I am not sure what will be the end result, so I will wait until it is resolved either way.

> there is no `xaxis.show` property and the only way hide the xaxis is by using `xaxis.floating: true`

The use of `floating` in general, and especially when using its side effect to hide the element, is a low level detail. From user perspective - if I may attempt to represent it - it is far from ideal, especially given the otherwise intuitive JSON structure of the library.

**Comment by rosco54** [comment]
Just pointing out that consistency is important and usually by design. If you find inconsistency, it usually suggests the designers have not intended it to be used a certain way, even if it happens to work.
