### ISSUE TITLE
Safari: trying to resize chart with ResizeObserver on parent element

### ISSUE THREAD

**Issue by Skrypt** [apexcharts/apexcharts.js#4350]
### Description

Using ApexChart with Vue 3. We are resizing the chart when the parent element is resizing with a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). It works on all other browsers but on Safari where when we resize the browser it will log an exception on the Safari dev console.

TypeError: null is not an object (evaluating 'a.gridRect.getBoundingClientRect')

Maybe related to: https://github.com/apexcharts/apexcharts.js/issues/3040

### Expected Behavior

The chart should resize.

### Actual Behavior

The chart does not resize.

### Screenshots

<img width="1008" alt="Capture d’écran, le 2024-03-22 à 11 37 08" src="https://github.com/apexcharts/apexcharts.js/assets/3228637/ff820f08-9cc5-48bf-89e5-f01439c74c3b">

**Comment by brianlagunas** [comment]
Please provide a reproduction app or this will be closed

**Comment by Skrypt** [comment]
Ok, will try to find the time.
