### ISSUE TITLE
unknwon reference causing AxesTooltip functionality

### ISSUE THREAD

**Issue by ccppoo** [apexcharts/apexcharts.js#4353]
@brianlagunas 

> There is no repro step or required repro link provided.

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/tooltip/AxesTooltip.js#L175

cannot find keyword `anno` used nor created looks like a typo

_Originally posted by @ccppoo in https://github.com/apexcharts/apexcharts.js/issues/4346#issuecomment-2016444575_

version : 3.48.0

# default (annotation on)

![image](https://github.com/apexcharts/apexcharts.js/assets/46418312/c5dac999-a300-4b8c-912e-f98cb088a1c8)

edit) reason why it was tricky to find 

this reference error is raised because `anno` isn't binded to `this`, 

so when building package, webpack automaticaly binded `anno` to `this`

variable name `anno` is in a function scope, and its value are passed by values

so it was impossible to traceback finding `this.anno` via search because there was no such code like that

# tooltip option off

![image](https://github.com/apexcharts/apexcharts.js/assets/46418312/c43ed3b0-aa85-4dc4-acb7-72ed1c5c2ea8)

**Comment by ccppoo** [comment]
passing reference of *anno* starting from

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/annotations/Annotations.js#L246

then

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/annotations/Annotations.js#L253

then

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/annotations/Annotations.js#L91-L93

which is created from

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/annotations/Annotations.js#L26

and

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/annotations/YAxisAnnotations.js#L4-L12


the problem 'AxesTooltip' instance is created as attribute of `class Tooltip`

https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/tooltip/Tooltip.js#L30

Tooltip is use at

**Comment by ccppoo** [comment]
https://github.com/apexcharts/apexcharts.js/blob/e03e8cbab71b1da386b5e73dbfb759360f1928f9/src/modules/tooltip/AxesTooltip.js#L173-L176

fixing like this works as I expected

```js
      let seriesIndex = w.globals.seriesYAxisMap[index][0]
```

@rosco54 could you check that it works as you intended?

**Comment by rosco54** [comment]
If index is the yaxis index then your fix odds probably correct, but I
would like to check it on context of the calling code and test, in the
morning my time, in about 8 hours.

Yes, a sloppy cut and paste most likely.

**Comment by ccppoo** [comment]
@rosco54 Thanks!
