### ISSUE TITLE
Multi-series color support for stroke in bar charts

### ISSUE THREAD

**Issue by Digvijayrao-KF** [apexcharts/apexcharts.js#4360]
## Summary

Multi-series color support for stroke in bar charts

## Intended Use Case

Similar to a functional support provided for **colors** (ref: [link](https://apexcharts.com/docs/options/colors/)) need to utilize the same for applying _**stroke** **colors**_ via a function.

**Requirement**:
> For 2nd series, I need to apply border colors to the paths/bar based on values driven on y-axis
![image](https://github.com/apexcharts/react-apexcharts/assets/104560649/cfb7f601-f766-4672-869f-029b2802a35d)

**Usage**:
> Have been trying this code for the same. (seriesIndex & value is required to apply the logic)

```
stroke: {
    show: true,
    width: 2,
    colors: [
      function ({ value, seriesIndex, w }) {
        if (seriesIndex == 1) value < 3.6 ? "#54A0FF" : "#FFC759";
      },
    ],
    dashArray: 0,
 } 
```
> Package versions used
```
"apexcharts": "3.45.2",
"react-apexcharts": "^1.4.1",
"react": "^17.0.2",
```
**Discussions**:
> Older [ref-2813](https://github.com/apexcharts/apexcharts.js/discussions/2813)

**Comment by junedchhipa** [comment]
fixed with #4374
