### ISSUE TITLE
Y axis not printed propelly when downloading the chart is zoomed view

### ISSUE THREAD

**Issue by solomonsolo123** [apexcharts/apexcharts.js#4362]
### Steps to Reproduce

1. Zoom on bar chart 
2. Download CSV from the menu
3. only zoomed labels is shown

### Expected Behavior

It should print full X Axis or Y Axis value even when zoom or show the X & Y Axis till the value its zoomed

### Actual Behavior

its opposite of the Expected Behavior 

### Screenshots
this issue can be easily reproduced

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
