### ISSUE TITLE
Customize multiple radial bars

### ISSUE THREAD

**Issue by charlieboygis** [apexcharts/apexcharts.js#437]
Thank you for this beautiful piece of code.
I'm trying to render a multple radial bars chart with and additional (svg or png) icon sticked to the end of the svg path of every serie.
Some like that:
![graph002](https://user-images.githubusercontent.com/1856828/54922932-7489d200-4f09-11e9-974c-0132e0b86a6b.png)
![graph001](https://user-images.githubusercontent.com/1856828/54922934-7489d200-4f09-11e9-9d5f-6d2674f13558.png)

Any suggestion?
Thank  you.

**Comment by junedchhipa** [comment]
Sorry, this is not achievable currently with ApexCharts.
There are examples to place images in the center, but drawing images on the SVG paths is not implemented.

**Comment by samuelba** [comment]
Why is this closed? I think this is an interesting feature request, could use it myself.
