### ISSUE TITLE
Donut chart Total

### ISSUE THREAD

**Issue by fr4nk3nst3in** [apexcharts/apexcharts.js#4370]
## Summary

It would be nice to split the total label in the label/name and this value. The purpose is to use the total value alone without the label/name. The Value should be centered in the middle of donut. 

## Intended Use Case

Use the total value as Big Numbers without the label. Like:

<img width="540" alt="donut-big-number" src="https://github.com/apexcharts/apexcharts.js/assets/4451184/0fd51bb1-0211-439c-8e1d-ca3982135297">

**Comment by halfpeeled** [comment]
Hello! I think I may have a simple working solution to this that I will submit a PR for soon, if this issue is still up for grabs. Thanks!

**Comment by fr4nk3nst3in** [comment]
@halfpeeled @junedchhipa First of all thank for the implementation of feature. I have question about documentation of this feature where I have to put the `hideLabel:true`. As I seen that this feature has been released in 3.54.0.

**Comment by junedchhipa** [comment]
You have to set the total label as empty string
```
options = {
  plotOptions: {
    radialBar: {
      dataLabels: {
        total: {
          label: ""
        }
      }
    }
  }
}
```

**Comment by fr4nk3nst3in** [comment]
Thanks
