### ISSUE TITLE
Setting yaxis min breaks in radar chart

### ISSUE THREAD

**Issue by RobertAndreiGit** [apexcharts/apexcharts.js#4371]
### Steps to Reproduce

1. Set chart to type 'radar'
2. Set `config.yaxis.min` value to 1
3. Add a series with values from 1 to 5

### Expected Behavior
Value of 1 will be found at the center of the radar, at 1.

### Actual Behavior
1 is found at 3, while 4 and 5 are outside the radar

### Screenshots
![Screenshot 2024-03-31 at 23 37 13](https://github.com/apexcharts/apexcharts.js/assets/49405795/c8437eb4-eb7d-45dc-897e-f949ca84e9b3)

### Reproduction Link
https://codepen.io/robertandreigit/pen/rNbYePp

**Comment by rosco54** [comment]
It seems to have broken going from version 3.11.2 to 3.11.3.

**Comment by RobertAndreiGit** [comment]
On 3.11.2 the behaviour is still different than I'd expect. When yaxis min is set to 1, having a value of 0 in the series is displayed in the center, and a value of 1 is somewhere between 1 and 2. Although 5 is displayed where it should be if that helps.
![Screenshot 2024-04-01 at 13 55 54](https://github.com/apexcharts/apexcharts.js/assets/49405795/61483a49-ab31-4def-8b47-ef1af3fe6f1f)
