### ISSUE TITLE
In the new version, null values no longer allow generating a linear graph

### ISSUE THREAD

**Issue by andresagab** [apexcharts/apexcharts.js#4377]
When you generate a line chart with null values, the chart stops working after the second series:

![imagen](https://github.com/apexcharts/apexcharts.js/assets/31632737/cdd87554-3f57-4f51-90f9-893f94482ff5)

data:

![imagen](https://github.com/apexcharts/apexcharts.js/assets/31632737/65662abb-4a15-42ba-a4e8-dbed55afb1cb)

### Discussed in https://github.com/apexcharts/apexcharts.js/discussions/4354

<div type='discussions-op-text'>

<sup>Originally posted by **reubenfirmin** March 23, 2024</sup>
Is there a setting in area charts that lets me "bridge" a line across null values? Ideally I could style the bridge differently, e.g. as a dashed line.</div>

**Comment by brianlagunas** [comment]
Did it follow bug template instructions.
