### ISSUE TITLE
Data series that starts with null isn't displayed correctly on v3.48

### ISSUE THREAD

**Issue by Raraby** [apexcharts/apexcharts.js#4388]
### Steps to Reproduce

1. Make a data series that starts with null

### Expected Behavior
On v3.47.0, all lines are displayed correctly.
https://raraby.github.io/apexcharts_bug_report/v3.47.0/
![image](https://github.com/apexcharts/apexcharts.js/assets/58139133/8298aad0-c83e-40fc-a977-ac80fc70c33b)
This time, the yellow line starts with null.
[null, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
### Actual Behavior
On v3.48.0, the latest version, yellow line vanished.
https://raraby.github.io/apexcharts_bug_report/v3.48.0/
![image](https://github.com/apexcharts/apexcharts.js/assets/58139133/3ea78b6b-5ed9-46e7-a2c5-95cda09a9ce5)
### Screenshots
(pasted above)

### Reproduction Link
(pasted above)
Though I tried to reproduce this problems on codepen, both v3.48.0 and v3.47.0 didn't work correctly. (idk why)
v3.47.0: https://codepen.io/versa-vice/pen/yLrvoEQ
v3.48.0: https://codepen.io/versa-vice/pen/eYoVEjX

With this issue, the graph on your official site is also displayed incorrectly. (David is gone.)
https://apexcharts.com/vue-chart-demos/line-charts/null-values/

Also, on both version, a dot point, like [null, (value), null], isn't displayed correctly once you hover on the graph. (the dot on the grren line, 3rd value will vanish after hovering the graph. But 13th value on the green line remains.)

**Comment by junedchhipa** [comment]
Fixed with https://github.com/apexcharts/apexcharts.js/commit/453a911020de5e9e3100fb2d26ce924b4df2a7b9
