### ISSUE TITLE
Add option min height/padding in chart bar

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#439]
**Is your feature request related to a problem?**
I'm always frustrated when I try to click on a "bar" that has a value of 1, because it's very difficult to click compared to values greater than 90.

**Describe the solution you'd like**
I would like to have a min padding or height metric for the bar.

**Additional context**
 ![alt text](https://i.imgur.com/dZM0V3K.png "Suggestion")

**Comment by junedchhipa** [comment]
Adding min-height / padding would mess up the readings on the y-axis.
You may try `yaxis.logarithmic: true` to minimize the gap between small and large values. (Although, that would also confuse the users in a bar/column chart as all bars would be somewhat similar in height).
