### ISSUE TITLE
Apexcharts management of series

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#44]
Feels like something is wrong with the way Apexcharts remember the state of the chart (at least for line type).

I use one instance of apexcharts, where depending the category the user choose from a select input, the js asynchronously fetch for data, and inject series and config into apexcharts. 

This works but it break quite some functionnalities : 

FIrst the zoom is broken (since the latest version of apexcharts it seems), whatever zoom tool takes the axis ranges from the default data shown at first render. 

Also the reset zoom reinject default series.

Maybe I missed something in the docs ?

See the gif : 

![deepin-screen-recorder_select area_20180821090851](https://user-images.githubusercontent.com/17592744/44386199-1b486300-a522-11e8-97f8-5b7a8008ef59.gif)

**Comment by junedchhipa** [comment]
I think this is related to the issue #38 
The zooming options keep the initial state in memory, but when updating data, it seems the new data is not reflected.
I am working on this, thanks for reporting

**Comment by junedchhipa** [comment]
I just tested the updateOptions() method with a different set of timeseries and it seems like for me zooming works as expected.
Can I see what options are you updating in updateOptions() method?

**Comment by junedchhipa** [comment]
Also, I would suggest trying with the latest build v1.3.9

**Comment by junedchhipa** [comment]
Yeah, maybe. I will update the vue wrapper's dependency and test updating the series with a large difference in the x-axis values.

**Comment by junedchhipa** [comment]
@arkhenstone 
Please try the latest release 1.4.9 - I have done major changes to the management of series. Tested a lot of use cases similar to what you have described.
