### ISSUE TITLE
First line value stacked on multiple y axis graph ( bar + line ) 

### ISSUE THREAD

**Issue by VirgileGaulier** [apexcharts/apexcharts.js#4402]
### Description

With a multiple Y axis graph multiple bar and lines, first values of line series are stacked.

### Steps to Reproduce

1. Create two bar graphs with 3 values
3. Create tow line graphs with 3 values
4. config chart option : stacked : true  ; stackOnlyBar : true 

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/11160030/f58c7c09-8bee-4029-9800-4d154582627e)

### Reproduction Link

https://codepen.io/vga_niko/pen/yLrEqgd

**Comment by rosco54** [comment]
@junedchhipa I'd like to look at this as I've been doing a lot of work in this area recently. This issue was introduced in 3.44.2.
