### ISSUE TITLE
Area chart on dynamicAnimation show line before area color

### ISSUE THREAD

**Issue by marciosalinodias** [apexcharts/apexcharts.js#442]
Hello my friend. 
Firstly, congrats for your plugin, thats awesome.

The problem:
When i try to make a realtime Area chart, i get a behavior interesting.
This is my code:
```
var lastDate = 0;
        var data = [];
        var data2 = [];
        function getDayWiseTimeSeries(baseval, count, yrange) {
            var i = 0;
            while (i < count) {
                var x = baseval;
                var y = Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min;
                var y2 = Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min;

                data.push({
                    x, y
                });
                data2.push({
                    x, y: y2
                });
                lastDate = baseval
                baseval += 86400000;
                i++;
            }
        }

        getDayWiseTimeSeries(new Date('11 Feb 2017 GMT').getTime(), 20, {
            min: 10,
            max: 90
        })

        function getNewSeries(baseval, yrange) {
            var newDate = baseval + 86400000;
            lastDate = newDate
            data.push({
                x: newDate,
                y: Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min
            })
            data2.push({
                x: newDate,
                y: Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min
            })
        }

        var options = {
            chart: {
                height: 350,
                type: 'area',
                animations: {
                    enabled: true,
                    easing: 'linear',
                    speed: 800,
                    animateGradually: {
                        enabled: true,
                        delay: 100
                    },
                    dynamicAnimation: {
                        enabled: true,
                        speed: 150
                    }
                }
            },
            dataLabels: {
                enabled: false
            },
            series: [{
                name: 'RX',
                data: data
            }, {
                name: 'TX',
                data: data2
            }],
            xaxis: {
                type: 'datetime',
                range: 977600000,
            },
            yaxis: {
                max: 200
            },
            stroke: {
                curve: 'smooth'
            },
            tooltip: {
                x: {
                    format: 'dd/MM/yy HH:mm'
                },
            }
        }

        var chart3 = new ApexCharts(
            document.querySelector("#chart3"),
            options
        );

        chart3.render();

        window.setInterval(function () {
            getNewSeries(lastDate, {
                min: 10,
                max: 90
            })

            chart3.updateSeries([{
                data: data
            }, {
                data: data2
            }])
        }, 2000)
```

## Explanation
- What is happening instead?
**The line of area is going to next point before the area color.**

- What is the behavior you expect?
**Both, line and Area color go together to next point.**

- What error message are you getting?
**None.**

- An the last one
**Am i using correctly your plugin?**

**Comment by junedchhipa** [comment]
Can you please create a working codepen example?
So, I can look quickly and get to the issue?

**Comment by marciosalinodias** [comment]
Of course, give me a minute..

**Comment by marciosalinodias** [comment]
Here we go: 
My CodePen
[https://codepen.io/marciosalinodias/pen/PLrwRK](https://codepen.io/marciosalinodias/pen/PLrwRK)

I have 500 error sometimes on codepen, so i created a jsfiddle to:
[https://jsfiddle.net/marciosalinodias/3rwdbptx/](https://jsfiddle.net/marciosalinodias/3rwdbptx/)

I put this values to 300 and 200 to make more visible:
```
animateGradually: {
    enabled: true,
    delay: 300
},
dynamicAnimation: {
    enabled: true,
    speed: 200
}
``` 

The original values are 100 and 150;
If i set to less values the line continue goes before the area color.

**Comment by junedchhipa** [comment]
I understood your point.

Both the line and area paths are drawn separately as both have different calculations. Now, to animate the previous path with the next path, I morph it using SVG.js morphing functions. These morphing functions are difficult to sync paths which have different shapes (in this case, line and area have different shapes although they look similar).

So, I won't be able to help much as I rely on 3rd party SVG.js for morphing animation.

**Comment by marciosalinodias** [comment]
Alright my friend, im so glad for your quickly answer.

I will try to talk with them (SVG.js team) to find a way, and if exists, i come back.
If they have the solution can i try to make this feature and make a pull request? 

Just to help everyone

Thanks for now.

**Comment by junedchhipa** [comment]
Sure, a pull request is always welcome.

**Comment by Jelly-exe** [comment]
Was there ever a solution to this? I am having a similar issue, except much more pronounced due to a 1000ms animation.
