### ISSUE TITLE
Method dataURI() returns a blank chart as the base64

### ISSUE THREAD

**Issue by jeanmmayer** [apexcharts/apexcharts.js#443]
Hello, i'm using dataURI method to get the base64 to use with jsPDF.

My chart:
![2019-03-27_11-15-12](https://user-images.githubusercontent.com/7142161/55083158-cf463980-5081-11e9-854c-6d39ef4f0ca8.png)

dataURI generated: https://paste.in/6llDep 
dataURI image: 
![2019-03-27_11-18-09](https://user-images.githubusercontent.com/7142161/55083208-e38a3680-5081-11e9-9ddb-20b0a2783da4.png)

My javascript code:

```
var options = {
	chart: {
		width: '100%',
		height: '400px',
		type: 'pie'
	},
	labels: chartLabels,
	series: chartData,
	responsive: [{
		breakpoint: 480,
		options: {
			chart: {
				size: '100%'
			},
			legend: {
				position: 'bottom'
			},
			dataLabels: {
				enabled: true,
				formatter: function (val) {
					return val + "%"
				}
			}
		}
	}]
};

chart = new ApexCharts(
	document.querySelector("#myChart"),
	options
);

chart.render();

var dataURL = chart.dataURI().then((uri) => {
	console.log(uri);
});
```

Am i doing something wrong?

Best regards.

**Comment by junedchhipa** [comment]
You should wait for the animation to complete before you can grab the image.

Hence, you should put your `dataURI()` function after `render()` has finished.

```javascript
chart.render().then(() => {
    window.setTimeout(function() {
        chart.dataURI().then((uri) => {
            console.log(uri);
        })
    }, 1000) 
})
```

I have put a timer currently, as chart resolves promise before the animation ends. I will fix this bug and then you won't have to use the timer.

**Comment by jeanmmayer** [comment]
Thank you so much for your support. 

It's working now.

**Comment by omericoramos** [comment]
Hello, would you have an example of how to export the graph in pdf using vue 3
