### ISSUE TITLE
Area Charts with Multiple Series Glitches Every Time on Animation using version 3.49.0

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#4437]
### Description

On version [3.49.0](https://github.com/apexcharts/apexcharts.js/releases/tag/v3.49.0) Area charts with multiple series have a glitchy animation when they render. This is happening on the Apexcharts.com demo page as well.

### Reproduction Link

You can see it on the Apexcharts.com demo pages: https://apexcharts.com/javascript-chart-demos/area-charts/spline/

https://github.com/apexcharts/apexcharts.js/assets/62159496/d0c50da7-3b7c-4789-a4a9-d978e632232e

**Comment by rosco54** [comment]
I'm looking into this.
