### ISSUE TITLE
Error when one single data value per serie in a stacked column chart

### ISSUE THREAD

**Issue by markusand** [apexcharts/apexcharts.js#444]
I'm using a stack bar chart, and after some filters the dataset may contain one single single data point per serie

```javascript
[
  { name: "Tripper", data: [{ x: "2019-02-28T23:00:00.000Z", y: 129689 }] },
  { name: "Overnighter", data: [{ x: "2019-02-28T23:00:00.000Z", y: 462186 }] }
]
```

Then no bar is drawn and 60 errors like the following appear
```
Error: Problem parsing d="M 59.769642857142856 390.169397515528L 59.769642857142856 365.07977116906835L 111.00076530612245 365.07977116906835L 111.00076530612245 390.169397515528L 59.769642857142856 390.169397515528L -3.6271814065499956e+301 390.169397515528L 3.6271814065499956e+301 390.169397515528L 3.6271814065499956e+301 390.169397515528L 3.6271814065499956e+301 390.169397515528L -3.6271814065499956e+301 390.169397515528"
```

**Comment by junedchhipa** [comment]
I was able to reproduce the issue, thanks for reporting.
This will be taken care of soon.

**Comment by Bassardes** [comment]
I also find a problem with single data point in series but for line chart.
If value of point is big enough (50000 for example) then chart stop render normally and browser tab start freezing, but if value is small (1) its render normally

`
{
  chart: {
    type: "line"
  },
  xaxis: {
    type: "datetime"
  },
  series: [
    {
      name: "",
      data: [{ x: "2019-03-28T14:11:53.469Z", y: 50000}]
    }
  ]
}
`

[https://codepen.io/anon/pen/MxNgQg](url)

**Comment by junedchhipa** [comment]
Fixed both the issues (line and stacked bar)

**Comment by rupam999** [comment]
The same issue is there for column chart (Column with Negative Values)
