### ISSUE TITLE
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')     at apexcharts.common.js:6:1

### ISSUE THREAD

**Issue by sai12-creator** [apexcharts/apexcharts.js#4445]
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')
    at apexcharts.common.js:6:1
     pls dont close this bug new version is giving this error if i pass single object in series like 
     series: [{name: 'values', data: [12,3,4,5,6,9]}]
     and react version is 18.2  reactdom 18.2 react-apexchart: 1.4.1 apexchart: 3.49 npm: 9.5.7  
     if i pass multiple objects to series then chart is working only single line chart not coming due to single object.
     series: [{name: 'values1', data: [12,3,4,5,6,9]}, {name: 'values2', data: [12,3,4,5,6,9]}, {name: 'values3', data: [12,3,4,5,6,9]}] its working

**Comment by brianlagunas** [comment]
Did not follow bug template instructions.
