### ISSUE TITLE
When I release the mouse, a point that is supposed to be null appears.

### ISSUE THREAD

**Issue by MurakawaTakuya** [apexcharts/apexcharts.js#4446]
### Steps to Reproduce

1. create a graph that contains null
2. hover and release the graph

### Expected Behavior
![image](https://github.com/apexcharts/apexcharts.js/assets/58139133/43dd81b3-e35f-406b-887b-86e8ec052221)

### Actual Behavior
those points that is supposed to be null appears(remains) after releasing the mouse from the graph

https://github.com/apexcharts/apexcharts.js/assets/58139133/6e7b0a7a-ca39-4dc7-90c8-1311380097f5

![スクリーンショット 2024-04-30 145304](https://github.com/apexcharts/apexcharts.js/assets/58139133/5045cba9-65b7-4f8b-88b4-7d373f03b017)

As you see the picture, it seems there is a mistake in the settings that prevent points from being displayed when they are null, as these points are appearing at the same y-coordinates where the mouse was last hovered.

![スクリーンショット 2024-04-30 145304](https://github.com/apexcharts/apexcharts.js/assets/58139133/f39ebcfe-1428-490f-8cbd-f76f57385ca6)

### Reproduction Link
https://apexcharts.com/javascript-chart-demos/line-charts/null-values/
try these steps with this graph

**Comment by junedchhipa** [comment]
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/a6cefdcdddf6430bce47edf937b974d22dd65a5a)
