### ISSUE TITLE
Error on use "logarithmic: true" when "0" value is present in the series

### ISSUE THREAD

**Issue by juliorosseti** [apexcharts/apexcharts.js#445]
## Codepen

https://codepen.io/anon/pen/jJjaRw?editors=0010

## Explanation

**What is the behavior you expect?**
That the bars appear

**What is happening instead?**
If a value of series has "0", no bars are shown.
`data: [10, 0, 30]` not working, but `data: [10, 1, 30]` it´s working

**What error message are you getting?**
Does not display errors

**Comment by junedchhipa** [comment]
The logScale doesn't accept 0 values.
You should try converting 0 to a very small number like 0.0001 and then try rendering again.
```
data: [10, 0.00001, 30]
```

**Comment by marcosalberto1991** [comment]
me esta presentando un problema con las grafica de las barras , cuando los datos presenta 0 , hay se genera un error con las grafica :

"data": [9126,1640,0,0,0,354],


puedo usar datos que  sea 0.0001, pero los usuarios desea que sea 0  , aun así me toca usa otra librería para este tipo de problemas
