### ISSUE TITLE
X Axis labels not being rotated so they overlap with each other

### ISSUE THREAD

**Issue by rpelorosso** [apexcharts/apexcharts.js#446]
I have a stacked bar chart with 3 columns. The labels for each column are large, so I'd expect them to be automatically rotated (or trimmed), but this is not  happening, and so the labels overlap. Note that if I add a 4th column then the labels are rotated.
 
[I've created a codepen where the overlap happens.](https://codepen.io/anon/pen/LaKgyx)

I've set the following options for the labels:

```
rotate: -45,
rotateAlways: false,
trim: true
```

Am I missing any configuration, or is this supposed to be rotating the labels as it is? 

thank you!

**Comment by junedchhipa** [comment]
```javascript
xaxis: {
  labels: {
    show: true,
    rotate: -45,
    rotateAlways: true,
    minHeight: 100,
    maxHeight: 180,
    style: {
      colors: "red"
    }
  },
  categories: [
    "This is a large label",
    "And Another large one",
    "Just in case one more"
  ]
}
```

**Comment by rpelorosso** [comment]
Thank you @junedchhipa , so there's no way to have the chart rotate the labels automatically if an overlap is going to occur? (and leave them unrotated if not)

**Comment by junedchhipa** [comment]
Well no, the labels should rotate automatically. I missed checking that, reopening issue.

**Comment by Krummelz** [comment]
The labels also do not rotate for other chart types - seems to only work for bar charts, and no sample exists on the website for other chart types to prove otherwise. 

[Here's a codepen of the basic line chart example taken from your site, with the rotate option.](https://codepen.io/Krummelz/pen/WNNrgYK)

**Comment by ericlcolvin** [comment]
👍

**Comment by ashokkumarsundar-ag** [comment]
I am having the same label overlap issue in bar chart. Here is the code pen url:

https://codepen.io/ashok999333/pen/mdVwxqL

**Comment by Teukros** [comment]
> 
> 
> I am having the same label overlap issue in bar chart. Here is the code pen url:
> 
> https://codepen.io/ashok999333/pen/mdVwxqL

Same story, I have to set  rotateAlways: true to avoid this. Not sure why it's marked as "Closed", seems to me it's still an obvious bug.

**Comment by saurabhnemade** [comment]
This is still the issue. when screen size is more it does not respect `rotateAlways` property and even drops some labels.
