### ISSUE TITLE
Unix Timestamp on zooming to milliseconds (timeline)

### ISSUE THREAD

**Issue by QuentinBubu** [apexcharts/apexcharts.js#4467]
Hi,

I opened this issue as a continuation of apexcharts/Blazor-ApexCharts#460

When zooming in to see the details, updating the X axis goes from minute to milliseconds, causing a display of timestamps. This happens when you want to scroll the graph with planning or zoom it with zoom selection.

### Steps to Reproduce

1. Have date with milliseconds 
2. Select zoom in selection
3. Zoom on short time

### Expected Behavior

Elements on timeline zoomed in

### Actual Behavior

Elements disappear and Unix Timestamp is set to X label axis

### Screenshots

https://github.com/apexcharts/Blazor-ApexCharts/assets/60854021/33747390-d53a-474e-9987-6e584a5e08e5

https://github.com/apexcharts/Blazor-ApexCharts/assets/60854021/b00d7051-bf7f-4877-849e-66181cb58013

### Reproduction Link

https://codepen.io/quentinbubu/full/xxNGOLJ

Best regards

**Comment by jasase** [comment]
I also have the same issue.

**Comment by coolmaxmustermann** [comment]
any updates?

**Comment by fmaltester** [comment]
I also have this issue. An update would be much appreciated. 

You can also replicate this on the demo charts on the ApexCharts website: 
https://apexcharts.com/javascript-chart-demos/timeline-charts/distributed/

If you keep zooming between the testing and deployment bars you will get the timestamps.
![image](https://github.com/user-attachments/assets/54bde1d2-a4fb-45e5-a4e9-73e4016ec3d3)
