### ISSUE TITLE
Irregular timeseries line chart displays vertical line

### ISSUE THREAD

**Issue by dev-guf** [apexcharts/apexcharts.js#4471]
### Description
Lines of an irregular timeseries line chart get vertically extended with version 3.49.

### Steps to Reproduce

1. Create irregular timeseries chart 
2. Add three series with different array length (2 ,3, 4) 
3. The second line get vertically extended.

### Expected Behavior
All lines should end with the last data point (ver. 3.48)
### Actual Behavior
Lines get vertically extended (ver. 3.48)
### Screenshots
![chart](https://github.com/apexcharts/apexcharts.js/assets/31572383/ff91b04b-1698-4cb5-8594-2bfa5ffa1890)

### Reproduction Link
v. 3.49: https://jsfiddle.net/igutech/v4nh1mLd/22/
v. 3.48: https://jsfiddle.net/igutech/wfcqgbpx/2/

**Comment by rosco54** [comment]
@junedchhipa I will look at this.
