### ISSUE TITLE
Update to 3.49.1 make the browser freeze

### ISSUE THREAD

**Issue by mysegfault** [apexcharts/apexcharts.js#4473]
### Description

Upgrading from 3.45.2 to 3.49.1, same code, make the browser page freeze. My graph can have more than 10k data points, there is no problem to display them with 3.45.2 but 3.49.1 freeze page with the same code base

### Steps to Reproduce

1. 
2. 
3.

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
