### ISSUE TITLE
Total data label not centered when using a stacked bar chart

### ISSUE THREAD

**Issue by zeux00** [apexcharts/apexcharts.js#4474]
### Description

With version 3.49.1, when displaying a vertical stacked bar chart, the label for total is not correctly centered. Meanwhile, the data label are centered.

Using version 3.49.0, this issue was not present.

### Steps to Reproduce

1. Create a chart with chart type 'bar' and 'stacked = true'
2. Add 'plotOptions.bar.dataLabels.total.enabled = true' and 'plotOptions.bar.dataLabels.position = center' options
3. Render the chart

### Expected Behavior

The total data label should be centered

### Actual Behavior

The total data label appears on the right of the bar

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/8832263/12559231-527b-48a9-9b9e-a40fde400665)

### Reproduction Link

https://codepen.io/zeux00/pen/VwOvVoR

**Comment by rosco54** [comment]
@junedchhipa I will look at this.
