### ISSUE TITLE
Improper spacing b/n tooltip and axis when inverted tooltip appears

### ISSUE THREAD

**Issue by SHVM-09** [apexcharts/apexcharts.js#4479]
### Description

There is an issue with the positioning of the inverted tooltip in the chart. The space between the tooltip and the axis is not consistent when comparing the inverted and non-inverted states.

### Steps to Reproduce

To illustrate the issue, here are some screenshots from the demo:

![Screenshot 2024-05-21 at 12 41 53 PM](https://github.com/apexcharts/apexcharts.js/assets/110282392/cc53a1e2-92d9-4fcf-ac93-8bfb3403cb7f)
![Screenshot 2024-05-21 at 12 43 47 PM](https://github.com/apexcharts/apexcharts.js/assets/110282392/e5a5f7e6-c2fd-4fca-ae1b-4651be745a3f)
![Screenshot 2024-05-21 at 12 45 29 PM](https://github.com/apexcharts/apexcharts.js/assets/110282392/070cad6c-81d0-4b21-8578-40f455cb8324)

### Expected Behavior

The spacing between the axis and the tooltip should be consistent, regardless of whether the tooltip is inverted or not.

Please provide a solution to ensure consistent spacing, so I can implement it in my project seamlessly.

~Awaiting response!

**Comment by brianlagunas** [comment]
Did not provide the required reproduction app.

**Comment by Hypher** [comment]
https://codepen.io/pgpp/pen/ZENeLpv
Compare last three tooltips
