### ISSUE TITLE
IE 11 y-axis rendering error

### ISSUE THREAD

**Issue by simo-berto98** [apexcharts/apexcharts.js#448]
Hi, I wanted to tell you that on **IE 11** I have a problem in rendering the column graph.
The graph does not remain fixed on the y axis but "fluctuates". This error on **chrome** with the same chart does not happen.
Can you tell me why it happens?
Thank you.
I leave you a screenshoot of the problem

![image](https://user-images.githubusercontent.com/38985338/55147044-f6663f00-5145-11e9-9100-da850f24479a.png)

**Comment by simo-berto98** [comment]
![image](https://user-images.githubusercontent.com/38985338/55147204-4218e880-5146-11e9-9414-de42a01fb648.png)

This is on Chrome, with the same chart

**Comment by junedchhipa** [comment]
Fixed IE11 issue in https://github.com/apexcharts/apexcharts.js/commit/44de94c4c2d890df6e35314d0ff55c299cf5eccf
