### ISSUE TITLE
3.49.0 breaks area chart series toggling for series with larger numbers of values

### ISSUE THREAD

**Issue by mrash** [apexcharts/apexcharts.js#4488]
### Description

In 3.49.0, for area charts with multiple series with larger numbers of values (say, about 3,000), series toggling is broken - or, at least, highly unresponsive. See the attached .html example that reproduces this issue. The initial rendering of the graph is fine in 3.49.0 - only toggling a series to hide it via a mouse click has the problem. Note that 3.48.0 does not have this problem, and was likely introduced in commit 7f04fa31. For 3.48.0, series toggling is fast even for area charts with multiple large series. If this is related to linearscale() assumptions, would it be be possible to add a new attribute to allow the user to select the old behavior?

### Steps to Reproduce

1. Load the '[ap_issue.html](https://gist.githubusercontent.com/mrash/8cd170c9e3cba6ef2cf610a1aa8c08a9/raw/40b30153ced0b255622043d9383e48be303ea4cc/ap_issue.html)' file from [this gist](https://gist.github.com/mrash/8cd170c9e3cba6ef2cf610a1aa8c08a9) against ApexChart 3.49.0 (note the '../../apexcharts/dist/apexcharts.js' path may need to be changed for your system).
2. The chart should load showing three series: 'vals', 'moving_avg_100D', and 'exp_moving_avg_100D'.
3. Select the 'vals' series in the legend and mouse click to try and toggle/hide it.
4. The browser tab will become unresponsive.
5. Switching to ApexCharts 3.48.0 or any prior version will not exhibit the above, and series toggling is fast and responsive.

### Expected Behavior

Series toggling should be fast and responsive as seen in 3.48.0 and prior versions.

### Actual Behavior

The browser tab becomes unresponsive (see screenshot below).

### Screenshots

Here is the complete rendered page that includes the three series:
<img width="2473" alt="Full chart" src="https://github.com/apexcharts/apexcharts.js/assets/380228/236e870c-b513-4043-a059-f703069dcc04">

When trying to toggle/hide the 'vals' series, mouse over 'vals' (which shows just the 'vals' series without the others), and then upon mouse click to toggle 'vals' the browser tab become unresponsive:
<img width="2515" alt="Screenshot 2024-05-25 at 2 34 21 PM" src="https://github.com/apexcharts/apexcharts.js/assets/380228/4aee6e50-7a4b-4338-8e9f-4f863a89445a">

Under 3.48.0, here is what should be shown after the mouse click:
<img width="2478" alt="Screenshot 2024-05-25 at 2 35 12 PM" src="https://github.com/apexcharts/apexcharts.js/assets/380228/03b33cd9-b043-4486-8bf5-2817a979168f">

### Reproduction Link

See the '[ap_issue.html](https://gist.githubusercontent.com/mrash/8cd170c9e3cba6ef2cf610a1aa8c08a9/raw/40b30153ced0b255622043d9383e48be303ea4cc/ap_issue.html)' file from [this gist](https://gist.github.com/mrash/8cd170c9e3cba6ef2cf610a1aa8c08a9) - (note the '../../apexcharts/dist/apexcharts.js' path may need to be changed for your system to point to the correct path for ApexCharts).

**Comment by rosco54** [comment]
@junedchhipa I'll look into this.

**Comment by mrash** [comment]
@rosco54 Thanks, and confirmed that 3.49.1 has the issue. Also, I tried HEAD from the main branch, and the issue appears to be there too (same behavior as reported above).

**Comment by rosco54** [comment]
Please check the build process. I find that I often need to kill and restart `npm run dev` to get a build that reflects the src following a branch switch or checkout.

I get the following timings using HEAD (idle time removed):
## Initial Load
![Initial_load](https://github.com/apexcharts/apexcharts.js/assets/159597299/b952c6ca-9c2b-4fb8-8120-71571440da35)
## Collapse Vals
![Collapse_vals](https://github.com/apexcharts/apexcharts.js/assets/159597299/4f4b0920-19ae-4f51-935a-dc6054468e72)

**Comment by rosco54** [comment]
@mrash Thanks for confirming.
@junedchhipa This issue can be closed as fixed by #4483

**Comment by mrash** [comment]
Thanks for the fast turn around time @rosco54. I look forward to the next release.
