### ISSUE TITLE
Is it possible set min and max range to radial bar?

### ISSUE THREAD

**Issue by luckys** [apexcharts/apexcharts.js#449]
I'd like to set a min and max values to radial bar chart.
Currently the min value is 0 and max value is 100, It would be nice if I could customize the min and max values like min 1000 and max 3000

**Comment by junedchhipa** [comment]
Sorry, not possible currently as radial-bar just expects values between 0 and 100.
Maybe in the future, we can think of it.

**Comment by luckys** [comment]
Thanks for you reply.
I solved it using a function to convert my values to percent.

```
const max = 3000
function valueToPercent (value) {
  return (value * 100) / max
} 
```
This function is used inside the serie like this:
`series: [valueToPercent(2500)]`

**Comment by mburger81** [comment]
Same request from us :) in combination of using always percentage the default output should be not % value. We should use formatter do adding % and not for removing it
Thx a lot

**Comment by RatherLogical** [comment]
Any updates on this or an eta on implementation?

**Comment by alansvieira** [comment]
> Thanks for you reply.
> I solved it using a function to convert my values to percent.
> 
> ```
> const max = 3000
> function valueToPercent (value) {
>   return (value * 100) / max
> } 
> ```
> 
> This function is used inside the serie like this:
> `series: [valueToPercent(2500)]`

Thanks man, that's exactly what I need.

**Comment by matthewlenz** [comment]
Those solutions work fine, the complexity happens when you want multiple bars. For that I ended up storing the series values in a variable.

```
var s_vals = [100,1000,10000];
var s_max =  series_vals.reduce(function (a, b) { return parseInt(a) + parseInt(b) }, 0);
var s_percs = series_vals.slice(0);
s_percs.forEach(function (val, idx, arr) { s_percs[idx] = 100 / (s_max / val); });

options.plotOptions.radialBar.dataLabels.value.formatter =
    (val) => { s_vals[s_percs.findIndex((perc) => { perc == val })];
options.series = s_percs;
options.categories = ['cat1', 'cat2', 'cat3'];
```

Hopefully this helps someone, but see the caveat below.

**ISSUE**: Anyone know of a better way to identify the dataLabels?  My way won't work if there are multiple s_percs with the same percentage (because findIndex will just return the first one).  The dataLabels.formatter doesn't receive the label or series index in the arguments. If it did, this would all be perfectly doable.

**Comment by sc979** [comment]
@luckys and @matthewlenz thanks for your comments. I used a formatter to convert % in real value ( >40k) with multiple radial bars :+1:

**Comment by bretscha** [comment]
> Those solutions work fine, the complexity happens when you want multiple bars. For that I ended up storing the series values in a variable.
> 
> ```
> var s_vals = [100,1000,10000];
> var s_max =  series_vals.reduce(function (a, b) { return parseInt(a) + parseInt(b) }, 0);
> var s_percs = series_vals.slice(0);
> s_percs.forEach(function (val, idx, arr) { s_percs[idx] = 100 / (s_max / val); });
> 
> options.plotOptions.radialBar.dataLabels.value.formatter =
>     (val) => { s_vals[s_percs.findIndex((perc) => { perc == val })];
> options.series = s_percs;
> options.categories = ['cat1', 'cat2', 'cat3'];
> ```
> 
> Hopefully this helps someone, but see the caveat below.
> 
> **ISSUE**: Anyone know of a better way to identify the dataLabels? My way won't work if there are multiple s_percs with the same percentage (because findIndex will just return the first one). The dataLabels.formatter doesn't receive the label or series index in the arguments. If it did, this would all be perfectly doable.

Could you solve this problem?  I would like to display the Actual number of the value in a multiple graph and not the percents. And have the graph be in percent but displaying the actual number. Kind of when you look at a speed indicator in your car. I dont want to know my velocity in Percent you know what I mean?

**Comment by matthewlenz** [comment]
@bretscha Didn't have time to fiddle it but here is a sample of my code https://pastebin.com/Qh9G0DWV.  I think some fixes have been committed to include the radialLabel in the params to the formatter to avoid the issue with duplicate s_vals.

**Comment by alekbless** [comment]
Setting min and max to this chart would be valuable👍

**Comment by mcristo1844** [comment]
Any updates on this one?

**Comment by mgpwilson** [comment]
This would be a useful feature!

**Comment by PlippiePlop** [comment]
I'm looking at the code and an option to set ranges is high on the list. For example:

```
radialBar:{
range: [0, 1000] // [startValue, endValue]
}
```

Extension to do stepped range:
`
radialBar:{
range:[ [0,100], [101, 200],[201,300] ... ]
]
`

But i am afraid we are going into Fusion 'gauge' territory with such options.

**Comment by nassimessaidi** [comment]
I found a solution that works for me. But please read until the last to understand how.

First, write a function as mentioned below:
Let's define a max value and targeted value.
With a simple formula we can know that the percentage is:
```
percentage = (value * 100) / maxValue;
```
So, we use the formula above in our function (I will take `60` as my maximum value)
```javascript
const maxValue = 60;

const valueToPercent = (val) => (val * 100) / maxValue;
```
Now, if you type the output of this function to the series like this:
```
series: [valueToPercent(value)],
```
In your chart, it will display the number in Percentage and of course, you don't want that you still need the original value to be printed in the chart, to do that, make a function inside :
```
const config = {
series: [valueToPercent(value)],
    options: {
        ...
        plotOptions: {
        radialBar: {
          ...
          dataLabels: {
            name: {
              ...
            },
            value: {
              ...
              formatter: (val) => (val * maxValue) / 100 ,
              ...
              },
            },
          },
        },
      },
       ...
      },
}
```

And now you in your chart you will see the original value but in the series in count as a percentage to make your chart looks correct.


You can do the same thing if you have a min value different than 0, but with a slight difference in the formula:
```
percentage = ( (value - minValue) * 100 ) / (maxValue - minValue)
```
Thus, the function will be:
```javascript
const maxValue = 60;
const minValue = 10;

const valueToPercent = (val) => ( (val - minValue) * 100 ) / (maxValue - minValue);
```
With a little bit of math from the previous formula above, the `formatter` will be:
```javascript
formatter: (val) => ( val * (maxValue - minValue) ) / 100 + minValue,
```

**Comment by v-braun** [comment]
I think it would be helpfull to have the current series inside of the formatter function to do a propper formatting
(like we have it in the other formatters):

``` js
            formatter: (seriesName, opts) => {
              let lbl = opts.w.config.series[opts.seriesIndex].data[opts.dataPointIndex].x;
              return lbl;
            }
```

**Comment by PlippiePlop** [comment]
I  have created a [codepen example](https://codepen.io/PlippiePlop/pen/abyZgPp) you can use both number and percentages and max totals.

**Comment by 2huge4u** [comment]
> I think it would be helpfull to have the current series inside of the formatter function to do a propper formatting (like we have it in the other formatters):
> 
> ```js
>             formatter: (seriesName, opts) => {
>               let lbl = opts.w.config.series[opts.seriesIndex].data[opts.dataPointIndex].x;
>               return lbl;
>             }
> ```

Just commenting because I would really like this too!

I have requirement for multiple arcs on my radial gauge all showing percentages on different scales. I could achieve this if the formatter method exposed the index of the item being rendered.

**Comment by pzambao** [comment]
> const max = 3000
> function valueToPercent (value) {
>   return (value * 100) / max
> }

Muito obrigado!

**Comment by pzambao** [comment]
> Eu criei um [exemplo de codepen onde](https://codepen.io/PlippiePlop/pen/abyZgPp) você pode usar números, porcentagens e totais máximos.

Muito obrigado!

**Comment by timsun28** [comment]
Just wanted to chime in that I’m also really interested in having the ability to set custom min and max values on the radial bar chart. It would be super helpful for cases where the data range isn’t 0 to 100. I hope the team might reconsider this feature in the future, it would open up a lot more flexibility for different use cases. Thanks for all the great work so far!
