### ISSUE TITLE
Multiple Y-Axis sample is not rendering properly

### ISSUE THREAD

**Issue by adnane-ka** [apexcharts/apexcharts.js#4492]
### Description

I encountered an issue with the ApexCharts library where some of the examples on the official documentation are not rendering correctly. Specifically, the example for the mixed chart with multiple Y-axes fails to render and produces an error. This issue is present on the official ApexCharts documentation sample page.

### Steps to Reproduce

1. Navigate to the following URL: https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/
2. Observe the chart failing to render on the page.
3. Open the browser console to see the error message.

### Expected Behavior
The chart should render correctly without any errors, displaying the mixed chart with multiple Y-axes as shown in the example on the documentation page.

### Actual Behavior
The chart does not render and the following error appears in the browser console:

```
Cannot read properties of undefined (reading 'group')
TypeError: Cannot read properties of undefined (reading 'group')
```

### Reproduction Link

Here is a minimal reproduction of the issue using the provided Codepen template: https://codepen.io/Danny_28/pen/VwOPLgN

**Comment by rosco54** [comment]
Even though there are no data series to plot, therefore nothing to match `yaxis.seriesName` and no series groups (in this case default group names would be generated), which means `group` (that is, `this.config.series.group`) is undefined, this condition needs to be handled more gracefully.

**Comment by junedchhipa** [comment]
Updated the page. Now, it should render correctly.
