### ISSUE TITLE
I have a problem with big data

### ISSUE THREAD

**Issue by Wellers0n** [apexcharts/apexcharts.js#4494]
### Description

I have a problem with large data

### Steps to Reproduce

```js
export const chartData = [
  {
    total: 3816,
    amount: 16418963,
  },
  {
    total: 6280,
    amount: 15983792,
  },
  {
    total: 2425,
    amount: 2155740,
  },
  {
    total: 1542,
    amount: 3114573,
  },
  {
    total: 1472,
    amount: 1047791,
  },
]
```

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/39449389/6d426d90-44a1-48dd-8f74-032f048a025b)

**Comment by brianlagunas** [comment]
Did not provide required reproduction link
