### ISSUE TITLE
Zoom disabled not working correctly

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#45]
As the zoom object is selected by default, setting :

```
zoom: {
    enabled: false
}
```
Just hide zoom tools, but do not disable the ability to zoom by clicking without choosing a tool.

Maybe add a "none" object to autoselected toolbar property and set it by default (or hint about this in the documentation).

**Comment by junedchhipa** [comment]
Good catch!
Will think of another way to handle this
