### ISSUE TITLE
[Feature Request] Total Data label in stacked column

### ISSUE THREAD

**Issue by jeroenpol** [apexcharts/apexcharts.js#450]
Hi!

I got two questions:

1. How can I show the sum of the data as a data label in a stacked column chart. For instance, both data labels should be 71 in the example below. 

2. How can I make sure the different columns stay in their category on the xaxis. Now the columns overlap multiple categories while I want one column in the 1 category and the other in the 2 category. While the others stay empty. 

Example:
![image](https://user-images.githubusercontent.com/6681199/55166441-6a690d00-516f-11e9-9b2e-761eca1302a4.png)

**Comment by vuphuctho** [comment]
Adding a hack from mine: https://codepen.io/vuphuctho/pen/poobNPG
In chart options we can retrieve and display total number of stacked bar chart like so:
```
dataLabels: {
    enabled: true,
    offsetY: -20,
    style: {
      fontSize: '12px',
      colors: ["#304758"]
    },
    formatter: function(value, { seriesIndex, dataPointIndex, w}) {
      return w.globals.stackedSeriesTotals[dataPointIndex];
    }
  },
```
Just wondering why no data label but only the ones on top of the stack is displayed. But overall it meets OP requirement.

**Comment by aessig** [comment]
@vuphuctho thank you for the snippet. 
Have you found a way of hiding the total amount when hovering the legends ?

**Comment by hardik-kondhiya** [comment]
@jeroenpol 

You can simply use **"formatter"** under **"dataLabels"** and it will give you the total of your stacked column.

Here is what I have used in my project and that's it.

    formatter: function (value, { seriesIndex, dataPointIndex, w }) {
        if (seriesIndex === ((w.config.series.length) - parseInt(1)))
            return w.globals.stackedSeriesTotals[dataPointIndex];
        return "";
    }

**Comment by fegoworks** [comment]
> @jeroenpol
> 
> You can simply use **"formatter"** under **"dataLabels"** and it will give you the total of your stacked column.
> 
> Here is what I have used in my project and that's it.
> 
> ```
> formatter: function (value, { seriesIndex, dataPointIndex, w }) {
>     if (seriesIndex === ((w.config.series.length) - parseInt(1)))
>         return w.globals.stackedSeriesTotals[dataPointIndex];
>     return "";
> }
> ```

 I have this stacked column chart that gets updated after selecting a drop down of different timeframes. The data labels show up on the default selection but get hidden in subsequent selections

**Comment by JulesCoch** [comment]
> > @jeroenpol
> > You can simply use **"formatter"** under **"dataLabels"** and it will give you the total of your stacked column.
> > Here is what I have used in my project and that's it.
> > ```
> > formatter: function (value, { seriesIndex, dataPointIndex, w }) {
> >     if (seriesIndex === ((w.config.series.length) - parseInt(1)))
> >         return w.globals.stackedSeriesTotals[dataPointIndex];
> >     return "";
> > }
> > ```
> 
> I have this stacked column chart that gets updated after selecting a drop down of different timeframes. The data labels show up on the default selection but get hidden in subsequent selections

Hi ! How can you show both the total and the individual datalabels of my series ?

**Comment by hk-spotline** [comment]
Hi! @JulesCoch and @jeroenpol 

You can get your problem resolved by updating the npm package **_apexcharts_** and use **plotOptions**.

1. Please make sure that your **_chartType_** must be **bar** under **option**.
2. Update related package(s) if you are using _React_ or _Angular_ or _Vue_.

```
plotOptions: {
  bar: {
    horizontal: false,
    dataLabels: {
      total: {
        enabled: true,
        style: {
          fontSize: '13px',
          fontWeight: 900
        }
      }
    }
  }
}
```

**Comment by hardik-kondhiya** [comment]
Hi! @JulesCoch and @fegoworks 

You can get your problem resolved by updating the npm package **_apexcharts_** and use **plotOptions**.

1. Please make sure that your **_chartType_** must be **bar** under **option**.
2. Update related package(s) if you are using _React_ or _Angular_ or _Vue_.

```
plotOptions: {
  bar: {
    horizontal: false,
    dataLabels: {
      total: {
        enabled: true,
        style: {
          fontSize: '13px',
          fontWeight: 900
        }
      }
    }
  }
}
```
