### ISSUE TITLE
安全漏洞：更新内部 svg.js 文件

### ISSUE THREAD

**Issue by qvitasoyq** [apexcharts/apexcharts.js#4502]
Description:
The version of the svg.js file used in the project has known security vulnerabilities. To ensure the security and stability of the project, we need to update this file to the latest secure version.

Details:

Vulnerability Description: The current version of svg.js 2.7.1 has a security vulnerability that results in users being redirected to unsafe gambling websites when accessing pages that use svg.js. This behavior could lead to information leakage and a poor user experience.

Vulnerability Impact: Users are redirected to gambling websites, which may expose them to phishing attacks, malware infections, and other security risks.

Current Version: svg.js 2.7.1

Suggested Solution: Update svg.js to the latest version.

Steps to Reproduce:

Clone the project repository and install dependencies.
Navigate to the path containing the svg.js file.
Access a page that uses svg.js and observe if there is a redirection to gambling websites.
Expected Behavior:
The project should use the latest version of the svg.js file to avoid known security vulnerabilities and ensure the project's security. Users should not be redirected to unsafe websites when accessing related pages.

Actual Behavior:
The current version of the svg.js file used in the project has known security vulnerabilities, causing users to be redirected to gambling websites when accessing related pages.

Appendix:
![image](https://github.com/apexcharts/apexcharts.js/assets/16370418/22757897-38d4-4419-bdf2-60ed169cd2c7)

**Comment by brianlagunas** [comment]
Did not provide required reproduction app
