### ISSUE TITLE
Getting `RangeError: Maximum call stack size exceeded at Object.reactiveGetter [as width]` with vue-apexcharts after v3.48.0

### ISSUE THREAD

**Issue by AbdAsh** [apexcharts/apexcharts.js#4504]
### Description
After updating the apexcharts library to v3.49.0, the pie chart is not loading in Vue2 using the package vue-apexcharts

### Steps to Reproduce

1. Create a Vue2 Project
2. Install apexcharts and vue-apexcharts per docs instruction
3. Try using the chart type `pie` (in my case)

### Expected Behavior
The Pie chart should render normally no issues

### Actual Behavior
The Pie chart is not rendering at all and the error `RangeError: Maximum call stack size exceeded at Object.reactiveGetter [as width]` is logged

### Screenshots
<img width="383" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/59181667/53195353-bb47-4072-8482-c2118e5990a3">

**Comment by junedchhipa** [comment]
works fine here - https://apexcharts.com/vue-chart-demos/pie-charts/simple-pie-chart/
Please provide a reproducible example in your case.

**Comment by Rehmanali-A** [comment]
Getting same issue while using the react-apexcharts library.
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
