### ISSUE TITLE
Tooltip not visible in stacked column chart , when y-axis is reversed.

### ISSUE THREAD

**Issue by Prakanksh** [apexcharts/apexcharts.js#4509]
https://github.com/apexcharts/apexcharts.js/assets/98647697/a6ab4972-8048-436c-a8e2-7d4a89a01ea2

### Description

We are using column chart (stacked)
having numeric values in y-axis  
sometimes those values can be negative 
according to which we 
set the boolean value for y-axis in chart options  "reversed" : true/ false
if reversed is false 
the chart works fine but 
if reversed is true 
then tooltip is not visible .

### Steps to Reproduce

1.  Create a column chart 
2.  Have a set of series data with negative values on Y-axis 
3.  Set the reversed options in y-axis to true 
4.  Set Tooltip enable option to true .
5.  Check for the chart tooltip

### Expected Behavior
It should show tooltip with y-axis value in the chart at the tip of the hovered bar 

### Actual Behavior
Tooltip is not visible 
until or unless tooltip is fixed 
(In fixing the tooltip there might be some difference between the tooltip height and hight of bars in column chart .)

### Screenshots
attached a video 

### Reproduction Link
https://codesandbox.io/embed/cyqjy2?view=editor+%2B+preview&module=%2Fsrc%2Fcomponents%2FChart.component.vue

https://codesandbox.io/embed/cyqjy2?view=editor+%2B+preview&module=%2Fsrc%2Fcomponents%2FChart.component.vue

attaching screenshots of the code pen  
pay attention to tooltip 
<img width="1440" alt="Screenshot 2024-06-07 at 2 51 31 PM" src="https://github.com/apexcharts/apexcharts.js/assets/98647697/5fca7e90-598b-4903-9fe9-dadb2d8f8a22">

<img width="1440" alt="Screenshot 2024-06-07 at 2 51 22 PM" src="https://github.com/apexcharts/apexcharts.js/assets/98647697/808a53be-485d-48c6-8118-3d4ff452fee9">

**Comment by antshpra** [comment]
Looks like ApexCharts is miscalculating the y coordinates or the `tooltip` when yaxis is `reversed`.

**Comment by antshpra** [comment]
Possibly `tooltip` is overshooting the chart area and hence not visible.

**Comment by Prakanksh** [comment]
Kindly check this issue in priority basis , as Its a major bug for a simple change in charts

**Comment by antshpra** [comment]
Any fix for this ?

**Comment by Prakanksh** [comment]
still facing issue ,
will this work in any upcoming npm updates ?
