### ISSUE TITLE
Area chart Datetime type, function to hide dates when no series are given

### ISSUE THREAD

**Issue by pedrooda** [apexcharts/apexcharts.js#451]
![ApexChart](https://user-images.githubusercontent.com/46965368/55233438-6b4d7d80-5207-11e9-9f6e-acc5b788aa79.gif)

Is that possible to create a function to hide dates when no series are given to then? At the gif example it gives the impression that there are values between days 20 and 26 but it doesn't have

**Comment by junedchhipa** [comment]
@pedrooda Sorry, that's not possible.
The x-axis labels are generated by getting the min date/max date and based on the days/months in between, labels are generated. 
Totally independent of the data of the chart data.
