### ISSUE TITLE
onClick for shared tooltips

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#452]
I'd like to invoke an onClick event when clicking on a shared tooltip. At the moment that isn't possible, but it would be very useful in one of my use cases. Ideally, it'd call the onClick event whenever the tooltip is showing, using the data from the datapoints from which tooltip is receiving its information.

**Comment by junedchhipa** [comment]
Added a new event
`chart.events.markerClick`
