### ISSUE TITLE
Chart plotting area shrinks when the type is datetime

### ISSUE THREAD

**Issue by zee0786** [apexcharts/apexcharts.js#4521]
### Steps to Reproduce

1. After giving all the required params for a vertical column graph, when the type is mentioned as **_datetime_** the graph just ignores the available width provided.

### Expected Behavior
it should take up the full width if the width provided is '100%'.

### Reproduction Link
https://codepen.io/zee0786/pen/OJYxQBO?editors=0010

or 

https://codesandbox.io/p/sandbox/react-basic-example-forked-6n82ky?file=%2Fsrc%2FApp.js

If you are using react-apexcharts, and want to create a demo in React environment, use the CodeSandbox React template - https://codesandbox.io/s/6yoqonyo7r
-->

**Comment by brianlagunas** [comment]
Your CSS is setting the max width to 650px.  Remove that.

**Comment by zee0786** [comment]
I agree that there was a max-width in codepen version, but there is none in the sandbox version. Can you please recheck it
