### ISSUE TITLE
bar chart with width '100%' and xaxis.type="datetime" has spacing around the chart

### ISSUE THREAD

**Issue by zee0786** [apexcharts/apexcharts.js#4522]
Description
Steps to Reproduce
1- draw a vertical bar chart with type= datetime
2- After giving all the required params the graph just ignores the available width provided., 

Actual behaviour
- there is some space before and after the plot

Expected Behavior
it should take up the full width if the width provided is '100%'.

Reproduction Link
https://codesandbox.io/p/sandbox/react-basic-example-forked-6n82ky?file=%2Fsrc%2FApp.js

**Comment by brianlagunas** [comment]
Your reproduction link does not work. Please update it.

Your react sample works, but you are hardcoding the width to 500, so I am confused on what you are trying to report.

**Comment by zee0786** [comment]
Im able to click on the reproduction link above and this is what I am getting. The extra white space that needs to be filled up with the plot has been marked in yellow

![image](https://github.com/apexcharts/apexcharts.js/assets/20573062/1aa24397-1fee-42bf-8a14-1d8f68dd00b0)
