### ISSUE TITLE
If height is smallish (200px) then data labels with offsets are drawn outside of visible bounds

### ISSUE THREAD

**Issue by mika76** [apexcharts/apexcharts.js#453]
## Codepen

https://codepen.io/anon/pen/MRgNrE

Labels "fall out" of bounds when height is small 

## Explanation

- What is the behavior you expect?
I expect either the grid resizes taking into account offsetX and offsetY so as to fit in the label, or for the label to move within visible bounds.

- What is happening instead?
Label disappears since it's draw outside of bounds

- What error message are you getting?
No error

**Comment by junedchhipa** [comment]
This is fixed recently. The patch will be released tomorrow

**Comment by mika76** [comment]
Brilliant thanks!
