### ISSUE TITLE
Edge of the series (line) drops vertically without reason.

### ISSUE THREAD

**Issue by AdrianoCasimiro** [apexcharts/apexcharts.js#4531]
### Description

I have several data series in the graph, where each series (line) has its respective time/value. The problem is that at certain points on the edge of the series, the line simply drops, as in the example of the green line. There is no data in the series to justify such behavior. 
Version used: ApexCharts v3.49.1.

### Expected Behavior

It is expected that this drop at the edge of the series does not occur.

### Screenshots
![error](https://github.com/apexcharts/apexcharts.js/assets/10772691/006991fe-42a4-478f-8423-3abf02ca687d)

**Comment by brianlagunas** [comment]
Did not follow bug template instructions. No reproduction provided
