### ISSUE TITLE
Download/export SVG,PNG images with ALL tooltips open

### ISSUE THREAD

**Issue by majortom84** [apexcharts/apexcharts.js#4537]
## Summary

I would love to be able to download/export SVG,PNG images with ALL tooltips open. This would help when the chart and data is needed for visuals in an image. 

## API Changes

I Do not believe an AIT change is needed.  

## Intended Use Case

This would be used to present data with visuals on Download/Export of images.

**Comment by mudssrali** [comment]
Any solution? Thanks
