### ISSUE TITLE
Scatter plot does not support X and Plus markers

### ISSUE THREAD

**Issue by alankalb** [apexcharts/apexcharts.js#4539]
### Description

When making a scatter plot using 'x', 'X', 'plus' or '+' as the marker shape results in an error as the Scatter plot only supports 'circle', 'square' or 'rect' markers. This is not clear based on documentation or typescript. 

### Steps to Reproduce

1. Create a scatter plot
2. Add markers to the chart options with 'plus', '+', 'x' or 'X' as the shape

### Expected Behavior
Scatter plots can use any shape from the `MarkerShapeOptions` type

### Actual Behavior
Scatter plot crashes when using anything other than 'circle', 'square' or 'rect' as marker shapes

### Reproduction Link
https://codepen.io/Alan-Kalbfleisch/pen/KKLorJe

**Comment by junedchhipa** [comment]
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/3d2aba0153a5202ccdfc172c79095b208c714a1c)

**Comment by junedchhipa** [comment]
Please note that the [markers.shape](https://apexcharts.com/docs/options/markers#shape) now supports the following options

```js
circle
square
line
plus
cross
```
