### ISSUE TITLE
Setting height on chart creates a larger style tag surrounding it

### ISSUE THREAD

**Issue by mika76** [apexcharts/apexcharts.js#454]
## Image
![Screen Shot 2019-03-30 at 19 58 27](https://user-images.githubusercontent.com/229311/55280484-89f66600-5326-11e9-8055-0dd2f4594119.png)

## Explanation

- What is the behavior you expect?
Setting height on the chart (380px in this case) I expect the resulting chart to be exactly that height

- What is happening instead?
A style tag is created surrounding the chart and a `min-height` style is set to larger than the height (394px in this case).

**Comment by junedchhipa** [comment]
There is some additional padding of around 14px to give some breathing space to the chart.
I will try removing it and see how it looks.

**Comment by junedchhipa** [comment]
A new property `chart.parentHeightOffset: 0` is added which will allow to remove the additional height appended.

**Comment by mika76** [comment]
Thanks that would help a lot. It's hard to design panels around charts if you can't control their size.

Do you really need this at all though? Seems like people can easily add their own wrapper element and css styles if they want (eg: for padding)

**Comment by junedchhipa** [comment]
Well, I made a mistake in the beginning by not providing inner padding which would give some breathing space by default.

Now, changing that seems difficult. So, I provided this new option to remove the extra height.

**Comment by mika76** [comment]
😊 I understand, I mean you might not need the style tag at all since anybody can just wrap the chart into their own div tag and place a margin

**Comment by mrabaev48** [comment]
Hello.
I still having this issue on initial load.
I'm using Vue js 2, ts, quasar framework.

Solution with chart.parentHeightOffset: 0 doesn't help me.

Any suggestions?


![image](https://user-images.githubusercontent.com/8854033/121635736-6cd58a00-ca8f-11eb-88fb-dc00ff168fe5.png)

**Comment by mika76** [comment]
Hey @mrabaev48 what exactly is your issue? The picture does not explain it...

**Comment by gabrielbertaglia** [comment]
Hi everyone, I'm having some trouble with resizing in ApexCharts using ReactJS. When I reload my page, sometimes the chart renders correctly and sometimes it doesn't. Does anyone have a solution for this?

Correct chart

![Image](https://github.com/user-attachments/assets/a59bcab9-4321-42d1-8860-12410b583a84)

Incorrect chart
![Image](https://github.com/user-attachments/assets/8c9bcd57-54a4-466c-aa46-dd3bd2ebe9a1)
