### ISSUE TITLE
#4505: Breaks transparent mode if you have a theme set

### ISSUE THREAD

**Issue by elucidsoft** [apexcharts/apexcharts.js#4541]
### Steps to Reproduce

1. Set theme to dark
2.  Set chart background to 'transparent'

### Expected Behavior
The chart background will remain transparent but other elements of the chart will still use dark theme.

### Actual Behavior
The chart background ignores the transparent setting and it's a dark grey color pulling from the theme.

Reverting back to 3.49.1 fixes the issue.

**Comment by Sebastian-Webster** [comment]
Hi @elucidsoft, I'm sorry about that. Does #4542 fix the problem?
