### ISSUE TITLE
Bar chart - datalabels misaligned when using multiple y-axis

### ISSUE THREAD

**Issue by chedighribi** [apexcharts/apexcharts.js#4558]
Description
The data labels of the second bar are shifted to the right, making them misaligned and not centered within the bars.

Steps to Reproduce
Create a bar chart with two series. 
Enable opposite: true for the second bar.
Hover over the bars to see the misalignment of the data labels.

Expected Behavior
The data labels should be centered on the bars.

Actual Behavior
The data labels are shifted to the left.

Screenshots
![Screenshot 2024-07-08 at 16 55 29](https://github.com/apexcharts/apexcharts.js/assets/74118861/a56e95cd-c95e-470d-9a69-43229b0e2159)

Reproduction Link
https://codepen.io/chedighribi/pen/poXoLJq

**Comment by junedchhipa** [comment]
@rosco54 This [commit](https://github.com/apexcharts/apexcharts.js/commit/4d12c5fe0e2dd27327939c8b64da9cd8b999fd7a) has caused this issue. Can you check this one?
