### ISSUE TITLE
Date Issue - Date representation on x-axis seems wrong

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#456]
![image](https://user-images.githubusercontent.com/8254178/55305395-ddbf9700-546d-11e9-8c8c-c7134ab87925.png)

**Comment by junedchhipa** [comment]
The first label shows January 2010.
When the value is the start of the month/start of the year, it is different than the rest of the ticks.

It is documented here - https://apexcharts.com/docs/datetime/

**Comment by irshadahmed** [comment]
@junedchhipa  Is there way to display it like 01 Jan, instead of Jan `10, without affecting the chart drill-down due to zooming ?

**Comment by junedchhipa** [comment]
In the same doc page, you will see

**b). xaxis.labels.format**
The X values formatting for datetime values can also be formatted by: 
xaxis.labels.format = 'DD/MM' 
This will fix the labels formatter and will not consider whether the difference in time is in years/months/days/hours

xaxis: {
  labels: {
    format: 'DD/MM',
  }
}

**c). xaxis.labels.formatter**
Overrides everything and applies a custom function for the xaxis value.
xaxis: {
  labels: {
    formatter: function (value, timestamp) {
      return new Date(timestamp) // The formatter function overrides format property
    }, 
  }
}

**Comment by irshadahmed** [comment]
Yeah, this will lead to display the labels in the same format no matter what. This doesn't work out with the requirement I have. BTW, thanks for the info.
