### ISSUE TITLE
Line Plot Y-range incorrect when series has multiple points with same x-value

### ISSUE THREAD

**Issue by alankalb** [apexcharts/apexcharts.js#4560]
### Description

When plotting a line chart, the y-axis range is not correct if the series has multiple points with the same x value and one of those points is outside of the range of all other points in the series. 

From my testing, it appears that this occurs when there are more than two points that share the same x value. Only the first two points are used to calculate the range. All others seem to be discarded.

### Steps to Reproduce

1. Create a line plot with at-least three points that have the same x value. Ensure the last point has a y value that is greater than any other y value in the series.

### Expected Behavior
Y-axis range for axis is calculated from absolute range of series

### Actual Behavior
Y-axis range axis range is not calculated correctly when multiple points in a series have the same x value.

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/37275661/abf83c24-f84e-4ff7-82f4-f7b0ed7c6ff0)

### Reproduction Link

https://codepen.io/Alan-Kalbfleisch/pen/KKLorJe

**Comment by alankalb** [comment]
The same issue occurs with scatter plots. This is actually more concerning for scatter plots as a scatter plot should definitely be able to plot multiple points with the same x-values without breaking. I can somewhat understand why this may break for line charts as there could be an assumption that line charts should be for results from well-defined functions.

**Comment by junedchhipa** [comment]
@rosco54 can you take a look at this one? This seems to be broken after v3.46.0

**Comment by rosco54** [comment]
@junedchhipa Working on it.
