### ISSUE TITLE
Y-axis ranges assigned to incorrect axes when using xy zoom selection

### ISSUE THREAD

**Issue by alankalb** [apexcharts/apexcharts.js#4561]
### Description

When plotting multiple y-axes each with multiple series assigned, using xy zoom selection results in the range for all y-axes other than the first in the list of the y-axes being incorrect.

### Steps to Reproduce

See details in reproduction link section.

### Expected Behavior
When zooming with xy selection, visible y-axes min and max ranges are set using the user's selection.

### Actual Behavior
When zooming with xy selection axis ranges are assigned in order of the yaxes list regardless of whether they are visible or not.

### Screenshots

https://github.com/apexcharts/apexcharts.js/assets/37275661/3ca46a39-78cc-4c23-b003-835b082acbfe

### Reproduction Link

https://codepen.io/Alan-Kalbfleisch/pen/WNqbQRg

Using the chart in the link above, open the console and make a zoom selection. In the console, note the ranges that have been attributed to each axis. Axes with ids 0 and 1 are for Series 1 data. Axes with ids 2 and 3 are for Series 2 data. The range for the second visible axis is assigned to the second axis (id 1) instead of the correct axis (id 2). This results in the range of any y axes other than the first visible axes to be incorrect.

**Comment by rosco54** [comment]
I confirm this as an issue and note that this appears to have been working in revision 3.45.2.

In the current version, if I change from old-style yaxis.seriesName to the newer style as follows (added in 3.46.0 or 3.47.0), it appears to behave as expected.

`  yaxis: [
    {show: true, seriesName: ["Series 1a","Series 1b"], title: { text: 'Series 1' }, id:0},
    {opposite: true, show: true, seriesName: ["Series 2a","Series 2b"], title: { text: 'Series 2' }, id:1},
  ]`

There is supposed to be full compatibility between the old and new configuration styles but it appears that the mapping of y-axis indices was missed in some or all of the zoom selection code.

Looking into this now.
