### ISSUE TITLE
Stacked bar chart mixed with line renders line in wrong position

### ISSUE THREAD

**Issue by jasonpolites** [apexcharts/apexcharts.js#4564]
### Description

I am trying to render an equivalent of something like this (rendered with Chart.js)

![image](https://github.com/apexcharts/apexcharts.js/assets/764528/3b2bc0ac-1875-452b-81ee-84413ede844a)

Using the demo chart [here](https://codepen.io/junedchhipa/pen/wYOzjd), with modifications to make it stacked, produces something _close_, but the chart line is rendered in the wrong place

### Expected Behavior

The line should represent the data in the series it represents

### Actual Behavior

The line renders below the zero (0) value, but none of the data in its series are negative

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/764528/4652c8c4-3599-41ba-bef4-26469c5bd415)

### Reproduction Link

https://codepen.io/jasonpolites/pen/VwJYKoR

**Comment by rosco54** [comment]
You have a multi-axis chart configured and the Y-axis scale for your chart is on the right side and appears to be correct, at least for the first point  at 1.4.

**Comment by jasonpolites** [comment]
OK.. that's fair
