### ISSUE TITLE
Line chart is not rendered properly (dots are off line)

### ISSUE THREAD

**Issue by uyoahz27** [apexcharts/apexcharts.js#4565]
### Description

Our line charts got screwed up after upgrade to 3.50.0 from 3.49.2

### Steps to Reproduce

1. create a simple data set and try to render as line chart
2. you'll see the line is rendered properly, but the dots are far away from the line

### Expected Behavior
It should be rendered like
![image](https://github.com/apexcharts/apexcharts.js/assets/171191202/095c1ff8-0208-4adc-b2ee-3e80dad7b794)

### Actual Behavior
It's rendered like
![image](https://github.com/apexcharts/apexcharts.js/assets/171191202/c3937c7e-5ff4-4d14-84e9-d21ebd8627fc)

### Screenshots

![image](https://github.com/apexcharts/apexcharts.js/assets/171191202/c3937c7e-5ff4-4d14-84e9-d21ebd8627fc)

**Comment by brianlagunas** [comment]
no reproduction link provided.
