### ISSUE TITLE
Series markers rendered on wrong location when showing multiple charts

### ISSUE THREAD

**Issue by PatrickSvenssonSL** [apexcharts/apexcharts.js#4568]
### Description

With version 3.50.0 the series markers shown on hover are affected by other charts, causing them to render way off under certain conditions.
I checked with 3.49.0 and in that version it works as expected.

### Steps to Reproduce

1. Add 2 charts, one area chart and one bar chart with at least 2 series
2. Hover over the area chart
3. Notice that the dots are not on the line

### Expected Behavior
Dots should be on the line

### Actual Behavior
Dots are rendered way off

### Screenshots
![image](https://github.com/user-attachments/assets/c3f27d7e-4731-43e7-a913-f882e99304dd)

### Reproduction Link
https://jsfiddle.net/gLh60msx/

**Comment by junedchhipa** [comment]
This is fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/061f90784b5747694aff71054dc77cfbe24ca045#diff-a669fc96d6ab4d9fd3974a4cdc79becb3c9d103d16c8c63290f04096a0caaa93) and the fix will be shipped with v3.51.0
