### ISSUE TITLE
Adding additional markers to the Scatterplot Chart

### ISSUE THREAD

**Issue by ris-tlp** [apexcharts/apexcharts.js#4569]
## Summary

Add additional in-built markers similar to how Plotly Express with Dash has. [Under custom marker styles](https://plotly.com/python/marker-style/) 

## Intended Use Case

I have a use case that would be greatly helped by the addition of additional in-built markers to the Scatter plot chart. I have data points that belong to different categories which are to be visualized through different marker symbols. While I can do this by using custom SVG images in Apex, I need the color of each individual marker to be changed and plotted dynamically according to a secondary metric. From my understanding, I cannot change an SVG's color dynamically through Apex, and hence I am unable to transition my project's feature from Plotly to ApexCharts. 

For example, this is what my scatterplot looks like in Plotly Express / Dash:
![image](https://github.com/user-attachments/assets/b8e8fd63-1bb1-4170-bedd-518df3419785)

I would really appreciate it more in-built markers could be added! Thank you for the awesome library!

**Comment by junedchhipa** [comment]
Recently, we added `plus`, `cross` shapes for the markers. We will add some more.

**Comment by alankalb** [comment]
In addition to more shapes, can a way to register custom shapes be added?
