### ISSUE TITLE
Draw series combination of solid and dashed line

### ISSUE THREAD

**Issue by piyushSinghalDemo** [apexcharts/apexcharts.js#457]
Can we create line graph with combination of dashed and solid line as per x-axis zone wise, for exaample after 8 point there will dashed line, else solid line
![dashed_line](https://user-images.githubusercontent.com/30336741/55309754-56c5eb00-547c-11e9-9472-8968e4235390.png)

**Comment by Dineshbha** [comment]
Is this feature support available in the new versions?

**Comment by dantart** [comment]
I did it creating two series, in your example, one from Jan to Sep, other from Sep to Dec and then setting different strokes for each one. It's not perfect but it's a cheat ;-)

**Comment by Fusseldieb** [comment]
![image](https://user-images.githubusercontent.com/4715129/120315558-de088680-c2b2-11eb-81eb-0a3c424a0bc1.png)

I did it like @dantart before I even saw his comment ahahah

Works fine for me
