### ISSUE TITLE
xaxis datetimeFormatter missing options in docs

### ISSUE THREAD

**Issue by davetapley** [apexcharts/apexcharts.js#4572]
### Description

`xaxis`'s `datetimeFormatter` accepts `minutes` and `seconds`, but they are missing in the docs.

### Steps to Reproduce

1. Visit https://apexcharts.com/docs/options/xaxis/
2. Search `datetimeFormatter`
3. Compare to: https://github.com/apexcharts/apexcharts.js/blob/b586399a913cf9841b1db480a65defad33d76226/types/apexcharts.d.ts#L1025-L1032

### Expected Behavior

Docs are correct

### Actual Behavior

They are not

### Screenshots
<img width="321" alt="Screen Shot 2024-07-17 at 11 16 20 AM" src="https://github.com/user-attachments/assets/55fe4db6-5f6a-4128-a4c2-a4eece82d15c">

### Reproduction Link
N/A

**Comment by davetapley** [comment]
Happy to do a PR, but can't find source for docs? 🤔

**Comment by junedchhipa** [comment]
Fixed
