### ISSUE TITLE
Add Repobeats (metrics) to README

### ISSUE THREAD

**Issue by JuanPabloDiaz** [apexcharts/apexcharts.js#4578]
## Summary

[Repobeats](https://repobeats.axiom.co) is a way to embed contributor analytics into your GitHub project's README.md

Metrics are everything. Data is powerful

#### Project Examples:

- [FreeForGeeks](https://github.com/JuanPabloDiaz/freeForGeeks#how-to-contribute)
- [Tabler](https://github.com/tabler/tabler#-project-activity)
- [Projectdiscovery](https://github.com/projectdiscovery/nuclei-templates#-contributions)
- [ArchiSteamFarm](https://github.com/JustArchiNET/ArchiSteamFarm)
- [Growthbook](https://github.com/growthbook/growthbook#license)

![image](https://github.com/user-attachments/assets/3e27ce01-cfb9-4091-bdc8-56bb6572e408)
## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

## Intended Use Case

Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by brianlagunas** [comment]
Closing as you have been spamming other repos with the same issue.

![image](https://github.com/user-attachments/assets/ddad2194-49c7-4be2-8290-805704bf643e)

**Comment by JuanPabloDiaz** [comment]
@brianlagunas, 

I wanted to reach out to apologize for my recent actions regarding the issue I opened about Repobeats in multiple repositories. My intention was never to spam; rather, I was trying to contribute with what I thought was a valuable tool to enhance contributor analytics in open-source projects.

You can check that I closed all the issues. Again, My intention was never to spam.
