### ISSUE TITLE
on click of line graph, how to get selected data labels

### ISSUE THREAD

**Issue by piyushSinghalDemo** [apexcharts/apexcharts.js#458]
whenever i click on line graph , i am able to capture click event using 
events: {
                 click: function (event, chartContext, config) {
                    console.log(chartContext);
                }
},
however i am not getting data-labels details, Is there any possibility i can get selected data-labels details here?

![capture_events](https://user-images.githubusercontent.com/30336741/55311129-cf7a7680-547f-11e9-9d95-eda1dfa4bfb2.png)

**Comment by rafalkrupinski** [comment]
dataPointSelection event might be what you're looking for
