### ISSUE TITLE
v3.51.0 is a breaking change but the version doesn't reflect that

### ISSUE THREAD

**Issue by infomiho** [apexcharts/apexcharts.js#4580]
### Description

Using the ApexCharts like before:
```ts
  const options: ApexOptions = {
    colors: ['#3C50E0'],
    ...
    legend: {
      show: true,
      position: 'top',
      horizontalAlign: 'left',
      fontFamily: 'inter',

      markers: {
        radius: 99,
      },
    },
...
  };
```

causes a Typescript error because the `radius` property was dropped. 

It's because the version bump was from 3.50.0 to 3.51.0 and `npm` installed the latest because I used `^3.50.0` in my `package.json` which allows for minor version bumps.

### Steps to Reproduce

1. Try running a project that you started with `3.50.0` that used `radius` property
2. Run `npm update --save` to update the deps
3. Try compiling the project with Typescript

### Expected Behavior

If the property is deprecated - it should be a warning but the old code should still work.

Alternatively, it should be a major version bump.

### Screenshots

<img width="825" alt="Screenshot 2024-07-22 at 10 49 55" src="https://github.com/user-attachments/assets/c13c7e30-89f1-4a7a-b8ce-1c9bb243ede5">

**Comment by brianlagunas** [comment]
Our decision to remove properties is not a bug. It is by design. Also, you are assuming this project follows semantic versioning. Not all projects follow semantic versioning.
