### ISSUE TITLE
How to set different colors to different labels or different label backgrounds based on label values ? 

### ISSUE THREAD

**Issue by GantaVenkataKousik** [apexcharts/apexcharts.js#4581]
dataLabels: {
          enabled: true,
          style: {
            fontSize: '12px',
            fontFamily: "'Gantari', sans-serif",
          },
          background: {
            enabled: true,
            formatter: function (value) {
              if (value > parseFloat(biomarkerInfo.highRange))
                return 'hsl(0 100% 60%)'
              if (value < parseFloat(biomarkerInfo.lowRange))
                return 'hsl(40 100% 62%)'
            },
          },
          dropShadow: {
            enabled: true,
          },
        },
        
        this was not working
        
        This was setting the same color
        
                dataLabels: {
          enabled: true,
          style: {
            fontSize: '12px',
            fontFamily: "'Gantari', sans-serif",
            formatter: function (value) {
              if (value > parseFloat(biomarkerInfo.highRange))
                return 'hsl(0 100% 60%)'
              if (value < parseFloat(biomarkerInfo.lowRange))
                return 'hsl(40 100% 62%)'
            },
          },
          background: {
            enabled: true,
            foreColor: 'red'
          },
          dropShadow: {
            enabled: true,
          },
        },

**Comment by brianlagunas** [comment]
Closing as this is not a feature request, but rather it appears to be a question. Questions should be asked in discussions.

**Comment by GantaVenkataKousik** [comment]
Okay sure , thanks
