### ISSUE TITLE
There is an error in the stacked bar graph: the percentage is showing as 1000% instead of 100%.

### ISSUE THREAD

**Issue by kentemman** [apexcharts/apexcharts.js#4584]
### Description
There is an error in the stacked bar graph: the percentage is showing as 1000% instead of 100%.

### Steps to Reproduce

1. Open the application or webpage displaying the stacked bar graph.
2. Navigate to the section where the stacked bar graph is implemented.
3. Observe the percentage labels on the stacked bars, noting that they exceed the expected 100%.

### Expected Behavior
The stacked bar graph should display accurate percentages, with the total percentage for any stack equaling 100%. Each section within the stack should represent a portion of the whole without exceeding 100%.

### Actual Behavior
The stacked bar graph incorrectly shows a total percentage of 1000%, leading to misinterpretation of data. Each stack's percentage labels are inflated beyond their actual value, suggesting a calculation or configuration issue.

### Screenshots
![image](https://github.com/user-attachments/assets/10eea431-63f9-4e5b-a184-9c7ca27eb76f)
Caption: Screenshot showing the stacked bar graph displaying +1000% instead of 100%.

**Comment by kentemman** [comment]
my code
![image](https://github.com/user-attachments/assets/eb213422-8e00-46fa-b64c-d912e58f5a7a)

**Comment by brianlagunas** [comment]
Did not provide required reproduction
