### ISSUE TITLE
Dynamically updating theme only changes background

### ISSUE THREAD

**Issue by elbojoloco** [apexcharts/apexcharts.js#459]
## Codepen
https://codepen.io/anon/pen/dLPoBM

## Explanation
- What is the behavior you expect?
Labels and tooltips (basically all theme-colored elements) should be updated when dynamically changing theme mode.

- What is happening instead?
Only the background color of the chart is updating.

- What error message are you getting?
No error.

**Comment by junedchhipa** [comment]
Thanks for providing the demo, I will look soon into it.

**Comment by cemujax** [comment]
Anyway, you can solve this way.

```javascript
function updateTheme(mode) {
    chart.updateOptions({
        theme: {
            mode: mode
        },
        chart: {
          foreColor: mode === 'dark' ? '#f6f7f8' : '#373d3f'
        },
        tooltip: {
            theme: mode
        }
    })
}
```

**Comment by junedchhipa** [comment]
I am going to review the PR by @cemujax and release a fix soon.
