### ISSUE TITLE
Support no comma in color functions

### ISSUE THREAD

**Issue by chrisands** [apexcharts/apexcharts.js#4590]
## Summary

`colors` params support only comma format `rgb(0, 0, 0)`, but when I try to pass valid css `rgb(0 0 0)` it fails because it didn't supported format of `rgb`. It would be nice to support new CSS format. I think it is 1 regexp change if not mistaken. 

## API Changes

No API changes.

## Intended Use Case

Here's article about new CSS syntax
https://css-tricks.com/no-comma-color-functions-in-css/

**Comment by Slokilla** [comment]
I would add that decimals are not supported either. When your data is calculated, it's common.
