### ISSUE TITLE
Wrong/outdated docs for removed "radius" property on markers

### ISSUE THREAD

**Issue by lukas-mertens** [apexcharts/apexcharts.js#4594]
### Description

After writing #4593 I noticed that the project doesn't seem to be following semantic versioning and breaking changes are to be expected. While adapting our code to the newest changes, I wanted to look at the new options reference: https://apexcharts.com/docs/options/markers/ On this page "radius" is still shown as a valid property. It would be nice if this could be adapted after the latest release of 3.51.0

**Comment by junedchhipa** [comment]
Fixed it, thanks!
