### ISSUE TITLE
Upon clicking any of the bars in apexcharts - it shows undefined -niceMax error

### ISSUE THREAD

**Issue by vaa2000** [apexcharts/apexcharts.js#4596]
### Description
when I click on bars or hover over bars in barchart- I get following error 

I have used apexcharts to display data as per date selected in dropdown(for example -hourly, daily, weekly, monthly and yealy accordingly data has to be displayed )

![image](https://github.com/user-attachments/assets/32ba0585-12cd-4817-8ee6-348fc9a6063e)

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Non -erroneous behaviour of apexcharts

### Actual Behavior
shows error upon hovering 

### Screenshots
![image](https://github.com/user-attachments/assets/e1b40e20-e953-4014-b06d-e21b426920bc)
![image](https://github.com/user-attachments/assets/1b16dd68-88f7-4b37-89b8-3ea3405d84d9)

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
