### ISSUE TITLE
[reopened] tooltip.enabledOnSeries doesn't work as expected in timeseries line charts

### ISSUE THREAD

**Issue by jdegger** [apexcharts/apexcharts.js#4597]
The issue below was wrongly closed and is not being reopened despite multiple responses requesting it to be reopened.

For maximum visibility I have copied the issue here.

https://github.com/apexcharts/apexcharts.js/issues/1339

> # Bug report
> 
> I have found some inconsistent `tooltip.enabledOnSeries` behavior in irregular timeseries line charts.
> ## Codepen
> 
> Minimal working example: https://codesandbox.io/s/vue-basic-example-0ibes?fontsize=14&hidenavigation=1&theme=dark
> ## Explanation
> 
> When using `tooltip.enabledOnSeries` I expect tooltips to be enabled on the series that have the corresponding indices, as specified in the docs. Right now I can't get it to work in my chart, which is a timeline line chart with different time ranges.
> 
> Example values of `enabledOnSeries` in the Codepen example, and what happens:
> 
>     * `enabledOnSeries: []`: tooltips disabled for all series
> 
>     * `enabledOnSeries: [0]`: tooltips enabled for all series
> 
>     * `enabledOnSeries: [1]`: tooltips disabled for all series
> 
>     * `enabledOnSeries: [0, 1]`: tooltips enabled for all series
> 
>     * `enabledOnSeries: [1, 2]`: tooltips disabled for all series
> 
> 
> The key element seems to be if series 0 is included or not, in which case all series get tooltips.

**Comment by brianlagunas** [comment]
The reproduction link does not work. Please provide a valid reproduction link or this issue will be closed.

**Comment by brianlagunas** [comment]
Closing as the original has been reopened
