### ISSUE TITLE
Stacked 100% Bar Shows original data as percentage numbers

### ISSUE THREAD

**Issue by kn327** [apexcharts/apexcharts.js#4600]
### Description
This appears to be a regression bug. Previously, when values were provided, the 100% stacked bar chart would show the label as the percentage and the label as the actual data value

In version 3.23.1, the actual data values are showing as percentages

### Steps to Reproduce

1. Create a 100% stacked bar chart
2. Fill with data for two or more series
3. Render on page

### Expected Behavior
Labels on the bar chart show the actual percentage, tooltip when hovering shows the actual data value

### Actual Behavior
Labels on the bar chart show the actual data value plus a percentage sign

### Screenshots
<img width="654" alt="image" src="https://github.com/user-attachments/assets/8ca99f97-f356-4daa-8f8c-3363e9658fca">

### Reproduction Link
https://codepen.io/Kom-/pen/yLdgdoW

**Comment by cynde** [comment]
how to fix this? because i have the same problem

**Comment by junedchhipa** [comment]
The issue has been fixed on the `main` branch. Please wait for the next release (which is coming in 4-5 days)

**Comment by cynde** [comment]
okay! thank you
