### ISSUE TITLE
Markers for line chart are off the line if i have a stacked bar 100% chart below it

### ISSUE THREAD

**Issue by cynde** [apexcharts/apexcharts.js#4603]
### Description
I have a line chart and the markers are not in the correct position (off the line) ONLY IF I have a stacked bar 100% chart below it with more than 1 type for the data. Below is the attachment:
<img width="928" alt="image" src="https://github.com/user-attachments/assets/56015f57-eb1d-4669-86b6-c24b62a58fc1">

I have 2 environment site, dev and prod. the code is literally same. But this bug only appears in production env. I also tried to reproduce in codepen but it doesn't appear. But I have a screenshot for the bug in my production environment. (same with this bug: https://github.com/apexcharts/apexcharts.js/issues/4600. -> this bug only appears in my dev site, prod site is fine so i think this may be another bug).

Anyway, I debugged and when I only have 1 type of data for my stacked bar chart, the markers are not off the line. But since i have 2 type of data (you can see there are 2 color for the stacked bar chart), the markers for the line chart are off the line.

### Steps to Reproduce
1. Have a line chart
2. Have a stacked bar 100% chart below it
3. The markers for the line chart will be off the line

### Expected Behavior
Markers should not be off the line
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/e780368b-aa75-4ae8-b422-0de7acb98733">

### Actual Behavior
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/14300714-912f-4fa8-a303-4c2e4f98d6f7">

### Reproduction Link
this is the codepen but somehow the markers are fine here : https://codesandbox.io/p/sandbox/react-basic-example-forked-7gq9tm?file=%2Fsrc%2FApp.js%3A186%2C15

**Comment by brianlagunas** [comment]
As you can imagine, if this cannot be duplicated, it will be extremely difficult to find the issue. Can you create a sample that does reproduce it locally, push it to a GitHub repo, and provide the link to the repo? We have to be able to duplicate the issue.

**Comment by cynde** [comment]
understand. but i copied literally my code to the codepen. and it does not appear. anyway this video maybe can help to understand the bug.

Uploading Screen Recording 2024-08-02 at 14.20.25.mov…

**Comment by cynde** [comment]
understand. but i copied literally my code to the codepen. and it does not appear. anyway this video maybe can help to understand the bug.

https://github.com/user-attachments/assets/c3b3b033-c084-4f2a-a6ec-ddd618a3f99c

**Comment by cynde** [comment]
understand. but i copied literally my code to the codepen. and it does not appear. anyway this video maybe can help to understand the bug. record this using slow 3g so the data of the stacked bar chart comes later than the line chart. if the data for the stacked bar chart is loaded, the markers for the line chart will off the line.

https://github.com/user-attachments/assets/ae03dadf-bc47-42f2-a7b9-4f97d2ac6840

**Comment by cynde** [comment]
anyway, i'm using react apex chart

**Comment by brianlagunas** [comment]
I'm sorry, but a reproduction app is required. We cannot fix what we cannot duplicate. I will reopen when you provide a sample that reproduces the issue.
