### ISSUE TITLE
X axis data are over laps on each other

### ISSUE THREAD

**Issue by ravi-kachhadiya** [apexcharts/apexcharts.js#4605]
I am getting the issue of overlapping x-axis data on each other when we zoom in or zoom out and the same issue occurs in large-size screen devices. you can see below image data is overlapping each other. If I do zoom out then it is rotated and if I do zoom in then it nice flat with some padding but at one moment it shows like this. so, there is any solution for this, I can control this? 

![Screenshot (357)](https://user-images.githubusercontent.com/83212598/120309847-555e0a80-c2f3-11eb-84bd-b576e0389029.png)

**Comment by junedchhipa** [comment]
Did not provide required reproduction.
