### ISSUE TITLE
502 Bad Gateway Error When Accessing Documentation

### ISSUE THREAD

**Issue by juanse1080** [apexcharts/apexcharts.js#4612]
Hello,

I'm encountering a 502 Bad Gateway error when attempting to access the [ApexCharts documentation](https://apexcharts.com/docs). Here are the details:

Steps to Reproduce:

- Open a web browser.
- Navigate to [ApexCharts docs](https://apexcharts.com/docs)
- Observe the 502 Bad Gateway error.

Expected Behavior:
The documentation should load without any errors.

Actual Behavior:
A 502 Bad Gateway error is displayed, preventing access to the documentation.

Screenshot:

![imagen](https://github.com/user-attachments/assets/9b56e912-cd94-482d-9710-187771ae36bb)
![imagen](https://github.com/user-attachments/assets/79708a1e-7918-47c1-9b8a-e978d6ef813a)

Browser and OS:

    Browser: Chrome, Firefox
    OS: Linux

Additional Information:

    Date and time of the error: 2024-08-02, 14:27 UTC

Thank you for looking into this issue.

Best regards,

Juan Marcon

**Comment by brianlagunas** [comment]
Yes, we are aware that the website is down. Thanks for letting us know.
