### ISSUE TITLE
Documentation website is returning a 502 Bad Gateway error

### ISSUE THREAD

**Issue by ltetreault-va** [apexcharts/apexcharts.js#4613]
### Description

**The following areas of the website are all currently returning a 502 page.**
There are likely more as well, but this is what I've come across so far. This began happening around 9:30AM CST/MST

https://apexcharts.com/docs/angular-charts/
https://apexcharts.com/docs/vue-charts/
https://apexcharts.com/angular-chart-demos/area-charts/

### Steps to Reproduce

1. Visit one of the links provided in the description
2. See `502 - Bad Gateway page`

### Expected Behavior
The documentation page works.

### Actual Behavior
The server is having issues returning the requested pages.

### Screenshots
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/2595ac3b-88dd-46dc-8b19-f4f020eb1a1a">

### Reproduction Link

https://apexcharts.com/docs/angular-charts/
https://apexcharts.com/docs/vue-charts/
https://apexcharts.com/angular-chart-demos/area-charts/

**Comment by ampodobas** [comment]
This is still occurring as of 12:13 PM pacific on August 2, 2024...

**Comment by Sebastian-Webster** [comment]
Also seems to be more than just the listed URLs above. These are the ones that I'm getting 502 for:
https://apexcharts.com/embedded-analytics
https://apexcharts.com/javascript-chart-demos/*
https://apexcharts.com/angular-chart-demos
https://apexcharts.com/vue-chart-demos
https://apexcharts.com/react-chart-demos/*
https://apexcharts.com/docs/* (except for docs/installation)

**Comment by dodsonw** [comment]
Temporary workaround is to just view the latest cached version of the site (June 28, 2024) on the Wayback Machine:

https://web.archive.org/web/20240628113829/https://apexcharts.com/docs/installation/#

**Comment by junedchhipa** [comment]
Sorry for the trouble everyone, the website is up again.
