### ISSUE TITLE
Document is downn !

### ISSUE THREAD

**Issue by AamirAnwar3311** [apexcharts/apexcharts.js#4614]
Documentation is down?
I am getting 502 Bad Gateway.

<img width="1920" alt="Screenshot 2024-08-03 at 3 41 39 AM" src="https://github.com/user-attachments/assets/098c42be-d2e6-4044-9d46-39bd5b69548c">

**Comment by brianlagunas** [comment]
duplicate #4613

**Comment by dodsonw** [comment]
Temporary workaround is to just view the latest cached version of the site (June 28, 2024) on the Wayback Machine:

https://web.archive.org/web/20240628113829/https://apexcharts.com/docs/installation/#
