### ISSUE TITLE
502 Bad gateway error

### ISSUE THREAD

**Issue by Agus-Wei** [apexcharts/apexcharts.js#4617]
Could not access https://apexcharts.com/docs/options/chart/type/. Got bad gateway error
![image](https://github.com/user-attachments/assets/0772270e-c600-4af6-a8e4-d07d0e16741b)

**Comment by junedchhipa** [comment]
Duplicate of #4613

**Comment by KalanaPerera** [comment]
still down

**Comment by HermanCeaser** [comment]
This is still the case as of Aug 4 23:45. What is happening?
