### ISSUE TITLE
Multiple Yaxis for multiple series

### ISSUE THREAD

**Issue by Jzueh** [apexcharts/apexcharts.js#462]
Hi,

I need to have multiple yaxis. Every yaxis also needs to be used by multiple series.
At the moment I'm only able to link one yaxis to one series.

It should be possible to link multiple series to one yaxis if I also need to use multiple yaxis.

**Comment by junedchhipa** [comment]
Yes, it is possible to link multiple series to just 1 y-axis.

Please refer this doc page 
https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/#3-series-2-scales

**How to associate a series with a Y-axis?**
By default, each index of Y-axis corresponds to the index of series. But, if you want to associate a series with a y-axis, you can target by specifying yaxis.seriesName when building y-axes array.

```javascript
series: [
  {
    name: 'TEAM A',
    data: [1, 2, 4, 5, 15, 28, 38, 46]
  },
  {
    name: 'TEAM B',
    data: [20, 29, 37, 36, 44, 45, 50, 58]
  },
  {
    name: 'TEAM C',
    data: [10, 19, 17, 36, 44, 45, 20, 38]
  }
],
yaxis: [
  {
    seriesName: 'TEAM A'
  },
  {
    seriesName: 'TEAM B'
  },
  {
    seriesName: 'TEAM B'
  }
],
```

In the above code, 2 series share the same scale (TEAM B), while 1 series plots on another scale (TEAM A)

**Comment by Jzueh** [comment]
Maybe I just don't get it, but it's not working for me.

I got 6 series. 1 and 4 need to be on one Yaxis, 2,3,5 and 6 need to be on an opposite yaxis. All line charts.
If I try it with your example, the scales are not what they should be

**Comment by Jzueh** [comment]
Got it. Sry my bad.
I got it working. Thanks

**Comment by barrynl** [comment]
I had the same question and I did not understand it either (just like @Jzueh). The crux was that you add a yaxis for every data series (and let the array index be the same), but for scaling refer to another data series (by seriesName). Also, you may want to add the show:false on the last yaxis object to not show it in your chart.

Thanks for the product, it saved me ALOT of time.

**Comment by praveenpuglia** [comment]
I guess the way apex achieves this is counter-intuitiuve. What we want to say is that "Plot these two series on a particular axis because they should be on same scale"

But here with the provided approach, 
```
yaxis: [
  {
    seriesName: 'TEAM A'
  },
  {
    seriesName: 'TEAM B'
  },
  {
    seriesName: 'TEAM B'
  }
```

if I wanted to plot say 10 series on a simple linear axis with some options, i would have to create those many axis?

Instead it would be much more intuitive if i could go to a series and say

```
 {
    name: 'TEAM A',
    data: [1, 2, 4, 5, 15, 28, 38, 46],
	axisName: 'axis1'
  },
  {
    name: 'TEAM B',
    data: [20, 29, 37, 36, 44, 45, 50, 58],
	axisName: 'axis2'
  },
  {
    name: 'TEAM C',
    data: [10, 19, 17, 36, 44, 45, 20, 38],
	axisName: 'axis2'
  }
```
and something like this for axis.
```
yaxis: [
  {
	name: 'axis1'
	logarithmic: true
  },
  {
	name: 'axis2'
  }
```

**Comment by sanket044** [comment]
Can anyone help me please. Having same issue. I want to show 2 series on 1 yaxis and other 2 on 2nd yaxis. I want to compare current month revenue vs last month's revenue, and current month order count with last month's. Please check below codepen.

https://codepen.io/sanket044/pen/ZEbxLGg

**Comment by sanket044** [comment]
I have solved the issue by updating version of apexcharts to 3.19 from 3.18.

**Comment by isuke01** [comment]
In this example there is missing one important thing. The example would show 3 axis
`series: [
  {
    name: 'TEAM A',
    data: [1, 2, 4, 5, 15, 28, 38, 46]
  },
  {
    name: 'TEAM B',
    data: [20, 29, 37, 36, 44, 45, 50, 58]
  },
  {
    name: 'TEAM C',
    data: [10, 19, 17, 36, 44, 45, 20, 38]
  }
],
yaxis: [
  {
    seriesName: 'TEAM A'
  },
  {
    seriesName: 'TEAM B'
  },
  {
    seriesName: 'TEAM B'
  }
],`
You must show `show: false` to all unwanted ones and `show: true`  to the one  you want to show.
So this one would show only two:

`yaxis: [
  {
    seriesName: 'TEAM A'
    show: true
  },
  {
    seriesName: 'TEAM B'
    show: true
  },
  {
    seriesName: 'TEAM B'
    show: false
  }
],`

But also important thing it does not combine them. You just pick another one as act as combined one `  seriesName: 'TEAM B'` in this example.
If there is a way to combine them I'd love to see that

**Comment by bitmover-studio** [comment]
> In this example there is missing one important thing. The example would show 3 axis `series: [ { name: 'TEAM A', data: [1, 2, 4, 5, 15, 28, 38, 46] }, { name: 'TEAM B', data: [20, 29, 37, 36, 44, 45, 50, 58] }, { name: 'TEAM C', data: [10, 19, 17, 36, 44, 45, 20, 38] } ], yaxis: [ { seriesName: 'TEAM A' }, { seriesName: 'TEAM B' }, { seriesName: 'TEAM B' } ],` You must show `show: false` to all unwanted ones and `show: true` to the one you want to show. So this one would show only two:
> 
> `yaxis: [ { seriesName: 'TEAM A' show: true }, { seriesName: 'TEAM B' show: true }, { seriesName: 'TEAM B' show: false } ],`
> 
> But also important thing it does not combine them. You just pick another one as act as combined one ` seriesName: 'TEAM B'` in this example. If there is a way to combine them I'd love to see that

I think docs should be updated with this information. I spend a few hours trying to make it works, but documentation is incomplete.

**Comment by vivek65k** [comment]
To configure a chart with multiple Y-axes, you need to define the yaxis property in the chart options. Each Y-axis can have its own set of configurations, such as position, title, and scaling. Here’s a basic example:
![Uploading Screenshot 2024-06-25 025400.png…]()

`var options = {
  chart: {
    type: 'line'
  },
  series: [
    {
      name: 'Cumulative Receipt',
      data: [30, 40, 45, 50, 49, 60, 70]
    },
    {
      name: 'Cumulative Projected Inventory',
      data: [20, 30, 35, 40, 39, 50, 60]
    },
    {
      name: 'Week-wise Receipt',
      data: [10, 20, 25, 30, 29, 40, 50]
    }
  ],
  yaxis: [
    {
      title: {
        text: 'Cumulative Metrics'
      },
      seriesName: ['Cumulative Receipt', 'Cumulative Projected Inventory'],
      opposite: false // Left Y-axis
    },
    {
      title: {
        text: 'Weekly Metrics'
      },
      seriesName: 'Week-wise Receipt',
      opposite: true // Right Y-axis
    }
  ],
  xaxis: {
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul']
  }
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
`

**Comment by arthuroaraujo** [comment]
What if I have names that are variables? I have a selector that can choose between A, B, and C, for example. Each letter will have 3 types of data: left, right, and delta. Left and right have the same magnitude, and ideally, they should use the same scale and Y-axis, while delta should be on another Y-axis.

So the issue with the names is that it will be A (Left), A (Right), A (Delta); B (Left), B (Right), B (Delta), and so on, depending on the size of the array. But when mapping or filtering through my seriesName, using an includes, the behavior is still incorrect, placing A on the first axis, B on the second, and C without an axis, whereas the idea was to use one axis for A and B and another for C.
