### ISSUE TITLE
How to contribute to ng-apexcharts?

### ISSUE THREAD

**Issue by ltetreault-va** [apexcharts/apexcharts.js#4624]
### Description

I recently created a PR in `ng-apexcharts`, but there hasn't been any progress or feedback on it. This repo seems to get a lot of activity so I figured I would post here.

### Steps to Reproduce

N/A

### Reproduction Link

Bug: https://github.com/apexcharts/ng-apexcharts/issues/348

Could someone from the ApexCharts' maintainers please review this PR

Fix: https://github.com/apexcharts/ng-apexcharts/pull/347

**Comment by junedchhipa** [comment]
`ng-apexcharts` is also maintained. Continuing the discussion there.
