### ISSUE TITLE
Not supplying datetime option for x axis causes page freeze

### ISSUE THREAD

**Issue by bglasgo** [apexcharts/apexcharts.js#4625]
I had charts that were working fine on 3.51 but when updating to 3.52 the page would completely freeze when calling updateSeries
All you have to do to replicate is put these two data points in the  example codepen: [1723007560001,6.1],[1723007550001,7.9]
https://codepen.io/apexcharts/pen/bxzgZJ
the code pen takes a long time to render that, however in my project in chrome it never finished and completely froze the page so that I had to close it.

if you just add the option 
xaxis: { type: 'datetime' }
then it completely works fine, however I did not have this before the recent update and had no issue with performance or freezing
I have remedied my issue, but thought some others might run into this.

**Comment by junedchhipa** [comment]
This is fixed and will be shipped in the next version
