### ISSUE TITLE
Breaking removal of radius property from configuration options

### ISSUE THREAD

**Issue by Luk-H** [apexcharts/apexcharts.js#4626]
### Description
A previously existing property `radius` is gone from the path: `options.legend.markers.radius` in type definitions since 3.51, this feels like a bug since it would be a breaking upgrade

Here is a link to the commit and line of the public api changing: https://github.com/apexcharts/apexcharts.js/commit/b31f7e13b13bf3f35e2b77df12a7445aa7071c71#diff-1156359dc5238d9290bf8627dd0d6607f612e09ef7bdc89eb1598205eab1825bL834
As also can be noted, properties with the same name but different path seems to also be removed (as can be noted with one user commenting on this commit https://github.com/apexcharts/apexcharts.js/commit/b31f7e13b13bf3f35e2b77df12a7445aa7071c71#r144780997 )

### Steps to Reproduce
1. Use old version of apexcharts > 3.51.0
2. Use the property: `options.legend.markers.radius` in the configuration of any of your charts
3. Upgrade the library to 3.51.0
4. The code no longer type-checks

### Expected Behavior
I expect to be able to upgrade to a new patch release without breakage 
### Actual Behavior
The code no longer passes type checking after upgrade

**Comment by brianlagunas** [comment]
This project does not follow semantic versioning, and the maintainers may at any time change the public API to improve the project.
