### ISSUE TITLE
TypeError when updating from a rangeArea chart to area chart

### ISSUE THREAD

**Issue by Phaneron404** [apexcharts/apexcharts.js#4628]
### Description

When a rangeArea chart is loaded and the updateOptions() method is called with options that contain an area chart,  a TypeError occurs and apexcharts does not display any data.

### Expected Behavior

Update to an area chart.

### Actual Behavior

TypeError and no chart is displayed

### Reproduction Link

[https://codepen.io/Phaneron404/pen/PorKVqd](https://codepen.io/Phaneron404/pen/PorKVqd)

**Comment by junedchhipa** [comment]
Range area chart cannot be converted to an area chart as the data required to render both is different.
