### ISSUE TITLE
Reversed stacked bar chart fails to load with all -ve data points

### ISSUE THREAD

**Issue by antshpra** [apexcharts/apexcharts.js#4630]
### Description
Stacked bar chart with negative series data fails to render when reversed.

### Steps to Reproduce
```
var options = {
  chart: {
    type: 'bar',
    stacked: true
  },
  series: [{
    name: 'sales',
    data: [-30,-40,-45,-50,-49,-60,-70,-91,-125]
  }],
  xaxis: {
    categories: [1991,1992,1993,1994,1995,1996,1997, 1998,1999]
  },
  yaxis: {
    reversed: true
  }
}

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```

### Screenshots
<img width="717" alt="image" src="https://github.com/user-attachments/assets/7297fc2f-3016-4701-b108-61296f281104">

### Reproduction Link
https://codepen.io/xplkbmga-the-reactor/pen/dyBVOOZ

**Comment by antshpra** [comment]
It works as expected if I switch to version **3.48.0** or older.

**Comment by rosco54** [comment]
@junedchhipa I will take a look at this.
