### ISSUE TITLE
toString() error in Nextjs during development

### ISSUE THREAD

**Issue by harsh7800** [apexcharts/apexcharts.js#4631]
i have been using apexcharts recently and i have very agressive usage of the charts in my app, during  development it keep popping .toString() error which is very annoying i need to doubble save my code to remove it, am i missing something here ??

`TypeError: Cannot read properties of undefined (reading 'toString')`

**Comment by brianlagunas** [comment]
Did not follow bug template instructions

**Comment by harsh7800** [comment]
Added   `width="100%"` and it worked
