### ISSUE TITLE
A "loading" animation state

### ISSUE THREAD

**Issue by mika76** [apexcharts/apexcharts.js#465]
I was just looking through the features and the animation on the page https://apexcharts.com/features/ next to the heading "Smooth Animations" stood out to me. 

It would be really cool to have a standard "loading" animation on each chart type since loading data for charts can take a while sometimes if done over ajax. Usually I show a loading indicator and only show the chart after, bit it would be pretty cool if the chart could display some sort of animation itself which then just morph into the loaded data.

Just an idea 😊 feel free to close this if you don't like it...

**Comment by junedchhipa** [comment]
Good idea!
If it was a single chart type (like line/area), this would be easier to morph as there are no multiple paths in those chart types.
But, if you try morphing a single element to multiple paths (bars/columns), then it becomes tricky.

So, theoretically, it's cool but not easy to implement for each chart type :)

**Comment by mika76** [comment]
Could you maybe show me how you did the since wave column chart? I tried to do it using vue but the update was horrendous...

**Comment by junedchhipa** [comment]
Sorry to deceive you into thinking that it’s a chart, it’s not! Just plain cas animation :)

**Comment by mika76** [comment]
Hah, I suspected. Is there a quicker way to update than by changing the series data?
