### ISSUE TITLE
Crash when displaying area chart

### ISSUE THREAD

**Issue by labo-flg** [apexcharts/apexcharts.js#4652]
### Description

A simple area chart throws errors and crashes with `Invalid array length`

This happens with apexcharts 3.52.0 and not in 3.51.0.

### Steps to Reproduce

Area chart, with 2 series.
See the repro sandbox it's quite simple case.

### Reproduction Link

Here is a [sandbox](https://codesandbox.io/p/sandbox/practical-jasper-zvckfp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm03kdxdb0006356jfdsl2tog%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm03kdxdb0002356juhj6whef%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm03kdxdb0003356j5gs6wsov%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm03kdxdb0005356j2lh1pr7w%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm03kdxdb0002356juhj6whef%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm03kdxda0001356jignqafu0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm03mq37y0002356j1hfys7bz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm03kdxdb0002356juhj6whef%2522%252C%2522activeTabId%2522%253A%2522cm03mq37y0002356j1hfys7bz%2522%257D%252C%2522cm03kdxdb0005356j2lh1pr7w%2522%253A%257B%2522id%2522%253A%2522cm03kdxdb0005356j2lh1pr7w%2522%252C%2522activeTabId%2522%253A%2522cm03mq6zu000x356jni4j8vga%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm03kdxdb0004356jer5abwv7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm03kewjt002e356jzk9i9g8k%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm03mq6zu000x356jni4j8vga%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm03kdxdb0003356j5gs6wsov%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm03kdxdb0003356j5gs6wsov%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) for reproduction.

Easier than codepen for dependency tests IMO.
Just change the version of apexcharts used. In 3.52.0 it crashes.

**Comment by junedchhipa** [comment]
The issue is solved in the last commits. A new version 3.52.1 will have it resolved. Please wait for the release.
