### ISSUE TITLE
Is it possible to highlight one value of a series in a bar chart?

### ISSUE THREAD

**Issue by Jzueh** [apexcharts/apexcharts.js#467]
Hi,

is it possible to highlight just one value in a bar chart in a diffrent color?
For example, the highest value or the lowest value?
I just found a color setting for the whole series, but not for the individual bars.

Thank you.

**Comment by junedchhipa** [comment]
Currently, you can target bar colors based on the value in `plotOptions.bar.colors.ranges[]`. 

```javascript
plotOptions: {
  bar: {
    horizontal: false,
    colors: {
        ranges: [{
            from: 0,
            to: 100,
            color: '#dedede'
        }],
    }
  }
}
```

Targetting dataPoints directly is not currently possible, but may come in future.

**Comment by Jzueh** [comment]
Would be great.
Thank you.
