### ISSUE TITLE
The apex charts zoom in and out when i scroll over it via mouse wheel. https://app.vturbotech.ai/dashboard

### ISSUE THREAD

**Issue by kazi86** [apexcharts/apexcharts.js#4677]
@junedchhipa  export const inventoryLevelForecastChartOptions: Partial<ChartOptions> = {
    series: [
        {
            name: 'Inventory Forecast',
            color: '#2DBDAA',
            data: [],
        },

        {
            name: 'Delivery Schedule',
            color: '#405189',
            data: []
        }
    ],
    chart: {
        animations: {
            enabled: true,
            easing: 'easein',
            speed: 800,
        },
        height: 350,
        width: '100%',
        type: 'line',
        toolbar: {
            show: true,
            tools: {
                download: false,
                selection: true,
                zoom: true,
                zoomin: true,
                zoomout: true,
                pan: true,
                customIcons: [],
            },
            export: {
                csv: {
                    filename: '',
                    headerCategory: 'Data & Time',
                    headerValue: 'value',
                    //@ts-ignore
                    categoryFormatter(x) {
                        return new Date(x).toLocaleDateString() + " " +
                            new Date(x).getHours() + ":" + new Date(x).getMinutes() + ":" + new Date(x).getSeconds();
                    }
                },
                png: {
                    filename: '',
                },
            },
        },
    },
    stroke: {
        width: [5, 0],
        curve: 'straight',
        dashArray: [0, 8],
    },
    markers: {
        size: [0, 5],
        strokeWidth: 1,
        colors: ['#2DBDAA', '#405189'],
        hover: {
            size: 5,
        },
    },
    xAxis: {
        type: 'datetime',
        labels: {
            style: textStyleSettings,
            datetimeUTC: false,
            datetimeFormatter: {
                day: 'dd MMM',
                hour: 'HH:mm ',
            },
        },
    },
    yAxis: [
        {
            labels: inventoryLabelsSettings,
            title: {
                text: 'Inventory Left (gal)',
                style: textLabelStyle,
            },
            axisBorder: {
                show: true,
                color: '#2DBDAA',
                width: 1,
            },
        },
        {
            opposite: true,
            labels: deliveryScheduleLabelsSettings,
            title: {
                text: 'Delivery Schedule',
                style: textLabelStyle,
            },
            axisBorder: {
                show: true,
                color: '#405189',
                width: 1,
            },
        }
    ],
    tooltip: {
        shared: true,
        x: {
            format: 'dd/MM/yy HH:mm ',
        },
        y: {
            formatter: function (y) {
                if (typeof y !== 'undefined') {
                    return y.toFixed(2) + '';
                }
                return y;
            }
        },
    },
    grid: {
        borderColor: '#f1f1f1',
        show: true,
    },
    legend: {
        show: true,
        onItemClick: {
            toggleDataSeries: false,
        },
    },
};

**Comment by brianlagunas** [comment]
The required reproduction link was not provided. We will reopen this when the required link has been provided. Code snippets do not count.

**Comment by SStembridge** [comment]
Also, judging from the title, this is likely just a feature from the latest release: https://github.com/apexcharts/apexcharts.js/releases/tag/v3.53.0
(see enhancements section)
