### ISSUE TITLE
Mouse Wheel Zoom error in rangeBar type

### ISSUE THREAD

**Issue by SStembridge** [apexcharts/apexcharts.js#4680]
### Description

Using the mouse wheel on a chart makes everything disappear and checking the console shows an error/warning saying:
`axis.min cannot be greater than axis.max: swapping min and max`

Using the Home button in the toolbar does bring everything back, but using the mouse wheel always makes things disappear.

This doesn't appear to be affecting some other chart types but I didn't test much since the focus was on the rangeBar chart I have.

### Steps to Reproduce

1. Have a rangeBar type chart
2. Mouse over the chart
3. Use the mouse wheel

### Expected Behavior
Zooming the same as though clicking the zoom in/out buttons in the toolbar (but fast)

### Actual Behavior
Everything in the chart area disappears with a NaN on the x-axis

### Screenshots
In this screencap I demonstrate that the zoom tools in the toolbar work, then at the end I use the mouse wheel and you can see everything disappear:

https://github.com/user-attachments/assets/f00223ea-550c-4c42-9e8c-35fdc4c555ab

### Reproduction Link
https://codepen.io/SStembridge/pen/RwzqWMz

**Comment by javipaganOle** [comment]
What it does when you scroll over a graph is that the element reacts by zooming in/out. It is very uncomfortable because it does not let you scroll the page. If you disable the zoom it no longer reacts, but you lose the zoom which is sometimes very useful.

,zoom: {
     enabled: false,
},

I would leave it as an option for the developer. For example: zoomWheel: false

**Comment by SStembridge** [comment]
@javipaganOle that's a fine suggestion that I would also like to see, but my issue is that the mouse wheel zoom is broken entirely on rangeBar charts.

**Comment by Zordiac** [comment]
same issue here for me, please fix if possible

**Comment by junedchhipa** [comment]
As tested on 3.54.1, this is fixed.
