### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by mdansari20101** [apexcharts/apexcharts.js#4683]
Error when hovering over legends in Donut/Pie chart - "Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

There seems to be a bug in the Donut/Pie chart of ApexCharts. When hovering over the legend section, the following error is thrown:

"Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

This issue started occurring after a recent release. It was working perfectly before.

Steps to Reproduce:

- Create a Donut/Pie chart using ApexCharts.
- Hover over the legend section.
- Observe the error in the console.
- Expected Behavior: The chart should function without throwing errors when interacting with the legend.

Actual Behavior: Hovering over the legend results in the following error:

"Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

Additional Information:

This issue also occurs on the ApexCharts documentation example for the Donut chart.

Attached is a screenshot of the error for reference.
![Screenshot 2024-09-03 211456](https://github.com/user-attachments/assets/bcb6929e-d657-4fd4-b992-aa767f69e8fe)

**Comment by junedchhipa** [comment]
It will be shipped with the next release.

**Comment by mdansari20101** [comment]
@junedchhipa , When we are releasing the new version?

**Comment by eviltik** [comment]
fix available in the latest version 3.54.0, thx !
