### ISSUE TITLE
color_threshold doesn't work anymore when stroke_width is applied

### ISSUE THREAD

**Issue by markuswesterberg** [apexcharts/apexcharts.js#4685]
Updated to latest release and my charts with color thresholds don't show colors anymore where stroke width is used.

**Comment by brianlagunas** [comment]
Did not follow bug template instructions.

**Comment by markuswesterberg** [comment]
Hi Brian,

Sorry for that. I'm not a programmer. But you did understand the issue I
assume?


--

Markus Westerberg


Den tors 5 sep. 2024 kl 16:18 skrev Brian Lagunas ***@***.***
