### ISSUE TITLE
line graph goes blank for single point(weird behaviour)

### ISSUE THREAD

**Issue by zee0786** [apexcharts/apexcharts.js#4686]
I am trying to draw a line graph, but it fails to draw the graph if it has only one point to draw, except for the second last point.

please go through the following pen.

 **In this pen I have made two samples of data, one that works and the other just doesn't.**

https://codepen.io/zee0786/pen/OJYxQBO?editors=0010

**Comment by junedchhipa** [comment]
Hey @rosco54 I did some tests and it seems that this broke after v3.49.0 update.
Can you please check this one?
