### ISSUE TITLE
codepen iFrames on apexcharts.com/docs are broken

### ISSUE THREAD

**Issue by Radla** [apexcharts/apexcharts.js#4688]
### Description

Some of the iFrames of the Demo pages are broken (404) because of illegal characters in URL (codepen id in '')

### Steps to Reproduce

1.  open https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/ 
2. 404 on each iFrame
3. 

### Expected Behavior

400

### Actual Behavior

404

**Comment by junedchhipa** [comment]
fixed
