### ISSUE TITLE
3.53.0 introduces instability and/or browser crashes in area charts

### ISSUE THREAD

**Issue by mrash** [apexcharts/apexcharts.js#4690]
### Description

In 3.53.0, area charts with somewhat larger number of entries (say, 2,000 or more) start to crash the browser tab making it unresponsive. This is new behavior in 3.53.0 as 3.52.0 does not have this problem. This [gist](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1) has the file '[apexcharts_test.html](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1#file-apexcharts_test-html)' that reproduces this problem.

### Steps to Reproduce

1. Acquire the '[apexcharts_test.html](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1#file-apexcharts_test-html)' file from this [gist](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1).
2. Edit the apexcharts_test.html file to replace all instances of "../../apexcharts/" with whatever the correct path is for your system. There are a total of 12 instances of this - one for the ApexCharts 'styles.css' file, and 11 for the ApexCharts 'apexcharts.js' file.
3. With 3.52.0, observe that the entire page loads just fine - maybe slightly slow depending on how powerful your local system is.
4. With 3.53.0, observe that the same page loads extremely slowly and frequently just causes the browser tab to become unresponsive. You may need to reload a couple of times to reproduce this. I can easily produce new versions of this testing page if more graph entries are needed for reproduction purposes on your system.

### Expected Behavior
The expected behavior is the same in 3.53.0 as for 3.52.0. Note there is one minor exception which is the 'apexcharts_test.html' page does use the new "hidden" attribute for "Graph1" to hide 5 of the series by default. This feature was added in 3.53.0, so is ignored in 3.52.0. This appears to be unrelated to the main problem where the entire page becomes unresponsive.

### Actual Behavior
Under 3.53.0, the page becomes unresponsive after a couple of reloads.

### Screenshots

Under normal behavior (ApexCharts prior to 3.53.0), all graphs in 'apexcharts_test.html' are rendered fine. For example, "Graph4" and "Graph5" should be visible at the bottom of the page like this:

<img width="2122" alt="Screenshot 2024-09-08 at 3 51 03 PM" src="https://github.com/user-attachments/assets/1df75a7f-8f11-4194-a7a4-d587e8257b17">

After upgrading to 3.53.0, the page becomes unresponsive. You may need to reload a couple of times to reproduce this, but eventually this will happen and the page won't render Graph4 or Graph5 (as shown above) at all:

<img width="2114" alt="Screenshot 2024-09-08 at 4 00 01 PM" src="https://github.com/user-attachments/assets/c7e6fe21-9c0c-44ef-a54b-514404bd5433">

### Reproduction Link

This [gist](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1) has the file '[apexcharts_test.html](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1#file-apexcharts_test-html)' that reproduces this problem. As noted above, you will need to replace all instances of "../../apexcharts/" with whatever the correct path is for your system.

**Comment by brianlagunas** [comment]
Please provide a working sample that does not require any modifications for it to function. We need to be able to run your sample as-is to verify it's an issue. You can modify your gist to use the CDN instead of a hard file path. This way we can download the HTML file and run it directly.

**Comment by mrash** [comment]
Revisiting this (sorry for the delay). I've updated the gist to point to the CDN in [947b5442](https://gist.github.com/mrash/a0fb49a0ede002b22d8f8f23ab031de1/revisions) per your instructions @brianlagunas

**Comment by mrash** [comment]
Also I should note that this issue affects version 4.0.0 as well.

**Comment by mrash** [comment]
I'm honing in on a better reproduction scenario and will close this issue in favor of a new issue that provides better information.
