### ISSUE TITLE
Angular project missing hidden property from series option

### ISSUE THREAD

**Issue by KerimM** [apexcharts/apexcharts.js#4692]
### Description
On Angular project is missing hidden property from series as reported by documentation on official site

### Steps to Reproduce

1.  Read the  [https://apexcharts.com/docs/options/series/](https://apexcharts.com/docs/options/series/)
2. Look the ApexOptions Interface in /node_modules/ng-apexcharts/lib/model/apex-types.d.ts
3. 

### Expected Behavior
That you are able to use the hidden property

### Actual Behavior
Lacks the hidden property from series

### Screenshots

<img width="1434" alt="Screenshot 2024-09-09 alle 12 28 35" src="https://github.com/user-attachments/assets/2c73a450-5d69-4e18-9070-7e576d69117e">
<img width="652" alt="Screenshot 2024-09-09 alle 12 29 14" src="https://github.com/user-attachments/assets/dc9879ac-b13c-4705-8fb5-2ec86116b99b">

### Reproduction Link

The example is based on vue example but you can clearly see that doesn't work either
https://codesandbox.io/p/sandbox/vue-basic-example-forked-2q5w5q

**Comment by junedchhipa** [comment]
released ng-apexcharts@1.12.0 which should fix the issue
