### ISSUE TITLE
IE-11. Line chart is getting displayed out of boundaries

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#470]
In chrome the line chart is perfectly coming within the expected boundries, but in IE-11, Win 10, it is going out of boundaries as shown in the below chart.

Chrome: 
![image](https://user-images.githubusercontent.com/8254178/55418114-97faef80-558f-11e9-8719-0cc56f50c5ca.png)

IE-11:
![image](https://user-images.githubusercontent.com/8254178/55417528-7a795600-558e-11e9-94bc-a7c058a7e604.png)

The series that am trying to plot:
[
  [
    1553817600000,
    3
  ],
  [
    1554163200000,
    10
  ]
]

**Comment by junedchhipa** [comment]
A codepen or a console error would be helpful.
Please create a codepen for me to easily test it in IE11.

**Comment by irshadahmed** [comment]
Hi @junedchhipa  There is no error in browser console. IE doesn't seem to support codepen. However I have created the one - https://codepen.io/vjakair/pen/GLpvvd. Hope that helps.

**Comment by OriginalEXE** [comment]
Seems to be working fine when I test it in BrowserStack

![Screenshot from 2019-04-03 10-57-40](https://user-images.githubusercontent.com/2056251/55466402-628dea80-55ff-11e9-9f64-756c19e8a82e.png)

**Comment by irshadahmed** [comment]
Hi @OriginalEXE The issue exist with 3.6.4. It seem to got resolved in 3.6.5. I updated apex chart to use latest one and I confirm that this issue is fixed. Thank to you and @junedchhipa Much appreciated..
