### ISSUE TITLE
TickPlacement 'between' crashes stacked category chart

### ISSUE THREAD

**Issue by Zordiac** [apexcharts/apexcharts.js#4704]
### Description

When setting X Axis TickPlacement to 'between' in a stacked column chart with category axis, the chart crashes. Removing the setting or setting it to 'on' resolves the issue

### Steps to Reproduce

1. Create Chart
2. Add Multiple Y AXis
3. Add Multiple Column Series
4. Enable Stacking
5. Set X Axis to type Category and TickPlacement 'between'

See reproduction link below

### Expected Behavior
Chart to not crash

### Actual Behavior
Chart crashes

### Reproduction Link
https://jsfiddle.net/ygwsmcnj/1/

**Comment by junedchhipa** [comment]
This seems to be broken after 3.47.0 release.
Can you take a look, please @rosco54 ?
