### ISSUE TITLE
Add 'Gap' Property to Bar Plot Options

### ISSUE THREAD

**Issue by Thimows** [apexcharts/apexcharts.js#4706]
## Summary

When using a bar chart with multiple series, it would be very helpful to have access to a 'gap' property. This property adds gap spacing between the bars and makes the chart not only look nicer, but will allow for more types of designs to be implemented with the library.

## API Changes

We can have a value called 'gap' in the bar plotOptions. It can be a pixel amount for example.

## Examples

This is the chart we can create now:
![Mooie Grafieken ApexCharts (1)](https://github.com/user-attachments/assets/b8a953ea-bd51-485c-8091-0c916420fab4)

But with this change we could add a gap between the series like this:
![Mooie Grafieken ApexCharts](https://github.com/user-attachments/assets/f2635993-35fe-4539-9787-47401d0644bd)

If this is already possible and I have missed it please let me know! (:

**Comment by rosco54** [comment]
The current method to create a gap is to define a stroke width but set the colour of the stroke to transparent. Eg:

```
        stroke: {
          show: true,
          width: 2,
          colors: ['transparent']
        }
```

See the demo
https://apexcharts.com/javascript-chart-demos/column-charts/basic/

**Comment by Thimows** [comment]
Thanks @rosco54! This works great for normal bar charts. However, for Stacked Bar Charts this doesn't seem to work unfortunately as it seems to be ignoring the stroke width when stacking the bars (in the image below I've used a colored stroke to show the overlap):

<img width="795" alt=" 2024-09-27 om 14 53 14" src="https://github.com/user-attachments/assets/b5fec2b9-6293-4091-b8df-8c9d2d5c879f">


Could this be a bug?

**Comment by rosco54** [comment]
There's another demo chart with stacked bars and a gap. It uses white as
the stroke colour rather than transparent.

**Comment by junedchhipa** [comment]
Suggested workaround from rosco54 will be sufficient to achieve this.
