### ISSUE TITLE
radialBar padding / margins?

### ISSUE THREAD

**Issue by brandonburkett** [apexcharts/apexcharts.js#471]
Radial bars seem to have white space around the actual chart.  Is it possible to reduce this similar to how grid has padding options?

**Comment by junedchhipa** [comment]
Nope, if you provide `chart.height`, it should squeeze the radialBar based on available width/height ratio.

**Comment by brandonburkett** [comment]
Thank you.  I was able to reduce some by using `offsetY` and a max-height container div (smaller than `client.height`).

```javascript
<div style={{ maxHeight: '350px' }}>
  <Chart
    type="radialBar"
    series={[70]}
    options={{
      chart: {
        height: '400px',
      },
      plotOptions: {
        radialBar: {
          offsetY: -25,
          hollow: {
            size: '50%',
          },
        },
      },
      labels: ['Engagement'],
    }}
  />
</div>
```

**Comment by junedchhipa** [comment]
Great! 👍

**Comment by mburger81** [comment]
We have the same problem, and think this is really an important feature.
The chart should fill the whole space available, the margin is really a lot, we would like use this chart in mobile use, it is nearly impossible use it there for that reason.

**Comment by brandonburkett** [comment]
My solution only worked for desktop :( It would take some responsible styles to get it to work for mobile.

Agreed it would be ideal if apex made use of the container space allowed to it.

**Comment by mburger81** [comment]
We are not an expert of canvas and svg, we had a look to source code and did some experiments.
But there is no way for us to figure out how we can implement such a thing in this technology :| To much effort for someone outside like us

**Comment by rinogo** [comment]
Using `chart.offsetY` helped a bit, but only for the top margin.

Inspired by [this comment](https://github.com/apexcharts/apexcharts.js/issues/1272#issuecomment-591388290), I was able to crop out unnecessary top and bottom margins using negative values for [`grid.padding.top` and `grid.padding.bottom`](https://apexcharts.com/docs/options/grid/). You can do something similar with the left and right padding as well. My code ended up looking something like this:

```
            var options = {
                ...
                //Remove the excess padding (https://github.com/apexcharts/apexcharts.js/issues/1272#issuecomment-591388290)
                grid: {
                    padding: {
                        top: -20,
                        bottom: -15
                    }
                },
                ...
            };
```
Hope this helps! 😁

**Comment by van9petryk** [comment]
> Inspired by [this comment](https://github.com/apexcharts/apexcharts.js/issues/1272#issuecomment-591388290), I was able to crop out unnecessary top and bottom margins using negative values for [`grid.padding.top` and `grid.padding.bottom`](https://apexcharts.com/docs/options/grid/).

Are you sure this is working for radialBar? Just tested not work. Can you provide some example (on stackblitz, codepen)?

**Comment by rinogo** [comment]
@van9petryk If you leave some kind of contact info here, I can privately send you an example.

**Comment by MrMooky** [comment]
Having issues with radialBar as well. The suggested workarounds don't really work for me. Because of the huge padding / margin, I am not getting this to work as needed. Here is what I want to end up with:

<img width="408" alt="Screenshot 2022-06-06 at 11 35 29" src="https://user-images.githubusercontent.com/3603346/172136147-610e9980-ea92-4fe9-9d0a-f97dade8760e.png">

And this is where I'm at:

<img width="663" alt="Screenshot 2022-06-06 at 11 38 03" src="https://user-images.githubusercontent.com/3603346/172136372-33559acc-5a8d-4005-8612-d85cc852bd91.png">

Width and height are set to `100`, yet only the width is respected. The blue area is too big, compared to the actual chart. Also, the 2 strokes gets way too slim when the chart is that size. I tried to change the stroke width, but setting it to anything bigger than 3, the chart is not showing anymore.

**Comment by rumitr** [comment]
@MrMooky, did you figure it out?

**Comment by MrMooky** [comment]
@rumitr I don't really remember. But I think I switched to another library that generated SVG charts instead of using canvas.
