### ISSUE TITLE
Stop forceful xaxis conversion to numeric type

### ISSUE THREAD

**Issue by OriginalEXE** [apexcharts/apexcharts.js#472]
## Codepen

I was not able to reproduce this in a codepen unfortunately. For some reason it's not happening there:
https://codepen.io/anon/pen/dLoQJX

## Explanation

- What is the behavior you expect?
If I set `xaxis` `type` to `'categories'`, I expect it to be that way 
- What is happening instead?
apexcharts converts it to numeric and removes my categories unless I use `xaxis.tickPlacement = 'between'` which I don't want

Not sure why this was introduced, but I don't see the logic in forcing it?

it's this line:
https://github.com/apexcharts/apexcharts.js/blob/94e059d46e0c1bd4fce47959841bb296c45af9a3/src/modules/settings/Config.js#L111

**Comment by junedchhipa** [comment]
If you do `xaxis.tickPlacement: on`, it is essential to convert the xaxis to numbers to remove the padding from left and right.

if you notice the xaxis in `xaxis.tickPlacement = 'between'`, the ticks calculation is different than numeric. The numeric x-axis allows drawing the chart from end to end (calculating from 0 to n).

Do you face any issues with this force conversion during updates? If yes, what issues?

**Comment by OriginalEXE** [comment]
The problem I am facing is that conversion removes my categories, and so I get less xaxis labels than I expect (I can no longer effectively force their number).

More specifically, I define up to 21 categories, but the conversion process removes them and so only up to 6 or 7 are displayed.

**Comment by junedchhipa** [comment]
If that's the case, the conversion logic needs to be modified.
I am afraid I will have to remove the `tickPlacement` setting if I remove the force conversion as `tickPlacement: 'on'` will only work for numeric xaxis.

I will try to find the best way to deal with this.

**Comment by OriginalEXE** [comment]
I see. Is there a reason `on` can't work with non-numeric xaxis? Seems like the logic for placement is already there if it can find the `between` values, perhaps that is what can be tackled?

I'll try to take a look tomorrow when I'm back at work.

**Comment by junedchhipa** [comment]
> More specifically, I define up to 21 categories, but the conversion process removes them and so only up to 6 or 7 are displayed.


I can not reproduce this issue on my side. Can you try some other demo (codesandbox / jsfiddle)?

**Comment by OriginalEXE** [comment]
I wasn't able to reproduce it either when creating the issue. I'll try again tomorrow.

How come that the conversion is not happening in the demo I have posted?

**Comment by junedchhipa** [comment]
I was able to produce it. It only happened when data-points exceeded 20.
I had a condition to reduce the tickAmount in numeric x-axis when it was more than 20.
Will modify that condition.

**Comment by OriginalEXE** [comment]
Awesome, glad to hear you were able to reproduce it, thank you for your efforts!

**Comment by michaeljakob** [comment]
I'm afraid this issue with "we only support 20 values" might still exist >> https://github.com/apexcharts/apexcharts.js/issues/965

**Comment by bercikboris** [comment]
hello,
is there any way to bypass / disable convertCatToNumeric to X axis?
thank you

**Comment by snakysnake** [comment]
happened to me aswell.. it does not always happen after 20plus but with over 300values on xaxis it happens..
the chart looks sh*t with 300 vals on xaxis anways but still,...
