### ISSUE TITLE
Mark a series as disabled by default?

### ISSUE THREAD

**Issue by PaulCombal** [apexcharts/apexcharts.js#4721]
## Summary

When a chart is loaded, we can click on the series name to hide it. It "disables" the series. It would be amazing to be able to load series "disabled" by default.

## API Changes

The series definition could be like this for example:
```js
[{name: 'name', disabled: true, data: [...]}]
``` 

## Intended Use Case

I have a series with lesser importance, which I still want on the chart if needed. I want to hide them by default to avaid the chart being too crowded. People should still have the option to turn it back on.

**Comment by junedchhipa** [comment]
Please post your codepen example to show what you did with "hidden" property

**Comment by PaulCombal** [comment]
My bad, turns out it was a bug with with "3.36.3" that was solved by upgrading to latest. Thank you for your work!
