### ISSUE TITLE
Const width between multiple dynamic yaxis

### ISSUE THREAD

**Issue by Diegolml** [apexcharts/apexcharts.js#473]
I'm currently doing a project where I can have multiple charts in a single window, they are all synchronized so the xaxis width has to be the same. The problem that I'm encountering is that because of the yaxis labels I can't align them. 

![charts](https://user-images.githubusercontent.com/24472778/55432307-2ce1f680-5558-11e9-833b-85959d890089.PNG)

Is there a way that i can fix all the yaxis labels to have the same width or padding?

**Comment by junedchhipa** [comment]
You can assign a minWidth to yaxis labels by

```javascript
yaxis: [{
  labels: {
    minWidth: 140
  }
}, {
  labels: {
    minWidth: 140
  }
}]
```

This will also prevent synced chart tooltip issues when hovering.

**Comment by Diegolml** [comment]
I already tried that. But it seems like it doesn't apply the minWidth when there are multiple yaxis in the same side.

**Comment by junedchhipa** [comment]
Ah! Ok then, I will take another look.

**Comment by Diegolml** [comment]
Here's a codesandbox to explain myself better. Note that i tried the minWidth you suggested but it doesn't seem to apply it.

https://codesandbox.io/s/x9xn4okz94

**Comment by Diegolml** [comment]
Worked great! Thanks!
