### ISSUE TITLE
Zoom Selection and Panning Not Supported on Mobile Devices

### ISSUE THREAD

**Issue by madhuri-predictive** [apexcharts/apexcharts.js#4733]
Description: Currently, the zoom selection and panning functionalities in ApexCharts are not supported on mobile devices. This limitation affects the user experience, especially for applications that require data interaction on smaller screens.

Steps to Reproduce:

Open the chart on a mobile device.
Attempt to use zoom selection and panning features.
Expected Result: Users should be able to use zoom selection and panning functionalities seamlessly on mobile devices.

Actual Result: The zoom selection and panning features are not responsive or functional on mobile devices.
![Image (10)](https://github.com/user-attachments/assets/e185c70c-604a-4099-8dca-8927b064bb9d)

**Comment by brianlagunas** [comment]
Did not provide required reproduction app.
