### ISSUE TITLE
Zoom with the mouse scroll button always activate when "selection" is enabled

### ISSUE THREAD

**Issue by antoniolopezmc** [apexcharts/apexcharts.js#4735]
### Steps to Reproduce

1. Create a column chart.
2. Enable the "selection" option (options -> chart -> selection -> enabled = true).
3. Disable the "zoom" option (options -> chart -> zoom -> enabled = false AND chart -> toolbar -> tools -> disable all tools related to the zoom).

### Expected Behavior

Users should be able to select a range in the column bar, but not zooming the chart.

### Actual Behavior

Users can  select a range in the column bar (which is correct), but they also can zooming the chart with the mouse scroll button.

Now, I am using the version 2.52 of the library, in which the zooming with the mouse scroll button is not implemented.

### Screenshots

![image](https://github.com/user-attachments/assets/24f04c7a-61a2-47c5-a7a0-651857d61e2f)

![image](https://github.com/user-attachments/assets/40842a95-1bfa-490b-88f5-eda2b8e02516)

After using the mouse scroll button inside the chart, the second image should not be zoomed.

### Reproduction Link

JAVASCRIPT CODE

```
var options = {
    chart: {
        type: "bar",
        toolbar: {
            show: true,
            tools: {
                download: true,
                selection: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
                customIcons: []
            }
        },
        selection: {
            enabled: true,
            type: 'x',
            xaxis: {
                min: 0,
                max: 100,
            }
        },
        zoom: {
            enabled: false
        }
    },
    series: [{
        name: "count",
        data: [
            [0, 50],
            [1, 48],
            [10, 99],
            [50, 75],
            [100, 87]
        ]
    }],
    xaxix: {
        type: 'numeric'
    },
};
var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
```

CSS CODE

```
#chart {
  max-width: 650px;
  margin: 35px auto;
}
```

HTML CODE

```
<div id="chart">
</div>
```

**Comment by brianlagunas** [comment]
Please provide the require reproduction codepen link. Code snippets do not count.

**Comment by antoniolopezmc** [comment]
https://codepen.io/antoniolopezmc/pen/yLmYGoV

Here is the fork  :)

**Comment by SkyEmie** [comment]
Hi all, same behavior was observed on my side, I had to downgrade the version
(Thank you for taking the time to make this issue 😊)
