### ISSUE TITLE
Area Charts : Fill color isn't applied when color is rgb()

### ISSUE THREAD

**Issue by Slokilla** [apexcharts/apexcharts.js#4742]
### Description

When using a rgb() color, the filling in the graph does not take into account the opacity.

### Steps to Reproduce

1. Use this fill objet : 
```
 {
        colors: ['rgb(236, 22, 26)'],
        opacity: [0.1],
        type: 'solid'
 }
```

See that the graph is full opaque.
2. Replace the color by the exact same hexadecimal color : 
```
 {
        colors: ['#EC1A16'],
        opacity: [0.1],
        type: 'solid'
 }
```

See that this time, the graph is not opaque.

### Expected Behavior

The graph should not be opaque.

### Screenshots

With rgb : 

![image](https://github.com/user-attachments/assets/cb89be14-6c4a-44a8-bd6c-44cff3181437)

With hex : 

![image](https://github.com/user-attachments/assets/40d92a22-3a0d-4ec6-820a-d23661e0e4c8)

### Reproduction Link

With rgb : https://codepen.io/slokilla/pen/bGXpBge

With hexa : https://codepen.io/slokilla/pen/LYwNbbM

**Comment by junedchhipa** [comment]
Not a bug. You can convert the rgb to hex with a function like this

```js
function rgb2hex(rgb) {
    rgb = rgb.match(
      /^rgba?[\s+]?\([\s+]?(\d+)[\s+]?,[\s+]?(\d+)[\s+]?,[\s+]?(\d+)[\s+]?/i
    )
    return rgb && rgb.length === 4
      ? '#' +
          ('0' + parseInt(rgb[1], 10).toString(16)).slice(-2) +
          ('0' + parseInt(rgb[2], 10).toString(16)).slice(-2) +
          ('0' + parseInt(rgb[3], 10).toString(16)).slice(-2)
      : ''
  }
```

**Comment by rosco54** [comment]
Or use rgba() color format:

colors: ['rgb(236, 22, 26, 0.1)'],

**Comment by Slokilla** [comment]
Mh, thanks for your answers. I do not understand in which scope it's not a bug. Actually, there is a reproducible way to have a not working fill opacity attribute. The minimal fix should be to update the documentation, adding that opacity works only with an hexadecimal color. 

A more valuable fix should be to integrate opacity in an rgba() call and use it when color is rgb and opacity is given.
