### ISSUE TITLE
3.54 does not render tooltips on majority of graph types

### ISSUE THREAD

**Issue by Multidmedia** [apexcharts/apexcharts.js#4748]
### Description

The most recent 3.54 does not render/display tooltips that would normally appear over the graph elements. This occurs for every type of graph I tested (Polar, Bar etc) - the only expcetion was Line graph which did render tooltips (however, as a side issue, line graph plot points were all rendered a few pixels lower than previous versions, so there is clearly some sort of rendering issue/miscalculation).

### Steps to Reproduce

Use any demo graph code, tooltips will not appear when using version 3.54 (all previous versions work)

**Comment by brianlagunas** [comment]
Did not follow bug template instructions.
