### ISSUE TITLE
First and last bar data labels get disappeared in mixed chart when line is configured on left y axis and 2 bars are configured on right y axis.

### ISSUE THREAD

**Issue by Krishna-Chidrawar** [apexcharts/apexcharts.js#4752]
### Steps to Reproduce

1. Create a Mixed Chart with line configured in left y axis and 2 bars configured in right yaxis.
2. Expand the chart horizontally.
3. When expanded beyond certain limit the first and last bar data label gets disappeared.
4. Below is the link of codepen for demonstration.

### Screenshots 
<img width="960" alt="Data Labels not visible" src="https://github.com/user-attachments/assets/d1486400-fd4b-4a8b-94a7-bea7cef7d0f1">

**Comment by brianlagunas** [comment]
Did not provide reproduction link.
