### ISSUE TITLE
Heatmap Chart: Unable to Display Duplicate Y-Axis Labels

### ISSUE THREAD

**Issue by ZahidChandio** [apexcharts/apexcharts.js#4757]
I encountered an issue where duplicate labels on the y-axis were not allowed. In the image below, the y-axis represents the days of the week. As a result, some labels, like Tuesday ('T') and Saturday ('S'), are missing. You can check the sample in the provided CodeSandbox.

![image](https://github.com/user-attachments/assets/9f34996a-f5e6-414a-be16-24c223821147)

These are the y-axis options I tried.

```
yaxis: {
      forceNiceScale: false,
      showAlways: true,
      show: true,
      showForNullSeries: true,
      crosshairs: {
        show: true
      },
      labels: {
        show: true,
        formatter(val, opts) {
          console.log('opts', opts);
          return val?.toString();
        }
      }
    }
```

I am using "^3.54.0" version of apexcharts.

**Reproduction link**
https://codesandbox.io/p/sandbox/apexcharts-heatmap-p6ddt7

**Comment by brianlagunas** [comment]
Did not provide required reproduction link.

**Comment by ZahidChandio** [comment]
@brianlagunas comment updated, please reopen the issue.
