### ISSUE TITLE
Reopening Issue #2676 - top most item on stacked bar chart do not always have rounded corners

### ISSUE THREAD

**Issue by ktoo-illuminexai** [apexcharts/apexcharts.js#4758]
### Description
Same issue as Issue #2676. The stacked bar chart does not have rounded corners if the data for the top most series is 0.

### Steps to Reproduce

1. Create stacked bar chart with plotOptions set to:
`plotOptions: {
    bar: {
      columnWidth: '60%',
      borderRadius: 4,
      borderRadiusWhenStacked: 'last',
      borderRadiusApplication: "end",
    }
  },`
2. Use the stacked bar chart option: 
`chart: {
    type: 'bar',
    stacked: true
  },`
4. Use the following series to plot data:
`setSeries([
        {
          name: 'A',
          data: [1,2,3],
        },
        {
          name: 'B',
          data: [2,0,4],
        },
      ]);`

### Expected Behavior
All 3 bars should have rounded corners.

### Actual Behavior
The first and last bar have rounded corners, but the middle one doesn't.

### Screenshots
![image](https://github.com/user-attachments/assets/8d575e8c-e0b9-4442-b651-22374bc95b76)

### Reproduction Link
https://codepen.io/ktooIlluminex/pen/wvVggRW

**Comment by successbyte** [comment]
Hi would you assign this issue to me please
thanks

**Comment by junedchhipa** [comment]
This is recently fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/15afc7b8051eb14c38d19b6cc2a5b7e4987130f0).
Please wait for the next release 3.54.1 for this to be fixed.

**Comment by successbyte** [comment]
Ok thanks I will find another issue
