### ISSUE TITLE
Dynamic set Title name on chart

### ISSUE THREAD

**Issue by sanymochi** [apexcharts/apexcharts.js#476]
Hi
	I have render **(#pic1)** chart on click of other chart **(#pic2)** . so is it possible to dynamically set Title in **(#pic1)**.?
       I have tried with several tests but none have worked out yet.

**Ex:** If I click on **PENS** from **#pic2**  chart then **#pic1** title should be **PENS by Billing** 

Thanks in advance for your help

**Pic 1:** 
![pic1](https://user-images.githubusercontent.com/40659606/55533161-ff1ebe00-56cd-11e9-99e8-38e1c4c3efe8.png)

**Pic 2:**
![pic2](https://user-images.githubusercontent.com/40659606/55533164-047c0880-56ce-11e9-8198-54ad313f3464.png)

**Comment by junedchhipa** [comment]
Can you post a full working example on codepen?

I think, `updateOptions()` method should be enough to update anything which you set in config. Please post your code so I can update that same example.

**Comment by sanymochi** [comment]
Yes It worked! Thank you so much!

**Comment by nitramreffehcs** [comment]
what a waste of space, please, i landed here because i'm trying to put a title on a pie chart, EXACTLY like those screenshots, but, no code ? why ??
