### ISSUE TITLE
Pie Chart Label Fails to Update

### ISSUE THREAD

**Issue by headless-kjh** [apexcharts/apexcharts.js#4775]
### Steps to Reproduce

1.  Setting config
2. Re-initilaize config options labels
3. Not working

### Actual Behavior

    type: "pie",
    height: 250,
    series: [],
    options: {
        chart: {
            width: 250,
            type: "pie",
        },
        colors: [
            "#62B2FD",
            "#9BDFC4",
            "#F99BAB",
            "#FFB44F",
            "#a3e635",
            "#6ee7b7",
            "#67e8f9",
            "#93c5fd",
            "#a78bfa",
            "#f472b6",
        ],
        labels: [],
        legend: {
            show: false,
        },
        responsive: [
            {
                breakpoint: 480,
                options: {
                    chart: {
                        width: 200,
                    },
                },
            },
        ],
    },

### Screenshots
<img width="352" alt="image" src="https://github.com/user-attachments/assets/ff411dd9-26e2-4677-9728-a328f76f73f1">
<img width="611" alt="image" src="https://github.com/user-attachments/assets/d337755d-d9a1-46ec-b54d-57ad5066522f">

**Comment by brianlagunas** [comment]
Reproduction link not provided
