### ISSUE TITLE
Fix for https://github.com/apexcharts/apexcharts.js/pull/4760 did not make it into 3.54.1 

### ISSUE THREAD

**Issue by 331studios-dev** [apexcharts/apexcharts.js#4776]
### Steps to Reproduce

1. Look at the code in src/common/bar/Helper.js line 254 - fix exists in master/mainline branch.
2. Look at PR https://github.com/apexcharts/apexcharts.js/pull/4760
3. Code is merged into mainline with 3.54.1 build/releasee label
4. 3.54.1 package release does not contain the fix (see screenshot).

### Expected Behavior
Code in 3.54.1 has the fix

### Actual Behavior
Code in 3.54.1 does NOT have the fix

### Screenshots
<img width="1556" alt="image" src="https://github.com/user-attachments/assets/18a78612-ff99-47ed-94ce-d227e33baff4">

### Reproduction Link

https://codepen.io/apexcharts/pen/bxzgZJ - no codepen necessary

**Comment by junedchhipa** [comment]
Released v4.0.0 which should have the fix.

**Comment by 331studios-dev** [comment]
@junedchhipa Thank you!
