### ISSUE TITLE
Categories in Horizontal Box Plot do not work

### ISSUE THREAD

**Issue by Zordiac** [apexcharts/apexcharts.js#4779]
### Description

Hi, categories in a horizontal box plot do not work, see attached below

### Steps to Reproduce

1. Open fiddle, see that categories are not working
2. set horizontal to false in options, see that categories do work

### Expected Behavior
Categories should show the given list of categories, instead of the indexes

### Actual Behavior
They show the indexes instead of the categories

### Screenshots
How it looks in horizontal mode:
![image](https://github.com/user-attachments/assets/c5c0ecbd-ed35-4258-9109-9410ecd476c1)
In vertical Mode:
![image](https://github.com/user-attachments/assets/1c55605d-47d1-4db6-b63c-155d69ff05dd)

### Reproduction Link
https://jsfiddle.net/uwmtzfk1/4/

**Comment by junedchhipa** [comment]
It looks like the array format doesn't work for boxplot, I will investigate later.
Meanwhile, use the xy series format for the time being.

```javascript
let options = {
  series: [{
    name: 'name1',
    type: "boxPlot",
    data: [
      {
        x: "cat1",
        y: [2, 21, 51, 74.5, 100],
      },
      {
        x: "cat2",
        y: [2, 21, 51, 74.5, 100],
      },
      {
        x: "cat3",
        y: [2, 21, 51, 74.5, 100],
      },
      {
        x: "cat4",
        y: [2, 21, 51, 74.5, 100],
      }
    ]
  }],
  chart: {
    height: 350,
    type: 'boxPlot'
  },
  plotOptions: {
  	bar: {
    	horizontal: true
    },
  },
};

const chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
```
