### ISSUE TITLE
Outliers don't work in horizontal box plot

### ISSUE THREAD

**Issue by Zordiac** [apexcharts/apexcharts.js#4780]
### Description
Outliers don't work in horizontal box plot

### Steps to Reproduce

1. Create horizontal box plot
2. add boxplot and scatter series
3. scatter series are plotted incorrectly

### Expected Behavior
Outliers should be shown correctly

### Screenshots

![image](https://github.com/user-attachments/assets/612a29b0-93b9-4ec7-b170-561af842c455)

### Reproduction Link

https://jsfiddle.net/uwmtzfk1/5/

**Comment by Zordiac** [comment]
If anybody has the same issue: I was able to get around this by using point annotations. For some reason, those are displayed correctly, but scatter points are not.

**Comment by junedchhipa** [comment]
@Zordiac A scatter chart won't render correctly in horizontal axis. So, I have another way to solve the issue.
We will use ApexCharts' goals property to achieve this (similar to https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-markers/)

I am currently working on it and will ship it in the next release.

**Comment by beldogueto** [comment]
Hi @junedchhipa!

Taking advantage of this post to ask: Do you think it would be possible to add the boxplot whiskers to the bar goals property? This would be great to show the deviations

![image](https://github.com/user-attachments/assets/4650cf58-8c90-4652-b7d0-fc867c72c92f)
![image](https://github.com/user-attachments/assets/843a55d0-5db7-41e9-bcdd-fae46ddc52ed)
