### ISSUE TITLE
Bad data points connection

### ISSUE THREAD

**Issue by barnaudvarhelyi** [apexcharts/apexcharts.js#4781]
### Description

The problem is that the chart is ordering the provided data by x-axis, but does not connect the points in this order

### Expected Behavior

Connect the points in order as the data

### Actual Behavior

Connects the points in original order

### Screenshots

![image](https://github.com/user-attachments/assets/932efb2b-a293-4f0f-92d0-607cce190b32)

### Reproduction Link

https://codepen.io/somaradoczi/pen/ZEgored

**Comment by junedchhipa** [comment]
For a timeline or a numeric x-axis, data should be sorted before feeding to ApexCharts. ApexCharts doesn't modify the data.
