### ISSUE TITLE
Add color range legend of heatmap

### ISSUE THREAD

**Issue by bunnyxt** [apexcharts/apexcharts.js#479]
**Describe the solution you'd like**
A legend bar to show the range of number in different color block.

**Additional context**
Expected legend like this(in google analytics): 
<img width="312" alt="QQ20190404-234229@2x" src="https://user-images.githubusercontent.com/32478279/55569025-6753bb00-5733-11e9-9469-ee00710b1526.png">

**Comment by jlil** [comment]
@junedchhipa any plans on adding this?
