### ISSUE TITLE
Javascript error - Charts do not render

### ISSUE THREAD

**Issue by PetrusSmit30025087** [apexcharts/apexcharts.js#4792]
When trying to render the charts and populate with data we get the following console error:

apexcharts:38 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'node')
As far as I can see this is the code snippet that breaks:
 key: "clearDomElements",
            value: function(t) {
                var e = this
                  , i = t.isUpdating
                  , a = this.w.globals.dom.Paper.node;
                a.parentNode && a.parentNode.parentNode && !i && (a.parentNode.parentNode.style.minHeight = "unset");
                var s = this.w.globals.dom.baseEl;
                s && this.ctx.eventList.forEach((function(t) {
                    s.removeEventListener(t, e.ctx.events.documentEvent)
                }
                ));
                var r = this.w.globals.dom;
                if (null !== this.ctx.el)
                    for (; this.ctx.el.firstChild; )
                        this.ctx.el.removeChild(this.ctx.el.firstChild);
                this.killSVG(r.Paper),
                r.Paper.remove(),
                r.elWrap = null,
                r.elGraphical = null,
                r.elLegendWrap = null,
                r.elLegendForeign = null,
                r.baseEl = null,
                r.elGridRect = null,
                r.elGridRectMask = null,
                r.elGridRectBarMask = null,
                r.elGridRectMarkerMask = null,
                r.elForecastMask = null,
                r.elNonForecastMask = null,
                r.elDefs = null
            }
        }]),
We use the cdn link to reference apex charts
It has worked previously, we have not changed our code. This is our code:

function renderProtocolChart(data) {
    let chartData = []
    let chartLabels = []
    if (data != null) {
        for (let i = 0; i < data.length; i++) {
            chartData.push(data[i].amount)
            chartLabels.push(data[i].name)
        }
    }
    var options = {
        chart: {
            id: "chart-bar-protocol",
            width: '100%',
            height: 280,
            type: 'bar',
            toolbar: {
                show: false
            },
            shadow: {
                enabled: false,
            },
            colors: colorPalette,
        },
        colors: colorPalette,
        plotOptions: {
            bar: {
                distributed: true,
                horizontal: true
            },
            colors: colorPalette,
        },
        series: [
            {
                name: "Protocol",
                data: chartData
            }],
        xaxis: {
            name: 'Total',
            categories: chartLabels
        },
    };
    if (protocolChart == null) {
        protocolChart = new ApexCharts(document.getElementById("chart-bar-protocol"), options);
        protocolChart.render();
    }
    else {
        protocolChart.updateOptions(options)
    }
}

**Comment by brianlagunas** [comment]
Did not follow bug template instructions

**Comment by eyal-rozenberg** [comment]
I also encountered this issue in pie chart. 
It does not occur always. 
It happens when using the 4.0.0 library. works well in 3.5.x
Where can I find the bug template instructions?
