### ISSUE TITLE
Can't use rgba color for heatmap charts

### ISSUE THREAD

**Issue by tonghohin** [apexcharts/apexcharts.js#4793]
### Steps to Reproduce

1. Set up a basic heatmap chart and set the color to a rgba color, e.g. colors: ["rgba(226, 163, 75, 0.4)"]

### Expected Behavior
Use the provided rgba color.
### Actual Behavior
All cells are in gray.

**Comment by brianlagunas** [comment]
Did not provide reproduction link.
