### ISSUE TITLE
Combine array values on toggle?

### ISSUE THREAD

**Issue by mabel69** [apexcharts/apexcharts.js#480]
Hi there,

Is there a way I can combine 2 series array values of a chart when toggled?

Sorry if this is a stupid request - I'm going through the documentation and I haven't seen anything related to this.

<img width="346" alt="Screen Shot 2019-04-04 at 23 08 59" src="https://user-images.githubusercontent.com/49292774/55592010-15a93180-572f-11e9-8af4-c329495730d0.png">

Thanks!

**Comment by junedchhipa** [comment]
Sorry, I didn't quite get what you're trying to achieve. Can you please elaborate?

**Comment by junedchhipa** [comment]
Closing as no response.
