### ISSUE TITLE
Toolbar customize icons not working

### ISSUE THREAD

**Issue by llagundimao** [apexcharts/apexcharts.js#481]
## Explanation
I'm trying to customize the icon on the toolbar. I'm trying to change the icon of the hamburger and try to add a new one but it's not working. I follow the documentation on the website but still no luck. Please help. Thanks in advance.

```javascript
chart: {
     toolbar: {
      tools: {
        download: '<img src="IMG_PATH" width="50" height="20" />',
        customIcons: [
          {
            icon: '<img src="IMG_PATH" class="ico-download" width="20">',
            index: 0,
            title: '',
            class: 'custom-icon',
            click: () => {
              console.log('clicked PRINT!');
            }
          }
        ]
      }
    }
  }
```

![Screen Shot 2019-04-05 at 3 01 28 PM](https://user-images.githubusercontent.com/3871577/55609652-c9540500-57b3-11e9-9e14-49cc644e9578.png)

**Comment by junedchhipa** [comment]
I just tried your code
```javascript
chart: {
    toolbar: {
        tools: {
            download: '<img src="../../assets/images/1101098.png" width="20" height="20" />',
        }
    }
}
```


Here is the result
![Screen Shot 2019-04-05 at 2 24 02 PM](https://user-images.githubusercontent.com/17950663/55616022-85123600-57ae-11e9-85a1-fceae1ebacee.png)

**Comment by llagundimao** [comment]
What is not working on my code? Did I do something wrong?

**Comment by junedchhipa** [comment]
Maybe the path you're setting doesn't exist?
Try an absolute path and see if it works.

**Comment by faizanahmed104** [comment]
i'm trying to add mui icon but its not working , anyone know how to do with material ui icons in a react ts project?

**Comment by VelaJafet** [comment]
> i'm trying to add mui icon but its not working , anyone know how to do with material ui icons in a react ts project?

You must use the <img> tag, you can download the icon's PNG,I did it in this way

**Comment by lhllyra** [comment]
I was able to make it work by transforming my custom icon through an svg tag and instantiating it as a string literal constant, then calling this constant as my download, such as the image below shows (apexcharts v3.40.0, react-apexcharts v1.4.0):

![image](https://github.com/apexcharts/apexcharts.js/assets/32777247/b9be0787-0042-4261-835a-409acf69560a)

![image](https://github.com/apexcharts/apexcharts.js/assets/32777247/84997f90-90cc-4489-a1fd-e321b933d861)
