### ISSUE TITLE
States hover animation is broken with v4.0.0 - tested for heatmap

### ISSUE THREAD

**Issue by dschweinbenz** [apexcharts/apexcharts.js#4810]
### Description

With ApexCharts v4.0.0 the states hover animation seems to be broken. As i can not find a change regarding this functionality in the changelog i assume this is a bug. 

### Steps to Reproduce

1. Use ApexCharts v4.0.0 and create a heatmap
2. Before v4 the hover state was a default, but even defining the options as documented [here](https://apexcharts.com/docs/options/states/) does not work:
`states: {
    normal: {
        filter: {
            type: 'none',
            value: 0,
        }
    },
    hover: {
        filter: {
            type: 'darken',
            value: 0.15,
        }
    },
    active: {
        allowMultipleDataPointsSelection: false,
        filter: {
            type: 'darken',
            value: 0.35,
        }
    }
  }`

### Expected Behavior

Hover effect is applied

### Actual Behavior

No hover effect is applied

### Screenshots

Hovering the item changes the color:
![grafik](https://github.com/user-attachments/assets/8d6c35a9-a7b8-4c22-b540-6e38198268d8)

### Reproduction Link

v4.0.0 https://codepen.io/Schweini/pen/rNXRPGO

v3.56.1 https://codepen.io/Schweini/pen/yLmwZxy

**Comment by junedchhipa** [comment]
This is fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/bf973ba38fb1e7bdab862b3c759c129cffc6351b)
A new patch version is going to be released soon.
