### ISSUE TITLE
4.0.0 Cannot find @type/type definition file error in node modules

### ISSUE THREAD

**Issue by sdmakwana** [apexcharts/apexcharts.js#4825]
Ok I am using "apexcharts": "^4.0.0" in my angular app @18.2.4 with the plugin "ng-apexcharts": "^1.10.0" now in the,
 
 "apexcharts": "^4.0.0" it gives me the error that: 
```
Error: node_modules/ng-apexcharts/lib/chart/chart.component.d.ts:1:23 - error TS2688: Cannot find type definition file for 'projects/ng-apexcharts/node_modules/apexcharts/types/apexcharts'.

1 /// <reference types="projects/ng-apexcharts/node_modules/apexcharts/types/apexcharts" />
```

I have tried changing the packages version and also tried installing the @types/apexcharts which does not exits(correct me if I am mad).

Do anyone else has this problem?

Thanks in advance.

**Comment by junedchhipa** [comment]
This should be fixed with `ng-apexcharts@1.5.0`
