### ISSUE TITLE
x-axis datetime label misaligned with categories

### ISSUE THREAD

**Issue by valeLib** [apexcharts/apexcharts.js#483]
## Codesandbox

 [codesandbox](https://codesandbox.io/embed/n9x5z64w6m?fontsize=14) 

## Explanation

I have an issue with the x-axis ticks values when working with dates with format. The tick values misaligned, showing the previous month instead of the corresponding one.

Is there a fix for this?

**Comment by junedchhipa** [comment]
Shows the correct x-axis labels aligned with the categories to me.
Can you post a screenshot of what you're seeing / what you're expecting?

**Comment by junedchhipa** [comment]
Shows me this

![Screen Shot 2019-04-10 at 3 45 50 PM](https://user-images.githubusercontent.com/17950663/55871178-be301900-5ba7-11e9-8848-fa4cf9cf9d26.png)


I suggest you change your dates to UTC/GMT
```javascript
categories: ["2018-03-01 GMT","2018-04-01 GMT","2018-05-01 GMT","2018-06-01 GMT","2018-07-01 GMT","2018-08-01 GMT","2018-09-01 GMT","2018-10-01 GMT","2018-11-01 GMT","2018-12-01 GMT"],

```

**Comment by valeLib** [comment]
Adding GMT to the dates didn't  fix it for me. 

There might be an issue with format and the local time, as I'm in GMT - 4.

**Comment by junedchhipa** [comment]
How about you try a lightweight date library (date-fns) and use it in the formatter functions of xaxis.labels?
Those libraries may handle the GMT/local differences.

```javascript
xaxis: {
  labels: {
    formatter: function(val) {
       dateFns.format(val, 'MM/DD/YYYY')
     }
  }
}
```

**Note:** The code above is not tested, just a thought on how to use custom formatter functions.

**Comment by simoami** [comment]
@junedchhipa I think this is for the maintainers to fix. by passing `2018-03-01` one is expected to see an exact representation of that. Additionally it's not clear from the docs what format the date categories are expected to be; Actual date objects or date strings and which formats are accepted?

**Comment by ErinaHuang200461** [comment]
> How about you try a lightweight date library (date-fns) and use it in the formatter functions of xaxis.labels?
> Those libraries may handle the GMT/local differences.
> 
> ```js
> xaxis: {
>   labels: {
>     formatter: function(val) {
>        dateFns.format(val, 'MM/DD/YYYY')
>      }
>   }
> }
> ```
> 
> **Note:** The code above is not tested, just a thought on how to use custom formatter functions.

I have the same problem and I very much hope to solve it.
[code pen](https://codepen.io/erinahuang200461/pen/XWNzKxe)
I set "hideOverlappingLabels" to false ,Can see the problem.
If I set it to true,  Obviously there will be "x-axis datetime label misaligned " problem.
![image](https://user-images.githubusercontent.com/34910377/109109282-fb87fa80-776f-11eb-816a-0be30ba131a9.png)

**Comment by dao-phuong** [comment]
I also meet this issue, any new update on this @junedchhipa

**Comment by krkaa** [comment]
I also have the same problem 
![image](https://github.com/apexcharts/apexcharts.js/assets/45094569/02e51e7d-7ca3-4650-b49d-9dee25097a6a)
