### ISSUE TITLE
Hiding XLabel does'nt work

### ISSUE THREAD

**Issue by NilkOne** [apexcharts/apexcharts.js#4834]
### Description

tooltip x show: false does'nt work
the tooltip is still visible

### Steps to Reproduce

`              
var options = {
    tooltip: {
        enabled: true,
        x: {
            show: false // Doesn't work
        },
    },
};
`

### Expected Behavior
hide x tooltip

### Actual Behavior
x tooltip is still visible

### Reproduction Link
https://codepen.io/NilkOne/pen/LEPYadE

**Comment by junedchhipa** [comment]
It does hides the x value in the tooltip. I only see the y value.
If you're talking about the x-axis tooltip that appears on the x-axis, you can do it

```
options = {
  xaxis: {
    tooltip: {
      enabled: false
    }
  }
}
```
