### ISSUE TITLE
Make apexcharts pluginable

### ISSUE THREAD

**Issue by frlinw** [apexcharts/apexcharts.js#484]
**Is your feature request related to a problem? Please describe.**
Apexcharts is huge > 410ko and will continue to grow

**Describe the solution you'd like**
Split differents parts of the lib into plugins:
- Core
- Bar chart
- Line chart
- ...
- toolbar
- other features

**Comment by junedchhipa** [comment]
I wanted to keep ApexCharts as simple as possible in the beginning, but with time - codebase grew to > 410kb minified which is huge indeed. 
But, with some refactoring, this size can be reduced. As you can see on https://codeclimate.com/github/apexcharts/apexcharts.js, there are a lot of improvements with regard to duplication/complexity which will be addressed soon.
I will try to squeeze the overall size first before trying to split each module into different plugins.

**Comment by junedchhipa** [comment]
Related to #567

**Comment by frlinw** [comment]
Closed as they are more followers on the newest issue
