### ISSUE TITLE
Pie chart not vertically aligned within container

### ISSUE THREAD

**Issue by elladziv** [apexcharts/apexcharts.js#4844]
### Steps to Reproduce

** Update - This seems to be some sort of an auto-resize issue. Is there a way to prevent redraw on resize, or to prevent the chart from adapting itself to the rendered container size?

1. I have a pie chart with a 400px X 400px size within a container - until now the pie was vertically aligned within the container, and properly fit within it.
2. Now I've upgraded to version 4 (and react-apexcharts 1.6), and the pie chart is always aligned to top-left, and doesn't fit well.
3. This behaves worse when within a scaled-down container.
4. 'customScale' and 'size' on the plotOptions->pie don't seem to do anything
5. 'redrawOnParentResize' on the chart doesn't seem to do anything

### Expected Behavior
Have the pie-chart aligned to center and fit container, or have the option to do it.

### Actual Behavior
Can't seem to center the pie chart, or have it properly fit its container.

### Screenshots
<img width="474" alt="Screenshot 2024-12-02 at 9 46 33" src="https://github.com/user-attachments/assets/7101f893-c42d-477d-bc79-0082577b3bd8">
<img width="429" alt="Screenshot 2024-12-02 at 9 44 19" src="https://github.com/user-attachments/assets/640860d1-1078-411d-a87e-2543cde1f32f">
<img width="696" alt="Screenshot 2024-12-02 at 9 43 36" src="https://github.com/user-attachments/assets/94b4fc25-3fa5-4eac-9e7e-b945428c0207">

### Reproduction Link
https://codesandbox.io/p/sandbox/react-basic-example-forked-snd548

**Comment by junedchhipa** [comment]
Codesandbox fails to open.

**Comment by elladziv** [comment]
Shared now

**Comment by elladziv** [comment]
@junedchhipa Shared now, sorry.
