### ISSUE TITLE
We don't have hideOverlappingLabels in dataLabels of charts

### ISSUE THREAD

**Issue by AFICION007** [apexcharts/apexcharts.js#4849]
Hey folks, this is an important issue and needs to be solved soon. I am also facing the same problem. Why can we have hideOverlappingLabels in dataLabels?? Or is there a property I am unaware of?
I am attaching the picture of my chart, the bottom 3 series' dataLabels are completely overlapping. 
Can somebody help please?

<img width="1237" alt="Screenshot 2024-12-03 at 11 06 36 AM" src="https://github.com/user-attachments/assets/63105dd2-e5b1-4ad3-86af-469aafd36134">

_Originally posted by @AFICION007 in https://github.com/apexcharts/apexcharts.js/issues/2219#issuecomment-2513604578_

**Comment by junedchhipa** [comment]
Please provide a reproducible codepen.

**Comment by brianlagunas** [comment]
Closing until a reproduction link is provided
