### ISSUE TITLE
Donut Chart breaks after first slice in 4.1.0

### ISSUE THREAD

**Issue by carokli** [apexcharts/apexcharts.js#4851]
### Description

Donut chart loads, displays first slice and stops displaying further slices in Typescript and Safari. Even with primitive configuration it breaks. I tried demo configuration from here to verify it's not a problem with my settings:

[Simple Donut](https://apexcharts.com/javascript-chart-demos/pie-charts/simple-donut/)

Console shows following error:

`Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.filterer().node')`

### Steps to Reproduce

1. install npm package 
2. include library  in Typescript
3. setup demo code and view html page in Safari

### Expected Behavior

Donut chart shows all slices

### Actual Behavior

Donut chart shows only one slice. Line chart shows correctly.

**Comment by junedchhipa** [comment]
This was fixed in [this commit](https://github.com/apexcharts/apexcharts.js/commit/d12c37515b2529d4a4aa42b6452764db59239e24)
The fix will be shipped in the next release.
