### ISSUE TITLE
No option for chartcolor on mousehover

### ISSUE THREAD

**Issue by fasterlars** [apexcharts/apexcharts.js#486]
When you hover a chart, donut chart for an example, the color on the current highlighted data fades out. Its like the transparency of the color sets to around 50%.

I would really like to alter this behaviour. Either remove the effect, or just change the color.
As far as I can see, this currently isn´t an option?

**Comment by junedchhipa** [comment]
```javascript
states: {
  hover: {
   filter: {
      type: 'none;
    }
  }
}
```

Enable/disable hover and selected states - https://apexcharts.com/docs/options/states/

As for your other question to change the hover color, currently, that's not possible.

**Comment by fasterlars** [comment]
Oh in the states object..
Thanks alot, and thanks for the great chart!

**Comment by DharmarajPS** [comment]
I found a workaround for this using CSS. Please correct if I am wrong.

.apexcharts-bar-area[filter^="url(#SvgjsFilter"]{
        fill: red;
  }

**Comment by Elaniobro** [comment]
@DharmarajPS interesting. This works just fine for me without all the added specificity

```css
.apexcharts-bar-area:hover {
  fill: #FF0099;
}
```

**Comment by JenniferTactill** [comment]
> @DharmarajPS interesting. This works just fine for me without all the added specificity
> 
> ```css
> .apexcharts-bar-area:hover {
>   fill: #FF0099;
> }
> ```

How do you override the css ?

**Comment by DharmarajPS** [comment]
@JenniferTactill 

You can override the css by using "!important".

Example: 

`.apexcharts-bar-area:hover {
  fill: #FF0099 !important;
}`

**Comment by JenniferTactill** [comment]
> @JenniferTactill
> 
> You can override the css by using "!important".
> 
> Example:
> 
> `.apexcharts-bar-area:hover { fill: #FF0099 !important; }`

That is not my question. I'm asking how do we override the css of this typical file.
Where do I write this style ?
How do I tell apexchart component to take this css file ?

**Comment by DharmarajPS** [comment]
> > @JenniferTactill
> > You can override the css by using "!important".
> > Example:
> > `.apexcharts-bar-area:hover { fill: #FF0099 !important; }`
> 
> That is not my question. I'm asking how do we override the css of this typical file.
> Where do I write this style ?
> How do I tell apexchart component to take this css file ?


Each Vue component will be having <style></style> tags(scoped/universal). You can specify in universal css

**Comment by JenniferTactill** [comment]
> > > @JenniferTactill
> > > You can override the css by using "!important".
> > > Example:
> > > `.apexcharts-bar-area:hover { fill: #FF0099 !important; }`
> > 
> > 
> > That is not my question. I'm asking how do we override the css of this typical file.
> > Where do I write this style ?
> > How do I tell apexchart component to take this css file ?
> 
> Each Vue component will be having <style></style> tags(scoped/universal). You can specify in universal css

Thank you

**Comment by sacalata** [comment]
> @JenniferTactill
> 
> You can override the css by using "!important".
> 
> Example:
> 
> `.apexcharts-bar-area:hover { fill: #FF0099 !important; }`

Thank you, is there any alternative for when clicking the bar?, I want to change the bar's style when it is selected.
