### ISSUE TITLE
Conflict JDate lib with apexchart

### ISSUE THREAD

**Issue by TestCoper** [apexcharts/apexcharts.js#4864]
when i set `window.Date = window.JDate;` that imported from JDate lib the functionality of **resize** and **create** have some errors in file `apexcharts.common.js`.

[JDate lib in github](https://github.com/arashm/JDate)

![image](https://github.com/user-attachments/assets/1ecb005e-daa8-4005-b8f2-3de15dcb76cd)

**Comment by brianlagunas** [comment]
did not follow bug issue template instructions
