### ISSUE TITLE
Create custom tooltip from element instead of HTML string

### ISSUE THREAD

**Issue by Radiergummi** [apexcharts/apexcharts.js#4869]
## Summary
Allow to provide an element instance from the custom tooltip callback in addition to just an HTML string. This would make it a lot easier to integrate with other libraries and frontend stacks.

## API Changes
Really just this:
```diff
-   tooltipEl.innerHTML = fn({
+   const customTooltip = fn({
      ctx: this.ctx,
      series: w.globals.series,
      seriesIndex: i,
      dataPointIndex: j,
      y1,
      y2,
      w,
    })
+
+   if (typeof customTooltip === 'string') {
+     tooltipEl.innerHTML = customTooltip
+   } else {
+     tooltipEl.appendChild(customTooltip)
+   }
```
[`src/modules/tooltip/Labels.js`, Lines 527–535](https://github.com/apexcharts/apexcharts.js/blob/72ecf9713e398a32c83755d2e286c1bcd58cfcc2/src/modules/tooltip/Labels.js#L527-L535)

## Intended Use Case

This allows the [custom tooltip callback](https://apexcharts.com/docs/options/tooltip/#custom) to not only return an HTML string, but also an HTML element instance, which solves a slew of issues and user questions, and allows more advanced integration, such as using a prop in React, or a slot in a Vue component, to render a tooltip.

The API change doesn't introduce any backwards incompatibilities.

**Comment by junedchhipa** [comment]
Great suggestion, will implement this.
