### ISSUE TITLE
Donut total label not showing

### ISSUE THREAD

**Issue by fasterlars** [apexcharts/apexcharts.js#487]
Following the documentation for the donut labels https://apexcharts.com/docs/options/plotoptions/pie/#labels
I´m trying to get the label inside the Donut to show. I´ve put the 'pie' object in the chart object and outside the chart object, but it seems like it´s ignored. I´ve tried lots of other solutions, but can´t get it to work. 
There is no example demonstrating this label in the center of the donut, not on the demo page either. 
So could this be a bug?
https://codepen.io/anon/pen/jRMpmP

**Comment by junedchhipa** [comment]
This may help - https://apexcharts.com/docs/chart-types/pie-donut/

**Comment by fasterlars** [comment]
Misses that the plotOptions object wasn´t the options object, but should be inside the options object.
Thanks!
