### ISSUE TITLE
Column chart bars fail to render randomly when columnWidth is 100%

### ISSUE THREAD

**Issue by tmyt** [apexcharts/apexcharts.js#4879]
### Description

When set `columnWidth` to `100%`, sometime bar could not be rendered.

Because SVG path data broke with exponential notation number.
![image](https://github.com/user-attachments/assets/3a49b116-da81-46cf-b278-e26608c2c17a)

### Steps to Reproduce

1. Render column chart with `options.plotOptions.bar.columnWidth = '100%'`
2. Resize chart to good size.
3. Some bars could not rendered.

### Expected Behavior

Render all bars.

### Actual Behavior

Some bars could not be rendered.

### Screenshots

![image](https://github.com/user-attachments/assets/2b8f0d3b-e4f4-4b29-95ae-ded8e6309621)

### Reproduction Link

https://codepen.io/tmyt/pen/QwLpWVr

**Comment by junedchhipa** [comment]
fixed with [this commit](https://github.com/apexcharts/apexcharts.js/commit/97ed0dcaf76e03c2009acd76d3e4fb8669dacb52)
