### ISSUE TITLE
Fix top height of area in area chart.

### ISSUE THREAD

**Issue by bunnyxt** [apexcharts/apexcharts.js#488]
I use area chart in my project to display time series data. I find that when I narrow the window, the top height of area comes lower than before. So how can I fix the top height of that area?

![Screen Recording 2019-04-08 at 14 51 09 2019-04-08 15_15_21](https://user-images.githubusercontent.com/32478279/55705348-2bf60c80-5a11-11e9-87ce-aa700a0a832e.gif)

repo: https://github.com/bunnyxt/tdd-frontend
url: http://tdd.bunnyxt.com/sprint/av456930

Sorry for my poor English! Hope u can get the point.

**Comment by junedchhipa** [comment]
The container gets smaller because xaxis labels are rotated on smaller screen size. You can turn off this default behavior by

```javascript
xaxis: {
  labels: {
      rotate: 0
  }
}
```
