### ISSUE TITLE
Chart wrapper always has a min-height bigger to the provided height

### ISSUE THREAD

**Issue by sagoncalves** [apexcharts/apexcharts.js#4889]
In order to reproduce you can check any chart on the website, the wrapper always has +15 px added for no reason, making the visual look unproportionate, this happens on any mode dark or light, but its more noticeable on dark.

Image from the apex site you can check there.

It happens on any project so no providing link for reproduction.

<img width="1028" alt="Screenshot 2024-12-23 at 9 08 29 AM" src="https://github.com/user-attachments/assets/ddf80175-c793-48a0-87ab-f8c060277ae2" />

In my project looks like this
<img width="780" alt="Screenshot 2024-12-23 at 9 14 06 AM" src="https://github.com/user-attachments/assets/033671fb-d4a4-4bdb-b3e0-711a56d8a5bf" />

You can see clearly the space at the end of the card.

**Comment by brianlagunas** [comment]
Did not follow bug template instructions and double posted in discussions.
