### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Mirio** [apexcharts/apexcharts.js#489]
**Is your feature request related to a problem? Please describe.**
The way to specify a watermark on the graphs

**Describe the solution you'd like**
Label on the right bottom side

**Comment by brandonburkett** [comment]
In addition, is it possible to include this watermark image on download svg / png.

**Comment by pmsoltani** [comment]
@Mirio I've successfully added a logo to my line chart using the `annotations` option in react:

```javascript
const options = {
  ...,
  annotations: {
    position: 'front',
    images: [{ path: 'absolute/path/to/logo.svg', width: 100, height: 100, x: 10, y: 10 }]
  }
}
```

@brandonburkett Unfortunately, it doesn't show up when I export the chart to SVG or PNG.

**Comment by pmsoltani** [comment]
not stale

**Comment by richinfante** [comment]
For anyone else looking to do this (using 3.42.0):

Looks like download is supported via the annotation method from @pmsoltani's comment, but in order for it to appear, you must encode the image as a data URI first. When I do this, the PNG / SVG export includes it properly
