### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by dnmalenke** [apexcharts/apexcharts.js#4894]
When calling append data, I sometimes receive an error:
`TypeError: Cannot read properties of undefined (reading 'length')`

It looks to be caused by this line here:
https://github.com/apexcharts/apexcharts.js/blob/0f3a4d784c16a6717bbd470d01cc3e3d0e5a3d7f/src/modules/Range.js#L174

Sometimes val is 0, which causes val.toString().split('.')[1] to be null.

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
