### ISSUE TITLE
The right edge of the series has a weird angle when curve is set to straight

### ISSUE THREAD

**Issue by OriginalEXE** [apexcharts/apexcharts.js#490]
## Codepen

https://codepen.io/anon/pen/dLoQJX

## Explanation

- What is the behavior you expect?
The right edge of the series path goes straight down to the point on the x axis

- What is happening instead?
The right edge is going down under an angle and falls randomly on the x axis 

- What error message are you getting?
None

This seems to not happen when I remove `curve: 'straight'`, so it seems to be connected to that property

P.S. Thanks for this weekends release and your continuous work on the library!

**Comment by junedchhipa** [comment]
@OriginalEXE Yeah, when the last value is null, it produces a weird shape. 
Tried to fix it, but looks like it will need some additional debugging to reach the cause of the issue.
