### ISSUE TITLE
X-axis range doesn't work

### ISSUE THREAD

**Issue by mzy2240** [apexcharts/apexcharts.js#491]
## Codepen

https://codepen.io/anon/pen/OGbwEG

## Explanation

- What is the behavior you expect? Realtime chart just like the example (https://apexcharts.com/javascript-chart-demos/line-charts/realtime/)
- What is happening instead? Range for x-axis does not work, so the line is getting compressed because of the incoming data.
- What error message are you getting? Nothing. Besides that, what puzzled me most is that, in our actual practice, **the chart in the website only looks as it should in my laptop, but fails in all my colleague's pcs, even if we are using the same system and same chrome version** (incognito mode).

**Comment by cemujax** [comment]
Why don't you delete sparkline option?
```javascript
var traffic = Array(11).fill(0)
var options = {
  chart: {
          // sparkline: {
          //   enabled: true
          // },
          ...
```
https://codepen.io/cemujax/pen/WWRQjW

I hope it's the result you wanted.

**Comment by mzy2240** [comment]
Hey @junedchhipa I just checked the latest release and I found the bug is still not fixed. Here is the codepen: https://codepen.io/anon/pen/OGbwEG. The line is still compressing instead of window moving.

**Comment by mzy2240** [comment]
Just test the codepen with the latest version 3.6.9, the bug is still there and no sign to be fixed. Please re-open the case. @junedchhipa

**Comment by junedchhipa** [comment]
Wow! I am surprised and embarrassed at the same time that after doing 3 fixes, still this didn’t get solved :)

What on earth is reverting it back!!

I will write more tests to avoid it. Sorry for the trouble you faced.

**Comment by junedchhipa** [comment]
Just noticed that cdnjs links are still cached and not reflecting the latest version of ApexCharts.
Please try https://unpkg.com/apexcharts@3.6.9/dist/apexcharts.min.js and see if it fixes the issue.

**Comment by mzy2240** [comment]
No, unfortunately, it is still not fixed. I have to see it is a weird bug, cause the first time I noticed that, I found the dynamic line behaves different in different PCs, which I never heard and met before.

**Comment by junedchhipa** [comment]
On what browser does it not work correctly? Please provide more information on how to reproduce it. Closing it until then. Feel free to open if the bug is still not fixed in specific browsers.
