### ISSUE TITLE
Line going off the top of chart

### ISSUE THREAD

**Issue by Boldonglen** [apexcharts/apexcharts.js#492]
I have an issue where the data on my line chart is going beyond the top of the chart. 

The below CodePen shows what I mean.

[Codepen](https://codepen.io/boldonglen/pen/mgOrpJ)

**Comment by Boldonglen** [comment]
Okay so after a bit more investigation it seems like its because the yaxis doesnt like decimal numbers. If I change the highest value in my array (4.791986999999999) to 5 it does not go off the top.

Not only this but if I set the max value of the yaxis to be a decimal (in my case i tried to set it to my max value in the array (4.791986999999999) it still doesnt work, guessing because the chart doesnt like the decimal value?

**Comment by junedchhipa** [comment]
The chart loves decimal values 😀, and care is taken to allow decimal values to be printed precisely.
Maybe I missed some checks, I will take a look soon.
