### ISSUE TITLE
X-axis tickamount mobile phone browsers

### ISSUE THREAD

**Issue by Thunderhaug** [apexcharts/apexcharts.js#493]
Hi,
My xaxis is not the same on a smartphone browser and a computer. Specifically, I want intervals of 4 on the x-axis like it is on the computer, but the mobile browser does not react to the xaxis code in the javascript. Have anyone else experienced this problem?

Graph on computer:
<img width="710" alt="Skjermbilde 2019-04-09 kl  12 28 20" src="https://user-images.githubusercontent.com/48654167/55793354-ff9ac880-5ac2-11e9-8ac8-790801466c52.png">

Graph on mobile:
![56490453_376210429643611_3343241021818404864_n](https://user-images.githubusercontent.com/48654167/55793606-9e272980-5ac3-11e9-8f43-79d2ab2e927c.jpg)

**Comment by mestaritonttu** [comment]
Can you share a Codepen or similar with the actual code?

**Comment by Thunderhaug** [comment]
Hi,

here is a codepen:
https://codepen.io/maxkomme/pen/JVWdaP

I can´t reproduce the error in codepen directly, but if I download the codepen and put it on a server, or add the code to a different software, I can.. 

The thing is, the graph is similar on a computer browser and inside messenger, but if you open the graph in a mobile browser, the x-axis doesn´t react to changes in min, max and tickamounts, it only reacts to changes in the number of datapoints in the data series..
