### ISSUE TITLE
Document of undefined

### ISSUE THREAD

**Issue by MiholapMaksim** [apexcharts/apexcharts.js#494]
Hello!
Is apexcharts support Server Side Rendering in React?
Now i have the following error module.exports = root.document ? factory(root, root.document) : function (w) {

**Comment by junedchhipa** [comment]
Sorry, ApexCharts doesn't support SSR.

**Comment by FernandoRogelin** [comment]
`const ApexChart = dynamic(
    () => {
      return import('react-apexcharts')
    },
    { ssr: false }
  )`

If you using Next.js, this works for me.
