### ISSUE TITLE
Less Padding/Margin for Pie/Donut Charts 

### ISSUE THREAD

**Issue by mburger81** [apexcharts/apexcharts.js#495]
**Is your feature request related to a problem? Please describe.**
We use `stencil-apexcharts` for your charts. The charts look really good!!!

But in our opinion as described already in this issue #471 there are to margin/padding for your charts. for sure on pie and radialBar charts. If you have not a lot of space like on mobile devices you need to minimize paddings and margins.

The inner padding of an chart should be customizable, from there all charts (at least radialBar) made use of the container space allowed to it.

So we hope you can do some improvements on this point.

Thx

**Comment by junedchhipa** [comment]
What if you provide fixed height to the chart? Does it still have space?
Please post a codepen so I can try tweaking it through configuration options if it is achievable by it.

**Comment by mburger81** [comment]
Honestly all your examples have a fixed hight and I think/saw all your examples have the same behavior?
Like this which for the moment is our use case
https://apexcharts.com/javascript-chart-demos/radialbar-charts/semi-circle-gauge/

**Comment by junedchhipa** [comment]
Yeah, that looks like a lot of unwanted space :)
Currently, the radial-bar charts attempt to make the width/height equal resulting in a square (which is not what everyone would want).

I will look at how this can be controlled.

**Comment by mburger81** [comment]
Yes I think the chart should took the entire container. So customer can add padding or margin do container.
I think the square could be fine, but you should check parent element and use min between width and height.

**Comment by mikaelkaron** [comment]
As a "quick-fix" it's possible to set negative margins on the chart (if you have a container of some sort, probably with overflow: hidden)

**Comment by oherik** [comment]
I see that this issue has been closed, but I think the issue still remains. If you look at this codepen:
https://codepen.io/oherik/pen/WNbqbYG

and highlight the chart container div:
![image](https://user-images.githubusercontent.com/10709871/73460940-a6659380-4379-11ea-8f49-76fd3a42cde1.png)

You can see that there is still quite some space around the chart itself, even though I have set `width: "100%"`. I would expect the chart to fill up the entire width of the parent container. Am I missing something?

**Comment by rinogo** [comment]
Cross-posting this here in case it helps someone who lands on this Issue.

Using a `radialBar` chart, we wanted to eliminate the top and bottom padding/margins. Using `chart.offsetY` helped a bit, but only for the top margin.

Inspired by [this comment](https://github.com/apexcharts/apexcharts.js/issues/1272#issuecomment-591388290), I was able to crop out unnecessary top and bottom margins using negative values for [`grid.padding.top` and `grid.padding.bottom`](https://apexcharts.com/docs/options/grid/). You can do something similar with the left and right padding as well. My code ended up looking something like this:

```
            var options = {
                ...
                //Remove the excess padding (https://github.com/apexcharts/apexcharts.js/issues/1272#issuecomment-591388290)
                grid: {
                    padding: {
                        top: -20,
                        bottom: -15
                    }
                },
                ...
            };
```
Hope this helps! 😁

**Comment by kamaladenalhomsi** [comment]
@rinogo man you are a life saver! I've been struggling with this for a while

**Comment by talforsher** [comment]
Saved my day @rinogo
