### ISSUE TITLE
Zoom doesn't work when the x-axis type is numeric

### ISSUE THREAD

**Issue by jenesiaf** [apexcharts/apexcharts.js#497]
## Code
```  xaxis: {
          type: 'numeric',
          labels: {
            formatter(value) {
              return Math.round(value);
            }
          },
          title: {
            text: 'Position in the media items',
            style: {
              fontSize: '16px',
              cssClass: 'apexcharts-yaxis-title'
            }
          }
},```

## Explanation

- Expect zoom to work for Scatter chart, Area chart and Line chart
- Zoom doesn't work. However, if the type is updated to dateTime instead of numeric, it zooms and the x-axis labels are correct, however the tooltip shows a default date of 1st Jan (which is incorrect)

**Comment by junedchhipa** [comment]
Can you please post a full codepen demo?
I just tried your xaxis and it works fine.

**Comment by jenesiaf** [comment]
Hi,

Just a bit of context, I am using `apex-charts` with `vue-apexcharts` to display charts in my Vue app. 
The issue was noticed when the dependencies `apexcharts` and `vue-apexcharts` was on versions `3.6.4` and `^1.3.1` respectively, when the zoom capabilities of scatter chart was not working when the xaxis was of type 'numeric'.

I recently updated the `apexcharts` and `vue-apexcharts` versions to `3.6.7` and `^1.3.4` respectively which are the latest versions for the dependencies as of today. Post the update, this issue no longer exists.

Hence, I am going ahead and closing the issue.

**Comment by bajlur** [comment]
Hi,
I have used react-apexchart for doing the same task. But I am facing the same issue where zoom is not working when the x-axis type is numeric. On the other hand if I not keeping X-axis numeric, then zoom is working but incase of huge data, the line chart is not displaying the stroke. I am using apexchart version 3.45.2 and react-apexchart version 1.4.1. So please tell me the solution.
