### ISSUE TITLE
dataURI() method not working with Angular 7

### ISSUE THREAD

**Issue by rvergar7** [apexcharts/apexcharts.js#499]
Hello, I'm currently trying to use the dataURI method to generate a base64 encoded image to use with pdfmake.

When I attempt to use the method similar to what is shown in the documentation:

```
    var chart = new ApexCharts(
        document.querySelector(elementID),
        options
    );

    var dataURL = chart.dataURI().then((uri) => {
        console.log(uri);
    })
```

I receive two different errors - "1" is in the angular compiler and "2" is in the console - the base64 encoded string/image is never generated.

1. Property 'then' does not exist on type 'void'.ts(2339)
2. Possible Unhandled Promise Rejection: TypeError: Cannot read property 'querySelector' of undefined

However, if I use the render method right before I call the dataURI method (shown below) the base64 string/image is generated - error "2" doesn't show up anymore but I'm still dealing with error "1". 

```
   var chart = new ApexCharts(
        document.querySelector(elementID),
        options
    );

    chart.render();

    var dataURL = chart.dataURI().then((uri) => {
        console.log(uri);
    })
```

I'm not sure if this is the expected behavior for error "2" and I don't know how to proceed with "1". If you guys can provide any help that would be great! thanks!

UPDATE:

I looked at the apexcharts.d.ts file and found that dataURI was declared as follows:

`
dataURI(): void;
`

I changed it to:

`
dataURI(): Promise<void>;
`

Now I have fixed the compiler error.

**Comment by junedchhipa** [comment]
Can you please create a PR for this fix?
