### ISSUE TITLE
Scrollbar size and chart width

### ISSUE THREAD

**Issue by mikaelkaron** [apexcharts/apexcharts.js#501]
Not really sure if this is a "bug" per say, but thought I'd drop it in here for future ref.

The problem I have is present when you have multiple charts on one page where you don't know the height of the _scrollable area_ beforehand.

Let's start with how it's _supposed_ to look if everything is fine:

![image](https://user-images.githubusercontent.com/478468/55945559-5501e180-5c4b-11e9-8a4c-7fb6bf839ab7.png)

This page lays out all the charts using a `flexbox` rows/cols setup:

- First chart uses ~45% of the available space and centers using `justify-content-center`
- Second chart uses 100% of the available width
- Third... use ~30% of and stacks when there's more graphs.

So how does it look when it's "broken":

![image](https://user-images.githubusercontent.com/478468/55946014-2b958580-5c4c-11e9-9524-2e1fde5f5ed5.png)

From a quick look it all looks the same, but if you check the right-hand margin you'll see that there's something going on with the first two charts.

- First chart is slightly larger than the "working" example and is not _quite_ centered (it's hard to see - just trust me)
- Second chart has some obvious problems with the right margin
- Third... looks ok - strange right?

Even more fun - when you resize the window _it all adjusts itself_ an looks like the first screen 😨 

So what's going on here? Well, the first clue is to look at how many pixels we're off by in "broken" mode - and on my system (Windows) it's ~17px, a magic number that corresponds to the width of the scrollbar.

When a chart is drawn there's an initial call to [`getDimensions`](https://github.com/apexcharts/apexcharts.js/blob/6167b9873741c9c986b0fa44fbf113d744f42ec1/src/utils/Utils.js#L146) to calculate the initial size of the chart. This method is called again whenever the chart parent or the window is resized - so far so good. The chart rendering is called in flow order of the page (top to bottom) and here's where the "problem" appears.

- When the first chart is drawn there's no scrollbar (as it's the only element on the "page" (think scrollable area, because it's that scrollar that will mess us up in a second).
- When the second chart is drawn there's _still_ no scrollbar (depending on the height of the viewport) so we're still calculating the width without it. _However_ once the chart is on the page we now have a scrollbar!
- From the third chart and onwards we have a scrollbar so the width is now ~-17px from what the previous two charts were based on.

> To make this even _more_ fun you can try doing this with the devtools open (from the bottom) and the breakpoint for when scrollbars appear is after the _first_ chart (since we have less viewport available).

So how does one deal with this? In my case (since I know I'll _always_ fill up a full viewport worth of charts) I set the height of the scrollable area to something like `100vh` so that all chart calculations will subtract the width of the scrollbars from the get-go.

There's probably a "better" way to do this, Either by re-calculating all the chart widths when we're done (but how do we know that?) or that already rendered charts resize whenever we pass the breakpoint where a scrollbar appears (I don't know why this is not happening at the moment, but at least in my case this is not happening).

As mentioned in the beginning I'm not sure it's a bug _per se_ but I thought I should mention it and post my workaround for others. Maybe we can add something to the docs about it?

**Comment by mikaelkaron** [comment]
There is another workaround to get the charts to have their `resize` trigger executed - by disabling animations:

```
options: {
  chart: {
    animations: {
      enabled: false
    }
  }
}
```

Not sure why this makes the resize trigger work vs just having them on...

**Comment by bozerkins** [comment]
Another work-around I'm using is to set the container width to ~97%. This number is "almost" full width, which will look more or less the same. Those 3% will account for the excess scrollbar width of the chart. You can center the container to get a more pleasant look.

I know it's dirty, but we live in a cruel world
