### ISSUE TITLE
Possible Unhandled Promise Rejection:

### ISSUE THREAD

**Issue by dcalmeida13** [apexcharts/apexcharts.js#502]
When I check the devtools on chrome, i get the following warning:

`Possible Unhandled Promise Rejection: TypeError: Cannot read property 'labels' of undefined
    at ApexCharts.js:6200
    at NodeList.forEach (<anonymous>)
    at t.value (ApexCharts.js:6198)
    at t.value (ApexCharts.js:8259)
    at ApexCharts.js:13950
    at tt (ApexCharts.js:8087)
    at new q (ApexCharts.js:8032)
    at i.value (ApexCharts.js:13948)
    at ApexCharts.js:13877
    at tt (ApexCharts.js:8087)
q._unhandledRejectionFn @ ApexCharts.js:8152`

How to solve this?

Here is the link to codepen: https://codepen.io/devdca/pen/vMmzqv 

On codepen is working fine, but the issue occurs when i try to refer to a file in my source, like: 
<script src="js/ApexCharts.js"></script>

**Comment by junedchhipa** [comment]
Please post a codepen to reproduce easily.

**Comment by dcalmeida13** [comment]
@junedchhipa I edited my question

**Comment by dcalmeida13** [comment]
I solved my problem here. I was calling twice the function that generates the graph.
