### ISSUE TITLE
Data isn't aligned correctly horizontally in line chart

### ISSUE THREAD

**Issue by machinex7** [apexcharts/apexcharts.js#503]
## Codepen
https://codepen.io/britterct/pen/OGmeoz

## Explanation

- What is the behavior you expect?
The data is [[20, 30],[30, 40],[40, 35]].
The line should start at the 20 label, then a point at the 30 label, and then a point at the 40 label.

- What is happening instead?
The line is squished and starts at the 30 label, then 35, then 40 correctly.
It's rendering as if I gave it [[30, 30],[35, 40],[40, 35]]

- What error message are you getting?
None

**Comment by junedchhipa** [comment]
Yes, I confirm the issue, but it is fixed in the last commit
Here is the screenshot of the fix.
![Uploading Screen Shot 2019-04-12 at 12.20.47 AM.png…]()

 Patch will be released soon.

**Comment by machinex7** [comment]
Thanks!
