### ISSUE TITLE
Column chart not rendering correctly

### ISSUE THREAD

**Issue by Acathur** [apexcharts/apexcharts.js#507]
## Codepen

https://codepen.io/acathur/pen/YMxjgq

<img width="710" alt="Screen Shot 2019-04-14 at 00 13 10" src="https://user-images.githubusercontent.com/4847490/56082327-2ef66000-5e4a-11e9-926f-dda55e49b176.png">

## Explanation

- Bars should not be overlapped
- Distribute bars

**Comment by Acathur** [comment]
Hi @junedchhipa , it seems bring a new bug when using `tickAmount` and `labels.formatter`

**Comment by junedchhipa** [comment]
Codepen please?

**Comment by Acathur** [comment]
@junedchhipa hi, just made the demos

- run on v3.6.7 https://codepen.io/acathur/pen/QPOywO
- run on v3.6.6 https://codepen.io/acathur/pen/mgqVqR
