### ISSUE TITLE
On the heatmap, color defined for zero is ignored

### ISSUE THREAD

**Issue by sebastian-raubach** [apexcharts/apexcharts.js#508]
## Codepen

https://codepen.io/wacmemphis/pen/xeXZOx

## Explanation

- What is the behavior you expect?
  Zero values should be colored according to specified range.
- What is happening instead?
  Zero values are white.
- What error message are you getting?
  None

**Comment by sebastian-raubach** [comment]
I checked the version currently in the master branch and it gives much better results. I can definitely work with this now. Thanks!
Any ETA for when a new release is coming out?

**Comment by junedchhipa** [comment]
The fix is already shipped in 3.6.8 released yesterday

**Comment by sebastian-raubach** [comment]
It's not listed under releases: https://github.com/apexcharts/apexcharts.js/releases
But I can see it on npm, thanks!

**Comment by junedchhipa** [comment]
Yeah, I didn't write a release note on GitHub yet, thanks for reminding :)

**Comment by Sigabiel** [comment]
The problem has seemed to reroccour in the recent version 3.40.0 since entries with the value of 0 always tint in a lighter color than set. 

Please check the codepen at the beginning (https://codepen.io/wacmemphis/pen/xeXZOx)

**Comment by el-sacapuntas** [comment]
what was the fix for this?
