### ISSUE TITLE
Anotations not work in stacked bar charts

### ISSUE THREAD

**Issue by katarina-simnova** [apexcharts/apexcharts.js#51]
Anotations in stacked bar charts don't show at all

**Comment by junedchhipa** [comment]
Can you please provide more information?
Were you trying in horizontal bars or vertical columns?

I would like to see your code what have you tried.

**Comment by KatarinaSimnova** [comment]
Finally, annotations appeared in my chart, but they still do not work properly. Here is my code: 

var options = {
        chart: {
            height: 200,
            type: 'bar',
            stacked: true,
        },
        plotOptions: {
            bar: {
                horizontal: true,
            },
        },
        series: [{
            name: 'Marine Sprite',
            data: [44]
        },{
            name: 'Striking Calf',
            data: [53]
        },{
            name: 'Tank Picture',
            data: [12]
        },{
            name: 'Bucket Slope',
            data: [9]
        },{
            name: 'Reborn Kid',
            data: [25]
        }],
        xaxis: {
            categories: ['Usage'],
        },
        legend: {
            show: false
        },
        annotations: {
            xaxis: [ {
                x: 100,
                borderColor: '#FEB019',
                label: {
                    text: 'limit',
                }
            }]
        }
    }

    var chart = new ApexCharts(
        document.querySelector("#chart"),
        options
    );
   
    chart.render();
Result:
![chart](https://user-images.githubusercontent.com/11189150/44601421-b40a0780-a7dc-11e8-8e5b-f507369215e2.PNG)

Annotation should by on tick 100.

**Comment by junedchhipa** [comment]
Thanks for providing details, the code is helpful to generate the issue on my side as well.

I confirm that annotations doesn’t works as expected on horizontal bar charts.
I will soon address the issue in the next patch release.

Thanks

**Comment by bcruddy** [comment]
@junedchhipa is this still an issue?

**Comment by junedchhipa** [comment]
Yes, couldn't work on this issue. Just started working on it, thanks for reminding ;)
