### ISSUE TITLE
Custom tooltip not showing in combo chart's line values

### ISSUE THREAD

**Issue by varrodani** [apexcharts/apexcharts.js#512]
## Codepen

https://codepen.io/anon/pen/zXPyWX

## Explanation

Hi devs!

I want to make a combo chart with line and bar diagrams and the mistakes is the following:
If I declare a chart with custom tooltip, it working only for the bar chart and a line chart doesn't focused.
I'd like to have the custom tooltips work separately.
Is it possible? I try it with shared tooltip and works fine, but I would like to be able to solve this.

Thanks in advance.

**Comment by junedchhipa** [comment]
Increase the marker size to allow the line chart to capture the event.
```
markers: {
   size: 6
}
```

**Comment by varrodani** [comment]
It works!
Thank you very much!
