### ISSUE TITLE
Minimal slice width for "Stacked, horizontal, 100%"

### ISSUE THREAD

**Issue by robsontenorio** [apexcharts/apexcharts.js#514]
## Codepen

https://codepen.io/anon/pen/yrpwmb

![Captura de Tela 2019-04-16 às 23 49 42](https://user-images.githubusercontent.com/118955/56257354-57789700-60a2-11e9-9767-b05e5d9c3a72.png)

## Explanation

When the numerical series has very disproportionate values the chart get "truncated". Is there any options to keep a minimal width for each slice in order to keep this "percentual" properly inside the bars? Thanks for your time!
 
```js
           series: [{
                name: 'TO DO',
                data: [600]
            },{
                name: 'DOING',
                data: [25]
            },{
                name: 'DONE',
                data: [10]
            }],  
```

**Comment by junedchhipa** [comment]
Minimal slice width can't be provided, as it will display wrong data.
The dataLabels will hide automatically if they overlap from now on.

**Comment by robsontenorio** [comment]
In another hand if hidden it can give a “illusion” of there is no data.

**Comment by tudor-ooo** [comment]
@junedchhipa Another example:

<img width="1128" alt="Screenshot 2020-01-23 at 18 15 13" src="https://user-images.githubusercontent.com/668451/73007210-6b5ce080-3e0c-11ea-9274-e4c69bb0441b.png">

the last elements are not visible, it would be nice to have at least "1px min width/height" for bars.
