### ISSUE TITLE
Pie chart values are overlapped 

### ISSUE THREAD

**Issue by bashairm** [apexcharts/apexcharts.js#516]
**Is your feature request related to a problem? 
the values in Pie charts are overlapped.

A clear and concise description of what the problem is. 
I work on Pie charts and it contained small values (smaller than 1) so it's overlapped.

**Describe the solution you'd like**
I think it will be better if I can control the values places and change it 

**Additional context**
<img width="238" alt="Screen Shot 2019-04-17 at 11 30 14 AM" src="https://user-images.githubusercontent.com/47118448/56272944-714ac600-6104-11e9-8749-d5ab9aa382b2.png">
<img width="179" alt="Screen Shot 2019-04-17 at 11 30 22 AM" src="https://user-images.githubusercontent.com/47118448/56272949-73148980-6104-11e9-82d0-fe136a846b3e.png">

the code:
       
```
  var options = {
            "chart": {
                "width": 580,
                "type": "pie"
            },
            "labels": [  "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%"],
            "colors": [  "#5a99d3","#e97c30","#a3a3a3","#fbbd00", "#4270c1","#444444","#245c8f", "#9b460c","#626262","#977200" ],
            "series": [ 2.4, 2.4, 10.3, 24.5,30.9,24.9,2.0, 0.7, 0.5,0.5],
        }

       var chart = new ApexCharts(
            document.querySelector("#chart"),
            options
        );
        
        chart.render();
```

**Comment by junedchhipa** [comment]
Thanks for raising the issue.
Yeah, the overlapping labels look bad. I think, preventing drawing the labels when they overlap is the quickest fix I can provide for now.

Maybe, another option is to add percentage in the legend labels will help to identify the values when there are many items with small values.

**Comment by robsontenorio** [comment]
@junedchhipa probably same issue as https://github.com/apexcharts/apexcharts.js/issues/514 and a fewer others.

**Comment by junedchhipa** [comment]
For pie charts, a new option will be provided to hide labels if they overlap.

```javascript
plotOptions: {
  pie: {
    dataLabels: {
      minAngleToShowLabel: 15
    }
  }
}
```

Using this, you can avoid printing labels for very small slices.

Alternatively, you can also use legend.formatter to display percentages there.

**Comment by robsontenorio** [comment]
@junedchipa the same can be provided for stacked 100% bars?

**Comment by junedchhipa** [comment]
Stacked 100% charts will automatically hide the dataLabels if they don't fit in the area.
No need to provide an additional option for that.
