### ISSUE TITLE
3D pie and Donut chart

### ISSUE THREAD

**Issue by bashairm** [apexcharts/apexcharts.js#517]
**Is your feature request related to a problem? 
no, but it will be better to be there.

**Describe the solution you'd like**
support 3D charts it will be a good feature in ApexCharts.
and I need it in my project 

**Additional context**
<img width="238" alt="Screen Shot 2019-04-17 at 11 30 14 AM" src="https://user-images.githubusercontent.com/47118448/56272844-3f396400-6104-11e9-8626-db635fe030d3.png">

**Comment by junedchhipa** [comment]
Sorry, 3D pie and donut are not in the roadmap currently, thanks for the suggestion.
