### ISSUE TITLE
[Docs Error] Default values for padding are incorrect

### ISSUE THREAD

**Issue by venits** [apexcharts/apexcharts.js#519]
Hi, I noticed small error in docs.

Here: https://apexcharts.com/docs/options/grid/

In example we have:
```js
padding: {
   top: 0,
   right: 0 // missing comma
   bottom: 0 // missing comma
   left: 0 // missing comma
}
```

I think in source code, commas are also missing because those `0` values do not apply.

Adding commas in `options.grid` solves problem and changes padding value to `0`.

Great library btw. Keep it up 👍

**Comment by junedchhipa** [comment]
Thanks for pointing it out, fixed it!
