### ISSUE TITLE
How to add custom tooltip to donut chart

### ISSUE THREAD

**Issue by felixalguzman** [apexcharts/apexcharts.js#52]
I want to add a array of tooltip to my donut chart. This is my chart
![image](https://user-images.githubusercontent.com/17243615/44619345-e6eee280-a852-11e8-9aff-c6b70c54367e.png)

**Comment by junedchhipa** [comment]
Sorry, I don't get your question correctly.
Can you please elaborate what are you trying to accomplish?

**Comment by felixalguzman** [comment]
I want to display some text instead of the default that is series. For each value in donut chart I have a text that i want to present as a tooltip

**Comment by junedchhipa** [comment]
You can use label formatters to modify the text instead of displaying the default one.
See the [example](https://codepen.io/apexcharts/pen/aaOrjE)

You will need to set
```javascript
tooltip: {
  y: {
    formatter: function(value) {
      return value * 2; // whatever you want to display
    }
  }
}
```

**Comment by felixalguzman** [comment]
ok that would work. Is it possible to remove the series name?

**Comment by junedchhipa** [comment]
Yes, but with CSS :)
Check the same example I just updated

**Comment by felixalguzman** [comment]
Ok thanks

**Comment by junedchhipa** [comment]
I forgot that you can also do it without CSS display:none using `tooltip.y.title.formatter` function :)

```javascript
tooltip: {
    y: {
      formatter: function(val) {
        return val + ".00" + " Rs"
      },
      title: {
        formatter: function (seriesName) {
          return ''
        }
      }
    }
  },
```

**Comment by DebasisBehera123** [comment]
thanks for above.

**Comment by DebasisBehera123** [comment]
Thanks @junedchhipa for above.

**Comment by anilreddy128** [comment]
but how to add dynamic data to tooltip? data can be there in dataset/json array.

**Comment by nuvenn** [comment]
`tooltip: {
      custom: function({ series, seriesIndex, dataPointIndex, w }) {
        return "<div>" + series + "</div>";
      }
    },`

**Comment by juanccamachob94** [comment]
> I forgot that you can also do it without CSS display:none using `tooltip.y.title.formatter` function :)
> 
> ```js
> tooltip: {
>     y: {
>       formatter: function(val) {
>         return val + ".00" + " Rs"
>       },
>       title: {
>         formatter: function (seriesName) {
>           return ''
>         }
>       }
>     }
>   },
> ```

It works to items of tooltip. I would like to change the tooltip title. A content different to categories values :(

**Comment by devinnogenio2** [comment]
const options = {
        cutout: "75%",
        borderWidth: 0,
        responsive: true,
        onHover: (event, chartElement) => {
          const target = event.native ? event.native.target : event.target;
          target.style.cursor = chartElement[0] ? "pointer" : "default";
        },
        plugins: {
          legend: {
            position: "bottom",
            labels: {
              usePointStyle: true,
              pointStyle: "circle",
            },
          },
          tooltip: {
            y: {
              formatter: function (value) {
                return value + "your text";
              },
            },
          },
        },
      };

**Comment by devinnogenio2** [comment]
`const options = {
        cutout: "75%",
        borderWidth: 0,
        responsive: true,
        onHover: (event, chartElement) => {
          const target = event.native ? event.native.target : event.target;
          target.style.cursor = chartElement[0] ? "pointer" : "default";
        },
        plugins: {
          legend: {
            position: "bottom",
            labels: {
              usePointStyle: true,
              pointStyle: "circle",
            },
          },
          tooltip: {
            y: {
              formatter: function (value) {
                return value + "your text";
              },
            },
          },
        },
      };`

I added options like this but it's not working

**Comment by xyresicdarshan** [comment]
Hey, 
I'm using Apexchart (StackedBarChart), I want to append the % sign in the hover value.

code is like this :
this.CategorySummaryChart = {
      series: [{
        name: "Completed",
        data: this.completedQuestionsPercentage,
      },
      {
        name: "NA",
        data: this.naQuestionsPercentage,
      },
      {
        name: "Overdue",
        data: this.missedQuestionsPercentage,
      },
      ],
      chart: {
        type: "bar",
        height: 350,
        stacked: true,
        stackType: "100%",
        width: '98%',
        toolbar: {
          show: false,
        },
      },
      tooltip: {
        y: {
          formatter: function (value) {
            return value + "%";
          },
        },
      },
      /* plotOptions: { 
        bar: {
          columnWidth: '20', 
        }, 
      }, */
      responsive: [{
        breakpoint: 900,
        options: {
          chart: {
            type: "bar",
            height: 350,
          },
        },
      },],
      xaxis: {
        categories: this.categoryNames,
      },
      fill: {
        opacity: 1,
      },
      legend: {
        show: false,
        position: "top",
        offsetX: -20,
        offsetY: 10,
        horizontalAlign: 'right',
        markers: {
          radius: 12,
          offsetY: 1,
        },
        onItemClick: {
          toggleDataSeries: false,
        },
        onItemHover: {
          highlightDataSeries: false
        },
      },
      colors: this.colors,
    };
  }
  
Expected Ouput - something like this
![Screenshot (41)](https://user-images.githubusercontent.com/41583291/216327441-d1843ad8-eb32-483f-9ef7-f787b97fa4b6.png)
