### ISSUE TITLE
Achieve 100% of the available height

### ISSUE THREAD

**Issue by codeflyin** [apexcharts/apexcharts.js#520]
Hi guys, I'm trying to make the graphic I can reach the 100% available that has its parent container in height and width. The width and I think is well configured, but in the high the problem still persists.

Try to do what #27 - #140  said but still it has not been possible to adapt the desired height.

Here I leave the code of a simple code, I have put a border to the container box to see the difference of the parent container to the spaces that there are with the graph.

https://codesandbox.io/embed/m371xwq0p8?fontsize=14

**Comment by junedchhipa** [comment]
You have to add
```javascript
chart: {
      sparkline: {
            enabled: true
      }
}
```

To remove all the unnecessary space around chart area (x-axis default padding/legend default padding, etc)

**Comment by codeflyin** [comment]
solved, thanks very much.

**Comment by Nivethan-Ar** [comment]
spent many hours to find this answer! thanks

**Comment by saad277** [comment]
@junedchhipa working thanks
