### ISSUE TITLE
wrong Y-Axis value scale

### ISSUE THREAD

**Issue by johncaipa** [apexcharts/apexcharts.js#522]
I was looking for if Apex had a forum but I did not find it, that's why I posted my problem here, if someone could help me.
It turns out that I am using the library to graph 2 variables with their respective y-axis, but it seems that the scales of the Y-axis do not agree with the real value shown. I do not know if you could help me with this inconvenience.

![image](https://user-images.githubusercontent.com/31298276/56392580-6886ec80-61f7-11e9-80ea-b6b842638c80.png)

**Comment by junedchhipa** [comment]
Please create a codepen demo so that it can be easily reproduced.

**Comment by johncaipa** [comment]
Hi @junedchhipa this is the codepen that reproduces the error, I think it has to do with the tooltip configuration.
https://codepen.io/johncaipa/pen/axjYNM

**Comment by junedchhipa** [comment]
That's a bug, thanks for reporting.
I will look into it soon.

**Comment by WojteKris** [comment]
Hi!
Problem solved?
