### ISSUE TITLE
Hiding Labels on Radial Chart

### ISSUE THREAD

**Issue by startupryan** [apexcharts/apexcharts.js#524]
On a Radial chart, the Label is displayed within the middle of the chart.  How can we completely hide this, while moving the dataLabels up to it's position, ideally without changing it's offsetY.

Here is the radial example provided in the docs.

```
var options = {
  chart: {
      height: 350,
      type: 'radialBar',
  },
  series: [70],
  labels: ['Progress'],
}

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```

This produces the label of **Progress**, but if we completely remove the Label key, it defaults to **series-1**

```
var options = {
  chart: {
      height: 350,
      type: 'radialBar',
  },
  series: [70],
 //  labels: ['Progress'], <-- hidden
}

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
```

Is there a way to hide the Label entirely without just adding a whitespace? 
```
labes: [' ']
```

**Comment by junedchhipa** [comment]
```javascript
plotOptions: {
  radialBar: {
     dataLabels: {
       show: false
     }
  }
}
```

https://apexcharts.com/docs/options/plotoptions/radialbar/#dataLabelsShow

**Comment by startupryan** [comment]
@junedchhipa This does not solve the issue I was asking.  This hides the dataLabels & the chat Labels.  I am asking how to only hide the chart Labels.

**Comment by junedchhipa** [comment]
Which labels?
Please show an image as I am not getting your point.

**Comment by startupryan** [comment]
Using the Basic Circle Char codepen example.

https://codepen.io/junedchhipa/pen/eQmmbO

Line 7 `labels: ['Progress']`

Is there a way to disable these, WITHOUT just entering an empty whitespace.  Not supplying the chart with a label key, defaults the label to `series-1`. 

Ideally, when not supplying labels, it removes that SVG <text/> and bumps everything below up.

**Comment by junedchhipa** [comment]
```javascript
plotOptions: {
  radialBar: {
     dataLabels: {
       name: {
          show: false
       }
     }
  }
}
```

**Comment by startupryan** [comment]
This is the same as your previous attempt.  DataLables are not the same as Labels. Keep dataLabels, hide Labels.

**Comment by junedchhipa** [comment]
I'm sorry, but I would like to see what you're expecting.

I see two texts in the center of the circle
**SeriesName**
**DataPointValue in percentage**

What do you want to hide and what do you want to show from these two? Have you gone through the doc I provided?

**Comment by falan** [comment]
Try this,
options:{
                legend: {
                    show: false
                },
}

**Comment by mridulasm** [comment]
legend: {
       show: false
    },

**Comment by ajithmjames** [comment]
chartOptions: {
        colors: ["#8b0b84", "#8b0b84", "#8b0b84", "#8b0b84", "#8b0b84"],
        chart: {
          width: 380,
          type: "pie",
        },
       legend:{
        display:false,
        show:false,
       },

        labels: ["Team A", "Team B", "Team C", "Team D", "Team E"],
        responsive: [
          {
            breakpoint: 480,
            options: {
              chart: {
                width: 200,
              },
              
              legend: {
                position: "bottom",
              },
            },
          },
        ],
      },

**Comment by lsdev200** [comment]
const radial = {
    chart: {
      height: 200,
      type: 'radialBar'
    },
    options: {
      colors: ['#0E8A74']
    },
    plotOptions: {
      radialBar: {
        dataLabels: {
          name: {
            show: false
          },
          value: {
            show: false
          }
        }
      }
    },
    series: radialdata,

    stroke: {
      lineCap: 'round'
    }
  }
  
I'm attempting to hide data labels by default in a React.js application, but I haven't been able to solve this issue. Can you please provide some guidance or assistance?

**Comment by brunovittoria** [comment]
@startupryan I solved doing this: 

`
dataLabels: {
    value: {
      show: false,
    },
  },
`
