### ISSUE TITLE
Annotations label artifact

### ISSUE THREAD

**Issue by tanguyvda** [apexcharts/apexcharts.js#528]
## Codepen
https://codepen.io/anon/pen/ZZRoEY

## Explanation
I'm not quite sure if it is a bug or if I'm missing something.
When you leave the annotation label empty, it still displays a small rectangle in the top left corner of the chart. I've tried to play with opacity and other options to hide it but none of them seemed to work.

- What is the behavior you expect? 
if I enable annotations and leave an empty label (or undefined value), I do not want any annotations label relative content to be displayed

- What is happening instead?
the label is not displayed but I have an artifact in the top left corner of the chart  

- Use case 
I want my users to be able to disable the annotation label because in some cases it can hide the data. 
![image](https://user-images.githubusercontent.com/7352865/56470396-f48e5380-6445-11e9-8056-1a1f3c7ff4de.png)

**Comment by junedchhipa** [comment]
Cool, I will make sure not to draw anything if label is empty string.
