### ISSUE TITLE
Chart will be misplaced if the "showForSingleSeries=true" and "series" has ONLY ONE number

### ISSUE THREAD

**Issue by dream-sky12** [apexcharts/apexcharts.js#529]
The problem will be a little complex and details are as following.
I made modifications in the "BarExample.vue" source code from the original repository of "vue-apexcharts"

1. I set the "categories" of "xaxis" from a list of numbers to ONLY ONE number.
2. I set the "series" with one set of data with one number.
3. I turned "showForSingleSeries" true, set toolbar show false, horizontal of bar false, 
 and columnWidth of 30%
4. I simply add another bar chart with style of "display: none"

Original Code
![image](https://user-images.githubusercontent.com/26947221/56471382-5f5e7f80-6484-11e9-8eb1-26f760a667d9.png)
Code with modification
![image](https://user-images.githubusercontent.com/26947221/56471388-78673080-6484-11e9-8b2d-1d96f9a5284e.png)

Original Code
![image](https://user-images.githubusercontent.com/26947221/56471416-d5fb7d00-6484-11e9-999a-3b3b8208fa62.png)
Code with modification
![image](https://user-images.githubusercontent.com/26947221/56471428-fcb9b380-6484-11e9-84ae-617ba1759ac1.png)

After the modifications, the page will show the first chart and  the second chart will not show due to "display: none"
![image](https://user-images.githubusercontent.com/26947221/56471454-5cb05a00-6485-11e9-8225-ab655a582089.png)

But **if I delete the "display: none" of second chart** in the element inspector of Chrome,
![image](https://user-images.githubusercontent.com/26947221/56471479-b6b11f80-6485-11e9-85d6-958981751fa3.png)
Theoretically, the second chart will show, but .......
![image](https://user-images.githubusercontent.com/26947221/56471486-e52efa80-6485-11e9-88fa-a7eaf7651707.png)
Now, the second chart will be very strange.
The labels of x-axis will be cut off,  the bar will flow above the x-axis, and the legend will be mixed with the grid.

Thank you very much for reading the boring and long descriptions!

**Comment by junedchhipa** [comment]
Sorry for the delayed response. Thank you for the detailed description, very helpful :)
I would really appreciate if you create a working codepen example of the issue so I can quickly reproduce it.

**Comment by junedchhipa** [comment]
I tried with your same config and got this result
![Screen Shot 2019-05-04 at 3 32 17 PM](https://user-images.githubusercontent.com/17950663/57177505-db43c900-6e81-11e9-8e5e-47b53d9a4cf2.png)


Feel free to re-open the issue if you can reproduce it on codesandbox/codepen.
