### ISSUE TITLE
RTL support ?

### ISSUE THREAD

**Issue by mhf-ir** [apexcharts/apexcharts.js#53]

**Comment by mhf-ir** [comment]
Thank you for fast response :+1: 

Actually it's not rtl, just the translation. RTL text is CSS/HTML property.
See example: https://codepen.io/anon/pen/yxOZzr

**Comment by junedchhipa** [comment]
Thank you for enlightening me, I tested the `dir="rtl"` attribute on chart element and the tooltip got corrected. But the title text and legends got misaligned.

Here is what I got
![screen shot 2018-08-27 at 11 44 18 pm](https://user-images.githubusercontent.com/17950663/44677253-23892c80-aa53-11e8-92f8-0a56422a4580.png)

Looks messed up!
I haven't taken this into consideration in the beginning but will think about how this can be supported.

**Comment by fakhamatia** [comment]
Any update for RTL support?

**Comment by HaniGerges** [comment]
> Any update for RTL support?

+1

**Comment by SamiAziz** [comment]
I think you can solve RTL issue temporary if not supported by using (**Reversed Bar Chart**).

and make sure add formatter :
`formatter: function(val, opt) {
            return opt.w.globals.labels[opt.dataPointIndex] + ':  ' + val
  }`

the result:
![image](https://user-images.githubusercontent.com/29497735/83316859-2a992c00-a231-11ea-8f92-f083b120a99c.png)

**Comment by davidv171** [comment]
Was this ever added? I'm using a timeline chart, it's still oriented left to right, but what did happen is that the hover value stopped showing up.

**Comment by nofalx** [comment]
This issue is still not resolved

**Comment by YitshakS** [comment]
I will also appreciate for fixing this issue.
