### ISSUE TITLE
#491 bug still not fixed

### ISSUE THREAD

**Issue by mzy2240** [apexcharts/apexcharts.js#532]
Hey @junedchhipa I just checked the latest release (3.6.8) and I found the bug related to #491 is still not fixed, again. Here is the codepen: https://codepen.io/anon/pen/OGbwEG. The line is still compressing instead of window moving.

**Comment by junedchhipa** [comment]
Please comment in the same thread to avoid duplicated issues :)
I will re-open the same issue and take a look.
