### ISSUE TITLE
x-axis labels are not appears 

### ISSUE THREAD

**Issue by bashairm** [apexcharts/apexcharts.js#533]
## Codepen

https://codepen.io/anon/pen/YMjPEa
added to code-pen 

## Explanation

- What is the behaviour you expect?
the x-axis labels are too long  
- What is happening instead?
so it is not appearing correctly. 
- What error message are you getting?
half of it replaced with ...  and I need it all to be visible

thanks

**Comment by junedchhipa** [comment]
Increase the yaxis labels maxWidth by

```javascript
yaxis: {
   labels: {
     maxWidth: 200
   }
}
```
