### ISSUE TITLE
values be in decimal

### ISSUE THREAD

**Issue by bashairm** [apexcharts/apexcharts.js#535]
## Codepen

https://codepen.io/anon/pen/ZZMJXz

## Explanation

- What is the behavior you expect?
I want the values without the .00 

- What is happening instead?
the values be decimal with .00 
I want just value. How can I do that ?

![chart](https://user-images.githubusercontent.com/47118448/56573826-963ead80-65ca-11e9-929e-b37a8d53c9dc.png)

thanks

**Comment by junedchhipa** [comment]
Add this in the configuration
```javascript
tooltip: {
  y: {
    formatter: function(val) {
      return val
    }
  }
}
```
