### ISSUE TITLE
Add the ability to create multi-line annotations

### ISSUE THREAD

**Issue by mmagdyy** [apexcharts/apexcharts.js#536]
**Is your feature request related to a problem? Please describe.**
Annotations become clumsy and overlap with one another when the annotation text length increases.

**Describe the solution you'd like**
Add a multi-line feature to word-break the annotation text into multiple lines.

**Additional context**
I've tried to create multiple '<tspan>' elements manually and insert them into the annotation text but the charts reads them as a plain text not html elements.
Is there a way this can be supported (to pass html instead of plain text to the annotation inner text)?

**Comment by junedchhipa** [comment]
Sorry, multiline line text in SVG is not easily achieved and extra care has to be taken to other calculations just to implement it correctly.
Hence, this feature won't be implemented in the near future.
