### ISSUE TITLE
Incosistencies between Documentation / Code Examples / apexcharts.d.ts

### ISSUE THREAD

**Issue by appreciated** [apexcharts/apexcharts.js#537]
## Introduction

As you might already know I am currently working on a [port of ApexCharts.js to the Vaadin platform](https://github.com/appreciated/apexcharts). This requires me to map the whole vanilla-js API to a Java API.  

I am making great progress, I really like the style of this chart library.

## Inconsistencies

While creating this API I stumbled over some inconsistencies between the Documentation / Code Examples and the `apexcharts.d.ts` (I don't know how good it represents the vanilla JS API nevertheless it gave me a great kickstart allowing me to generate the attributes of the Java-API). 
While the `apexcharts.d.ts` seems to match pretty much always I found a difference between 
[This part](https://github.com/apexcharts/apexcharts.js/blob/master/types/apexcharts.d.ts#L481-L501) and the [Code examples](https://github.com/apexcharts/apexcharts.js/blob/master/samples/vanilla-js/radialBar/circle-gradient.html#L97-L114) and the [Documentation](https://apexcharts.com/docs/chart-types/radialbar-gauge/#dataLabels).

Another Inconsistency I found is the missing [dropShadow attribute in the `apexcharts.d.ts`](https://github.com/apexcharts/apexcharts.js/blob/master/types/apexcharts.d.ts#L453-L463). 

## Questions
- So which version one is now correct?
- Is this supposed to be that way? (I gladly report any other inconsistencies I find if you want me to)
- Which version should I now use?

**Comment by junedchhipa** [comment]
Hi,

The apexcharts.d.ts is generated by a bunch of users who wanted TypeScript support. As I don't know much of TypeScript, I rely on the community to make changes there.

So, [Options.js](https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/settings/Options.js) which is in the /src/modules/settings directory is the source of everything. Any new property will be added/removed from this file.

If you find inconsistencies between this file and `apexcharts.d.ts`, I would appreciate if you make a fix in the `apexcharts.d.ts` by opening a PR, which I will merge after reviewing.

Meanwhile, I will take a look at the example you provided.

Thanks,
Juned.

**Comment by appreciated** [comment]
> The apexcharts.d.ts is generated by a bunch of users who wanted TypeScript support. 

I see!

> As I don't know much of TypeScript.

So do I, I can read it but in fact I've never used it 🙈.

> If you find inconsistencies between this file and apexcharts.d.ts, I would appreciate if you make a fix in the apexcharts.d.ts by opening a PR, which I will merge after reviewing.

While this would be usually no problem at all, I think it would be better if this would done by somebody who has experience with TypeScript. I report any inconsistencies I find. 

> So, Options.js which is in the /src/modules/settings directory is the source of everything. Any new property will be added/removed from this file.

Thanks for the hint!
