### ISSUE TITLE
First and last bars in bar chart are cropped

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#540]
Hi, just started using this library and am loving it.

I've found an odd issue that appears to be caused by the way I'd like to structure my data.

It might be similar to this previous issue:

https://github.com/apexcharts/apexcharts.js/issues/280

I started with this example that works the way I want:

https://apexcharts.com/javascript-chart-demos/column-charts/column-with-data-labels/

Then I restructured the data to be the way I'd like it, example code in this repo:

https://github.com/ashleydavis/apex-charts-example

Now my first and last bars are cropped:

![image](https://user-images.githubusercontent.com/625126/56621173-d6f00280-666e-11e9-8cf9-6ce74d88180a.png)

Is this a bug or is this a mistake in the way that I'm using it?

Thanks so much.

**Comment by ashleydavis** [comment]
This is the code that renders the chart with the cropped bars:

```
var chartDef = {
    chart: {
        type: 'bar',
    },
    series: [{
        name: 'Inflation',
        data: [
            { x: 0, y: 2.3 }, 
            { x: 1, y: 3.1, },
            { x: 2, y: 4.0,  },
            { x: 3, y: 10.1,  },
            { x: 4, y: 4.0,  },
            { x: 5, y: 3.6,  },
            { x: 6, y: 3.2,  },
            { x: 7, y: 2.3,  },
            { x: 8, y: 1.4,  },
            { x: 9, y: 0.8,  },
            { x: 10, y: 0.5,  },
            { x: 11, y: 0.2 },
        ]
    }],
};

var chart = new ApexCharts(document.querySelector("#chart"), chartDef);

chart.render();

```

**Comment by junedchhipa** [comment]
Sorry for the late response.
The fix for the candlestick issue which you referenced was for datetime x-axis.
If you're seeing this issue in a numeric x-axis, I will take another look.

You can also avoid it by converting x-axis to category (if you're not plotting linear/datetime data). I will show an example soon.

**Comment by junedchhipa** [comment]
Adding this would prevent the cropping of the first and last bar
```javascript
   xaxis: {
      type: 'numeric',
      tickAmount: 'dataPoints'
    }
```

**Comment by ashleydavis** [comment]
Thanks adding `type: 'numeric'` does the job.

I'm integrated ApexCharts into my application:

http://www.data-forge-notebook.com/

I've love to give you a free copy of it and be able to get your feedback ;)

**Comment by junedchhipa** [comment]
Sorry for the late response, I missed your last message.
Sure, I would love to try it out ;)

**Comment by ashleydavis** [comment]
Awesome. Please send me an email to ashley@codecapers.com.au, then I'll have your email and I can sign you for a free copy of Data-Forge Notebook.

**Comment by EvanBarbour3** [comment]
@junedchhipa I'm having the same problem, but can't change my `type` to `numeric` or `category` as I have a large data set, and when changing it to one of these, I get lots of labels that overlap one another (even when `hideOverlappingLabels` is used, or `tickAmount` is a number like 10, it still shows them all).

For me, only the last column is cropped off

![Screenshot 2019-05-23 at 17 25 00](https://user-images.githubusercontent.com/7600557/58269759-20239700-7d80-11e9-8b0a-a0f4c8db1b54.png)
![Screenshot 2019-05-23 at 17 23 25](https://user-images.githubusercontent.com/7600557/58269761-20239700-7d80-11e9-8281-2d7dd1d9cc82.png)

Should this be a new issue?

**Comment by Evanda-crypto** [comment]
Hello..may I get help why my graph is showing 23rd instead of 1st..This occurs for every month in apex chart.
![Screenshot from 2023-09-01 10-37-50](https://github.com/apexcharts/apexcharts.js/assets/93912360/69f0e124-0bd7-421e-800c-4c8e42af0fa0)
![Screenshot from 2023-09-01 10-38-54](https://github.com/apexcharts/apexcharts.js/assets/93912360/ca399e75-619e-463d-854b-3623008d0a62)
