### ISSUE TITLE
Scroll for bar chart

### ISSUE THREAD

**Issue by ismaildervisoglu** [apexcharts/apexcharts.js#543]
**### Problem**

We have a large data set. We need to display this dataset with a bar chart. With the current features, the columns of the bar graph appear to be very narrow. Is it possible to add a scroll for the bar chart like this?  
![scrool_barchart](https://user-images.githubusercontent.com/35444583/56661924-7501be00-66ab-11e9-85b7-835415f665e9.png)

**Comment by junedchhipa** [comment]
Sorry, this feature is not available in the current version of ApexCharts.

**Comment by lordsfantasy** [comment]
Any update on this? We too have large sets of data and would like to have a scrollbar in the chart area.

**Comment by mauroviniciussilva** [comment]
Have an idea on how to solve this problem. Not a great solution, but it works. In the `height` propery I just calculate the length of my array and multiply for the height I want for each bar:

```JS
this.options = {
    chart: {
        height: array.length * 20,
        ...
    },
    ...
}
```

Then, I wrapped my chart in a `div` with a fixed height and the scroll property set to auto:

```html
<div class="graphic-container">
    <!-- Your chart goes here -->
</div>
```
The `graphic-container` class only have this:

```CSS
.graphic-container {
  min-height: 300px;
  max-height: 300px;
  overflow-y: auto;
  overflow-x: hidden;
}
```

Voilá

![image](https://user-images.githubusercontent.com/49000408/98954500-9b30be00-24dc-11eb-8c87-7b72fcaa8440.png)

**Comment by bahung1221** [comment]
The problem with the above solution is the xaxis isn't sticky.
It seems that the chart structure must be changed to achieve sticky xaxis (just like [highcharts scrollable](https://www.highcharts.com/docs/chart-concepts/scrollbar)), 

May I have a future request for it?

**Comment by luchosilva** [comment]
Any update on this? :eyes:
