### ISSUE TITLE
Missing options on Annotations' position documentation

### ISSUE THREAD

**Issue by haroflow** [apexcharts/apexcharts.js#544]
Hello!

Not really a bug, but I've noticed that some options for the yaxis.label.position key for annotations are missing on the "Available Options": https://apexcharts.com/docs/options/annotations/

For Y-Axis it also accepts "right" and "left".

Thank you!

**Comment by junedchhipa** [comment]
Thanks for pointing it out.
Actually, y-axis annotations just accept `left` and `right` positions. `top` and `bottom` are for x-axis.

Fixed it on the website.
