### ISSUE TITLE
Tooltip was not working on pie chart in Firefox 45 version 

### ISSUE THREAD

**Issue by balaramc** [apexcharts/apexcharts.js#545]
hi,
I am using apex charts in Firefox 45 version but in pie chart i am unable to see the tool tip. also in apex demo page also i am unable to see the tool tip in PIE charts

Any solution for this problem will helpful

**Comment by junedchhipa** [comment]
It was a bug in Firefox older versions ([Foreign object preventing mouse events](https://stackoverflow.com/questions/25972013/events-not-triggering-in-foreignobject-for-firefox))

The bug is fixed in recent versions of Firefox.
