### ISSUE TITLE
Work logic for Pie - expandOnClick.

### ISSUE THREAD

**Issue by zxcdimka** [apexcharts/apexcharts.js#547]
When clicked on the pie / donut slice, the data in the circle should be saved. Now you remove the mouse and the data disappears. Is there any solution for this?
Today I will be insistent :) How to increase the "donut slice" when you hover the mouse?

**Comment by junedchhipa** [comment]
Your first option can be enabled by

```javascript
options = {
  plotOptions: {
    pie: {
      donut: {
        labels: {
         show: true
        }
      }
    }
  }
}
```
Please update to the latest version of apexcharts to allow it to work - https://cdn.jsdelivr.net/npm/apexcharts@latest

Regarding your second question, increasing donut slice size on hover is not supported currently.
