### ISSUE TITLE
axisBorder does not work

### ISSUE THREAD

**Issue by mzy2240** [apexcharts/apexcharts.js#549]
## Codepen

https://codepen.io/apexcharts/pen/bxzgZJ

## Explanation

- What is the behavior you expect? Have a axis line with different color at Y=0.
- What is happening instead? Nothing.
- What error message are you getting? Nothing.

**Comment by junedchhipa** [comment]
Please provide updated codepen. The one you provided is the basic ApexCharts template.

**Comment by mzy2240** [comment]
The codepen is updated.

**Comment by junedchhipa** [comment]
`axisBorder` will not show at 0 value.
It just means that the dark border that appears above x-axis labels can be customized with that property.

To show a line on 0 value, you might need to look into [yaxis annotations].(https://apexcharts.com/docs/options/annotations/#yaxis)
