### ISSUE TITLE
Theme examples?

### ISSUE THREAD

**Issue by zocheyado** [apexcharts/apexcharts.js#55]
Not a bug exactly but I just read over all the docs and I can't seem to find an example of what theme's look like. I see that there are 10 presets but not what they look like. Any chance this is planned?

**Comment by junedchhipa** [comment]
I will add a demo of all theme on the theme page with a dropdown so the user can see which colors are in the theme

**Comment by junedchhipa** [comment]
Here is the [codesandbox demo](https://codesandbox.io/s/qzjkzmzxoj) 

And, here is the updated website page
https://apexcharts.com/docs/themes/

**Comment by qroft** [comment]
Just to make sure that i understood the "themes" part correct: once that it is set up, the colors should appear automaticaly or do we need to manualy use the "colors" attribute for the series?
