### ISSUE TITLE
Heatmap performance

### ISSUE THREAD

**Issue by it-xtech-dev** [apexcharts/apexcharts.js#550]
Hello,

I have a heatmap chart with 36x60 data point resolution. It seems not much as for the heat map:
https://codepen.io/anon/pen/jRXgmL?editors=1010

On my developer machine this renders ca. 1000 ms. It's quite a lot when to consider that this is desktop developer machine (Intel Core i5, 2.8Ghz). When i use my Samsung Tab A tablet time increases to few seconds.

Its a noticeable **LAG**.

I would like to use multiple charts on a single page and i'm afraid it could lead to page blocking for few seconds.

Is there any way to solve this issue? Maybe there is something wrong with my understanding of this chart?

**Comment by junedchhipa** [comment]
SVG is noticeably slower while rendering lots of elements in the DOM. Your chart renders around 2200 DOM elements because each heatmap rect is a separate DOM element. Even if the rendering logic is optimized, there will be some lag in this case.

The same data-points, if rendered in a line/area chart will render fine as a line/area chart just have 1 main `path` element.

Sorry, but there is no solution to allow rendering lots of data-points in a heatmap chart.

**Comment by it-xtech-dev** [comment]
So for this particular chart type an alternative could be a canvas? 
I know it would broke other chart features like tooltips, zooming etc...
But any way can this be considered as more efficient alternative?

**Comment by junedchhipa** [comment]
Yes, canvas is best to render a heatmap chart with lots of data-points.
Chart.js is drawn with canvas, but it doesn't have heatmap.
One alternative is to use WebGL for performance (plotly.js does it, but it's too heavy in size).

**Comment by it-xtech-dev** [comment]
OK,

One more question - I'm trying to understand potential performance bottle necks when using ApexCharts. Although I truly admire Apex for wide range of functions I would be also glad to know its limitations.

As I properly understand SVG / DOM performance bottle neck will be also revealed when I will have multiple charts on a single page (dashboard)? Is there any way to estimate how many chart is "to much" in this case?

**Comment by junedchhipa** [comment]
Well, I don't have a very definite answer to that, as even one or two charts can be too much with a lot of data while you can have 20 simple charts with not so complex data-series.

You can check out the dashboard examples - https://apexcharts.com/javascript-chart-demos/dashboards/material/ to get a better idea.

**Comment by it-xtech-dev** [comment]
OK, thanks for all the answers!
