### ISSUE TITLE
Zero values are plotted and are getting overlapped

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#552]
## Codepen

Modify [this codepen](https://codepen.io/vjakair/pen/OGdraR) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation
Chart Typed: Stacked bar chart
Need a way to handle uneven data.
- What is the behavior you expect?
Zero values shouldn't be displayed in stacked bar chart
- What is happening instead?
Zero values are getting displayed.
- What error message are you getting?
No error messages.

FYR: 
![image](https://user-images.githubusercontent.com/8254178/56849390-45ec8600-6911-11e9-8c41-0889d72cd180.png)

**Comment by junedchhipa** [comment]
Can you please update the codepen link? It is showing the default ApexCharts template

**Comment by irshadahmed** [comment]
This issue exist in 3.6.5, but not in the latest version.. Hence closing the issue.

**Comment by irshadahmed** [comment]
> Can you please update the codepen link? It is showing the default ApexCharts template

@junedchhipa  Thanks for your quick response.

I updated the pen. However I see another issue with the latest version, the actual values are not displayed for some of the categories. Is it intentional ?
![image](https://user-images.githubusercontent.com/8254178/56849615-78e44900-6914-11e9-937d-2bd3e0d5cba0.png)

You can refer the same pen: https://codepen.io/vjakair/pen/OGdraR

**Comment by junedchhipa** [comment]
Yes, it was intentional to hide the labels which don't fit the area.
I am planning to add an option to allow the user to control whether to hide/show in such case.

**Comment by irshadahmed** [comment]
> Yes, it was intentional to hide the labels which don't fit the area.
> I am planning to add an option to allow the user to control whether to hide/show in such case.

Makes sense. Thanks a lot for all your support.

**Comment by junedchhipa** [comment]
A new property named `hideOverflowingLabels` is added in `plotOptions.bar.dataLabels` which will allow controlling the overflowing text issue for small values in stacked bar/column charts.

**Comment by irshadahmed** [comment]
> A new property named `hideOverflowingLabels` is added in `plotOptions.bar.dataLabels` which will allow controlling the overflowing text issue for small values in stacked bar/column charts.

This is awesome :)
