### ISSUE TITLE
pie chart appears clipped 

### ISSUE THREAD

**Issue by bashairm** [apexcharts/apexcharts.js#555]
## Codepen

https://codepen.io/anon/pen/BEbMjp

## Explanation

- What is the behavior you expect?
I want the apex pie chart appear to fit the screen size but in some size its not appear good
- What is happening instead?
the pie chart appears clipped 
this how its appear in the website :
![image](https://user-images.githubusercontent.com/47118448/56877333-ea77e080-6a55-11e9-839c-5a8afa200bd8.png)

**Comment by junedchhipa** [comment]
You have to either provide `height` or `weight`. 
```javascript
chart: {
  width: 350,
  height: 'auto'
}
```

**Comment by bashairm** [comment]
it didn't work good

**Comment by junedchhipa** [comment]
Removed all unnecessary configuration code.
And the chart is rendering correctly.

[Codepen](https://codepen.io/apexcharts/pen/yWVBLy)
