### ISSUE TITLE
Legend click bug

### ISSUE THREAD

**Issue by caoguotao** [apexcharts/apexcharts.js#556]
## Codepen
https://codepen.io/tao1874/pen/QPoXZe

## Explanation

- What is the behavior you expect?
After I click on legend marke "Series1" and "Series2" , the line will be render when i click a legender marker
- What is happening instead?
 the line is't  render when i click  anyone of them again.
- What error message are you getting?
![image](https://user-images.githubusercontent.com/39721479/56884517-a22fe100-6a9c-11e9-8693-5a8147bf098b.png)

**Comment by junedchhipa** [comment]
I just checked the codepen demo and the bug doesn't appear.
Which browser you're testing? Can you also specify the version of apexcharts you tested on?

**Comment by junedchhipa** [comment]
Closing as no response.
Feel free to re-open if you're able to reproduce the error.
