### ISSUE TITLE
Y-axis put image ?

### ISSUE THREAD

**Issue by JACK123wang** [apexcharts/apexcharts.js#557]
HI!
I want to put icon to y-axis ,but I don't find any method to do it.

example:
![擷取3](https://user-images.githubusercontent.com/47593069/56886555-d8bc2a80-6aa1-11e9-8b10-f12cf37fa003.PNG)
Put the icon of sun to Y-axis.
thank you for your help!

**Comment by junedchhipa** [comment]
Duplicate of #574
