### ISSUE TITLE
Repetaed yaxis tick value when max value is small

### ISSUE THREAD

**Issue by disagol** [apexcharts/apexcharts.js#56]
I've been experiencing some difficulties when trying to render an apexchart when the value  of the yaxis is repetaed across xaxis values. 
[Here](https://codepen.io/anon/pen/wEWpdG) is the example I am talking about. Any advise or guidance would be greatly appreciated. 
Thanks.

**Comment by junedchhipa** [comment]
You are trying to create a backward timeline, meaning the larger datetime value is printed before the smaller datetime value.

I updated your [codepen](https://codepen.io/apexcharts/pen/jvrYpL) example and see no issue with small values in y-axis

**Comment by disagol** [comment]
Ohh I see, anyway It was happening for forward timeline too but It seems this line val.toFixed(2) i the formatter did the job.
Thanks for your time!

**Comment by junedchhipa** [comment]
No worries
