### ISSUE TITLE
Use JS to select position on chart?

### ISSUE THREAD

**Issue by tommyhansson** [apexcharts/apexcharts.js#565]
Using javascript, is it possible to "highlight" a X position on the chart? So that it behaves just as if the cursor was on that X position, showing the tooltip and all. Something like this:

```
<button>Go to position 3</button>
<script>
document.querySelector('button').addEventListener('click', function(){
chart.highlightPosition(3);
});
</script>
```
Hope my question is clear :)

**Comment by junedchhipa** [comment]
Sorry, programmatically firing tooltip events is not currently possible, it might come in future.

**Comment by nhh** [comment]
Any updates on this? We are currently missing this feature? Are there workarounds?

**Comment by y0nd0** [comment]
Wait this feature request is closed because the feature does not exist? xD

**Comment by StarryFire** [comment]
Are there any plans to work on this feature?

**Comment by j3dyy** [comment]
are there any feature or workaround ?

**Comment by skyracer2012** [comment]
You might be able to use
https://echarts.apache.org/en/api.html#action.tooltip.showTip
