### ISSUE TITLE
Pass to yaxis max/min property the min/max values on the selected timeframe

### ISSUE THREAD

**Issue by AurelReb** [apexcharts/apexcharts.js#566]
**Is your feature request related to a problem? Please describe.**
Create a function with the min / max properties of yaxis, which would allow us to zoom automatically on the yaxis when we change the xaxis selection.

**Describe the solution you'd like**
In the function, it would be interesting to add an argument named minOnSelection so that the function looks like this:
```javascript
{
  yaxis: {
    min: (min, minOnSelection) => //...
    max: (max, maxOnSelection) => //...
  }
}
```
for example, if a series includes y-values between 1 and 10, but the x-axis scale on this series includes only y-values between 5 and 7, min should be equal to 1 and minOnSelection should be equal to 5

The feature would be handy for many people I think.

**Comment by junedchhipa** [comment]
We have `zoom.autoScaleYaxis` property. Unfortunately, this property is not in the docs as it is not finished yet.
As you've already contributed to the initial idea of scaling Y-axis on zooming, I need to make it work for multi-yaxis too.
Thanks for another suggestion!

**Comment by junedchhipa** [comment]
Added the option `chart.zoom.autoScaleYaxis` which fixes the above issue.

**Comment by mattwensing** [comment]
Can this option also be used somehow for an `area` type of chart?  Here's my options; I'm not seeing the desired behaviour: 

```
      chart: {
        type: 'area',
        stacked: false,
        height: 350,
        zoom: {
          type: 'x',
          autoScaleYaxis: true,
          enabled: true
        },
        toolbar: {
          autoSelected: 'zoom'
        }
      },
```
