### ISSUE TITLE
Thick overlapping bars in bar charts

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#569]
I've found another odd issue.

I've managed to create a bar chart with thick overlapping bars that looks as follows:

![image](https://user-images.githubusercontent.com/625126/57126340-040b8600-6dd0-11e9-88a6-be5a8ccf4e9d.png)

Note also that if I change the xaxis data type from "categories" to "numeric" I get no bars at all! Just an empty chart.

Any advice on how I could correct this?

Here's a zip file with example code and data:

[apex-charts-example.zip](https://github.com/apexcharts/apexcharts.js/files/3141102/apex-charts-example.zip)

**Comment by rogerioufjf** [comment]
Same problema here. Any solution?

**Comment by ashokkumarsundar** [comment]
Same problem. Any one have solution to this?

**Comment by junedchhipa** [comment]
@rogerioufjf @ashokkumarsundar Please provide a codepen to reproduce the issue.

**Comment by ashokkumarsundar** [comment]
Here is the codepen url : https://codepen.io/ashok999333/pen/MWayyyY

**Comment by junedchhipa** [comment]
Seems like your data is not sorted into ascending order.
Updated the codepen - https://codepen.io/apexcharts/pen/ExVKKgN

Re-opening the issue as the data should have been automatically sorted when `xaxis.sorted` is true.

**Comment by fosks45** [comment]
Hey, are there any updates on this at all? I have the same issue using type: 'dateTime'. Oddly for me it looks like if I have an even number of data points it causes the about behavior. Changing to type: 'categories'  and reversing the categories and the series data results in the chart being displayed as expected, but I lose the functionality that comes with the dateTime type, so it's not really an option for me.

**Comment by ashokkumarsundar** [comment]
@fosks45 the way I used workaround this without losing the date time functionality is :
Sort the data by x axis (date time field in my case) before giving it to apex chart fixed the issue temporarily.

**Comment by fosks45** [comment]
> @fosks45 the way I used to workaround this without losing the date time functionality is :
> Sort the data by x axis (date time field in my case) before giving it to apex chart fixed the issue temporarily.

So, as the data is currently sorted as I want it to be, you suggest, sort it again (reverse()) before I supply it to apex, then sort it again as I give it to the argument?
