### ISSUE TITLE
Question: Access chart data inside legend

### ISSUE THREAD

**Issue by apertureless** [apexcharts/apexcharts.js#57]
Hi, 

is it possible to access the chart data inside the legend?
For example I want to show the individual value next to the legend text in a doughnut chart.

```js
labels: ['A', 'B', 'C']
series: [100, 20, 55]
```

And the legend should display:

```
🔴  A - 100
🔵  B - 20
⚫️  C - 55
```

However inside the `legend.formatter` I have only access to the label itself.

**Comment by junedchhipa** [comment]
Very good point and I have already taken that into consideration.
You can do it like this

```javascript
legend: {
    formatter: function(val, opts) {
        return val + " - " + opts.globals.series[opts.seriesIndex]
    }
}
```
![screen shot 2018-08-28 at 5 31 14 pm](https://user-images.githubusercontent.com/17950663/44721629-326dee80-aae8-11e8-80cc-739972a68911.png)

Will add in the docs.
PS:  I need to write better docs, I suck at it ;)

**Comment by apertureless** [comment]
Sweet! Thanks 🙏 

Followup question: Is it possible to pass in custom markup for the labels?

**Comment by junedchhipa** [comment]
Not directly, but there is another way you can style your legend text elements.

If you return an array in the `legend.formatter` function, your texts are split into different tspan elements inside the parent <text> element. So, you can then target them with CSS and apply styles.

Here is how you would format the `legend.formatter` function
```javascript
legend: {
    formatter: function(val, opts) {
        return [val, " - ", opts.globals.series[opts.seriesIndex]]
    }
}
```

and then you can apply CSS like
```css
.apexcharts-legend-text tspan:nth-child(1) {
    font-weight: lighter;
    fill: #999;
}

.apexcharts-legend-text tspan:nth-child(3) {
    font-weight: bold;
}
```

which will result in legend like these
![screen shot 2018-08-28 at 6 36 50 pm](https://user-images.githubusercontent.com/17950663/44724778-5aae1b00-aaf1-11e8-8019-bf04f2291995.png)

**Comment by junedchhipa** [comment]
btw, you might need to update the apexcharts version to v1.3.14 to use the above settings

**Comment by apertureless** [comment]
Ah I see, thanks!

**Comment by MedinaGitHub** [comment]
opts.globals NOT WORKING

**Comment by junedchhipa** [comment]
The params have changed a little bit for `legend.formatter` function in the last update.
Please see the docs - https://apexcharts.com/docs/options/legend/#formatter

```javascript
legend: {
    formatter: function(val, opts) {
        return [val, " - ", opts.w.globals.series[opts.seriesIndex]]
    }
}
```

**Comment by junedchhipa** [comment]
Ah! I see you're already using opts.w.globals.
Are you using v2.2.1?

**Comment by gemmagarcias1** [comment]
> ```css
> tspan:nth-child(3)
> ```



> Not directly, but there is another way you can style your legend text elements.
> 
> If you return an array in the `legend.formatter` function, your texts are split into different tspan elements inside the parent element. So, you can then target them with CSS and apply styles.
> 
> Here is how you would format the `legend.formatter` function
> 
> ```js
> legend: {
>     formatter: function(val, opts) {
>         return [val, " - ", opts.w.globals.series[opts.seriesIndex]]
>     }
> }
> ```
> 
> and then you can apply CSS like
> 
> ```css
> .apexcharts-legend-text tspan:nth-child(1) {
>     font-weight: lighter;
>     fill: #999;
> }
> 
> .apexcharts-legend-text tspan:nth-child(3) {
>     font-weight: bold;
> }
> ```
> 
> which will result in legend like these
> ![screen shot 2018-08-28 at 6 36 50 pm](https://user-images.githubusercontent.com/17950663/44724778-5aae1b00-aaf1-11e8-8019-bf04f2291995.png)

Is not working anymore? I need it...

**Comment by chaimmw** [comment]
I am trying to return an array from the legend formatter, but I am getting a type error
```
(method) ApexLegend.formatter?(legendName: string, opts?: any): string
Type '(val: string) => string | string[]' is not assignable to type '(legendName: string, opts?: any) => string'.
  Type 'string | string[]' is not assignable to type 'string'.
    Type 'string[]' is not assignable to type 'string'.ts(2322)
apex-types.d.ts(643, 5): The expected type comes from property 'formatter' which is declared here on type 'ApexLegend'
```
