### ISSUE TITLE
Can't rotate y-axis labels on stacked bar chart

### ISSUE THREAD

**Issue by HorizonShadow** [apexcharts/apexcharts.js#571]
## Codepen

https://codepen.io/anon/pen/mYbVKq

## Explanation

- What is the behavior you expect?

The y-axis labels should rotate.

- What is happening instead?

They're not rotating

- What error message are you getting?

There is no error message.

**Comment by junedchhipa** [comment]
Thanks for reporting. Fixed it.
Will be released in 3.6.10
Just make sure you also increase the `yaxis.labels.maxWidth` to some bigger value to prevent the ellipsis in the text.

**Comment by HorizonShadow** [comment]
Thanks for the quick turn around!
