### ISSUE TITLE
Stacked column chart not rendering

### ISSUE THREAD

**Issue by jasonclemens** [apexcharts/apexcharts.js#572]
We have a single-column stacked column chart that has been working until we updated vue-apexcharts to  to 1.3.4 (from 1.3.3) and apexcharts to 3.6.9 (from 3.6.6). After updating, the chart no longer renders, although the axis, legend and grid does. 

If the series data contains more than one data point in the array, like this...

```javascript
series: [
        {
          name: "Cost of Funds",
          data: [4, 5]
        },
        {
          name: "Option Spread",
          data: [3, 4]
        },
        {
          name: "Credit Spread",
          data: [1, 6]
        }
      ]
```
...the chart columns render fine:
![alt text](https://almfirst.com/public/2-points.png "1 point = No Render")

 

If there is only one data point...
```javascript
series: [
        {
          name: "Cost of Funds",
          data: [4]
        },
        {
          name: "Option Spread",
          data: [3]
        },
        {
          name: "Credit Spread",
          data: [1]
        }
      ]
```
...no chart renders:
![alt text](https://almfirst.com/public/1-point.png "1 point = No Render")

Before the update, a single column was rendering fine. Any ideas?

**Comment by junedchhipa** [comment]
Can you post the full example, please? As I tried with the series you provided and it rendered fine.

**Comment by jasonclemens** [comment]
Here's the code:
https://codepen.io/yehawdude/pen/zQGqRx

"series1" shows that 1-column series doesn't render. Use "series2" to test 2-column data (working).

**Comment by junedchhipa** [comment]
Thanks for the demo, I will look soon.

**Comment by junedchhipa** [comment]
Looks like you forgot to provide `xaxis.categories` or maybe you intentionally omitted it.

Adding
```javascript
xaxis: {
          categories: [1, 2],
          labels: {
            show: false
          }
}
```
gets the chart back.

Thank you for your patience.

**Comment by jasonclemens** [comment]
Thank you very much. I wouldn't have guess this, but it makes sense. I guess it was a change to require this in the latest version...
