### ISSUE TITLE
Badly formatted values in y axis

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#573]
I found another issue that might need looking at.

When I set fractional minimum and maximum values I get badly formatted y axis:

![image](https://user-images.githubusercontent.com/625126/57174924-f82fca80-6e88-11e9-9d7e-63daa9587e5d.png)

Formatting still has way too many decimal places if I remove the min/max from the chart definition:

![image](https://user-images.githubusercontent.com/625126/57174932-1ac1e380-6e89-11e9-8bee-90e2422ddd0d.png)

I'm using latest version of ApexCharts that's available for download from the ApexCharts landing page.

Here is example code:

[apex-charts-example.zip](https://github.com/apexcharts/apexcharts.js/files/3144077/apex-charts-example.zip)

**Comment by junedchhipa** [comment]
Your initial series values contain decimal values with 16 digits after the decimal place.
So, ApexCharts preserves the original decimal place settings.

You can easily change it by
```javascript
   "yaxis": [{
        "min": -2.01,
        "max": 5.17,
        "labels": {
            "formatter": function (val) {
                return val.toFixed(2)
            }
        }
    }]
```

**Comment by ashleydavis** [comment]
Ok that makes sense.
