### ISSUE TITLE
How to put img on the lables of y_axis?

### ISSUE THREAD

**Issue by Hao-Wei-Huang** [apexcharts/apexcharts.js#574]
I want to put img to the lables of y_axis,but I try formatter: function (val) {return val}.
yaxis: {
		labels: {
			 formatter: function (val) {
					return val
		         },
                },
},
I want to replace val with tag img.
However,I don't do that like this picture.
![擷取3](https://user-images.githubusercontent.com/47593069/57175264-4ee2d780-6e7c-11e9-8887-a8c0d6b0b619.PNG)
How to achieve this picture?
Thanks to your help!

**Comment by junedchhipa** [comment]
This is not possible but is in the roadmap.
Thanks for the suggestion.

**Comment by havardl** [comment]
@junedchhipa - any updates on this? Is it possible to do on the x-axis?

**Comment by reachrahul** [comment]
@havardl did you manage to do this somehow? showing the images with yaxis labels?

**Comment by Tobjoern** [comment]
Are there any updates on this?

**Comment by pepaulo8** [comment]
Any updates here? I really need to put some images on axis

**Comment by developervinoth** [comment]
Any Updates on this, I have a similar kind of requirement.

**Comment by RadisavRistic** [comment]
Any updates?

**Comment by mtinnes** [comment]
This would be great, we are looking for a way to use a country flag as the label, rather than text.

**Comment by yehiasalam** [comment]
yup same, looking to add the profile photos of the users in y-axis in the bar chart, would be much neater.

**Comment by peshanghiwa** [comment]
Any updates?

**Comment by neolee6053** [comment]
Any updates?

**Comment by mrdrews-hub** [comment]
any update ?

**Comment by MFaqihRidho** [comment]
Any updates?
