### ISSUE TITLE
Be able to specify a label format string for formatting labels on xaxis and yaxis

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#575]
Would it be possible for you to add a label formatting string to the ApexChart chart definition?

For example:

```
yaxis: {
    labels: {
        format: "0.00",
    }
}
```

Or 

```
xaxis: {
    labels: {
        format: "DD/MM/YYYY",
    }
}
```

The library [Numeral.js](http://numeraljs.com/#format) could be used for number formatting. Or [Dayjs](https://www.npmjs.com/package/dayjs) for date formatting.

I could do the same thing with the `formatter` function, but have you considered integrating this kind of functionality directly?

**Comment by junedchhipa** [comment]
ApexCharts does the basic datetime formatting, then leaves on the user to do advanced stuff with the help of other 3rd party libs (in the formatter function).
Integrating it directly would increase the library size drastically.
