### ISSUE TITLE
Zoom with mouse out of graph

### ISSUE THREAD

**Issue by bencultureinfo** [apexcharts/apexcharts.js#578]
Hello all,

I'm writing you to ask, how to do when I want to zoom on the right/left borders? It's very hard to select the last values...

[![screenshot-cloud le-vert net-2019 05 06-10-08-30](https://user-images.githubusercontent.com/50316605/57213401-009e1780-6fe7-11e9-8bc0-bf20b8aba715.png)(https://cloud.le-vert.net/s/oGdRRcXSsgpxdQJ)](https://cloud.le-vert.net/s/oGdRRcXSsgpxdQJ)

How I can do to keep the right click event enabled if the mouse is out of the graph ?
And then, zoom on the last values ?

Thanks for your help and thanks for apexcharts !

Benoit.

**Comment by junedchhipa** [comment]
Yeah, that seems like a bug.
I will check the mouse-move event to determine if the user was zooming, and based on that, zoom in to the outermost values.
Thanks for reporting the bug.

**Comment by bencultureinfo** [comment]
Thanks a lot for your work !
Now I will try to keep the zoom level when data has been refreshed !

**Comment by haroflow** [comment]
@junedchhipa @bencultureinfo Hi! I needed this fixed as well...

I made some changes and worked for my use case, if anyone would like to take a look and implement it officially here's the diff: https://gist.github.com/haroflow/ace6fe4a7aea490a1101cc8f6ea8ce08

Thanks to everyone!

**Comment by junedchhipa** [comment]
@haroflow thanks
I will check out your solution.

**Comment by haroflow** [comment]
Works for us, thank you very much!

**Comment by bencultureinfo** [comment]
Thanks a lot for your dev !! It is ok !
