### ISSUE TITLE
Chart selection bugs with dynamic data

### ISSUE THREAD

**Issue by cschwengler** [apexcharts/apexcharts.js#579]
Hello, I noticed 2 bugs when using the selection option of the chart with dynamic data. The codepen is only an enhanced version of your brush demo found here: "https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/".

## Codepen

https://codepen.io/anon/pen/EzxBJe

## Explanation Bug 1

- What is the behavior you expect?
Data selection window should keep its position after a updateSeries() call, when moved before.

- What is happening instead?
Data selection window jumps to its initial position.

- How to reproduce?
In the codepen first move the selection window, then click "Add Data". Now the selection window jumps to its initial position.

- What error message are you getting?
None

## Explanation Bug 2

- What is the behavior you expect?
When updating the series the window should keep its position and update the upper graph accordingly.

- What is happening instead?
Data selection window moves to the left until it moves out of the window. Or when creating a new selection window (not moving the current) it stays on its position but doesn't update the upper graph.

- How to reproduce?
In the codepen click "Animate second bug". Now the selection window moves to the left until it moves out of the window or when you have created a new selection window the selection window keep its position but doesn't update the upper graph.

- What error message are you getting?
None

Thanks,
hope you can help me out!

**Comment by quexten** [comment]
I'm experiencing the same bug using the vue version of apexcharts.

**Comment by larsmathuseck** [comment]
Same here, using the react version..

**Comment by zxpectre** [comment]
Same here, any news? workarounds?

**Comment by Huggzorx** [comment]
I'm just having this same issue, also using vue. Anybody find a workaround?
