### ISSUE TITLE
Trigger Specific legendClick or pieClicked intially 

### ISSUE THREAD

**Issue by tatva-hiral** [apexcharts/apexcharts.js#580]
Hi,
I want to get an initial(default) series selected while initial load to highlight the pie, and want to change the default seriesIndex selected option.

Right now, Dount pie is not affected while I m triggering click event on specific series.

$('.apexcharts-legend-series[rel = ' + (seriesIndex) + '].active').trigger('click');

I'm looking forward to your positive reply.

Thanks in Advance.

**Comment by tatva-hiral** [comment]
Hi @junedchhipa,
Thanks for the follow-up, can you please give me an approximate ETA for the completion of this enhancement.
Thanks again.

**Comment by capitamalta** [comment]
Dont be rude

**Comment by tatva-hiral** [comment]
Not sure if my message sounds like a rude, I never intended for that. I aim was to check if the library is being enhanced to add a feature of handling chart events by outer elements then if that is possible to release in the coming days.

**Comment by junedchhipa** [comment]
What @capitamalta meant is - It is not cool to ask for ETA for a new feature in an open-source library.
You could have better waited for any of us to respond if the feature is planned to be added :)

Anyways, to answer the original question, pre-selecting a data-point on the first load is being considered. Unfortunately, I don't have an ETA for it.

**Comment by Alex-Sokolov** [comment]
It will be useful to show information about the largest part of the chart after its initialization

**Comment by lunvjp** [comment]
Hey guys, Any progress on this? I need the same idea as well. Hic.

**Comment by Amosss** [comment]
+1 is there a way to set an initial pie slice selection? 
In other words, call the click event with a certain pie slice when the page loads.
Thanks

**Comment by abboos** [comment]
> +1 is there a way to set an initial pie slice selection?
> In other words, call the click event with a certain pie slice when the page loads.
> Thanks

You can find the solution here:
[https://github.com/apexcharts/apexcharts.js/issues/16](url)
