### ISSUE TITLE
Bar chart with "categories" data type for xaxis doesn't show tooltips

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#581]
I've discovered an issue that seems to prevent tooltips from working on a bar chart.

Example code is attached. If you hover the mouse over a bar there is no tooltip.

However if you remove the following code tooltips will work:

```
    "xaxis": {
        "type": "categories"
    }
```

Probably something I'm doing wrong, but I'm not sure.

[apex-charts-example.zip](https://github.com/apexcharts/apexcharts.js/files/3151359/apex-charts-example.zip)

**Comment by junedchhipa** [comment]
`xaxis.type: category`
https://apexcharts.com/docs/options/xaxis/#type

**Comment by ashleydavis** [comment]
Thanks so much for putting up with my silly mistakes.

**Comment by ashleydavis** [comment]
Actually not so much a silly mistake of mine... it looks like I got this wrong because the Apex TypeScript type definitions are wrong:

![image](https://user-images.githubusercontent.com/625126/57413138-6f24e480-7236-11e9-9681-e64dd4026a00.png)

**Comment by junedchhipa** [comment]
Ahh!
Re-opening it in case I miss to fix it.

**Comment by ashleydavis** [comment]
Thanks so much.
