### ISSUE TITLE
Legends appear for categories whose values are zero

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#584]
## Codepen

Modify [this codepen](https://codepen.io/vjakair/pen/qGZONO) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behavior you expect?
  In the stacked bar chart we don't plot zero values, as it doesn't make sense as well. But in contrast we are showing legends. What I feel is, when there is no curresponding values plotted, we should not show legends as well.
- What is happening instead?
Legends appear for those categories whose values is zero.
- What error message are you getting?
No error

FYR:
![image](https://user-images.githubusercontent.com/8254178/57506093-66a4da80-7318-11e9-86ce-7051a3f4042f.png)

**Comment by junedchhipa** [comment]
There is a property called [showForZeroSeries](https://apexcharts.com/docs/options/legend#showForZeroSeries) for this.
Try
```javascript
  "legend":{
     "showForZeroSeries": false
   }
```

**Comment by irshadahmed** [comment]
@junedchhipa This works!!! Thank you very much :)
