### ISSUE TITLE
Line color based on value

### ISSUE THREAD

**Issue by kentrh** [apexcharts/apexcharts.js#585]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to set color on line based on value. I'd really like to set a different color on the line when it's below zero. 

**Describe the solution you'd like**
Set the color as a function with value as parameter. 

**Describe alternatives you've considered**
`const color = value => value >= 0 ? "#00ff00" : "#ff0000";`

**Comment by junedchhipa** [comment]
I assume you're talking about a line like this
![Screen Shot 2019-05-15 at 11 12 22 PM](https://user-images.githubusercontent.com/17950663/57796956-fc03fc80-7766-11e9-8ebd-4137d50ab0fb.png)

Unfortunately, the line chart doesn't currently support having a different color based on value. Hence, providing dataPointIndex will serve no purpose here.

**Comment by alexp4dev** [comment]
Is there any ability now to draw a line chart with more then one color  ? like in the sample

**Comment by arsalanulhaque** [comment]
Hi, 

Is this feature added? Please respond asap.

Thanks.

**Comment by alexp4dev** [comment]
Nope

**Comment by JeremyBellaiche** [comment]
Hi,

I'm able to get this kind of charts using apexcharts. I guess that's what you're looking for : 

<img width="543" alt="image" src="https://user-images.githubusercontent.com/5360722/194470942-fb1de687-8832-4624-bd0e-4fac928ed24c.png">


First, I've created a function : 

```
const generateColors = (data) => {
        return data.map((d, idx) => {
            let color = d > 0 ? '#22c55f': '#ef4544';

            return {
                offset: idx / data.length * 100,
                color,
                opacity: 1
            }
        })
    }
```


and my options looks like this : 

```
const options = {
        chart: {
            type: 'line',
            height: 350,
            width: "auto",
        }, 
        // ...
        fill: {
            type: 'gradient',
            gradient: {
                shadeIntensity: 1,
                opacityFrom: 0.7,
                opacityTo: 0.9,
                colorStops: generateColors(data)
            }
        } 
}
```

Hope that can help !

**Comment by Onlyukesh** [comment]
can you please explain detailing 
 my API DATA 
{
0: (2) [1675328878000, 17517.1]
1: (2) [1675328879000, 17517.1]
2: (2) [1675328880000, 17517.1]
3: (2) [1675328881000, 17517.1]
4: (2) [1675328882000, 17517.1]
5: (2) [1675328883000, 17517.1]
}
same like that how to color condition passing map function 
please help

**Comment by mohammadimanifard** [comment]
Hope that can help !

https://write.corbpie.com/apex-charts-temperature-line-chart-example/

**Comment by Monstermash28425R1** [comment]
it's possible to add a gradient to the fill background and the stroke at the same time to the area chart?

**Comment by zef-firo** [comment]
> Hi,
> 
> I'm able to get this kind of charts using apexcharts. I guess that's what you're looking for :
> 
> <img alt="image" width="543" src="https://user-images.githubusercontent.com/5360722/194470942-fb1de687-8832-4624-bd0e-4fac928ed24c.png">
> 
> First, I've a variable "data" containing all the values I will display on the chart. With that, I've created a function :
> 
> ```
> const generateColors = (data) => {
>         return data.map((d, idx) => {
>             let color = d > 0 ? '#22c55f': '#ef4544';
> 
>             return {
>                 offset: idx / data.length * 100,
>                 color,
>                 opacity: 1
>             }
>         })
>     }
> ```
> 
> and my options looks like this :
> 
> ```
> const options = {
>         chart: {
>             type: 'line',
>             height: 350,
>             width: "auto",
>         }, 
>         // ...
>         fill: {
>             type: 'gradient',
>             gradient: {
>                 shadeIntensity: 1,
>                 opacityFrom: 0.7,
>                 opacityTo: 0.9,
>                 colorStops: generateColors(data)
>             }
>         } 
> }
> ```
> 
> Hope that can help !

Thanks @JeremyBellaiche for this solution!

I tested it with multiple colors and intervals and I had to modify the gradient function like this:

```
const generateColors = (data) => {
        return data.map((d, idx) => {
            let color = d > 0 ? '#22c55f': '#ef4544';

            return {
                offset: idx / (data.length - 1) * 100,
                color,
                opacity: 1
            }
        })
    }
```

because the last element should be offset 100, otherwise colors are not perfectly aligned with values on the chart.

Hope this helps!

**Comment by andavb** [comment]
Check [this comment](https://github.com/apexcharts/apexcharts.js/issues/3723#issuecomment-2620247204) for possible workaround.

**Comment by alexp4dev** [comment]
Hi , its not relevant any more . Please ignore
