### ISSUE TITLE
Pass dataPointIndex to options.colors callback function

### ISSUE THREAD

**Issue by soconne** [apexcharts/apexcharts.js#586]
Currently it's not possible to assign unique colors to each data point in a bar chart (can only assign unique colors to each series as a whole).  However as an example, suppose you're charting the performance of various CPUs across different workloads of the same benchmark.  For each workload, you wish to display the top 5 performing CPUs.  Each CPU is assigned a unique color.   This is not currently possible without having dataPointIndex passed to the callback function.

var options = {
    colors: [function({value, seriesIndex, w}) { 
        // If dataPointIndex was passed as a parameter, then unique colors per data point could be assigned.
    }
}

**Comment by joeyJsonar** [comment]
Such a shame this is not implemented. This sounds like an easy thing to handle more customizability.
