### ISSUE TITLE
Custom tooltip not working

### ISSUE THREAD

**Issue by ludovicthomas** [apexcharts/apexcharts.js#59]
The custom tooltip function seems to not be working properly, and the demo is not showing any tooltip: https://codepen.io/apexcharts/pen/NBdyvV

After digging into the code, it seems that the issue is that when calling https://github.com/apexcharts/apexcharts.js/blob/022f242b99629bdd4a12cd70e54aaec90cd87dbb/src/modules/tooltip/Labels.js#L27

The method arguments `{ i, j }` are missing.
When added, it's ok.

Thanks.

**Comment by junedchhipa** [comment]
Ouch! The last tooltip refactoring caused this.

Thanks for reporting. Don't hesitate to create a PR for these obvious issues ;)
Lack of tests may scare away some people, but I will add as I get more time.

**Comment by junedchhipa** [comment]
Fixed in https://github.com/apexcharts/apexcharts.js/commit/cf8eb08be9c2ce3beeef8e0402117cb960e936b2

**Comment by ludovicthomas** [comment]
True! Will do next time. Thanks for the quick fix, as always :)
