### ISSUE TITLE
Line chart - Y axis max value out of bound

### ISSUE THREAD

**Issue by arfff** [apexcharts/apexcharts.js#590]
## Codepen

[codepen](https://codepen.io/arfff/pen/dEpOWq)

## Explanation

- What is the behavior you expect?

Y axis autoscaling should show every values

- What is happening instead?

Y axis max value is out ouf bound.

- What error message are you getting?

No error message, but the issues seems related to the data values : autoscaling works fine if you change the last value from 3.1 to 3

**Comment by junedchhipa** [comment]
The bug is fixed in 3.7.1
