### ISSUE TITLE
Non-shared tooltips are not working correctly when xaxis type is set to category

### ISSUE THREAD

**Issue by mmagdyy** [apexcharts/apexcharts.js#592]
## Codepen
[Codepen example](https://codepen.io/anon/pen/rgMpqx)

## Explanation
The tooltip is not working as expected given the following conditions:
- xaxis type = category
- tooltip shared is set to false
- multiple data series

**Comment by junedchhipa** [comment]
If `shared` tooltip is false, you have to turn on `tooltip.intersect: true`.
And also increase the marker's size so the event can fire when the user hovers over the marker.

Updated codepen - https://codepen.io/apexcharts/pen/VOKdWG

**Comment by mmagdyy** [comment]
@junedchhipa But why this is not needed when the type is set to 'datetime'?
Codepen updated: https://codepen.io/anon/pen/rgMpqx
