### ISSUE TITLE
Point annotation type error

### ISSUE THREAD

**Issue by royprigat** [apexcharts/apexcharts.js#594]
## Explanation

- What is the behavior you expect? 
When adding a point annotation with numeric x and y values, no type error should be thrown

- What is happening instead?
Adding a numeric y value throws an error

- What error message are you getting?
TypeError, the y value for point annotations is defined as null in the type definition file

**Comment by junedchhipa** [comment]
Please provide a working codepen demo so the issue can be reproduced easily.

**Comment by royprigat** [comment]
I am sorry but I wasn't able to reproduce a codepen with typings. I can only reference the PointAnnotation definition in the apexcharts.d.ts file. You can see that the y value is defined as null instead of number.

**Comment by junedchhipa** [comment]
@royprigat No worries.
I have fixed the typings as you can see in this [commit](https://github.com/apexcharts/apexcharts.js/commit/90a25656cfc4820d7f22fe5e9a91d16c7bd5ad42).
It will be released soon.
