### ISSUE TITLE
Heatmap color shades for negative numbers

### ISSUE THREAD

**Issue by jesusthatsgreat** [apexcharts/apexcharts.js#597]
## Codepen

https://codepen.io/anon/pen/ZNeEgx

![logic](https://user-images.githubusercontent.com/35536996/57792134-3acd8e80-7736-11e9-8df3-16bdd26d074a.PNG)

## What is the behavior you expect?

With positive numbers, the higher the number, the darker the shade. 5 is darker than 1 for example (which is fine, no problems there).

With negative numbers however, if we're being logically consistent, you'd expect the shade to get lighter the closer to zero the number is. For example -1 should be lighter than -5.

## What is happening instead?

Currently with negative numbers, the shade is darker the closer to zero you get. Another example of what I'd expect here: (where darker reds mean larger losses, darker greens mean larger gains)

![darker](https://user-images.githubusercontent.com/35536996/57792848-e4f9e600-7737-11e9-850e-80a3d69e4291.PNG)

**Comment by junedchhipa** [comment]
Sure.
Added a new property `plotOptions.heatmap.reverseNegativeShade` which when turned on will reverse the shades for negatives but keep the positive shades as it is now.

The change will be released in `apexcharts@3.6.12`

**Comment by JianhengHou** [comment]
@junedchhipa 

reverseNegativeShade does help. However, the color is set at the 0 for negative values, as the value become closer to negative infinite, the color become very dark to a extent that people don't expect. Ideally, the color configured for negative values, after reverseNegativeShade is true, should set for the negative infinite value and become lighter for number close to zero. This should provide same scale of darkness as green that is set. Please fix this, thanks!
