### ISSUE TITLE
All X-Axis annotations are at X=0

### ISSUE THREAD

**Issue by jamesuniversalstore** [apexcharts/apexcharts.js#598]
## Explanation

- What is the behavior you expect?
Multiple X annotations across the timeline 
- What is happening instead?
All X annotations are far left of screen at the equivalent of X=0
- What error message are you getting?
Console is reading nothing. No other errors

Codepen [HERE](https://codepen.io/anon/pen/JqWaLQ)

**Comment by junedchhipa** [comment]
In a datetime xaxis, you should pass a timestamp in the `x` property of annotation.
```javascript
annotations: {
    xaxis: [
      {
        x: new Date("2019-05-11 17:05:57").getTime(),
      }
   ]
}
```

Updated your [codepen](https://codepen.io/apexcharts/pen/YbZRQJ)

**Comment by jamesuniversalstore** [comment]
Thanks. I'm just fonfused 

> In a datetime xaxis, you should pass a timestamp in the `x` property of annotation.
> 
> ```js
> annotations: {
>     xaxis: [
>       {
>         x: new Date("2019-05-11 17:05:57").getTime(),
>       }
>    ]
> }
> ```
> 
> Updated your [codepen](https://codepen.io/apexcharts/pen/YbZRQJ)

Thanks, I'm just confused why this is needed for annotation but not for the actual data series?

**Comment by junedchhipa** [comment]
Ok, I will allow date string in `x` property to make it consistent.
Thanks for pointing it out.

**Comment by junedchhipa** [comment]
It seems a lot of checking to enable date strings in annotations.
For now, I will leave it as it is - i.e., to provide timestamps for x-annotations in a datetime x-axis.
