### ISSUE TITLE
Show only tooltip for one serie

### ISSUE THREAD

**Issue by thijscrombeen** [apexcharts/apexcharts.js#599]
I have a graph with multiple series: 
- Area
- Line
- Line with stroke stepline

Is it possible to only show the tooltip for one of these series, for example the area only?

**Comment by junedchhipa** [comment]
Not possible with the current version.
But, I have added a new property `tooltip.enabledOnSeries` which will accept an array in which you can specify which series index should the tooltip be enabled on.

Will be released in 3.6.12

**Comment by thijscrombeen** [comment]
That's great! Thanks
