### ISSUE TITLE
Broken URL in Radialbar-Charts demo page

### ISSUE THREAD

**Issue by yamash723** [apexcharts/apexcharts.js#6]
Thanks for your great works. Its so simply nice library.

Btw, I found broken urls in the demo page.
Could you check it out please?

**demo page**
https://apexcharts.com/javascript-chart-demos/radialbar-charts/

- Circle Chart – Custom Angle
    - Wrong
        - https://apexcharts.com/javascript-chart-demos/radialbar-charts/circle-chart-custom-angle/
    - Correct
        - https://apexcharts.com/javascript-chart-demos/radialbar-charts/custom-angle-circle/
- Stroked Circular Guage
    - Wrong
        - https://apexcharts.com/javascript-chart-demos/radialbar-charts/stroked-circular-gauge/
    - Correct
        - https://apexcharts.com/javascript-chart-demos/radialbar-charts/stroked-gauge/
- Semi Circular Guage
    - Wrong
        -  https://apexcharts.com/javascript-chart-demos/radialbar-charts/semi-circular-gauge/
    - Correct
        - https://apexcharts.com/javascript-chart-demos/radialbar-charts/semi-circle-gauge/

**Comment by junedchhipa** [comment]
@yamash723 Thanks for reporting. Fixed it.
