### ISSUE TITLE
Apex Charts Isomorphic?

### ISSUE THREAD

**Issue by zocheyado** [apexcharts/apexcharts.js#60]
Been using this package for the past few days and my only real complaint is that that it is not isomorphic. Currently using React wrapper with Next.js, any chance this is on the timeline for the next week, month, year? Awesome package btw.

**Comment by Xdabier** [comment]
Hello I'm using apexcharts , on an angular 9 project.
My issue is when using @nguniversal, to do server side rendering, it throws this error:

`ERROR Error: Uncaught (in promise): ReferenceError: SVG is not defined
ReferenceError: SVG is not defined`

Is there anyway to make it working on the server side by using?

**Comment by ceichinger** [comment]
Any update on this? Server Side Rendering support would be pretty cool 🙌🏼
