### ISSUE TITLE
Filled Annotations not showing correctly with xaxis being type categories with Strings

### ISSUE THREAD

**Issue by rmky** [apexcharts/apexcharts.js#600]
## Codepen

https://codepen.io/anon/pen/eaWOyO

## Explanation

- What is the behavior you expect?
 I expect an annotation field from "Canada" to "Italy"

- What is happening instead?
There is no annotation field at all, just the label at "Canada". If you put any number into x2, like x2: "0", there will be a field from the the y axis till the string put in x, in this case "Canada".

- What error message are you getting?
There's no error message.

**Comment by junedchhipa** [comment]
Thanks for reporting the issue.
It looks like range annotations are only supported for numeric x-axis currently.
I will provide a fix soon.
