### ISSUE TITLE
Multiple x-axis

### ISSUE THREAD

**Issue by kreejzak** [apexcharts/apexcharts.js#601]
Hi,
I'd like to suggest a feature that allows you to have multiple x-axis in horizontal bar chart.
Is there any option to do this right now?

Thanks for your time.

**Comment by junedchhipa** [comment]
Hi @kreejzak 
Unfortunately, multiple x-axes in a bar chart are not supported currently. Also, they are not being considered to be added in the near future.

Thank you for your suggestion.

**Comment by rmky** [comment]
Is there a feature for multiple X-axis in general? I did search the Docu and tried a bit but I am not able to actually get a second or more x-axis. Is it supported and if so, how do I manage to get it working ?

**Comment by junedchhipa** [comment]
@rmky As said in the previous comment, multiple x-axes are not supported currently.

**Comment by rmky** [comment]
Thanks for the fast reply. Wanted to be sure as you explicitly mentioned it for bar charts, so I thought it maybe is for other chart types. Thanks for the answer.

**Comment by aadito123** [comment]
did you add it now?

**Comment by dradevnet** [comment]
how about multiple X-axis ?  only want show total in x top

**Comment by Harish-Shejokar** [comment]
in the area chart of reactApex i want data on X-axis should be diff color for eg jan to june blue color and then june to dec in red color is that possible pls tell how to do that .
