### ISSUE TITLE
Option to offset tooltip without setting it to a fixed position

### ISSUE THREAD

**Issue by mitom** [apexcharts/apexcharts.js#603]
**Is your feature request related to a problem? Please describe.**
When tooltips contain relatively long content, they may block out a significant part of the chart:
![image](https://user-images.githubusercontent.com/3754515/57922143-f6a5cf80-7896-11e9-9008-576a18c6b7f5.png)

**Describe the solution you'd like**
I would like to be able to render the tooltip below the chart, in a floating panel to avoid breaking up the layout

**Describe alternatives you've considered**
Considered using the legend, but this would take up a significant amount of space in the layout. Tried using CSS and a margin but the position is calculated so it's unreliable to set a static value.

**Additional context**
Please excuse my poor editing skills, but this is more or less what I'd like to get to:
![image](https://user-images.githubusercontent.com/3754515/57922595-feb23f00-7897-11e9-8c9e-f7c36ac10f58.png)

**Comment by wujekbogdan** [comment]
I'm having a similar issue. I use a custom tooltip and I'd like to position it always above the cursor. It would be great if the position of the tooltip was customizable via a callback function.

I'm thinking of something like this:

``` js
{
  tooltip: {
    /**
     * @param {Number} mouseX - mouse x position
     * @param {Number} mouseY - mouse y position
     * @param {Number} tooltipX - the default tooltip x position
     * @param {Number} tooltipY - the default tooltip y position
     */
    position(mouseX, mouseY, tooltipX, tooltipY) {
      const calculatedX = () => {
        /* do sth */
      };
      const calculatedY = () => {
        /* do sth */
      };

      return {
        x: calculatedX,
        y: calculatedY,
      };
    },
  },
};
```
