### ISSUE TITLE
Unnecessary space in donut chart with bootstrap-vue

### ISSUE THREAD

**Issue by easuck** [apexcharts/apexcharts.js#607]
There're space at bottom of chart when I use with bootstrap-vue's card
Tried with grid padding option in issue https://github.com/apexcharts/vue-apexcharts/issues/44

![image](https://user-images.githubusercontent.com/14039085/57965658-6b4d3c80-7971-11e9-836a-b5f2b7999c8d.png)

Here are vue code and chart's option.
```
<b-card title="Storage Summary">  
  <apexchart type="donut" width="75%" :options="pieChartOptions" :series="[storageSummary.totalFree, storageSummary.totalUsed]" />
</b-card>
```

```
pieChartOptions: {
        labels: ["Free Space", "Used Space"],
        colors: ["#28a745", "#dc3545"],
        grid: {
          show: true,
          padding: {
            top: 0,
            bottom: 0
          }
        }
      }
```

**Comment by junedchhipa** [comment]
Closing as related to #495 #561 
I will provide a fix for this soon.
