### ISSUE TITLE
Vertical orientation in x-axis annotations doesn't align to top when position: top is provided.

### ISSUE THREAD

**Issue by xxx44yyy** [apexcharts/apexcharts.js#608]
![Снимок экрана 2019-05-19 в 21 29 44](https://user-images.githubusercontent.com/40538167/57986421-71c8da80-7a7d-11e9-9005-1fc2738f1901.png)

**Comment by junedchhipa** [comment]
Please provide a codepen demo.

**Comment by xxx44yyy** [comment]
> Please provide a codepen demo.

https://codepen.io/xxx44yyy/pen/KLvZqz
