### ISSUE TITLE
UPdating ONE chart out of multiple GROUPED charts

### ISSUE THREAD

**Issue by superfeedboy** [apexcharts/apexcharts.js#610]
Hi Juned,

I'm fighting with a "weird" (as for my use of the charts) behavior when trying to update options (and series) only ONE chart out of multiple GROUPED charts.

Capital GROUPED because i need them to be grouped and i already saw that the behaviour is OK when not grouped :/

I coded this codepen quickly and it shows quite well my problem:
https://codepen.io/superfeedboy/pen/vweXbP

Can you please check into this?

Best regards,
Gilles

**Comment by superfeedboy** [comment]
Hi there,

FYI, i found out that updating only the datas (via updateSeries) updates only the one chart i need but i also need to update some options :'(

Regards,
Gilles

**Comment by junedchhipa** [comment]
Thanks for creating another demo/ticket for this issue.
I just fixed the problem and the patch will be released soon.

**Comment by superfeedboy** [comment]
You're the Best mate !

Envoyé depuis mon mobile Huawei


-------- Message original --------
Objet : Re: [apexcharts/apexcharts.js] UPdating ONE chart out of multiple GROUPED charts (#610)
De : Juned Chhipa
À : "apexcharts/apexcharts.js"
Cc : Gilles ,Author


Thanks for creating another demo/ticket for this issue.
I just fixed the problem and the patch will be released soon.
