### ISSUE TITLE
Two bar charts 

### ISSUE THREAD

**Issue by mazoin** [apexcharts/apexcharts.js#611]
Hi,
is there any way, how to render two bar charts behind each other? Similar to the example image (first chart has orange color, other chart is grey). 
![image](https://user-images.githubusercontent.com/5843445/58038862-6df69000-7b31-11e9-8de0-2e3cea8c88cc.png)

**Comment by junedchhipa** [comment]
Sorry, this is not possible currently.
A stacked bar chart is the closest you can use to achieve what you have shown above.
