### ISSUE TITLE
Possible memory leak: Charts are adding mousemove EventListeners to unrelated elements on the page

### ISSUE THREAD

**Issue by haroflow** [apexcharts/apexcharts.js#612]
## Codepen

https://codepen.io/anon/pen/XweoqM

## Explanation

- What is the behavior you expect?
I would think the charts shouldn't be creating mouse events for elements outside it's parent container. If it needs to, it should unbind them on destroy() or make it so it is not duplicating events on updateSeries().
- What is happening instead?
Each call to updateSeries() adds a mousemove eventlistener to a text element outside the chart container. On chrome, inspect the text element and go to Event Listeners -> mousemove, the quantity of events keeps increasing.
![image](https://user-images.githubusercontent.com/4776931/58072840-58a45480-7b77-11e9-84f3-d960a810cf5c.png)
- What error message are you getting?
None.

If I'm misunderstanding the problem, please feel free to close this issue.
Thank you!

**Comment by junedchhipa** [comment]
You're right. Just fixed it.
Thanks for the catch!
