### ISSUE TITLE
Negative tick mark on Y-Axis when there is no corresponding value on X-Axis

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#614]
## Codepen

Modify [this codepen](https://codepen.io/vjakair/pen/NVXrdv) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behavior you expect?
Negative tick mark should not be plotted on y  axis, when there is no corresponding value on X-Axis is available. 
- What is happening instead?
Negative tick mark is getting plotted.
- What error message are you getting?
No error message

FYR:
![image](https://user-images.githubusercontent.com/8254178/58168084-12501200-7cab-11e9-8130-4f947b4d7fd2.png)

**Comment by irshadahmed** [comment]
Hi @junedchhipa. Please let me know if there is a way to handle this.

**Comment by junedchhipa** [comment]
Setting yaxis.min = 0 is the easiest fix for now.

**Comment by junedchhipa** [comment]
The yaxis values are generated based on the range of minimum and maximum.
In your chart, min is around 10 and max is around 3200, hence the bottom range exceeds 0

**Comment by irshadahmed** [comment]
Thanks @junedchhipa . This helps.
