### ISSUE TITLE
plotOptions.bar.bar.barHegith only applies for the background

### ISSUE THREAD

**Issue by tarreislam** [apexcharts/apexcharts.js#615]
https://i.imgur.com/69mJcfC.png

```javascript
       plotOptions: {
          bar: {
            barHeight: '50%', 
            distributed: true,
            horizontal: true,
            dataLabels: {
              position: 'bottom'
            }
          }
        },
```
If you look at the picture, the painted area is where I want to remove the margin/padding. But I can't find the options for it.

**Comment by junedchhipa** [comment]
The barHeight options didn't work out?
https://apexcharts.com/docs/options/plotoptions/bar#barHeight

Try changing the percentage of `barHeight` to 90% and see if it works.

**Comment by junedchhipa** [comment]
Closing as no response.
Feel free to re-open if the barHeight option doesn't work.
