### ISSUE TITLE
css classes aren't applied when generating dataURI

### ISSUE THREAD

**Issue by ThomasKuhlmann** [apexcharts/apexcharts.js#616]
## Codepen

https://codepen.io/anon/pen/mYpQEJ

## Explanation

Right now css class which have been applied to the x axis and y axis aren't being used when exporting a chart to a dataURI even though they work perfectly fine in the chart itself. I am not sure if I misunderstood how this is supposed to work, but it'd be great if the same css could be used when generating the dataURI.

**Comment by junedchhipa** [comment]
The `dataURI()` function grabs the `SVG` element and exports it. 
It cannot detect the stylesheets which are outside the SVG element. Hence, it will add the class to the elements but will be unable to apply the styles as the exported SVG will not have those styles.

Hence, I suggest you provide font-size, colors to the config object itself if you need them in the export.

**Comment by ThomasKuhlmann** [comment]
Thanks for the explanation!
