### ISSUE TITLE
donut total formatter errror

### ISSUE THREAD

**Issue by paolog22** [apexcharts/apexcharts.js#620]
i dont know what to spec with the result but i think this is wrong

![image](https://user-images.githubusercontent.com/12680745/58313715-ccc54d80-7e40-11e9-8266-c062e8fea053.png)

also when chart type is donut or pie and the series is empty or zero it give an error
![image](https://user-images.githubusercontent.com/12680745/58314175-8c1a0400-7e41-11e9-9483-723f7fe0154d.png)
![image](https://user-images.githubusercontent.com/12680745/58314248-b53a9480-7e41-11e9-9687-90fcb60546cf.png)

please fix this.. this is major bug i guess its a show stopper 

thank you

**Comment by junedchhipa** [comment]
Please provide a codepen demo.

**Comment by paolog22** [comment]
@junedchhipa sorry cant provide codepen demo but this all the screenshot are from the code base as you can.  just try empty array as the series of the chart 

thank you

**Comment by haroflow** [comment]
@paolog22 the maintainer asked for a simple example demonstrating the exact problem, doesn't need to be your real world code, like this:

https://codepen.io/anon/pen/KLxEVr

This is the error you are reporting, right?
In this case you could simply put `series: [ 0 ]` instead. Sending no value to a pie/donut chart might be undefined, i don't know.

**Comment by junedchhipa** [comment]
@haroflow Thanks for the demo.
Yeah, looks like a bug. I will take an in-depth look soon.

**Comment by paolog22** [comment]
@haroflow thank you for replicating @junedchhipa i am so sorry for not providing a demo my bad.

**Comment by matz1237** [comment]
I'm Having Same Problem in Vue
If Series is empty, or 0 Donut Chart is not Visible.
