### ISSUE TITLE
Updating options for a grouped chart makes all of the charts get the same options

### ISSUE THREAD

**Issue by x42y** [apexcharts/apexcharts.js#623]
Demo: https://codesandbox.io/s/vue-apexcharts-sync-annotation-problem-kz2ff

Steps to reproduce: Click on the **Set annotation** button

- What is the behavior you expect?
The first chart gets an annotation between the first and the second xaxis point, while the second chart gets an annotation between the sixth and the seventh point.

- What is happening instead?
Both charts get an annotation between the sixth and the seventh point.

This only happens to grouped charts - if I remove `group: "sameGroup"`, the problem goes away.

**Comment by x42y** [comment]
It seems like it doesn't matter if you only update one chart, the effect is still the same. I have updated the demo to simplify (removed for-loop which updated both charts with different options)

**Comment by junedchhipa** [comment]
For the time being, I suggest using the `exec()` method for updating a chart in a grouped charts situation.
https://apexcharts.com/docs/methods/#exec

**Comment by thellimist** [comment]
I'm having this issue with modifying data. 

https://codesandbox.io/s/react-basic-example-8cn4q?fontsize=14&hidenavigation=1&theme=dark

**Comment by junedchhipa** [comment]
@thellimist  A workaround for now is to use the `ApexCharts.exec` method.
In your codesandbox, I tried this and it worked fine.
```javascript
    ApexCharts.exec('series1', 'updateSeries', copySeries1)
    ApexCharts.exec('series2', 'updateSeries', this.series2)
```

**Comment by thellimist** [comment]
https://codesandbox.io/s/react-basic-example-ky41h @junedchhipa 

For the example above your solution works. But, I can't make it work where the Chart render component does not have idea about how many others are being rendered so each chart needs to call `ApexCharts.exec` themselves or the caller (in the example case `App` should call `ApexCharts.exec`. 

Basically I want the sync to work in this kind of a setup. Would appriciate your help.

Thanks

**Comment by simplayy** [comment]
so for now there is no real solution, is there only a workaround with ApexCharts.exec()?
for example if I take the data async with tanstack query there is no way to make it work?

**Comment by mariusberlinghof** [comment]
@junedchhipa 
This issue still exist. Somehow the options get overwritten completely after adding the same group to several Charts. (see example below)
Right now i'm reprogramming the functionality manually, as there is no way for me to make it work. 
An option to programatically trigger a hovered x Value would come in very handy at this point.
before:
![image](https://user-images.githubusercontent.com/36261096/221590575-b068095b-4610-4fee-8b38-5f80db5eba8a.png)

after:
![image](https://user-images.githubusercontent.com/36261096/221590642-277853fa-f9ef-4703-afd8-c66081d564d0.png)

Right now i'm reprogramming the functionality manually, as there is no way for me to make it work. 
An option to programatically trigger a hovered x Value would come in very handy at this point.

**Comment by parallaxe** [comment]
I'm working with version 3.37.3, which still has the issue.
My workaround is to call `updateOptions` to remove the group (`updateOptions({chart: {group: undefined}})`), and then call the `updateOptions` again, which sets all options as wanted and also restores the group. Hacky, but it works fine.

**Comment by RafaelCENG** [comment]
bump

**Comment by RafaelCENG** [comment]
bump
