### ISSUE TITLE
Stacked column charts don't work with multiple y-axis.

### ISSUE THREAD

**Issue by simoami** [apexcharts/apexcharts.js#625]
## Codepen

https://codepen.io/anon/pen/YbvoEv

## Explanation

- What is the behavior you expect?
The stacked charts look small. They should be able to use a proper scale to maximize the use of the vertical space 
- What is happening instead?
Defining two y-axis, one for the line and one for the stacked columns breaks the stacked columns into 2 separate columns.
- What error message are you getting?
No error messages.

**Comment by junedchhipa** [comment]
You're right.
Stacked columns don't work in a multi-yaxis chart as I can see in the codepen.
Thanks for reporting, I will look into it soon.

**Comment by jlil** [comment]
@junedchhipa first, awesome library! the API is extensive, yet simple to use. Very similar to echarts without the big bundle size and dependencies.

I am however also stuck on the issue reported by @simoami above. Do you have any idea on when a fix can be pushed?

**Comment by junedchhipa** [comment]
@jlil Thanks for the compliment.
The bug is under the roadmap as it is a major constraint to not being able to use stacked column charts with multiple y-axis.
You can expect a fix in a week or two.

**Comment by JohnRomanski** [comment]
This issue is closed, but the code pen remains the same, showing the issue. Is there any documentation that shows how to get this working?

**Comment by FireGreeks** [comment]
This is still a problem.... Has anyone found a workaround?

**Comment by yubinjodev** [comment]
Still does not work. This issue should not be closed @junedchhipa
