### ISSUE TITLE
Annotation position seems to be calculated in pixels since version 3.7.0

### ISSUE THREAD

**Issue by gurix** [apexcharts/apexcharts.js#627]
```javascript
annotations: {
    xaxis: [{
      x: 10,
      x2: 30,
      label: {
        text: 'Test'
      }
    }]
  }
```

## Codepen
Version using Apexchartsjs 3.6.12: https://codepen.io/gurix/pen/wbxmYb
Version using Apexchartsjs 3.7.0:   https://codepen.io/gurix/pen/LoBmYm

## Explanation
In 3.6.12 the annotation correctly spans from the x-value 10 to 30. Since version 3.7.0 it seems like x respectively x2 is taking the number as pixels from the left.

I did not found any hints about this change in the documentation so I had to fix my version to 3.6.12.

**Comment by junedchhipa** [comment]
Thanks for reporting the issue.
I missed checking for horizontal bar charts while drawing annotations for category x-axis.

Just fixed it.
