### ISSUE TITLE
Last bar in chart is cropped

### ISSUE THREAD

**Issue by EvanBarbour3** [apexcharts/apexcharts.js#628]
## Codepen

[Demonstration](https://codepen.io/anon/pen/vwaRmd) to show the problem clearly.

## Explanation

I have a graph with bars, and I expect for the bar at the end to not fall past the y-axis and be cropped off. I cannot get the last bar to be inside of the chart and not fall past the end.

I am getting no error messages or warnings. I have seen [this](https://github.com/apexcharts/apexcharts.js/issues/540) issue but I am plotting a `datetime` category, and cannot use `category`, as I can have 3 months of data plotted onto the graph and the labels overlap one another.

![Screenshot 2019-05-23 at 17 25 00](https://user-images.githubusercontent.com/7600557/58269759-20239700-7d80-11e9-8b0a-a0f4c8db1b54.png)
![Screenshot 2019-05-23 at 17 23 25](https://user-images.githubusercontent.com/7600557/58269761-20239700-7d80-11e9-8281-2d7dd1d9cc82.png)

**Comment by junedchhipa** [comment]
Thanks for reporting, fixed it. Patch will be released in 3.7.1
