### ISSUE TITLE
X-axis according to given timezone

### ISSUE THREAD

**Issue by sreekm** [apexcharts/apexcharts.js#631]
I have a requirement to show X-axis in 24 format according to given timezone. How can I achieve this using Apexcharts

**Comment by ericdoerheit** [comment]
Recently, we had the same requirement. I managed it by converting the UTC timestamp to a local timestamp. Using moment-timezone you can do this via:
```
let timezone = "Europe/Berlin"
let utcOffset = moment.tz(utcTimestamp, timezone).utcOffset() * 60;  // offset in seconds
let localTimstamp = utcTimestamp + utcOffset  // use this as the timestamp in apexcharts
```

You need to calculate the `utcOffset` for each timestamp in order to handle DST (Daylight Saving Time).

**Comment by razorsky** [comment]
@sreekm have you solved your problem with the response of @ericdoerheit please ?
