### ISSUE TITLE
Line color can't be changed

### ISSUE THREAD

**Issue by NTsvetkov** [apexcharts/apexcharts.js#634]
## Codepen

https://codepen.io/NO_CARRIER/pen/oRQLMz

## Explanation

- I expect lines to be same color as dots.
- Dots are colored of defined color, lines remaining grey.
- There is no error messages.

**Comment by junedchhipa** [comment]
You should only provide either hex or rgb/rgba format. Color names are not accepted at the moment.
[Docs](https://apexcharts.com/docs/options/colors/)

**Comment by NTsvetkov** [comment]
Thank you! I'm sure I read this couple of times, but...
