### ISSUE TITLE
Chart height on mobile chrome/brave not correct (depending on number of lines in legend)

### ISSUE THREAD

**Issue by guybrush** [apexcharts/apexcharts.js#636]
## Codepen

https://codepen.io/guybrush-the-bold/full/LoXdgN

## Explanation

- What is the behavior you expect?
  The chart should look the same on all devices
- What is happening instead?
  On chrome (and brave) the height of the chart-plot is much less than on other devices - depending on the amount of lines in the legend.
- What error message are you getting?
  None

Here is a screenshot: (on the left its chrome on desktop, on the right its chrome on android)
![Screenshot from 2019-05-31 10-21-23](https://user-images.githubusercontent.com/306324/58692110-363be380-838e-11e9-9043-5d31b36d3655.png)

**Comment by OneWebDev** [comment]
I am facing the same problem. Have you been able to fix this since posting?

**Comment by guybrush** [comment]
Sorry no, I am now using another charting-lib.

**Comment by astronati** [comment]
Any news about this?

**Comment by junedchhipa** [comment]
Yes, the issue is fixed. Please wait for the release of apexcharts@**v3.16.2**

**Comment by jan-nick** [comment]
Using 3.20.0 the issue still persists. Are there any updates or workaround on this?

**Comment by RenierC** [comment]
I'm facing the same problem

**Comment by junedchhipa** [comment]
This is no more an issue as tested on 3.50.0
If anyone still faces the issue, please provide a new codepen.
