### ISSUE TITLE
Ability to keep the tooltip opened

### ISSUE THREAD

**Issue by emilianodelvalle** [apexcharts/apexcharts.js#639]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to being able to focus on the hover tooltip and keep it open. I would like to give the user the ability to change the data on the chart in that tooltip. However, right now, the tooltip will dissapear when the user tries to focus on that.

**Describe alternatives you've considered**
Another option would be to have the tooltip appear on the datapoint selection. Right now, we have the event of selection but no way to draw anything on the chart.

**Comment by junedchhipa** [comment]
```css
 .apexcharts-tooltip {
     opacity: 1 !important;
 }
```
will keep the tooltip always open.
