### ISSUE TITLE
Default zoom when xaxis type is datetime

### ISSUE THREAD

**Issue by alc32** [apexcharts/apexcharts.js#64]
First and last datalabels are not displayed correctly

![Datetime](https://user-images.githubusercontent.com/23075572/44898197-70446000-acfe-11e8-9d59-adcebcd41ca1.PNG)
![No datetime](https://user-images.githubusercontent.com/23075572/44898199-70dcf680-acfe-11e8-84a6-9498e98212e7.PNG)

[CodePen](https://codepen.io/alc32/pen/eLpjrM)

**Comment by junedchhipa** [comment]
Thanks for reporting.
Fixed it
