### ISSUE TITLE
Enable html tags formatter  in y and x axis label

### ISSUE THREAD

**Issue by blackwill123** [apexcharts/apexcharts.js#640]
On using html tags in custom formatter function of x axis or y axis then it prints the html tag eg if i want to use an anchor tag on labels then it prints the whole html tag in string format
instead of [GGNFC6](http://customwebsite.com)

Is there any way to enable html tag inside of formatter function?

**Comment by MaxLeiter** [comment]
Bump? Is this currently possible?

**Comment by joshstrange** [comment]
Also very interested in if this is possible. Trying to style the labels and also add newlines.

**Comment by junedchhipa** [comment]
Inserting HTML into SVG is not simple.
A <foreignObject> element is required to insert custom HTML into SVG which is quite tricky.

Multiline text can be achieved by providing the text in an array.

```javascript
xaxis: {
  type: 'category',
  categories: [
    ['ABC', 'XYZ'],
    'Another label'
  ]
}
```

Docs: https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/
