### ISSUE TITLE
stacked bar chart horizontal option not working and x axis labels not getting rotated 

### ISSUE THREAD

**Issue by tanyashr95** [apexcharts/apexcharts.js#641]
chartOptions:{
   plotOptions: {
            bar: 
           {
               **horizontal: true,**
               dataLabels: 
              {
                enabled: false,
                position: 'top'
              }
            }
      },
       xaxis: {
             labels:{
              **rotate:-45**
            },
            categories: ["a","b","c","d","e"],
            title: {
                text: ' categories',
              },
              
        },

} 

<img width="1099" alt="Screenshot 2019-06-01 at 5 21 57 PM" src="https://user-images.githubusercontent.com/48240786/58748133-c9117680-8491-11e9-9afd-c51f100b5676.png">

i need to submit this...please reply asap :(

**Comment by junedchhipa** [comment]
I tried the following code and it seems to be working fine
```javascript
chartOptions: {
    chart: {
        height: 350,
        type: 'bar',
        stacked: true,
    },
    colors: ['#DE4C5A', '#4AA89C', '#4C486A' ], 
    plotOptions: {
        bar: {
            horizontal: true,
        },
    },
    
    yaxis: {
    labels: {
            rotate:-45
        }
    },
    xaxis: {
        categories: [2008, 2009, 2010, 2011, 2012, 2013, 2014],
    },            
}
```

Make sure you invert the y-axis for a horizontal bar chart (if you intend to invert the category labels)
![qucceduz](https://user-images.githubusercontent.com/17950663/58748588-b77f9d00-8498-11e9-8975-6678bc25ab10.png)

**Comment by gusalvestavo** [comment]
Make sure you are passing the plotOptions to the apexcharts component. I was having this same issue and it turned out I wasn't passing this config prop to the component.
