### ISSUE TITLE
Keep the same zoom level on Realtime chart

### ISSUE THREAD

**Issue by bencultureinfo** [apexcharts/apexcharts.js#643]
Dear all,

I'm continuing to develop with your very nice library but now I have a new issue.
I have a realtime chart with lot of data and I need to zoom on last values and keep the live.
Does it possible to do that ? Or to bypass my problem ?

[![screenshot-cloud le-vert net-2019 05 06-10-08-30](https://user-images.githubusercontent.com/50316605/57213401-009e1780-6fe7-11e9-8bc0-bf20b8aba715.png)(https://cloud.le-vert.net/s/17mseoQnSN7yhTl)](https://cloud.le-vert.net/s/17mseoQnSN7yhTl)

(You have to wait the end of the video to see the chart refresh)

Thanks for your help and thanks for apexcharts !

Benoit.

**Comment by luispestana** [comment]
Hi, i'm kinda on the same problem.

In fact, all the actions made in the chart are lost, for example toggledSeries, that come back active when there is update of the series, or an annotation that has been disabled, comes back to be enabled when we update the series.
How to update the series without these interactions being lost?

**Comment by gmatkowski** [comment]
Yes that would be really nice to know how to deal with this situation

**Comment by paparent** [comment]
Might be related (Sorry, I can't see the video anymore).

I'm using the sample Brush Chart (https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/). I adjust the selection the way I want it. And at an interval, I add new data using `.appendData()` to both charts. Unfortunately the selection reset back to the end of the charts :(

Thanks !

**Comment by sneko** [comment]
Hey, after almost a year I would like to know if you guys succeeded solving this issue?

Thank you,

**Comment by MichaelPluessBluesky** [comment]
I found a hack that solved this issue in my use-case: Hiding the chart by setting the color to transparent before the update and resetting the colors after the update. In my case, this prevents the nauseating zooming action that occurs when updating the series data.

This might look something like this:
`
// hiding the chart. otherwise, ugly jumping animation will occur
await this.chart.updateOptions( { colors: ['rgba(0,0,0,0)'] } );

// the actual update
await this.chart.updateSeries(...);
await this.chart.zoomX(...); // zooming back to the position where we just previously were

// showing the chart again
await this.chart.updateOptions( { colors: ['var(--lumo-primary-color)'] } );
`

**Comment by EnzoKilm** [comment]
Hello there,

Little up for this problem which I didn't solved. Anyone has a solution ?

**Comment by kempsteven** [comment]
Anyone fixed this issue?

**Comment by hrynko** [comment]
After 2+ years, there is no direct solution to the issue. However, in my opinion, @MichaelPluessBluesky's workaround might be the way to go, though not well described.

I tried to restore the zoom after updating the series, but I couldn't find how to get the current zoom level, thus I have to keep it manually. I also had to turn off the animation to avoid blinking on the next update. Anyhow, the following solution works for me.

``` js
var data = [];
var lastZoom = null;

var options = {
  series: [{ data: data }],
  chart: {
    // Disable animation to avoid blinking when updating
    animations: { enabled: false },
    // Add events to handle zoom changes
    events: {
      beforeResetZoom: function () {
        lastZoom = null;
      },
      zoomed: function (_, value) {
        lastZoom = [value.xaxis.min, value.xaxis.max];
      },
    },
  },
};

var chart = new ApexCharts(document.querySelector('#chart'), options);
chart.render();

// Simulate real-time updates
window.setInterval(function () {
  data.push([data.length, Math.random()]);
  chart.updateSeries([{ data: data }]);

  // Restore zoom after updating
  if (lastZoom) {
    chart.zoomX(lastZoom[0], lastZoom[1]);
  }
}, 1000);
```

@luispestana, I think this approach can be easily extended to solve your problem as well.

**Comment by AntonLugtenburg** [comment]
Also having Issues with this

**Comment by juanluidos** [comment]
Any native solution yet from the library?

**Comment by alexisfouquet** [comment]
+1! It should be a great improvement to have this as a native behavior. Actually the current behavior (losing the zoom when we update the data) sounds like a bug to me !

**Comment by juocal** [comment]
Is it possible to reopen this issue, as it is not addressed?

**Comment by edfy32** [comment]
The same problem continues, with real-time data the graph keeps returning to the initial zoom

**Comment by Acervans** [comment]
> After 2+ years, there is no direct solution to the issue. However, in my opinion, @MichaelPluessBluesky's workaround might be the way to go, though not well described.
> 
> I tried to restore the zoom after updating the series, but I couldn't find how to get the current zoom level, thus I have to keep it manually. I also had to turn off the animation to avoid blinking on the next update. Anyhow, the following solution works for me.
> 
> ```js
> var data = [];
> var lastZoom = null;
> 
> var options = {
>   series: [{ data: data }],
>   chart: {
>     // Disable animation to avoid blinking when updating
>     animations: { enabled: false },
>     // Add events to handle zoom changes
>     events: {
>       beforeResetZoom: function () {
>         lastZoom = null;
>       },
>       zoomed: function (_, value) {
>         lastZoom = [value.xaxis.min, value.xaxis.max];
>       },
>     },
>   },
> };
> 
> var chart = new ApexCharts(document.querySelector('#chart'), options);
> chart.render();
> 
> // Simulate real-time updates
> window.setInterval(function () {
>   data.push([data.length, Math.random()]);
>   chart.updateSeries([{ data: data }]);
> 
>   // Restore zoom after updating
>   if (lastZoom) {
>     chart.zoomX(lastZoom[0], lastZoom[1]);
>   }
> }, 1000);
> ```
> 
> @luispestana, I think this approach can be easily extended to solve your problem as well.

I built upon this code and managed to preserve animations:

```js
events: {
  beforeResetZoom: (chart) => {
    zoom = undefined;
    chart.w.globals.lastXAxis.min = undefined;
    chart.w.globals.lastXAxis.max = undefined;
    return true;
  },
  zoomed: (_, value) => {
    zoom = [value.xaxis.min, value.xaxis.max];
  },
  updated: (chart, options) => {
    // Make sure its a series update and not config
    if (zoom &&
      options.config.xaxis.min !== zoom[0] &&
      options.config.xaxis.max !== zoom[1]) {
      chart.updateOptions({ chart: { animations: { dynamicAnimations: { enabled: false } } } });
      chart.zoomX(zoom[0], zoom[1]);
      chart.updateOptions({ chart: { animations: { dynamicAnimations: { enabled: true } } } });
    }
  }
},
```
