### ISSUE TITLE
Does apexcharts support this kind of chart, see image in the link?

### ISSUE THREAD

**Issue by visaru** [apexcharts/apexcharts.js#644]
Does apexcharts support this kind of chart, see image in the link, I'm more interested on the top green label (+$6.31) (need to show the difference in amount between this year and last year in numbers)

[https://imgur.com/a/moLi1Q4](https://imgur.com/a/moLi1Q4)

**Comment by junedchhipa** [comment]
No, ApexCharts directly doesn't support this functionality.
Although, you can use annotations and do the calculations to put such custom label anywhere on the chart.
https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/
[Docs](https://apexcharts.com/docs/options/annotations)
