### ISSUE TITLE
No exact correspondence with series and values on y axis

### ISSUE THREAD

**Issue by darkoromanov** [apexcharts/apexcharts.js#645]
## Codepen

https://codepen.io/darkoromanov/pen/RmvOrG?editors=0010

## Explanation

- What is the behavior you expect?

Double y-axis should have unique labels, exact correspondence with series and values on y axis

- What is happening instead?
In my example you can see double 2s and 6s and there's not exact correspondence with series and values on y axis

- What error message are you getting?

No message errors.

**Comment by junedchhipa** [comment]
You forgot to provide the `seriesName` in yaxis. In a multi-yaxis chart, if you are hiding some y-axes, you should correspond those y-axes to the visible ones.

```javascript
  yaxis: [
    {
      title: { text: "Kilograms" },
      seriesName: 'Weight 1',
      tickAmount: 8
    },
    {
      title: { text: "Kilograms" },  
      seriesName: 'Weight 1', 
      show: false
    },
    {
      title: { text: "Meters" },  
      opposite: true,
      seriesName: 'Height 1', 
    },
    {
      title: { text: "Meters" },  
      show: false,
      seriesName: 'Height 1', 
    }
  ]
```

Here is your revised example - https://codepen.io/apexcharts/pen/wLdBYQ
