### ISSUE TITLE
Treemap Chart Type

### ISSUE THREAD

**Issue by JustinHoldstock** [apexcharts/apexcharts.js#646]
**Is your feature request related to a problem? Please describe.**
The project I am working on requires Treemap Charts in the near future, and is currently working on a plan to deprecate our current charting library.

**Describe the solution you'd like**
Add the Treemap Chart type to Apex Charts.

**Describe alternatives you've considered**
ngxCharts supports tree maps, however, ngxCharts does not come close to having the same set of features that Apex has. 

**Additional context**
Apex Charts feature-set exceeds our requirements for a charting library, that would allow us to move off of ngxCharts.

![Example of Treemap chart](https://user-images.githubusercontent.com/763560/58835916-81672800-8614-11e9-83fd-1c3d69dc3f46.png)

**Comment by jlil** [comment]
bump

**Comment by elbasan** [comment]
any news on this?

**Comment by junedchhipa** [comment]
Alright, I have started working on it.

**Comment by junedchhipa** [comment]
The first version done.
![Screenshot 2020-09-14 at 2 01 22 AM](https://user-images.githubusercontent.com/17950663/93027967-3ff26480-f62e-11ea-9710-281f51031cc0.png)
Most probably, demos and docs will be ready in 7-15 days with a new ApexCharts release.

**Comment by junedchhipa** [comment]
Treemap charts are released with 3.21.0
Here are the demos - https://apexcharts.com/javascript-chart-demos/treemap-charts/

**Comment by fguimara** [comment]
> Treemap charts are released with 3.21.0
> Here are the demos - https://apexcharts.com/javascript-chart-demos/treemap-charts/

Great improvement!! Thx.

How can I make the categories larger? I mean, how to make the label font size base a large proportion from the rectangle?

**Comment by junedchhipa** [comment]
@fguimara Please open a new ticket for that.

**Comment by fguimara** [comment]
Done

**Comment by Aarsh-Tatva** [comment]
@junedchhipa Having great problem in label size.
![image](https://github.com/apexcharts/apexcharts.js/assets/97931904/164f0d61-3e43-4dd2-a536-26a0fc993d47)
Already tried setting fontSize. Does not work. Please help.
![image](https://github.com/apexcharts/apexcharts.js/assets/97931904/1e259a5b-0da5-4ca6-9147-813d31361565)
It automatically changes size to small.

**Comment by Aarsh-Tatva** [comment]
Also tooltip goes out of chart.
![image](https://github.com/apexcharts/apexcharts.js/assets/97931904/8050b600-deae-4d89-ab3b-d178ba4c10d9)
