### ISSUE TITLE
Donut chart cutting off top when single value is provided for the series

### ISSUE THREAD

**Issue by fabriciojs** [apexcharts/apexcharts.js#647]
![image](https://user-images.githubusercontent.com/1116377/58835967-c64b8880-862d-11e9-83e5-00ff1357f6bb.png)

## Codepen

https://codepen.io/anon/pen/qGvbGq
  

## Explanation

- What is the behavior you expect?

> Not cut off the top of the chart. When have more than one element in the series it works properly: https://codepen.io/anon/pen/dErMXV

- What is happening instead?

> Top of the chart is cutting off.
>
> ![image](https://user-images.githubusercontent.com/1116377/58835960-c3509800-862d-11e9-8171-ef66f58ca9d3.png)

- What error message are you getting?

> No error messages.

**Comment by fabriciojs** [comment]
FWIW - I am also seeing a similar issue on the line chart, now cutting off the labels - 

![image](https://user-images.githubusercontent.com/1116377/58836388-15de8400-862f-11e9-889f-ce0ecf35993f.png)


Works for a bunch of cases, still could not narrow down exactly what data situation triggers it.

**Comment by junedchhipa** [comment]
Please provide a codepen demo for the line chart

**Comment by OlaoreFouad** [comment]
> ![image](https://user-images.githubusercontent.com/1116377/58835967-c64b8880-862d-11e9-83e5-00ff1357f6bb.png)
> 
> ## Codepen
> https://codepen.io/anon/pen/qGvbGq
> 
> ## Explanation
> * What is the behavior you expect?
> 
> > Not cut off the top of the chart. When have more than one element in the series it works properly: https://codepen.io/anon/pen/dErMXV
> 
> * What is happening instead?
> 
> > Top of the chart is cutting off.
> > ![image](https://user-images.githubusercontent.com/1116377/58835960-c3509800-862d-11e9-8171-ef66f58ca9d3.png)
> 
> * What error message are you getting?
> 
> > No error messages.

i faced the same issue, it's cutting off for some reason at the top. I used a transform on the .apexcharts-pie-series class to push it downwards. worked for me.
