### ISSUE TITLE
Have a way to display data labels even when their content is 0

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/apexcharts.js#65]
In my application I have a barchart that shows percentages, and it shows the dataLabels for every row, excepts rows that are "0".

I would like a way to always show the labels.

In the example bellow, United Kingdom has a value of 0 and the data label doesn't show:
https://codesandbox.io/s/oq85k0l2wq

**Comment by junedchhipa** [comment]
I saw that and just corrected it.
When the value was 0, it was getting ignored. 

Thanks for reporting

**Comment by Khanh-Ngy** [comment]
> I saw that and just corrected it.
> When the value was 0, it was getting ignored.
> 
> Thanks for reporting

I need to show the columns of value 0 and their labels. But got nothing. How can i do it ?
![image](https://user-images.githubusercontent.com/71876037/94636251-ce3d3a80-02fe-11eb-8d9b-ca318f302663.png)

**Comment by gcpando** [comment]
> I saw that and just corrected it. When the value was 0, it was getting ignored.
> 
> Thanks for reporting

Hello, sadly this solution doesn't work for me because I define a specific color for each bar based on the value. Do you have another solution ?

**Comment by dparvanov** [comment]
> > I saw that and just corrected it. When the value was 0, it was getting ignored.
> > Thanks for reporting
> 
> Hello, sadly this solution doesn't work for me because I define a specific color for each bar based on the value. Do you have another solution ?

You can try to set hideOverflowingLabels to true
https://apexcharts.com/docs/options/plotoptions/bar/
