### ISSUE TITLE
Zooming with sync charts makes yaxis borders appear

### ISSUE THREAD

**Issue by Diegolml** [apexcharts/apexcharts.js#650]
Codesandbox: https://codesandbox.io/s/react-apex-chart-83wbh

I have two synced charts, one of those has the borders hidden for multiple series. The main issue is that when I zoom in any of the charts, the hidden property seems to disappear and the borders are shown.

This is how the chart initially looks:
![image](https://user-images.githubusercontent.com/24472778/58897128-3a813d00-86bd-11e9-8408-ae9b1a5e81f1.png)

If I use the zoom in the bigger chart it ends up like this: 
![image](https://user-images.githubusercontent.com/24472778/58897272-8f24b800-86bd-11e9-9d02-d1f7582ab927.png)

If I use the zoom in the smaller chart it ends up like this: 
![image](https://user-images.githubusercontent.com/24472778/58897332-a9f72c80-86bd-11e9-8640-32261cebcd81.png)

It also breaks using the pan tool.

Funny thing is that this issue wasn't happening in the 3.6.8 version.

Is there any workaround for this?

**Comment by junedchhipa** [comment]
Thanks for reporting.
I will soon look into it.

**Comment by Diegolml** [comment]
I've noticed that in version 3.6.8 the same issue happens only when using the pan tool.
