### ISSUE TITLE
Duplicate <style> in rendered html

### ISSUE THREAD

**Issue by tammai** [apexcharts/apexcharts.js#652]
I don't know why I have 2 style tags in head. When built, they didn't extracted to vendor-*.css too. Does anyway to load CSS separately or exclude it?

**Comment by tammai** [comment]
Thanks! I just want to modify CSS to match our style. But currently it isn't optimal because I must add !important to each line of my CSS file (my CSS file render before chart's CSS).

**Comment by junedchhipa** [comment]
Maybe try a higher specificity like using an ID selector will help you to not write !important for each line.
```CSS
#your-app .apexcharts-tooltip {
  // styles
}
```
