### ISSUE TITLE
RadialBar chart legend click

### ISSUE THREAD

**Issue by sergioalejanpro** [apexcharts/apexcharts.js#653]
**Is your feature request related to a problem? Please describe.**
I can catch the click on the legend marker (the small circle before each series legend):
            markers: {
                size: 0,
                onClick: function(chart, seriesIndex, opts) {
                    console.log("series- " +seriesIndex + "'s marker was clicked")
                }
            },

**Describe the solution you'd like**
Clicking on the legend text will turn off the series and return the corresponding series index... It's easier to click on legend text than on the marker...

![legends](https://user-images.githubusercontent.com/43328025/58924518-bd2fe980-8709-11e9-80fa-eb41a3dc90a6.JPG)

**Comment by junedchhipa** [comment]
Legend click also returns seriesIndex in the function parameter.
May I see a codepen of what have you tried?

**Comment by sergioalejanpro** [comment]
Thanks for your response...

I think the real question is: Where do I need to put the code for catching the click event on the legend text ?  Markers onClick works fine, but the legends onClick it's not fired, it just toggles the series visibility on the chart...

This is the code I'm using right now:

`        legend: {
            show: true,
            floating: true,
            fontSize: '18px',
            position: 'left',
            offsetX: 0,
            offsetY: 0,
            labels: {
                useSeriesColors: true,
            },
            markers: {
                size: 0,
                onClick: function(chart, seriesIndex, opts) {
                    console.log("series- " +seriesIndex + "'s marker was clicked")
                },
            },
            formatter: function(seriesName, opts) {
                return seriesName + ":  " + opts.w.globals.series[opts.seriesIndex] + '%'
            },
            itemMargin: {
                horizontal: 1,
            },
            onClick: function(chart, seriesIndex, opts) {
                console.log("series- " +seriesIndex + "'s legend was clicked")
            },
        },
`
But the legend click event is not being fired...

I'll try to put the full example on codepen

**Comment by junedchhipa** [comment]
You should put the function legendClick event as follows

```javascript
chart: {
  events: {
    legendClick: function(chartContext, seriesIndex, config) {
     // your code
    }
  }
}
```

Docs - https://apexcharts.com/docs/options/chart/events#legendClick

**Comment by sergioalejanpro** [comment]
This worked as expected...

Thanks and have a great day !

**Comment by marchitecht** [comment]
Hello! that really works. Could you please kindly advise me on how to show datalabels inside radialbar while hovering or clicking on legend?
