### ISSUE TITLE
Tooltip is not shown on some points in an irregular time series

### ISSUE THREAD

**Issue by xumix** [apexcharts/apexcharts.js#654]
## Codepen
https://codesandbox.io/s/obsg1

## Explanation
- What is the behavior you expect?

Expect a tooltip with 2 values shown for the rightmost points.

- What is happening instead?

Only one value is shown, unable to get a tooltip for the second point

- What error message are you getting?
No errors

![image](https://user-images.githubusercontent.com/250118/58949607-84d5ed00-8795-11e9-8d0e-56b9e9fe13d5.png)

**Comment by junedchhipa** [comment]
Can you provide a codepen demo, please?

**Comment by junedchhipa** [comment]
Ok, I can see the issue. The hover function cannot get hold of the value of close data-points in an irregular time-series. Thanks for reporting.

**Comment by xumix** [comment]
> 
> 
> Ok, I can see the issue. The hover function cannot get hold of the value of close data-points in an irregular time-series. Thanks for reporting.
Ok, great!
Why is it irregular?

**Comment by junedchhipa** [comment]
I  just meant, the issue is in `irregular time-series` means when each series has different start and end dates. Similar to this - https://apexcharts.com/javascript-chart-demos/area-charts/

**Comment by ludovicturmel** [comment]
Hi @junedchhipa, do you have any update on this issue or work around ?

**Comment by maxkochetov** [comment]
@junedchhipa is there a common solution that apexcharts suggest to use in this case?

like finding the nearest data point value of each time-series and displaying it in the tooltip?

or should it be made like by subscribing to a `mouseMove` event and having a custom tooltip?
