### ISSUE TITLE
updateSeries resets chart to also include values of toggled series

### ISSUE THREAD

**Issue by paaaz** [apexcharts/apexcharts.js#655]
## Codepen

[Codepen](https://codepen.io/anon/pen/eaoVgO)

## Explanation

- What is the behavior you expect?
The "min" and "max" values of the yaxis should stay the same if "updateSeries()" is called and there is a deselected (toggled) series.

- What is happening instead?
The scaling of the yaxis is set to the max.-Value of the deselected series, and the deselected series is also somehow included in the chart (as space but no visible column)

**Comment by paaaz** [comment]
I found a work-around for this:
set the "data" for the deselected series to an empty array [] when updateSeries()

**Comment by junedchhipa** [comment]
This is a specific use case where some users may want to update series even when it is hidden, so next time when the series is toggled using a legend, the new series values are shown.
Hence, the solution which you found for your case is the correct approach to deal with it.

**Comment by paaaz** [comment]
> 
> 
> This is a specific use case where some users may want to update series even when it is hidden, so next time when the series is toggled using a legend, the new series values are shown.
> Hence, the solution which you found for your case is the correct approach to deal with it.

Yes this exactly the use case I want, but as you can see in de CodePen example the toggled series gets inserted as "blank column" between the activated series. And also the yaxis changes to the max. of the second series, but the second series is not activated!

**Comment by junedchhipa** [comment]
One option is to toggle the invisible series by `toggleSeries(seriesName)` method before calling the `updateSeries()` method.
https://apexcharts.com/docs/methods/#toggleSeries

Q: How do you know which series is collapsed by legend click?
A: You can check the global variables `chart.w.globals.collapsedSeriesIndices` which contains indexes of all collapsed series. Then, you can do `chart.w.config.series[index].name` to get series-name which you will need to pass in toggleSeries(seriesName).

**Comment by junedchhipa** [comment]
I have added a new method `resetSeries()` which will be called before `updateSeries()`
The change will be released with `3.8.0`
