### ISSUE TITLE
Column chart datetime axis not displaying correct date

### ISSUE THREAD

**Issue by azivkovi** [apexcharts/apexcharts.js#657]
## Codepen

https://codepen.io/azivkovi/pen/rgbEMj

## Explanation

- What is the behavior you expect?

I am using column chart and want the x axis to show dates in 'yyyy' format (raw data is 'yyyy-mm-dd').

- What is happening instead?

What happens is that years are offset by one in the future. Data should start with 2017 (datapoint is 2017-12-31) but starts with 2018 (long data format shows the first datapoint as 2018-07-01, which is unexpected).

- What error message are you getting?

No errors.

Thank you for your time.
Ante

**Comment by azivkovi** [comment]
Hello Juned,

do you know what might be causing this behaviour or if there is a way to work around this?

**Comment by azivkovi** [comment]
I haven't been able to figure out how to fix this issue, but since I didn't require the 'yyyy-mm-dd' date format which was displaying incorrectly, I switched my input data to 'yyyy' instead and the years are displaying as expected. The bug remains when the long date format is used.

Anyway, this is the new codepen: https://codepen.io/azivkovi/pen/jgOVvX

I guess the issue should remain open because someone might need to use the long date format.

**Comment by junedchhipa** [comment]
Hi @azivkovi 
Sorry for the delay in this thread.

As I see in the codepen, the first data-point is the last day of the year. Hence, the next tick which is drawn is the new year. In such cases, one can use `xaxis.min` and `xaxis.max` along with custom formatter function. 

Also, bar charts needs some padding on the left and right. Therefore, the `xaxis.min/max` is adjusted to prevent cropping of data-labels.

Hope this clears things up!
