### ISSUE TITLE
Add categories to Tooltip based on y-axis

### ISSUE THREAD

**Issue by harshanaravindakshan** [apexcharts/apexcharts.js#658]
I currently have 6 series on my line graph. 3 of the series correspond to one y-axis and the other 3 correspond to another y-axis. 

I would like the option for the tooltip to categorize the series instead of just showing all 6 series names and its values. An example of what I mean would be:

![Capture6](https://user-images.githubusercontent.com/49285402/58990657-42afaa00-879b-11e9-99d1-e05cb229c0fd.PNG)
(with better styling than that haha)

Huge thanks in advance! I appreciate all the work you've been doing for Apexcharts :)

**Comment by junedchhipa** [comment]
Yeah, that makes sense.
I will try to order it accordingly.

**Comment by harshanaravindakshan** [comment]
Thank you!
