### ISSUE TITLE
In a stacked 100% bar chart , tooltip displays values instead of percentage.

### ISSUE THREAD

**Issue by tanyashr95** [apexcharts/apexcharts.js#659]
## Codepen
here is the codepen
[(https://codepen.io/tanya-shrivastava/pen/Jqqpbd)]

## Explanation

- What is the behavior I expect?
   i expect the chart to show the percentage values on the bar. for example if the the series is 
  -   series: [{
                name: 'Marine Sprite',
                data: [44, 55, 41, 37, 22, 43, 21]
            },{
                name: 'Striking Calf',
                data: [53, 32, 33, 52, 13, 43, 32]
            },{
                name: 'Tank Picture',
                data: [12, 17, 11, 9, 15, 11, 20]
            },{
                name: 'Bucket Slope',
                data: [9, 7, 5, 8, 6, 9, 4]
            },{
                name: 'Reborn Kid',
                data: [25, 12, 19, 32, 25, 24, 10]
            }] 

    then the value for the first category must be calculated as (44/(44+53+12+9+25) = 31%)
- What is happening instead?
  - but the value doesn't change it remains 44.

**Comment by junedchhipa** [comment]
The percentages are displayed in data-labels.
If you want percentages in the tooltip as well, you can change the formatter function of the tooltip.

```javascript
tooltip: {
  y: {
    formatter: function(value, opts) {
      let percent = opts.w.globals.seriesPercent[opts.seriesIndex][opts.dataPointIndex];
      return percent.toFixed(0) + '%'
    }
  }
}
```

**Comment by iftu06** [comment]
Hi, I want the opposite,mine was is showing percentage value which is expected but I want to show number in the bar but keep the bar as percentage wise,that means bar will bar stretched as percentage wise but label will be number

**Comment by pavanmullapudi1** [comment]
> ## Codepen
> here is the codepen [(https://codepen.io/tanya-shrivastava/pen/Jqqpbd)]
> 
> ## Explanation
> * What is the behavior I expect?
>   i expect the chart to show the percentage values on the bar. for example if the the series is
>   
>   * series: [{
>     name: 'Marine Sprite',
>     data: [44, 55, 41, 37, 22, 43, 21]
>     },{
>     name: 'Striking Calf',
>     data: [53, 32, 33, 52, 13, 43, 32]
>     },{
>     name: 'Tank Picture',
>     data: [12, 17, 11, 9, 15, 11, 20]
>     },{
>     name: 'Bucket Slope',
>     data: [9, 7, 5, 8, 6, 9, 4]
>     },{
>     name: 'Reborn Kid',
>     data: [25, 12, 19, 32, 25, 24, 10]
>     }]
>   
>   then the value for the first category must be calculated as (44/(44+53+12+9+25) = 31%)
> * What is happening instead?
>   
>   * but the value doesn't change it remains 44.

You can just simply put this, i've been struggling for 30 mins, sed lyf.I guess this is helpful
  dataLabels: {
        enabled: true,
        formatter: function(value: string, { seriesIndex, dataPointIndex, w }: any) {
          return w.config.series[seriesIndex]
        }
      }
