### ISSUE TITLE
Radial Bar chart giving error in IE 11 

### ISSUE THREAD

**Issue by soapking** [apexcharts/apexcharts.js#660]
Here is the location details of the bug :
file name : apexchart.js
Line No : 8793
bug code sample :

var slices = document.querySelectorAll(".apexcharts-pie-area");
var sliceOut = false;

Error in IE : v 11
![error](https://user-images.githubusercontent.com/15814084/59055464-80075b00-88b3-11e9-86f2-d3e68aea01fa.png)

**Comment by soapking** [comment]
Do this change then it will throw away the error in IE 11

file name D:\Apex chart\apexcharts.js\src\charts\Pie.js

if (slices.length !== 0) {
        slices.forEach((s) => {
          if (s.getAttribute('data:pieClicked') === 'true') {
            sliceOut = true
            this.printDataLabelsInner(s, dataLabelsConfig)
          }
        })
      }

**Comment by junedchhipa** [comment]
Thank you, fixed it.

**Comment by soapking** [comment]
Thanks apex team :)

**Comment by ZiFFeL1992** [comment]
I'm still seeing this issue on `3.8.0`

![image](https://user-images.githubusercontent.com/5492960/60425537-05e89e80-9bf3-11e9-90e8-ee0eee18f810.png)

Not only Internet Explorer BTW:
![image](https://user-images.githubusercontent.com/5492960/60425621-34ff1000-9bf3-11e9-9e05-394502c0caba.png)

Let me know if I can help or should open a new issue @junedchhipa :)

**Comment by junedchhipa** [comment]
@ZiFFeL1992 Can you please create a new issue with a working codepen demo?
