### ISSUE TITLE
Line Chart numbers being cut off

### ISSUE THREAD

**Issue by prydonian** [apexcharts/apexcharts.js#661]
[codepen example](https://codepen.io/apexcharts/pen/bxzgZJ)

So using the line chart with data labels and markers, the readings are being cut off at the top, bottom and edges of the chart. Is there any way to prevent this?

**Comment by michaeltoohig** [comment]
Same problem currently. Perhaps some way to switch the data label position to below the line when not enough space at the top?

**Comment by leopold-kamp** [comment]
Same Problem here. Points get cut off on the right and left:
![left](https://user-images.githubusercontent.com/45014393/72341393-68564780-36ca-11ea-8873-d91d7027490d.png)
![right](https://user-images.githubusercontent.com/45014393/72341394-68564780-36ca-11ea-9fdb-0118a2ff7975.png)
Marker config:
`size: 8,
          colors: ['#54D8DF', '#fff'],
          fill: '#54D8DF',
          strokeColors: ['#30BBC6', '#FF7575'],
          strokeWidth: 5,
          fillOpacity: 1,
          shape: 'circle',
          radius: 2,
          offsetX: 0,
          offsetY: 0,
          onClick: undefined,
          onDblClick: undefined,
          hover: {
            size: undefined,
            sizeOffset: 3
          }`
I also set grid padding:
` grid: {
          padding: {
            left: 24,
            right: 0
          },
          show: true,`

Is there a workaround or does this get solved?

**Comment by mlafortune1223** [comment]
I'm also having this problem
![Screen Shot 2021-06-23 at 12 21 54 PM](https://user-images.githubusercontent.com/70543759/123156040-b02fe100-d41d-11eb-85cb-d2067c5efd20.png)

**Comment by sidharthramesh** [comment]
Same problem

**Comment by ruiaraujo012** [comment]
Any update? I have the same problem

**Comment by Viridiris** [comment]
Same problem here. But I just solved it. Don't use strings for your number data. It looks like by default parseInt() was being used and it was getting held up on my the comma in my number format. 

I'm going to try the formatter on this page to change the number format https://apexcharts.com/docs/datetime/. There's probably a more relevant page but just relaying the information I have right now.

**Comment by Rafhael369** [comment]
Any update? I have the same problem
