### ISSUE TITLE
How do I remove the padding entirely for a stacked bar chart?

### ISSUE THREAD

**Issue by jlil** [apexcharts/apexcharts.js#664]
## Codepen

https://codesandbox.io/s/react-apex-charts-mqv6c

![image](https://user-images.githubusercontent.com/2744873/59133842-408a4e80-8947-11e9-9aa8-65b6ca21cfa9.png)

## Explanation

- What is the behavior you expect?
I tried setting `grid.padding` to `0` for left/top/right/bottom but it didn't help. There's a div wrapping the chart with a lot of padding.

- What is happening instead?
I expect to have an option to remove all padding for a chart. I am looking to embed this in a table with a fixed height and a 100% width.

- What error message are you getting?
n/a

**Comment by junedchhipa** [comment]
To remove all xaxis, yaxis spacings, turn on the sparkline flag.

```javascript
chart: {
  type: "bar",
  sparkline: {
    enabled: true
  }
},
plotOptions: {
  bar: {
    barHeight: '100%',
  }
}
```

**Comment by jlil** [comment]
@junedchhipa thanks!

**Comment by immint023** [comment]
@juedchippa it works for me :D  thanks
