### ISSUE TITLE
How do you tune data labels show/hide settings?

### ISSUE THREAD

**Issue by jlil** [apexcharts/apexcharts.js#665]
![image](https://user-images.githubusercontent.com/2744873/59149516-d2479980-89e3-11e9-936b-2d473163a904.png)

## Explanation
- What is the behavior you expect?
I expect the labels to show whenever there's enough space for them
- What is happening instead?
The label is only showing for the first series and hidden for the rest
- What error message are you getting?
n/a

**Comment by junedchhipa** [comment]
Can I see the whole code? 
Please provide a codepen to quickly reproduce.

**Comment by jlil** [comment]
I am struggling a bit to get this reproduced in a sandbox environment:

https://codesandbox.io/s/react-apex-charts-mqv6c
(better seen full screen)

I am using the same react/material-ui/apex versions locally too but not seeing the labels:
![image](https://user-images.githubusercontent.com/2744873/59215110-63ef0c80-8b86-11e9-83d1-934edb98bbed.png)
Anything in the config that could explain this? Changing the height to `100` fixes the problems but the rows become massive in the table.

**Comment by jlil** [comment]
@junedchhipa here's a super simple example: https://codepen.io/anon/pen/YopNXG
When you turn off the sparkline, the labels show. Can you please help look into this? This is blocking a big project on my side that needs to be deployed asap. Thanks!

**Comment by junedchhipa** [comment]
@jlil Thanks for providing extra details. I will provide a fix very soon as I know that I turned off data-labels for sparkline (which shouldn't be turned off)

Thank you for your patience.

**Comment by jlil** [comment]
@junedchhipa thanks 🙏

**Comment by jlil** [comment]
@junedchhipa is there a page i can look at for the bug schedules?

**Comment by junedchhipa** [comment]
@jlil Unfortunately, not yet.
But, you can click on the bug label which I added above and expect the fix in descending order (The previous bugs gets fixed first)

**Comment by junedchhipa** [comment]
@jlil  I had to revert this change as some users complain of having data-labels showing up in their spark-lines. It makes sense to turn on data-labels manually for sparkline if you need to show.

From the next version, you will have to manually do

```javascript
dataLabels: {
   enabled: false
}
```
