### ISSUE TITLE
Unexpected formatter in tooltip header (category name)

### ISSUE THREAD

**Issue by paulshatalov** [apexcharts/apexcharts.js#666]
First of all - thank you guys for that incredible tool! Very configurable and easy to use. Really great!

And I want to help a bit by posting possible bug.

I use x axis formatter to add percentage and it seems it affects tooltips categories name.

Here is codepen: https://codepen.io/shatalovpaul/pen/EzqrOz

Actual for 3.7 and 3.6.12 at least

![image](https://user-images.githubusercontent.com/5530873/59157113-c45e4b00-8aad-11e9-8078-fcc435339eee.png)

**Comment by junedchhipa** [comment]
@paulshatalov Thanks for the compliment :)
Yeah, the formatter seems to be applied for both key and value of a tooltip. I will take a look soon, thanks for reporting.
