### ISSUE TITLE
Rename cryptic global w object

### ISSUE THREAD

**Issue by lacostenycoder** [apexcharts/apexcharts.js#668]
[Documentation](https://apexcharts.com/javascript-chart-demos/column-charts/dynamic-loaded-chart/) shows code like:

```
      dataLabels: {
          enabled: true,
          textAnchor: 'start',
          style: {
              colors: ['#fff']
          },
          formatter: function(val, opt) {
              return opt.w.globals.labels[opt.dataPointIndex]
          },
          offsetX: 0,
          dropShadow: {
            enabled: true
          }
      },
```

The` .w` naming is cryptic and has no obvious meaning.  There must be a better way.

**Comment by junedchhipa** [comment]
I agree that the name chosen for the global variable is somewhat cryptic but this change will require a change at each place in the library. It is used in every function and renaming at this point is asking for more trouble. It was more for internal use, but I had to expose it to formatters and other public functions.

Thanks for the suggestion.
