### ISSUE TITLE
Stacked bar charts display NaN when value is 0 and stackType is 100%

### ISSUE THREAD

**Issue by drummad** [apexcharts/apexcharts.js#669]
When using the following chart options a large "NaN" is displayed in place of the bar when the data in the series array is 0. The "NaN" disappears when the stackType option is removed so potentially a divide by 0 error.

`{
     height: 450,
     type: 'bar',
     stacked: true,
     stackType: '100%'
}"`

**Comment by drummad** [comment]
Sure thing, with a bit more investigation it seems to be caused by having the dropShadow property enabled on the dataLabels.

https://codepen.io/Drummad/pen/orNMej

**Comment by junedchhipa** [comment]
Thanks for the codepen. Will fix soon.
