### ISSUE TITLE
[Question] Is there a way to render the chart with a given series already selected?

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/apexcharts.js#67]
Be it one or multiple selected series?

**Comment by junedchhipa** [comment]
Which chart type are you referring to?
Pie Chart?
Because in axis charts, the series is never selected. 
It hides/shows based on legend clicks. Or a particular series highlights if the user hovers over a legend.

**Comment by JCQuintas** [comment]
Bar chart in my case.

My designers want to display a few age percentages on a chart, but have some already selected based on filter criteria (Example below).

![screen shot 2018-08-31 at 15 33 05](https://user-images.githubusercontent.com/9891233/44929998-52ddb900-ad33-11e8-8dee-2570641b6cac.png)

**Comment by junedchhipa** [comment]
Currently, you cannot select a dataPoint by default for any chart type, but we will see in future as an enhancement :)

Right now, if you just want to highlight certain dataPoint in the bar chart, then you can take advantage of the color range properties in the bar chart options.

```javascript
  plotOptions: {
    bar: {
      horizontal: true,
      colors: {
        ranges: [
          {
            from: 0,
            to: 15,
            color: "#E4E8EF"
          },
          {
            from: 15,
            to: 30,
            color: "#005263"
          }
        ]
      }
    }
  }
```

I created an example on [codepen](https://codepen.io/apexcharts/pen/LJxaRE) which resulted in something like this

![screen shot 2018-09-01 at 12 55 09 am](https://user-images.githubusercontent.com/17950663/44932215-1c7b5a80-ad82-11e8-8323-130f70bee44e.png)

**Comment by JCQuintas** [comment]
Nice! I'll take a look into that property.

Thanks :)

**Comment by rasca** [comment]
Hi @junedchhipa I'm interested in this as well. In my case, I'm updating the data and the currently selected series is unselected. And If I select it again via toggleDataSeries it waits till the end of the update animation to get selected again and it just looks weird
