### ISSUE TITLE
Apexcharts doesn't handle tooltips longer than the chart well

### ISSUE THREAD

**Issue by lukas-mertens** [apexcharts/apexcharts.js#671]
Apexcharts doesn't handle tooltips with text longer than the chart itself very well.
# Codepen
[Here is the Codepen demonstrating the issue](https://codepen.io/lukas-mertens/pen/WqbgKW)

# Expected behavior
I would suggest, that the tooltip should start a new line as soon as it detects, that it is wider than the chart itself. An alternative would be, that it at least gets forced to stay on the screen.

# Current behavior
Currently labels shorter than the chart itself are being moved around on the chart to always stay on the screen. When the text is longer than the chart, they are being rendered on the left side of the cursor. This causes the tooltip to escape from the screen resulting in it not being readable anymore.

# Why is this relevant?
When displaying results from a poll, the answer-options are sometimes quite long. As the text is already shorted below the chart, currently there is no way for users to see the full text.

**Comment by junedchhipa** [comment]
You can tweak the tooltip with CSS if it doesn't fit the chart area

```css
.apexcharts-tooltip {
  white-space: pre-wrap;
  max-width: 200px;
}
```

https://codepen.io/apexcharts/pen/YoPRQP

**Comment by lukas-mertens** [comment]
Thanks a lot, that works as well!
