### ISSUE TITLE
Horizontal bar chart: datalabel styling when positive and negative values and bar is not as wide as text

### ISSUE THREAD

**Issue by thijscrombeen** [apexcharts/apexcharts.js#675]
**Is your feature request related to a problem? Please describe.**
Datalabel styling configuration for a horizontal bar chart is not sufficient.
When the bar is not wide enough the text is hardly readable depending on back/front color.

Please see following code-pen
https://codepen.io/anon/pen/jjbdzN 

**Describe the solution you'd like**
I would like to be able to set the datalabel to the right of the bar (if positive) or to the left of the bar (if negative)

**Describe alternatives you've considered**
I've tried playing with the offsets but this does not work as it depends on the positive or negative value.

**Additional context**
As is:
![as-is](https://user-images.githubusercontent.com/16554258/59499276-593ebb00-8e97-11e9-88b8-f68c0cd68843.PNG)
To be:
![to-be](https://user-images.githubusercontent.com/16554258/59499280-5ba11500-8e97-11e9-8d00-680b326d2249.PNG)

**Comment by thijscrombeen** [comment]
To solve this I think if the value is negative then I think you need to invert the textAnchor property on the datalabel. Combining this with offsetX on the datalabel and position: 'top' on the plotOptions/bar/dataLabels will solve it.

What do you think?

**Comment by junedchhipa** [comment]
You're right. Changing the `textAnchor` for negative values would fix it, I guess.

**Comment by thijscrombeen** [comment]
Is there a way to do this without a code change from your side?
If not, then are you willing to make a change like this ? 

Thanks for your quick reply

**Comment by junedchhipa** [comment]
I will fix it from my side.
For the time being, you can use the code in this updated codepen - https://codepen.io/apexcharts/pen/orjRwe

**Comment by thijscrombeen** [comment]
Hey, I don't want to be rude but I'm wondering if i'm seeing the correct codepen as the text is just centered. I was expecting a workaround but maybe this is as you intented.

Do you have any idea when you will have the time to fix this? 
Thanks in advance

**Comment by junedchhipa** [comment]
Yes, the intention in that codepen was to center the text so it stays the same in all bars.

As this issue is marked with `bug` label, it has the highest priority with all issues labeled as `bug`. You can expect a fix in around 2 weeks.

**Comment by thijscrombeen** [comment]
Would you accept a pull request for this bug?

I've made a change on my fork to the Bar.js and this seems to fix it. I might see it too simple though :)

https://github.com/thijscrombeen/apexcharts.js/commit/cbf337ac964b855cc12602738c1652d77d96e4bc

If it's ok, then let me know and I can create a PR.

**Comment by junedchhipa** [comment]
Of course, a pull request is welcome.
Please check your code in column chart as well as horizontal bar chart both. 
There is a boolean called `w.globals.isBarHorizontal` which helps you determine if it is a column or bar chart.

I also recommend testing in stacked charts.

**Comment by thijscrombeen** [comment]
I've created a PR. Please have a look.
Note: I've also fixed an issue where you have stacked:true and hideOverflowingLabels: true it always hides negative value datalabels (see https://codepen.io/anon/pen/jjbdzN)
