### ISSUE TITLE
Ability to download dataset as csv

### ISSUE THREAD

**Issue by Bearzooka** [apexcharts/apexcharts.js#676]
I am working to add functionality to download the dataset as a CSV; however, it won't be really integrated with the existing download buttons, which I think will be a bit confusing.

So, I think it would be cool to have this directly from Apex.

**Comment by junedchhipa** [comment]
Can you provide the code for generating the CSV? I will see if the code is small enough to be integrated directly into ApexCharts.

**Comment by Bearzooka** [comment]
Unfortunately, the code I'm using isn't generic… Since I was already doing the export, I used the effort to combine three DataSets and also did some formatting, so my CSV is ready for the user.

**Comment by Simonefardella** [comment]
@Bearzooka , can you share the generic implementation of your CSV export? it can be useful.

Thanks.

**Comment by junedchhipa** [comment]
Implemented CSV export.
Will be available in the next minor release.

**Comment by ustincameron** [comment]
Updated to react-apex 1.3.6 and still not seeing the export csv option.

**Comment by junedchhipa** [comment]
@ustincameron  You should update the core apexcharts lib to the latest version (3.15.3 as of now) to get the CSV export option

```
npm i apexcharts@3.15.3 --save
```

**Comment by ustincameron** [comment]
> @ustincameron You should update the core apexcharts lib to the latest version (3.15.3 as of now) to get the CSV export option
> 
> ```
> npm i apexcharts@3.15.3 --save
> ```

Ah thanks, I had to restart my localhost for it to show up. Though the download menu is still a white bg with white text making it unusable even when I'm using theme:dark. Is this a separate issue or only on my end?

**Comment by junedchhipa** [comment]
![Screen Shot 2020-01-30 at 11 10 53 PM](https://user-images.githubusercontent.com/17950663/73475559-9d46e780-43b6-11ea-90ef-bc98d39a5a96.png)

It shows me this view in a dark theme.
Can you create a codepen so I can take a closer look?

**Comment by mdsr82** [comment]
Is there any example to export to CSV with Arabic Contents? Currently when I export the chart to CSV the arabic text are not supported.

![ArabicTestExportCSV](https://user-images.githubusercontent.com/54616121/83738357-e22ca480-a65c-11ea-8d2f-e07dbc7326d8.PNG)

**Comment by nr101011k9** [comment]
Hi @mdsr82,
were you able to solve this problem?
Thanks
