### ISSUE TITLE
Problems with this chart - Responsive

### ISSUE THREAD

**Issue by prsolucoes** [apexcharts/apexcharts.js#677]
Hi,

Im trying make this chart render inside my container (a column in bulma) like other chart libraries, but only this i have problems:

Is the blue chart in my screenshot:

![image](https://user-images.githubusercontent.com/395096/59560124-bd21ca80-8fe2-11e9-9dec-4b98c8e40bb2.png)

Can anyone help me? Thanks.

**Comment by prsolucoes** [comment]
Another problem is that i use type="line" and it appear with bars:

```
chart: {
          id: "vuechart-example",
          width: "100%",
          type: "line"
        },
        stroke: {
          curve: "straight"
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
        }
```

**Comment by prsolucoes** [comment]
Hi,

I solve the problems. Thanks.

**Comment by GeoAbbey** [comment]
> Hi,
> 
> I solve the problems. Thanks.

@prsolucoes  Please, how did you solve the problem? I'm facing a similar challenge.

**Comment by prsolucoes** [comment]
Yes,

I put all here:
https://github.com/prsolucoes/firedash

Thanks.

**Comment by prsolucoes** [comment]
> > Hi,
> > I solve the problems. Thanks.
> 
> @prsolucoes Please, how did you solve the problem? I'm facing a similar challenge.

Yes,

I put all here:
https://github.com/prsolucoes/firedash

Thanks.
