### ISSUE TITLE
Labels readable and it not update like data

### ISSUE THREAD

**Issue by paulo-coutinho** [apexcharts/apexcharts.js#679]
Hi,

I want make the "apex chart" like my "chart.js". I show they here:

![image](https://user-images.githubusercontent.com/395096/59580970-ad20ee00-90a9-11e9-871f-81525ef0bcd8.png)

1 - I want the labels with a space between theirs.
2 - The labels are not updated, the data is updated and the labels not. Im using:
`this.apexChartOptions.xaxis.categories = response.data.data.labels;`

Thanks.

**Comment by prsolucoes** [comment]
The number 2 i solved using:

```
this.apexChartOptions = {
...this.apexChartOptions,
...{
    xaxis: {
    type: "category",
    categories: response.data.data.labels,
    labels: {
        show: true,
        rotate: -45,
        rotateAlways: true,
        hideOverlappingLabels: true,
        trim: true,
        minHeight: 40,
        showDuplicates: false
    }
    }
}
};
```
