### ISSUE TITLE
Reset zoom not respecting initial values

### ISSUE THREAD

**Issue by putyourlightson** [apexcharts/apexcharts.js#68]
I haven't tested all settings, but in v1.3.1 I'm setting the following for a zoomable line chart:

```
yaxis: {
   max: 100,
},
```

When I zoom in and then click the "reset zoom" button, the `max` setting of `100` is ignored and the chart's max value is used instead. I assume this is not expected behaviour.

Thanks you for the amazing charting library!!

**Comment by junedchhipa** [comment]
This is somewhat related to #38 

When I will fix #38, this will be taken care of, thanks for reporting 👍

**Comment by putyourlightson** [comment]
Great thanks!

**Comment by niccooper3ds** [comment]
@junedchhipa can you check this again please, because it is happening in the current version

**Comment by duyn-stanford** [comment]
This still seems to be an issue for timeline charts that set xaxis.min. In my project, set the minimum value to today, March 1, 2023.

My initial chart:
<img width="1572" alt="Screenshot 2023-03-01 at 9 26 32 PM" src="https://user-images.githubusercontent.com/89502875/222338979-4f387ecd-50d7-4b2e-b06f-ac9768d40ae4.png">

When I click on zoom reset:
<img width="1569" alt="Screenshot 2023-03-01 at 9 26 54 PM" src="https://user-images.githubusercontent.com/89502875/222339043-a8096fbf-1ebb-4ae3-934d-6c3ca14244ec.png">
