### ISSUE TITLE
Data labels did not show in bar chart negative space when stacked is true

### ISSUE THREAD

**Issue by pudelduscher** [apexcharts/apexcharts.js#680]
Hi,

if i create a chart from this example [example](https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-negative-values/) and add

```
dataLabels: {
      enabled: true
}
```

the negative space will not get any labels until i switch stacked: false

**Comment by thijscrombeen** [comment]
#681 fixes this issue

**Comment by jlil** [comment]
@thijscrombeen i'm still running into this issue even in 3.8.1

**Comment by thijscrombeen** [comment]
Please see this codepen: https://codepen.io/anon/pen/KjzJvr 
Can you check your configuration?

**Comment by pudelduscher** [comment]
For me it works perfect...thank you :)

**Comment by jlil** [comment]
@thijscrombeen @pudelduscher, set `plotOptions.bar.horizontal = false` the negative labels won't show.
