### ISSUE TITLE
Add option to reverse legend order

### ISSUE THREAD

**Issue by npkumar** [apexcharts/apexcharts.js#683]
**Is your feature request related to a problem? Please describe.**
Tooltip can be reversed using `tooltip.inverseOrder`. Could not find a similar option for legends. So probably need to add `legend.inverseOrder`

**Describe the solution you'd like**
Reverse legend order (including markers + labels)

**Describe alternatives you've considered**
Reversing the series will reverse legends. But does not suite current use case.

**Additional context**
NA

**Comment by junedchhipa** [comment]
There is currently no option in the configuration object, but you can use CSS to do this.

```css
.apexcharts-legend {
  flex-direction: row-reverse
}
```
