### ISSUE TITLE
Is it possible to set the font size for the axis labels?

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#684]
A user of my library Data-Forge Plot is [looking to change the font size for axis labels](https://github.com/data-forge/data-forge-plot/issues/5).

Is it possible to change font size for axis labels in ApexCharts?

I did a quick search of the docs for "font" and "size" and couldn't see anything.

**Comment by junedchhipa** [comment]
Yes.

```javascript
  xaxis: {
        labels: {
            style: {
                fontSize: '12px'
            }
       }
   }
```
https://apexcharts.com/docs/options/xaxis/#labelsFontSize

**Comment by ashleydavis** [comment]
Thanks!

**Comment by devdomsos** [comment]
Hey guys, 

would you also know if we can change the fontSize of the series array? I cannot seem to find an appropriate object I could pass. Or should this be edited via yaxis?

**Comment by deepakcs7050** [comment]
Hey!
I have 4  data
xaxis: {
        categories: [
          "Feb",
          "Mar",
          "Apr",
          "May",
        ]
}
I want only the last labels should be bold "**May**"
Can you help me

**Comment by Rukeeo1** [comment]
I am interested in this too... [junedchhipa](https://github.com/junedchhipa)

> Hey! I have 4 data xaxis: { categories: [ "Feb", "Mar", "Apr", "May", ] } I want only the last labels should be bold "**May**" Can you help me
