### ISSUE TITLE
Sample code references grid.xaxis.showLines but this is not in the types

### ISSUE THREAD

**Issue by iansan5653** [apexcharts/apexcharts.js#686]
On [this page](https://apexcharts.com/javascript-chart-demos/scatter-charts/datetime/) of the documentation, the code references a `grid.xaxis.showLines` property but this is not present in the types file or (as far as I can tell) in the module code. This should probably be removed  but I don't know the code well enough to be sure.

```javascript
    var options = {
      ...
      grid: {
        xaxis: {
          showLines: true
        },
        yaxis: {
          showLines: true
        },
      ...
    }

**Comment by junedchhipa** [comment]
You are correct.
That is an old option which was removed and needs to be removed from examples and docs.
Thanks for pointing it out.

**Comment by iansan5653** [comment]
I don't really care about this issue anymore since I don't use the library anymore, so I have nothing personally against closing it.

However I can't see what could possibly be the benefit in closing it just because it's old - if the problem hasn't been fixed, the issue should remain open until it is. If it's not a real problem or won't ever be fixed, then sure - close the issue. But in this case it's real and has an easy fix, so why not leave it backlogged until some day you get to it? 

Anyway, that's my 2¢ on stale issue bots. Some further reading: https://blog.benwinding.com/github-stale-bots/ and https://drewdevault.com/2021/10/26/stalebot.html.
