### ISSUE TITLE
Rounded bars / border radius option for stacked bar charts

### ISSUE THREAD

**Issue by afrozl** [apexcharts/apexcharts.js#688]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow for custom shapes within stacked bar charts - such as rounded or diamond shaped sections of a bar chart. See attached screenshot as an example

**Describe alternatives you've considered**
None
**Additional context**
![image](https://user-images.githubusercontent.com/6628282/59706418-71cc0f80-91ce-11e9-894c-be469b5c0882.png)

**Comment by eved42** [comment]
Hi,

I would like that too, I saw [that topic](https://github.com/apexcharts/vue-apexcharts/issues/79) but I can't find `borderRadius` option...

**Comment by eved42** [comment]
I found a solution [here](https://github.com/apexcharts/vue-apexcharts/issues/79#issuecomment-593299866).

**Comment by junedchhipa** [comment]
Rounded borders are supported only on the ending side of the bar (not on both side)

```javascript
plotOptions: {
  bar: {
    endingShape: 'rounded'
  }
}
```
No plans to add more shapes for now.

**Comment by junedchhipa** [comment]
Released v.3.17.0
A new property `plotOptions.bar.startingShape` added.
So, using `plotOptions.bar.startingShape` & `plotOptions.bar.endingShape`, you can have the desired effect of rounded borders in bar/column charts.

**Comment by IsaacSomething** [comment]
Here is an alternative solution using clip-path

https://github.com/apexcharts/apexcharts.js/issues/2097
