### ISSUE TITLE
Tooltip Hover in a multi-series chart when not shared is broken

### ISSUE THREAD

**Issue by jenil** [apexcharts/apexcharts.js#689]
## Codepen

https://codesandbox.io/s/apexchart-hover-series-issue-prjcd

## Explanation

I have a simple time series line graph and the hover of the series is not precise, [see this video](https://cl.ly/0a9b8de48e9b)

**Comment by junedchhipa** [comment]
The tooltip behavior, when not shared in a multi-series chart, is buggy.
I have tried several ways, but couldn't find a solution to this issue yet.

The code for detecting data-point in a multi-series chart when `tooltip.shared: false` is located at https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/tooltip/Utils.js#L121

If anyone with a knowledge of detecting close items based on cursor position can help, that would be great!

**Comment by m50434** [comment]
I have the same problem with the unprecise hover while using a multi-series-chart.
Maybe an idea is to check, if the cursor is over the right color.... so the tooltip could depends on the color of the chart.... so you could avoid, that the tooltip from a wrong chart is shown.

> The code for detecting data-point in a multi-series chart when tooltip.shared: false is located at https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/tooltip/Utils.js#L121

By the way: Thanks for the link but acutally we need the code when tooltip.shared is true (like in the video), dont we....

**Comment by tran-simon** [comment]
Any update on this bug @junedchhipa ? I have a line series and a scatter series and I can show the tooltip on the points of my scatter, because it always show the tooltip on the points of the line. tooltip.shared=true is not working

**Comment by damarsimple** [comment]
any update on this issue ?

**Comment by Sergioramasano** [comment]
The tooltip behavior, when not shared in a Multi-series chart, is still buggy. Does it work for you, guys? thanks

**Comment by DespuesLeeWallace** [comment]
This is still not working
