### ISSUE TITLE
Not returning a promise

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#690]
According to the docs, [chart.render() should return a promise](https://apexcharts.com/docs/methods/#).

I'm getting a React component. Are the docs out of date or??

**Comment by junedchhipa** [comment]
The `return` method of `core-apexcharts`, not the `render` method of `react` returns a promise
https://github.com/apexcharts/apexcharts.js/blob/master/src/apexcharts.js#L83

Also, the `render` method of apexcharts is not directly accessible in `react-apexcharts` wrapper.
It is called in `componentDidMount()` method - https://github.com/apexcharts/react-apexcharts/blob/master/src/react-apexcharts.jsx#L28

**Comment by ThinkSalat** [comment]
@junedchhipa Then the docs should be updated to be more accurate! Anyway, is there a way to use that promise in react? I'd like to have my charts draw one by one, and have the next chart start drawing once the first chart is done. 

How should I do that with the react library?
