### ISSUE TITLE
Negatives Data Labels did not show in bar chart negative

### ISSUE THREAD

**Issue by ddominguezh** [apexcharts/apexcharts.js#692]
Hi

It only shows the labels of positive values.

 dataLabels: {
    enabled: true,
 },

![image](https://user-images.githubusercontent.com/7001960/59763197-5843ca00-9299-11e9-8485-4f34fc5ece30.png)

**Comment by junedchhipa** [comment]
DId you find a solution for it or it was a configuration error?

**Comment by mddanishansari** [comment]
@junedchhipa If you're still facing this issue as I also did 

I did some research and I had to change this option, set `hideOverflowingLabels` to `false`

```javascript
plotOptions: {
    bar: {
        dataLabels: {
            hideOverflowingLabels: false
        }
    }
}
```
