### ISSUE TITLE
experiencing blank screen on Firefox

### ISSUE THREAD

**Issue by agksuraj** [apexcharts/apexcharts.js#693]
Appearing a blank page in firefox when using apex chart. After resizing the screen we are able to see the values.Seems like a window sizing event is not firing. Is there any way to fix the issue.
![download (22)](https://user-images.githubusercontent.com/51997889/59764547-a49f0200-92b9-11e9-8165-bdb98761c644.png)

**Comment by junedchhipa** [comment]
Can you please provide a simple codepen demo so I can reproduce easily?
