### ISSUE TITLE
Allow for Legend clicks  when onItemClick has toggleDataSeries disabled

### ISSUE THREAD

**Issue by afrozl** [apexcharts/apexcharts.js#694]
**Is your feature request related to a problem? Please describe.**
The only way to set a custom event handler on legendClicks is by setting toggleDataSeries to true. This allows the custom event handler to fire, but also causes the data series to be toggled off which is not the desired outcome. 
**Describe the solution you'd like**
Let the custom event handler over-ride the toggleDataSeries. In other words, allow clicks to be registered, but do not toggle the data series.

**Describe alternatives you've considered**
forcing a manual toggle after the execution of the custom event

**Comment by gerbenqikker** [comment]
This should be reopened, it is still an issue
