### ISSUE TITLE
How to display number and % in tooltip for Donut Chart

### ISSUE THREAD

**Issue by anilreddy128** [apexcharts/apexcharts.js#695]
I am using a donut chart. I want to see absolute number and % value on tooltip. How to achieve that. For now, I can either display % or actual number.
My data is like this
Status     Count  Percentage
Pass          10            5%
Fail            5            2.5%
Not Tested  185      92.5%

Below is the code I am using for tooltip.
 tooltip: {
                        enabled: true,
                        followCursor: true,
                        style: {
                            fontSize: '12px'
                        },
                        onDatasetHover: {
                            highlightDataSeries: false,
                        },
                        x: {
                            show: true,
                            format: 'dd MMM',
                            formatter: undefined,
                        },
                        y: {
                            formatter: undefined,
                            title: {
                                formatter: (seriesName) => seriesName,
                            },
                        },
                        z: {
                            formatter: undefined,
                            title: 'Size: '
                        },
                        marker: {
                            show: true,
                        },

                        fixed: {
                            enabled: false,
                            position: 'topRight',
                            offsetX: 0,
                            offsetY: 0,
                        },
                    },

Thanks,
Anil

**Comment by ws420** [comment]
Same question here

**Comment by AlbertTj** [comment]
hi. Anil and ws420
to show actual number, you can set in datalabels formatter 
`
dataLabels: {
            enabled: true,
            formatter: function (val, opt) {
                return opt.w.config.series[opt.seriesIndex] + " " + val+"%" 
            }
        },
`
regards,
AlbertTj

**Comment by ws420** [comment]
Thanks for the reply, however, the question was about displaying both the raw number AND the percentage, in the same tooltip.

I am also wondering if it is possible to have line breaks (both in dataLabels and tooltips)

**Comment by AlbertTj** [comment]
sorry for misunderstanding the question 
but actually the basic idea still same you can used `custom` function
`
tooltip: {
                enabled: true,
                custom: function ({ series, seriesIndex, dataPointIndex, w }) {
                    let total = 0;
                    for (let x of series) {
                        total += x;
                    }
                    let selected = series[seriesIndex]
                    return w.config.labels[seriesIndex] + ": " + selected + "(" + (selected / total * 100).toFixed(2) + "%)";
                }
            },
`
source https://apexcharts.com/docs/options/tooltip/#custom
