### ISSUE TITLE
TypeScript types are out of date

### ISSUE THREAD

**Issue by ashleydavis** [apexcharts/apexcharts.js#696]
Looks like TypeScript types are a bit out of date.

`fontFamily` is missing from xaxis.title.style (it is there for yaxis.title.style).

![image](https://user-images.githubusercontent.com/625126/59823573-ebe8c980-9371-11e9-8f52-bf03b4dcb687.png)

**Comment by junedchhipa** [comment]
Yeah, looks like some of the new options are not updated.
Thanks for reporting, will be fixed soon.

**Comment by Genarito** [comment]
Excuse me, how do you import these definitions? I'm looking for it in `node_modules` and it's not present. Just got the `react-apexcharts.d.ts` file:

    interface Props {
        type?: "line" | "area" | "bar" | "histogram" | "pie" | "donut" | "rangeBar" |
            "radialBar" | "scatter" | "bubble" | "heatmap" | "candlestick" | "radar",
        series?: Array<any>,
        width?: string | number,
        height?: string | number,
        options?: object
    }

**Comment by junedchhipa** [comment]
They are present in the core `apexcharts` library
https://cdn.jsdelivr.net/npm/apexcharts@3.24.0/types/apexcharts.d.ts

**Comment by Genarito** [comment]
Cool! Thank you
