### ISSUE TITLE
Tooltip enabledOnSeries does not work

### ISSUE THREAD

**Issue by thijscrombeen** [apexcharts/apexcharts.js#697]
## Codepen

https://codepen.io/anon/pen/OeWVVJ

## Explanation

The enabledOnSeries on the tooltip does not work. When setting the array to the index of one of the series it won't show any of them.

I took a quick look at the code and believe the following is the issue.

` var index = parseInt(opt.paths.getAttribute('index'));
 if (this.tConfig.enabledOnSeries.indexOf(index) < 0) {
            self.handleMouseOut(opt);
            return;
          }`

The index results in NaN. The opt.paths property results in the entire graph and not in the path of the stroke where the index attribute is on. I'm able to get the index using below snippet and then it does work:

`var index = self.tooltipUtil.getNearestValues({
            context: self,
            hoverArea: opt.hoverArea,
            elGrid: opt.elGrid,
            clientX: clientX,
            clientY: clientY,
            hasBars: self.hasBars
          }).capturedSeries;`

**Comment by thijscrombeen** [comment]
Can you give your opinion on if the below code snippet can be used to retrieve the correct index?
If yes then I'd be happy to create a PR for this.

**Comment by junedchhipa** [comment]
Thanks for reporting. The change was required at another place although what you proposed would also work.

**Comment by smismailalam** [comment]
I am facing same issue, tooltip enabledOnSeries is not working

**Comment by mariusberlinghof** [comment]
I just relized, that the #[mentioned issue](https://github.com/apexcharts/apexcharts.js/issues/824) is relating to a different problem (dataLabels.enabledOnSeries) and does not relate to tooltip.enabledOnSeries.
As far as I can tell, the issue still exists.
Would be nice to reopen this issue.

**Comment by bosseDev** [comment]
Why is this closed? I have the problem with irregular timeseries.

**Comment by functionpointer** [comment]
Same issue here, plotting two irregular timeseries. I can supply `[0]`, then it shows tooltips for all series. But if i supply 1 or above, no tooltips are shown at all.

Running [apexcharts-card v2.0.4](https://github.com/RomRider/apexcharts-card/releases/tag/v2.0.4), with whatever version of apexcharts that ships

**Comment by matheo** [comment]
Hi @junedchhipa! 
I hope you're doing good!

I'm pinging here because I'm using the latest version and `tooltip.enabledOnSeries` is not working as intended.
I bet that a small check from you can get it fixed and with a minor patch released to fix this annoying one :pray: 
Thanks in advance for your time!

**Comment by dmutsaers** [comment]
Today I tried to configure "enabledOnSeries", but it has no effect.
