### ISSUE TITLE
Multiple data Bubble chart breaks when radius for all the data point becomes the same

### ISSUE THREAD

**Issue by yadavAnshumaan** [apexcharts/apexcharts.js#699]
## Codepen
https://codepen.io/anon/pen/YoNqMX?editors=1010

## Explanation

- What is the behaviour you expect? 
Expected a graph with different circles with the same radius, spread across the graph area. 
- What is happening instead?
The graph becomes a rectangle and needs "two" updates before it properly renders again.
- What error message are you getting?
No Error Message

**Comment by BiggerNoise** [comment]
FWIW - This is ugly, but allows you to apply your own logic to fix the broken zRatio calculation:

```
        const chart = new ApexCharts(this.controller.element, apexOptions);
        chart.core.coreUtils.__proto__.getCalculatedRatios = this.fixChartZRatios(apexOptions.user.zRatio, chart.core.coreUtils.__proto__.getCalculatedRatios );
        chart.render();
```

Obviously, the content of fixChartZRatios() is going to be up to your particular application.
