### ISSUE TITLE
Option to scale other axis when using zoom: "x" or "y"

### ISSUE THREAD

**Issue by xumix** [apexcharts/apexcharts.js#700]
If one selects `zoom: "x" or "y"` option and then uses zoom then apexcharts has no option to rescale the graph. It would be nice to have this kind of option.

**Describe the solution you'd like**
An option like `rescaleChart` so the chart can take all the vertical/horizontal space

**Describe alternatives you've considered**
`zoom: "xy"` is almost a solution, but it is actually not very convenient if a chart is rather big

**Additional context**
Here are some screenshots:
Initial state:
![image](https://user-images.githubusercontent.com/250118/59917491-c075e580-942a-11e9-80df-55095d2592db.png)
Actual zoom `type: "x"` chart:
![image](https://user-images.githubusercontent.com/250118/59917519-d5527900-942a-11e9-87bb-2335a2aa8278.png)
Desired state is something like this:
![image](https://user-images.githubusercontent.com/250118/59917915-e94aaa80-942b-11e9-9334-4fe8c57ddbb9.png)

**Comment by junedchhipa** [comment]
We have a new option `autoScaleYAxis` which achieves what you described.

```javascript
chart: {    
    zoom: {
          autoScaleYaxis: true
     }
}
```
https://apexcharts.com/docs/options/chart/zoom#autoScaleYaxis

**Comment by xumix** [comment]
Thanks!
