### ISSUE TITLE
How to add a background image on the ApexCharts. 

### ISSUE THREAD

**Issue by bubuamu** [apexcharts/apexcharts.js#701]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandonburkett** [comment]
I believe you can set a background image via:
```javascript
chart: {
  background: 'url(/assets/img/some.svg)'
},
```

BUT it doesn't look like it will work if you download the svg / png

**Comment by brakop** [comment]
Second Brandon's comment, I was able to get into the paper() (https://apexcharts.com/docs/methods/#paper) property on the chart and add a custom image with SVG.js image() method (https://svgjs.com/docs/3.0/shape-elements/#image), but then it doesn't stay in the exported file. I wonder if there's a method to flatten the custom additions into the chart so they are exported as well? Alternatively would probably have to replace the default download function with a custom one built around dataURI() that runs the additional operation on download. Any advice on this? It's great that the paper() opens up the entire SVG.js library, but I need to download what I see (after adding components), not just the original chart.

**Comment by brakop** [comment]
PS - The changes disappear on browser resize as well (I'm assuming for same reason, the re-draw/re-size function is unaware of the custom additions).
