### ISSUE TITLE
How to put Multi Category to the label of Y-Axis in  group bar chart 

### ISSUE THREAD

**Issue by sanymochi** [apexcharts/apexcharts.js#705]
Hi, 

I want to Put **Multi category** to the label of Y-Axis in **Group Bar chart** 

Now the Group Chart: 
![image](https://user-images.githubusercontent.com/40659606/60073360-d989d980-973d-11e9-8989-9d379facc863.png)

I want Like this: 

**Example1 :** Region is category and state is subcategory 
![image](https://user-images.githubusercontent.com/40659606/60073136-40f35980-973d-11e9-8031-aa58bb4eb93f.png)
**Example2:**
![image](https://user-images.githubusercontent.com/40659606/60239623-f2c09080-98cb-11e9-863c-993bdf227da8.png)

**Example3:**
![image](https://user-images.githubusercontent.com/40659606/60239733-4f23b000-98cc-11e9-8665-26ca5df9182d.png)

**Example4:**
![image](https://user-images.githubusercontent.com/40659606/60239810-8db96a80-98cc-11e9-8455-51cf28544dd9.png)

so, How to achieve this.? 

**Thanks in Advance..!!!**

**Comment by junedchhipa** [comment]
Sorry, this is not achievable directly, but you can try playing with annotations and achieve a similar look.

Below is the image which I tried creating with annotations
![Screen Shot 2019-07-06 at 5 20 09 PM](https://user-images.githubusercontent.com/17950663/60755779-50fb1b00-a012-11e9-9042-f4b8e172e120.png)

Codepen Example - https://codepen.io/apexcharts/pen/bPxQvV

**Comment by Raptr12** [comment]
Is this possible in the xaxis aswell?

**Comment by diedel** [comment]
The xaxis has the group property for this:
https://apexcharts.com/docs/options/xaxis/

For a sample:
https://apexcharts.com/javascript-chart-demos/column-charts/column-with-group-label/

**Comment by ChucNB** [comment]
> The xaxis has the group property for this: https://apexcharts.com/docs/options/xaxis/
> 
> For a sample: https://apexcharts.com/javascript-chart-demos/column-charts/column-with-group-label/

But it's not for horizontal charts right?
