### ISSUE TITLE
Radialbar chart is not showing properly in edge if series's value is low

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/apexcharts.js#706]
Hi,
I would like to inform you about the new bug recently I encountered. When we try to use low number in series of radial bar it crops/cut that series. This only happens in microsoft edge browser. I have tested this in edge 44.177....

![delete](https://user-images.githubusercontent.com/31243533/59960860-8e2cbc80-94ec-11e9-9466-5444b0bc9fb6.PNG)

Link: https://jsfiddle.net/jsinh0001/xpsz12oa/7/

**Comment by junedchhipa** [comment]
Disabled the drop-shadow effect in IE for radial-bar charts as it seems to cause issues.
In all other chart types, it will be as it is.

**Comment by jd-0001** [comment]
Hello @junedchhipa,
Thanks for quick implementation. This issue still remains if I **hover** over chart.
Can you please check it.

~ Thanks

**Comment by jsinhSolanki** [comment]
@junedchhipa  Any updates??

**Comment by Jarkovato** [comment]
I also have a problem with hovering and clicking. Please help
![bug](https://user-images.githubusercontent.com/62695620/113153080-6af57c00-923f-11eb-8ee9-eddb4b45a793.JPG)
