### ISSUE TITLE
Drilldown Feature

### ISSUE THREAD

**Issue by kalimuthu123** [apexcharts/apexcharts.js#707]
**Is your feature request related to a problem? Please describe.**
drilldown feature is requested for easy implementation of charts 

**Describe the solution you'd like**

**Describe alternatives you've considered**
element level of hierarchies need for design 

**Additional context**
enchanced chart design

**Comment by junedchhipa** [comment]
Sorry, a direct implementation of this feature is out of the chart's scope. 
Maybe you can try tweaking 2 charts to create an effect of a drilldown chart as shown here - https://apexcharts.com/javascript-chart-demos/column-charts/dynamic-loaded-chart/

**Comment by oktayaa** [comment]
Came through search. I was more looking for a ready made dashboard software (lighter grafana) but that feature looks really nice. Good job.
