### ISSUE TITLE
Dynamic Data from array in Tooltip

### ISSUE THREAD

**Issue by RahulUNC** [apexcharts/apexcharts.js#708]
Is there anyway to dynamically add text in the tooltip from a predefined array. I tried using the y formatter with a radial bar chart, but when i did "return value +  arr[seriesIndex]" i got undefined for the array value, so I was wondering if this was possible

`
	tooltip: {
                        y: {
                            formatter: function(value, { series, seriesIndex, dataPointIndex, w}) {
                                console.log(arr[seriesIndex]);
                                return value + " " + arr[seriesIndex];          //arr defined as a global variable
                            }
                        },
                        enabled: true,                   
                    },

`

**Comment by vicpon** [comment]
@RahulUNC are you sure the array has a value at the index specified by seriesIndex?

**Comment by RahulUNC** [comment]
> @RahulUNC are you sure the array has a value at the index specified by seriesIndex?

Yes, 100% sure. If i put in values like arr[0] it works just fine. However with seriesIndex it prints the correct output in the console, followed immediately by undefined

**Comment by vicpon** [comment]
Are you sure value is not null or undefined? Maybe change it to this:

```javascript
return value ? (value + " " + arr[seriesIndex]) : "";
```

**Comment by junedchhipa** [comment]
@RahulUNC 
Please create a codepen demo, so we can jump quickly and see if there's any issue with configuration.

**Comment by RahulUNC** [comment]
> @RahulUNC
> Please create a codepen demo, so we can jump quickly and see if there's any issue with configuration.

https://codepen.io/rahulunc/pen/MNgqqX

**Comment by VishaliniVijayarahavan** [comment]
Is there any solution for this issue?

**Comment by CinoMizar** [comment]
At the beginning I had the same issue. This now works for me:

  <script>
        $(function () {

            var data_test = [3, 4, 5];
            var others = [134, 342, 334];

            (dataColors = $("#live_pl_per_trade").data("colors")) && (colors = dataColors.split(","));
            options = {
                chart: {height: 440, type: "bar", toolbar: {show: !1}},
                plotOptions: {
                    bar: {
                        colors: {
                            ranges: [{
                                from: -100,
                                to: -4,
                                color: "#fa5c7c"
                            },
                                {
                                    from: -4,
                                    to: 0,
                                    color: "#ffbc00"
                                },
                                {
                                    from: 0,
                                    to: 100,
                                    color: "#7CFC00"
                                }]
                        }, columnWidth: "90%"
                    }
                },
                dataLabels: {enabled: !1},
                series: [{
                    name: "Profit/loss per trade",
                    data: data_test,
                }],

                tooltip: {
                    custom: function ({series, seriesIndex, dataPointIndex}) {
                        return series[seriesIndex][dataPointIndex] + " and " + others [dataPointIndex]
                    }
                },

                legend: {
                    show: false
                },

                yaxis: {
                    title: {
                        text: ""
                    }
                    ,
                    labels: {
                        formatter: function (o) {
                            return o.toFixed(0) + "%"
                        }
                    }
                },

                grid: {
                    row: {
                        colors: ["transparent", "transparent"], opacity: 0.2
                    }
                    ,
                    borderColor: "#3eb3d8"
                }

            };

            (chart_pl_trade = new ApexCharts(document.querySelector("#live_pl_per_trade"), options)).render();

        });
    </script>
