### ISSUE TITLE
x-axis values not rendered properly for real-time chart

### ISSUE THREAD

**Issue by gcornetta** [apexcharts/apexcharts.js#709]
## Codepen

<template>
  <div class="app">
    <apexcharts ref="realtime" type="line" height="350" :options="options" :series="series"></apexcharts>
  </div>
</template>

<script>
import VueApexCharts from "vue-apexcharts";

export default {
  name: "Chart",
  components: {
    apexcharts: VueApexCharts
  },
  mounted() {
    this.loop();
  },
  methods: {
    init() {
      const BUF_SIZE = 10;
      let d = new Date().getTime();

      if (this.series[0].data.length >= BUF_SIZE) {
        this.series[0].data.shift();
        this.series[1].data.shift();
      }
      this.series[0].data.push([d, 10]);
      this.series[1].data.push([d, 20]);
      this.$refs.realtime.updateSeries([
        {
          name: "temperature",
          data: this.series[0].data
        },
        { name: "pressure", data: this.series[1].data }
      ]);
    },
    loop() {
      setInterval(() => {
        this.init();
      }, 2000);
    }
  },
  data: function() {
    return {
      options: {
        chart: {
          animations: {
            enabled: true,
            easing: "linear",
            dynamicAnimation: {
              speed: 1000
            }
          },
          toolbar: {
            show: true
          },
          zoom: {
            enabled: false
          }
        },
        dataLabels: {
          enabled: true
        },
        stroke: {
          curve: "smooth"
        },
        title: {
          text: "Measured sensor values",
          align: "left"
        },
        markers: {
          size: 3
        },
        xaxis: {
          type: "datetime",
          range: 20000,
          tickAmount: 10,
          labels: {
            format: "HH:mm:ss"
          }
        },
        yaxis: {
          max: 100
        },
        legend: {
          show: true
        },
        tooltip: {
          x: {
            format: "dd/MM/yy HH:mm:ss"
          }
        }
      },
      series: [
        {
          name: "series1",
          data: [[new Date().getTime(), 0]]
        },
        {
          name: "series2",
          data: [[new Date().getTime(), 0]]
        }
      ]
    };
  }
};
</script>

## Explanation

- What is the behavior you expect?
  I would expect that in the x axis the sampling time of each values is rendered with the format ('HH:mm:ss')

- What is happening instead?
   In the codepen nothing is rendered, but on my MAC at each x-axis tick appears the time in milliseconds instead of the selected format. I tried also to uses a custom formatter (with and without moment.js) but my impression is the the formatting callback is never invoked.
The tooltip is update correctly.

Interestingly, there are also a couple of other issues related with this codepen. If you look at the init method where I update the time series, you will see that I use both an array push and the updateSeries method. updateSeries could seem redundant but it is necessary, otherwise there is a lag between the update of the marker points and of the graph line (i.e. first are shifted forward the marker points and then the graph lines). I also tried to use the updateSeries method applying the spread operator to the series array and then adding at the end a new data point but it does not work (the graph lines are not correctly updated)

- What error message are you getting?
I don't get any error, the application does not crash and the graph looks fine, only the x-axis is incorrect.

Hope this could help to solve this issue and thank you so much for sharing this fantastic charting library.

Best regards,

Gianluca Cornetta

**Comment by junedchhipa** [comment]
Can you please create a codepen and provide a link for it?
It will be helpful to directly jump into the issue if I see a working demo.

**Comment by gcornetta** [comment]
Hi the codepen was in my previous comment; however I have just realised it was incomplete.

This is the URL:

https://codesandbox.io/s/vue-basic-example-ssl8r?fontsize=14

and just for security here comes again the full code:




<template>
  <div class="app">
    <apexcharts ref="realtime" type="line" height="350" :options="options" :series="series"></apexcharts>
  </div>
</template>

<script>
import VueApexCharts from "vue-apexcharts";

export default {
  name: "Chart",
  components: {
    apexcharts: VueApexCharts
  },
  mounted() {
    this.loop();
  },
  methods: {
    init() {
      const BUF_SIZE = 10;
      let d = new Date().getTime();

      if (this.series[0].data.length >= BUF_SIZE) {
        this.series[0].data.shift();
        this.series[1].data.shift();
      }
      this.series[0].data.push([d, 10]);
      this.series[1].data.push([d, 20]);
      this.$refs.realtime.updateSeries([
        {
          name: "temperature",
          data: this.series[0].data
        },
        { name: "pressure", data: this.series[1].data }
      ]);
    },
    loop() {
      setInterval(() => {
        this.init();
      }, 2000);
    }
  },
  data: function() {
    return {
      options: {
        chart: {
          animations: {
            enabled: true,
            easing: "linear",
            dynamicAnimation: {
              speed: 1000
            }
          },
          toolbar: {
            show: true
          },
          zoom: {
            enabled: false
          }
        },
        dataLabels: {
          enabled: true
        },
        stroke: {
          curve: "smooth"
        },
        title: {
          text: "Measured sensor values",
          align: "left"
        },
        markers: {
          size: 3
        },
        xaxis: {
          type: "datetime",
          range: 20000,
          tickAmount: 10,
          labels: {
            format: "HH:mm:ss"
          }
        },
        yaxis: {
          max: 100
        },
        legend: {
          show: true
        },
        tooltip: {
          x: {
            format: "dd/MM/yy HH:mm:ss"
          }
        }
      },
      series: [
        {
          name: "series1",
          data: [[new Date().getTime(), 0]]
        },
        {
          name: "series2",
          data: [[new Date().getTime(), 0]]
        }
      ]
    };
  }
};
</script>

**Comment by junedchhipa** [comment]
If nothing shows up in x-axis datetime, I suggest switching to `xaxis.type: 'category'` and formatting the datetime using a tiny datetime library (day.js)
Sorry for the long delay in replying.
