### ISSUE TITLE
Date/Time on yaxis? How to?

### ISSUE THREAD

**Issue by enxinas** [apexcharts/apexcharts.js#710]
So I tried using Moment.js by using the formatter function. While I was able to modify the value, It was somehow rounding it to whole numbers. IE: 3:30 (min:sec) will return a value of 3 only. Is there an easy way to show date or time on the yaxis with a single line chart or even a combo chart similar to my mockup? This the mockup I made:

![Screen Shot 2019-06-25 at 10 00 38 AM](https://user-images.githubusercontent.com/32417703/60118289-e18f4c80-9730-11e9-971a-c5ad116bbc41.png)

**Comment by junedchhipa** [comment]
Can you please create a codepen demo?

**Comment by enxinas** [comment]
Here you go, not 100% the same as the design mock but similar. Also do note I'm not a developer, so I may have missed some dumb mistakes.

https://codepen.io/reginaldvs/pen/OejZPX

**Comment by enxinas** [comment]
Fixed; I ended up using plain JS with the code I found somewhere in stackoverflow in a hacky way. There's probably a better way of doing this but it works for my needs and I don't need it to be 100% perfect/efficient. I updated the Codepen for those who are curios.
