### ISSUE TITLE
Extension/override of library methods

### ISSUE THREAD

**Issue by Demak** [apexcharts/apexcharts.js#711]
**Is your feature request related to a problem? Please describe.**
I need to make adjustments to the chart that go beyond what is achievable with chart configuration. I need to make changes to the library methods which are drawing the chart, more specifically I need to override about half methods of the Pie class, with drawArcs method to be most heavily modified. I could not find this class in global namespace or chart instance, looks like it is created using some sort of factory function, but I can't understand if it possible to somehow modify its creation.

**Describe the solution you'd like**
I need to know if it is possible to override Pie class method and so than how should I do that. Adding that to documentation and providing a simple example would be great.

**Describe alternatives you've considered**
I can modify library directly but its not desirable.

**Comment by Mihailoff** [comment]
This is a great library. Unfortunately, the lack of extensibility forces us switching to https://www.chartjs.org/docs/latest/developers/plugins.html

**Comment by Demak** [comment]
Closing since if there was an existing method someone would probably described it by this time. I have made changes I needed to the library directly.
