### ISSUE TITLE
Different colors for each bar, plus monochromatic feature

### ISSUE THREAD

**Issue by abbasahmed** [apexcharts/apexcharts.js#713]
I was trying to create a confidence chart where each bar is stacked based on the confidence level(0.0 - 1.0), with higher confidence reflecting darker stack of the same color. I could achieve this with the monochromatic theme, and setting 'shadeTo' set to dark. 

However, I would also have liked for each bar to a different color, as each bar represent a different label. 

For now, I have created multiple monochromatic graphs and disabled all the axes and grids to make them look like they are the same graph. (This is on Vue framework)

<img width="296" alt="Screen Shot 2019-06-27 at 12 42 50 AM" src="https://user-images.githubusercontent.com/23068142/60217112-98e0ac00-9874-11e9-8da3-5a6f504f01ca.png">

However, they are all unlinked, don't have a proper scale and I would very much like it to be within the same graph. I think it would be a really cool feature to add.

**Comment by TomDeSmet** [comment]
You can pass a color for each bar with the `colors: []` setting in your options object and than add 
```
plotOptions: {
                        bar: {
                            distributed: true
                        }
                    }
```
That will create what you want in one graph with one series.

**Comment by binoculars88** [comment]
@TomDeSmet doesn't seem to work for rangeBar charts (https://jsfiddle.net/d3qnrpot/)
