### ISSUE TITLE
How can I flip the axes of a line chart?

### ISSUE THREAD

**Issue by jlil** [apexcharts/apexcharts.js#714]
- Codepen:
https://codepen.io/anon/pen/KjXYKa

- What is the behavior you expect?
if i have a line chart with the following data (xaxis numeric, yaxis string/category):
```
series: [{
    data: [{
        x: 54,
        y: 'Apple'
    }, {
        x: 66,
        y: 'Orange'
    }],
}]
```
I expect the chart to render the series

- What is happening instead?
the chart doesn't render the series. 

- What error message are you getting?
none

**Comment by jlil** [comment]
@junedchhipa is this feasible?

**Comment by junedchhipa** [comment]
Sorry, flipped axis on line chart is not possible currently.
It is not even on the roadmap due to the complexities involved in achieving it.
