### ISSUE TITLE
forceNiceScale for xAxis

### ISSUE THREAD

**Issue by npkumar** [apexcharts/apexcharts.js#715]
**Is your feature request related to a problem? Please describe.**
yaxis has `forceNiceScale` option. Needed a similar one for xaxis. See https://github.com/apexcharts/apexcharts.js/commit/64cca3b16765f11bfa8043f0f7058672e0dc9c31

![xaxis](https://user-images.githubusercontent.com/7235671/60245158-f584ab00-98f6-11e9-97d0-5080ccc40c2b.png)

**Describe the solution you'd like**
```js
xaxis: {
  forceNiceScale: true
}
```
**Describe alternatives you've considered**
Rounding via `labels.formatter` but this causes inconsistencies and mismatch between xaxis label and tool-tip values.

**Additional context**
Looking for a way to force xaxis labels to numbers either ending in 0 or in 5, no other numbers. But `forceNiceScale` behavior also works. Also not sure if this works well if `tickAmount` is specified.

**Comment by joerez** [comment]
🥲

**Comment by AwesomeZaidi** [comment]
😒

**Comment by yoimnik** [comment]
[junedchhipa](https://github.com/apexcharts/apexcharts.js/commits?author=junedchhipa)

any assistance here? i'm using ReactApexCharts type="line" and my x-axis looks very weird. would be great if there is a forceNiceScale option.

<img width="332" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/12193963/f9bbb5ae-9d01-4c6d-a68b-a5b80527446f">

**Comment by yoimnik** [comment]
@junedchhipa 

any assistance here? i'm using ReactApexCharts type="line" and my x-axis looks very weird. would be great if there is a forceNiceScale option.

<img width="332" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/12193963/f9bbb5ae-9d01-4c6d-a68b-a5b80527446f">

**Comment by arjolpanci** [comment]
I am also interested in this. There seems to be no way to force xAxis to have integer steps without messing up the alignment with the data points.

**Comment by arjolpanci** [comment]
@yoimnik 

Did you end up solving this problem? I am facing the exact same thing and there doesn't seem to be a way to fix this without messing up alignment with the data points, which is a pretty big limitation.
