### ISSUE TITLE
X-axis labels does not rotate when overlapped

### ISSUE THREAD

**Issue by dream-sky12** [apexcharts/apexcharts.js#716]
## Codepen
https://codepen.io/Dream_Sky12/pen/wLPGvq
## Explanation
I created a line chart and set the x-axis labels' "trim" property "false" and rotating angle -45 degrees.
I created severals x-axis labels and the last character of the previous label overlaps with the first character of the next label.
I think that the x-axis labels (overlapped) should rotate but they does not.

**Comment by mickenorlen** [comment]
It seems the breakpoint comes in too late.
![image](https://user-images.githubusercontent.com/9784434/64346850-3124ab00-cff3-11e9-95b7-ed8801d57b4b.png)

But for me it does rotate when the space gets smaller:
![image](https://user-images.githubusercontent.com/9784434/64346926-51ed0080-cff3-11e9-9e99-5443b92c765d.png)

**Comment by mickenorlen** [comment]
Maybe you could add some rotate sensitivity param for tweaking? :P

**Comment by CalyphoZz** [comment]
It seem xaxis rotate is broken ?

**Comment by dream-sky12** [comment]
> It seems the breakpoint comes in too late.
> ![image](https://user-images.githubusercontent.com/9784434/64346850-3124ab00-cff3-11e9-95b7-ed8801d57b4b.png)
> 
> But for me it does rotate when the space gets smaller:
> ![image](https://user-images.githubusercontent.com/9784434/64346926-51ed0080-cff3-11e9-9e99-5443b92c765d.png)
> 
> Maybe you could add some rotate sensitivity param for tweaking? :P
> 
> Btw, trim seems to sense when the overlap happens better than rotate. As i get the "..." at appropriate timings

Yes, If I add more labels or make the space get smaller the x-axis will rotate. But it always has a situation that when the space is in a certain range, the labels will overlapped
