### ISSUE TITLE
Wrong seriesIndex on markerClick event in stacked area charts 

### ISSUE THREAD

**Issue by dragfire** [apexcharts/apexcharts.js#720]
## Codepen

https://codepen.io/d3vas3m/pen/rEYYLx

## Explanation

- What is the behavior you expect?

When I click on an area(not on the marker or datapoint) for a particular series, it should return the correct seriesIndex.

- What is happening instead?

I am using markerClick event to get the clicked seriesIndex, it does return correct value sometimes but other times it seems to pick up the wrong seriesIndex.

Also, if I click anywhere but the stacked areas, it just returns the top stacked series. I don't know if it is the desired behavior.

- What error message are you getting?

No error message.

If there is any better way to get the correct seriesIndex, it would be really great. Thank you!

**Comment by tejaswinieswar** [comment]
+1

**Comment by HardikSLathiya** [comment]
+1 
Today I found that if we set **tickPlacement: 'between'** in xaxis config in line chart Or area chart then **markerClick** event seems to pick top seriesIndex always

If i don't use **tickPlacement: 'between'** then it works fine and pick up correct seriesIndex.

**Comment by keyone2693z** [comment]
+1
same issue
