### ISSUE TITLE
Discrete Markers and Radar Graphs

### ISSUE THREAD

**Issue by Craicerjack** [apexcharts/apexcharts.js#723]
Im having an issue with discrete markers and radar graphs. 
I took your working codepen from #286 and changed the chart type to radar graph and the discrete markers dont take effect. 
Can discrete markers be used with radar Graphs 

https://codepen.io/craicerjack/pen/ewMBbj

**Comment by junedchhipa** [comment]
You're correct.
Discrete markers don't work in Radar Charts. I will release a fix soon.
