### ISSUE TITLE
Pie/Donut not using the correct height

### ISSUE THREAD

**Issue by ajsheldon93** [apexcharts/apexcharts.js#724]
I am trying to create a donut chart. I set the width as 100% and the height to 450px as seen here:
`<apexchart width="100%" height="450px" type="donut" :options="chartOptions" :series="series"></apexchart>
`
Upon inspection, the SVG of the donut chart never renders at 450px. It is either larger or smaller and changes as the width changes. the same issue occurs with a pie chart. This results in the bottom of the chart being cut off. or If I have a legend positioned on the bottom, it get cut off by the chart.

![Screen Shot 2019-07-01 at 4 31 06 PM](https://user-images.githubusercontent.com/2422834/60464859-aeabf380-9c1d-11e9-85fa-f4d2cdeed92d.png)
_Note: in the screenshot, the surrounding dix has style of `height: 450px`, but you see the chart is getting cut off because the svg is 351px._

I am doing the same thing with a bar, column, and line charts and they all render to the correct height.

I am also pretty sure this issue wasn't happening a few weeks ago when I built these charts originally. 

Any help here? Thanks!

**Comment by manisha-seclogic** [comment]
@junedchhipa I am using Donut Apex Chart and when I try to reduce the height from 250 there is some unexpected padding-top
I don't know the reason 
Please Help  

Code:
options:{
    series: [15,5,5,20],
    chart: {
      height: 200,
      type: "donut",
      toolbar: {
        show: true,
        tools: {
          download: true,
          selection: true,
          zoom: true,
          zoomin: true,
          zoomout: true,
          pan: true,
          reset: true
        },
        export: {
          csv: {
            filename: 'Lastest Phishing Graph Data',
            columnDelimiter: ',',
            headerCategory: 'category',
            headerValue: 'value',
            dateFormatter(timestamp) {
              return new Date(timestamp).toDateString()
            }
          },
        },
      },
    },
    plotOptions: {
        pie: {
          donut: {
            size: '65%',
            customScale: 0.1,
            expandOnClick: true,
            labels: {
              show: true,
              name: {
                show: true,
                fontSize: '22px',
                fontFamily: 'Rubik',
                color: '#dfsda',
                offsetY: -10
              },
              value: {
                show: true,
                fontSize: '16px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                color: isDark?'white':'Black',
                offsetY: 16,
                formatter: function (val) {
                  return val
                }
              },
              total: {
                show: true,
                label: 'Total',
                color: isDark?'white':'Black',
              }
            }
          }
        }
    },
    stroke: {
      width: 2,
      colors : ['#008FFB', '#00E396','#FEB019', '#EA3546'],
      opacity: 1,
    },
    fill:{
      colors : ['#008FFB', '#00E396','#FEB019', '#EA3546'],
      opacity: 0.7,
    },
    legend: {
      show: true,
      labels:{
        colors: isDark ? 'gray' : 'black',
      }
    },
  dataLabels: {
    enabled: false,
  },
  tooltip: {
    theme: isDark ? 'light' : 'dark',
    marker: {
      show: false,
    },
  },
  labels: ['Total', 'Good', 'Warning', 'Danger'],
  }
}

<ReactApexChart options={options()} series={options().series} type="donut" height={20
<img width="243" alt="hhhhhhhhhhhhhhhhhhhhhhhh" src="https://user-images.githubusercontent.com/64947641/91558311-bc5d2600-e953-11ea-9723-37e4a94c3d89.PNG">
0}  />

**Comment by sivabalan18102001** [comment]
Hi, @junedchhipa ,
      We are using the Donut Apex Chart with legend position as bottom and I want the height of the chart to be 260px like the outer div of height:260px but it generates the height of the chart container as 227.7px. So it generates some space between the chart and the bottom of the outer container.

We couldn't find the reason for this.

Could you please help us to solve this issue?

donutOption:
{
    "series": [10800,0,16800,4800],
    "labels": ["Legent (1)","Legent (2)","Legent (3)","Legent (4)"],
    "chart": {
        "type": "donut",
        "width": "100%",
        "height": "260",
    },
    "legend": {
        "position": "bottom",
    },
}

![Apex Chart Height](https://github.com/user-attachments/assets/1170618a-744f-41d8-9c24-45fb7f7b437f)
