### ISSUE TITLE
Legend color markers are not displayed when a function is used for chart color

### ISSUE THREAD

**Issue by harshit3** [apexcharts/apexcharts.js#725]
When we use function in 'colors' option then legend colors are not visible.
Sandbox link: https://codesandbox.io/s/new-paper-ep1ei
![Screenshot 2019-07-02 at 12 35 55 PM](https://user-images.githubusercontent.com/19990615/60491297-14ec5100-9cc6-11e9-8f45-974eaaa7dc94.png)

**Comment by LaurentEsc** [comment]
Hi there. I am facing the same problem. Is there any solution?

**Comment by harshit3** [comment]
No, I did not get any solution for this yet.

**Comment by harshit3** [comment]
> Hi there. I am facing the same problem. Is there any solution?

I did not get any solution yet.

**Comment by AndreaMinato** [comment]
I'm facing the same bug.

@junedchhipa since is quite important to me right now do you need some help to fix it?

**Comment by junedchhipa** [comment]
Fixed the issue.


If for some reasons, the legend and the tooltip markers colors don't show up, I have added new properties. (as in bar charts, the legend and tooltip markers still won't show up correctly).
So, as a workaround, you can use

```
legend: {
  markers: {
    fillColors: []
  }
},
tooltip: {
  marker: {
    fillColors: []
  }
}
```

**Comment by vincemat** [comment]
Hi @junedchhipa,

I'm facing the same issue as above and using your workaround does not solve the issue.
Do you confirm that it has been solved ?

Thanks !

**Comment by anupsamanta** [comment]
Hi @junedchhipa,
Worked for me. excellent staff
