### ISSUE TITLE
Display wrong datetime (1/7) in xaxis

### ISSUE THREAD

**Issue by boyanhtrai** [apexcharts/apexcharts.js#728]
Codepen: https://codepen.io/azivkovi/pen/rgbEMj
![image](https://user-images.githubusercontent.com/29662022/60568159-3a489000-9d96-11e9-8856-41490ed9fe70.png)
Current date in the image:  Jul'18
Expect date:  01 Jul
---------------------------------
Other case: 
Current date in the image :  06/07/2019
Expect date:  01/07/2019
![image](https://user-images.githubusercontent.com/29662022/60568350-ce1a5c00-9d96-11e9-9ef7-1c840142e0f6.png)

**Comment by drummad** [comment]
I was about to post the same issue myself. I've reproduced it in a simple codepen here:

https://codepen.io/Drummad/pen/Oewyrb

In this instance the dates are from a series containing timestamps. It seems to potentially be a problem with the format function.
