### ISSUE TITLE
using selection zoom/pan with sync charts copying yaxis option of the chart zoomed to the other charts synched

### ISSUE THREAD

**Issue by tektosdhon** [apexcharts/apexcharts.js#729]
Codepen: https://codepen.io/anon/pen/ordOWB

**Explanation:** 

What is happening?
On syncing line chart, I add a y-axis option of min, max and title for both chart with different value, I set the y-axis min: 10, max: 70 and title: Facebook of the first chart and set y-axis min: 0, max: 45 and title: Twitter on the second chart. But once I use selection zoom or panning on first chart, it copies it's y-axis value of and it's title to the second chart, vice versa.

It is important for my project to have the y-axis min max to be different in each chart and at the same time to use the sync chart to show their data is related. The two chart is humidity and temperature.

EDIT:
I am using the latest version v3.8.1
using this link : https://cdn.jsdelivr.net/npm/apexcharts

**Comment by junedchhipa** [comment]
It is fixed in the latest version of apexcharts@3.8.3

**Comment by tektosdhon** [comment]
> It is fixed in the latest version of apexcharts@3.8.3
Thanks for the fast action. It's working now
