### ISSUE TITLE
Merge columns

### ISSUE THREAD

**Issue by xxx44yyy** [apexcharts/apexcharts.js#730]
https://codepen.io/xxx44yyy/pen/QXxLBE

![image](https://user-images.githubusercontent.com/40538167/60576416-07969b80-9d86-11e9-92b1-0b598e51baed.png)

**Is your feature request related to a problem? Please describe.**
I would like to be able to combine consecutive columns.

**Describe the solution you'd like**
The easiest way is to specify a range. For example, December 1 to December 10 is set to 25.

**Describe alternatives you've considered**
Looked at different options, but it's not that.

**Comment by junedchhipa** [comment]
Sorry, this is difficult to achieve in a numeric/datetime x-axis.

**Comment by xxx44yyy** [comment]
> Sorry, this is difficult to achieve in a numeric/datetime x-axis.

What if it's not datetime?

**Comment by junedchhipa** [comment]
Sorry, I misunderstood your question.
I assumed you wanted columns in a datetime chart to be merged like the below category bar chart.

![Screen Shot 2019-07-06 at 4 29 12 PM](https://user-images.githubusercontent.com/17950663/60755288-340f1980-a00b-11e9-8981-555758038f94.png)


If not, please elaborate your question/provide a sketch of what you want to achieve.
