### ISSUE TITLE
toggleDataPointSelection not available in exec method

### ISSUE THREAD

**Issue by nemax23** [apexcharts/apexcharts.js#731]
Hi,

I just saw that toggleDataPointSelection is not managed in the exec method. Is this a bug? In the exec switch implementation toggleDataPointSelection is not taken into account so always returns undefined. 

The following code in React always returns undefined.

`ApexCharts.exec('mychart', 'toggleDataPointSelection', 0, 0);`

**Comment by junedchhipa** [comment]
Yes, this is a mistake. Thanks for pointing it out.
