### ISSUE TITLE
Mutliple Y axis scale error with brush

### ISSUE THREAD

**Issue by paulocbranco** [apexcharts/apexcharts.js#737]
## Codepen

https://codepen.io/paulocbranco/pen/ewjeoj

## Explanation

- What is the behavior you expect?
I expect the first Y axis has the correct scale.
- What is happening instead?
The first Y axis has the same scale as the second Y axis.
- What error message are you getting?
None.

**Comment by junedchhipa** [comment]
The option `chart.brush.autoScaleYaxis` doesn't work well with multiple y-axis chart.
Hence, I suggest turning it off.

```javascript
chart: {
    id: "brush",
    brush: { 
      target: "chart", 
      enabled: true, 
      autoScaleYaxis: false 
   }
}
```
