### ISSUE TITLE
Brush selection pane with erratic behavior

### ISSUE THREAD

**Issue by paulocbranco** [apexcharts/apexcharts.js#738]
## Codepen

https://codepen.io/paulocbranco/pen/pXZpmB

## Explanation

- What is the behavior you expect?
I expect the selection pane in the brush charts keeps always stable.
- What is happening instead?
When I start a new selection from right to left and then select it and slide to left the selection pane goes out of the brush chart and starts to have erratic behavior.
- What error message are you getting?
None.

**Comment by itshallrun** [comment]
I have the same issue, furthermore I have the issue that I can start the selection of the brush chart, outside of the chart. e.g. by clicking on the left yAxis. See the gif below for details:
![apexchart_bug](https://user-images.githubusercontent.com/21173275/70434719-42afa000-1a85-11ea-9edc-6c926eabe4be.gif)
