### ISSUE TITLE
Missing "updateSyncedCharts" in apexcharts.d.ts

### ISSUE THREAD

**Issue by bartguz** [apexcharts/apexcharts.js#739]
Hello,

Parameter **updateSyncedCharts** added in [336e8ac](https://github.com/apexcharts/apexcharts.js/commit/336e8ac9f41d72e1ad6aa6a7179ce1acb802161b#diff-b7806010c2dfdb9c34126d015ecad0c4) is missing in [apexcharts.d.ts](https://github.com/apexcharts/apexcharts.js/blob/master/types/apexcharts.d.ts), thus unusable.
It's even mentioned in [docs](https://apexcharts.com/docs/methods/#updateOptions).

Please, include this.

Cheers

**Comment by junedchhipa** [comment]
Thank you for reporting, fixed it :)
