### ISSUE TITLE
Series disappear when resizing

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#74]
Tested with Firefox and Brave Browser (chromium based) here's what happens.
Datas are not refresh but they are initially set by ajax request.
It's because of breakpoints, I've only set that : 
```
responsive: [{
          breakpoint: 600,
          options: {
            height: 300
          }
}],
```
See below : 
![issue_resize](https://user-images.githubusercontent.com/17592744/45081133-cd715480-b0f6-11e8-96b9-93b1e75fb046.gif)

**Comment by junedchhipa** [comment]
Ok, so on resize also the initial Series is not taken into account when responsive breakpoints are used.
Interesting! 
Thanks for reporting @arkhenstone 
This will be worked on along with #38

**Comment by junedchhipa** [comment]
This should also work properly now.
I have tested resizing after `updateSeries()`

If the issue persists, please provide me the exact series/options which you use to update
