### ISSUE TITLE
how can i fix apexcharts line chart fill the canvas with color 

### ISSUE THREAD

**Issue by bubuamu** [apexcharts/apexcharts.js#740]
![Screenshot from 2019-07-05 02-24-51](https://user-images.githubusercontent.com/4094489/60705202-cb3e7900-9f06-11e9-92b0-84b04cca0f7e.png)

**Comment by junedchhipa** [comment]
What do you want to achieve?
Can I see a working codepen?

**Comment by bubuamu** [comment]
This is the link of the js chart library i usesd.
https://apexcharts.com/javascript-chart-demos/line-charts/data-labels/

I am writing a code in node -red and for some reason it is not drawing correctly. i checked for css conflict but i don't find any.

**Comment by bubuamu** [comment]
The line char with more than two points in the serious will fills the entire graph and drow a shape instead of a line. I think you deal with this kind of bug previously. here is the link 
https://github.com/apexcharts/react-apexcharts/issues/34#issue-399994537

**Comment by bubuamu** [comment]
[
![Screenshot from 2019-07-07 14-08-09](https://user-images.githubusercontent.com/4094489/60772774-6730d600-a0fb-11e9-803a-1e911169b8b1.png)
](url)

**Comment by junedchhipa** [comment]
No, https://github.com/apexcharts/react-apexcharts/issues/34 is a different bug.
Please create a [codepen](https://codepen.io/) demo so I can see the code which you have tried.

**Comment by Miliks** [comment]
The issue have been resolved. It was the wrong configuration of node red theme in UI template settings. Thanks for your support.
