### ISSUE TITLE
Padding between bars 

### ISSUE THREAD

**Issue by jacksoncool** [apexcharts/apexcharts.js#745]
I'm working on a horizontal bar chart and wanted to know if you can control the padding between bars?  I haven't been able to find anything in the documentation.

**Comment by junedchhipa** [comment]
Yes, you can control the space between bars by adjusting
```javascript
options = {
  plotOptions: {
    bar: {
      barHeight: '80%'
    }
  }
}
```

Docs: https://apexcharts.com/docs/options/plotoptions/bar#barHeight

Note: If you want to do the same with column charts, you can adjust `columnWidth`

**Comment by jacksoncool** [comment]
Thanks! I tried that didn't get the results I was looking for. What about the width of the bar itself?

**Comment by junedchhipa** [comment]
You have put the `barHeight` prop at the wrong place.

```javascript
       plotOptions: {
            bar: {
                horizontal: true,
                barHeight: '50%'
            }, 
        }
```
