### ISSUE TITLE
labels on right side for horizontal bar chart 

### ISSUE THREAD

**Issue by jacksoncool** [apexcharts/apexcharts.js#746]
Question, 

Is it possible to create a data label on the right axis for each horizontal bar?

So the link below is for a tradition chart of reviews. The numbers on the left represent the rating. On the right, I want to show how many actual reviews there are for each star rating (eg. (10)). 

https://codepen.io/jacksoncool/pen/vqzvmN

**Comment by junedchhipa** [comment]
Sorry, multiple y-axes on a horizontal bar chart aren't supported.
Also, data-labels won't work for these, as you have centered position data-labels for the first series, so you can't have differently positioned data-labels for other series.
Maybe, using annotations can help
![Screen Shot 2019-07-09 at 12 53 43 AM](https://user-images.githubusercontent.com/17950663/60836766-0630fd00-a1e4-11e9-9796-2863ede54d0f.png)

[Codepen](https://codepen.io/apexcharts/pen/GbwEdP)

**Comment by jacksoncool** [comment]
Ok. Could this be a feature request?

**Comment by junedchhipa** [comment]
Possibly, but as it is a very corner case, I am not sure of implementing it into the core library :)

**Comment by dhimanvaishali** [comment]
dataLabels: {
                enabled: true,
                textAnchor: 'start',
                offsetX: "110%",
                formatter: function(val) {
                    return val.toFixed(0);
                },
                style: {
                    fontSize: '12px',
                    fontWeight: 'bold',
                    colors: ["#000"],
                }
  },
  
  set textAnchor to start and set offsetX to 100% will help you to render the lebel to the bar end.

**Comment by giacomo** [comment]
@dhimanvaishali your solution did not work for me
