### ISSUE TITLE
How do I have more than one stacked bars in one category?

### ISSUE THREAD

**Issue by onearth92** [apexcharts/apexcharts.js#749]
![ko32wujq](https://user-images.githubusercontent.com/42352670/60793907-42ce0b80-a186-11e9-9128-b06655ebd7f9.png)

I have lets say two categories: A, and B. They will be my X axis. Under each category I have two sets of data, namely Unique and NonUnique. Each Unique and NonUnique data sets will have Passed Failed count. 

A -> 
       Unique -> 
                        Pass - > 10
                        Failed -> 5
       NonUnique -> 
                        Pass - > 10
                        Failed -> 5

B
 -> 
       Unique -> 
                        Pass - > 10
                        Failed -> 5
       NonUnique -> 
                        Pass - > 10
                        Failed -> 5

I want to have a 100% stacked bar graph in which there will be two categories A and B along the X axis. Each category A, and B will have two 100% stacked bars for Passed and Failed value of Unique and NonUnique sub categories.

**Comment by junedchhipa** [comment]
Sorry, sub-categories in the x-axis are not yet supported.
