### ISSUE TITLE
Is it possible to change color of a column if x axis value matches a variable.

### ISSUE THREAD

**Issue by DMamak** [apexcharts/apexcharts.js#750]
I have a api call that loads in data to column chart, on x axis i have days of the past month (01/06/2019 ...30/06/2019) and y-axis has corresponding value of entries of the day.
i also have a variable with specific date "05/06/2019" , what i want to do is to set color of one column that x-axis value matches with that variable value to be red.That variable will also be updated with api call so if it changes then the first column should turn back to the original color and the new column that matches the date should be changed to red again. Is that possible ?  I'm using vue js with apexcharts

**Comment by junedchhipa** [comment]
I can provide a generic example in which color is set in the series itself.

```javascript
var data = [
  {
    x: "2011",
    y: 1292
  },
  {
    x: "2012",
    y: 4432
  },
  {
    x: "2013",
    y: 5423
  },
  {
    x: "2014",
    y: 6653
  },
  {
    x: "2015",
    y: 8133
  },
  {
    x: "2016",
    y: 7132
  },
  {
    x: "2017",
    y: 7332
  },
  {
    x: "2018",
    y: 6553
  }
];

data.forEach((d, i) => {
  if (d.x === "2015") {
    data[i].fillColor = "#CB2F31";
  }
});

var options = {
  series: [
    {
      data: data
    }
  ],
  chart: {
    height: 350,
    type: "bar"
  },
  plotOptions: {
    bar: {
      horizontal: false,
      columnWidth: "60%"
    }
  },
  stroke: {
    show: true,
    width: 2
  },
  dataLabels: {
    enabled: false
  },
  yaxis: {
    labels: {
      formatter: function(val) {
        return val / 1000 + "K $";
      }
    }
  },
  fill: {
    opacity: 1
  },
  xaxis: {
    type: "datetime"
  }
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();

window.setTimeout(() => {
  data.forEach((d, i) => {
    data[i].fillColor = undefined;
    if (d.x === "2017") {
      data[i].fillColor = "#CB2F31";
    }
  });

  chart.updateSeries([
    {
      data: data
    }
  ]);
}, 2000);

```
https://codepen.io/apexcharts/pen/povGKKo

Based on that, you can extend if for vue.js
