### ISSUE TITLE
Combined tooltips for stacked columns

### ISSUE THREAD

**Issue by AuspeXeu** [apexcharts/apexcharts.js#752]
Is there a plan to include an option to have the tooltip of a stacked column chart display all series values of the current hovered column/category?

**Comment by junedchhipa** [comment]
You can achieve it easily using custom tooltip formatter

```javascript
tooltip: {
  followCursor: true,
  shared: false,
  custom: function({ series, seriesIndex, dataPointIndex, w }) {
    let currentTotal = 0
    series.forEach((s) => {
      currentTotal += s[dataPointIndex]
    })
    return '<div class="custom-tooltip">' +
      '<span><b>Total: </b>' + currentTotal + '</span>' +
      '</div>'
  }
}
```

**Comment by Developeranees** [comment]
tooltip { 
   shared: true,
   intersect: false,
};

**Comment by Ungov77** [comment]
is it possible to display the combined total AND still display each individual series number? Just add the total under the existing tooltip

**Comment by adeel-usmani** [comment]
@junedchhipa brother is there anyway that I can return the function as react instead of inline html in above given code ??
