### ISSUE TITLE
Toolbar does not work in vue integration

### ISSUE THREAD

**Issue by AuspeXeu** [apexcharts/apexcharts.js#753]
## Codepen
https://codesandbox.io/s/vue-basic-example-6fe1v
## Explanation
I tried to enable the toolbar, however it does not seem to work in the vue integration. See codepen.

**Comment by arkhenstone** [comment]
It's just that toolbars are for datetime charts and not for categories. 

See examples in the docs for series in the link below, made in plain JS that also have tools only for datetime examples.

[https://apexcharts.com/docs/series/](
https://apexcharts.com/docs/series/)

**Comment by AuspeXeu** [comment]
Is there any way I could have these tools for categories charts? :)

**Comment by junedchhipa** [comment]
As zooming/panning are not possible with category charts, it doesn't make sense to include them in the toolbar.
Category charts' toolbar only has the download option.

**Comment by AuspeXeu** [comment]
I see. It would just be nice to be able to be a bit more selective on the categories. Let's say I have 10000 of them and then want to narrow it down to 100 in a particular range?

**Comment by arkhenstone** [comment]
If what you're trying to do is with dates like your example, just use a datetime charts.
If you're trying to get a categories filtered chart, then the zooming tool wouldn't be as useful as you think.
