### ISSUE TITLE
"Total" data label for stacked bar chart

### ISSUE THREAD

**Issue by MaxLeiter** [apexcharts/apexcharts.js#754]
I'd like to be able to show the total sum of a stacked bar chart as a label, like so (notice the 18. its wrong for the second bar but idea is the same)

<img width="547" alt="Screen Shot 2019-07-09 at 2 41 43 PM" src="https://user-images.githubusercontent.com/8675906/60925155-bd1a9080-a257-11e9-8000-b3d1f04fb0ef.png">

is this possible?

Thanks

**Comment by paulshatalov** [comment]
Possible workaround: maybe you can add one more item to stacked bar with white bg and just format it's value to be sum of all previous values

**Comment by junedchhipa** [comment]
@MaxLeiter  **Total** data-labels for stacked bar chart is in the roadmap.
Don't have an ETA for it though.

**Comment by yukinotech** [comment]
> Possible workaround: maybe you can add one more item to stacked bar with white bg and just format it's value to be sum of all previous values

that is impossible ,you will find last item to long , because last item is the value of total

**Comment by Indreed** [comment]
One can use point annotations as a workaround. I've prepared a demo here: 

https://codepen.io/indreed/pen/qBOxJmB

The downside is that the sum of series values are recalculated for each chart update (including resize).

**Comment by FirefoxMetzger** [comment]
It's not as perfect as getting out-of-box support, but another workaround is to use a custom formatter that computes the value on-the-fly:
https://codepen.io/FirefoxMetzger/pen/rNeVENz
(This is an edited version of the example)

Here I used the labels from the rightmost bar and disabled the rest (stylistic choice). If you need all the numbers, you could add another series that is constant 0.

**Comment by carlossantoswd** [comment]
> One can use point annotations as a workaround. I've prepared a demo here:
> 
> https://codepen.io/indreed/pen/qBOxJmB

Hi @Indreed  , thanks for sharing your demo. I've used your code to generate the annotations for one chart and worked very well!

But when it's necessary create more than one chart at the same page, the anotations turn a mess.

I'm not a JS programmer, but debuging the code, I could notice the error is in function `adjustPointAnnotationXCoord`, but I don't have knowledge to fix this.

Can u help me?

(using your demo, I created a demo of this issue: https://codepen.io/carlossantoswd/pen/PozBQGo)

**Comment by benhaynes** [comment]
This was stale because it was not worked on internally, not because it's not still a good feature. Can we re-open?

**Comment by sarahsga** [comment]
Can we please re-open this issue? This feature would be really helpful

**Comment by ksvLeo** [comment]
Bumping this up because this could be really useful

**Comment by slicedbread** [comment]
Agreed, those values are being tracked together for a reason so it'd be nice to see the total somewhere.

**Comment by Ungov77** [comment]
Still no news since 2019?

**Comment by Lukasiniho** [comment]
Any update? This feature would be greatly appreciated!

**Comment by Kszysiek** [comment]
Hey, any updates on how to use the total value? I've tried to find a way to add it based on the commit and find something in the built-in types and documentation but with no luck

**Comment by matheusjulio96** [comment]
have a look, guys: https://stackblitz.com/edit/apexcharts-aligns?file=src%2Fapp%2Fapp.component.ts @Kszysiek @MoteCL . Sorry for commenting in a closed issue, i just want to help

**Comment by MoteCL** [comment]
@matheusjulio96 thanks bro!

**Comment by adeel-usmani** [comment]
I am trying to display sum of the data points in tooltip of an stacked area chart. Is it a doable ? 
@matheusjulio96 sir, maybe you can help

**Comment by rephlexions** [comment]
@matheusjulio96 thanks for the solution. Had to update to version `"apexcharts": "^3.36.0"`
in order for this to work.

**Comment by mebaysan** [comment]
I downloaded the latest version of Apex Charts from the official website. It still doesn't work..

**Comment by lucasrachid** [comment]
> have a look, guys: https://stackblitz.com/edit/apexcharts-aligns?file=src%2Fapp%2Fapp.component.ts @Kszysiek @MoteCL . configure as chart: { type: 'bar', stacked: true, }, plotOptions: { bar: { dataLabels: { total: { enabled: true }, }, }, } Sorry for commenting in a closed issue, i just want to help

Tnx, it works
