### ISSUE TITLE
Multiple stacked bars per label

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#755]
Hi,

I have a situation where I need a chart like this:

![chart](https://user-images.githubusercontent.com/31082405/61012703-6df65d80-a334-11e9-80b2-f98485b5d7ce.png)

As you can see, I need multiple stacked bars for each label. I don't believe there's currently a way to do this or any workaround.

Are there any ways to achieve this in the current form?

Ideally, I'd be able to add multiple datapoints to each object in the series, so the series would looking something like:
      ` [ [{ name: 'series1', data: [{ x: 'label', y: 1, y2: 2}], 
      [{name: 'series2', data: [{x: 'label', y: 2, y2: 5}] ] `

**Comment by onearth92** [comment]
I have a similar situation. Would love to have a solution for this.

**Comment by ThinkSalat** [comment]
[Chart.js has this feature apparently](https://www.chartjs.org/samples/latest/charts/bar/stacked-group.html)
