### ISSUE TITLE
Is there a way to automatically wrap title and subtitle in multi-lines?

### ISSUE THREAD

**Issue by Webling** [apexcharts/apexcharts.js#756]
When titles or subtitles contain long paragraphs, they are cutted at the end of the line.
It would be great to wrap long paragraphs to have multi-line text.

I´ve tried to shorten the lines with \n, but that doesn´t work.

Any hint how I can make this work would be much appreciated.

Thanks.

**Comment by junedchhipa** [comment]
The `title` and `subtitle` are merely provided to quickly add headings to the charts.
They are not meant to be used as paragraphs.

SVG text doesn't allow multi-line text easily. Hence, I would suggest you use simple HTML elements to add title and subtitle for the chart.

**Comment by strekalin** [comment]
According source code:
`title : {
    text : ['title1', 'title line 2'],
},
subtitle : {
    text : ['subtitle1', 'subtitle line 2'],
},`

Working for me.

**Comment by Sany18** [comment]
I can provie react js implementation. I did not find an implementation, I made my own
```js
  ....
  const [ title, setTitle ] = useState<string[]>([]); // title to apexchart options
  const ref = useRef<any>();
 
  useEffect(() => {
    const title = `${clientId ? 'Client' : 'Your'} my looooong title which does not fit on one line`;
    const symbolWidth = 10; //px
    const paddingRight = 60; //px

    const e = () => {
      const chartWidth = ref.current.chartRef.current.getBoundingClientRect().width - paddingRight;
      const rows = Math.ceil(chartWidth / title.length * symbolWidth);
      const newTitle: string[] = [];
      const symbolQuantity = Math.floor(chartWidth / symbolWidth);

      for (let i = 0; i < rows; i++) {
        newTitle.push(title.substr(symbolQuantity * i, symbolQaontity)); 
      }

      setTitle(newTitle);
    };

    window.addEventListener('resize', () => e());

    e();

    return window.removeEventListener('resize', () => e());
  }, []);
  
  ...
  
  <Chart
              ref={ref}
              width='100%'
              height='100%'... />
  ```
