### ISSUE TITLE
dataLabels background customization

### ISSUE THREAD

**Issue by Amber-Williams** [apexcharts/apexcharts.js#758]
The dataLabels as is extremely rigid and not readable with multiple line series and importantly cuts off values. ( see image first and last values on the graph are cut)

If you could add a background option that overlaid on top of the line this would help immensely until there is more flexibility for styling. 

I've also tried to over write the stylings but it doesn't seem to accept anything outside of things like font-size due to how to SVG text is generated. Ideally it would be great to be able to overwrite stylings of the data labels to add customisation.

**Comment by Amber-Williams** [comment]
<img width="667" alt="Screenshot 2019-07-11 at 14 08 17" src="https://user-images.githubusercontent.com/27780374/61078045-5dea8680-a3e5-11e9-8bfd-f2448f7f22ae.png">

**Comment by junedchhipa** [comment]
The dataLabels would need an additional `rect` element to be drawn behind the text to customize the background styles. Maybe that can be tagged as an enhancement.

But, the cropping of the data-labels seems to provide an incorrect representation, hence I have tagged as a bug. I will provide a fix for it soon.

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/9c6197822e26662a2277e073e5f8f3e2b01aebe1 fixes the cropped data-label issue.
