### ISSUE TITLE
y-axis forceNiceScale only works when the range is larger than 10

### ISSUE THREAD

**Issue by timoly** [apexcharts/apexcharts.js#759]
forceNiceScale option, https://apexcharts.com/docs/options/yaxis/#forceNiceScale works fine when the range between min/max value is larger than 10, as can be seen in this codepen example:
https://codepen.io/anon/pen/agxvxO

But when the difference is less than 10, the value rounding is not working as can be seen here:
https://codepen.io/anon/pen/gNyaPw

**Comment by junedchhipa** [comment]
Closing this as it is fixed in this [commit](https://github.com/nadvornik/apexcharts.js/commit/f9c86d5ad59d5eea081f21912ce17339ab5d40b1)

Now, forceNiceScale works for range > 2.

**Comment by AwesomeZaidi** [comment]
What about below 2? This is NEEDED.

**Comment by jaypinho** [comment]
I have the same issue with sub-2 ranges.

**Comment by samssann** [comment]
Same here. It's impossible to get nice scales for percentage figures

**Comment by efolio** [comment]
Up on this.
With percentages, if there are values equal to 100%, yaxis displays 108, which makes no sense when max is set on 100…

**Comment by msm1227** [comment]
any update on this? currently seeing the issue when the number is 2 or less 
![image](https://github.com/user-attachments/assets/096555b7-d4f5-4748-9f11-eb6e73a6e63c)
