### ISSUE TITLE
Bug using Mozilla Firefox hover function not working and charts are not well displayed.

### ISSUE THREAD

**Issue by adrien2612** [apexcharts/apexcharts.js#760]
## Codepen

Link to the [Codepen](https://codepen.io/adrien2612/pen/jjogoo)

## Explanation

Functionalities like the change of the chart opacity don't work on Firefox. There are also display problems the quality of the chart is worst on Firefox than chrome.

**Comment by adrien2612** [comment]
Functionalities like the change of the chart opacity don't work on Firefox. There are also display problems the quality of the chart is worst on firefox than chrome.

**Comment by vkh98** [comment]
By adding "dataPointMouseEnter" , "dataPointMouseLeave" to options>chart>events fill-opacity of every  series path is adjustable :
chart: {
        width: 380,
        type: 'pie',
        **events: {
            dataPointMouseEnter: function (a, b) {
                document.getElementById(a.target.instance.node.id).setAttribute('fill-opacity', '0.2')
            },
            dataPointMouseLeave: function (a, b) {
                document.getElementById(a.target.instance.node.id).setAttribute('fill-opacity', '1')
            }
        }**
    },
