### ISSUE TITLE
Missing colors in legend when printing the page

### ISSUE THREAD

**Issue by darkoromanov** [apexcharts/apexcharts.js#761]
## Codepen

https://codepen.io/apexcharts/pen/bxzgZJ

## Explanation

- What is the behavior you expect?

We should see colors in legend when we print the page

- What is happening instead?

Colors in legend are not shown

- What error message are you getting?

<img width="875" alt="Screenshot 2019-07-12 at 14 46 28" src="https://user-images.githubusercontent.com/711784/61129560-f3088080-a4b4-11e9-966f-8f7d840b9d0a.png">

**Comment by darkoromanov** [comment]
Ok, it's a simple issue caused by printers not printing background colors by default. I "fixed" by adding this CSS rule:

`@media print {
  .apexcharts-legend-marker:before {
    content: "\25A0";
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    line-height: 12px;
    font-size: 24px;
  }
}`

I think it would be correct to use another way to show colors in legend. I'll try to find time to send a pull request.

**Comment by junedchhipa** [comment]
The legend is drawn with HTML elements. And the div is applied a background color.
I don't have an alternative to draw the legend points using any other method. If you have any suggestions, a PR is welcome :)

**Comment by darkoromanov** [comment]
The only workaround is currently the one I posted:

```
@media print {
  .apexcharts-legend-marker:before {
    content: "\25A0";
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    line-height: 12px;
    font-size: 24px;
  }
}
```

I don't know if it's the best solution but it works perfectly and no doubt it's much better than nothing.

**Comment by LewisCarthy** [comment]
The issue is with using "background: [color],"

Instead, use "background-colour: [color]" and it'll fix it (See below).

![print-test](https://user-images.githubusercontent.com/7261897/67495514-efb79000-f672-11e9-88f2-a553bf24c85d.jpg)

**Comment by RollingStone85** [comment]
Apologies, it's actually the "!important" that's making it work for print. 

In Legend.js, I replaced 

mStyle.background = fillcolor[i];      ---->

elMarker.style.setProperty('background', fillcolor[i], 'important');

Although, this only works in Google Chrome.

**Comment by pierre-alain-b** [comment]
@RollingStone85 did work in Firefox 80, thank you! I think this solution shall be elected for implementation in the code maybe.

**Comment by djak250** [comment]
For anyone else who gets here because it still disappears in some cases, Chrome has background colors disabled by default these days.
Adding this seems to fix it. 
```css
@media print {
  .apexcharts-legend-marker {
    -webkit-print-color-adjust: exact;
  }
}
```
It might be worth setting that in the library though @pierre-alain-b

**Comment by carbogninalberto** [comment]
> The only workaround is currently the one I posted:
> 
> ```
> @media print {
>   .apexcharts-legend-marker:before {
>     content: "\25A0";
>     position: absolute;
>     top: 0;
>     left: 0;
>     display: block;
>     line-height: 12px;
>     font-size: 24px;
>   }
> }
> ```
> 
> I don't know if it's the best solution but it works perfectly and no doubt it's much better than nothing.

Cool! I just edited this idea to get closer to the original bullet point.

```css
// inside @media print
.apexcharts-legend-marker:before {
  content: "\25CF";
  position: absolute;
  top: 0;
  left: 0;
  display: block;
}
 .apexcharts-legend-marker {
  padding-right: 1rem;
  border-radius: 0.55rem;
}
```
