### ISSUE TITLE
Allow zoom on Timeline (Range Bar)

### ISSUE THREAD

**Issue by LonnyX** [apexcharts/apexcharts.js#763]
**Is your feature request related to a problem? Please describe.**
For timeline that cover a large periods (ex 2017 - 2020), it would be very nice to have the possibility to zoom, just like on area

**Describe the solution you'd like**
As the zoom is already implemented, maybe not a lot of works to port it to RangeBar (Timeline)

**Additional context**
did anyone ever need this feature?

**Comment by geferon** [comment]
So, this happening anytime soon? This is a feature I require.

**Comment by Kilou1709** [comment]
Same question here !

**Comment by pashapanther** [comment]
Same question, is there a timeline for when this feature would be added?

**Comment by Splaxi** [comment]
@junedchhipa 

Would a sponsorship or bounty award like payment be an option to give this feature request some attention?

**Comment by junedchhipa** [comment]
Released v3.23.0 which includes this feature
