### ISSUE TITLE
Synched Charts Updating Data

### ISSUE THREAD

**Issue by vhphan** [apexcharts/apexcharts.js#764]
Hi

https://codepen.io/vhphan/pen/MMddve

I am trying to update the synchronous charts with new data.

However anytime I update one of the charts, all of the charts are updated with the same data.

In the codepen, I just modified the code from the documentation for synchronous charts.

Is there anything I am missing?

**Comment by kevinehosford** [comment]
I think I'm seeing the same issue. Eventually multiple charts render the same data for me, too.

**Comment by kevinehosford** [comment]
It looks like there are additional args that can be specified. By passing in `updateSyncedCharts: false` you can achieve the desired behavior:

https://github.com/apexcharts/apexcharts.js/blob/4d0cad839caa579a88d5b03ca1aef678f295930a/src/apexcharts.js#L409
