### ISSUE TITLE
Provide build without Polyfills?

### ISSUE THREAD

**Issue by hc-codersatlas** [apexcharts/apexcharts.js#766]
I understand the bundle size issue was discussed and closed, but would be good for a build without the IE11? polyfills for those that use vue-cli or other build tools that include core-js and can specify polyfills (or users that don't need IE11 support).

**Comment by junedchhipa** [comment]
You're correct.
The plan is to release the default build without polyfills. And in the README, users who need IE11 support will need to include the polyfills themselves.
We can save another 10-15 kB in the minified build this way.

**Comment by mestaritonttu** [comment]
Looks like this is solved by release 3.12.0

**Comment by junedchhipa** [comment]
Yes, in 3.12.0, the bundled size is 425 kB while the bundled size in 3.11.3 was around 448 kB.
So, a good improvement in terms of bundle size is achieved.
