### ISSUE TITLE
I need gauge chart with following options.

### ISSUE THREAD

**Issue by kinjalgodavale** [apexcharts/apexcharts.js#771]
- Increase / decrease round buttons 
- Markable options (0, 25, 50...)
- Min / Max Data Labels

**Note : I attached the image of gauge chart that I want to make.**

![guage chart](https://user-images.githubusercontent.com/53047704/61460706-ebe9e280-a98c-11e9-9569-ec7b147ecc22.png)

Thanking you.

**Comment by junedchhipa** [comment]
Sorry, this is not achievable with ApexCharts.
You might need a plugin specifically to create gauges. ApexCharts provides a basic gauge/circle chart without complex customizations.
