### ISSUE TITLE
Ticks in y axis are in consistent in nature, some times they are float and some other times they are whole numbers

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#773]
## Codepen

Modify [this codepen](https://codepen.io/vjakair/pen/bXNwqV) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behavior you expect?
The tick values on y axis should either be whole number or floats
- What is happening instead?
based on the input values, the ticks are either decimal or number
- What error message are you getting?
No error message

Is there a way to configure only decimal values for certain type of charts ?

FYR:
![image](https://user-images.githubusercontent.com/8254178/61513047-70824280-aa19-11e9-8106-0b600bf70e7c.png)

![image](https://user-images.githubusercontent.com/8254178/61513071-898af380-aa19-11e9-99eb-7f5d5c08b96b.png)

**Comment by junedchhipa** [comment]
For small range y-axis (for eg. 1 to 5), the numbers get converted into decimals to avoid repetition.
If you set tickAmount to 8 and you print whole numbers for a range of 1-to-5, you will get repeated numbers. Hence, to avoid it, the small range adds a decimal.

For a larger range, the problem of repeated numbers doesn't happen. Hence, the y-axis is always in whole numbers there.

To override this default behavior, you can always change yaxis.labels.formatter

```
  yaxis: {
    labels: {
      formatter: function(val, index) {
        return val.toFixed(0);
      }
    }
  }
```

Docs: https://apexcharts.com/docs/options/yaxis#formatter
