### ISSUE TITLE
"smooth" curves are not worked in radar multi series chart

### ISSUE THREAD

**Issue by kinjalgodavale** [apexcharts/apexcharts.js#774]
Is it possible to convert "polygon" shape into "circle" shape for radar multi series chart and if yes then how can I implement it in my chart ?
and I need small red dots to data labels (e.g. one, two, three, ....). 

I attached the image : the right side image shows the actual chart that I have made and left side image shows that I want to implement to my chart.

Thanking You.
![radar chart](https://user-images.githubusercontent.com/53047704/61516942-b0e6be00-aa23-11e9-979d-025c022ae58c.png)

**Comment by kinjalgodavale** [comment]
Anyone? I'm stuck in to this. Not sure if its possible or not..

**Comment by junedchhipa** [comment]
Smooth curves don't work with the radar chart currently. 
Marking this as "future enhancement" to work on it later.

**Comment by HeliumAce** [comment]
Hello, just curious if there has been any progress on this feature request. Have the same need as the original poster for a curved path radar chart. Thanks!

**Comment by Phantomo** [comment]
Hi from 2021, any updates about bezier style lines or curves?

**Comment by SyedKabeerAhmed** [comment]
is any body got to make the above chart example

**Comment by achoimet** [comment]
@kinjalgodavale Hello, just for my information, how did you display the total amount on the center of the image? do you mind share this option ? maybe with a custom tooltip ?

**Comment by tomtx** [comment]
I think your best option is to go with chart.js, circles instead of polygons work there (there are lot more options in general), not sure why this has not been picked up by apexcharts team in the past 3 years

**Comment by brihol** [comment]
To add to the conversation, I played around with Chart.js but I actually found Apex better for what I wanted to achieve. However, with that said, I'm wondering how the red dots near the labels were added. Something I missed in the documentation?

**Comment by Kutlwiwiso** [comment]
Anyone know if the above feature (smooth radar chart) has been implemented yet ?
