### ISSUE TITLE
XAxis annotation range doesn't work with zoom

### ISSUE THREAD

**Issue by sebastianbassenblg** [apexcharts/apexcharts.js#776]
Currently when I'm using an XAxisAnnotation with x: date and x2: date the annotations diappears when zooming.

Example: https://codepen.io/anon/pen/rXapWw

Try to zoom anywhere inside or at the end of the "X Axis Anno Vertical" annotation.

**Comment by junedchhipa** [comment]
Yeah, it's a known issue.
Continued on #917
