### ISSUE TITLE
Different stroke color for different value in Line chart

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#777]
Is there any way to change stroke **color** for different value in the line chart. I read the docs but did not find anything related to this. 

I am wanting something like this. this bar chart is created using amcharts. And I wanted this for line chart.
![DeepinScreenshot_select-area_20190721195757](https://user-images.githubusercontent.com/28239287/61592249-af1f2500-abf2-11e9-80f4-c0605d6d68ba.png)

**Comment by junedchhipa** [comment]
Sorry, this is not possible yet.
May come in the future.
