### ISSUE TITLE
I want heat map chart with legend and spacing between two y-axis rows

### ISSUE THREAD

**Issue by kinjalgodavale** [apexcharts/apexcharts.js#778]
![heatmap](https://user-images.githubusercontent.com/53047704/61617624-b0029600-ac88-11e9-8248-33fe3b0a8813.png)
****Here is my Code for Heat Map Chart :-**** 

function generateData(count, yrange) {
    var i = 0,
      series = [];
    while (i < count) {
      var x = 'w' + (i + 1).toString(),
        y = Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min;

      series.push({
        x: x,
        y: y
      });
      i++;
    }
    return series;
  }
  var heatChartOptions = {
    chart: {
      height: 220,
      type: 'heatmap',
      toolbar: {
        show: false
      }
    },
    dataLabels: {
      enabled: false
    },
    colors: [$primary],
    series: [{
      name: 'Day 1',
      data: generateData(24, {
        min: 60,
        max: 90
      })
    },
    {
      name: 'Day 2',
      data: generateData(24, {
        min: 40,
        max: 90
      })
    },
    {
      name: 'Day 3',
      data: generateData(24, {
        min: 30,
        max: 90
      })
    },
    {
      name: 'Day 4',
      data: generateData(24, {
        min: 30,
        max: 90
      })
    },
    {
      name: 'Day 5',
      data: generateData(24, {
        min: 50,
        max: 90
      })
    },
    {
      name: 'Day 6',
      data: generateData(24, {
        min: 45,
        max: 90
      })
    }],
    xaxis: {
      labels: {
          show: false
      },
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
  }
  var heatChart = new ApexCharts(
    document.querySelector("#sales-heatmap-chart"),
    heatChartOptions);
  heatChart.render();

Thanking You,

**Comment by junedchhipa** [comment]
Sorry, such customization is not achievable with ApexCharts.
