### ISSUE TITLE
Cannot display only whole integers on y axis for small values

### ISSUE THREAD

**Issue by drummad** [apexcharts/apexcharts.js#779]
## Codepen

https://codepen.io/Drummad/pen/Oewyrb

## Explanation

For the data in this chart I would expect to see the values on the y-axis be 0, 1, 2, 3. Instead, the y-axis is made up of quite odd decimal divisions. In our use case the data will always consist of whole integers so the decimal divisions do not make logical sense to our users.

I have tried adding the forceNiceScale on the y-axis but this appears to have no effect. Am I missing a trick here or is this a bug?

**Comment by junedchhipa** [comment]
No, it's not a bug but default behavior.
If the yaxis range is small (in your case 1 to 3), and tickAmount is greater than this range (default tickAmount is 6), then decimals will appear in the y-axis.

To avoid this behavior, you can decrease the `tickAmount` and format the labels using the `formatter` function.

```javascript
  yaxis: {
    tickAmount: 3,
    labels: {
      formatter: function(val) {
        return val.toFixed(0)
      }
    },
  }
```
