### ISSUE TITLE
[Angular] ERROR TypeError: r.default.extend is not a function

### ISSUE THREAD

**Issue by e4r** [apexcharts/apexcharts.js#78]
Hey guys, I've been working with ApexCharts (which I find incredibly well done) since a bit ago, but when I decided to include this library in my angular project everything works pretty fine until I build the project with the optimisation flag.

I've read here and there ([e.g.](https://github.com/angular/angular-cli/issues/10658)) that the building process is sometimes buggy.

In my case, when I run the application, at runtime I receive this error

<img width="803" alt="schermata 2018-09-06 alle 10 23 42" src="https://user-images.githubusercontent.com/814002/45144748-489e3d80-b1bf-11e8-9412-63fcca442761.png">

which is fired exactly when I try to instantiate a new ApexCharts object
`const chart = new ApexCharts(this.myPieChart.nativeElement, options);`

the block causing this error is this one

`{
                key: "init",
                value: function(t) {
                    var e = this.globalVars();
                    return e.initialConfig = n.default.extend({}, t),
                    e.initialSeries = JSON.parse(JSON.stringify(e.initialConfig.series)),
                    e
                }
            }]),`

Do you have any idea about what could possibly cause this problem?

**Comment by hpoul** [comment]
I had the same error, only way i found to work around it yet, was to disable the `buildOptimizer` for production environment in `angular.json`. I guess it has something to do with uglify js? unfortunately the whole angular build process is still a bit a mystery to me though..  (it also increased my minified JS files by 8%, so it's not really the best solution..)

**Comment by e4r** [comment]
That's right, if I build either without the flag `buildOptimizer` it works but it's not an option since the resulting files are way bigger for me (7MB vs 1.8MB).

I am regretfully using another library until an Angular wrapper/Typescript typings will be out ( check #24 )

**Comment by junedchhipa** [comment]
Would be interested to know if the error still occurs after the typings are provided.
