### ISSUE TITLE
Trimmed first label in graph with no y labels and datetime on x axis

### ISSUE THREAD

**Issue by lukasleitsch** [apexcharts/apexcharts.js#780]
## Codepen
https://codepen.io/lukasleitsch/pen/OKyxvN

## Explanation

- The first label for the x axis is trimmed if the y labels are hidden
- The first label should be skipped and the x axis labels starts with the second datetime

**Comment by junedchhipa** [comment]
Fixed in this commit - https://github.com/apexcharts/apexcharts.js/commit/1439c32607d98de80e58657126553aea7276b14e
