### ISSUE TITLE
Misleading information into the documentation (for Vue users)

### ISSUE THREAD

**Issue by funderbenz** [apexcharts/apexcharts.js#781]
Hello, 

I just want to point out that while reading the documentation related to the "donut" chart, I had problems figuring out how to setup the chart labels.

By reading the documentation, it looks like labels and series are at the same level, into the options object, while is not like that. 

By looking at a code example, I've figured out that the labels are belonging to the options object, while series are meant to be set outside the options object. 

Probably I've faced this because **I'm working with the Vue version**, and other people who are using the normal version are not reading the docs this way. In fact with vue you have to define the series array, separately, and give it a reference into the component tag.

[You can see here the part of the documentation here ](https://ibb.co/fFfMSnT)

Just put a note maybe: "If you are using Vue, define the labels into the chart options and the series values separately" ... just to save that 30 minutes figuring out what's wrong :)

Thanks! :)

**Comment by junedchhipa** [comment]
@funderbenz Sorry for the confusion. I agree that it is misleading for vue/react users.
Updated the docs - https://apexcharts.com/docs/chart-types/pie-donut/

Thanks for pointing it out!
