### ISSUE TITLE
Datetime series with bar chart type visualization is misleading

### ISSUE THREAD

**Issue by xumix** [apexcharts/apexcharts.js#784]
## Codepen
https://codesandbox.io/s/react-basic-example-qq7sp
![image](https://user-images.githubusercontent.com/250118/61702980-5b731f80-ad49-11e9-9e9f-60057d9e9eb0.png)
![image](https://user-images.githubusercontent.com/250118/61703037-6d54c280-ad49-11e9-9629-1a145547b2b2.png)

## Explanation
I expect the bar with the date '2019-03-31T00:00:00' to be positioned above 'Mar19', "2019-04-30T00:00:00" above 'Apr 19' etc.

- What is happening instead?
'2019-03-31T00:00:00' is positioned above 'Apr 19', "2019-04-30T00:00:00" above 'May19'
- What error message are you getting?
No errors are shown.

Is there any way to position the bars according to the month of the date?

**Comment by mysilkworld** [comment]
very interesting too

**Comment by junedchhipa** [comment]
The x-axis ticks generation is done in such a way that the 1st day of the month is shown instead of the value of the data point.

To override this behavior, you can use a lightweight datetime library such as dayjs and use `labels.formatter`

```javascript
xaxis: {
  type: "datetime",
  labels: {
    formatter: function(val) {
      ...
    }
  }
}
```
