### ISSUE TITLE
Datetime xaxis label is showing incorrect value

### ISSUE THREAD

**Issue by AlexanderArvidsson** [apexcharts/apexcharts.js#785]
## Codepen
https://codepen.io/anon/pen/KOVQVz

## Explanation
I am having an issue with the datetime xaxis. When my points are in a monthly interval, always on the 1st of a month, the xaxis will say the "18th" or "19th" on the points rather than the 1st.
This is weird because if you hover the point, the cursor will show the correct label on the xaxis but the label that shows when you're not hovering is completely different.
![image](https://user-images.githubusercontent.com/2972103/61708055-26b49780-ad4c-11e9-88f0-eb8de445eff7.png)
![image](https://user-images.githubusercontent.com/2972103/61708068-2ddba580-ad4c-11e9-8902-1c85a48c9c62.png)

Is there any way to get these to show the correct x values?
In my actual app that has the chart in it, the grid is aligned with all my datapoints, and every single one of them is showing as "18th", when they actually are on the 1st.
![image](https://user-images.githubusercontent.com/2972103/61708235-a04c8580-ad4c-11e9-8b17-48f4face63de.png)

**Comment by junedchhipa** [comment]
The '18 and '19 are the years of the date.
If you want to change the format to show day and month, you can do
```javascript
xaxis: {
  labels: {
    format: 'dd MMM'
  }
}
```

**Comment by AlexanderArvidsson** [comment]
@junedchhipa Oh wow, now I feel pretty damn dumb for not thinking of that. 😑
Thanks man!
