### ISSUE TITLE
Add image annotation feature

### ISSUE THREAD

**Issue by llagundimao** [apexcharts/apexcharts.js#789]
**Is your feature request related to a problem? Please describe.**
ApexCharts only supports text annotation. In my case I would like to add an image which can also clickable, hoverable, etc.

**Comment by drewtownchi** [comment]
Some use-case justification for this feature request: We have line charts that track people and companies over time.  Being able to put a face or logo as an annotation on the last entry of a line chart provides users an easy way to distinguish the separate lines without having to rely on the key.

**Comment by dfiorini** [comment]
Hi, how you can resolve it, I want to add an image too
