### ISSUE TITLE
Legend text color

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#79]
Hello,

in doc, there's an options.legend.style.useSeriesColors property but when text node is created in Legend.js options.legend.useSeriesColors property is checked instead.

**Comment by junedchhipa** [comment]
Thanks for pointing out @pnemi 
The docs were inconsistent with the options. 

The correct way has to be
```javascript
legend: {
  labels: {
    colors: undefined,
    useSeriesColors: false
  },
}
```

Updated the docs on the website as well.
[legend config](https://apexcharts.com/docs/options/legend/)

**Comment by junedchhipa** [comment]
Fixed in https://github.com/apexcharts/apexcharts.js/commit/07d5f135450abfb23f7d5c0a5e2cfe1c0f4c47ce

**Comment by pnemi** [comment]
It's not just docs. Take a look at Legend.js.

<img width="956" alt="screen shot 2018-09-06 at 14 02 08" src="https://user-images.githubusercontent.com/5919903/45156108-7db98880-b1dd-11e8-9e81-14b28410163e.png">

**Comment by junedchhipa** [comment]
As said,
this is fixed in https://github.com/apexcharts/apexcharts.js/commit/07d5f135450abfb23f7d5c0a5e2cfe1c0f4c47ce

![screen shot 2018-09-06 at 6 06 18 pm](https://user-images.githubusercontent.com/17950663/45157738-9d61a880-b1ff-11e8-8ffb-b7e55032cba2.png)

**Comment by junedchhipa** [comment]
The change will be reflected in the next patch release :)

**Comment by cosmicknox** [comment]
`series={[5,20,40,35]} 
            options={{
                dataLabels: {
                    
                    style: {
                        fontSize: "14px",
                        fontFamily: "Helvetica, Arial, sans-serif",
                        fontWeight: "bold",
                        colors: ["#FF9900"],
                        
                    },
                  },
                  legend: {
                    show: true,
                    labels: {
                      colors: "white",  // TEXT COLOR CAN BE CHANGED HERE
                      useSeriesColors: false
                  },
                  },
                  labels:['AirDrop','Circulation Supply','Locked Supply','Team/Developement'
                    ]
            }}       `
