### ISSUE TITLE
Annotations accept series of data

### ISSUE THREAD

**Issue by Ulgerd** [apexcharts/apexcharts.js#791]
**Is your feature request related to a problem? Please describe.**
At the moment, annotations can only be drawn as a square https://codepen.io/Ulgerd/pen/rXeGKz 
But it would be great if annotations could work with series of data.

**Describe the solution you'd like**
I suppose it could looks like that: https://codepen.io/Ulgerd/pen/JgGwME

**Describe alternatives you've considered**
As alternative solution I assume making `tickPlacement: 'between'` working for the mixed charts with bars, if the first and the last bars are `null`.

**Comment by junedchhipa** [comment]
Sorry, that is difficult to achieve and outside the scope of this project.
Maybe "Range Area Charts" is the functionality you're looking for (which will be implemented in future).
