### ISSUE TITLE
Donut Chart - Labels are not shown as default

### ISSUE THREAD

**Issue by kinjalgodavale** [apexcharts/apexcharts.js#792]
## Codepen

https://codepen.io/anon/pen/bXpoaG

## Explanation

- I want to show Label in center as default (like : "total" attribute), instead of hover on series
- In Line Chart, I want markers icons with drop shadow.
- In Donut Chart, can be any series active as default ?

I have attached an image of donut chart, line chart, 
![apex charts](https://user-images.githubusercontent.com/53047704/61777995-93e32e00-ae1b-11e9-8ca1-83f9716ecf69.png)
those I want to make.

Thanking You

**Comment by junedchhipa** [comment]
a) Showing a total label by default can be achieved by
```
plotOptions: {
  pie: {
    donut: {
      labels: {
        show: true,
        name: {
          show: true,
          fontSize: '22px',
          fontFamily: 'Rubik',
          color: '#dfsda',
          offsetY: -10
        },
        value: {
          show: true,
          fontSize: '16px',
          fontFamily: 'Helvetica, Arial, sans-serif',
          color: undefined,
          offsetY: 16,
          formatter: function (val) {
            return val
          }
        },
        total: {
          show: true,
          label: 'Total',
          color: '#373d3f',
          formatter: function (w) {
            return w.globals.seriesTotals.reduce((a, b) => {
              return a + b
            }, 0)
          }
        }
      }
    }
  }
}
```
Codepen - https://codepen.io/apexcharts/pen/XvdqPm

b)Markers drop-shadow is not available currently, may come in future.

c) I will create a demo on how to achieve this with `toggleSeries()` method. There is a bug which needs to be fixed before this.

**Comment by kinjalgodavale** [comment]
'Total Label' is working fine in my charts.

Thanks.
