### ISSUE TITLE
'firstElementChild' bug with pie/donut charts

### ISSUE THREAD

**Issue by Ulgerd** [apexcharts/apexcharts.js#793]
When I change line chart/bar chart to pie/donut chart (with totally different data/series!) lag occured, an this bugreport could be found in the console log:
https://drive.google.com/open?id=1XQ-HiSXZakK62ojLsGsBj2Ev_j2uL4Da

I don't really know what to put in codepen, because I used demo charts. 
I'm usung react btw.

Thanks.

**Comment by junedchhipa** [comment]
Line/Bar charts cannot be updated to pie/donut charts as they have different data formats. As there is no morphing of line/bar to pie/donut, it is better to create different elements for different chart types.
