### ISSUE TITLE
Click on legend causes problem in Brush chart

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#795]
When I click on one legend it causes a problem in my chart if I scroll brush chart. My chart becomes smaller and smaller and finally gone. I did not use any legend configuration. it's using the default configuration. I have no idea how to resolve this.

made a gif for better understanding.

![deepin-screen-recorder_Select area_20190724184845](https://user-images.githubusercontent.com/28239287/61796268-dcfca780-ae46-11e9-9229-4ba5e8e52ddf.gif)

**Comment by junedchhipa** [comment]
This is surely a bug, and I have tagged it.
For now, you can turn off autoScaling on brush by

```javascript
options = {
  chart: {
    brush: {
      autoScaleYaxis: false
    }
  }
}
```

**Comment by Sumon-miazi** [comment]
zoom in y and xy is not working in 3.8.4v. @junedchhipa 
```
zoom: {
       enabled: true,
       type: 'y',  
},
```

![deepin-screen-recorder_Select area_20190806172733](https://user-images.githubusercontent.com/28239287/62536388-b475a400-b86f-11e9-909e-d974361f2259.gif)
