### ISSUE TITLE
hoizontal bars with 'datetime' type

### ISSUE THREAD

**Issue by Ulgerd** [apexcharts/apexcharts.js#796]
- What is the behavior you expect?
1) correct date(not in milliseconds) 
2) correct size of bars(currently neither 'columnWidth' nor 'barHeight' works correctly
3) correct positioning of bars after click on the legend, now it's half a bar higher than it should be
4) correct number of labels on y axis (5 instead of 7 now)

If 'horizontal' changes to 'false' everything works just fine.

Codepen: https://codepen.io/Ulgerd/pen/KOzJNw

Thanks!

**Comment by junedchhipa** [comment]
Sorry, horizontal bars with datetime x-axis are not supported.
You may look into [Timeline Bar Charts](https://apexcharts.com/javascript-chart-demos/timeline-charts/) though.

**Comment by charliearaya** [comment]
Why is this not supported?
