### ISSUE TITLE
How to Export Chart as Image using external button.

### ISSUE THREAD

**Issue by anilreddy128** [apexcharts/apexcharts.js#797]
I created a dashboard with multiple apex charts controls on it. I need to give users a feature to export whole page as image. Right now, i see an option to download individual component only. But How can I call this function from outside click event to export chart as image (svg or png).

**Comment by georgehardy** [comment]
I do this using the global Apex object dataURI method:
https://apexcharts.com/docs/methods/#dataURI

This will give you a base64 enocded PNG - not sure if you can get the SVG this way.

Example function:
```
const saveToArchive = async (chartId) => {
  const chartInstance = window.Apex._chartInstances.find(chart => chart.id === chartId);
  const base64 = await chartInstance.chart.dataURI();
  return base64;
}
```

**Comment by prasad1791** [comment]
@georgehardy  dateURI( ) method always returns PNG image , but what about SVG images , any idea ?

**Comment by georgehardy** [comment]
@prasad1791 
You can do this using https://apexcharts.com/docs/methods/#paper
```
const paper = chartInstance.chart.paper()
const svg = paper.svg()
```

**Comment by junedchhipa** [comment]
@georgehardy Yes, that's the correct way of getting SVG string.

**Comment by prasad1791** [comment]
Yes I already implemented that in my current project thanks @georgehardy and @junedchhipa

**Comment by rujaraju** [comment]
Hi, I tried calling paper() but the result was undefined, am I doing it in the wrong place or is the method not there anymore? I would need the svg from the chart.

var chart1 = new ApexCharts(document.querySelector("#chart1"), options1);
console.log(chart1.paper())

**Comment by j-a-h-i-r** [comment]
Adding to what @rujaraju already said above, this link (https://apexcharts.com/docs/methods/#paper) does not contain any mention of the `paper` method. Moreover, when I searched for `paper` using the search function, it did not return any result. So, I guess the method is not working anymore.

**Comment by tdallagnol** [comment]
Hi

I looked at the Apex Charts source code and found a way to get the SVG.
It is not something that looks really OK, as this can change, but you can always adapt.

As the javascript is not so restrictive in messing up with internal data from the objects, I'm obtaining the svg by reading the data from:

`myChartInstance.chart.w.globals.base.dom.Paper.svg()`

**Comment by kishan93** [comment]
thank you @georgehardy @tdallagnol

I was able to get svg using the following on apexcharts  version `3.32.0`
```
const paper = apexChartRef.current.chart.w.globals.dom.Paper
const svg = paper.svg()
```

**Comment by jameswestgate** [comment]
You need to gain access to an instance of the Export class. Once you have that, you can trigger the methods the chart uses to download csv, svg etc.

    const cts = chart.ctx;
    ctx.exports.exportToSVG(this.ctx);
    ctx.exports.exportToCSV({
        series: your.chart.series,
        columnDelimiter: ','
    });

For more details see the source code here: https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/Toolbar.js

**Comment by gagwithgaffer** [comment]
@[jameswestgate](https://github.com/jameswestgate) typo? cts on 2nd & 3rd line, not ctx

const cts = chart.ctx;
cts.exports.exportToSVG(this.ctx);
cts.exports.exportToCSV({
    series: your.chart.series,
    columnDelimiter: ','
});

**Comment by drabi-he** [comment]
hello guys I am trying to make it work using typescript
but i get an error of undefined property
can anyone help

**Comment by sanathko** [comment]
invoke this function with the correct chartid passed into it, when the button is clicked.

```
async function downloadSVG(chartId) {
    console.log(window.Apex._chartInstances);
    const chartInstance = window.Apex._chartInstances.find(
      (chart) => chart.id === chartId
    );
    
    const base64 = await chartInstance.chart.dataURI();
    // create a temporary element to facilitate downloading
    const downloadLink = document.createElement("a");
    downloadLink.href = base64.imgURI;
    downloadLink.download = "image.png";

    // Add the anchor element to the document
    document.body.appendChild(downloadLink);

    // Simulate a click event to initiate the download
    downloadLink.click();

    // Remove the anchor element from the document
    document.body.removeChild(downloadLink);
  }
```

**Comment by eLTehh** [comment]
Modified and shortened the above suggestions to work for both .PNG and .SVG:

```
async function downloadSVG(chartId, datatype) {
    console.log(window.Apex._chartInstances);
    const chartInstance = window.Apex._chartInstances.find(
      (chart) => chart.id === chartId
    );
    if (datatype === "png") {
        chartInstance.chart.exports.exportToPng();
    }
    else if (datatype === "svg") {
        chartInstance.chart.exports.exportToSVG();
    }
  }
```

Calling the builtin exportToPng() and exportToSVG() functions within chart.exports

**Comment by abyshake-anand** [comment]
Has anyone successfully tried to download a chart that results in the annotations getting included in the output? When I am trying to download images - annotations are missing. Both in svg and png.

**Comment by nguyenquocdaile** [comment]
For anyone who wants to download a CSV file. You can refer to my solution here.
I'm working on Vuejs project. And chartInstance here is a ref of chart.

```
class ExportCSV {
    async export(fileName: string, chartInstance: any) {
        chartInstance.chart.exports.exportToCSV({
            series: chartInstance.chart.w.config.series,
            fileName: fileName,
        });
    }
}

export default new ExportCSV();
```

**Comment by desarrollador1IR** [comment]
hello, is there any way to place a watermark when exporting the chart?
