### ISSUE TITLE
Inconvenient panning

### ISSUE THREAD

**Issue by mbuczko** [apexcharts/apexcharts.js#8]
It's definitely not an issue but I feel like paning works in a bit unpredictable way. 

A simple scenario: I would like to zoom in a line chart, pan it left and zoom in again. In this case I need to go back and forth to the toolbar selecting a "zoom in" icon first, then a "pan" icon and then a "zoom in" icon again. In a meantime chart goes randomly left or right because in "paning mode" it follows mouse moves and it's horribly hard to escape from chart area without moving a chart itself :)

Ideally, I would combine pan & zooming and would use mouse-down event for selecting area to zoom (as it is already done), and mouse-down + shift or control key to pan a chart. That would save constant switching between pan/zoom tools and would make paning itself way more convenient.

If you think it's ridiculous idea, feel free to close this issue :)

Anyway, awesome library. Thanks for great work.

**Comment by junedchhipa** [comment]
Hi @mbuczko ,
Zooming and Panning together is carried out in a number of different ways. I got the inspiration for the current behavior in ApexCharts from plot.ly, but I think your suggestion to allow panning while holding an additional key is not bad. 

Another option to avoid going back and forth the toolbar is to allow zoomin/zoomout by mousewheel/pinch gesture and allow panning by mousedown/drag. This way you never will have to reach for toolbar multiple times.

I will keep this ticket open, so I have it in my to-do list, thanks!

**Comment by pribilinskiy** [comment]
@junedchhipa Shift+click to pan like in plotly would be very nice to have too

**Comment by junedchhipa** [comment]
@pribilinskiy I just checked out panning in plotly with the shift being held, and it is indeed a very good UX improvement.
I will definitely think more about this. Thanks

**Comment by arkhenstone** [comment]
Either this, or just make a double arrow cross like when you drag a windows on any OS. Any desktop OS have this symbol for moving windows around. The way it is now is complicated because it moves on its own just by hovering the chart. Look at amCharts lines chart demos for an implementation of this feature.

**Comment by junedchhipa** [comment]
@arkhenstone Tested in firefox, the panning is weird, it moves without button down event.
I will have a look at it along with the shitf + click, thanks for reporting

**Comment by junedchhipa** [comment]
Shift+mousedown = panning enabled.
Firefox bug while panning fixed.
