### ISSUE TITLE
xAxis when using Timeseries inconsistent behavior

### ISSUE THREAD

**Issue by Carniatto** [apexcharts/apexcharts.js#80]
I've been using ApexCharts with timeseries and Line charts. I encountered three weird behaviors regarding the way the xAxis is drawn:
- The first and last data point are often cropped on the chart:
![screen shot 2018-09-06 at 15 32 24](https://user-images.githubusercontent.com/1366831/45160877-cfb4db00-b1ea-11e8-95a9-236b2f2d5e9b.png)

- When only two days are in the series the `xAxis` has hours and days.
<img width="654" alt="screen shot 2018-09-06 at 15 35 03" src="https://user-images.githubusercontent.com/1366831/45160998-199dc100-b1eb-11e8-8907-a96664a10891.png">
https://codepen.io/Carniatto/pen/LJzbOx

- Sometimes the format for `month` gets mixed up with `year`
<img width="665" alt="screen shot 2018-09-06 at 15 27 33" src="https://user-images.githubusercontent.com/1366831/45160763-86fd2200-b1ea-11e8-92af-ce1f40505109.png">
https://codepen.io/Carniatto/pen/EewNLy

**Comment by junedchhipa** [comment]
Hi @Carniatto 

Actually, this is the way I have kept the x-axis tick generation to differentiate the days and hours when the difference is more than 1 day.

In certain cases, a user may not like this and would just prefer a single format - in your case: just the hours.

So, as suggested by you in another thread, I am going to provide the raw date-time value in the `formatter` function as a parameter where the user can use whatever suits them - no default behaviors.

Thanks for reporting @Carniatto

**Comment by Carniatto** [comment]
Thank you @junedchhipa. Can I suggest the option to add padding in the beginning and the end so all the points are contained inside the Chart? avoiding the first problem

**Comment by junedchhipa** [comment]
@Carniatto Ah! I didn't see the edited comment.
So, the cropped dataPoints issue was fixed in the apexcharts@1.3.20. May I ask which version of ApexCharts you are testing on?

**Comment by Carniatto** [comment]
@junedchhipa I'm using version: 1.3.12.

**Comment by junedchhipa** [comment]
Yes, you are right - Currently, you have no control over the number of ticks when `type = datetime`

**Comment by Carniatto** [comment]
@junedchhipa thanks for the quick response,  let me know when you shipp the `raw datetime`.  I'd like to contribute to the repo like add download as png or something like this. Let me know if I can open a PR.

**Comment by junedchhipa** [comment]
@Carniatto I appreciate your willingness to make the library better. 
I will soon create a simple contributing guideline.
For now, just create a PR with "feature/featureName" branch.
Thanks
