### ISSUE TITLE
Pie chart initial animation with 0 value in series

### ISSUE THREAD

**Issue by AlexanderArvidsson** [apexcharts/apexcharts.js#802]
## Codepen
https://codepen.io/anon/pen/oKzJgR

## Explanation
When the series includes the value 0, the animation will run for about 1/5th of its duration, then snap to its finished state.
The animation works fine if the series does not include any 0s, and I expect it to work the same even if it does include 0s.

**Comment by mikerockett** [comment]
Just bumped into this as well… @AlexanderArvidsson Do you perhaps have any workarounds until this is fixed?

**Comment by AlexanderArvidsson** [comment]
@mikerockett My only workaround is using another graphing package at the moment 🤷

**Comment by mikerockett** [comment]
@AlexanderArvidsson I see – well I've landed up turning off animations for these charts, not the end of the world for now. 🙂

**Comment by junedchhipa** [comment]
Fixed it.
The next minor release will be released soon with this fix.
