### ISSUE TITLE
How to adjust for dynamic number of series?

### ISSUE THREAD

**Issue by azivkovi** [apexcharts/apexcharts.js#805]
My chart is supposed to receive JSON with anywhere between 1 - 3 series and I want to draw just the ones that are available.

If I use the code below for chart options and I only get two series, the third is drawn and 'NaN' value is shown. Also, the series name (keys[3]) is not set so the chart shows name 'series-3'.

`
series:[
  {
    name: keys[1],
    data: one
  },
  {
    name: keys[2],
    data: two
  },		
  {
    name: keys[3],
    data: three
  }]
`

Is there a way to check if the series is set beforehand, or is there a better way of accessing series data in the case I don't know how many series the chart will need to show?

I would appreciate any suggestion you guys might have.

**Comment by junedchhipa** [comment]
When you get data from JSON, you should check for the series existence before passing them to
the `series` array. If the JSON contains empty items, you should filter them out.

Or you should create an empty array and push whatever data is available in the received JSON prior to injecting into ApexCharts series.

**Comment by azivkovi** [comment]
Thanks, Juned. I got it now. My js understanding needs more work.
