### ISSUE TITLE
Y axis not scaling

### ISSUE THREAD

**Issue by will-banfield** [apexcharts/apexcharts.js#806]
Hello.

I have my Y Axis set to scale, but even when I zoom all of the way in, the Y axis does not scale, so when looking at a small timeframe, the y axis should be zoomed in more.

https://codepen.io/anon/pen/VoPeBw

**Comment by junedchhipa** [comment]
This commit - https://github.com/apexcharts/apexcharts.js/commit/f9c86d5ad59d5eea081f21912ce17339ab5d40b1 fixes the issue

The new version will be released soon.
