### ISSUE TITLE
Heatmap updateSeries not animated

### ISSUE THREAD

**Issue by jicihome** [apexcharts/apexcharts.js#807]
Hi.
Maybe it's more a feature request, but actually, when I use updateSeries and data value are updated, there's no animation (but data are updated). (maybe because change are too small? like +1/-1 somewhere at each refresh)

If this is not implemented, maybe you can consider to only animate the data that are updated and not the whole chart.

**Comment by junedchhipa** [comment]
Heatmap does animate on updateSeries

![heatmap-update](https://user-images.githubusercontent.com/17950663/72747506-d8892f80-3bda-11ea-8a1a-c0569a28efef.gif)
 
Yes, if the difference is too small, it might not be visible.
