### ISSUE TITLE
Bar charts drawing NULL values

### ISSUE THREAD

**Issue by hhu-mahmoud** [apexcharts/apexcharts.js#809]
In Bar charts, i don't want to show the 0 value at all. I have some people and they think, there is a value but it's a 0. How can I hide them?

![grafik](https://user-images.githubusercontent.com/32834850/62051402-98d92080-b213-11e9-8326-0c427ebf3538.png)

## Explanation

- I don't want it to draw anything by 0 or Null values for Bar charts and it would be nice also for another charts.
- I want to be able to show and hide the labels on (X) if the value is 0 or NULL

**Comment by MattBudz** [comment]
How did you end up hiding the bars with `null` values?
