### ISSUE TITLE
Define different background color rules for a chart

### ISSUE THREAD

**Issue by sgba00** [apexcharts/apexcharts.js#813]
For example, I want to split an Area Chart in two ->

The first 'x' values of yAxis must have 'x' background, and everything higher than 'n' will have 'xx' background. Something like this:

![image](https://user-images.githubusercontent.com/38985289/62078541-3ab43980-b223-11e9-9120-28125b3e6609.png)

**Comment by junedchhipa** [comment]
You can use annotations to achieve this.
```javascript
  annotations: {
    position: "back",
    yaxis: [
      {
        label: {
          text: " "
        },
        y: 8200,
        y2: 9600,
        fillColor: "#00E396"
      },
      {
        label: {
          text: " "
        },
        y: 7800,
        y2: 8200,
        fillColor: "yellow"
      }
    ]
  }
```

![9kdynk74l](https://user-images.githubusercontent.com/17950663/62110819-dea5ef80-b2cc-11e9-9e9a-8e813262deae.png)

Codepen demo - https://codepen.io/apexcharts/pen/MNpOOY

**Comment by victor-insper** [comment]
Is position still working?
