### ISSUE TITLE
Horizontal bar axis not showing last (max) label & tick 

### ISSUE THREAD

**Issue by yairEO** [apexcharts/apexcharts.js#815]
https://codepen.io/vsync/pen/XvMPGq

When using horizontal bar chart, with data set such as `[10,20,100]`, the _xaxis_ last label (and tick) are missing. Expected to show the value `100` in the right-most side:

![image](https://user-images.githubusercontent.com/845031/62125160-013c0680-b2d5-11e9-96af-9c5e83fd87ac.png)

## Options:
```javascript
{
  chart: {
    height: 380,
    width: "100%",
    type: "bar"
  },
  plotOptions: {
      bar: {
          barHeight: '100%',
          horizontal: true   // ← "true" flip the axis, "100" is not shown anymore
      }
  },
  series: [
    {
      name: "Series 1",
      data: [10,20,100]
    }
  ]
}
```

When `horizontal` set to `false` and the axis flip, the max value is shown as expected & at the current position (although now on the Y axis)

**Comment by MerApelsin** [comment]
I'm wonder this as well but using React instead. Hoping for someone to shed some light on this! :)

**Comment by tanguyvda** [comment]
I've noticed that too

**Comment by ThinkSalat** [comment]
I have the same problem

**Comment by junedchhipa** [comment]
The last x-axis label is intentionally hidden to avoid overflowing in some cases.
But, I think, in horizontal bar charts, this should be avoided.

I will change this behavior for horizontal bar charts.

**Comment by algresie** [comment]
> The last x-axis label is intentionally hidden to avoid overflowing in some cases.
> But, I think, in horizontal bar charts, this should be avoided.
> 
> I will change this behavior for horizontal bar charts.

How can I hide the max and show the min label in horizontal bar charts?

**Comment by meir-achieved** [comment]
Is ther a way to change this behavior in a line chart? @hila-achieved @shalombar29

**Comment by manhbui21** [comment]
Is there any way to change this in timeline chart? @junedchhipa

**Comment by rutpshah-omnirio** [comment]
What should be done to show last label in Line Chart Dual Axis? @junedchhipa

**Comment by NickSutton** [comment]
I see this remains unresolved

**Comment by Gunjansokal07** [comment]
> The last x-axis label is intentionally hidden to avoid overflowing in some cases. But, I think, in horizontal bar charts, this should be avoided.
> 
> I will change this behavior for horizontal bar charts.

-Hi @junedchhipa ,

Is there any configuration available where I can show the last label on x-axis.

**Comment by mustakim** [comment]
@junedchhipa

5 years gone, but why you can't solve it?

**Comment by felipevvasconcelos** [comment]
I fixed this with th following prop: 
labels: {
     rotateAlways: true,
}

if you don't want rotate the value from xaxis, set the prop rotate to -1 but you will have to fix the layout

**Comment by junedchhipa** [comment]
Closing this as this no longer seems to an issue. I tested in v3.51.0
Please provide a new Codepen, and I will re-open this if the issue still persists.

**Comment by spanwair** [comment]
in version 4.5.0 is the problem again 

![Image](https://github.com/user-attachments/assets/0601fca6-4173-48b9-9977-3492948641be)

**Comment by spanwair** [comment]
my solution is to turn date labels by 45°:
```
labels: {
        formatter: (val) => momentTz.tz(new Date(val), currentUser.timeZone).format(props.xLabelFormat)
        rotateAlways: true,
        rotate: -45,
        offsetY: 5,
        offsetX: -5
}
