### ISSUE TITLE
Labels and markers getting cutoff  on line chart

### ISSUE THREAD

**Issue by jinujj** [apexcharts/apexcharts.js#817]
Issue codepen : https://codepen.io/jinujohnj/pen/aeWbKB
The dataLabel positioning is getting cutoff on using line chart with version 3.8.1 on mouse over for the first and last data value.
Also the xaxis label is getting cutoff. 

Tried with apexchart version 3.5.1: xaxis label issue is fixed but the dataLabel issue persist.
Issue seems to have happened with version 3.6.0
Code pen with apex chart v3.5.0 : https://codepen.io/jinujohnj/pen/LwyYBL

**Comment by valecj** [comment]
+1 :(
