### ISSUE TITLE
AMD ApexChart isn't being loaded

### ISSUE THREAD

**Issue by sgba00** [apexcharts/apexcharts.js#818]
Using RequireJs and AMD ApexCharts (apexcharts.amd.js) 

```
define([
    "js/modules/OEE/apex-charts/apex-charts_amd",
],
function (apexChart) {

});
```
'apexChart' results in null. Is this a bug or am I doing something wrong?

**Comment by byander** [comment]
Hi @sgba00 , did you solve in your case? I have the same problem.
