### ISSUE TITLE
Bar chart custom tooltip function is called repeatedly on mouseover

### ISSUE THREAD

**Issue by yairEO** [apexcharts/apexcharts.js#819]
In the below demo, move the mouse over a column and look at the top left corner at the number of events fired:
https://codepen.io/vsync/pen/jgmxGb

I would expect it to be called only on `mouseenter` event and not thousands on `mousemove` which affects performance.

Is there any justification for the current behaviour?

**Comment by junedchhipa** [comment]
The tooltip is a common functionality between line/area/scatter/bar/column charts and the `mousemove` event is helpful in determining the values based on mouse position. As in the line/area charts, there are no elements where mouseenter/mouseleave can be captured, 
 mousemove is used for all chart types.

**Comment by yairEO** [comment]
Bummer
