### ISSUE TITLE
"querySelectorAll of undefined" if initial series is empty list

### ISSUE THREAD

**Issue by tommie** [apexcharts/apexcharts.js#82]
I'm trying to use the Vue.js wrapper with an HTTP request to fetch the data. I noticed I have to set `series` to the empty list, because the prop is defined as Array, so I can't pass `null` (due to a Vue.js type check) as a placeholder while loading.

So I set it to the empty list initially, but then `updateSeries` throws an exception of `Cannot read property 'querySelectorAll' of undefined` when invoked with the real (single) series.

I can reproduce this without the Vue binding: https://codepen.io/anon/pen/jvaRYm

Clicking the button makes `chartGood` render the data and `chartBad` throws an exception.

I couldn't find anything in the documentation saying changing the number of series with `updateSeries` is unsupported.

**Comment by junedchhipa** [comment]
Hi @tommie 
That's a valid use case of not having anything in the initial series.
Also in your example, I see `-Infinity` in the x-axis which doesn't look OK.

I am going to test more with the scenarios when updating from empty series.
Thanks for reporting, this will be taken care of.

**Comment by junedchhipa** [comment]
Fixed in https://github.com/apexcharts/apexcharts.js/commit/6a853d9829ea05570c77ebd39cfbc466e3fa2540

**Comment by sumitaney** [comment]
This is still an issue in latest version

**Comment by sumitaney** [comment]
![Screenshot 2024-10-08 at 1 19 05 PM](https://github.com/user-attachments/assets/3bf4f54d-c86f-4bf3-884a-30eba9c0e348)
Chrome Browser

**Comment by sumitaney** [comment]
> Fixed in [6a853d9](https://github.com/apexcharts/apexcharts.js/commit/6a853d9829ea05570c77ebd39cfbc466e3fa2540)
> 
> Please update to apexcharts@1.4.8

Can you check it once
