### ISSUE TITLE
Heatmap Documentation Wrong

### ISSUE THREAD

**Issue by jicihome** [apexcharts/apexcharts.js#820]
In Documentation (https://apexcharts.com/docs/chart-types/heatmap-charts/) it say for distributed to set this:
options = {
  plotOptions: {
    heatmap: {
      distributed: true
    }
  }
}

But in example (https://apexcharts.com/javascript-chart-demos/heatmap-charts/multiple-series-colors-flipped/), it seem to be :
            plotOptions: {
                heatmap: {
                    colorScale: {
                        inverse: true
                    }
                }
            },
Both seem to have the same effect, but the first one doesn't seem to work. Is it an error in documentation or a bug if distributed doesn't work?

**Comment by junedchhipa** [comment]
You're right.
I have mixed the two functionalities in the docs which is very confusing.

I will fix the docs soon, thanks for reporting.

**Comment by junedchhipa** [comment]
Fixed it
https://apexcharts.com/docs/chart-types/heatmap-charts/

**Comment by maitegm** [comment]
Hi, I'm trying to use the "distributed" argument, and when I use it, it also inverses the color series from  horizontal to vertical.
Can you check this please?
