### ISSUE TITLE
dataLabels.enabledOnSeries works opposite to expectation

### ISSUE THREAD

**Issue by forenpm** [apexcharts/apexcharts.js#824]
## Codepen

https://codepen.io/anon/pen/xvPRXL

## Explanation
The chart has 2 series (0 & 1 index).

```
dataLabels: {
    enabled: true,
    enabledOnSeries: [0]
}
```
- Expected: Series 1 shows labels
- Actual: Series 2 shows labels

You can also modify the enabledOnSeries array to: [0, 1] to see that no labels are shown. [ ] shows all labels (as expected).
This behavior is opposite to what is expected.  It's as if the bool logic is swapped.

Changing enabled to false also does not change the desired behavior.

#697 is related

**Comment by junedchhipa** [comment]
😁  Such a silly mistake. Thanks for reporting.
