### ISSUE TITLE
Any idea for creating a Depth chart?

### ISSUE THREAD

**Issue by andynguy3n** [apexcharts/apexcharts.js#825]
**Is your feature request related to a problem? Please describe.**
The second y-axis can't move to the right side
![Screen Shot 2019-08-05 at 6 02 12 PM](https://user-images.githubusercontent.com/10527554/62460614-a4e15700-b7ac-11e9-9f94-1e04ad75e560.png)

I've tried to remove the y-axis config then I got this one:
![Screen Shot 2019-08-05 at 6 56 31 PM](https://user-images.githubusercontent.com/10527554/62462904-cfcea980-b7b2-11e9-9b25-4a188f8edf24.png)

Is there any way to move the Green line to the right side?

**Describe the solution you'd like**
- When we have 2 y-axes, the second y-axis should able to move to the right side
- The categories should not move from both side, it should move straightforward from the 0 to the biggest value

**Describe alternatives you've considered**
I used ChartJS to get this feature
- I created 2 series, the first one has 20 items, in order to move the second one to the right side, I need to create an array of 40 items with the first 20 items are empty/null (So it will create a space between 2 areas)

**Additional context**

Yes Houbi did it very well
![Screen Shot 2019-08-05 at 6 15 10 PM](https://user-images.githubusercontent.com/10527554/62460720-fe498600-b7ac-11e9-8902-b113b528261e.png)

**Comment by andynguy3n** [comment]
Nevermind. I'm able to do that. I was wrong at creating the values for both sides.

The values for the right side should be
`createRightSeries: (leftSeries, rightSeries) => [...leftSeries, ...rightSeries]`

![Screen Shot 2019-08-05 at 11 05 35 PM](https://user-images.githubusercontent.com/10527554/62478664-cd317b80-b7d5-11e9-9767-680a4d8c2eec.png)

**Comment by junedchhipa** [comment]
Glad you figured it out :)

**Comment by andynguy3n** [comment]
I'm sorry. I think I need to re-open this issue
This is when I turn off the Sell-side:

![Screen Shot 2019-08-06 at 1 59 28 PM](https://user-images.githubusercontent.com/10527554/62517844-6ef6ae00-b852-11e9-96b0-134bc73097ca.png)

This is when I turn off the Buy-side:
![Screen Shot 2019-08-06 at 1 59 34 PM](https://user-images.githubusercontent.com/10527554/62517889-85046e80-b852-11e9-8a9e-5bb60bc86be5.png)


As you can see this is a fake behavior. The right basic is overlapped by the left side, at first glance we thought it worked but it didn't

**Comment by andyngdz** [comment]
> @andyngdz Hello! Could you please share an example of your code that you used to create this chart?

@hramtsov13  It was a long time ago I didn't have the source code anymore. Ideally, I made 2 charts  for each side  sell and buy then flipped of one them to the other side, it looks like 1 chart, but actually 2 charts got merged together

**Comment by andyngdz** [comment]
> @andyngdz Hello! Could you please share an example of your code that you used to create this chart?

@hramtsov13  It was a long time ago I didn't have the source code anymore. Ideally, I made 2 charts  for each side  sell and buy then flipped of one them to the other side, it looks like 1 chart, but actually 2 charts near  each other
