### ISSUE TITLE
White space between each slice in Donut chart

### ISSUE THREAD

**Issue by anilreddy128** [apexcharts/apexcharts.js#827]
## Explanation
When using donut charts, there is some white space between each slice.
How to remove that.
See attached image.
![Apex DOnut White Space issue](https://user-images.githubusercontent.com/51972003/62512755-eb4fa980-b7de-11e9-8a1e-22c2f6d38fe0.png)

**Comment by junedchhipa** [comment]
```javascript
options = {
  stroke: {
    width: 0
  }
}
```

**Comment by SimonChatillon** [comment]
What if i want to have transparent spaces between each slice ? I can't manage to achieve this, I tried using transparent stroke but it's not working because the fill colors always connect below the stroke. My background is a gradient pattern so I can't use any specific stroke color either. Any idea ?

**Comment by jstadev** [comment]
i was trying the same, ,if you found a solution please share

**Comment by michele1234567** [comment]
Does anybody found a solution for this? I need the same , transparent spaces between slices

**Comment by TimChinye** [comment]
If you came here looking for a way to get rid of the gaps:

```js
    elements: {
        arc: {
            borderWidth: 0
        }
    }
```

**Comment by musados** [comment]
<code>
stroke: {
                  show: false,
                    curve: 'straight',
                    lineCap: 'butt',
                    colors: '#ffffff',
                    width: 5,
                    dashArray: 0, 
                },
                chart: {
                    type: 'donut',
.....
</code>

In the main option body, set stroke settings (show: false)
