### ISSUE TITLE
How to show big label on Heatmap

### ISSUE THREAD

**Issue by marcoferre** [apexcharts/apexcharts.js#828]
## Codepen

https://codepen.io/anon/pen/jgYXMa

## Explanation

- How can i show the entire label when it is bigger than a simple word or number?

For example: in the Pen all the "Title - Artist" labels on the left of the chart are cutted.

Thanks for help

**Comment by junedchhipa** [comment]
You can set the minimum width of the yaxis labels by

```javascript
yaxis: {
  labels: {
    minWidth: 200
  }
}
```
