### ISSUE TITLE
Percentage chart

### ISSUE THREAD

**Issue by felixalguzman** [apexcharts/apexcharts.js#83]
Is it posible to create a percentage chart ?

Something like this
![image](https://user-images.githubusercontent.com/17243615/45322361-0b66e200-b516-11e8-893f-3f0ac9103e4c.png)

**Comment by junedchhipa** [comment]
There is not a chart-type which gives an out-of-the-box percentage chart, but it is very easy to tweak a "100% stacked bar chart" to create something like the image you provided.

Here is an [example](https://codepen.io/apexcharts/pen/ZMrvRK) which produces this result

![screen shot 2018-09-11 at 2 49 06 am](https://user-images.githubusercontent.com/17950663/45324981-4ba57f00-b56d-11e8-9fe0-9ffa288abda2.png)

**Comment by felixalguzman** [comment]
Nice, this will work thanks!
