### ISSUE TITLE
Hiding first series in stacked bar chart hides the second series too

### ISSUE THREAD

**Issue by uunbound** [apexcharts/apexcharts.js#830]
I have a mixed area and stacked bar chart. The order of charts series type is area, bar, bar. When I click on the legend of first bar series, it hides/shows both bars. However, clicking on second bar legend only affects that bar visibility. I expect legend click function to only affect associated series. Here is a gif:

![](https://i.imgur.com/03T2EuI.gif)

And here is [the codepen](https://codepen.io/anon/pen/vodOgJ)

**Comment by junedchhipa** [comment]
Stacked mixed charts are not supported at the moment.
You can either have stacked area charts or stacked bar charts.
