### ISSUE TITLE
RadialBar Size issue

### ISSUE THREAD

**Issue by jicihome** [apexcharts/apexcharts.js#832]
Hi!
I'm trying to understand Radial bar "size" property.
If I set a number (integer) the chart is render and a kind of calculation happen with the heigth. A little bit like if we set undefined, but the result is different. But it's hard to dynamically set it because  we don't know how this is calculated and we cannot replicated the calculation to get what we need.
If I enter "100%", the middle of the chart is rendered but no bar. Same for "100px" for example.
I think that "100%" should work but it doesn't seem to work.
So actually, the size parameters is impossible to use in radial bar (except if you have a specific height that never change, this is possible to find the size integer to use).

**Comment by junedchhipa** [comment]
Yes, the `size` property was intended to provide a fixed size to the radial-bars, but it seems they cause more issues in the positions.
The correct way to control the size of any chart type would be to set the `chart.height` and `chart.width` properties.
Then to control the size of specific elements of radial bars, setting `radialBar.hollow.margin` or `radialBar.hollow.size` would help.

**Comment by jicihome** [comment]
@junedchhipa I think I understand what you mean. And I think I didn't explain well enough. 
Is this normal that in this example: https://sandboxjc.bubbleapps.io/version-test/radial there's a lot of free space (margin) all around the chart? I would think that if no title and legend are shown, this should be centered and use 100% width. I tested with your codepen example, and this seem fine. So not sure what is causing this issue. I will continue to test and will send all settings later. Thanks

**Comment by jicihome** [comment]
After playing a bit more with the demo, it's seem that this is the normal behavior actually. The chart seem to use a specific width and height and keep space for title, legend and anything else around the chart (addtext for example) instead of adjusting automatically to available space. Is this expected behavior?

**Comment by oherik** [comment]
I have the same issue; there seems to be a lot of white-space to the left and right of the chart, even though I have disabled the legend and other items than might take up that space.

**Comment by oherik** [comment]
I've created a codepen to show what I mean: https://codepen.io/oherik/pen/WNbqbYG

When the `chart` div is highlighted, you can see that there is some whites-pace between its borders and the chart itself: 
![image](https://user-images.githubusercontent.com/10709871/73458991-6b159580-4376-11ea-8d30-98049db0f961.png)

To be fair, I'm not sure if this is a part of the original question, or if it should count as a new one. @junedchhipa, do you think I should open a new issue/feature request for this?
