### ISSUE TITLE
Add prefix and suffix for when formatter is undefined

### ISSUE THREAD

**Issue by styd** [apexcharts/apexcharts.js#833]
**Is your feature request related to a problem? Please describe.**
In ApexCharts.rb, the way we configure options is with ruby hash converted to JSON. We have no way to specify, e.g. `formatter: function(val) { return "Rp " + val + "-" }`. Function is a valid value for JS object but not for JSON.

**Describe the solution you'd like**
I'd like to propose `prefix` and `suffix`. So, instead of specifying `formatter` above, we can do this:
```js
prefix: "Rp ",
suffix: "-",
```
It's a valid key-value for JS object and JSON too. So we can specify it from ruby hash.
`prefix` and `suffix` should be checked only when `formatter` is undefined.

**Comment by junedchhipa** [comment]
Good suggestion.
However, what about situations where you need to modify the value.
For eg., `10000` to `10,000`

The `formatter` function is available in 14 different places. All those places will need `prefix` and `suffix` to maintain consistency.

Any other workaround?

**Comment by styd** [comment]
For the case that you mentioned, they won't help. But for other cases that don't need to change the values, e.g. `3 Instances` or `Bucket No. 2`, they can be a great help.

I happen to just released a new experimental gem [functionable-json](https://github.com/styd/functionable-json) that can help for the case that you mentioned. It's against the law of RFC8259, but it works. But probably not all of users of ApexCharts.RB want to use this. For people that won't use `functionable-json` gem, `prefix` and `suffix` will be a nice alternatives.

**Comment by junedchhipa** [comment]
How about this approach?

```javascript
var fnObj = {"function":{"arguments":"a,b,c","body":"return a*b+c;"}}
var fn = new Function(fnObj.function.arguments, fnObj.function.body);
```

Source: https://stackoverflow.com/questions/36517173/how-to-store-a-javascript-function-in-json#answer-47558227

**Comment by styd** [comment]
That's definitely better than `prefix` and `suffix`. I'd like that.

**Comment by styd** [comment]
Hi, @junedchhipa.
Can you tell me the status of supporting function object in your roadmap? When can we expect this feature?
I'm not rushing you or anything. It's just that some of ApexCharts.RB users really need this for their options.
Thanks for your great work.

**Comment by junedchhipa** [comment]
Hi @styd,
Sorry, I have been very busy with other things lately, and this issue went unnoticed from my list.
I have added additional tags to this issue to keep reminding myself to work on it soon.
Thank you for your patience.

**Comment by junedchhipa** [comment]
@styd Unfortunately, I won't be able to fix this easily.
As said above, the formatter functions are used at a lot of places and checking everywhere whether it's a function or an object will introduce a big maintenance overhead.
I think, handling with the [functionable-json](https://github.com/styd/functionable-json) is the correct approach for now.

**Comment by styd** [comment]
Hi @junedchhipa. I read your comment as soon as you posted, but then I forgot to reply to it, sorry.
Thanks so much for considering the feature. I guess I'll just implement it in the ruby code.
