### ISSUE TITLE
Axis' labels in multiple line for long length texts

### ISSUE THREAD

**Issue by max8hine** [apexcharts/apexcharts.js#834]
**Is your feature request related to a problem? Please describe.**
I want to display axis' long labels in multiple lines 

Current:

```html
// Example in xaxis
<text>
  <tspan>Line1, line2</tspan>
  <title>Line1, line2</title>
</text>
```

PS: Labels on X-Axis and Y-Axis, not the title.

**Describe the solution you'd like**

Wanted:
```html
// Example in xaxis
<text>
  <tspan>Line1,</tspan>
  <tspan>Line2</tspan>
  <title>Line1, line2</title>
</text>
```

**Describe alternatives you've considered**
Give the **formatter** function in labels object that can target `<tspan>` and `<text>` if I shorten the label in `<tspan>`, but the hover tooltips in x-axis won't be affected.

Alternatives:
```html
// Example in xaxis
<text>
  <tspan>Line1</tspan>
  <title>Line1, line2</title>
</text>
```

**Additional context**
screenshot:
![image](https://user-images.githubusercontent.com/15165714/62671425-f9721580-b9ea-11e9-97ee-42b96e88505d.png)

**Comment by junedchhipa** [comment]
Thanks for the suggestion.
Closing this one in favor of #388

**Comment by jatindumka** [comment]
@max8hine  were u able to get it any way on multiple lines .
In my case i hava a chart called as weekly view , where the labels on xaxis for each bar says,
2019-10-11 To
2019-11-12
