### ISSUE TITLE
Graph segment disappears on mouse hover in Safari

### ISSUE THREAD

**Issue by mirayadav-toast** [apexcharts/apexcharts.js#836]
![image](https://user-images.githubusercontent.com/50370848/62710148-bf8e1880-b9c4-11e9-8e58-f2d26df0648a.png)
![image](https://user-images.githubusercontent.com/50370848/62709727-f283dc80-b9c3-11e9-8f93-563b5dbfe1b6.png)
![image](https://user-images.githubusercontent.com/50370848/62709745-fb74ae00-b9c3-11e9-9060-9b8f4441518a.png)

## Explanation
*This bug only appears on Safari, on Chrome the behavior is normal as expected. 

- What is the behavior you expect?
When the mouse is hovered over a graph segment, its respective tooltip should appear and the segment's color should darken slightly. 

- What is happening instead?
The tooltip appears but the segment completely disappears (turns white) instead of just slightly darkening.

- What error message are you getting?
No error message.

**Comment by luqmanyasin** [comment]
I'm having similar issues in safari where series are not being rendered correctly.
Any news on this?

**Comment by jbultez** [comment]
Same issue here, did u figured out of this bug ?

**Comment by junedchhipa** [comment]
I am unable to reproduce it in the latest version - 3.19.3
Can you please specify which version of Safari you're using? (Also, please test in the latest ApexCharts release)
