### ISSUE TITLE
high max value breaks datalabel display

### ISSUE THREAD

**Issue by tanguyvda** [apexcharts/apexcharts.js#837]
Hello there,

here are all the details about this issue (apex 3.8.4 on my test plateform)

## Codepen
https://codepen.io/tcharles/pen/mNLJwR

in this codeopen you have two horizontal bar charts, one using a five digits max with a five digits serie value. Everything work as expected on this one. 

The second horizontal bar chart uses a six digits max with a six digits serie value. On this one, the datalabels doesn't show up

## Explanation

- What is the behavior you expect?
I want my datalabel to be displayed 

- What is happening instead?
if the max value of the bar is too high (more than five digitis), the datalabel is not going to be displayed

- What error message are you getting?
none
![max-more-than-5numbers](https://user-images.githubusercontent.com/7352865/62720213-d440cf80-ba09-11e9-95bf-93cf065a9ac7.gif)

**Comment by junedchhipa** [comment]
Fixed since 3.12.0
