### ISSUE TITLE
Additional chart types

### ISSUE THREAD

**Issue by CheyenneForbes** [apexcharts/apexcharts.js#84]
Apexcharts.js would be the ultimate graph library if it had the following:

-  world map charts (location based chats)

-  relational charts (graph database visualization)

- timeline chart

**Comment by junedchhipa** [comment]
Hi @CheyenneForbes, thanks for the suggestions.

- A map can another plugin itself, out of scope for current repo. Maybe in future - ApexMaps 😁 
- Relational charts are interesting - but again, it will make the library heavy (already it is now)
- Timeline chart - this can be implemented, as I just need to implement a timescale for horizontal bar charts, and provide a start and end position for those bars.

**Comment by CheyenneForbes** [comment]
Your points about making Apexcharts too heavy were a good.

Anyone looking for a relational graph library could try [cytoscape.js](https://github.com/cytoscape/cytoscape.js)

Could you add Timeline chart soon?

**Comment by junedchhipa** [comment]
Hi,

Yes, I think - timeline charts are useful and I already thought about it before. Need to refactor the horizontal bar chart's code to support the timeline on the x-axis for it (at the same time not increasing the library size a lot).

FYI,
I am talking about these timeline charts as seen on Google charts
![screen shot 2018-09-13 at 12 16 40 pm](https://user-images.githubusercontent.com/17950663/45471495-dd201700-b74e-11e8-8547-d82ad455e534.png)

No estimated timeline for it, though.

Thanks for the suggestion again

**Comment by KristerV** [comment]
oh wow what a deal breaker. Well, I mean this chart is amazing without it, so sad I can't use it :D

**Comment by junedchhipa** [comment]
@KristerV which one you're talking about? The timeline chart?

**Comment by KristerV** [comment]
yes. specifically I need horizontal ones like this: https://zoomcharts.com/en/chart-types-demo/multiple-level-span-chart-with-categorical-data-using-facetchart
Compared to that Google Chart or Gantt charts I need overlapping blocks.

**Comment by junedchhipa** [comment]
The example which you gave of zoomcharts is more of a range column chart 
![screen shot 2018-09-18 at 12 12 05 pm](https://user-images.githubusercontent.com/17950663/45668945-17692a00-bb3c-11e8-8264-beb2d3e2a5a9.png)

This can be implemented easily ApexCharts contains candlestick chart already https://apexcharts.com/javascript-chart-demos/candlestick-charts/basic/ and the calculation of range is no different in case of range-charts.

Thanks for the input

**Comment by hariharaselvam** [comment]
> Hi @CheyenneForbes, thanks for the suggestions.
> 
> * A map can be another plugin itself, out of scope for current repo. Maybe in future - ApexMaps 😁
> * Relational charts are interesting - but again, it will make the library heavy (already it is now)
> * Timeline chart - this can be implemented, as I just need to implement a timescale for horizontal bar charts, and provide a start and end position for those bars.

May I know, when the timeline chart will be available? I have to do lot of formats to make your stacked horizontal bar chart like a timeline chart.

**Comment by junedchhipa** [comment]
You can expect timeline charts in the next 6-8 weeks (somewhere around mid-March)

**Comment by hariharaselvam** [comment]
We are eagerly anticipating timeline charts.

**Comment by junedchhipa** [comment]
Here is a sneak peek of the timeline charts which will be very soon released.
![Screen Shot 2019-04-08 at 2 54 16 PM](https://user-images.githubusercontent.com/17950663/55822881-233f2c80-5b1e-11e9-8403-623f5cfa3c19.png)

**Comment by renancavalieri** [comment]
> Here is a sneak peek of the timeline charts which will be released very soon.
> ![Screen Shot 2019-04-08 at 2 54 16 PM](https://user-images.githubusercontent.com/17950663/55822881-233f2c80-5b1e-11e9-8403-623f5cfa3c19.png)

It is possible to create a timeline like this one?

![GObfw](https://user-images.githubusercontent.com/16182725/57815565-52b10c80-774e-11e9-8d50-e9db4d8cec04.png)

**Comment by junedchhipa** [comment]
@renancavalieri Not yet. It has also been proposed here  #560
No ETA for it though.

**Comment by renancavalieri** [comment]
It will be very good, because today we have only Google and Highcharts, and both have huge limitations while working with Vue.

**Comment by junedchhipa** [comment]
Sure, I will consider this for future enhancements.

**Comment by junedchhipa** [comment]
The latest version 3.11.0 supports timeline charts with multiple ranges - https://apexcharts.com/javascript-chart-demos/timeline-charts/advanced/

![Screen Shot 2019-12-18 at 1 17 59 PM](https://user-images.githubusercontent.com/17950663/71066561-d75a8200-2198-11ea-9f18-82d73e5067d4.png)

**Comment by themustafaomar** [comment]
If someone is looking for a lightweight map.
I've rebuilt the jvectormap project using pure Javascript instead of jQuery.
https://github.com/themustafaomar/jsvectormap

**Comment by KristerV** [comment]
Link gives 404.

**Comment by themustafaomar** [comment]
@KristerV Sorry, I've encountered a problem with npm yesterday, I had to disable the repo for a while until I fix it.
It's working now.
https://github.com/themustafaomar/jsvectormap
