### ISSUE TITLE
Unable to get xaxis.categories array

### ISSUE THREAD

**Issue by groubis** [apexcharts/apexcharts.js#842]
Hi everyone,

i've been struggling to somehow extract the array of x.axis.categories from a rendered line chart. Definition is quite simple:

```
chartRecentHours = new ApexCharts(
  document.querySelector(`#chart-recent-hours`),
  {
    chart: {
      width: "100%",
      height: 380,
      type: "line"
    },
    series: [
      {
        name: "Total",
        data: []
      },
      {
        name: "Allowed",
        data: []
      },
      {
        name: "Denied",
        data: []
      }
    ],
    xaxis: {
      categories: []
    },
    yaxis: {
      max: 10
    },
    tooltip: {
      theme: "light"
    }
  }
);
```
In my case xaxis.categories values come from an array of strings, right after initialization, through ajax:

`["22:35 - 22:40", "22:40 - 22:45", "22:45 - 22:50", "22:50 - 22:55", "22:55 - 23:00", "23:00 - 23:05"]`

The chart is rendered correctly, but since my concept is realtime, i am trying to find a way to get the array every n minutes, remove the first element and add one at the end. I've been searching the chart object for hours, but i am unable to locate the "pure" array, only the generated html. Is there anything i am missing in the documentation? Thanks!

**Comment by junedchhipa** [comment]
If you cannot find the provided categories in the config object, you may try this.

```javascript
var chart = new ApexCharts(el, options)

categories = chart.w.globals.labels.map((i) => {
    return w.config.xaxis.labels.formatter(i)
})
```

Sorry for the delayed response.
