### ISSUE TITLE
Multiple YAxis does not adjust grid width

### ISSUE THREAD

**Issue by brenkao** [apexcharts/apexcharts.js#843]
## Codepen
https://codesandbox.io/s/apexcharts-yaxis-bug-cjvoh
## Explanation
- What is the behavior you expect?
I expect the grid width to be reduced when more yaxis are added.
- What is happening instead?
The grid overlaps with the legend causing the xaxis to appear in the legend.
This is more noticeable in charts with larger widths.
- What error message are you getting?
No errors.

**Comment by junedchhipa** [comment]
I checked with v3.12.0 and I got the below result
![chart](https://user-images.githubusercontent.com/17950663/71781911-1f333300-2ffa-11ea-8a95-3e6b05212e8b.png)

The above output is valid, hence closing it.
