### ISSUE TITLE
Chart getting higher and higher

### ISSUE THREAD

**Issue by dipixx** [apexcharts/apexcharts.js#845]
# Codepen
https://codepen.io/dipixx/pen/zYOKrwK

# Explanation
The chart starts getting higher and higher in every browser when you start panning. In Firefox to get the same result you can just press the keyboard button Alt. The problem seems to be the 
`height: '100%'`
in the chart options.

**Comment by junedchhipa** [comment]
Wrap the chart element in a fixed height container and then apply `height: 100%` to the chart.

Working example - https://codepen.io/apexcharts/pen/pozEgOj
