### ISSUE TITLE
dataLabels formatter not working on bubble chart

### ISSUE THREAD

**Issue by taesfreitas** [apexcharts/apexcharts.js#846]
When you specify something in formatter for dataLabels, it does not work. If you enable dataLabels for this type of chart, it always shows the bubble size.

**Comment by junedchhipa** [comment]
This might have been fixed in recent releases as I cannot reproduce it.

When trying this
```javascript
dataLabels: {
  enabled: true,
  formatter: function(val) {
    return val + '$'
  }
}
```
It correctly renders the formatted value in the bubble.

Closing it.
