### ISSUE TITLE
Tooltip isn't displayed when the first series is hidden

### ISSUE THREAD

**Issue by rzds** [apexcharts/apexcharts.js#85]
I only tested this on a stacked area chart. I used 2 versions of apexcharts.js:
- one from the CDN
- one that I downloaded from https://apexcharts.com/downloads/apexcharts-bundle.zip

CDN: I've noticed that only when you hide the first series (Series A in the example below) the tooltip doesn't show anymore.
https://codepen.io/anon/pen/rZdgKv

Downloaded version: The tooltip shows but there is a problem on the first day of the interval because the x parameter in the formatter function is undefined.

![title](https://user-images.githubusercontent.com/1256878/45413481-fa3ae400-b681-11e8-93d3-8b2f69fe44bb.png)
```
tooltip: {    
        x: {    
            formatter: function (x) {
                if(typeof x==='undefined') {
                     return null;
                 } else {
                     return new Date(x).toCustomFormat();
                 }           
            }
        }
    }

**Comment by junedchhipa** [comment]
Thanks for reporting.
Yes, since 1.4.11 - I see that the tooltip doesn't behave correctly when series is shown/hide with the legend interaction.

I will also test with the custom `tooltip.x.formatter` function which you provided.

**Comment by junedchhipa** [comment]
Fixed it.

But couldn't reproduce the issue for `tooltip.x.formatter` which you mentioned. I don't get `x = undefined` when I hide the first series.

Please create a codepen with that issue so I can see what data you are using if the issue still persists after this patch.

**Comment by rzds** [comment]
Thanks for the fix. 
I just checked and the version available for download (the one with the formatter bug) is 1.0.0. Way too old. Maybe someone could put a newer version on apexcharts site.

**Comment by junedchhipa** [comment]
No worries.
I will upload the latest version for the ApexCharts website.

**Comment by rzds** [comment]
Awesome.
Can you check it now with the latest version on cdn? Just go to "Sep 6" after you hide Serie A. You'll see there's no date displayed in that tooltip.
https://codepen.io/anon/pen/rZdgKv

**Comment by rzds** [comment]
I did some more tests.
When I zoomed out this happens.
![a1](https://user-images.githubusercontent.com/1256878/45420443-d9c75580-b692-11e8-9bcf-c00754632cdf.png)

But when I move the mouse just a little...
![a2](https://user-images.githubusercontent.com/1256878/45420480-ecda2580-b692-11e8-8c5a-7788c3bd4da6.png)

Maybe this helps.

**Comment by junedchhipa** [comment]
Indeed, it will help.
Thanks for providing extra details!
