### ISSUE TITLE
Stacked and single/grouped column in combination

### ISSUE THREAD

**Issue by sanketkarandikar** [apexcharts/apexcharts.js#854]
Hello @junedchhipa, i struggled a lot to get this but at the time i just cant find any proper solution. I want to create a chart where 1 column is stacked with 2 dataSeries and 1 column is seperate. I have created a fiddle where i am showing three separate columns. Instead what i would like to do is stack first 2 data series and keep 3rd in separate column.
Codepen for the same - [https://codepen.io/sanket-karandikar/pen/OKaZYE](url)
Now how can i stack green and orange bar together and keep red separate?

TIA

**Comment by junedchhipa** [comment]
This feature is not available yet but may come in future.

**Comment by junedchhipa** [comment]
Closing as duplicate of #196
