### ISSUE TITLE
Add option tooltip.animation to disable tooltip animations

### ISSUE THREAD

**Issue by bf** [apexcharts/apexcharts.js#855]
**Is your feature request related to a problem? Please describe.**
Tooltip animations can only be disabled by manually adding CSS rules, as documented in this issue: https://github.com/apexcharts/apexcharts.js/issues/447

**Describe the solution you'd like**
Add an option `tooltip.animations` with default value `true`. If set to `false`, then disable all CSS animations and CSS class changes during showing of tooltip.

**Describe alternatives you've considered**
Alternative is to manually add the following CSS to your page:
```
.apexcharts-tooltip,
.apexcharts-tooltip.active,
.apexcharts-xaxistooltip,
.apexcharts-xaxistooltip.active,
.apexcharts-marker {
   transition: none;
}
```

Thank you for your consideration.

**Comment by suhaibmujahid** [comment]
I think recently the class `.active` got changed to `.apexcharts-active`:
```
.apexcharts-tooltip,
.apexcharts-tooltip.apexcharts-active,
.apexcharts-xaxistooltip,
.apexcharts-xaxistooltip.apexcharts-active,
.apexcharts-marker {
  transition: none;
}
```

**Comment by dexalorian** [comment]
morons
