### ISSUE TITLE
Align tooltip values to the right

### ISSUE THREAD

**Issue by bf** [apexcharts/apexcharts.js#856]
When creating a tooltip for a chart with multiple series, the labels and values are displayed all over the place. I would like to align the labels to the left side and the label values to the right hand side.

**Comment by bf** [comment]
The labels and values displayed in the tooltip can be aligned nicely by adding the following CSS to your project:

```
.apexcharts-tooltip-text {
    width: 100%;
}

.apexcharts-tooltip-y-group {
    display: flex;
    justify-content: space-between;
}
```

**Comment by Jelledb** [comment]
The above suggestion worked 
<img width="243" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/14248574/0b2af03e-75e8-4c80-8eaf-1af73cd39edf">

but somehow the `tooltip-marker` (the small colored circle) didn't get the right width anymore. I fixed it by:

```
.apexcharts-tooltip-marker {
  flex: 0 0 12px;
}
```
