### ISSUE TITLE
Add option legend.inverseOrder to match tooltip.inverseOrder

### ISSUE THREAD

**Issue by bf** [apexcharts/apexcharts.js#858]
We have the option to reverse order of tooltips by setting `tooltip.inverseOrder = true`.
I suggest we create the same flag for the legends, so we can set the same order of labels both for the tooltips and the legend.

Therefore I propose `legend.inverseOrder` flag to be added.

Please let me know if you are open to this suggestion, I will then author a pull request for this great project.

**Comment by junedchhipa** [comment]
Yes, sounds reasonable.

If you want to create a PR, go ahead :)
My suggestion would be to add a CSS class when the `legend.inverseOrder` is true and use that CSS class to change the styles.

Refer #850

**Comment by junedchhipa** [comment]
Ignore my CSS suggestion above.
I have done the change.

**Comment by bf** [comment]
Perfect, thank you. Please don't forget to update the docs accordingly!
