### ISSUE TITLE
In straight data line in line chart not showing in IE 11

### ISSUE THREAD

**Issue by alex-wanigasekara** [apexcharts/apexcharts.js#859]
In straight data line in line chart not showing in Internet Explorer 11. Ex : ( data: [3,3,3,3,3] )  
Here is the code pen example.  https://codepen.io/alex-wanigasekara/pen/zYOoExZ

Can you help please ?

**Comment by venil7** [comment]
I'm seeing this issue too, It's been a year, anyone can provide soma clarity on this bug?

**Comment by kylebradshaw** [comment]
I am hitting this right now. This is a serious bug. Any solution here?

**Comment by kylebradshaw** [comment]
YMMV, but I found a workaround that fixed the issue of a horizontal line in IE11 - tried making another ex but no one supports IE11 anymore (codepen, jsfiddle)

At any rate, my fix was for a horizontal data set like [3, 3, 3, 3, 3] I was able to get IE to render a horizontal line of imperceptible variation by just introducing some noise into the recordset

[3,3,3,3,3].map(v => v + ((Math.random() > 0.5) ? 0.0001 : -0.0001)); 

That was the nudge that IE11 needed to render the horizontal line, a hack for sure but expecting this bug to live on indefinitely. Hopefully it helps the next person

https://jsfiddle.net/kylebradshaw/h31obzx7/
