### ISSUE TITLE
Mobile: Impossible to pan/zoom selection/selection

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#86]
Touching the screen only permits to see the points on the yaxis. Maybe not if tooltip's shared property is set to false, it's sometimes non sense to set shared to false.

Also, this is certainly related to the fact that it's not well supported yet, but when touching and moving to try to get the value expected, on iOS it unselect the point really easily. As such, there's no other choice than removing toolbar for mobile users as it's frustrating.

**Comment by MarkGStacey** [comment]
I'll certainly second the importance of this - I love the zoom function and was really hopeful it'd be working the same on mobile but alas

**Comment by junedchhipa** [comment]
I couldn't provide the same experience on mobile, because the zooming/panning functionality was becoming a hindrance in displaying tooltips.
If you scroll on the chart currently, the tooltip is displayed following the touch gesture. The only possibility is to allow user pinch on the chart and get to the desired zoom/pan level. 

I will move this functionality up in the roadmap.

**Comment by balex25** [comment]
I really like to see more functions on the mobile line chart. Also, nice work @junedchhipa 👍

**Comment by rcoundon** [comment]
+1 for pinch as alternative to pan/zoom

**Comment by abuisman** [comment]
Panning doesn't work at all for me on both Firefox and Chromium.

When I try to pan, the chart flies to 1964 and I can't move from there.

**Comment by junedchhipa** [comment]
@abuisman The general panning issue which is related to #1287  is fixed. The patch will be released soon.

**Comment by abuisman** [comment]
Thanks. That is good news. Any idea how soon?

**Comment by aferreiramartinez** [comment]
Thanks in advance for your work. Is this feature going to be delivered soon? I think touch controls for tablet/mobile devices would be totally awesome.

**Comment by darshanDevrai** [comment]
@junedchhipa Thank you very much for the awesome library. Any ETA for the touch controls??

**Comment by cmcheatham** [comment]
Hi @junedchhipa, I am just going to echo @darshanDevrai and @aferreiramartinez . The charts are fantastic but it would great to see the touch controls working on IOS. I've thought about some work arounds in the meantime but is that still on the roadmap?

**Comment by mspinelli** [comment]
> I couldn't provide the same experience on mobile, because the zooming/panning functionality was becoming a hindrance in displaying tooltips.
> If you scroll on the chart currently, the tooltip is displayed following the touch gesture. The only possibility is to allow user pinch on the chart and get to the desired zoom/pan level.
> 
> I will move this functionality up in the roadmap.

What if I don't want a tooltip for mobile? Is there a way to configure tooltip vs pan/zoom being the mobile default?

**Comment by amtavari** [comment]
> @abuisman It was a major bug (related to #1287) which is fixed. The patch will be released soon.

Hi
When do you make patch available?

**Comment by SebstianSchwemer** [comment]
Any news on this topic?

**Comment by bridgecode** [comment]
Also still curious, or maybe a different chart recommendation that works well with mobile?

**Comment by SimonFavraud** [comment]
I would like this kind of features too, it would be amazing

**Comment by V1CTOR-cloud** [comment]
> I would like this kind of features too, it would be amazing

+1

**Comment by c0deMaster** [comment]
Still waiting for solution..

**Comment by rkeshwani** [comment]
I would prefer the pinch and zoom functionality over tooltips on mobile devices. Especially when displaying lots of data. Maybe make this configurable?

**Comment by AleXSR700** [comment]
+1

**Comment by SMKim94** [comment]
+1

**Comment by vandelpavel** [comment]
+1

**Comment by tpid-nalendro** [comment]
+1

> Still waiting for solution..

**Comment by AleXSR700** [comment]
Is this on the todo or will this not be pursued?
Mobile devices are increasingly important.

Would be nice also for all the home automation plattforms that use apexcharts :)

**Comment by cvjensen** [comment]
+1

**Comment by wakie92** [comment]
+1

**Comment by sakko80** [comment]
+1

**Comment by SebstianSchwemer** [comment]
+1

**Comment by mustafahafidi** [comment]
+1. Why is this closed?

**Comment by bridgecode** [comment]
Please reopen
+100

**Comment by havingfu** [comment]
+1

**Comment by matheo** [comment]
For the record, this seems included in the `v4.1.0` release:
https://github.com/apexcharts/apexcharts.js/releases/tag/v4.1.0

**Comment by bridgecode** [comment]
We can finally rest, gent. Thanks to everyone that made it possible!
