### ISSUE TITLE
Start Date doesn't display, while end date is displayed partially on x-Axis tickmark

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#861]
## Codepen

Modify [this codepen](https://codepen.io/vjakair/pen/oNvYwLr) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. 

## Explanation

- Starting tick mark & ending tick mark on x-axis should be displayed properly.
- What is happening instead?
Starting tick mark doesn't show up on x-axis, while ending tick mark is displayed partially.
- What error message are you getting?
No error message

![image](https://user-images.githubusercontent.com/8254178/63482670-596ebe80-c4b7-11e9-8430-ff9e159ebd47.png)

**Comment by irshadahmed** [comment]
Hi @junedchhipa Is there a work around to handle this ? Please advise.

**Comment by junedchhipa** [comment]
This is fixed in 3.12.0
