### ISSUE TITLE
Problem rendering sample code on site.

### ISSUE THREAD

**Issue by patrickmonteiro** [apexcharts/apexcharts.js#863]
Hello, there is a problem rendering the examples on the site. When we first tried it, it does not show the sample code. But after reloading a few times displays normally.

![image](https://user-images.githubusercontent.com/13258255/63642262-06e9f980-c693-11e9-978c-249114a9a335.png)

After f5:

![image](https://user-images.githubusercontent.com/13258255/63642269-1cf7ba00-c693-11e9-94d7-500412f15cfa.png)

**Comment by junedchhipa** [comment]
Fixed it. 
Thanks for the catch
