### ISSUE TITLE
Donut chart, show bordered hollow/transparent donut even when data is 0's

### ISSUE THREAD

**Issue by Rc85** [apexcharts/apexcharts.js#864]
When series contains 0, give us an option to show a donut that has a border but is hollowed/transparent.

Imagine a row with several donuts in it, each representing a type of data. If one donut have series of 0's, it would show nothing, making the design inconsistent.

**Comment by junedchhipa** [comment]
If you have 0 data, you can show a data-point with value 100 which will draw a round circle to keep the design consistent.

Here is the configuration you can use to achieve that.

```javascript
            series: [100],
            fill: {
                opacity: 0
            },
            stroke: {
                colors: ['#3C99BA']
            },
            dataLabels: {
                formatter: function(val) {
                    return ''
                }
            },  
            tooltip: {
                enabled: false
            },
```
