### ISSUE TITLE
tooltip colors don't respect fill color

### ISSUE THREAD

**Issue by danielschmitz** [apexcharts/apexcharts.js#865]
## Codepen

https://codepen.io/danielschmitz/pen/MWgpjNN

## Explanation

- What is the behavior you expect?
tooltip color and bar color are same, when fill.colors are set

- What is happening instead?
tooltip colors still using pallete color, over the fill property

- What error message are you getting?
no errors

Image:

![image](https://user-images.githubusercontent.com/1509692/63649222-64bd2680-c711-11e9-9cb3-eacfc90e39a8.png)

**Comment by junedchhipa** [comment]
If you want to have universal colors for everything, you need to define the main `colors` property like this


```javascript
options = {
   colors: ['#aa0000']
}
```
