### ISSUE TITLE
Area Chart uses old Max Date as starting point on redraw

### ISSUE THREAD

**Issue by yeagercmbpd** [apexcharts/apexcharts.js#866]
I've created a datepicker and variable selection process that filters json data prior to it being pushed to an array. It is then rendered in a date time area chart after a click event. I added a clear button which empties out all the arrays and series, however, when the chart is rendered with a new selection for a date earlier than the first selection, it draws the beginning of the line from where the first rendering ended, the whole way back to the beginning of the new axis. I've also tried .destoy() with the same results as updateseries and updateoptions. Any thoughts? images attached

![firstselect](https://user-images.githubusercontent.com/46506442/63687285-26d40700-c7d2-11e9-8c30-0a19b6c8848f.PNG)

![secondselect](https://user-images.githubusercontent.com/46506442/63687292-2c315180-c7d2-11e9-813d-27914a3e2895.PNG)

Thanks!

**Comment by junedchhipa** [comment]
I would appreciate a working codepen example.

**Comment by junedchhipa** [comment]
Closing as no response from the reporter and can't reproduce.
