### ISSUE TITLE
数据太多,当有1万条时加载慢

### ISSUE THREAD

**Issue by yjjind** [apexcharts/apexcharts.js#867]
数据太多,当有1万条时加载慢要15秒才能加载完成,官网中的案例25000条也很快,但在项目中却很慢

**Comment by junedchhipa** [comment]
Google translation of the above issue:
There is too much data. When there are 10,000 pieces, it takes 15 seconds to load and it can be loaded. The 25,000 cases in the official website are also very fast, but it is very slow in the project.


**Answer:**
Large data-points only work well in `line-charts` with no markers and also animation turned off. The example on the website has all heavy features turned off and hence loads faster.
