### ISSUE TITLE
yaxis in Radar Chart.

### ISSUE THREAD

**Issue by nunovalenciaIBM** [apexcharts/apexcharts.js#869]
Knows someone how to change the yaxis at radar chart? I need the label write the next numbers (0, 5, 10, 25, 50, 100, 200)

Thanks

**Comment by junedchhipa** [comment]
The yaxis labels in a radar chart are generated on a linear scale.
So, a range of 0 to 200 with tickAmount set to 5 will generate 0, 50, 100, 150, 200.

But, if you still want custom labels, you can check out the [yaxis.labels.formatter](https://apexcharts.com/docs/options/yaxis/#formatter) property

**Comment by nunovalenciaIBM** [comment]
Thanks ;)
