### ISSUE TITLE
Label layout problem on vue-stacked-columns-chart 

### ISSUE THREAD

**Issue by MarcelKendy** [apexcharts/apexcharts.js#871]
----------------------------------------------------------------------------------------------------------

**My versions:**
_**"apexcharts": "^3.6.8",
"vue-apexcharts": "^1.3.4",**_

----------------------------------------------------------------------------------------------------------
### My label on hovering the column is white with a gray background, making it impossible to read:

![image](https://user-images.githubusercontent.com/32130772/63791386-c4fac680-c8d1-11e9-9315-a3432d8b2f85.png)

![problem](https://user-images.githubusercontent.com/32130772/63791018-e60ee780-c8d0-11e9-8668-3a7cd767c815.png)
----------------------------------------------------------------------------------------------------------

**My template:**
![image](https://user-images.githubusercontent.com/32130772/63791171-400fad00-c8d1-11e9-99c7-f25c847c9e88.png)

----------------------------------------------------------------------------------------------------------

**My chartOptions:**
chartOptions: {
        chart: {
          stacked: true,
          toolbar: {
            show: false
          },
          zoom: {
            enabled: false
          }
        },
        responsive: [
          {
            breakpoint: 480,
            options: {
              legend: {
                position: 'bottom',
                offsetX: -10,
                offsetY: 0
              }
            }
          }],
        plotOptions: {
          bar: {
            horizontal: false
          }
        },
        xaxis: {
          type: 'category',
          categories: [],
          labels: {
            style: {
              colors: 'black'
            }
          }
        },
        legend: {
          position: 'right',
          offsetY: 40
        },
        fill: {
          opacity: 3
        }
      }

----------------------------------------------------------------------------------------------------------

**Comment by junedchhipa** [comment]
The tooltip inherits its color from the parent element.

You can override it easily

```css
.apexcharts-tooltip {
  color: #333
}
```
