### ISSUE TITLE
Distributed colors for dataLabels?

### ISSUE THREAD

**Issue by TomDeSmet** [apexcharts/apexcharts.js#872]
**Is your feature request related to a problem? Please describe.**
I'd like my labels to be colored exactly like the bars they are linked with.

**Describe the solution you'd like**
If I set something like this for my labels:
```
dataLabels: {
  style: {
    colors: [ "#AABBCC", "#112233" ]
  },
}
```
I'd like to have a `distributed: true` setting that acts the same as setting colors for separate bars inside the same series.
It is the default behaviour for axis labels but doesn't seem to work for dataLabels.

**Comment by junedchhipa** [comment]
Thanks for the suggestion.
I have fixed it and it will be working in the next version (3.11.0).

To use distributed colors for data-labels in a bar chart, you will have to do this.


```javascript
options = {
  colors: ['#f3f4f5', '#fff'],
  plotOptions: {
    bar: {
      distributed: true,
    }
  },
  dataLabels: {
    style: {
      colors: ['#f3f4f5', '#fff']
    }
  }
}
```
