### ISSUE TITLE
Animation on donut fails if series contains a 0

### ISSUE THREAD

**Issue by nabeelmehmood** [apexcharts/apexcharts.js#873]
I ran into this issue working on a project with the dependencies: 
    "apexcharts": "^3.8.5",
    "react-apexcharts": "^1.3.3",

I haven't tested the behavior with other chart types but I reproduced it with donuts in the codepen attached.

If the series for the chart contains a 0 in the array, the animation fails to go through smoothly and renders the whole chart instantly. 

https://codepen.io/nabeelmehmood/pen/XWrRLRR

Chart 1 has incorrect behaviour
Chart 2 works as intended because it doesn't contain a 0

**Comment by junedchhipa** [comment]
Fixed in 3.14.0
