### ISSUE TITLE
How to get your help?

### ISSUE THREAD

**Issue by parkyeonkyu** [apexcharts/apexcharts.js#874]
Our company is using apexcharts.
but there is some issue, so we're gonna purchase premium support.
if we buy it, could you support new function?

we need a function about customizing xaix label value(datetime, we want to show every monday ) and scrollbar option(if we need to show long term, we should show them with scrollbar)

please reply us, then we're gonna decide buy it or not
have a nice day :)

**Comment by junedchhipa** [comment]
@parkyeonkyu 
The premium support plans are to get help with the existing functionality of ApexCharts.
Implementing new features is not covered in those premium plans.

You can still post feature requests in GitHub issues, but I cannot guarantee of implementing them immediately.

Thank you for your interest.
