### ISSUE TITLE
inner label on donut chart doesn't appear

### ISSUE THREAD

**Issue by ElNath11** [apexcharts/apexcharts.js#875]
Using this code

        this.state = {

          plotOptions: {
              pie: {
              size: undefined,
              customScale: 0,
              offsetX: 0,
              offsetY: 0,
              dataLabels: {
                // These are the percentage values which are displayed on slice
                offset: 0 // offset by which labels will move outside
              },
              donut: {
                size: '85%',
                background: '#fff',
                labels: {
                  // These are the inner labels appearing inside donut
                  show: false,
                  name: {
                    show: true,
                    fontSize: '16px',
                    fontFamily: 'Helvetica, Arial, sans-serif',
                    color: '#666666',
                    offsetY: -10
                  },
                  value: {
                    show: true,
                    fontSize: '20px',
                    fontFamily: 'Helvetica, Arial, sans-serif',
                    color: '#666666',
                    offsetY: 10,
                    formatter: function (val) {
                      return val
                    }
                  },
                  total: {
                    show: true,
                    label: 'Total',
                    color: '#373d3f',
                    formatter: function (w) {
                      return w.globals.seriesTotals.reduce((a, b) => {
                        return a + b
                      }, 0)
                    }
                  }
                }
              }
            },

            dataLabels: {
              enabled: false
            },

            responsive: [{
              breakpoint: 480,
              options: {
                chart: {
                  width: 200
                },
                legend: {
                  show: true
                }
              }
            }],
            colors: ['#e74c3c', '#2ecc71', '#3498db', '#9b59b6', '#1abc9c'],
            labels: ['Change Plan', 'Price', 'Location', 'Others', 'Poor of Services'],
            legend: {
                position: 'right',
                offsetY: 0,
                height: 230,
              formatter: function(seriesName, opts) {
                  return seriesName + ":  " + opts.w.globals.series[opts.seriesIndex]+'%'
              },
            },
          },
          series: [30, 20, 10, 10, 30],
        }
      }

	render(){
		return(
		<div id="chart">
            <Chart options={this.state.plotOptions} series={this.state.series} type="donut" width="600" />
          </div>
		);
	}
}

and then I got my chart looks like this,

![image](https://user-images.githubusercontent.com/16522776/63988875-679c8a80-cb08-11e9-8512-9cd1dee6593a.png)

anyone here can help me, how to add inner label inside donut chart to come out. 
Like this chart bellow

![image](https://user-images.githubusercontent.com/16522776/63988941-a6cadb80-cb08-11e9-82ac-44ff32841517.png)

**Comment by junedchhipa** [comment]
```javascript
options = {
  plotOptions: {
    pie: {
      donut: {
        labels: {
          show: true
        }
      }
    }
  }
}
```

https://apexcharts.com/docs/options/plotoptions/pie#labels

**Comment by rakhman01** [comment]
> ```js
> options = {
>   plotOptions: {
>     pie: {
>       donut: {
>         labels: {
>           show: true
>         }
>       }
>     }
>   }
> }
> ```
> 
> https://apexcharts.com/docs/options/plotoptions/pie#labels

    options: {
      plotOptions: {
        pie: {
          donut: {
            labels: {
              show: true,
              name: {
                show: true,
              },
              value: {
                show: true,
              },
              total: {
                show: true,
                showAlways: true,
                label: "Total",
              },
            },
          },
        },
      },
      series: [70, 30],
    },
