### ISSUE TITLE
remove a particular series dynamically

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#878]
Is there any way to remove a particular series from multiple series dynamically.I tried this one. but it misbehave. 

```
chart.updateSeries(removeSeries(1));

function removeSeries(seriesIndex){
    var arr = chart.w.globals.series;

    if (seriesIndex > -1) {
           arr.splice(seriesIndex, 1);
    }
    return arr;
}
```

a method to remove a particular series will be really appreciate.

**Comment by junedchhipa** [comment]
Data transformation is better to be handled on the user's side.
The `updateSeries` method accepts dynamic number of series. If you have 3 series and later update with 2 series, it will work fine.
