### ISSUE TITLE
Expose export filename as definable property on config object

### ISSUE THREAD

**Issue by timhere** [apexcharts/apexcharts.js#88]
I'd like to be able to pass a variable into a config object which would be used as the filename prefix when downloading a chart svg image.

Currently, the filename is fixed to something like `apexcharts-12a3bcde.svg` by [this line in modules/Exports.js](https://github.com/apexcharts/apexcharts.js/blob/1252cc9e212f1caa2ba5ad3ef2eff6e1f5c29dd4/src/modules/Exports.js#L35):

```js
downloadLink.download = 'apexcharts-' + w.globals.cuid + '.svg'
```

**Comment by junedchhipa** [comment]
An option named `options.chart.id` already exists.
So, instead of creating a new one, we can use that and I will have to just change that particular line to use `options.chart.id` instead of cuid.

**Comment by junedchhipa** [comment]
Now, chart.id will be used as a filename.
Will be available in 1.5.2 release

**Comment by timhere** [comment]
Many thanks for sorting this out so quickly, much appreciated.

**Comment by cnokobe** [comment]
Is there a way to put some separator symbols like '-' or '_' in the export, because currently these symbols are replaced by 'x'?

**Comment by yunusunver** [comment]
> Is there a way to put some separator symbols like '-' or '_' in the export, because currently these symbols are replaced by 'x'?

Can anyone fix this problem?
