### ISSUE TITLE
'colors' in TypeScript type declaration for stroke is string but should be string[]

### ISSUE THREAD

**Issue by mark-langer** [apexcharts/apexcharts.js#880]
## Explanation
 
Hi there, I'm trying to be brief. It would be great if you could fix this!
* What is the behavior you expect?
Typescript reflects all available options correctly.

* What is happening instead?
The types declaration has stroke.colors declared as simple `string` but this should be an array of strings `string[]` according to the [docs](https://apexcharts.com/docs/options/plotoptions/bar/).

It should be adjusted to `ApexStroke.colors: string[]`.

**Comment by junedchhipa** [comment]
You're correct.
Fixed it.
