### ISSUE TITLE
The promise returned from render() gets resolved before animations are finished

### ISSUE THREAD

**Issue by msageryd** [apexcharts/apexcharts.js#884]
## Code

```
var options = {
  chart: {
    height: 380,
    width: "100%",
    type: "line",
    animations: {
      speed: 10000
    }, 
  },
  series: [
    {
      name: "Series 1",
      data: [1,2,3  ]
    }
  ]
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render().then(()=>window.alert('finished'));
```

## Explanation

I don't know what to expect, but it would sure help me if the returned promise was resolved **after** the animations have finished.

I'm using (trying to use) Apexcharts in jsreport (http://jsreport.net). Since the target format is PDF I have no use for animations, in fact they give me trouble because the charts will not be finished in time for the rendered PDF. 

There are two solutions, but none of them are working. I want to use solution no 1, but I have no clue of why stuff disappears as soon as I disable animations.

### 1. disable animations in Apexcharts.
If I set animations.enabled=true or animations.speed=0 I get very unpredictable results. Most of the time everything after the chart div disappears.

If I set animations.speed=1 it works sometimes. It seems to depend on how complicated the rest of the report is.

If I set speed=100 it works consistently, but I don't dare to trust this "hack".

If I set speed=1000 only part of the chart will be included in the PDF. This leeds to solution no 2.

### 2. Wait until the animations have finished before printing to PDF
In jsreport there is a way to tell chrome-pdf when everything is rendered so the PDF printing can start safely. The concept is to set `window.JSREPORT_READY_TO_START = true`. This is how I do it:

```chart.render().then(()=>window.JSREPORT_READY_TO_START = true);```

With Highcharts and Charts.js this variable can be set in their respective "after animation event". In Apex, this won't work since the promise resolves before the animations are finished.

**Comment by junedchhipa** [comment]
I will add a new event `animationEnd`soon.
