### ISSUE TITLE
Hide null bars

### ISSUE THREAD

**Issue by evgenyelyashevich** [apexcharts/apexcharts.js#887]
hide null bars or how to solve this problem with caps before animation?

![image](https://user-images.githubusercontent.com/54266063/64193890-7bd4e480-ce86-11e9-97f4-8e8f780ee4ee.png)

![image](https://user-images.githubusercontent.com/54266063/64194263-58f70000-ce87-11e9-8c6d-4519d4343384.png)

**Comment by junedchhipa** [comment]
Please provide a working codepen example to easily reproduce it.
Closing as not able to reproduce.
