### ISSUE TITLE
Add Inner dataLabels in radar chart

### ISSUE THREAD

**Issue by CalyphoZz** [apexcharts/apexcharts.js#890]
**Is your feature request related to a problem? Please describe.**
Hello, first of all thanks work the awesome work.

I wanted to add inner dataLabel in my radar chart like "this":

![image](https://user-images.githubusercontent.com/12392555/64259088-b4c59580-cf28-11e9-8dfb-2b3707b88257.png)

but i couldn't find a way to do it. Do you think add this fonctionnality ?

thanks !

**Comment by junedchhipa** [comment]
Work in progress.
![fc3noor2 (8)](https://user-images.githubusercontent.com/17950663/71632981-766e8780-2c37-11ea-98f5-7eca8b2eabd3.png)

It will be released soon.
