### ISSUE TITLE
Discrete square markers not working with size 0

### ISSUE THREAD

**Issue by emilianodelvalle** [apexcharts/apexcharts.js#892]
## Codepen

https://codepen.io/emilianodelvalle/pen/xxKPzbz

## Explanation

For some reasons, I need to "hide" some markers in my line charts. I was using discrete markers with size 0 successfully. Unfortunately when I change the markers to square shape, a small marker still appears in the chart.

It can be seen in the example in codepen. Two lines, one with criclle, one with sqaure, two different behaviors for "size 0" discrete martkers

**Comment by emailnikola** [comment]
What we discovered is that assigning new value to array markers.discrete doesn't apply if new array has length less than current markers.discrete array. To fix this apply following logic:

while (markers.discrete.length > 0) {
   markers.discrete.pop()
}

Object.assign(markers.discrete, newMarkersDiscreteArray)
