### ISSUE TITLE
Remove Whitespace from radialBar Apexchart

### ISSUE THREAD

**Issue by wasifHafeez** [apexcharts/apexcharts.js#894]
## Codepen
Hi, I am new to Apexcharts and I need to remove the extra whitespace around this radialBar chart, I have attached the images which I am facing right now and what I want to achieve within the image.
(https://codepen.io/wasifhafeez/pen/JjPyGNa?editors=1010
![without-space](https://user-images.githubusercontent.com/54930837/64320624-6243b200-cfd8-11e9-876d-756174ef805c.png)
![withspace](https://user-images.githubusercontent.com/54930837/64320625-62dc4880-cfd8-11e9-85a4-4ddc7f3933ee.png)

**Comment by SyedAzeemJaved** [comment]
Issue not fixed, facing the same issue again.
