### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by PrimozRome** [apexcharts/apexcharts.js#895]
Can a chart have transparent background? How to achieve it? I tried this but nothing gave me the desired result:

```
options: {
   chart: {
      background: 'transparent'
    }
}

options: {
   chart: {
      background: 'none'
    }
}

```

**Comment by wasifHafeez** [comment]
It is already transparent, and if you change the color, it changes, see [here](https://codepen.io/wasifhafeez/pen/gOYoOwm)

**Comment by PrimozRome** [comment]
@wasifHafeez thank a lot, got it !

**Comment by wasifHafeez** [comment]
Could you please share the link of the chart? Which you are trying to use.

> @wasifHafeez thank a lot, got it !

Is the issue resolved?

**Comment by PrimozRome** [comment]
@wasifHafeez not quite. Just tested it and my result is white background... Here is my options object:

```
      options: {
        chart: {
          height: 100
        }
      }

```

<img width="1002" alt="Screenshot 2019-09-05 at 13 29 39" src="https://user-images.githubusercontent.com/1180467/64338153-48f33380-cfe1-11e9-8bb6-07640e3e4919.png">

**Comment by wasifHafeez** [comment]
please share a live example, codepen or any other live example with Vue.js

**Comment by PrimozRome** [comment]
OK I need time to prepare codepen project. Basically here is my full code and it renders what you see on above picture with white background:

<template>
  <div id="statistics">
       <vue-apex-charts
            slot="value" 
            type="donut"
            class="chart"
            height="200"
            style="position: absolute; right: -70px; top: -40px;"
            :options="options"
            :series="series"
       />
  </div>
</template>

<script>
import VueApexCharts from 'vue-apexcharts'

export default {
  name: 'ProductStatistics',

  components: {
    VueApexCharts
  },

  data() {
    return {
      series: [44, 55, 41, 17, 15, 22],
      options: {
        labels: ['Automotive', 'Aerospace', 'Power & Energy', 'Industrial', 'Military', 'Civil Engineering'],
        chart: {
          height: 100
        }
      }
    }
  }
}
</script>

If I change to this I get:

```
  data() {
    return {
      series: [44, 55, 41, 17, 15, 22],
      options: {
        labels: ['Automotive', 'Aerospace', 'Power & Energy', 'Industrial', 'Military', 'Civil Engineering'],
        chart: {
          background: 'red',
          height: 100
        }
      }
    }
  }

```
<img width="670" alt="Screenshot 2019-09-05 at 13 56 34" src="https://user-images.githubusercontent.com/1180467/64339762-029fd380-cfe5-11e9-83c0-90f929c015c7.png">

**Comment by PrimozRome** [comment]
@wasifHafeez you can close this. It was my stupid mistake. Sorry for the inconvenience.

**Comment by rishabbahal9** [comment]
> 
> ```
> options: {
>    chart: {
>       background: '0'
>     }
> }
> ```

**Comment by rishabbahal9** [comment]
Use `background: '0'` 
**At-least this works for me**


```
chart: {
          type: 'bar',
          height: 350,
          background: '0'
        },
```
