### ISSUE TITLE
Feature Request: Candlesticks

### ISSUE THREAD

**Issue by DVSoftware** [apexcharts/apexcharts.js#9]
Hi, it would be nice if this library could support candlesticks chart, and perhaps other financial charts

**Comment by junedchhipa** [comment]
Don't have any immediate plans to implement these.
The financial charts require a lot of work and are out of the scope for the moment.
Thank you for the suggestion though :)

**Comment by junedchhipa** [comment]
Reopening this as I got a lot of requests for this.

Will be provided in the next major release. It won't be a breaking change as most of the barChart code will be reusable. Just thinking of how the user will provide the input.
I am guessing OHLC values in y property of the `series.data` would work.

Thanks for the suggestion.

**Comment by junedchhipa** [comment]
An update on this one.

Candlestick's progress is going well, and I have just finished the initial version.
I will merge with the master soon, here is a small glimpse of the candlestick in ApexCharts

![candlestick-chart](https://user-images.githubusercontent.com/17950663/45097984-ab50f400-b141-11e8-85ef-b6f95157787d.gif)

**Comment by junedchhipa** [comment]
Released v1.5.0 which includes candlestick charts.
https://apexcharts.com/javascript-chart-demos/candlestick-charts/
