### ISSUE TITLE
zoomed event call problem

### ISSUE THREAD

**Issue by atoy40** [apexcharts/apexcharts.js#90]
Hello,

I'm using apexcharts 1.5.0 release and trying to play with the zoomed event.
It seems the event is only call when you use the selection zomming, but never when you use the zoom-in/zoom-out button

Anthony.

**Comment by junedchhipa** [comment]
@atoy40 Thanks for the catch, just added the event to zoomin/zoomout as well.
Will be available in v1.5.2
