### ISSUE TITLE
Unable to see the data on the Stacked Columns chart when the data is too small. 

### ISSUE THREAD

**Issue by MarcelKendy** [apexcharts/apexcharts.js#900]
**My versions:
"apexcharts": "^3.6.8",
"vue-apexcharts": "^1.3.4",**

When the differences between the datas on stacked columns charts are too big, you can`t see the numbers on the smaller columns, like this:

https://prnt.sc/p1x342

There is any quick solution to this, like putting the number **above** the column instead inside when its too small to fit? 

My chartOptions:
chartOptions: {
chart: {
stacked: true,
toolbar: {
show: false
},
zoom: {
enabled: false
}
},
responsive: [
{
breakpoint: 480,
options: {
legend: {
position: 'bottom',
offsetX: -10,
offsetY: 0
}
}
}],
plotOptions: {
bar: {
horizontal: false
}
},
xaxis: {
type: 'category',
categories: [],
labels: {
style: {
colors: 'black'
}
}
},
legend: {
position: 'right',
offsetY: 40
},
fill: {
opacity: 3
}
}

**Comment by junedchhipa** [comment]
```javascript
plotOptions: {
  bar: {
     dataLabels: {
        hideOverflowingLabels: false
     }
  }
}
```

**Comment by caio-2k** [comment]
Hello!

Sorry, but the same occurs to me:

![image](https://user-images.githubusercontent.com/59366705/198308039-d89e5d16-d50f-4427-97e4-03cfaaad0359.png)

There's any way to fix it? I've already tried to put `hideOverflowingLabels` to false and it didn't work out as I expected.

**Comment by Mundzir77** [comment]
is it solve?

**Comment by Astha-Anand** [comment]
Any update or any solution for above issue, we are also facing similar issue.  I've already tried to put hideOverflowingLabels to false and it didn't work out as I expected.

**Comment by cn-2k** [comment]
> Any update or any solution for above issue, we are also facing similar issue. I've already tried to put hideOverflowingLabels to false and it didn't work out as I expected.

I've tried use logarithmic scale on chart, but dont work also, check my issue: https://github.com/apexcharts/apexcharts.js/issues/3456

I changed my chart library to ECharts (works wonderfully)
