### ISSUE TITLE
Chart re-renders when display is toggled in tabs and accordion

### ISSUE THREAD

**Issue by blocksera** [apexcharts/apexcharts.js#902]
We've put apexcharts inside an accordion and it re-renders whenever it is toggled. Its slightly ruining the experience so we wish it can be fixed in any way.

https://prnt.sc/p2xo56

The first chart here is Chart.js and the next is apexchart. Notice how chart.js chart is stable and apexchart just flickers.

**Comment by junedchhipa** [comment]
Whenever the container around apexcharts gets changed, the chart re-renders.
I will provide a new property `chart.redrawOnParentResize` which you can turn off to prevent this behavior.
