### ISSUE TITLE
Sort inside Shared Tooltip 

### ISSUE THREAD

**Issue by brfer8** [apexcharts/apexcharts.js#903]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a option in "tooltip" where we can sort the order by values

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jkpubsrc** [comment]
Indeed. That issue I was trying to solve for the last to hours - unsuccessfully. Apparently it doesn't seem to be possible to sort the values in the tooltip. (Which renders the tooltip quite useless in my case.)

I write this comment here to indicate that this would is a quite important feature!

**Comment by luffy-taro** [comment]
`tooltip:{
      // inverseOrder: true,
      // shared: true,
      custom: function ({ series, seriesIndex, dataPointIndex, w }) {
        let title = w.globals.tooltip.tooltipTitle.outerHTML;
        let items = "";
        const ttItems = Array.from(w.globals.tooltip.ttItems);
        
        // sort or modify the order of ttItems with respect to series data using dataPointIndex

        
        // build final tooltip markup
        ttItems.forEach((ttItem) => {
          items = items + ttItem.outerHTML;
        });
        
        // create a container for tooltip
        const customTooltipContent = document.createElement("div");
        customTooltipContent.innerHTML = title + items;
        return customTooltipContent.outerHTML;
      },

      container: {
      }
    },`

I solved this by copying default markup for tooltip and returning it from custom tooltip option. However, it seems to reset to rendering the default tooltip for complex modifications which is fixed by adding container.

**Comment by cedricve** [comment]
exactly fixed it like this, sorting was missing in @luffy-taro  example:
    
    tooltip:{
        // inverseOrder: true,
        // shared: true,
        custom: function ({ series, seriesIndex, dataPointIndex, w }) {
          let title = w.globals.tooltip.tooltipTitle.outerHTML;
          let items = "";
          const ttItems = Array.from(w.globals.tooltip.ttItems);
          
          // sort or modify the order of ttItems with respect to series data using dataPointIndex
          ttItems.sort((a, b) => {
            const elementA = a as HTMLDivElement;
            const elementB = b as HTMLDivElement;
            // Read out element with classname "apexcharts-tooltip-text-value"
            const valueA = elementA.getElementsByClassName("apexcharts-tooltip-text-value")[0].innerHTML;
            const valueB = elementB.getElementsByClassName("apexcharts-tooltip-text-value")[0].innerHTML;
            // Convert to number values for a and b 
            const numberA = parseInt(valueA);
            const numberB = parseInt(valueB);
            return numberB - numberA;
          });
          
          // build final tooltip markup
          ttItems.forEach((ttItem) => {
            // cast to HTLMDivElement
            const ttItemElement = ttItem as HTMLDivElement;
            items = items + ttItemElement.outerHTML;
          });
          
          // create a container for tooltip
          const customTooltipContent = document.createElement("div");
          customTooltipContent.innerHTML = title + items;
          return customTooltipContent.outerHTML;
        },
  
      },
