### ISSUE TITLE
Different width for bars depends on datetime

### ISSUE THREAD

**Issue by m50434** [apexcharts/apexcharts.js#904]
Hi, 
as you can see in the picture every bar has the same width.

![Unbenannt](https://user-images.githubusercontent.com/24473301/64490207-e4dba400-d25a-11e9-90e2-c8fd120554e3.JPG)

The values of the bars based on measures between two timestamps (in the picture you can see that the hooverd bar has a measure-time from 03:00:10 - 03:14:56).

Now it would like to get that the bar starts exactly at the first timestamp (03:00:10) and ends at the second (03:14:56).
I know the main position of the bar is oriented at the first timestamp by default but it would be nice if there would be this option for different width for the bars.

Maybe its possible to do this over the serial data:
Current Version:
series: [{
          data: [
            [timestamp,value],
            [timestamp2,value],
...

new:

series: [{
          data: [
            [timestampStart1, timestampEnd1,value],
             [timestampStart2, timestampEnd2,value],
...

I hope I could make my wishes clear.

**Comment by gsabetta** [comment]
I also need this feature, I would like to add that when you have many items in your series that are too close from one another the bars start overlapping, if anyone knows how to deal with this I would highly appreciate a solution

**Comment by junedchhipa** [comment]
In my opinion, providing custom widths for bars in a datetime xaxis will result in unpredictable behavior as the width of the bar is calculated based on how many bars can fit in the given timescale. 

If you have 2 timestamps, and a single value, you can look into [timeline charts](https://apexcharts.com/javascript-chart-demos/timeline-charts/multi-series/), but keep in mind that they are rendered horizontally.
