### ISSUE TITLE
Poor scale with heatmap

### ISSUE THREAD

**Issue by SumNeuron** [apexcharts/apexcharts.js#905]
## Codepen

Modify [this codepen](https://codepen.io/apexcharts/pen/bxzgZJ) to demonstrate the problem clearly, just fork it and paste the resulting codepen in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

If you are using vue-apexcharts, and want to create a demo in Vue environment, use [CodeSandbox Vue template](https://codesandbox.io/s/pwwz8009n0)
If you are using react-apexcharts, and want to create a demo in React environment, use [CodeSandbox React template](https://codesandbox.io/s/6yoqonyo7r)

## Explanation

- What is the behavior you expect?
Heatmap doesn't lag system
- What is happening instead?
Total lag
- What error message are you getting?
None

Heatmap of 5 series with 500 points each.

**Comment by junedchhipa** [comment]
2500 points will result in 2500 dom elements in a heatmap chart which will likely result in poor performance.
ApexCharts heatmap is not the optimal chart type for so many datapoints.

**Comment by SumNeuron** [comment]
I am aware that it is a lot of cells. However, I can get good performance with my d3 maps. It is your interactivity that is lagging behind. So I wanted to bring it to your attention
