### ISSUE TITLE
Long labels cause JavaScript error

### ISSUE THREAD

**Issue by Remo** [apexcharts/apexcharts.js#906]
I've got a chart where in some cases we have very long labels. Usually apexchart cuts them to not break anything, but I assume that doesn't work if the label would be longer than the whole chart.

You can see it here:
https://codepen.io/ortic/pen/XWrZxyV

If you shorten the first label the chart will show up.
Right now it fails with these errors:

```
apexcharts:6 Error: <foreignObject> attribute height: A negative value is not valid. ("-22.975609756097562")
value @ apexcharts:6
apexcharts:6 Error: <svg> attribute height: A negative value is not valid. ("-22.975609756097562")
```

**Comment by junedchhipa** [comment]
If the legend position is set to `legend.position: right`, then the remaining space is not enough for chart to draw.

Hence, to use long labels in legend, you should set legend.position to bottom

```javascript
legend: {
  position: 'bottom'
}

```

**Comment by Remo** [comment]
Shouldn't apexcharts catch that and at least cut off the label instead of crashing with a JavaScript error?
