### ISSUE TITLE
mixed chart with stacked bars and line series - incorrect line draw

### ISSUE THREAD

**Issue by miuosh** [apexcharts/apexcharts.js#907]
I noticed that when I have mixed stacked chart with bars and line series, the line drawings are stacked.
I got 2 line series. Second line drawing does not correspond to provided values. I get it that chart type is stacked but it should apply only for bar (or column) series.

## Codepen
Here is example:
https://codesandbox.io/s/react-basic-example-o3erk

## Explanation

- What is the behavior you expect?
Draw not stacked lines. Values in tooltip are correct but drawing is not.
- What is happening instead?
Lines series are stacked.
- What error message are you getting?
No error.

**Comment by alejandroeclair** [comment]
BUMP
this is a recurring issue, here's another pen you can use to test:
https://codepen.io/l1qu1d1c3/pen/eYBWWWW
the blue line should be below the orange line as per the values.

**Comment by MarcelFranken** [comment]
No update? This issue is still present.

**Comment by aminebelmahi** [comment]
No updates?

**Comment by ahvincent** [comment]
I had this same issue and it was due to how I had my axes defined. I was defining a separate axis for each series for the bars, when I needed to have them share the same axis. This page from their docs helped, under the section "3 series with 2 scales" https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/

**Comment by aminebelmahi** [comment]
> I'm still facing with this issue

Nothing has been merged yet

See [here](https://github.com/apexcharts/apexcharts.js/pull/3477)
