### ISSUE TITLE
Auto-scale y-axis on zoom feature does not work when using toolbar zoom buttons

### ISSUE THREAD

**Issue by ArnauBlanch** [apexcharts/apexcharts.js#908]
I was testing the auto-scale y-axis functionality on a zoomable line chart and it works fine when zooming by doing a selection with the mouse, but this functionality does not seem to work when zooming by using the zoom-in/zoom-out buttons of the chart toolbar.

Due to this, the only way to change the axis when zooming out is by resetting the selection (home button on the toolbar).

I hope you can take a look at this, thanks 😄

**Comment by junedchhipa** [comment]
Yeah, that was a bug.
Fixed it.
