### ISSUE TITLE
Data Labels missing on stacked column charts with negative values

### ISSUE THREAD

**Issue by jhadenfeldt** [apexcharts/apexcharts.js#909]
## Codesandbox

Here's a link showing the issue: [https://codesandbox.io/s/react-basic-example-8zrui](https://codesandbox.io/s/react-basic-example-8zrui). The example uses react, but I was able to observe the issue in Vue as well.

## Explanation

_- What is the behavior you expect?_
I expected dataLabels to be visible on the negative columns

_- What is happening instead?_
There are no dataLabels visible on the negative columns

_- What error message are you getting?_
No error message

**Comment by astronati** [comment]
+1

**Comment by junedchhipa** [comment]
Can you please provide a minimal example? The provided example doesn't have any negative values.

**Comment by astronati** [comment]
![Screenshot from 2020-01-05 17-01-53](https://user-images.githubusercontent.com/2708431/71782670-1c761500-2fdd-11ea-8a08-513997a3b56d.png)
This is an example.

Pink bar contains negative values.

**Comment by junedchhipa** [comment]
Please provide a working [codepen](https://codepen.io/apexcharts/pen/xYqyYm)

**Comment by fengtan** [comment]
Here is one: https://codepen.io/fengtan/pen/mdypRmd

It looks like datalabels are missing only if *all* values of the series are negative. In the example above the values are `[-10, -10]`, but if I change that to `[-10, 10]` then they all show up: https://codepen.io/fengtan/pen/QWwadgp

**Comment by junedchhipa** [comment]
Thank you for the demo, will be addressed soon.

**Comment by alexxbetancourt** [comment]
Hi @junedchhipa, This issue still occurs in the current version, there are no labels on negative values. I am using version 3.23.1 from https://cdn.jsdelivr.net/npm/apexcharts
Here is a screenshot
![image](https://user-images.githubusercontent.com/48101673/105898979-b2615100-5fdf-11eb-9516-69e579a4234d.png)

**Comment by Jarkovato** [comment]
Hi @junedchhipa I have the same problem as @alexxbetancourt, plz tell me if there is any solution

![problem](https://user-images.githubusercontent.com/62695620/113399100-52ed3c00-93a8-11eb-8e9d-854888f516c5.JPG)
