### ISSUE TITLE
Chart Configuration is not worked

### ISSUE THREAD

**Issue by kinjalgodavale** [apexcharts/apexcharts.js#910]
lineCap: "round" is not worked in "donut" Chart.
I want space between stroke in Stroke Gauge Chart.

I want to make my Charts as like attached image file.

// Donut Chart
  // ---------------------
  var donutChartOption = {
    chart: {
      width: 265,
      type: 'donut',
    },
    dataLabels: {
      enabled: false
    },
    series: [80, 30, 60],
    labels: ["Social", "Email", "Search"],
    stroke: {
      width: 0,
      lineCap: 'round',
    },
    colors: [$primary, $info, $warning],
    plotOptions: {
      pie: {
        donut: {
          size: '90%',
          labels: {
            show: true,
            name: {
              show: true,
              fontSize: '15px',
              colors: $sub_label_color,
              offsetY: 20,
            },
            value: {
              show: true,
              fontSize: '26px',
              fontFamily: 'Rubik',
              color: $label_color,
              offsetY: -20,
              formatter: function (val) {
                return val
              }
            },
            total: {
              show: true,
              label: 'Impression',
              color: $gray_light,
              formatter: function (w) {
                return w.globals.seriesTotals.reduce(function (a, b) {
                  return a + b
                }, 0)
              }
            }
          }
        }
      }
    },
    legend: {
      show: false
    }
  }

  var donutChart = new ApexCharts(
    document.querySelector("#donut-chart"),
    donutChartOption
  );

  donutChart.render();

// Growth Radial Chart
  // --------------------
![chart configuration](https://user-images.githubusercontent.com/53047704/64594728-30628f00-d3ce-11e9-9543-393678b18e0f.png)

  var growthChartOptions = {
    chart: {
      height: 200,
      type: 'radialBar',
      sparkline:{
        show: true
      }
    },
    grid: {
      show: false,
    },
    plotOptions: {
      radialBar: {
        size: 100,
        startAngle: -135,
        endAngle: 135,
        offsetY: 40,
        hollow: {
          size: '60%',
        },
        track: {
          strokeWidth: '90%',
        },
        dataLabels: {
          value: {
            offsetY: -10,
            color: '#475f7b',
            fontSize: '26px'
          },
          name: {
            fontSize: '15px',
            color: "#596778",
            offsetY: 30
          },
        }
      },
    },
    colors: [$danger],
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'dark',
        type: 'horizontal',
        shadeIntensity: 0.5,
        gradientToColors: [$primary],
        inverseColors: true,
        opacityFrom: 1,
        opacityTo: 1,
        stops: [0, 100]
      },
    },
    stroke: {
      dashArray: 3
    },
    series: [78],
    labels: ['Growth'],
  }

  var growthChart = new ApexCharts(
    document.querySelector("#growth-Chart"),
    growthChartOptions
  );

  growthChart.render();

Thanks,

**Comment by junedchhipa** [comment]
Sorry, rounded edges in individual donut slice are not achievable with ApexCharts.
The examples on ApexCharts website cover most of the functionalities of ApexCharts. So, if you don't find anything there, there is a possibility it is not achievable.
