### ISSUE TITLE
Stock Heatmap

### ISSUE THREAD

**Issue by danielschmitz** [apexcharts/apexcharts.js#911]
Hi all,

 needs a "stock heatmap" with one single serie, like this image in the docs (heatmap > reverse negative):

![image](https://user-images.githubusercontent.com/1509692/64646747-09b45080-d3ee-11e9-922c-269e4f654090.png)

is that possible create a heatmap like this image?

or just like this:

![image](https://user-images.githubusercontent.com/1509692/64647067-b1318300-d3ee-11e9-9e17-4f7729c8ceb0.png)

**Comment by junedchhipa** [comment]
Sorry, the image in the docs gives a wrong impression of a treemap.
But, a treemap is currently not supported in ApexCharts.
Closing as Treemap suggestion is already made in #646
