### ISSUE TITLE
Styling of line chart data series

### ISSUE THREAD

**Issue by maasha** [apexcharts/apexcharts.js#913]
After going over the documentation, examples and interwebs it baffles my why ApexChart - which is otherwise a thing of beauty - apparently don't allow you to do the most elementary plotting tasks for a line chart:

1. I would like to have more marker shape options than circle and square.
2. I would like to be able to set the marker shape in the series object and not on some global marker object.
3. Likewise, I would like to be able to color a series in the series object and not on the global color array.
4. And dashed lines - again something to set per series ...

Are there any design reasons why this is not possible. Or can we have any of these options soonish? :o)

**Comment by junedchhipa** [comment]
The reason you won't find many options in the `series` array is that I decided to keep the styling configuration separate from the data.
It is easier to update the series this way as stuffing all data in `series` and then updating/mutating the `series` may introduce more problems.

Also, the `series` array accepts different formats for different chart types.
For pie/donut, the `series` just accepts numbers like `series: [30, 40, 60]` but for a line chart, the `series` accepts `series: [{ data: [30, 50, 60] }]`.

These decisions were taken in the very beginning of the creation of the library and hence at this point, it will require big changes :)

Regarding more marker shapes, I will think of an option to allow the user to inject custom SVG shapes.

**Comment by maasha** [comment]
Right - custom SVG shapes (or icons) would be great!

So is there a way to have different markers on each series?

**Comment by junedchhipa** [comment]
Currently, only `square` and `circle` are supported.
If you want to have different shapes for different series, just provide an array of strings instead of a single value.

```javascript
markers: {
  shape: ['circle', 'square']
}
```

**Comment by maasha** [comment]
OK gotit :o) Now we just need some more shapes; asterisk, triangles, daggers, crosses, etc ...

**Comment by maasha** [comment]
Hm, according to typescript, `markers.shape` only accepts `'circle'` or `'square'` - not an array.

**Comment by junedchhipa** [comment]
You're correct.
That was a mistake which I just fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/4ca6b35bebccd9574f5b7e590dbb49a86551ce5d)

Will be available in the next release.

**Comment by maasha** [comment]
OK, I have gotten to the point where I need more shapes. How may I help?

**Comment by jboysen** [comment]
I would also like to see more marker shapes, or even custom shapes like font awesome as @maasha suggests. Charts with lots of series quickly become messy ;-)

**Comment by maasha** [comment]
*bump* :o)

**Comment by junedchhipa** [comment]
Sorry, I have been very busy fixing other bugs and features. I once tried introducing more marker shapes but faced some blockers and hence couldn't continue.
Can we close this ticket in favor of #868?

**Comment by maasha** [comment]
Yes, sure. Keep up the good work!

**Comment by hearchad** [comment]
@junedchhipa 
It looks like drawMarker in Graphics.js would be very easy to extend with something like...
`if (opts.jsx) then render opts.jsx`
In this way, people can render anything and style it however they like.

**Comment by junedchhipa** [comment]
@hearchad It's not possible to inject HTML elements into SVG directly. You have to use `<foreignElement>` for that. And when that is used, other things need to be considered.

**Comment by hearchad** [comment]
Wow!  You're fast.  Thanks!  I was editing... but given your response, how about something like

if (opts.shape === 'svg') then render opts.svg, etc.?

**Comment by junedchhipa** [comment]
Yes, that's a better idea.

**Comment by hearchad** [comment]
I'm in a hurry and so, attempting to edit this myself... I was using ReCharts but it renders too slowly React and it appears apex will be much faster, but I absolutely must have custom markers.  Did you like opts.shape === 'svg' or the earlier suggestion where opts.shape() could be a function call?

**Comment by julienlaglasseadhzm** [comment]
Hi, still not possible to add new shape of markers ?
