### ISSUE TITLE
Zoomable line chart type='category'

### ISSUE THREAD

**Issue by catnip123** [apexcharts/apexcharts.js#920]
I was using apexcharts line chart for visual representation and the X axis had timestamp in nanoseconds, the datetime type only works till microseconds and the numeric type has also restricted digit size of 16, this I could not use both. The category type can be used but it is not zoomable which is something that I require, kindly provide zooming in category

**Comment by binoculars88** [comment]
I agree! Zooming shouldn't be limited to datetime. I have a chart that can contain +100 values. Zooming options would make it much more readable. Anyone knows a workaround to get zooming working on category types?

**Comment by thirukumaran13** [comment]
I am also looking for the same feature. Can anyone help ?

**Comment by michaeljakob** [comment]
Could you please fix this? Please enable zooming for type='category' ! That's a truly critical feature for us

**Comment by junedchhipa** [comment]
Released v3.15.0 with the zooming enabled on category x-axis.
Example - https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/

Doc: https://apexcharts.com/docs/zooming-in-category-x-axis/
