### ISSUE TITLE
Overlapping columns on datetime x axis

### ISSUE THREAD

**Issue by gsabetta** [apexcharts/apexcharts.js#924]
[codesandbox](https://codesandbox.io/embed/react-basic-example-gyc9n)

Awesome work with the library!

I'm having a hard time having columns on a datetime x axis and making sure the don't overlap, I'm working on a interactable chart and it ruins the experience. AFAIK there's no way of controlling the widh of collumns with 2 different values like it's proposed [here](https://github.com/apexcharts/apexcharts.js/issues/904)

Is there a work arround to avoid this overlapping? Thanks in advance

**Comment by DMOAbove** [comment]
This problem happens on last version. on datetime x.axis it is overlapping when in the same date. And with datetime the stack bar doesnt work either? I tried to bypass the overlap issue.
