### ISSUE TITLE
dataLabels is not custom in BubbleChart?

### ISSUE THREAD

**Issue by tudiantuan** [apexcharts/apexcharts.js#925]
I read document custom datalabels https://apexcharts.com/docs/options/datalabels/. I want dataLabels follow name series: bubble "blue" 39 -> Bubble1
![Capturssssssse](https://user-images.githubusercontent.com/39153315/65130912-8c5d9100-da28-11e9-9af4-73becb0835a5.PNG)

**Comment by junedchhipa** [comment]
You're right.
Custom dataLabels formatter is ignored in Bubble Charts currently.
I will fix it soon.

**Comment by alex-gla** [comment]
@junedchhipa when your fix will be available in the npm?
