### ISSUE TITLE
About css codes and svg generated in DOM.

### ISSUE THREAD

**Issue by C3maLi** [apexcharts/apexcharts.js#927]
## Codepen
[Codepen](https://codepen.io/CemaLi/pen/zgxZzp)
On a page where I do not use Apexchart, the css code belonging to Apexchart appears in the DOM. However, SVG forms. Is this normal?

## Explanation
- What is the behavior you expect?
Apex Chart css codes and SVG codes do not appear on the page where I do not use Apex Chart.
Apex libraries are called on this page.

- What is happening instead?
no

- What error message are you getting?
no

**Comment by junedchhipa** [comment]
If you import ApexCharts through `<script>` tag, the global apexcharts CSS will be added on the whole page.
The CSS properties start from `.apexcharts` so I doubt they will conflict with your styles.
