### ISSUE TITLE
Performance and markers.

### ISSUE THREAD

**Issue by maasha** [apexcharts/apexcharts.js#928]
I want to plot two data series: one with 10 data points with markers and one with +5000 data points and no markers. Using:

```
markers: {
   size: [5, 0],
}
```

the rendering is dead slow?

**Comment by m50434** [comment]
did you turned on datalabels? This made my datasets (with just 500 entries) quite slow !!!
Wihtout datalabels its fast (anyway I dont know why it takes so much time to print the datalabels).

**Comment by maasha** [comment]
Data labels and animations are turned off.

**Comment by junedchhipa** [comment]
I cannot reproduce this anymore.
Markers with size 0 are not rendered now.

Closing this.
Please let me know if the problem still persists.
