### ISSUE TITLE
Set max xaxis value is not showing

### ISSUE THREAD

**Issue by pnemi** [apexcharts/apexcharts.js#93]
Hello,

when I set `options.xaxis.max` to certain Date, it doesn't get rendered (although it's value is being sent to my xaxis labels formatter).

**Comment by junedchhipa** [comment]
Can you provide a codepen example, please?

**Comment by pnemi** [comment]
Here's a slightly modified version of codepen you sent me earlier.
https://codepen.io/anon/pen/EepyEO

[These stocks data](https://apexcharts.com/samples/assets/stock-prices.js) are from 13 Nov 2017 to 8 Dec. I desperately need to display first and end (min and max) xaxis datetime value. I see no 08 Dec on xaxis and when I set `xaxis.xmax` to `new Date("06 Dec 2017").getTime()` that time is not being displayed either.

**Comment by junedchhipa** [comment]
I think - you want something like this, right?
![screen shot 2018-09-16 at 12 56 16 am](https://user-images.githubusercontent.com/17950663/45589887-613eee00-b94b-11e8-9677-cd6a6ea976b0.png)

You will have to turn off the automatic timescale generation and use the custom `xaxis.labels.formatter` function along with setting the `xaxis.tickAmount` property.

For eg., I used moment.js to format dates and set the tickAmount to 2
```javascript
xaxis: {
    type: 'datetime',
    tickAmount: 2,
    min: new Date('13 Nov 2017').getTime(),
    max: new Date('08 Dec 2017').getTime(),
    labels: {
        formatter: function(val) {
            return moment(new Date(val)).format("DD MMM");
        }
    }
},
```

**Comment by junedchhipa** [comment]
Please use the latest version apescharts@1.5.2 for it to work correctly as I have made some changes related to this.

**Comment by pnemi** [comment]
Works perfectly how I wanted to. Thank you so much for it.

**Comment by farih96** [comment]
hello @junedchhipa, can you please show me how did you show those x and y line line , ( support , anno test ) if you still remeber of course. thank you

**Comment by netham91** [comment]
If anyone is still looking at this, here is the update:

```
xaxis: {
    type: 'datetime',
    tickAmount: 2,
    min: new Date('13 Nov 2017').getTime(),
    max: new Date('08 Dec 2017').getTime(),
    labels: {
        formatter: function(val, timestamp) {
            return moment(new Date(timestamp)).format("DD MMM");
        }
    }
},
```

**Comment by AshokLKumawat** [comment]
Im using apex zoomable timeseries , as im selection particular date  its doesn't show me 24 hour, also its show me pervious day time,
<img width="911" alt="image" src="https://user-images.githubusercontent.com/100796177/208294141-e5d140cd-a819-4808-9cb7-ce7855d95e24.png">
