### ISSUE TITLE
sparkline title/subtitle margin not changing

### ISSUE THREAD

**Issue by zacwillis** [apexcharts/apexcharts.js#932]
I am trying to change the margin on the title attribute for my sparkline charts. It appears that no vertical margin is being set. I have my title text size set to 40px and my subtitle size set to 14px. When the charts are created the title over laps the subtitle no matter what the margin is set to. Does anyone know why?
<img width="818" alt="Screen Shot 2019-09-23 at 3 36 14 PM (1)" src="https://user-images.githubusercontent.com/36970370/65464854-1dad7880-de18-11e9-9e44-939cb267088f.png">

**Comment by junedchhipa** [comment]
Sorry for the late response.
Fixed the issue, will be working fine in the next release.

You can also try setting `title.offset` / `subtitle.offsetY` to get some spacing in between.
