### ISSUE TITLE
how to update Apexchart (line) on a click

### ISSUE THREAD

**Issue by bensweeney** [apexcharts/apexcharts.js#934]
i was hoping that there was a way i could update my line chart by clicking on a bar from a bar chart. i was able to define a function that will return data from the bar chart:

```
      dataPointSelectionHandler(event, chartContext, config) {
         let year = this.barOptions.xaxis.categories[config.dataPointIndex];
         this.lineSeries.data = yearlyData[year]
    }
```

the lineSeries.data will return an array that has data i want graphed on my line chart.

however using Apexcharts line chart, it doesn't seem to acknowledge that i defined my lineSeries.data array in my method. or is this a rendering problem. here's my lineSeries:

```
    lineSeries: [
      {
        name: "Yearly Photo Total",
        data: []
      }
    ]
```

![stackoverflow1](https://user-images.githubusercontent.com/37051429/65558316-0c816c00-deeb-11e9-8fb6-1d5360873d5f.png)

what am i missing here?

**Comment by junedchhipa** [comment]
Please post a full [codepen](https://codepen.io/apexcharts/pen/xYqyYm) demo.

**Comment by bensweeney** [comment]
@junedchhipa that example is almost exactly what I am looking to replicate; however, I didn't want it to be that specific (was hoping for separation between the line and bar chart & also wanted a line chart to update when clicked on a bar)

i can't seem to replicate it via codepen

is there like a force re-render? i know apexcharts has updateSeries() and render() functions but i can't figure out how to use them
