### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by gustawdaniel** [apexcharts/apexcharts.js#937]
**Is your feature request related to a problem? Please describe.**
In chrome I see warning 

```
apexcharts.esm.js:7 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Describe the solution you'd like**
Problem was described here

https://github.com/angular/components/issues/4221

And it seems that we should use

```
document.addEventListener('touchstart', handler, {passive: true});
```

**Describe alternatives you've considered**
It can be problem from one of dependencies of apexchart. I can't find `touchstart` in source code of apexcharts.

**Additional context**
I attaching screenshot

![Screenshot from 2019-09-26 12-19-41](https://user-images.githubusercontent.com/16663028/65680792-f80eb200-e057-11e9-9c35-e2fceace0a30.png)

I experienced problem using vue.

**Comment by andersevenrud** [comment]
I hit this one as well, and it spammed my console heavily due to using it on a dashboard with lots of charts that periodically updates.

After doing some grepping based on the stack trace messages I narrowed it down to the "zoom" functionality. I don't need this at the moment, so disabling it made these messages disappear:

```
// options
{
  chart: {
    zoom: {
      enabled: false
    }
  }
}
```

**Comment by osxisl** [comment]
> I hit this one as well, and it spammed my console heavily due to using it on a dashboard with lots of charts that periodically updates.
> 
> After doing some grepping based on the stack trace messages I narrowed it down to the "zoom" functionality. I don't need this at the moment, so disabling it made these messages disappear:
> 
> ```
> // options
> {
>   chart: {
>     zoom: {
>       enabled: false
>     }
>   }
> }
> ```

I have the same issue, but disabling zoom didn't help.

**Comment by alenamm** [comment]
I have same issue, disabling zoom does not help. This was first reported almost a year ago. Any progress?

**Comment by dtrouillet** [comment]
Like @alenamm and @osxisl, disabling zoom not work, and it's not a solution 😢

**Comment by simonmaass** [comment]
can confirm the same problem - any news here?

**Comment by sutthikiat1** [comment]
I also ran into this problem, please tell me how to fix it.
