### ISSUE TITLE
updating tooltips on line chart options

### ISSUE THREAD

**Issue by bensweeney** [apexcharts/apexcharts.js#940]
i did not find a way to keep the current tooltip format and remote the 'series' name from the tool tip; i know some of this can be modified in the CSS class, but I don't want to modify the look of the current tooltip.. just want less information displayed
![gimp1](https://user-images.githubusercontent.com/37051429/65712317-9fd1b300-e04b-11e9-9dba-e68092b2719d.jpg)

**Comment by junedchhipa** [comment]
```javascript
title: {
   y: {
    title: {
      formatter(seriesName) {
        return ''
      }
    }
  }
}
```
https://apexcharts.com/docs/options/tooltip/#ytitleformatter
