### ISSUE TITLE
dataPointSelection event with multiple series

### ISSUE THREAD

**Issue by BBLN** [apexcharts/apexcharts.js#943]
I believe dataPointSelection event should at least provide the nearest hovered value for every data series.
For example, if the crosshair currently points on some values, the same values should be exported somehow in the chart state.
Otherwise, clicking on specific values could be problematic when there is overlapping between paths. (In my chart of lines and bars, I need the values on both y axes from one user click)

Currently the hack I used to bypass it, is to use the y label formatter for the tooltip module, and keep the last seen value for every series. If we could provide event better suited for this, or export the getNearestValue from Tooltip module, that might also work.

**Comment by duecknoah** [comment]
Any update here? I'm also wondering the same thing :)
