### ISSUE TITLE
Distributed bar chart with legend

### ISSUE THREAD

**Issue by egisberto** [apexcharts/apexcharts.js#944]
**Is your feature request related to a problem? Please describe.**
I can't do a simple bar chart with distributed values with legends.

this is the first solution:
![image](https://user-images.githubusercontent.com/2185033/65879200-d1a58b00-e365-11e9-8fed-d1f29591e46c.png)

The first thing I try is to set the distributed option to false and make some adjustments in set series data. The result was:
![image](https://user-images.githubusercontent.com/2185033/65882522-90b07500-e36b-11e9-8a35-3d7ae6200f11.png)

**Describe the solution you'd like**
I want to hide the categories in the x-axis and show the legends for it.

The expected result is:
![image](https://user-images.githubusercontent.com/2185033/65882570-a58d0880-e36b-11e9-9e27-4be8e85d4c76.png)

**Comment by y-nk** [comment]
is there a codepen we can help you with ?

**Comment by junedchhipa** [comment]
Sorry, this was not possible previously.
I have just fixed this behaviour to show legends for distributed bar charts.

**Comment by mensetyo** [comment]
how to set multi series but single legend ?
