### ISSUE TITLE
stroke is not available for scatter/bubble chart

### ISSUE THREAD

**Issue by alex-gla** [apexcharts/apexcharts.js#945]
https://apexcharts.com/docs/options/stroke/

stroke is no available for buble chart

**Comment by junedchhipa** [comment]
For scatter/bubble charts, use `markers` stroke option.

```javascript
markers: {
    strokeColors: '#fff',
    strokeWidth: 2,
    strokeOpacity: 0.9,
    strokeDashArray: 0,
    fillOpacity: 1,
}
```

Docs for markers: https://apexcharts.com/docs/options/markers/
