### ISSUE TITLE
wrong xaxis labels generation

### ISSUE THREAD

**Issue by y-nk** [apexcharts/apexcharts.js#947]
## Codepen

https://codepen.io/y_nk/pen/MWgMGNP

## Explanation

When using series with `[x, y]` point format, xaxis labels are calculated in a wrong way.

In this codepen, you can see : 

`dates` in a generated array for 2019-10-01 to 2019-10-07
`serie` is a pseudo random generated serie with data points for 2019-10-01, 2019-10-03 and 2019-10-05

In the current codepen, there's no use for `dates` for now, but ideally it should be provided in `xaxis.categories`. regardless of this, xaxis labels are wrongly generated. You can see the logs i've provided in the `<pre>` block and compare the x values in `serie` and what is given as `val` to `xaxis.labels.formatter`

- What is the behavior you expect?
ideally, `xaxis.categories` is taken in consideration for `xaxis.type === 'datetime'` so we can use `dates` instead of auto-generated labels.

- What is happening instead?
labels are wrongly generated.

- What error message are you getting?
none

**Comment by junedchhipa** [comment]
If you want complete control over datetime generation, along with the `formatter` function, you can use `xaxis.min`, `xaxis.tickAmount` and `xaxis.max` like below

```javascript
xaxis: {
  type: 'datetime',
  min: new Date('2019-10-01 GMT').getTime(),
  max: new Date('2019-10-10 GMT').getTime(),
  tickAmount: 10,
  labels: {
    formatter: (val, series, index) => {
      return new Date(val).toString()
    }
  }
}
```
