### ISSUE TITLE
xaxis tickAmount breaks bar distribution

### ISSUE THREAD

**Issue by y-nk** [apexcharts/apexcharts.js#948]
## Codepen

https://codepen.io/y_nk/pen/LYPKrKy

## Explanation

when explicitely setting `tickAmount = 0`, the width of the bars in a bar charts becomes incorrect.
you can comment the line to see the difference (or set to `1`).

- What is the behavior you expect?
if should behave at least the same as `tickAmount = 1`

- What is happening instead?
bars of the charts are wrongly large

- What error message are you getting?
none

**Comment by junedchhipa** [comment]
`tickAmount: 0` means you don't want any xaxis label.
In such a case, you can hide the whole xaxis.

Hence, checking for `tickAmount: 0` is not required.

**Comment by y-nk** [comment]
@junedchhipa that doesn't explain why the width of bars are differents, does it ?
