### ISSUE TITLE
Datetime xaxis is one hour off 

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#95]
![deepin-screen-recorder_select area_20180913134958](https://user-images.githubusercontent.com/17592744/45486723-64c05280-b75c-11e8-9277-33be2be80a23.gif)

As you can see, the first tick is off one hour in space. Zooming in would show that a tick hold the date of the day.
On the gif, the 01:00 tick is the date, and the 02:00 is 01:00 (then the off hour is on all next ticks).

I use this formatter on xaxis : 

``` 
labels: {
            datetimeFormatter: {
              year: 'yyyy',
              month: 'MM / yy',
              day: 'dd/MM/yy',
              hour: 'HH:mm'
            }
          }
```

That shootage is done in 1.4.6 and may be corrected since then.

**Comment by louis123562** [comment]
If anyone is still facing this issue, check https://github.com/apexcharts/apexcharts.js/issues/110#issuecomment-633227332

**Comment by eng-gabrielcardoso** [comment]
I have the same issue on the candlestick chart, is off by 1 hour
