### ISSUE TITLE
strokeWidth is not used for the bubble chart 

### ISSUE THREAD

**Issue by GlabzW** [apexcharts/apexcharts.js#950]
Good day everyone,

stroke width is not used for the bubble chart, i find the reason of the error and create pull request 

https://github.com/apexcharts/apexcharts.js/pull/949/commits/4a81efb8fc950f6ad924b45560f2f1da1c35b9d1

**Comment by GlabzW** [comment]
```
   markers: {
      size: 6,
      strokeWidth: 10,
      strokeColors: [
        '#e5e5a1',
        '#bfe0af',
        '#a3ccc5',
        '#e5e5a1',
        '#bfe0af',
        '#a3ccc5',
      ],
    },
```

you can check this by adding such code to the standard bubble chart demo code
https://apexcharts.com/javascript-chart-demos/bubble-charts/simple/

**Comment by junedchhipa** [comment]
Fixed it.
To use stroke-width in bubble charts, you will need to do it this way

```javascript
stroke: {
  width: 3
}
```
