### ISSUE TITLE
Add linebreaks on noData text

### ISSUE THREAD

**Issue by igormartimiano** [apexcharts/apexcharts.js#951]
I had a problem where I had a big text to be displayed when noData was set. On mobile, I needed it to break in several lines so the entire text would be displayed correctly. Couldn't find a way to it using the lib, had to do some js append <*tspan>s to take care of that after it was rendered.

I'm not exactly familiar to SVGs but I've first imagined that an ideal solution would be to specify a max-width to the the <text> where noData is displayed, although I later found out that this isn't possible: https://stackoverflow.com/a/16701952/7837637. 
According to that same answer, we could use <*textArea>.. but that would also limit the support for SVG 1.1.
So, maybe passing a max character length prop for every line until it breaks? We could use it to render multiple <*tspan> which would do the job. Don't know if that is exactly ideal either.

Thank you

**Comment by junedchhipa** [comment]
Multi-line texts in SVG are a bit tricky and the solution provided in your stack-overflow link is not very feasible.
`<foreignObject>` is something to consider but it doesn't have support in IE.

**Comment by junedchhipa** [comment]
From the next version, you will be able to add multiline texts in the nodata options.

```javascript
noData:{
  text: ['No data available', ' Please try later']
}
```

![Screen Shot 2020-01-04 at 5 17 54 PM](https://user-images.githubusercontent.com/17950663/71765077-2bde5b00-2f16-11ea-8ee0-e144de7018ad.png)

**Comment by igormartimiano** [comment]
Good one! Thank you 😄

**Comment by MauricioPaez** [comment]
Hi there! It would be nice if you could update the ApexNoData interface to follow this functionality

![image](https://user-images.githubusercontent.com/26752783/118827825-5d916100-b882-11eb-85bf-f06f7e57ddeb.png)
