### ISSUE TITLE
toggleDataPointSelection does not toggle a selection with valid data points

### ISSUE THREAD

**Issue by qbunt** [apexcharts/apexcharts.js#954]
## Codepen
https://codepen.io/qbunt/pen/GRRKKRo

## Explanation
The `toggleDataPointSelection` method in Vue or anywhere else yields the following console warning
```
toggleDataPointSelection: Element not found with a valid reference
```
Followed by an error

```
Uncaught TypeError: Cannot read property 'node' of undefined
    at i.value (apexcharts:6)
    at pen.js:18
```

- What is the behavior you expect?

> `toggleDataPointSelection` should select a datapoint and highlight that point in the chart

- What is happening instead?

> An error and no selection of the valid datapoint & a valid index

- What error message are you getting?

```
Uncaught TypeError: Cannot read property 'node' of undefined
    at i.value (apexcharts:6)
    at pen.js:18
```

**Comment by junedchhipa** [comment]
You should use the `mounted` event of ApexCharts to allow the chart to finish rendering before you can call `toggleDataPointSelection`

```javascript
chart: {
    events: {
      mounted: function(chartContext, config) {
         // ...
       },
    }
}
```

**Comment by ionutmihai1995** [comment]
@junedchhipa , this not working for pie/donut chart.

I tried:
`mounted: function(chartContext, _){
              chartContext.toggleDataPointSelection(0);
            }`
