### ISSUE TITLE
Brush selection area doesn't follow the target chart on panning

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#957]
In the brush chart, the brush selection area doesn't follow the target chart. Is there any way to move this selection alone target chart?

the default selection moves. but when i select the area then it does not move. like official demo.

![deepin-screen-recorder_Select area_20191003190847](https://user-images.githubusercontent.com/28239287/66129668-308f2c80-e612-11e9-8676-61d8645b7b8f.gif)

I want to move the brush selection if I pan the target chart.

**Comment by junedchhipa** [comment]
Yeah, the brush should move when the panning occurs in the other chart.
I will take a look soon.

**Comment by pavpavtan** [comment]
Any updates on this? This is a bit of a blocker and I could not find a way to work around this - it also seems to disconnect brush chart with zoom in and out buttons as well as put default home at what was selected by user - would be nice to be able to control that behaviour.

**Comment by junedchhipa** [comment]
Sorry for the delay, the issue is fixed now and will be shipped with the next patch release.
