### ISSUE TITLE
Bar chart with 'datetime' x-axis shows wrong date

### ISSUE THREAD

**Issue by Carniatto** [apexcharts/apexcharts.js#958]
## CodePen
https://codepen.io/Carniatto/pen/WNNeGmR

## Explanation

- What is the behavior you expect?
My first data point is for '2019-01-01' so I spect the `x-axis` to show this date. Also, it should show two ticks since I've set `tickAmount: 2`

![Screenshot 2019-10-03 at 15 43 59](https://user-images.githubusercontent.com/1366831/66132067-c87e1d80-e5f4-11e9-9ca7-d40111fb0120.png)

- What is happening instead?
The first tick on the `x-axis` is one day before and the second tick is not shown

- Note
Changing the type of the chart to `line` solves the date problem

**Comment by Carniatto** [comment]
@junedchhipa Do you have any idea how I could work this around?

**Comment by junedchhipa** [comment]
In datetime column charts, the xaxis gets adjusted to accommodate the first column. And hence, you may see 1-day prior date.

To force change the first tick in the x-axis, you can do
```javascript
xaxis: {
    type: 'datetime',
    min: new Date('2019-01-01').getTime()
}
```
but this will crop the first column and result into untidy visualization.

**Comment by Carniatto** [comment]
Thanks @junedchhipa 
This worked for us like a charm.

![Screenshot 2019-10-08 at 11 55 23](https://user-images.githubusercontent.com/1366831/66386456-938e1400-e9c2-11e9-9f75-95c4809789e8.png)

**Comment by ganySA** [comment]
I have this issue with area charts....
Is there no other work around for this - why would it adjust it like this?

**Comment by Animatr** [comment]
I had the same issue and I solved it formatting the datetime labels with custom function. I'm not good at js. So if there is a better way to do it I don't know. 
```
type: 'datetime',
labels: {
   formatter: function (value) {
      const formatter = new Intl.DateTimeFormat('en-US', { day: '2-digit', month: 'short' });
      const formattedDate = formatter.format(value);
      return formattedDate 
      }, 
 }
```
