### ISSUE TITLE
Apex chart with bootstrap class

### ISSUE THREAD

**Issue by gouravlath** [apexcharts/apexcharts.js#959]
Hi
We are using apexchart. When parent div is having bootstrap grid class (like col-md-6), apexchart is not taking up width:100% but it works fine when parent width is set in px. It would be great if you could provide a solution for the issue?

**Comment by junedchhipa** [comment]
ApexChart's default width is set to take up `100%` whether fixed or percentage values.
Sorry for the late response, please provide a codepen if you still face issues.
