### ISSUE TITLE
Documentation for theme.palette string incorrect

### ISSUE THREAD

**Issue by timhere** [apexcharts/apexcharts.js#96]
In the ["Themes" section of the documentation](https://apexcharts.com/docs/themes/) the following instructions are given:

> Setting a palette can be done by.
```js
theme: {
  palette: 'colorPalette1' // upto colorPalette10
}
```

I believe it should read `palette1` instead of `colorPalette1`. 

The codepen examples specify the correct string value, however.

**Comment by junedchhipa** [comment]
Thank you for the catch.
Fixed!

**Comment by qroft** [comment]
It would be awesome if you could add an example on where to insert the theme attribute. I defined "palette4" in my bar chart but all bars are light blue. Would be great to have some more detail in the documenation. Greetings and thanks!
