### ISSUE TITLE
Zoom In/Out using mouse wheel

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#960]
@junedchhipa Is there any way to zoom in/out using mouse wheel? I need these features. Or how can I call apex chart build in handleZoomIn/handleZoomOut function from outside? help please...

**Comment by haroflow** [comment]
This would be nice, but I think it should be configurable to turn it off as well... In pages with lots of charts it might get difficult to scroll the page normally.

Thanks!

**Comment by elbasan** [comment]
any update on this?

**Comment by DBESSIERE** [comment]
It's an indispensable function today. 
It's surprising that it's not supported

**Comment by brianlagunas** [comment]
I agree. This is a must have feature. Reopening.

**Comment by OsmnShkh** [comment]
Agreed here, would be useful for the timeline charts especially

**Comment by justinyng** [comment]
Thanks for reopening this feature request, I also agree it would be a very useful feature.

**Comment by gyoogle** [comment]
Not yet?? I want this feature

**Comment by SerhatUzbas** [comment]
+1

**Comment by Sandr0oo** [comment]
Please tell me if this functionality has appeared?

**Comment by RDUser-dev** [comment]
I agree. This is a must have feature. please Reopening.

**Comment by fikrihanda** [comment]
+ 1

**Comment by jbiosca78** [comment]
I got tired of waiting for this, 4 years and nobody cares about a simple mouse option.. I'm moving to flotcharts

**Comment by abruu** [comment]
need this feature !!

**Comment by mrosminin** [comment]
+1

**Comment by hokascha** [comment]
use this, note var `chart` is the chart instance after it is rendered.

```
document.querySelector("#your-chart").addEventListener('wheel', function(event) {
    event.preventDefault(); // Prevent scrolling the page

    // Calculate the relative position of the mouse on the chart
    var chartRect = chart.w.globals.dom.baseEl.getBoundingClientRect();
    var mouseX = (event.clientX - chartRect.left) / chartRect.width;

    var currentMinX = chart.w.globals.minX;
    var currentMaxX = chart.w.globals.maxX;
    var totalX = currentMaxX - currentMinX;

    // Determine zoom factor
    var zoomFactorIn = 0.1; // Adjust this value as needed for zooming in
    var zoomFactorOut = 0.9; // Significantly larger factor for zooming out
    var zoomRange;

    var newMinX, newMaxX;
    if (event.deltaY < 0) {
        // Zoom In
        zoomRange = zoomFactorIn * totalX;
        var midPoint = currentMinX + mouseX * totalX;
        newMinX = midPoint - zoomRange / 2;
        newMaxX = midPoint + zoomRange / 2;
    } else {
        // Zoom Out
        zoomRange = zoomFactorOut * totalX;
        newMinX = currentMinX - zoomRange / 2;
        newMaxX = currentMaxX + zoomRange / 2;
    }

    // Constrain within original chart bounds
    newMinX = Math.max(newMinX, chart.w.globals.initialMinX);
    newMaxX = Math.min(newMaxX, chart.w.globals.initialMaxX);

    // Apply zoom if valid
    if (!isNaN(newMinX) && !isNaN(newMaxX) && newMinX < newMaxX) {
        chart.zoomX(newMinX, newMaxX);
    }
});
```

(Thanks, ChatGPT!)

**Comment by tony-nz** [comment]
> flotcharts

You went from this to a jquery library?

**Comment by thdwoqor** [comment]
+1

**Comment by mishelen** [comment]
+1, especially appreciated in case of candlesticks => this is only one expected type of interaction
those manual selection  based zooms or via dedicated buttons is really annoying
