### ISSUE TITLE
Bar Charts 'numeric' tickPlacement: 'on' stopped working

### ISSUE THREAD

**Issue by michaeljakob** [apexcharts/apexcharts.js#965]
We want to show the Revenue per Year in the following chart. It's a 'numeric' chart. However, the X-axis doesn't show the exact value of the year, and instead shows "every half" year.

We chose "numeric" as chart-type, because datetime was not suitable either. "datetime" didn't show EVERY year (but only every 5th year or so), which is not what we want. If we select "category", the chart won't be zoomable :/.

<img width="846" alt="Screenshot 2019-10-07 15 34 46" src="https://user-images.githubusercontent.com/3597595/66292932-1017e880-e918-11e9-9335-d1b4f78921dc.png">

<img width="846" alt="Screenshot 2019-10-07 15 39 01" src="https://user-images.githubusercontent.com/3597595/66293152-9a604c80-e918-11e9-8f9c-355c324bd482.png">

`
ApexCharts.exec("vuechart-example", "updateOptions", {
        series: new_series,
        xaxis: {  
          type: 'numeric',
          tickAmount: 'dataPoints',
          tickPlacement: 'on'
          // categories: arr_year
        }
      });

`

**Comment by michaeljakob** [comment]
BUG: Why is `tickPlacement: "on"` not working?

**Comment by michaeljakob** [comment]
Another solution I tried: Switch the entire chart to `type: "datetime"` to quickfix our issue. However, here my main problem is that the xaxis only shows SOME of the 25 years (e.g. 2000, 2010, 2020), whereas I want the year below every bar. If there's a way to force labels for every datapoint at `"datetime"`, this would also be a great solution for me :).

**Comment by alex-lechner** [comment]
Having the same issue... I can't event use datetime anymore due to it's datetime conversion

**Comment by michaeljakob** [comment]
On using `xaxis = datetime`.

That works for us, but creates another big problem:
We want to show the x-axis value for every year (discrete years in our series). The x-axis type "datetime" doesn't allow us to do this, does it? (please see the image below)
Any help here would be hugely appreciated.

There must be a way to display such a simple chart, right? :)

<img width="809" alt="Screenshot 2019-12-31 00 40 47" src="https://user-images.githubusercontent.com/3597595/71591218-7783b400-2b66-11ea-894d-680220d1b94e.png">

**Comment by iq-codechef** [comment]
@junedchhipa  Any fixes for this yet?

**Comment by ludenslabs** [comment]
I'd like to bring this to the attention once more.

Concretely, in my case, without explicitly setting xaxis.type changing xaxis.tickPlacement to anything except 'between' makes it ignore labels in the tooltip (it just counts 1,2,3,4, etc.). Setting xaxis.type does not fix the issue, but I can see the label as displayed in the tooltip being processed differently, which makes me suspect this is a bug.

Happy to provide more info if it helps the bugfix.
