### ISSUE TITLE
unwanted duplicated charts!!

### ISSUE THREAD

**Issue by MohammadGoodarzi** [apexcharts/apexcharts.js#966]
hi
after load page that have apexchart, i found that if i put one  div tag for a chart in page, 5-6 chart  created in loading progress and this bug can slow down my web page. 
ofcourse after resize browser those charts will be hidden
thanks

**Comment by markosko** [comment]
Hello, can you post script ?

**Comment by MohammadGoodarzi** [comment]
function pieCharts(
    p1,p1_text,
    p2,p2_text,
    p3,p3_text,
    p4,p4_text
    ){
    
       
    var Pchart1Option = {
        chart: {
            
            dropShadow: {
            enabled: true,
            enabledOnSeries: undefined,
            top: 0,
            left: 0,
            blur: 3,
            color: '#3333335c',
            opacity: 0.35
        },
            height: 350,
            type: 'radialBar',
        },
        plotOptions: {
            radialBar: {
                offsetY: -10,
                startAngle: 0,
                endAngle: 280,
                hollow: {
                    margin: 0,
                    size: '30%',
                    background: 'transparent',
                    image: undefined,
                },
                
                dataLabels: {
                    name: {
                        show: true,
                        fontSize: '13px', 
                        fontFamily: 'IRANSans',
                    },
                    value: {
                        show: true,
                        formatter: function (val) {
                      return val + ''
                         }
                    }
                }
            }
        },
        colors: ['#1ab7ea', '#0084ff', '#39539E', '#0077B5'],
        series: [p1,p2,p3,p4],
        labels: [p1_text,p2_text,p3_text,p4_text],
        legend: {
            show: true,
            floating: true,
            fontSize: '14px',
            fontFamily: 'IRANSans',
            position: 'left',
            offsetX: -15,
            offsetY:3,
            labels: {
                // useSeriesColors: true,
                useSeriesColors: false,
                
            },
            markers: {
                size: 0
            },
            formatter: function(seriesName, opts) {
                return seriesName + " :  " + opts.w.globals.series[opts.seriesIndex]
            },
            itemMargin: {
                horizontal: 1,
            }
        },
        responsive: [{
            breakpoint: 480,
            options: {
                legend: {
                    show: false
                }
            }
        }]
    }

 

    /*=====================================================*/


    var options = {
        chart: {
            animations: {
                enabled: true,
                easing: 'linear', // linear, easeout, easein, easeinout, swing, bounce, elastic
                speed: 800,
                animateGradually: {
                  delay: 150,
                  enabled: true
                },
                dynamicAnimation: {
                  enabled: true,
                  speed: 350
                }
              },
              
            dropShadow: {
                enabled: true,
                enabledOnSeries: undefined,
                top: 0,
                left: 0,
                blur: 3,
                color: '#3333335c',
                opacity: 0.35
            },
            type: 'radialBar',
            offsetY: -20
        },
        plotOptions: {
            
            radialBar: {
                startAngle: -90,
                endAngle: 90,
                track: {
                    background: "#e7e7e7",
                    strokeWidth: '97%',
                    margin: 5, // margin is in pixels
                    shadow: {
                        enabled: true,
                        top: 2,
                        left: 0,
                        color: '#999',
                        opacity: 1,
                        blur: 2
                    }
                },
                dataLabels: {
                    name: {
                        show: true,
                        fontSize: '13px', 
                        fontFamily: 'IRANSans',
                    },
                    value: {
                        show: true,
                        formatter: function (val) {
                      return val + '  '
                         }
                    }
                }
            }
        },
        fill: {
            type: 'gradient',
            gradient: {
                shade: 'light',
                shadeIntensity: 0.4,
                inverseColors: false,
                opacityFrom: 1,
                opacityTo: 1,
                stops: [0, 50, 53, 91]
            },
        },
        series: [76,10],
        labels: ['نمره سالانه','نمره فصل'],
        legend: {
            show: true,
            floating: true,
            fontSize: '14px',
            fontFamily: 'IRANSans',
            position: 'left',
            offsetX: -15,
            offsetY:3,
            labels: {
                // useSeriesColors: true,
                useSeriesColors: false,
                
            },
            markers: {
                size: 0
            },
            formatter: function(seriesName, opts) {
                return seriesName + " :  " + opts.w.globals.series[opts.seriesIndex]
            },
            itemMargin: {
                horizontal: 1,
            }
        },
       
    }

    var chart = new ApexCharts(
        document.querySelector("#Pchart1"),
        Pchart1Option
    );
    
    chart.render();
   var chart = new ApexCharts(
        document.querySelector("#chart"),
        options
    );  
    chart.render();



}

**Comment by junedchhipa** [comment]
Your code is not sufficient to reproduce the issue.
Please post a working [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example.

**Comment by MohammadGoodarzi** [comment]
> Your code is not sufficient to reproduce the issue.
> Please post a working [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example.

hi, while changing my script for put in codepen, I found my mistake, :) 
thanks.

**Comment by santhoshkumars1234** [comment]
> > Your code is not sufficient to reproduce the issue.
> > Please post a working [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example.
> 
> hi, while changing my script for put in codepen, I found my mistake, :) thanks.

What was your mistake can you ellobrate so others can know
