### ISSUE TITLE
Chart showing negative Y axis

### ISSUE THREAD

**Issue by vkvinaykumar6600** [apexcharts/apexcharts.js#968]
I am using following array in apex charts values. 

But its showing negative Y axis but I don't have any negative values.

`   data = [442, 7901, 1152, 3010, 5905, 79881, 4508, 3323];`
` Months = ["Apr", "Aug", "Jul", "Jun", "Mar", "May", "Oct", "Sep"];`

![image](https://user-images.githubusercontent.com/51202415/66313233-a7d50100-e92f-11e9-8f1d-e5d1734a2d3e.png)

**Comment by rhera** [comment]
This issue is not fix. One example:

https://codepen.io/rhera/pen/ZEYWKmv

Version: 3.10.1

**Comment by junedchhipa** [comment]
Fixed in 3.11.0
