### ISSUE TITLE
Having issues with x axis tooltip when using Candlestick chart

### ISSUE THREAD

**Issue by d-amit** [apexcharts/apexcharts.js#975]
I'm using ng-apexcharts wrapper with apexchart lib.  My config for the chart are as followed...

```
this.series = [{
  name: 12234342,
  data: [{
    x: '2019-10-02T08:00:00Z',
    y: [6.309113, 6.328829, 6.239565, 6.25243]
  }, ...
]
}

this.xaxis = {
      type: 'datetime',
      max: max, // last timestamp from data
      min: min, // first timestamp from data
      tooltip: {
        enabled: true
      }
    };

    this.yaxis = {
      tooltip: {
        enabled: true
      }
    };

this.title = {
      text: `${this.stock.name} [${this.stock.exchange ? this.stock.exchange + ' - ' : ''}  ${this.stock.ticker}]`,
      align: 'left'
    };

this.chart = {
      type: 'candlestick',
      height: 400,
      zoom: {
        type: 'x',
        enabled: true,
        autoScaleYaxis: true
      },
      toolbar: {
        autoSelected: 'zoom'
      }
    };
```

But for some reason, the xaxis tooltip is stuck in place.  Also notice how when I zoom in, the candles do NOT scale accordingly.  Please let me know if Im missing a config or if I have conflicting configs setup.

![stock_chart_issues](https://user-images.githubusercontent.com/14062379/66408212-853cf980-e9bc-11e9-9aae-dd08a11c799f.gif)

**Comment by junedchhipa** [comment]
Can you please post a full working codepen demo to easily reproduce the issue?

**Comment by junedchhipa** [comment]
I have released candlestick chats with category x-axis that supports zooming.
You might take a look at https://apexcharts.com/javascript-chart-demos/candlestick-charts/category-x-axis/ to see if it resolves the issue.

**Comment by junedchhipa** [comment]
Closing as not reproducible.
