### ISSUE TITLE
axis tick value data formatter

### ISSUE THREAD

**Issue by deevolutionism** [apexcharts/apexcharts.js#977]
currently I have a prime number of data points and I would like x-axis to just show me integers rather than floats for each of the ticks. I could set the tick interval to the prime number itself, but the problem is I have a number of data points that is a large prime number so, setting the ticks to a large number would render them illegible as they would be way too scrunched up together. So currently I will always get ticks with floating points.

I would like a data format option similar to what's available to labels where I can modify the tick value if I need to, such as flooring the value in my case or at least limiting the maximum number of decimal places.

**Comment by junedchhipa** [comment]
Sorry for the delayed response.
If you want to format the text of xaxis labels, you can do it like this

```javascript
xaxis: {
  labels: {
    formatter: function(value, timestamp, index) {
      return value.toFixed(0)
    }
  }
}
```

If I misunderstood your question, please feel free to reopen the issue and elaborate.
