### ISSUE TITLE
Stacked column labels are off

### ISSUE THREAD

**Issue by afontcu** [apexcharts/apexcharts.js#979]
Hi! 👋 

The example from docs already serves as a demo, I believe: 

https://apexcharts.com/javascript-chart-demos/column-charts/stacked/

Took a screenshot, just in case:

![imatge](https://user-images.githubusercontent.com/9197791/66632603-23bd9a80-ec09-11e9-8517-7fc106427360.png)

As you can see, both values and the column overlay are a bit off.

**Comment by afontcu** [comment]
Hm okay, I think it is related to `xaxis` being a `datetime` 🤔

**Comment by junedchhipa** [comment]
Yes, that’s a bug. 
A fix will be released soon, thanks for reporting.

**Comment by freekbass** [comment]
I have the same problem when I use column charts with more than one series:

[http://prntscr.com/pi4e6t](url)

**Comment by freekbass** [comment]
Hi, i think this cause this problem to:

http://prntscr.com/pj5yl1

The first serie of chart is renderized out of scope.
