### ISSUE TITLE
Trouble with rotated categories labels

### ISSUE THREAD

**Issue by FDArchy** [apexcharts/apexcharts.js#980]
## Codepen
https://codepen.io/fd_archy/pen/YzzyMQp

## Explanation

Hello. When plotting a chart with rotated categories, a large margins appears under the chart. What to do with it?

![123](https://user-images.githubusercontent.com/6572223/66665647-9fdecf00-ec57-11e9-9846-8621d686feff.PNG)

**Comment by junedchhipa** [comment]
Thanks for reporting, that's a bug.
I have just fixed it by removing the unnecessary padding I gave while trimming labels.

**Comment by FDArchy** [comment]
Exuse me, when will the release be with fixes? Now i'm tested 3.10.0 version, trouble is still present.

**Comment by junedchhipa** [comment]
The new patch version will be released in the next 1-2 weeks.

**Comment by FDArchy** [comment]
Here's work example
https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/
