### ISSUE TITLE
Please add vertical panning

### ISSUE THREAD

**Issue by maasha** [apexcharts/apexcharts.js#981]
**Is your feature request related to a problem? Please describe.**
While horizontal panning and zoom works nicely, in scientific charts, which can contain a lot of data series, it would be very useful to inspect areas of interest using vertical panning.

**Describe the solution you'd like**
Just like horizontal panning - but vertical.

**Describe alternatives you've considered**
chart.js?

**Additional context**
None really

**Comment by abdullRahman95** [comment]
@junedchhipa Any updates about this feature request ?
I believe it will be nice to add it
