### ISSUE TITLE
Ticks do not match labels in a column chart with numeric x-axis

### ISSUE THREAD

**Issue by mnagl** [apexcharts/apexcharts.js#982]
## Codepen

https://codepen.io/mnagl/pen/ZEEQyor

## Explanation

- What is the behavior you expect?
The ticks should match the label positions. These are at the intended positions

- What is happening instead?
There is one tick too much

- What error message are you getting?
none

**Comment by mnagl** [comment]
For me it works after changing line 234 in Grid.js to

`if (w.globals.isXNumeric)`

i.e. removing the second condition. I'm not sure if this change is a proper fix which won't intrduce new problems in other usage scenarios.

**Comment by junedchhipa** [comment]
You are right.
Removing the second condition fixes the issue.
Checked the other areas and it's not causing any problems, thanks for the hint.

**Comment by junedchhipa** [comment]
The new version will be released in a week or two.
