### ISSUE TITLE
All existing charts now have data in reverse order (since last version)

### ISSUE THREAD

**Issue by azivkovi** [apexcharts/apexcharts.js#983]
Does anyone else have this issue as well?

Only thing I can think of is it came with the latest Apexcharts update.

**Comment by junedchhipa** [comment]
Which version? 3.9.0?
Can you please share an example?

**Comment by azivkovi** [comment]
This chart, for example: https://investiramo.com/chart

this is the data feed : https://investiramo.com/includes/chart/quote-price.inc.php

Date is correct, but data is reversed somehow.

**Comment by junedchhipa** [comment]
Both the links you provided are not accessible on my side.
Can you create a working codepen example?

**Comment by azivkovi** [comment]
I am sorry about that., should have made a codepen right away.

Here's the codepen: https://codepen.io/azivkovi/pen/poogZOW

**Comment by junedchhipa** [comment]
That's a major bug. Thanks for reporting it quickly.
I will release a new patch very soon.

**Comment by azivkovi** [comment]
Happy to help. Thank you for fixing it so swiftly!

**Comment by azivkovi** [comment]
Juned, just for your information - I sent a purge request @ https://purge.jsdelivr.net/npm/apexcharts
so it updated Apexcharts to the newest version. It was taking a long time.

I am usually very patient with the updates, but this was a bit more time urgent.

Thanks again for the quick fix.

**Comment by junedchhipa** [comment]
Yeah, sometimes cdn of jsdelivr takes 24 hours to serve new files. Thanks for sending a purge request to clear cache.

**Comment by azivkovi** [comment]
Yeah, its the only reason I didn't notice it earlier. It had me puzzled because you had the 3.9.0 released yesterday and everything was working good on my end. Then all the sudden today my charts were going the wrong way. :)
