### ISSUE TITLE
[Column Charts] Colors Range for Positive Values

### ISSUE THREAD

**Issue by AdrianoFSilva1** [apexcharts/apexcharts.js#984]
After seeing [Column with Negative Values](https://apexcharts.com/javascript-chart-demos/column-charts/column-with-negative-values/) I tried to do the same but for positive values, instead of being from -100 to -46 being from 50 to 25 but didn't work.

I would like set the colors for those positive values instead negative.

If already have any post for this issue please refer me to it. 

Thank you for your attention.

**Comment by junedchhipa** [comment]
You have to do it `from: 0` and `to: 50`
Full code
```javascript
plotOptions: {
  bar: {
    colors: {
      ranges: [
        {
          from: 0,
          to: 46,
          color: '#F15B46'
        },
        {
          from: 47,
          to: 100,
          color: '#FEB019'
        }
      ]
    },
    columnWidth: '80%'
  }
}
```

I got the following result in all positive values
![Screen Shot 2019-12-30 at 11 08 41 PM](https://user-images.githubusercontent.com/17950663/71593289-7730ec00-2b59-11ea-9683-783b34825764.png)
