### ISSUE TITLE
Mixed Chart - Marker with size 0 and hover 3 doesnt work properly

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#986]
## Codepen

I'm using vue, but the problem occurs on this one as well:
https://codepen.io/leinad4mind/pen/qBBZdEN

## Explanation

- What is the behavior you expect?
I am expecting to see the marker on both area graphs, it only appear on 1 of them when hover.

- What is happening instead?
With marker with size: 0 and hover: 6 it only appear the hover on one of the area graphs, but I discover that if I put size 3 (any number above 0) it appears on boths and the hover works too.
So a solution for me was to put size: 0.1.

- What error message are you getting?
No errors.

best regards

**Comment by junedchhipa** [comment]
This is fixed in the latest version 3.15.2.
Closing it.
