### ISSUE TITLE
Multiple Axis Series Problem

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#987]
## Codepen

I am using vuejs but the problem happens on this one too:
https://codepen.io/leinad4mind/pen/oNNxXbB

## Explanation

- What is the behavior you expect?
I was expecting to only use 2 y axis, even having 3 series, but it obliged me to use:
`,
            {
                show: false,
            }`

to make it work.

- What is happening instead?
The graph doesnt show at all if I don't use the same number of series I've in the yaxis

- What error message are you getting?
Just look at my codepen and search for:
"Need to use code below to make it work"

And uncomment that code to see the graph working and when removing that code it stops working and it shouldnt imo.

**Comment by junedchhipa** [comment]
It's not a bug, it's a requirement for a multi-axis chart (mentioned in [docs](https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/)).
