### ISSUE TITLE
 A negative value is not valid

### ISSUE THREAD

**Issue by ngovando** [apexcharts/apexcharts.js#988]
Hi!.
I have some problem with pie chart. 
My pie chart  return : <svg> attribute height: A negative value is not valid. ("-35.65853658536585") when i zoom out the screen. With display is 1920 x  , pie chart work well but when i zoom outdisplay , pie chart is unvisible. 

My code : 
 const options = {
    labels,
    series,
    colors,
    tooltip: {
      custom({ series, seriesIndex }) {
        return `<div style='background-color : ${
          colors[seriesIndex]
        }' class="tooltips-pie-chart"><span >${
          labels[seriesIndex].split(':')[0]
        }  :</span> <strong >${series[seriesIndex]}h</strong> </div>
       `;
      },
      theme: 'none',
    },
    legend: {
      formatter(seriesName) {
        return `<strong> ${seriesName.split(':')[0]}</strong> : ${
          seriesName.split(':')[1]
        } `;
      },
      tooltipHoverFormatter(seriesName, opts) {
        return `${seriesName} - <strong>${
          opts.w.globals.series[opts.seriesIndex][opts.dataPointIndex]
        }</strong>`;
      },
    },
  };
  return (
    <div className="project-pie-chart">
        <ReactApexChart options={options} series={options.series} type="pie" />
    </div>
  );
 and clas 'project-pie-chart' : 
     .project-pie-chart {
       max-width: 1200px;
       height: 460px;
       padding: 0;
       margin-left: 400px;
     }

**Comment by junedchhipa** [comment]
If there is not enough space to draw the chart, it results in this error.
Can you please provide a working codepen example as the code you provided is incomplete.
