### ISSUE TITLE
Date values incorrectly showing as times of the same day

### ISSUE THREAD

**Issue by Greig-DF** [apexcharts/apexcharts.js#989]
## Explanation

Given the (shortened) series of 
[1451919600,6] (4/3/2016-3:00pm)
[1466930040,1] (26/6/2016-8:34am)
provided to the scatter:date-time chart, we are seeing the value being reported as the same day (18 Jan), but for different times. Y-axis quantity is displayed correctly.

## Codepen
https://codepen.io/Greig-DF/pen/KKKzQzJ

- What is the behaviour you expect?
The data points should show over multiple days

- What is happening instead?
Data points show as different points on the same day. (See snapshot)

- What error message are you getting?
No error given

Please let me know if I've done something stupid, or if this is a known issue.

Thanks,

![image](https://user-images.githubusercontent.com/56574710/66801122-7504bb80-ef74-11e9-909c-f1cddd3c147e.png)

**Comment by junedchhipa** [comment]
You need to input JavaScript timestamps, not Unix timestamps.

Here is the correct data (Unix-timestamp * 1000).

```javascript
data: [
    [1451919600000, 6],
    [1466930040000, 1]
]
```

Also, due to a bug, the first marker is not showing. I have fixed the issue and the patch will be released after some time.
