### ISSUE TITLE
Yaxis repetition of labels

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#99]
Yaxis labels repeat themselves to fill space, why?

![sketch](https://user-images.githubusercontent.com/6877046/45501327-8257e100-b789-11e8-8e9f-155fe5c6c63e.png)

**Comment by junedchhipa** [comment]
Look for `options.yaxis.tickAmount` option.
You will be able to control the number of ticks generated on y-axis.
 Try `tickAmount: 2`

If you have smaller values and want more ticks - you can format the `yaxis.labels.formatter` to something like below
```javascript
function(val) {
  return val.toFixed(1)
}
```

The ticks generated will be 0, 0.5, 1.0, 1.5, 2, 2.5 and so on.

**Comment by jimfilippou** [comment]
Thanks!
