### ISSUE TITLE
Multiple series for 1 scale of an axis

### ISSUE THREAD

**Issue by FranKiie-XIV** [apexcharts/apexcharts.js#990]
Hi,

I have been using your library and i've come across this problem.

I'm trying to add 2 series to the same scale in the same axis. This is what I found in your page:
yaxis: [
  {
    seriesName: 'TEAM A'
  },
  {
    seriesName: 'TEAM B'
  },
  {
    seriesName: 'TEAM B'
  }
],

but what I really need is:
yaxis: [
  {
    seriesName: ['TEAM A', 'TEAM B']
  },
  {
    seriesName: 'TEAM C'
  },
],

Why?
Because your solution creates another scale for the axis and different scales have different ranges. They don't share the same spot of the graphic for the same value. What I really need is to be able to put 2 series or multiple series into 1 scale so that the data can be comprehensive in the same scale.

If there's an actual way of making both scales share a range, maybe that could be a patch for me, but not a final solution.

Thank you for your time!

**Comment by junedchhipa** [comment]
The number of yaxis has to be equal to the number of series. Then, when you need to share a scale between 2 or more series, you can hide them easily.

```
yaxis: [
  {
    seriesName: 'TEAM A'
  },
  {
    seriesName: 'TEAM B'
  },
  {
    seriesName: 'TEAM B',
    show: false
  }
]
```

This way, the last 2 series will have a shared scale.

Docs: https://apexcharts.com/docs/chart-types/multiple-yaxis-scales#3-series-2-scales
