### ISSUE TITLE
Multiple Yaxis causes zoom AutoScaleYaxis to not work

### ISSUE THREAD

**Issue by FranKiie-XIV** [apexcharts/apexcharts.js#991]
## Explanation
This is what i have in my options:
chart: {
         zoom: { enabled: config.zoomable, type: 'x', autoScaleYaxis: true },
    },
autoscaleYaxis seems to work only in the case of a single YAxis, but having multiple YAxis makes this functionality to not work.

- What is the behavior you expect?
When selecting a zone in the chart YAxis would automatically decrease based on the min and max value displayed by the chart.
- What is happening instead?
It doesn't move at all.
- What error message are you getting?
Not getting an error message.

**Comment by junedchhipa** [comment]
Sorry, this is a known issue that I forgot to mention in docs.
Just added it - https://apexcharts.com/docs/options/chart/zoom#autoScaleYaxis

**Comment by FranKiie-XIV** [comment]
Hi again,
Are you planning on fixing this issue any time soon?
Thanks!

**Comment by TimothyLuke** [comment]
Turning this off i still get a billion "autoScaleYaxis is not supported in a multi-yaxis chart." in the console.log
