### ISSUE TITLE
The labels are breaking in bar chart when downloaded as PNG or SVG

### ISSUE THREAD

**Issue by Vaseem88** [apexcharts/apexcharts.js#992]
@junedchhipa 
Navigate to https://apexcharts.com/react-chart-demos/bar-charts/stacked/
Click on the Hamburger icon and click download as SVG
see that the labels are missing their alignment
![image](https://user-images.githubusercontent.com/23305215/66836868-bfd80080-ef7f-11e9-9fca-131088848869.png)

**Comment by junedchhipa** [comment]
Thanks for reporting. 
A change in the last version 3.10.0 caused it.
Will be fixed soon.
