### ISSUE TITLE
Candlestick Tooltip Customize

### ISSUE THREAD

**Issue by ninjamonz** [apexcharts/apexcharts.js#995]
## Codepen

https://codepen.io/esdegan/pen/mddEqJj

## Explanation

- What is the behavior you expect?
  customizing **candlestick** **tooltip**,
  for example adding suffix like **Open: 123 U$D**
- What is happening instead?
```
tooltip: {
      x: {
          show: true,
          format: 'dd MMM',
          formatter: undefined,
      },
      y: {
          formatter: undefined,
          title: {
              formatter: (seriesName) => seriesName,
          },
      },
      z: {
          formatter: undefined,
          title: 'Size: '
      }
}
```
tooltip property able for customizing chart with type 'line', 'area', and maybe others but for 'candlestick' seems not working.

I don't know what happen, any clue or help?
Thanks Q(^_^)Q

**Comment by junedchhipa** [comment]
The candlestick tooltip is customizable with the `tooltip.custom` property.
Here is the example


```javascript
tooltip: {
  custom: function({ seriesIndex, dataPointIndex, w }) {
    const o = w.globals.seriesCandleO[seriesIndex][dataPointIndex]
    const h = w.globals.seriesCandleH[seriesIndex][dataPointIndex]
    const l = w.globals.seriesCandleL[seriesIndex][dataPointIndex]
    const c = w.globals.seriesCandleC[seriesIndex][dataPointIndex]
    return (
      '<div class="apexcharts-tooltip-candlestick">' +
      '<div>Open: <span class="value">' +
      o +
      '</span></div>' +
      '<div>High: <span class="value">' +
      h +
      '</span></div>' +
      '<div>Low: <span class="value">' +
      l +
      '</span></div>' +
      '<div>Close: <span class="value">' +
      c +
      '</span></div>' +
      '</div>'
    )
  }
}
```

**Comment by tolgaatrgt** [comment]
Hey junedchhipa i tried this in latest version but couldnt manage it.
`  tooltip: {
    y: {
      formatter: function (value, { seriesIndex, dataPointIndex, w
      }) {
        const o = w.globals.seriesCandleO[seriesIndex][dataPointIndex]
        const h = w.globals.seriesCandleH[seriesIndex][dataPointIndex]
        const l = w.globals.seriesCandleL[seriesIndex][dataPointIndex]
        const c = w.globals.seriesCandleC[seriesIndex][dataPointIndex]
        return (
          '<div>' +
          '<div>asdsad: <span class="value">' +
          o +
          '</span></div>' +
          '<div>asdsad: <span class="value">' +
          h +
          '</span></div>' +
          '<div>asdasd: <span class="value">' +
          l +
          '</span></div>' +
          '<div>asdsad: <span class="value">' +
          c +
          '</span></div>' +
          '</div>'
        )
      }
    }

  }`

**Comment by tolgaatrgt** [comment]
Hey Juned, i couldnt manage it what is the up to date solution ? Thank you..

**Comment by junedchhipa** [comment]
@tolgaatrgt What have you tried?

**Comment by tolgaatrgt** [comment]
i need to convert price string so i tried this;

`  tooltip: {
    y: {
      formatter: function (value, { seriesIndex, dataPointIndex, w
      }) {
        const o = w.globals.seriesCandleO[seriesIndex][dataPointIndex]
        const h = w.globals.seriesCandleH[seriesIndex][dataPointIndex]
        const l = w.globals.seriesCandleL[seriesIndex][dataPointIndex]
        const c = w.globals.seriesCandleC[seriesIndex][dataPointIndex]

        return (
          parseFloat(o).toLocaleString('en') + "$" +
          parseFloat(h).toLocaleString('en') + " $" +
          parseFloat(l).toLocaleString('en') + " $" +
          parseFloat(c).toLocaleString('en') + " $"
        )
      }
    }

  }`

**Comment by tolgaatrgt** [comment]
i can log the values but cant render it.

**Comment by tolgaatrgt** [comment]
Sorry, my fault thanks !

**Comment by Pablo-Yadav** [comment]
thanks for sharing, it helped
