### ISSUE TITLE
[Question] Forest plot chart

### ISSUE THREAD

**Issue by Codermar** [apexcharts/apexcharts.js#996]
**Is your feature request related to a problem? Please describe.**

I am looking to create a forest plot chart similar to what you can see here https://cran.r-project.org/web/packages/forestplot/vignettes/forestplot.html or this one https://codepen.io/team/amcharts/pen/58db558447b347ab4ed8d1cab28b2160

Is it possible to build in Apexcharts?

**Describe the solution you'd like**
A Native way to build forest plot charts in Apexchart

**Describe alternatives you've considered**
A way to build the chart with the existing codebase

**Comment by junedchhipa** [comment]
Sorry, currently it is not possible to plot such a chart.
It will be difficult to extend it using the current codebase.
