### ISSUE TITLE
Pie chart overflows width when legend not positioned at left/right

### ISSUE THREAD

**Issue by kevinresol** [apexcharts/apexcharts.js#997]
## Codepen

![Screen Shot 2019-10-17 at 9 23 28 AM](https://user-images.githubusercontent.com/1103788/66970350-d1c0bd00-f0bf-11e9-9acc-0e7f8265b6d3.png)

https://codepen.io/kevinresol/pen/WNNxmgv

## Explanation

- What is the behavior you expect?
Pie fits inside the container

- What is happening instead?
Pie overflows the container width

- What error message are you getting?
None

**Comment by junedchhipa** [comment]
The `width` setting overrides `height` setting to scale the pie inside. Also, you cannot set `width: 100%` and `height: 100%` at the same time.

The recommended way is to set the `width: 100%` and a fixed `height: 200px`.

**Comment by kevinresol** [comment]
In the codepen, setting height to 400px gives the same overflow result, is that expected too?
